from dataclasses import dataclass, field
from datetime import datetime
from marshmallow import fields
import dateutil.parser
from typing import Optional
from dataclasses_json import dataclass_json
from . import committeehistory
from . import committeehistory


@dataclass_json
@dataclass
class ScheduleB:
    amendment_indicator: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'amendment_indicator' }})
    amendment_indicator_desc: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'amendment_indicator_desc' }})
    back_reference_schedule_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'back_reference_schedule_id' }})
    back_reference_transaction_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'back_reference_transaction_id' }})
    beneficiary_committee_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'beneficiary_committee_name' }})
    candidate_first_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_first_name' }})
    candidate_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_id' }})
    candidate_last_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_last_name' }})
    candidate_middle_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_middle_name' }})
    candidate_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_name' }})
    candidate_office: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_office' }})
    candidate_office_description: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_office_description' }})
    candidate_office_district: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_office_district' }})
    candidate_office_state: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_office_state' }})
    candidate_office_state_full: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_office_state_full' }})
    candidate_prefix: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_prefix' }})
    candidate_suffix: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_suffix' }})
    category_code: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'category_code' }})
    category_code_full: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'category_code_full' }})
    comm_dt: Optional[datetime] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'comm_dt', 'encoder': datetime.isoformat, 'decoder': dateutil.parser.isoparse, 'mm_field': fields.DateTime(format='iso') }})
    committee: Optional[committeehistory.CommitteeHistory] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'committee' }})
    committee_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'committee_id' }})
    conduit_committee_city: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'conduit_committee_city' }})
    conduit_committee_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'conduit_committee_name' }})
    conduit_committee_state: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'conduit_committee_state' }})
    conduit_committee_street1: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'conduit_committee_street1' }})
    conduit_committee_street2: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'conduit_committee_street2' }})
    conduit_committee_zip: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'conduit_committee_zip' }})
    disbursement_amount: Optional[float] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'disbursement_amount' }})
    disbursement_date: Optional[datetime] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'disbursement_date', 'encoder': datetime.isoformat, 'decoder': dateutil.parser.isoparse, 'mm_field': fields.DateTime(format='iso') }})
    disbursement_description: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'disbursement_description' }})
    disbursement_purpose_category: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'disbursement_purpose_category' }})
    disbursement_type: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'disbursement_type' }})
    disbursement_type_description: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'disbursement_type_description' }})
    election_type: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'election_type' }})
    election_type_full: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'election_type_full' }})
    entity_type: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'entity_type' }})
    entity_type_desc: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'entity_type_desc' }})
    fec_election_type_desc: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'fec_election_type_desc' }})
    fec_election_year: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'fec_election_year' }})
    file_number: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'file_number' }})
    filing_form: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'filing_form' }})
    image_number: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'image_number' }})
    line_number: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'line_number' }})
    line_number_label: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'line_number_label' }})
    link_id: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'link_id' }})
    load_date: Optional[datetime] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'load_date', 'encoder': datetime.isoformat, 'decoder': dateutil.parser.isoparse, 'mm_field': fields.DateTime(format='iso') }})
    memo_code: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'memo_code' }})
    memo_code_full: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'memo_code_full' }})
    memo_text: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'memo_text' }})
    memoed_subtotal: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'memoed_subtotal' }})
    national_committee_nonfederal_account: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'national_committee_nonfederal_account' }})
    original_sub_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'original_sub_id' }})
    payee_employer: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'payee_employer' }})
    payee_first_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'payee_first_name' }})
    payee_last_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'payee_last_name' }})
    payee_middle_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'payee_middle_name' }})
    payee_occupation: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'payee_occupation' }})
    payee_prefix: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'payee_prefix' }})
    payee_suffix: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'payee_suffix' }})
    pdf_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'pdf_url' }})
    recipient_city: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'recipient_city' }})
    recipient_committee: Optional[committeehistory.CommitteeHistory] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'recipient_committee' }})
    recipient_committee_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'recipient_committee_id' }})
    recipient_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'recipient_name' }})
    recipient_state: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'recipient_state' }})
    recipient_zip: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'recipient_zip' }})
    ref_disp_excess_flg: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'ref_disp_excess_flg' }})
    report_type: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'report_type' }})
    report_year: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'report_year' }})
    schedule_type: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'schedule_type' }})
    schedule_type_full: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'schedule_type_full' }})
    semi_annual_bundled_refund: Optional[float] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'semi_annual_bundled_refund' }})
    spender_committee_designation: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'spender_committee_designation' }})
    spender_committee_org_type: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'spender_committee_org_type' }})
    spender_committee_type: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'spender_committee_type' }})
    sub_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'sub_id' }})
    transaction_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'transaction_id' }})
    two_year_transaction_period: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'two_year_transaction_period' }})
    unused_recipient_committee_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'unused_recipient_committee_id' }})
    
