from dataclasses import dataclass, field
from datetime import datetime
from marshmallow import fields
import dateutil.parser
from typing import Optional
from dataclasses_json import dataclass_json
from . import committeehistory
from . import committeehistory


@dataclass_json
@dataclass
class ScheduleA:
    amendment_indicator: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'amendment_indicator' }})
    amendment_indicator_desc: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'amendment_indicator_desc' }})
    back_reference_schedule_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'back_reference_schedule_name' }})
    back_reference_transaction_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'back_reference_transaction_id' }})
    candidate_first_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_first_name' }})
    candidate_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_id' }})
    candidate_last_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_last_name' }})
    candidate_middle_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_middle_name' }})
    candidate_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_name' }})
    candidate_office: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_office' }})
    candidate_office_district: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_office_district' }})
    candidate_office_full: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_office_full' }})
    candidate_office_state: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_office_state' }})
    candidate_office_state_full: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_office_state_full' }})
    candidate_prefix: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_prefix' }})
    candidate_suffix: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'candidate_suffix' }})
    committee: Optional[committeehistory.CommitteeHistory] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'committee' }})
    committee_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'committee_id' }})
    committee_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'committee_name' }})
    conduit_committee_city: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'conduit_committee_city' }})
    conduit_committee_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'conduit_committee_id' }})
    conduit_committee_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'conduit_committee_name' }})
    conduit_committee_state: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'conduit_committee_state' }})
    conduit_committee_street1: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'conduit_committee_street1' }})
    conduit_committee_street2: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'conduit_committee_street2' }})
    conduit_committee_zip: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'conduit_committee_zip' }})
    contribution_receipt_amount: Optional[float] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contribution_receipt_amount' }})
    contribution_receipt_date: Optional[datetime] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contribution_receipt_date', 'encoder': datetime.isoformat, 'decoder': dateutil.parser.isoparse, 'mm_field': fields.DateTime(format='iso') }})
    contributor: Optional[committeehistory.CommitteeHistory] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contributor' }})
    contributor_aggregate_ytd: Optional[float] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contributor_aggregate_ytd' }})
    contributor_city: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contributor_city' }})
    contributor_employer: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contributor_employer' }})
    contributor_first_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contributor_first_name' }})
    contributor_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contributor_id' }})
    contributor_last_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contributor_last_name' }})
    contributor_middle_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contributor_middle_name' }})
    contributor_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contributor_name' }})
    contributor_occupation: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contributor_occupation' }})
    contributor_prefix: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contributor_prefix' }})
    contributor_state: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contributor_state' }})
    contributor_street_1: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contributor_street_1' }})
    contributor_street_2: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contributor_street_2' }})
    contributor_suffix: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contributor_suffix' }})
    contributor_zip: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contributor_zip' }})
    donor_committee_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'donor_committee_name' }})
    election_type: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'election_type' }})
    election_type_full: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'election_type_full' }})
    entity_type: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'entity_type' }})
    entity_type_desc: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'entity_type_desc' }})
    fec_election_type_desc: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'fec_election_type_desc' }})
    fec_election_year: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'fec_election_year' }})
    file_number: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'file_number' }})
    filing_form: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'filing_form' }})
    image_number: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'image_number' }})
    increased_limit: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'increased_limit' }})
    is_individual: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'is_individual' }})
    line_number: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'line_number' }})
    line_number_label: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'line_number_label' }})
    link_id: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'link_id' }})
    load_date: Optional[datetime] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'load_date', 'encoder': datetime.isoformat, 'decoder': dateutil.parser.isoparse, 'mm_field': fields.DateTime(format='iso') }})
    memo_code: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'memo_code' }})
    memo_code_full: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'memo_code_full' }})
    memo_text: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'memo_text' }})
    memoed_subtotal: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'memoed_subtotal' }})
    national_committee_nonfederal_account: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'national_committee_nonfederal_account' }})
    original_sub_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'original_sub_id' }})
    pdf_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'pdf_url' }})
    receipt_type: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'receipt_type' }})
    receipt_type_desc: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'receipt_type_desc' }})
    receipt_type_full: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'receipt_type_full' }})
    recipient_committee_designation: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'recipient_committee_designation' }})
    recipient_committee_org_type: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'recipient_committee_org_type' }})
    recipient_committee_type: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'recipient_committee_type' }})
    report_type: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'report_type' }})
    report_year: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'report_year' }})
    schedule_type: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'schedule_type' }})
    schedule_type_full: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'schedule_type_full' }})
    sub_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'sub_id' }})
    transaction_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'transaction_id' }})
    two_year_transaction_period: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'two_year_transaction_period' }})
    unused_contbr_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'unused_contbr_id' }})
    
