# coding: utf-8

# flake8: noqa
"""
    Compute Admin Client

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2015-12-01-preview
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.azure_blob import AzureBlob
from openapi_client.models.vm_extension import VMExtension
from openapi_client.models.vm_extension_parameters import VMExtensionParameters
from openapi_client.models.vm_extension_properties import VMExtensionProperties
