from .adultcontentdetection import *
from .commercialdetection import *
from .documentsimilarity import *
from .educationaldetection import *
from .genderdetection import *
from .keywordextraction import *
from .languagedetection import *
from .readabilityassessment import *
from .sentimentanalysis import *
from .spamdetection import *
from .subjectivityanalysis import *
from .textextraction import *
from .topicclassification import *
from .twittersentimentanalysis import *
