from dataclasses import dataclass, field
from datetime import date, datetime
from marshmallow import fields
import dateutil.parser
from enum import Enum

class ImageDetailFieldValuesEnum(str, Enum):
    ALLOWED_USE = "allowed_use"
    ALTERNATIVE_IDS = "alternative_ids"
    ARTIST = "artist"
    ARTIST_TITLE = "artist_title"
    ASSET_FAMILY = "asset_family"
    CALL_FOR_IMAGE = "call_for_image"
    CAPTION = "caption"
    CITY = "city"
    COLLECTION_CODE = "collection_code"
    COLLECTION_ID = "collection_id"
    COLLECTION_NAME = "collection_name"
    COLOR_TYPE = "color_type"
    COMP = "comp"
    COPYRIGHT = "copyright"
    COUNTRY = "country"
    CREDIT_LINE = "credit_line"
    DATE_CAMERA_SHOT = "date_camera_shot"
    DATE_CREATED = "date_created"
    DATE_SUBMITTED = "date_submitted"
    DETAIL_SET = "detail_set"
    DISPLAY_SET = "display_set"
    DOWNLOAD_SIZES = "download_sizes"
    DOWNLOAD_PRODUCT = "download_product"
    DOWNLOADS = "downloads"
    EDITORIAL_SEGMENTS = "editorial_segments"
    EDITORIAL_SOURCE = "editorial_source"
    ENTITY_DETAILS = "entity_details"
    EVENT_IDS = "event_ids"
    GRAPHICAL_STYLE = "graphical_style"
    ID = "id"
    ISTOCK_COLLECTION = "istock_collection"
    ISTOCK_LICENSES = "istock_licenses"
    KEYWORDS = "keywords"
    LARGEST_DOWNLOADS = "largest_downloads"
    LICENSE_MODEL = "license_model"
    LINKS = "links"
    MAX_DIMENSIONS = "max_dimensions"
    OBJECT_NAME = "object_name"
    ORIENTATION = "orientation"
    PEOPLE = "people"
    PREVIEW = "preview"
    PRODUCT_TYPES = "product_types"
    QUALITY_RANK = "quality_rank"
    REFERRAL_DESTINATIONS = "referral_destinations"
    STATE_PROVINCE = "state_province"
    SUMMARY_SET = "summary_set"
    THUMB = "thumb"
    TITLE = "title"
    URI_OEMBED = "uri_oembed"

