from dataclasses import dataclass, field
from datetime import date, datetime
from marshmallow import fields
import dateutil.parser
from enum import Enum

class VideoDetailFieldValuesEnum(str, Enum):
    ID = "id"
    ALLOWED_USE = "allowed_use"
    ARTIST = "artist"
    ASSET_FAMILY = "asset_family"
    CALL_FOR_IMAGE = "call_for_image"
    CAPTION = "caption"
    CLIP_LENGTH = "clip_length"
    COLLECTION_CODE = "collection_code"
    COLLECTION_ID = "collection_id"
    COLLECTION_NAME = "collection_name"
    COLOR_TYPE = "color_type"
    COMP = "comp"
    COPYRIGHT = "copyright"
    DATE_CREATED = "date_created"
    DATE_SUBMITTED = "date_submitted"
    DETAIL_SET = "detail_set"
    DISPLAY_SET = "display_set"
    DOWNLOAD_SIZES = "download_sizes"
    DOWNLOAD_PRODUCT = "download_product"
    DOWNLOADS = "downloads"
    EDITORIAL_SEGMENTS = "editorial_segments"
    ENTITY_DETAILS = "entity_details"
    ERA = "era"
    EVENT_IDS = "event_ids"
    ISTOCK_COLLECTION = "istock_collection"
    ISTOCK_LICENSES = "istock_licenses"
    KEYWORDS = "keywords"
    LICENSE_MODEL = "license_model"
    MASTERED_TO = "mastered_to"
    OBJECT_NAME = "object_name"
    ORIENTATION = "orientation"
    ORIGINALLY_SHOT_ON = "originally_shot_on"
    PREVIEW = "preview"
    PRODUCT_TYPES = "product_types"
    QUALITY_RANK = "quality_rank"
    REFERRAL_DESTINATIONS = "referral_destinations"
    SHOT_SPEED = "shot_speed"
    SOURCE = "source"
    SUMMARY_SET = "summary_set"
    THUMB = "thumb"
    TITLE = "title"

