# coding: utf-8

"""
    SiteRecoveryManagementClient

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2018-01-10
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.in_mage_azure_v2_failover_provider_input import InMageAzureV2FailoverProviderInput

class TestInMageAzureV2FailoverProviderInput(unittest.TestCase):
    """InMageAzureV2FailoverProviderInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InMageAzureV2FailoverProviderInput:
        """Test InMageAzureV2FailoverProviderInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InMageAzureV2FailoverProviderInput`
        """
        model = InMageAzureV2FailoverProviderInput()
        if include_optional:
            return InMageAzureV2FailoverProviderInput(
                recovery_point_id = '',
                vault_location = ''
            )
        else:
            return InMageAzureV2FailoverProviderInput(
        )
        """

    def testInMageAzureV2FailoverProviderInput(self):
        """Test InMageAzureV2FailoverProviderInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
