# coding: utf-8

"""
    VirtualWANAsAServiceManagementClient

    REST API for Azure VirtualWAN As a Service.

    The version of the OpenAPI document: 2018-06-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.vpn_site_properties_address_space import VpnSitePropertiesAddressSpace

class TestVpnSitePropertiesAddressSpace(unittest.TestCase):
    """VpnSitePropertiesAddressSpace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VpnSitePropertiesAddressSpace:
        """Test VpnSitePropertiesAddressSpace
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VpnSitePropertiesAddressSpace`
        """
        model = VpnSitePropertiesAddressSpace()
        if include_optional:
            return VpnSitePropertiesAddressSpace(
                address_prefixes = [
                    ''
                    ]
            )
        else:
            return VpnSitePropertiesAddressSpace(
        )
        """

    def testVpnSitePropertiesAddressSpace(self):
        """Test VpnSitePropertiesAddressSpace"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
