{
  "swagger": "2.0",
  "info": {
    "title": "Fitness",
    "x-serviceName": "fitness",
    "description": "Google Fit API",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v1",
    "x-origin": {
      "format": "google",
      "version": "v1",
      "url": "https://www.googleapis.com/discovery/v1/apis/fitness/v1/rest"
    }
  },
  "host": "www.googleapis.com",
  "basePath": "/fitness/v1/users",
  "schemes": [
    "https"
  ],
  "paths": {
    "/{userId}/dataSources": {
      "post": {
        "description": "Creates a new data source that is unique across all data sources belonging to this user. The data stream ID field can be omitted and will be generated by the server with the correct format. The data stream ID is an ordered combination of some fields from the data source. In addition to the data source fields reflected into the data source ID, the developer project number that is authenticated when creating the data source is included. This developer project number is obfu[...]",
        "operationId": "fitness.users.dataSources.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/fitness.activity.write",
              "https://www.googleapis.com/auth/fitness.body.write",
              "https://www.googleapis.com/auth/fitness.location.write"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      },
      "get": {
        "description": "Lists all data sources that are visible to the developer, using the OAuth scopes provided. The list is not exhaustive: the user may have private data sources that are only visible to other developers or calls using other scopes.",
        "operationId": "fitness.users.dataSources.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/fitness.activity.read",
              "https://www.googleapis.com/auth/fitness.activity.write",
              "https://www.googleapis.com/auth/fitness.body.read",
              "https://www.googleapis.com/auth/fitness.body.write",
              "https://www.googleapis.com/auth/fitness.location.read",
              "https://www.googleapis.com/auth/fitness.location.write"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/dataSources/{dataSourceId}": {
      "delete": {
        "description": "Delete the data source if there are no datapoints associated with it",
        "operationId": "fitness.users.dataSources.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/fitness.activity.write",
              "https://www.googleapis.com/auth/fitness.body.write",
              "https://www.googleapis.com/auth/fitness.location.write"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      },
      "get": {
        "description": "Returns a data source identified by a data stream ID.",
        "operationId": "fitness.users.dataSources.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/fitness.activity.read",
              "https://www.googleapis.com/auth/fitness.activity.write",
              "https://www.googleapis.com/auth/fitness.body.read",
              "https://www.googleapis.com/auth/fitness.body.write",
              "https://www.googleapis.com/auth/fitness.location.read",
              "https://www.googleapis.com/auth/fitness.location.write"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      },
      "patch": {
        "description": "Updates a given data source. It is an error to modify the data source's data stream ID, data type, type, stream name or device information apart from the device version. Changing these fields would require a new unique data stream ID and separate data source.\n\nData sources are identified by their data stream ID. This method supports patch semantics.",
        "operationId": "fitness.users.dataSources.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/fitness.activity.write",
              "https://www.googleapis.com/auth/fitness.body.write",
              "https://www.googleapis.com/auth/fitness.location.write"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      },
      "put": {
        "description": "Updates a given data source. It is an error to modify the data source's data stream ID, data type, type, stream name or device information apart from the device version. Changing these fields would require a new unique data stream ID and separate data source.\n\nData sources are identified by their data stream ID.",
        "operationId": "fitness.users.dataSources.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/fitness.activity.write",
              "https://www.googleapis.com/auth/fitness.body.write",
              "https://www.googleapis.com/auth/fitness.location.write"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/dataSources/{dataSourceId}/datasets/{datasetId}": {
      "delete": {
        "description": "Performs an inclusive delete of all data points whose start and end times have any overlap with the time range specified by the dataset ID. For most data types, the entire data point will be deleted. For data types where the time span represents a consistent value (such as com.google.activity.segment), and a data point straddles either end point of the dataset, only the overlapping portion of the data point will be deleted.",
        "operationId": "fitness.users.dataSources.datasets.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/fitness.activity.write",
              "https://www.googleapis.com/auth/fitness.body.write",
              "https://www.googleapis.com/auth/fitness.location.write"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      },
      "get": {
        "description": "Returns a dataset containing all data points whose start and end times overlap with the specified range of the dataset minimum start time and maximum end time. Specifically, any data point whose start time is less than or equal to the dataset end time and whose end time is greater than or equal to the dataset start time.",
        "operationId": "fitness.users.dataSources.datasets.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/fitness.activity.read",
              "https://www.googleapis.com/auth/fitness.activity.write",
              "https://www.googleapis.com/auth/fitness.body.read",
              "https://www.googleapis.com/auth/fitness.body.write",
              "https://www.googleapis.com/auth/fitness.location.read",
              "https://www.googleapis.com/auth/fitness.location.write"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      },
      "patch": {
        "description": "Adds data points to a dataset. The dataset need not be previously created. All points within the given dataset will be returned with subsquent calls to retrieve this dataset. Data points can belong to more than one dataset. This method does not use patch semantics.",
        "operationId": "fitness.users.dataSources.datasets.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/fitness.activity.write",
              "https://www.googleapis.com/auth/fitness.body.write",
              "https://www.googleapis.com/auth/fitness.location.write"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/dataset:aggregate": {
      "post": {
        "operationId": "fitness.users.dataset.aggregate",
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/sessions/{sessionId}": {
      "delete": {
        "description": "Deletes a session specified by the given session ID.",
        "operationId": "fitness.users.sessions.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/fitness.activity.write"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      },
      "put": {
        "description": "Updates or insert a given session.",
        "operationId": "fitness.users.sessions.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/fitness.activity.write"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/sessions": {
      "get": {
        "description": "Lists sessions previously created.",
        "operationId": "fitness.users.sessions.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/fitness.activity.read",
              "https://www.googleapis.com/auth/fitness.activity.write",
              "https://www.googleapis.com/auth/fitness.body.read",
              "https://www.googleapis.com/auth/fitness.body.write",
              "https://www.googleapis.com/auth/fitness.location.read",
              "https://www.googleapis.com/auth/fitness.location.write"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/fitness.activity.read": "View your activity information in Google Fit",
        "https://www.googleapis.com/auth/fitness.activity.write": "View and store your activity information in Google Fit",
        "https://www.googleapis.com/auth/fitness.body.read": "View body sensor information in Google Fit",
        "https://www.googleapis.com/auth/fitness.body.write": "View and store body sensor data in Google Fit",
        "https://www.googleapis.com/auth/fitness.location.read": "View your stored location data in Google Fit",
        "https://www.googleapis.com/auth/fitness.location.write": "View and store your location data in Google Fit"
      }
    }
  }
}