openapi: 3.0.0
servers:
  - url: https://admin.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: Admin SDK lets administrators of enterprise domains to view and manage resources like user, groups etc. It also provides audit and usage reports of domain.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Admin SDK API
  version: datatransfer_v1
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png
  x-origin:
    - format: google
      url: https://admin.googleapis.com/$discovery/rest?version=datatransfer_v1
      version: v1
  x-preferred: false
  x-providerName: googleapis.com
  x-serviceName: admin
tags:
  - name: applications
  - name: transfers
paths:
  /admin/datatransfer/v1/applications:
    get:
      description: Lists the applications available for data transfer for a customer.
      operationId: datatransfer.applications.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
      tags:
        - applications
  "/admin/datatransfer/v1/applications/{applicationId}":
    get:
      description: Retrieves information about an application for the given application ID.
      operationId: datatransfer.applications.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
      tags:
        - applications
  /admin/datatransfer/v1/transfers:
    get:
      description: Lists the transfers for a customer by source user, destination user, or status.
      operationId: datatransfer.transfers.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
      tags:
        - transfers
    post:
      description: Inserts a data transfer request. See the [Transfer parameters](/admin-sdk/data-transfer/v1/parameters) reference for specific application requirements.
      operationId: datatransfer.transfers.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer
      tags:
        - transfers
  "/admin/datatransfer/v1/transfers/{dataTransferId}":
    get:
      description: Retrieves a data transfer request by its resource ID.
      operationId: datatransfer.transfers.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer
        - Oauth2:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.datatransfer.readonly
      tags:
        - transfers
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/admin.datatransfer: View and manage data transfers between users in your organization
            https://www.googleapis.com/auth/admin.datatransfer.readonly: View data transfers between users in your organization
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/admin.datatransfer: View and manage data transfers between users in your organization
            https://www.googleapis.com/auth/admin.datatransfer.readonly: View data transfers between users in your organization
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
