# flake8: noqa

# import apis into api package
from openapi_client.api.application_gateways_api import ApplicationGatewaysApi
from openapi_client.api.express_route_circuit_arp_table_api import ExpressRouteCircuitArpTableApi
from openapi_client.api.express_route_circuit_authorizations_api import ExpressRouteCircuitAuthorizationsApi
from openapi_client.api.express_route_circuit_peerings_api import ExpressRouteCircuitPeeringsApi
from openapi_client.api.express_route_circuit_routes_table_api import ExpressRouteCircuitRoutesTableApi
from openapi_client.api.express_route_circuit_routes_table_summary_api import ExpressRouteCircuitRoutesTableSummaryApi
from openapi_client.api.express_route_circuit_stats_api import ExpressRouteCircuitStatsApi
from openapi_client.api.express_route_circuits_api import ExpressRouteCircuitsApi
from openapi_client.api.express_route_service_providers_api import ExpressRouteServiceProvidersApi
from openapi_client.api.load_balancers_api import LoadBalancersApi
from openapi_client.api.local_network_gateways_api import LocalNetworkGatewaysApi
from openapi_client.api.network_interfaces_api import NetworkInterfacesApi
from openapi_client.api.network_security_groups_api import NetworkSecurityGroupsApi
from openapi_client.api.public_ip_addresses_api import PublicIPAddressesApi
from openapi_client.api.route_tables_api import RouteTablesApi
from openapi_client.api.routes_api import RoutesApi
from openapi_client.api.security_rules_api import SecurityRulesApi
from openapi_client.api.subnets_api import SubnetsApi
from openapi_client.api.usages_api import UsagesApi
from openapi_client.api.virtual_network_gateway_connections_api import VirtualNetworkGatewayConnectionsApi
from openapi_client.api.virtual_network_gateways_api import VirtualNetworkGatewaysApi
from openapi_client.api.virtual_network_peerings_api import VirtualNetworkPeeringsApi
from openapi_client.api.virtual_networks_api import VirtualNetworksApi
from openapi_client.api.default_api import DefaultApi

