{
  "swagger": "2.0",
  "info": {
    "title": "AdSense Management API",
    "x-serviceName": "adsense",
    "description": "Gives AdSense publishers access to their inventory and the ability to generate reports",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v1.2",
    "x-origin": {
      "format": "google",
      "version": "v1",
      "url": "https://www.googleapis.com/discovery/v1/apis/adsense/v1.2/rest"
    }
  },
  "host": "www.googleapis.com",
  "basePath": "/adsense/v1.2",
  "schemes": [
    "https"
  ],
  "paths": {
    "/accounts/{accountId}": {
      "get": {
        "description": "Get information about the selected AdSense account.",
        "operationId": "adsense.accounts.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts": {
      "get": {
        "description": "List all accounts available to this AdSense account.",
        "operationId": "adsense.accounts.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/adclients": {
      "get": {
        "description": "List all ad clients in the specified account.",
        "operationId": "adsense.accounts.adclients.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/adclients/{adClientId}/adunits/{adUnitId}": {
      "get": {
        "description": "Gets the specified ad unit in the specified ad client for the specified account.",
        "operationId": "adsense.accounts.adunits.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/adclients/{adClientId}/adunits": {
      "get": {
        "description": "List all ad units in the specified ad client for the specified account.",
        "operationId": "adsense.accounts.adunits.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/adclients/{adClientId}/adunits/{adUnitId}/customchannels": {
      "get": {
        "description": "List all custom channels which the specified ad unit belongs to.",
        "operationId": "adsense.accounts.adunits.customchannels.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/adclients/{adClientId}/customchannels/{customChannelId}": {
      "get": {
        "description": "Get the specified custom channel from the specified ad client for the specified account.",
        "operationId": "adsense.accounts.customchannels.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/adclients/{adClientId}/customchannels": {
      "get": {
        "description": "List all custom channels in the specified ad client for the specified account.",
        "operationId": "adsense.accounts.customchannels.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/adclients/{adClientId}/customchannels/{customChannelId}/adunits": {
      "get": {
        "description": "List all ad units in the specified custom channel.",
        "operationId": "adsense.accounts.customchannels.adunits.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/reports": {
      "get": {
        "description": "Generate an AdSense report based on the report request sent in the query parameters. Returns the result as JSON; to retrieve output in CSV format specify \"alt=csv\" as a query parameter.",
        "operationId": "adsense.accounts.reports.generate",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/reports/{savedReportId}": {
      "get": {
        "description": "Generate an AdSense report based on the saved report ID sent in the query parameters.",
        "operationId": "adsense.accounts.reports.saved.generate",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/reports/saved": {
      "get": {
        "description": "List all saved reports in the specified AdSense account.",
        "operationId": "adsense.accounts.reports.saved.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/savedadstyles/{savedAdStyleId}": {
      "get": {
        "description": "List a specific saved ad style for the specified account.",
        "operationId": "adsense.accounts.savedadstyles.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/savedadstyles": {
      "get": {
        "description": "List all saved ad styles in the specified account.",
        "operationId": "adsense.accounts.savedadstyles.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/adclients/{adClientId}/urlchannels": {
      "get": {
        "description": "List all URL channels in the specified ad client for the specified account.",
        "operationId": "adsense.accounts.urlchannels.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/adclients": {
      "get": {
        "description": "List all ad clients in this AdSense account.",
        "operationId": "adsense.adclients.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "adclients"
        ]
      }
    },
    "/adclients/{adClientId}/adunits/{adUnitId}": {
      "get": {
        "description": "Gets the specified ad unit in the specified ad client.",
        "operationId": "adsense.adunits.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "adunits"
        ]
      }
    },
    "/adclients/{adClientId}/adunits": {
      "get": {
        "description": "List all ad units in the specified ad client for this AdSense account.",
        "operationId": "adsense.adunits.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "adunits"
        ]
      }
    },
    "/adclients/{adClientId}/adunits/{adUnitId}/customchannels": {
      "get": {
        "description": "List all custom channels which the specified ad unit belongs to.",
        "operationId": "adsense.adunits.customchannels.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "adunits"
        ]
      }
    },
    "/adclients/{adClientId}/customchannels/{customChannelId}": {
      "get": {
        "description": "Get the specified custom channel from the specified ad client.",
        "operationId": "adsense.customchannels.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "customchannels"
        ]
      }
    },
    "/adclients/{adClientId}/customchannels": {
      "get": {
        "description": "List all custom channels in the specified ad client for this AdSense account.",
        "operationId": "adsense.customchannels.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "customchannels"
        ]
      }
    },
    "/adclients/{adClientId}/customchannels/{customChannelId}/adunits": {
      "get": {
        "description": "List all ad units in the specified custom channel.",
        "operationId": "adsense.customchannels.adunits.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "customchannels"
        ]
      }
    },
    "/reports": {
      "get": {
        "description": "Generate an AdSense report based on the report request sent in the query parameters. Returns the result as JSON; to retrieve output in CSV format specify \"alt=csv\" as a query parameter.",
        "operationId": "adsense.reports.generate",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "reports"
        ]
      }
    },
    "/reports/{savedReportId}": {
      "get": {
        "description": "Generate an AdSense report based on the saved report ID sent in the query parameters.",
        "operationId": "adsense.reports.saved.generate",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "reports"
        ]
      }
    },
    "/reports/saved": {
      "get": {
        "description": "List all saved reports in this AdSense account.",
        "operationId": "adsense.reports.saved.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "reports"
        ]
      }
    },
    "/savedadstyles/{savedAdStyleId}": {
      "get": {
        "description": "Get a specific saved ad style from the user's account.",
        "operationId": "adsense.savedadstyles.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "savedadstyles"
        ]
      }
    },
    "/savedadstyles": {
      "get": {
        "description": "List all saved ad styles in the user's account.",
        "operationId": "adsense.savedadstyles.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "savedadstyles"
        ]
      }
    },
    "/adclients/{adClientId}/urlchannels": {
      "get": {
        "description": "List all URL channels in the specified ad client for this AdSense account.",
        "operationId": "adsense.urlchannels.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/adsense",
              "https://www.googleapis.com/auth/adsense.readonly"
            ]
          }
        ],
        "tags": [
          "urlchannels"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/adsense": "View and manage your AdSense data",
        "https://www.googleapis.com/auth/adsense.readonly": "View your AdSense data"
      }
    }
  }
}