swagger: '2.0'
schemes:
  - https
host: api.flat.io
basePath: /v2
info:
  contact:
    email: developers@flat.io
    name: Flat
    url: 'https://flat.io/support'
  description: |
    The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:

    * Creating and importing new music scores using MusicXML or MIDI files
    * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI)
    * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.

    The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body.
    The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/).
    This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).

    You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).

    Getting Started and learn more:

    * [API Overview and interoduction](https://flat.io/developers/docs/api/)
    * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html)
    * [SDKs](https://flat.io/developers/docs/api/sdks.html)
    * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html)
    * [Changelog](https://flat.io/developers/docs/api/changelog.html)
  termsOfService: 'https://flat.io/legal'
  title: Flat
  version: 2.0.0
  x-apisguru-categories:
    - media
    - collaboration
  x-logo:
    url: 'https://flat.io/img/logo-white.svg'
  x-origin:
    - format: swagger
      url: 'https://raw.githubusercontent.com/FlatIO/api-reference/master/spec/swagger.yaml'
      version: '2.0'
  x-providerName: flat.io
securityDefinitions:
  OAuth2:
    authorizationUrl: 'https://flat.io/auth/oauth'
    description: |
      OAuth 2.0 authentication for your app or script.
    flow: accessCode
    scopes:
      account.education_profile: |
        Provides access to the basic person's education profile and public organization information.
      account.public_profile: |
        Provides access to the basic person's public profile. Education profiles may be anonymized with this scope, you can request the scope `education_profile` to access to the a basic education account profile.
      scores: |
        Full, permissive scope to access all of a user's scores.
      scores.readonly: |
        Allows read-only access to all a user's scores. You won't need this scope to read public scores.
      scores.social: |
        Allow to post comments and like scores
    tokenUrl: 'https://api.flat.io/oauth/access_token'
    type: oauth2
tags:
  - description: |
      These API endpoints are related to the Flat account you are currently using. When using an OAuth2 access token, you can use [`GET /me`](#operation/getAuthenticatedUser) to get information about the account.
    name: Account
    x-displayName: Flat Account
  - description: |
      Sheet music is the main API object type available for all Flat account.

      Here is a typical lifecycle for a music score document on Flat:
        - An end user can **create a music score** or **import a document** using our [web interface](https://flat.io) or a third-party website/app (e.g. Google Drive) using this API (see [`POST /v2/scores`](#operation/createScore). The creation and import of music scores can be done with this single API endpoint. This one currently supports the [MusicXML](http://www.musicxml.com/) (compressed or not) and [MIDI](https://www.midi.org/specifications).
        - The scores from a single account can **be listed** with [`GET /users/{user}/scores`](#operation/getUserScores) as well of scores shared with a specific group with [`GET /groups/{group}/scores`](#operation/getGroupScores).
        - The metadata of a single score can be retrieved with [`GET /scores/{score}`](#operation/getScore).
        - Scores on Flat have **one or multiple revisions**: creating a new score will create a first revision. These **revisions can be listed** using [`GET /scores/{score}/revisions`](#operation/getScoreRevisions) and a specific **revision data can be downloaded** with [`GET /scores/{score}/revisions/{revision}/{format}`](#operation/getScoreRevisionData). New revisions can be created using our [sheet music editor](https://flat.io) or using [`POST /scores/{score}/revisions`](#operation/createSc[...]
        - Scores can be **shared publicly** by changing the privacy option with [`POST /scores/{score}`](#operation/editScore), or **individually shared** using the different collaborators API endpoints (see [`POST /scores/{score}/collaborators`](#operation/addScoreCollaborator)).
    name: Score
    x-displayName: Music scores
  - description: Flat users
    name: User
paths:
  '/groups/{group}/scores':
    get:
      description: |
        Get the list of scores shared with a group.
      operationId: getGroupScores
      security: []
      summary: List group's scores
      tags:
        - Group
        - Score
  /me:
    get:
      description: |
        Get details about the current authenticated User.
      operationId: getAuthenticatedUser
      security:
        - OAuth2:
            - account.public_profile
            - account.education_profile
      summary: Get current user profile
      tags:
        - Account
  /scores:
    post:
      description: |
        Use this API method to **create a new music score in the current User account**. You will need a MusicXML 3 (`vnd.recordare.musicxml` or `vnd.recordare.musicxml+xml`) or a MIDI (`audio/midi`) file to create the new Flat document.

        This API call will automatically create the first revision of the document, the score can be modified by the using our web application or by uploading a new revision of this file (`POST /v2/scores/{score}/revisions/{revision}`).

        The currently authenticated user will be granted owner of the file and will be able to add other collaborators (users and groups).
      operationId: createScore
      security:
        - OAuth2:
            - scores
      summary: Create a new score
      tags:
        - Score
  '/scores/{score}':
    delete:
      description: |
        This API call will schedule the deletion of the score, its revisions, and whole history.
        The user calling this API method must have the `aclAdmin` rights on this document to process this action.
        The score won't be accessible anymore after calling this method and the user's quota will directly be updated.
      operationId: deleteScore
      security:
        - OAuth2:
            - scores
      summary: Delete a score
      tags:
        - Score
    get:
      description: |
        Get the details of a score identified by the `score` parameter in the URL.
        The currently authenticated user must have at least a read access to the document to use this API call.
      operationId: getScore
      security:
        - OAuth2:
            - scores
            - scores.readonly
      summary: Get a score's metadata
      tags:
        - Score
    put:
      description: |
        This API method allows you to change the metadata of a score document (e.g. its `title` or `privacy`), all the properties are optional.

        To edit the file itself, create a new revision using the appropriate method (`POST /v2/scores/{score}/revisions/{revision}`).
      operationId: editScore
      security:
        - OAuth2:
            - scores
      summary: Edit a score's metadata
      tags:
        - Score
  '/scores/{score}/collaborators':
    get:
      description: |
        This API call will list the different collaborators of a score and their rights on the document. The returned list will at least contain the owner of the document.

        Collaborators can be a single user (the object `user` will be populated) or a group (the object `group` will be populated).
      operationId: getScoreCollaborators
      security:
        - OAuth2:
            - scores.readonly
            - scores
      summary: List the collaborators
      tags:
        - Score
    post:
      description: |
        Share a score with a single user or a group. This API call allows to add, invite and update the collaborators of a document.
        - To add an existing Flat user to the document, specify its unique identifier in the `user` property.
        - To invite an external user to the document, specify its email in the `userEmail` property.
        - To add a Flat group to the document, specify its unique identifier in the `group` property.
        - To update an existing collaborator, process the same request with different rights.
      operationId: addScoreCollaborator
      security:
        - OAuth2:
            - scores
      summary: Add a new collaborator
      tags:
        - Score
  '/scores/{score}/collaborators/{collaborator}':
    delete:
      description: |
        Remove the specified collaborator from the score
      operationId: removeScoreCollaborator
      security:
        - OAuth2:
            - scores
      summary: Delete a collaborator
      tags:
        - Score
    get:
      description: |
        Get the information about a collaborator (User or Group).
      operationId: getScoreCollaborator
      security:
        - OAuth2:
            - scores.readonly
      summary: Get a collaborator
      tags:
        - Score
  '/scores/{score}/comments':
    get:
      description: This method lists the different comments added on a music score (documents and inline) sorted by their post dates.
      operationId: getScoreComments
      security:
        - OAuth2:
            - scores.readonly
            - scores.social
            - scores
      summary: List comments
      tags:
        - Score
    post:
      description: |
        Post a document or a contextualized comment on a document.

        Please note that this method includes an anti-spam system for public scores. We don't guarantee that your comments will be accepted and displayed to end-user. Comments are be blocked by returning a `403` HTTP error and hidden from other users when the `spam` property is `true`.
      operationId: postScoreComment
      security:
        - OAuth2:
            - scores.social
            - scores
      summary: Post a new comment
      tags:
        - Score
  '/scores/{score}/comments/{comment}':
    delete:
      operationId: deleteScoreComment
      security:
        - OAuth2:
            - scores.social
            - scores
      summary: Delete a comment
      tags:
        - Score
    put:
      operationId: updateScoreComment
      security:
        - OAuth2:
            - scores.social
            - scores
      summary: Update an existing comment
      tags:
        - Score
  '/scores/{score}/comments/{comment}/resolved':
    delete:
      operationId: markScoreCommentUnresolved
      security:
        - OAuth2:
            - scores.social
            - scores
      summary: Mark the comment as unresolved
      tags:
        - Score
    put:
      operationId: markScoreCommentResolved
      security:
        - OAuth2:
            - scores.social
            - scores
      summary: Mark the comment as resolved
      tags:
        - Score
  '/scores/{score}/fork':
    post:
      description: |
        This API call will make a copy of the last revision of the specified score and create a new score. The copy of the score will have a privacy set to `private`.

        When using a [Flat for Education](https://flat.io/edu) account, the inline and contextualized comments will be accessible in the child document.
      operationId: forkScore
      security:
        - OAuth2:
            - scores
      summary: Fork a score
      tags:
        - Score
  '/scores/{score}/revisions':
    get:
      description: |
        When creating a score or saving a new version of a score, a revision is created in our storage. This method allows you to list all of them, sorted by last modification.

        Depending the plan of the account, this list can be trunked to the few last revisions.
      operationId: getScoreRevisions
      security:
        - OAuth2:
            - scores
            - scores.readonly
      summary: List the revisions
      tags:
        - Score
    post:
      description: |
        Update a score by uploading a new revision for this one.
      operationId: createScoreRevision
      security:
        - OAuth2:
            - scores
      summary: Create a new revision
      tags:
        - Score
  '/scores/{score}/revisions/{revision}':
    get:
      description: |
        When creating a score or saving a new version of a score, a revision is created in our storage. This method allows you to get a specific
        revision metadata.
      operationId: getScoreRevision
      security: []
      summary: Get a score revision
      tags:
        - Score
  '/scores/{score}/revisions/{revision}/{format}':
    get:
      description: |
        Retrieve the file corresponding to a score revision (the following formats are available: Flat JSON/Adagio JSON `json`, MusicXML
        `mxl`/`xml`, MP3 `mp3`, WAV `wav`, MIDI `midi`, or a tumbnail of the first page `thumbnail.png`).
      operationId: getScoreRevisionData
      security: []
      summary: Get a score revision data
      tags:
        - Score
  '/users/{user}':
    get:
      description: |
        Get a public profile of a Flat User.
      operationId: getUser
      security:
        - OAuth2:
            - account.public_profile
            - account.education_profile
      summary: Get a public user profile
      tags:
        - User
  '/users/{user}/likes':
    get:
      operationId: gerUserLikes
      security:
        - OAuth2:
            - account.public_profile
      summary: List liked scores
      tags:
        - User
        - Score
  '/users/{user}/scores':
    get:
      description: |
        Get the list of scores owned by the User
      operationId: getUserScores
      security:
        - OAuth2:
            - scores
            - scores.readonly
      summary: List user's scores
      tags:
        - User
        - Score