openapi: 3.0.1
servers:
  - url: https://api.hubapi.com
info:
  title: CMS Domains
  version: v3
  x-hubspot-api-use-case: Retrieve all currently connected domains to see which sites are live in a given account.
  x-hubspot-documentation-banner: NONE
  x-hubspot-introduction: Use the domain management API to return information about the domains connected to a HubSpot account. You can return data for all currently connected domains, or for a single domain by ID.
  x-hubspot-product-tier-requirements:
    cms: STARTER
    marketing: PROFESSIONAL
  x-hubspot-related-documentation:
    - name: Domains Guide
      url: https://hubspot.dev/guides/api/cms/domains
  x-logo:
    url: https://developers.hubspot.com/hubfs/assets/hubspot.com/buzz/HubSpotOpenGraph.png
  x-origin:
    - format: openapi
      url: https://api.hubspot.com/api-catalog-public/v1/apis/cms/v3/domains
      version: "3.0"
  x-providerName: hubapi.com
  x-serviceName: cms
tags:
  - name: Domains
paths:
  /cms/v3/domains/:
    get:
      description: Returns all existing domains that have been created. Results can be limited and filtered by creation or updated date.
      operationId: get-/cms/v3/domains/_getPage
      security:
        - private_apps_legacy: []
        - oauth2:
            - cms.domains.read
        - private_apps: []
        - private_apps: []
        - oauth2:
            - cms.domains.write
        - oauth2_legacy:
            - cms.knowledge_base.settings.read
        - private_apps_legacy: []
        - oauth2_legacy:
            - cms.knowledge_base.settings.write
        - oauth2_legacy:
            - content
        - private_apps_legacy: []
      summary: Get current domains
      tags:
        - Domains
  /cms/v3/domains/{domainId}:
    get:
      description: Returns a single domains with the id specified.
      operationId: get-/cms/v3/domains/{domainId}_getById
      security:
        - private_apps_legacy: []
        - oauth2:
            - cms.domains.read
        - private_apps: []
        - private_apps: []
        - oauth2:
            - cms.domains.write
        - oauth2_legacy:
            - cms.knowledge_base.settings.read
        - private_apps_legacy: []
        - oauth2_legacy:
            - cms.knowledge_base.settings.write
        - oauth2_legacy:
            - content
        - private_apps_legacy: []
      summary: Get a single domain
      tags:
        - Domains
components:
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            cms.domains.read: Read domains.
            cms.domains.write: Create or update domains.
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            cms.knowledge_base.settings.read: View knowledge base settings
            cms.knowledge_base.settings.write: Update knowledge base settings
            content: Read from and write to my Content
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps:
      in: header
      name: private-app
      type: apiKey
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
x-hubspot-available-client-libraries:
  - PHP
  - Node
  - Ruby
  - Python
x-hubspot-documentation-banner: NONE
x-hubspot-product-tier-requirements:
  cms: STARTER
  marketing: PROFESSIONAL
