openapi: 3.0.0
servers:
  - url: https://www.bungie.net/Platform
info:
  contact:
    email: support@bungie.com
    name: Bungie.net API Support
    url: https://github.com/Bungie-net/api
  description: These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
  license:
    name: BSD License 2.0
    url: https://github.com/Bungie-net/api/blob/master/LICENSE
  termsOfService: https://www.bungie.net/en/View/Bungie/terms
  title: Bungie.Net API
  version: 2.18.0
  x-apisguru-categories:
    - media
  x-logo:
    backgroundColor: "#FFFFFF"
    url: https://api.apis.guru/v2/cache/logo/https_pbs.twimg.com_profile_images_560547568992944129_x46z946T_400x400.jpeg
  x-origin:
    - format: openapi
      url: https://raw.githubusercontent.com/Bungie-net/api/master/openapi-2.json
      version: "3.0"
  x-providerName: bungie.net
tags:
  - description: application
    name: App
  - description: user
    name: User
  - description: content
    name: Content
  - description: forum
    name: Forum
  - description: groupV2
    name: GroupV2
  - description: tokens
    name: Tokens
  - description: destiny2
    name: Destiny2
  - description: communitycontent
    name: CommunityContent
  - description: trending
    name: Trending
  - description: fireteam
    name: Fireteam
  - description: social
    name: Social
  - description: core
    name: ""
paths:
  "/App/ApiUsage/{applicationId}/":
    get:
      deprecated: false
      description: Get API usage by application for time frame specified. You can go as far back as 30 days ago, and can ask for up to a 48 hour window of time in a single request. You must be authenticated with at least the ReadUserData permission to access this endpoint.
      operationId: App.GetApplicationApiUsage
      security:
        - oauth2:
            - ReadUserData
      tags:
        - App
  /App/FirstParty/:
    get:
      deprecated: false
      description: Get list of applications created by Bungie.
      operationId: App.GetBungieApplications
      tags:
        - App
  "/CommunityContent/Get/{sort}/{mediaFilter}/{page}/":
    get:
      deprecated: false
      description: Returns community content.
      operationId: CommunityContent.GetCommunityContent
      tags:
        - CommunityContent
  "/Content/GetContentById/{id}/{locale}/":
    get:
      deprecated: false
      description: Returns a content item referenced by id
      operationId: Content.GetContentById
      tags:
        - Content
  "/Content/GetContentByTagAndType/{tag}/{type}/{locale}/":
    get:
      deprecated: false
      description: Returns the newest item that matches a given tag and Content Type.
      operationId: Content.GetContentByTagAndType
      tags:
        - Content
  "/Content/GetContentType/{type}/":
    get:
      deprecated: false
      description: Gets an object describing a particular variant of content.
      operationId: Content.GetContentType
      tags:
        - Content
  "/Content/Rss/NewsArticles/{pageToken}/":
    get:
      deprecated: false
      description: Returns a JSON string response that is the RSS feed for news articles.
      operationId: Content.RssNewsArticles
      tags:
        - Content
  "/Content/Search/{locale}/":
    get:
      deprecated: false
      description: Gets content based on querystring information passed in. Provides basic search and text search capabilities.
      operationId: Content.SearchContentWithText
      tags:
        - Content
  "/Content/SearchContentByTagAndType/{tag}/{type}/{locale}/":
    get:
      deprecated: false
      description: Searches for Content Items that match the given Tag and Content Type.
      operationId: Content.SearchContentByTagAndType
      tags:
        - Content
  "/Content/SearchHelpArticles/{searchtext}/{size}/":
    get:
      deprecated: false
      description: Search for Help Articles.
      operationId: Content.SearchHelpArticles
      tags:
        - Content
  /Destiny2/Actions/Items/EquipItem/:
    post:
      deprecated: false
      description: Equip an item. You must have a valid Destiny Account, and either be in a social space, in orbit, or offline.
      operationId: Destiny2.EquipItem
      security:
        - oauth2:
            - MoveEquipDestinyItems
      tags:
        - Destiny2
      x-documentation-attributes:
        ThrottleSecondsBetweenActionPerUser: "0.1"
  /Destiny2/Actions/Items/EquipItems/:
    post:
      deprecated: false
      description: Equip a list of items by itemInstanceIds. You must have a valid Destiny Account, and either be in a social space, in orbit, or offline. Any items not found on your character will be ignored.
      operationId: Destiny2.EquipItems
      security:
        - oauth2:
            - MoveEquipDestinyItems
      tags:
        - Destiny2
      x-documentation-attributes:
        ThrottleSecondsBetweenActionPerUser: "0.1"
  /Destiny2/Actions/Items/InsertSocketPlug/:
    post:
      deprecated: false
      description: Insert a plug into a socketed item. I know how it sounds, but I assure you it's much more G-rated than you might be guessing. We haven't decided yet whether this will be able to insert plugs that have side effects, but if we do it will require special scope permission for an application attempting to do so. You must have a valid Destiny Account, and either be in a social space, in orbit, or offline. Request must include proof of permission for 'InsertPlugs' from the account ow[...]
      operationId: Destiny2.InsertSocketPlug
      security:
        - oauth2:
            - AdvancedWriteActions
      tags:
        - Destiny2
        - Preview
      x-documentation-attributes:
        ThrottleSecondsBetweenActionPerUser: "0.5"
      x-preview: true
  /Destiny2/Actions/Items/InsertSocketPlugFree/:
    post:
      deprecated: false
      description: Insert a 'free' plug into an item's socket. This does not require 'Advanced Write Action' authorization and is available to 3rd-party apps, but will only work on 'free and reversible' socket actions (Perks, Armor Mods, Shaders, Ornaments, etc.). You must have a valid Destiny Account, and the character must either be in a social space, in orbit, or offline.
      operationId: Destiny2.InsertSocketPlugFree
      security:
        - oauth2:
            - MoveEquipDestinyItems
      tags:
        - Destiny2
        - Preview
      x-documentation-attributes:
        ThrottleSecondsBetweenActionPerUser: "0.5"
      x-preview: true
  /Destiny2/Actions/Items/PullFromPostmaster/:
    post:
      deprecated: false
      description: Extract an item from the Postmaster, with whatever implications that may entail. You must have a valid Destiny account. You must also pass BOTH a reference AND an instance ID if it's an instanced item.
      operationId: Destiny2.PullFromPostmaster
      security:
        - oauth2:
            - MoveEquipDestinyItems
      tags:
        - Destiny2
      x-documentation-attributes:
        ThrottleSecondsBetweenActionPerUser: "0.1"
  /Destiny2/Actions/Items/SetLockState/:
    post:
      deprecated: false
      description: Set the Lock State for an instanced item. You must have a valid Destiny Account.
      operationId: Destiny2.SetItemLockState
      security:
        - oauth2:
            - MoveEquipDestinyItems
      tags:
        - Destiny2
      x-documentation-attributes:
        ThrottleSecondsBetweenActionPerUser: "0.1"
  /Destiny2/Actions/Items/SetTrackedState/:
    post:
      deprecated: false
      description: Set the Tracking State for an instanced item, if that item is a Quest or Bounty. You must have a valid Destiny Account. Yeah, it's an item.
      operationId: Destiny2.SetQuestTrackedState
      security:
        - oauth2:
            - MoveEquipDestinyItems
      tags:
        - Destiny2
      x-documentation-attributes:
        ThrottleSecondsBetweenActionPerUser: "1"
  /Destiny2/Actions/Items/TransferItem/:
    post:
      deprecated: false
      description: Transfer an item to/from your vault. You must have a valid Destiny account. You must also pass BOTH a reference AND an instance ID if it's an instanced item. itshappening.gif
      operationId: Destiny2.TransferItem
      security:
        - oauth2:
            - MoveEquipDestinyItems
      tags:
        - Destiny2
      x-documentation-attributes:
        ThrottleSecondsBetweenActionPerUser: "0.1"
  /Destiny2/Actions/Loadouts/ClearLoadout/:
    post:
      deprecated: false
      description: Clear the identifiers and items of a loadout.
      operationId: Destiny2.ClearLoadout
      security:
        - oauth2:
            - MoveEquipDestinyItems
      tags:
        - Destiny2
      x-documentation-attributes:
        ThrottleSecondsBetweenActionPerUser: "1"
  /Destiny2/Actions/Loadouts/EquipLoadout/:
    post:
      deprecated: false
      description: Equip a loadout. You must have a valid Destiny Account, and either be in a social space, in orbit, or offline.
      operationId: Destiny2.EquipLoadout
      security:
        - oauth2:
            - MoveEquipDestinyItems
      tags:
        - Destiny2
      x-documentation-attributes:
        ThrottleSecondsBetweenActionPerUser: "1"
  /Destiny2/Actions/Loadouts/SnapshotLoadout/:
    post:
      deprecated: false
      description: Snapshot a loadout with the currently equipped items.
      operationId: Destiny2.SnapshotLoadout
      security:
        - oauth2:
            - MoveEquipDestinyItems
      tags:
        - Destiny2
      x-documentation-attributes:
        ThrottleSecondsBetweenActionPerUser: "1"
  /Destiny2/Actions/Loadouts/UpdateLoadoutIdentifiers/:
    post:
      deprecated: false
      description: Update the color, icon, and name of a loadout.
      operationId: Destiny2.UpdateLoadoutIdentifiers
      security:
        - oauth2:
            - MoveEquipDestinyItems
      tags:
        - Destiny2
      x-documentation-attributes:
        ThrottleSecondsBetweenActionPerUser: "1"
  "/Destiny2/Armory/Search/{type}/{searchTerm}/":
    get:
      deprecated: false
      description: Gets a page list of Destiny items.
      operationId: Destiny2.SearchDestinyEntities
      tags:
        - Destiny2
  /Destiny2/Awa/AwaProvideAuthorizationResult/:
    post:
      deprecated: false
      description: Provide the result of the user interaction. Called by the Bungie Destiny App to approve or reject a request.
      operationId: Destiny2.AwaProvideAuthorizationResult
      tags:
        - Destiny2
  "/Destiny2/Awa/GetActionToken/{correlationId}/":
    get:
      deprecated: false
      description: Returns the action token if user approves the request.
      operationId: Destiny2.AwaGetActionToken
      security:
        - oauth2:
            - AdvancedWriteActions
      tags:
        - Destiny2
  /Destiny2/Awa/Initialize/:
    post:
      deprecated: false
      description: Initialize a request to perform an advanced write action.
      operationId: Destiny2.AwaInitializeRequest
      security:
        - oauth2:
            - AdvancedWriteActions
      tags:
        - Destiny2
  /Destiny2/Clan/ClanBannerDictionary/:
    get:
      deprecated: false
      description: Returns the dictionary of values for the Clan Banner
      operationId: Destiny2.GetClanBannerSource
      tags:
        - Destiny2
  "/Destiny2/Clan/{groupId}/WeeklyRewardState/":
    get:
      deprecated: false
      description: Returns information on the weekly clan rewards and if the clan has earned them or not. Note that this will always report rewards as not redeemed.
      operationId: Destiny2.GetClanWeeklyRewardState
      tags:
        - Destiny2
  /Destiny2/Manifest/:
    get:
      deprecated: false
      description: Returns the current version of the manifest as a json object.
      operationId: Destiny2.GetDestinyManifest
      tags:
        - Destiny2
  "/Destiny2/Manifest/{entityType}/{hashIdentifier}/":
    get:
      deprecated: false
      description: Returns the static definition of an entity of the given Type and hash identifier. Examine the API Documentation for the Type Names of entities that have their own definitions. Note that the return type will always *inherit from* DestinyDefinition, but the specific type returned will be the requested entity type if it can be found. Please don't use this as a chatty alternative to the Manifest database if you require large sets of data, but for simple and one-off accesses this s[...]
      operationId: Destiny2.GetDestinyEntityDefinition
      tags:
        - Destiny2
  /Destiny2/Milestones/:
    get:
      deprecated: false
      description: Gets public information about currently available Milestones.
      operationId: Destiny2.GetPublicMilestones
      tags:
        - Destiny2
  "/Destiny2/Milestones/{milestoneHash}/Content/":
    get:
      deprecated: false
      description: Gets custom localized content for the milestone of the given hash, if it exists.
      operationId: Destiny2.GetPublicMilestoneContent
      tags:
        - Destiny2
  "/Destiny2/SearchDestinyPlayerByBungieName/{membershipType}/":
    post:
      deprecated: false
      description: Returns a list of Destiny memberships given a global Bungie Display Name. This method will hide overridden memberships due to cross save.
      operationId: Destiny2.SearchDestinyPlayerByBungieName
      tags:
        - Destiny2
  "/Destiny2/Stats/AggregateClanStats/{groupId}/":
    get:
      deprecated: false
      description: "Gets aggregated stats for a clan using the same categories as the clan leaderboards. PREVIEW: This endpoint is still in beta, and may experience rough edges. The schema is in final form, but there may be bugs that prevent desirable operation."
      operationId: Destiny2.GetClanAggregateStats
      tags:
        - Destiny2
        - Preview
      x-preview: true
  /Destiny2/Stats/Definition/:
    get:
      deprecated: false
      description: Gets historical stats definitions.
      operationId: Destiny2.GetHistoricalStatsDefinition
      tags:
        - Destiny2
  "/Destiny2/Stats/Leaderboards/Clans/{groupId}/":
    get:
      deprecated: false
      description: "Gets leaderboards with the signed in user's friends and the supplied destinyMembershipId as the focus. PREVIEW: This endpoint is still in beta, and may experience rough edges. The schema is in final form, but there may be bugs that prevent desirable operation."
      operationId: Destiny2.GetClanLeaderboards
      tags:
        - Destiny2
        - Preview
      x-preview: true
  "/Destiny2/Stats/Leaderboards/{membershipType}/{destinyMembershipId}/{characterId}/":
    get:
      deprecated: false
      description: "Gets leaderboards with the signed in user's friends and the supplied destinyMembershipId as the focus. PREVIEW: This endpoint is still in beta, and may experience rough edges. The schema is in final form, but there may be bugs that prevent desirable operation."
      operationId: Destiny2.GetLeaderboardsForCharacter
      tags:
        - Destiny2
        - Preview
      x-preview: true
  "/Destiny2/Stats/PostGameCarnageReport/{activityId}/":
    get:
      deprecated: false
      description: Gets the available post game carnage report for the activity ID.
      operationId: Destiny2.GetPostGameCarnageReport
      tags:
        - Destiny2
  "/Destiny2/Stats/PostGameCarnageReport/{activityId}/Report/":
    post:
      deprecated: false
      description: Report a player that you met in an activity that was engaging in ToS-violating activities. Both you and the offending player must have played in the activityId passed in. Please use this judiciously and only when you have strong suspicions of violation, pretty please.
      operationId: Destiny2.ReportOffensivePostGameCarnageReportPlayer
      security:
        - oauth2:
            - BnetWrite
      tags:
        - Destiny2
  /Destiny2/Vendors/:
    get:
      deprecated: false
      description: "Get items available from vendors where the vendors have items for sale that are common for everyone. If any portion of the Vendor's available inventory is character or account specific, we will be unable to return their data from this endpoint due to the way that available inventory is computed. As I am often guilty of saying: 'It's a long story...'"
      operationId: Destiny2.GetPublicVendors
      tags:
        - Destiny2
        - Preview
      x-preview: true
  "/Destiny2/{membershipType}/Account/{destinyMembershipId}/Character/{characterId}/Stats/":
    get:
      deprecated: false
      description: Gets historical stats for indicated character.
      operationId: Destiny2.GetHistoricalStats
      tags:
        - Destiny2
  "/Destiny2/{membershipType}/Account/{destinyMembershipId}/Character/{characterId}/Stats/Activities/":
    get:
      deprecated: false
      description: Gets activity history stats for indicated character.
      operationId: Destiny2.GetActivityHistory
      tags:
        - Destiny2
  "/Destiny2/{membershipType}/Account/{destinyMembershipId}/Character/{characterId}/Stats/AggregateActivityStats/":
    get:
      deprecated: false
      description: Gets all activities the character has participated in together with aggregate statistics for those activities.
      operationId: Destiny2.GetDestinyAggregateActivityStats
      tags:
        - Destiny2
  "/Destiny2/{membershipType}/Account/{destinyMembershipId}/Character/{characterId}/Stats/UniqueWeapons/":
    get:
      deprecated: false
      description: Gets details about unique weapon usage, including all exotic weapons.
      operationId: Destiny2.GetUniqueWeaponHistory
      tags:
        - Destiny2
  "/Destiny2/{membershipType}/Account/{destinyMembershipId}/Stats/":
    get:
      deprecated: false
      description: Gets aggregate historical stats organized around each character for a given account.
      operationId: Destiny2.GetHistoricalStatsForAccount
      tags:
        - Destiny2
  "/Destiny2/{membershipType}/Account/{destinyMembershipId}/Stats/Leaderboards/":
    get:
      deprecated: false
      description: "Gets leaderboards with the signed in user's friends and the supplied destinyMembershipId as the focus. PREVIEW: This endpoint has not yet been implemented. It is being returned for a preview of future functionality, and for public comment/suggestion/preparation."
      operationId: Destiny2.GetLeaderboards
      tags:
        - Destiny2
        - Preview
      x-preview: true
  "/Destiny2/{membershipType}/Profile/{destinyMembershipId}/":
    get:
      deprecated: false
      description: Returns Destiny Profile information for the supplied membership.
      operationId: Destiny2.GetProfile
      tags:
        - Destiny2
  "/Destiny2/{membershipType}/Profile/{destinyMembershipId}/Character/{characterId}/":
    get:
      deprecated: false
      description: Returns character information for the supplied character.
      operationId: Destiny2.GetCharacter
      tags:
        - Destiny2
  "/Destiny2/{membershipType}/Profile/{destinyMembershipId}/Character/{characterId}/Collectibles/{collectiblePresentationNodeHash}/":
    get:
      deprecated: false
      description: Given a Presentation Node that has Collectibles as direct descendants, this will return item details about those descendants in the context of the requesting character.
      operationId: Destiny2.GetCollectibleNodeDetails
      tags:
        - Destiny2
  "/Destiny2/{membershipType}/Profile/{destinyMembershipId}/Character/{characterId}/Vendors/":
    get:
      deprecated: false
      description: Get currently available vendors from the list of vendors that can possibly have rotating inventory. Note that this does not include things like preview vendors and vendors-as-kiosks, neither of whom have rotating/dynamic inventories. Use their definitions as-is for those.
      operationId: Destiny2.GetVendors
      tags:
        - Destiny2
  "/Destiny2/{membershipType}/Profile/{destinyMembershipId}/Character/{characterId}/Vendors/{vendorHash}/":
    get:
      deprecated: false
      description: Get the details of a specific Vendor.
      operationId: Destiny2.GetVendor
      tags:
        - Destiny2
  "/Destiny2/{membershipType}/Profile/{destinyMembershipId}/Item/{itemInstanceId}/":
    get:
      deprecated: false
      description: Retrieve the details of an instanced Destiny Item. An instanced Destiny item is one with an ItemInstanceId. Non-instanced items, such as materials, have no useful instance-specific details and thus are not queryable here.
      operationId: Destiny2.GetItem
      tags:
        - Destiny2
  "/Destiny2/{membershipType}/Profile/{membershipId}/LinkedProfiles/":
    get:
      deprecated: false
      description: Returns a summary information about all profiles linked to the requesting membership type/membership ID that have valid Destiny information. The passed-in Membership Type/Membership ID may be a Bungie.Net membership or a Destiny membership. It only returns the minimal amount of data to begin making more substantive requests, but will hopefully serve as a useful alternative to UserServices for people who just care about Destiny data. Note that it will only return linked account[...]
      operationId: Destiny2.GetLinkedProfiles
      tags:
        - Destiny2
  "/Fireteam/Clan/{groupId}/ActiveCount/":
    get:
      deprecated: false
      description: Gets a count of all active non-public fireteams for the specified clan. Maximum value returned is 25.
      operationId: Fireteam.GetActivePrivateClanFireteamCount
      security:
        - oauth2:
            - ReadGroups
      tags:
        - Fireteam
  "/Fireteam/Clan/{groupId}/Available/{platform}/{activityType}/{dateRange}/{slotFilter}/{publicOnly}/{page}/":
    get:
      deprecated: false
      description: Gets a listing of all of this clan's fireteams that are have available slots. Caller is not checked for join criteria so caching is maximized.
      operationId: Fireteam.GetAvailableClanFireteams
      security:
        - oauth2:
            - ReadGroups
      tags:
        - Fireteam
  "/Fireteam/Clan/{groupId}/My/{platform}/{includeClosed}/{page}/":
    get:
      deprecated: false
      description: Gets a listing of all fireteams that caller is an applicant, a member, or an alternate of.
      operationId: Fireteam.GetMyClanFireteams
      security:
        - oauth2:
            - ReadGroups
      tags:
        - Fireteam
  "/Fireteam/Clan/{groupId}/Summary/{fireteamId}/":
    get:
      deprecated: false
      description: Gets a specific fireteam.
      operationId: Fireteam.GetClanFireteam
      security:
        - oauth2:
            - ReadGroups
      tags:
        - Fireteam
  "/Fireteam/Search/Available/{platform}/{activityType}/{dateRange}/{slotFilter}/{page}/":
    get:
      deprecated: false
      description: Gets a listing of all public fireteams starting now with open slots. Caller is not checked for join criteria so caching is maximized.
      operationId: Fireteam.SearchPublicAvailableClanFireteams
      security:
        - oauth2:
            - ReadGroups
      tags:
        - Fireteam
  "/Forum/GetCoreTopicsPaged/{page}/{sort}/{quickDate}/{categoryFilter}/":
    get:
      deprecated: false
      description: Gets a listing of all topics marked as part of the core group.
      operationId: Forum.GetCoreTopicsPaged
      tags:
        - Forum
  /Forum/GetForumTagSuggestions/:
    get:
      deprecated: false
      description: Gets tag suggestions based on partial text entry, matching them with other tags previously used in the forums.
      operationId: Forum.GetForumTagSuggestions
      tags:
        - Forum
  "/Forum/GetPostAndParent/{childPostId}/":
    get:
      deprecated: false
      description: Returns the post specified and its immediate parent.
      operationId: Forum.GetPostAndParent
      tags:
        - Forum
  "/Forum/GetPostAndParentAwaitingApproval/{childPostId}/":
    get:
      deprecated: false
      description: Returns the post specified and its immediate parent of posts that are awaiting approval.
      operationId: Forum.GetPostAndParentAwaitingApproval
      tags:
        - Forum
  "/Forum/GetPostsThreadedPaged/{parentPostId}/{page}/{pageSize}/{replySize}/{getParentPost}/{rootThreadMode}/{sortMode}/":
    get:
      deprecated: false
      description: Returns a thread of posts at the given parent, optionally returning replies to those posts as well as the original parent.
      operationId: Forum.GetPostsThreadedPaged
      tags:
        - Forum
  "/Forum/GetPostsThreadedPagedFromChild/{childPostId}/{page}/{pageSize}/{replySize}/{rootThreadMode}/{sortMode}/":
    get:
      deprecated: false
      description: Returns a thread of posts starting at the topicId of the input childPostId, optionally returning replies to those posts as well as the original parent.
      operationId: Forum.GetPostsThreadedPagedFromChild
      tags:
        - Forum
  "/Forum/GetTopicForContent/{contentId}/":
    get:
      deprecated: false
      description: Gets the post Id for the given content item's comments, if it exists.
      operationId: Forum.GetTopicForContent
      tags:
        - Forum
  "/Forum/GetTopicsPaged/{page}/{pageSize}/{group}/{sort}/{quickDate}/{categoryFilter}/":
    get:
      deprecated: false
      description: Get topics from any forum.
      operationId: Forum.GetTopicsPaged
      tags:
        - Forum
  "/Forum/Poll/{topicId}/":
    get:
      deprecated: false
      description: Gets the specified forum poll.
      operationId: Forum.GetPoll
      tags:
        - Forum
  /Forum/Recruit/Summaries/:
    post:
      deprecated: false
      description: Allows the caller to get a list of to 25 recruitment thread summary information objects.
      operationId: Forum.GetRecruitmentThreadSummaries
      tags:
        - Forum
  /GetAvailableLocales/:
    get:
      deprecated: false
      description: List of available localization cultures
      operationId: .GetAvailableLocales
      tags:
        - ""
  /GlobalAlerts/:
    get:
      deprecated: false
      description: Gets any active global alert for display in the forum banners, help pages, etc. Usually used for DOC alerts.
      operationId: .GetGlobalAlerts
      tags:
        - ""
  /GroupV2/GetAvailableAvatars/:
    get:
      deprecated: false
      description: Returns a list of all available group avatars for the signed-in user.
      operationId: GroupV2.GetAvailableAvatars
      tags:
        - GroupV2
  /GroupV2/GetAvailableThemes/:
    get:
      deprecated: false
      description: Returns a list of all available group themes.
      operationId: GroupV2.GetAvailableThemes
      tags:
        - GroupV2
  "/GroupV2/GetUserClanInviteSetting/{mType}/":
    get:
      deprecated: false
      description: Gets the state of the user's clan invite preferences for a particular membership type - true if they wish to be invited to clans, false otherwise.
      operationId: GroupV2.GetUserClanInviteSetting
      security:
        - oauth2:
            - ReadUserData
      tags:
        - GroupV2
  "/GroupV2/Name/{groupName}/{groupType}/":
    get:
      deprecated: false
      description: Get information about a specific group with the given name and type.
      operationId: GroupV2.GetGroupByName
      tags:
        - GroupV2
  /GroupV2/NameV2/:
    post:
      deprecated: false
      description: Get information about a specific group with the given name and type. The POST version.
      operationId: GroupV2.GetGroupByNameV2
      tags:
        - GroupV2
  "/GroupV2/Recommended/{groupType}/{createDateRange}/":
    post:
      deprecated: false
      description: Gets groups recommended for you based on the groups to whom those you follow belong.
      operationId: GroupV2.GetRecommendedGroups
      security:
        - oauth2:
            - ReadGroups
      tags:
        - GroupV2
  "/GroupV2/Recover/{membershipType}/{membershipId}/{groupType}/":
    get:
      deprecated: false
      description: Allows a founder to manually recover a group they can see in game but not on bungie.net
      operationId: GroupV2.RecoverGroupForFounder
      tags:
        - GroupV2
  /GroupV2/Search/:
    post:
      deprecated: false
      description: Search for Groups.
      operationId: GroupV2.GroupSearch
      tags:
        - GroupV2
  "/GroupV2/User/Potential/{membershipType}/{membershipId}/{filter}/{groupType}/":
    get:
      deprecated: false
      description: Get information about the groups that a given member has applied to or been invited to.
      operationId: GroupV2.GetPotentialGroupsForMember
      tags:
        - GroupV2
  "/GroupV2/User/{membershipType}/{membershipId}/{filter}/{groupType}/":
    get:
      deprecated: false
      description: Get information about the groups that a given member has joined.
      operationId: GroupV2.GetGroupsForMember
      tags:
        - GroupV2
  "/GroupV2/{groupId}/":
    get:
      deprecated: false
      description: Get information about a specific group of the given ID.
      operationId: GroupV2.GetGroup
      tags:
        - GroupV2
  "/GroupV2/{groupId}/Admin/AbdicateFoundership/{membershipType}/{founderIdNew}/":
    post:
      deprecated: false
      description: An administrative method to allow the founder of a group or clan to give up their position to another admin permanently.
      operationId: GroupV2.AbdicateFoundership
      tags:
        - GroupV2
  "/GroupV2/{groupId}/AdminsAndFounder/":
    get:
      deprecated: false
      description: Get the list of members in a given group who are of admin level or higher.
      operationId: GroupV2.GetAdminsAndFounderOfGroup
      tags:
        - GroupV2
  "/GroupV2/{groupId}/Banned/":
    get:
      deprecated: false
      description: Get the list of banned members in a given group. Only accessible to group Admins and above. Not applicable to all groups. Check group features.
      operationId: GroupV2.GetBannedMembersOfGroup
      security:
        - oauth2:
            - AdminGroups
      tags:
        - GroupV2
  "/GroupV2/{groupId}/Edit/":
    post:
      deprecated: false
      description: Edit an existing group. You must have suitable permissions in the group to perform this operation. This latest revision will only edit the fields you pass in - pass null for properties you want to leave unaltered.
      operationId: GroupV2.EditGroup
      security:
        - oauth2:
            - AdminGroups
      tags:
        - GroupV2
  "/GroupV2/{groupId}/EditClanBanner/":
    post:
      deprecated: false
      description: Edit an existing group's clan banner. You must have suitable permissions in the group to perform this operation. All fields are required.
      operationId: GroupV2.EditClanBanner
      security:
        - oauth2:
            - AdminGroups
      tags:
        - GroupV2
  "/GroupV2/{groupId}/EditFounderOptions/":
    post:
      deprecated: false
      description: Edit group options only available to a founder. You must have suitable permissions in the group to perform this operation.
      operationId: GroupV2.EditFounderOptions
      security:
        - oauth2:
            - AdminGroups
      tags:
        - GroupV2
  "/GroupV2/{groupId}/Members/":
    get:
      deprecated: false
      description: Get the list of members in a given group.
      operationId: GroupV2.GetMembersOfGroup
      tags:
        - GroupV2
  "/GroupV2/{groupId}/Members/Approve/{membershipType}/{membershipId}/":
    post:
      deprecated: false
      description: Approve the given membershipId to join the group/clan as long as they have applied.
      operationId: GroupV2.ApprovePending
      security:
        - oauth2:
            - AdminGroups
      tags:
        - GroupV2
  "/GroupV2/{groupId}/Members/ApproveAll/":
    post:
      deprecated: false
      description: Approve all of the pending users for the given group.
      operationId: GroupV2.ApproveAllPending
      security:
        - oauth2:
            - AdminGroups
      tags:
        - GroupV2
  "/GroupV2/{groupId}/Members/ApproveList/":
    post:
      deprecated: false
      description: Approve all of the pending users for the given group.
      operationId: GroupV2.ApprovePendingForList
      security:
        - oauth2:
            - AdminGroups
      tags:
        - GroupV2
  "/GroupV2/{groupId}/Members/DenyAll/":
    post:
      deprecated: false
      description: Deny all of the pending users for the given group.
      operationId: GroupV2.DenyAllPending
      security:
        - oauth2:
            - AdminGroups
      tags:
        - GroupV2
  "/GroupV2/{groupId}/Members/DenyList/":
    post:
      deprecated: false
      description: Deny all of the pending users for the given group that match the passed-in .
      operationId: GroupV2.DenyPendingForList
      security:
        - oauth2:
            - AdminGroups
      tags:
        - GroupV2
  "/GroupV2/{groupId}/Members/IndividualInvite/{membershipType}/{membershipId}/":
    post:
      deprecated: false
      description: Invite a user to join this group.
      operationId: GroupV2.IndividualGroupInvite
      security:
        - oauth2:
            - AdminGroups
      tags:
        - GroupV2
  "/GroupV2/{groupId}/Members/IndividualInviteCancel/{membershipType}/{membershipId}/":
    post:
      deprecated: false
      description: Cancels a pending invitation to join a group.
      operationId: GroupV2.IndividualGroupInviteCancel
      security:
        - oauth2:
            - AdminGroups
      tags:
        - GroupV2
  "/GroupV2/{groupId}/Members/InvitedIndividuals/":
    get:
      deprecated: false
      description: Get the list of users who have been invited into the group.
      operationId: GroupV2.GetInvitedIndividuals
      security:
        - oauth2:
            - AdminGroups
      tags:
        - GroupV2
  "/GroupV2/{groupId}/Members/Pending/":
    get:
      deprecated: false
      description: Get the list of users who are awaiting a decision on their application to join a given group. Modified to include application info.
      operationId: GroupV2.GetPendingMemberships
      security:
        - oauth2:
            - AdminGroups
      tags:
        - GroupV2
  "/GroupV2/{groupId}/Members/{membershipType}/{membershipId}/Ban/":
    post:
      deprecated: false
      description: Bans the requested member from the requested group for the specified period of time.
      operationId: GroupV2.BanMember
      security:
        - oauth2:
            - AdminGroups
      tags:
        - GroupV2
  "/GroupV2/{groupId}/Members/{membershipType}/{membershipId}/Kick/":
    post:
      deprecated: false
      description: Kick a member from the given group, forcing them to reapply if they wish to re-join the group. You must have suitable permissions in the group to perform this operation.
      operationId: GroupV2.KickMember
      security:
        - oauth2:
            - AdminGroups
      tags:
        - GroupV2
  "/GroupV2/{groupId}/Members/{membershipType}/{membershipId}/SetMembershipType/{memberType}/":
    post:
      deprecated: false
      description: Edit the membership type of a given member. You must have suitable permissions in the group to perform this operation.
      operationId: GroupV2.EditGroupMembership
      security:
        - oauth2:
            - AdminGroups
      tags:
        - GroupV2
  "/GroupV2/{groupId}/Members/{membershipType}/{membershipId}/Unban/":
    post:
      deprecated: false
      description: Unbans the requested member, allowing them to re-apply for membership.
      operationId: GroupV2.UnbanMember
      security:
        - oauth2:
            - AdminGroups
      tags:
        - GroupV2
  "/GroupV2/{groupId}/OptionalConversations/":
    get:
      deprecated: false
      description: Gets a list of available optional conversation channels and their settings.
      operationId: GroupV2.GetGroupOptionalConversations
      tags:
        - GroupV2
  "/GroupV2/{groupId}/OptionalConversations/Add/":
    post:
      deprecated: false
      description: Add a new optional conversation/chat channel. Requires admin permissions to the group.
      operationId: GroupV2.AddOptionalConversation
      security:
        - oauth2:
            - AdminGroups
      tags:
        - GroupV2
  "/GroupV2/{groupId}/OptionalConversations/Edit/{conversationId}/":
    post:
      deprecated: false
      description: Edit the settings of an optional conversation/chat channel. Requires admin permissions to the group.
      operationId: GroupV2.EditOptionalConversation
      security:
        - oauth2:
            - AdminGroups
      tags:
        - GroupV2
  /Settings/:
    get:
      deprecated: false
      description: Get the common settings used by the Bungie.Net environment.
      operationId: .GetCommonSettings
      tags:
        - ""
  /Social/Friends/:
    get:
      deprecated: false
      description: Returns your Bungie Friend list
      operationId: Social.GetFriendList
      security:
        - oauth2:
            - ReadUserData
      tags:
        - Social
  "/Social/Friends/Add/{membershipId}/":
    post:
      deprecated: false
      description: Requests a friend relationship with the target user. Any of the target user's linked membership ids are valid inputs.
      operationId: Social.IssueFriendRequest
      security:
        - oauth2:
            - BnetWrite
      tags:
        - Social
  "/Social/Friends/Remove/{membershipId}/":
    post:
      deprecated: false
      description: Remove a friend relationship with the target user. The user must be on your friend list, though no error will occur if they are not.
      operationId: Social.RemoveFriend
      security:
        - oauth2:
            - BnetWrite
      tags:
        - Social
  /Social/Friends/Requests/:
    get:
      deprecated: false
      description: Returns your friend request queue.
      operationId: Social.GetFriendRequestList
      security:
        - oauth2:
            - ReadUserData
      tags:
        - Social
  "/Social/Friends/Requests/Accept/{membershipId}/":
    post:
      deprecated: false
      description: Accepts a friend relationship with the target user. The user must be on your incoming friend request list, though no error will occur if they are not.
      operationId: Social.AcceptFriendRequest
      security:
        - oauth2:
            - BnetWrite
      tags:
        - Social
  "/Social/Friends/Requests/Decline/{membershipId}/":
    post:
      deprecated: false
      description: Declines a friend relationship with the target user. The user must be on your incoming friend request list, though no error will occur if they are not.
      operationId: Social.DeclineFriendRequest
      security:
        - oauth2:
            - BnetWrite
      tags:
        - Social
  "/Social/Friends/Requests/Remove/{membershipId}/":
    post:
      deprecated: false
      description: Remove a friend relationship with the target user. The user must be on your outgoing request friend list, though no error will occur if they are not.
      operationId: Social.RemoveFriendRequest
      security:
        - oauth2:
            - BnetWrite
      tags:
        - Social
  "/Social/PlatformFriends/{friendPlatform}/{page}/":
    get:
      deprecated: false
      description: Gets the platform friend of the requested type, with additional information if they have Bungie accounts. Must have a recent login session with said platform.
      operationId: Social.GetPlatformFriendList
      tags:
        - Social
  "/Tokens/Partner/ApplyMissingOffers/{partnerApplicationId}/{targetBnetMembershipId}/":
    post:
      deprecated: false
      description: Apply a partner offer to the targeted user. This endpoint does not claim a new offer, but any already claimed offers will be applied to the game if not already.
      operationId: Tokens.ApplyMissingPartnerOffersWithoutClaim
      security:
        - oauth2:
            - PartnerOfferGrant
      tags:
        - Tokens
  /Tokens/Partner/ClaimOffer/:
    post:
      deprecated: false
      description: Claim a partner offer as the authenticated user.
      operationId: Tokens.ClaimPartnerOffer
      security:
        - oauth2:
            - PartnerOfferGrant
      tags:
        - Tokens
  /Tokens/Partner/ForceDropsRepair/:
    post:
      deprecated: false
      description: Twitch Drops self-repair function - scans twitch for drops not marked as fulfilled and resyncs them.
      operationId: Tokens.ForceDropsRepair
      security:
        - oauth2:
            - PartnerOfferGrant
      tags:
        - Tokens
  "/Tokens/Partner/History/{partnerApplicationId}/{targetBnetMembershipId}/":
    get:
      deprecated: false
      description: Returns the partner sku and offer history of the targeted user. Elevated permissions are required to see users that are not yourself.
      operationId: Tokens.GetPartnerOfferSkuHistory
      security:
        - oauth2:
            - PartnerOfferGrant
      tags:
        - Tokens
  "/Tokens/Partner/History/{targetBnetMembershipId}/Application/{partnerApplicationId}/":
    get:
      deprecated: false
      description: Returns the partner rewards history of the targeted user, both partner offers and Twitch drops.
      operationId: Tokens.GetPartnerRewardHistory
      security:
        - oauth2:
            - PartnerOfferGrant
      tags:
        - Tokens
  /Tokens/Rewards/BungieRewards/:
    get:
      deprecated: false
      description: Returns a list of the current bungie rewards
      operationId: Tokens.GetBungieRewardsList
      tags:
        - Tokens
  "/Tokens/Rewards/GetRewardsForPlatformUser/{membershipId}/{membershipType}/":
    get:
      deprecated: false
      description: Returns the bungie rewards for the targeted user when a platform membership Id and Type are used.
      operationId: Tokens.GetBungieRewardsForPlatformUser
      security:
        - oauth2:
            - ReadAndApplyTokens
      tags:
        - Tokens
  "/Tokens/Rewards/GetRewardsForUser/{membershipId}/":
    get:
      deprecated: false
      description: Returns the bungie rewards for the targeted user.
      operationId: Tokens.GetBungieRewardsForUser
      security:
        - oauth2:
            - ReadAndApplyTokens
      tags:
        - Tokens
  /Trending/Categories/:
    get:
      deprecated: false
      description: Returns trending items for Bungie.net, collapsed into the first page of items per category. For pagination within a category, call GetTrendingCategory.
      operationId: Trending.GetTrendingCategories
      tags:
        - Trending
  "/Trending/Categories/{categoryId}/{pageNumber}/":
    get:
      deprecated: false
      description: Returns paginated lists of trending items for a category.
      operationId: Trending.GetTrendingCategory
      tags:
        - Trending
  "/Trending/Details/{trendingEntryType}/{identifier}/":
    get:
      deprecated: false
      description: "Returns the detailed results for a specific trending entry. Note that trending entries are uniquely identified by a combination of *both* the TrendingEntryType *and* the identifier: the identifier alone is not guaranteed to be globally unique."
      operationId: Trending.GetTrendingEntryDetail
      tags:
        - Trending
  /User/GetAvailableThemes/:
    get:
      deprecated: false
      description: Returns a list of all available user themes.
      operationId: User.GetAvailableThemes
      tags:
        - User
  "/User/GetBungieNetUserById/{id}/":
    get:
      deprecated: false
      description: Loads a bungienet user by membership id.
      operationId: User.GetBungieNetUserById
      tags:
        - User
  "/User/GetCredentialTypesForTargetAccount/{membershipId}/":
    get:
      deprecated: false
      description: Returns a list of credential types attached to the requested account
      operationId: User.GetCredentialTypesForTargetAccount
      tags:
        - User
  "/User/GetMembershipFromHardLinkedCredential/{crType}/{credential}/":
    get:
      deprecated: false
      description: Gets any hard linked membership given a credential. Only works for credentials that are public (just SteamID64 right now). Cross Save aware.
      operationId: User.GetMembershipFromHardLinkedCredential
      tags:
        - User
  "/User/GetMembershipsById/{membershipId}/{membershipType}/":
    get:
      deprecated: false
      description: Returns a list of accounts associated with the supplied membership ID and membership type. This will include all linked accounts (even when hidden) if supplied credentials permit it.
      operationId: User.GetMembershipDataById
      tags:
        - User
  /User/GetMembershipsForCurrentUser/:
    get:
      deprecated: false
      description: Returns a list of accounts associated with signed in user. This is useful for OAuth implementations that do not give you access to the token response.
      operationId: User.GetMembershipDataForCurrentUser
      security:
        - oauth2:
            - ReadBasicUserProfile
      tags:
        - User
  "/User/GetSanitizedPlatformDisplayNames/{membershipId}/":
    get:
      deprecated: false
      description: Gets a list of all display names linked to this membership id but sanitized (profanity filtered). Obeys all visibility rules of calling user and is heavily cached.
      operationId: User.GetSanitizedPlatformDisplayNames
      tags:
        - User
  "/User/Search/GlobalName/{page}/":
    post:
      deprecated: false
      description: Given the prefix of a global display name, returns all users who share that name.
      operationId: User.SearchByGlobalNamePost
      tags:
        - User
  "/User/Search/Prefix/{displayNamePrefix}/{page}/":
    get:
      deprecated: false
      description: "[OBSOLETE] Do not use this to search users, use SearchByGlobalNamePost instead."
      operationId: User.SearchByGlobalNamePrefix
      tags:
        - User
  /UserSystemOverrides/:
    get:
      deprecated: false
      description: Get the user-specific system overrides that should be respected alongside common systems.
      operationId: .GetUserSystemOverrides
      tags:
        - ""
components:
  securitySchemes:
    apiKey:
      description: Every request requires an API key.  To get an API key, register a new application at https://www.bungie.net/en/Application.
      in: header
      name: X-API-Key
      type: apiKey
    oauth2:
      description: For requests that require Authentication, you will need to have your users authenticate via our OAuth mechanisms.  See https://github.com/Bungie-net/api/wiki/OAuth-Documentation for more details.
      flows:
        authorizationCode:
          authorizationUrl: https://www.bungie.net/en/OAuth/Authorize
          scopes:
            AdminGroups: "Administer Group/Clan Forums, Wall, and Members for groups and clans that the \r

              user is a founder or an administrator."
            AdvancedWriteActions: Can perform actions that will result in a prompt to the user via the Destiny app.
            BnetWrite: "Create new groups, clans, and forum posts, along with other actions that are reserved for Bungie.net\r

              elevated scope: not meant to be used by third party applications."
            DestinyUnlockValueQuery: Allows an app to query sensitive information like unlock flags and values not available through normal methods.
            EditUserData: Edit user data such as preferred language, status, motto, avatar selection and theme.
            MoveEquipDestinyItems: Move or equip Destiny items
            PartnerOfferGrant: Can use the partner offer api to claim rewards defined for a partner
            ReadAndApplyTokens: Read offer history and claim and apply tokens for the user.
            ReadBasicUserProfile: Read basic user profile information such as the user's handle, avatar icon, etc.
            ReadDestinyInventoryAndVault: "Read Destiny 1 Inventory and Vault contents.\r

              For Destiny 2, this scope is needed to read anything regarded as private. This is the only scope a\r

              Destiny 2 app needs for read operations against Destiny 2 data such as inventory, vault, currency,\r

              vendors, milestones, progression, etc."
            ReadDestinyVendorsAndAdvisors: Access vendor and advisor data specific to a user. OBSOLETE. This scope is only used on the Destiny 1 API.
            ReadGroups: "Read Group/Clan Forums, Wall, and Members for groups and clans that the \r

              user has joined."
            ReadUserData: "Read user data such as who they are web notifications, \r

              clan/group memberships, recent activity, muted users."
            UserPiiRead: Allows an app to query sensitive user PII, most notably email information.
            WriteGroups: "Write Group/Clan Forums, Wall, and Members for groups and clans that the \r

              user has joined."
          tokenUrl: https://www.bungie.net/Platform/App/OAuth/token/
      type: oauth2
