from .batchexecutestatement import *
from .batchgetitem import *
from .batchwriteitem import *
from .createbackup import *
from .createglobaltable import *
from .createtable import *
from .deletebackup import *
from .deleteitem import *
from .deletetable import *
from .describebackup import *
from .describecontinuousbackups import *
from .describecontributorinsights import *
from .describeendpoints import *
from .describeexport import *
from .describeglobaltable import *
from .describeglobaltablesettings import *
from .describekinesisstreamingdestination import *
from .describelimits import *
from .describetable import *
from .describetablereplicaautoscaling import *
from .describetimetolive import *
from .disablekinesisstreamingdestination import *
from .enablekinesisstreamingdestination import *
from .executestatement import *
from .executetransaction import *
from .exporttabletopointintime import *
from .getitem import *
from .listbackups import *
from .listcontributorinsights import *
from .listexports import *
from .listglobaltables import *
from .listtables import *
from .listtagsofresource import *
from .putitem import *
from .query import *
from .restoretablefrombackup import *
from .restoretabletopointintime import *
from .scan import *
from .tagresource import *
from .transactgetitems import *
from .transactwriteitems import *
from .untagresource import *
from .updatecontinuousbackups import *
from .updatecontributorinsights import *
from .updateglobaltable import *
from .updateglobaltablesettings import *
from .updateitem import *
from .updatetable import *
from .updatetablereplicaautoscaling import *
from .updatetimetolive import *
