swagger: '2.0'
schemes:
  - https
host: api.netatmo.net
basePath: /api
info:
  contact:
    email: contact-api@netatmo.com
    name: Netatmo
  description: '<h3>Welcome to the Netatmo swagger on-line documentation !</h3>This site is a complement to the official <a href="https://dev.netatmo.com/">Netatmo developper documentation</a> using swagger to bring interactivity and easy testing of requests with the "try it" button (authenticate with the authorization code 0Auth2 flow by clicking the authenticate button in the methods). You can find the source code for this site can be found in the project <a href="https://github.com/cbornet/ne[...]'
  license:
    name: 'Netatmo : Terms of Service'
    url: 'https://dev.netatmo.com/dev/resources/legal/introduction'
  termsOfService: 'https://dev.netatmo.com/dev/resources/legal/introduction'
  title: Netatmo
  version: 1.1.0
  x-apiClientRegistration:
    url: 'https://dev.netatmo.com/dev/createanapp'
  x-apisguru-categories:
    - iot
  x-logo:
    url: 'https://dev.netatmo.com/images/common/netatmo-connect-horiz.png'
  x-origin:
    - format: swagger
      url: 'https://raw.githubusercontent.com/cbornet/netatmo-swagger-decl/master/swagger.json'
      version: '2.0'
  x-providerName: netatmo.net
  x-unofficialSpec: true
securityDefinitions:
  code_oauth:
    authorizationUrl: 'https://api.netatmo.net/oauth2/authorize'
    flow: accessCode
    scopes:
      access_camera: Access welcome camera
      read_camera: Read welcome camera's data
      read_station: Read weather station's data
      read_thermostat: Read thermostat's data
      write_camera: Write welcome camera's data
      write_thermostat: Configure the thermostat
    tokenUrl: 'https://api.netatmo.net/oauth2/token'
    type: oauth2
  password_oauth:
    flow: password
    scopes: {}
    tokenUrl: 'https://api.netatmo.net/oauth2/token'
    type: oauth2
tags:
  - description: Weather station specific methods
    name: station
  - description: Thermostat specific methods
    name: thermostat
  - description: Welcome specific methods
    name: welcome
  - description: Public stations specific methods
    name: public
  - description: Partner API specific methods
    name: partner
paths:
  /addwebhook:
    get:
      deprecated: false
      description: |
        Links a callback url to a user.
      operationId: addwebhook
      security:
        - code_oauth: []
        - password_oauth: []
      tags:
        - welcome
  /createnewschedule:
    post:
      description: The method createnewschedule creates a new schedule stored in the backup list.
      operationId: createnewschedule
      security:
        - code_oauth:
            - write_thermostat
        - password_oauth: []
      tags:
        - thermostat
  /devicelist:
    get:
      deprecated: true
      description: |
        The method devicelist returns the list of devices owned by the user, and their modules.
        A device is identified by its _id (which is its mac address) and each device may have one, several or no modules, also identified by an _id.
      operationId: devicelist
      security:
        - code_oauth:
            - read_thermostat
            - read_station
        - password_oauth: []
      tags:
        - station
        - thermostat
        - partner
  /dropwebhook:
    get:
      deprecated: false
      description: |
        Dissociates a webhook from a user.
      operationId: dropwebhook
      security:
        - code_oauth: []
        - password_oauth: []
      tags:
        - welcome
  /getcamerapicture:
    get:
      deprecated: false
      description: |
        Returns the snapshot associated to an event.
      operationId: getcamerapicture
      security:
        - code_oauth: []
        - password_oauth: []
      tags:
        - welcome
  /geteventsuntil:
    get:
      deprecated: false
      description: |
        Returns the snapshot associated to an event.
      operationId: geteventsuntil
      security:
        - code_oauth:
            - access_camera
            - read_camera
        - password_oauth: []
      tags:
        - welcome
  /gethomedata:
    get:
      deprecated: false
      description: |
        Returns information about users homes and cameras.
      operationId: gethomedata
      security:
        - code_oauth:
            - access_camera
            - read_camera
        - password_oauth: []
      tags:
        - welcome
  /getlasteventof:
    get:
      deprecated: false
      description: |
        Returns most recent events.
      operationId: getlasteventof
      security:
        - code_oauth:
            - access_camera
            - read_camera
        - password_oauth: []
      tags:
        - welcome
  /getmeasure:
    get:
      description: |
        The method getmeasure returns the measurements of a device or a module.
      operationId: getmeasure
      security:
        - code_oauth:
            - read_thermostat
            - read_station
        - password_oauth: []
      tags:
        - station
        - thermostat
        - partner
        - public
  /getnextevents:
    get:
      deprecated: false
      description: |
        Returns previous events.
      operationId: getnextevents
      security:
        - code_oauth:
            - access_camera
            - read_camera
        - password_oauth: []
      tags:
        - welcome
  /getstationsdata:
    get:
      description: The method getstationsdata Returns data from a user Weather Stations (measures and device specific data).
      operationId: getstationsdata
      tags:
        - station
  /getthermostatsdata:
    get:
      description: The method getthermostatsdata returns information about user's thermostats such as their last measurements.
      operationId: getthermostatsdata
      tags:
        - thermostat
  /getthermstate:
    get:
      deprecated: true
      description: 'The method getthermstate returns the last Thermostat measurements, its current weekly schedule, and, if present, its current manual temperature setpoint.'
      operationId: getthermstate
      security:
        - code_oauth:
            - read_thermostat
        - password_oauth: []
      tags:
        - thermostat
        - partner
  /getuser:
    get:
      deprecated: true
      description: |
        The method getuser returns information about a user such as prefered language, prefered units, and list of devices.
      operationId: getuser
      security:
        - code_oauth: []
        - password_oauth: []
      tags:
        - station
        - thermostat
  /partnerdevices:
    get:
      description: The method partnerdevices returns the list of device_id to which your partner application has access to.
      operationId: partnerdevices
      security:
        - code_oauth: []
        - password_oauth: []
      tags:
        - partner
  /setpersonsaway:
    get:
      deprecated: false
      description: |
        Sets a person as 'Away' or the Home as 'Empty'. The event will be added to the user’s timeline.
      operationId: setpersonsaway
      security:
        - code_oauth:
            - write_camera
        - password_oauth: []
      tags:
        - welcome
  /setthermpoint:
    post:
      description: The method setthermpoint changes the Thermostat manual temperature setpoint.
      operationId: setthermpoint
      security:
        - code_oauth:
            - write_thermostat
        - password_oauth: []
      tags:
        - thermostat
  /switchschedule:
    post:
      description: The method switchschedule switches the Thermostat's schedule to another existing schedule.
      operationId: switchschedule
      security:
        - code_oauth:
            - write_thermostat
        - password_oauth: []
      tags:
        - thermostat
  /syncschedule:
    post:
      description: The method syncschedule changes the Thermostat weekly schedule.
      operationId: syncschedule
      security:
        - code_oauth:
            - write_thermostat
        - password_oauth: []
      tags:
        - thermostat