from .tagmanager_accounts_containers_create import *
from .tagmanager_accounts_containers_delete import *
from .tagmanager_accounts_containers_environments_create import *
from .tagmanager_accounts_containers_environments_delete import *
from .tagmanager_accounts_containers_environments_get import *
from .tagmanager_accounts_containers_environments_list import *
from .tagmanager_accounts_containers_environments_update import *
from .tagmanager_accounts_containers_folders_create import *
from .tagmanager_accounts_containers_folders_delete import *
from .tagmanager_accounts_containers_folders_entities_list import *
from .tagmanager_accounts_containers_folders_get import *
from .tagmanager_accounts_containers_folders_list import *
from .tagmanager_accounts_containers_folders_update import *
from .tagmanager_accounts_containers_get import *
from .tagmanager_accounts_containers_list import *
from .tagmanager_accounts_containers_move_folders_update import *
from .tagmanager_accounts_containers_reauthorize_environments_update import *
from .tagmanager_accounts_containers_tags_create import *
from .tagmanager_accounts_containers_tags_delete import *
from .tagmanager_accounts_containers_tags_get import *
from .tagmanager_accounts_containers_tags_list import *
from .tagmanager_accounts_containers_tags_update import *
from .tagmanager_accounts_containers_triggers_create import *
from .tagmanager_accounts_containers_triggers_delete import *
from .tagmanager_accounts_containers_triggers_get import *
from .tagmanager_accounts_containers_triggers_list import *
from .tagmanager_accounts_containers_triggers_update import *
from .tagmanager_accounts_containers_update import *
from .tagmanager_accounts_containers_variables_create import *
from .tagmanager_accounts_containers_variables_delete import *
from .tagmanager_accounts_containers_variables_get import *
from .tagmanager_accounts_containers_variables_list import *
from .tagmanager_accounts_containers_variables_update import *
from .tagmanager_accounts_containers_versions_create import *
from .tagmanager_accounts_containers_versions_delete import *
from .tagmanager_accounts_containers_versions_get import *
from .tagmanager_accounts_containers_versions_list import *
from .tagmanager_accounts_containers_versions_publish import *
from .tagmanager_accounts_containers_versions_restore import *
from .tagmanager_accounts_containers_versions_undelete import *
from .tagmanager_accounts_containers_versions_update import *
from .tagmanager_accounts_get import *
from .tagmanager_accounts_list import *
from .tagmanager_accounts_permissions_create import *
from .tagmanager_accounts_permissions_delete import *
from .tagmanager_accounts_permissions_get import *
from .tagmanager_accounts_permissions_list import *
from .tagmanager_accounts_permissions_update import *
from .tagmanager_accounts_update import *
