{
  "openapi": "3.0.1",
  "servers": [
    {
      "url": "https://api.hubapi.com/"
    }
  ],
  "info": {
    "description": "These APIs allow you to interact with HubSpot's Marketing Events Extension. It allows you to:\n* Create, Read or update Marketing Event information in HubSpot\n* Specify whether a HubSpot contact has registered, attended or cancelled a registration to a Marketing Event.\n* Specify a URL that can be called to get the details of a Marketing Event.\n",
    "title": "Marketing Events Extension",
    "version": "v3",
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_developers.hubspot.com_hubfs_assets_hubspot.com_buzz_HubSpotOpenGraph.png"
    },
    "x-origin": [
      {
        "format": "openapi",
        "url": "https://api.hubspot.com/api-catalog-public/v1/apis/marketing/v3/marketing-events-beta",
        "version": "3.0"
      }
    ],
    "x-providerName": "hubapi.com",
    "x-serviceName": "marketing"
  },
  "tags": [
    {
      "description": "Endpoints that allow you to search for Marketing Events in HubSpot.",
      "name": "Search"
    },
    {
      "description": "Operations to mark HubSpot contacts as registered, attended or cancelled a registration to a Marketing Event.",
      "name": "Attendance Subscriber State Changes"
    },
    {
      "name": "Marketing_Events_External"
    },
    {
      "name": "Settings_External"
    }
  ],
  "paths": {
    "/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create": {
      "post": {
        "description": "Record a subscription state between multiple HubSpot contacts and a marketing event, using HubSpot contact ids.",
        "operationId": "post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create_create",
        "security": [
          {
            "private_apps_legacy": []
          },
          {
            "oauth2_legacy": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "summary": "Record",
        "tags": [
          "Attendance Subscriber State Changes"
        ]
      }
    },
    "/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create": {
      "post": {
        "description": "Record a subscription state between multiple HubSpot contacts and a marketing event, using contact email addresses. If contact is not present it will be automatically created. If you set params ",
        "operationId": "post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create_createByEmail",
        "security": [
          {
            "private_apps_legacy": []
          },
          {
            "oauth2_legacy": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "summary": "Record",
        "tags": [
          "Attendance Subscriber State Changes"
        ]
      }
    },
    "/marketing/v3/marketing-events/events": {
      "post": {
        "operationId": "post-/marketing/v3/marketing-events/events_create",
        "security": [
          {
            "private_apps_legacy": []
          },
          {
            "oauth2_legacy": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "tags": [
          "Marketing_Events_External"
        ]
      }
    },
    "/marketing/v3/marketing-events/events/delete": {
      "post": {
        "operationId": "post-/marketing/v3/marketing-events/events/delete_archiveBatch",
        "security": [
          {
            "private_apps_legacy": []
          },
          {
            "oauth2_legacy": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "tags": [
          "Marketing_Events_External"
        ]
      }
    },
    "/marketing/v3/marketing-events/events/search": {
      "get": {
        "description": "Search for marketing events that have an event id that starts with the query string",
        "operationId": "get-/marketing/v3/marketing-events/events/search_doSearch",
        "security": [
          {
            "oauth2_legacy": [
              "crm.objects.marketing_events.read"
            ]
          },
          {
            "private_apps_legacy": []
          }
        ],
        "summary": "Search for marketing events",
        "tags": [
          "Search"
        ]
      }
    },
    "/marketing/v3/marketing-events/events/upsert": {
      "post": {
        "operationId": "post-/marketing/v3/marketing-events/events/upsert_doUpsert",
        "security": [
          {
            "private_apps_legacy": []
          },
          {
            "oauth2_legacy": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "tags": [
          "Marketing_Events_External"
        ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}": {
      "delete": {
        "operationId": "delete-/marketing/v3/marketing-events/events/{externalEventId}_archive",
        "security": [
          {
            "private_apps_legacy": []
          },
          {
            "oauth2_legacy": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "tags": [
          "Marketing_Events_External"
        ]
      },
      "get": {
        "operationId": "get-/marketing/v3/marketing-events/events/{externalEventId}_getById",
        "security": [
          {
            "oauth2_legacy": [
              "crm.objects.marketing_events.read"
            ]
          },
          {
            "private_apps_legacy": []
          }
        ],
        "tags": [
          "Marketing_Events_External"
        ]
      },
      "patch": {
        "operationId": "patch-/marketing/v3/marketing-events/events/{externalEventId}_update",
        "security": [
          {
            "private_apps_legacy": []
          },
          {
            "oauth2_legacy": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "tags": [
          "Marketing_Events_External"
        ]
      },
      "put": {
        "operationId": "put-/marketing/v3/marketing-events/events/{externalEventId}_replace",
        "security": [
          {
            "private_apps_legacy": []
          },
          {
            "oauth2_legacy": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "tags": [
          "Marketing_Events_External"
        ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/cancel": {
      "post": {
        "operationId": "post-/marketing/v3/marketing-events/events/{externalEventId}/cancel_doCancel",
        "security": [
          {
            "private_apps_legacy": []
          },
          {
            "oauth2_legacy": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "tags": [
          "Marketing_Events_External"
        ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/complete": {
      "post": {
        "operationId": "post-/marketing/v3/marketing-events/events/{externalEventId}/complete_complete",
        "security": [
          {
            "private_apps_legacy": []
          },
          {
            "oauth2_legacy": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "tags": [
          "Marketing_Events_External"
        ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert": {
      "post": {
        "operationId": "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert_doEmailUpsertById",
        "security": [
          {
            "private_apps_legacy": []
          },
          {
            "oauth2_legacy": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "tags": [
          "Marketing_Events_External"
        ]
      }
    },
    "/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert": {
      "post": {
        "operationId": "post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert_doUpsertById",
        "security": [
          {
            "private_apps_legacy": []
          },
          {
            "oauth2_legacy": [
              "crm.objects.marketing_events.write"
            ]
          }
        ],
        "tags": [
          "Marketing_Events_External"
        ]
      }
    },
    "/marketing/v3/marketing-events/{appId}/settings": {
      "get": {
        "operationId": "get-/marketing/v3/marketing-events/{appId}/settings_getAll",
        "security": [
          {
            "hapikey": []
          },
          {
            "developer_hapikey": []
          }
        ],
        "tags": [
          "Settings_External"
        ]
      },
      "post": {
        "operationId": "post-/marketing/v3/marketing-events/{appId}/settings_create",
        "security": [
          {
            "hapikey": []
          },
          {
            "developer_hapikey": []
          }
        ],
        "tags": [
          "Settings_External"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "developer_hapikey": {
        "in": "query",
        "name": "hapikey",
        "type": "apiKey"
      },
      "hapikey": {
        "in": "query",
        "name": "hapikey",
        "type": "apiKey"
      },
      "oauth2_legacy": {
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
            "scopes": {
              "crm.objects.marketing_events.read": "Read marketing events",
              "crm.objects.marketing_events.write": "Write marketing events"
            },
            "tokenUrl": "https://api.hubapi.com/oauth/v1/token"
          }
        },
        "type": "oauth2"
      },
      "private_apps_legacy": {
        "in": "header",
        "name": "private-app-legacy",
        "type": "apiKey"
      }
    }
  },
  "x-hubspot-available-client-libraries": [
    "PHP",
    "Node",
    "Python",
    "Ruby"
  ]
}