# coding: utf-8

"""
    Microsoft Storage Sync

    Microsoft Storage Sync Service API

    The version of the OpenAPI document: 2019-06-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.pre_restore_request import PreRestoreRequest

class TestPreRestoreRequest(unittest.TestCase):
    """PreRestoreRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PreRestoreRequest:
        """Test PreRestoreRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PreRestoreRequest`
        """
        model = PreRestoreRequest()
        if include_optional:
            return PreRestoreRequest(
                azure_file_share_uri = '',
                backup_metadata_property_bag = '',
                partition = '',
                pause_wait_for_sync_drain_time_period_in_seconds = 56,
                replica_group = '',
                request_id = '',
                restore_file_spec = [
                    openapi_client.models.restore_file_spec.RestoreFileSpec(
                        isdir = True, 
                        path = '', )
                    ],
                source_azure_file_share_uri = '',
                status = ''
            )
        else:
            return PreRestoreRequest(
        )
        """

    def testPreRestoreRequest(self):
        """Test PreRestoreRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
