package shared

type DescribeDominantLanguageDetectionJobResponse struct {
	DominantLanguageDetectionJobProperties *DominantLanguageDetectionJobProperties `json:"DominantLanguageDetectionJobProperties,omitempty"`
}
