openapi: 3.0.1
servers:
  - description: Production
    url: https://products.izettle.com
    variables: {}
info:
  description: The Product Library API is used for managing merchant's product information and product images.
  title: Product Library API
  version: 1.0.0
  x-apisguru-categories:
    - ecommerce
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_cdn.izettle.com_favicons_favicon-32x32.png
  x-origin:
    - format: openapi
      url: https://products.izettle.com/openapi.json
      version: "3.0"
  x-providerName: izettle.com
  x-serviceName: products
paths:
  "/organizations/{organizationUuid}/categories/v2":
    get:
      operationId: getProductTypes
      security:
        - ZettleOauth:
            - READ:PRODUCT
      summary: Retrieve all categories
      tags:
        - categories
    post:
      operationId: createCategories
      security:
        - ZettleOauth:
            - WRITE:PRODUCT
      summary: Create a new category
      tags:
        - categories
  "/organizations/{organizationUuid}/categories/v2/{categoryUuid}":
    delete:
      operationId: deleteCategory
      security:
        - ZettleOauth:
            - WRITE:PRODUCT
      summary: Delete a category
      tags:
        - categories
    patch:
      operationId: renameCategory
      security:
        - ZettleOauth:
            - WRITE:PRODUCT
      summary: Rename a category
      tags:
        - categories
  "/organizations/{organizationUuid}/discounts":
    get:
      operationId: getAllDiscounts
      security:
        - ZettleOauth:
            - READ:PRODUCT
      summary: Retrieve all discounts
      tags:
        - discounts
    post:
      description: Creates a single discount entity. The location of the newly created discount will be available in the successful response as a HttpHeaders.LOCATION header
      operationId: createDiscount
      security:
        - ZettleOauth:
            - WRITE:PRODUCT
      summary: Create a discount
      tags:
        - discounts
  "/organizations/{organizationUuid}/discounts/{discountUuid}":
    delete:
      operationId: deleteDiscount
      security:
        - ZettleOauth:
            - WRITE:PRODUCT
      summary: "Delete a single discount "
      tags:
        - discounts
    get:
      description: "Get the full discount with the provided UUID. The method supports conditional GET through providing a HttpHeaders.IF_NONE_MATCH header. If the conditional prerequisite is fullfilled, the full discount is returned: otherwise a 304 not modified will be returned with an empty body."
      operationId: getDiscount
      security:
        - ZettleOauth:
            - READ:PRODUCT
      summary: Retrieve a single discount
      tags:
        - discounts
    put:
      description: "Updates a discount entity using JSON merge patch (https://tools.ietf.org/html/rfc7386). This means that only included fields will be changed: null values removes the field on the target entity, and other values updates the field. Conditional updates are supported through the HttpHeaders.IF_MATCH header. If the conditional prerequisite is fullfilled, the discount is updated: otherwise a 412 precondition failed will be returned with an empty body."
      operationId: updateDiscount
      security:
        - ZettleOauth:
            - WRITE:PRODUCT
      summary: Update a single discount
      tags:
        - discounts
  "/organizations/{organizationUuid}/images":
    get:
      description: Retrieves all library items images used by the organization, sorted by updated date
      operationId: getAllImageUrls
      security:
        - ZettleOauth:
            - READ:PRODUCT
      summary: Retrieve all library item images
      tags:
        - images
  "/organizations/{organizationUuid}/import/status":
    get:
      operationId: getLatestImportStatus
      security:
        - ZettleOauth:
            - READ:PRODUCT
      summary: Get status for latest import
      tags:
        - import
  "/organizations/{organizationUuid}/import/status/{importUuid}":
    get:
      operationId: getStatusByUuid
      security:
        - ZettleOauth:
            - READ:PRODUCT
      summary: Get status for an import
      tags:
        - import
  "/organizations/{organizationUuid}/import/v2":
    post:
      operationId: importLibraryV2
      security:
        - ZettleOauth:
            - WRITE:PRODUCT
      summary: Import library items
      tags:
        - import
  "/organizations/{organizationUuid}/library":
    get:
      description: |
        Will return the entire library for the authenticated user. If size of the library exceeds server preferences (normally 500) or the value of the optional limit parameter, the result will be paginated. Paginated responses return a Link header, indicating the next URI to fetch. The resulting header value will look something like:

        <https://products.izettle.com/organizations/self/library?limit=X&offset=Y>; rel="next"

        where limit is number of items in response, and offset is the current position in pagination. The rel-part in the header is the links relation to the data previously recieved. The idea is that as long as this header is present there are still items remaining to be fetched. When either the header is not present or it's value doesn't contain any "next" value, all items have been sent to the client.

        Note: The client should NOT try to extract query parameters from the URI, but rather use it as-is for the next request. Also, clients should be perpared that one Link header might contain multiple other IRIs that are not "next" (there will never be more than one "next" though). See more at:

            IETF: https://tools.ietf.org/html/rfc5988
            GitHub: https://developer.github.com/guides/traversing-with-pagination/

        If eventLogUuid is provided, the response will only include events affecting the library since that event. Such responses are normally quite small and would be a preferred method for most fat clients after retrieving the initial full library.
      operationId: getLibrary
      security:
        - ZettleOauth:
            - READ:PRODUCT
      summary: Retrieve the entire library
      tags:
        - library
  "/organizations/{organizationUuid}/products":
    delete:
      operationId: deleteProducts
      security:
        - ZettleOauth:
            - WRITE:PRODUCT
      summary: Delete a list of products
      tags:
        - products
    get:
      operationId: getAllProductsInPos
      security:
        - ZettleOauth:
            - READ:PRODUCT
      summary: Retrieve all products visible in POS
      tags:
        - products
    post:
      operationId: createProduct
      security:
        - ZettleOauth:
            - WRITE:PRODUCT
      summary: Create a new product
      tags:
        - products
  "/organizations/{organizationUuid}/products/online/slug":
    post:
      description: Creates a unique slug (identifier) for a product. The slug is used to create a product URL
      operationId: createProductSlug
      security:
        - ZettleOauth:
            - READ:PRODUCT
      summary: Create a product identifier
      tags:
        - products/online
  "/organizations/{organizationUuid}/products/options":
    get:
      operationId: getAllOptions
      security:
        - ZettleOauth:
            - READ:PRODUCT
      summary: Retrieve an aggregate of active Options in the library
      tags:
        - products
  "/organizations/{organizationUuid}/products/v2":
    get:
      operationId: getAllProductsV2
      security:
        - ZettleOauth:
            - READ:PRODUCT
      summary: Retrieve all products visible in POS – v2
      tags:
        - products
  "/organizations/{organizationUuid}/products/v2/count":
    get:
      operationId: countAllProducts
      security:
        - ZettleOauth:
            - READ:PRODUCT
      summary: Retrieve the count of existing products
      tags:
        - products
  "/organizations/{organizationUuid}/products/v2/{productUuid}":
    put:
      description: "Updates a product entity using JSON merge patch (https://tools.ietf.org/html/rfc7386). This means that only included fields will be changed: null values removes the field on the target entity, and other values updates the field. Conditional updates are supported through the HttpHeaders.IF_MATCH header. If the conditional prerequisite is fullfilled, the product is updated: otherwise a 412 (precondition failed) will be returned with an empty body."
      operationId: updateProduct
      security:
        - ZettleOauth:
            - WRITE:PRODUCT
      summary: Update a single product
      tags:
        - products
  "/organizations/{organizationUuid}/products/{productUuid}":
    delete:
      operationId: deleteProduct
      security:
        - ZettleOauth:
            - WRITE:PRODUCT
      summary: Delete a single product
      tags:
        - products
    get:
      description: Get the full product with the provided UUID. The method supports conditional GET through providing a HttpHeaders.IF_NONE_MATCH header. If the conditional prerequisite is fullfilled, the full product is returned, otherwise a 304 not modified will be returned with an empty body.
      operationId: getProduct
      security:
        - ZettleOauth:
            - READ:PRODUCT
      summary: Retrieve a single product
      tags:
        - products
  /v1/taxes:
    get:
      operationId: getTaxRates
      security:
        - ZettleOauth:
            - READ:PRODUCT
      summary: Get all available tax rates
      tags:
        - taxes
    post:
      operationId: createTaxRates
      security:
        - ZettleOauth:
            - WRITE:PRODUCT
      summary: Create new tax rates
      tags:
        - taxes
  /v1/taxes/count:
    get:
      operationId: getProductCountForAllTaxes
      security:
        - ZettleOauth:
            - READ:PRODUCT
      summary: Get all tax rates and a count of products associated with each
      tags:
        - taxes
  /v1/taxes/settings:
    get:
      operationId: getTaxSettings
      security:
        - ZettleOauth:
            - READ:PRODUCT
      summary: "Get the organization tax settings "
      tags:
        - taxes
    put:
      operationId: setTaxationMode
      security:
        - ZettleOauth:
            - WRITE:PRODUCT
      summary: Update the organization tax settings
      tags:
        - taxes
  "/v1/taxes/{taxRateUuid}":
    delete:
      operationId: deleteTaxRate
      security:
        - ZettleOauth:
            - WRITE:PRODUCT
      summary: Delete a single tax rate
      tags:
        - taxes
    get:
      operationId: getTaxRate
      security:
        - ZettleOauth:
            - READ:PRODUCT
      summary: Get a single tax rate
      tags:
        - taxes
    put:
      operationId: updateTaxRate
      security:
        - ZettleOauth:
            - WRITE:PRODUCT
      summary: Update a single tax rate
      tags:
        - taxes
components:
  securitySchemes:
    ZettleOauth:
      description: "For more information about authorization API visit: https://developer.zettle.com/docs/api/oauth/overview"
      flows:
        authorizationCode:
          authorizationUrl: https://oauth.zettle.com/authorize
          scopes:
            READ:PRODUCT: Access to read product library data
            WRITE:PRODUCT: Access to write product library data
          tokenUrl: https://oauth.zettle.com/token
      type: oauth2
