# coding: utf-8

"""
    Cloud Vision API

    Integrates Google Vision features, including image labeling, face, logo, and landmark detection, optical character recognition (OCR), and detection of explicit content, into applications.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.google_cloud_vision_v1p3beta1_import_product_sets_response import GoogleCloudVisionV1p3beta1ImportProductSetsResponse

class TestGoogleCloudVisionV1p3beta1ImportProductSetsResponse(unittest.TestCase):
    """GoogleCloudVisionV1p3beta1ImportProductSetsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GoogleCloudVisionV1p3beta1ImportProductSetsResponse:
        """Test GoogleCloudVisionV1p3beta1ImportProductSetsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GoogleCloudVisionV1p3beta1ImportProductSetsResponse`
        """
        model = GoogleCloudVisionV1p3beta1ImportProductSetsResponse()
        if include_optional:
            return GoogleCloudVisionV1p3beta1ImportProductSetsResponse(
                reference_images = [
                    openapi_client.models.google_cloud_vision_v1p3beta1_reference_image.GoogleCloudVisionV1p3beta1ReferenceImage(
                        bounding_polys = [
                            openapi_client.models.google_cloud_vision_v1p3beta1_bounding_poly.GoogleCloudVisionV1p3beta1BoundingPoly(
                                normalized_vertices = [
                                    openapi_client.models.google_cloud_vision_v1p3beta1_normalized_vertex.GoogleCloudVisionV1p3beta1NormalizedVertex(
                                        x = 1.337, 
                                        y = 1.337, )
                                    ], 
                                vertices = [
                                    openapi_client.models.google_cloud_vision_v1p3beta1_vertex.GoogleCloudVisionV1p3beta1Vertex(
                                        x = 56, 
                                        y = 56, )
                                    ], )
                            ], 
                        name = '', 
                        uri = '', )
                    ],
                statuses = [
                    openapi_client.models.status.Status(
                        code = 56, 
                        details = [
                            {
                                'key' : null
                                }
                            ], 
                        message = '', )
                    ]
            )
        else:
            return GoogleCloudVisionV1p3beta1ImportProductSetsResponse(
        )
        """

    def testGoogleCloudVisionV1p3beta1ImportProductSetsResponse(self):
        """Test GoogleCloudVisionV1p3beta1ImportProductSetsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
