openapi: 3.0.0
servers:
  - url: https://www.googleapis.com/adsense/v1.4
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: Accesses AdSense publishers' inventory and generates performance reports.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: AdSense Management API
  version: v1.4
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png
  x-origin:
    - format: google
      url: https://adsense.googleapis.com/$discovery/rest?version=v1.4
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: adsense
tags:
  - name: accounts
  - name: adclients
  - name: adunits
  - name: alerts
  - name: customchannels
  - name: metadata
  - name: payments
  - name: reports
  - name: savedadstyles
  - name: urlchannels
paths:
  /accounts:
    get:
      description: List all accounts available to this AdSense account.
      operationId: adsense.accounts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/accounts/{accountId}":
    get:
      description: Get information about the selected AdSense account.
      operationId: adsense.accounts.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/accounts/{accountId}/adclients":
    get:
      description: List all ad clients in the specified account.
      operationId: adsense.accounts.adclients.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/accounts/{accountId}/adclients/{adClientId}/adcode":
    get:
      description: Get Auto ad code for a given ad client.
      operationId: adsense.accounts.adclients.getAdCode
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/accounts/{accountId}/adclients/{adClientId}/adunits":
    get:
      description: List all ad units in the specified ad client for the specified account.
      operationId: adsense.accounts.adunits.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/accounts/{accountId}/adclients/{adClientId}/adunits/{adUnitId}":
    get:
      description: Gets the specified ad unit in the specified ad client for the specified account.
      operationId: adsense.accounts.adunits.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/accounts/{accountId}/adclients/{adClientId}/adunits/{adUnitId}/adcode":
    get:
      description: Get ad code for the specified ad unit.
      operationId: adsense.accounts.adunits.getAdCode
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/accounts/{accountId}/adclients/{adClientId}/adunits/{adUnitId}/customchannels":
    get:
      description: List all custom channels which the specified ad unit belongs to.
      operationId: adsense.accounts.adunits.customchannels.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/accounts/{accountId}/adclients/{adClientId}/customchannels":
    get:
      description: List all custom channels in the specified ad client for the specified account.
      operationId: adsense.accounts.customchannels.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/accounts/{accountId}/adclients/{adClientId}/customchannels/{customChannelId}":
    get:
      description: Get the specified custom channel from the specified ad client for the specified account.
      operationId: adsense.accounts.customchannels.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/accounts/{accountId}/adclients/{adClientId}/customchannels/{customChannelId}/adunits":
    get:
      description: List all ad units in the specified custom channel.
      operationId: adsense.accounts.customchannels.adunits.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/accounts/{accountId}/adclients/{adClientId}/urlchannels":
    get:
      description: List all URL channels in the specified ad client for the specified account.
      operationId: adsense.accounts.urlchannels.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/accounts/{accountId}/alerts":
    get:
      description: List the alerts for the specified AdSense account.
      operationId: adsense.accounts.alerts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/accounts/{accountId}/alerts/{alertId}":
    delete:
      description: Dismiss (delete) the specified alert from the specified publisher AdSense account.
      operationId: adsense.accounts.alerts.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
      tags:
        - accounts
  "/accounts/{accountId}/payments":
    get:
      description: List the payments for the specified AdSense account.
      operationId: adsense.accounts.payments.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/accounts/{accountId}/reports":
    get:
      description: Generate an AdSense report based on the report request sent in the query parameters. Returns the result as JSON; to retrieve output in CSV format specify "alt=csv" as a query parameter.
      operationId: adsense.accounts.reports.generate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/accounts/{accountId}/reports/saved":
    get:
      description: List all saved reports in the specified AdSense account.
      operationId: adsense.accounts.reports.saved.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/accounts/{accountId}/reports/{savedReportId}":
    get:
      description: Generate an AdSense report based on the saved report ID sent in the query parameters.
      operationId: adsense.accounts.reports.saved.generate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/accounts/{accountId}/savedadstyles":
    get:
      description: List all saved ad styles in the specified account.
      operationId: adsense.accounts.savedadstyles.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/accounts/{accountId}/savedadstyles/{savedAdStyleId}":
    get:
      description: List a specific saved ad style for the specified account.
      operationId: adsense.accounts.savedadstyles.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  /adclients:
    get:
      description: List all ad clients in this AdSense account.
      operationId: adsense.adclients.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - adclients
  "/adclients/{adClientId}/adunits":
    get:
      description: List all ad units in the specified ad client for this AdSense account.
      operationId: adsense.adunits.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - adunits
  "/adclients/{adClientId}/adunits/{adUnitId}":
    get:
      description: Gets the specified ad unit in the specified ad client.
      operationId: adsense.adunits.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - adunits
  "/adclients/{adClientId}/adunits/{adUnitId}/adcode":
    get:
      description: Get ad code for the specified ad unit.
      operationId: adsense.adunits.getAdCode
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - adunits
  "/adclients/{adClientId}/adunits/{adUnitId}/customchannels":
    get:
      description: List all custom channels which the specified ad unit belongs to.
      operationId: adsense.adunits.customchannels.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - adunits
  "/adclients/{adClientId}/customchannels":
    get:
      description: List all custom channels in the specified ad client for this AdSense account.
      operationId: adsense.customchannels.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - customchannels
  "/adclients/{adClientId}/customchannels/{customChannelId}":
    get:
      description: Get the specified custom channel from the specified ad client.
      operationId: adsense.customchannels.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - customchannels
  "/adclients/{adClientId}/customchannels/{customChannelId}/adunits":
    get:
      description: List all ad units in the specified custom channel.
      operationId: adsense.customchannels.adunits.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - customchannels
  "/adclients/{adClientId}/urlchannels":
    get:
      description: List all URL channels in the specified ad client for this AdSense account.
      operationId: adsense.urlchannels.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - urlchannels
  /alerts:
    get:
      description: List the alerts for this AdSense account.
      operationId: adsense.alerts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - alerts
  "/alerts/{alertId}":
    delete:
      description: Dismiss (delete) the specified alert from the publisher's AdSense account.
      operationId: adsense.alerts.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
      tags:
        - alerts
  /metadata/dimensions:
    get:
      description: List the metadata for the dimensions available to this AdSense account.
      operationId: adsense.metadata.dimensions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - metadata
  /metadata/metrics:
    get:
      description: List the metadata for the metrics available to this AdSense account.
      operationId: adsense.metadata.metrics.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - metadata
  /payments:
    get:
      description: List the payments for this AdSense account.
      operationId: adsense.payments.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - payments
  /reports:
    get:
      description: Generate an AdSense report based on the report request sent in the query parameters. Returns the result as JSON; to retrieve output in CSV format specify "alt=csv" as a query parameter.
      operationId: adsense.reports.generate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - reports
  /reports/saved:
    get:
      description: List all saved reports in this AdSense account.
      operationId: adsense.reports.saved.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - reports
  "/reports/{savedReportId}":
    get:
      description: Generate an AdSense report based on the saved report ID sent in the query parameters.
      operationId: adsense.reports.saved.generate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - reports
  /savedadstyles:
    get:
      description: List all saved ad styles in the user's account.
      operationId: adsense.savedadstyles.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - savedadstyles
  "/savedadstyles/{savedAdStyleId}":
    get:
      description: Get a specific saved ad style from the user's account.
      operationId: adsense.savedadstyles.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - savedadstyles
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/adsense: View and manage your AdSense data
            https://www.googleapis.com/auth/adsense.readonly: View your AdSense data
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/adsense: View and manage your AdSense data
            https://www.googleapis.com/auth/adsense.readonly: View your AdSense data
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
