package shared

type GoogleCloudBeyondcorpAppconnectorsV1AppConnectorPrincipalInfo struct {
	ServiceAccount *GoogleCloudBeyondcorpAppconnectorsV1AppConnectorPrincipalInfoServiceAccount `json:"serviceAccount"`
}
