package shared

type GoogleCloudBeyondcorpAppconnectorsV1ResolveInstanceConfigResponse struct {
	InstanceConfig *GoogleCloudBeyondcorpAppconnectorsV1AppConnectorInstanceConfig `json:"instanceConfig,omitempty"`
}
