package shared

type HostedNumberOrderEnumVerificationTypeEnum string

const (
	HostedNumberOrderEnumVerificationTypeEnumPhoneCall HostedNumberOrderEnumVerificationTypeEnum = "phone-call"
	HostedNumberOrderEnumVerificationTypeEnumPhoneBill HostedNumberOrderEnumVerificationTypeEnum = "phone-bill"
)
