package shared

type InstanceAccessControlAttributeConfigurationStatusEnum string

const (
	InstanceAccessControlAttributeConfigurationStatusEnumEnabled            InstanceAccessControlAttributeConfigurationStatusEnum = "ENABLED"
	InstanceAccessControlAttributeConfigurationStatusEnumCreationInProgress InstanceAccessControlAttributeConfigurationStatusEnum = "CREATION_IN_PROGRESS"
	InstanceAccessControlAttributeConfigurationStatusEnumCreationFailed     InstanceAccessControlAttributeConfigurationStatusEnum = "CREATION_FAILED"
)
