# coding: utf-8

"""
    Contact Center AI Insights API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GoogleCloudContactcenterinsightsV1alpha1AnswerFeedback(BaseModel):
    """
    The feedback that the customer has about a certain answer in the conversation.
    """ # noqa: E501
    clicked: Optional[StrictBool] = Field(default=None, description="Indicates whether an answer or item was clicked by the human agent.")
    correctness_level: Optional[StrictStr] = Field(default=None, description="The correctness level of an answer.", alias="correctnessLevel")
    displayed: Optional[StrictBool] = Field(default=None, description="Indicates whether an answer or item was displayed to the human agent in the agent desktop UI.")
    __properties: ClassVar[List[str]] = ["clicked", "correctnessLevel", "displayed"]

    @field_validator('correctness_level')
    def correctness_level_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['CORRECTNESS_LEVEL_UNSPECIFIED', 'NOT_CORRECT', 'PARTIALLY_CORRECT', 'FULLY_CORRECT']):
            raise ValueError("must be one of enum values ('CORRECTNESS_LEVEL_UNSPECIFIED', 'NOT_CORRECT', 'PARTIALLY_CORRECT', 'FULLY_CORRECT')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GoogleCloudContactcenterinsightsV1alpha1AnswerFeedback from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GoogleCloudContactcenterinsightsV1alpha1AnswerFeedback from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "clicked": obj.get("clicked"),
            "correctnessLevel": obj.get("correctnessLevel"),
            "displayed": obj.get("displayed")
        })
        return _obj


