from .createconfigurationset import *
from .createconfigurationseteventdestination import *
from .creatededicatedippool import *
from .createdeliverabilitytestreport import *
from .createemailidentity import *
from .deleteconfigurationset import *
from .deleteconfigurationseteventdestination import *
from .deletededicatedippool import *
from .deleteemailidentity import *
from .getaccount import *
from .getblacklistreports import *
from .getconfigurationset import *
from .getconfigurationseteventdestinations import *
from .getdedicatedip import *
from .getdedicatedips import *
from .getdeliverabilitydashboardoptions import *
from .getdeliverabilitytestreport import *
from .getdomaindeliverabilitycampaign import *
from .getdomainstatisticsreport import *
from .getemailidentity import *
from .listconfigurationsets import *
from .listdedicatedippools import *
from .listdeliverabilitytestreports import *
from .listdomaindeliverabilitycampaigns import *
from .listemailidentities import *
from .listtagsforresource import *
from .putaccountdedicatedipwarmupattributes import *
from .putaccountsendingattributes import *
from .putconfigurationsetdeliveryoptions import *
from .putconfigurationsetreputationoptions import *
from .putconfigurationsetsendingoptions import *
from .putconfigurationsettrackingoptions import *
from .putdedicatedipinpool import *
from .putdedicatedipwarmupattributes import *
from .putdeliverabilitydashboardoption import *
from .putemailidentitydkimattributes import *
from .putemailidentityfeedbackattributes import *
from .putemailidentitymailfromattributes import *
from .sendemail import *
from .tagresource import *
from .untagresource import *
from .updateconfigurationseteventdestination import *
