from dataclasses import dataclass, field
from typing import Optional
from enum import Enum
from dataclasses_json import dataclass_json
from sdk import utils

class SensitiveCategoryTargetingOptionDetailsSensitiveCategoryEnum(str, Enum):
    SENSITIVE_CATEGORY_UNSPECIFIED = "SENSITIVE_CATEGORY_UNSPECIFIED"
    SENSITIVE_CATEGORY_ADULT = "SENSITIVE_CATEGORY_ADULT"
    SENSITIVE_CATEGORY_DEROGATORY = "SENSITIVE_CATEGORY_DEROGATORY"
    SENSITIVE_CATEGORY_DOWNLOADS_SHARING = "SENSITIVE_CATEGORY_DOWNLOADS_SHARING"
    SENSITIVE_CATEGORY_WEAPONS = "SENSITIVE_CATEGORY_WEAPONS"
    SENSITIVE_CATEGORY_GAMBLING = "SENSITIVE_CATEGORY_GAMBLING"
    SENSITIVE_CATEGORY_VIOLENCE = "SENSITIVE_CATEGORY_VIOLENCE"
    SENSITIVE_CATEGORY_SUGGESTIVE = "SENSITIVE_CATEGORY_SUGGESTIVE"
    SENSITIVE_CATEGORY_PROFANITY = "SENSITIVE_CATEGORY_PROFANITY"
    SENSITIVE_CATEGORY_ALCOHOL = "SENSITIVE_CATEGORY_ALCOHOL"
    SENSITIVE_CATEGORY_DRUGS = "SENSITIVE_CATEGORY_DRUGS"
    SENSITIVE_CATEGORY_TOBACCO = "SENSITIVE_CATEGORY_TOBACCO"
    SENSITIVE_CATEGORY_POLITICS = "SENSITIVE_CATEGORY_POLITICS"
    SENSITIVE_CATEGORY_RELIGION = "SENSITIVE_CATEGORY_RELIGION"
    SENSITIVE_CATEGORY_TRAGEDY = "SENSITIVE_CATEGORY_TRAGEDY"
    SENSITIVE_CATEGORY_TRANSPORTATION_ACCIDENTS = "SENSITIVE_CATEGORY_TRANSPORTATION_ACCIDENTS"
    SENSITIVE_CATEGORY_SENSITIVE_SOCIAL_ISSUES = "SENSITIVE_CATEGORY_SENSITIVE_SOCIAL_ISSUES"
    SENSITIVE_CATEGORY_SHOCKING = "SENSITIVE_CATEGORY_SHOCKING"


@dataclass_json
@dataclass
class SensitiveCategoryTargetingOptionDetails:
    r"""SensitiveCategoryTargetingOptionDetails
    Represents a targetable sensitive category. This will be populated in the sensitive_category_details field of the TargetingOption when targeting_type is `TARGETING_TYPE_SENSITIVE_CATEGORY_EXCLUSION`.
    """
    
    sensitive_category: Optional[SensitiveCategoryTargetingOptionDetailsSensitiveCategoryEnum] = field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.field_name('sensitiveCategory') }})
    
