from dataclasses import dataclass, field
from typing import Enum,Optional
from dataclasses_json import dataclass_json

class ThirdPartyURLTypeEnum(str, Enum):
    THIRD_PARTY_URL_TYPE_UNSPECIFIED = "THIRD_PARTY_URL_TYPE_UNSPECIFIED"
    THIRD_PARTY_URL_TYPE_IMPRESSION = "THIRD_PARTY_URL_TYPE_IMPRESSION"
    THIRD_PARTY_URL_TYPE_CLICK_TRACKING = "THIRD_PARTY_URL_TYPE_CLICK_TRACKING"
    THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_START = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_START"
    THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_FIRST_QUARTILE = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_FIRST_QUARTILE"
    THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_MIDPOINT = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_MIDPOINT"
    THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_THIRD_QUARTILE = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_THIRD_QUARTILE"
    THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_COMPLETE = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_COMPLETE"
    THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_MUTE = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_MUTE"
    THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_PAUSE = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_PAUSE"
    THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_REWIND = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_REWIND"
    THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_FULLSCREEN = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_FULLSCREEN"
    THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_STOP = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_STOP"
    THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_CUSTOM = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_CUSTOM"
    THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_SKIP = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_SKIP"
    THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_PROGRESS = "THIRD_PARTY_URL_TYPE_AUDIO_VIDEO_PROGRESS"


@dataclass_json
@dataclass
class ThirdPartyURL:
    type: Optional[ThirdPartyURLTypeEnum] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'type' }})
    url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'url' }})
    
