from dataclasses import dataclass, field
from typing import List,Optional
from dataclasses_json import dataclass_json
from . import appointmentauditviewmodel
from . import customfieldviewmodel
from . import appointmentcustomerviewmodel
from . import appointmentresourceviewmodel


@dataclass_json
@dataclass
class AppointmentViewModel:
    audit_trail: Optional[List[appointmentauditviewmodel.AppointmentAuditViewModel]] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'auditTrail' }})
    booked_by: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'bookedBy' }})
    business_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'businessName' }})
    calendar_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'calendarId' }})
    confirmation_number: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'confirmationNumber' }})
    confirmed: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'confirmed' }})
    create_date: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'createDate' }})
    custom_fields: Optional[dict[str, customfieldviewmodel.CustomFieldViewModel]] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'customFields' }})
    customer_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'customerId' }})
    customer_message: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'customerMessage' }})
    customers: Optional[List[appointmentcustomerviewmodel.AppointmentCustomerViewModel]] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'customers' }})
    date: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'date' }})
    date_international: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'dateInternational' }})
    download_ics_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'downloadIcsUrl' }})
    duration: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'duration' }})
    email: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'email' }})
    email_confirmation_sent: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'emailConfirmationSent' }})
    email_reminder_sent: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'emailReminderSent' }})
    end_date_time: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'endDateTime' }})
    firstname: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'firstname' }})
    group_size: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'groupSize' }})
    id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'id' }})
    ip_address: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'ipAddress' }})
    last_modified_by: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'lastModifiedBy' }})
    last_modified_on: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'lastModifiedOn' }})
    lastname: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'lastname' }})
    latitude: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'latitude' }})
    location: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'location' }})
    location_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'locationId' }})
    longitude: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'longitude' }})
    name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'name' }})
    notes: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'notes' }})
    object_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'objectName' }})
    online_booking: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'onlineBooking' }})
    payment_status: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'paymentStatus' }})
    phone: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'phone' }})
    phone_ext: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'phoneExt' }})
    phone_type: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'phoneType' }})
    rescheduled_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'rescheduledId' }})
    resource_group_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'resourceGroupId' }})
    resource_group_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'resourceGroupName' }})
    resource_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'resourceId' }})
    resource_image_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'resourceImageUrl' }})
    resource_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'resourceName' }})
    resources: Optional[List[appointmentresourceviewmodel.AppointmentResourceViewModel]] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'resources' }})
    service_allocation_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'serviceAllocationId' }})
    service_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'serviceId' }})
    service_image_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'serviceImageUrl' }})
    service_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'serviceName' }})
    sms_confirmation_sent: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'smsConfirmationSent' }})
    sms_reminder_sent: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'smsReminderSent' }})
    start_date_time: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'startDateTime' }})
    status: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'status' }})
    stripe_charge_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'stripeChargeId' }})
    stripe_refund_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'stripeRefundId' }})
    time: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'time' }})
    timezone: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'timezone' }})
    timezone_iana: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'timezoneIana' }})
    timezone_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'timezoneId' }})
    
