swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /taskqueue/v1beta2/projects
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Accesses a Google App Engine Pull Task Queue over REST.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: TaskQueue
  version: v1beta2
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/taskqueue/v1beta2/rest'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: taskqueue
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/taskqueue': Manage your Tasks and Taskqueues
      'https://www.googleapis.com/auth/taskqueue.consumer': Consume Tasks from your Taskqueues
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/taskqueue': Manage your Tasks and Taskqueues
      'https://www.googleapis.com/auth/taskqueue.consumer': Consume Tasks from your Taskqueues
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: taskqueues
  - name: tasks
paths:
  '/{project}/taskqueues/{taskqueue}':
    get:
      description: Get detailed information about a TaskQueue.
      operationId: taskqueue.taskqueues.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/taskqueue'
          Oauth2c:
            - 'https://www.googleapis.com/auth/taskqueue'
        - Oauth2:
            - 'https://www.googleapis.com/auth/taskqueue.consumer'
          Oauth2c:
            - 'https://www.googleapis.com/auth/taskqueue.consumer'
      tags:
        - taskqueues
  '/{project}/taskqueues/{taskqueue}/tasks':
    get:
      description: List Tasks in a TaskQueue
      operationId: taskqueue.tasks.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/taskqueue'
          Oauth2c:
            - 'https://www.googleapis.com/auth/taskqueue'
        - Oauth2:
            - 'https://www.googleapis.com/auth/taskqueue.consumer'
          Oauth2c:
            - 'https://www.googleapis.com/auth/taskqueue.consumer'
      tags:
        - tasks
    post:
      description: Insert a new task in a TaskQueue
      operationId: taskqueue.tasks.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/taskqueue'
          Oauth2c:
            - 'https://www.googleapis.com/auth/taskqueue'
        - Oauth2:
            - 'https://www.googleapis.com/auth/taskqueue.consumer'
          Oauth2c:
            - 'https://www.googleapis.com/auth/taskqueue.consumer'
      tags:
        - tasks
  '/{project}/taskqueues/{taskqueue}/tasks/lease':
    post:
      description: Lease 1 or more tasks from a TaskQueue.
      operationId: taskqueue.tasks.lease
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/taskqueue'
          Oauth2c:
            - 'https://www.googleapis.com/auth/taskqueue'
        - Oauth2:
            - 'https://www.googleapis.com/auth/taskqueue.consumer'
          Oauth2c:
            - 'https://www.googleapis.com/auth/taskqueue.consumer'
      tags:
        - tasks
  '/{project}/taskqueues/{taskqueue}/tasks/{task}':
    delete:
      description: Delete a task from a TaskQueue.
      operationId: taskqueue.tasks.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/taskqueue'
          Oauth2c:
            - 'https://www.googleapis.com/auth/taskqueue'
        - Oauth2:
            - 'https://www.googleapis.com/auth/taskqueue.consumer'
          Oauth2c:
            - 'https://www.googleapis.com/auth/taskqueue.consumer'
      tags:
        - tasks
    get:
      description: Get a particular task from a TaskQueue.
      operationId: taskqueue.tasks.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/taskqueue'
          Oauth2c:
            - 'https://www.googleapis.com/auth/taskqueue'
        - Oauth2:
            - 'https://www.googleapis.com/auth/taskqueue.consumer'
          Oauth2c:
            - 'https://www.googleapis.com/auth/taskqueue.consumer'
      tags:
        - tasks
    patch:
      description: Update tasks that are leased out of a TaskQueue. This method supports patch semantics.
      operationId: taskqueue.tasks.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/taskqueue'
          Oauth2c:
            - 'https://www.googleapis.com/auth/taskqueue'
        - Oauth2:
            - 'https://www.googleapis.com/auth/taskqueue.consumer'
          Oauth2c:
            - 'https://www.googleapis.com/auth/taskqueue.consumer'
      tags:
        - tasks
    post:
      description: Update tasks that are leased out of a TaskQueue.
      operationId: taskqueue.tasks.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/taskqueue'
          Oauth2c:
            - 'https://www.googleapis.com/auth/taskqueue'
        - Oauth2:
            - 'https://www.googleapis.com/auth/taskqueue.consumer'
          Oauth2c:
            - 'https://www.googleapis.com/auth/taskqueue.consumer'
      tags:
        - tasks