swagger: "2.0"
schemes:
  - https
host: connect.squareup.com
info:
  contact:
    email: developers@squareup.com
    name: Square Developer Platform
    url: https://squareup.com/developers
  description: Client library for accessing the Square Connect APIs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://connect.squareup.com/tos
  title: Square Connect
  version: "2.0"
  x-apisguru-categories:
    - payment
  x-logo:
    url: http://square.github.io/images/logo.png
  x-origin:
    - format: swagger
      url: https://raw.githubusercontent.com/square/connect-api-specification/master/api.json
      version: "2.0"
  x-providerName: squareup.com
securityDefinitions:
  oauth2:
    authorizationUrl: https://connect.squareup.com/oauth2/authorize
    flow: accessCode
    scopes:
      BANK_ACCOUNTS_READ: GET endpoints related to a merchant's bank accounts
      CUSTOMERS_READ: " GET endpoints related to customer management"
      CUSTOMERS_WRITE: POST, PUT, and DELETE endpoints related to customer management
      EMPLOYEES_READ: GET endpoints related to employee management
      EMPLOYEES_WRITE: POST, PUT, and DELETE endpoints related to employee management
      ITEMS_READ: GET endpoints related to a merchant's item library
      ITEMS_WRITE: POST, PUT, and DELETE endpoints related to a merchant's item library
      MERCHANT_PROFILE_READ: GET endpoints related to a merchant's business and location entities. Almost all Connect API applications need this permission in order to obtain a merchant's location IDs
      ORDERS_READ: GET endpoints related to a merchant's orders
      ORDERS_WRITE: POST, PUT, and DELETE endpoints related to a merchant's orders
      PAYMENTS_READ: GET endpoints related to transactions and refunds
      PAYMENTS_WRITE: POST, PUT, and DELETE endpoints related to transactions and refunds. E-commerce applications must request this permission
      SETTLEMENTS_READ: GET endpoints related to settlements (deposits)
      TIMECARDS_READ: GET endpoints related to employee timecards
      TIMECARDS_WRITE: POST, PUT, and DELETE endpoints related to employee timecards
    tokenUrl: https://connect.squareup.com/oauth2/token
    type: oauth2
paths:
  /v1/me:
    get:
      deprecated: true
      description: Get a business's information.
      operationId: RetrieveBusiness
      security:
        - oauth2:
            - MERCHANT_PROFILE_READ
      summary: Get a business's information.
      tags:
        - V1Locations
  /v1/me/employees:
    get:
      deprecated: false
      description: Provides summary information for all of a business's employees.
      operationId: ListEmployees
      security:
        - oauth2:
            - EMPLOYEES_READ
      summary: Provides summary information for all of a business's employees.
      tags:
        - V1Employees
    post:
      deprecated: false
      description: Creates an employee for a business.
      operationId: CreateEmployee
      security:
        - oauth2:
            - EMPLOYEES_WRITE
      summary: Creates an employee for a business.
      tags:
        - V1Employees
  "/v1/me/employees/{employee_id}":
    get:
      deprecated: false
      description: Provides the details for a single employee.
      operationId: RetrieveEmployee
      security:
        - oauth2:
            - EMPLOYEES_READ
      summary: Provides the details for a single employee.
      tags:
        - V1Employees
    put:
      deprecated: false
      operationId: UpdateEmployee
      security:
        - oauth2:
            - EMPLOYEES_WRITE
      summary: V1 UpdateEmployee
      tags:
        - V1Employees
  /v1/me/locations:
    get:
      deprecated: true
      description: Provides details for a business's locations, including their IDs.
      security:
        - oauth2:
            - MERCHANT_PROFILE_READ
      summary: Provides details for a business's locations, including their IDs.
      tags:
        - V1Locations
  /v1/me/roles:
    get:
      deprecated: false
      description: Provides summary information for all of a business's employee roles.
      operationId: ListEmployeeRoles
      security:
        - oauth2:
            - EMPLOYEES_READ
      summary: Provides summary information for all of a business's employee roles.
      tags:
        - V1Employees
    post:
      deprecated: false
      description: Creates an employee role you can then assign to employees.
      operationId: CreateEmployeeRole
      security:
        - oauth2:
            - EMPLOYEES_WRITE
      summary: Creates an employee role you can then assign to employees.
      tags:
        - V1Employees
  "/v1/me/roles/{role_id}":
    get:
      deprecated: false
      description: Provides the details for a single employee role.
      operationId: RetrieveEmployeeRole
      security:
        - oauth2:
            - EMPLOYEES_READ
      summary: Provides the details for a single employee role.
      tags:
        - V1Employees
    put:
      deprecated: false
      description: Modifies the details of an employee role.
      operationId: UpdateEmployeeRole
      security:
        - oauth2:
            - EMPLOYEES_WRITE
      summary: Modifies the details of an employee role.
      tags:
        - V1Employees
  /v1/me/timecards:
    get:
      deprecated: false
      description: Provides summary information for all of a business's employee timecards.
      operationId: ListTimecards
      security:
        - oauth2:
            - TIMECARDS_READ
      summary: Provides summary information for all of a business's employee timecards.
      tags:
        - V1Employees
    post:
      deprecated: false
      description: Creates a timecard for an employee. Each timecard corresponds to a single shift.
      operationId: CreateTimecard
      security:
        - oauth2:
            - TIMECARDS_WRITE
      summary: Creates a timecard for an employee. Each timecard corresponds to a single shift.
      tags:
        - V1Employees
  "/v1/me/timecards/{timecard_id}":
    delete:
      deprecated: false
      description: Deletes a timecard. Deleted timecards are still accessible from Connect API endpoints, but the value of their deleted field is set to true. See Handling deleted timecards for more information.
      operationId: DeleteTimecard
      security:
        - oauth2:
            - TIMECARDS_WRITE
      summary: Deletes a timecard. Deleted timecards are still accessible from Connect API endpoints, but the value of their deleted field is set to true. See Handling deleted timecards for more information.
      tags:
        - V1Employees
    get:
      deprecated: false
      description: Provides the details for a single timecard.
      operationId: RetrieveTimecard
      security:
        - oauth2:
            - TIMECARDS_READ
      summary: Provides the details for a single timecard.
      tags:
        - V1Employees
    put:
      deprecated: false
      description: Modifies a timecard's details. This creates an API_EDIT event for the timecard. You can view a timecard's event history with the List Timecard Events endpoint.
      operationId: UpdateTimecard
      security:
        - oauth2:
            - TIMECARDS_WRITE
      summary: Modifies a timecard's details. This creates an API_EDIT event for the timecard. You can view a timecard's event history with the List Timecard Events endpoint.
      tags:
        - V1Employees
  "/v1/me/timecards/{timecard_id}/events":
    get:
      deprecated: false
      description: Provides summary information for all events associated with a particular timecard.
      operationId: ListTimecardEvents
      security:
        - oauth2:
            - TIMECARDS_READ
      summary: Provides summary information for all events associated with a particular timecard.
      tags:
        - V1Employees
  "/v1/{location_id}/bank-accounts":
    get:
      deprecated: false
      description: Provides non-confidential details for all of a location's associated bank accounts. This endpoint does not provide full bank account numbers, and there is no way to obtain a full bank account number with the Connect API.
      operationId: ListBankAccounts
      security:
        - oauth2:
            - BANK_ACCOUNTS_READ
      summary: Provides non-confidential details for all of a location's associated bank accounts. This endpoint does not provide full bank account numbers, and there is no way to obtain a full bank account number with the Connect API.
      tags:
        - V1Transactions
  "/v1/{location_id}/bank-accounts/{bank_account_id}":
    get:
      deprecated: false
      description: Provides non-confidential details for a merchant's associated bank account. This endpoint does not provide full bank account numbers, and there is no way to obtain a full bank account number with the Connect API.
      operationId: RetrieveBankAccount
      security:
        - oauth2:
            - BANK_ACCOUNTS_READ
      summary: Provides non-confidential details for a merchant's associated bank account. This endpoint does not provide full bank account numbers, and there is no way to obtain a full bank account number with the Connect API.
      tags:
        - V1Transactions
  "/v1/{location_id}/cash-drawer-shifts":
    get:
      deprecated: false
      description: Provides the details for all of a location's cash drawer shifts during a date range. The date range you specify cannot exceed 90 days.
      operationId: ListCashDrawerShifts
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: Provides the details for all of a location's cash drawer shifts during a date range. The date range you specify cannot exceed 90 days.
      tags:
        - V1Employees
  "/v1/{location_id}/cash-drawer-shifts/{shift_id}":
    get:
      deprecated: false
      description: Provides the details for a single cash drawer shift, including all events that occurred during the shift.
      operationId: RetrieveCashDrawerShift
      security:
        - oauth2:
            - TIMECARDS_READ
      summary: Provides the details for a single cash drawer shift, including all events that occurred during the shift.
      tags:
        - V1Employees
  "/v1/{location_id}/categories":
    get:
      deprecated: false
      description: Lists all of a location's item categories.
      operationId: ListCategories
      security:
        - oauth2:
            - ITEMS_READ
      summary: Lists all of a location's item categories.
      tags:
        - V1Items
    post:
      deprecated: false
      description: Creates an item category.
      operationId: CreateCategory
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Creates an item category.
      tags:
        - V1Items
  "/v1/{location_id}/categories/{category_id}":
    delete:
      deprecated: false
      description: Deletes an existing item category.
      operationId: DeleteCategory
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Deletes an existing item category.
      tags:
        - V1Items
    put:
      deprecated: false
      description: Modifies the details of an existing item category.
      operationId: UpdateCategory
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Modifies the details of an existing item category.
      tags:
        - V1Items
  "/v1/{location_id}/discounts":
    get:
      deprecated: false
      description: Lists all of a location's discounts.
      operationId: ListDiscounts
      security:
        - oauth2:
            - ITEMS_READ
      summary: Lists all of a location's discounts.
      tags:
        - V1Items
    post:
      deprecated: false
      description: Creates a discount.
      operationId: CreateDiscount
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Creates a discount.
      tags:
        - V1Items
  "/v1/{location_id}/discounts/{discount_id}":
    delete:
      deprecated: false
      description: Deletes an existing discount.
      operationId: DeleteDiscount
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Deletes an existing discount.
      tags:
        - V1Items
    put:
      deprecated: false
      description: Modifies the details of an existing discount.
      operationId: UpdateDiscount
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Modifies the details of an existing discount.
      tags:
        - V1Items
  "/v1/{location_id}/fees":
    get:
      deprecated: false
      description: Lists all of a location's fees (taxes).
      operationId: ListFees
      security:
        - oauth2:
            - ITEMS_READ
      summary: Lists all of a location's fees (taxes).
      tags:
        - V1Items
    post:
      deprecated: false
      description: Creates a fee (tax).
      operationId: CreateFee
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Creates a fee (tax).
      tags:
        - V1Items
  "/v1/{location_id}/fees/{fee_id}":
    delete:
      deprecated: false
      description: Deletes an existing fee (tax).
      operationId: DeleteFee
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Deletes an existing fee (tax).
      tags:
        - V1Items
    put:
      deprecated: false
      description: Modifies the details of an existing fee (tax).
      operationId: UpdateFee
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Modifies the details of an existing fee (tax).
      tags:
        - V1Items
  "/v1/{location_id}/inventory":
    get:
      deprecated: false
      description: Provides inventory information for all of a merchant's inventory-enabled item variations.
      operationId: ListInventory
      security:
        - oauth2:
            - ITEMS_READ
      summary: Provides inventory information for all of a merchant's inventory-enabled item variations.
      tags:
        - V1Items
  "/v1/{location_id}/inventory/{variation_id}":
    post:
      deprecated: false
      description: Adjusts an item variation's current available inventory.
      operationId: AdjustInventory
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Adjusts an item variation's current available inventory.
      tags:
        - V1Items
  "/v1/{location_id}/items":
    get:
      deprecated: false
      description: Provides summary information for all of a location's items.
      operationId: ListItems
      security:
        - oauth2:
            - ITEMS_READ
      summary: Provides summary information for all of a location's items.
      tags:
        - V1Items
    post:
      deprecated: false
      description: Creates an item and at least one variation for it.
      operationId: CreateItem
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Creates an item and at least one variation for it.
      tags:
        - V1Items
  "/v1/{location_id}/items/{item_id}":
    delete:
      deprecated: false
      description: Deletes an existing item and all item variations associated with it.
      operationId: DeleteItem
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Deletes an existing item and all item variations associated with it.
      tags:
        - V1Items
    get:
      deprecated: false
      description: Provides the details for a single item, including associated modifier lists and fees.
      operationId: RetrieveItem
      security:
        - oauth2:
            - ITEMS_READ
      summary: Provides the details for a single item, including associated modifier lists and fees.
      tags:
        - V1Items
    put:
      deprecated: false
      description: Modifies the core details of an existing item.
      operationId: UpdateItem
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Modifies the core details of an existing item.
      tags:
        - V1Items
  "/v1/{location_id}/items/{item_id}/fees/{fee_id}":
    delete:
      deprecated: false
      description: Removes a fee assocation from an item, meaning the fee is no longer automatically applied to the item in Square Register.
      operationId: RemoveFee
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Removes a fee assocation from an item, meaning the fee is no longer automatically applied to the item in Square Register.
      tags:
        - V1Items
    put:
      deprecated: false
      description: Associates a fee with an item, meaning the fee is automatically applied to the item in Square Register.
      operationId: ApplyFee
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Associates a fee with an item, meaning the fee is automatically applied to the item in Square Register.
      tags:
        - V1Items
  "/v1/{location_id}/items/{item_id}/modifier-lists/{modifier_list_id}":
    delete:
      deprecated: false
      description: Removes a modifier list association from an item, meaning modifier options from the list can no longer be applied to the item.
      operationId: RemoveModifierList
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Removes a modifier list association from an item, meaning modifier options from the list can no longer be applied to the item.
      tags:
        - V1Items
    put:
      deprecated: false
      description: Associates a modifier list with an item, meaning modifier options from the list can be applied to the item.
      operationId: ApplyModifierList
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Associates a modifier list with an item, meaning modifier options from the list can be applied to the item.
      tags:
        - V1Items
  "/v1/{location_id}/items/{item_id}/variations":
    post:
      deprecated: false
      description: Creates an item variation for an existing item.
      operationId: CreateVariation
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Creates an item variation for an existing item.
      tags:
        - V1Items
  "/v1/{location_id}/items/{item_id}/variations/{variation_id}":
    delete:
      deprecated: false
      description: Deletes an existing item variation from an item.
      operationId: DeleteVariation
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Deletes an existing item variation from an item.
      tags:
        - V1Items
    put:
      deprecated: false
      description: Modifies the details of an existing item variation.
      operationId: UpdateVariation
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Modifies the details of an existing item variation.
      tags:
        - V1Items
  "/v1/{location_id}/modifier-lists":
    get:
      deprecated: false
      description: Lists all of a location's modifier lists.
      operationId: ListModifierLists
      security:
        - oauth2:
            - ITEMS_READ
      summary: Lists all of a location's modifier lists.
      tags:
        - V1Items
    post:
      deprecated: false
      description: Creates an item modifier list and at least one modifier option for it.
      operationId: CreateModifierList
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Creates an item modifier list and at least one modifier option for it.
      tags:
        - V1Items
  "/v1/{location_id}/modifier-lists/{modifier_list_id}":
    delete:
      deprecated: false
      description: Deletes an existing item modifier list and all modifier options associated with it.
      operationId: DeleteModifierList
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Deletes an existing item modifier list and all modifier options associated with it.
      tags:
        - V1Items
    get:
      deprecated: false
      description: Provides the details for a single modifier list.
      operationId: RetrieveModifierList
      security:
        - oauth2:
            - ITEMS_READ
      summary: Provides the details for a single modifier list.
      tags:
        - V1Items
    put:
      deprecated: false
      description: Modifies the details of an existing item modifier list.
      operationId: UpdateModifierList
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Modifies the details of an existing item modifier list.
      tags:
        - V1Items
  "/v1/{location_id}/modifier-lists/{modifier_list_id}/modifier-options":
    post:
      deprecated: false
      description: Creates an item modifier option and adds it to a modifier list.
      operationId: CreateModifierOption
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Creates an item modifier option and adds it to a modifier list.
      tags:
        - V1Items
  "/v1/{location_id}/modifier-lists/{modifier_list_id}/modifier-options/{modifier_option_id}":
    delete:
      deprecated: false
      description: Deletes an existing item modifier option from a modifier list.
      operationId: DeleteModifierOption
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Deletes an existing item modifier option from a modifier list.
      tags:
        - V1Items
    put:
      deprecated: false
      description: Modifies the details of an existing item modifier option.
      operationId: UpdateModifierOption
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Modifies the details of an existing item modifier option.
      tags:
        - V1Items
  "/v1/{location_id}/orders":
    get:
      deprecated: false
      description: Provides summary information for a merchant's online store orders.
      operationId: ListOrders
      security:
        - oauth2:
            - ORDERS_READ
      summary: Provides summary information for a merchant's online store orders.
      tags:
        - V1Transactions
  "/v1/{location_id}/orders/{order_id}":
    get:
      deprecated: false
      description: Provides comprehensive information for a single online store order, including the order's history.
      operationId: RetrieveOrder
      security:
        - oauth2:
            - ORDERS_READ
      summary: Provides comprehensive information for a single online store order, including the order's history.
      tags:
        - V1Transactions
    put:
      deprecated: false
      description: "Updates the details of an online store order. Every update you perform on an order corresponds to one of three actions:"
      operationId: UpdateOrder
      security:
        - oauth2:
            - ORDERS_WRITE
      summary: "Updates the details of an online store order. Every update you perform on an order corresponds to one of three actions:"
      tags:
        - V1Transactions
  "/v1/{location_id}/pages":
    get:
      deprecated: false
      description: Lists all of a location's Favorites pages in Square Register.
      operationId: ListPages
      security:
        - oauth2:
            - ITEMS_READ
      summary: Lists all of a location's Favorites pages in Square Register.
      tags:
        - V1Items
    post:
      deprecated: false
      description: Creates a Favorites page in Square Register.
      operationId: CreatePage
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Creates a Favorites page in Square Register.
      tags:
        - V1Items
  "/v1/{location_id}/pages/{page_id}":
    delete:
      deprecated: false
      description: Deletes an existing Favorites page and all of its cells.
      operationId: DeletePage
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Deletes an existing Favorites page and all of its cells.
      tags:
        - V1Items
    put:
      deprecated: false
      description: Modifies the details of a Favorites page in Square Register.
      operationId: UpdatePage
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Modifies the details of a Favorites page in Square Register.
      tags:
        - V1Items
  "/v1/{location_id}/pages/{page_id}/cells":
    delete:
      deprecated: false
      description: Deletes a cell from a Favorites page in Square Register.
      operationId: DeletePageCell
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Deletes a cell from a Favorites page in Square Register.
      tags:
        - V1Items
    put:
      deprecated: false
      description: Modifies a cell of a Favorites page in Square Register.
      operationId: UpdatePageCell
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: Modifies a cell of a Favorites page in Square Register.
      tags:
        - V1Items
  "/v1/{location_id}/payments":
    get:
      deprecated: false
      description: Provides summary information for all payments taken by a merchant or any of the merchant's mobile staff during a date range. Date ranges cannot exceed one year in length. See Date ranges for details of inclusive and exclusive dates.
      operationId: ListPayments
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: Provides summary information for all payments taken by a merchant or any of the merchant's mobile staff during a date range. Date ranges cannot exceed one year in length. See Date ranges for details of inclusive and exclusive dates.
      tags:
        - V1Transactions
  "/v1/{location_id}/payments/{payment_id}":
    get:
      deprecated: false
      description: Provides comprehensive information for a single payment.
      operationId: RetrievePayment
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: Provides comprehensive information for a single payment.
      tags:
        - V1Transactions
  "/v1/{location_id}/refunds":
    get:
      deprecated: false
      description: Provides the details for all refunds initiated by a merchant or any of the merchant's mobile staff during a date range. Date ranges cannot exceed one year in length.
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: Provides the details for all refunds initiated by a merchant or any of the merchant's mobile staff during a date range. Date ranges cannot exceed one year in length.
      tags:
        - V1Transactions
    post:
      deprecated: false
      description: Issues a refund for a previously processed payment. You must issue a refund within 60 days of the associated payment.
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: Issues a refund for a previously processed payment. You must issue a refund within 60 days of the associated payment.
      tags:
        - V1Transactions
  "/v1/{location_id}/settlements":
    get:
      deprecated: false
      description: "Provides summary information for all deposits and withdrawals initiated by Square to a merchant's bank account during a date range. Date ranges cannot exceed one year in length. "
      operationId: ListSettlements
      security:
        - oauth2:
            - SETTLEMENTS_READ
      summary: Provides summary information for all deposits and withdrawals initiated by Square to a merchant's bank account during a date range. Date ranges cannot exceed one year in length.
      tags:
        - V1Transactions
  "/v1/{location_id}/settlements/{settlement_id}":
    get:
      deprecated: false
      description: Provides comprehensive information for a single settlement, including the entries that contribute to the settlement's total.
      operationId: RetrieveSettlement
      security:
        - oauth2:
            - SETTLEMENTS_READ
      summary: Provides comprehensive information for a single settlement, including the entries that contribute to the settlement's total.
      tags:
        - V1Transactions
  /v2/catalog/batch-delete:
    post:
      description: >-
        Deletes a set of [CatalogItem](#type-catalogitem)s based on the

        provided list of target IDs and returns a set of successfully deleted IDs in

        the response. Deletion is a cascading event such that all children of the

        targeted object are also deleted. For example, deleting a CatalogItem will

        also delete all of its [CatalogItemVariation](#type-catalogitemvariation)

        children.


        `BatchDeleteCatalogObjects` succeeds even if only a portion of the targeted

        IDs can be deleted. The response will only include IDs that were

        actually deleted.
      operationId: BatchDeleteCatalogObjects
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: BatchDeleteCatalogObjects
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_WRITE
  /v2/catalog/batch-retrieve:
    post:
      description: >-
        Returns a set of objects based on the provided ID.

        Each [CatalogItem](#type-catalogitem) returned in the set includes all of its

        child information including: all of its

        [CatalogItemVariation](#type-catalogitemvariation) objects, references to

        its [CatalogModifierList](#type-catalogmodifierlist) objects, and the ids of

        any [CatalogTax](#type-catalogtax) objects that apply to it.
      operationId: BatchRetrieveCatalogObjects
      security:
        - oauth2:
            - ITEMS_READ
      summary: BatchRetrieveCatalogObjects
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_READ
  /v2/catalog/batch-upsert:
    post:
      description: >-
        Creates or updates up to 10,000 target objects based on the provided

        list of objects. The target objects are grouped into batches and each batch is

        inserted/updated in an all-or-nothing manner. If an object within a batch is

        malformed in some way, or violates a database constraint, the entire batch

        containing that item will be disregarded. However, other batches in the same

        request may still succeed. Each batch may contain up to 1,000 objects, and

        batches will be processed in order as long as the total object count for the

        request (items, variations, modifier lists, discounts, and taxes) is no more

        than 10,000.
      operationId: BatchUpsertCatalogObjects
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: BatchUpsertCatalogObjects
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_WRITE
  /v2/catalog/info:
    get:
      description: >-
        Returns information about the Square Catalog API, such as batch size

        limits for `BatchUpsertCatalogObjects`.
      operationId: CatalogInfo
      security:
        - oauth2:
            - ITEMS_READ
      summary: CatalogInfo
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_READ
  /v2/catalog/list:
    get:
      description: >-
        Returns a list of [CatalogObject](#type-catalogobject)s that includes

        all objects of a set of desired types (for example, all [CatalogItem](#type-catalogitem)

        and [CatalogTax](#type-catalogtax) objects) in the catalog. The types parameter

        is specified as a comma-separated list of valid [CatalogObject](#type-catalogobject) types:

        `ITEM`, `ITEM_VARIATION`, `MODIFIER`, `MODIFIER_LIST`, `CATEGORY`, `DISCOUNT`, `TAX`.
      operationId: ListCatalog
      security:
        - oauth2:
            - ITEMS_READ
      summary: ListCatalog
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_READ
  /v2/catalog/object:
    post:
      description: Creates or updates the target [CatalogObject](#type-catalogobject).
      operationId: UpsertCatalogObject
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: UpsertCatalogObject
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_WRITE
  "/v2/catalog/object/{object_id}":
    delete:
      description: >-
        Deletes a single [CatalogObject](#type-catalogobject) based on the

        provided ID and returns the set of successfully deleted IDs in the response.

        Deletion is a cascading event such that all children of the targeted object

        are also deleted. For example, deleting a [CatalogItem](#type-catalogitem)

        will also delete all of its

        [CatalogItemVariation](#type-catalogitemvariation) children.
      operationId: DeleteCatalogObject
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: DeleteCatalogObject
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_WRITE
    get:
      description: >-
        Returns a single [CatalogItem](#type-catalogitem) as a

        [CatalogObject](#type-catalogobject) based on the provided ID. The returned

        object includes all of the relevant [CatalogItem](#type-catalogitem)

        information including: [CatalogItemVariation](#type-catalogitemvariation)

        children, references to its

        [CatalogModifierList](#type-catalogmodifierlist) objects, and the ids of

        any [CatalogTax](#type-catalogtax) objects that apply to it.
      operationId: RetrieveCatalogObject
      security:
        - oauth2:
            - ITEMS_READ
      summary: RetrieveCatalogObject
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_READ
  /v2/catalog/search:
    post:
      description: >-
        Queries the targeted catalog using a variety of query types

        ([CatalogQuerySortedAttribute](#type-catalogquerysortedattribute),

        ([CatalogQueryExact](#type-catalogqueryexact),

        ([CatalogQueryRange](#type-catalogqueryrange),

        ([CatalogQueryText](#type-catalogquerytext),

        ([CatalogQueryItemsForTax](#type-catalogqueryitemsfortax),

        ([CatalogQueryItemsForModifierList](#type-catalogqueryitemsformodifierlist)).
      operationId: SearchCatalogObjects
      security:
        - oauth2:
            - ITEMS_READ
      summary: SearchCatalogObjects
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_READ
  /v2/catalog/update-item-modifier-lists:
    post:
      description: >-
        Updates the [CatalogModifierList](#type-catalogmodifierlist) objects

        that apply to the targeted [CatalogItem](#type-catalogitem) without having

        to perform an upsert on the entire item.
      operationId: UpdateItemModifierLists
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: UpdateItemModifierLists
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_WRITE
  /v2/catalog/update-item-taxes:
    post:
      description: >-
        Updates the [CatalogTax](#type-catalogtax) objects that apply to the

        targeted [CatalogItem](#type-catalogitem) without having to perform an

        upsert on the entire item.
      operationId: UpdateItemTaxes
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: UpdateItemTaxes
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_WRITE
  /v2/customers:
    get:
      description: Lists a business's customers.
      operationId: ListCustomers
      security:
        - oauth2:
            - CUSTOMERS_READ
      summary: ListCustomers
      tags:
        - Customers
      x-oauthpermissions:
        - CUSTOMERS_READ
    post:
      description: >-
        Creates a new customer for a business, which can have associated cards on file.


        You must provide __at least one__ of the following values in your request to this

        endpoint:


        - `given_name`

        - `family_name`

        - `company_name`

        - `email_address`

        - `phone_number`


        This endpoint does not accept an idempotency key. If you accidentally create

        a duplicate customer, you can delete it with the

        [DeleteCustomer](#endpoint-deletecustomer) endpoint.
      operationId: CreateCustomer
      security:
        - oauth2:
            - CUSTOMERS_WRITE
      summary: CreateCustomer
      tags:
        - Customers
      x-oauthpermissions:
        - CUSTOMERS_WRITE
  "/v2/customers/{customer_id}":
    delete:
      description: Deletes a customer from a business, along with any linked cards on file.
      operationId: DeleteCustomer
      security:
        - oauth2:
            - CUSTOMERS_WRITE
      summary: DeleteCustomer
      tags:
        - Customers
      x-oauthpermissions:
        - CUSTOMERS_WRITE
    get:
      description: Returns details for a single customer.
      operationId: RetrieveCustomer
      security:
        - oauth2:
            - CUSTOMERS_READ
      summary: RetrieveCustomer
      tags:
        - Customers
      x-oauthpermissions:
        - CUSTOMERS_READ
    put:
      description: >-
        Updates the details of an existing customer.

        The ID of the customer may change if the customer has been merged into another customer.


        You cannot edit a customer's cards on file with this endpoint. To make changes

        to a card on file, you must delete the existing card on file with the

        [DeleteCustomerCard](#endpoint-deletecustomercard) endpoint, then create a new one with the

        [CreateCustomerCard](#endpoint-createcustomercard) endpoint.
      operationId: UpdateCustomer
      security:
        - oauth2:
            - CUSTOMERS_WRITE
      summary: UpdateCustomer
      tags:
        - Customers
      x-oauthpermissions:
        - CUSTOMERS_WRITE
  "/v2/customers/{customer_id}/cards":
    post:
      description: >-
        Adds a card on file to an existing customer. In the United States

        Square takes care of automatically updating any cards on file that might

        have expired since you first attached them to a customer.
      operationId: CreateCustomerCard
      security:
        - oauth2:
            - CUSTOMERS_WRITE
      summary: CreateCustomerCard
      tags:
        - Customers
      x-oauthpermissions:
        - CUSTOMERS_WRITE
  "/v2/customers/{customer_id}/cards/{card_id}":
    delete:
      description: Removes a card on file from a customer.
      operationId: DeleteCustomerCard
      security:
        - oauth2:
            - CUSTOMERS_WRITE
      summary: DeleteCustomerCard
      tags:
        - Customers
      x-oauthpermissions:
        - CUSTOMERS_WRITE
  /v2/locations:
    get:
      description: >-
        Provides the details for all of a business's locations.


        Most other Connect API endpoints have a required `location_id` path parameter.

        The `id` field of the [`Location`](#type-location) objects returned by this

        endpoint correspond to that `location_id` parameter.
      security:
        - oauth2:
            - MERCHANT_PROFILE_READ
      summary: ListLocations
      tags:
        - Locations
      x-oauthpermissions:
        - MERCHANT_PROFILE_READ
  "/v2/locations/{location_id}/checkouts":
    post:
      description: >-
        Creates a [Checkout](#type-checkout) response that links a

        `checkoutId` and `checkout_page_url` that customers can be directed to in

        order to provide their payment information using a payment processing

        workflow hosted on connect.squareup.com.
      operationId: CreateCheckout
      security:
        - oauth2:
            - PAYMENTS_WRITE
            - ORDERS_WRITE
      summary: CreateCheckout
      tags:
        - Checkout
      x-oauthpermissions:
        - PAYMENTS_WRITE
        - ORDERS_WRITE
  "/v2/locations/{location_id}/refunds":
    get:
      description: >-
        Lists refunds for one of a business's locations.


        Refunds with a `status` of `PENDING` are not currently included in this

        endpoint's response.


        Max results per [page](#paginatingresults): 50
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: ListRefunds
      tags:
        - Transactions
      x-oauthpermissions:
        - PAYMENTS_READ
  "/v2/locations/{location_id}/transactions":
    get:
      description: >-
        Lists transactions for a particular location.


        Max results per [page](#paginatingresults): 50
      operationId: ListTransactions
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: ListTransactions
      tags:
        - Transactions
      x-oauthpermissions:
        - PAYMENTS_READ
    post:
      description: >-
        Charges a card represented by a card nonce or a customer's card on file.


        Your request to this endpoint must include _either_:


        - A value for the `card_nonce` parameter (to charge a card nonce generated

        with the `SqPaymentForm`)

        - Values for the `customer_card_id` and `customer_id` parameters (to charge

        a customer's card on file)


        In order for an e-commerce payment to potentially qualify for

        [Square chargeback protection](https://squareup.com/help/article/5394), you

        _must_ provide values for the following parameters in your request:


        - `buyer_email_address`

        - At least one of `billing_address` or `shipping_address`


        When this response is returned, the amount of Square's processing fee might not yet be

        calculated. To obtain the processing fee, wait about ten seconds and call

        [RetrieveTransaction](#endpoint-retrievetransaction). See the `processing_fee_money`

        field of each [Tender included](#type-tender) in the transaction.
      operationId: Charge
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: Charge
      tags:
        - Transactions
      x-oauthpermissions:
        - PAYMENTS_WRITE
  "/v2/locations/{location_id}/transactions/{transaction_id}":
    get:
      description: Retrieves details for a single transaction.
      operationId: RetrieveTransaction
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: RetrieveTransaction
      tags:
        - Transactions
      x-oauthpermissions:
        - PAYMENTS_READ
  "/v2/locations/{location_id}/transactions/{transaction_id}/capture":
    post:
      description: >-
        Captures a transaction that was created with the [Charge](#endpoint-charge)

        endpoint with a `delay_capture` value of `true`.


        See [Delayed capture transactions](/articles/delayed-capture-transactions/)

        for more information.
      operationId: CaptureTransaction
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: CaptureTransaction
      tags:
        - Transactions
      x-oauthpermissions:
        - PAYMENTS_WRITE
  "/v2/locations/{location_id}/transactions/{transaction_id}/refund":
    post:
      description: >-
        Initiates a refund for a previously charged tender.


        You must issue a refund within 120 days of the associated payment. See

        (this article)[https://squareup.com/help/us/en/article/5060] for more information

        on refund behavior.
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: CreateRefund
      tags:
        - Transactions
      x-oauthpermissions:
        - PAYMENTS_WRITE
  "/v2/locations/{location_id}/transactions/{transaction_id}/void":
    post:
      description: >-
        Cancels a transaction that was created with the [Charge](#endpoint-charge)

        endpoint with a `delay_capture` value of `true`.


        See [Delayed capture transactions](/articles/delayed-capture-transactions/)

        for more information.
      operationId: VoidTransaction
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: VoidTransaction
      tags:
        - Transactions
      x-oauthpermissions:
        - PAYMENTS_WRITE