swagger: '2.0'
schemes:
  - https
host: connect.squareup.com
info:
  contact:
    email: developers@squareup.com
    name: Square Developer Platform
    url: 'https://squareup.com/developers'
  description: Client library for accessing the Square Connect APIs
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  termsOfService: 'https://connect.squareup.com/tos'
  title: Square Connect
  version: '2.0'
  x-logo:
    url: 'http://square.github.io/images/logo.png'
  x-origin:
    format: swagger
    url: 'https://raw.githubusercontent.com/square/connect-api-specification/master/api.json'
    version: '2.0'
  x-providerName: squareup.com
securityDefinitions:
  oauth2:
    authorizationUrl: 'https://connect.squareup.com/oauth2/authorize?<PARAMETERS>'
    flow: accessCode
    scopes:
      BANK_ACCOUNTS_READ: GET endpoints related to a merchant's bank accounts
      CUSTOMERS_READ: ' GET endpoints related to customer management'
      CUSTOMERS_WRITE: 'POST, PUT, and DELETE endpoints related to customer management'
      EMPLOYEES_READ: GET endpoints related to employee management
      EMPLOYEES_WRITE: 'POST, PUT, and DELETE endpoints related to employee management'
      ITEMS_READ: GET endpoints related to a merchant's item library
      ITEMS_WRITE: 'POST, PUT, and DELETE endpoints related to a merchant''s item library'
      MERCHANT_PROFILE_READ: GET endpoints related to a merchant's business and location entities. Almost all Connect API applications need this permission in order to obtain a merchant's location IDs
      ORDERS_READ: GET endpoints related to a merchant's Square online store.
      ORDERS_WRITE: 'POST, PUT, and DELETE endpoints related to a merchant''s Square online store'
      PAYMENTS_READ: GET endpoints related to transactions and refunds
      PAYMENTS_WRITE: 'POST, PUT, and DELETE endpoints related to transactions and refunds. E-commerce applications must request this permission'
      SETTLEMENTS_READ: GET endpoints related to settlements (deposits)
      TIMECARDS_READ: GET endpoints related to employee timecards
      TIMECARDS_WRITE: 'POST, PUT, and DELETE endpoints related to employee timecards'
    tokenUrl: 'https://connect.squareup.com/oauth2/token'
    type: oauth2
paths:
  /v2/customers:
    get:
      description: Lists a business's customers.
      operationId: ListCustomers
      summary: ListCustomers
      tags:
        - Customer
      x-oauthpermissions:
        - CUSTOMERS_READ
    post:
      description: |-
        Creates a new customer for a business, which can have associated cards on file.

        You must provide __at least one__ of the following values in your request to this
        endpoint:

        - `given_name`
        - `family_name`
        - `company_name`
        - `email_address`
        - `phone_number`

        This endpoint does not accept an idempotency key. If you accidentally create
        a duplicate customer, you can delete it with the
        [DeleteCustomer](#endpoint-deletecustomer) endpoint.
      operationId: CreateCustomer
      summary: CreateCustomer
      tags:
        - Customer
      x-oauthpermissions:
        - CUSTOMERS_WRITE
  '/v2/customers/{customer_id}':
    delete:
      description: 'Deletes a customer from a business, along with any linked cards on file.'
      operationId: DeleteCustomer
      summary: DeleteCustomer
      tags:
        - Customer
      x-oauthpermissions:
        - CUSTOMERS_WRITE
    get:
      description: Returns details for a single customer.
      operationId: RetrieveCustomer
      summary: RetrieveCustomer
      tags:
        - Customer
      x-oauthpermissions:
        - CUSTOMERS_READ
    put:
      description: |-
        Updates the details of an existing customer.

        You cannot edit a customer's cards on file with this endpoint. To make changes
        to a card on file, you must delete the existing card on file with the
        [DeleteCustomerCard](#endpoint-deletecustomercard) endpoint, then create a new one with the
        [CreateCustomerCard](#endpoint-createcustomercard) endpoint.
      operationId: UpdateCustomer
      summary: UpdateCustomer
      tags:
        - Customer
      x-oauthpermissions:
        - CUSTOMERS_WRITE
  '/v2/customers/{customer_id}/cards':
    post:
      description: Adds a card on file to an existing customer.
      operationId: CreateCustomerCard
      summary: CreateCustomerCard
      tags:
        - Customer.Card
      x-oauthpermissions:
        - CUSTOMERS_WRITE
  '/v2/customers/{customer_id}/cards/{card_id}':
    delete:
      description: Removes a card on file from a customer.
      operationId: DeleteCustomerCard
      summary: DeleteCustomerCard
      tags:
        - Customer.Card
      x-oauthpermissions:
        - CUSTOMERS_WRITE
  /v2/locations:
    get:
      description: |-
        Provides the details for all of a business's locations.

        Most other Connect API endpoints have a required `location_id` path parameter.
        The `id` field of the [`Location`](#type-location) objects returned by this
        endpoint correspond to that `location_id` parameter.
      operationId: ListLocations
      summary: ListLocations
      tags:
        - Location
      x-oauthpermissions:
        - MERCHANT_PROFILE_READ
  '/v2/locations/{location_id}/checkouts':
    post:
      description: |-
        Creates a [Checkout](#type-checkout) response that links a
        `checkoutId` and `checkout_page_url` that customers can be directed to in
        order to provide their payment information using a payment processing
        workflow hosted on connect.squareup.com.
      operationId: CreateCheckout
      summary: CreateCheckout
      tags:
        - Checkout
      x-oauthpermissions:
        - ORDERS_V2_WRITE
        - PAYMENTS_WRITE
  '/v2/locations/{location_id}/refunds':
    get:
      description: |-
        Lists refunds for one of a business's locations.

        Refunds with a `status` of `PENDING` are not currently included in this
        endpoint's response.

        Max results per [page](#paginatingresults): 50
      operationId: ListRefunds
      summary: ListRefunds
      tags:
        - Refund
      x-oauthpermissions:
        - PAYMENTS_READ
  '/v2/locations/{location_id}/transactions':
    get:
      description: |-
        Lists transactions for a particular location.

        Max results per [page](#paginatingresults): 50
      operationId: ListTransactions
      summary: ListTransactions
      tags:
        - Transaction
      x-oauthpermissions:
        - PAYMENTS_READ
    post:
      description: |-
        Charges a card represented by a card nonce or a customer's card on file.

        Your request to this endpoint must include _either_:

        - A value for the `card_nonce` parameter (to charge a card nonce generated
        with the `SqPaymentForm`)
        - Values for the `customer_card_id` and `customer_id` parameters (to charge
        a customer's card on file)

        In order for an e-commerce payment to potentially qualify for
        [Square chargeback protection](https://squareup.com/help/article/5394), you
        _must_ provide values for the following parameters in your request:

        - `buyer_email_address`
        - At least one of `billing_address` or `shipping_address`

        When this response is returned, the amount of Square's processing fee might not yet be
        calculated. To obtain the processing fee, wait about ten seconds and call
        [RetrieveTransaction](#endpoint-retrievetransaction). See the `processing_fee_money`
        field of each [Tender included](#type-tender) in the transaction.
      operationId: Charge
      summary: Charge
      tags:
        - Transaction
      x-oauthpermissions:
        - PAYMENTS_WRITE
  '/v2/locations/{location_id}/transactions/{transaction_id}':
    get:
      description: Retrieves details for a single transaction.
      operationId: RetrieveTransaction
      summary: RetrieveTransaction
      tags:
        - Transaction
      x-oauthpermissions:
        - PAYMENTS_READ
  '/v2/locations/{location_id}/transactions/{transaction_id}/capture':
    post:
      description: |-
        Captures a transaction that was created with the [Charge](#endpoint-charge)
        endpoint with a `delay_capture` value of `true`.

        See [Delayed capture transactions](/articles/delayed-capture-transactions/)
        for more information.
      operationId: CaptureTransaction
      summary: CaptureTransaction
      tags:
        - Transaction
      x-oauthpermissions:
        - PAYMENTS_WRITE
  '/v2/locations/{location_id}/transactions/{transaction_id}/refund':
    post:
      description: Initiates a refund for a previously charged tender.
      operationId: CreateRefund
      summary: CreateRefund
      tags:
        - Refund
      x-oauthpermissions:
        - PAYMENTS_WRITE
  '/v2/locations/{location_id}/transactions/{transaction_id}/void':
    post:
      description: |-
        Cancels a transaction that was created with the [Charge](#endpoint-charge)
        endpoint with a `delay_capture` value of `true`.

        See [Delayed capture transactions](/articles/delayed-capture-transactions/)
        for more information.
      operationId: VoidTransaction
      summary: VoidTransaction
      tags:
        - Transaction
      x-oauthpermissions:
        - PAYMENTS_WRITE