swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /adexchangeseller/v1
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Gives Ad Exchange seller users access to their inventory and the ability to generate reports
  title: Ad Exchange Seller
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.doubleclickbygoogle.com/static/core/img/doubleclick-google-logo-wide.svg'
  x-origin:
    format: google
    url: 'https://www.googleapis.com/discovery/v1/apis/adexchangeseller/v1/rest'
    version: v1
  x-preferred: false
  x-providerName: googleapis.com
  x-serviceName: adexchangeseller
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/adexchange.seller': View and manage your Ad Exchange data
      'https://www.googleapis.com/auth/adexchange.seller.readonly': View your Ad Exchange data
    type: oauth2
tags:
  - name: adclients
  - name: adunits
  - name: customchannels
  - name: reports
  - name: urlchannels
paths:
  /adclients:
    get:
      description: List all ad clients in this Ad Exchange account.
      operationId: adexchangeseller.adclients.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - adclients
  '/adclients/{adClientId}/adunits':
    get:
      description: List all ad units in the specified ad client for this Ad Exchange account.
      operationId: adexchangeseller.adunits.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - adunits
  '/adclients/{adClientId}/adunits/{adUnitId}':
    get:
      description: Gets the specified ad unit in the specified ad client.
      operationId: adexchangeseller.adunits.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - adunits
  '/adclients/{adClientId}/adunits/{adUnitId}/customchannels':
    get:
      description: List all custom channels which the specified ad unit belongs to.
      operationId: adexchangeseller.adunits.customchannels.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - adunits
  '/adclients/{adClientId}/customchannels':
    get:
      description: List all custom channels in the specified ad client for this Ad Exchange account.
      operationId: adexchangeseller.customchannels.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - customchannels
  '/adclients/{adClientId}/customchannels/{customChannelId}':
    get:
      description: Get the specified custom channel from the specified ad client.
      operationId: adexchangeseller.customchannels.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - customchannels
  '/adclients/{adClientId}/customchannels/{customChannelId}/adunits':
    get:
      description: List all ad units in the specified custom channel.
      operationId: adexchangeseller.customchannels.adunits.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - customchannels
  '/adclients/{adClientId}/urlchannels':
    get:
      description: List all URL channels in the specified ad client for this Ad Exchange account.
      operationId: adexchangeseller.urlchannels.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - urlchannels
  /reports:
    get:
      description: Generate an Ad Exchange report based on the report request sent in the query parameters. Returns the result as JSON; to retrieve output in CSV format specify "alt=csv" as a query parameter.
      operationId: adexchangeseller.reports.generate
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - reports
  /reports/saved:
    get:
      description: List all saved reports in this Ad Exchange account.
      operationId: adexchangeseller.reports.saved.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - reports
  '/reports/{savedReportId}':
    get:
      description: Generate an Ad Exchange report based on the saved report ID sent in the query parameters.
      operationId: adexchangeseller.reports.saved.generate
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - reports