# coding: utf-8

"""
    ApiManagementClient

    Use these REST APIs for performing operations on who is going to receive notifications associated with your Azure API Management deployment.

    The version of the OpenAPI document: 2018-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.recipient_user_collection import RecipientUserCollection

class TestRecipientUserCollection(unittest.TestCase):
    """RecipientUserCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecipientUserCollection:
        """Test RecipientUserCollection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecipientUserCollection`
        """
        model = RecipientUserCollection()
        if include_optional:
            return RecipientUserCollection(
                next_link = '',
                value = [
                    openapi_client.models.recipient_user_contract.RecipientUserContract(
                        properties = openapi_client.models.recipient_users_contract_properties.RecipientUsersContractProperties(
                            user_id = '', ), )
                    ]
            )
        else:
            return RecipientUserCollection(
        )
        """

    def testRecipientUserCollection(self):
        """Test RecipientUserCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
