# coding: utf-8

"""
    Influx OSS API Service

    # Authentication  &lt;!-- ReDoc-Inject: &lt;security-definitions&gt; --&gt;

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class NotificationEndpointType(str, Enum):
    """
    NotificationEndpointType
    """

    """
    allowed enum values
    """
    SLACK = 'slack'
    PAGERDUTY = 'pagerduty'
    HTTP = 'http'
    TELEGRAM = 'telegram'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NotificationEndpointType from a JSON string"""
        return cls(json.loads(json_str))


