# coding: utf-8

"""
    StorSimple8000SeriesManagementClient

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2017-06-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.hardware_component_group_list import HardwareComponentGroupList

class TestHardwareComponentGroupList(unittest.TestCase):
    """HardwareComponentGroupList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HardwareComponentGroupList:
        """Test HardwareComponentGroupList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HardwareComponentGroupList`
        """
        model = HardwareComponentGroupList()
        if include_optional:
            return HardwareComponentGroupList(
                value = [
                    openapi_client.models.hardware_component_group.HardwareComponentGroup(
                        properties = openapi_client.models.hardware_component_group_properties.HardwareComponentGroupProperties(
                            components = [
                                openapi_client.models.hardware_component.HardwareComponent(
                                    component_id = '', 
                                    display_name = '', 
                                    status = 'Unknown', 
                                    status_display_name = '', )
                                ], 
                            display_name = '', 
                            last_updated_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), )
                    ]
            )
        else:
            return HardwareComponentGroupList(
                value = [
                    openapi_client.models.hardware_component_group.HardwareComponentGroup(
                        properties = openapi_client.models.hardware_component_group_properties.HardwareComponentGroupProperties(
                            components = [
                                openapi_client.models.hardware_component.HardwareComponent(
                                    component_id = '', 
                                    display_name = '', 
                                    status = 'Unknown', 
                                    status_display_name = '', )
                                ], 
                            display_name = '', 
                            last_updated_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), )
                    ],
        )
        """

    def testHardwareComponentGroupList(self):
        """Test HardwareComponentGroupList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
