from dataclasses import dataclass, field
from enum import Enum

class AppLaunchStatusEnum(str, Enum):
    READY_FOR_CONFIGURATION = "READY_FOR_CONFIGURATION"
    CONFIGURATION_IN_PROGRESS = "CONFIGURATION_IN_PROGRESS"
    CONFIGURATION_INVALID = "CONFIGURATION_INVALID"
    READY_FOR_LAUNCH = "READY_FOR_LAUNCH"
    VALIDATION_IN_PROGRESS = "VALIDATION_IN_PROGRESS"
    LAUNCH_PENDING = "LAUNCH_PENDING"
    LAUNCH_IN_PROGRESS = "LAUNCH_IN_PROGRESS"
    LAUNCHED = "LAUNCHED"
    PARTIALLY_LAUNCHED = "PARTIALLY_LAUNCHED"
    DELTA_LAUNCH_IN_PROGRESS = "DELTA_LAUNCH_IN_PROGRESS"
    DELTA_LAUNCH_FAILED = "DELTA_LAUNCH_FAILED"
    LAUNCH_FAILED = "LAUNCH_FAILED"
    TERMINATE_IN_PROGRESS = "TERMINATE_IN_PROGRESS"
    TERMINATE_FAILED = "TERMINATE_FAILED"
    TERMINATED = "TERMINATED"

