# flake8: noqa

# import apis into api package
from openapi_client.api.aliases_movie_television_show_aliases_api import AliasesMovieTelevisionShowAliasesApi
from openapi_client.api.awards_television_movies_api import AwardsTelevisionMoviesApi
from openapi_client.api.calendar_television_show_schedules_api import CalendarTelevisionShowSchedulesApi
from openapi_client.api.cast_crew_cast_crew_in_movies_television_shows_api import CastCrewCastCrewInMoviesTelevisionShowsApi
from openapi_client.api.images_movie_television_show_images_api import ImagesMovieTelevisionShowImagesApi
from openapi_client.api.magnets_magnet_hashes_of_movies_television_shows_api import MagnetsMagnetHashesOfMoviesTelevisionShowsApi
from openapi_client.api.miscellaneous_conversion_other_utilities_api import MiscellaneousConversionOtherUtilitiesApi
from openapi_client.api.movies_movies_documentaries_made_for_television_movies_api import MoviesMoviesDocumentariesMadeForTelevisionMoviesApi
from openapi_client.api.music_artists_bands_tracks_album_art_cover_art_videos_api import MusicArtistsBandsTracksAlbumArtCoverArtVideosApi
from openapi_client.api.ratings_movie_television_show_ratings_api import RatingsMovieTelevisionShowRatingsApi
from openapi_client.api.television_shows_episodes_statuses_api import TelevisionShowsEpisodesStatusesApi
from openapi_client.api.trailers_movie_television_show_trailers_api import TrailersMovieTelevisionShowTrailersApi

