package shared

type RoomParticipantPublishedTrackEnumKindEnum string

const (
	RoomParticipantPublishedTrackEnumKindEnumAudio RoomParticipantPublishedTrackEnumKindEnum = "audio"
	RoomParticipantPublishedTrackEnumKindEnumVideo RoomParticipantPublishedTrackEnumKindEnum = "video"
	RoomParticipantPublishedTrackEnumKindEnumData  RoomParticipantPublishedTrackEnumKindEnum = "data"
)
