{
  "swagger": "2.0",
  "info": {
    "title": "Google Analytics API",
    "x-serviceName": "analytics",
    "description": "View and manage your Google Analytics data",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v3",
    "x-providerName": "googleapis.com",
    "x-origin": {
      "format": "google",
      "version": "v1",
      "url": "https://www.googleapis.com/discovery/v1/apis/analytics/v3/rest"
    },
    "x-logo": "https://www.google.com/images/srpr/logo11w.png"
  },
  "host": "www.googleapis.com",
  "basePath": "/analytics/v3",
  "schemes": [
    "https"
  ],
  "paths": {
    "/data/ga": {
      "get": {
        "description": "Returns Analytics data for a view (profile).",
        "operationId": "analytics.data.ga.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "data"
        ]
      }
    },
    "/data/mcf": {
      "get": {
        "description": "Returns Analytics Multi-Channel Funnels data for a view (profile).",
        "operationId": "analytics.data.mcf.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "data"
        ]
      }
    },
    "/data/realtime": {
      "get": {
        "description": "Returns real time data for a view (profile).",
        "operationId": "analytics.data.realtime.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "data"
        ]
      }
    },
    "/management/accountSummaries": {
      "get": {
        "description": "Lists account summaries (lightweight tree comprised of accounts/properties/profiles) to which the user has access.",
        "operationId": "analytics.management.accountSummaries.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/entityUserLinks/{linkId}": {
      "delete": {
        "description": "Removes a user from the given account.",
        "operationId": "analytics.management.accountUserLinks.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.manage.users"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "put": {
        "description": "Updates permissions for an existing user on the given account.",
        "operationId": "analytics.management.accountUserLinks.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.manage.users"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/entityUserLinks": {
      "post": {
        "description": "Adds a new user to the given account.",
        "operationId": "analytics.management.accountUserLinks.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.manage.users"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "get": {
        "description": "Lists account-user links for a given account.",
        "operationId": "analytics.management.accountUserLinks.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.manage.users",
              "https://www.googleapis.com/auth/analytics.manage.users.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts": {
      "get": {
        "description": "Lists all accounts to which the user has access.",
        "operationId": "analytics.management.accounts.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources": {
      "get": {
        "description": "List custom data sources to which the user has access.",
        "operationId": "analytics.management.customDataSources.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions/{customDimensionId}": {
      "get": {
        "description": "Get a custom dimension to which the user has access.",
        "operationId": "analytics.management.customDimensions.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "patch": {
        "description": "Updates an existing custom dimension. This method supports patch semantics.",
        "operationId": "analytics.management.customDimensions.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "put": {
        "description": "Updates an existing custom dimension.",
        "operationId": "analytics.management.customDimensions.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions": {
      "post": {
        "description": "Create a new custom dimension.",
        "operationId": "analytics.management.customDimensions.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "get": {
        "description": "Lists custom dimensions to which the user has access.",
        "operationId": "analytics.management.customDimensions.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics/{customMetricId}": {
      "get": {
        "description": "Get a custom metric to which the user has access.",
        "operationId": "analytics.management.customMetrics.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "patch": {
        "description": "Updates an existing custom metric. This method supports patch semantics.",
        "operationId": "analytics.management.customMetrics.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "put": {
        "description": "Updates an existing custom metric.",
        "operationId": "analytics.management.customMetrics.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics": {
      "post": {
        "description": "Create a new custom metric.",
        "operationId": "analytics.management.customMetrics.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "get": {
        "description": "Lists custom metrics to which the user has access.",
        "operationId": "analytics.management.customMetrics.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments/{experimentId}": {
      "delete": {
        "description": "Delete an experiment.",
        "operationId": "analytics.management.experiments.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "get": {
        "description": "Returns an experiment to which the user has access.",
        "operationId": "analytics.management.experiments.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "patch": {
        "description": "Update an existing experiment. This method supports patch semantics.",
        "operationId": "analytics.management.experiments.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "put": {
        "description": "Update an existing experiment.",
        "operationId": "analytics.management.experiments.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments": {
      "post": {
        "description": "Create a new experiment.",
        "operationId": "analytics.management.experiments.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "get": {
        "description": "Lists experiments to which the user has access.",
        "operationId": "analytics.management.experiments.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/filters/{filterId}": {
      "delete": {
        "description": "Delete a filter.",
        "operationId": "analytics.management.filters.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "get": {
        "description": "Returns a filters to which the user has access.",
        "operationId": "analytics.management.filters.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "patch": {
        "description": "Updates an existing filter. This method supports patch semantics.",
        "operationId": "analytics.management.filters.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "put": {
        "description": "Updates an existing filter.",
        "operationId": "analytics.management.filters.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/filters": {
      "post": {
        "description": "Create a new filter.",
        "operationId": "analytics.management.filters.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "get": {
        "description": "Lists all filters for an account",
        "operationId": "analytics.management.filters.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals/{goalId}": {
      "get": {
        "description": "Gets a goal to which the user has access.",
        "operationId": "analytics.management.goals.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "patch": {
        "description": "Updates an existing view (profile). This method supports patch semantics.",
        "operationId": "analytics.management.goals.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "put": {
        "description": "Updates an existing view (profile).",
        "operationId": "analytics.management.goals.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals": {
      "post": {
        "description": "Create a new goal.",
        "operationId": "analytics.management.goals.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "get": {
        "description": "Lists goals to which the user has access.",
        "operationId": "analytics.management.goals.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks/{linkId}": {
      "delete": {
        "description": "Delete a profile filter link.",
        "operationId": "analytics.management.profileFilterLinks.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "get": {
        "description": "Returns a single profile filter link.",
        "operationId": "analytics.management.profileFilterLinks.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "patch": {
        "description": "Update an existing profile filter link. This method supports patch semantics.",
        "operationId": "analytics.management.profileFilterLinks.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "put": {
        "description": "Update an existing profile filter link.",
        "operationId": "analytics.management.profileFilterLinks.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks": {
      "post": {
        "description": "Create a new profile filter link.",
        "operationId": "analytics.management.profileFilterLinks.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "get": {
        "description": "Lists all profile filter links for a profile.",
        "operationId": "analytics.management.profileFilterLinks.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks/{linkId}": {
      "delete": {
        "description": "Removes a user from the given view (profile).",
        "operationId": "analytics.management.profileUserLinks.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.manage.users"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "put": {
        "description": "Updates permissions for an existing user on the given view (profile).",
        "operationId": "analytics.management.profileUserLinks.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.manage.users"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks": {
      "post": {
        "description": "Adds a new user to the given view (profile).",
        "operationId": "analytics.management.profileUserLinks.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.manage.users"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "get": {
        "description": "Lists profile-user links for a given view (profile).",
        "operationId": "analytics.management.profileUserLinks.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.manage.users",
              "https://www.googleapis.com/auth/analytics.manage.users.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}": {
      "delete": {
        "description": "Deletes a view (profile).",
        "operationId": "analytics.management.profiles.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "get": {
        "description": "Gets a view (profile) to which the user has access.",
        "operationId": "analytics.management.profiles.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "patch": {
        "description": "Updates an existing view (profile). This method supports patch semantics.",
        "operationId": "analytics.management.profiles.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "put": {
        "description": "Updates an existing view (profile).",
        "operationId": "analytics.management.profiles.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/profiles": {
      "post": {
        "description": "Create a new view (profile).",
        "operationId": "analytics.management.profiles.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "get": {
        "description": "Lists views (profiles) to which the user has access.",
        "operationId": "analytics.management.profiles.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/segments": {
      "get": {
        "description": "Lists segments to which the user has access.",
        "operationId": "analytics.management.segments.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/unsampledReports/{unsampledReportId}": {
      "get": {
        "description": "Returns a single unsampled report.",
        "operationId": "analytics.management.unsampledReports.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/unsampledReports": {
      "post": {
        "description": "Create a new unsampled report.",
        "operationId": "analytics.management.unsampledReports.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "get": {
        "description": "Lists unsampled reports to which the user has access.",
        "operationId": "analytics.management.unsampledReports.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/deleteUploadData": {
      "post": {
        "description": "Delete data associated with a previous upload.",
        "operationId": "analytics.management.uploads.deleteUploadData",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/uploads/{uploadId}": {
      "get": {
        "description": "List uploads to which the user has access.",
        "operationId": "analytics.management.uploads.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/uploads": {
      "get": {
        "description": "List uploads to which the user has access.",
        "operationId": "analytics.management.uploads.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "post": {
        "description": "Upload data for a custom data source.",
        "operationId": "analytics.management.uploads.uploadData",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks/{webPropertyAdWordsLinkId}": {
      "delete": {
        "description": "Deletes a web property-AdWords link.",
        "operationId": "analytics.management.webPropertyAdWordsLinks.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "get": {
        "description": "Returns a web property-AdWords link to which the user has access.",
        "operationId": "analytics.management.webPropertyAdWordsLinks.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "patch": {
        "description": "Updates an existing webProperty-AdWords link. This method supports patch semantics.",
        "operationId": "analytics.management.webPropertyAdWordsLinks.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "put": {
        "description": "Updates an existing webProperty-AdWords link.",
        "operationId": "analytics.management.webPropertyAdWordsLinks.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks": {
      "post": {
        "description": "Creates a webProperty-AdWords link.",
        "operationId": "analytics.management.webPropertyAdWordsLinks.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "get": {
        "description": "Lists webProperty-AdWords links for a given web property.",
        "operationId": "analytics.management.webPropertyAdWordsLinks.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}": {
      "get": {
        "description": "Gets a web property to which the user has access.",
        "operationId": "analytics.management.webproperties.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "patch": {
        "description": "Updates an existing web property. This method supports patch semantics.",
        "operationId": "analytics.management.webproperties.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "put": {
        "description": "Updates an existing web property.",
        "operationId": "analytics.management.webproperties.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties": {
      "post": {
        "description": "Create a new property if the account has fewer than 20 properties. Web properties are visible in the Google Analytics interface only if they have at least one profile.",
        "operationId": "analytics.management.webproperties.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.edit"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "get": {
        "description": "Lists web properties to which the user has access.",
        "operationId": "analytics.management.webproperties.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks/{linkId}": {
      "delete": {
        "description": "Removes a user from the given web property.",
        "operationId": "analytics.management.webpropertyUserLinks.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.manage.users"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "put": {
        "description": "Updates permissions for an existing user on the given web property.",
        "operationId": "analytics.management.webpropertyUserLinks.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.manage.users"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks": {
      "post": {
        "description": "Adds a new user to the given web property.",
        "operationId": "analytics.management.webpropertyUserLinks.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.manage.users"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      },
      "get": {
        "description": "Lists webProperty-user links for a given web property.",
        "operationId": "analytics.management.webpropertyUserLinks.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.manage.users",
              "https://www.googleapis.com/auth/analytics.manage.users.readonly"
            ]
          }
        ],
        "tags": [
          "management"
        ]
      }
    },
    "/metadata/{reportType}/columns": {
      "get": {
        "description": "Lists all columns for a report type",
        "operationId": "analytics.metadata.columns.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.edit",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ],
        "tags": [
          "metadata"
        ]
      }
    },
    "/provisioning/createAccountTicket": {
      "post": {
        "description": "Creates an account ticket.",
        "operationId": "analytics.provisioning.createAccountTicket",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics.provision"
            ]
          }
        ],
        "tags": [
          "provisioning"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/analytics": "View and manage your Google Analytics data",
        "https://www.googleapis.com/auth/analytics.edit": "Edit Google Analytics management entities",
        "https://www.googleapis.com/auth/analytics.manage.users": "Manage Google Analytics Account users by email address",
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": "View Google Analytics user permissions",
        "https://www.googleapis.com/auth/analytics.provision": "Create a new Google Analytics account along with its default property and view",
        "https://www.googleapis.com/auth/analytics.readonly": "View your Google Analytics data"
      }
    }
  }
}