# coding: utf-8

"""
    Cloud Key Management Service (KMS) API

    Manages keys and performs cryptographic operations in a central cloud service, for direct use by other cloud resources and applications. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_key_rings_response import ListKeyRingsResponse

class TestListKeyRingsResponse(unittest.TestCase):
    """ListKeyRingsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListKeyRingsResponse:
        """Test ListKeyRingsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListKeyRingsResponse`
        """
        model = ListKeyRingsResponse()
        if include_optional:
            return ListKeyRingsResponse(
                key_rings = [
                    openapi_client.models.key_ring.KeyRing(
                        create_time = '', 
                        name = '', )
                    ],
                next_page_token = '',
                total_size = 56
            )
        else:
            return ListKeyRingsResponse(
        )
        """

    def testListKeyRingsResponse(self):
        """Test ListKeyRingsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
