# coding: utf-8

# flake8: noqa

"""
    ServerManagement

    REST API for Azure Server Management Service.

    The version of the OpenAPI document: 2015-07-01-preview
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.gateways_api import GatewaysApi
from openapi_client.api.nodes_api import NodesApi
from openapi_client.api.power_shell_api import PowerShellApi
from openapi_client.api.sessions_api import SessionsApi
from openapi_client.api.default_api import DefaultApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.error import Error
from openapi_client.models.gateway_parameters import GatewayParameters
from openapi_client.models.gateway_parameters_properties import GatewayParametersProperties
from openapi_client.models.gateway_profile import GatewayProfile
from openapi_client.models.gateway_resource import GatewayResource
from openapi_client.models.gateway_resources import GatewayResources
from openapi_client.models.gateway_status import GatewayStatus
from openapi_client.models.node_parameters import NodeParameters
from openapi_client.models.node_parameters_properties import NodeParametersProperties
from openapi_client.models.node_resource import NodeResource
from openapi_client.models.node_resources import NodeResources
from openapi_client.models.power_shell_command_parameters import PowerShellCommandParameters
from openapi_client.models.power_shell_command_parameters_properties import PowerShellCommandParametersProperties
from openapi_client.models.power_shell_command_result import PowerShellCommandResult
from openapi_client.models.power_shell_command_results import PowerShellCommandResults
from openapi_client.models.power_shell_command_status import PowerShellCommandStatus
from openapi_client.models.power_shell_session_resource import PowerShellSessionResource
from openapi_client.models.power_shell_session_resources import PowerShellSessionResources
from openapi_client.models.power_shell_tab_completion_parameters import PowerShellTabCompletionParameters
from openapi_client.models.power_shell_tab_completion_results import PowerShellTabCompletionResults
from openapi_client.models.prompt_field_description import PromptFieldDescription
from openapi_client.models.prompt_message_response import PromptMessageResponse
from openapi_client.models.resource import Resource
from openapi_client.models.session_parameters import SessionParameters
from openapi_client.models.session_parameters_properties import SessionParametersProperties
from openapi_client.models.session_resource import SessionResource
from openapi_client.models.version import Version
