# coding: utf-8

"""
    Stream Chat API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v80.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.hls_settings import HLSSettings

class TestHLSSettings(unittest.TestCase):
    """HLSSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HLSSettings:
        """Test HLSSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HLSSettings`
        """
        model = HLSSettings()
        if include_optional:
            return HLSSettings(
                auto_on = True,
                enabled = True,
                quality_tracks = [
                    ''
                    ]
            )
        else:
            return HLSSettings(
                auto_on = True,
                enabled = True,
                quality_tracks = [
                    ''
                    ],
        )
        """

    def testHLSSettings(self):
        """Test HLSSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
