package shared




type GoogleSecuritySafebrowsingV4ThreatListDescriptorPlatformTypeEnum string

const (
    GoogleSecuritySafebrowsingV4ThreatListDescriptorPlatformTypeEnumPlatformTypeUnspecified GoogleSecuritySafebrowsingV4ThreatListDescriptorPlatformTypeEnum = "PLATFORM_TYPE_UNSPECIFIED"
GoogleSecuritySafebrowsingV4ThreatListDescriptorPlatformTypeEnumWindows GoogleSecuritySafebrowsingV4ThreatListDescriptorPlatformTypeEnum = "WINDOWS"
GoogleSecuritySafebrowsingV4ThreatListDescriptorPlatformTypeEnumLinux GoogleSecuritySafebrowsingV4ThreatListDescriptorPlatformTypeEnum = "LINUX"
GoogleSecuritySafebrowsingV4ThreatListDescriptorPlatformTypeEnumAndroid GoogleSecuritySafebrowsingV4ThreatListDescriptorPlatformTypeEnum = "ANDROID"
GoogleSecuritySafebrowsingV4ThreatListDescriptorPlatformTypeEnumOsx GoogleSecuritySafebrowsingV4ThreatListDescriptorPlatformTypeEnum = "OSX"
GoogleSecuritySafebrowsingV4ThreatListDescriptorPlatformTypeEnumIos GoogleSecuritySafebrowsingV4ThreatListDescriptorPlatformTypeEnum = "IOS"
GoogleSecuritySafebrowsingV4ThreatListDescriptorPlatformTypeEnumAnyPlatform GoogleSecuritySafebrowsingV4ThreatListDescriptorPlatformTypeEnum = "ANY_PLATFORM"
GoogleSecuritySafebrowsingV4ThreatListDescriptorPlatformTypeEnumAllPlatforms GoogleSecuritySafebrowsingV4ThreatListDescriptorPlatformTypeEnum = "ALL_PLATFORMS"
GoogleSecuritySafebrowsingV4ThreatListDescriptorPlatformTypeEnumChrome GoogleSecuritySafebrowsingV4ThreatListDescriptorPlatformTypeEnum = "CHROME"
)



type GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatEntryTypeEnum string

const (
    GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatEntryTypeEnumThreatEntryTypeUnspecified GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatEntryTypeEnum = "THREAT_ENTRY_TYPE_UNSPECIFIED"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatEntryTypeEnumURL GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatEntryTypeEnum = "URL"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatEntryTypeEnumExecutable GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatEntryTypeEnum = "EXECUTABLE"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatEntryTypeEnumIPRange GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatEntryTypeEnum = "IP_RANGE"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatEntryTypeEnumChromeExtension GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatEntryTypeEnum = "CHROME_EXTENSION"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatEntryTypeEnumFilename GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatEntryTypeEnum = "FILENAME"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatEntryTypeEnumCert GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatEntryTypeEnum = "CERT"
)



type GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum string

const (
    GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnumThreatTypeUnspecified GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum = "THREAT_TYPE_UNSPECIFIED"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnumMalware GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum = "MALWARE"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnumSocialEngineering GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum = "SOCIAL_ENGINEERING"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnumUnwantedSoftware GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum = "UNWANTED_SOFTWARE"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnumPotentiallyHarmfulApplication GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum = "POTENTIALLY_HARMFUL_APPLICATION"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnumSocialEngineeringInternal GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum = "SOCIAL_ENGINEERING_INTERNAL"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnumAPIAbuse GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum = "API_ABUSE"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnumMaliciousBinary GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum = "MALICIOUS_BINARY"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnumCsdWhitelist GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum = "CSD_WHITELIST"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnumCsdDownloadWhitelist GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum = "CSD_DOWNLOAD_WHITELIST"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnumClientIncident GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum = "CLIENT_INCIDENT"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnumClientIncidentWhitelist GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum = "CLIENT_INCIDENT_WHITELIST"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnumApkMalwareOffline GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum = "APK_MALWARE_OFFLINE"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnumSubresourceFilter GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum = "SUBRESOURCE_FILTER"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnumSuspicious GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum = "SUSPICIOUS"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnumTrickToBill GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum = "TRICK_TO_BILL"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnumHighConfidenceAllowlist GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum = "HIGH_CONFIDENCE_ALLOWLIST"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnumAccuracyTips GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum = "ACCURACY_TIPS"
GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnumSocialEngineeringLowerPrecision GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum = "SOCIAL_ENGINEERING_LOWER_PRECISION"
)


type GoogleSecuritySafebrowsingV4ThreatListDescriptor struct {
    PlatformType *GoogleSecuritySafebrowsingV4ThreatListDescriptorPlatformTypeEnum `json:"platformType,omitempty"`
    ThreatEntryType *GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatEntryTypeEnum `json:"threatEntryType,omitempty"`
    ThreatType *GoogleSecuritySafebrowsingV4ThreatListDescriptorThreatTypeEnum `json:"threatType,omitempty"`
    
}

