from .appliedterminology import *
from .createparalleldatarequest import *
from .createparalleldataresponse import *
from .deleteparalleldatarequest import *
from .deleteparalleldataresponse import *
from .deleteterminologyrequest import *
from .describetexttranslationjobrequest import *
from .describetexttranslationjobresponse import *
from .encryptionkey import *
from .encryptionkeytype_enum import *
from .getparalleldatarequest import *
from .getparalleldataresponse import *
from .getterminologyrequest import *
from .getterminologyresponse import *
from .importterminologyrequest import *
from .importterminologyresponse import *
from .inputdataconfig import *
from .jobdetails import *
from .jobstatus_enum import *
from .listparalleldatarequest import *
from .listparalleldataresponse import *
from .listterminologiesrequest import *
from .listterminologiesresponse import *
from .listtexttranslationjobsrequest import *
from .listtexttranslationjobsresponse import *
from .mergestrategy_enum import *
from .outputdataconfig import *
from .paralleldataconfig import *
from .paralleldatadatalocation import *
from .paralleldataformat_enum import *
from .paralleldataproperties import *
from .paralleldatastatus_enum import *
from .security import *
from .starttexttranslationjobrequest import *
from .starttexttranslationjobresponse import *
from .stoptexttranslationjobrequest import *
from .stoptexttranslationjobresponse import *
from .term import *
from .terminologydata import *
from .terminologydataformat_enum import *
from .terminologydatalocation import *
from .terminologyproperties import *
from .texttranslationjobfilter import *
from .texttranslationjobproperties import *
from .translatetextrequest import *
from .translatetextresponse import *
from .updateparalleldatarequest import *
from .updateparalleldataresponse import *
