openapi: 3.0.0
servers:
  - url: https://adsense.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: The AdSense Management API allows publishers to access their inventory and run earnings and performance reports.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: AdSense Management API
  version: v2
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png
  x-origin:
    - format: openapi
      url: https://adsense.googleapis.com/$discovery/rest?version=v2
      version: "3.0"
  x-preferred: false
  x-providerName: googleapis.com
  x-serviceName: adsense
tags:
  - name: accounts
paths:
  /v2/accounts:
    get:
      description: Lists all accounts available to this user.
      operationId: adsense.accounts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/v2/{account}/reports:generate":
    get:
      description: Generates an ad hoc report.
      operationId: adsense.accounts.reports.generate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/v2/{account}/reports:generateCsv":
    get:
      description: Generates a csv formatted ad hoc report.
      operationId: adsense.accounts.reports.generateCsv
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/v2/{name}":
    delete:
      description: Deletes a custom channel. This method can only be used by projects enabled for the [AdSense for Platforms](https://developers.google.com/adsense/platforms/) product.
      operationId: adsense.accounts.adclients.customchannels.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
      tags:
        - accounts
    get:
      description: Gets information about the selected site.
      operationId: adsense.accounts.sites.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
    patch:
      description: Updates a custom channel. This method can only be used by projects enabled for the [AdSense for Platforms](https://developers.google.com/adsense/platforms/) product.
      operationId: adsense.accounts.adclients.customchannels.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
      tags:
        - accounts
  "/v2/{name}/adBlockingRecoveryTag":
    get:
      description: Gets the ad blocking recovery tag of an account.
      operationId: adsense.accounts.getAdBlockingRecoveryTag
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/v2/{name}/adcode":
    get:
      description: Gets the ad unit code for a given ad unit. For more information, see [About the AdSense code](https://support.google.com/adsense/answer/9274634) and [Where to place the ad code in your HTML](https://support.google.com/adsense/answer/9190028).
      operationId: adsense.accounts.adclients.adunits.getAdcode
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/v2/{name}/saved":
    get:
      description: Gets the saved report from the given resource name.
      operationId: adsense.accounts.reports.getSaved
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/v2/{name}/saved:generate":
    get:
      description: Generates a saved report.
      operationId: adsense.accounts.reports.saved.generate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/v2/{name}/saved:generateCsv":
    get:
      description: Generates a csv formatted saved report.
      operationId: adsense.accounts.reports.saved.generateCsv
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/v2/{parent}/adclients":
    get:
      description: Lists all the ad clients available in an account.
      operationId: adsense.accounts.adclients.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/v2/{parent}/adunits":
    get:
      description: Lists all ad units under a specified account and ad client.
      operationId: adsense.accounts.adclients.adunits.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
    post:
      description: 'Creates an ad unit. This method can only be used by projects enabled for the [AdSense for Platforms](https://developers.google.com/adsense/platforms/) product. Note that ad units can only be created for ad clients with an "AFC" product code. For more info see the [AdClient resource](/adsense/management/reference/rest/v2/accounts.adclients). For now, this method can only be used to create `DISPLAY` ad units. See: https://support.google.com/adsense/answer/9183566'
      operationId: adsense.accounts.adclients.adunits.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
      tags:
        - accounts
  "/v2/{parent}/alerts":
    get:
      description: Lists all the alerts available in an account.
      operationId: adsense.accounts.alerts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/v2/{parent}/customchannels":
    get:
      description: Lists all the custom channels available in an ad client.
      operationId: adsense.accounts.adclients.customchannels.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
    post:
      description: Creates a custom channel. This method can only be used by projects enabled for the [AdSense for Platforms](https://developers.google.com/adsense/platforms/) product.
      operationId: adsense.accounts.adclients.customchannels.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
      tags:
        - accounts
  "/v2/{parent}/payments":
    get:
      description: Lists all the payments available for an account.
      operationId: adsense.accounts.payments.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/v2/{parent}/reports/saved":
    get:
      description: Lists saved reports.
      operationId: adsense.accounts.reports.saved.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/v2/{parent}/sites":
    get:
      description: Lists all the sites available in an account.
      operationId: adsense.accounts.sites.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/v2/{parent}/urlchannels":
    get:
      description: Lists active url channels.
      operationId: adsense.accounts.adclients.urlchannels.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/v2/{parent}:listChildAccounts":
    get:
      description: Lists all accounts directly managed by the given AdSense account.
      operationId: adsense.accounts.listChildAccounts
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/v2/{parent}:listLinkedAdUnits":
    get:
      description: Lists all the ad units available for a custom channel.
      operationId: adsense.accounts.adclients.customchannels.listLinkedAdUnits
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
  "/v2/{parent}:listLinkedCustomChannels":
    get:
      description: Lists all the custom channels available for an ad unit.
      operationId: adsense.accounts.adclients.adunits.listLinkedCustomChannels
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/adsense
          Oauth2c:
            - https://www.googleapis.com/auth/adsense
        - Oauth2:
            - https://www.googleapis.com/auth/adsense.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/adsense.readonly
      tags:
        - accounts
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/adsense: View and manage your AdSense data
            https://www.googleapis.com/auth/adsense.readonly: View your AdSense data
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/adsense: View and manage your AdSense data
            https://www.googleapis.com/auth/adsense.readonly: View your AdSense data
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
