swagger: '2.0'
schemes:
  - https
host: sheets.googleapis.com
basePath: /
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Reads and writes Google Sheets.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Google Sheets
  version: v4
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://sheets.googleapis.com/$discovery/rest?version=v4'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: sheets
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/drive': View and manage the files in your Google Drive
      'https://www.googleapis.com/auth/drive.file': View and manage Google Drive files and folders that you have opened or created with this app
      'https://www.googleapis.com/auth/drive.readonly': View the files in your Google Drive
      'https://www.googleapis.com/auth/spreadsheets': View and manage your spreadsheets in Google Drive
      'https://www.googleapis.com/auth/spreadsheets.readonly': View your Google Spreadsheets
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/drive': View and manage the files in your Google Drive
      'https://www.googleapis.com/auth/drive.file': View and manage Google Drive files and folders that you have opened or created with this app
      'https://www.googleapis.com/auth/drive.readonly': View the files in your Google Drive
      'https://www.googleapis.com/auth/spreadsheets': View and manage your spreadsheets in Google Drive
      'https://www.googleapis.com/auth/spreadsheets.readonly': View your Google Spreadsheets
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: spreadsheets
paths:
  /v4/spreadsheets:
    post:
      description: 'Creates a spreadsheet, returning the newly created spreadsheet.'
      operationId: sheets.spreadsheets.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/spreadsheets'
          Oauth2c:
            - 'https://www.googleapis.com/auth/spreadsheets'
      tags:
        - spreadsheets
  '/v4/spreadsheets/{spreadsheetId}':
    get:
      description: |-
        Returns the spreadsheet at the given ID.
        The caller must specify the spreadsheet ID.

        By default, data within grids will not be returned.
        You can include grid data one of two ways:

        * Specify a field mask listing your desired fields using the `fields` URL
        parameter in HTTP

        * Set the includeGridData
        URL parameter to true.  If a field mask is set, the `includeGridData`
        parameter is ignored

        For large spreadsheets, it is recommended to retrieve only the specific
        fields of the spreadsheet that you want.

        To retrieve only subsets of the spreadsheet, use the
        ranges URL parameter.
        Multiple ranges can be specified.  Limiting the range will
        return only the portions of the spreadsheet that intersect the requested
        ranges. Ranges are specified using A1 notation.
      operationId: sheets.spreadsheets.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/spreadsheets'
          Oauth2c:
            - 'https://www.googleapis.com/auth/spreadsheets'
        - Oauth2:
            - 'https://www.googleapis.com/auth/spreadsheets.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/spreadsheets.readonly'
      tags:
        - spreadsheets
  '/v4/spreadsheets/{spreadsheetId}/sheets/{sheetId}:copyTo':
    post:
      description: |-
        Copies a single sheet from a spreadsheet to another spreadsheet.
        Returns the properties of the newly created sheet.
      operationId: sheets.spreadsheets.sheets.copyTo
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/spreadsheets'
          Oauth2c:
            - 'https://www.googleapis.com/auth/spreadsheets'
      tags:
        - spreadsheets
  '/v4/spreadsheets/{spreadsheetId}/values/{range}':
    get:
      description: |-
        Returns a range of values from a spreadsheet.
        The caller must specify the spreadsheet ID and a range.
      operationId: sheets.spreadsheets.values.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/spreadsheets'
          Oauth2c:
            - 'https://www.googleapis.com/auth/spreadsheets'
        - Oauth2:
            - 'https://www.googleapis.com/auth/spreadsheets.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/spreadsheets.readonly'
      tags:
        - spreadsheets
    put:
      description: |-
        Sets values in a range of a spreadsheet.
        The caller must specify the spreadsheet ID, range, and
        a valueInputOption.
      operationId: sheets.spreadsheets.values.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/spreadsheets'
          Oauth2c:
            - 'https://www.googleapis.com/auth/spreadsheets'
      tags:
        - spreadsheets
  '/v4/spreadsheets/{spreadsheetId}/values/{range}:append':
    post:
      description: |-
        Appends values to a spreadsheet. The input range is used to search for
        existing data and find a "table" within that range. Values will be
        appended to the next row of the table, starting with the first column of
        the table. See the
        [guide](/sheets/api/guides/values#appending_values)
        and
        [sample code](/sheets/api/samples/writing#append_values)
        for specific details of how tables are detected and data is appended.

        The caller must specify the spreadsheet ID, range, and
        a valueInputOption.  The `valueInputOption` only
        controls how the input data will be added to the sheet (column-wise or
        row-wise), it does not influence what cell the data starts being written
        to.
      operationId: sheets.spreadsheets.values.append
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/spreadsheets'
          Oauth2c:
            - 'https://www.googleapis.com/auth/spreadsheets'
      tags:
        - spreadsheets
  '/v4/spreadsheets/{spreadsheetId}/values/{range}:clear':
    post:
      description: |-
        Clears values from a spreadsheet.
        The caller must specify the spreadsheet ID and range.
        Only values are cleared -- all other properties of the cell (such as
        formatting, data validation, etc..) are kept.
      operationId: sheets.spreadsheets.values.clear
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/spreadsheets'
          Oauth2c:
            - 'https://www.googleapis.com/auth/spreadsheets'
      tags:
        - spreadsheets
  '/v4/spreadsheets/{spreadsheetId}/values:batchClear':
    post:
      description: |-
        Clears one or more ranges of values from a spreadsheet.
        The caller must specify the spreadsheet ID and one or more ranges.
        Only values are cleared -- all other properties of the cell (such as
        formatting, data validation, etc..) are kept.
      operationId: sheets.spreadsheets.values.batchClear
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/spreadsheets'
          Oauth2c:
            - 'https://www.googleapis.com/auth/spreadsheets'
      tags:
        - spreadsheets
  '/v4/spreadsheets/{spreadsheetId}/values:batchGet':
    get:
      description: |-
        Returns one or more ranges of values from a spreadsheet.
        The caller must specify the spreadsheet ID and one or more ranges.
      operationId: sheets.spreadsheets.values.batchGet
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/spreadsheets'
          Oauth2c:
            - 'https://www.googleapis.com/auth/spreadsheets'
        - Oauth2:
            - 'https://www.googleapis.com/auth/spreadsheets.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/spreadsheets.readonly'
      tags:
        - spreadsheets
  '/v4/spreadsheets/{spreadsheetId}/values:batchUpdate':
    post:
      description: |-
        Sets values in one or more ranges of a spreadsheet.
        The caller must specify the spreadsheet ID,
        a valueInputOption, and one or more
        ValueRanges.
      operationId: sheets.spreadsheets.values.batchUpdate
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/spreadsheets'
          Oauth2c:
            - 'https://www.googleapis.com/auth/spreadsheets'
      tags:
        - spreadsheets
  '/v4/spreadsheets/{spreadsheetId}:batchUpdate':
    post:
      description: |-
        Applies one or more updates to the spreadsheet.

        Each request is validated before
        being applied. If any request is not valid then the entire request will
        fail and nothing will be applied.

        Some requests have replies to
        give you some information about how
        they are applied. The replies will mirror the requests.  For example,
        if you applied 4 updates and the 3rd one had a reply, then the
        response will have 2 empty replies, the actual reply, and another empty
        reply, in that order.

        Due to the collaborative nature of spreadsheets, it is not guaranteed that
        the spreadsheet will reflect exactly your changes after this completes,
        however it is guaranteed that the updates in the request will be
        applied together atomically. Your changes may be altered with respect to
        collaborator changes. If there are no collaborators, the spreadsheet
        should reflect your changes.
      operationId: sheets.spreadsheets.batchUpdate
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/spreadsheets'
          Oauth2c:
            - 'https://www.googleapis.com/auth/spreadsheets'
      tags:
        - spreadsheets