{
  "swagger": "2.0",
  "info": {
    "title": "Webmaster Tools API",
    "description": "Lets you view Google Webmaster Tools data for your verified sites.",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v3"
  },
  "host": "www.googleapis.com",
  "basePath": "/webmasters/v3",
  "schemes": [
    "https"
  ],
  "paths": {
    "/sites/{siteUrl}/sitemaps/{feedpath}": {
      "delete": {
        "description": "Deletes a sitemap from this site.",
        "operationId": "webmasters.sitemaps.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters"
            ]
          }
        ],
        "tags": [
          "sitemaps"
        ]
      },
      "get": {
        "description": "Retrieves information about a specific sitemap.",
        "operationId": "webmasters.sitemaps.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters",
              "https://www.googleapis.com/auth/webmasters.readonly"
            ]
          }
        ],
        "tags": [
          "sitemaps"
        ]
      },
      "put": {
        "description": "Submits a sitemap for a site.",
        "operationId": "webmasters.sitemaps.submit",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters"
            ]
          }
        ],
        "tags": [
          "sitemaps"
        ]
      }
    },
    "/sites/{siteUrl}/sitemaps": {
      "get": {
        "description": "Lists sitemaps uploaded to the site.",
        "operationId": "webmasters.sitemaps.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters",
              "https://www.googleapis.com/auth/webmasters.readonly"
            ]
          }
        ],
        "tags": [
          "sitemaps"
        ]
      }
    },
    "/sites/{siteUrl}": {
      "put": {
        "description": "Adds a site to the set of the user's sites in Webmaster Tools.",
        "operationId": "webmasters.sites.add",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters"
            ]
          }
        ],
        "tags": [
          "sites"
        ]
      },
      "delete": {
        "description": "Removes a site from the set of the user's Webmaster Tools sites.",
        "operationId": "webmasters.sites.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters"
            ]
          }
        ],
        "tags": [
          "sites"
        ]
      },
      "get": {
        "description": "Retrieves information about specific site.",
        "operationId": "webmasters.sites.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters",
              "https://www.googleapis.com/auth/webmasters.readonly"
            ]
          }
        ],
        "tags": [
          "sites"
        ]
      }
    },
    "/sites": {
      "get": {
        "description": "Lists your Webmaster Tools sites.",
        "operationId": "webmasters.sites.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters",
              "https://www.googleapis.com/auth/webmasters.readonly"
            ]
          }
        ],
        "tags": [
          "sites"
        ]
      }
    },
    "/sites/{siteUrl}/urlCrawlErrorsCounts/query": {
      "get": {
        "description": "Retrieves a time series of the number of URL crawl errors per error category and platform.",
        "operationId": "webmasters.urlcrawlerrorscounts.query",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters",
              "https://www.googleapis.com/auth/webmasters.readonly"
            ]
          }
        ],
        "tags": [
          "urlcrawlerrorscounts"
        ]
      }
    },
    "/sites/{siteUrl}/urlCrawlErrorsSamples/{url}": {
      "get": {
        "description": "Retrieves details about crawl errors for a site's sample URL.",
        "operationId": "webmasters.urlcrawlerrorssamples.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters",
              "https://www.googleapis.com/auth/webmasters.readonly"
            ]
          }
        ],
        "tags": [
          "urlcrawlerrorssamples"
        ]
      },
      "delete": {
        "description": "Marks the provided site's sample URL as fixed, and removes it from the samples list.",
        "operationId": "webmasters.urlcrawlerrorssamples.markAsFixed",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters"
            ]
          }
        ],
        "tags": [
          "urlcrawlerrorssamples"
        ]
      }
    },
    "/sites/{siteUrl}/urlCrawlErrorsSamples": {
      "get": {
        "description": "Lists a site's sample URLs for the specified crawl error category and platform.",
        "operationId": "webmasters.urlcrawlerrorssamples.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters",
              "https://www.googleapis.com/auth/webmasters.readonly"
            ]
          }
        ],
        "tags": [
          "urlcrawlerrorssamples"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/webmasters": "View and modify Webmaster Tools data for your verified sites",
        "https://www.googleapis.com/auth/webmasters.readonly": "View Webmaster Tools data for your verified sites"
      }
    }
  }
}