package shared




type ContentOutstreamPositionTargetingOptionDetailsContentOutstreamPositionEnum string

const (
    ContentOutstreamPositionTargetingOptionDetailsContentOutstreamPositionEnumContentOutstreamPositionUnspecified ContentOutstreamPositionTargetingOptionDetailsContentOutstreamPositionEnum = "CONTENT_OUTSTREAM_POSITION_UNSPECIFIED"
ContentOutstreamPositionTargetingOptionDetailsContentOutstreamPositionEnumContentOutstreamPositionUnknown ContentOutstreamPositionTargetingOptionDetailsContentOutstreamPositionEnum = "CONTENT_OUTSTREAM_POSITION_UNKNOWN"
ContentOutstreamPositionTargetingOptionDetailsContentOutstreamPositionEnumContentOutstreamPositionInArticle ContentOutstreamPositionTargetingOptionDetailsContentOutstreamPositionEnum = "CONTENT_OUTSTREAM_POSITION_IN_ARTICLE"
ContentOutstreamPositionTargetingOptionDetailsContentOutstreamPositionEnumContentOutstreamPositionInBanner ContentOutstreamPositionTargetingOptionDetailsContentOutstreamPositionEnum = "CONTENT_OUTSTREAM_POSITION_IN_BANNER"
ContentOutstreamPositionTargetingOptionDetailsContentOutstreamPositionEnumContentOutstreamPositionInFeed ContentOutstreamPositionTargetingOptionDetailsContentOutstreamPositionEnum = "CONTENT_OUTSTREAM_POSITION_IN_FEED"
ContentOutstreamPositionTargetingOptionDetailsContentOutstreamPositionEnumContentOutstreamPositionInterstitial ContentOutstreamPositionTargetingOptionDetailsContentOutstreamPositionEnum = "CONTENT_OUTSTREAM_POSITION_INTERSTITIAL"
)


type ContentOutstreamPositionTargetingOptionDetails struct {
    ContentOutstreamPosition *ContentOutstreamPositionTargetingOptionDetailsContentOutstreamPositionEnum `json:"contentOutstreamPosition,omitempty"`
    
}

