package shared

type ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnum string

const (
	ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnumContentInstreamPositionUnspecified ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnum = "CONTENT_INSTREAM_POSITION_UNSPECIFIED"
	ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnumContentInstreamPositionPreRoll     ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnum = "CONTENT_INSTREAM_POSITION_PRE_ROLL"
	ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnumContentInstreamPositionMidRoll     ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnum = "CONTENT_INSTREAM_POSITION_MID_ROLL"
	ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnumContentInstreamPositionPostRoll    ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnum = "CONTENT_INSTREAM_POSITION_POST_ROLL"
	ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnumContentInstreamPositionUnknown     ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnum = "CONTENT_INSTREAM_POSITION_UNKNOWN"
)

type ContentInstreamPositionTargetingOptionDetails struct {
	ContentInstreamPosition *ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnum `json:"contentInstreamPosition"`
}
