package shared




type DigitalContentLabelAssignedTargetingOptionDetailsContentRatingTierEnum string

const (
    DigitalContentLabelAssignedTargetingOptionDetailsContentRatingTierEnumContentRatingTierUnspecified DigitalContentLabelAssignedTargetingOptionDetailsContentRatingTierEnum = "CONTENT_RATING_TIER_UNSPECIFIED"
DigitalContentLabelAssignedTargetingOptionDetailsContentRatingTierEnumContentRatingTierUnrated DigitalContentLabelAssignedTargetingOptionDetailsContentRatingTierEnum = "CONTENT_RATING_TIER_UNRATED"
DigitalContentLabelAssignedTargetingOptionDetailsContentRatingTierEnumContentRatingTierGeneral DigitalContentLabelAssignedTargetingOptionDetailsContentRatingTierEnum = "CONTENT_RATING_TIER_GENERAL"
DigitalContentLabelAssignedTargetingOptionDetailsContentRatingTierEnumContentRatingTierParentalGuidance DigitalContentLabelAssignedTargetingOptionDetailsContentRatingTierEnum = "CONTENT_RATING_TIER_PARENTAL_GUIDANCE"
DigitalContentLabelAssignedTargetingOptionDetailsContentRatingTierEnumContentRatingTierTeens DigitalContentLabelAssignedTargetingOptionDetailsContentRatingTierEnum = "CONTENT_RATING_TIER_TEENS"
DigitalContentLabelAssignedTargetingOptionDetailsContentRatingTierEnumContentRatingTierMature DigitalContentLabelAssignedTargetingOptionDetailsContentRatingTierEnum = "CONTENT_RATING_TIER_MATURE"
)


type DigitalContentLabelAssignedTargetingOptionDetails struct {
    ContentRatingTier *DigitalContentLabelAssignedTargetingOptionDetailsContentRatingTierEnum `json:"contentRatingTier,omitempty"`
    ExcludedTargetingOptionID *string `json:"excludedTargetingOptionId,omitempty"`
    
}

