package shared




type DoubleVerifyDisplayViewabilityIabEnum string

const (
    DoubleVerifyDisplayViewabilityIabEnumIabViewedRateUnspecified DoubleVerifyDisplayViewabilityIabEnum = "IAB_VIEWED_RATE_UNSPECIFIED"
DoubleVerifyDisplayViewabilityIabEnumIabViewedRate80PercentHigher DoubleVerifyDisplayViewabilityIabEnum = "IAB_VIEWED_RATE_80_PERCENT_HIGHER"
DoubleVerifyDisplayViewabilityIabEnumIabViewedRate75PercentHigher DoubleVerifyDisplayViewabilityIabEnum = "IAB_VIEWED_RATE_75_PERCENT_HIGHER"
DoubleVerifyDisplayViewabilityIabEnumIabViewedRate70PercentHigher DoubleVerifyDisplayViewabilityIabEnum = "IAB_VIEWED_RATE_70_PERCENT_HIGHER"
DoubleVerifyDisplayViewabilityIabEnumIabViewedRate65PercentHigher DoubleVerifyDisplayViewabilityIabEnum = "IAB_VIEWED_RATE_65_PERCENT_HIGHER"
DoubleVerifyDisplayViewabilityIabEnumIabViewedRate60PercentHigher DoubleVerifyDisplayViewabilityIabEnum = "IAB_VIEWED_RATE_60_PERCENT_HIGHER"
DoubleVerifyDisplayViewabilityIabEnumIabViewedRate55PercentHigher DoubleVerifyDisplayViewabilityIabEnum = "IAB_VIEWED_RATE_55_PERCENT_HIGHER"
DoubleVerifyDisplayViewabilityIabEnumIabViewedRate50PercentHigher DoubleVerifyDisplayViewabilityIabEnum = "IAB_VIEWED_RATE_50_PERCENT_HIGHER"
DoubleVerifyDisplayViewabilityIabEnumIabViewedRate40PercentHigher DoubleVerifyDisplayViewabilityIabEnum = "IAB_VIEWED_RATE_40_PERCENT_HIGHER"
DoubleVerifyDisplayViewabilityIabEnumIabViewedRate30PercentHigher DoubleVerifyDisplayViewabilityIabEnum = "IAB_VIEWED_RATE_30_PERCENT_HIGHER"
)



type DoubleVerifyDisplayViewabilityViewableDuringEnum string

const (
    DoubleVerifyDisplayViewabilityViewableDuringEnumAverageViewDurationUnspecified DoubleVerifyDisplayViewabilityViewableDuringEnum = "AVERAGE_VIEW_DURATION_UNSPECIFIED"
DoubleVerifyDisplayViewabilityViewableDuringEnumAverageViewDuration5Sec DoubleVerifyDisplayViewabilityViewableDuringEnum = "AVERAGE_VIEW_DURATION_5_SEC"
DoubleVerifyDisplayViewabilityViewableDuringEnumAverageViewDuration10Sec DoubleVerifyDisplayViewabilityViewableDuringEnum = "AVERAGE_VIEW_DURATION_10_SEC"
DoubleVerifyDisplayViewabilityViewableDuringEnumAverageViewDuration15Sec DoubleVerifyDisplayViewabilityViewableDuringEnum = "AVERAGE_VIEW_DURATION_15_SEC"
)


type DoubleVerifyDisplayViewability struct {
    Iab *DoubleVerifyDisplayViewabilityIabEnum `json:"iab,omitempty"`
    ViewableDuring *DoubleVerifyDisplayViewabilityViewableDuringEnum `json:"viewableDuring,omitempty"`
    
}

