package shared




type ExchangeReviewStatusExchangeEnum string

const (
    ExchangeReviewStatusExchangeEnumExchangeUnspecified ExchangeReviewStatusExchangeEnum = "EXCHANGE_UNSPECIFIED"
ExchangeReviewStatusExchangeEnumExchangeGoogleAdManager ExchangeReviewStatusExchangeEnum = "EXCHANGE_GOOGLE_AD_MANAGER"
ExchangeReviewStatusExchangeEnumExchangeAppnexus ExchangeReviewStatusExchangeEnum = "EXCHANGE_APPNEXUS"
ExchangeReviewStatusExchangeEnumExchangeBrightroll ExchangeReviewStatusExchangeEnum = "EXCHANGE_BRIGHTROLL"
ExchangeReviewStatusExchangeEnumExchangeAdform ExchangeReviewStatusExchangeEnum = "EXCHANGE_ADFORM"
ExchangeReviewStatusExchangeEnumExchangeAdmeta ExchangeReviewStatusExchangeEnum = "EXCHANGE_ADMETA"
ExchangeReviewStatusExchangeEnumExchangeAdmixer ExchangeReviewStatusExchangeEnum = "EXCHANGE_ADMIXER"
ExchangeReviewStatusExchangeEnumExchangeAdsmogo ExchangeReviewStatusExchangeEnum = "EXCHANGE_ADSMOGO"
ExchangeReviewStatusExchangeEnumExchangeAdswizz ExchangeReviewStatusExchangeEnum = "EXCHANGE_ADSWIZZ"
ExchangeReviewStatusExchangeEnumExchangeBidswitch ExchangeReviewStatusExchangeEnum = "EXCHANGE_BIDSWITCH"
ExchangeReviewStatusExchangeEnumExchangeBrightrollDisplay ExchangeReviewStatusExchangeEnum = "EXCHANGE_BRIGHTROLL_DISPLAY"
ExchangeReviewStatusExchangeEnumExchangeCadreon ExchangeReviewStatusExchangeEnum = "EXCHANGE_CADREON"
ExchangeReviewStatusExchangeEnumExchangeDailymotion ExchangeReviewStatusExchangeEnum = "EXCHANGE_DAILYMOTION"
ExchangeReviewStatusExchangeEnumExchangeFive ExchangeReviewStatusExchangeEnum = "EXCHANGE_FIVE"
ExchangeReviewStatusExchangeEnumExchangeFluct ExchangeReviewStatusExchangeEnum = "EXCHANGE_FLUCT"
ExchangeReviewStatusExchangeEnumExchangeFreewheel ExchangeReviewStatusExchangeEnum = "EXCHANGE_FREEWHEEL"
ExchangeReviewStatusExchangeEnumExchangeGeniee ExchangeReviewStatusExchangeEnum = "EXCHANGE_GENIEE"
ExchangeReviewStatusExchangeEnumExchangeGumgum ExchangeReviewStatusExchangeEnum = "EXCHANGE_GUMGUM"
ExchangeReviewStatusExchangeEnumExchangeImobile ExchangeReviewStatusExchangeEnum = "EXCHANGE_IMOBILE"
ExchangeReviewStatusExchangeEnumExchangeIbillboard ExchangeReviewStatusExchangeEnum = "EXCHANGE_IBILLBOARD"
ExchangeReviewStatusExchangeEnumExchangeImproveDigital ExchangeReviewStatusExchangeEnum = "EXCHANGE_IMPROVE_DIGITAL"
ExchangeReviewStatusExchangeEnumExchangeIndex ExchangeReviewStatusExchangeEnum = "EXCHANGE_INDEX"
ExchangeReviewStatusExchangeEnumExchangeKargo ExchangeReviewStatusExchangeEnum = "EXCHANGE_KARGO"
ExchangeReviewStatusExchangeEnumExchangeMicroad ExchangeReviewStatusExchangeEnum = "EXCHANGE_MICROAD"
ExchangeReviewStatusExchangeEnumExchangeMopub ExchangeReviewStatusExchangeEnum = "EXCHANGE_MOPUB"
ExchangeReviewStatusExchangeEnumExchangeNend ExchangeReviewStatusExchangeEnum = "EXCHANGE_NEND"
ExchangeReviewStatusExchangeEnumExchangeOneByAolDisplay ExchangeReviewStatusExchangeEnum = "EXCHANGE_ONE_BY_AOL_DISPLAY"
ExchangeReviewStatusExchangeEnumExchangeOneByAolMobile ExchangeReviewStatusExchangeEnum = "EXCHANGE_ONE_BY_AOL_MOBILE"
ExchangeReviewStatusExchangeEnumExchangeOneByAolVideo ExchangeReviewStatusExchangeEnum = "EXCHANGE_ONE_BY_AOL_VIDEO"
ExchangeReviewStatusExchangeEnumExchangeOoyala ExchangeReviewStatusExchangeEnum = "EXCHANGE_OOYALA"
ExchangeReviewStatusExchangeEnumExchangeOpenx ExchangeReviewStatusExchangeEnum = "EXCHANGE_OPENX"
ExchangeReviewStatusExchangeEnumExchangePermodo ExchangeReviewStatusExchangeEnum = "EXCHANGE_PERMODO"
ExchangeReviewStatusExchangeEnumExchangePlatformone ExchangeReviewStatusExchangeEnum = "EXCHANGE_PLATFORMONE"
ExchangeReviewStatusExchangeEnumExchangePlatformid ExchangeReviewStatusExchangeEnum = "EXCHANGE_PLATFORMID"
ExchangeReviewStatusExchangeEnumExchangePubmatic ExchangeReviewStatusExchangeEnum = "EXCHANGE_PUBMATIC"
ExchangeReviewStatusExchangeEnumExchangePulsepoint ExchangeReviewStatusExchangeEnum = "EXCHANGE_PULSEPOINT"
ExchangeReviewStatusExchangeEnumExchangeRevenuemax ExchangeReviewStatusExchangeEnum = "EXCHANGE_REVENUEMAX"
ExchangeReviewStatusExchangeEnumExchangeRubicon ExchangeReviewStatusExchangeEnum = "EXCHANGE_RUBICON"
ExchangeReviewStatusExchangeEnumExchangeSmartclip ExchangeReviewStatusExchangeEnum = "EXCHANGE_SMARTCLIP"
ExchangeReviewStatusExchangeEnumExchangeSmartrtb ExchangeReviewStatusExchangeEnum = "EXCHANGE_SMARTRTB"
ExchangeReviewStatusExchangeEnumExchangeSmartstreamtv ExchangeReviewStatusExchangeEnum = "EXCHANGE_SMARTSTREAMTV"
ExchangeReviewStatusExchangeEnumExchangeSovrn ExchangeReviewStatusExchangeEnum = "EXCHANGE_SOVRN"
ExchangeReviewStatusExchangeEnumExchangeSpotxchange ExchangeReviewStatusExchangeEnum = "EXCHANGE_SPOTXCHANGE"
ExchangeReviewStatusExchangeEnumExchangeStroer ExchangeReviewStatusExchangeEnum = "EXCHANGE_STROER"
ExchangeReviewStatusExchangeEnumExchangeTeadstv ExchangeReviewStatusExchangeEnum = "EXCHANGE_TEADSTV"
ExchangeReviewStatusExchangeEnumExchangeTelaria ExchangeReviewStatusExchangeEnum = "EXCHANGE_TELARIA"
ExchangeReviewStatusExchangeEnumExchangeTvn ExchangeReviewStatusExchangeEnum = "EXCHANGE_TVN"
ExchangeReviewStatusExchangeEnumExchangeUnited ExchangeReviewStatusExchangeEnum = "EXCHANGE_UNITED"
ExchangeReviewStatusExchangeEnumExchangeYieldlab ExchangeReviewStatusExchangeEnum = "EXCHANGE_YIELDLAB"
ExchangeReviewStatusExchangeEnumExchangeYieldmo ExchangeReviewStatusExchangeEnum = "EXCHANGE_YIELDMO"
ExchangeReviewStatusExchangeEnumExchangeUnrulyx ExchangeReviewStatusExchangeEnum = "EXCHANGE_UNRULYX"
ExchangeReviewStatusExchangeEnumExchangeOpen8 ExchangeReviewStatusExchangeEnum = "EXCHANGE_OPEN8"
ExchangeReviewStatusExchangeEnumExchangeTriton ExchangeReviewStatusExchangeEnum = "EXCHANGE_TRITON"
ExchangeReviewStatusExchangeEnumExchangeTriplelift ExchangeReviewStatusExchangeEnum = "EXCHANGE_TRIPLELIFT"
ExchangeReviewStatusExchangeEnumExchangeTaboola ExchangeReviewStatusExchangeEnum = "EXCHANGE_TABOOLA"
ExchangeReviewStatusExchangeEnumExchangeInmobi ExchangeReviewStatusExchangeEnum = "EXCHANGE_INMOBI"
ExchangeReviewStatusExchangeEnumExchangeSmaato ExchangeReviewStatusExchangeEnum = "EXCHANGE_SMAATO"
ExchangeReviewStatusExchangeEnumExchangeAja ExchangeReviewStatusExchangeEnum = "EXCHANGE_AJA"
ExchangeReviewStatusExchangeEnumExchangeSupership ExchangeReviewStatusExchangeEnum = "EXCHANGE_SUPERSHIP"
ExchangeReviewStatusExchangeEnumExchangeNexstarDigital ExchangeReviewStatusExchangeEnum = "EXCHANGE_NEXSTAR_DIGITAL"
ExchangeReviewStatusExchangeEnumExchangeWaze ExchangeReviewStatusExchangeEnum = "EXCHANGE_WAZE"
ExchangeReviewStatusExchangeEnumExchangeSoundcast ExchangeReviewStatusExchangeEnum = "EXCHANGE_SOUNDCAST"
ExchangeReviewStatusExchangeEnumExchangeSharethrough ExchangeReviewStatusExchangeEnum = "EXCHANGE_SHARETHROUGH"
ExchangeReviewStatusExchangeEnumExchangeFyber ExchangeReviewStatusExchangeEnum = "EXCHANGE_FYBER"
ExchangeReviewStatusExchangeEnumExchangeRedForPublishers ExchangeReviewStatusExchangeEnum = "EXCHANGE_RED_FOR_PUBLISHERS"
ExchangeReviewStatusExchangeEnumExchangeMedianet ExchangeReviewStatusExchangeEnum = "EXCHANGE_MEDIANET"
ExchangeReviewStatusExchangeEnumExchangeTapjoy ExchangeReviewStatusExchangeEnum = "EXCHANGE_TAPJOY"
ExchangeReviewStatusExchangeEnumExchangeVistar ExchangeReviewStatusExchangeEnum = "EXCHANGE_VISTAR"
ExchangeReviewStatusExchangeEnumExchangeDax ExchangeReviewStatusExchangeEnum = "EXCHANGE_DAX"
)



type ExchangeReviewStatusStatusEnum string

const (
    ExchangeReviewStatusStatusEnumReviewStatusUnspecified ExchangeReviewStatusStatusEnum = "REVIEW_STATUS_UNSPECIFIED"
ExchangeReviewStatusStatusEnumReviewStatusApproved ExchangeReviewStatusStatusEnum = "REVIEW_STATUS_APPROVED"
ExchangeReviewStatusStatusEnumReviewStatusRejected ExchangeReviewStatusStatusEnum = "REVIEW_STATUS_REJECTED"
ExchangeReviewStatusStatusEnumReviewStatusPending ExchangeReviewStatusStatusEnum = "REVIEW_STATUS_PENDING"
)


type ExchangeReviewStatus struct {
    Exchange *ExchangeReviewStatusExchangeEnum `json:"exchange,omitempty"`
    Status *ExchangeReviewStatusStatusEnum `json:"status,omitempty"`
    
}

