package shared

type ExchangeTargetingOptionDetailsExchangeEnum string

const (
	ExchangeTargetingOptionDetailsExchangeEnumExchangeUnspecified       ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_UNSPECIFIED"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeGoogleAdManager   ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_GOOGLE_AD_MANAGER"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeAppnexus          ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_APPNEXUS"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeBrightroll        ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_BRIGHTROLL"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeAdform            ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_ADFORM"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeAdmeta            ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_ADMETA"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeAdmixer           ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_ADMIXER"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeAdsmogo           ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_ADSMOGO"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeAdswizz           ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_ADSWIZZ"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeBidswitch         ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_BIDSWITCH"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeBrightrollDisplay ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_BRIGHTROLL_DISPLAY"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeCadreon           ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_CADREON"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeDailymotion       ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_DAILYMOTION"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeFive              ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_FIVE"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeFluct             ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_FLUCT"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeFreewheel         ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_FREEWHEEL"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeGeniee            ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_GENIEE"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeGumgum            ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_GUMGUM"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeImobile           ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_IMOBILE"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeIbillboard        ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_IBILLBOARD"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeImproveDigital    ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_IMPROVE_DIGITAL"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeIndex             ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_INDEX"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeKargo             ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_KARGO"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeMicroad           ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_MICROAD"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeMopub             ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_MOPUB"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeNend              ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_NEND"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeOneByAolDisplay   ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_ONE_BY_AOL_DISPLAY"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeOneByAolMobile    ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_ONE_BY_AOL_MOBILE"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeOneByAolVideo     ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_ONE_BY_AOL_VIDEO"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeOoyala            ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_OOYALA"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeOpenx             ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_OPENX"
	ExchangeTargetingOptionDetailsExchangeEnumExchangePermodo           ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_PERMODO"
	ExchangeTargetingOptionDetailsExchangeEnumExchangePlatformone       ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_PLATFORMONE"
	ExchangeTargetingOptionDetailsExchangeEnumExchangePlatformid        ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_PLATFORMID"
	ExchangeTargetingOptionDetailsExchangeEnumExchangePubmatic          ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_PUBMATIC"
	ExchangeTargetingOptionDetailsExchangeEnumExchangePulsepoint        ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_PULSEPOINT"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeRevenuemax        ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_REVENUEMAX"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeRubicon           ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_RUBICON"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeSmartclip         ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_SMARTCLIP"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeSmartrtb          ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_SMARTRTB"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeSmartstreamtv     ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_SMARTSTREAMTV"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeSovrn             ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_SOVRN"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeSpotxchange       ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_SPOTXCHANGE"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeStroer            ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_STROER"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeTeadstv           ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_TEADSTV"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeTelaria           ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_TELARIA"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeTvn               ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_TVN"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeUnited            ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_UNITED"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeYieldlab          ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_YIELDLAB"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeYieldmo           ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_YIELDMO"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeUnrulyx           ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_UNRULYX"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeOpen8             ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_OPEN8"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeTriton            ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_TRITON"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeTriplelift        ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_TRIPLELIFT"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeTaboola           ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_TABOOLA"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeInmobi            ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_INMOBI"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeSmaato            ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_SMAATO"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeAja               ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_AJA"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeSupership         ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_SUPERSHIP"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeNexstarDigital    ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_NEXSTAR_DIGITAL"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeWaze              ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_WAZE"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeSoundcast         ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_SOUNDCAST"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeSharethrough      ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_SHARETHROUGH"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeFyber             ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_FYBER"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeRedForPublishers  ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_RED_FOR_PUBLISHERS"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeMedianet          ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_MEDIANET"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeTapjoy            ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_TAPJOY"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeVistar            ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_VISTAR"
	ExchangeTargetingOptionDetailsExchangeEnumExchangeDax               ExchangeTargetingOptionDetailsExchangeEnum = "EXCHANGE_DAX"
)

type ExchangeTargetingOptionDetails struct {
	Exchange *ExchangeTargetingOptionDetailsExchangeEnum `json:"exchange"`
}
