swagger: '2.0'
schemes:
  - https
host: api.bitbucket.org
basePath: /2.0
info:
  contact:
    email: support@bitbucket.org
    name: Bitbucket Support
    url: 'https://bitbucket.org/support'
  description: 'Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.'
  termsOfService: 'https://www.atlassian.com/legal/customer-agreement'
  title: Bitbucket
  version: '2.0'
  x-apisguru-categories:
    - developer_tools
    - collaboration
  x-logo:
    url: 'https://d301sr5gafysq2.cloudfront.net/0c55837759e5/img/homepage/bitbucket-logo-blue.svg'
  x-origin:
    format: swagger
    url: 'https://bitbucket.org/api/swagger.json'
    version: '2.0'
  x-providerName: bitbucket.org
  x-tags:
    - code repository
    - code collaboration
    - git
securityDefinitions:
  api_key:
    description: API Keys can be used as Basic HTTP Authentication credentials and provide a substitute for the account's actual username and password. API Keys are only available to team accounts and there is only 1 key per account. API Keys do not support scopes and have therefore access to all contents of the account.
    in: header
    name: Authorization
    type: apiKey
  basic:
    description: 'Basic HTTP Authentication as per [RFC-2617](https://tools.ietf.org/html/rfc2617) (Digest not supported). Note that Basic Auth with username and password as credentials is only available on accounts that have 2-factor-auth / 2-step-verification disabled. If you use 2fa, you should authenticate using OAuth2 instead.'
    type: basic
  oauth2:
    authorizationUrl: 'https://bitbucket.org/site/oauth2/authorize'
    description: 'OAuth 2 as per [RFC-6749](https://tools.ietf.org/html/rfc6749).'
    flow: accessCode
    scopes:
      account: Read your account information
      'account:write': Read and modify your account information
      email: Read your account's primary email address
      issue: Read your repositories' issues
      'issue:write': Read and modify your repositories' issues
      pipeline: Access your repositories' build pipelines
      'pipeline:variable': Access your repositories' build pipelines and configure their variables
      'pipeline:write': Access and rerun your repositories' build pipelines
      project: Read your team's project settings and read repositories contained within your team's projects
      'project:write': 'Read and modify your team''s project settings, and read and transfer repositories within your team''s projects'
      pullrequest: Read your repositories and their pull requests
      'pullrequest:write': Read and modify your repositories and their pull requests
      repository: Read your repositories
      'repository:admin': Administer your repositories
      'repository:delete': Delete your repositories
      'repository:write': Read and modify your repositories
      snippet: Read your snippets
      'snippet:write': Read and modify your snippets
      team: Read your team membership information
      'team:write': Read and modify your team membership information
      webhook: Read and modify your repositories' webhooks
      wiki: Read and modify your repositories' wikis
    tokenUrl: 'https://bitbucket.org/site/oauth2/access_token'
    type: oauth2
tags:
  - description: ''
    name: users
  - description: ''
    name: teams
  - description: ''
    name: repositories
  - description: ''
    name: refs
  - description: ''
    name: commits
  - description: ''
    name: pullrequests
  - description: |-
      The issues resource provides functionality for getting information on
      issues in an issue tracker, creating new issues, updating them and deleting
      them.

      You can access public issues without authentication, but you can't gain access
      to private repositories' issues. By authenticating, you will get the ability
      to create issues, as well as access to updating data or deleting issues you
      have access to.
    name: issue_tracker
  - description: ''
    name: wiki
  - description: ''
    name: downloads
  - description: ''
    name: snippets
  - description: |
      Webhooks provide a way to configure Bitbucket Cloud to make requests to
      your server (or another external service) whenever certain events occur in
      Bitbucket Cloud.

      A webhook consists of:

      * A subject -- The resource that generates the events. Currently, this resource
        is the repository, user account, or team where you create the webhook.
      * One or more event -- The default event is a repository push, but you can
        select multiple events that can trigger the webhook.
      * A URL -- The endpoint where you want Bitbucket to send the event payloads
        when a matching event happens.

      There are two parts to getting a webhook to work: creating the webhook and
      triggering the webhook. After you create a webhook for an event, every time
      that event occurs, Bitbucket sends a payload request that describes the event
      to the specified URL. Thus, you can think of webhooks as a kind of
      notification system.

      Use webhooks to integrate applications with Bitbucket Cloud. The following
      use cases provides examples of when you would want to use webhooks:

      * Every time a user pushes commits in a repository, you may want to notify
        your CI server to start a build.
      * Every time a user pushes commits or creates a pull request, you may want to
        display a notification in your application.
    name: webhooks
  - description: |
      Commit statuses provide a way to tag commits with meta data,
      like automated build results.
    name: commitstatuses
  - description: |
      Repository owners and administrators can set branch management
      rules on a repository that control what can be pushed by whom.
      Through these rules, you can enforce a project or team
      workflow. For example, owners or administrators can:

      * Limit push powers
      * Prevent branch (bookmark) deletion
      * Prevent history re-writes (Git only)
    name: branchrestrictions
  - description: |
      Bitbucket Cloud projects make it easier for teams to focus on
      a goal, product, or process by organizing their repositories.
    name: projects
  - description: |
      Bitbucket Pipelines brings continuous delivery to Bitbucket
      Cloud, empowering teams with full branching to deployment
      visibility and faster feedback loops.
    name: pipelines
paths:
  /addon:
    delete:
      description: ''
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      tags:
        - addon
    put:
      description: ''
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      tags:
        - addon
  /addon/linkers:
    get:
      description: ''
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      tags:
        - addon
  '/addon/linkers/{linker_key}':
    get:
      description: ''
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      tags:
        - addon
  '/addon/linkers/{linker_key}/values':
    delete:
      description: ''
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      tags:
        - addon
    get:
      description: ''
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      tags:
        - addon
    post:
      description: ''
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      tags:
        - addon
    put:
      description: ''
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      tags:
        - addon
  '/addon/linkers/{linker_key}/values/':
    delete:
      description: ''
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      tags:
        - addon
    get:
      description: ''
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      tags:
        - addon
  /hook_events:
    get:
      description: |-
        Returns the webhook resource or subject types on which webhooks can
        be registered.

        Each resource/subject type contains an `event` link that returns the
        paginated list of specific events each individual subject type can
        emit.

        This endpoint is publicly accessible and does not require
        authentication or scopes.
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      tags:
        - webhooks
  '/hook_events/{subject_type}':
    get:
      description: |-
        Returns a paginated list of all valid webhook events for the
        specified entity.

        This is public data that does not require any scopes or authentication.
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      tags:
        - webhooks
  /repositories:
    get:
      description: |-
        Returns a paginated list of all public repositories.

        This endpoint also supports filtering and sorting of the results. See
        [filtering and sorting](../meta/filtering) for more details.
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - repositories
  '/repositories/{username}':
    get:
      description: |-
        Returns a paginated list of all repositories owned by the specified
        account or UUID.

        The result can be narrowed down based on the authenticated user's role.

        E.g. with `?role=contributor`, only those repositories that the
        authenticated user has write access to are returned (this includes any
        repo the user is an admin on, as that implies write access).

        This endpoint also supports filtering and sorting of the results. See
        [filtering and sorting](../../meta/filtering) for more details.
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - repositories
  '/repositories/{username}/{repo_slug}':
    delete:
      description: |-
        Deletes the repository. This is an irreversible operation.

        This does not affect its forks.
      security:
        - oauth2:
            - 'repository:delete'
        - basic: []
        - api_key: []
      tags:
        - repositories
    get:
      description: Returns the object describing this repository.
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - repositories
    post:
      description: |-
        Creates a new repository.

        Note: In order to set the project for the newly created repository,
        pass in either the project key or the project UUID as part of the
        request body as shown in the examples below:

        ```
        $ curl -X POST -H "Content-Type: application/json" -d '{
            "scm": "git",
            "project": {
                "key": "MARS"
            }
        }' https://api.bitbucket.org/2.0/repositories/teamsinspace/hablanding
        ```

        or

        ```
        $ curl -X POST -H "Content-Type: application/json" -d '{
            "scm": "git",
            "project": {
                "key": "{ba516952-992a-4c2d-acbd-17d502922f96}"
            }
        }' https://api.bitbucket.org/2.0/repositories/teamsinspace/hablanding
        ```

        The project must only be assigned for repositories belonging to a team.
        If the repository owner is a team and the project is not provided, the
        repository is automatically assigned to the oldest project in the team.

        Note: In the examples above, the username `teamsinspace`,
        and/or the repository name `hablanding` can be replaced by UUIDs.
      security:
        - oauth2:
            - 'repository:admin'
        - basic: []
        - api_key: []
      tags:
        - repositories
    put:
      description: |-
        Since this endpoint can be used to both update and to create a
        repository, the request body depends on the intent.

        ### Creation

        See the POST documentation for the repository endpoint for an example
        of the request body.

        ### Update

        Note: Changing the `name` of the repository will cause the location to
        be changed. This is because the URL of the repo is derived from the
        name (a process called slugification). In such a scenario, it is
        possible for the request to fail if the newly created slug conflicts
        with an existing repository's slug. But if there is no conflict,
        the new location will be returned in the `Location` header of the
        response.
      security:
        - oauth2:
            - 'repository:admin'
        - basic: []
        - api_key: []
      tags:
        - repositories
  '/repositories/{username}/{repo_slug}/branch-restrictions':
    get:
      description: |-
        Returns a paginated list of all branch restrictions on the
        repository.
      security:
        - oauth2:
            - 'repository:admin'
        - basic: []
        - api_key: []
      tags:
        - branchrestrictions
    post:
      description: |-
        Creates a new branch restriction rule for a repository.

        `kind` describes what will be restricted. Allowed values are: `push`,
        `force`, `delete`, and `restrict_merges`.

        Different kinds of branch restrictions have different requirements:

        * `push` and `restrict_merges` require `users` and `groups` to be
          specified. Empty lists are allowed, in which case permission is
          denied for everybody.
        * `force` can not be specified in a Mercurial repository.

        `pattern` is used to determine which branches will be restricted.

        A `'*'` in `pattern` will expand to match zero or more characters, and
        every other character matches itself. For example, `'foo*'` will match
        `'foo'` and `'foobar'`, but not `'barfoo'`. `'*'` will match all
        branches.

        `users` and `groups` are lists of user names and group names.

        `kind` and `pattern` must be unique within a repository; adding new
        users or groups to an existing restriction should be done via `PUT`.

        Note that branch restrictions with overlapping patterns are allowed,
        but the resulting behavior may be surprising.
      security:
        - oauth2:
            - 'repository:admin'
        - basic: []
        - api_key: []
      tags:
        - branchrestrictions
  '/repositories/{username}/{repo_slug}/branch-restrictions/{id}':
    delete:
      description: Deletes an existing branch restriction rule.
      security:
        - oauth2:
            - 'repository:admin'
        - basic: []
        - api_key: []
      tags:
        - branchrestrictions
    get:
      description: Returns a specific branch restriction rule.
      security:
        - oauth2:
            - 'repository:admin'
        - basic: []
        - api_key: []
      tags:
        - branchrestrictions
    put:
      description: |-
        Updates an existing branch restriction rule.

        Fields not present in the request body are ignored.

        See [`POST`](../../branch-restrictions#post) for details.
      security:
        - oauth2:
            - 'repository:admin'
        - basic: []
        - api_key: []
      tags:
        - branchrestrictions
  '/repositories/{username}/{repo_slug}/commit/{node}/approve':
    delete:
      description: |-
        Redact the authenticated user's approval of the specified commit.

        This operation is only available to users that have explicit access to
        the repository. In contrast, just the fact that a repository is
        publicly accessible to users does not give them the ability to approve
        commits.
      security:
        - oauth2:
            - 'repository:write'
        - basic: []
        - api_key: []
      tags:
        - commits
    post:
      description: |-
        Approve the specified commit as the authenticated user.

        This operation is only available to users that have explicit access to
        the repository. In contrast, just the fact that a repository is
        publicly accessible to users does not give them the ability to approve
        commits.
      security:
        - oauth2:
            - 'repository:write'
        - basic: []
        - api_key: []
      tags:
        - commits
  '/repositories/{username}/{repo_slug}/commit/{node}/statuses':
    get:
      description: Returns all statuses (e.g. build results) for a specific commit.
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - repositories
        - commitstatuses
  '/repositories/{username}/{repo_slug}/commit/{node}/statuses/build':
    post:
      description: |-
        Creates a new build status against the specified commit.

        If the specified key already exists, the existing status object will
        be overwritten.

        When creating a new commit status, you can use a URI template for the URL.
        Templates are URLs that contain variable names that Bitbucket will
        evaluate at runtime whenever the URL is displayed anywhere similar to
        parameter substitution in
        [Bitbucket Connect](https://developer.atlassian.com/bitbucket/concepts/context-parameters.html).
        For example, one could use `https://foo.com/builds/{repository.full_name}`
        which Bitbucket will turn into `https://foo.com/builds/foo/bar` at render time.
        The context variables available are `repository` and `commit`.
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - repositories
        - commitstatuses
  '/repositories/{username}/{repo_slug}/commit/{node}/statuses/build/{key}':
    get:
      description: Returns the specified build status for a commit.
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - repositories
        - commitstatuses
    put:
      description: |-
        Used to update the current status of a build status object on the
        specific commit.

        This operation can also be used to change other properties of the
        build status:

        * `state`
        * `name`
        * `description`
        * `url`
        * `refname`

        The `key` cannot be changed.
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - repositories
        - commitstatuses
  '/repositories/{username}/{repo_slug}/commit/{revision}':
    get:
      description: Returns the specified commit.
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - commits
  '/repositories/{username}/{repo_slug}/commit/{sha}/comments':
    get:
      description: |-
        Returns the commit's comments.

        This includes both global and inline comments.

        The default sorting is oldest to newest and can be overridden with
        the `sort` query parameter.
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - commits
  '/repositories/{username}/{repo_slug}/commit/{sha}/comments/{comment_id}':
    get:
      description: Returns the specified commit comment.
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - commits
  '/repositories/{username}/{repo_slug}/commits':
    get:
      description: |-
        These are the repository's commits. They are paginated and returned
        in reverse chronological order, similar to the output of `git log` and
        `hg log`. Like these tools, the DAG can be filtered.

        ## GET /repositories/{username}/{repo_slug}/commits/

        Returns all commits in the repo in topological order (newest commit
        first). All branches and tags are included (similar to
        `git log --all` and `hg log`).

        ## GET /repositories/{username}/{repo_slug}/commits/master

        Returns all commits on rev `master` (similar to `git log master`,
        `hg log master`).

        ## GET /repositories/{username}/{repo_slug}/commits/dev?exclude=master

        Returns all commits on ref `dev`, except those that are reachable on
        `master` (similar to `git log dev ^master`).

        ## GET /repositories/{username}/{repo_slug}/commits/?exclude=master

        Returns all commits in the repo that are not on master
        (similar to `git log --all ^master`).

        ## GET /repositories/{username}/{repo_slug}/commits/?include=foo&include=bar&exclude=fu&exclude=fubar

        Returns all commits that are on refs `foo` or `bar`, but not on `fu` or
        `fubar` (similar to `git log foo bar ^fu ^fubar`).

        Because the response could include a very large number of commits, it
        is paginated. Follow the 'next' link in the response to navigate to the
        next page of commits. As with other paginated resources, do not
        construct your own links.

        When the include and exclude parameters are more than ca fit in a
        query string, clients can use a `x-www-form-urlencoded` POST instead.
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - commits
    post:
      description: |-
        Identical to `GET /repositories/{username}/{repo_slug}/commits`,
        except that POST allows clients to place the include and exclude
        parameters in the request body to avoid URL length issues.

        **Note that this resource does NOT support new commit creation.**
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - commits
  '/repositories/{username}/{repo_slug}/commits/{revision}':
    get:
      description: |-
        These are the repository's commits. They are paginated and returned
        in reverse chronological order, similar to the output of `git log` and
        `hg log`. Like these tools, the DAG can be filtered.

        ## GET /repositories/{username}/{repo_slug}/commits/

        Returns all commits in the repo in topological order (newest commit
        first). All branches and tags are included (similar to
        `git log --all` and `hg log`).

        ## GET /repositories/{username}/{repo_slug}/commits/master

        Returns all commits on rev `master` (similar to `git log master`,
        `hg log master`).

        ## GET /repositories/{username}/{repo_slug}/commits/dev?exclude=master

        Returns all commits on ref `dev`, except those that are reachable on
        `master` (similar to `git log dev ^master`).

        ## GET /repositories/{username}/{repo_slug}/commits/?exclude=master

        Returns all commits in the repo that are not on master
        (similar to `git log --all ^master`).

        ## GET /repositories/{username}/{repo_slug}/commits/?include=foo&include=bar&exclude=fu&exclude=fubar

        Returns all commits that are on refs `foo` or `bar`, but not on `fu` or
        `fubar` (similar to `git log foo bar ^fu ^fubar`).

        Because the response could include a very large number of commits, it
        is paginated. Follow the 'next' link in the response to navigate to the
        next page of commits. As with other paginated resources, do not
        construct your own links.

        When the include and exclude parameters are more than ca fit in a
        query string, clients can use a `x-www-form-urlencoded` POST instead.
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - commits
    post:
      description: |-
        Identical to `GET /repositories/{username}/{repo_slug}/commits`,
        except that POST allows clients to place the include and exclude
        parameters in the request body to avoid URL length issues.

        **Note that this resource does NOT support new commit creation.**
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - commits
  '/repositories/{username}/{repo_slug}/components':
    get:
      description: |-
        Returns the components that have been defined in the issue tracker.

        This resource is only available on repositories that have the issue
        tracker enabled.
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
  '/repositories/{username}/{repo_slug}/components/{component_id}':
    get:
      description: Returns the specified issue tracker component object.
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
  '/repositories/{username}/{repo_slug}/default-reviewers':
    get:
      description: |-
        Returns the repository's default reviewers.

        These are the users that are automatically added as reviewers on every
        new pull request that is created.
      security:
        - oauth2:
            - 'repository:admin'
        - basic: []
        - api_key: []
      tags:
        - pullrequests
  '/repositories/{username}/{repo_slug}/default-reviewers/{target_username}':
    delete:
      description: Removes a default reviewer from the repository.
      security:
        - oauth2:
            - 'repository:admin'
        - basic: []
        - api_key: []
      tags:
        - pullrequests
    get:
      description: |-
        Returns the specified reviewer.

        This can be used to test whether a user is among the repository's
        default reviewers list. A 404 indicates that that specified user is not
        a default reviewer.
      security:
        - oauth2:
            - 'repository:admin'
        - basic: []
        - api_key: []
      tags:
        - pullrequests
    put:
      description: |-
        Adds the specified user to the repository's list of default
        reviewers.

        This method is idempotent. Adding a user a second time has no effect.
      security:
        - oauth2:
            - 'repository:admin'
        - basic: []
        - api_key: []
      tags:
        - pullrequests
  '/repositories/{username}/{repo_slug}/diff/{spec}':
    get:
      description: |-
        Produces a raw, git-style diff for either a single commit (diffed
        against its first parent), or a revspec of 2 commits (e.g.
        `3a8b42..9ff173` where the first commit represents the source and the
        second commit the destination).

        In case of the latter (diffing a revspec), a 3-way diff, or merge diff,
        is computed. This shows the changes introduced by the left branch
        (`3a8b42` in our example) as compared againt the right branch
        (`9ff173`).

        This is equivalent to merging the left branch into the right branch and
        then computing the diff of the merge commit against its first parent
        (the right branch). This follows the same behavior as pull requests
        that also show this style of 3-way, or merge diff.

        While similar to patches, diffs:

        * Don't have a commit header (username, commit message, etc)
        * Support the optional `path=foo/bar.py` query param to filter
          the diff to just that one file diff

        The raw diff is returned as-is, in whatever encoding the files in the
        repository use. It is not decoded into unicode. As such, the
        content-type is `text/plain`.
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - commits
  '/repositories/{username}/{repo_slug}/downloads':
    get:
      description: Returns a list of download links associated with the repository.
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - downloads
    post:
      description: |-
        Upload new download artifacts.

        To upload files, perform a `multipart/form-data` POST containing one
        or more `files` fields:

            $ echo Hello World > hello.txt
            $ curl -s -u evzijst -X POST https://api.bitbucket.org/2.0/repositories/evzijst/git-tests/downloads -F files=@hello.txt

        When a file is uploaded with the same name as an existing artifact,
        then the existing file will be replaced.
      security:
        - oauth2:
            - 'repository:write'
        - basic: []
        - api_key: []
      tags:
        - downloads
  '/repositories/{username}/{repo_slug}/downloads/{filename}':
    delete:
      description: Deletes the specified download artifact from the repository.
      security:
        - oauth2:
            - 'repository:write'
        - basic: []
        - api_key: []
      tags:
        - downloads
    get:
      description: |-
        Return a redirect to the contents of a download artifact.

        This endpoint returns the actual file contents and not the artifact's
        metadata.

            $ curl -s -L https://api.bitbucket.org/2.0/repositories/evzijst/git-tests/downloads/hello.txt
            Hello World
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - downloads
  '/repositories/{username}/{repo_slug}/forks':
    get:
      description: |-
        Returns a paginated list of all the forks of the specified
        repository.
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - repositories
  '/repositories/{username}/{repo_slug}/hooks':
    get:
      description: Returns a paginated list of webhooks installed on this repository.
      security:
        - oauth2:
            - webhook
        - basic: []
        - api_key: []
      tags:
        - repositories
        - webhooks
    post:
      description: |-
        Creates a new webhook on the specified repository.

        Example:

        ```
        $ curl -X POST -u credentials -H 'Content-Type: application/json'           https://api.bitbucket.org/2.0/repositories/username/slug/hooks           -d '
            {
              "description": "Webhook Description",
              "url": "https://example.com/",
              "active": true,
              "events": [
                "repo:push",
                "issue:created",
                "issue:updated"
              ]
            }'
        ```

        Note that this call requires the webhook scope, as well as any scope
        that applies to the events that the webhook subscribes to. In the
        example above that means: `webhook`, `repository` and `issue`.

        Also note that the `url` must properly resolve and cannot be an
        internal, non-routed address.
      security:
        - oauth2:
            - webhook
        - basic: []
        - api_key: []
      tags:
        - repositories
        - webhooks
  '/repositories/{username}/{repo_slug}/hooks/{uid}':
    delete:
      description: |-
        Deletes the specified webhook subscription from the given
        repository.
      security:
        - oauth2:
            - webhook
        - basic: []
        - api_key: []
      tags:
        - repositories
        - webhooks
    get:
      description: |-
        Returns the webhook with the specified id installed on the specified
        repository.
      security:
        - oauth2:
            - webhook
        - basic: []
        - api_key: []
      tags:
        - repositories
        - webhooks
    put:
      description: |-
        Updates the specified webhook subscription.

        The following properties can be mutated:

        * `description`
        * `url`
        * `active`
        * `events`
      security:
        - oauth2:
            - webhook
        - basic: []
        - api_key: []
      tags:
        - repositories
        - webhooks
  '/repositories/{username}/{repo_slug}/issues':
    get:
      description: Returns the issues in the issue tracker.
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
    post:
      description: |-
        Creates a new issue.

        This call requires authentication. Private repositories or private
        issue trackers require the caller to authenticate with an account that
        has appropriate authorisation.

        The authenticated user is used for the issue's `reporter` field.
      security:
        - oauth2:
            - 'issue:write'
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
  '/repositories/{username}/{repo_slug}/issues/{issue_id}':
    delete:
      description: |-
        Deletes the specified issue. This requires write access to the
        repository.
      security:
        - oauth2:
            - 'issue:write'
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
    get:
      description: Returns the specified issue.
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
  '/repositories/{username}/{repo_slug}/issues/{issue_id}/attachments':
    get:
      description: |-
        Returns all attachments for this issue.

        This returns the files' meta data. This does not return the files'
        actual contents.

        The files are always ordered by their upload date.
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
    post:
      description: |-
        Upload new issue attachments.

        To upload files, perform a `multipart/form-data` POST containing one
        or more file fields.

        When a file is uploaded with the same name as an existing attachment,
        then the existing file will be replaced.
      security:
        - oauth2:
            - 'issue:write'
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
  '/repositories/{username}/{repo_slug}/issues/{issue_id}/attachments/{path}':
    delete:
      description: Deletes an attachment.
      security:
        - oauth2:
            - 'issue:write'
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
    get:
      description: |-
        Returns the contents of the specified file attachment.

        Note that this endpoint does not return a JSON response, but instead
        returns a redirect pointing to the actual file that in turn will return
        the raw contents.

        The redirect URL contains a one-time token that has a limited lifetime.
        As a result, the link should not be persisted, stored, or shared.
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
  '/repositories/{username}/{repo_slug}/issues/{issue_id}/comments':
    get:
      description: |-
        Returns all comments that were made on the specified issue.

        The default sorting is oldest to newest and can be overridden with
        the `sort` query parameter.
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
  '/repositories/{username}/{repo_slug}/issues/{issue_id}/comments/{comment_id}':
    get:
      description: Returns the specified issue comment object.
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
  '/repositories/{username}/{repo_slug}/issues/{issue_id}/vote':
    delete:
      description: Retract your vote.
      security:
        - oauth2:
            - 'issue:write'
            - 'account:write'
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
    get:
      description: |-
        Check whether the authenticated user has voted for this issue.
        A 204 status code indicates that the user has voted, while a 404
        implies they haven't.
      security:
        - oauth2:
            - issue
            - account
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
    put:
      description: |-
        Vote for this issue.

        To cast your vote, do an empty PUT. The 204 status code indicates that
        the operation was successful.
      security:
        - oauth2:
            - issue
            - 'account:write'
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
  '/repositories/{username}/{repo_slug}/issues/{issue_id}/watch':
    delete:
      description: Stop watching this issue.
      security:
        - oauth2:
            - 'issue:write'
            - 'account:write'
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
    get:
      description: |-
        Indicated whether or not the authenticated user is watching this
        issue.
      security:
        - oauth2:
            - issue
            - account
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
    put:
      description: |-
        Start watching this issue.

        To start watching this issue, do an empty PUT. The 204 status code
        indicates that the operation was successful.
      security:
        - oauth2:
            - issue
            - 'account:write'
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
  '/repositories/{username}/{repo_slug}/milestones':
    get:
      description: |-
        Returns the milestones that have been defined in the issue tracker.

        This resource is only available on repositories that have the issue
        tracker enabled.
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
  '/repositories/{username}/{repo_slug}/milestones/{milestone_id}':
    get:
      description: Returns the specified issue tracker milestone object.
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
  '/repositories/{username}/{repo_slug}/patch/{spec}':
    get:
      description: |-
        Produces a raw patch for a single commit (diffed against its first
        parent), or a patch-series for a revspec of 2 commits (e.g.
        `3a8b42..9ff173` where the first commit represents the source and the
        second commit the destination).

        In case of the latter (diffing a revspec), a patch series is returned
        for the commits on the source branch (`3a8b42` and its ancestors in
        our example). For Mercurial, a single patch is returned that combines
        the changes of all commits on the source branch.

        While similar to diffs, patches:

        * Have a commit header (username, commit message, etc)
        * Do not support the `path=foo/bar.py` query parameter

        The raw patch is returned as-is, in whatever encoding the files in the
        repository use. It is not decoded into unicode. As such, the
        content-type is `text/plain`.
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - commits
  '/repositories/{username}/{repo_slug}/pipelines/':
    get:
      description: Find pipelines
      operationId: getPipelinesForRepository
      tags:
        - pipelines
    post:
      description: |
        Endpoint to create and initiate a pipeline. 
        There are a couple of different options to initiate a pipeline, where the payload of the request will determine which type of pipeline will be instantiated.
        # Trigger a Pipeline for a branch or tag
        One way to trigger pipelines is by specifying the reference for which you want to trigger a pipeline (e.g. a branch or tag). 
        The specified reference will be used to determine which pipeline definition from the `bitbucket-pipelines.yml` file will be applied to initiate the pipeline. The pipeline will then do a clone of the repository and checkout the latest revision of the specified reference.

        ### Example

        ```
        $ curl -X POST -is -u username:password \
          -H 'Content-Type: application/json' \
         https://api.bitbucket.org/2.0/repositories/jeroendr/meat-demo2/pipelines/ \
          -d '
          {
            "target": {
              "ref_type": "branch", 
              "type": "pipeline_ref_target", 
              "ref_name": "master"
            }
          }'
        ```
        # Trigger a Pipeline for a commit on a branch or tag
        You can initiate a pipeline for a specific commit and in the context of a specified reference (e.g. a branch, tag or bookmark).
        The specified reference will be used to determine which pipeline definition from the bitbucket-pipelines.yml file will be applied to initiate the pipeline. The pipeline will clone the repository and then do a checkout the specified reference. 

        The following reference types are supported:

        * `branch` 
        * `named_branch`
        * `bookmark` 
         * `tag`

        ### Example

        ```
        $ curl -X POST -is -u username:password \
          -H 'Content-Type: application/json' \
          https://api.bitbucket.org/2.0/repositories/jeroendr/meat-demo2/pipelines/ \
          -d '
          {
            "target": {
              "commit": {
                "type": "commit", 
                "hash": "ce5b7431602f7cbba007062eeb55225c6e18e956"
              }, 
              "ref_type": "branch", 
              "type": "pipeline_ref_target", 
              "ref_name": "master"
            }
          }'
        ```
        # Trigger a specific pipeline definition for a commit
        You can trigger a specific pipeline that is defined in your `bitbucket-pipelines.yml` file for a specific commit. 
        In addition to the commit revision, you specify the type and pattern of the selector that identifies the pipeline definition. The resulting pipeline will then clone the repository and checkout the specified revision.

        ### Example

        ```
        $ curl -X POST -is -u username:password \
          -H 'Content-Type: application/json' \
         https://api.bitbucket.org/2.0/repositories/jeroendr/meat-demo2/pipelines/ \
         -d '
          {
             "target": {
              "commit": {
                 "hash":"a3c4e02c9a3755eccdc3764e6ea13facdf30f923",
                 "type":"commit"
               },
                "selector": {
                   "type":"custom",
                      "pattern":"Deploy to production"
                  },
                "type":"pipeline_commit_target"
           }
          }'
        ```
        # Trigger a specific pipeline definition for a commit on a branch or tag
        You can trigger a specific pipeline that is defined in your `bitbucket-pipelines.yml` file for a specific commit in the context of a specified reference. 
        In addition to the commit revision, you specify the type and pattern of the selector that identifies the pipeline definition, as well as the reference information. The resulting pipeline will then clone the repository a checkout the specified reference.

        ### Example

        ```
        $ curl -X POST -is -u username:password \
          -H 'Content-Type: application/json' \
         https://api.bitbucket.org/2.0/repositories/jeroendr/meat-demo2/pipelines/ \
         -d '
          {
             "target": {
              "commit": {
                 "hash":"a3c4e02c9a3755eccdc3764e6ea13facdf30f923",
                 "type":"commit"
               },
               "selector": {
                  "type": "custom",
                  "pattern": "Deploy to production"
               },
               "type": "pipeline_ref_target",
               "ref_name": "master",
               "ref_type": "branch"
             }
          }'
        ```
      operationId: createPipelineForRepository
      tags:
        - pipelines
  '/repositories/{username}/{repo_slug}/pipelines/{pipeline_uuid}':
    get:
      description: Retrieve a specified pipeline
      operationId: getPipelineForRepository
      tags:
        - pipelines
  '/repositories/{username}/{repo_slug}/pipelines/{pipeline_uuid}/steps/':
    get:
      description: Find steps for the given pipeline.
      operationId: getPipelineStepsForRepository
      tags:
        - pipelines
  '/repositories/{username}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}':
    get:
      description: Retrieve a given step of a pipeline.
      operationId: getPipelineStepForRepository
      tags:
        - pipelines
  '/repositories/{username}/{repo_slug}/pipelines/{pipeline_uuid}/steps/{step_uuid}/log':
    get:
      description: |-
        Retrieve the log file for a given step of a pipeline.

        This endpoint supports (and encourages!) the use of [HTTP Range requests](https://tools.ietf.org/html/rfc7233) to deal with potentially very large log files.
      operationId: getPipelineStepLogForRepository
      tags:
        - pipelines
  '/repositories/{username}/{repo_slug}/pipelines/{pipeline_uuid}/stopPipeline':
    post:
      description: Signal the stop of a pipeline and all of its steps that not have completed yet.
      operationId: stopPipeline
      tags:
        - pipelines
  '/repositories/{username}/{repo_slug}/pipelines_config':
    get:
      description: Retrieve the repository pipelines configuration.
      operationId: getRepositoryPipelineConfig
      tags:
        - pipelines
    put:
      description: Update the pipelines configuration for a repository.
      operationId: updateRepositoryPipelineConfig
      tags:
        - pipelines
  '/repositories/{username}/{repo_slug}/pipelines_config/ssh/key_pair':
    delete:
      description: Delete the repository SSH key pair.
      operationId: deleteRepositoryPipelineKeyPair
      tags:
        - pipelines
    get:
      description: Retrieve the repository SSH key pair excluding the SSH private key. The private key is a write only field and will never be exposed in the logs or the REST API.
      operationId: getRepositoryPipelineSshKeyPair
      tags:
        - pipelines
    put:
      description: Create or update the repository SSH key pair. The private key will be set as a default SSH identity in your build container.
      operationId: updateRepositoryPipelineKeyPair
      tags:
        - pipelines
  '/repositories/{username}/{repo_slug}/pipelines_config/ssh/known_hosts/':
    get:
      description: Find repository level known hosts.
      operationId: getRepositoryPipelineKnownHosts
      tags:
        - pipelines
    post:
      description: Create a repository level known host.
      operationId: createRepositoryPipelineKnownHost
      tags:
        - pipelines
  '/repositories/{username}/{repo_slug}/pipelines_config/ssh/known_hosts/{known_host_uuid}':
    delete:
      description: Delete a repository level known host.
      operationId: deleteRepositoryPipelineKnownHost
      tags:
        - pipelines
    get:
      description: Retrieve a repository level known host.
      operationId: getRepositoryPipelineKnownHost
      tags:
        - pipelines
    put:
      description: Update a repository level known host.
      operationId: updateRepositoryPipelineKnownHost
      tags:
        - pipelines
  '/repositories/{username}/{repo_slug}/pipelines_config/variables/':
    get:
      description: Find repository level variables.
      operationId: getRepositoryPipelineVariables
      tags:
        - pipelines
    post:
      description: Create a repository level variable.
      operationId: createRepositoryPipelineVariable
      tags:
        - pipelines
  '/repositories/{username}/{repo_slug}/pipelines_config/variables/{variable_uuid}':
    delete:
      description: Delete a repository level variable.
      operationId: deleteRepositoryPipelineVariable
      tags:
        - pipelines
    get:
      description: Retrieve a repository level variable.
      operationId: getRepositoryPipelineVariable
      tags:
        - pipelines
    put:
      description: Update a repository level variable.
      operationId: updateRepositoryPipelineVariable
      tags:
        - pipelines
  '/repositories/{username}/{repo_slug}/pullrequests':
    get:
      description: |-
        Returns a paginated list of all pull requests on the specified
        repository. By default only open pull requests are returned. This can
        be controlled using the `state` query parameter. To retrieve pull
        requests that are in one of multiple states, repeat the `state`
        parameter for each individual state.

        This endpoint also supports filtering and sorting of the results. See
        [filtering and sorting](../../../../meta/filtering) for more details.
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      tags:
        - pullrequests
    post:
      description: Creates a new pull request.
      security:
        - oauth2:
            - 'pullrequest:write'
        - basic: []
        - api_key: []
      tags:
        - pullrequests
  '/repositories/{username}/{repo_slug}/pullrequests/activity':
    get:
      description: |-
        Returns a paginated list of the pull request's activity log.

        This includes comments that were made by the reviewers, updates and
        approvals.
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      tags:
        - pullrequests
  '/repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}':
    get:
      description: Returns the specified pull request.
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      tags:
        - pullrequests
    put:
      description: |-
        Mutates the specified pull request.

        This can be used to change the pull request's branches or description.

        Only open pull requests can be mutated.
      security:
        - oauth2:
            - 'pullrequest:write'
        - basic: []
        - api_key: []
      tags:
        - pullrequests
  '/repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/activity':
    get:
      description: |-
        Returns a paginated list of the pull request's activity log.

        This includes comments that were made by the reviewers, updates and
        approvals.
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      tags:
        - pullrequests
  '/repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/approve':
    delete:
      description: |-
        Redact the authenticated user's approval of the specified pull
        request.
      security:
        - oauth2:
            - 'pullrequest:write'
        - basic: []
        - api_key: []
      tags:
        - pullrequests
    post:
      description: Approve the specified pull request as the authenticated user.
      security:
        - oauth2:
            - 'pullrequest:write'
        - basic: []
        - api_key: []
      tags:
        - pullrequests
  '/repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/comments':
    get:
      description: |-
        Returns a paginated list of the pull request's comments.

        This includes both global, inline comments and replies.

        The default sorting is oldest to newest and can be overridden with
        the `sort` query parameter.

        This endpoint also supports filtering and sorting of the results. See
        [filtering and sorting](../../../../../../meta/filtering) for more
        details.
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      tags:
        - pullrequests
  '/repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/comments/{comment_id}':
    get:
      description: Returns a specific pull request comment.
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      tags:
        - pullrequests
  '/repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/commits':
    get:
      description: |-
        Returns a paginated list of the pull request's commits.

        These are the commits that are being merged into the destination
        branch when the pull requests gets accepted.
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      tags:
        - pullrequests
  '/repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/decline':
    post:
      description: Declines the pull request.
      security:
        - oauth2:
            - 'pullrequest:write'
        - basic: []
        - api_key: []
      tags:
        - pullrequests
  '/repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/diff':
    get:
      description: ''
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      tags:
        - pullrequests
  '/repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/merge':
    post:
      description: Merges the pull request.
      security:
        - oauth2:
            - 'pullrequest:write'
        - basic: []
        - api_key: []
      tags:
        - pullrequests
  '/repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/patch':
    get:
      description: ''
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      tags:
        - pullrequests
  '/repositories/{username}/{repo_slug}/pullrequests/{pull_request_id}/statuses':
    get:
      description: |-
        Returns all statuses (e.g. build results) for the given pull
        request.
      security:
        - oauth2:
            - pullrequest
        - basic: []
        - api_key: []
      tags:
        - repositories
        - pullrequests
        - commitstatuses
  '/repositories/{username}/{repo_slug}/refs':
    get:
      description: ''
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - refs
  '/repositories/{username}/{repo_slug}/refs/branches':
    get:
      description: ''
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - refs
  '/repositories/{username}/{repo_slug}/refs/branches/{name}':
    get:
      description: ''
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - refs
  '/repositories/{username}/{repo_slug}/refs/tags':
    get:
      description: ''
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - refs
    post:
      description: |-
        Creates a new tag in the specified repository.

        The payload of the POST should consist of a JSON document that
        contains the name of the tag and the target hash.

        ```
        {
            "name" : "new tag name",
            "target" : {
                "hash" : "target commit hash"
            }
        }
        ```

        This endpoint does support using short hash prefixes for the commit
        hash, but it may return a 400 response if the provided prefix is
        ambiguous. Using a full commit hash is the preferred approach.
      security:
        - oauth2:
            - 'repository:write'
        - basic: []
        - api_key: []
      tags:
        - refs
  '/repositories/{username}/{repo_slug}/refs/tags/{name}':
    get:
      description: ''
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - refs
  '/repositories/{username}/{repo_slug}/versions':
    get:
      description: |-
        Returns the versions that have been defined in the issue tracker.

        This resource is only available on repositories that have the issue
        tracker enabled.
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
  '/repositories/{username}/{repo_slug}/versions/{version_id}':
    get:
      description: Returns the specified issue tracker version object.
      security:
        - oauth2:
            - issue
        - basic: []
        - api_key: []
      tags:
        - issue_tracker
  '/repositories/{username}/{repo_slug}/watchers':
    get:
      description: |-
        Returns a paginated list of all the watchers on the specified
        repository.
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - repositories
  /snippets:
    get:
      description: |-
        Returns all snippets. Like pull requests, repositories and teams, the
        full set of snippets is defined by what the current user has access to.

        This includes all snippets owned by the current user, but also all snippets
        owned by any of the teams the user is a member of, or snippets by other
        users that the current user is either watching or has collaborated on (for
        instance by commenting on it).

        To limit the set of returned snippets, apply the
        `?role=[owner|contributor|member]` query parameter where the roles are
        defined as follows:

        * `owner`: all snippets owned by the current user
        * `contributor`: all snippets owned by, or watched by the current user
        * `member`: owned by the user, their teams, or watched by the current user

        When no role is specified, all public snippets are returned, as well as all
        privately owned snippets watched or commented on.

        The returned response is a normal paginated JSON list. This endpoint
        only supports `application/json` responses and no
        `multipart/form-data` or `multipart/related`. As a result, it is not
        possible to include the file contents.
      security:
        - oauth2:
            - snippet
        - basic: []
        - api_key: []
      tags:
        - snippets
    post:
      description: |-
        Creates a new snippet under the authenticated user's account.

        Snippets can contain multiple files. Both text and binary files are
        supported.

        The simplest way to create a new snippet from a local file:

            $ curl -u username:password -X POST https://api.bitbucket.org/2.0/snippets               -F file=@image.png

        Creating snippets through curl has a few limitations and so let's look
        at a more complicated scenario.

        Snippets are created with a multipart POST. Both `multipart/form-data`
        and `multipart/related` are supported. Both allow the creation of
        snippets with both meta data (title, etc), as well as multiple text
        and binary files.

        The main difference is that `multipart/related` can use rich encoding
        for the meta data (currently JSON).


        multipart/related (RFC-2387)
        ----------------------------

        This is the most advanced and efficient way to create a paste.

            POST /2.0/snippets/evzijst HTTP/1.1
            Content-Length: 1188
            Content-Type: multipart/related; start="snippet"; boundary="===============1438169132528273974=="
            MIME-Version: 1.0

            --===============1438169132528273974==
            Content-Type: application/json; charset="utf-8"
            MIME-Version: 1.0
            Content-ID: snippet

            {
              "title": "My snippet",
              "is_private": true,
              "scm": "hg",
              "files": {
                  "foo.txt": {},
                  "image.png": {}
                }
            }

            --===============1438169132528273974==
            Content-Type: text/plain; charset="us-ascii"
            MIME-Version: 1.0
            Content-Transfer-Encoding: 7bit
            Content-ID: "foo.txt"
            Content-Disposition: attachment; filename="foo.txt"

            foo

            --===============1438169132528273974==
            Content-Type: image/png
            MIME-Version: 1.0
            Content-Transfer-Encoding: base64
            Content-ID: "image.png"
            Content-Disposition: attachment; filename="image.png"

            iVBORw0KGgoAAAANSUhEUgAAABQAAAAoCAYAAAD+MdrbAAABD0lEQVR4Ae3VMUoDQRTG8ccUaW2m
            TKONFxArJYJamCvkCnZTaa+VnQdJSBFl2SMsLFrEWNjZBZs0JgiL/+KrhhVmJRbCLPx4O+/DT2TB
            cbblJxf+UWFVVRNsEGAtgvJxnLm2H+A5RQ93uIl+3632PZyl/skjfOn9Gvdwmlcw5aPUwimG+NT5
            EnNN036IaZePUuIcK533NVfal7/5yjWeot2z9ta1cAczHEf7I+3J0ws9Cgx0fsOFpmlfwKcWPuBQ
            73Oc4FHzBaZ8llq4q1mr5B2mOUCt815qYR8eB1hG2VJ7j35q4RofaH7IG+Xrf/PfJhfmwtfFYoIN
            AqxFUD6OMxcvkO+UfKfkOyXfKdsv/AYCHMLVkHAFWgAAAABJRU5ErkJggg==
            --===============1438169132528273974==--

        The request contains multiple parts and is structured as follows.

        The first part is the JSON document that describes the snippet's
        properties or meta data. It either has to be the first part, or the
        request's `Content-Type` header must contain the `start` parameter to
        point to it.

        The remaining parts are the files of which there can be zero or more.
        Each file part should contain the `Content-ID` MIME header through
        which the JSON meta data's `files` element addresses it. The value
        should be the name of the file.

        `Content-Disposition` is an optional MIME header. The header's
        optional `filename` parameter can be used to specify the file name
        that Bitbucket should use when writing the file to disk. When present,
        `filename` takes precedence over the value of `Content-ID`.

        When the JSON body omits the `files` element, the remaining parts are
        not ignored. Instead, each file is added to the new snippet as if its
        name was explicitly linked (the use of the `files` elements is
        mandatory for some operations like deleting or renaming files).


        multipart/form-data
        -------------------

        The use of JSON for the snippet's meta data is optional. Meta data can
        also be supplied as regular form fields in a more conventional
        `multipart/form-data` request:

            $ curl -X POST -u credentials https://api.bitbucket.org/2.0/snippets               -F title="My snippet"               -F file=@foo.txt -F file=@image.png

            POST /2.0/snippets HTTP/1.1
            Content-Length: 951
            Content-Type: multipart/form-data; boundary=----------------------------63a4b224c59f

            ------------------------------63a4b224c59f
            Content-Disposition: form-data; name="file"; filename="foo.txt"
            Content-Type: text/plain

            foo

            ------------------------------63a4b224c59f
            Content-Disposition: form-data; name="file"; filename="image.png"
            Content-Type: application/octet-stream

            ?PNG

            IHDR?1??I.....
            ------------------------------63a4b224c59f
            Content-Disposition: form-data; name="title"

            My snippet
            ------------------------------63a4b224c59f--

        Here the meta data properties are included as flat, top-level form
        fields. The file attachments use the `file` field name. To attach
        multiple files, simply repeat the field.

        The advantage of `multipart/form-data` over `multipart/related` is
        that it can be easier to build clients.

        Essentially all properties are optional, `title` and `files` included.


        Sharing and Visibility
        ----------------------

        Snippets can be either public (visible to anyone on Bitbucket, as well
        as anonymous users), or private (visible only to the owner, creator
        and members of the team in case the snippet is owned by a team). This
        is controlled through the snippet's `is_private` element:

        * **is_private=false** -- everyone, including anonymous users can view
          the snippet
        * **is_private=true** -- only the owner and team members (for team
          snippets) can view it

        To create the snippet under a team account, just append the team name
        to the URL (see `/2.0/snippets/{username}`).
      security:
        - oauth2:
            - 'snippet:write'
        - basic: []
        - api_key: []
      tags:
        - snippets
  '/snippets/{username}':
    get:
      description: |-
        Identical to `/snippets`, except that the result is further filtered
        by the snippet owner and only those that are owned by `{username}` are
        returned.
      security:
        - oauth2:
            - snippet
        - basic: []
        - api_key: []
      tags:
        - snippets
    post:
      description: |-
        Identical to `/snippets`, except that the new snippet will be
        created under the account specified in the path parameter `{username}`.
      security:
        - oauth2:
            - 'snippet:write'
        - basic: []
        - api_key: []
      tags:
        - snippets
  '/snippets/{username}/{encoded_id}':
    delete:
      description: Deletes a snippet and returns an empty response.
      security:
        - oauth2:
            - 'snippet:write'
        - basic: []
        - api_key: []
      tags:
        - snippets
    get:
      description: |-
        Retrieves a single snippet.

        Snippets support multiple content types:

        * application/json
        * multipart/related
        * multipart/form-data


        application/json
        ----------------

        The default content type of the response is `application/json`.
        Since JSON is always `utf-8`, it cannot reliably contain file contents
        for files that are not text. Therefore, JSON snippet documents only
        contain the filename and links to the file contents.

        This means that in order to retrieve all parts of a snippet, N+1
        requests need to be made (where N is the number of files in the
        snippet).


        multipart/related
        -----------------

        To retrieve an entire snippet in a single response, use the
        `Accept: multipart/related` HTTP request header.

            $ curl -H "Accept: multipart/related" https://api.bitbucket.org/2.0/snippets/evzijst/1

        Response:

            HTTP/1.1 200 OK
            Content-Length: 2214
            Content-Type: multipart/related; start="snippet"; boundary="===============1438169132528273974=="
            MIME-Version: 1.0

            --===============1438169132528273974==
            Content-Type: application/json; charset="utf-8"
            MIME-Version: 1.0
            Content-ID: snippet

            {
              "id": kypj,
              "title": "My snippet",
              "created_on": "2014-12-29T22:22:04.790331+00:00",
              "updated_on": "2014-12-29T22:22:04.790331+00:00",
              "is_private": false,
              "files": {
                "foo.txt": {
                },
                "image.png": {
                }
              ],
              "owner": {
                "username": "evzijst",
                "display_name": "Erik van Zijst",
                "uuid": "{d301aafa-d676-4ee0-88be-962be7417567}"
              },
              "creator": {
                "username": "evzijst",
                "display_name": "Erik van Zijst",
                "uuid": "{d301aafa-d676-4ee0-88be-962be7417567}"
              }
            }

            --===============1438169132528273974==
            Content-Type: text/plain; charset="us-ascii"
            MIME-Version: 1.0
            Content-Transfer-Encoding: 7bit
            Content-ID: "foo.txt"
            Content-Disposition: attachment; filename="foo.txt"

            foo

            --===============1438169132528273974==
            Content-Type: image/png
            MIME-Version: 1.0
            Content-Transfer-Encoding: base64
            Content-ID: "image.png"
            Content-Disposition: attachment; filename="image.png"

            iVBORw0KGgoAAAANSUhEUgAAABQAAAAoCAYAAAD+MdrbAAABD0lEQVR4Ae3VMUoDQRTG8ccUaW2m
            TKONFxArJYJamCvkCnZTaa+VnQdJSBFl2SMsLFrEWNjZBZs0JgiL/+KrhhVmJRbCLPx4O+/DT2TB
            cbblJxf+UWFVVRNsEGAtgvJxnLm2H+A5RQ93uIl+3632PZyl/skjfOn9Gvdwmlcw5aPUwimG+NT5
            EnNN036IaZePUuIcK533NVfal7/5yjWeot2z9ta1cAczHEf7I+3J0ws9Cgx0fsOFpmlfwKcWPuBQ
            73Oc4FHzBaZ8llq4q1mr5B2mOUCt815qYR8eB1hG2VJ7j35q4RofaH7IG+Xrf/PfJhfmwtfFYoIN
            AqxFUD6OMxcvkO+UfKfkOyXfKdsv/AYCHMLVkHAFWgAAAABJRU5ErkJggg==
            --===============1438169132528273974==--

        multipart/form-data
        -------------------

        As with creating new snippets, `multipart/form-data` can be used as an
        alternative to `multipart/related`. However, the inherently flat
        structure of form-data means that only basic, root-level properties
        can be returned, while nested elements like `links` are omitted:

            $ curl -H "Accept: multipart/form-data" https://api.bitbucket.org/2.0/snippets/evzijst/kypj

        Response:

            HTTP/1.1 200 OK
            Content-Length: 951
            Content-Type: multipart/form-data; boundary=----------------------------63a4b224c59f

            ------------------------------63a4b224c59f
            Content-Disposition: form-data; name="title"
            Content-Type: text/plain; charset="utf-8"

            My snippet
            ------------------------------63a4b224c59f--
            Content-Disposition: attachment; name="file"; filename="foo.txt"
            Content-Type: text/plain

            foo

            ------------------------------63a4b224c59f
            Content-Disposition: attachment; name="file"; filename="image.png"
            Content-Transfer-Encoding: base64
            Content-Type: application/octet-stream

            iVBORw0KGgoAAAANSUhEUgAAABQAAAAoCAYAAAD+MdrbAAABD0lEQVR4Ae3VMUoDQRTG8ccUaW2m
            TKONFxArJYJamCvkCnZTaa+VnQdJSBFl2SMsLFrEWNjZBZs0JgiL/+KrhhVmJRbCLPx4O+/DT2TB
            cbblJxf+UWFVVRNsEGAtgvJxnLm2H+A5RQ93uIl+3632PZyl/skjfOn9Gvdwmlcw5aPUwimG+NT5
            EnNN036IaZePUuIcK533NVfal7/5yjWeot2z9ta1cAczHEf7I+3J0ws9Cgx0fsOFpmlfwKcWPuBQ
            73Oc4FHzBaZ8llq4q1mr5B2mOUCt815qYR8eB1hG2VJ7j35q4RofaH7IG+Xrf/PfJhfmwtfFYoIN
            AqxFUD6OMxcvkO+UfKfkOyXfKdsv/AYCHMLVkHAFWgAAAABJRU5ErkJggg==
            ------------------------------5957323a6b76--
      security:
        - oauth2:
            - snippet
        - basic: []
        - api_key: []
      tags:
        - snippets
    put:
      description: |-
        Used to update a snippet. Use this to add and delete files and to
        change a snippet's title.

        To update a snippet, one can either PUT a full snapshot, or only the
        parts that need to be changed.

        The contract for PUT on this API is that properties missing from the
        request remain untouched so that snippets can be efficiently
        manipulated with differential payloads.

        To delete a property (e.g. the title, or a file), include its name in
        the request, but omit its value (use `null`).

        As in Git, explicit renaming of files is not supported. Instead, to
        rename a file, delete it and add it again under another name. This can
        be done atomically in a single request. Rename detection is left to
        the SCM.

        PUT supports three different content types for both request and
        response bodies:

        * `application/json`
        * `multipart/related`
        * `multipart/form-data`

        The content type used for the request body can be different than that
        used for the response. Content types are specified using standard HTTP
        headers.

        Use the `Content-Type` and `Accept` headers to select the desired
        request and response format.


        application/json
        ----------------

        As with creation and retrieval, the content type determines what
        properties can be manipulated. `application/json` does not support
        file contents and is therefore limited to a snippet's meta data.

        To update the title, without changing any of its files:

            $ curl -X POST -H "Content-Type: application/json" https://api.bitbucket.org/2.0/snippets/evzijst/kypj             -d '{"title": "Updated title"}'


        To delete the title:

            $ curl -X POST -H "Content-Type: application/json" https://api.bitbucket.org/2.0/snippets/evzijst/kypj             -d '{"title": null}'

        Not all parts of a snippet can be manipulated. The owner and creator
        for instance are immutable.


        multipart/related
        -----------------

        `multipart/related` can be used to manipulate all of a snippet's
        properties. The body is identical to a POST. properties omitted from
        the request are left unchanged. Since the `start` part contains JSON,
        the mechanism for manipulating the snippet's meta data is identical
        to `application/json` requests.

        To update one of a snippet's file contents, while also changing its
        title:

            PUT /2.0/snippets/evzijst/kypj HTTP/1.1
            Content-Length: 288
            Content-Type: multipart/related; start="snippet"; boundary="===============1438169132528273974=="
            MIME-Version: 1.0

            --===============1438169132528273974==
            Content-Type: application/json; charset="utf-8"
            MIME-Version: 1.0
            Content-ID: snippet

            {
              "title": "My updated snippet",
              "files": {
                  "foo.txt": {}
                }
            }

            --===============1438169132528273974==
            Content-Type: text/plain; charset="us-ascii"
            MIME-Version: 1.0
            Content-Transfer-Encoding: 7bit
            Content-ID: "foo.txt"
            Content-Disposition: attachment; filename="foo.txt"

            Updated file contents.

            --===============1438169132528273974==--

        Here only the parts that are changed are included in the body. The
        other files remain untouched.

        Note the use of the `files` list in the JSON part. This list contains
        the files that are being manipulated. This list should have
        corresponding multiparts in the request that contain the new contents
        of these files.

        If a filename in the `files` list does not have a corresponding part,
        it will be deleted from the snippet, as shown below:

            PUT /2.0/snippets/evzijst/kypj HTTP/1.1
            Content-Length: 188
            Content-Type: multipart/related; start="snippet"; boundary="===============1438169132528273974=="
            MIME-Version: 1.0

            --===============1438169132528273974==
            Content-Type: application/json; charset="utf-8"
            MIME-Version: 1.0
            Content-ID: snippet

            {
              "files": {
                "image.png": {}
              }
            }

            --===============1438169132528273974==--

        To simulate a rename, delete a file and add the same file under
        another name:

            PUT /2.0/snippets/evzijst/kypj HTTP/1.1
            Content-Length: 212
            Content-Type: multipart/related; start="snippet"; boundary="===============1438169132528273974=="
            MIME-Version: 1.0

            --===============1438169132528273974==
            Content-Type: application/json; charset="utf-8"
            MIME-Version: 1.0
            Content-ID: snippet

            {
                "files": {
                  "foo.txt": {},
                  "bar.txt": {}
                }
            }

            --===============1438169132528273974==
            Content-Type: text/plain; charset="us-ascii"
            MIME-Version: 1.0
            Content-Transfer-Encoding: 7bit
            Content-ID: "bar.txt"
            Content-Disposition: attachment; filename="bar.txt"

            foo

            --===============1438169132528273974==--


        multipart/form-data
        -----------------

        Again, one can also use `multipart/form-data` to manipulate file
        contents and meta data atomically.

            $ curl -X PUT http://localhost:12345/2.0/snippets/evzijst/kypj             -F title="My updated snippet" -F file=@foo.txt

            PUT /2.0/snippets/evzijst/kypj HTTP/1.1
            Content-Length: 351
            Content-Type: multipart/form-data; boundary=----------------------------63a4b224c59f

            ------------------------------63a4b224c59f
            Content-Disposition: form-data; name="file"; filename="foo.txt"
            Content-Type: text/plain

            foo

            ------------------------------63a4b224c59f
            Content-Disposition: form-data; name="title"

            My updated snippet
            ------------------------------63a4b224c59f

        To delete a file, omit its contents while including its name in the
        `files` field:

            $ curl -X PUT https://api.bitbucket.org/2.0/snippets/evzijst/kypj -F files=image.png

            PUT /2.0/snippets/evzijst/kypj HTTP/1.1
            Content-Length: 149
            Content-Type: multipart/form-data; boundary=----------------------------ef8871065a86

            ------------------------------ef8871065a86
            Content-Disposition: form-data; name="files"

            image.png
            ------------------------------ef8871065a86--

        The explicit use of the `files` element in `multipart/related` and
        `multipart/form-data` is only required when deleting files.
        The default mode of operation is for file parts to be processed,
        regardless of whether or not they are listed in `files`, as a
        convenience to the client.
      security:
        - oauth2:
            - 'snippet:write'
        - basic: []
        - api_key: []
      tags:
        - snippets
  '/snippets/{username}/{encoded_id}/comments':
    get:
      description: |-
        Used to retrieve a paginated list of all comments for a specific
        snippet.

        This resource works identical to commit and pull request comments.

        The default sorting is oldest to newest and can be overridden with
        the `sort` query parameter.
      security:
        - oauth2:
            - snippet
        - basic: []
        - api_key: []
      tags:
        - snippets
    post:
      description: |-
        Creates a new comment.

        The only required field in the body is `content.raw`.

        To create a threaded reply to an existing comment, include `parent.id`.
      security:
        - oauth2:
            - snippet
        - basic: []
        - api_key: []
      tags:
        - snippets
  '/snippets/{username}/{encoded_id}/comments/{comment_id}':
    delete:
      description: |-
        Deletes a snippet comment.

        Comments can only be removed by their author.
      security:
        - oauth2:
            - snippet
        - basic: []
        - api_key: []
      tags:
        - snippets
    get:
      description: Returns the specific snippet comment.
      security:
        - oauth2:
            - snippet
        - basic: []
        - api_key: []
      tags:
        - snippets
    put:
      description: |-
        Updates a comment.

        Comments can only be updated by their author.
      security:
        - oauth2:
            - snippet
        - basic: []
        - api_key: []
      tags:
        - snippets
  '/snippets/{username}/{encoded_id}/commits':
    get:
      description: Returns the changes (commits) made on this snippet.
      security:
        - oauth2:
            - snippet
        - basic: []
        - api_key: []
      tags:
        - snippets
  '/snippets/{username}/{encoded_id}/commits/{revision}':
    get:
      description: ''
      security:
        - oauth2:
            - snippet
        - basic: []
        - api_key: []
      tags:
        - snippets
  '/snippets/{username}/{encoded_id}/watch':
    delete:
      description: |-
        Used to stop watching a specific snippet. Returns 204 (No Content)
        to indicate success.
      security:
        - oauth2:
            - 'snippet:write'
        - basic: []
        - api_key: []
      tags:
        - snippets
    get:
      description: |-
        Used to check if the current user is watching a specific snippet.

        Returns 204 (No Content) if the user is watching the snippet and 404 if
        not.

        Hitting this endpoint anonymously always returns a 404.
      security:
        - oauth2:
            - snippet
        - basic: []
        - api_key: []
      tags:
        - snippets
    put:
      description: Used to start watching a specific snippet. Returns 204 (No Content).
      security:
        - oauth2:
            - 'snippet:write'
        - basic: []
        - api_key: []
      tags:
        - snippets
  '/snippets/{username}/{encoded_id}/watchers':
    get:
      deprecated: true
      description: Returns a paginated list of all users watching a specific snippet.
      security:
        - oauth2:
            - snippet
        - basic: []
        - api_key: []
      tags:
        - snippets
  '/snippets/{username}/{encoded_id}/{node_id}':
    delete:
      description: |-
        Deletes the snippet.

        Note that this only works for versioned URLs that point to the latest
        commit of the snippet. Pointing to an older commit results in a 405
        status code.

        To delete a snippet, regardless of whether or not concurrent changes
        are being made to it, use `DELETE /snippets/{encoded_id}` instead.
      security:
        - oauth2:
            - 'snippet:write'
        - basic: []
        - api_key: []
      tags:
        - snippets
    get:
      description: |-
        Identical to `GET /snippets/encoded_id`, except that this endpoint
        can be used to retrieve the contents of the snippet as it was at an
        older revision, while `/snippets/encoded_id` always returns the
        snippet's current revision.

        Note that only the snippet's file contents are versioned, not its
        meta data properties like the title.

        Other than that, the two endpoints are identical in behavior.
      security:
        - oauth2:
            - snippet
        - basic: []
        - api_key: []
      tags:
        - snippets
    put:
      description: |-
        Identical to `UPDATE /snippets/encoded_id`, except that this endpoint
        takes an explicit commit revision. Only the snippet's "HEAD"/"tip"
        (most recent) version can be updated and requests on all other,
        older revisions fail by returning a 405 status.

        Usage of this endpoint over the unrestricted `/snippets/encoded_id`
        could be desired if the caller wants to be sure no concurrent
        modifications have taken place between the moment of the UPDATE
        request and the original GET.

        This can be considered a so-called "Compare And Swap", or CAS
        operation.

        Other than that, the two endpoints are identical in behavior.
      security:
        - oauth2:
            - 'snippet:write'
        - basic: []
        - api_key: []
      tags:
        - snippets
  '/snippets/{username}/{encoded_id}/{node_id}/files/{path}':
    get:
      description: |-
        Retrieves the raw contents of a specific file in the snippet. The
        `Content-Disposition` header will be "attachment" to avoid issues with
        malevolent executable files.

        The file's mime type is derived from its filename and returned in the
        `Content-Type` header.

        Note that for text files, no character encoding is included as part of
        the content type.
      security:
        - oauth2:
            - snippet
        - basic: []
        - api_key: []
      tags:
        - snippets
  '/snippets/{username}/{encoded_id}/{revision}/diff':
    get:
      description: |-
        Returns the diff of the specified commit against its first parent.

        Note that this resource is different in functionality from the `patch`
        resource.

        The differences between a diff and a patch are:

        * patches have a commit header with the username, message, etc
        * diffs support the optional `path=foo/bar.py` query param to filter the
          diff to just that one file diff (not supported for patches)
        * for a merge, the diff will show the diff between the merge commit and
          its first parent (identical to how PRs work), while patch returns a
          response containing separate patches for each commit on the second
          parent's ancestry, up to the oldest common ancestor (identical to
          its reachability).

        Note that the character encoding of the contents of the diff is
        unspecified as Git and Mercurial do not track this, making it hard for
        Bitbucket to reliably determine this.
      security:
        - oauth2:
            - snippet
        - basic: []
        - api_key: []
      tags:
        - snippets
  '/snippets/{username}/{encoded_id}/{revision}/patch':
    get:
      description: |-
        Returns the patch of the specified commit against its first
        parent.

        Note that this resource is different in functionality from the `diff`
        resource.

        The differences between a diff and a patch are:

        * patches have a commit header with the username, message, etc
        * diffs support the optional `path=foo/bar.py` query param to filter the
          diff to just that one file diff (not supported for patches)
        * for a merge, the diff will show the diff between the merge commit and
          its first parent (identical to how PRs work), while patch returns a
          response containing separate patches for each commit on the second
          parent's ancestry, up to the oldest common ancestor (identical to
          its reachability).

        Note that the character encoding of the contents of the patch is
        unspecified as Git and Mercurial do not track this, making it hard for
        Bitbucket to reliably determine this.
      security:
        - oauth2:
            - snippet
        - basic: []
        - api_key: []
      tags:
        - snippets
  /teams:
    get:
      description: |-
        Returns all the teams that the authenticated user is associated
        with.
      security:
        - oauth2:
            - team
        - basic: []
        - api_key: []
      tags:
        - teams
  '/teams/{owner}/projects/':
    get:
      description: ''
      security:
        - oauth2:
            - project
        - basic: []
        - api_key: []
      tags:
        - projects
    post:
      description: |-
        Creates a new project.

        Note that the avatar has to be embedded as either a data-url
        or a URL to an external image as shown in the examples below:

        ```
        $ body=$(cat << EOF
        {
            "name": "Mars Project",
            "key": "MARS",
            "description": "Software for colonizing mars.",
            "is_private": false
        }
        EOF
        )
        $ curl -H "Content-Type: application/json" \
               -X POST \
               -d "$body" \
               https://api.bitbucket.org/2.0/teams/teams-in-space/projects/ | jq .
        {
          // Serialized project document
        }
        ```

        or even:

        ```
        $ body=$(cat << EOF
        {
            "name": "Mars Project",
            "key": "MARS",
            "description": "Software for colonizing mars.",
            "is_private": false
        }
        EOF
        )
        $ curl -H "Content-Type: application/json" \
               -X POST \
               -d "$body" \
               https://api.bitbucket.org/2.0/teams/teams-in-space/projects/ | jq .
        {
          // Serialized project document
        }
        ```
      security:
        - oauth2:
            - 'project:write'
        - basic: []
        - api_key: []
      tags:
        - projects
  '/teams/{owner}/projects/{project_key}':
    delete:
      description: ''
      security:
        - oauth2:
            - 'project:write'
        - basic: []
        - api_key: []
      tags:
        - projects
    get:
      description: ''
      security:
        - oauth2:
            - project
        - basic: []
        - api_key: []
      tags:
        - projects
    put:
      description: |-
        Since this endpoint can be used to both update and to create a
        project, the request body depends on the intent.

        ### Creation

        See the POST documentation for the project collection for an
        example of the request body.

        Note: The `key` should not be specified in the body of request
        (since it is already present in the URL). The `name` is required,
        everything else is optional.

        ### Update

        See the POST documentation for the project collection for an
        example of the request body.

        Note: The key is not required in the body (since it is already in
        the URL). The key may be specified in the body, if the intent is
        to change the key itself. In such a scenario, the location of the
        project is changed and is returned in the `Location` header of the
        response.
      security:
        - oauth2:
            - 'project:write'
        - basic: []
        - api_key: []
      tags:
        - projects
  '/teams/{username}':
    get:
      description: |-
        Gets the public information associated with a team.

        If the team's profile is private, `location`, `website` and
        `created_on` elements are omitted.
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      tags:
        - teams
  '/teams/{username}/followers':
    get:
      description: Returns the list of accounts that are following this team.
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      tags:
        - teams
  '/teams/{username}/following':
    get:
      description: Returns the list of accounts this team is following.
      security:
        - oauth2:
            - account
        - basic: []
        - api_key: []
      tags:
        - teams
  '/teams/{username}/hooks':
    get:
      description: Returns a paginated list of webhooks installed on this team.
      security:
        - oauth2:
            - webhook
        - basic: []
        - api_key: []
      tags:
        - teams
        - webhooks
    post:
      description: |-
        Creates a new webhook on the specified team.

        Team webhooks are fired for events from all repositories belonging to
        that team account.

        Note that only admins can install webhooks on teams.
      security:
        - oauth2:
            - webhook
        - basic: []
        - api_key: []
      tags:
        - teams
        - webhooks
  '/teams/{username}/hooks/{uid}':
    delete:
      description: |-
        Deletes the specified webhook subscription from the given team
        account.
      security:
        - oauth2:
            - webhook
        - basic: []
        - api_key: []
      tags:
        - teams
        - webhooks
    get:
      description: |-
        Returns the webhook with the specified id installed on the given
        team account.
      security:
        - oauth2:
            - webhook
        - basic: []
        - api_key: []
      tags:
        - teams
        - webhooks
    put:
      description: |-
        Updates the specified webhook subscription.

        The following properties can be mutated:

        * `description`
        * `url`
        * `active`
        * `events`
      security:
        - oauth2:
            - webhook
        - basic: []
        - api_key: []
      tags:
        - teams
        - webhooks
  '/teams/{username}/members':
    get:
      description: |-
        All members of a team.

        Returns all members of the specified team. Any member of any of the
        team's groups is considered a member of the team. This includes users
        in groups that may not actually have access to any of the team's
        repositories.

        Note that members using the "private profile" feature are not included.
      security:
        - oauth2:
            - account
        - basic: []
        - api_key: []
      tags:
        - teams
  '/teams/{username}/pipelines_config/variables/':
    get:
      description: Find account level variables.
      operationId: getPipelineVariablesForTeam
      tags:
        - pipelines
    post:
      description: Create an account level variable.
      operationId: createPipelineVariableForTeam
      tags:
        - pipelines
  '/teams/{username}/pipelines_config/variables/{variable_uuid}':
    delete:
      description: Delete a team level variable.
      operationId: deletePipelineVariableForTeam
      tags:
        - pipelines
    get:
      description: Retrieve a team level variable.
      operationId: getPipelineVariableForTeam
      tags:
        - pipelines
    put:
      description: Update a team level variable.
      operationId: updatePipelineVariableForTeam
      tags:
        - pipelines
  '/teams/{username}/repositories':
    get:
      description: |-
        All repositories owned by a user/team. This includes private
        repositories, but filtered down to the ones that the calling user has
        access to.
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - users
        - teams
  /user:
    get:
      description: Returns the currently logged in user.
      security:
        - oauth2:
            - account
        - basic: []
        - api_key: []
      tags:
        - users
  /user/emails:
    get:
      description: |-
        Returns all the authenticated user's email addresses. Both
        confirmed and unconfirmed.
      security:
        - oauth2:
            - email
        - basic: []
        - api_key: []
      tags:
        - users
  '/user/emails/{email}':
    get:
      description: |-
        Returns details about a specific one of the authenticated user's
        email addresses.

        Details describe whether the address has been confirmed by the user and
        whether it is the user's primary address or not.
      security:
        - oauth2:
            - email
        - basic: []
        - api_key: []
      tags:
        - users
  '/users/{username}':
    get:
      description: |-
        Gets the public information associated with a user account.

        If the user's profile is private, `location`, `website` and
        `created_on` elements are omitted.
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      tags:
        - users
  '/users/{username}/followers':
    get:
      description: Returns the list of accounts that are following this team.
      security:
        - oauth2: []
        - basic: []
        - api_key: []
      tags:
        - users
  '/users/{username}/following':
    get:
      description: Returns the list of accounts this user is following.
      security:
        - oauth2:
            - account
        - basic: []
        - api_key: []
      tags:
        - users
  '/users/{username}/hooks':
    get:
      description: Returns a paginated list of webhooks installed on this user account.
      security:
        - oauth2:
            - webhook
        - basic: []
        - api_key: []
      tags:
        - users
        - webhooks
    post:
      description: |-
        Creates a new webhook on the specified user account.

        Account-level webhooks are fired for events from all repositories
        belonging to that account.

        Note that one can only register webhooks on one's own account, not that
        of others.
      security:
        - oauth2:
            - webhook
        - basic: []
        - api_key: []
      tags:
        - users
        - webhooks
  '/users/{username}/hooks/{uid}':
    delete:
      description: |-
        Deletes the specified webhook subscription from the given user
        account.
      security:
        - oauth2:
            - webhook
        - basic: []
        - api_key: []
      tags:
        - users
        - webhooks
    get:
      description: |-
        Returns the webhook with the specified id installed on the given
        user account.
      security:
        - oauth2:
            - webhook
        - basic: []
        - api_key: []
      tags:
        - users
        - webhooks
    put:
      description: |-
        Updates the specified webhook subscription.

        The following properties can be mutated:

        * `description`
        * `url`
        * `active`
        * `events`
      security:
        - oauth2:
            - webhook
        - basic: []
        - api_key: []
      tags:
        - users
        - webhooks
  '/users/{username}/pipelines_config/variables/':
    get:
      description: Find user level variables.
      operationId: getPipelineVariablesForUser
      tags:
        - pipelines
    post:
      description: Create a user level variable.
      operationId: createPipelineVariableForUser
      tags:
        - pipelines
  '/users/{username}/pipelines_config/variables/{variable_uuid}':
    delete:
      description: Delete an account level variable.
      operationId: deletePipelineVariableForUser
      tags:
        - pipelines
    get:
      description: Retrieve a user level variable.
      operationId: getPipelineVariableForUser
      tags:
        - pipelines
    put:
      description: Update a user level variable.
      operationId: updatePipelineVariableForUser
      tags:
        - pipelines
  '/users/{username}/repositories':
    get:
      description: |-
        All repositories owned by a user/team. This includes private
        repositories, but filtered down to the ones that the calling user has
        access to.
      security:
        - oauth2:
            - repository
        - basic: []
        - api_key: []
      tags:
        - users
        - teams
x-radar-pages:
  - content: |

      # Authentication methods

      The purpose of this section is to describe how to authenticate when making API calls using the Bitbucket REST API.

      -----

      *On this page*

      * [Oauth 2](#oauth-2)
        * [Making requests](#make-requests)
        * [Repository cloning](#repo-clone)
        * [Refresh tokens](#refresh-tokens)
      * [Scopes](#scopes-bbc)
      * [App passwords](#app-pw)
      * [Basic auth](#basic-auth)

      ---

      # Bitbucket Cloud OAuth 2.0 <a name="oauth-2"></a>

      Our OAuth 2 implementation is merged in with our existing OAuth 1 in
      such a way that existing OAuth 1 consumers automatically become
      valid OAuth 2 clients. The only thing you need to do is edit your
      existing consumer and configure a callback URL.

      Once that is in place, you'll have the following 2 URLs:

          https://bitbucket.org/site/oauth2/authorize
          https://bitbucket.org/site/oauth2/access_token

      For obtaining access/bearer tokens, we support all 4 of RFC-6749's grant
      flows, plus a custom Bitbucket flow for exchanging JWT tokens for access tokens:


      ### 1. Authorization Code Grant (4.1)

      The full-blown 3-LO flow. Request authorization from the end user by
      sending their browser to:

          https://bitbucket.org/site/oauth2/authorize?client_id={client_id}&response_type=code

      The callback includes the `?code={}` query parameter that you can swap
      for an access token:

          $ curl -X POST -u "client_id:secret" \
            https://bitbucket.org/site/oauth2/access_token \
            -d grant_type=authorization_code -d code={code}


      ### 2. Implicit Grant (4.2)

      This flow is useful for browser-based add-ons that operate without server-side backends.

      Request the end user for authorization by directing the browser to:

          https://bitbucket.org/site/oauth2/authorize?client_id={client_id}&response_type=token

      That will redirect to your preconfigured callback URL with a fragment
      containing the access token
      (`#access_token={token}&token_type=bearer`) where your page's js can
      pull it out of the URL.


      ### 3. Resource Owner Password Credentials Grant (4.3)

      Useful if you have the end user's password but you want to use a more
      secure end user access token instead. This method will not work when the user has two-step verification enabled.

          $ curl -X POST -u "client_id:secret" \
            https://bitbucket.org/site/oauth2/access_token -d grant_type=password \
            -d username={username} -d password={password}


      ### 4. Client Credentials Grant (4.4)

      Somewhat like our existing "2-LO" flow for OAuth 1. Obtain an access
      token that represents not an end user, but the owner of the
      client/consumer:

          $ curl -X POST -u "client_id:secret" \
            https://bitbucket.org/site/oauth2/access_token \
            -d grant_type=client_credentials


      ### 5. Bitbucket Cloud JWT Grant (urn:bitbucket:oauth2:jwt)

      If your Atlassian Connect add-on uses JWT authentication, you can swap a
      JWT for an OAuth access token. The resulting access token represents the
      account for which the add-on is installed.

      Make sure you send the JWT token in the Authorization request header
      using the "JWT" scheme (case sensitive). Note that this custom scheme
      makes this different from HTTP Basic Auth (and so you cannot use "curl
      -u").

          $ curl -X POST -H "Authorization: JWT {jwt_token}" \
            https://bitbucket.org/site/oauth2/access_token \
            -d grant_type=urn:bitbucket:oauth2:jwt


      ## Making Requests <a name="make-requests"></a>

      Once you have an access token, as per RFC-6750, you can use it in a request in any of
      the following ways (in decreasing order of desirability):

      1. Send it in a request header: `Authorization: Bearer {access_token}`
      2. Include it in a (application/x-www-form-urlencoded) POST body as `access_token={access_token}`
      3. Put it in the query string of a non-POST: `?access_token={access_token}`


      ## Repository Cloning <a name="repo-clone"></a>

      Since add-ons will not be able to upload their own SSH keys to clone
      with, access tokens can be used as Basic HTTP Auth credentials to
      clone securely over HTTPS. This is much like GitHub, yet slightly
      different:

          $ git clone https://x-token-auth:{access_token}@bitbucket.org/user/repo.git

      The literal string `x-token-auth` as a substitute for username is
      required (note the difference with GitHub where the actual token is in
      the username field).


      ## Refresh Tokens <a name="refresh-tokens"></a>

      Our access tokens expire in one hour. When this happens you'll get 401
      responses.

      Most access tokens grant responses (Implicit and JWT excluded). Therefore, you should include a
      refresh token that can then be used to generate a new access token,
      without the need for end user participation:

          $ curl -X POST -u "client_id:secret" \
            https://bitbucket.org/site/oauth2/access_token \
            -d grant_type=refresh_token -d refresh_token={refresh_token}


      # Scopes for the Bitbucket Cloud REST API <a name="scopes-bbc"></a>

      Bitbucket's API applies a number of privilege scopes to endpoints. In order to access an endpoint, a request will need to have the necessary scopes.

      Scopes are declared in the descriptor as a list of strings, with each string being the name of a unique scope.

      A descriptor lacking the `scopes` element is implicitly assumed to require all scopes and as a result, Bitbucket will require end users authorizing/installing the add-on
      to explicitly accept all scopes.

      Our best practice suggests you add the scopes your add-on needs, but no more than it needs.

      Invalid scope strings will cause the descriptor to be rejected and the installation to fail.

      Following is the set of all currently available scopes.

      ### repository

      Gives the add-on read access to all the repositories the authorizing user has access to.
      Note that this scope does not give access to a repository's pull requests.

      * access to the repo's source code
      * clone over https
      * access the the file browsing API
      * download zip archives of the repo's contents
      * the ability to view and use the issue tracker on any repo (created issues, comment, vote, etc)
      * the ability to view and use the wiki on any repo (create/edit pages)

      ### repository:write

      Gives the add-on write (not admin) access to all the repositories the authorizing user has access to. No distinction is made between public or private repos. This scope implies `repository`, which does not need to be requested separately.
      This scope alone does not give access to the pull requests API.

      * push access over https
      * fork repos

      ### repository:admin

      Gives the add-on admin access to all the repositories the authorizing user has access to. No distinction is made between public or private repos. This scope does not imply `repository` or `repository:write`. It gives access to the admin features of a repo only, not direct access to its contents. Of course it can be (mis)used to grant read access to another user account who can then clone the repo, but repos that need to read of write source code would also request explicit read or write.
      This scope comes with access to the following functionality:

      * view and manipulate committer mappings
      * list and edit deploy keys
      * ability to delete the repo
      * view and edit repo permissions
      * view and edit branch permissions
      * import and export the issue tracker
      * enable and disable the issue tracker
      * list and edit issue tracker version, milestones and components
      * enable and disable the wiki
      * list and edit default reviewers
      * list and edit repo links (JIRA/Bamboo/Custom)
      * list and edit the repository web hooks
      * initiate a repo ownership transfer

      ### snippet

      Gives the add-on read access to all the snippets the authorizing user has access to.
      No distinction is made between public and private snippets (public snippets are accessible without any form of authentication).

      * view any snippet
      * create snippet comments

      ### snippet:write

      Gives the add-on write access to all the snippets the authorizing user can edit.
      No distinction is made between public and private snippets (public snippets are accessible without any form of authentication).
      This implies the Snippet Read scope which does not need to be requested separately.

      * edit snippets
      * delete snippets

      ### issue

      Ability to interact with issue trackers the way non-repo members can.
      This scope does not imply any other scopes and does not give implicit access to the repository the issue is attached to.

      * view, list and search issues
      * create new issues
      * comment on issues
      * watch issues
      * vote for issues

      ### issue:write

      This implies `issue`, but adds the ability to transition and delete issues.
      This scope does not imply any other scopes and does not give implicit access to the repository the issue is attached to.

      * transition issues
      * delete issues

      ### wiki

      Gives access to wikis. No distinction is made between read and write as wikis are always editable by anyone.
      This scope does not imply any other scopes and does not give implicit access to the repository the wiki is attached to.

      * view wikis
      * create pages
      * edit pages
      * push to wikis
      * clone wikis

      ### pullrequest

      Gives the add-on read access to pull requests.
      This scope implies `repository`, giving read access to the pull request's destination repository.

      * see and list pull requests
      * create and resolve tasks

      ### pullrequest:write

      Implies `pullrequest` but adds the ability to create, merge and decline pull requests.
      This scope implies `repository:write`, giving write access to the pull request's destination repository. This is necessary to facilitate merging.

      * merge pull requests
      * decline pull requests
      * create pull requests
      * comment on pull requests
      * approve pull requests

      ### email

      Ability to see the user's primary email address. This should make it easier to use Bitbucket Cloud as a login provider to add-ons or external applications.

      ### account

      Ability to see all the user's account information. Note that this does not include any ability to mutate any of the data.

      * see all email addresses
      * language
      * location
      * website
      * full name
      * SSH keys
      * user groups

      ### account:write

      Ability to change properties on the user's account.

      * delete the authorizing user's account
      * manage the user's groups
      * manupilate a user's email addresses
      * change username, display name and avatar

      ### team

      The ability to find out what teams the current user is part of. This is covered by the teams endpoint.

      * information about all the groups and teams I am a member or admin of


      ### team:write

      Implies `team`, but adds the ability to manage the teams that the authorizing user is an admin on.

      * manage team permissions

      ### webhook

      Gives access to webhooks. This scope is required for any webhook
      related operation.

      This scope gives read access to existing webhook subscriptions on all
      resources you can access, without needing further scopes. This means that
      a client can list all existing webhook subscriptions on repository
      `foo/bar` (assuming the principal user has access to this repo). The
      additional `repository` scope is not required for this.

      Likewise, existing webhook subscriptions for a repo's issue tracker can be
      retrieved without holding the `issue` scope. All that is required is the
      `webhook` scope.

      However, to create a webhook for `issue:created`, the client will need to
      have both the `webhook` as well as `issue` scope.

      * list webhook subscriptions on any accessible repository, user, team, or snippet
      * create/update/delete webhook subscriptions


      # App passwords <a name="app-pw"></a>

      App passwords allow two-step verification users to make API calls to their Bitbucket account through apps such as SourceTree.

      Some important points about app passwords:

      * You cannot view an app password or adjust permissions after you create the app password. Because app passwords are encrypted on our database and cannot be viewed by anyone. They are essentially designed to be disposable. If you need to change the scopes or lost the password just create a new one.
      * You cannot use them to log into your Bitbucket account.
      * You cannot use app passwords to manage team actions.

          App passwords are tied to an individual account's credentials and should not be shared. If you're sharing your app password you're essentially giving direct, authenticated, access to everything that password has been scoped to do with the Bitbucket API's.

      * You can use them for API call authentication, even if you don't have two-step verification enabled.
      * You can set permission scopes (specific access rights) for each app password.

      ### Create an app password

      To create an app password:

      1. Select **Avatar > Bitbucket settings**.
      2. Click **App passwords** in the Access management section.
      3. Click **Create app password**.
      4. Give the app password a name related to the application that will use the password.
      5. Select the specific access and permissions you want this application password to have.
      6. Copy the generated password and either record or paste it into the application you want to give access. The password is only displayed this one time.

      That's all there is to creating an app password. See your applications documentation for how to apply the app password for a specific application.

      ## Basic auth <a name="basic-auth"></a>

      Basic HTTP Authentication as per [RFC-2617](https://tools.ietf.org/html/rfc2617) (Digest not supported). Note that Basic Auth with username and password as credentials is only available on accounts that have 2-factor-auth / 2-step-verification disabled. If you use 2fa, you should authenticate using OAuth2 instead.
    description: How to authenticate API actions
    icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALIAAACyCAIAAABp6AI/AAAZPElEQVR4nO2deZAc1Z3nv7/3MrMy6+hLrdZBS0ISOpAsC0tcRoA9mEEiOOw1xjEGbzD2BDZjzy6O3QlmZxwbno3xrneHGceytndg7RnfNh7AmEOIEUZgzCGBZAnQLYGkVqvVp/qoqq6qzHzvt39kt2ggu+mqbh3Veh9VdLSkqurqzE++4/d+75fEzDAY3o040x/AcDZitDDEYLQwxGC0MMRgtDDEYLQwxGC0MMRgtDDEYLQwxGC0MMRgtDDEYLQwxGC0MMRgtDDEYLQwxGC0MMRgtDDEYLQwxGC0MMRgtDDEYLQwxGC0MMRgtDDEYLQwxGC0MMRgtDDEYLQwxGC0MMRgtDDEYLQwxGC0MMRgtDDEYLQwxGC0MMRgtDDEYLQwxGC0MMRgtDDEYFXwGjZFG88mCCCiyX3PsrW[...]'
    key: authentication
    title: Authentication methods
  - content: "\n# Filter and sort API objects\n\nYou can query the 2.0 API for specific objects using a simple language which resembles SQL.\n\n---\n**On this page**\n\n* [Supported endpoints](#supp-endpoints)\n* [Operators](#operators)\n* [Data types](#data-types)\n* [Querying](#querying)\n    * [Repositoriess](#query-repo)\n    * [Pull requests](#query-pullreq)\n    * [Issues](#query-issues)\n    * [Refs, tags, bookmarks](#query-ref)\n* [Sorting query results](#query-sort)\n\n----\n\n### Suppo[...]"
    description: Query the 2.0 API for specific objects
    icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAFm1JREFUeNrsnVtvW9eVgDclUtTVulmO48SSateTXjKwgRoFMg1gAQH6kBcnfZun2L+gmj8wVeYPVP0FVZ7yGOclDwO0IwMt+jAuYM+4k6aBU8lOXCuydbWuJMU56+jQ4dl7ncNDi6Qo8vvQA9aMbJGbXN9ea99OqlgsGgBoTzpoAgAEAAAIAAAQAAAgAABAAACAAAAAAQAAAgAABAAACAAAEAAAIAAAQAAAgAAAAAEAAAIAAAQAAAgAABAAACAAAEAAAIAAAAABAAACAAAEAAAIAAAQAAAgAABAAACAAAAAAQAAAgAABAAACAAAEAAAIAAABAAACAAAEAAAIAAAQAA[...]'
    key: filtering
    title: Filter and sort API objects
  - content: |

      # Pagination

      Endpoints that return collections of objects should always apply pagination.
      Paginated collections are always wrapped in the following wrapper object:

      ```json
      {
        "size": 5421,
        "page": 2,
        "pagelen: 10,
        "next": "https://api.bitbucket.org/2.0/repositories/pypy/pypy/commits?page=3",
        "previous": "https://api.bitbucket.org/2.0/repositories/pypy/pypy/commits?page=1",
        "values": [
          ...
        ]
      }
      ```

      Pagination is often page-bound, with a query parameter page indicating which
      page is to be returned.

      However, clients are not expected to construct URLs themselves by manipulating
      the page number query parameter. Instead, the response contains a link to the
      next page. This link should be treated as an opaque location that is not to be
      constructed by clients or even assumed to be predictable. The only contract
      around the next link is that it will return the next chunk of results.

      Lack of a next link in the response indicates the end of the collection.

      The paginated response contains the following fields:

      <table class='aui'>
          <thead>
              <tr>
                  <th>Field</th>
                  <th>Value</th>
              </tr>
          </thead>
          <tr>
              <td><code>size</code></td>
              <td>Total number of objects in the response. This is an optional element that is not provided in all responses, as it can be expensive to compute. </td>
          </tr>
          <tr>
              <td><code>page</code></td>
              <td>Page number of the current results. This is an optional element that is not provided in all responses.</td>
          </tr>
          <tr>
              <td><code>pagelen</code></td>
              <td>Current number of objects on the existing page. Globally, the minimum length is 10 and the maximum is 100. Some APIs may specify a different default.</td>
          </tr>
          <tr>
              <td><code>next</code></td>
              <td>Link to the next page if it exists. The last page of a collection does not have this value. Use this link to navigate the result set and refrain from constructing your own URLs.</td>
          </tr>
          <tr>
              <td><code>previous</code></td>
              <td>Link to previous page if it exists. A collections first page does not have this value. This is an optional element that is not provided in all responses. Some result sets strictly support forward navigation and never provide previous links. Clients must anticipate that backwards navigation is not always available.

              Use this link to navigate the result set and refrain from constructing your own URLs.</td>
          </tr>
          <tr>
              <td><code>values</code></td>
              <td>The list of objects. This contains at most <code>pagelen</code> objects.</td>
          </tr>
      </table>

      The link to the next page is included such that you don't have to hardcode or construct any links.  Only values and next are guaranteed (except the last page, which lacks next). This is because the previous and size values can be expensive for some data sets.

      It is important to realize that Bitbucket support both list-based pagination and iterator-based pagination. List-based pagination assumes that the collection is a discrete, immutable, consistently ordered, finite array of objects with a fixed size. Clients navigate a list-based collection by requesting offset-based chunks. In Bitbucket Cloud, list-based responses include the optional size, page, and previous element. The the next and previous links typically resemble something like /foo/ba[...]

      However, not all result sets can be treated as immutable and finite – much like how programming languages tend to distinguish between lists and arrays on one hand and iterators or stream on the other. Where an list-based pagination offers random access into any point in a collection, iterator-based pagination can only navigate forward one element at a time. In Bitbucket such iterator-based pagination contains the next link and pagelen elements, but not necessarily anything else. In these c[...]
    description: Learn more about pagination
    icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALIAAACyCAIAAABp6AI/AAAL+0lEQVR4nO3dfYxc1XnH8ec55947d972xWvjF3AwFKdgIgeKCxJpJPJSoGkitSEhbRK1SaO0f6NKbaNWlco/Uf5KQqIoitQoitpKuBCFtrRUJUCJ8wLBgS6248RxzNoxNiz2vs7Oyz3nefrH7C54fWZmN7vsvOT3kRFatEbn3vnOmTt35p7LqkoAlzLdHgD0ImQBAcgCApAFBCALCEAWEIAsIABZQACygABkAQHIAgKQBQQgCwhAFhCALCAAWUAAsoAAZAEByAICkAUEIAsIQBYQgCwgAFlAALKAAGQBAcgCApAFBCALCEAWEIAsIABZQACygABkAQHIAgKi1fySLv4D68Lc7RGsWocsRFVVrTHUP5vUs0SUmEw/1MFtVtpTVVUyhqv1rFrPNnNYgyeJolIhUVWlPiij5Ww[...]'
    key: pagination
    title: Pagination
  - content: |

      # Partial responses

      By default, each endpoint returns the full representation of a resource and in
      some cases that can be a lot of data. For example, retrieving a list of pull
      requests can amount to quite a large document.

      For better performance, you can ask the server to only return the fields you
      really need and to omit unwanted data. To request a partial response and to
      add or remove specific fields from a response, use the `fields` query
      parameter.


      ## Example

      Most API resources embed a substantial list of links pointing to related
      resources. This saves the client from constructing its own URLs, but is
      somewhat wasteful when the client doesn't need them.

      To significantly reduce the size of the response, use `?fields=-links`:

      ```
      $ curl https://api.bitbucket.org/2.0/users/evzijst?fields=-links
      {
        "username": "evzijst",
        "website": "",
        "display_name": "Erik van Zijst",
        "uuid": "{a288a0ab-e13b-43f0-a689-c4ef0a249875}",
        "created_on": "2010-07-07T05:16:36+00:00",
        "location": null,
        "type": "user"
      }
      ```

      ## Fields parameter syntax

      The `fields` parameter supports 3 modes of operation:

      1. Removal of select fields (e.g. `-links`)
      2. Pulling in additional fields not normally returned by an endpoint, while
         still getting all the default fields (e.g. `+reviewers`)
      3. Omitting all fields, except those specified (e.g. `owner.username`)

      The fields parameter can contain a list of multiple comma-separated field names
      (e.g. `fields=owner.username,uuid,links.self.href`). The parameter itself is
      not repeated.

      As discussed at [Condensed Versus Full Objects](serialization#representations),
      most objects that are embedded inside other objects (like how `owner` is an
      embedded `user` object in `repository`) appear in "condensed" form that omits
      many fields. The `fields` parameter allows us to pull in additional fields in
      such cases.

      For example, the embedded repository object in a pull request does not normally
      contain its `owner`. To add that in we can use:
      `+values.destination.repository.owner`.


      ## Wildcards

      The asterisk can be used to match all fields on a particular level. For
      example, removing all entries from the `links` element can be done like this:

      ```
      $ curl https://api.bitbucket.org/2.0/users/evzijst?fields=-links.*
      {
        "username": "evzijst",
        "website": "",
        "display_name": "Erik van Zijst",
        "uuid": "{a288a0ab-e13b-43f0-a689-c4ef0a249875}",
        "created_on": "2010-07-07T05:16:36+00:00",
        "location": null,
        "type": "user"
      }
      ```

      Wildcards can be used in combination with exclusion and inclusion. For
      instance, `-*,+foo,+bar` will remove all elements from the root level and then
      add in `foo` and `bar`.


      ## URL encoding

      Be aware that when using the `+foo.bar` syntax in the query string, that the
      "+" must be URL encoded as "%2B" and so the URL will be:

      ```
      https://api.bitbucket.org/2.0/repositories/evzijst/interruptingcow?fields=%2Bowner.created_on
      ```

      Without URL escaping, "+" is interpreted as an encoded space which will not
      match any fields.


      ## Field discovery

      While a resource's `self` URL, as well its "collection" URL typically return
      the full object with all its fields, there are some exceptions for fields that
      are overly verbose or costly to generate.

      For instance, a pull request contains the embedded lists of reviewers and
      participants. These fields are included from the `self` URL, but not from the
      `/pullrequests` collections resource, as it would impact performance too much.

      To discover any additional fields that might not be included by default,
      `fields=*` can be used.


      ## More examples

      If we want to get a list of all reviewer usernames on pull requests I created,
      we could combine a [filter](filtering) with a partial response. This will omit
      all other data from the response:

      ```
      /2.0/repositories/bitbucket/bitbucket/pullrequests?fields=values.id,values.reviewers.username,values.state&q=author.username%3D%22erik%22
      {
        "values": [
          {
            "reviewers": [
              {
                "username": "abhin"
              },
              {
                "username": "dtao"
              },
              {
                "username": "csomme"
              }
            ],
            "state": "OPEN",
            "id": 11355
          },
          {
            "reviewers": [
              {
                "username": "csomme"
              },
              {
                "username": "abhin"
              },
              {
                "username": "dstevens"
              }
            ],
            "state": "MERGED",
            "id": 11347
          },
          {
            "reviewers": [
              {
                "username": "csomme"
              },
              {
                "username": "jmooring"
              },
              {
                "username": "zdavis"
              },
              {
                "username": "flexbox"
              }
            ],
            "state": "OPEN",
            "id": 11344
          }
        ]
      }
      ```
    description: Tweak which fields are returned
    icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAACBJJREFUeNrs3V9onWcdwPE3SU2zdEtsbczaUskcTLYIgrO9dOndcF7YC+uVsqHMC291ghdd1ynInN5tiCgTRIZFLCJd71ynu0qmiNBuFLokZK2micO0zUk3zI7P7zSBbLazJzk5ed/zfD7wctqObTnP2+f7/j3v6arX6wWQp25DAAIACAAgAIAAAAIACAAgAIAAAAIACAAgAIAAAAIACAAgAIAAAAIACAAgAIAAAAIACAAgAIAAAAIACAAgAIAAAAIACAAgAIAAAAIACAAgAIAAgAAAAgAIACAAgAAAAgAIACAAgAAAAgAIACAAgAAAAgAIACAAgAAAAgAIACAAgAA[...]'
    key: partial-response
    title: Partial responses
  - content: |

      # Open API Specification and Object Representations

      ----

      *On this page*

      * [Open API Specification](#oai)
      * [JSON Schema](#jsonschema)
      * [Condensed Versus Full Objects](#representations)

      ____


      ## Open API Specification <a name="aoi"></a>

      Bitbucket uses the [Open API Specification](https://openapis.org) (OAI,
      formerly known as Swagger) to describe its APIs. Our OAI specification schema
      is hosted at [https://api.bitbucket.org/swagger.json](https://api.bitbucket.org/swagger.json)
      and serves as the canonical definition and comprehensive declaration of all
      available endpoints.

      The OAI specification makes writing client applications easier by:
      auto-generating boilerplate code (like data object classes) and dealing with
      authentication and error handling.

      You can find a comprehensive set of open tools for the OAI specification at:
      [https://github.com/swagger-api](https://github.com/swagger-api).


      ## JSON Schema <a name="jsonschema"></a>

      Bitbucket uses JSON Schema to describe the layout of every type of object
      consumed or produced by the API. These schemas are collected under the
      `#definitions` element of our swagger.json file.

      When an endpoint expects an object as part of a POST or PUT, it also expects
      the object to validate against the JSON schemas. The same applies to objects
      returned by an endpoint.


      ## Condensed Versus Full Objects <a name="representations"></a>

      Most objects in Bitbucket come both in "full" and "partial" representation.
      The full representation is when all elements are included. This is the layout
      returned by a resource's `self` location (e.g. `/2.0/repositories/foo/bar`),
      as well as resource collection endpoints (e.g. `/2.0/repositories`).

      However, Bitbucket objects often embed other objects. For example, a `repository`
      object embeds a `user` object for its owner. Likewise, a `pullrequest` object
      embeds its `repository` object.

      These related objects are embedded, or inlined, to reduce the "chatter" when
      clients make frequent followup API calls to collect information on common,
      related information.

      Embedded related objects are typically limited in their fields to avoid such
      object graphs from becoming too deep and noisy. They often exclude their own
      nested objects in an attempt to strike a balance between performance and
      utility.

      An object's embedded or condensed representation tends to be standardized,
      meaning the fields included is the same set, regardless of where the object
      was embedded.
    description: Learn more about object representations
    icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALIAAACyCAIAAABp6AI/AAA62ElEQVR4nO2dd3xdxbXv15rZ7TR1yZYsS5YluclyldwrtgFXcAHTOyGhhLSb93Jf7v285N2Sm0oSSgiBkAQCBhuDjXHDvXfJ3ZaLbFlWb0en7DYz748tKwZkY8lqgfP9CwRn19+eWbNmFRRCQIQIn4V09QVE6I5EZBGhBSKyiNACEVlEaIGILCK0QEQWEVogIosILRCRRYQWiMgiQgtEZBGhBSKyiNACEVlEaIGILCK0QEQWEVogIosILSB19QVEaAUCQAgBAhABETvuRJHR4p8GLoQQgiASggDAOO+4c2EkOqv7I4QQAARRCHGmpLoxZPRJiYuLcgsBAgTpgGEjIotujRCCC0GQIMKF8rrfv7d1+ZYjtf7QqEG9n5o/bv7koYjABYDghLTnwB+RRfeFCwEABLGuMfTmqr1[...]'
    key: serialization
    title: Schemas and Serialization
  - content: |

      # URI, UUID, and structures

      You should be familiar with REST architecture before writing an integration. Read this overview page to gain a good understanding of Bitbucket's REST implementation.

      ----
      **On this page**

      * [URI structure](#uri-structure)
      * [HTTP methods](#http-methods)
      * [UUID](#uuid)
          * [User object and UUID](#userobj)
          * [Repository object and UUID](#repo-obj)
          * [Team object and UUID](#teamobj)
      * [Standard error repsponses](#stand-error)
      * [Standard ISO-8601 timestamps](#timestamp)

      ----


      ## URI structure <a name="uri-structure"></a>

      All Bitbucket Cloud requests start with the `https://api.bitbucket.org/2.0` prefix (for the 2.0 API) and `https://api.bitbucket.org/1.0` prefix (1.0 API).

      The next segment of the URI path depends on the endpoint of the request. For example, using the curl command and the repositories endpoint you can list all the issues on Bitbucket's tutorial repository:

      ```
      curl https://api.bitbucket.org/2.0/repositories/tutorials/tutorials.bitbucket.org
      ```
      Given a specific endpoint, you can then drill down to a particular aspect or resource of that endpoint. The issues resource on a repository is an example:

      ```
      curl https://api.bitbucket.org/1.0/repositories/tutorials/tutorials.bitbucket.org/issues
      ```
      ### HTTP methods <a name="http-methods"></a>
      A given endpoint or resource has a series of actions (or methods) associated with it. The Bitbucket service supports these standard HTTP methods:

      <table class='aui'>
          <thead>
              <tr>
                  <th>Call</th>
                  <th>Description</th>
              </tr>
          </thead>
          <tr>
              <td>GET</td>
              <td>Retrieves information.  </td>
          </tr>
          <tr>
              <td>PUT</td>
              <td>Updates existing information.</td>
          </tr>
          <tr>
              <td>POST</td>
              <td>Creates new information.</td>
          </tr>
          <tr>
              <td>DELETE</td>
              <td>Removes existing information.</td>
          </tr>
      </table>

      For example, you can call use the POST action on the issues resource and create an issue on the issue tracker.

      **Specifying content length**

      You can get a `411 Length Required` response. If this happens, the API requires a Content-Length header but the client is not sending it. You should add the header yourself, for example using the curl client:

      ```
      curl -r PUT --header "Content-Length: 0" -u user:pass https://api.bitbucket.org/1.0/emails/rap@atlassian.com
      ```
      ## Universally Unique Identifier <a name="uuid"></a>

      UUID's provide a single point of recognition for users, teams, and repositories. The UUID is distinct from the username, team name, and repository name fields and remains the same even when those fields change. For example when a user changes their username or moves a repository you will need to modify calls which use those identifiers but not if you are pointing to the UUID.

      ### UUID examples and structure

      UUID's work with both the 1.0 and 2.0 APIs for the user, team, and repository objects. The following examples the following characters are replacements for curly brackets: `%7B` replaces `{`  and `%7D` replaces `}`. You will see this structure in the following example sections.

      ### User object and UUID <a name="userobj"></a>

      When you make a call using either the username or the UUID for that user the response is the same.

      **Call with username**:

      ```
      curl https://api.bitbucket.org/2.0/users/tutorials
      ```

      ***Call with UUID for the user**:

      ```
      curl https://api.bitbucket.org/2.0/users/%7Bc788b2da-b7a2-404c-9e26-d3f077557007%7D
      ```

      **Response**
      ```JSON
      {
          "username": "tutorials",
          "website": "https://tutorials.bitbucket.org/",
          "display_name": "tutorials account",
          "uuid": "{c788b2da-b7a2-404c-9e26-d3f077557007}",
          "created_on": "2011-12-20T16:34:07.132459+00:00",
          "location": "Santa Monica, CA",
          "type": "user"
      }
      ```

      ### Repository object and UUID <a name="repo-obj"></a>

      Once you have the UUID for a repository you no longer need a username or team name to make the API call so long as you use an empty field. This helps you resolve repositories no matter if the username or team name changes.

      **Call with team name (1team) and repository name (moxie)**:

      ```
      curl https://api.bitbucket.org/2.0/repositories/1team/moxie
      ```
      **Call with UUID and empty field**:

      ```
      curl https://api.bitbucket.org/2.0/repositories/%7B%7D/%7B21fa9bf8-b5b2-4891-97ed-d590bad0f871%7D
      ```

      **Call with UUID and teamname**:

      ```
      curl https://api.bitbucket.org/2.0/repositories/1team/%7B21fa9bf8-b5b2-4891-97ed-d590bad0f871%7D
      ```

      **Response**

      ```JSON
      {
          "created_on": "2013-11-08T01:11:03.222520+00:00",
          "description": "",
          "fork_policy": "allow_forks",
          "full_name": "1team/moxie",
          "has_issues": false,
          "has_wiki": false,
          "is_private": false,
          "language": "",
          "name": "moxie",
          "owner": {
              "display_name": "the team",
              "type": "team",
              "username": "1team",
              "uuid": "{aa559944-83c9-4963-a9a8-69ac8d9cf5d2}"
          },
          "project": {
              "key": "PROJ",
              "name": "Untitled project",
              "type": "project",
              "uuid": "{ab52aaeb-16ad-4fb0-bb1d-47e4f00367ff}"
          },
          "scm": "git",
          "size": 33348,
          "type": "repository",
          "updated_on": "2013-11-08T01:11:03.263237+00:00",
          "uuid": "{21fa9bf8-b5b2-4891-97ed-d590bad0f871}",
          "website": ""
      }
      ```

      ### Team object and UUID <a name="teamobj"></a>

      This example shows a call for a list of team members using both the team name and with the UUID for the team object. As the call is unauthenticated in the following example the response object will only show members with public profiles. The response is the same in either case.

      **Call with teamname**

      ```
      curl https://api.bitbucket.org/2.0/teams/1team/members
      ```
      **Call with UUID for team object**

      ```
      curl https://api.bitbucket.org/2.0/teams/%7Baa559944-83c9-4963-a9a8-69ac8d9cf5d2%7D/members
      ```

      **Response**

      ```JSON
      {
          "page": 1,
          "pagelen": 50,
          "size": 2,
          "values": [
              {
                  "created_on": "2011-12-20T16:34:07.132459+00:00",
                  "display_name": "tutorials account",
                  "location": null,
                  "type": "user",
                  "username": "tutorials",
                  "uuid": "{c788b2da-b7a2-404c-9e26-d3f077557007}",
                  "website": "https://tutorials.bitbucket.org/"
              },
              {
                  "created_on": "2013-12-10T14:44:13+00:00",
                  "display_name": "Dan Stevens [Atlassian]",
                  "location": null,
                  "type": "user",
                  "username": "dans9190",
                  "uuid": "{1cd06601-cd0e-4fce-be03-e9ac226978b7}",
                  "website": ""
              }
          ]
      }
      ```

      ## Standardized error responses <a name="stand-error"></a>

      The 2.0 API standardizes the error response layout. The 2.0 API serves a JSON
      object along with the appropriate HTTP status code. The JSON object provides a
      detailed  problem description.

      ```json
      {
          "error": {
              "message": "Bad request",
              "fields": {
                  "src": [
                      "This field is required."
                  ]
              },
              "detail": "You must specify a valid source branch when creating a pull request.",
              "id": "d23a1cc5178f7637f3d9bf2d13824258",
              "data": {
                "extra": "Optional, endpoint-specific data to further augment the error."
              }
          }
      }
      ```

      This object contains an error element which contains the following nested
      elements:

      <table class='aui'>
          <thead>
              <tr>
                  <th>Element</th>
                  <th>Description</th>
              </tr>
          </thead>
          <tr>
              <td>message</td>
              <td>A short description of the problem. This element is always present. Its value may be localized.</td>
          </tr>
          <tr>
              <td>fields</td>
              <td>This optional element is used in response to POST or PUT operations in which clients have provided invalid input. It contains a list of one or more client-provided fields that failed validation. The values may be localized.</td>
          </tr>
          <tr>
              <td>detail</td>
              <td>An optional detailed explanation of the failure. Its value may be localized.</td>
          </tr>
          <tr>
              <td>id</td>
              <td>An optional unique error identifier that identifies the error in Bitbucket's logging system. If you feel you hit a bug in an API and this field is provided, please mention it if you decide to contact support as it will greatly help us narrow down the problem.</td>
          </tr>
      </table>

      ## Standard ISO-8601 timestamps <a name="timestamp"></a>

      All 2.0 APIs use standardized ISO-8601 timestamps. In most cases, our APIs return UTC timestamps and for these, the timezone offset part will be 00:00. In rare cases where the original localized timestamp has significance, the timezone offset may identify the event's original timezone.
    description: 'URL''s, UUID''s, errors, and timestamps'
    icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALIAAACyCAIAAABp6AI/AAAMe0lEQVR4nO2dbYwdVRmA3/edMzP3Y/fux23ZbjfQ7YKxJW1qIgohgkpICCQVEzGpiYIi/Wf8hxEk+kOCiZHoD8IPMApGIxhSQ0LE8mEREhWQigWhNRC67VLYbvf74947d855/TG7tYTT7b0zd/fO3H2fbPbHfsycO+eZ95zzzjlnkJlBED4KtbsAQhoRLQQLooVgQbQQLIgWggXRQrAgWggWRAvBgmghWBAtBAuihWBBtBAsiBaCBdFCsCBaCBZEC8GCaCFYEC0EC6KFYEG0ECyIFoIF0UKwIFoIFkQLwYJoIVgQLQQLooVgQbQQLIgWggXRQrAgWggWRAvBgmghWFDJD2FkP52UQYgJj5BIC2MYsAWFEFqLYQYGovj1El8LY5gIK7X60ePjT7745geTs8ohCRztAhFCbQb[...]'
    key: uri-uuid
    title: 'URI, UUID, and structures'
  - content: |

      # Cors and hypermedia

      This section describes [Cross-origin resource sharing](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) (CORS), what content types we support in requests and responses, and hyperlinking resources in each json responses.


      ----
      **On this page**

      * [CORS](#cors)
      * [Supported content types](#supported-content)
      * [Resource links](#resource-links)

      ----

      ## Cors <a name="cors"></a>

      The Bitbucket API supports Cross-origin resource sharing to allow requests for restricted resources across domains. For more information you can refer to:

      * [Wikipedia article on CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing)
      * [W3C CORS recommendation](https://www.w3.org/TR/cors/)

      Sending a general request from the api to bitbucket.com:

      `curl -i https://api.bitbucket.org -H "origin: http://bitbucket.com"`

      Gives this result:

          HTTP/1.1 302 FOUND
          Server: nginx/1.6.2
          Vary: Cookie
          Cache-Control: max-age=900
          Content-Type: text/html; charset=utf-8
          Strict-Transport-Security: max-age=31536000
          Date: Tue, 21 Jun 2016 17:54:37 GMT
          Location: http://confluence.atlassian.com/x/IYBGDQ
          X-Served-By: app-110
          X-Static-Version: 2c820eb0d2b3
          ETag: "d41d8cd98f00b204e9800998ecf8427e"
          X-Content-Type-Options: nosniff
          X-Render-Time: 0.00379920005798
          Connection: Keep-Alive
          X-Version: 2c820eb0d2b3
          X-Frame-Options: SAMEORIGIN
          X-Request-Count: 383
          X-Cache-Info: cached
          Content-Length: 0

      Sending the same request with the CORS check -X OPTIONS in the call:

      `curl -i https://api.bitbucket.org -H "origin: http://bitbucket.com" -X OPTIONS`

      Gives this result:

          HTTP/1.1 302 FOUND
          Server: nginx/1.6.2
          Vary: Cookie
          Cache-Control: max-age=900
          Content-Type: text/html; charset=utf-8
          Access-Control-Expose-Headers: Accept-Ranges, Content-Encoding, Content-Length, Content-Type, ETag, Last-Modified
          Strict-Transport-Security: max-age=31536000
          Date: Tue, 21 Jun 2016 18:04:30 GMT
          Access-Control-Max-Age: 86400
          Location: http://confluence.atlassian.com/x/IYBGDQ
          X-Served-By: app-111
          Access-Control-Allow-Origin: *
          X-Static-Version: 2c820eb0d2b3
          ETag: "d41d8cd98f00b204e9800998ecf8427e"
          X-Content-Type-Options: nosniff
          X-Render-Time: 0.00371098518372
          Connection: keep-alive
          X-Version: 2c820eb0d2b3
          X-Frame-Options: SAMEORIGIN
          X-Request-Count: 357
          Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
          Access-Control-Allow-Headers: Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Origin, Range, X-CsrftokenX-Requested-With
          X-Cache-Info: not cacheable; request wasn't a GET or HEAD
          Content-Length: 0



      ## Supported content types <a name="supported-content"></a>

      The default and primary content type for 2.0 APIs is JSON. This applies both to responses from the server and to the request bodies provided by the client.

      Unless documented otherwise, whenever creating a new (POST) or modifying an existing (PUT) object, your client must provide the object's normal representation. Not every object element can be mutated. For example, a repository's created_on date is an auto-generated, immutable field. Your client can omit immutable fields from a request body.

      In some cases, a resource might also accept regular application/x-www-url-form-encoded POST and PUT bodies. Such bodies can be more convenient in scripts and command line usage. Requests bodies can contain contain nested elements or they can be flat (without nested elements). Clients can send flat request bodies as either as application/json or as application/x-www-url-form-encoded. Nested objects always require JSON.

      ## Resource links <a name="resource-links"></a>

      Every 2.0 object contains a links element that points to related resources or alternate representations. Use links to quickly discover and traverse to related objects. Links serve a "self-documenting" function for each endpoint. For example, the following request for a specific user:


      `$ curl https://api.bitbucket.org/2.0/users/tutorials`

      ```json
      {
          "username": "tutorials",
          "website": "https://tutorials.bitbucket.org/",
          "display_name": "tutorials account",
          "uuid": "{c788b2da-b7a2-404c-9e26-d3f077557007}",
          "created_on": "2011-12-20T16:34:07.132459+00:00",
          "location": "Santa Monica, CA",
          "type": "user"
      }
      ```
      Links can be actual REST API resources or they can be informational. In this example, informative resources include the user's avatar and the HTML URL for the user's Bitbucket account. Your client should avoid hardcoding an API's URL and instead use the URLs returned in API responses.

      A link's key is its `rel` (relationship) attribute and it contains a mandatory href element. For example, the following link:

      ```json
      "self": {
            "href": "https://api.bitbucket.org/api/2.0/users/tutorials"
      }
      ```

      The rel for this link is self and the href is https://api.bitbucket.org/api/2.0/users/tutorials. A single rel key can contain an list (array) of href objects. Your client should anticipate that any rel key can contain one or more href objects.

      Finally, links can also contain optional elements. Two common optional elements are the name element and the title element. They are often used to disambiguate links that share the same rel key. In the example below, the repository object that contains a clone link with two href objects. Each object contains the optional name element to clarify its use.

      ```json
      ```
      Links can support [URI Templates](https://tools.ietf.org/html/rfc6570); Those that do contain a `"templated": "true"` element.
    description: Learn about resources and linking
    icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALIAAACyCAIAAABp6AI/AAA1u0lEQVR4nO2dd3xd1ZXv1y6n3qIuWZZtybbcu42NC80YMOAQekhIHZIBZvLyMikz8yZvMuUzmZfJm0kmyTBJSDJ5gWRCCAkQArYhxphig3uTq2TLTVaXrm47be+93h9HupZBuGDZRuJ+P9efj3192znnd/Zee+1VCCJCnjynQy/3D8jzfiQvizwDkJdFngHIyyLPAORlkWcA8rLIMwB5WeQZgLws8gxAXhZ5BiAvizwDkJdFngHIyyLPAORlkWcA8rLIMwB5WeQZgLws8gxAXhZ5BiAvizwDkJdFngHIyyLPAORlkWcA8rLIMwB5WeQZgLws8gwAv9w/4OKCiFKhEEoqpRRKpRQiAFBCGKWUEkYp55RRQgi53D/2fcTwlAUieIHwgkBIJSQqpfquef9rj+EfSilnhDNqaJq[...]'
    key: cors-hypermedia
    title: Cors and hypermedia
  - content: |

      # Atlassian Connect for Bitbucket

      You can use the Atlassian Connect for Bitbucket Cloud to build add-ons which
      can connect with the Bitbucket UI and your own application set. An add-on could
      be an integration with another existing service, new features for the Atlassian
      application, or even a new product that runs within the Atlassian application.

      For complete information see:
      [Atlassian Connect for Bitbucket Cloud](https://developer.atlassian.com/bitbucket/index.html)
    description: Build Bitbucket add-ons with Connect
    icon: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALIAAACyCAIAAABp6AI/AAAabElEQVR4nO2deXBd13nYv++cu739PWwPAElsJEEQXLWLNLUvtkTFiewqW2PZladT223dZibjpnHH6bi1M01GHrXTTJJRvFaOKid16qW2RSlaKZESJXEDV5AESewggPeAt97lnK9/XBCCoEsCIAFQjz6/PyQNdO975937u9855zvLRSICheKDsGtdAMVHEaWFIgClhSIApYUiAKWFIgClhSIApYUiAKWFIgClhSIApYUiAKWFIgClhSIApYUiAKWFIgClhSIApYUiAKWFIgClhSIApYUiAKWFIgClhSIApYUiAKWFIgClhSIApYUiAKWFIgClhSIApYUiAKWFIgClhSIApYUiAKWFIgClhSIApYUiAKWFIgClhSIApYUiAKWFIgClhSIApYUiAKWFIgClhSIApYUiAG2exxE[...]'
    key: bb-connect
    title: Atlassian Connect
x-revision: 17556b40496a
