from .addprofilekey import *
from .createdomain import *
from .createprofile import *
from .deletedomain import *
from .deleteintegration import *
from .deleteprofile import *
from .deleteprofilekey import *
from .deleteprofileobject import *
from .deleteprofileobjecttype import *
from .getdomain import *
from .getintegration import *
from .getmatches import *
from .getprofileobjecttype import *
from .getprofileobjecttypetemplate import *
from .listaccountintegrations import *
from .listdomains import *
from .listintegrations import *
from .listprofileobjects import *
from .listprofileobjecttypes import *
from .listprofileobjecttypetemplates import *
from .listtagsforresource import *
from .mergeprofiles import *
from .putintegration import *
from .putprofileobject import *
from .putprofileobjecttype import *
from .searchprofiles import *
from .tagresource import *
from .untagresource import *
from .updatedomain import *
from .updateprofile import *
