from dataclasses import dataclass, field
from typing import Enum,Optional
from dataclasses_json import dataclass_json

class TransitionInEnum(str, Enum):
    FADE = "fade"
    FADE_SLOW = "fadeSlow"
    FADE_FAST = "fadeFast"
    REVEAL = "reveal"
    REVEAL_SLOW = "revealSlow"
    REVEAL_FAST = "revealFast"
    WIPE_LEFT = "wipeLeft"
    WIPE_LEFT_SLOW = "wipeLeftSlow"
    WIPE_LEFT_FAST = "wipeLeftFast"
    WIPE_RIGHT = "wipeRight"
    WIPE_RIGHT_SLOW = "wipeRightSlow"
    WIPE_RIGHT_FAST = "wipeRightFast"
    SLIDE_LEFT = "slideLeft"
    SLIDE_LEFT_SLOW = "slideLeftSlow"
    SLIDE_LEFT_FAST = "slideLeftFast"
    SLIDE_RIGHT = "slideRight"
    SLIDE_RIGHT_SLOW = "slideRightSlow"
    SLIDE_RIGHT_FAST = "slideRightFast"
    SLIDE_UP = "slideUp"
    SLIDE_UP_SLOW = "slideUpSlow"
    SLIDE_UP_FAST = "slideUpFast"
    SLIDE_DOWN = "slideDown"
    SLIDE_DOWN_SLOW = "slideDownSlow"
    SLIDE_DOWN_FAST = "slideDownFast"
    CAROUSEL_LEFT = "carouselLeft"
    CAROUSEL_LEFT_SLOW = "carouselLeftSlow"
    CAROUSEL_LEFT_FAST = "carouselLeftFast"
    CAROUSEL_RIGHT = "carouselRight"
    CAROUSEL_RIGHT_SLOW = "carouselRightSlow"
    CAROUSEL_RIGHT_FAST = "carouselRightFast"
    CAROUSEL_UP = "carouselUp"
    CAROUSEL_UP_SLOW = "carouselUpSlow"
    CAROUSEL_UP_FAST = "carouselUpFast"
    CAROUSEL_DOWN = "carouselDown"
    CAROUSEL_DOWN_SLOW = "carouselDownSlow"
    CAROUSEL_DOWN_FAST = "carouselDownFast"
    SHUFFLE_TOP_RIGHT = "shuffleTopRight"
    SHUFFLE_TOP_RIGHT_SLOW = "shuffleTopRightSlow"
    SHUFFLE_TOP_RIGHT_FAST = "shuffleTopRightFast"
    SHUFFLE_RIGHT_TOP = "shuffleRightTop"
    SHUFFLE_RIGHT_TOP_SLOW = "shuffleRightTopSlow"
    SHUFFLE_RIGHT_TOP_FAST = "shuffleRightTopFast"
    SHUFFLE_RIGHT_BOTTOM = "shuffleRightBottom"
    SHUFFLE_RIGHT_BOTTOM_SLOW = "shuffleRightBottomSlow"
    SHUFFLE_RIGHT_BOTTOM_FAST = "shuffleRightBottomFast"
    SHUFFLE_BOTTOM_RIGHT = "shuffleBottomRight"
    SHUFFLE_BOTTOM_RIGHT_SLOW = "shuffleBottomRightSlow"
    SHUFFLE_BOTTOM_RIGHT_FAST = "shuffleBottomRightFast"
    SHUFFLE_BOTTOM_LEFT = "shuffleBottomLeft"
    SHUFFLE_BOTTOM_LEFT_SLOW = "shuffleBottomLeftSlow"
    SHUFFLE_BOTTOM_LEFT_FAST = "shuffleBottomLeftFast"
    SHUFFLE_LEFT_BOTTOM = "shuffleLeftBottom"
    SHUFFLE_LEFT_BOTTOM_SLOW = "shuffleLeftBottomSlow"
    SHUFFLE_LEFT_BOTTOM_FAST = "shuffleLeftBottomFast"
    SHUFFLE_LEFT_TOP = "shuffleLeftTop"
    SHUFFLE_LEFT_TOP_SLOW = "shuffleLeftTopSlow"
    SHUFFLE_LEFT_TOP_FAST = "shuffleLeftTopFast"
    SHUFFLE_TOP_LEFT = "shuffleTopLeft"
    SHUFFLE_TOP_LEFT_SLOW = "shuffleTopLeftSlow"
    SHUFFLE_TOP_LEFT_FAST = "shuffleTopLeftFast"
    ZOOM = "zoom"

class TransitionOutEnum(str, Enum):
    FADE = "fade"
    FADE_SLOW = "fadeSlow"
    FADE_FAST = "fadeFast"
    REVEAL = "reveal"
    REVEAL_SLOW = "revealSlow"
    REVEAL_FAST = "revealFast"
    WIPE_LEFT = "wipeLeft"
    WIPE_LEFT_SLOW = "wipeLeftSlow"
    WIPE_LEFT_FAST = "wipeLeftFast"
    WIPE_RIGHT = "wipeRight"
    WIPE_RIGHT_SLOW = "wipeRightSlow"
    WIPE_RIGHT_FAST = "wipeRightFast"
    SLIDE_LEFT = "slideLeft"
    SLIDE_LEFT_SLOW = "slideLeftSlow"
    SLIDE_LEFT_FAST = "slideLeftFast"
    SLIDE_RIGHT = "slideRight"
    SLIDE_RIGHT_SLOW = "slideRightSlow"
    SLIDE_RIGHT_FAST = "slideRightFast"
    SLIDE_UP = "slideUp"
    SLIDE_UP_SLOW = "slideUpSlow"
    SLIDE_UP_FAST = "slideUpFast"
    SLIDE_DOWN = "slideDown"
    SLIDE_DOWN_SLOW = "slideDownSlow"
    SLIDE_DOWN_FAST = "slideDownFast"
    CAROUSEL_LEFT = "carouselLeft"
    CAROUSEL_LEFT_SLOW = "carouselLeftSlow"
    CAROUSEL_LEFT_FAST = "carouselLeftFast"
    CAROUSEL_RIGHT = "carouselRight"
    CAROUSEL_RIGHT_SLOW = "carouselRightSlow"
    CAROUSEL_RIGHT_FAST = "carouselRightFast"
    CAROUSEL_UP = "carouselUp"
    CAROUSEL_UP_SLOW = "carouselUpSlow"
    CAROUSEL_UP_FAST = "carouselUpFast"
    CAROUSEL_DOWN = "carouselDown"
    CAROUSEL_DOWN_SLOW = "carouselDownSlow"
    CAROUSEL_DOWN_FAST = "carouselDownFast"
    SHUFFLE_TOP_RIGHT = "shuffleTopRight"
    SHUFFLE_TOP_RIGHT_SLOW = "shuffleTopRightSlow"
    SHUFFLE_TOP_RIGHT_FAST = "shuffleTopRightFast"
    SHUFFLE_RIGHT_TOP = "shuffleRightTop"
    SHUFFLE_RIGHT_TOP_SLOW = "shuffleRightTopSlow"
    SHUFFLE_RIGHT_TOP_FAST = "shuffleRightTopFast"
    SHUFFLE_RIGHT_BOTTOM = "shuffleRightBottom"
    SHUFFLE_RIGHT_BOTTOM_SLOW = "shuffleRightBottomSlow"
    SHUFFLE_RIGHT_BOTTOM_FAST = "shuffleRightBottomFast"
    SHUFFLE_BOTTOM_RIGHT = "shuffleBottomRight"
    SHUFFLE_BOTTOM_RIGHT_SLOW = "shuffleBottomRightSlow"
    SHUFFLE_BOTTOM_RIGHT_FAST = "shuffleBottomRightFast"
    SHUFFLE_BOTTOM_LEFT = "shuffleBottomLeft"
    SHUFFLE_BOTTOM_LEFT_SLOW = "shuffleBottomLeftSlow"
    SHUFFLE_BOTTOM_LEFT_FAST = "shuffleBottomLeftFast"
    SHUFFLE_LEFT_BOTTOM = "shuffleLeftBottom"
    SHUFFLE_LEFT_BOTTOM_SLOW = "shuffleLeftBottomSlow"
    SHUFFLE_LEFT_BOTTOM_FAST = "shuffleLeftBottomFast"
    SHUFFLE_LEFT_TOP = "shuffleLeftTop"
    SHUFFLE_LEFT_TOP_SLOW = "shuffleLeftTopSlow"
    SHUFFLE_LEFT_TOP_FAST = "shuffleLeftTopFast"
    SHUFFLE_TOP_LEFT = "shuffleTopLeft"
    SHUFFLE_TOP_LEFT_SLOW = "shuffleTopLeftSlow"
    SHUFFLE_TOP_LEFT_FAST = "shuffleTopLeftFast"
    ZOOM = "zoom"


@dataclass_json
@dataclass
class Transition:
    in_: Optional[TransitionInEnum] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'in' }})
    out: Optional[TransitionOutEnum] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'out' }})
    
