from .read_dependencies_v1_en_core_web_sm_dependencies_post import *
from .read_entities_v1_en_core_web_sm_entities_post import *
from .read_root_v1_en_core_web_sm__get import *
from .read_sentence_dependencies_v1_en_core_web_sm_sentence_dependencies_post import *
from .read_version_v1_en_core_web_sm_version_get import *
