openapi: 3.0.0
servers:
  - url: https://api.slmonitor.com
info:
  title: SafetyLine
  version: "2.1"
  x-apisguru-categories:
    - enterprise
  x-logo:
    url: https://images.squarespace-cdn.com/content/v1/5da0d7a42ae7d60e27334f91/1599832509107-MH74LTAWZ4N33TPMZP6M/SafetyLine%2BLogo-min.png
  x-origin:
    - format: swagger
      url: https://api.slmonitor.com/swagger/v2.1/swagger.json
      version: "2.0"
  x-providerName: slmonitor.com
security:
  - EmailLogin: []
  - MicrosoftLogin: []
  - Pin: []
paths:
  "/api/v2.1/companies/{companyId}/me":
    get:
      description: This operation gets the authenticated user's profile.
      operationId: Api_GetUser
      security:
        - EmailLogin: []
        - MicrosoftLogin: []
        - Pin: []
      summary: Get the authenticated user
      tags:
        - Api
  "/api/v2.1/companies/{companyId}/users":
    get:
      description: This operation gets all the users' profiles.
      operationId: Api_GetUsers
      security:
        - EmailLogin:
            - CompanyAdministrator
            - CompanyMonitor
        - MicrosoftLogin:
            - CompanyAdministrator
            - CompanyMonitor
        - Pin: []
      summary: Get all the users
      tags:
        - Api
  "/api/v2.1/companies/{companyId}/users/{uniqueUserId}":
    get:
      description: This operation gets the specified user's profile.
      operationId: Api_GetUser2
      security:
        - EmailLogin:
            - CompanyAdministrator
            - CompanyMonitor
        - MicrosoftLogin:
            - CompanyAdministrator
            - CompanyMonitor
        - Pin: []
      summary: Get the user's profile
      tags:
        - Api
  "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/checkin":
    post:
      description: This operation checks the worker in for a default time or a custom time if the optional interval is provided.
      operationId: Api_CheckIn
      security:
        - EmailLogin:
            - CompanyMonitor
        - MicrosoftLogin:
            - CompanyMonitor
        - Pin: []
      summary: Check in
      tags:
        - Api
  "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/checkin-audio":
    post:
      description: This operation checks the worker in for a default time or a custom time if the optional interval is provided, and includes an audio attachment.
      operationId: Api_CheckInWithAudio
      security:
        - EmailLogin:
            - CompanyMonitor
        - MicrosoftLogin:
            - CompanyMonitor
        - Pin: []
      summary: Check in with an audio recording
      tags:
        - Api
  "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/checkin-text":
    post:
      description: This operation checks the worker in for a default time or a custom time if the optional interval is provided.
      operationId: Api_CheckInWithText
      security:
        - EmailLogin:
            - CompanyMonitor
        - MicrosoftLogin:
            - CompanyMonitor
        - Pin: []
      summary: Check in with a text report
      tags:
        - Api
  "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/emergency":
    post:
      description: This operation declares an emergency.
      operationId: Api_Emergency
      security:
        - EmailLogin:
            - CompanyMonitor
        - MicrosoftLogin:
            - CompanyMonitor
        - Pin: []
      summary: Declare an emergency
      tags:
        - Api
  "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/emergency-audio":
    post:
      description: This operation declares an emergency, and includes an audio attachment.
      operationId: Api_EmergencyWithAudio
      security:
        - EmailLogin:
            - CompanyMonitor
        - MicrosoftLogin:
            - CompanyMonitor
        - Pin: []
      summary: Declare an emergency with an audio recording
      tags:
        - Api
  "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/emergency-text":
    post:
      description: This operation declares an emergency.
      operationId: Api_EmergencyWithText
      security:
        - EmailLogin:
            - CompanyMonitor
        - MicrosoftLogin:
            - CompanyMonitor
        - Pin: []
      summary: Declare an emergency with a text report
      tags:
        - Api
  "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/end":
    post:
      description: This operation ends monitoring.
      operationId: Api_End
      security:
        - EmailLogin:
            - CompanyMonitor
        - MicrosoftLogin:
            - CompanyMonitor
        - Pin: []
      summary: End monitoring
      tags:
        - Api
  "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/end-audio":
    post:
      description: This operation ends monitoring, and includes an audio attachment.
      operationId: Api_EndWithAudio
      security:
        - EmailLogin:
            - CompanyMonitor
        - MicrosoftLogin:
            - CompanyMonitor
        - Pin: []
      summary: End monitoring with an audio recording
      tags:
        - Api
  "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/end-text":
    post:
      description: This operation ends monitoring.
      operationId: Api_EndWithText
      security:
        - EmailLogin:
            - CompanyMonitor
        - MicrosoftLogin:
            - CompanyMonitor
        - Pin: []
      summary: End monitoring with a text report
      tags:
        - Api
  "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/itinerary":
    put:
      description: This operation updates the worker's itinerary.
      operationId: Api_UpdateItinerary
      security:
        - EmailLogin:
            - CompanyMonitor
        - MicrosoftLogin:
            - CompanyMonitor
        - Pin: []
      summary: Update the itinerary
      tags:
        - Api
  "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/itinerary-file":
    put:
      description: This operation updates the worker's itinerary.
      operationId: Api_UpdateItineraryFile
      security:
        - EmailLogin:
            - CompanyMonitor
        - MicrosoftLogin:
            - CompanyMonitor
        - Pin: []
      summary: Update the itinerary file
      tags:
        - Api
  "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/location":
    post:
      description: This operation adds a location to the worker's event history.
      operationId: Api_ReportLocation
      security:
        - EmailLogin:
            - CompanyMonitor
        - MicrosoftLogin:
            - CompanyMonitor
        - Pin: []
      summary: Report a location
      tags:
        - Api
  "/api/v2.1/companies/{companyId}/users/{uniqueUserId}/text":
    post:
      description: The operation adds a text message to the worker's event history.
      operationId: Api_ReportText
      security:
        - EmailLogin:
            - CompanyMonitor
        - MicrosoftLogin:
            - CompanyMonitor
        - Pin: []
      summary: Send a text message
      tags:
        - Api
components:
  securitySchemes:
    EmailLogin:
      description: ""
      flows:
        implicit:
          authorizationUrl: https://prodsafetyline.b2clogin.com/prodsafetyline.onmicrosoft.com/B2C_1_si/oauth2/v2.0/authorize
          scopes:
            CompanyAdministrator: This scope can only be set within SafetyLine.
            CompanyMonitor: This scope can only be set within SafetyLine.
            https://prodsafetyline.onmicrosoft.com/e22f72d0-b056-4155-a2db-da02bc226023/access_as_user: Access the API as the signed-in user
      type: oauth2
    MicrosoftLogin:
      description: ""
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize
          scopes:
            CompanyAdministrator: This scope can only be set within SafetyLine.
            CompanyMonitor: This scope can only be set within SafetyLine.
            https://prodsafetyline.onmicrosoft.com/e22f72d0-b056-4155-a2db-da02bc226023/.default: Use the default scopes
      type: oauth2
    Pin:
      description: ""
      scheme: basic
      type: http
x-generator: NSwag v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))
