# coding: utf-8

"""
    Network Management API

    The Network Management API provides a collection of network performance monitoring and diagnostic capabilities.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.forwarding_rule_info import ForwardingRuleInfo

class TestForwardingRuleInfo(unittest.TestCase):
    """ForwardingRuleInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ForwardingRuleInfo:
        """Test ForwardingRuleInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ForwardingRuleInfo`
        """
        model = ForwardingRuleInfo()
        if include_optional:
            return ForwardingRuleInfo(
                display_name = '',
                matched_port_range = '',
                matched_protocol = '',
                network_uri = '',
                target = '',
                uri = '',
                vip = ''
            )
        else:
            return ForwardingRuleInfo(
        )
        """

    def testForwardingRuleInfo(self):
        """Test ForwardingRuleInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
