{
  "swagger": "2.0",
  "info": {
    "title": "Calendar API",
    "x-serviceName": "calendar",
    "description": "Lets you manipulate events and other calendar data.",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v3",
    "x-origin": {
      "format": "google",
      "version": "v1",
      "url": "https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest"
    }
  },
  "host": "www.googleapis.com",
  "basePath": "/calendar/v3",
  "schemes": [
    "https"
  ],
  "paths": {
    "/calendars/{calendarId}/acl/{ruleId}": {
      "delete": {
        "description": "Deletes an access control rule.",
        "operationId": "calendar.acl.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "acl"
        ]
      },
      "get": {
        "description": "Returns an access control rule.",
        "operationId": "calendar.acl.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar",
              "https://www.googleapis.com/auth/calendar.readonly"
            ]
          }
        ],
        "tags": [
          "acl"
        ]
      },
      "patch": {
        "description": "Updates an access control rule. This method supports patch semantics.",
        "operationId": "calendar.acl.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "acl"
        ]
      },
      "put": {
        "description": "Updates an access control rule.",
        "operationId": "calendar.acl.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "acl"
        ]
      }
    },
    "/calendars/{calendarId}/acl": {
      "post": {
        "description": "Creates an access control rule.",
        "operationId": "calendar.acl.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "acl"
        ]
      },
      "get": {
        "description": "Returns the rules in the access control list for the calendar.",
        "operationId": "calendar.acl.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "acl"
        ]
      }
    },
    "/calendars/{calendarId}/acl/watch": {
      "post": {
        "description": "Watch for changes to ACL resources.",
        "operationId": "calendar.acl.watch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "acl"
        ]
      }
    },
    "/users/me/calendarList/{calendarId}": {
      "delete": {
        "description": "Deletes an entry on the user's calendar list.",
        "operationId": "calendar.calendarList.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "calendarList"
        ]
      },
      "get": {
        "description": "Returns an entry on the user's calendar list.",
        "operationId": "calendar.calendarList.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar",
              "https://www.googleapis.com/auth/calendar.readonly"
            ]
          }
        ],
        "tags": [
          "calendarList"
        ]
      },
      "patch": {
        "description": "Updates an entry on the user's calendar list. This method supports patch semantics.",
        "operationId": "calendar.calendarList.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "calendarList"
        ]
      },
      "put": {
        "description": "Updates an entry on the user's calendar list.",
        "operationId": "calendar.calendarList.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "calendarList"
        ]
      }
    },
    "/users/me/calendarList": {
      "post": {
        "description": "Adds an entry to the user's calendar list.",
        "operationId": "calendar.calendarList.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "calendarList"
        ]
      },
      "get": {
        "description": "Returns entries on the user's calendar list.",
        "operationId": "calendar.calendarList.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar",
              "https://www.googleapis.com/auth/calendar.readonly"
            ]
          }
        ],
        "tags": [
          "calendarList"
        ]
      }
    },
    "/users/me/calendarList/watch": {
      "post": {
        "description": "Watch for changes to CalendarList resources.",
        "operationId": "calendar.calendarList.watch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar",
              "https://www.googleapis.com/auth/calendar.readonly"
            ]
          }
        ],
        "tags": [
          "calendarList"
        ]
      }
    },
    "/calendars/{calendarId}/clear": {
      "post": {
        "description": "Clears a primary calendar. This operation deletes all events associated with the primary calendar of an account.",
        "operationId": "calendar.calendars.clear",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "calendars"
        ]
      }
    },
    "/calendars/{calendarId}": {
      "delete": {
        "description": "Deletes a secondary calendar. Use calendars.clear for clearing all events on primary calendars.",
        "operationId": "calendar.calendars.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "calendars"
        ]
      },
      "get": {
        "description": "Returns metadata for a calendar.",
        "operationId": "calendar.calendars.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar",
              "https://www.googleapis.com/auth/calendar.readonly"
            ]
          }
        ],
        "tags": [
          "calendars"
        ]
      },
      "patch": {
        "description": "Updates metadata for a calendar. This method supports patch semantics.",
        "operationId": "calendar.calendars.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "calendars"
        ]
      },
      "put": {
        "description": "Updates metadata for a calendar.",
        "operationId": "calendar.calendars.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "calendars"
        ]
      }
    },
    "/calendars": {
      "post": {
        "description": "Creates a secondary calendar.",
        "operationId": "calendar.calendars.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "calendars"
        ]
      }
    },
    "/channels/stop": {
      "post": {
        "description": "Stop watching resources through this channel",
        "operationId": "calendar.channels.stop",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar",
              "https://www.googleapis.com/auth/calendar.readonly"
            ]
          }
        ],
        "tags": [
          "channels"
        ]
      }
    },
    "/colors": {
      "get": {
        "description": "Returns the color definitions for calendars and events.",
        "operationId": "calendar.colors.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar",
              "https://www.googleapis.com/auth/calendar.readonly"
            ]
          }
        ],
        "tags": [
          "colors"
        ]
      }
    },
    "/calendars/{calendarId}/events/{eventId}": {
      "delete": {
        "description": "Deletes an event.",
        "operationId": "calendar.events.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "events"
        ]
      },
      "get": {
        "description": "Returns an event.",
        "operationId": "calendar.events.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar",
              "https://www.googleapis.com/auth/calendar.readonly"
            ]
          }
        ],
        "tags": [
          "events"
        ]
      },
      "patch": {
        "description": "Updates an event. This method supports patch semantics.",
        "operationId": "calendar.events.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "events"
        ]
      },
      "put": {
        "description": "Updates an event.",
        "operationId": "calendar.events.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "events"
        ]
      }
    },
    "/calendars/{calendarId}/events/import": {
      "post": {
        "description": "Imports an event. This operation is used to add a private copy of an existing event to a calendar.",
        "operationId": "calendar.events.import",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "events"
        ]
      }
    },
    "/calendars/{calendarId}/events": {
      "post": {
        "description": "Creates an event.",
        "operationId": "calendar.events.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "events"
        ]
      },
      "get": {
        "description": "Returns events on the specified calendar.",
        "operationId": "calendar.events.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar",
              "https://www.googleapis.com/auth/calendar.readonly"
            ]
          }
        ],
        "tags": [
          "events"
        ]
      }
    },
    "/calendars/{calendarId}/events/{eventId}/instances": {
      "get": {
        "description": "Returns instances of the specified recurring event.",
        "operationId": "calendar.events.instances",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar",
              "https://www.googleapis.com/auth/calendar.readonly"
            ]
          }
        ],
        "tags": [
          "events"
        ]
      }
    },
    "/calendars/{calendarId}/events/{eventId}/move": {
      "post": {
        "description": "Moves an event to another calendar, i.e. changes an event's organizer.",
        "operationId": "calendar.events.move",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "events"
        ]
      }
    },
    "/calendars/{calendarId}/events/quickAdd": {
      "post": {
        "description": "Creates an event based on a simple text string.",
        "operationId": "calendar.events.quickAdd",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar"
            ]
          }
        ],
        "tags": [
          "events"
        ]
      }
    },
    "/calendars/{calendarId}/events/watch": {
      "post": {
        "description": "Watch for changes to Events resources.",
        "operationId": "calendar.events.watch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar",
              "https://www.googleapis.com/auth/calendar.readonly"
            ]
          }
        ],
        "tags": [
          "events"
        ]
      }
    },
    "/freeBusy": {
      "post": {
        "description": "Returns free/busy information for a set of calendars.",
        "operationId": "calendar.freebusy.query",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar",
              "https://www.googleapis.com/auth/calendar.readonly"
            ]
          }
        ],
        "tags": [
          "freebusy"
        ]
      }
    },
    "/users/me/settings/{setting}": {
      "get": {
        "description": "Returns a single user setting.",
        "operationId": "calendar.settings.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar",
              "https://www.googleapis.com/auth/calendar.readonly"
            ]
          }
        ],
        "tags": [
          "settings"
        ]
      }
    },
    "/users/me/settings": {
      "get": {
        "description": "Returns all user settings for the authenticated user.",
        "operationId": "calendar.settings.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar",
              "https://www.googleapis.com/auth/calendar.readonly"
            ]
          }
        ],
        "tags": [
          "settings"
        ]
      }
    },
    "/users/me/settings/watch": {
      "post": {
        "description": "Watch for changes to Settings resources.",
        "operationId": "calendar.settings.watch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/calendar",
              "https://www.googleapis.com/auth/calendar.readonly"
            ]
          }
        ],
        "tags": [
          "settings"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/calendar": "Manage your calendars",
        "https://www.googleapis.com/auth/calendar.readonly": "View your calendars"
      }
    }
  }
}