openapi: 3.0.0
servers:
  - url: https://cloudchannel.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: The Cloud Channel API enables Google Cloud partners to have a single unified resale platform and APIs across all of Google Cloud including GCP, Workspace, Maps and Chrome.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Cloud Channel API
  version: v1
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_upload.wikimedia.org_wikipedia_commons_e_e1_YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
    - format: openapi
      url: https://cloudchannel.googleapis.com/$discovery/rest?version=v1
      version: "3.0"
  x-providerName: googleapis.com
  x-serviceName: cloudchannel
tags:
  - name: accounts
  - name: operations
  - name: products
paths:
  /v1/products:
    get:
      description: "Lists the Products the reseller is authorized to sell. Possible error codes: * INVALID_ARGUMENT: Required request parameters are missing or invalid."
      operationId: cloudchannel.products.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - products
  "/v1/{account}:listSubscribers":
    get:
      description: "Lists service accounts with subscriber privileges on the Cloud Pub/Sub topic created for this Channel Services account. Possible error codes: * PERMISSION_DENIED: The reseller account making the request and the provided reseller account are different, or the impersonated user is not a super admin. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The topic resource doesn't exist. * INTERNAL: Any non-user error related to a technical issue in[...]"
      operationId: cloudchannel.accounts.listSubscribers
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{account}:register":
    post:
      description: "Registers a service account with subscriber privileges on the Cloud Pub/Sub topic for this Channel Services account. After you create a subscriber, you get the events through SubscriberEvent Possible error codes: * PERMISSION_DENIED: The reseller account making the request and the provided reseller account are different, or the impersonated user is not a super admin. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * INTERNAL: Any non-user error related[...]"
      operationId: cloudchannel.accounts.register
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{account}:unregister":
    post:
      description: "Unregisters a service account with subscriber privileges on the Cloud Pub/Sub topic created for this Channel Services account. If there are no service accounts left with subscriber privileges, this deletes the topic. You can call ListSubscribers to check for these accounts. Possible error codes: * PERMISSION_DENIED: The reseller account making the request and the provided reseller account are different, or the impersonated user is not a super admin. * INVALID_ARGUMENT: Requir[...]"
      operationId: cloudchannel.accounts.unregister
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{customer}:listPurchasableOffers":
    get:
      description: "Lists the following: * Offers that you can purchase for a customer. * Offers that you can change for an entitlement. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller * INVALID_ARGUMENT: Required request parameters are missing or invalid."
      operationId: cloudchannel.accounts.customers.listPurchasableOffers
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{customer}:listPurchasableSkus":
    get:
      description: "Lists the following: * SKUs that you can purchase for a customer * SKUs that you can upgrade or downgrade for an entitlement. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid."
      operationId: cloudchannel.accounts.customers.listPurchasableSkus
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{customer}:provisionCloudIdentity":
    post:
      description: "Creates a Cloud Identity for the given customer using the customer's information, or the information provided here. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The customer was not found. * ALREADY_EXISTS: The customer's primary email already exists. Retry after changing the customer's primary contact email. * INTERNAL: Any non-user error related to[...]"
      operationId: cloudchannel.accounts.customers.provisionCloudIdentity
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{entitlement}:lookupOffer":
    get:
      description: "Returns the requested Offer resource. Possible error codes: * PERMISSION_DENIED: The entitlement doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: Entitlement or offer was not found. Return value: The Offer resource."
      operationId: cloudchannel.accounts.customers.entitlements.lookupOffer
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{name}":
    delete:
      description: Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.
      operationId: cloudchannel.operations.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - operations
    get:
      description: Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.
      operationId: cloudchannel.operations.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - operations
    patch:
      description: "Updates a CustomerRepricingConfig. Call this method to set modifications for a specific customer's bill. This method overwrites the existing CustomerRepricingConfig. You can only update configs if the RepricingConfig.effective_invoice_month is a future month. To make changes to configs for the current month, use CreateCustomerRepricingConfig, taking note of its restrictions. You cannot update the RepricingConfig.effective_invoice_month. When updating a config in the future: *[...]"
      operationId: cloudchannel.accounts.customers.customerRepricingConfigs.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{name}:activate":
    post:
      description: "Activates a previously suspended entitlement. Entitlements suspended for pending ToS acceptance can't be activated using this method. An entitlement activation is a long-running operation and it updates the state of the customer entitlement. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: Entitlement[...]"
      operationId: cloudchannel.accounts.customers.entitlements.activate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{name}:cancel":
    post:
      description: Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an operat[...]
      operationId: cloudchannel.operations.cancel
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - operations
  "/v1/{name}:changeOffer":
    post:
      description: "Updates the Offer for an existing customer entitlement. An entitlement update is a long-running operation and it updates the entitlement as a result of fulfillment. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: Offer or Entitlement resource not found. * INTERNAL: Any non-user error related to a technical issue in the backend. Contact Cloud Channel sup[...]"
      operationId: cloudchannel.accounts.customers.entitlements.changeOffer
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{name}:changeParameters":
    post:
      description: "Change parameters of the entitlement. An entitlement update is a long-running operation and it updates the entitlement as a result of fulfillment. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. For example, the number of seats being changed is greater than the allowed number of max seats, or decreasing seats for a commitment based plan. * NOT_FOUND: Entitlement res[...]"
      operationId: cloudchannel.accounts.customers.entitlements.changeParameters
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{name}:changeRenewalSettings":
    post:
      description: "Updates the renewal settings for an existing customer entitlement. An entitlement update is a long-running operation and it updates the entitlement as a result of fulfillment. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: Entitlement resource not found. * NOT_COMMITMENT_PLAN: Renewal Settings are only applicable for a commitment plan. Can't enable or [...]"
      operationId: cloudchannel.accounts.customers.entitlements.changeRenewalSettings
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{name}:run":
    post:
      description: "Begins generation of data for a given report. The report identifier is a UID (for example, `613bf59q`). Possible error codes: * PERMISSION_DENIED: The user doesn't have access to this report. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The report identifier was not found. * INTERNAL: Any non-user error related to a technical issue in the backend. Contact Cloud Channel support. * UNKNOWN: Any non-user error related to a technical issue [...]"
      operationId: cloudchannel.accounts.reports.run
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.reports.usage.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/apps.reports.usage.readonly
      tags:
        - accounts
  "/v1/{name}:startPaidService":
    post:
      description: "Starts paid service for a trial entitlement. Starts paid service for a trial entitlement immediately. This method is only applicable if a plan is set up for a trial entitlement but has some trial days remaining. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: Entitlement resource not found. * FAILED_PRECONDITION/NOT_IN_TRIAL: This method only works for [...]"
      operationId: cloudchannel.accounts.customers.entitlements.startPaidService
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{name}:suspend":
    post:
      description: "Suspends a previously fulfilled entitlement. An entitlement suspension is a long-running operation. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: Entitlement resource not found. * NOT_ACTIVE: Entitlement is not active. * INTERNAL: Any non-user error related to a technical issue in the backend. Contact Cloud Channel support. * UNKNOWN: Any non-user err[...]"
      operationId: cloudchannel.accounts.customers.entitlements.suspend
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{parent}/channelPartnerLinks":
    get:
      description: "List ChannelPartnerLinks belonging to a distributor. You must be a distributor to call this method. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. Return value: The list of the distributor account's ChannelPartnerLink resources."
      operationId: cloudchannel.accounts.channelPartnerLinks.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
    post:
      description: "Initiates a channel partner link between a distributor and a reseller, or between resellers in an n-tier reseller channel. Invited partners need to follow the invite_link_uri provided in the response to accept. After accepting the invitation, a link is set up between the two parties. You must be a distributor to call this method. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVA[...]"
      operationId: cloudchannel.accounts.channelPartnerLinks.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{parent}/channelPartnerRepricingConfigs":
    get:
      description: "Lists information about how a Reseller modifies their bill before sending it to a ChannelPartner. Possible Error Codes: * PERMISSION_DENIED: If the account making the request and the account being queried are different. * NOT_FOUND: The ChannelPartnerRepricingConfig specified does not exist or is not associated with the given account. * INTERNAL: Any non-user error related to technical issues in the backend. In this case, contact Cloud Channel support. Return Value: If succes[...]"
      operationId: cloudchannel.accounts.channelPartnerLinks.channelPartnerRepricingConfigs.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
    post:
      description: "Creates a ChannelPartnerRepricingConfig. Call this method to set modifications for a specific ChannelPartner's bill. You can only create configs if the RepricingConfig.effective_invoice_month is a future month. If needed, you can create a config for the current month, with some restrictions. When creating a config for a future month, make sure there are no existing configs for that RepricingConfig.effective_invoice_month. The following restrictions are for creating configs in[...]"
      operationId: cloudchannel.accounts.channelPartnerLinks.channelPartnerRepricingConfigs.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{parent}/customerRepricingConfigs":
    get:
      description: "Lists information about how a Reseller modifies their bill before sending it to a Customer. Possible Error Codes: * PERMISSION_DENIED: If the account making the request and the account being queried are different. * NOT_FOUND: The CustomerRepricingConfig specified does not exist or is not associated with the given account. * INTERNAL: Any non-user error related to technical issues in the backend. In this case, contact Cloud Channel support. Return Value: If successful, the Cu[...]"
      operationId: cloudchannel.accounts.customers.customerRepricingConfigs.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
    post:
      description: "Creates a CustomerRepricingConfig. Call this method to set modifications for a specific customer's bill. You can only create configs if the RepricingConfig.effective_invoice_month is a future month. If needed, you can create a config for the current month, with some restrictions. When creating a config for a future month, make sure there are no existing configs for that RepricingConfig.effective_invoice_month. The following restrictions are for creating configs in the current[...]"
      operationId: cloudchannel.accounts.customers.customerRepricingConfigs.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{parent}/customers":
    get:
      description: "List Customers. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. Return value: List of Customers, or an empty list if there are no customers."
      operationId: cloudchannel.accounts.customers.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
    post:
      description: "Creates a new Customer resource under the reseller or distributor account. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: * Required request parameters are missing or invalid. * Domain field value doesn't match the primary email domain. Return value: The newly created Customer resource."
      operationId: cloudchannel.accounts.customers.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{parent}/customers:import":
    post:
      description: "Imports a Customer from the Cloud Identity associated with the provided Cloud Identity ID or domain before a TransferEntitlements call. If a linked Customer already exists and overwrite_if_exists is true, it will update that Customer's data. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * NOT_FOUND: Cloud Identity doesn't exist or was deleted. * INVALID_ARGUMENT: Required parameter[...]"
      operationId: cloudchannel.accounts.customers.import
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{parent}/entitlements":
    get:
      description: "Lists Entitlements belonging to a customer. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. Return value: A list of the customer's Entitlements."
      operationId: cloudchannel.accounts.customers.entitlements.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
    post:
      description: "Creates an entitlement for a customer. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: * Required request parameters are missing or invalid. * There is already a customer entitlement for a SKU from the same product family. * INVALID_VALUE: Make sure the OfferId is valid. If it is, contact Google Channel support for further troubleshooting. * NOT_FOUND: The customer or offer resource was not found. * ALREADY_EXISTS: *[...]"
      operationId: cloudchannel.accounts.customers.entitlements.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{parent}/offers":
    get:
      description: "Lists the Offers the reseller can sell. Possible error codes: * INVALID_ARGUMENT: Required request parameters are missing or invalid."
      operationId: cloudchannel.accounts.offers.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{parent}/reports":
    get:
      description: Lists the reports that RunReportJob can run. These reports include an ID, a description, and the list of columns that will be in the result.
      operationId: cloudchannel.accounts.reports.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.reports.usage.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/apps.reports.usage.readonly
      tags:
        - accounts
  "/v1/{parent}/skus":
    get:
      description: "Lists the SKUs for a product the reseller is authorized to sell. Possible error codes: * INVALID_ARGUMENT: Required request parameters are missing or invalid."
      operationId: cloudchannel.products.skus.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - products
  "/v1/{parent}:checkCloudIdentityAccountsExist":
    post:
      description: "Confirms the existence of Cloud Identity accounts based on the domain and if the Cloud Identity accounts are owned by the reseller. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * INVALID_VALUE: Invalid domain value in the request. Return value: A list of CloudIdentityCustomerAccount resources for the domain (m[...]"
      operationId: cloudchannel.accounts.checkCloudIdentityAccountsExist
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{parent}:listEntitlementChanges":
    get:
      description: "List entitlement history. Possible error codes: * PERMISSION_DENIED: The reseller account making the request and the provided reseller account are different. * INVALID_ARGUMENT: Missing or invalid required fields in the request. * NOT_FOUND: The parent resource doesn't exist. Usually the result of an invalid name parameter. * INTERNAL: Any non-user error related to a technical issue in the backend. In this case, contact CloudChannel support. * UNKNOWN: Any non-user error rela[...]"
      operationId: cloudchannel.accounts.customers.entitlements.listEntitlementChanges
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{parent}:listTransferableOffers":
    post:
      description: "List TransferableOffers of a customer based on Cloud Identity ID or Customer Name in the request. Use this method when a reseller gets the entitlement information of an unowned customer. The reseller should provide the customer's Cloud Identity ID or Customer Name. Possible error codes: * PERMISSION_DENIED: * The customer doesn't belong to the reseller and has no auth token. * The customer provided incorrect reseller information when generating auth token. * The reseller acco[...]"
      operationId: cloudchannel.accounts.listTransferableOffers
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{parent}:listTransferableSkus":
    post:
      description: "List TransferableSkus of a customer based on the Cloud Identity ID or Customer Name in the request. Use this method to list the entitlements information of an unowned customer. You should provide the customer's Cloud Identity ID or Customer Name. Possible error codes: * PERMISSION_DENIED: * The customer doesn't belong to the reseller and has no auth token. * The supplied auth token is invalid. * The reseller account making the request is different from the reseller account in[...]"
      operationId: cloudchannel.accounts.listTransferableSkus
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{parent}:transferEntitlements":
    post:
      description: "Transfers customer entitlements to new reseller. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The customer or offer resource was not found. * ALREADY_EXISTS: The SKU was already transferred for the customer. * CONDITION_NOT_MET or FAILED_PRECONDITION: * The SKU requires domain verification to transfer, but the domain is not verified. * An Add-On SKU [...]"
      operationId: cloudchannel.accounts.customers.transferEntitlements
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{parent}:transferEntitlementsToGoogle":
    post:
      description: "Transfers customer entitlements from their current reseller to Google. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The customer or offer resource was not found. * ALREADY_EXISTS: The SKU was already transferred for the customer. * CONDITION_NOT_MET or FAILED_PRECONDITION: * The SKU requires domain verification to transfer, but the domain is not veri[...]"
      operationId: cloudchannel.accounts.customers.transferEntitlementsToGoogle
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - accounts
  "/v1/{reportJob}:fetchReportResults":
    post:
      description: Retrieves data generated by CloudChannelReportsService.RunReportJob.
      operationId: cloudchannel.accounts.reportJobs.fetchReportResults
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.reports.usage.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/apps.reports.usage.readonly
      tags:
        - accounts
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/apps.order: Manage users on your domain
            https://www.googleapis.com/auth/apps.reports.usage.readonly: View usage reports for your G Suite domain
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/apps.order: Manage users on your domain
            https://www.googleapis.com/auth/apps.reports.usage.readonly: View usage reports for your G Suite domain
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
