# coding: utf-8

"""
    Azure Container Registry

    Metadata API definition for the Azure Container Registry runtime

    The version of the OpenAPI document: 2019-07-15-preview
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.acr_token_api import AcrTokenApi


class TestAcrTokenApi(unittest.TestCase):
    """AcrTokenApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AcrTokenApi()

    def tearDown(self) -> None:
        pass

    def test_get_acr_access_token(self) -> None:
        """Test case for get_acr_access_token

        """
        pass

    def test_get_acr_access_token_from_login(self) -> None:
        """Test case for get_acr_access_token_from_login

        """
        pass

    def test_get_acr_refresh_token_from_exchange(self) -> None:
        """Test case for get_acr_refresh_token_from_exchange

        """
        pass


if __name__ == '__main__':
    unittest.main()
