package shared




type VoiceIDEnum string

const (
    VoiceIDEnumAditi VoiceIDEnum = "Aditi"
VoiceIDEnumAmy VoiceIDEnum = "Amy"
VoiceIDEnumAstrid VoiceIDEnum = "Astrid"
VoiceIDEnumBianca VoiceIDEnum = "Bianca"
VoiceIDEnumBrian VoiceIDEnum = "Brian"
VoiceIDEnumCamila VoiceIDEnum = "Camila"
VoiceIDEnumCarla VoiceIDEnum = "Carla"
VoiceIDEnumCarmen VoiceIDEnum = "Carmen"
VoiceIDEnumCeline VoiceIDEnum = "Celine"
VoiceIDEnumChantal VoiceIDEnum = "Chantal"
VoiceIDEnumConchita VoiceIDEnum = "Conchita"
VoiceIDEnumCristiano VoiceIDEnum = "Cristiano"
VoiceIDEnumDora VoiceIDEnum = "Dora"
VoiceIDEnumEmma VoiceIDEnum = "Emma"
VoiceIDEnumEnrique VoiceIDEnum = "Enrique"
VoiceIDEnumEwa VoiceIDEnum = "Ewa"
VoiceIDEnumFiliz VoiceIDEnum = "Filiz"
VoiceIDEnumGabrielle VoiceIDEnum = "Gabrielle"
VoiceIDEnumGeraint VoiceIDEnum = "Geraint"
VoiceIDEnumGiorgio VoiceIDEnum = "Giorgio"
VoiceIDEnumGwyneth VoiceIDEnum = "Gwyneth"
VoiceIDEnumHans VoiceIDEnum = "Hans"
VoiceIDEnumInes VoiceIDEnum = "Ines"
VoiceIDEnumIvy VoiceIDEnum = "Ivy"
VoiceIDEnumJacek VoiceIDEnum = "Jacek"
VoiceIDEnumJan VoiceIDEnum = "Jan"
VoiceIDEnumJoanna VoiceIDEnum = "Joanna"
VoiceIDEnumJoey VoiceIDEnum = "Joey"
VoiceIDEnumJustin VoiceIDEnum = "Justin"
VoiceIDEnumKarl VoiceIDEnum = "Karl"
VoiceIDEnumKendra VoiceIDEnum = "Kendra"
VoiceIDEnumKevin VoiceIDEnum = "Kevin"
VoiceIDEnumKimberly VoiceIDEnum = "Kimberly"
VoiceIDEnumLea VoiceIDEnum = "Lea"
VoiceIDEnumLiv VoiceIDEnum = "Liv"
VoiceIDEnumLotte VoiceIDEnum = "Lotte"
VoiceIDEnumLucia VoiceIDEnum = "Lucia"
VoiceIDEnumLupe VoiceIDEnum = "Lupe"
VoiceIDEnumMads VoiceIDEnum = "Mads"
VoiceIDEnumMaja VoiceIDEnum = "Maja"
VoiceIDEnumMarlene VoiceIDEnum = "Marlene"
VoiceIDEnumMathieu VoiceIDEnum = "Mathieu"
VoiceIDEnumMatthew VoiceIDEnum = "Matthew"
VoiceIDEnumMaxim VoiceIDEnum = "Maxim"
VoiceIDEnumMia VoiceIDEnum = "Mia"
VoiceIDEnumMiguel VoiceIDEnum = "Miguel"
VoiceIDEnumMizuki VoiceIDEnum = "Mizuki"
VoiceIDEnumNaja VoiceIDEnum = "Naja"
VoiceIDEnumNicole VoiceIDEnum = "Nicole"
VoiceIDEnumOlivia VoiceIDEnum = "Olivia"
VoiceIDEnumPenelope VoiceIDEnum = "Penelope"
VoiceIDEnumRaveena VoiceIDEnum = "Raveena"
VoiceIDEnumRicardo VoiceIDEnum = "Ricardo"
VoiceIDEnumRuben VoiceIDEnum = "Ruben"
VoiceIDEnumRussell VoiceIDEnum = "Russell"
VoiceIDEnumSalli VoiceIDEnum = "Salli"
VoiceIDEnumSeoyeon VoiceIDEnum = "Seoyeon"
VoiceIDEnumTakumi VoiceIDEnum = "Takumi"
VoiceIDEnumTatyana VoiceIDEnum = "Tatyana"
VoiceIDEnumVicki VoiceIDEnum = "Vicki"
VoiceIDEnumVitoria VoiceIDEnum = "Vitoria"
VoiceIDEnumZeina VoiceIDEnum = "Zeina"
VoiceIDEnumZhiyu VoiceIDEnum = "Zhiyu"
VoiceIDEnumAria VoiceIDEnum = "Aria"
VoiceIDEnumAyanda VoiceIDEnum = "Ayanda"
)


