swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /youtube/analytics/v1
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Retrieves your YouTube Analytics data.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: YouTube Analytics
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-apisguru-categories:
    - analytics
  x-logo:
    url: 'https://pbs.twimg.com/profile_images/902547949103841281/TmdokZcM_400x400.jpg'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/youtubeAnalytics/v1/rest'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: youtubeAnalytics
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/youtube': Manage your YouTube account
      'https://www.googleapis.com/auth/youtube.readonly': View your YouTube account
      'https://www.googleapis.com/auth/youtubepartner': View and manage your assets and associated content on YouTube
      'https://www.googleapis.com/auth/yt-analytics-monetary.readonly': View monetary and non-monetary YouTube Analytics reports for your YouTube content
      'https://www.googleapis.com/auth/yt-analytics.readonly': View YouTube Analytics reports for your YouTube content
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/youtube': Manage your YouTube account
      'https://www.googleapis.com/auth/youtube.readonly': View your YouTube account
      'https://www.googleapis.com/auth/youtubepartner': View and manage your assets and associated content on YouTube
      'https://www.googleapis.com/auth/yt-analytics-monetary.readonly': View monetary and non-monetary YouTube Analytics reports for your YouTube content
      'https://www.googleapis.com/auth/yt-analytics.readonly': View YouTube Analytics reports for your YouTube content
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: groupItems
  - name: groups
  - name: reports
paths:
  /groupItems:
    delete:
      description: Removes an item from a group.
      operationId: youtubeAnalytics.groupItems.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - groupItems
    get:
      description: Returns a collection of group items that match the API request parameters.
      operationId: youtubeAnalytics.groupItems.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
      tags:
        - groupItems
    post:
      description: Creates a group item.
      operationId: youtubeAnalytics.groupItems.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - groupItems
  /groups:
    delete:
      description: Deletes a group.
      operationId: youtubeAnalytics.groups.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - groups
    get:
      description: 'Returns a collection of groups that match the API request parameters. For example, you can retrieve all groups that the authenticated user owns, or you can retrieve one or more groups by their unique IDs.'
      operationId: youtubeAnalytics.groups.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
      tags:
        - groups
    post:
      description: Creates a group.
      operationId: youtubeAnalytics.groups.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - groups
    put:
      description: 'Modifies a group. For example, you could change a group''s title.'
      operationId: youtubeAnalytics.groups.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - groups
  /reports:
    get:
      description: Retrieve your YouTube Analytics reports.
      operationId: youtubeAnalytics.reports.query
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
      tags:
        - reports