openapi: 3.0.0
servers:
  - url: https://fitness.googleapis.com/fitness/v1/users
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: The Fitness API for managing users' fitness tracking data.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Fitness API
  version: v1
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png
  x-origin:
    - format: google
      url: https://fitness.googleapis.com/$discovery/rest?version=v1
      version: v1
  x-providerName: googleapis.com
  x-serviceName: fitness
tags:
  - name: users
paths:
  "/{userId}/dataSources":
    get:
      description: Lists all data sources that are visible to the developer, using the OAuth scopes provided. The list is not exhaustive; the user may have private data sources that are only visible to other developers, or calls using other scopes.
      operationId: fitness.users.dataSources.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.activity.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.activity.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.activity.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.activity.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_glucose.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_glucose.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_pressure.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_pressure.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body_temperature.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body_temperature.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.heart_rate.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.heart_rate.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.location.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.location.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.location.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.location.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.nutrition.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.nutrition.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.nutrition.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.nutrition.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.reproductive_health.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.reproductive_health.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.sleep.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.sleep.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.sleep.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.sleep.write
      tags:
        - users
    post:
      description: Creates a new data source that is unique across all data sources belonging to this user. A data source is a unique source of sensor data. Data sources can expose raw data coming from hardware sensors on local or companion devices. They can also expose derived data, created by transforming or merging other data sources. Multiple data sources can exist for the same data type. Every data point in every dataset inserted into or read from the Fitness API has an associated data sour[...]
      operationId: fitness.users.dataSources.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.activity.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.activity.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.location.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.location.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.nutrition.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.nutrition.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.sleep.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.sleep.write
      tags:
        - users
  "/{userId}/dataSources/{dataSourceId}":
    delete:
      description: Deletes the specified data source. The request will fail if the data source contains any data points.
      operationId: fitness.users.dataSources.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.activity.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.activity.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.location.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.location.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.nutrition.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.nutrition.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.sleep.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.sleep.write
      tags:
        - users
    get:
      description: Returns the specified data source.
      operationId: fitness.users.dataSources.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.activity.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.activity.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.activity.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.activity.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_glucose.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_glucose.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_pressure.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_pressure.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body_temperature.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body_temperature.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.heart_rate.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.heart_rate.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.location.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.location.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.location.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.location.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.nutrition.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.nutrition.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.nutrition.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.nutrition.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.reproductive_health.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.reproductive_health.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.sleep.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.sleep.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.sleep.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.sleep.write
      tags:
        - users
    put:
      description: Updates the specified data source. The dataStreamId, dataType, type, dataStreamName, and device properties with the exception of version, cannot be modified. Data sources are identified by their dataStreamId.
      operationId: fitness.users.dataSources.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.activity.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.activity.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.location.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.location.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.nutrition.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.nutrition.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.sleep.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.sleep.write
      tags:
        - users
  "/{userId}/dataSources/{dataSourceId}/dataPointChanges":
    get:
      description: Queries for user's data point changes for a particular data source.
      operationId: fitness.users.dataSources.dataPointChanges.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.activity.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.activity.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.activity.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.activity.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_glucose.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_glucose.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_pressure.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_pressure.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body_temperature.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body_temperature.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.heart_rate.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.heart_rate.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.location.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.location.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.location.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.location.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.nutrition.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.nutrition.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.nutrition.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.nutrition.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.reproductive_health.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.reproductive_health.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.sleep.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.sleep.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.sleep.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.sleep.write
      tags:
        - users
  "/{userId}/dataSources/{dataSourceId}/datasets/{datasetId}":
    delete:
      description: Performs an inclusive delete of all data points whose start and end times have any overlap with the time range specified by the dataset ID. For most data types, the entire data point will be deleted. For data types where the time span represents a consistent value (such as com.google.activity.segment), and a data point straddles either end point of the dataset, only the overlapping portion of the data point will be deleted.
      operationId: fitness.users.dataSources.datasets.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.activity.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.activity.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.location.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.location.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.nutrition.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.nutrition.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.sleep.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.sleep.write
      tags:
        - users
    get:
      description: Returns a dataset containing all data points whose start and end times overlap with the specified range of the dataset minimum start time and maximum end time. Specifically, any data point whose start time is less than or equal to the dataset end time and whose end time is greater than or equal to the dataset start time.
      operationId: fitness.users.dataSources.datasets.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.activity.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.activity.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.activity.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.activity.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_glucose.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_glucose.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_pressure.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_pressure.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body_temperature.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body_temperature.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.heart_rate.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.heart_rate.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.location.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.location.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.location.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.location.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.nutrition.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.nutrition.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.nutrition.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.nutrition.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.reproductive_health.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.reproductive_health.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.sleep.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.sleep.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.sleep.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.sleep.write
      tags:
        - users
    patch:
      description: "Adds data points to a dataset. The dataset need not be previously created. All points within the given dataset will be returned with subsquent calls to retrieve this dataset. Data points can belong to more than one dataset. This method does not use patch semantics: the data points provided are merely inserted, with no existing data replaced."
      operationId: fitness.users.dataSources.datasets.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.activity.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.activity.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.location.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.location.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.nutrition.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.nutrition.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.sleep.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.sleep.write
      tags:
        - users
  "/{userId}/dataset:aggregate":
    post:
      description: Aggregates data of a certain type or stream into buckets divided by a given type of boundary. Multiple data sets of multiple types and from multiple sources can be aggregated into exactly one bucket type per request.
      operationId: fitness.users.dataset.aggregate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.activity.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.activity.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.activity.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.activity.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_glucose.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_glucose.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_pressure.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_pressure.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body_temperature.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body_temperature.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.heart_rate.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.heart_rate.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.location.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.location.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.location.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.location.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.nutrition.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.nutrition.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.nutrition.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.nutrition.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.reproductive_health.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.reproductive_health.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.sleep.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.sleep.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.sleep.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.sleep.write
      tags:
        - users
  "/{userId}/sessions":
    get:
      description: Lists sessions previously created.
      operationId: fitness.users.sessions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.activity.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.activity.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.activity.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.activity.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_glucose.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_glucose.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_glucose.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_pressure.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_pressure.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.blood_pressure.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body_temperature.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body_temperature.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.body_temperature.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.heart_rate.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.heart_rate.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.heart_rate.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.location.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.location.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.location.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.location.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.nutrition.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.nutrition.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.nutrition.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.nutrition.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.oxygen_saturation.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.reproductive_health.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.reproductive_health.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.reproductive_health.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.sleep.read
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.sleep.read
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.sleep.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.sleep.write
      tags:
        - users
  "/{userId}/sessions/{sessionId}":
    delete:
      description: Deletes a session specified by the given session ID.
      operationId: fitness.users.sessions.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.activity.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.activity.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.sleep.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.sleep.write
      tags:
        - users
    put:
      description: Updates or insert a given session.
      operationId: fitness.users.sessions.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.activity.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.activity.write
        - Oauth2:
            - https://www.googleapis.com/auth/fitness.sleep.write
          Oauth2c:
            - https://www.googleapis.com/auth/fitness.sleep.write
      tags:
        - users
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/fitness.activity.read: Use Google Fit to see and store your physical activity data
            https://www.googleapis.com/auth/fitness.activity.write: Add to your Google Fit physical activity data
            https://www.googleapis.com/auth/fitness.blood_glucose.read: See info about your blood glucose in Google Fit. I consent to Google sharing my blood glucose information with this app.
            https://www.googleapis.com/auth/fitness.blood_glucose.write: Add info about your blood glucose to Google Fit. I consent to Google using my blood glucose information with this app.
            https://www.googleapis.com/auth/fitness.blood_pressure.read: See info about your blood pressure in Google Fit. I consent to Google sharing my blood pressure information with this app.
            https://www.googleapis.com/auth/fitness.blood_pressure.write: Add info about your blood pressure in Google Fit. I consent to Google using my blood pressure information with this app.
            https://www.googleapis.com/auth/fitness.body.read: See info about your body measurements in Google Fit
            https://www.googleapis.com/auth/fitness.body.write: Add info about your body measurements to Google Fit
            https://www.googleapis.com/auth/fitness.body_temperature.read: See info about your body temperature in Google Fit. I consent to Google sharing my body temperature information with this app.
            https://www.googleapis.com/auth/fitness.body_temperature.write: Add to info about your body temperature in Google Fit. I consent to Google using my body temperature information with this app.
            https://www.googleapis.com/auth/fitness.heart_rate.read: See your heart rate data in Google Fit. I consent to Google sharing my heart rate information with this app.
            https://www.googleapis.com/auth/fitness.heart_rate.write: Add to your heart rate data in Google Fit. I consent to Google using my heart rate information with this app.
            https://www.googleapis.com/auth/fitness.location.read: See your Google Fit speed and distance data
            https://www.googleapis.com/auth/fitness.location.write: Add to your Google Fit location data
            https://www.googleapis.com/auth/fitness.nutrition.read: See info about your nutrition in Google Fit
            https://www.googleapis.com/auth/fitness.nutrition.write: Add to info about your nutrition in Google Fit
            https://www.googleapis.com/auth/fitness.oxygen_saturation.read: See info about your oxygen saturation in Google Fit. I consent to Google sharing my oxygen saturation information with this app.
            https://www.googleapis.com/auth/fitness.oxygen_saturation.write: Add info about your oxygen saturation in Google Fit. I consent to Google using my oxygen saturation information with this app.
            https://www.googleapis.com/auth/fitness.reproductive_health.read: See info about your reproductive health in Google Fit. I consent to Google sharing my reproductive health information with this app.
            https://www.googleapis.com/auth/fitness.reproductive_health.write: Add info about your reproductive health in Google Fit. I consent to Google using my reproductive health information with this app.
            https://www.googleapis.com/auth/fitness.sleep.read: See your sleep data in Google Fit. I consent to Google sharing my sleep information with this app.
            https://www.googleapis.com/auth/fitness.sleep.write: Add to your sleep data in Google Fit. I consent to Google using my sleep information with this app.
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/fitness.activity.read: Use Google Fit to see and store your physical activity data
            https://www.googleapis.com/auth/fitness.activity.write: Add to your Google Fit physical activity data
            https://www.googleapis.com/auth/fitness.blood_glucose.read: See info about your blood glucose in Google Fit. I consent to Google sharing my blood glucose information with this app.
            https://www.googleapis.com/auth/fitness.blood_glucose.write: Add info about your blood glucose to Google Fit. I consent to Google using my blood glucose information with this app.
            https://www.googleapis.com/auth/fitness.blood_pressure.read: See info about your blood pressure in Google Fit. I consent to Google sharing my blood pressure information with this app.
            https://www.googleapis.com/auth/fitness.blood_pressure.write: Add info about your blood pressure in Google Fit. I consent to Google using my blood pressure information with this app.
            https://www.googleapis.com/auth/fitness.body.read: See info about your body measurements in Google Fit
            https://www.googleapis.com/auth/fitness.body.write: Add info about your body measurements to Google Fit
            https://www.googleapis.com/auth/fitness.body_temperature.read: See info about your body temperature in Google Fit. I consent to Google sharing my body temperature information with this app.
            https://www.googleapis.com/auth/fitness.body_temperature.write: Add to info about your body temperature in Google Fit. I consent to Google using my body temperature information with this app.
            https://www.googleapis.com/auth/fitness.heart_rate.read: See your heart rate data in Google Fit. I consent to Google sharing my heart rate information with this app.
            https://www.googleapis.com/auth/fitness.heart_rate.write: Add to your heart rate data in Google Fit. I consent to Google using my heart rate information with this app.
            https://www.googleapis.com/auth/fitness.location.read: See your Google Fit speed and distance data
            https://www.googleapis.com/auth/fitness.location.write: Add to your Google Fit location data
            https://www.googleapis.com/auth/fitness.nutrition.read: See info about your nutrition in Google Fit
            https://www.googleapis.com/auth/fitness.nutrition.write: Add to info about your nutrition in Google Fit
            https://www.googleapis.com/auth/fitness.oxygen_saturation.read: See info about your oxygen saturation in Google Fit. I consent to Google sharing my oxygen saturation information with this app.
            https://www.googleapis.com/auth/fitness.oxygen_saturation.write: Add info about your oxygen saturation in Google Fit. I consent to Google using my oxygen saturation information with this app.
            https://www.googleapis.com/auth/fitness.reproductive_health.read: See info about your reproductive health in Google Fit. I consent to Google sharing my reproductive health information with this app.
            https://www.googleapis.com/auth/fitness.reproductive_health.write: Add info about your reproductive health in Google Fit. I consent to Google using my reproductive health information with this app.
            https://www.googleapis.com/auth/fitness.sleep.read: See your sleep data in Google Fit. I consent to Google sharing my sleep information with this app.
            https://www.googleapis.com/auth/fitness.sleep.write: Add to your sleep data in Google Fit. I consent to Google using my sleep information with this app.
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
