openapi: 3.0.0
servers:
  - url: https://keep.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: The Google Keep API is used in an enterprise environment to manage Google Keep content and resolve issues identified by cloud security software.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Google Keep API
  version: v1
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_upload.wikimedia.org_wikipedia_commons_e_e1_YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
    - format: google
      url: https://keep.googleapis.com/$discovery/rest?version=v1
      version: v1
  x-providerName: googleapis.com
  x-serviceName: keep
tags:
  - name: media
  - name: notes
paths:
  /v1/notes:
    get:
      description: Lists notes. Every list call returns a page of results with `page_size` as the upper bound of returned items. A `page_size` of zero allows the server to choose the upper bound. The ListNotesResponse contains at most `page_size` entries. If there are more things left to list, it provides a `next_page_token` value. (Page tokens are opaque values.) To get the next page of results, copy the result's `next_page_token` into the next request's `page_token`. Repeat until the `next_pag[...]
      operationId: keep.notes.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/keep
          Oauth2c:
            - https://www.googleapis.com/auth/keep
        - Oauth2:
            - https://www.googleapis.com/auth/keep.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/keep.readonly
      tags:
        - notes
    post:
      description: Creates a new note.
      operationId: keep.notes.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/keep
          Oauth2c:
            - https://www.googleapis.com/auth/keep
      tags:
        - notes
  "/v1/{name}":
    delete:
      description: Deletes a note. Caller must have the `OWNER` role on the note to delete. Deleting a note removes the resource immediately and cannot be undone. Any collaborators will lose access to the note.
      operationId: keep.notes.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/keep
          Oauth2c:
            - https://www.googleapis.com/auth/keep
      tags:
        - notes
    get:
      description: Gets a note.
      operationId: keep.notes.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/keep
          Oauth2c:
            - https://www.googleapis.com/auth/keep
        - Oauth2:
            - https://www.googleapis.com/auth/keep.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/keep.readonly
      tags:
        - notes
  "/v1/{parent}/permissions:batchCreate":
    post:
      description: Creates one or more permissions on the note. Only permissions with the `WRITER` role may be created. If adding any permission fails, then the entire request fails and no changes are made.
      operationId: keep.notes.permissions.batchCreate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/keep
          Oauth2c:
            - https://www.googleapis.com/auth/keep
      tags:
        - notes
  "/v1/{parent}/permissions:batchDelete":
    post:
      description: Deletes one or more permissions on the note. The specified entities will immediately lose access. A permission with the `OWNER` role can't be removed. If removing a permission fails, then the entire request fails and no changes are made. Returns a 400 bad request error if a specified permission does not exist on the note.
      operationId: keep.notes.permissions.batchDelete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/keep
          Oauth2c:
            - https://www.googleapis.com/auth/keep
      tags:
        - notes
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/keep: See, edit, create and permanently delete all your Google Keep data
            https://www.googleapis.com/auth/keep.readonly: View all your Google Keep data
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/keep: See, edit, create and permanently delete all your Google Keep data
            https://www.googleapis.com/auth/keep.readonly: View all your Google Keep data
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
