from dataclasses import dataclass, field
from typing import Enum

class CustomDomainAssociationStatusEnum(str, Enum):
    CREATING = "CREATING"
    CREATE_FAILED = "CREATE_FAILED"
    ACTIVE = "ACTIVE"
    DELETING = "DELETING"
    DELETE_FAILED = "DELETE_FAILED"
    PENDING_CERTIFICATE_DNS_VALIDATION = "PENDING_CERTIFICATE_DNS_VALIDATION"
    BINDING_CERTIFICATE = "BINDING_CERTIFICATE"

