from .canceltask import *
from .createtask import *
from .describedevice import *
from .describedeviceec2instances import *
from .describeexecution import *
from .describetask import *
from .listdeviceresources import *
from .listdevices import *
from .listexecutions import *
from .listtagsforresource import *
from .listtasks import *
from .tagresource import *
from .untagresource import *
