openapi: 3.0.0
servers:
  - url: https://docs.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: Reads and writes Google Docs documents.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Google Docs API
  version: v1
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png
  x-origin:
    - converter:
        url: https://github.com/mermade/oas-kit
        version: 7.0.4
      format: google
      url: https://docs.googleapis.com/$discovery/rest?version=v1
      version: v1
  x-providerName: googleapis.com
  x-serviceName: docs
tags:
  - name: documents
paths:
  /v1/documents:
    post:
      description: Creates a blank document using the title given in the request. Other fields in the request, including any provided content, are ignored. Returns the created document.
      operationId: docs.documents.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/documents
          Oauth2c:
            - https://www.googleapis.com/auth/documents
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      tags:
        - documents
  "/v1/documents/{documentId}":
    get:
      description: Gets the latest version of the specified document.
      operationId: docs.documents.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/documents
          Oauth2c:
            - https://www.googleapis.com/auth/documents
        - Oauth2:
            - https://www.googleapis.com/auth/documents.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/documents.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
        - Oauth2:
            - https://www.googleapis.com/auth/drive.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/drive.readonly
      tags:
        - documents
  "/v1/documents/{documentId}:batchUpdate":
    post:
      description: "Applies one or more updates to the document. Each request is validated before being applied. If any request is not valid, then the entire request will fail and nothing will be applied. Some requests have replies to give you some information about how they are applied. Other requests do not need to return information; these each return an empty reply. The order of replies matches that of the requests. For example, suppose you call batchUpdate with four updates, and only the th[...]"
      operationId: docs.documents.batchUpdate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/documents
          Oauth2c:
            - https://www.googleapis.com/auth/documents
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/drive.file
          Oauth2c:
            - https://www.googleapis.com/auth/drive.file
      tags:
        - documents
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/documents: See, edit, create, and delete all your Google Docs documents
            https://www.googleapis.com/auth/documents.readonly: See all your Google Docs documents
            https://www.googleapis.com/auth/drive: See, edit, create, and delete all of your Google Drive files
            https://www.googleapis.com/auth/drive.file: See, edit, create, and delete only the specific Google Drive files you use with this app
            https://www.googleapis.com/auth/drive.readonly: See and download all your Google Drive files
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/documents: See, edit, create, and delete all your Google Docs documents
            https://www.googleapis.com/auth/documents.readonly: See all your Google Docs documents
            https://www.googleapis.com/auth/drive: See, edit, create, and delete all of your Google Drive files
            https://www.googleapis.com/auth/drive.file: See, edit, create, and delete only the specific Google Drive files you use with this app
            https://www.googleapis.com/auth/drive.readonly: See and download all your Google Drive files
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
