from .recommender_projects_locations_insighttypes_insights_list import *
from .recommender_projects_locations_insighttypes_insights_markaccepted import *
from .recommender_projects_locations_recommenders_recommendations_get import *
from .recommender_projects_locations_recommenders_recommendations_list import *
from .recommender_projects_locations_recommenders_recommendations_markclaimed import *
from .recommender_projects_locations_recommenders_recommendations_markfailed import *
from .recommender_projects_locations_recommenders_recommendations_marksucceeded import *
from .recommender_projects_locations_recommenders_updateconfig import *
