from .classroom_courses_aliases_create import *
from .classroom_courses_aliases_delete import *
from .classroom_courses_aliases_list import *
from .classroom_courses_announcements_create import *
from .classroom_courses_announcements_delete import *
from .classroom_courses_announcements_get import *
from .classroom_courses_announcements_list import *
from .classroom_courses_announcements_modifyassignees import *
from .classroom_courses_announcements_patch import *
from .classroom_courses_coursework_create import *
from .classroom_courses_coursework_delete import *
from .classroom_courses_coursework_get import *
from .classroom_courses_coursework_list import *
from .classroom_courses_coursework_modifyassignees import *
from .classroom_courses_coursework_patch import *
from .classroom_courses_coursework_studentsubmissions_get import *
from .classroom_courses_coursework_studentsubmissions_list import *
from .classroom_courses_coursework_studentsubmissions_modifyattachments import *
from .classroom_courses_coursework_studentsubmissions_patch import *
from .classroom_courses_coursework_studentsubmissions_reclaim import *
from .classroom_courses_coursework_studentsubmissions_return import *
from .classroom_courses_coursework_studentsubmissions_turnin import *
from .classroom_courses_courseworkmaterials_create import *
from .classroom_courses_courseworkmaterials_delete import *
from .classroom_courses_courseworkmaterials_get import *
from .classroom_courses_courseworkmaterials_list import *
from .classroom_courses_courseworkmaterials_patch import *
from .classroom_courses_create import *
from .classroom_courses_delete import *
from .classroom_courses_get import *
from .classroom_courses_list import *
from .classroom_courses_patch import *
from .classroom_courses_students_create import *
from .classroom_courses_students_delete import *
from .classroom_courses_students_get import *
from .classroom_courses_students_list import *
from .classroom_courses_teachers_create import *
from .classroom_courses_teachers_delete import *
from .classroom_courses_teachers_get import *
from .classroom_courses_teachers_list import *
from .classroom_courses_topics_create import *
from .classroom_courses_topics_delete import *
from .classroom_courses_topics_get import *
from .classroom_courses_topics_list import *
from .classroom_courses_topics_patch import *
from .classroom_courses_update import *
from .classroom_invitations_accept import *
from .classroom_invitations_create import *
from .classroom_invitations_delete import *
from .classroom_invitations_get import *
from .classroom_invitations_list import *
from .classroom_registrations_create import *
from .classroom_registrations_delete import *
from .classroom_userprofiles_get import *
from .classroom_userprofiles_guardianinvitations_create import *
from .classroom_userprofiles_guardianinvitations_get import *
from .classroom_userprofiles_guardianinvitations_list import *
from .classroom_userprofiles_guardianinvitations_patch import *
from .classroom_userprofiles_guardians_delete import *
from .classroom_userprofiles_guardians_get import *
from .classroom_userprofiles_guardians_list import *
