swagger: '2.0'
schemes:
  - https
host: supportcases.googleapis.com
basePath: /v2
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Support Cases API
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Google Support Cases Private
  version: v2
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/supportcases/v2/rest'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: supportcases
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/cases': View and manage your Google Support Cases
      'https://www.googleapis.com/auth/cases.readonly': View your Google Support Cases
      'https://www.googleapis.com/auth/supportcontent': View and manage your support data
    type: oauth2
tags:
  - name: agentActivities
  - name: agentSettings
  - name: attributes
  - name: cases
  - name: categoryInfos
  - name: communications
  - name: customerInteractions
  - name: customerIssues
  - name: devices
  - name: giftCards
  - name: ginlogs
  - name: hardwareAuditor
  - name: hardwareOrders
  - name: hardwareShipments
  - name: opportunities
  - name: play
  - name: products
  - name: resolutions
  - name: rma
  - name: rmas
  - name: teams
  - name: troubleshooterSessions
  - name: wallets
  - name: youtube
paths:
  /agentActivities:
    get:
      description: Lists an agent activities.
      operationId: supportcases.agentActivities.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - agentActivities
    post:
      description: Adds an agent activity.
      operationId: supportcases.agentActivities.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - agentActivities
  '/agentActivities:createFromHelpCenterDeepLink':
    post:
      description: Creates an agent activity from a help center deep link.
      operationId: supportcases.agentActivities.createFromHelpCenterDeepLink
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
        - Oauth2:
            - 'https://www.googleapis.com/auth/supportcontent'
      tags:
        - agentActivities
  /agentSettings:
    get:
      description: List all agent settings.
      operationId: supportcases.agentSettings.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - agentSettings
  '/cases:GetAgentUnreadCasesInfo':
    get:
      description: Gets information about unread cases for the calling agent. Only intended for use by the Cases frontend.
      operationId: supportcases.cases.getAgentUnreadCasesInfo
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - cases
  '/cases:autoAssign':
    post:
      description: Auto assign a case to the calling user.
      operationId: supportcases.cases.autoAssign
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/cases:createNewCase':
    post:
      description: Creates a new case (Note this is not a true CRUD method as no resource is being passed in).
      operationId: supportcases.cases.createNewCase
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/cases:getAgentSearchCount':
    get:
      description: 'Gets the search count for cases associated with the calling agent, and begin sending Tango notifications when the count changes.'
      operationId: supportcases.cases.getAgentSearchCount
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - cases
  '/cases:listByAgent':
    get:
      description: Lists cases associated with the agent. Only intended for use by the Cases frontend.
      operationId: supportcases.cases.listByAgent
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - cases
  '/cases:validateConsultForm':
    post:
      description: Validates that consult forms are properly configured.
      operationId: supportcases.cases.validateConsultForm
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/supportcontent'
      tags:
        - cases
  '/categoryInfos:batchGet':
    get:
      description: 'Batch gets category info. (Best effort, returns valid category infos only) Suppresses warning: GET requires method name starting with "Get" or "List"'
      operationId: supportcases.categoryInfos.batchGet
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - categoryInfos
  '/categoryInfos:listTopLevel':
    get:
      description: Lists gKMS top level category info.
      operationId: supportcases.categoryInfos.listTopLevel
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - categoryInfos
  '/categoryInfos:search':
    get:
      description: 'Searches category info. Suppresses warning: GET requires method name starting with "Get" or "List"'
      operationId: supportcases.categoryInfos.search
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - categoryInfos
  '/categoryInfos:searchMultiple':
    post:
      description: Searches multiple category info.
      operationId: supportcases.categoryInfos.searchMultiple
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - categoryInfos
  /communications:
    get:
      description: Lists communications that match the filter.
      operationId: supportcases.communications.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - communications
  '/communications:buildNewEmail':
    post:
      description: Builds an email template for the first email on a case.
      operationId: supportcases.communications.buildNewEmail
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - communications
  '/communications:buildReplyEmail':
    post:
      description: Builds an email template for a reply to an existing email.
      operationId: supportcases.communications.buildReplyEmail
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - communications
  '/communications:createConsultNote':
    post:
      description: Creates a draft note that replies to a consult note.
      operationId: supportcases.communications.createConsultNote
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - communications
  '/communications:createEmail':
    post:
      description: Creates a draft email and adds it to a case.
      operationId: supportcases.communications.createEmail
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - communications
  '/communications:createNote':
    post:
      description: Creates a note.
      operationId: supportcases.communications.createNote
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - communications
  '/communications:listRelated':
    get:
      description: 'Lists communications that are related to each other, including the communications on the requested case. Related communications include consult communications from target cases. Currently, only related communications from consult cases are supported.'
      operationId: supportcases.communications.listRelated
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - communications
  '/communications:suggestReplyEmailHeaders':
    get:
      description: 'Suggests a set of email headers for an email reply to another email. Suppresses warning: GET requires method name starting with "Get" or "List"'
      operationId: supportcases.communications.suggestReplyEmailHeaders
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - communications
  /customerInteractions:
    get:
      description: List customer interactions.
      operationId: supportcases.customerInteractions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - customerInteractions
  '/customerInteractions:summarize':
    get:
      description: 'Summary statistics about the cutomer''s interaction history. Suppresses warning: GET requires method name starting with "Get" or "List"'
      operationId: supportcases.customerInteractions.summarize
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - customerInteractions
  '/customerIssues:list':
    get:
      description: List issues and their resolutions for a customer.
      operationId: supportcases.customerIssues.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - customerIssues
  /devices:
    get:
      description: List devices.
      operationId: supportcases.devices.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - devices
  '/devices:getById':
    get:
      description: Gets the specified device by any device ID.
      operationId: supportcases.devices.getById
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - devices
  '/devices:updateOwner':
    get:
      description: 'Updates the owner of a device. Suppresses warning: GET requires method name starting with "Get" or "List"'
      operationId: supportcases.devices.updateOwner
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - devices
  '/giftCards:checkRedeemer':
    post:
      description: 'If the card is already redeemed by somebody else, customer can try a few users.'
      operationId: supportcases.giftCards.checkRedeemer
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - giftCards
  '/giftCards:lookup':
    post:
      description: 'Finds a gift card based on its full redemption code or activation number. With full redemption code, returns redemption token on success.'
      operationId: supportcases.giftCards.lookup
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - giftCards
  '/giftCards:redeem':
    post:
      description: Redeems a gift card to a customer using the redemption token.
      operationId: supportcases.giftCards.redeem
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - giftCards
  '/giftCards:verify':
    post:
      description: Verifies ownership of a damaged GC by checking if the activation number and partial redemption code are valid and refers to the same card. Returns the redemption token on success.
      operationId: supportcases.giftCards.verify
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - giftCards
  '/ginlogs:logDataAccess':
    post:
      description: Logs data access.
      operationId: supportcases.ginlogs.logDataAccess
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - ginlogs
  '/hardwareAuditor/orders:list':
    post:
      description: Lists hardware orders.
      operationId: supportcases.hardwareAuditor.orders.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - hardwareAuditor
  '/hardwareOrders:hardwareSignals':
    post:
      description: Gets hardware signals based on the case and customer.
      operationId: supportcases.hardwareOrders.hardwareSignals
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - hardwareOrders
  '/hardwareOrders:list':
    post:
      description: Lists hardware orders.
      operationId: supportcases.hardwareOrders.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - hardwareOrders
  '/hardwareOrders:listOtherDevices':
    post:
      description: Gets a user's devices that are not in the ListHardwareOrders result.
      operationId: supportcases.hardwareOrders.listOtherDevices
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - hardwareOrders
  /opportunities:
    get:
      description: Lists opportunities.
      operationId: supportcases.opportunities.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - opportunities
  '/opportunities/pitches:batchCreate':
    post:
      description: Batch creates pitches.
      operationId: supportcases.opportunities.pitches.batchCreate
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - opportunities
  '/play/digitalContent/orders:batchGet':
    post:
      description: Get a collection of orders.
      operationId: supportcases.play.digitalContent.orders.batchGet
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - play
  '/play/digitalContent/orders:refund':
    post:
      description: Refund orders.
      operationId: supportcases.play.digitalContent.orders.refund
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - play
  '/play/digitalContent/orders:search':
    post:
      description: Search for orders.
      operationId: supportcases.play.digitalContent.orders.search
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - play
  '/play/digitalContent/subscriptions:batchGet':
    post:
      description: Get a collection of subscriptions.
      operationId: supportcases.play.digitalContent.subscriptions.batchGet
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - play
  '/play/digitalContent/subscriptions:cancel':
    post:
      description: Cancel subscription.
      operationId: supportcases.play.digitalContent.subscriptions.cancel
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - play
  '/play/digitalContent/subscriptions:getCancellationStatus':
    post:
      description: Get cancellation status.
      operationId: supportcases.play.digitalContent.subscriptions.getCancellationStatus
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - play
  '/play/digitalContent/subscriptions:list':
    post:
      description: List subscriptions.
      operationId: supportcases.play.digitalContent.subscriptions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - play
  '/play/digitalContent:getRefundStatus':
    post:
      description: Get refund status.
      operationId: supportcases.play.digitalContent.getRefundStatus
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - play
  /products:
    get:
      description: Lists products.
      operationId: supportcases.products.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - products
  /resolutions:
    get:
      description: Query for resolutions.
      operationId: supportcases.resolutions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/supportcontent'
      tags:
        - resolutions
  '/resolutions/cohorts:assign':
    post:
      description: Query and assign cohorts for this case.
      operationId: supportcases.resolutions.cohorts.assign
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
        - Oauth2:
            - 'https://www.googleapis.com/auth/supportcontent'
      tags:
        - resolutions
  '/resolutions:log':
    post:
      description: Log a resolution.
      operationId: supportcases.resolutions.log
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - resolutions
  '/resolutions:suggest':
    post:
      description: Suggest some resolutions to a case based on provided signals.
      operationId: supportcases.resolutions.suggest
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/supportcontent'
      tags:
        - resolutions
  '/rma:save':
    post:
      description: Saves (Insert/Update) an RMA.
      operationId: supportcases.rma.save
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - rma
  '/rma:submit':
    post:
      description: 'DEPRECATED: Use SendRma instead. Submit an RMA.'
      operationId: supportcases.rma.submit
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - rma
  /rmas:
    get:
      description: Lists RMAs by Case ID and RMA state
      operationId: supportcases.rmas.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - rmas
  '/rmas:createExchangeWithoutReturn':
    post:
      description: Sends merchandise without expecting a return.
      operationId: supportcases.rmas.createExchangeWithoutReturn
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - rmas
  '/rmas:listBuyersRemorseCountryCodes':
    get:
      description: Lists two-character country codes valid for Buyer's Remorse RMAs.
      operationId: supportcases.rmas.listBuyersRemorseCountryCodes
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - rmas
  '/rmas:runWorkflow':
    post:
      description: 'DEPRECATED: Use RunRmaSteps instead. Run the given workflow for an RMA.'
      operationId: supportcases.rmas.runWorkflow
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - rmas
  '/rmas:send':
    post:
      description: Initiates a new RMA.
      operationId: supportcases.rmas.send
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - rmas
  '/teams:getMyAssignStreamSearches':
    get:
      description: Gets assign-stream-enabled searches associated with the agent.
      operationId: supportcases.teams.getMyAssignStreamSearches
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - teams
  '/troubleshooterSessions:create':
    post:
      description: Start a new troubleshooter session.
      operationId: supportcases.troubleshooterSessions.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
        - Oauth2:
            - 'https://www.googleapis.com/auth/supportcontent'
      tags:
        - troubleshooterSessions
  '/troubleshooterSessions:listDevices':
    post:
      description: Lists devices on a customer's account.
      operationId: supportcases.troubleshooterSessions.listDevices
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
        - Oauth2:
            - 'https://www.googleapis.com/auth/supportcontent'
      tags:
        - troubleshooterSessions
  '/troubleshooterSessions:listIssues':
    get:
      description: Lists issues.
      operationId: supportcases.troubleshooterSessions.listIssues
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
        - Oauth2:
            - 'https://www.googleapis.com/auth/supportcontent'
      tags:
        - troubleshooterSessions
  '/troubleshooterSessions:listPurchasedApps':
    post:
      description: Lists purchased apps on a customer's account.
      operationId: supportcases.troubleshooterSessions.listPurchasedApps
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
        - Oauth2:
            - 'https://www.googleapis.com/auth/supportcontent'
      tags:
        - troubleshooterSessions
  '/troubleshooterSessions:listPurchasedBooks':
    post:
      description: Lists purchased books on a customer's account.
      operationId: supportcases.troubleshooterSessions.listPurchasedBooks
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
        - Oauth2:
            - 'https://www.googleapis.com/auth/supportcontent'
      tags:
        - troubleshooterSessions
  '/troubleshooterSessions:listPurchasedVideos':
    post:
      description: Lists purchased videos on a customer's account.
      operationId: supportcases.troubleshooterSessions.listPurchasedVideos
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
        - Oauth2:
            - 'https://www.googleapis.com/auth/supportcontent'
      tags:
        - troubleshooterSessions
  '/wallets/accounts/paymentInstruments:getHijackReviewsStatus':
    post:
      description: Retrieve status for Payment Method Hijack (PMH) reviews. This is a POST API because it takes in a sso_ticket.
      operationId: supportcases.wallets.accounts.paymentInstruments.getHijackReviewsStatus
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - wallets
  '/wallets/accounts/paymentInstruments:initiateHijackReviews':
    post:
      description: Initiate Payment Method Hijack (PMH) reviews.
      operationId: supportcases.wallets.accounts.paymentInstruments.initiateHijackReviews
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - wallets
  '/wallets/accounts:getPaymentsInfo':
    post:
      description: 'Fetches Payments info, such as number of Payments accounts for the user.'
      operationId: supportcases.wallets.accounts.getPaymentsInfo
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - wallets
  '/wallets/accounts:getReviewStatus':
    post:
      description: Fetches the review status of a wallet account. This is a POST API because it takes in a sso_ticket.
      operationId: supportcases.wallets.accounts.getReviewStatus
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - wallets
  '/wallets/accounts:getSignals':
    get:
      description: Fetches Wallet account signals for troubleshooting Wallet issues.
      operationId: supportcases.wallets.accounts.getSignals
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - wallets
  '/wallets/accounts:searchReviews':
    post:
      description: Initiates a review on the Wallet account. This is a POST API because it takes in a sso_ticket. This API could lead to a review escalation (increase in priority).
      operationId: supportcases.wallets.accounts.searchReviews
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - wallets
  /wallets/bankAccountCountries:
    post:
      description: List supported Bank Account countries. Initially will only return supported Bank Account countries for Payment Method Hijacks (PMH). This is a POST API because it takes in a sso_ticket.
      operationId: supportcases.wallets.bankAccountCountries
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - wallets
  /wallets/creditCardTypes:
    post:
      description: List supported Credit Card types. Initially will only return supported credit cards for Payment Method Hijacks (PMH). This is a POST API because it takes in a sso_ticket.
      operationId: supportcases.wallets.creditCardTypes
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - wallets
  /wallets/paymentInstrumentTypeInfos:
    get:
      description: List supported payment instrument types. This API is not customer contextual.
      operationId: supportcases.wallets.paymentInstrumentTypeInfos.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - wallets
  '/wallets/paymentInstruments:suggestIssuer':
    get:
      description: 'Fetches suggestions for payment(credit card, bank, direct carrier billing) issuers.'
      operationId: supportcases.wallets.paymentInstruments.suggestIssuer
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - wallets
  /wallets/transactions:
    post:
      description: Query for transactions.
      operationId: supportcases.wallets.transactions
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - wallets
  '/wallets:troubleshootAccount':
    post:
      description: Troubleshoots a Wallet account for issues.
      operationId: supportcases.wallets.troubleshootAccount
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - wallets
  '/wallets:troubleshootTransaction':
    post:
      description: Troubleshoots a Wallet transaction for issues.
      operationId: supportcases.wallets.troubleshootTransaction
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - wallets
  '/youtube/components:cancel':
    post:
      description: Cancel/Downgrade component(s).
      operationId: supportcases.youtube.components.cancel
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - youtube
  '/youtube/entitlements:cancel':
    post:
      description: Cancel entitlement.
      operationId: supportcases.youtube.entitlements.cancel
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - youtube
  /youtube/onetimepurchases:
    post:
      description: Gets a list of one time purchases.
      operationId: supportcases.youtube.onetimepurchases
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - youtube
  /youtube/summary:
    post:
      description: Get Customer Summary Information for entitlements and refund history.
      operationId: supportcases.youtube.summary
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - youtube
  '/youtube/transactions:listByEntitlements':
    post:
      description: Get all transactions for entitlements.
      operationId: supportcases.youtube.transactions.listByEntitlements
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - youtube
  '/youtube/transactions:refund':
    post:
      description: Refund a batch of transactions.
      operationId: supportcases.youtube.transactions.refund
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - youtube
  '/{name}':
    delete:
      description: Deletes an attachment from a draft.
      operationId: supportcases.communications.attachments.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - communications
    get:
      description: Gets the specified RMA.
      operationId: supportcases.rmas.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - rmas
    post:
      description: Creates a new workflow state on a case.
      operationId: supportcases.cases.workflows.post
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
    put:
      description: Updates product for the specified case.
      operationId: supportcases.cases.issue.updateProduct
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}/customer/billingAddresses':
    post:
      description: Lists customer billing addresses. Only intended for use by the Cases frontend.
      operationId: supportcases.cases.customer.billingAddresses
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - cases
  '/{name}/customer/shippingAddresses':
    post:
      description: Lists customer shipping addresses. Only intended for use by the Cases frontend.
      operationId: supportcases.cases.customer.shippingAddresses
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - cases
  '/{name}/properties':
    get:
      description: Lists all properties associated with a category info.
      operationId: supportcases.categoryInfos.properties.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - categoryInfos
  '/{name}/refunds':
    post:
      description: 'Lists refunds for a hardware order. Get by shipmentId: /v2/hardwareShipments/:'
      operationId: supportcases.hardwareShipments.refunds
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - hardwareShipments
  '/{name}:WaitForConsult':
    post:
      description: Sets a case with an active consult case to IN_CONSULT state.
      operationId: supportcases.cases.waitForConsult
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:assign':
    post:
      description: Assigns the specified case.
      operationId: supportcases.cases.assign
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:authenticate':
    post:
      description: Authenticates a customer for a case.
      operationId: supportcases.cases.customer.authenticate
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:batchUpdate':
    post:
      description: Updates attributes for a case in batch.
      operationId: supportcases.cases.attributes.batchUpdate
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:block':
    post:
      description: 'Indicate the specified case is blocked by a bug/case/legal order, etc.'
      operationId: supportcases.cases.block
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:callBack':
    post:
      description: Makes a callback. Deauthenticates customer.
      operationId: supportcases.cases.callBack
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:cancel':
    post:
      description: Cancel an RMA.
      operationId: supportcases.rmas.cancel
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - rmas
  '/{name}:cancelAuthHold':
    post:
      description: Cancels an auth hold for an advanced exchange RMA.
      operationId: supportcases.rmas.cancelAuthHold
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - rmas
  '/{name}:cancelSend':
    post:
      description: Cancel a pending send (for email only).
      operationId: supportcases.communications.cancelSend
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - communications
  '/{name}:checkWalletAccount':
    get:
      description: 'Check if a customer has a valid Wallet account. Suppresses warning: GET requires method name starting with "Get" or "List"'
      operationId: supportcases.cases.customer.checkWalletAccount
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - cases
  '/{name}:createNoteConsult':
    post:
      description: Creates a consult case via note channel for this case.
      operationId: supportcases.cases.createNoteConsult
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:createRealTimeConsult':
    post:
      description: Creates a consult case via RealTime channel for this case.
      operationId: supportcases.cases.createRealTimeConsult
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:deauthenticate':
    post:
      description: Deauthenticates a customer for a case.
      operationId: supportcases.cases.customer.deauthenticate
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:dedupe':
    post:
      description: Deduplicates a case by closing duplicates cases.
      operationId: supportcases.cases.dedupe
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:discardDraft':
    post:
      description: Discards a draft communication.
      operationId: supportcases.communications.discardDraft
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - communications
  '/{name}:escalate':
    post:
      description: Escalates a case.
      operationId: supportcases.cases.escalate
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:finalizeConsultNote':
    post:
      description: Finalizes and sends a draft note for a consult case.
      operationId: supportcases.communications.finalizeConsultNote
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - communications
  '/{name}:finalizeNote':
    post:
      description: Finalize a note (a note cannot be updated after it is finalized).
      operationId: supportcases.communications.finalizeNote
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - communications
  '/{name}:finish':
    post:
      description: Sets the specified case to the finished state and triggers other finisher related workflows.
      operationId: supportcases.cases.finish
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:getAuthenticationCreditCardTypes':
    post:
      description: Get credit card types for authentication.
      operationId: supportcases.cases.customer.getAuthenticationCreditCardTypes
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - cases
  '/{name}:getAuthenticationQuestions':
    post:
      description: Get authentication options for a customer for a case.
      operationId: supportcases.cases.customer.getAuthenticationQuestions
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - cases
  '/{name}:getAuthenticationResult':
    post:
      description: Get authentication status for a customer of a case.
      operationId: supportcases.cases.customer.getAuthenticationResult
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:getBusinessListings':
    post:
      description: Gets the business listings for a customer.
      operationId: supportcases.cases.customer.getBusinessListings
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:getConsultSla':
    post:
      description: Calculates the SLA due by time that a new consult case would have.
      operationId: supportcases.cases.getConsultSla
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - cases
  '/{name}:getDetail':
    post:
      description: Gets detail for a hardware order.
      operationId: supportcases.hardwareOrders.getDetail
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - hardwareOrders
  '/{name}:getEscalationTargets':
    get:
      description: Gets the available escalation targets.
      operationId: supportcases.products.getEscalationTargets
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - products
  '/{name}:getLostStolenEligibility':
    post:
      description: Determines the eligibility of a lost/stolen RMA.
      operationId: supportcases.rmas.getLostStolenEligibility
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - rmas
  '/{name}:getLostStolenRefundEligibility':
    post:
      description: 'Gets lost stolen refund eligibility for account Get by shipmentId: /v2/hardwareShipments/:'
      operationId: supportcases.hardwareShipments.getLostStolenRefundEligibility
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - hardwareShipments
  '/{name}:getMailingAddress':
    post:
      description: Get mailing address for an RMA
      operationId: supportcases.rmas.getMailingAddress
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - rmas
  '/{name}:getOrderDetail':
    post:
      description: Gets an RMA's order detail.
      operationId: supportcases.rmas.getOrderDetail
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - rmas
  '/{name}:getReplacementDetail':
    post:
      description: Get details for a replacement device that is not associated with an order.
      operationId: supportcases.rmas.getReplacementDetail
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - rmas
  '/{name}:getRoutingTargets':
    get:
      description: Gets the available routing targets.
      operationId: supportcases.products.getRoutingTargets
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - products
  '/{name}:getShippingAddress':
    post:
      description: '--------- Begin of shipment Id based calls ----------------- Gets shipping address for a purchase Get by shipmentId: /v2/hardwareShipments/:'
      operationId: supportcases.hardwareShipments.getShippingAddress
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - hardwareShipments
  '/{name}:getShippingCustomerName':
    post:
      description: 'Gets the shipping customer name for a hardware order Get by shipmentId: /v2/hardwareShipments/:'
      operationId: supportcases.hardwareShipments.getShippingCustomerName
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - hardwareShipments
  '/{name}:getShippingCustomerPhoneNumber':
    post:
      description: 'Gets the shipping customer phone number for a hardware order Get by shipmentId: /v2/hardwareShipments/:'
      operationId: supportcases.hardwareShipments.getShippingCustomerPhoneNumber
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - hardwareShipments
  '/{name}:listChildren':
    get:
      description: Lists children category info.
      operationId: supportcases.categoryInfos.listChildren
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - categoryInfos
  '/{name}:listSettings':
    get:
      description: Lists product settings for an agent.
      operationId: supportcases.products.listSettings
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - products
  '/{name}:log':
    post:
      description: Log troubleshooter activity.
      operationId: supportcases.troubleshooterSessions.log
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
        - Oauth2:
            - 'https://www.googleapis.com/auth/supportcontent'
      tags:
        - troubleshooterSessions
  '/{name}:markOriginalDeviceReceived':
    post:
      description: Marks an original device as received in a Standard Exchange.
      operationId: supportcases.rmas.markOriginalDeviceReceived
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - rmas
  '/{name}:needsInfo':
    post:
      description: Sets the specified case to the needs info state.
      operationId: supportcases.cases.needsInfo
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:offeredSolution':
    post:
      description: Sets the specified case to the solution offered state indicating that a previous communication was a "solution".
      operationId: supportcases.cases.offeredSolution
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:read':
    post:
      description: Marks a case as read by the calling agent if they are the assignee.
      operationId: supportcases.cases.read
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:refund':
    post:
      description: Refunds a hardware shipment by shipment id.
      operationId: supportcases.hardwareShipments.refund
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - hardwareShipments
  '/{name}:release':
    post:
      description: Unassigns the specified case from the gaia user associated with this call.
      operationId: supportcases.cases.release
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:route':
    post:
      description: Routes the specified case to another product or team.
      operationId: supportcases.cases.route
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:runRmaSteps':
    post:
      description: Run the given RMA workflow steps.
      operationId: supportcases.rmas.runRmaSteps
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - rmas
  '/{name}:send':
    post:
      description: Sends a draft email. This finalizes the email.
      operationId: supportcases.communications.send
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - communications
  '/{name}:spam':
    post:
      description: Marks the specified case as spam.
      operationId: supportcases.cases.spam
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:split':
    post:
      description: Move a case's communication into a new case.
      operationId: supportcases.cases.split
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:suggestNewEmailHeaders':
    get:
      description: 'Suggests a set of headers (like from aliases) for a new email on a case. Suppresses warning: GET requires method name starting with "Get" or "List"'
      operationId: supportcases.cases.suggestNewEmailHeaders
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - cases
  '/{name}:suggestNoteHeaders':
    get:
      description: 'Suggests a set of headers (like from aliases) for a note Suppresses warning: GET requires method name starting with "Get" or "List"'
      operationId: supportcases.cases.suggestNoteHeaders
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases.readonly'
      tags:
        - cases
  '/{name}:take':
    post:
      description: Assigns the specified case to the gaia user associated with this call.
      operationId: supportcases.cases.take
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:transfer':
    post:
      description: Transfers the specified case from the gaia user associated with this call to another user.
      operationId: supportcases.cases.transfer
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:troubleshootIssue':
    post:
      description: Troubleshoot issue.
      operationId: supportcases.troubleshooterSessions.troubleshootIssue
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
        - Oauth2:
            - 'https://www.googleapis.com/auth/supportcontent'
      tags:
        - troubleshooterSessions
  '/{name}:unassign':
    post:
      description: Unassigns the specified case from its current assignee. Note that this also moves the case to the UNASSIGNED state.
      operationId: supportcases.cases.unassign
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:unblock':
    post:
      description: 'Indicate the specified case is no longer blocked by a bug/case/ legal order, etc.'
      operationId: supportcases.cases.unblock
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:unspam':
    post:
      description: Unmark the specified case as spam.
      operationId: supportcases.cases.unspam
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:update':
    post:
      description: 'Updates attributes for the specified case. Note: This call adds the attributes that are not present on the case to the case. If attribute is already present on the case, the value is replaced.'
      operationId: supportcases.cases.attributes.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
    put:
      description: Updates workflow state.
      operationId: supportcases.cases.workflows.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:updateAgentCategories':
    post:
      description: 'Updates agent categories for the specified case. Note: This call replaces categories on the case by new categories passed in the request.'
      operationId: supportcases.cases.issue.product.updateAgentCategories
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:updateConsultNote':
    post:
      description: Updates a draft consult note with new content.
      operationId: supportcases.communications.updateConsultNote
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - communications
  '/{name}:updateContactEmail':
    post:
      description: Updates contact email for the specified case.
      operationId: supportcases.cases.customer.updateContactEmail
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:updateContactName':
    post:
      description: Updates contact name for the specified case.
      operationId: supportcases.cases.customer.updateContactName
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:updateCustomerAttributes':
    post:
      description: Updates customer attributes for the specified case.
      operationId: supportcases.cases.customer.updateCustomerAttributes
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:updateDisconnectedChannel':
    post:
      description: Updates disconnected channel for the specified case.
      operationId: supportcases.cases.updateDisconnectedChannel
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:updateEligibleProgram':
    post:
      description: Update customer attributes indicating eligibility for opportunities.
      operationId: supportcases.cases.updateEligibleProgram
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:updateEmail':
    post:
      description: Updates a draft email.
      operationId: supportcases.communications.updateEmail
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - communications
  '/{name}:updateLocale':
    post:
      description: Updates the case's issue locale.
      operationId: supportcases.cases.issue.updateLocale
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases
  '/{name}:updateNote':
    post:
      description: Updates a draft note.
      operationId: supportcases.communications.updateNote
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - communications
  '/{name}:updateSummary':
    post:
      description: Updates case's issue summary.
      operationId: supportcases.cases.issue.updateSummary
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cases'
      tags:
        - cases