package shared

type AwsRdsDbInstanceDetails struct {
	AllocatedStorage                      *int64                             `json:"AllocatedStorage"`
	AssociatedRoles                       []AwsRdsDbInstanceAssociatedRole   `json:"AssociatedRoles"`
	AutoMinorVersionUpgrade               *bool                              `json:"AutoMinorVersionUpgrade"`
	AvailabilityZone                      *string                            `json:"AvailabilityZone"`
	BackupRetentionPeriod                 *int64                             `json:"BackupRetentionPeriod"`
	CaCertificateIdentifier               *string                            `json:"CACertificateIdentifier"`
	CharacterSetName                      *string                            `json:"CharacterSetName"`
	CopyTagsToSnapshot                    *bool                              `json:"CopyTagsToSnapshot"`
	DbClusterIdentifier                   *string                            `json:"DBClusterIdentifier"`
	DbInstanceClass                       *string                            `json:"DBInstanceClass"`
	DbInstanceIdentifier                  *string                            `json:"DBInstanceIdentifier"`
	DbName                                *string                            `json:"DBName"`
	DbInstancePort                        *int64                             `json:"DbInstancePort"`
	DbInstanceStatus                      *string                            `json:"DbInstanceStatus"`
	DbParameterGroups                     []AwsRdsDbParameterGroup           `json:"DbParameterGroups"`
	DbSecurityGroups                      []string                           `json:"DbSecurityGroups"`
	DbSubnetGroup                         *AwsRdsDbSubnetGroup               `json:"DbSubnetGroup"`
	DbiResourceID                         *string                            `json:"DbiResourceId"`
	DeletionProtection                    *bool                              `json:"DeletionProtection"`
	DomainMemberships                     []AwsRdsDbDomainMembership         `json:"DomainMemberships"`
	EnabledCloudWatchLogsExports          []string                           `json:"EnabledCloudWatchLogsExports"`
	Endpoint                              *AwsRdsDbInstanceEndpoint          `json:"Endpoint"`
	Engine                                *string                            `json:"Engine"`
	EngineVersion                         *string                            `json:"EngineVersion"`
	EnhancedMonitoringResourceArn         *string                            `json:"EnhancedMonitoringResourceArn"`
	IamDatabaseAuthenticationEnabled      *bool                              `json:"IAMDatabaseAuthenticationEnabled"`
	InstanceCreateTime                    *string                            `json:"InstanceCreateTime"`
	Iops                                  *int64                             `json:"Iops"`
	KmsKeyID                              *string                            `json:"KmsKeyId"`
	LatestRestorableTime                  *string                            `json:"LatestRestorableTime"`
	LicenseModel                          *string                            `json:"LicenseModel"`
	ListenerEndpoint                      *AwsRdsDbInstanceEndpoint          `json:"ListenerEndpoint"`
	MasterUsername                        *string                            `json:"MasterUsername"`
	MaxAllocatedStorage                   *int64                             `json:"MaxAllocatedStorage"`
	MonitoringInterval                    *int64                             `json:"MonitoringInterval"`
	MonitoringRoleArn                     *string                            `json:"MonitoringRoleArn"`
	MultiAz                               *bool                              `json:"MultiAz"`
	OptionGroupMemberships                []AwsRdsDbOptionGroupMembership    `json:"OptionGroupMemberships"`
	PendingModifiedValues                 *AwsRdsDbPendingModifiedValues     `json:"PendingModifiedValues"`
	PerformanceInsightsEnabled            *bool                              `json:"PerformanceInsightsEnabled"`
	PerformanceInsightsKmsKeyID           *string                            `json:"PerformanceInsightsKmsKeyId"`
	PerformanceInsightsRetentionPeriod    *int64                             `json:"PerformanceInsightsRetentionPeriod"`
	PreferredBackupWindow                 *string                            `json:"PreferredBackupWindow"`
	PreferredMaintenanceWindow            *string                            `json:"PreferredMaintenanceWindow"`
	ProcessorFeatures                     []AwsRdsDbProcessorFeature         `json:"ProcessorFeatures"`
	PromotionTier                         *int64                             `json:"PromotionTier"`
	PubliclyAccessible                    *bool                              `json:"PubliclyAccessible"`
	ReadReplicaDbClusterIdentifiers       []string                           `json:"ReadReplicaDBClusterIdentifiers"`
	ReadReplicaDbInstanceIdentifiers      []string                           `json:"ReadReplicaDBInstanceIdentifiers"`
	ReadReplicaSourceDbInstanceIdentifier *string                            `json:"ReadReplicaSourceDBInstanceIdentifier"`
	SecondaryAvailabilityZone             *string                            `json:"SecondaryAvailabilityZone"`
	StatusInfos                           []AwsRdsDbStatusInfo               `json:"StatusInfos"`
	StorageEncrypted                      *bool                              `json:"StorageEncrypted"`
	StorageType                           *string                            `json:"StorageType"`
	TdeCredentialArn                      *string                            `json:"TdeCredentialArn"`
	Timezone                              *string                            `json:"Timezone"`
	VpcSecurityGroups                     []AwsRdsDbInstanceVpcSecurityGroup `json:"VpcSecurityGroups"`
}
