package shared

type ResourceDetails struct {
	AwsAPIGatewayRestAPI              *AwsAPIGatewayRestAPIDetails              `json:"AwsApiGatewayRestApi,omitempty"`
	AwsAPIGatewayStage                *AwsAPIGatewayStageDetails                `json:"AwsApiGatewayStage,omitempty"`
	AwsAPIGatewayV2API                *AwsAPIGatewayV2APIDetails                `json:"AwsApiGatewayV2Api,omitempty"`
	AwsAPIGatewayV2Stage              *AwsAPIGatewayV2StageDetails              `json:"AwsApiGatewayV2Stage,omitempty"`
	AwsAutoScalingAutoScalingGroup    *AwsAutoScalingAutoScalingGroupDetails    `json:"AwsAutoScalingAutoScalingGroup,omitempty"`
	AwsAutoScalingLaunchConfiguration *AwsAutoScalingLaunchConfigurationDetails `json:"AwsAutoScalingLaunchConfiguration,omitempty"`
	AwsCertificateManagerCertificate  *AwsCertificateManagerCertificateDetails  `json:"AwsCertificateManagerCertificate,omitempty"`
	AwsCloudFrontDistribution         *AwsCloudFrontDistributionDetails         `json:"AwsCloudFrontDistribution,omitempty"`
	AwsCloudTrailTrail                *AwsCloudTrailTrailDetails                `json:"AwsCloudTrailTrail,omitempty"`
	AwsCodeBuildProject               *AwsCodeBuildProjectDetails               `json:"AwsCodeBuildProject,omitempty"`
	AwsDynamoDbTable                  *AwsDynamoDbTableDetails                  `json:"AwsDynamoDbTable,omitempty"`
	AwsEc2Eip                         *AwsEc2EipDetails                         `json:"AwsEc2Eip,omitempty"`
	AwsEc2Instance                    *AwsEc2InstanceDetails                    `json:"AwsEc2Instance,omitempty"`
	AwsEc2NetworkACL                  *AwsEc2NetworkACLDetails                  `json:"AwsEc2NetworkAcl,omitempty"`
	AwsEc2NetworkInterface            *AwsEc2NetworkInterfaceDetails            `json:"AwsEc2NetworkInterface,omitempty"`
	AwsEc2SecurityGroup               *AwsEc2SecurityGroupDetails               `json:"AwsEc2SecurityGroup,omitempty"`
	AwsEc2Subnet                      *AwsEc2SubnetDetails                      `json:"AwsEc2Subnet,omitempty"`
	AwsEc2Volume                      *AwsEc2VolumeDetails                      `json:"AwsEc2Volume,omitempty"`
	AwsEc2Vpc                         *AwsEc2VpcDetails                         `json:"AwsEc2Vpc,omitempty"`
	AwsEc2VpnConnection               *AwsEc2VpnConnectionDetails               `json:"AwsEc2VpnConnection,omitempty"`
	AwsEcrContainerImage              *AwsEcrContainerImageDetails              `json:"AwsEcrContainerImage,omitempty"`
	AwsEcsCluster                     *AwsEcsClusterDetails                     `json:"AwsEcsCluster,omitempty"`
	AwsEcsService                     *AwsEcsServiceDetails                     `json:"AwsEcsService,omitempty"`
	AwsEcsTaskDefinition              *AwsEcsTaskDefinitionDetails              `json:"AwsEcsTaskDefinition,omitempty"`
	AwsElasticBeanstalkEnvironment    *AwsElasticBeanstalkEnvironmentDetails    `json:"AwsElasticBeanstalkEnvironment,omitempty"`
	AwsElasticsearchDomain            *AwsElasticsearchDomainDetails            `json:"AwsElasticsearchDomain,omitempty"`
	AwsElbLoadBalancer                *AwsElbLoadBalancerDetails                `json:"AwsElbLoadBalancer,omitempty"`
	AwsElbv2LoadBalancer              *AwsElbv2LoadBalancerDetails              `json:"AwsElbv2LoadBalancer,omitempty"`
	AwsIamAccessKey                   *AwsIamAccessKeyDetails                   `json:"AwsIamAccessKey,omitempty"`
	AwsIamGroup                       *AwsIamGroupDetails                       `json:"AwsIamGroup,omitempty"`
	AwsIamPolicy                      *AwsIamPolicyDetails                      `json:"AwsIamPolicy,omitempty"`
	AwsIamRole                        *AwsIamRoleDetails                        `json:"AwsIamRole,omitempty"`
	AwsIamUser                        *AwsIamUserDetails                        `json:"AwsIamUser,omitempty"`
	AwsKmsKey                         *AwsKmsKeyDetails                         `json:"AwsKmsKey,omitempty"`
	AwsLambdaFunction                 *AwsLambdaFunctionDetails                 `json:"AwsLambdaFunction,omitempty"`
	AwsLambdaLayerVersion             *AwsLambdaLayerVersionDetails             `json:"AwsLambdaLayerVersion,omitempty"`
	AwsRdsDbCluster                   *AwsRdsDbClusterDetails                   `json:"AwsRdsDbCluster,omitempty"`
	AwsRdsDbClusterSnapshot           *AwsRdsDbClusterSnapshotDetails           `json:"AwsRdsDbClusterSnapshot,omitempty"`
	AwsRdsDbInstance                  *AwsRdsDbInstanceDetails                  `json:"AwsRdsDbInstance,omitempty"`
	AwsRdsDbSnapshot                  *AwsRdsDbSnapshotDetails                  `json:"AwsRdsDbSnapshot,omitempty"`
	AwsRdsEventSubscription           *AwsRdsEventSubscriptionDetails           `json:"AwsRdsEventSubscription,omitempty"`
	AwsRedshiftCluster                *AwsRedshiftClusterDetails                `json:"AwsRedshiftCluster,omitempty"`
	AwsS3AccountPublicAccessBlock     *AwsS3AccountPublicAccessBlockDetails     `json:"AwsS3AccountPublicAccessBlock,omitempty"`
	AwsS3Bucket                       *AwsS3BucketDetails                       `json:"AwsS3Bucket,omitempty"`
	AwsS3Object                       *AwsS3ObjectDetails                       `json:"AwsS3Object,omitempty"`
	AwsSecretsManagerSecret           *AwsSecretsManagerSecretDetails           `json:"AwsSecretsManagerSecret,omitempty"`
	AwsSnsTopic                       *AwsSnsTopicDetails                       `json:"AwsSnsTopic,omitempty"`
	AwsSqsQueue                       *AwsSqsQueueDetails                       `json:"AwsSqsQueue,omitempty"`
	AwsSsmPatchCompliance             *AwsSsmPatchComplianceDetails             `json:"AwsSsmPatchCompliance,omitempty"`
	AwsWafWebACL                      *AwsWafWebACLDetails                      `json:"AwsWafWebAcl,omitempty"`
	Container                         *ContainerDetails                         `json:"Container,omitempty"`
	Other                             map[string]string                         `json:"Other,omitempty"`
}
