

export enum FleetErrorCodeEnum {
    IamServiceRoleMissingEniDescribeAction = "IAM_SERVICE_ROLE_MISSING_ENI_DESCRIBE_ACTION"
,    IamServiceRoleMissingEniCreateAction = "IAM_SERVICE_ROLE_MISSING_ENI_CREATE_ACTION"
,    IamServiceRoleMissingEniDeleteAction = "IAM_SERVICE_ROLE_MISSING_ENI_DELETE_ACTION"
,    NetworkInterfaceLimitExceeded = "NETWORK_INTERFACE_LIMIT_EXCEEDED"
,    InternalServiceError = "INTERNAL_SERVICE_ERROR"
,    IamServiceRoleIsMissing = "IAM_SERVICE_ROLE_IS_MISSING"
,    MachineRoleIsMissing = "MACHINE_ROLE_IS_MISSING"
,    StsDisabledInRegion = "STS_DISABLED_IN_REGION"
,    SubnetHasInsufficientIpAddresses = "SUBNET_HAS_INSUFFICIENT_IP_ADDRESSES"
,    IamServiceRoleMissingDescribeSubnetAction = "IAM_SERVICE_ROLE_MISSING_DESCRIBE_SUBNET_ACTION"
,    SubnetNotFound = "SUBNET_NOT_FOUND"
,    ImageNotFound = "IMAGE_NOT_FOUND"
,    InvalidSubnetConfiguration = "INVALID_SUBNET_CONFIGURATION"
,    SecurityGroupsNotFound = "SECURITY_GROUPS_NOT_FOUND"
,    IgwNotAttached = "IGW_NOT_ATTACHED"
,    IamServiceRoleMissingDescribeSecurityGroupsAction = "IAM_SERVICE_ROLE_MISSING_DESCRIBE_SECURITY_GROUPS_ACTION"
,    FleetStopped = "FLEET_STOPPED"
,    FleetInstanceProvisioningFailure = "FLEET_INSTANCE_PROVISIONING_FAILURE"
,    DomainJoinErrorFileNotFound = "DOMAIN_JOIN_ERROR_FILE_NOT_FOUND"
,    DomainJoinErrorAccessDenied = "DOMAIN_JOIN_ERROR_ACCESS_DENIED"
,    DomainJoinErrorLogonFailure = "DOMAIN_JOIN_ERROR_LOGON_FAILURE"
,    DomainJoinErrorInvalidParameter = "DOMAIN_JOIN_ERROR_INVALID_PARAMETER"
,    DomainJoinErrorMoreData = "DOMAIN_JOIN_ERROR_MORE_DATA"
,    DomainJoinErrorNoSuchDomain = "DOMAIN_JOIN_ERROR_NO_SUCH_DOMAIN"
,    DomainJoinErrorNotSupported = "DOMAIN_JOIN_ERROR_NOT_SUPPORTED"
,    DomainJoinNerrInvalidWorkgroupName = "DOMAIN_JOIN_NERR_INVALID_WORKGROUP_NAME"
,    DomainJoinNerrWorkstationNotStarted = "DOMAIN_JOIN_NERR_WORKSTATION_NOT_STARTED"
,    DomainJoinErrorDsMachineAccountQuotaExceeded = "DOMAIN_JOIN_ERROR_DS_MACHINE_ACCOUNT_QUOTA_EXCEEDED"
,    DomainJoinNerrPasswordExpired = "DOMAIN_JOIN_NERR_PASSWORD_EXPIRED"
,    DomainJoinInternalServiceError = "DOMAIN_JOIN_INTERNAL_SERVICE_ERROR"
}
