from .changeserverlifecyclestate import *
from .createreplicationconfigurationtemplate import *
from .deletejob import *
from .deletereplicationconfigurationtemplate import *
from .deletesourceserver import *
from .describejoblogitems import *
from .describejobs import *
from .describereplicationconfigurationtemplates import *
from .describesourceservers import *
from .disconnectfromservice import *
from .finalizecutover import *
from .getlaunchconfiguration import *
from .getreplicationconfiguration import *
from .initializeservice import *
from .listtagsforresource import *
from .markasarchived import *
from .retrydatareplication import *
from .startcutover import *
from .starttest import *
from .tagresource import *
from .terminatetargetinstances import *
from .untagresource import *
from .updatelaunchconfiguration import *
from .updatereplicationconfiguration import *
from .updatereplicationconfigurationtemplate import *
