# coding: utf-8

"""
    Authentiq API

    Strong authentication, without the passwords.

    The version of the OpenAPI document: 6
    Contact: hello@authentiq.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.login_api import LoginApi


class TestLoginApi(unittest.TestCase):
    """LoginApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LoginApi()

    def tearDown(self) -> None:
        pass

    def test_push_login_request(self) -> None:
        """Test case for push_login_request

        """
        pass


if __name__ == '__main__':
    unittest.main()
