package shared




type ResourceShareAssociationStatusEnum string

const (
    ResourceShareAssociationStatusEnumAssociating ResourceShareAssociationStatusEnum = "ASSOCIATING"
ResourceShareAssociationStatusEnumAssociated ResourceShareAssociationStatusEnum = "ASSOCIATED"
ResourceShareAssociationStatusEnumFailed ResourceShareAssociationStatusEnum = "FAILED"
ResourceShareAssociationStatusEnumDisassociating ResourceShareAssociationStatusEnum = "DISASSOCIATING"
ResourceShareAssociationStatusEnumDisassociated ResourceShareAssociationStatusEnum = "DISASSOCIATED"
)


