# coding: utf-8

"""
    ApiManagementClient

    Use these REST APIs for performing operations on API entity and their Operations associated with your Azure API Management deployment.

    The version of the OpenAPI document: 2016-10-10
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.operation_update_contract import OperationUpdateContract

class TestOperationUpdateContract(unittest.TestCase):
    """OperationUpdateContract unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OperationUpdateContract:
        """Test OperationUpdateContract
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OperationUpdateContract`
        """
        model = OperationUpdateContract()
        if include_optional:
            return OperationUpdateContract(
                id = '',
                method = '',
                name = '0',
                url_template = '0',
                description = '',
                request = openapi_client.models.request_contract.RequestContract(
                    description = '', 
                    headers = [
                        openapi_client.models.parameter_contract.ParameterContract(
                            default_value = '', 
                            description = '', 
                            name = '', 
                            required = True, 
                            type = '', 
                            values = [
                                ''
                                ], )
                        ], 
                    query_parameters = [
                        openapi_client.models.parameter_contract.ParameterContract(
                            default_value = '', 
                            description = '', 
                            name = '', 
                            required = True, 
                            type = '', )
                        ], 
                    representations = [
                        openapi_client.models.representation_contract.RepresentationContract(
                            content_type = '', 
                            sample = '', )
                        ], ),
                responses = [
                    openapi_client.models.result_contract.ResultContract(
                        description = '', 
                        representations = [
                            openapi_client.models.representation_contract.RepresentationContract(
                                content_type = '', 
                                sample = '', )
                            ], 
                        status_code = 1E+2, )
                    ],
                template_parameters = [
                    openapi_client.models.parameter_contract.ParameterContract(
                        default_value = '', 
                        description = '', 
                        name = '', 
                        required = True, 
                        type = '', 
                        values = [
                            ''
                            ], )
                    ]
            )
        else:
            return OperationUpdateContract(
        )
        """

    def testOperationUpdateContract(self):
        """Test OperationUpdateContract"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
