# coding: utf-8

"""
    FrontDoorManagementClient

    Use these APIs to manage Azure Front Door resources through the Azure Resource Manager. You must make sure that requests made to these resources are secure.

    The version of the OpenAPI document: 2020-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.rules_engine_update_parameters import RulesEngineUpdateParameters

class TestRulesEngineUpdateParameters(unittest.TestCase):
    """RulesEngineUpdateParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RulesEngineUpdateParameters:
        """Test RulesEngineUpdateParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RulesEngineUpdateParameters`
        """
        model = RulesEngineUpdateParameters()
        if include_optional:
            return RulesEngineUpdateParameters(
                rules = [
                    openapi_client.models.rules_engine_rule.RulesEngineRule(
                        action = openapi_client.models.rules_engine_action.RulesEngineAction(
                            request_header_actions = [
                                openapi_client.models.header_action.HeaderAction(
                                    header_action_type = 'Append', 
                                    header_name = '', 
                                    value = '', )
                                ], 
                            response_header_actions = [
                                openapi_client.models.header_action.HeaderAction(
                                    header_action_type = 'Append', 
                                    header_name = '', 
                                    value = '', )
                                ], 
                            route_configuration_override = openapi_client.models.route_configuration.RouteConfiguration(
                                @odata/type = '', ), ), 
                        match_conditions = [
                            openapi_client.models.rules_engine_match_condition.RulesEngineMatchCondition(
                                negate_condition = True, 
                                rules_engine_match_value = [
                                    ''
                                    ], 
                                rules_engine_match_variable = 'IsMobile', 
                                rules_engine_operator = 'Any', 
                                selector = '', 
                                transforms = [
                                    'Lowercase'
                                    ], )
                            ], 
                        match_processing_behavior = 'Continue', 
                        name = '', 
                        priority = 56, )
                    ]
            )
        else:
            return RulesEngineUpdateParameters(
        )
        """

    def testRulesEngineUpdateParameters(self):
        """Test RulesEngineUpdateParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
