# coding: utf-8

"""
    ApiManagementClient

    Use these REST APIs for performing operations on API entity and their Operations associated with your Azure API Management deployment.

    The version of the OpenAPI document: 2017-03-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_list_by_tags200_response_value_inner_properties_tag_properties import ApiListByTags200ResponseValueInnerPropertiesTagProperties

class TestApiListByTags200ResponseValueInnerPropertiesTagProperties(unittest.TestCase):
    """ApiListByTags200ResponseValueInnerPropertiesTagProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiListByTags200ResponseValueInnerPropertiesTagProperties:
        """Test ApiListByTags200ResponseValueInnerPropertiesTagProperties
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiListByTags200ResponseValueInnerPropertiesTagProperties`
        """
        model = ApiListByTags200ResponseValueInnerPropertiesTagProperties()
        if include_optional:
            return ApiListByTags200ResponseValueInnerPropertiesTagProperties(
                display_name = '0'
            )
        else:
            return ApiListByTags200ResponseValueInnerPropertiesTagProperties(
                display_name = '0',
        )
        """

    def testApiListByTags200ResponseValueInnerPropertiesTagProperties(self):
        """Test ApiListByTags200ResponseValueInnerPropertiesTagProperties"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
