swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /youtube/v3
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: 'Supports core YouTube features, such as uploading videos, creating and managing playlists, searching for content, and much more.'
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: YouTube Data
  version: v3
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://pbs.twimg.com/profile_images/902547949103841281/TmdokZcM_400x400.jpg'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/youtube/v3/rest'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: youtube
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/youtube': Manage your YouTube account
      'https://www.googleapis.com/auth/youtube.force-ssl': Manage your YouTube account
      'https://www.googleapis.com/auth/youtube.readonly': View your YouTube account
      'https://www.googleapis.com/auth/youtube.upload': Manage your YouTube videos
      'https://www.googleapis.com/auth/youtubepartner': View and manage your assets and associated content on YouTube
      'https://www.googleapis.com/auth/youtubepartner-channel-audit': View private information of your YouTube channel relevant during the audit process with a YouTube partner
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/youtube': Manage your YouTube account
      'https://www.googleapis.com/auth/youtube.force-ssl': Manage your YouTube account
      'https://www.googleapis.com/auth/youtube.readonly': View your YouTube account
      'https://www.googleapis.com/auth/youtube.upload': Manage your YouTube videos
      'https://www.googleapis.com/auth/youtubepartner': View and manage your assets and associated content on YouTube
      'https://www.googleapis.com/auth/youtubepartner-channel-audit': View private information of your YouTube channel relevant during the audit process with a YouTube partner
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: activities
  - name: captions
  - name: channelBanners
  - name: channelSections
  - name: channels
  - name: commentThreads
  - name: comments
  - name: fanFundingEvents
  - name: guideCategories
  - name: i18nLanguages
  - name: i18nRegions
  - name: liveBroadcasts
  - name: liveChatBans
  - name: liveChatMessages
  - name: liveChatModerators
  - name: liveStreams
  - name: playlistItems
  - name: playlists
  - name: search
  - name: sponsors
  - name: subscriptions
  - name: superChatEvents
  - name: thumbnails
  - name: videoAbuseReportReasons
  - name: videoCategories
  - name: videos
  - name: watermarks
paths:
  /activities:
    get:
      description: 'Returns a list of channel activity events that match the request criteria. For example, you can retrieve events associated with a particular channel, events associated with the user''s subscriptions and Google+ friends, or the YouTube home page feed, which is customized for each user.'
      operationId: youtube.activities.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
      tags:
        - activities
    post:
      description: |-
        Posts a bulletin for a specific channel. (The user submitting the request must be authorized to act on the channel's behalf.)

        Note: Even though an activity resource can contain information about actions like a user rating a video or marking a video as a favorite, you need to use other API methods to generate those activity resources. For example, you would use the API's videos.rate() method to rate a video and the playlistItems.insert() method to mark a video as a favorite.
      operationId: youtube.activities.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - activities
  /captions:
    delete:
      description: Deletes a specified caption track.
      operationId: youtube.captions.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - captions
    get:
      description: Returns a list of caption tracks that are associated with a specified video. Note that the API response does not contain the actual captions and that the captions.download method provides the ability to retrieve a caption track.
      operationId: youtube.captions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - captions
    post:
      description: Uploads a caption track.
      operationId: youtube.captions.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - captions
    put:
      description: 'Updates a caption track. When updating a caption track, you can change the track''s draft status, upload a new caption file for the track, or both.'
      operationId: youtube.captions.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - captions
  '/captions/{id}':
    get:
      description: Downloads a caption track. The caption track is returned in its original format unless the request specifies a value for the tfmt parameter and in its original language unless the request specifies a value for the tlang parameter.
      operationId: youtube.captions.download
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - captions
  /channelBanners/insert:
    post:
      description: |-
        Uploads a channel banner image to YouTube. This method represents the first two steps in a three-step process to update the banner image for a channel:

        - Call the channelBanners.insert method to upload the binary image data to YouTube. The image must have a 16:9 aspect ratio and be at least 2120x1192 pixels.
        - Extract the url property's value from the response that the API returns for step 1.
        - Call the channels.update method to update the channel's branding settings. Set the brandingSettings.image.bannerExternalUrl property's value to the URL obtained in step 2.
      operationId: youtube.channelBanners.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.upload'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.upload'
      tags:
        - channelBanners
  /channelSections:
    delete:
      description: Deletes a channelSection.
      operationId: youtube.channelSections.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - channelSections
    get:
      description: Returns channelSection resources that match the API request criteria.
      operationId: youtube.channelSections.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - channelSections
    post:
      description: Adds a channelSection for the authenticated user's channel.
      operationId: youtube.channelSections.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - channelSections
    put:
      description: Update a channelSection.
      operationId: youtube.channelSections.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - channelSections
  /channels:
    get:
      description: Returns a collection of zero or more channel resources that match the request criteria.
      operationId: youtube.channels.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner-channel-audit'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner-channel-audit'
      tags:
        - channels
    put:
      description: Updates a channel's metadata. Note that this method currently only supports updates to the channel resource's brandingSettings and invideoPromotion objects and their child properties.
      operationId: youtube.channels.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - channels
  /commentThreads:
    get:
      description: Returns a list of comment threads that match the API request parameters.
      operationId: youtube.commentThreads.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - commentThreads
    post:
      description: 'Creates a new top-level comment. To add a reply to an existing comment, use the comments.insert method instead.'
      operationId: youtube.commentThreads.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - commentThreads
    put:
      description: Modifies the top-level comment in a comment thread.
      operationId: youtube.commentThreads.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - commentThreads
  /comments:
    delete:
      description: Deletes a comment.
      operationId: youtube.comments.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - comments
    get:
      description: Returns a list of comments that match the API request parameters.
      operationId: youtube.comments.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - comments
    post:
      description: 'Creates a reply to an existing comment. Note: To create a top-level comment, use the commentThreads.insert method.'
      operationId: youtube.comments.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - comments
    put:
      description: Modifies a comment.
      operationId: youtube.comments.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - comments
  /comments/markAsSpam:
    post:
      description: Expresses the caller's opinion that one or more comments should be flagged as spam.
      operationId: youtube.comments.markAsSpam
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - comments
  /comments/setModerationStatus:
    post:
      description: Sets the moderation status of one or more comments. The API request must be authorized by the owner of the channel or video associated with the comments.
      operationId: youtube.comments.setModerationStatus
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - comments
  /fanFundingEvents:
    get:
      description: Lists fan funding events for a channel.
      operationId: youtube.fanFundingEvents.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
      tags:
        - fanFundingEvents
  /guideCategories:
    get:
      description: Returns a list of categories that can be associated with YouTube channels.
      operationId: youtube.guideCategories.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - guideCategories
  /i18nLanguages:
    get:
      description: Returns a list of application languages that the YouTube website supports.
      operationId: youtube.i18nLanguages.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - i18nLanguages
  /i18nRegions:
    get:
      description: Returns a list of content regions that the YouTube website supports.
      operationId: youtube.i18nRegions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - i18nRegions
  /liveBroadcasts:
    delete:
      description: Deletes a broadcast.
      operationId: youtube.liveBroadcasts.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - liveBroadcasts
    get:
      description: Returns a list of YouTube broadcasts that match the API request parameters.
      operationId: youtube.liveBroadcasts.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
      tags:
        - liveBroadcasts
    post:
      description: Creates a broadcast.
      operationId: youtube.liveBroadcasts.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - liveBroadcasts
    put:
      description: 'Updates a broadcast. For example, you could modify the broadcast settings defined in the liveBroadcast resource''s contentDetails object.'
      operationId: youtube.liveBroadcasts.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - liveBroadcasts
  /liveBroadcasts/bind:
    post:
      description: 'Binds a YouTube broadcast to a stream or removes an existing binding between a broadcast and a stream. A broadcast can only be bound to one video stream, though a video stream may be bound to more than one broadcast.'
      operationId: youtube.liveBroadcasts.bind
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - liveBroadcasts
  /liveBroadcasts/control:
    post:
      description: Controls the settings for a slate that can be displayed in the broadcast stream.
      operationId: youtube.liveBroadcasts.control
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - liveBroadcasts
  /liveBroadcasts/transition:
    post:
      description: 'Changes the status of a YouTube live broadcast and initiates any processes associated with the new status. For example, when you transition a broadcast''s status to testing, YouTube starts to transmit video to that broadcast''s monitor stream. Before calling this method, you should confirm that the value of the status.streamStatus property for the stream bound to your broadcast is active.'
      operationId: youtube.liveBroadcasts.transition
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - liveBroadcasts
  /liveChat/bans:
    delete:
      description: Removes a chat ban.
      operationId: youtube.liveChatBans.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - liveChatBans
    post:
      description: Adds a new ban to the chat.
      operationId: youtube.liveChatBans.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - liveChatBans
  /liveChat/messages:
    delete:
      description: Deletes a chat message.
      operationId: youtube.liveChatMessages.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - liveChatMessages
    get:
      description: Lists live chat messages for a specific chat.
      operationId: youtube.liveChatMessages.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
      tags:
        - liveChatMessages
    post:
      description: Adds a message to a live chat.
      operationId: youtube.liveChatMessages.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - liveChatMessages
  /liveChat/moderators:
    delete:
      description: Removes a chat moderator.
      operationId: youtube.liveChatModerators.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - liveChatModerators
    get:
      description: Lists moderators for a live chat.
      operationId: youtube.liveChatModerators.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
      tags:
        - liveChatModerators
    post:
      description: Adds a new moderator for the chat.
      operationId: youtube.liveChatModerators.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - liveChatModerators
  /liveStreams:
    delete:
      description: Deletes a video stream.
      operationId: youtube.liveStreams.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - liveStreams
    get:
      description: Returns a list of video streams that match the API request parameters.
      operationId: youtube.liveStreams.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
      tags:
        - liveStreams
    post:
      description: 'Creates a video stream. The stream enables you to send your video to YouTube, which can then broadcast the video to your audience.'
      operationId: youtube.liveStreams.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - liveStreams
    put:
      description: 'Updates a video stream. If the properties that you want to change cannot be updated, then you need to create a new stream with the proper settings.'
      operationId: youtube.liveStreams.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
      tags:
        - liveStreams
  /playlistItems:
    delete:
      description: Deletes a playlist item.
      operationId: youtube.playlistItems.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - playlistItems
    get:
      description: Returns a collection of playlist items that match the API request parameters. You can retrieve all of the playlist items in a specified playlist or retrieve one or more playlist items by their unique IDs.
      operationId: youtube.playlistItems.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - playlistItems
    post:
      description: Adds a resource to a playlist.
      operationId: youtube.playlistItems.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - playlistItems
    put:
      description: 'Modifies a playlist item. For example, you could update the item''s position in the playlist.'
      operationId: youtube.playlistItems.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - playlistItems
  /playlists:
    delete:
      description: Deletes a playlist.
      operationId: youtube.playlists.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - playlists
    get:
      description: 'Returns a collection of playlists that match the API request parameters. For example, you can retrieve all playlists that the authenticated user owns, or you can retrieve one or more playlists by their unique IDs.'
      operationId: youtube.playlists.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - playlists
    post:
      description: Creates a playlist.
      operationId: youtube.playlists.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - playlists
    put:
      description: 'Modifies a playlist. For example, you could change a playlist''s title, description, or privacy status.'
      operationId: youtube.playlists.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - playlists
  /search:
    get:
      description: 'Returns a collection of search results that match the query parameters specified in the API request. By default, a search result set identifies matching video, channel, and playlist resources, but you can also configure queries to only retrieve a specific type of resource.'
      operationId: youtube.search.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - search
  /sponsors:
    get:
      description: Lists sponsors for a channel.
      operationId: youtube.sponsors.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
      tags:
        - sponsors
  /subscriptions:
    delete:
      description: Deletes a subscription.
      operationId: youtube.subscriptions.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - subscriptions
    get:
      description: Returns subscription resources that match the API request criteria.
      operationId: youtube.subscriptions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - subscriptions
    post:
      description: Adds a subscription for the authenticated user's channel.
      operationId: youtube.subscriptions.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - subscriptions
  /superChatEvents:
    get:
      description: Lists Super Chat events for a channel.
      operationId: youtube.superChatEvents.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
      tags:
        - superChatEvents
  /thumbnails/set:
    post:
      description: Uploads a custom video thumbnail to YouTube and sets it for a video.
      operationId: youtube.thumbnails.set
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.upload'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.upload'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - thumbnails
  /videoAbuseReportReasons:
    get:
      description: Returns a list of abuse reasons that can be used for reporting abusive videos.
      operationId: youtube.videoAbuseReportReasons.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
      tags:
        - videoAbuseReportReasons
  /videoCategories:
    get:
      description: Returns a list of categories that can be associated with YouTube videos.
      operationId: youtube.videoCategories.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - videoCategories
  /videos:
    delete:
      description: Deletes a YouTube video.
      operationId: youtube.videos.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - videos
    get:
      description: Returns a list of videos that match the API request parameters.
      operationId: youtube.videos.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - videos
    post:
      description: Uploads a video to YouTube and optionally sets the video's metadata.
      operationId: youtube.videos.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.upload'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.upload'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - videos
    put:
      description: Updates a video's metadata.
      operationId: youtube.videos.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - videos
  /videos/getRating:
    get:
      description: Retrieves the ratings that the authorized user gave to a list of specified videos.
      operationId: youtube.videos.getRating
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - videos
  /videos/rate:
    post:
      description: Add a like or dislike rating to a video or remove a rating from a video.
      operationId: youtube.videos.rate
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - videos
  /videos/reportAbuse:
    post:
      description: Report abuse for a video.
      operationId: youtube.videos.reportAbuse
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - videos
  /watermarks/set:
    post:
      description: Uploads a watermark image to YouTube and sets it for a channel.
      operationId: youtube.watermarks.set
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.upload'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.upload'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - watermarks
  /watermarks/unset:
    post:
      description: Deletes a channel's watermark image.
      operationId: youtube.watermarks.unset
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
        - Oauth2:
            - 'https://www.googleapis.com/auth/youtubepartner'
          Oauth2c:
            - 'https://www.googleapis.com/auth/youtubepartner'
      tags:
        - watermarks