# coding: utf-8

"""
    Google Analytics Admin API

    Manage properties in Google Analytics. Warning: Creating multiple Customer Applications, Accounts, or Projects to simulate or act as a single Customer Application, Account, or Project (respectively) or to circumvent Service-specific usage limits or quotas is a direct violation of Google Cloud Platform Terms of Service as well as Google APIs Terms of Service. These actions can result in immediate termination of your GCP project(s) without any warning.

    The version of the OpenAPI document: v1alpha
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.google_analytics_admin_v1alpha_list_measurement_protocol_secrets_response import GoogleAnalyticsAdminV1alphaListMeasurementProtocolSecretsResponse

class TestGoogleAnalyticsAdminV1alphaListMeasurementProtocolSecretsResponse(unittest.TestCase):
    """GoogleAnalyticsAdminV1alphaListMeasurementProtocolSecretsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GoogleAnalyticsAdminV1alphaListMeasurementProtocolSecretsResponse:
        """Test GoogleAnalyticsAdminV1alphaListMeasurementProtocolSecretsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GoogleAnalyticsAdminV1alphaListMeasurementProtocolSecretsResponse`
        """
        model = GoogleAnalyticsAdminV1alphaListMeasurementProtocolSecretsResponse()
        if include_optional:
            return GoogleAnalyticsAdminV1alphaListMeasurementProtocolSecretsResponse(
                measurement_protocol_secrets = [
                    openapi_client.models.google_analytics_admin_v1alpha_measurement_protocol_secret.GoogleAnalyticsAdminV1alphaMeasurementProtocolSecret(
                        display_name = '', 
                        name = '', 
                        secret_value = '', )
                    ],
                next_page_token = ''
            )
        else:
            return GoogleAnalyticsAdminV1alphaListMeasurementProtocolSecretsResponse(
        )
        """

    def testGoogleAnalyticsAdminV1alphaListMeasurementProtocolSecretsResponse(self):
        """Test GoogleAnalyticsAdminV1alphaListMeasurementProtocolSecretsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
