# coding: utf-8

"""
    NetBox API

    API to access NetBox

    The version of the OpenAPI document: 3.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.cable_termination import CableTermination

class TestCableTermination(unittest.TestCase):
    """CableTermination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CableTermination:
        """Test CableTermination
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CableTermination`
        """
        model = CableTermination()
        if include_optional:
            return CableTermination(
                cable = 56,
                cable_end = 'A',
                display = '',
                id = 56,
                termination = openapi_client.models.termination.Termination(),
                termination_id = 0,
                termination_type = '',
                url = ''
            )
        else:
            return CableTermination(
                cable = 56,
                cable_end = 'A',
                termination_id = 0,
                termination_type = '',
        )
        """

    def testCableTermination(self):
        """Test CableTermination"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
