openapi: 3.0.0
servers:
  - url: https://chromepolicy.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: The Chrome Policy API is a suite of services that allows Chrome administrators to control the policies applied to their managed Chrome OS devices and Chrome browsers.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Chrome Policy API
  version: v1
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_upload.wikimedia.org_wikipedia_commons_e_e1_YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
    - format: google
      url: https://chromepolicy.googleapis.com/$discovery/rest?version=v1
      version: v1
  x-providerName: googleapis.com
  x-serviceName: chromepolicy
tags:
  - name: customers
  - name: media
paths:
  "/v1/{customer}/policies/files:uploadPolicyFile":
    post:
      description: Creates an enterprise file from the content provided by user. Returns a public download url for end user.
      operationId: chromepolicy.media.upload
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.policy
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.policy
      tags:
        - media
  "/v1/{customer}/policies/groups:batchDelete":
    post:
      description: Delete multiple policy values that are applied to a specific group. All targets must have the same target format. That is to say that they must point to the same target resource and must have the same keys specified in `additionalTargetKeyNames`, though the values for those keys may be different. On failure the request will return the error details as part of the google.rpc.Status.
      operationId: chromepolicy.customers.policies.groups.batchDelete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.policy
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.policy
      tags:
        - customers
  "/v1/{customer}/policies/groups:batchModify":
    post:
      description: Modify multiple policy values that are applied to a specific group. All targets must have the same target format. That is to say that they must point to the same target resource and must have the same keys specified in `additionalTargetKeyNames`, though the values for those keys may be different. On failure the request will return the error details as part of the google.rpc.Status.
      operationId: chromepolicy.customers.policies.groups.batchModify
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.policy
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.policy
      tags:
        - customers
  "/v1/{customer}/policies/groups:listGroupPriorityOrdering":
    post:
      description: Retrieve a group priority ordering for an app. The target app must be supplied in `additionalTargetKeyNames` in the PolicyTargetKey. On failure the request will return the error details as part of the google.rpc.Status.
      operationId: chromepolicy.customers.policies.groups.listGroupPriorityOrdering
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.policy
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.policy
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.policy.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.policy.readonly
      tags:
        - customers
  "/v1/{customer}/policies/groups:updateGroupPriorityOrdering":
    post:
      description: Update a group priority ordering for an app. The target app must be supplied in `additionalTargetKeyNames` in the PolicyTargetKey. On failure the request will return the error details as part of the google.rpc.Status.
      operationId: chromepolicy.customers.policies.groups.updateGroupPriorityOrdering
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.policy
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.policy
      tags:
        - customers
  "/v1/{customer}/policies/networks:defineCertificate":
    post:
      description: Creates a certificate at a specified OU for a customer.
      operationId: chromepolicy.customers.policies.networks.defineCertificate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.policy
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.policy
      tags:
        - customers
  "/v1/{customer}/policies/networks:defineNetwork":
    post:
      description: Define a new network.
      operationId: chromepolicy.customers.policies.networks.defineNetwork
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.policy
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.policy
      tags:
        - customers
  "/v1/{customer}/policies/networks:removeCertificate":
    post:
      description: Remove an existing certificate by guid.
      operationId: chromepolicy.customers.policies.networks.removeCertificate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.policy
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.policy
      tags:
        - customers
  "/v1/{customer}/policies/networks:removeNetwork":
    post:
      description: Remove an existing network by guid.
      operationId: chromepolicy.customers.policies.networks.removeNetwork
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.policy
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.policy
      tags:
        - customers
  "/v1/{customer}/policies/orgunits:batchInherit":
    post:
      description: Modify multiple policy values that are applied to a specific org unit so that they now inherit the value from a parent (if applicable). All targets must have the same target format. That is to say that they must point to the same target resource and must have the same keys specified in `additionalTargetKeyNames`, though the values for those keys may be different. On failure the request will return the error details as part of the google.rpc.Status.
      operationId: chromepolicy.customers.policies.orgunits.batchInherit
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.policy
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.policy
      tags:
        - customers
  "/v1/{customer}/policies/orgunits:batchModify":
    post:
      description: Modify multiple policy values that are applied to a specific org unit. All targets must have the same target format. That is to say that they must point to the same target resource and must have the same keys specified in `additionalTargetKeyNames`, though the values for those keys may be different. On failure the request will return the error details as part of the google.rpc.Status.
      operationId: chromepolicy.customers.policies.orgunits.batchModify
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.policy
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.policy
      tags:
        - customers
  "/v1/{customer}/policies:resolve":
    post:
      description: Gets the resolved policy values for a list of policies that match a search query.
      operationId: chromepolicy.customers.policies.resolve
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.policy
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.policy
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.policy.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.policy.readonly
      tags:
        - customers
  "/v1/{name}":
    get:
      description: Get a specific policy schema for a customer by its resource name.
      operationId: chromepolicy.customers.policySchemas.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.policy
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.policy
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.policy.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.policy.readonly
      tags:
        - customers
  "/v1/{parent}/policySchemas":
    get:
      description: Gets a list of policy schemas that match a specified filter value for a given customer.
      operationId: chromepolicy.customers.policySchemas.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.policy
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.policy
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.policy.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.policy.readonly
      tags:
        - customers
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/chrome.management.policy: See, edit, create or delete policies applied to Chrome OS and Chrome Browsers managed within your organization
            https://www.googleapis.com/auth/chrome.management.policy.readonly: See policies applied to Chrome OS and Chrome Browsers managed within your organization
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/chrome.management.policy: See, edit, create or delete policies applied to Chrome OS and Chrome Browsers managed within your organization
            https://www.googleapis.com/auth/chrome.management.policy.readonly: See policies applied to Chrome OS and Chrome Browsers managed within your organization
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
