package shared

type StreamingImageEncryptionConfigurationKeyTypeEnum string

const (
	StreamingImageEncryptionConfigurationKeyTypeEnumCustomerManagedKey StreamingImageEncryptionConfigurationKeyTypeEnum = "CUSTOMER_MANAGED_KEY"
)
