package shared

type PowerPortTemplateTypeLabelEnum string

const (
	PowerPortTemplateTypeLabelEnumC6                 PowerPortTemplateTypeLabelEnum = "C6"
	PowerPortTemplateTypeLabelEnumC8                 PowerPortTemplateTypeLabelEnum = "C8"
	PowerPortTemplateTypeLabelEnumC14                PowerPortTemplateTypeLabelEnum = "C14"
	PowerPortTemplateTypeLabelEnumC16                PowerPortTemplateTypeLabelEnum = "C16"
	PowerPortTemplateTypeLabelEnumC20                PowerPortTemplateTypeLabelEnum = "C20"
	PowerPortTemplateTypeLabelEnumPPlusNPlusE4H      PowerPortTemplateTypeLabelEnum = "P+N+E 4H"
	PowerPortTemplateTypeLabelEnumPPlusNPlusE6H      PowerPortTemplateTypeLabelEnum = "P+N+E 6H"
	PowerPortTemplateTypeLabelEnumPPlusNPlusE9H      PowerPortTemplateTypeLabelEnum = "P+N+E 9H"
	PowerPortTemplateTypeLabelEnumTwoPPlusE4H        PowerPortTemplateTypeLabelEnum = "2P+E 4H"
	PowerPortTemplateTypeLabelEnumTwoPPlusE6H        PowerPortTemplateTypeLabelEnum = "2P+E 6H"
	PowerPortTemplateTypeLabelEnumTwoPPlusE9H        PowerPortTemplateTypeLabelEnum = "2P+E 9H"
	PowerPortTemplateTypeLabelEnumThreePPlusE4H      PowerPortTemplateTypeLabelEnum = "3P+E 4H"
	PowerPortTemplateTypeLabelEnumThreePPlusE6H      PowerPortTemplateTypeLabelEnum = "3P+E 6H"
	PowerPortTemplateTypeLabelEnumThreePPlusE9H      PowerPortTemplateTypeLabelEnum = "3P+E 9H"
	PowerPortTemplateTypeLabelEnumThreePPlusNPlusE4H PowerPortTemplateTypeLabelEnum = "3P+N+E 4H"
	PowerPortTemplateTypeLabelEnumThreePPlusNPlusE6H PowerPortTemplateTypeLabelEnum = "3P+N+E 6H"
	PowerPortTemplateTypeLabelEnumThreePPlusNPlusE9H PowerPortTemplateTypeLabelEnum = "3P+N+E 9H"
	PowerPortTemplateTypeLabelEnumNema115P           PowerPortTemplateTypeLabelEnum = "NEMA 1-15P"
	PowerPortTemplateTypeLabelEnumNema515P           PowerPortTemplateTypeLabelEnum = "NEMA 5-15P"
	PowerPortTemplateTypeLabelEnumNema520P           PowerPortTemplateTypeLabelEnum = "NEMA 5-20P"
	PowerPortTemplateTypeLabelEnumNema530P           PowerPortTemplateTypeLabelEnum = "NEMA 5-30P"
	PowerPortTemplateTypeLabelEnumNema550P           PowerPortTemplateTypeLabelEnum = "NEMA 5-50P"
	PowerPortTemplateTypeLabelEnumNema615P           PowerPortTemplateTypeLabelEnum = "NEMA 6-15P"
	PowerPortTemplateTypeLabelEnumNema620P           PowerPortTemplateTypeLabelEnum = "NEMA 6-20P"
	PowerPortTemplateTypeLabelEnumNema630P           PowerPortTemplateTypeLabelEnum = "NEMA 6-30P"
	PowerPortTemplateTypeLabelEnumNema650P           PowerPortTemplateTypeLabelEnum = "NEMA 6-50P"
	PowerPortTemplateTypeLabelEnumNema1030P          PowerPortTemplateTypeLabelEnum = "NEMA 10-30P"
	PowerPortTemplateTypeLabelEnumNema1050P          PowerPortTemplateTypeLabelEnum = "NEMA 10-50P"
	PowerPortTemplateTypeLabelEnumNema1420P          PowerPortTemplateTypeLabelEnum = "NEMA 14-20P"
	PowerPortTemplateTypeLabelEnumNema1430P          PowerPortTemplateTypeLabelEnum = "NEMA 14-30P"
	PowerPortTemplateTypeLabelEnumNema1450P          PowerPortTemplateTypeLabelEnum = "NEMA 14-50P"
	PowerPortTemplateTypeLabelEnumNema1460P          PowerPortTemplateTypeLabelEnum = "NEMA 14-60P"
	PowerPortTemplateTypeLabelEnumNemaL115P          PowerPortTemplateTypeLabelEnum = "NEMA L1-15P"
	PowerPortTemplateTypeLabelEnumNemaL515P          PowerPortTemplateTypeLabelEnum = "NEMA L5-15P"
	PowerPortTemplateTypeLabelEnumNemaL520P          PowerPortTemplateTypeLabelEnum = "NEMA L5-20P"
	PowerPortTemplateTypeLabelEnumNemaL530P          PowerPortTemplateTypeLabelEnum = "NEMA L5-30P"
	PowerPortTemplateTypeLabelEnumNemaL550P          PowerPortTemplateTypeLabelEnum = "NEMA L5-50P"
	PowerPortTemplateTypeLabelEnumNemaL615P          PowerPortTemplateTypeLabelEnum = "NEMA L6-15P"
	PowerPortTemplateTypeLabelEnumNemaL620P          PowerPortTemplateTypeLabelEnum = "NEMA L6-20P"
	PowerPortTemplateTypeLabelEnumNemaL630P          PowerPortTemplateTypeLabelEnum = "NEMA L6-30P"
	PowerPortTemplateTypeLabelEnumNemaL650P          PowerPortTemplateTypeLabelEnum = "NEMA L6-50P"
	PowerPortTemplateTypeLabelEnumNemaL1030P         PowerPortTemplateTypeLabelEnum = "NEMA L10-30P"
	PowerPortTemplateTypeLabelEnumNemaL1420P         PowerPortTemplateTypeLabelEnum = "NEMA L14-20P"
	PowerPortTemplateTypeLabelEnumNemaL1430P         PowerPortTemplateTypeLabelEnum = "NEMA L14-30P"
	PowerPortTemplateTypeLabelEnumNemaL1450P         PowerPortTemplateTypeLabelEnum = "NEMA L14-50P"
	PowerPortTemplateTypeLabelEnumNemaL1460P         PowerPortTemplateTypeLabelEnum = "NEMA L14-60P"
	PowerPortTemplateTypeLabelEnumNemaL2120P         PowerPortTemplateTypeLabelEnum = "NEMA L21-20P"
	PowerPortTemplateTypeLabelEnumNemaL2130P         PowerPortTemplateTypeLabelEnum = "NEMA L21-30P"
	PowerPortTemplateTypeLabelEnumCs6361C            PowerPortTemplateTypeLabelEnum = "CS6361C"
	PowerPortTemplateTypeLabelEnumCs6365C            PowerPortTemplateTypeLabelEnum = "CS6365C"
	PowerPortTemplateTypeLabelEnumCs8165C            PowerPortTemplateTypeLabelEnum = "CS8165C"
	PowerPortTemplateTypeLabelEnumCs8265C            PowerPortTemplateTypeLabelEnum = "CS8265C"
	PowerPortTemplateTypeLabelEnumCs8365C            PowerPortTemplateTypeLabelEnum = "CS8365C"
	PowerPortTemplateTypeLabelEnumCs8465C            PowerPortTemplateTypeLabelEnum = "CS8465C"
	PowerPortTemplateTypeLabelEnumItaTypeECee75      PowerPortTemplateTypeLabelEnum = "ITA Type E (CEE 7/5)"
	PowerPortTemplateTypeLabelEnumItaTypeFCee74      PowerPortTemplateTypeLabelEnum = "ITA Type F (CEE 7/4)"
	PowerPortTemplateTypeLabelEnumItaTypeEfCee77     PowerPortTemplateTypeLabelEnum = "ITA Type E/F (CEE 7/7)"
	PowerPortTemplateTypeLabelEnumItaTypeGBs1363     PowerPortTemplateTypeLabelEnum = "ITA Type G (BS 1363)"
	PowerPortTemplateTypeLabelEnumItaTypeH           PowerPortTemplateTypeLabelEnum = "ITA Type H"
	PowerPortTemplateTypeLabelEnumItaTypeI           PowerPortTemplateTypeLabelEnum = "ITA Type I"
	PowerPortTemplateTypeLabelEnumItaTypeJ           PowerPortTemplateTypeLabelEnum = "ITA Type J"
	PowerPortTemplateTypeLabelEnumItaTypeK           PowerPortTemplateTypeLabelEnum = "ITA Type K"
	PowerPortTemplateTypeLabelEnumItaTypeLCei2350    PowerPortTemplateTypeLabelEnum = "ITA Type L (CEI 23-50)"
	PowerPortTemplateTypeLabelEnumItaTypeMBs546      PowerPortTemplateTypeLabelEnum = "ITA Type M (BS 546)"
	PowerPortTemplateTypeLabelEnumItaTypeN           PowerPortTemplateTypeLabelEnum = "ITA Type N"
	PowerPortTemplateTypeLabelEnumItaTypeO           PowerPortTemplateTypeLabelEnum = "ITA Type O"
)

type PowerPortTemplateTypeValueEnum string

const (
	PowerPortTemplateTypeValueEnumIec60320C6     PowerPortTemplateTypeValueEnum = "iec-60320-c6"
	PowerPortTemplateTypeValueEnumIec60320C8     PowerPortTemplateTypeValueEnum = "iec-60320-c8"
	PowerPortTemplateTypeValueEnumIec60320C14    PowerPortTemplateTypeValueEnum = "iec-60320-c14"
	PowerPortTemplateTypeValueEnumIec60320C16    PowerPortTemplateTypeValueEnum = "iec-60320-c16"
	PowerPortTemplateTypeValueEnumIec60320C20    PowerPortTemplateTypeValueEnum = "iec-60320-c20"
	PowerPortTemplateTypeValueEnumIec60309Pne4h  PowerPortTemplateTypeValueEnum = "iec-60309-p-n-e-4h"
	PowerPortTemplateTypeValueEnumIec60309Pne6h  PowerPortTemplateTypeValueEnum = "iec-60309-p-n-e-6h"
	PowerPortTemplateTypeValueEnumIec60309Pne9h  PowerPortTemplateTypeValueEnum = "iec-60309-p-n-e-9h"
	PowerPortTemplateTypeValueEnumIec603092pE4h  PowerPortTemplateTypeValueEnum = "iec-60309-2p-e-4h"
	PowerPortTemplateTypeValueEnumIec603092pE6h  PowerPortTemplateTypeValueEnum = "iec-60309-2p-e-6h"
	PowerPortTemplateTypeValueEnumIec603092pE9h  PowerPortTemplateTypeValueEnum = "iec-60309-2p-e-9h"
	PowerPortTemplateTypeValueEnumIec603093pE4h  PowerPortTemplateTypeValueEnum = "iec-60309-3p-e-4h"
	PowerPortTemplateTypeValueEnumIec603093pE6h  PowerPortTemplateTypeValueEnum = "iec-60309-3p-e-6h"
	PowerPortTemplateTypeValueEnumIec603093pE9h  PowerPortTemplateTypeValueEnum = "iec-60309-3p-e-9h"
	PowerPortTemplateTypeValueEnumIec603093pNe4h PowerPortTemplateTypeValueEnum = "iec-60309-3p-n-e-4h"
	PowerPortTemplateTypeValueEnumIec603093pNe6h PowerPortTemplateTypeValueEnum = "iec-60309-3p-n-e-6h"
	PowerPortTemplateTypeValueEnumIec603093pNe9h PowerPortTemplateTypeValueEnum = "iec-60309-3p-n-e-9h"
	PowerPortTemplateTypeValueEnumNema115p       PowerPortTemplateTypeValueEnum = "nema-1-15p"
	PowerPortTemplateTypeValueEnumNema515p       PowerPortTemplateTypeValueEnum = "nema-5-15p"
	PowerPortTemplateTypeValueEnumNema520p       PowerPortTemplateTypeValueEnum = "nema-5-20p"
	PowerPortTemplateTypeValueEnumNema530p       PowerPortTemplateTypeValueEnum = "nema-5-30p"
	PowerPortTemplateTypeValueEnumNema550p       PowerPortTemplateTypeValueEnum = "nema-5-50p"
	PowerPortTemplateTypeValueEnumNema615p       PowerPortTemplateTypeValueEnum = "nema-6-15p"
	PowerPortTemplateTypeValueEnumNema620p       PowerPortTemplateTypeValueEnum = "nema-6-20p"
	PowerPortTemplateTypeValueEnumNema630p       PowerPortTemplateTypeValueEnum = "nema-6-30p"
	PowerPortTemplateTypeValueEnumNema650p       PowerPortTemplateTypeValueEnum = "nema-6-50p"
	PowerPortTemplateTypeValueEnumNema1030p      PowerPortTemplateTypeValueEnum = "nema-10-30p"
	PowerPortTemplateTypeValueEnumNema1050p      PowerPortTemplateTypeValueEnum = "nema-10-50p"
	PowerPortTemplateTypeValueEnumNema1420p      PowerPortTemplateTypeValueEnum = "nema-14-20p"
	PowerPortTemplateTypeValueEnumNema1430p      PowerPortTemplateTypeValueEnum = "nema-14-30p"
	PowerPortTemplateTypeValueEnumNema1450p      PowerPortTemplateTypeValueEnum = "nema-14-50p"
	PowerPortTemplateTypeValueEnumNema1460p      PowerPortTemplateTypeValueEnum = "nema-14-60p"
	PowerPortTemplateTypeValueEnumNemaL115p      PowerPortTemplateTypeValueEnum = "nema-l1-15p"
	PowerPortTemplateTypeValueEnumNemaL515p      PowerPortTemplateTypeValueEnum = "nema-l5-15p"
	PowerPortTemplateTypeValueEnumNemaL520p      PowerPortTemplateTypeValueEnum = "nema-l5-20p"
	PowerPortTemplateTypeValueEnumNemaL530p      PowerPortTemplateTypeValueEnum = "nema-l5-30p"
	PowerPortTemplateTypeValueEnumNemaL550p      PowerPortTemplateTypeValueEnum = "nema-l5-50p"
	PowerPortTemplateTypeValueEnumNemaL615p      PowerPortTemplateTypeValueEnum = "nema-l6-15p"
	PowerPortTemplateTypeValueEnumNemaL620p      PowerPortTemplateTypeValueEnum = "nema-l6-20p"
	PowerPortTemplateTypeValueEnumNemaL630p      PowerPortTemplateTypeValueEnum = "nema-l6-30p"
	PowerPortTemplateTypeValueEnumNemaL650p      PowerPortTemplateTypeValueEnum = "nema-l6-50p"
	PowerPortTemplateTypeValueEnumNemaL1030p     PowerPortTemplateTypeValueEnum = "nema-l10-30p"
	PowerPortTemplateTypeValueEnumNemaL1420p     PowerPortTemplateTypeValueEnum = "nema-l14-20p"
	PowerPortTemplateTypeValueEnumNemaL1430p     PowerPortTemplateTypeValueEnum = "nema-l14-30p"
	PowerPortTemplateTypeValueEnumNemaL1450p     PowerPortTemplateTypeValueEnum = "nema-l14-50p"
	PowerPortTemplateTypeValueEnumNemaL1460p     PowerPortTemplateTypeValueEnum = "nema-l14-60p"
	PowerPortTemplateTypeValueEnumNemaL2120p     PowerPortTemplateTypeValueEnum = "nema-l21-20p"
	PowerPortTemplateTypeValueEnumNemaL2130p     PowerPortTemplateTypeValueEnum = "nema-l21-30p"
	PowerPortTemplateTypeValueEnumCs6361c        PowerPortTemplateTypeValueEnum = "cs6361c"
	PowerPortTemplateTypeValueEnumCs6365c        PowerPortTemplateTypeValueEnum = "cs6365c"
	PowerPortTemplateTypeValueEnumCs8165c        PowerPortTemplateTypeValueEnum = "cs8165c"
	PowerPortTemplateTypeValueEnumCs8265c        PowerPortTemplateTypeValueEnum = "cs8265c"
	PowerPortTemplateTypeValueEnumCs8365c        PowerPortTemplateTypeValueEnum = "cs8365c"
	PowerPortTemplateTypeValueEnumCs8465c        PowerPortTemplateTypeValueEnum = "cs8465c"
	PowerPortTemplateTypeValueEnumItaE           PowerPortTemplateTypeValueEnum = "ita-e"
	PowerPortTemplateTypeValueEnumItaF           PowerPortTemplateTypeValueEnum = "ita-f"
	PowerPortTemplateTypeValueEnumItaEf          PowerPortTemplateTypeValueEnum = "ita-ef"
	PowerPortTemplateTypeValueEnumItaG           PowerPortTemplateTypeValueEnum = "ita-g"
	PowerPortTemplateTypeValueEnumItaH           PowerPortTemplateTypeValueEnum = "ita-h"
	PowerPortTemplateTypeValueEnumItaI           PowerPortTemplateTypeValueEnum = "ita-i"
	PowerPortTemplateTypeValueEnumItaJ           PowerPortTemplateTypeValueEnum = "ita-j"
	PowerPortTemplateTypeValueEnumItaK           PowerPortTemplateTypeValueEnum = "ita-k"
	PowerPortTemplateTypeValueEnumItaL           PowerPortTemplateTypeValueEnum = "ita-l"
	PowerPortTemplateTypeValueEnumItaM           PowerPortTemplateTypeValueEnum = "ita-m"
	PowerPortTemplateTypeValueEnumItaN           PowerPortTemplateTypeValueEnum = "ita-n"
	PowerPortTemplateTypeValueEnumItaO           PowerPortTemplateTypeValueEnum = "ita-o"
)

type PowerPortTemplateType struct {
	Label PowerPortTemplateTypeLabelEnum `json:"label"`
	Value PowerPortTemplateTypeValueEnum `json:"value"`
}

type PowerPortTemplate struct {
	AllocatedDraw *int64                 `json:"allocated_draw,omitempty"`
	DeviceType    NestedDeviceType       `json:"device_type"`
	ID            *int64                 `json:"id,omitempty"`
	MaximumDraw   *int64                 `json:"maximum_draw,omitempty"`
	Name          string                 `json:"name"`
	Type          *PowerPortTemplateType `json:"type,omitempty"`
}
