package shared




type WritableInterfaceTemplateTypeEnum string

const (
    WritableInterfaceTemplateTypeEnumVirtual WritableInterfaceTemplateTypeEnum = "virtual"
WritableInterfaceTemplateTypeEnumLag WritableInterfaceTemplateTypeEnum = "lag"
WritableInterfaceTemplateTypeEnumOneHundredbaseTx WritableInterfaceTemplateTypeEnum = "100base-tx"
WritableInterfaceTemplateTypeEnumOneThousandbaseT WritableInterfaceTemplateTypeEnum = "1000base-t"
WritableInterfaceTemplateTypeEnumTwo5gbaseT WritableInterfaceTemplateTypeEnum = "2.5gbase-t"
WritableInterfaceTemplateTypeEnumFivegbaseT WritableInterfaceTemplateTypeEnum = "5gbase-t"
WritableInterfaceTemplateTypeEnumTengbaseT WritableInterfaceTemplateTypeEnum = "10gbase-t"
WritableInterfaceTemplateTypeEnumTengbaseCx4 WritableInterfaceTemplateTypeEnum = "10gbase-cx4"
WritableInterfaceTemplateTypeEnumOneThousandbaseXGbic WritableInterfaceTemplateTypeEnum = "1000base-x-gbic"
WritableInterfaceTemplateTypeEnumOneThousandbaseXSfp WritableInterfaceTemplateTypeEnum = "1000base-x-sfp"
WritableInterfaceTemplateTypeEnumTengbaseXSfpp WritableInterfaceTemplateTypeEnum = "10gbase-x-sfpp"
WritableInterfaceTemplateTypeEnumTengbaseXXfp WritableInterfaceTemplateTypeEnum = "10gbase-x-xfp"
WritableInterfaceTemplateTypeEnumTengbaseXXenpak WritableInterfaceTemplateTypeEnum = "10gbase-x-xenpak"
WritableInterfaceTemplateTypeEnumTengbaseXx2 WritableInterfaceTemplateTypeEnum = "10gbase-x-x2"
WritableInterfaceTemplateTypeEnumTwentyFivegbaseXSfp28 WritableInterfaceTemplateTypeEnum = "25gbase-x-sfp28"
WritableInterfaceTemplateTypeEnumFortygbaseXQsfpp WritableInterfaceTemplateTypeEnum = "40gbase-x-qsfpp"
WritableInterfaceTemplateTypeEnumFiftygbaseXSfp28 WritableInterfaceTemplateTypeEnum = "50gbase-x-sfp28"
WritableInterfaceTemplateTypeEnumOneHundredgbaseXCfp WritableInterfaceTemplateTypeEnum = "100gbase-x-cfp"
WritableInterfaceTemplateTypeEnumOneHundredgbaseXCfp2 WritableInterfaceTemplateTypeEnum = "100gbase-x-cfp2"
WritableInterfaceTemplateTypeEnumTwoHundredgbaseXCfp2 WritableInterfaceTemplateTypeEnum = "200gbase-x-cfp2"
WritableInterfaceTemplateTypeEnumOneHundredgbaseXCfp4 WritableInterfaceTemplateTypeEnum = "100gbase-x-cfp4"
WritableInterfaceTemplateTypeEnumOneHundredgbaseXCpak WritableInterfaceTemplateTypeEnum = "100gbase-x-cpak"
WritableInterfaceTemplateTypeEnumOneHundredgbaseXQsfp28 WritableInterfaceTemplateTypeEnum = "100gbase-x-qsfp28"
WritableInterfaceTemplateTypeEnumTwoHundredgbaseXQsfp56 WritableInterfaceTemplateTypeEnum = "200gbase-x-qsfp56"
WritableInterfaceTemplateTypeEnumFourHundredgbaseXQsfpdd WritableInterfaceTemplateTypeEnum = "400gbase-x-qsfpdd"
WritableInterfaceTemplateTypeEnumFourHundredgbaseXOsfp WritableInterfaceTemplateTypeEnum = "400gbase-x-osfp"
WritableInterfaceTemplateTypeEnumIeee80211a WritableInterfaceTemplateTypeEnum = "ieee802.11a"
WritableInterfaceTemplateTypeEnumIeee80211g WritableInterfaceTemplateTypeEnum = "ieee802.11g"
WritableInterfaceTemplateTypeEnumIeee80211n WritableInterfaceTemplateTypeEnum = "ieee802.11n"
WritableInterfaceTemplateTypeEnumIeee80211ac WritableInterfaceTemplateTypeEnum = "ieee802.11ac"
WritableInterfaceTemplateTypeEnumIeee80211ad WritableInterfaceTemplateTypeEnum = "ieee802.11ad"
WritableInterfaceTemplateTypeEnumIeee80211ax WritableInterfaceTemplateTypeEnum = "ieee802.11ax"
WritableInterfaceTemplateTypeEnumGsm WritableInterfaceTemplateTypeEnum = "gsm"
WritableInterfaceTemplateTypeEnumCdma WritableInterfaceTemplateTypeEnum = "cdma"
WritableInterfaceTemplateTypeEnumLte WritableInterfaceTemplateTypeEnum = "lte"
WritableInterfaceTemplateTypeEnumSonetOc3 WritableInterfaceTemplateTypeEnum = "sonet-oc3"
WritableInterfaceTemplateTypeEnumSonetOc12 WritableInterfaceTemplateTypeEnum = "sonet-oc12"
WritableInterfaceTemplateTypeEnumSonetOc48 WritableInterfaceTemplateTypeEnum = "sonet-oc48"
WritableInterfaceTemplateTypeEnumSonetOc192 WritableInterfaceTemplateTypeEnum = "sonet-oc192"
WritableInterfaceTemplateTypeEnumSonetOc768 WritableInterfaceTemplateTypeEnum = "sonet-oc768"
WritableInterfaceTemplateTypeEnumSonetOc1920 WritableInterfaceTemplateTypeEnum = "sonet-oc1920"
WritableInterfaceTemplateTypeEnumSonetOc3840 WritableInterfaceTemplateTypeEnum = "sonet-oc3840"
WritableInterfaceTemplateTypeEnumOnegfcSfp WritableInterfaceTemplateTypeEnum = "1gfc-sfp"
WritableInterfaceTemplateTypeEnumTwogfcSfp WritableInterfaceTemplateTypeEnum = "2gfc-sfp"
WritableInterfaceTemplateTypeEnumFourgfcSfp WritableInterfaceTemplateTypeEnum = "4gfc-sfp"
WritableInterfaceTemplateTypeEnumEightgfcSfpp WritableInterfaceTemplateTypeEnum = "8gfc-sfpp"
WritableInterfaceTemplateTypeEnumSixteengfcSfpp WritableInterfaceTemplateTypeEnum = "16gfc-sfpp"
WritableInterfaceTemplateTypeEnumThirtyTwogfcSfp28 WritableInterfaceTemplateTypeEnum = "32gfc-sfp28"
WritableInterfaceTemplateTypeEnumOneHundredAndTwentyEightgfcSfp28 WritableInterfaceTemplateTypeEnum = "128gfc-sfp28"
WritableInterfaceTemplateTypeEnumInfinibandSdr WritableInterfaceTemplateTypeEnum = "infiniband-sdr"
WritableInterfaceTemplateTypeEnumInfinibandDdr WritableInterfaceTemplateTypeEnum = "infiniband-ddr"
WritableInterfaceTemplateTypeEnumInfinibandQdr WritableInterfaceTemplateTypeEnum = "infiniband-qdr"
WritableInterfaceTemplateTypeEnumInfinibandFdr10 WritableInterfaceTemplateTypeEnum = "infiniband-fdr10"
WritableInterfaceTemplateTypeEnumInfinibandFdr WritableInterfaceTemplateTypeEnum = "infiniband-fdr"
WritableInterfaceTemplateTypeEnumInfinibandEdr WritableInterfaceTemplateTypeEnum = "infiniband-edr"
WritableInterfaceTemplateTypeEnumInfinibandHdr WritableInterfaceTemplateTypeEnum = "infiniband-hdr"
WritableInterfaceTemplateTypeEnumInfinibandNdr WritableInterfaceTemplateTypeEnum = "infiniband-ndr"
WritableInterfaceTemplateTypeEnumInfinibandXdr WritableInterfaceTemplateTypeEnum = "infiniband-xdr"
WritableInterfaceTemplateTypeEnumT1 WritableInterfaceTemplateTypeEnum = "t1"
WritableInterfaceTemplateTypeEnumE1 WritableInterfaceTemplateTypeEnum = "e1"
WritableInterfaceTemplateTypeEnumT3 WritableInterfaceTemplateTypeEnum = "t3"
WritableInterfaceTemplateTypeEnumE3 WritableInterfaceTemplateTypeEnum = "e3"
WritableInterfaceTemplateTypeEnumCiscoStackwise WritableInterfaceTemplateTypeEnum = "cisco-stackwise"
WritableInterfaceTemplateTypeEnumCiscoStackwisePlus WritableInterfaceTemplateTypeEnum = "cisco-stackwise-plus"
WritableInterfaceTemplateTypeEnumCiscoFlexstack WritableInterfaceTemplateTypeEnum = "cisco-flexstack"
WritableInterfaceTemplateTypeEnumCiscoFlexstackPlus WritableInterfaceTemplateTypeEnum = "cisco-flexstack-plus"
WritableInterfaceTemplateTypeEnumJuniperVcp WritableInterfaceTemplateTypeEnum = "juniper-vcp"
WritableInterfaceTemplateTypeEnumExtremeSummitstack WritableInterfaceTemplateTypeEnum = "extreme-summitstack"
WritableInterfaceTemplateTypeEnumExtremeSummitstack128 WritableInterfaceTemplateTypeEnum = "extreme-summitstack-128"
WritableInterfaceTemplateTypeEnumExtremeSummitstack256 WritableInterfaceTemplateTypeEnum = "extreme-summitstack-256"
WritableInterfaceTemplateTypeEnumExtremeSummitstack512 WritableInterfaceTemplateTypeEnum = "extreme-summitstack-512"
WritableInterfaceTemplateTypeEnumOther WritableInterfaceTemplateTypeEnum = "other"
)


type WritableInterfaceTemplate struct {
    DeviceType int64 `json:"device_type"`
    ID *int64 `json:"id,omitempty"`
    MgmtOnly *bool `json:"mgmt_only,omitempty"`
    Name string `json:"name"`
    Type WritableInterfaceTemplateTypeEnum `json:"type"`
    
}

