# coding: utf-8

"""
    PayRun.IO

    Open, scableable, transparent payroll API.

    The version of the OpenAPI document: 23.24.2.136
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.rti_api import RTIApi


class TestRTIApi(unittest.TestCase):
    """RTIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RTIApi()

    def tearDown(self) -> None:
        pass

    def test_delete_rti_transaction(self) -> None:
        """Test case for delete_rti_transaction

        Delete the RTI transaction
        """
        pass

    def test_get_all_rti_transaction_tags_0(self) -> None:
        """Test case for get_all_rti_transaction_tags_0

        Get all RTI transaction tags
        """
        pass

    def test_get_rti_transaction_from_employer(self) -> None:
        """Test case for get_rti_transaction_from_employer

        Get the RTI transaction
        """
        pass

    def test_get_rti_transaction_summaries_from_employer(self) -> None:
        """Test case for get_rti_transaction_summaries_from_employer

        Get all RTI transaction summaries for the employer
        """
        pass

    def test_get_rti_transaction_summary_from_employer(self) -> None:
        """Test case for get_rti_transaction_summary_from_employer

        Get the RTI transaction summary
        """
        pass

    def test_get_rti_transactions_from_employer(self) -> None:
        """Test case for get_rti_transactions_from_employer

        Get all RTI transactions for the employer
        """
        pass

    def test_get_rti_transactions_with_tag_0(self) -> None:
        """Test case for get_rti_transactions_with_tag_0

        Get RTI transactions with tag
        """
        pass


if __name__ == '__main__':
    unittest.main()
