# coding: utf-8

"""
    PayRun.IO

    Open, scableable, transparent payroll API.

    The version of the OpenAPI document: 23.24.2.136
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.reporting_instruction1 import ReportingInstruction1

class TestReportingInstruction1(unittest.TestCase):
    """ReportingInstruction1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReportingInstruction1:
        """Test ReportingInstruction1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReportingInstruction1`
        """
        model = ReportingInstruction1()
        if include_optional:
            return ReportingInstruction1(
                end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                tax_month = 56,
                tax_year = 56,
                value = 1.337
            )
        else:
            return ReportingInstruction1(
        )
        """

    def testReportingInstruction1(self):
        """Test ReportingInstruction1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
