import { SpeakeasyMetadata, SpeakeasyBase } from "../../../internal/utils";
import { PageElementProperties } from "./pageelementproperties";


export enum CreateShapeRequestShapeTypeEnum {
    TypeUnspecified = "TYPE_UNSPECIFIED",
    TextBox = "TEXT_BOX",
    Rectangle = "RECTANGLE",
    RoundRectangle = "ROUND_RECTANGLE",
    Ellipse = "ELLIPSE",
    Arc = "ARC",
    BentArrow = "BENT_ARROW",
    BentUpArrow = "BENT_UP_ARROW",
    Bevel = "BEVEL",
    BlockArc = "BLOCK_ARC",
    BracePair = "BRACE_PAIR",
    BracketPair = "BRACKET_PAIR",
    Can = "CAN",
    Chevron = "CHEVRON",
    Chord = "CHORD",
    Cloud = "CLOUD",
    Corner = "CORNER",
    Cube = "CUBE",
    CurvedDownArrow = "CURVED_DOWN_ARROW",
    CurvedLeftArrow = "CURVED_LEFT_ARROW",
    CurvedRightArrow = "CURVED_RIGHT_ARROW",
    CurvedUpArrow = "CURVED_UP_ARROW",
    Decagon = "DECAGON",
    DiagonalStripe = "DIAGONAL_STRIPE",
    Diamond = "DIAMOND",
    Dodecagon = "DODECAGON",
    Donut = "DONUT",
    DoubleWave = "DOUBLE_WAVE",
    DownArrow = "DOWN_ARROW",
    DownArrowCallout = "DOWN_ARROW_CALLOUT",
    FoldedCorner = "FOLDED_CORNER",
    Frame = "FRAME",
    HalfFrame = "HALF_FRAME",
    Heart = "HEART",
    Heptagon = "HEPTAGON",
    Hexagon = "HEXAGON",
    HomePlate = "HOME_PLATE",
    HorizontalScroll = "HORIZONTAL_SCROLL",
    IrregularSeal1 = "IRREGULAR_SEAL_1",
    IrregularSeal2 = "IRREGULAR_SEAL_2",
    LeftArrow = "LEFT_ARROW",
    LeftArrowCallout = "LEFT_ARROW_CALLOUT",
    LeftBrace = "LEFT_BRACE",
    LeftBracket = "LEFT_BRACKET",
    LeftRightArrow = "LEFT_RIGHT_ARROW",
    LeftRightArrowCallout = "LEFT_RIGHT_ARROW_CALLOUT",
    LeftRightUpArrow = "LEFT_RIGHT_UP_ARROW",
    LeftUpArrow = "LEFT_UP_ARROW",
    LightningBolt = "LIGHTNING_BOLT",
    MathDivide = "MATH_DIVIDE",
    MathEqual = "MATH_EQUAL",
    MathMinus = "MATH_MINUS",
    MathMultiply = "MATH_MULTIPLY",
    MathNotEqual = "MATH_NOT_EQUAL",
    MathPlus = "MATH_PLUS",
    Moon = "MOON",
    NoSmoking = "NO_SMOKING",
    NotchedRightArrow = "NOTCHED_RIGHT_ARROW",
    Octagon = "OCTAGON",
    Parallelogram = "PARALLELOGRAM",
    Pentagon = "PENTAGON",
    Pie = "PIE",
    Plaque = "PLAQUE",
    Plus = "PLUS",
    QuadArrow = "QUAD_ARROW",
    QuadArrowCallout = "QUAD_ARROW_CALLOUT",
    Ribbon = "RIBBON",
    Ribbon2 = "RIBBON_2",
    RightArrow = "RIGHT_ARROW",
    RightArrowCallout = "RIGHT_ARROW_CALLOUT",
    RightBrace = "RIGHT_BRACE",
    RightBracket = "RIGHT_BRACKET",
    Round1Rectangle = "ROUND_1_RECTANGLE",
    Round2DiagonalRectangle = "ROUND_2_DIAGONAL_RECTANGLE",
    Round2SameRectangle = "ROUND_2_SAME_RECTANGLE",
    RightTriangle = "RIGHT_TRIANGLE",
    SmileyFace = "SMILEY_FACE",
    Snip1Rectangle = "SNIP_1_RECTANGLE",
    Snip2DiagonalRectangle = "SNIP_2_DIAGONAL_RECTANGLE",
    Snip2SameRectangle = "SNIP_2_SAME_RECTANGLE",
    SnipRoundRectangle = "SNIP_ROUND_RECTANGLE",
    Star10 = "STAR_10",
    Star12 = "STAR_12",
    Star16 = "STAR_16",
    Star24 = "STAR_24",
    Star32 = "STAR_32",
    Star4 = "STAR_4",
    Star5 = "STAR_5",
    Star6 = "STAR_6",
    Star7 = "STAR_7",
    Star8 = "STAR_8",
    StripedRightArrow = "STRIPED_RIGHT_ARROW",
    Sun = "SUN",
    Trapezoid = "TRAPEZOID",
    Triangle = "TRIANGLE",
    UpArrow = "UP_ARROW",
    UpArrowCallout = "UP_ARROW_CALLOUT",
    UpDownArrow = "UP_DOWN_ARROW",
    UturnArrow = "UTURN_ARROW",
    VerticalScroll = "VERTICAL_SCROLL",
    Wave = "WAVE",
    WedgeEllipseCallout = "WEDGE_ELLIPSE_CALLOUT",
    WedgeRectangleCallout = "WEDGE_RECTANGLE_CALLOUT",
    WedgeRoundRectangleCallout = "WEDGE_ROUND_RECTANGLE_CALLOUT",
    FlowChartAlternateProcess = "FLOW_CHART_ALTERNATE_PROCESS",
    FlowChartCollate = "FLOW_CHART_COLLATE",
    FlowChartConnector = "FLOW_CHART_CONNECTOR",
    FlowChartDecision = "FLOW_CHART_DECISION",
    FlowChartDelay = "FLOW_CHART_DELAY",
    FlowChartDisplay = "FLOW_CHART_DISPLAY",
    FlowChartDocument = "FLOW_CHART_DOCUMENT",
    FlowChartExtract = "FLOW_CHART_EXTRACT",
    FlowChartInputOutput = "FLOW_CHART_INPUT_OUTPUT",
    FlowChartInternalStorage = "FLOW_CHART_INTERNAL_STORAGE",
    FlowChartMagneticDisk = "FLOW_CHART_MAGNETIC_DISK",
    FlowChartMagneticDrum = "FLOW_CHART_MAGNETIC_DRUM",
    FlowChartMagneticTape = "FLOW_CHART_MAGNETIC_TAPE",
    FlowChartManualInput = "FLOW_CHART_MANUAL_INPUT",
    FlowChartManualOperation = "FLOW_CHART_MANUAL_OPERATION",
    FlowChartMerge = "FLOW_CHART_MERGE",
    FlowChartMultidocument = "FLOW_CHART_MULTIDOCUMENT",
    FlowChartOfflineStorage = "FLOW_CHART_OFFLINE_STORAGE",
    FlowChartOffpageConnector = "FLOW_CHART_OFFPAGE_CONNECTOR",
    FlowChartOnlineStorage = "FLOW_CHART_ONLINE_STORAGE",
    FlowChartOr = "FLOW_CHART_OR",
    FlowChartPredefinedProcess = "FLOW_CHART_PREDEFINED_PROCESS",
    FlowChartPreparation = "FLOW_CHART_PREPARATION",
    FlowChartProcess = "FLOW_CHART_PROCESS",
    FlowChartPunchedCard = "FLOW_CHART_PUNCHED_CARD",
    FlowChartPunchedTape = "FLOW_CHART_PUNCHED_TAPE",
    FlowChartSort = "FLOW_CHART_SORT",
    FlowChartSummingJunction = "FLOW_CHART_SUMMING_JUNCTION",
    FlowChartTerminator = "FLOW_CHART_TERMINATOR",
    ArrowEast = "ARROW_EAST",
    ArrowNorthEast = "ARROW_NORTH_EAST",
    ArrowNorth = "ARROW_NORTH",
    Speech = "SPEECH",
    Starburst = "STARBURST",
    Teardrop = "TEARDROP",
    EllipseRibbon = "ELLIPSE_RIBBON",
    EllipseRibbon2 = "ELLIPSE_RIBBON_2",
    CloudCallout = "CLOUD_CALLOUT",
    Custom = "CUSTOM"
}


// CreateShapeRequest
/** 
 * Creates a new shape.
**/
export class CreateShapeRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({ data: "json, name=elementProperties" })
  elementProperties?: PageElementProperties;

  @SpeakeasyMetadata({ data: "json, name=objectId" })
  objectId?: string;

  @SpeakeasyMetadata({ data: "json, name=shapeType" })
  shapeType?: CreateShapeRequestShapeTypeEnum;
}
