# coding: utf-8

"""
    Pub/Sub Lite API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.seek_subscription_request import SeekSubscriptionRequest

class TestSeekSubscriptionRequest(unittest.TestCase):
    """SeekSubscriptionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SeekSubscriptionRequest:
        """Test SeekSubscriptionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SeekSubscriptionRequest`
        """
        model = SeekSubscriptionRequest()
        if include_optional:
            return SeekSubscriptionRequest(
                named_target = 'NAMED_TARGET_UNSPECIFIED',
                time_target = openapi_client.models.time_target.TimeTarget(
                    event_time = '', 
                    publish_time = '', )
            )
        else:
            return SeekSubscriptionRequest(
        )
        """

    def testSeekSubscriptionRequest(self):
        """Test SeekSubscriptionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
