openapi: 3.0.0
servers:
  - url: https://admob.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: "The AdMob API allows publishers to programmatically get information about their AdMob account. "
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: AdMob API
  version: v1beta
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
    - format: google
      url: https://admob.googleapis.com/$discovery/rest?version=v1beta
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: admob
tags:
  - name: accounts
paths:
  /v1beta/accounts:
    get:
      description: Lists the AdMob publisher account that was most recently signed in to from the AdMob UI. For more information, see https://support.google.com/admob/answer/10243672.
      operationId: admob.accounts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admob.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admob.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admob.report
          Oauth2c:
            - https://www.googleapis.com/auth/admob.report
      tags:
        - accounts
  /v1beta/{name}:
    get:
      description: Gets information about the specified AdMob publisher account.
      operationId: admob.accounts.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admob.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admob.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admob.report
          Oauth2c:
            - https://www.googleapis.com/auth/admob.report
      tags:
        - accounts
    patch:
      description: Update the specified mediation group under the specified AdMob account. This method has limited access. If you see a 403 permission denied error, please reach out to your account manager for access.
      operationId: admob.accounts.mediationGroups.patch
      tags:
        - accounts
  /v1beta/{name}:stop:
    post:
      description: Stop the mediation A/B experiment and choose a variant. This method has limited access. If you see a 403 permission denied error, please reach out to your account manager for access.
      operationId: admob.accounts.mediationGroups.mediationAbExperiments.stop
      tags:
        - accounts
  /v1beta/{parent}/adSources:
    get:
      description: List the ad sources.
      operationId: admob.accounts.adSources.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admob.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admob.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admob.report
          Oauth2c:
            - https://www.googleapis.com/auth/admob.report
      tags:
        - accounts
  /v1beta/{parent}/adUnitMappings:
    get:
      description: List ad unit mappings under the specified AdMob account and ad unit. This method has limited access. If you see a 403 permission denied error, please reach out to your account manager for access.
      operationId: admob.accounts.adUnits.adUnitMappings.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admob.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admob.readonly
      tags:
        - accounts
    post:
      description: Create an ad unit mapping under the specific AdMob account and ad unit. This method has limited access. If you see a 403 permission denied error, please reach out to your account manager for access.
      operationId: admob.accounts.adUnits.adUnitMappings.create
      tags:
        - accounts
  /v1beta/{parent}/adUnitMappings:batchCreate:
    post:
      description: Batch create the ad unit mappings under the specific AdMob account. The maximum allowed batch size is 100. This method has limited access. If you see a 403 permission denied error, please reach out to your account manager for access.
      operationId: admob.accounts.adUnitMappings.batchCreate
      tags:
        - accounts
  /v1beta/{parent}/adUnits:
    get:
      description: List the ad units under the specified AdMob account.
      operationId: admob.accounts.adUnits.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admob.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admob.readonly
      tags:
        - accounts
    post:
      description: Creates an ad unit under the specified AdMob account. This method has limited access. If you see a 403 permission denied error, please reach out to your account manager for access.
      operationId: admob.accounts.adUnits.create
      tags:
        - accounts
  /v1beta/{parent}/adapters:
    get:
      description: List the adapters of the ad source.
      operationId: admob.accounts.adSources.adapters.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admob.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admob.readonly
      tags:
        - accounts
  /v1beta/{parent}/apps:
    get:
      description: List the apps under the specified AdMob account.
      operationId: admob.accounts.apps.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admob.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admob.readonly
      tags:
        - accounts
    post:
      description: Creates an app under the specified AdMob account. This method has limited access. If you see a 403 permission denied error, please reach out to your account manager for access.
      operationId: admob.accounts.apps.create
      tags:
        - accounts
  /v1beta/{parent}/campaignReport:generate:
    post:
      description: Generates Campaign Report based on provided specifications.
      operationId: admob.accounts.campaignReport.generate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admob.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admob.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admob.report
          Oauth2c:
            - https://www.googleapis.com/auth/admob.report
      tags:
        - accounts
  /v1beta/{parent}/mediationAbExperiments:
    post:
      description: Create an A/B testing experiment for a specified AdMob account and a mediation group. This method has limited access. If you see a 403 permission denied error, please reach out to your account manager for access.
      operationId: admob.accounts.mediationGroups.mediationAbExperiments.create
      tags:
        - accounts
  /v1beta/{parent}/mediationGroups:
    get:
      description: List mediation groups under the specified AdMob account. This method has limited access. If you see a 403 permission denied error, please reach out to your account manager for access.
      operationId: admob.accounts.mediationGroups.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admob.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admob.readonly
      tags:
        - accounts
    post:
      description: Create a mediation group under the specific AdMob account. This method has limited access. If you see a 403 permission denied error, please reach out to your account manager for access.
      operationId: admob.accounts.mediationGroups.create
      tags:
        - accounts
  /v1beta/{parent}/mediationReport:generate:
    post:
      description: Generates an AdMob mediation report based on the provided report specification. Returns result of a server-side streaming RPC. The result is returned in a sequence of responses.
      operationId: admob.accounts.mediationReport.generate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admob.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admob.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admob.report
          Oauth2c:
            - https://www.googleapis.com/auth/admob.report
      tags:
        - accounts
  /v1beta/{parent}/networkReport:generate:
    post:
      description: Generates an AdMob Network report based on the provided report specification. Returns result of a server-side streaming RPC. The result is returned in a sequence of responses.
      operationId: admob.accounts.networkReport.generate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admob.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admob.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admob.report
          Oauth2c:
            - https://www.googleapis.com/auth/admob.report
      tags:
        - accounts
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/admob.readonly: See your AdMob data
            https://www.googleapis.com/auth/admob.report: See your AdMob data
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/admob.readonly: See your AdMob data
            https://www.googleapis.com/auth/admob.report: See your AdMob data
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
