from dataclasses import dataclass, field
from enum import Enum

class MessageCode400AisEnum(str, Enum):
    FORMAT_ERROR = "FORMAT_ERROR"
    PARAMETER_NOT_CONSISTENT = "PARAMETER_NOT_CONSISTENT"
    PARAMETER_NOT_SUPPORTED = "PARAMETER_NOT_SUPPORTED"
    SERVICE_INVALID = "SERVICE_INVALID"
    RESOURCE_UNKNOWN = "RESOURCE_UNKNOWN"
    RESOURCE_EXPIRED = "RESOURCE_EXPIRED"
    RESOURCE_BLOCKED = "RESOURCE_BLOCKED"
    TIMESTAMP_INVALID = "TIMESTAMP_INVALID"
    PERIOD_INVALID = "PERIOD_INVALID"
    SCA_METHOD_UNKNOWN = "SCA_METHOD_UNKNOWN"
    SCA_INVALID = "SCA_INVALID"
    CONSENT_UNKNOWN = "CONSENT_UNKNOWN"
    SESSIONS_NOT_SUPPORTED = "SESSIONS_NOT_SUPPORTED"

