from .people_contactgroups_batchget import *
from .people_contactgroups_create import *
from .people_contactgroups_delete import *
from .people_contactgroups_list import *
from .people_contactgroups_members_modify import *
from .people_contactgroups_update import *
from .people_othercontacts_copyothercontacttomycontactsgroup import *
from .people_othercontacts_list import *
from .people_othercontacts_search import *
from .people_people_batchcreatecontacts import *
from .people_people_batchdeletecontacts import *
from .people_people_batchupdatecontacts import *
from .people_people_connections_list import *
from .people_people_createcontact import *
from .people_people_deletecontact import *
from .people_people_deletecontactphoto import *
from .people_people_get import *
from .people_people_getbatchget import *
from .people_people_listdirectorypeople import *
from .people_people_searchcontacts import *
from .people_people_searchdirectorypeople import *
from .people_people_updatecontact import *
from .people_people_updatecontactphoto import *
