# coding: utf-8

"""
    TimeSeriesInsightsClient

    Time Series Insights client

    The version of the OpenAPI document: 2017-11-15
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.event_source_update_parameters import EventSourceUpdateParameters

class TestEventSourceUpdateParameters(unittest.TestCase):
    """EventSourceUpdateParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventSourceUpdateParameters:
        """Test EventSourceUpdateParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventSourceUpdateParameters`
        """
        model = EventSourceUpdateParameters()
        if include_optional:
            return EventSourceUpdateParameters(
                tags = {
                    'key' : ''
                    }
            )
        else:
            return EventSourceUpdateParameters(
        )
        """

    def testEventSourceUpdateParameters(self):
        """Test EventSourceUpdateParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
