{
  "openapi": "3.0.0",
  "servers": [
    {
      "description": "Live server",
      "url": "https://api.shutterstock.com"
    },
    {
      "description": "Sandbox server",
      "url": "https://api-sandbox.shutterstock.com"
    }
  ],
  "info": {
    "contact": {
      "x-twitter": "Shutterstock"
    },
    "description": "The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.",
    "title": "Shutterstock API Explorer",
    "version": "1.1.32",
    "x-apisguru-categories": [
      "media"
    ],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_twitter.com_Shutterstock_profile_image.jpeg"
    },
    "x-origin": [
      {
        "format": "openapi",
        "url": "https://api-explorer.shutterstock.com/openapi.json",
        "version": "3.0"
      }
    ],
    "x-providerName": "shutterstock.com"
  },
  "paths": {
    "/v2/ai/audio/descriptors": {
      "get": {
        "description": "This endpoint lists the descriptors that you can use in the audio regions in an audio render.",
        "operationId": "listCustomDescriptors",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List computer audio descriptors",
        "tags": [
          "custom_music"
        ]
      }
    },
    "/v2/ai/audio/instruments": {
      "get": {
        "description": "This endpoint lists the instruments that you can include in computer audio. If you specify more than one search parameter, the API uses an AND condition.",
        "operationId": "listCustomInstruments",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List computer audio instruments",
        "tags": [
          "custom_music"
        ]
      }
    },
    "/v2/ai/audio/renders": {
      "get": {
        "description": "This endpoint shows the status of one or more audio renders, including download links for completed audio.",
        "operationId": "fetchRenders",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Get details about audio renders",
        "tags": [
          "custom_music"
        ]
      },
      "post": {
        "description": "This endpoint creates rendered audio from timeline data. It returns a render ID that you can use to download the finished audio when it is ready. The render ID is valid for up to 48 hours.",
        "operationId": "createAudioRenders",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Create rendered audio",
        "tags": [
          "custom_music"
        ]
      }
    },
    "/v2/audio": {
      "get": {
        "description": "This endpoint lists information about one or more audio tracks, including the description and publication date.",
        "operationId": "getTrackList",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List audio tracks",
        "tags": [
          "audio"
        ]
      }
    },
    "/v2/audio/collections": {
      "get": {
        "description": "This endpoint lists your collections of audio tracks and their basic attributes.",
        "operationId": "getTrackCollectionList",
        "security": [
          {
            "customer_accessCode": [
              "collections.view"
            ]
          }
        ],
        "summary": "List audio collections",
        "tags": [
          "audio"
        ]
      },
      "post": {
        "description": "This endpoint creates one or more collections (soundboxes). To add tracks, use `POST /v2/audio/collections/{id}/items`.",
        "operationId": "createTrackCollection",
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "summary": "Create audio collections",
        "tags": [
          "audio"
        ]
      }
    },
    "/v2/audio/collections/{id}": {
      "delete": {
        "description": "This endpoint deletes a collection.",
        "operationId": "deleteTrackCollection",
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "summary": "Delete audio collections",
        "tags": [
          "audio"
        ]
      },
      "get": {
        "description": "This endpoint gets more detailed information about a collection, including the number of items in it and when it was last updated. To get the tracks in collections, use `GET /v2/audio/collections/{id}/items`.",
        "operationId": "getTrackCollection",
        "security": [
          {
            "customer_accessCode": [
              "collections.view"
            ]
          }
        ],
        "summary": "Get the details of audio collections",
        "tags": [
          "audio"
        ]
      },
      "post": {
        "description": "This endpoint sets a new name for a collection.",
        "operationId": "renameTrackCollection",
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "summary": "Rename audio collections",
        "tags": [
          "audio"
        ]
      }
    },
    "/v2/audio/collections/{id}/items": {
      "delete": {
        "description": "This endpoint removes one or more tracks from a collection.",
        "operationId": "deleteTrackCollectionItems",
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "summary": "Remove audio tracks from collections",
        "tags": [
          "audio"
        ]
      },
      "get": {
        "description": "This endpoint lists the IDs of tracks in a collection and the date that each was added.",
        "operationId": "getTrackCollectionItems",
        "security": [
          {
            "customer_accessCode": [
              "collections.view"
            ]
          }
        ],
        "summary": "Get the contents of audio collections",
        "tags": [
          "audio"
        ]
      },
      "post": {
        "description": "This endpoint adds one or more tracks to a collection by track IDs.",
        "operationId": "addTrackCollectionItems",
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "summary": "Add audio tracks to collections",
        "tags": [
          "audio"
        ]
      }
    },
    "/v2/audio/genres": {
      "get": {
        "description": "This endpoint returns a list of all audio genres.",
        "operationId": "listGenres",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List audio genres",
        "tags": [
          "audio"
        ]
      }
    },
    "/v2/audio/instruments": {
      "get": {
        "description": "This endpoint returns a list of all audio instruments.",
        "operationId": "listInstruments",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List audio instruments",
        "tags": [
          "audio"
        ]
      }
    },
    "/v2/audio/licenses": {
      "get": {
        "description": "This endpoint lists existing licenses. You can filter the results according to the track ID to see if you have an existing license for a specific track.",
        "operationId": "getTrackLicenseList",
        "security": [
          {
            "customer_accessCode": [
              "licenses.view"
            ]
          }
        ],
        "summary": "List audio licenses",
        "tags": [
          "audio"
        ]
      },
      "post": {
        "description": "This endpoint gets licenses for one or more tracks. The download links in the response are valid for 8 hours.",
        "operationId": "licenseTrack",
        "security": [
          {
            "customer_accessCode": [
              "licenses.create"
            ]
          }
        ],
        "summary": "License audio tracks",
        "tags": [
          "audio"
        ]
      }
    },
    "/v2/audio/licenses/{id}/downloads": {
      "post": {
        "description": "This endpoint redownloads tracks that you have already received a license for. The download links in the response are valid for 8 hours.",
        "operationId": "downloadTracks",
        "security": [
          {
            "customer_accessCode": [
              "licenses.view"
            ]
          }
        ],
        "summary": "Download audio tracks",
        "tags": [
          "audio"
        ]
      }
    },
    "/v2/audio/moods": {
      "get": {
        "description": "This endpoint returns a list of all audio moods.",
        "operationId": "listMoods",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List audio moods",
        "tags": [
          "audio"
        ]
      }
    },
    "/v2/audio/search": {
      "get": {
        "description": "This endpoint searches for tracks. If you specify more than one search parameter, the API uses an AND condition. Array parameters can be specified multiple times; in this case, the API uses an AND or an OR condition with those values, depending on the parameter.",
        "operationId": "searchTracks",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Search for tracks",
        "tags": [
          "audio"
        ]
      }
    },
    "/v2/audio/{id}": {
      "get": {
        "description": "This endpoint shows information about a track, including its genres, instruments, and other attributes.",
        "operationId": "getTrack",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Get details about audio tracks",
        "tags": [
          "audio"
        ]
      }
    },
    "/v2/bulk_search/images": {
      "post": {
        "description": "This endpoint runs up to 5 image searches in a single request and returns up to 20 results per search. You can provide global search parameters in the query parameters and override them for each search in the body parameter. The query and body parameters are the same as in the `GET /v2/images/search` endpoint.",
        "operationId": "bulkSearchImages",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Run multiple image searches",
        "tags": [
          "images"
        ]
      }
    },
    "/v2/catalog/collections": {
      "get": {
        "description": "This endpoint returns a list of catalog collections.",
        "operationId": "getCollections",
        "security": [
          {
            "customer_accessCode": [
              "collections.view"
            ]
          }
        ],
        "summary": "List catalog collections",
        "tags": [
          "catalog"
        ]
      },
      "post": {
        "description": "This endpoint creates a catalog collection and optionally adds assets. To add assets to the collection later, use `PATCH /v2/catalog/collections/{collection_id}/items`.",
        "operationId": "createCollection",
        "security": [
          {
            "customer_accessCode": [
              "collections.view",
              "collections.edit"
            ]
          }
        ],
        "summary": "Create catalog collections",
        "tags": [
          "catalog"
        ]
      }
    },
    "/v2/catalog/collections/{collection_id}": {
      "delete": {
        "description": "This endpoint deletes a catalog collection. It does not remove the assets from the user's account's catalog.",
        "operationId": "deleteCollection",
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "summary": "Delete catalog collections",
        "tags": [
          "catalog"
        ]
      },
      "patch": {
        "description": "This endpoint updates the metadata of a catalog collection.",
        "operationId": "updateCollection",
        "security": [
          {
            "customer_accessCode": [
              "collections.view",
              "collections.edit"
            ]
          }
        ],
        "summary": "Update collection metadata",
        "tags": [
          "catalog"
        ]
      }
    },
    "/v2/catalog/collections/{collection_id}/items": {
      "delete": {
        "description": "This endpoint removes assets from a catalog collection. It does not remove the assets from the user's account's catalog.",
        "operationId": "deleteFromCollection",
        "security": [
          {
            "customer_accessCode": [
              "collections.view",
              "collections.edit"
            ]
          }
        ],
        "summary": "Remove items from catalog collection",
        "tags": [
          "catalog"
        ]
      },
      "post": {
        "description": "This endpoint adds assets to a catalog collection. It also automatically adds the assets to the user's account's catalog.",
        "operationId": "addToCollection",
        "security": [
          {
            "customer_accessCode": [
              "collections.view",
              "collections.edit"
            ]
          }
        ],
        "summary": "Add items to catalog collections",
        "tags": [
          "catalog"
        ]
      }
    },
    "/v2/catalog/search": {
      "get": {
        "description": "This endpoint searches for assets in the account's catalog. If you specify more than one search parameter, the API uses an AND condition. Array parameters can be specified multiple times; in this case, the API uses an AND or an OR condition with those values, depending on the parameter. You can also filter search terms out in the `query` parameter by prefixing the term with NOT.",
        "operationId": "searchCatalog",
        "security": [
          {
            "customer_accessCode": [
              "collections.view"
            ]
          }
        ],
        "summary": "Search catalogs for assets",
        "tags": [
          "catalog"
        ]
      }
    },
    "/v2/contributors": {
      "get": {
        "description": "This endpoint lists information about one or more contributors, including contributor type, equipment they use and other attributes.",
        "operationId": "getContributorList",
        "security": [
          {
            "customer_accessCode": []
          },
          {
            "basic": []
          }
        ],
        "summary": "Get details about multiple contributors",
        "tags": [
          "contributors"
        ]
      }
    },
    "/v2/contributors/{contributor_id}": {
      "get": {
        "description": "This endpoint shows information about a single contributor, including contributor type, equipment they use, and other attributes.",
        "operationId": "getContributor",
        "security": [
          {
            "customer_accessCode": []
          },
          {
            "basic": []
          }
        ],
        "summary": "Get details about a single contributor",
        "tags": [
          "contributors"
        ]
      }
    },
    "/v2/contributors/{contributor_id}/collections": {
      "get": {
        "description": "This endpoint lists collections based on contributor ID.",
        "operationId": "getContributorCollectionsList",
        "security": [
          {
            "customer_accessCode": []
          },
          {
            "basic": []
          }
        ],
        "summary": "List contributors' collections",
        "tags": [
          "contributors"
        ]
      }
    },
    "/v2/contributors/{contributor_id}/collections/{id}": {
      "get": {
        "description": "This endpoint gets more detailed information about a contributor's collection, including its cover image, timestamps for its creation, and most recent update. To get the items in collections, use GET /v2/contributors/{contributor_id}/collections/{id}/items.",
        "operationId": "getContributorCollections",
        "security": [
          {
            "customer_accessCode": []
          },
          {
            "basic": []
          }
        ],
        "summary": "Get details about contributors' collections",
        "tags": [
          "contributors"
        ]
      }
    },
    "/v2/contributors/{contributor_id}/collections/{id}/items": {
      "get": {
        "description": "This endpoint lists the IDs of items in a contributor's collection and the date that each was added.",
        "operationId": "getContributorCollectionItems",
        "security": [
          {
            "customer_accessCode": []
          },
          {
            "basic": []
          }
        ],
        "summary": "Get the items in contributors' collections",
        "tags": [
          "contributors"
        ]
      }
    },
    "/v2/cv/images": {
      "post": {
        "description": "This endpoint uploads an image for reverse image or video search. Images must be in JPEG or PNG format. To get the search results, pass the upload ID that this endpoint returns to the GET /v2/cv/similar/images or GET /v2/cv/similar/videos endpoints. Contact us for access to this endpoint.",
        "operationId": "uploadImage",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Upload images",
        "tags": [
          "computer_vision"
        ]
      }
    },
    "/v2/cv/keywords": {
      "get": {
        "description": "This endpoint returns a list of suggested keywords for a media item that you specify or upload.",
        "operationId": "getKeywords",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List suggested keywords",
        "tags": [
          "computer_vision"
        ]
      }
    },
    "/v2/cv/similar/images": {
      "get": {
        "description": "This endpoint returns images that are visually similar to an image that you specify or upload.",
        "operationId": "getSimilarImages",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List similar images",
        "tags": [
          "computer_vision"
        ]
      }
    },
    "/v2/cv/similar/videos": {
      "get": {
        "description": "This endpoint returns videos that are visually similar to an image that you specify or upload.",
        "operationId": "getSimilarVideos",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List similar videos",
        "tags": [
          "computer_vision"
        ]
      }
    },
    "/v2/editorial/categories": {
      "get": {
        "deprecated": true,
        "description": "Deprecated; use `GET /v2/editorial/images/categories` instead. This endpoint lists the categories that editorial images can belong to, which are separate from the categories that other types of assets can belong to.",
        "operationId": "getEditorialCategories",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "(Deprecated) List editorial categories",
        "tags": [
          "editorial_images"
        ]
      }
    },
    "/v2/editorial/images/categories": {
      "get": {
        "description": "This endpoint lists the categories that editorial images can belong to, which are separate from the categories that other types of assets can belong to.",
        "operationId": "listEditorialImageCategories",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List editorial categories",
        "tags": [
          "editorial_images"
        ]
      }
    },
    "/v2/editorial/images/licenses": {
      "get": {
        "description": "This endpoint lists existing editorial image licenses.",
        "operationId": "getEditorialImageLicenseList",
        "security": [
          {
            "customer_accessCode": [
              "licenses.view"
            ]
          }
        ],
        "summary": "List editorial image licenses",
        "tags": [
          "editorial_images"
        ]
      },
      "post": {
        "description": "This endpoint gets licenses for one or more editorial images. You must specify the country and one or more editorial images to license. The download links in the response are valid for 8 hours.",
        "operationId": "licenseEditorialImages",
        "security": [
          {
            "customer_accessCode": [
              "licenses.create",
              "purchases.view"
            ]
          }
        ],
        "summary": "License editorial content",
        "tags": [
          "editorial_images"
        ]
      }
    },
    "/v2/editorial/images/livefeeds": {
      "get": {
        "operationId": "getEditorialImageLivefeedList",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Get editorial livefeed list",
        "tags": [
          "editorial_images"
        ]
      }
    },
    "/v2/editorial/images/livefeeds/{id}": {
      "get": {
        "operationId": "getEditorialImageLivefeed",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Get editorial livefeed",
        "tags": [
          "editorial_images"
        ]
      }
    },
    "/v2/editorial/images/livefeeds/{id}/items": {
      "get": {
        "operationId": "getEditorialImageLivefeedItems",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Get editorial livefeed items",
        "tags": [
          "editorial_images"
        ]
      }
    },
    "/v2/editorial/images/search": {
      "get": {
        "description": "This endpoint searches for editorial images. If you specify more than one search parameter, the API uses an AND condition. For example, if you set the `category` parameter to \"Alone,Performing\" and also specify a `query` parameter, the results include only images that match the query and are in both the Alone and Performing categories. You can also filter search terms out in the `query` parameter by prefixing the term with NOT.",
        "operationId": "searchEditorialImages",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Search editorial images",
        "tags": [
          "editorial_images"
        ]
      }
    },
    "/v2/editorial/images/updated": {
      "get": {
        "description": "This endpoint lists editorial images that have been updated in the specified time period to update content management systems (CMS) or digital asset management (DAM) systems. In most cases, use the date_updated_start and date_updated_end parameters to specify a range updates based on when the updates happened. You can also use the date_taken_start and date_taken_end parameters to specify a range of updates based on when the image was taken.",
        "operationId": "getUpdatedEditorialImages",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List updated content",
        "tags": [
          "editorial_images"
        ]
      }
    },
    "/v2/editorial/images/{id}": {
      "get": {
        "description": "This endpoint shows information about an editorial image, including a URL to a preview image and the sizes that it is available in.",
        "operationId": "getEditorialImage",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Get editorial content details",
        "tags": [
          "editorial_images"
        ]
      }
    },
    "/v2/editorial/licenses": {
      "post": {
        "deprecated": true,
        "description": "Deprecated; use `POST /v2/editorial/images/licenses` instead to get licenses for one or more editorial images. You must specify the country and one or more editorial images to license. The download links in the response are valid for 8 hours.",
        "operationId": "licenseEditorialImage",
        "security": [
          {
            "customer_accessCode": [
              "licenses.create"
            ]
          }
        ],
        "summary": "(Deprecated) License editorial content",
        "tags": [
          "editorial_images"
        ]
      }
    },
    "/v2/editorial/livefeeds": {
      "get": {
        "deprecated": true,
        "description": "Deprecated; use `GET /v2/editorial/images/livefeeds` instead to get a list of editorial livefeeds.",
        "operationId": "getEditorialLivefeedList",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "(Deprecated) Get editorial livefeed list",
        "tags": [
          "editorial_images"
        ]
      }
    },
    "/v2/editorial/livefeeds/{id}": {
      "get": {
        "deprecated": true,
        "description": "Deprecated: use `GET /v2/editorial/images/livefeeds/{id}` instead to get an editorial livefeed.",
        "operationId": "getEditorialLivefeed",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "(Deprecated) Get editorial livefeed",
        "tags": [
          "editorial_images"
        ]
      }
    },
    "/v2/editorial/livefeeds/{id}/items": {
      "get": {
        "deprecated": true,
        "description": "Deprecated; use `GET /v2/editorial/images/livefeeds/{id}/items` instead to get editorial livefeed items.",
        "operationId": "getEditorialLivefeedItems",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "(Deprecated) Get editorial livefeed items",
        "tags": [
          "editorial_images"
        ]
      }
    },
    "/v2/editorial/search": {
      "get": {
        "deprecated": true,
        "description": "Deprecated; use `GET /v2/editorial/images/search` instead to search for editorial images.",
        "operationId": "searchEditorial",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "(Deprecated) Search editorial content",
        "tags": [
          "editorial_images"
        ]
      }
    },
    "/v2/editorial/updated": {
      "get": {
        "deprecated": true,
        "description": "Deprecated; use `GET /v2/editorial/images/updated` instead to get recently updated items.",
        "operationId": "getUpdatedEditorialImage",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "(Deprecated) List updated content",
        "tags": [
          "editorial_images"
        ]
      }
    },
    "/v2/editorial/videos/categories": {
      "get": {
        "description": "This endpoint lists the categories that editorial videos can belong to, which are separate from the categories that other types of assets can belong to.",
        "operationId": "listEditorialVideoCategories",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List editorial video categories",
        "tags": [
          "editorial_video"
        ]
      }
    },
    "/v2/editorial/videos/licenses": {
      "get": {
        "description": "This endpoint lists existing editorial video licenses.",
        "operationId": "getEditorialVideoLicenseList",
        "security": [
          {
            "customer_accessCode": [
              "licenses.view"
            ]
          }
        ],
        "summary": "List editorial video licenses",
        "tags": [
          "editorial_video"
        ]
      },
      "post": {
        "description": "This endpoint gets licenses for one or more editorial videos. You must specify the country and one or more editorial videos to license. The download links in the response are valid for 8 hours.",
        "operationId": "licenseEditorialVideo",
        "security": [
          {
            "customer_accessCode": [
              "licenses.create",
              "purchases.view"
            ]
          }
        ],
        "summary": "License editorial video content",
        "tags": [
          "editorial_video"
        ]
      }
    },
    "/v2/editorial/videos/search": {
      "get": {
        "description": "This endpoint searches for editorial videos. If you specify more than one search parameter, the API uses an AND condition. For example, if you set the `category` parameter to \"Alone,Performing\" and also specify a `query` parameter, the results include only videos that match the query and are in both the Alone and Performing categories.  You can also filter search terms out in the `query` parameter by prefixing the term with NOT.",
        "operationId": "searchEditorialVideos",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Search editorial video content",
        "tags": [
          "editorial_video"
        ]
      }
    },
    "/v2/editorial/videos/{id}": {
      "get": {
        "description": "This endpoint shows information about an editorial image, including a URL to a preview image and the sizes that it is available in.",
        "operationId": "getEditorialVideo",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Get editorial video content details",
        "tags": [
          "editorial_video"
        ]
      }
    },
    "/v2/editorial/{id}": {
      "get": {
        "deprecated": true,
        "description": "Deprecated; use `GET /v2/editorial/images/{id}` instead to show information about an editorial image, including a URL to a preview image and the sizes that it is available in.",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "(Deprecated) Get editorial content details",
        "tags": [
          "editorial_images"
        ]
      }
    },
    "/v2/images": {
      "get": {
        "description": "This endpoint lists information about one or more images, including the available sizes.",
        "operationId": "getImageList",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List images",
        "tags": [
          "images"
        ]
      },
      "post": {
        "deprecated": true,
        "description": "Deprecated; use `POST /v2/cv/images` instead. This endpoint uploads an image for reverse image search. The image must be in JPEG or PNG format. To get the search results, pass the ID that this endpoint returns to the `GET /v2/images/{id}/similar` endpoint.",
        "operationId": "uploadEphemeralImage",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Upload ephemeral images",
        "tags": [
          "computer_vision"
        ]
      }
    },
    "/v2/images/categories": {
      "get": {
        "description": "This endpoint lists the categories (Shutterstock-assigned genres) that images can belong to.",
        "operationId": "listImageCategories",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List image categories",
        "tags": [
          "images"
        ]
      }
    },
    "/v2/images/collections": {
      "get": {
        "description": "This endpoint lists your collections of images and their basic attributes.",
        "operationId": "getImageCollectionList",
        "security": [
          {
            "customer_accessCode": [
              "collections.view"
            ]
          }
        ],
        "summary": "List image collections",
        "tags": [
          "images"
        ]
      },
      "post": {
        "description": "This endpoint creates one or more image collections (lightboxes). To add images to the collections, use `POST /v2/images/collections/{id}/items`.",
        "operationId": "createImageCollection",
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "summary": "Create image collections",
        "tags": [
          "images"
        ]
      }
    },
    "/v2/images/collections/featured": {
      "get": {
        "description": "This endpoint lists featured collections of specific types and a name and cover image for each collection.",
        "operationId": "getFeaturedImageCollectionList",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List featured image collections",
        "tags": [
          "images"
        ]
      }
    },
    "/v2/images/collections/featured/{id}": {
      "get": {
        "description": "This endpoint gets more detailed information about a featured collection, including its cover image and timestamps for its creation and most recent update. To get the images, use `GET /v2/images/collections/featured/{id}/items`.",
        "operationId": "getFeaturedImageCollection",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Get the details of featured image collections",
        "tags": [
          "images"
        ]
      }
    },
    "/v2/images/collections/featured/{id}/items": {
      "get": {
        "description": "This endpoint lists the IDs of images in a featured collection and the date that each was added.",
        "operationId": "getFeaturedImageCollectionItems",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Get the contents of featured image collections",
        "tags": [
          "images"
        ]
      }
    },
    "/v2/images/collections/{id}": {
      "delete": {
        "description": "This endpoint deletes an image collection.",
        "operationId": "deleteImageCollection",
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "summary": "Delete image collections",
        "tags": [
          "images"
        ]
      },
      "get": {
        "description": "This endpoint gets more detailed information about a collection, including its cover image and timestamps for its creation and most recent update. To get the images in collections, use `GET /v2/images/collections/{id}/items`.",
        "operationId": "getImageCollection",
        "security": [
          {
            "customer_accessCode": [
              "collections.view"
            ]
          }
        ],
        "summary": "Get the details of image collections",
        "tags": [
          "images"
        ]
      },
      "post": {
        "description": "This endpoint sets a new name for an image collection.",
        "operationId": "renameImageCollection",
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "summary": "Rename image collections",
        "tags": [
          "images"
        ]
      }
    },
    "/v2/images/collections/{id}/items": {
      "delete": {
        "description": "This endpoint removes one or more images from a collection.",
        "operationId": "deleteImageCollectionItems",
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "summary": "Remove images from collections",
        "tags": [
          "images"
        ]
      },
      "get": {
        "description": "This endpoint lists the IDs of images in a collection and the date that each was added.",
        "operationId": "getImageCollectionItems",
        "security": [
          {
            "customer_accessCode": [
              "collections.view"
            ]
          }
        ],
        "summary": "Get the contents of image collections",
        "tags": [
          "images"
        ]
      },
      "post": {
        "description": "This endpoint adds one or more images to a collection by image IDs.",
        "operationId": "addImageCollectionItems",
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "summary": "Add images to collections",
        "tags": [
          "images"
        ]
      }
    },
    "/v2/images/licenses": {
      "get": {
        "description": "This endpoint lists existing licenses.",
        "operationId": "getImageLicenseList",
        "security": [
          {
            "customer_accessCode": [
              "licenses.view"
            ]
          }
        ],
        "summary": "List image licenses",
        "tags": [
          "images"
        ]
      },
      "post": {
        "description": "This endpoint gets licenses for one or more images. You must specify the image IDs in the body parameter and other details like the format, size, and subscription ID either in the query parameter or with each image ID in the body parameter. Values in the body parameter override values in the query parameters. The download links in the response are valid for 8 hours.",
        "operationId": "licenseImages",
        "security": [
          {
            "customer_accessCode": [
              "licenses.create",
              "purchases.view"
            ]
          }
        ],
        "summary": "License images",
        "tags": [
          "images"
        ]
      }
    },
    "/v2/images/licenses/{id}/downloads": {
      "post": {
        "description": "This endpoint redownloads images that you have already received a license for. The download links in the response are valid for 8 hours.",
        "operationId": "downloadImage",
        "security": [
          {
            "customer_accessCode": [
              "licenses.view"
            ]
          }
        ],
        "summary": "Download images",
        "tags": [
          "images"
        ]
      }
    },
    "/v2/images/recommendations": {
      "get": {
        "description": "This endpoint returns images that customers put in the same collection as the specified image IDs.",
        "operationId": "getImageRecommendations",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List recommended images",
        "tags": [
          "images"
        ]
      }
    },
    "/v2/images/search": {
      "get": {
        "description": "This endpoint searches for images. If you specify more than one search parameter, the API uses an AND condition. Array parameters can be specified multiple times; in this case, the API uses an AND or an OR condition with those values, depending on the parameter. You can also filter search terms out in the `query` parameter by prefixing the term with NOT. Free API accounts show results only from a limited library of media, not the full Shutterstock media library. Also, the[...]",
        "operationId": "searchImages",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Search for images",
        "tags": [
          "images"
        ]
      }
    },
    "/v2/images/search/suggestions": {
      "get": {
        "description": "This endpoint provides autocomplete suggestions for partial search terms.",
        "operationId": "getImageSuggestions",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Get suggestions for a search term",
        "tags": [
          "images"
        ]
      },
      "post": {
        "description": "This endpoint returns up to 10 important keywords from a block of plain text.",
        "operationId": "getImageKeywordSuggestions",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Get keywords from text",
        "tags": [
          "images"
        ]
      }
    },
    "/v2/images/updated": {
      "get": {
        "description": "This endpoint lists images that have been updated in the specified time period to update content management systems (CMS) or digital asset management (DAM) systems. In most cases, use the `interval` parameter to show images that were updated recently, but you can also use the `start_date` and `end_date` parameters to specify a range of no more than three days. Do not use the `interval` parameter with either `start_date` or `end_date`.",
        "operationId": "getUpdatedImages",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List updated images",
        "tags": [
          "images"
        ]
      }
    },
    "/v2/images/{id}": {
      "get": {
        "description": "This endpoint shows information about an image, including a URL to a preview image and the sizes that it is available in.",
        "operationId": "getImage",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Get details about images",
        "tags": [
          "images"
        ]
      }
    },
    "/v2/images/{id}/similar": {
      "get": {
        "description": "This endpoint returns images that are visually similar to an image that you specify.",
        "operationId": "listSimilarImages",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List similar images",
        "tags": [
          "images"
        ]
      }
    },
    "/v2/oauth/access_token": {
      "post": {
        "description": "This endpoint returns an access token for the specified user and with the specified scopes. The token does not expire until the user changes their password. The body parameters must be encoded as form data.",
        "operationId": "createAccessToken",
        "summary": "Get access tokens",
        "tags": [
          "oauth"
        ]
      }
    },
    "/v2/oauth/authorize": {
      "get": {
        "description": "This endpoint returns a redirect URI (in the 'Location' header) that the customer uses to authorize your application and, together with POST /v2/oauth/access_token, generate an access token that represents that authorization.",
        "operationId": "authorize",
        "summary": "Authorize applications",
        "tags": [
          "oauth"
        ]
      }
    },
    "/v2/sfx": {
      "get": {
        "description": "This endpoint shows information about sound effects.",
        "operationId": "getSfxListDetails",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List details about sound effects",
        "tags": [
          "sound_effects"
        ]
      }
    },
    "/v2/sfx/licenses": {
      "get": {
        "description": "This endpoint lists existing licenses.",
        "operationId": "getSfxLicenseList",
        "security": [
          {
            "customer_accessCode": [
              "licenses.view"
            ]
          }
        ],
        "summary": "List sound effects licenses",
        "tags": [
          "sound_effects"
        ]
      },
      "post": {
        "description": "This endpoint licenses sounds effect assets.",
        "operationId": "licensesSFX",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "License sound effects",
        "tags": [
          "sound_effects"
        ]
      }
    },
    "/v2/sfx/licenses/{id}/downloads": {
      "post": {
        "description": "This endpoint redownloads sound effects that you have already received a license for. The download links in the response are valid for 8 hours.",
        "operationId": "downloadSfx",
        "security": [
          {
            "customer_accessCode": [
              "licenses.view"
            ]
          }
        ],
        "summary": "Download sound effects",
        "tags": [
          "sound_effects"
        ]
      }
    },
    "/v2/sfx/search": {
      "get": {
        "description": "This endpoint searches for sound effects. If you specify more than one search parameter, the API uses an AND condition.",
        "operationId": "searchSFX",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Search for sound effects",
        "tags": [
          "sound_effects"
        ]
      }
    },
    "/v2/sfx/{id}": {
      "get": {
        "description": "This endpoint shows information about a sound effect.",
        "operationId": "getSfxDetails",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Get details about sound effects",
        "tags": [
          "sound_effects"
        ]
      }
    },
    "/v2/test": {
      "get": {
        "operationId": "echo",
        "summary": "Echo text",
        "tags": [
          "test"
        ]
      }
    },
    "/v2/test/validate": {
      "get": {
        "operationId": "validate",
        "summary": "Validate input",
        "tags": [
          "test"
        ]
      }
    },
    "/v2/user": {
      "get": {
        "operationId": "getUser",
        "security": [
          {
            "customer_accessCode": [
              "user.view"
            ]
          }
        ],
        "summary": "Get user details",
        "tags": [
          "users"
        ]
      }
    },
    "/v2/user/access_token": {
      "get": {
        "operationId": "getAccessToken",
        "security": [
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Get access token details",
        "tags": [
          "users"
        ]
      }
    },
    "/v2/user/subscriptions": {
      "get": {
        "operationId": "getUserSubscriptionList",
        "security": [
          {
            "customer_accessCode": [
              "purchases.view"
            ]
          }
        ],
        "summary": "List user subscriptions",
        "tags": [
          "users"
        ]
      }
    },
    "/v2/videos": {
      "get": {
        "description": "This endpoint lists information about one or more videos, including the aspect ratio and URLs to previews.",
        "operationId": "getVideoList",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List videos",
        "tags": [
          "videos"
        ]
      }
    },
    "/v2/videos/categories": {
      "get": {
        "description": "This endpoint lists the categories (Shutterstock-assigned genres) that videos can belong to.",
        "operationId": "listVideoCategories",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List video categories",
        "tags": [
          "videos"
        ]
      }
    },
    "/v2/videos/collections": {
      "get": {
        "description": "This endpoint lists your collections of videos and their basic attributes.",
        "operationId": "getVideoCollectionList",
        "security": [
          {
            "customer_accessCode": [
              "collections.view"
            ]
          }
        ],
        "summary": "List video collections",
        "tags": [
          "videos"
        ]
      },
      "post": {
        "description": "This endpoint creates one or more collections (clipboxes). To add videos to collections, use `POST /v2/videos/collections/{id}/items`.",
        "operationId": "createVideoCollection",
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "summary": "Create video collections",
        "tags": [
          "videos"
        ]
      }
    },
    "/v2/videos/collections/featured": {
      "get": {
        "description": "This endpoint lists featured video collections and a name and cover video for each collection.",
        "operationId": "getFeaturedVideoCollectionList",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List featured video collections",
        "tags": [
          "videos"
        ]
      }
    },
    "/v2/videos/collections/featured/{id}": {
      "get": {
        "description": "This endpoint gets more detailed information about a featured video collection, including its cover video and timestamps for its creation and most recent update. To get the videos, use `GET /v2/videos/collections/featured/{id}/items`.",
        "operationId": "getFeaturedVideoCollection",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Get the details of featured video collections",
        "tags": [
          "videos"
        ]
      }
    },
    "/v2/videos/collections/featured/{id}/items": {
      "get": {
        "description": "This endpoint lists the IDs of videos in a featured collection and the date that each was added.",
        "operationId": "getFeaturedVideoCollectionItems",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Get the contents of featured video collections",
        "tags": [
          "videos"
        ]
      }
    },
    "/v2/videos/collections/{id}": {
      "delete": {
        "description": "This endpoint deletes a collection.",
        "operationId": "deleteVideoCollection",
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "summary": "Delete video collections",
        "tags": [
          "videos"
        ]
      },
      "get": {
        "description": "This endpoint gets more detailed information about a collection, including the timestamp for its creation and the number of videos in it. To get the videos in collections, use GET /v2/videos/collections/{id}/items.",
        "operationId": "getVideoCollection",
        "security": [
          {
            "customer_accessCode": [
              "collections.view"
            ]
          }
        ],
        "summary": "Get the details of video collections",
        "tags": [
          "videos"
        ]
      },
      "post": {
        "description": "This endpoint sets a new name for a collection.",
        "operationId": "renameVideoCollection",
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "summary": "Rename video collections",
        "tags": [
          "videos"
        ]
      }
    },
    "/v2/videos/collections/{id}/items": {
      "delete": {
        "description": "This endpoint removes one or more videos from a collection.",
        "operationId": "deleteVideoCollectionItems",
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "summary": "Remove videos from collections",
        "tags": [
          "videos"
        ]
      },
      "get": {
        "description": "This endpoint lists the IDs of videos in a collection and the date that each was added.",
        "operationId": "getVideoCollectionItems",
        "security": [
          {
            "customer_accessCode": [
              "collections.view"
            ]
          }
        ],
        "summary": "Get the contents of video collections",
        "tags": [
          "videos"
        ]
      },
      "post": {
        "description": "This endpoint adds one or more videos to a collection by video IDs.",
        "operationId": "addVideoCollectionItems",
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "summary": "Add videos to collections",
        "tags": [
          "videos"
        ]
      }
    },
    "/v2/videos/licenses": {
      "get": {
        "description": "This endpoint lists existing licenses.",
        "operationId": "getVideoLicenseList",
        "security": [
          {
            "customer_accessCode": [
              "licenses.view"
            ]
          }
        ],
        "summary": "List video licenses",
        "tags": [
          "videos"
        ]
      },
      "post": {
        "description": "This endpoint gets licenses for one or more videos. You must specify the video IDs in the body parameter and the size and subscription ID either in the query parameter or with each video ID in the body parameter. Values in the body parameter override values in the query parameters. The download links in the response are valid for 8 hours.",
        "operationId": "licenseVideos",
        "security": [
          {
            "customer_accessCode": [
              "licenses.create",
              "purchases.view"
            ]
          }
        ],
        "summary": "License videos",
        "tags": [
          "videos"
        ]
      }
    },
    "/v2/videos/licenses/{id}/downloads": {
      "post": {
        "description": "This endpoint redownloads videos that you have already received a license for.",
        "operationId": "downloadVideos",
        "security": [
          {
            "customer_accessCode": [
              "licenses.view"
            ]
          }
        ],
        "summary": "Download videos",
        "tags": [
          "videos"
        ]
      }
    },
    "/v2/videos/search": {
      "get": {
        "description": "This endpoint searches for videos. If you specify more than one search parameter, the API uses an AND condition. Array parameters can be specified multiple times; in this case, the API uses an AND or an OR condition with those values, depending on the parameter. You can also filter search terms out in the `query` parameter by prefixing the term with NOT.",
        "operationId": "searchVideos",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Search for videos",
        "tags": [
          "videos"
        ]
      }
    },
    "/v2/videos/search/suggestions": {
      "get": {
        "description": "This endpoint provides autocomplete suggestions for partial search terms.",
        "operationId": "getVideoSuggestions",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Get suggestions for a search term",
        "tags": [
          "videos"
        ]
      }
    },
    "/v2/videos/updated": {
      "get": {
        "description": "This endpoint lists videos that have been updated in the specified time period to update content management systems (CMS) or digital asset management (DAM) systems. In most cases, use the `interval` parameter to show videos that were updated recently, but you can also use the `start_date` and `end_date` parameters to specify a range of no more than three days. Do not use the `interval` parameter with either `start_date` or `end_date`.",
        "operationId": "getUpdatedVideos",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List updated videos",
        "tags": [
          "videos"
        ]
      }
    },
    "/v2/videos/{id}": {
      "get": {
        "description": "This endpoint shows information about a video, including URLs to previews and the sizes that it is available in.",
        "operationId": "getVideo",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "Get details about videos",
        "tags": [
          "videos"
        ]
      }
    },
    "/v2/videos/{id}/similar": {
      "get": {
        "description": "This endpoint searches for videos that are similar to a video that you specify.",
        "operationId": "findSimilarVideos",
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "summary": "List similar videos",
        "tags": [
          "videos"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "basic": {
        "scheme": "basic",
        "type": "http"
      },
      "customer_accessCode": {
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts.shutterstock.com/oauth/authorize",
            "scopes": {
              "collections.edit": "Grant the ability to create new collections, edit a collection, and modify the contents of a collection",
              "collections.view": "Grant read-only access to a collection and its contents.",
              "licenses.create": "Grant the ability to download and license media on behalf of the user.",
              "licenses.view": "Grant read-only access to a user's licenses.",
              "purchases.view": "Grant read-only access to a user's purchase history.",
              "user.view": "*Originally missing*"
            },
            "tokenUrl": "https://api.shutterstock.com/v2/oauth/access_token"
          }
        },
        "type": "oauth2",
        "x-shutterstock-realm": "customer"
      }
    },
    "x-string-formats": {
      "asset-id": {
        "format": "A Shutterstock asset ID that starts with a nonzero digit and has any number of other digits",
        "pattern": "^[1-9]\\d*$"
      },
      "asset-upload-id": {
        "format": "A Shutterstock upload ID consisting of the letter U followed by one or more other characters",
        "pattern": "^U\\w+$"
      },
      "country-code-2": {
        "format": "A two-character (ISO 3166 Alpha-2) country code",
        "pattern": "^(?:[A-Z]{2}|[a-z]{2})$"
      },
      "country-code-3": {
        "format": "A three-character (ISO 3166 Alpha-3) country code",
        "pattern": "^(?:[A-Z]{3}|[a-z]{3})$"
      },
      "date": {
        "format": "YYYY-MM-DD"
      },
      "date-time": {
        "format": "YYYY-MM-DDTHH:mm:ssZ"
      },
      "ipv4": {
        "format": "A valid IPv4 address"
      },
      "negated-country-code-2": {
        "format": "A NOT followed by a two-character (ISO 3166 Alpha-2) country code",
        "pattern": "^(NOT\\s)(?:[A-Z]{2}|[a-z]{2})$"
      },
      "uri": {
        "format": "A valid URI"
      }
    }
  }
}