package shared

type LandmarkTypeEnum string

const (
	LandmarkTypeEnumEyeLeft           LandmarkTypeEnum = "eyeLeft"
	LandmarkTypeEnumEyeRight          LandmarkTypeEnum = "eyeRight"
	LandmarkTypeEnumNose              LandmarkTypeEnum = "nose"
	LandmarkTypeEnumMouthLeft         LandmarkTypeEnum = "mouthLeft"
	LandmarkTypeEnumMouthRight        LandmarkTypeEnum = "mouthRight"
	LandmarkTypeEnumLeftEyeBrowLeft   LandmarkTypeEnum = "leftEyeBrowLeft"
	LandmarkTypeEnumLeftEyeBrowRight  LandmarkTypeEnum = "leftEyeBrowRight"
	LandmarkTypeEnumLeftEyeBrowUp     LandmarkTypeEnum = "leftEyeBrowUp"
	LandmarkTypeEnumRightEyeBrowLeft  LandmarkTypeEnum = "rightEyeBrowLeft"
	LandmarkTypeEnumRightEyeBrowRight LandmarkTypeEnum = "rightEyeBrowRight"
	LandmarkTypeEnumRightEyeBrowUp    LandmarkTypeEnum = "rightEyeBrowUp"
	LandmarkTypeEnumLeftEyeLeft       LandmarkTypeEnum = "leftEyeLeft"
	LandmarkTypeEnumLeftEyeRight      LandmarkTypeEnum = "leftEyeRight"
	LandmarkTypeEnumLeftEyeUp         LandmarkTypeEnum = "leftEyeUp"
	LandmarkTypeEnumLeftEyeDown       LandmarkTypeEnum = "leftEyeDown"
	LandmarkTypeEnumRightEyeLeft      LandmarkTypeEnum = "rightEyeLeft"
	LandmarkTypeEnumRightEyeRight     LandmarkTypeEnum = "rightEyeRight"
	LandmarkTypeEnumRightEyeUp        LandmarkTypeEnum = "rightEyeUp"
	LandmarkTypeEnumRightEyeDown      LandmarkTypeEnum = "rightEyeDown"
	LandmarkTypeEnumNoseLeft          LandmarkTypeEnum = "noseLeft"
	LandmarkTypeEnumNoseRight         LandmarkTypeEnum = "noseRight"
	LandmarkTypeEnumMouthUp           LandmarkTypeEnum = "mouthUp"
	LandmarkTypeEnumMouthDown         LandmarkTypeEnum = "mouthDown"
	LandmarkTypeEnumLeftPupil         LandmarkTypeEnum = "leftPupil"
	LandmarkTypeEnumRightPupil        LandmarkTypeEnum = "rightPupil"
	LandmarkTypeEnumUpperJawlineLeft  LandmarkTypeEnum = "upperJawlineLeft"
	LandmarkTypeEnumMidJawlineLeft    LandmarkTypeEnum = "midJawlineLeft"
	LandmarkTypeEnumChinBottom        LandmarkTypeEnum = "chinBottom"
	LandmarkTypeEnumMidJawlineRight   LandmarkTypeEnum = "midJawlineRight"
	LandmarkTypeEnumUpperJawlineRight LandmarkTypeEnum = "upperJawlineRight"
)
