package shared

type GoogleCloudDatalabelingV1beta1EvaluationConfig struct {
	BoundingBoxEvaluationOptions *GoogleCloudDatalabelingV1beta1BoundingBoxEvaluationOptions `json:"boundingBoxEvaluationOptions,omitempty"`
}
