{
  "swagger": "2.0",
  "info": {
    "title": "Tasks API",
    "x-serviceName": "tasks",
    "description": "Lets you manage your tasks and task lists.",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v1"
  },
  "host": "www.googleapis.com",
  "basePath": "/tasks/v1",
  "schemes": [
    "https"
  ],
  "paths": {
    "/users/@me/lists/{tasklist}": {
      "delete": {
        "description": "Deletes the authenticated user's specified task list.",
        "operationId": "tasks.tasklists.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ]
          }
        ],
        "tags": [
          "tasklists"
        ]
      },
      "get": {
        "description": "Returns the authenticated user's specified task list.",
        "operationId": "tasks.tasklists.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks",
              "https://www.googleapis.com/auth/tasks.readonly"
            ]
          }
        ],
        "tags": [
          "tasklists"
        ]
      },
      "patch": {
        "description": "Updates the authenticated user's specified task list. This method supports patch semantics.",
        "operationId": "tasks.tasklists.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ]
          }
        ],
        "tags": [
          "tasklists"
        ]
      },
      "put": {
        "description": "Updates the authenticated user's specified task list.",
        "operationId": "tasks.tasklists.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ]
          }
        ],
        "tags": [
          "tasklists"
        ]
      }
    },
    "/users/@me/lists": {
      "post": {
        "description": "Creates a new task list and adds it to the authenticated user's task lists.",
        "operationId": "tasks.tasklists.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ]
          }
        ],
        "tags": [
          "tasklists"
        ]
      },
      "get": {
        "description": "Returns all the authenticated user's task lists.",
        "operationId": "tasks.tasklists.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks",
              "https://www.googleapis.com/auth/tasks.readonly"
            ]
          }
        ],
        "tags": [
          "tasklists"
        ]
      }
    },
    "/lists/{tasklist}/clear": {
      "post": {
        "description": "Clears all completed tasks from the specified task list. The affected tasks will be marked as 'hidden' and no longer be returned by default when retrieving all tasks for a task list.",
        "operationId": "tasks.tasks.clear",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ]
          }
        ],
        "tags": [
          "tasks"
        ]
      }
    },
    "/lists/{tasklist}/tasks/{task}": {
      "delete": {
        "description": "Deletes the specified task from the task list.",
        "operationId": "tasks.tasks.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ]
          }
        ],
        "tags": [
          "tasks"
        ]
      },
      "get": {
        "description": "Returns the specified task.",
        "operationId": "tasks.tasks.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks",
              "https://www.googleapis.com/auth/tasks.readonly"
            ]
          }
        ],
        "tags": [
          "tasks"
        ]
      },
      "patch": {
        "description": "Updates the specified task. This method supports patch semantics.",
        "operationId": "tasks.tasks.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ]
          }
        ],
        "tags": [
          "tasks"
        ]
      },
      "put": {
        "description": "Updates the specified task.",
        "operationId": "tasks.tasks.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ]
          }
        ],
        "tags": [
          "tasks"
        ]
      }
    },
    "/lists/{tasklist}/tasks": {
      "post": {
        "description": "Creates a new task on the specified task list.",
        "operationId": "tasks.tasks.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ]
          }
        ],
        "tags": [
          "tasks"
        ]
      },
      "get": {
        "description": "Returns all tasks in the specified task list.",
        "operationId": "tasks.tasks.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks",
              "https://www.googleapis.com/auth/tasks.readonly"
            ]
          }
        ],
        "tags": [
          "tasks"
        ]
      }
    },
    "/lists/{tasklist}/tasks/{task}/move": {
      "post": {
        "description": "Moves the specified task to another position in the task list. This can include putting it as a child task under a new parent and/or move it to a different position among its sibling tasks.",
        "operationId": "tasks.tasks.move",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ]
          }
        ],
        "tags": [
          "tasks"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/tasks": "Manage your tasks",
        "https://www.googleapis.com/auth/tasks.readonly": "View your tasks"
      }
    }
  }
}