from .calendar_acl_delete import *
from .calendar_acl_get import *
from .calendar_acl_insert import *
from .calendar_acl_list import *
from .calendar_acl_patch import *
from .calendar_acl_update import *
from .calendar_acl_watch import *
from .calendar_calendarlist_delete import *
from .calendar_calendarlist_get import *
from .calendar_calendarlist_insert import *
from .calendar_calendarlist_list import *
from .calendar_calendarlist_patch import *
from .calendar_calendarlist_update import *
from .calendar_calendarlist_watch import *
from .calendar_calendars_clear import *
from .calendar_calendars_delete import *
from .calendar_calendars_get import *
from .calendar_calendars_insert import *
from .calendar_calendars_patch import *
from .calendar_calendars_update import *
from .calendar_channels_stop import *
from .calendar_colors_get import *
from .calendar_events_delete import *
from .calendar_events_get import *
from .calendar_events_import import *
from .calendar_events_insert import *
from .calendar_events_instances import *
from .calendar_events_list import *
from .calendar_events_move import *
from .calendar_events_patch import *
from .calendar_events_quickadd import *
from .calendar_events_update import *
from .calendar_events_watch import *
from .calendar_freebusy_query import *
from .calendar_settings_get import *
from .calendar_settings_list import *
from .calendar_settings_watch import *
