package shared

type ServerConfiguration struct {
	ActivityLogRetentionDays           *int32                     `json:"ActivityLogRetentionDays"`
	AutoDiscovery                      *bool                      `json:"AutoDiscovery"`
	AutoDiscoveryTracing               *bool                      `json:"AutoDiscoveryTracing"`
	BaseURL                            *string                    `json:"BaseUrl"`
	CachePath                          *string                    `json:"CachePath"`
	CertificatePassword                *string                    `json:"CertificatePassword"`
	CertificatePath                    *string                    `json:"CertificatePath"`
	CodecsUsed                         []string                   `json:"CodecsUsed"`
	ContentTypes                       []NameValuePair            `json:"ContentTypes"`
	CorsHosts                          []string                   `json:"CorsHosts"`
	DisableLiveTvChannelUserDataName   *bool                      `json:"DisableLiveTvChannelUserDataName"`
	DisablePluginImages                *bool                      `json:"DisablePluginImages"`
	DisplaySpecialsWithinSeasons       *bool                      `json:"DisplaySpecialsWithinSeasons"`
	EnableCaseSensitiveItemIds         *bool                      `json:"EnableCaseSensitiveItemIds"`
	EnableDashboardResponseCaching     *bool                      `json:"EnableDashboardResponseCaching"`
	EnableExternalContentInSuggestions *bool                      `json:"EnableExternalContentInSuggestions"`
	EnableFolderView                   *bool                      `json:"EnableFolderView"`
	EnableGroupingIntoCollections      *bool                      `json:"EnableGroupingIntoCollections"`
	EnableHTTPS                        *bool                      `json:"EnableHttps"`
	EnableIpv4                         *bool                      `json:"EnableIPV4"`
	EnableIpv6                         *bool                      `json:"EnableIPV6"`
	EnableMetrics                      *bool                      `json:"EnableMetrics"`
	EnableMultiSocketBinding           *bool                      `json:"EnableMultiSocketBinding"`
	EnableNewOmdbSupport               *bool                      `json:"EnableNewOmdbSupport"`
	EnableNormalizedItemByNameIds      *bool                      `json:"EnableNormalizedItemByNameIds"`
	EnableRemoteAccess                 *bool                      `json:"EnableRemoteAccess"`
	EnableSsdpTracing                  *bool                      `json:"EnableSSDPTracing"`
	EnableSimpleArtistDetection        *bool                      `json:"EnableSimpleArtistDetection"`
	EnableSlowResponseWarning          *bool                      `json:"EnableSlowResponseWarning"`
	EnableUPnP                         *bool                      `json:"EnableUPnP"`
	GatewayMonitorPeriod               *int32                     `json:"GatewayMonitorPeriod"`
	HdHomerunPortRange                 *string                    `json:"HDHomerunPortRange"`
	HTTPServerPortNumber               *int32                     `json:"HttpServerPortNumber"`
	HTTPSPortNumber                    *int32                     `json:"HttpsPortNumber"`
	IgnoreVirtualInterfaces            *bool                      `json:"IgnoreVirtualInterfaces"`
	ImageExtractionTimeoutMs           *int32                     `json:"ImageExtractionTimeoutMs"`
	ImageSavingConvention              *ImageSavingConventionEnum `json:"ImageSavingConvention"`
	IsPortAuthorized                   *bool                      `json:"IsPortAuthorized"`
	IsRemoteIPFilterBlacklist          *bool                      `json:"IsRemoteIPFilterBlacklist"`
	IsStartupWizardCompleted           *bool                      `json:"IsStartupWizardCompleted"`
	KnownProxies                       []string                   `json:"KnownProxies"`
	LibraryMetadataRefreshConcurrency  *int32                     `json:"LibraryMetadataRefreshConcurrency"`
	LibraryMonitorDelay                *int32                     `json:"LibraryMonitorDelay"`
	LibraryScanFanoutConcurrency       *int32                     `json:"LibraryScanFanoutConcurrency"`
	LocalNetworkAddresses              []string                   `json:"LocalNetworkAddresses"`
	LocalNetworkSubnets                []string                   `json:"LocalNetworkSubnets"`
	LogFileRetentionDays               *int32                     `json:"LogFileRetentionDays"`
	MaxAudiobookResume                 *int32                     `json:"MaxAudiobookResume"`
	MaxResumePct                       *int32                     `json:"MaxResumePct"`
	MetadataCountryCode                *string                    `json:"MetadataCountryCode"`
	MetadataNetworkPath                *string                    `json:"MetadataNetworkPath"`
	MetadataOptions                    []MetadataOptions          `json:"MetadataOptions"`
	MetadataPath                       *string                    `json:"MetadataPath"`
	MinAudiobookResume                 *int32                     `json:"MinAudiobookResume"`
	MinResumeDurationSeconds           *int32                     `json:"MinResumeDurationSeconds"`
	MinResumePct                       *int32                     `json:"MinResumePct"`
	PathSubstitutions                  []PathSubstitution         `json:"PathSubstitutions"`
	PluginRepositories                 []RepositoryInfo           `json:"PluginRepositories"`
	PreferredMetadataLanguage          *string                    `json:"PreferredMetadataLanguage"`
	PreviousVersion                    *Version                   `json:"PreviousVersion"`
	PreviousVersionStr                 *string                    `json:"PreviousVersionStr"`
	PublicHTTPSPort                    *int32                     `json:"PublicHttpsPort"`
	PublicPort                         *int32                     `json:"PublicPort"`
	PublishedServerURIBySubnet         []string                   `json:"PublishedServerUriBySubnet"`
	QuickConnectAvailable              *bool                      `json:"QuickConnectAvailable"`
	RemoteClientBitrateLimit           *int32                     `json:"RemoteClientBitrateLimit"`
	RemoteIPFilter                     []string                   `json:"RemoteIPFilter"`
	RemoveOldPlugins                   *bool                      `json:"RemoveOldPlugins"`
	RequireHTTPS                       *bool                      `json:"RequireHttps"`
	SsdpTracingFilter                  *string                    `json:"SSDPTracingFilter"`
	SaveMetadataHidden                 *bool                      `json:"SaveMetadataHidden"`
	ServerName                         *string                    `json:"ServerName"`
	SkipDeserializationForBasicTypes   *bool                      `json:"SkipDeserializationForBasicTypes"`
	SlowResponseThresholdMs            *int64                     `json:"SlowResponseThresholdMs"`
	SortRemoveCharacters               []string                   `json:"SortRemoveCharacters"`
	SortRemoveWords                    []string                   `json:"SortRemoveWords"`
	SortReplaceCharacters              []string                   `json:"SortReplaceCharacters"`
	TrustAllIp6Interfaces              *bool                      `json:"TrustAllIP6Interfaces"`
	UDPPortRange                       *string                    `json:"UDPPortRange"`
	UDPSendCount                       *int32                     `json:"UDPSendCount"`
	UDPSendDelay                       *int32                     `json:"UDPSendDelay"`
	UICulture                          *string                    `json:"UICulture"`
	UPnPCreateHTTPPortMap              *bool                      `json:"UPnPCreateHttpPortMap"`
	UninstalledPlugins                 []string                   `json:"UninstalledPlugins"`
	VirtualInterfaceNames              *string                    `json:"VirtualInterfaceNames"`
}
