package shared




type GoogleCloudVisionV1p1beta1FeatureTypeEnum string

const (
    GoogleCloudVisionV1p1beta1FeatureTypeEnumTypeUnspecified GoogleCloudVisionV1p1beta1FeatureTypeEnum = "TYPE_UNSPECIFIED"
GoogleCloudVisionV1p1beta1FeatureTypeEnumFaceDetection GoogleCloudVisionV1p1beta1FeatureTypeEnum = "FACE_DETECTION"
GoogleCloudVisionV1p1beta1FeatureTypeEnumLandmarkDetection GoogleCloudVisionV1p1beta1FeatureTypeEnum = "LANDMARK_DETECTION"
GoogleCloudVisionV1p1beta1FeatureTypeEnumLogoDetection GoogleCloudVisionV1p1beta1FeatureTypeEnum = "LOGO_DETECTION"
GoogleCloudVisionV1p1beta1FeatureTypeEnumLabelDetection GoogleCloudVisionV1p1beta1FeatureTypeEnum = "LABEL_DETECTION"
GoogleCloudVisionV1p1beta1FeatureTypeEnumTextDetection GoogleCloudVisionV1p1beta1FeatureTypeEnum = "TEXT_DETECTION"
GoogleCloudVisionV1p1beta1FeatureTypeEnumDocumentTextDetection GoogleCloudVisionV1p1beta1FeatureTypeEnum = "DOCUMENT_TEXT_DETECTION"
GoogleCloudVisionV1p1beta1FeatureTypeEnumSafeSearchDetection GoogleCloudVisionV1p1beta1FeatureTypeEnum = "SAFE_SEARCH_DETECTION"
GoogleCloudVisionV1p1beta1FeatureTypeEnumImageProperties GoogleCloudVisionV1p1beta1FeatureTypeEnum = "IMAGE_PROPERTIES"
GoogleCloudVisionV1p1beta1FeatureTypeEnumCropHints GoogleCloudVisionV1p1beta1FeatureTypeEnum = "CROP_HINTS"
GoogleCloudVisionV1p1beta1FeatureTypeEnumWebDetection GoogleCloudVisionV1p1beta1FeatureTypeEnum = "WEB_DETECTION"
GoogleCloudVisionV1p1beta1FeatureTypeEnumProductSearch GoogleCloudVisionV1p1beta1FeatureTypeEnum = "PRODUCT_SEARCH"
GoogleCloudVisionV1p1beta1FeatureTypeEnumObjectLocalization GoogleCloudVisionV1p1beta1FeatureTypeEnum = "OBJECT_LOCALIZATION"
)


type GoogleCloudVisionV1p1beta1Feature struct {
    MaxResults *int32 `json:"maxResults,omitempty"`
    Model *string `json:"model,omitempty"`
    Type *GoogleCloudVisionV1p1beta1FeatureTypeEnum `json:"type,omitempty"`
    
}

