# coding: utf-8

"""
    eDRV API

    edrv.io API Documentation

    The version of the OpenAPI document: v1
    Contact: hello@edrv.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_locations_request import PostLocationsRequest

class TestPostLocationsRequest(unittest.TestCase):
    """PostLocationsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostLocationsRequest:
        """Test PostLocationsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostLocationsRequest`
        """
        model = PostLocationsRequest()
        if include_optional:
            return PostLocationsRequest(
                active = True,
                address = openapi_client.models.post_drivers_request_address.postDrivers_request_address(
                    city = '', 
                    country = '', 
                    postal_code = '', 
                    street_and_number = '', ),
                chargestations = [
                    null
                    ],
                coordinates = openapi_client.models.patch_location_request_coordinates.patchLocation_request_coordinates(
                    latitude = 1.337, 
                    longitude = 1.337, ),
                operator_name = ''
            )
        else:
            return PostLocationsRequest(
                address = openapi_client.models.post_drivers_request_address.postDrivers_request_address(
                    city = '', 
                    country = '', 
                    postal_code = '', 
                    street_and_number = '', ),
                coordinates = openapi_client.models.patch_location_request_coordinates.patchLocation_request_coordinates(
                    latitude = 1.337, 
                    longitude = 1.337, ),
                operator_name = '',
        )
        """

    def testPostLocationsRequest(self):
        """Test PostLocationsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
