from .get_deletealarms import *
from .get_deletedashboards import *
from .get_deleteinsightrules import *
from .get_deletemetricstream import *
from .get_describealarmhistory import *
from .get_describealarms import *
from .get_describeinsightrules import *
from .get_disablealarmactions import *
from .get_disableinsightrules import *
from .get_enablealarmactions import *
from .get_enableinsightrules import *
from .get_getdashboard import *
from .get_getinsightrulereport import *
from .get_getmetricstream import *
from .get_getmetricwidgetimage import *
from .get_listdashboards import *
from .get_listmetricstreams import *
from .get_listtagsforresource import *
from .get_putdashboard import *
from .get_setalarmstate import *
from .get_startmetricstreams import *
from .get_stopmetricstreams import *
from .get_untagresource import *
from .post_deletealarms import *
from .post_deleteanomalydetector import *
from .post_deletedashboards import *
from .post_deleteinsightrules import *
from .post_deletemetricstream import *
from .post_describealarmhistory import *
from .post_describealarms import *
from .post_describealarmsformetric import *
from .post_describeanomalydetectors import *
from .post_describeinsightrules import *
from .post_disablealarmactions import *
from .post_disableinsightrules import *
from .post_enablealarmactions import *
from .post_enableinsightrules import *
from .post_getdashboard import *
from .post_getinsightrulereport import *
from .post_getmetricdata import *
from .post_getmetricstatistics import *
from .post_getmetricstream import *
from .post_getmetricwidgetimage import *
from .post_listdashboards import *
from .post_listmetrics import *
from .post_listmetricstreams import *
from .post_listtagsforresource import *
from .post_putanomalydetector import *
from .post_putcompositealarm import *
from .post_putdashboard import *
from .post_putinsightrule import *
from .post_putmetricalarm import *
from .post_putmetricdata import *
from .post_putmetricstream import *
from .post_setalarmstate import *
from .post_startmetricstreams import *
from .post_stopmetricstreams import *
from .post_tagresource import *
from .post_untagresource import *
