from .get_addclientidtoopenidconnectprovider import *
from .get_addroletoinstanceprofile import *
from .get_addusertogroup import *
from .get_attachgrouppolicy import *
from .get_attachrolepolicy import *
from .get_attachuserpolicy import *
from .get_changepassword import *
from .get_createaccesskey import *
from .get_createaccountalias import *
from .get_creategroup import *
from .get_createloginprofile import *
from .get_createpolicyversion import *
from .get_createservicelinkedrole import *
from .get_createservicespecificcredential import *
from .get_deactivatemfadevice import *
from .get_deleteaccesskey import *
from .get_deleteaccountalias import *
from .get_deleteaccountpasswordpolicy import *
from .get_deletegroup import *
from .get_deletegrouppolicy import *
from .get_deleteinstanceprofile import *
from .get_deleteloginprofile import *
from .get_deleteopenidconnectprovider import *
from .get_deletepolicy import *
from .get_deletepolicyversion import *
from .get_deleterole import *
from .get_deleterolepermissionsboundary import *
from .get_deleterolepolicy import *
from .get_deletesamlprovider import *
from .get_deleteservercertificate import *
from .get_deleteservicelinkedrole import *
from .get_deleteservicespecificcredential import *
from .get_deletesigningcertificate import *
from .get_deletesshpublickey import *
from .get_deleteuser import *
from .get_deleteuserpermissionsboundary import *
from .get_deleteuserpolicy import *
from .get_deletevirtualmfadevice import *
from .get_detachgrouppolicy import *
from .get_detachrolepolicy import *
from .get_detachuserpolicy import *
from .get_enablemfadevice import *
from .get_generatecredentialreport import *
from .get_generateorganizationsaccessreport import *
from .get_generateservicelastaccesseddetails import *
from .get_getaccesskeylastused import *
from .get_getaccountauthorizationdetails import *
from .get_getaccountpasswordpolicy import *
from .get_getaccountsummary import *
from .get_getcontextkeysforcustompolicy import *
from .get_getcontextkeysforprincipalpolicy import *
from .get_getcredentialreport import *
from .get_getgroup import *
from .get_getgrouppolicy import *
from .get_getinstanceprofile import *
from .get_getloginprofile import *
from .get_getopenidconnectprovider import *
from .get_getorganizationsaccessreport import *
from .get_getpolicy import *
from .get_getpolicyversion import *
from .get_getrole import *
from .get_getrolepolicy import *
from .get_getsamlprovider import *
from .get_getservercertificate import *
from .get_getservicelastaccesseddetails import *
from .get_getservicelastaccesseddetailswithentities import *
from .get_getservicelinkedroledeletionstatus import *
from .get_getsshpublickey import *
from .get_getuser import *
from .get_getuserpolicy import *
from .get_listaccesskeys import *
from .get_listaccountaliases import *
from .get_listattachedgrouppolicies import *
from .get_listattachedrolepolicies import *
from .get_listattacheduserpolicies import *
from .get_listentitiesforpolicy import *
from .get_listgrouppolicies import *
from .get_listgroups import *
from .get_listgroupsforuser import *
from .get_listinstanceprofiles import *
from .get_listinstanceprofilesforrole import *
from .get_listinstanceprofiletags import *
from .get_listmfadevices import *
from .get_listmfadevicetags import *
from .get_listopenidconnectproviders import *
from .get_listopenidconnectprovidertags import *
from .get_listpolicies import *
from .get_listpoliciesgrantingserviceaccess import *
from .get_listpolicytags import *
from .get_listpolicyversions import *
from .get_listrolepolicies import *
from .get_listroles import *
from .get_listroletags import *
from .get_listsamlproviders import *
from .get_listsamlprovidertags import *
from .get_listservercertificates import *
from .get_listservercertificatetags import *
from .get_listservicespecificcredentials import *
from .get_listsigningcertificates import *
from .get_listsshpublickeys import *
from .get_listuserpolicies import *
from .get_listusers import *
from .get_listusertags import *
from .get_listvirtualmfadevices import *
from .get_putgrouppolicy import *
from .get_putrolepermissionsboundary import *
from .get_putrolepolicy import *
from .get_putuserpermissionsboundary import *
from .get_putuserpolicy import *
from .get_removeclientidfromopenidconnectprovider import *
from .get_removerolefrominstanceprofile import *
from .get_removeuserfromgroup import *
from .get_resetservicespecificcredential import *
from .get_resyncmfadevice import *
from .get_setdefaultpolicyversion import *
from .get_setsecuritytokenservicepreferences import *
from .get_untaginstanceprofile import *
from .get_untagmfadevice import *
from .get_untagopenidconnectprovider import *
from .get_untagpolicy import *
from .get_untagrole import *
from .get_untagsamlprovider import *
from .get_untagservercertificate import *
from .get_untaguser import *
from .get_updateaccesskey import *
from .get_updateaccountpasswordpolicy import *
from .get_updateassumerolepolicy import *
from .get_updategroup import *
from .get_updateloginprofile import *
from .get_updateopenidconnectproviderthumbprint import *
from .get_updaterole import *
from .get_updateroledescription import *
from .get_updatesamlprovider import *
from .get_updateservercertificate import *
from .get_updateservicespecificcredential import *
from .get_updatesigningcertificate import *
from .get_updatesshpublickey import *
from .get_updateuser import *
from .get_uploadsigningcertificate import *
from .get_uploadsshpublickey import *
from .post_addclientidtoopenidconnectprovider import *
from .post_addroletoinstanceprofile import *
from .post_addusertogroup import *
from .post_attachgrouppolicy import *
from .post_attachrolepolicy import *
from .post_attachuserpolicy import *
from .post_changepassword import *
from .post_createaccesskey import *
from .post_createaccountalias import *
from .post_creategroup import *
from .post_createinstanceprofile import *
from .post_createloginprofile import *
from .post_createopenidconnectprovider import *
from .post_createpolicy import *
from .post_createpolicyversion import *
from .post_createrole import *
from .post_createsamlprovider import *
from .post_createservicelinkedrole import *
from .post_createservicespecificcredential import *
from .post_createuser import *
from .post_createvirtualmfadevice import *
from .post_deactivatemfadevice import *
from .post_deleteaccesskey import *
from .post_deleteaccountalias import *
from .post_deleteaccountpasswordpolicy import *
from .post_deletegroup import *
from .post_deletegrouppolicy import *
from .post_deleteinstanceprofile import *
from .post_deleteloginprofile import *
from .post_deleteopenidconnectprovider import *
from .post_deletepolicy import *
from .post_deletepolicyversion import *
from .post_deleterole import *
from .post_deleterolepermissionsboundary import *
from .post_deleterolepolicy import *
from .post_deletesamlprovider import *
from .post_deleteservercertificate import *
from .post_deleteservicelinkedrole import *
from .post_deleteservicespecificcredential import *
from .post_deletesigningcertificate import *
from .post_deletesshpublickey import *
from .post_deleteuser import *
from .post_deleteuserpermissionsboundary import *
from .post_deleteuserpolicy import *
from .post_deletevirtualmfadevice import *
from .post_detachgrouppolicy import *
from .post_detachrolepolicy import *
from .post_detachuserpolicy import *
from .post_enablemfadevice import *
from .post_generatecredentialreport import *
from .post_generateorganizationsaccessreport import *
from .post_generateservicelastaccesseddetails import *
from .post_getaccesskeylastused import *
from .post_getaccountauthorizationdetails import *
from .post_getaccountpasswordpolicy import *
from .post_getaccountsummary import *
from .post_getcontextkeysforcustompolicy import *
from .post_getcontextkeysforprincipalpolicy import *
from .post_getcredentialreport import *
from .post_getgroup import *
from .post_getgrouppolicy import *
from .post_getinstanceprofile import *
from .post_getloginprofile import *
from .post_getopenidconnectprovider import *
from .post_getorganizationsaccessreport import *
from .post_getpolicy import *
from .post_getpolicyversion import *
from .post_getrole import *
from .post_getrolepolicy import *
from .post_getsamlprovider import *
from .post_getservercertificate import *
from .post_getservicelastaccesseddetails import *
from .post_getservicelastaccesseddetailswithentities import *
from .post_getservicelinkedroledeletionstatus import *
from .post_getsshpublickey import *
from .post_getuser import *
from .post_getuserpolicy import *
from .post_listaccesskeys import *
from .post_listaccountaliases import *
from .post_listattachedgrouppolicies import *
from .post_listattachedrolepolicies import *
from .post_listattacheduserpolicies import *
from .post_listentitiesforpolicy import *
from .post_listgrouppolicies import *
from .post_listgroups import *
from .post_listgroupsforuser import *
from .post_listinstanceprofiles import *
from .post_listinstanceprofilesforrole import *
from .post_listinstanceprofiletags import *
from .post_listmfadevices import *
from .post_listmfadevicetags import *
from .post_listopenidconnectproviders import *
from .post_listopenidconnectprovidertags import *
from .post_listpolicies import *
from .post_listpoliciesgrantingserviceaccess import *
from .post_listpolicytags import *
from .post_listpolicyversions import *
from .post_listrolepolicies import *
from .post_listroles import *
from .post_listroletags import *
from .post_listsamlproviders import *
from .post_listsamlprovidertags import *
from .post_listservercertificates import *
from .post_listservercertificatetags import *
from .post_listservicespecificcredentials import *
from .post_listsigningcertificates import *
from .post_listsshpublickeys import *
from .post_listuserpolicies import *
from .post_listusers import *
from .post_listusertags import *
from .post_listvirtualmfadevices import *
from .post_putgrouppolicy import *
from .post_putrolepermissionsboundary import *
from .post_putrolepolicy import *
from .post_putuserpermissionsboundary import *
from .post_putuserpolicy import *
from .post_removeclientidfromopenidconnectprovider import *
from .post_removerolefrominstanceprofile import *
from .post_removeuserfromgroup import *
from .post_resetservicespecificcredential import *
from .post_resyncmfadevice import *
from .post_setdefaultpolicyversion import *
from .post_setsecuritytokenservicepreferences import *
from .post_simulatecustompolicy import *
from .post_simulateprincipalpolicy import *
from .post_taginstanceprofile import *
from .post_tagmfadevice import *
from .post_tagopenidconnectprovider import *
from .post_tagpolicy import *
from .post_tagrole import *
from .post_tagsamlprovider import *
from .post_tagservercertificate import *
from .post_taguser import *
from .post_untaginstanceprofile import *
from .post_untagmfadevice import *
from .post_untagopenidconnectprovider import *
from .post_untagpolicy import *
from .post_untagrole import *
from .post_untagsamlprovider import *
from .post_untagservercertificate import *
from .post_untaguser import *
from .post_updateaccesskey import *
from .post_updateaccountpasswordpolicy import *
from .post_updateassumerolepolicy import *
from .post_updategroup import *
from .post_updateloginprofile import *
from .post_updateopenidconnectproviderthumbprint import *
from .post_updaterole import *
from .post_updateroledescription import *
from .post_updatesamlprovider import *
from .post_updateservercertificate import *
from .post_updateservicespecificcredential import *
from .post_updatesigningcertificate import *
from .post_updatesshpublickey import *
from .post_updateuser import *
from .post_uploadservercertificate import *
from .post_uploadsigningcertificate import *
from .post_uploadsshpublickey import *
