package shared

type FirewallRuleGroupAssociationStatusEnum string

const (
	FirewallRuleGroupAssociationStatusEnumComplete FirewallRuleGroupAssociationStatusEnum = "COMPLETE"
	FirewallRuleGroupAssociationStatusEnumDeleting FirewallRuleGroupAssociationStatusEnum = "DELETING"
	FirewallRuleGroupAssociationStatusEnumUpdating FirewallRuleGroupAssociationStatusEnum = "UPDATING"
)
