swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /consumersurveys/v2
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: 'Creates and conducts surveys, lists the surveys that an authenticated user owns, and retrieves survey results and information about specified surveys.'
  title: Consumer Surveys
  version: v2
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    format: google
    url: 'https://www.googleapis.com/discovery/v1/apis/consumersurveys/v2/rest'
    version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: consumersurveys
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/consumersurveys': View and edit your surveys and results
      'https://www.googleapis.com/auth/consumersurveys.readonly': View the results for your surveys
      'https://www.googleapis.com/auth/userinfo.email': View your email address
    type: oauth2
tags:
  - name: results
  - name: surveys
paths:
  /surveys:
    get:
      description: Lists the surveys owned by the authenticated user.
      operationId: consumersurveys.surveys.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/consumersurveys'
        - Oauth2:
            - 'https://www.googleapis.com/auth/consumersurveys.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/userinfo.email'
      tags:
        - surveys
    post:
      description: Creates a survey.
      operationId: consumersurveys.surveys.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/consumersurveys'
        - Oauth2:
            - 'https://www.googleapis.com/auth/userinfo.email'
      tags:
        - surveys
  '/surveys/{resourceId}/start':
    post:
      description: Begins running a survey.
      operationId: consumersurveys.surveys.start
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/consumersurveys'
        - Oauth2:
            - 'https://www.googleapis.com/auth/userinfo.email'
      tags:
        - surveys
  '/surveys/{resourceId}/stop':
    post:
      description: Stops a running survey.
      operationId: consumersurveys.surveys.stop
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/consumersurveys'
        - Oauth2:
            - 'https://www.googleapis.com/auth/userinfo.email'
      tags:
        - surveys
  '/surveys/{surveyUrlId}':
    get:
      description: Retrieves information about the specified survey.
      operationId: consumersurveys.surveys.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/consumersurveys'
        - Oauth2:
            - 'https://www.googleapis.com/auth/consumersurveys.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/userinfo.email'
      tags:
        - surveys
    put:
      description: Updates a survey. Currently the only property that can be updated is the owners property.
      operationId: consumersurveys.surveys.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/consumersurveys'
        - Oauth2:
            - 'https://www.googleapis.com/auth/userinfo.email'
      tags:
        - surveys
  '/surveys/{surveyUrlId}/results':
    get:
      description: Retrieves any survey results that have been produced so far. Results are formatted as an Excel file.
      operationId: consumersurveys.results.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/consumersurveys'
        - Oauth2:
            - 'https://www.googleapis.com/auth/consumersurveys.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/userinfo.email'
      tags:
        - results