swagger: '2.0'
schemes:
  - https
host: sourcerepo.googleapis.com
basePath: /
x-hasEquivalentPaths: true
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Access source code repositories hosted by Google.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Cloud Source Repositories
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-apisguru-categories:
    - developer_tools
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.6.0
      format: google
      url: 'https://sourcerepo.googleapis.com/$discovery/rest?version=v1'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: sourcerepo
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/cloud-platform': View and manage your data across Google Cloud Platform services
      'https://www.googleapis.com/auth/source.full_control': Manage your source code repositories
      'https://www.googleapis.com/auth/source.read_only': View the contents of your source code repositories
      'https://www.googleapis.com/auth/source.read_write': Manage the contents of your source code repositories
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/cloud-platform': View and manage your data across Google Cloud Platform services
      'https://www.googleapis.com/auth/source.full_control': Manage your source code repositories
      'https://www.googleapis.com/auth/source.read_only': View the contents of your source code repositories
      'https://www.googleapis.com/auth/source.read_write': Manage the contents of your source code repositories
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: projects
paths:
  '/v1/{name}':
    delete:
      description: Deletes a repo.
      operationId: sourcerepo.projects.repos.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.full_control'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.full_control'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.read_only'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.read_only'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.read_write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.read_write'
      tags:
        - projects
    get:
      description: Returns information about a repo.
      operationId: sourcerepo.projects.repos.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.full_control'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.full_control'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.read_only'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.read_only'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.read_write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.read_write'
      tags:
        - projects
  '/v1/{name}/repos':
    get:
      description: |-
        Returns all repos belonging to a project. The sizes of the repos are
        not set by ListRepos.  To get the size of a repo, use GetRepo.
      operationId: sourcerepo.projects.repos.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.full_control'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.full_control'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.read_only'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.read_only'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.read_write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.read_write'
      tags:
        - projects
  '/v1/{parent}/repos':
    post:
      description: |-
        Creates a repo in the given project with the given name.

        If the named repository already exists, `CreateRepo` returns
        `ALREADY_EXISTS`.
      operationId: sourcerepo.projects.repos.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.full_control'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.full_control'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.read_only'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.read_only'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.read_write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.read_write'
      tags:
        - projects
  '/v1/{resource}:getIamPolicy':
    get:
      description: |-
        Gets the access control policy for a resource.
        Returns an empty policy if the resource exists and does not have a policy
        set.
      operationId: sourcerepo.projects.repos.getIamPolicy
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.full_control'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.full_control'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.read_only'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.read_only'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.read_write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.read_write'
      tags:
        - projects
  '/v1/{resource}:setIamPolicy':
    post:
      description: |-
        Sets the access control policy on the specified resource. Replaces any
        existing policy.
      operationId: sourcerepo.projects.repos.setIamPolicy
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.full_control'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.full_control'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.read_only'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.read_only'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.read_write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.read_write'
      tags:
        - projects
  '/v1/{resource}:testIamPermissions':
    post:
      description: |-
        Returns permissions that a caller has on the specified resource.
        If the resource does not exist, this will return an empty set of
        permissions, not a NOT_FOUND error.
      operationId: sourcerepo.projects.repos.testIamPermissions
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.full_control'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.full_control'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.read_only'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.read_only'
        - Oauth2:
            - 'https://www.googleapis.com/auth/source.read_write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/source.read_write'
      tags:
        - projects