swagger: '2.0'
schemes:
  - https
host: youtubereporting.googleapis.com
basePath: /
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Schedules reporting jobs containing your YouTube Analytics data and downloads the resulting bulk data reports in the form of CSV files.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: YouTube Reporting
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-apisguru-categories:
    - analytics
  x-logo:
    url: 'https://pbs.twimg.com/profile_images/902547949103841281/TmdokZcM_400x400.jpg'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://youtubereporting.googleapis.com/$discovery/rest?version=v1'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: youtubereporting
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/yt-analytics-monetary.readonly': View monetary and non-monetary YouTube Analytics reports for your YouTube content
      'https://www.googleapis.com/auth/yt-analytics.readonly': View YouTube Analytics reports for your YouTube content
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/yt-analytics-monetary.readonly': View monetary and non-monetary YouTube Analytics reports for your YouTube content
      'https://www.googleapis.com/auth/yt-analytics.readonly': View YouTube Analytics reports for your YouTube content
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: jobs
  - name: media
  - name: reportTypes
paths:
  /v1/jobs:
    get:
      description: Lists jobs.
      operationId: youtubereporting.jobs.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
      tags:
        - jobs
    post:
      description: Creates a job and returns it.
      operationId: youtubereporting.jobs.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
      tags:
        - jobs
  '/v1/jobs/{jobId}':
    delete:
      description: Deletes a job.
      operationId: youtubereporting.jobs.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
      tags:
        - jobs
    get:
      description: Gets a job.
      operationId: youtubereporting.jobs.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
      tags:
        - jobs
  '/v1/jobs/{jobId}/reports':
    get:
      description: |-
        Lists reports created by a specific job.
        Returns NOT_FOUND if the job does not exist.
      operationId: youtubereporting.jobs.reports.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
      tags:
        - jobs
  '/v1/jobs/{jobId}/reports/{reportId}':
    get:
      description: Gets the metadata of a specific report.
      operationId: youtubereporting.jobs.reports.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
      tags:
        - jobs
  '/v1/media/{resourceName}':
    get:
      description: |-
        Method for media download. Download is supported
        on the URI `/v1/media/{+name}?alt=media`.
      operationId: youtubereporting.media.download
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
      tags:
        - media
  /v1/reportTypes:
    get:
      description: Lists report types.
      operationId: youtubereporting.reportTypes.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
      tags:
        - reportTypes