swagger: '2.0'
schemes:
  - https
host: youtubereporting.googleapis.com
basePath: /
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: 'An API to schedule reporting jobs and download the resulting bulk data reports about YouTube channels, videos etc. in the form of CSV files.'
  title: YouTube Reporting
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    format: google
    url: 'https://www.googleapis.com/discovery/v1/apis/youtubereporting/v1/rest'
    version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: youtubereporting
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/yt-analytics-monetary.readonly': View monetary and non-monetary YouTube Analytics reports for your YouTube content
      'https://www.googleapis.com/auth/yt-analytics.readonly': View YouTube Analytics reports for your YouTube content
    type: oauth2
paths:
  /v1/jobs:
    get:
      description: Lists jobs.
      operationId: youtubereporting.jobs.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
      tags:
        - jobs
    post:
      description: Creates a job and returns it.
      operationId: youtubereporting.jobs.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
      tags:
        - jobs
  '/v1/jobs/{jobId}':
    delete:
      description: Deletes a job.
      operationId: youtubereporting.jobs.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
      tags:
        - jobs
    get:
      description: Gets a job.
      operationId: youtubereporting.jobs.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
      tags:
        - jobs
  '/v1/jobs/{jobId}/reports':
    get:
      description: Lists reports created by a specific job. Returns NOT_FOUND if the job does not exist.
      operationId: youtubereporting.jobs.reports.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
      tags:
        - jobs
  '/v1/jobs/{jobId}/reports/{reportId}':
    get:
      description: Gets the metadata of a specific report.
      operationId: youtubereporting.jobs.reports.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
      tags:
        - jobs
  '/v1/media/{resourceName}':
    get:
      description: 'Method for media download. Download is supported on the URI `/v1/media/{+name}?alt=media`.'
      operationId: youtubereporting.media.download
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
      tags:
        - media
  /v1/reportTypes:
    get:
      description: Lists report types.
      operationId: youtubereporting.reportTypes.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/yt-analytics-monetary.readonly'
            - 'https://www.googleapis.com/auth/yt-analytics.readonly'
      tags:
        - reportTypes