# coding: utf-8

"""
    Metadata API

    The Metadata API has operations that retrieve configuration details pertaining to the different eBay marketplaces. In addition to marketplace information, the API also has operations that get information that helps sellers list items on eBay.

    The version of the OpenAPI document: v1.6.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.extended_producer_responsibility import ExtendedProducerResponsibility

class TestExtendedProducerResponsibility(unittest.TestCase):
    """ExtendedProducerResponsibility unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExtendedProducerResponsibility:
        """Test ExtendedProducerResponsibility
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExtendedProducerResponsibility`
        """
        model = ExtendedProducerResponsibility()
        if include_optional:
            return ExtendedProducerResponsibility(
                enabled_for_variations = True,
                name = '',
                usage = ''
            )
        else:
            return ExtendedProducerResponsibility(
        )
        """

    def testExtendedProducerResponsibility(self):
        """Test ExtendedProducerResponsibility"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
