{
  "swagger": "2.0",
  "info": {
    "title": "Webmaster Tools API",
    "x-serviceName": "webmasters",
    "description": "Lets you view Google Webmaster Tools data for your verified sites.",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v3",
    "x-providerName": "googleapis.com",
    "x-origin": {
      "format": "google",
      "version": "v1",
      "url": "https://www.googleapis.com/discovery/v1/apis/webmasters/v3/rest"
    },
    "x-logo": "https://www.google.com/images/srpr/logo11w.png"
  },
  "host": "www.googleapis.com",
  "basePath": "/webmasters/v3",
  "schemes": [
    "https"
  ],
  "paths": {
    "/sites/{siteUrl}/searchAnalytics/query": {
      "post": {
        "description": "[LIMITED ACCESS]\n\nQuery your data with filters and parameters that you define. Returns zero or more rows grouped by the row keys that you define. You must define a date range of one or more days.\n\nWhen date is one of the group by values, any days without data are omitted from the result list. If you need to know which days have data, issue a broad date range query grouped by date for any metric, and see which day rows are returned.",
        "operationId": "webmasters.searchanalytics.query",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters",
              "https://www.googleapis.com/auth/webmasters.readonly"
            ]
          }
        ],
        "tags": [
          "searchanalytics"
        ]
      }
    },
    "/sites/{siteUrl}/sitemaps/{feedpath}": {
      "delete": {
        "description": "Deletes a sitemap from this site.",
        "operationId": "webmasters.sitemaps.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters"
            ]
          }
        ],
        "tags": [
          "sitemaps"
        ]
      },
      "get": {
        "description": "Retrieves information about a specific sitemap.",
        "operationId": "webmasters.sitemaps.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters",
              "https://www.googleapis.com/auth/webmasters.readonly"
            ]
          }
        ],
        "tags": [
          "sitemaps"
        ]
      },
      "put": {
        "description": "Submits a sitemap for a site.",
        "operationId": "webmasters.sitemaps.submit",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters"
            ]
          }
        ],
        "tags": [
          "sitemaps"
        ]
      }
    },
    "/sites/{siteUrl}/sitemaps": {
      "get": {
        "description": "Lists the sitemaps-entries submitted for this site, or included in the sitemap index file (if sitemapIndex is specified in the request).",
        "operationId": "webmasters.sitemaps.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters",
              "https://www.googleapis.com/auth/webmasters.readonly"
            ]
          }
        ],
        "tags": [
          "sitemaps"
        ]
      }
    },
    "/sites/{siteUrl}": {
      "put": {
        "description": "Adds a site to the set of the user's sites in Webmaster Tools.",
        "operationId": "webmasters.sites.add",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters"
            ]
          }
        ],
        "tags": [
          "sites"
        ]
      },
      "delete": {
        "description": "Removes a site from the set of the user's Webmaster Tools sites.",
        "operationId": "webmasters.sites.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters"
            ]
          }
        ],
        "tags": [
          "sites"
        ]
      },
      "get": {
        "description": "Retrieves information about specific site.",
        "operationId": "webmasters.sites.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters",
              "https://www.googleapis.com/auth/webmasters.readonly"
            ]
          }
        ],
        "tags": [
          "sites"
        ]
      }
    },
    "/sites": {
      "get": {
        "description": "Lists the user's Webmaster Tools sites.",
        "operationId": "webmasters.sites.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters",
              "https://www.googleapis.com/auth/webmasters.readonly"
            ]
          }
        ],
        "tags": [
          "sites"
        ]
      }
    },
    "/sites/{siteUrl}/urlCrawlErrorsCounts/query": {
      "get": {
        "description": "Retrieves a time series of the number of URL crawl errors per error category and platform.",
        "operationId": "webmasters.urlcrawlerrorscounts.query",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters",
              "https://www.googleapis.com/auth/webmasters.readonly"
            ]
          }
        ],
        "tags": [
          "urlcrawlerrorscounts"
        ]
      }
    },
    "/sites/{siteUrl}/urlCrawlErrorsSamples/{url}": {
      "get": {
        "description": "Retrieves details about crawl errors for a site's sample URL.",
        "operationId": "webmasters.urlcrawlerrorssamples.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters",
              "https://www.googleapis.com/auth/webmasters.readonly"
            ]
          }
        ],
        "tags": [
          "urlcrawlerrorssamples"
        ]
      },
      "delete": {
        "description": "Marks the provided site's sample URL as fixed, and removes it from the samples list.",
        "operationId": "webmasters.urlcrawlerrorssamples.markAsFixed",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters"
            ]
          }
        ],
        "tags": [
          "urlcrawlerrorssamples"
        ]
      }
    },
    "/sites/{siteUrl}/urlCrawlErrorsSamples": {
      "get": {
        "description": "Lists a site's sample URLs for the specified crawl error category and platform.",
        "operationId": "webmasters.urlcrawlerrorssamples.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/webmasters",
              "https://www.googleapis.com/auth/webmasters.readonly"
            ]
          }
        ],
        "tags": [
          "urlcrawlerrorssamples"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/webmasters": "View and modify Webmaster Tools data for your verified sites",
        "https://www.googleapis.com/auth/webmasters.readonly": "View Webmaster Tools data for your verified sites"
      }
    }
  }
}