swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /apps/reseller/v1
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Creates and manages your customers and their subscriptions.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Enterprise Apps Reseller
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-apisguru-categories:
    - enterprise
  x-logo:
    url: 'https://www.gstatic.com/images/icons/material/product/2x/admin_64dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/reseller/v1/rest'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: reseller
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/apps.order': Manage users on your domain
      'https://www.googleapis.com/auth/apps.order.readonly': Manage users on your domain
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/apps.order': Manage users on your domain
      'https://www.googleapis.com/auth/apps.order.readonly': Manage users on your domain
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: customers
  - name: resellernotify
  - name: subscriptions
paths:
  /customers:
    post:
      description: Order a new customer's account.
      operationId: reseller.customers.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order'
      tags:
        - customers
  '/customers/{customerId}':
    get:
      description: Get a customer account.
      operationId: reseller.customers.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order'
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order.readonly'
      tags:
        - customers
    patch:
      description: Update a customer account's settings. This method supports patch semantics.
      operationId: reseller.customers.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order'
      tags:
        - customers
    put:
      description: Update a customer account's settings.
      operationId: reseller.customers.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order'
      tags:
        - customers
  '/customers/{customerId}/subscriptions':
    post:
      description: Create or transfer a subscription.
      operationId: reseller.subscriptions.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order'
      tags:
        - subscriptions
  '/customers/{customerId}/subscriptions/{subscriptionId}':
    delete:
      description: 'Cancel, suspend or transfer a subscription to direct.'
      operationId: reseller.subscriptions.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order'
      tags:
        - subscriptions
    get:
      description: Get a specific subscription.
      operationId: reseller.subscriptions.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order'
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order.readonly'
      tags:
        - subscriptions
  '/customers/{customerId}/subscriptions/{subscriptionId}/activate':
    post:
      description: Activates a subscription previously suspended by the reseller
      operationId: reseller.subscriptions.activate
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order'
      tags:
        - subscriptions
  '/customers/{customerId}/subscriptions/{subscriptionId}/changePlan':
    post:
      description: Update a subscription plan. Use this method to update a plan for a 30-day trial or a flexible plan subscription to an annual commitment plan with monthly or yearly payments.
      operationId: reseller.subscriptions.changePlan
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order'
      tags:
        - subscriptions
  '/customers/{customerId}/subscriptions/{subscriptionId}/changeRenewalSettings':
    post:
      description: Update a user license's renewal settings. This is applicable for accounts with annual commitment plans only.
      operationId: reseller.subscriptions.changeRenewalSettings
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order'
      tags:
        - subscriptions
  '/customers/{customerId}/subscriptions/{subscriptionId}/changeSeats':
    post:
      description: Update a subscription's user license settings.
      operationId: reseller.subscriptions.changeSeats
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order'
      tags:
        - subscriptions
  '/customers/{customerId}/subscriptions/{subscriptionId}/startPaidService':
    post:
      description: Immediately move a 30-day free trial subscription to a paid service subscription.
      operationId: reseller.subscriptions.startPaidService
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order'
      tags:
        - subscriptions
  '/customers/{customerId}/subscriptions/{subscriptionId}/suspend':
    post:
      description: Suspends an active subscription.
      operationId: reseller.subscriptions.suspend
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order'
      tags:
        - subscriptions
  /resellernotify/getwatchdetails:
    get:
      description: Returns all the details of the watch corresponding to the reseller.
      operationId: reseller.resellernotify.getwatchdetails
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order'
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order.readonly'
      tags:
        - resellernotify
  /resellernotify/register:
    post:
      description: Registers a Reseller for receiving notifications.
      operationId: reseller.resellernotify.register
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order'
      tags:
        - resellernotify
  /resellernotify/unregister:
    post:
      description: Unregisters a Reseller for receiving notifications.
      operationId: reseller.resellernotify.unregister
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order'
      tags:
        - resellernotify
  /subscriptions:
    get:
      description: 'List of subscriptions managed by the reseller. The list can be all subscriptions, all of a customer''s subscriptions, or all of a customer''s transferable subscriptions.'
      operationId: reseller.subscriptions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order'
        - Oauth2:
            - 'https://www.googleapis.com/auth/apps.order.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/apps.order.readonly'
      tags:
        - subscriptions