# coding: utf-8

"""
    ConsumptionManagementClient

    Consumption management client provides access to consumption resources for Azure Enterprise Subscriptions.

    The version of the OpenAPI document: 2019-10-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ModernUsageDetailProperties(BaseModel):
    """
    The properties of the usage detail.
    """ # noqa: E501
    additional_info: Optional[StrictStr] = Field(default=None, description="Additional details of this usage item. Use this field to get usage line item specific details such as the actual VM Size (ServiceType) or the ratio in which the reservation discount is applied.", alias="additionalInfo")
    billing_account_id: Optional[StrictStr] = Field(default=None, description="Billing Account identifier.", alias="billingAccountId")
    billing_account_name: Optional[StrictStr] = Field(default=None, description="Name of the Billing Account.", alias="billingAccountName")
    billing_currency_code: Optional[StrictStr] = Field(default=None, description="The currency defining the billed cost.", alias="billingCurrencyCode")
    billing_period_end_date: Optional[datetime] = Field(default=None, description="Billing Period End Date as in the invoice.", alias="billingPeriodEndDate")
    billing_period_start_date: Optional[datetime] = Field(default=None, description="Billing Period Start Date as in the invoice.", alias="billingPeriodStartDate")
    billing_profile_id: Optional[StrictStr] = Field(default=None, description="Identifier for the billing profile that groups costs across invoices in the a singular billing currency across across the customers who have onboarded the Microsoft customer agreement and the customers in CSP who have made entitlement purchases like SaaS, Marketplace, RI, etc.", alias="billingProfileId")
    billing_profile_name: Optional[StrictStr] = Field(default=None, description="Name of the billing profile that groups costs across invoices in the a singular billing currency across across the customers who have onboarded the Microsoft customer agreement and the customers in CSP who have made entitlement purchases like SaaS, Marketplace, RI, etc.", alias="billingProfileName")
    charge_type: Optional[StrictStr] = Field(default=None, description="Indicates a charge represents credits, usage, a Marketplace purchase, a reservation fee, or a refund.", alias="chargeType")
    consumed_service: Optional[StrictStr] = Field(default=None, description="Consumed service name. Name of the azure resource provider that emits the usage or was purchased. This value is not provided for marketplace usage.", alias="consumedService")
    cost_center: Optional[StrictStr] = Field(default=None, description="The cost center of this department if it is a department and a cost center is provided.", alias="costCenter")
    cost_in_billing_currency: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="ExtendedCost or blended cost before tax in billed currency.", alias="costInBillingCurrency")
    cost_in_pricing_currency: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="ExtendedCost or blended cost before tax in pricing currency to correlate with prices.", alias="costInPricingCurrency")
    cost_in_usd: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Estimated extendedCost or blended cost before tax in USD.", alias="costInUSD")
    customer_name: Optional[StrictStr] = Field(default=None, description="Name of the customer's AAD tenant.", alias="customerName")
    customer_tenant_id: Optional[StrictStr] = Field(default=None, description="Identifier of the customer's AAD tenant.", alias="customerTenantId")
    var_date: Optional[datetime] = Field(default=None, description="Date for the usage record.", alias="date")
    exchange_rate: Optional[StrictStr] = Field(default=None, description="Exchange rate used in conversion from pricing currency to billing currency.", alias="exchangeRate")
    exchange_rate_date: Optional[datetime] = Field(default=None, description="Date on which exchange rate used in conversion from pricing currency to billing currency.", alias="exchangeRateDate")
    exchange_rate_pricing_to_billing: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Exchange Rate from pricing currency to billing currency.", alias="exchangeRatePricingToBilling")
    frequency: Optional[StrictStr] = Field(default=None, description="Indicates how frequently this charge will occur. OneTime for purchases which only happen once, Monthly for fees which recur every month, and UsageBased for charges based on how much a service is used.")
    instance_name: Optional[StrictStr] = Field(default=None, description="Instance Name.", alias="instanceName")
    invoice_id: Optional[StrictStr] = Field(default=None, description="Invoice ID as on the invoice where the specific transaction appears.", alias="invoiceId")
    invoice_section_id: Optional[StrictStr] = Field(default=None, description="Identifier of the project that is being charged in the invoice. Not applicable for Microsoft Customer Agreements onboarded by partners.", alias="invoiceSectionId")
    invoice_section_name: Optional[StrictStr] = Field(default=None, description="Name of the project that is being charged in the invoice. Not applicable for Microsoft Customer Agreements onboarded by partners.", alias="invoiceSectionName")
    is_azure_credit_eligible: Optional[StrictBool] = Field(default=None, description="Determines if the cost is eligible to be paid for using Azure credits.", alias="isAzureCreditEligible")
    market_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Market Price that's charged for the usage.", alias="marketPrice")
    meter_category: Optional[StrictStr] = Field(default=None, description="Identifies the top-level service for the usage.", alias="meterCategory")
    meter_id: Optional[StrictStr] = Field(default=None, description="The meter id (GUID). Not available for marketplace. For reserved instance this represents the primary meter for which the reservation was purchased. For the actual VM Size for which the reservation is purchased see productOrderName.", alias="meterId")
    meter_name: Optional[StrictStr] = Field(default=None, description="Identifies the name of the meter against which consumption is measured.", alias="meterName")
    meter_region: Optional[StrictStr] = Field(default=None, description="Identifies the location of the datacenter for certain services that are priced based on datacenter location.", alias="meterRegion")
    meter_sub_category: Optional[StrictStr] = Field(default=None, description="Defines the type or sub-category of Azure service that can affect the rate.", alias="meterSubCategory")
    partner_earned_credit_applied: Optional[StrictStr] = Field(default=None, description="Flag to indicate if partner earned credit has been applied or not.", alias="partnerEarnedCreditApplied")
    partner_earned_credit_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Rate of discount applied if there is a partner earned credit (PEC) based on partner admin link access.", alias="partnerEarnedCreditRate")
    partner_name: Optional[StrictStr] = Field(default=None, description="Name of the partner' AAD tenant.", alias="partnerName")
    partner_tenant_id: Optional[StrictStr] = Field(default=None, description="Identifier for the partner's AAD tenant.", alias="partnerTenantId")
    payg_cost_in_billing_currency: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The amount of PayG cost before tax in billing currency.", alias="paygCostInBillingCurrency")
    payg_cost_in_usd: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The amount of PayG cost before tax in US Dollar currency.", alias="paygCostInUSD")
    previous_invoice_id: Optional[StrictStr] = Field(default=None, description="Reference to an original invoice there is a refund (negative cost). This is populated only when there is a refund.", alias="previousInvoiceId")
    pricing_currency_code: Optional[StrictStr] = Field(default=None, description="Pricing Billing Currency.", alias="pricingCurrencyCode")
    product: Optional[StrictStr] = Field(default=None, description="Name of the product that has accrued charges by consumption or purchase as listed in the invoice. Not available for Marketplace.")
    product_identifier: Optional[StrictStr] = Field(default=None, description="Identifer for the product that has accrued charges by consumption or purchase . This is the concatenated key of productId and SKuId in partner center.", alias="productIdentifier")
    product_order_id: Optional[StrictStr] = Field(default=None, description="The identifier for the asset or Azure plan name that the subscription belongs to. For example: Azure Plan. For reservations this is the Reservation Order ID.", alias="productOrderId")
    product_order_name: Optional[StrictStr] = Field(default=None, description="Product Order Name. For reservations this is the SKU that was purchased.", alias="productOrderName")
    publisher_id: Optional[StrictStr] = Field(default=None, description="Publisher Id.", alias="publisherId")
    publisher_name: Optional[StrictStr] = Field(default=None, description="Name of the publisher of the service including Microsoft or Third Party publishers.", alias="publisherName")
    publisher_type: Optional[StrictStr] = Field(default=None, description="Type of publisher that identifies if the publisher is first party, third party reseller or third party agency.", alias="publisherType")
    quantity: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Measure the quantity purchased or consumed.The amount of the meter used during the billing period.")
    reseller_mpn_id: Optional[StrictStr] = Field(default=None, description="MPNId for the reseller associated with the subscription.", alias="resellerMpnId")
    reseller_name: Optional[StrictStr] = Field(default=None, description="Reseller Name.", alias="resellerName")
    reservation_id: Optional[StrictStr] = Field(default=None, description="ARM resource id of the reservation. Only applies to records relevant to reservations.", alias="reservationId")
    reservation_name: Optional[StrictStr] = Field(default=None, description="User provided display name of the reservation. Last known name for a particular day is populated in the daily data. Only applies to records relevant to reservations.", alias="reservationName")
    resource_group: Optional[StrictStr] = Field(default=None, description="Name of the Azure resource group used for cohesive lifecycle management of resources.", alias="resourceGroup")
    resource_location: Optional[StrictStr] = Field(default=None, description="Name of the resource location.", alias="resourceLocation")
    resource_location_normalized: Optional[StrictStr] = Field(default=None, description="Resource Location Normalized.", alias="resourceLocationNormalized")
    service_family: Optional[StrictStr] = Field(default=None, description="List the service family for the product purchased or charged (Example: Storage ; Compute).", alias="serviceFamily")
    service_info1: Optional[StrictStr] = Field(default=None, description="Service Info 1.", alias="serviceInfo1")
    service_info2: Optional[StrictStr] = Field(default=None, description="Service Info 2.", alias="serviceInfo2")
    service_period_end_date: Optional[datetime] = Field(default=None, description="End date for the period when the service usage was rated for charges. The prices for Azure services are determined based on the rating period.", alias="servicePeriodEndDate")
    service_period_start_date: Optional[datetime] = Field(default=None, description="Start date for the rating period when the service usage was rated for charges. The prices for Azure services are determined for the rating period.", alias="servicePeriodStartDate")
    subscription_guid: Optional[StrictStr] = Field(default=None, description="Unique Microsoft generated identifier for the Azure Subscription.", alias="subscriptionGuid")
    subscription_name: Optional[StrictStr] = Field(default=None, description="Name of the Azure Subscription.", alias="subscriptionName")
    term: Optional[StrictStr] = Field(default=None, description="Term (in months). Displays the term for the validity of the offer. For example. In case of reserved instances it displays 12 months for yearly term of reserved instance. For one time purchases or recurring purchases, the terms displays 1 month; This is not applicable for Azure consumption.")
    unit_of_measure: Optional[StrictStr] = Field(default=None, description="Identifies the Unit that the service is charged in. For example, GB, hours, 10,000 s.", alias="unitOfMeasure")
    unit_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Unit Price is the price applicable to you. (your EA or other contract price).", alias="unitPrice")
    __properties: ClassVar[List[str]] = ["additionalInfo", "billingAccountId", "billingAccountName", "billingCurrencyCode", "billingPeriodEndDate", "billingPeriodStartDate", "billingProfileId", "billingProfileName", "chargeType", "consumedService", "costCenter", "costInBillingCurrency", "costInPricingCurrency", "costInUSD", "customerName", "customerTenantId", "date", "exchangeRate", "exchangeRateDate", "exchangeRatePricingToBilling", "frequency", "instanceName", "invoiceId", "invoiceSectionId", "invoiceSectionName", "isAzureCreditEligible", "marketPrice", "meterCategory", "meterId", "meterName", "meterRegion", "meterSubCategory", "partnerEarnedCreditApplied", "partnerEarnedCreditRate", "partnerName", "partnerTenantId", "paygCostInBillingCurrency", "paygCostInUSD", "previousInvoiceId", "pricingCurrencyCode", "product", "productIdentifier", "productOrderId", "productOrderName", "publisherId", "publisherName", "publisherType", "quantity", "resellerMpnId", "resellerName", "reservationId", "reservationName", "resourceGroup", "resourceLocation", "resourceLocationNormalized", "serviceFamily", "serviceInfo1", "serviceInfo2", "servicePeriodEndDate", "servicePeriodStartDate", "subscriptionGuid", "subscriptionName", "term", "unitOfMeasure", "unitPrice"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModernUsageDetailProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "additional_info",
            "billing_account_id",
            "billing_account_name",
            "billing_currency_code",
            "billing_period_end_date",
            "billing_period_start_date",
            "billing_profile_id",
            "billing_profile_name",
            "charge_type",
            "consumed_service",
            "cost_center",
            "cost_in_billing_currency",
            "cost_in_pricing_currency",
            "cost_in_usd",
            "customer_name",
            "customer_tenant_id",
            "var_date",
            "exchange_rate",
            "exchange_rate_date",
            "exchange_rate_pricing_to_billing",
            "frequency",
            "instance_name",
            "invoice_id",
            "invoice_section_id",
            "invoice_section_name",
            "is_azure_credit_eligible",
            "market_price",
            "meter_category",
            "meter_id",
            "meter_name",
            "meter_region",
            "meter_sub_category",
            "partner_earned_credit_applied",
            "partner_earned_credit_rate",
            "partner_name",
            "partner_tenant_id",
            "payg_cost_in_billing_currency",
            "payg_cost_in_usd",
            "previous_invoice_id",
            "pricing_currency_code",
            "product",
            "product_identifier",
            "product_order_id",
            "product_order_name",
            "publisher_id",
            "publisher_name",
            "publisher_type",
            "quantity",
            "reseller_mpn_id",
            "reseller_name",
            "reservation_id",
            "reservation_name",
            "resource_group",
            "resource_location",
            "resource_location_normalized",
            "service_family",
            "service_info1",
            "service_info2",
            "service_period_end_date",
            "service_period_start_date",
            "subscription_guid",
            "subscription_name",
            "term",
            "unit_of_measure",
            "unit_price",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModernUsageDetailProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "additionalInfo": obj.get("additionalInfo"),
            "billingAccountId": obj.get("billingAccountId"),
            "billingAccountName": obj.get("billingAccountName"),
            "billingCurrencyCode": obj.get("billingCurrencyCode"),
            "billingPeriodEndDate": obj.get("billingPeriodEndDate"),
            "billingPeriodStartDate": obj.get("billingPeriodStartDate"),
            "billingProfileId": obj.get("billingProfileId"),
            "billingProfileName": obj.get("billingProfileName"),
            "chargeType": obj.get("chargeType"),
            "consumedService": obj.get("consumedService"),
            "costCenter": obj.get("costCenter"),
            "costInBillingCurrency": obj.get("costInBillingCurrency"),
            "costInPricingCurrency": obj.get("costInPricingCurrency"),
            "costInUSD": obj.get("costInUSD"),
            "customerName": obj.get("customerName"),
            "customerTenantId": obj.get("customerTenantId"),
            "date": obj.get("date"),
            "exchangeRate": obj.get("exchangeRate"),
            "exchangeRateDate": obj.get("exchangeRateDate"),
            "exchangeRatePricingToBilling": obj.get("exchangeRatePricingToBilling"),
            "frequency": obj.get("frequency"),
            "instanceName": obj.get("instanceName"),
            "invoiceId": obj.get("invoiceId"),
            "invoiceSectionId": obj.get("invoiceSectionId"),
            "invoiceSectionName": obj.get("invoiceSectionName"),
            "isAzureCreditEligible": obj.get("isAzureCreditEligible"),
            "marketPrice": obj.get("marketPrice"),
            "meterCategory": obj.get("meterCategory"),
            "meterId": obj.get("meterId"),
            "meterName": obj.get("meterName"),
            "meterRegion": obj.get("meterRegion"),
            "meterSubCategory": obj.get("meterSubCategory"),
            "partnerEarnedCreditApplied": obj.get("partnerEarnedCreditApplied"),
            "partnerEarnedCreditRate": obj.get("partnerEarnedCreditRate"),
            "partnerName": obj.get("partnerName"),
            "partnerTenantId": obj.get("partnerTenantId"),
            "paygCostInBillingCurrency": obj.get("paygCostInBillingCurrency"),
            "paygCostInUSD": obj.get("paygCostInUSD"),
            "previousInvoiceId": obj.get("previousInvoiceId"),
            "pricingCurrencyCode": obj.get("pricingCurrencyCode"),
            "product": obj.get("product"),
            "productIdentifier": obj.get("productIdentifier"),
            "productOrderId": obj.get("productOrderId"),
            "productOrderName": obj.get("productOrderName"),
            "publisherId": obj.get("publisherId"),
            "publisherName": obj.get("publisherName"),
            "publisherType": obj.get("publisherType"),
            "quantity": obj.get("quantity"),
            "resellerMpnId": obj.get("resellerMpnId"),
            "resellerName": obj.get("resellerName"),
            "reservationId": obj.get("reservationId"),
            "reservationName": obj.get("reservationName"),
            "resourceGroup": obj.get("resourceGroup"),
            "resourceLocation": obj.get("resourceLocation"),
            "resourceLocationNormalized": obj.get("resourceLocationNormalized"),
            "serviceFamily": obj.get("serviceFamily"),
            "serviceInfo1": obj.get("serviceInfo1"),
            "serviceInfo2": obj.get("serviceInfo2"),
            "servicePeriodEndDate": obj.get("servicePeriodEndDate"),
            "servicePeriodStartDate": obj.get("servicePeriodStartDate"),
            "subscriptionGuid": obj.get("subscriptionGuid"),
            "subscriptionName": obj.get("subscriptionName"),
            "term": obj.get("term"),
            "unitOfMeasure": obj.get("unitOfMeasure"),
            "unitPrice": obj.get("unitPrice")
        })
        return _obj


