swagger: '2.0'
schemes:
  - https
host: cloudsearch.googleapis.com
basePath: /
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Cloud Search provides cloud-based search capabilities over G Suite data.  The Cloud Search API allows indexing of non-G Suite data into Cloud Search.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Cloud Search
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.7.31
      format: google
      url: 'https://cloudsearch.googleapis.com/$discovery/rest?version=v1'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: cloudsearch
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/cloud_search': Index and serve your organization's data with Cloud Search
      'https://www.googleapis.com/auth/cloud_search.debug': 'New Service: https://www.googleapis.com/auth/cloud_search.debug'
      'https://www.googleapis.com/auth/cloud_search.indexing': 'New Service: https://www.googleapis.com/auth/cloud_search.indexing'
      'https://www.googleapis.com/auth/cloud_search.query': Search your organization's data in the Cloud Search index
      'https://www.googleapis.com/auth/cloud_search.settings': 'New Service: https://www.googleapis.com/auth/cloud_search.settings'
      'https://www.googleapis.com/auth/cloud_search.settings.indexing': 'New Service: https://www.googleapis.com/auth/cloud_search.settings.indexing'
      'https://www.googleapis.com/auth/cloud_search.settings.query': 'New Service: https://www.googleapis.com/auth/cloud_search.settings.query'
      'https://www.googleapis.com/auth/cloud_search.stats': 'New Service: https://www.googleapis.com/auth/cloud_search.stats'
      'https://www.googleapis.com/auth/cloud_search.stats.indexing': 'New Service: https://www.googleapis.com/auth/cloud_search.stats.indexing'
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/cloud_search': Index and serve your organization's data with Cloud Search
      'https://www.googleapis.com/auth/cloud_search.debug': 'New Service: https://www.googleapis.com/auth/cloud_search.debug'
      'https://www.googleapis.com/auth/cloud_search.indexing': 'New Service: https://www.googleapis.com/auth/cloud_search.indexing'
      'https://www.googleapis.com/auth/cloud_search.query': Search your organization's data in the Cloud Search index
      'https://www.googleapis.com/auth/cloud_search.settings': 'New Service: https://www.googleapis.com/auth/cloud_search.settings'
      'https://www.googleapis.com/auth/cloud_search.settings.indexing': 'New Service: https://www.googleapis.com/auth/cloud_search.settings.indexing'
      'https://www.googleapis.com/auth/cloud_search.settings.query': 'New Service: https://www.googleapis.com/auth/cloud_search.settings.query'
      'https://www.googleapis.com/auth/cloud_search.stats': 'New Service: https://www.googleapis.com/auth/cloud_search.stats'
      'https://www.googleapis.com/auth/cloud_search.stats.indexing': 'New Service: https://www.googleapis.com/auth/cloud_search.stats.indexing'
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: debug
  - name: indexing
  - name: media
  - name: operations
  - name: query
  - name: settings
  - name: stats
paths:
  '/v1/debug/{name}/items:searchByViewUrl':
    post:
      description: |-
        Fetches the item whose viewUrl exactly matches that of the URL provided
        in the request.
      operationId: cloudsearch.debug.datasources.items.searchByViewUrl
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.debug'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.debug'
      tags:
        - debug
  '/v1/debug/{name}:checkAccess':
    post:
      description: Checks whether an item is accessible by specified principal.
      operationId: cloudsearch.debug.datasources.items.checkAccess
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.debug'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.debug'
      tags:
        - debug
  '/v1/debug/{parent}/items:forunmappedidentity':
    get:
      description: Lists names of items associated with an unmapped identity.
      operationId: cloudsearch.debug.identitysources.items.listForunmappedidentity
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.debug'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.debug'
      tags:
        - debug
  '/v1/debug/{parent}/unmappedids':
    get:
      description: List all unmapped identities for a specific item.
      operationId: cloudsearch.debug.datasources.items.unmappedids.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.debug'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.debug'
      tags:
        - debug
  '/v1/indexing/{name}':
    delete:
      description: |-
        Deletes Item resource for the
        specified resource name.
      operationId: cloudsearch.indexing.datasources.items.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
      tags:
        - indexing
    get:
      description: Gets Item resource by item name.
      operationId: cloudsearch.indexing.datasources.items.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
      tags:
        - indexing
  '/v1/indexing/{name}/items':
    get:
      description: Lists all or a subset of Item resources.
      operationId: cloudsearch.indexing.datasources.items.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
      tags:
        - indexing
  '/v1/indexing/{name}/items:deleteQueueItems':
    post:
      description: |-
        Deletes all items in a queue. This method is useful for deleting stale
        items.
      operationId: cloudsearch.indexing.datasources.items.deleteQueueItems
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
      tags:
        - indexing
  '/v1/indexing/{name}/items:poll':
    post:
      description: |-
        Polls for unreserved items from the indexing queue and marks a
        set as reserved, starting with items that have
        the oldest timestamp from the highest priority
        ItemStatus.
        The priority order is as follows: <br />
        ERROR
        <br />
        MODIFIED
        <br />
        NEW_ITEM
        <br />
        ACCEPTED
        <br />
        Reserving items ensures that polling from other threads
        cannot create overlapping sets.

        After handling the reserved items, the client should put items back
        into the unreserved state, either by calling
        index,
        or by calling
        push with
        the type REQUEUE.

        Items automatically become available (unreserved) after 4 hours even if no
        update or push method is called.
      operationId: cloudsearch.indexing.datasources.items.poll
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
      tags:
        - indexing
  '/v1/indexing/{name}/items:unreserve':
    post:
      description: |-
        Unreserves all items from a queue, making them all eligible to be
        polled.  This method is useful for resetting the indexing queue
        after a connector has been restarted.
      operationId: cloudsearch.indexing.datasources.items.unreserve
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
      tags:
        - indexing
  '/v1/indexing/{name}/schema':
    delete:
      description: Deletes the schema of a data source.
      operationId: cloudsearch.indexing.datasources.deleteSchema
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings.indexing'
      tags:
        - indexing
    get:
      description: Gets the schema of a data source.
      operationId: cloudsearch.indexing.datasources.getSchema
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings.indexing'
      tags:
        - indexing
    put:
      description: Updates the schema of a data source.
      operationId: cloudsearch.indexing.datasources.updateSchema
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings.indexing'
      tags:
        - indexing
  '/v1/indexing/{name}:index':
    post:
      description: |-
        Updates Item ACL, metadata, and
        content. It will insert the Item if it
        does not exist.
        This method does not support partial updates.  Fields with no provided
        values are cleared out in the Cloud Search index.
      operationId: cloudsearch.indexing.datasources.items.index
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
      tags:
        - indexing
  '/v1/indexing/{name}:push':
    post:
      description: Pushes an item onto a queue for later polling and updating.
      operationId: cloudsearch.indexing.datasources.items.push
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
      tags:
        - indexing
  '/v1/indexing/{name}:upload':
    post:
      description: |-
        Creates an upload session for uploading item content. For items smaller
        than 100 KiB, it's easier to embed the content
        inline within
        update.
      operationId: cloudsearch.indexing.datasources.items.upload
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
      tags:
        - indexing
  '/v1/media/{resourceName}':
    post:
      description: |-
        Uploads media for indexing.

        The upload endpoint supports direct and resumable upload protocols and
        is intended for large items that can not be inlined during index requests. To
        index large content:

        1. Call upload to begin
           a session and get the item reference.
        1. Upload the content using the item reference's resource name.
        1. Call index with the item
           reference as the content.

        For additional information, see
        [Create a content connector using the REST API](https://developers.google.com/cloud-search/docs/guides/content-connector#rest).
      operationId: cloudsearch.media.upload
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
      tags:
        - media
  /v1/query/search:
    post:
      description: |-
        The Cloud Search Query API provides the search method, which returns
        the most relevant results from a user query.  The results can come from
        G Suite Apps, such as Gmail or Google Drive, or they can come from data
        that you have indexed from a third party.
      operationId: cloudsearch.query.search
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.query'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.query'
      tags:
        - query
  /v1/query/sources:
    get:
      description: Returns list of sources that user can use for Search and Suggest APIs.
      operationId: cloudsearch.query.sources.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.query'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.query'
      tags:
        - query
  /v1/query/suggest:
    post:
      description: Provides suggestions for autocompleting the query.
      operationId: cloudsearch.query.suggest
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.query'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.query'
      tags:
        - query
  /v1/settings/datasources:
    get:
      description: Lists datasources.
      operationId: cloudsearch.settings.datasources.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings.indexing'
      tags:
        - settings
    post:
      description: Creates a datasource.
      operationId: cloudsearch.settings.datasources.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings.indexing'
      tags:
        - settings
  /v1/settings/searchapplications:
    get:
      description: Lists all search applications.
      operationId: cloudsearch.settings.searchapplications.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings.query'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings.query'
      tags:
        - settings
    post:
      description: Creates a search application.
      operationId: cloudsearch.settings.searchapplications.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings.query'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings.query'
      tags:
        - settings
  '/v1/settings/{name}':
    delete:
      description: Deletes a datasource.
      operationId: cloudsearch.settings.datasources.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings.indexing'
      tags:
        - settings
    get:
      description: Gets a datasource.
      operationId: cloudsearch.settings.datasources.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings.indexing'
      tags:
        - settings
    put:
      description: Updates a datasource.
      operationId: cloudsearch.settings.datasources.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings.indexing'
      tags:
        - settings
  '/v1/settings/{name}:reset':
    post:
      description: |-
        Resets a search application to default settings. This will return an empty
        response.
      operationId: cloudsearch.settings.searchapplications.reset
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings.query'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings.query'
      tags:
        - settings
  /v1/stats/index:
    get:
      description: |-
        Gets indexed item statistics aggreggated across all data sources. This
        API only returns statistics for previous dates; it doesn't return
        statistics for the current day.
      operationId: cloudsearch.stats.getIndex
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.stats'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.stats'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.stats.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.stats.indexing'
      tags:
        - stats
  '/v1/stats/index/{name}':
    get:
      description: Gets indexed item statistics for a single data source.
      operationId: cloudsearch.stats.index.datasources.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.stats'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.stats'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.stats.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.stats.indexing'
      tags:
        - stats
  '/v1/{name}':
    get:
      description: |-
        Gets the latest state of a long-running operation.  Clients can use this
        method to poll the operation result at intervals as recommended by the API
        service.
      operationId: cloudsearch.operations.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.debug'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.debug'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.indexing'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings.indexing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings.indexing'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud_search.settings.query'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud_search.settings.query'
      tags:
        - operations
definitions:
  BooleanOperatorOptions:
    description: |-
      Used to provide a search operator for boolean properties. This is
      optional. Search operators let users restrict the query to specific fields
      relevant to the type of item being searched.
    properties:
      operatorName:
        description: |-
          Indicates the operator name required in the query in order to isolate the
          boolean property. For example, if operatorName is *closed* and the
          property's name is *isClosed*, then queries like
          *closed:&lt;value&gt;* will show results only where the value of the
          property named *isClosed* matches *&lt;value&gt;*. By contrast, a
          search that uses the same *&lt;value&gt;* without an operator will return
          all items where *&lt;value&gt;* matches the value of any
          String properties or text within the content field for the item.
          The operator name can only contain lowercase letters (a-z).
          The maximum length is 32 characters.
        type: string
    type: object
  BooleanPropertyOptions:
    description: Options for boolean properties.
    properties:
      operatorOptions:
        $ref: '#/definitions/BooleanOperatorOptions'
        description: 'If set, describes how the boolean should be used as a search operator.'
    type: object
  CheckAccessResponse:
    properties:
      hasAccess:
        description: Returns true if principal has access.  Returns false otherwise.
        type: boolean
    type: object
  CompositeFilter:
    properties:
      logicOperator:
        description: The logic operator of the sub filter.
        enum:
          - AND
          - OR
          - NOT
        type: string
      subFilters:
        description: Sub filters.
        items:
          $ref: '#/definitions/Filter'
        type: array
    type: object
  CustomerIndexStats:
    description: Aggregation of items by status code as of the specified date.
    properties:
      date:
        $ref: '#/definitions/Date'
        description: Date for which statistics were calculated.
      itemCountByStatus:
        description: Number of items aggregrated by status code.
        items:
          $ref: '#/definitions/ItemCountByStatus'
        type: array
    type: object
  DataSource:
    description: |-
      Datasource is a logical namespace for items to be indexed.
      All items must belong to a datasource.  This is the prerequisite before
      items can be indexed into Cloud Search.
    properties:
      disableModifications:
        description: |-
          If true, Indexing API rejects any modification calls to this datasource
          such as create, update, and delete.
          Disabling this does not imply halting process of previously
          accepted data.
        type: boolean
      disableServing:
        description: Disable serving any search or assist results.
        type: boolean
      displayName:
        description: |-
          Required. Display name of the datasource
          The maximum length is 300 characters.
        type: string
      indexingServiceAccounts:
        description: List of service accounts that have indexing access.
        items:
          type: string
        type: array
      itemsVisibility:
        description: |-
          This field restricts visibility to items at the datasource level. Items
          within the datasource are restricted to the union of users and groups
          included in this field. Note that, this does not ensure access to a
          specific item, as users need to have ACL permissions on the contained
          items. This ensures a high level access on the entire datasource, and
          that the individual items are not shared outside this visibility.
        items:
          $ref: '#/definitions/GSuitePrincipal'
        type: array
      name:
        description: |-
          Name of the datasource resource.
          Format: datasources/{source_id}.
          <br />The name is ignored when creating a datasource.
        type: string
      operationIds:
        description: |-
          IDs of the Long Running Operations (LROs) currently running for this
          schema.
        items:
          type: string
        type: array
      shortName:
        description: |-
          A short name or alias for the source.  This value will be used to match the
          'source' operator. For example, if the short name is *&lt;value&gt;* then
          queries like *source:&lt;value&gt;* will only return results for this
          source. The value must be unique across all datasources. The value must
          only contain alphanumeric characters (a-zA-Z0-9). The value cannot start
          with 'google' and cannot be one of the following: mail, gmail, docs, drive,
          groups, sites, calendar, hangouts, gplus, keep, people, teams.
          Its maximum length is 32 characters.
        type: string
    type: object
  DataSourceIndexStats:
    description: Aggregation of items by status code as of the specified date.
    properties:
      date:
        $ref: '#/definitions/Date'
        description: |-
          Date for which index stats were calculated. If the date of request is not
          the current date then stats calculated on the next day are returned. Stats
          are calculated close to mid night in this case. If date of request is
          current date, then real time stats are returned.
      itemCountByStatus:
        description: Number of items aggregrated by status code.
        items:
          $ref: '#/definitions/ItemCountByStatus'
        type: array
    type: object
  DataSourceRestriction:
    description: Restriction on Datasource.
    properties:
      filterOptions:
        description: |-
          Filter options restricting the results. If multiple filters
          are present, they are grouped by object type before joining.
          Filters with the same object type are joined conjunctively, then
          the resulting expressions are joined disjunctively.

          The maximum number of elements is 20.

          NOTE: Suggest API supports only few filters at the moment:
            "objecttype", "type" and "mimetype".
          For now, schema specific filters cannot be used to filter suggestions.
        items:
          $ref: '#/definitions/FilterOptions'
        type: array
      source:
        $ref: '#/definitions/Source'
        description: The source of restriction.
    type: object
  Date:
    description: 'Represents a whole calendar date, for example a date of birth. The time of day and time zone are either specified elsewhere or are not significant. The date is relative to the [Proleptic Gregorian Calendar](https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar). The date must be a valid calendar date between the year 1 and 9999.'
    properties:
      day:
        description: Day of month. Must be from 1 to 31 and valid for the year and month.
        format: int32
        type: integer
      month:
        description: Month of date. Must be from 1 to 12.
        format: int32
        type: integer
      year:
        description: Year of date. Must be from 1 to 9999.
        format: int32
        type: integer
    type: object
  DateOperatorOptions:
    description: |-
      Optional. Provides a search operator for date properties.
      Search operators let users restrict the query to specific fields relevant
      to the type of item being searched.
    properties:
      greaterThanOperatorName:
        description: |-
          Indicates the operator name required in the query in order to isolate the
          date property using the greater-than operator. For example, if
          greaterThanOperatorName is *closedafter* and the property's name is
          *closeDate*, then queries like *closedafter:&lt;value&gt;* will
          show results only where the value of the property named *closeDate* is
          later than *&lt;value&gt;*.
          The operator name can only contain lowercase letters (a-z).
          The maximum length is 32 characters.
        type: string
      lessThanOperatorName:
        description: |-
          Indicates the operator name required in the query in order to isolate the
          date property using the less-than operator. For example, if
          lessThanOperatorName is *closedbefore* and the property's name is
          *closeDate*, then queries like *closedbefore:&lt;value&gt;* will
          show results only where the value of the property named *closeDate* is
          earlier than *&lt;value&gt;*.
          The operator name can only contain lowercase letters (a-z).
          The maximum length is 32 characters.
        type: string
      operatorName:
        description: |-
          Indicates the actual string required in the query in order to isolate the
          date property. For example, suppose an issue tracking schema object
          has a property named *closeDate* that specifies an operator with an
          operatorName of *closedon*. For searches on that data, queries like
          *closedon:&lt;value&gt;* will show results only where the value of the
          *closeDate* property matches *&lt;value&gt;*. By contrast, a
          search that uses the same *&lt;value&gt;* without an operator will return
          all items where *&lt;value&gt;* matches the value of any String
          properties or text within the content field for the indexed datasource.
          The operator name can only contain lowercase letters (a-z).
          The maximum length is 32 characters.
        type: string
    type: object
  DatePropertyOptions:
    description: Options for date properties.
    properties:
      operatorOptions:
        $ref: '#/definitions/DateOperatorOptions'
        description: 'If set, describes how the date should be used as a search operator.'
    type: object
  DateValues:
    description: List of date values.
    properties:
      values:
        items:
          $ref: '#/definitions/Date'
        type: array
    type: object
  DebugOptions:
    description: Shared request debug options for all cloudsearch RPC methods.
    properties:
      enableDebugging:
        description: |-
          If you are asked by Google to help with debugging, set this field.
          Otherwise, ignore this field.
        type: boolean
    type: object
  DeleteQueueItemsRequest:
    properties:
      connectorName:
        description: |-
          Name of connector making this call.
          <br />Format: datasources/{source_id}/connectors/{ID}
        type: string
      debugOptions:
        $ref: '#/definitions/DebugOptions'
        description: Common debug options.
      queue:
        description: Name of a queue to delete items from.
        type: string
    type: object
  DisplayedProperty:
    description: |-
      A reference to a top-level property within the object that should be
      displayed in search results. The values of the chosen properties will be
      displayed in the search results along with the
      dislpay label
      for that property if one is specified. If a display label is not specified,
      only the values will be shown.
    properties:
      propertyName:
        description: |-
          The name of the top-level property as defined in a property definition
          for the object. If the name is not a defined property in the schema, an
          error will be given when attempting to update the schema.
        type: string
    type: object
  DoubleOperatorOptions:
    description: |-
      Used to provide a search operator for double properties. This is
      optional. Search operators let users restrict the query to specific fields
      relevant to the type of item being searched.
    properties:
      operatorName:
        description: |-
          Indicates the operator name required in the query in order to use the
          double property in sorting or as a facet.
          The operator name can only contain lowercase letters (a-z).
          The maximum length is 32 characters.
        type: string
    type: object
  DoublePropertyOptions:
    description: Options for double properties.
    properties:
      operatorOptions:
        $ref: '#/definitions/DoubleOperatorOptions'
        description: 'If set, describes how the double should be used as a search operator.'
    type: object
  DoubleValues:
    description: List of double values.
    properties:
      values:
        items:
          format: double
          type: number
        type: array
    type: object
  DriveFollowUpRestrict:
    description: 'Drive follow-up search restricts (e.g. "followup:suggestions").'
    properties:
      type:
        enum:
          - UNSPECIFIED
          - FOLLOWUP_SUGGESTIONS
          - FOLLOWUP_ACTION_ITEMS
        type: string
    type: object
  DriveLocationRestrict:
    description: 'Drive location search restricts (e.g. "is:starred").'
    properties:
      type:
        enum:
          - UNSPECIFIED
          - TRASHED
          - STARRED
        type: string
    type: object
  DriveMimeTypeRestrict:
    description: 'Drive mime-type search restricts (e.g. "type:pdf").'
    properties:
      type:
        enum:
          - UNSPECIFIED
          - PDF
          - DOCUMENT
          - PRESENTATION
          - SPREADSHEET
          - FORM
          - DRAWING
          - SCRIPT
          - MAP
          - IMAGE
          - AUDIO
          - VIDEO
          - FOLDER
          - ARCHIVE
          - SITE
        type: string
    type: object
  DriveTimeSpanRestrict:
    description: 'The time span search restrict (e.g. "after:2017-09-11 before:2017-09-12").'
    properties:
      type:
        enum:
          - UNSPECIFIED
          - TODAY
          - YESTERDAY
          - LAST_7_DAYS
          - LAST_30_DAYS
          - LAST_90_DAYS
        type: string
    type: object
  EmailAddress:
    description: A person's email address.
    properties:
      emailAddress:
        description: The email address.
        type: string
    type: object
  EnumOperatorOptions:
    description: |-
      Used to provide a search operator for enum properties. This is
      optional. Search operators let users restrict the query to specific fields
      relevant to the type of item being searched. For example, if you provide no
      operator for a *priority* enum property with possible values *p0* and *p1*,
      a query that contains the term *p0* will return items that have *p0* as the
      value of the *priority* property, as well as any items that contain the
      string *p0* in other fields. If you provide an operator name for the enum,
      such as *priority*, then search users can use that operator to refine
      results to only items that have *p0* as this property's value, with the
      query *priority:p0*.
    properties:
      operatorName:
        description: |-
          Indicates the operator name required in the query in order to isolate the
          enum property. For example, if operatorName is *priority* and the
          property's name is *priorityVal*, then queries like
          *priority:&lt;value&gt;* will show results only where the value of the
          property named *priorityVal* matches *&lt;value&gt;*. By contrast, a
          search that uses the same *&lt;value&gt;* without an operator will return
          all items where *&lt;value&gt;* matches the value of any String
          properties or text within the content field for the item.
          The operator name can only contain lowercase letters (a-z).
          The maximum length is 32 characters.
        type: string
    type: object
  EnumPropertyOptions:
    description: |-
      Options for enum properties, which allow you to define a restricted set of
      strings to match user queries, set rankings for those string values, and
      define an operator name to be paired with those strings so that users can
      narrow results to only items with a specific value. For example, for items in
      a request tracking system with priority information, you could define *p0* as
      an allowable enum value and tie this enum to the operator name *priority* so
      that search users could add *priority:p0* to their query to restrict the set
      of results to only those items indexed with the value *p0*.
    properties:
      operatorOptions:
        $ref: '#/definitions/EnumOperatorOptions'
        description: 'If set, describes how the enum should be used as a search operator.'
      orderedRanking:
        description: |-
          Used to specify the ordered ranking for the enumeration that determines how
          the integer values provided in the possible EnumValuePairs are used to rank
          results. If specified, integer values must be provided for all possible
          EnumValuePair values given for this property. Can only be used if
          isRepeatable
          is false.
        enum:
          - NO_ORDER
          - ASCENDING
          - DESCENDING
        type: string
      possibleValues:
        description: |-
          The list of possible values for the enumeration property. All
          EnumValuePairs must provide a string value. If you specify an integer value
          for one EnumValuePair, then all possible EnumValuePairs must provide an
          integer value. Both the string value and integer value must be unique over
          all possible values. Once set, possible values cannot be removed or
          modified. If you supply an ordered ranking and think you might insert
          additional enum values in the future, leave gaps in the initial integer
          values to allow adding a value in between previously registered values.
          The maximum number of elements is 100.
        items:
          $ref: '#/definitions/EnumValuePair'
        type: array
    type: object
  EnumValuePair:
    description: |-
      The enumeration value pair defines two things: a required string value and
      an optional integer value. The string value defines the necessary query
      term required to retrieve that item, such as *p0* for a priority item.
      The integer value determines the ranking of that string value relative
      to other enumerated values for the same property. For example, you might
      associate *p0* with *0* and define another enum pair such as *p1* and *1*.
      You must use the integer value in combination with
      ordered
      ranking to
      set the ranking of a given value relative to other enumerated values for
      the same property name. Here, a ranking order of DESCENDING for *priority*
      properties results in a ranking boost for items indexed with a value of
      *p0* compared to items indexed with a value of *p1*. Without a specified
      ranking order, the integer value has no effect on item ranking.
    properties:
      integerValue:
        description: |-
          The integer value of the EnumValuePair which must be non-negative.
          Optional.
        format: int32
        type: integer
      stringValue:
        description: |-
          The string value of the EnumValuePair.
          The maximum length is 32 characters.
        type: string
    type: object
  EnumValues:
    description: List of enum values.
    properties:
      values:
        description: The maximum allowable length for string values is 32 characters.
        items:
          type: string
        type: array
    type: object
  ErrorInfo:
    description: Error information about the response.
    properties:
      errorMessages:
        items:
          $ref: '#/definitions/ErrorMessage'
        type: array
    type: object
  ErrorMessage:
    description: Error message per source response.
    properties:
      errorMessage:
        type: string
      source:
        $ref: '#/definitions/Source'
    type: object
  FacetBucket:
    description: |-
      A bucket in a facet is the basic unit of operation. A bucket can comprise
      either a single value OR a contiguous range of values, depending on the
      type of the field bucketed.
      FacetBucket is currently used only for returning the response object.
    properties:
      count:
        description: |-
          Number of results that match the bucket value. Counts are only returned
          for searches when count accuracy is ensured. Can be empty.
        format: int32
        type: integer
      percentage:
        description: |-
          Percent of results that match the bucket value. This value is between
          (0-100]. Percentages are returned for all searches, but are an estimate.
          Because percentages are always returned, you should render percentages
          instead of counts.
        format: int32
        type: integer
      value:
        $ref: '#/definitions/Value'
    type: object
  FacetOptions:
    description: |-
      Specifies operators to return facet results for. There will be one
      FacetResult for every source_name/object_type/operator_name combination.
    properties:
      numFacetBuckets:
        description: |-
          Maximum number of facet buckets that should be returned for this facet.
          Defaults to 10.
          Maximum value is 100.
        format: int32
        type: integer
      objectType:
        description: |-
          If object_type is set, only those objects of that type will be used to
          compute facets. If empty, then all objects will be used to compute facets.
        type: string
      operatorName:
        description: |-
          Name of the operator chosen for faceting. @see
          cloudsearch.SchemaPropertyOptions
        type: string
      sourceName:
        description: |-
          Source name to facet on. Format: datasources/{source_id}
          If empty, all data sources will be used.
        type: string
    type: object
  FacetResult:
    description: Source specific facet response
    properties:
      buckets:
        description: FacetBuckets for values in response containing at least a single result.
        items:
          $ref: '#/definitions/FacetBucket'
        type: array
      objectType:
        description: Object type for which facet results are returned. Can be empty.
        type: string
      operatorName:
        description: |-
          Name of the operator chosen for faceting. @see
          cloudsearch.SchemaPropertyOptions
        type: string
      sourceName:
        description: Source name for which facet results are returned. Will not be empty.
        type: string
    type: object
  FieldViolation:
    properties:
      description:
        description: Description of the error.
        type: string
      field:
        description: Path of field with violation.
        type: string
    type: object
  Filter:
    description: |-
      A generic way of expressing filters in a query, which supports two
      approaches: <br/><br/>
      **1. Setting a ValueFilter.** The name must match an operator_name defined in
      the schema for your data source.
      <br/>
      **2. Setting a CompositeFilter.** The filters are evaluated
      using the logical operator. The top-level operators can only be either an AND
      or a NOT. AND can appear only at the top-most level. OR can appear only under
      a top-level AND.
    properties:
      compositeFilter:
        $ref: '#/definitions/CompositeFilter'
      valueFilter:
        $ref: '#/definitions/ValueFilter'
    type: object
  FilterOptions:
    description: Filter options to be applied on query.
    properties:
      filter:
        $ref: '#/definitions/Filter'
        description: 'Generic filter to restrict the search, such as `lang:en`, `site:xyz`.'
      objectType:
        description: |-
          If object_type is set, only objects of that type are returned. This should
          correspond to the name of the object that was registered within the
          definition of schema. The maximum length is 256 characters.
        type: string
    type: object
  FreshnessOptions:
    description: |-
      Indicates which freshness property to use when adjusting search ranking for
      an item. Fresher, more recent dates indicate higher quality. Use the
      freshness option property that best works with your data. For fileshare
      documents, last modified time is most relevant. For calendar event data,
      the time when the event occurs is a more relevant freshness indicator. In
      this way, calendar events that occur closer to the time of the search query
      are considered higher quality and ranked accordingly.
    properties:
      freshnessDuration:
        description: |-
          The duration after which an object should be considered
          stale. The default value is 180 days (in seconds).
        format: google-duration
        type: string
      freshnessProperty:
        description: |-
          This property indicates the freshness level of the object in the index.
          If set, this property must be a top-level property within the
          property definitions
          and it must be a
          timestamp type
          or
          date type.
          Otherwise, the Indexing API uses
          updateTime
          as the freshness indicator.
          The maximum length is 256 characters.

          When a property is used to calculate fresheness, the value defaults
          to 2 years from the current time.
        type: string
    type: object
  GSuitePrincipal:
    properties:
      gsuiteDomain:
        description: |-
          This principal represents all users of the G Suite domain of the
          customer.
        type: boolean
      gsuiteGroupEmail:
        description: This principal references a G Suite group account
        type: string
      gsuiteUserEmail:
        description: This principal references a G Suite user account
        type: string
    type: object
  GetCustomerIndexStatsResponse:
    properties:
      stats:
        description: 'Summary of indexed item counts, one for each day in the requested range.'
        items:
          $ref: '#/definitions/CustomerIndexStats'
        type: array
    type: object
  GetDataSourceIndexStatsResponse:
    properties:
      stats:
        description: 'Summary of indexed item counts, one for each day in the requested range.'
        items:
          $ref: '#/definitions/DataSourceIndexStats'
        type: array
    type: object
  GmailActionRestrict:
    description: Gmail Action restricts (i.e. read/replied/snoozed).
    properties:
      type:
        enum:
          - UNSPECIFIED
          - UNREAD
          - READ
          - REPLIED_TO
          - MUTED
        type: string
    type: object
  GmailAttachmentRestrict:
    description: 'Gmail Attachment restricts (i.e. has:attachment, has:drive, filename:pdf).'
    properties:
      type:
        enum:
          - UNSPECIFIED
          - HAS_ATTACHMENT
          - HAS_PHOTO
          - HAS_DRIVE
          - HAS_DOCUMENT
          - HAS_SPREADSHEET
          - HAS_PRESENTATION
          - HAS_YOUTUBE
          - HAS_PDF
        type: string
    type: object
  GmailFolderRestrict:
    description: Gmail Folder restricts (i.e. in Drafts/Sent/Chats/User Generated Labels).
    properties:
      type:
        enum:
          - UNSPECIFIED
          - IN_SENT
          - IN_DRAFT
          - CHATS
          - IN_TRASH
          - USER_GENERATED_LABEL
        type: string
    type: object
  GmailIntelligentRestrict:
    description: 'Gmail Intelligent restricts (i.e. smartlabels, important).'
    properties:
      type:
        enum:
          - UNSPECIFIED
          - SOCIAL
          - UPDATES
          - FORUMS
          - PROMOTIONS
          - IMPORTANT
          - FLIGHT_RESERVATION
          - LODGING_RESERVATION
          - CAR_RESERVATION
          - BUS_RESERVATION
        type: string
    type: object
  GmailTimeRestrict:
    description: 'Gmail Time restricts (i.e. received today, this week).'
    properties:
      type:
        enum:
          - UNSPECIFIED
          - FROM_THIS_WEEK
          - OLDER_THAN_ONE_YEAR
          - FROM_TODAY
          - FROM_YESTERDAY
          - FROM_THIS_MONTH
          - FROM_CERTAIN_MONTH
          - OLDER_THAN_TODAY
          - OLDER_THAN_YESTERDAY
          - OLDER_THAN_A_WEEK
          - OLDER_THAN_A_MONTH
        type: string
    type: object
  HtmlOperatorOptions:
    description: |-
      Used to provide a search operator for html properties. This is optional.
      Search operators let users restrict the query to specific fields relevant
      to the type of item being searched.
    properties:
      operatorName:
        description: |-
          Indicates the operator name required in the query in order to isolate the
          html property. For example, if operatorName is *subject* and the
          property's name is *subjectLine*, then queries like
          *subject:&lt;value&gt;* will show results only where the value of the
          property named *subjectLine* matches *&lt;value&gt;*. By contrast, a
          search that uses the same *&lt;value&gt;* without an operator will return
          all items where *&lt;value&gt;* matches the value of any
          html properties or text within the content field for the item.
          The operator name can only contain lowercase letters (a-z).
          The maximum length is 32 characters.
        type: string
    type: object
  HtmlPropertyOptions:
    description: Options for html properties.
    properties:
      operatorOptions:
        $ref: '#/definitions/HtmlOperatorOptions'
        description: 'If set, describes how the property should be used as a search operator.'
      retrievalImportance:
        $ref: '#/definitions/RetrievalImportance'
        description: |-
          Indicates the search quality importance of the tokens within the
          field when used for retrieval. Can only be set to DEFAULT or NONE.
    type: object
  HtmlValues:
    description: List of html values.
    properties:
      values:
        description: The maximum allowable length for html values is 2048 characters.
        items:
          type: string
        type: array
    type: object
  IndexItemOptions:
    properties:
      allowUnknownGsuitePrincipals:
        description: |-
          Specifies if the index request should allow gsuite principals that do not
          exist or are deleted in the index request.
        type: boolean
    type: object
  IndexItemRequest:
    properties:
      connectorName:
        description: |-
          Name of connector making this call.
          <br />Format: datasources/{source_id}/connectors/{ID}
        type: string
      debugOptions:
        $ref: '#/definitions/DebugOptions'
        description: Common debug options.
      indexItemOptions:
        $ref: '#/definitions/IndexItemOptions'
      item:
        $ref: '#/definitions/Item'
        description: |-
          Name of the item.  Format:
          datasources/{source_id}/items/{item_id}
      mode:
        description: Required. The RequestMode for this request.
        enum:
          - UNSPECIFIED
          - SYNCHRONOUS
          - ASYNCHRONOUS
        type: string
    type: object
  IntegerOperatorOptions:
    description: |-
      Used to provide a search operator for integer properties. This is
      optional. Search operators let users restrict the query to specific fields
      relevant to the type of item being searched.
    properties:
      greaterThanOperatorName:
        description: |-
          Indicates the operator name required in the query in order to isolate the
          integer property using the greater-than operator. For example, if
          greaterThanOperatorName is *priorityabove* and the property's name is
          *priorityVal*, then queries like *priorityabove:&lt;value&gt;* will
          show results only where the value of the property named *priorityVal* is
          greater than *&lt;value&gt;*.
          The operator name can only contain lowercase letters (a-z).
          The maximum length is 32 characters.
        type: string
      lessThanOperatorName:
        description: |-
          Indicates the operator name required in the query in order to isolate the
          integer property using the less-than operator. For example, if
          lessThanOperatorName is *prioritybelow* and the property's name is
          *priorityVal*, then queries like *prioritybelow:&lt;value&gt;* will
          show results only where the value of the property named *priorityVal* is
          less than *&lt;value&gt;*.
          The operator name can only contain lowercase letters (a-z).
          The maximum length is 32 characters.
        type: string
      operatorName:
        description: |-
          Indicates the operator name required in the query in order to isolate the
          integer property. For example, if operatorName is *priority* and the
          property's name is *priorityVal*, then queries like
          *priority:&lt;value&gt;* will show results only where the value of the
          property named *priorityVal* matches *&lt;value&gt;*. By contrast, a
          search that uses the same *&lt;value&gt;* without an operator will return
          all items where *&lt;value&gt;* matches the value of any String
          properties or text within the content field for the item.
          The operator name can only contain lowercase letters (a-z).
          The maximum length is 32 characters.
        type: string
    type: object
  IntegerPropertyOptions:
    description: Options for integer properties.
    properties:
      maximumValue:
        description: |-
          The maximum value of the property. The minimum and maximum values for the
          property are used to rank results according to the
          ordered ranking.
          Indexing requests with values greater than the maximum are accepted and
          ranked with the same weight as items indexed with the maximum value.
        format: int64
        type: string
      minimumValue:
        description: |-
          The minimum value of the property. The minimum and maximum values for the
          property are used to rank results according to the
          ordered ranking.
          Indexing requests with values less than the minimum are accepted and
          ranked with the same weight as items indexed with the minimum value.
        format: int64
        type: string
      operatorOptions:
        $ref: '#/definitions/IntegerOperatorOptions'
        description: 'If set, describes how the integer should be used as a search operator.'
      orderedRanking:
        description: |-
          Used to specify the ordered ranking for the integer. Can only be used if
          isRepeatable
          is false.
        enum:
          - NO_ORDER
          - ASCENDING
          - DESCENDING
        type: string
    type: object
  IntegerValues:
    description: List of integer values.
    properties:
      values:
        items:
          format: int64
          type: string
        type: array
    type: object
  Interaction:
    description: Represents an interaction between a user and an item.
    properties:
      interactionTime:
        description: |-
          The time when the user acted on the item.  If multiple actions of the same
          type exist for a single user, only the most recent action is recorded.
        format: google-datetime
        type: string
      principal:
        $ref: '#/definitions/Principal'
        description: The user that acted on the item.
      type:
        enum:
          - UNSPECIFIED
          - VIEW
          - EDIT
        type: string
    type: object
  Item:
    description: |-
      Represents a single object that is an item in the search index, such as a
      file, folder, or a database record.
    properties:
      acl:
        $ref: '#/definitions/ItemAcl'
        description: Access control list for this item.
      content:
        $ref: '#/definitions/ItemContent'
        description: Item content to be indexed and made text searchable.
      itemType:
        description: Type for this item.
        enum:
          - UNSPECIFIED
          - CONTENT_ITEM
          - CONTAINER_ITEM
          - VIRTUAL_CONTAINER_ITEM
        type: string
      metadata:
        $ref: '#/definitions/ItemMetadata'
        description: Metadata information.
      name:
        description: |-
          Name of the Item. Format:
          datasources/{source_id}/items/{item_id}
          <br />This is a required field.
          The maximum length is 1536 characters.
        type: string
      payload:
        description: |-
          Additional state connector can store for this item.
          The maximum length is 10000 bytes.
        format: byte
        type: string
      queue:
        description: |-
          Queue this item belongs to.
          The maximum length is 100 characters.
        type: string
      status:
        $ref: '#/definitions/ItemStatus'
        description: |-
          Status of the item.
          Output only field.
      structuredData:
        $ref: '#/definitions/ItemStructuredData'
        description: |-
          The structured data for the item that should conform to a registered
          object definition in the schema for the data source.
      version:
        description: |-
          Required. The indexing system stores the version from the datasource as a
          byte string and compares the Item version in the index
          to the version of the queued Item using lexical ordering.
          <br /><br />
          Cloud Search Indexing won't index or delete any queued item with
          a version value that is less than or equal to the version of the
          currently indexed item.
          The maximum length for this field is 1024 bytes.
        format: byte
        type: string
    type: object
  ItemAcl:
    description: |-
      Access control list information for the item. For more information see
      https://developers.google.com/cloud-search/docs/guides/index-your-data#acls
    properties:
      aclInheritanceType:
        description: |-
          Sets the type of access rules to apply when an item inherits its ACL from a
          parent. This should always be set in tandem with the
          inheritAclFrom
          field. Also, when the
          inheritAclFrom field
          is set, this field should be set to a valid AclInheritanceType.
        enum:
          - NOT_APPLICABLE
          - CHILD_OVERRIDE
          - PARENT_OVERRIDE
          - BOTH_PERMIT
        type: string
      deniedReaders:
        description: |-
          List of principals who are explicitly denied access to the item in search
          results. While principals are denied access by default, use denied readers
          to handle exceptions and override the list allowed readers.
          The maximum number of elements is 100.
        items:
          $ref: '#/definitions/Principal'
        type: array
      inheritAclFrom:
        description: |-
          Name of the item to inherit the Access Permission List (ACL) from.
          Note: ACL inheritance *only* provides access permissions
          to child items and does not define structural relationships, nor does it
          provide convenient ways to delete large groups of items.
          Deleting an ACL parent from the index only alters the access permissions of
          child items that reference the parent in the
          inheritAclFrom
          field. The item is still in the index, but may not
          visible in search results. By contrast, deletion of a container item
          also deletes all items that reference the container via the
          containerName
          field.
          The maximum length for this field is 1536 characters.
        type: string
      owners:
        description: |-
          Optional. List of owners for the item. This field has no bearing on
          document access permissions. It does, however, offer
          a slight ranking boosts items where the querying user is an owner.
          The maximum number of elements is 5.
        items:
          $ref: '#/definitions/Principal'
        type: array
      readers:
        description: |-
          List of principals who are allowed to see the item in search results.
          Optional if inheriting permissions from another item or if the item
          is not intended to be visible, such as
          virtual
          containers.
          The maximum number of elements is 1000.
        items:
          $ref: '#/definitions/Principal'
        type: array
    type: object
  ItemContent:
    description: Content of an item to be indexed and surfaced by Cloud Search.
    properties:
      contentDataRef:
        $ref: '#/definitions/UploadItemRef'
        description: Upload reference ID of a previously uploaded content via write method.
      contentFormat:
        enum:
          - UNSPECIFIED
          - HTML
          - TEXT
          - RAW
        type: string
      hash:
        description: |-
          Hashing info calculated and provided by the API client for content.
          Can be used with the items.push method to calculate modified state.
          The maximum length is 2048 characters.
        type: string
      inlineContent:
        description: |-
          Content that is supplied inlined within the update method.
          The maximum length is 102400 bytes (100 KiB).
        format: byte
        type: string
    type: object
  ItemCountByStatus:
    properties:
      count:
        description: Number of items matching the status code.
        format: int64
        type: string
      statusCode:
        description: Status of the items.
        enum:
          - CODE_UNSPECIFIED
          - ERROR
          - MODIFIED
          - NEW_ITEM
          - ACCEPTED
        type: string
    type: object
  ItemMetadata:
    description: Available metadata fields for the item.
    properties:
      containerName:
        description: |-
          The name of the container for this item.
          Deletion of the container item leads to automatic deletion of this
          item.  Note: ACLs are not inherited from a container item.
          To provide ACL inheritance for an item, use the
          inheritAclFrom
          field. The maximum length is 1536 characters.
        type: string
      contentLanguage:
        description: |-
          The BCP-47 language code for the item, such as "en-US" or "sr-Latn". For
          more information, see
          http://www.unicode.org/reports/tr35/#Unicode_locale_identifier.
          The maximum length is 32 characters.
        type: string
      createTime:
        description: The time when the item was created in the source repository.
        format: google-datetime
        type: string
      hash:
        description: |-
          Hashing value provided by the API caller.
          This can be used with the
          items.push
          method to calculate modified state.
          The maximum length is 2048 characters.
        type: string
      interactions:
        description: |-
          A list of interactions for the item.  Interactions are used to improve
          Search quality, but are not exposed to end users.
          The maximum number of elements is 1000.
        items:
          $ref: '#/definitions/Interaction'
        type: array
      keywords:
        description: |-
          Additional keywords or phrases that should match the item.
          Used internally for user generated content.
          The maximum number of elements is 100.
          The maximum length is 8192 characters.
        items:
          type: string
        type: array
      mimeType:
        description: |-
          The original mime-type of
          ItemContent.content
          in the source repository.
          The maximum length is 256 characters.
        type: string
      objectType:
        description: |-
          The type of the item.  This should correspond to the name of an object
          definition in the schema registered for the data source.  For example, if
          the schema for the data source contains an object definition with name
          'document', then item indexing requests for objects of that type should set
          objectType to 'document'.
          The maximum length is 256 characters.
        type: string
      searchQualityMetadata:
        $ref: '#/definitions/SearchQualityMetadata'
        description: Additional search quality metadata of the item
      sourceRepositoryUrl:
        description: |-
          Link to the source repository serving the data.  &#83;earch results apply
          this link to the title.
          The maximum length is 2048 characters.
        type: string
      title:
        description: |-
          The title of the item.  If given, this will be the displayed title of the
          Search result.
          The maximum length is 2048 characters.
        type: string
      updateTime:
        description: The time when the item was last modified in the source repository.
        format: google-datetime
        type: string
    type: object
  ItemStatus:
    description: This contains item's status and any errors.
    properties:
      code:
        description: Status code.
        enum:
          - CODE_UNSPECIFIED
          - ERROR
          - MODIFIED
          - NEW_ITEM
          - ACCEPTED
        type: string
      processingErrors:
        description: Error details in case the item is in ERROR state.
        items:
          $ref: '#/definitions/ProcessingError'
        type: array
      repositoryErrors:
        description: Repository error reported by connector.
        items:
          $ref: '#/definitions/RepositoryError'
        type: array
    type: object
  ItemStructuredData:
    description: Available structured data fields for the item.
    properties:
      hash:
        description: |-
          Hashing value provided by the API caller.
          This can be used with the
          items.push
          method to calculate modified state.
          The maximum length is 2048 characters.
        type: string
      object:
        $ref: '#/definitions/StructuredDataObject'
        description: |-
          The structured data object that should conform to a registered object
          definition in the schema for the data source.
    type: object
  ListDataSourceResponse:
    properties:
      nextPageToken:
        description: |-
          Token to retrieve the next page of results, or empty if there are no
          more results in the list.
        type: string
      sources:
        items:
          $ref: '#/definitions/DataSource'
        type: array
    type: object
  ListItemNamesForUnmappedIdentityResponse:
    properties:
      itemNames:
        items:
          type: string
        type: array
      nextPageToken:
        description: |-
          Token to retrieve the next page of results, or empty if there are no
          more results in the list.
        type: string
    type: object
  ListItemsResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/Item'
        type: array
      nextPageToken:
        description: |-
          Token to retrieve the next page of results, or empty if there are no
          more results in the list.
        type: string
    type: object
  ListQuerySourcesResponse:
    description: List sources response.
    properties:
      nextPageToken:
        type: string
      sources:
        items:
          $ref: '#/definitions/QuerySource'
        type: array
    type: object
  ListSearchApplicationsResponse:
    properties:
      nextPageToken:
        description: |-
          Token to retrieve the next page of results, or empty if there are no
          more results in the list.
        type: string
      searchApplications:
        items:
          $ref: '#/definitions/SearchApplication'
        type: array
    type: object
  ListUnmappedIdentitiesResponse:
    properties:
      nextPageToken:
        description: |-
          Token to retrieve the next page of results, or empty if there are no
          more results in the list.
        type: string
      unmappedIdentities:
        items:
          $ref: '#/definitions/UnmappedIdentity'
        type: array
    type: object
  MatchRange:
    description: 'Matched range of a snippet [start, end).'
    properties:
      end:
        description: End of the match in the snippet.
        format: int32
        type: integer
      start:
        description: Starting position of the match in the snippet.
        format: int32
        type: integer
    type: object
  Media:
    description: Media resource.
    properties:
      resourceName:
        description: Name of the media resource.
        type: string
    type: object
  Metadata:
    description: Metadata of a matched search result.
    properties:
      createTime:
        description: The creation time for this document or object in the search result.
        format: google-datetime
        type: string
      displayOptions:
        $ref: '#/definitions/ResultDisplayMetadata'
        description: Options that specify how to display a structured data search result.
      fields:
        description: 'Indexed fields in structured data, returned as a generic named property.'
        items:
          $ref: '#/definitions/NamedProperty'
        type: array
      mimeType:
        description: Mime type of the search result.
        type: string
      objectType:
        description: Object type of the search result.
        type: string
      owner:
        $ref: '#/definitions/Person'
        description: Owner (usually creator) of the document or object of the search result.
      source:
        $ref: '#/definitions/Source'
        description: 'The named source for the result, such as Gmail.'
      updateTime:
        description: |-
          The last modified date for the object in the search result. If not
          set in the item, the value returned here is empty. When
          `updateTime` is used for calculating freshness and is not set, this
          value defaults to 2 years from the current time.
        format: google-datetime
        type: string
    type: object
  Metaline:
    description: |-
      A metaline is a list of properties that are displayed along with the search
      result to provide context.
    properties:
      properties:
        description: |-
          The list of displayed properties for the metaline. The maxiumum number of
          properties is 5.
        items:
          $ref: '#/definitions/DisplayedProperty'
        type: array
    type: object
  Name:
    description: A person's name.
    properties:
      displayName:
        description: |-
          The read-only display name formatted according to the locale specified by
          the viewer's account or the <code>Accept-Language</code> HTTP header.
        type: string
    type: object
  NamedProperty:
    description: |-
      A typed name-value pair for structured data.  The type of the value should
      be the same as the registered type for the `name` property in the object
      definition of `objectType`.
    properties:
      booleanValue:
        type: boolean
      dateValues:
        $ref: '#/definitions/DateValues'
      doubleValues:
        $ref: '#/definitions/DoubleValues'
      enumValues:
        $ref: '#/definitions/EnumValues'
      htmlValues:
        $ref: '#/definitions/HtmlValues'
      integerValues:
        $ref: '#/definitions/IntegerValues'
      name:
        description: |-
          The name of the property.  This name should correspond to the name of the
          property that was registered for object definition in the schema.
          The maximum allowable length for this property is 256 characters.
        type: string
      objectValues:
        $ref: '#/definitions/ObjectValues'
      textValues:
        $ref: '#/definitions/TextValues'
      timestampValues:
        $ref: '#/definitions/TimestampValues'
    type: object
  ObjectDefinition:
    description: The definition for an object within a data source.
    properties:
      name:
        description: |-
          Name for the object, which then defines its type. Item indexing requests
          should set the
          objectType field
          equal to this value. For example, if *name* is *Document*, then indexing
          requests for items of type Document should set
          objectType equal to
          *Document*. Each object definition must be uniquely named within a schema.
          The name must start with a letter and can only contain letters (A-Z, a-z)
          or numbers (0-9).
          The maximum length is 256 characters.
        type: string
      options:
        $ref: '#/definitions/ObjectOptions'
        description: The optional object-specific options.
      propertyDefinitions:
        description: |-
          The property definitions for the object.
          The maximum number of elements is 1000.
        items:
          $ref: '#/definitions/PropertyDefinition'
        type: array
    type: object
  ObjectDisplayOptions:
    description: The display options for an object.
    properties:
      metalines:
        description: |-
          Defines the properties that will be displayed in the metalines of the
          search results. The property values will be displayed in the order given
          here. If a property holds multiple values, all of the values will be
          diplayed before the next properties. For this reason, it is a good practice
          to specify singular properties before repeated properties in this list. All
          of the properties must set
          is_returnable
          to true. The maximum number of metalines is 3.
        items:
          $ref: '#/definitions/Metaline'
        type: array
      objectDisplayLabel:
        description: |-
          The user friendly label to display in the search result to inidicate the
          type of the item. This is OPTIONAL; if not given, an object label will not
          be displayed on the context line of the search results. The maximum length
          is 32 characters.
        type: string
    type: object
  ObjectOptions:
    description: The options for an object.
    properties:
      displayOptions:
        $ref: '#/definitions/ObjectDisplayOptions'
        description: |-
          Options that determine how the object is displayed in the Cloud Search
          results page.
      freshnessOptions:
        $ref: '#/definitions/FreshnessOptions'
        description: The freshness options for an object.
    type: object
  ObjectPropertyOptions:
    description: Options for object properties.
    properties:
      subobjectProperties:
        description: |-
          The properties of the sub-object. These properties represent a nested
          object. For example, if this property represents a postal address, the
          subobjectProperties might be named *street*, *city*, and *state*.
          The maximum number of elements is 1000.
        items:
          $ref: '#/definitions/PropertyDefinition'
        type: array
    type: object
  ObjectValues:
    description: List of object values.
    properties:
      values:
        items:
          $ref: '#/definitions/StructuredDataObject'
        type: array
    type: object
  Operation:
    description: |-
      This resource represents a long-running operation that is the result of a
      network API call.
    properties:
      done:
        description: |-
          If the value is `false`, it means the operation is still in progress.
          If `true`, the operation is completed, and either `error` or `response` is
          available.
        type: boolean
      error:
        $ref: '#/definitions/Status'
        description: The error result of the operation in case of failure or cancellation.
      metadata:
        additionalProperties:
          description: Properties of the object. Contains field @type with type URL.
        description: |-
          Service-specific metadata associated with the operation.  It typically
          contains progress information and common metadata such as create time.
          Some services might not provide such metadata.  Any method that returns a
          long-running operation should document the metadata type, if any.
        type: object
      name:
        description: |-
          The server-assigned name, which is only unique within the same service that
          originally returns it. If you use the default HTTP mapping, the
          `name` should be a resource name ending with `operations/{unique_id}`.
        type: string
    type: object
  PeopleSuggestion:
    description: This field contains information about the person being suggested.
    properties:
      person:
        $ref: '#/definitions/Person'
        description: Suggested person. All fields of the person object might not be populated.
    type: object
  Person:
    description: Object to represent a person.
    properties:
      emailAddresses:
        description: The person's email addresses
        items:
          $ref: '#/definitions/EmailAddress'
        type: array
      name:
        description: |-
          The resource name of the person to provide information about.
          See <a href="https://developers.google.com/people/api/rest/v1/people/get">
          People.get</a> from Google People API.
        type: string
      obfuscatedId:
        description: Obfuscated ID of a person.
        type: string
      personNames:
        description: The person's name
        items:
          $ref: '#/definitions/Name'
        type: array
      photos:
        description: |-
          A person's read-only photo. A picture shown next to the person's name to
          help others recognize the person in search results.
        items:
          $ref: '#/definitions/Photo'
        type: array
    type: object
  Photo:
    description: A person's photo.
    properties:
      url:
        description: The URL of the photo.
        type: string
    type: object
  PollItemsRequest:
    properties:
      connectorName:
        description: |-
          Name of connector making this call.
          <br />Format: datasources/{source_id}/connectors/{ID}
        type: string
      debugOptions:
        $ref: '#/definitions/DebugOptions'
        description: Common debug options.
      limit:
        description: |-
          Maximum number of items to return.
          <br />The maximum and the default value is 1000
        format: int32
        type: integer
      queue:
        description: |-
          Queue name to fetch items from.  If unspecified, PollItems will
          fetch from 'default' queue.
          The maximum length is 100 characters.
        type: string
      statusCodes:
        description: Limit the items polled to the ones with these statuses.
        items:
          enum:
            - CODE_UNSPECIFIED
            - ERROR
            - MODIFIED
            - NEW_ITEM
            - ACCEPTED
          type: string
        type: array
    type: object
  PollItemsResponse:
    properties:
      items:
        description: |-
          Set of items from the queue available for connector to process.
          <br />These items have the following subset of fields populated: <br />
          <br />version
          <br />metadata.hash
          <br />structured_data.hash
          <br />content.hash
          <br />payload
          <br />status
          <br />queue
        items:
          $ref: '#/definitions/Item'
        type: array
    type: object
  Principal:
    description: 'Reference to a user, group, or domain.'
    properties:
      groupResourceName:
        description: |-
          This principal is a group identified using an external identity.
          The name field must specify the group resource name with this format:
          identitysources/{source_id}/groups/{ID}
        type: string
      gsuitePrincipal:
        $ref: '#/definitions/GSuitePrincipal'
        description: 'This principal is a GSuite user, group or domain.'
      userResourceName:
        description: |-
          This principal is a user identified using an external identity.
          The name field must specify the user resource name with this format:
          identitysources/{source_id}/users/{ID}
        type: string
    type: object
  ProcessingError:
    properties:
      code:
        description: Error code indicating the nature of the error.
        enum:
          - PROCESSING_ERROR_CODE_UNSPECIFIED
          - MALFORMED_REQUEST
          - UNSUPPORTED_CONTENT_FORMAT
          - INDIRECT_BROKEN_ACL
          - ACL_CYCLE
        type: string
      errorMessage:
        description: Description of the error.
        type: string
      fieldViolations:
        description: |-
          In case the item fields are invalid, this field contains the details
          about the validation errors.
        items:
          $ref: '#/definitions/FieldViolation'
        type: array
    type: object
  PropertyDefinition:
    description: The definition of a property within an object.
    properties:
      booleanPropertyOptions:
        $ref: '#/definitions/BooleanPropertyOptions'
      datePropertyOptions:
        $ref: '#/definitions/DatePropertyOptions'
      displayOptions:
        $ref: '#/definitions/PropertyDisplayOptions'
        description: |-
          Options that determine how the property is displayed in the Cloud Search
          results page if it is specified to be displayed in the object's
          display options
          .
      doublePropertyOptions:
        $ref: '#/definitions/DoublePropertyOptions'
      enumPropertyOptions:
        $ref: '#/definitions/EnumPropertyOptions'
      htmlPropertyOptions:
        $ref: '#/definitions/HtmlPropertyOptions'
      integerPropertyOptions:
        $ref: '#/definitions/IntegerPropertyOptions'
      isFacetable:
        description: |-
          Indicates that the property can be used for generating facets. Cannot be
          true for properties whose type is object. IsReturnable must be true to set
          this option.
          Only supported for Boolean, Enum, and Text properties.
        type: boolean
      isRepeatable:
        description: |-
          Indicates that multiple values are allowed for the property. For example, a
          document only has one description but can have multiple comments. Cannot be
          true for properties whose type is a boolean.
          If set to false, properties that contain more than one value will cause the
          indexing request for that item to be rejected.
        type: boolean
      isReturnable:
        description: |-
          Indicates that the property identifies data that should be returned in
          search results via the Query API. If set to *true*, indicates that Query
          API users can use matching property fields in results. However, storing
          fields requires more space allocation and uses more bandwidth for search
          queries, which impacts performance over large datasets. Set to *true* here
          only if the field is needed for search results. Cannot be true for
          properties whose type is an object.
        type: boolean
      isSortable:
        description: |-
          Indicates that the property can be used for sorting. Cannot be true for
          properties that are repeatable. Cannot be true for properties whose type
          is object or user identifier. IsReturnable must be true to set this option.
          Only supported for Boolean, Date, Double, Integer, and Timestamp
          properties.
        type: boolean
      isWildcardSearchable:
        description: |-
          Indicates that users can perform wildcard search for this
          property. Only supported for Text properties. IsReturnable must be true to
          set this option. In a given datasource maximum of 5 properties can be
          marked as is_wildcard_searchable.

          Note: This is an alpha feature and is enabled for whitelisted users only.
        type: boolean
      name:
        description: |-
          The name of the property. Item indexing requests sent to the Indexing API
          should set the property name
          equal to this value. For example, if name is *subject_line*, then indexing
          requests for document items with subject fields should set the
          name for that field equal to
          *subject_line*. Use the name as the identifier for the object property.
          Once registered as a property for an object, you cannot re-use this name
          for another property within that object.
          The name must start with a letter and can only contain letters (A-Z, a-z)
          or numbers (0-9).
          The maximum length is 256 characters.
        type: string
      objectPropertyOptions:
        $ref: '#/definitions/ObjectPropertyOptions'
      textPropertyOptions:
        $ref: '#/definitions/TextPropertyOptions'
      timestampPropertyOptions:
        $ref: '#/definitions/TimestampPropertyOptions'
    type: object
  PropertyDisplayOptions:
    description: The display options for a property.
    properties:
      displayLabel:
        description: |-
          The user friendly label for the property that will be used if the property
          is specified to be displayed in ObjectDisplayOptions. If given, the display
          label will be shown in front of the property values when the property is
          part of the object display options. For example, if the property value is
          '1', the value by itself may not be useful context for the user. If the
          display name given was 'priority', then the user will see 'priority : 1' in
          the search results which provides clear conext to search users. This is
          OPTIONAL; if not given, only the property values will be displayed.
          The maximum length is 32 characters.
        type: string
    type: object
  PushItem:
    description: Represents an item to be pushed to the indexing queue.
    properties:
      contentHash:
        description: |-
          Content hash of the item according to the repository. If specified, this is
          used to determine how to modify this
          item's status. Setting this field and the
          type field results in argument
          error.
          The maximum length is 2048 characters.
        type: string
      metadataHash:
        description: |-
          Metadata hash of the item according to the repository. If specified, this
          is used to determine how to modify this
          item's status. Setting this field and the
          type field results in argument
          error.
          The maximum length is 2048 characters.
        type: string
      payload:
        description: |-
          Provides additional document state information for the connector,
          such as an alternate repository ID and other metadata.
          The maximum length is 8192 bytes.
        format: byte
        type: string
      queue:
        description: |-
          Queue to which this item belongs to.  The <code>default</code> queue is
          chosen if this field is not specified. The maximum length is
          512 characters.
        type: string
      repositoryError:
        $ref: '#/definitions/RepositoryError'
        description: |-
          Populate this field to store Connector or repository error details.
          This information is displayed in the Admin Console.
          This field may only be populated when the
          Type is
          REPOSITORY_ERROR.
      structuredDataHash:
        description: |-
          Structured data hash of the item according to the repository. If specified,
          this is used to determine how to modify this item's status. Setting this
          field and the type field
          results in argument error.
          The maximum length is 2048 characters.
        type: string
      type:
        description: The type of the push operation that defines the push behavior.
        enum:
          - UNSPECIFIED
          - MODIFIED
          - NOT_MODIFIED
          - REPOSITORY_ERROR
          - REQUEUE
        type: string
    type: object
  PushItemRequest:
    properties:
      connectorName:
        description: |-
          Name of connector making this call.
          <br />Format: datasources/{source_id}/connectors/{ID}
        type: string
      debugOptions:
        $ref: '#/definitions/DebugOptions'
        description: Common debug options.
      item:
        $ref: '#/definitions/PushItem'
        description: Item to push onto the queue.
    type: object
  QueryInterpretation:
    properties:
      interpretationType:
        enum:
          - NONE
          - BLEND
          - REPLACE
        type: string
      interpretedQuery:
        description: |-
          The interpretation of the query used in search. For example, query "email
          from john" will be interpreted as "from:john source:mail"
        type: string
    type: object
  QueryInterpretationOptions:
    description: Options to interpret user query.
    properties:
      disableNlInterpretation:
        description: |-
          Flag to disable natural language (NL) interpretation of queries. Default is
          false, Set to true to disable natural language interpretation. NL
          interpretation only applies to predefined datasources.
        type: boolean
    type: object
  QueryItem:
    description: Information relevant only to a query entry.
    properties:
      isSynthetic:
        description: True if the text was generated by means other than a previous user search.
        type: boolean
    type: object
  QueryOperator:
    description: The definition of a operator that can be used in a Search/Suggest request.
    properties:
      displayName:
        description: Display name of the operator
        type: string
      enumValues:
        description: |-
          Potential list of values for the opeatror field. This field is only filled
          when we can safely enumerate all the possible values of this operator.
        items:
          type: string
        type: array
      greaterThanOperatorName:
        description: |-
          Indicates the operator name that can be used to  isolate the property using
          the greater-than operator.
        type: string
      isFacetable:
        description: Can this operator be used to get facets.
        type: boolean
      isRepeatable:
        description: Indicates if multiple values can be set for this property.
        type: boolean
      isReturnable:
        description: |-
          Will the property associated with this facet be returned as part of search
          results.
        type: boolean
      isSortable:
        description: Can this operator be used to sort results.
        type: boolean
      isSuggestable:
        description: Can get suggestions for this field.
        type: boolean
      lessThanOperatorName:
        description: |-
          Indicates the operator name that can be used to  isolate the property using
          the less-than operator.
        type: string
      operatorName:
        description: The name of the operator.
        type: string
      type:
        description: Type of the operator.
        enum:
          - UNKNOWN
          - INTEGER
          - DOUBLE
          - TIMESTAMP
          - BOOLEAN
          - ENUM
          - DATE
          - TEXT
          - HTML
        type: string
    type: object
  QuerySource:
    description: List of sources that the user can search using the query API.
    properties:
      displayName:
        description: Display name of the data source.
        type: string
      operators:
        description: List of all operators applicable for this source.
        items:
          $ref: '#/definitions/QueryOperator'
        type: array
      shortName:
        description: |-
          A short name or alias for the source.  This value can be used with the
          'source' operator.
        type: string
      source:
        $ref: '#/definitions/Source'
        description: Name of the source
    type: object
  QuerySuggestion:
    description: |-
      This field does not contain anything as of now and is just used as an
      indicator that the suggest result was a phrase completion.
    properties: {}
    type: object
  RepositoryError:
    description: Errors when the connector is communicating to the source repository.
    properties:
      errorMessage:
        description: |-
          Message that describes the error. The maximum allowable length
          of the message is 8192 characters.
        type: string
      httpStatusCode:
        description: Error codes.  Matches the definition of HTTP status codes.
        format: int32
        type: integer
      type:
        description: Type of error.
        enum:
          - UNKNOWN
          - NETWORK_ERROR
          - DNS_ERROR
          - CONNECTION_ERROR
          - AUTHENTICATION_ERROR
          - AUTHORIZATION_ERROR
          - SERVER_ERROR
          - QUOTA_EXCEEDED
          - SERVICE_UNAVAILABLE
          - CLIENT_ERROR
        type: string
    type: object
  RequestOptions:
    description: Shared request options for all RPC methods.
    properties:
      debugOptions:
        $ref: '#/definitions/DebugOptions'
        description: Debug options of the request
      languageCode:
        description: |-
          The BCP-47 language code, such as "en-US" or "sr-Latn".
          For more information, see
          http://www.unicode.org/reports/tr35/#Unicode_locale_identifier.
          For translations.

          When specified, the documents in search results are biased towards the
          specified language.
          Suggest API does not use this parameter. It autocompletes only based on
          characters in the query.
        type: string
      searchApplicationId:
        description: Id of the application created using SearchApplicationsService.
        type: string
      timeZone:
        description: |-
          Current user's time zone id, such as "America/Los_Angeles" or
          "Australia/Sydney". These IDs are defined by
          [Unicode Common Locale Data Repository (CLDR)](http://cldr.unicode.org/)
          project, and currently available in the file
          [timezone.xml](http://unicode.org/repos/cldr/trunk/common/bcp47/timezone.xml)
        type: string
    type: object
  ResetSearchApplicationRequest:
    properties:
      debugOptions:
        $ref: '#/definitions/DebugOptions'
        description: Common debug options.
    type: object
  ResponseDebugInfo:
    description: Debugging information about the response.
    properties:
      formattedDebugInfo:
        description: General debug info formatted for display.
        type: string
    type: object
  RestrictItem:
    description: |-
      Information relevant only to a restrict entry.
      NextId: 12
    properties:
      driveFollowUpRestrict:
        $ref: '#/definitions/DriveFollowUpRestrict'
        description: LINT.ThenChange(//depot/google3/java/com/google/apps/search/quality/itemsuggest/utils/SubtypeRerankingUtils.java)
      driveLocationRestrict:
        $ref: '#/definitions/DriveLocationRestrict'
      driveMimeTypeRestrict:
        $ref: '#/definitions/DriveMimeTypeRestrict'
        description: |-
          LINT.IfChange
          Drive Types.
      driveTimeSpanRestrict:
        $ref: '#/definitions/DriveTimeSpanRestrict'
      gmailActionRestrict:
        $ref: '#/definitions/GmailActionRestrict'
      gmailAttachmentRestrict:
        $ref: '#/definitions/GmailAttachmentRestrict'
      gmailFolderRestrict:
        $ref: '#/definitions/GmailFolderRestrict'
        description: Gmail Types.
      gmailIntelligentRestrict:
        $ref: '#/definitions/GmailIntelligentRestrict'
      gmailTimeRestrict:
        $ref: '#/definitions/GmailTimeRestrict'
      searchOperator:
        description: 'The search restrict (e.g. "after:2017-09-11 before:2017-09-12").'
        type: string
    type: object
  ResultCounts:
    description: Result count information
    properties:
      sourceResultCounts:
        description: Result count information for each source with results.
        items:
          $ref: '#/definitions/SourceResultCount'
        type: array
    type: object
  ResultDebugInfo:
    description: Debugging information about the result.
    properties:
      formattedDebugInfo:
        description: General debug info formatted for display.
        type: string
    type: object
  ResultDisplayField:
    description: Display Fields for Search Results
    properties:
      label:
        description: The display label for the property.
        type: string
      operatorName:
        description: The operator name of the property.
        type: string
      property:
        $ref: '#/definitions/NamedProperty'
        description: The name value pair for the property.
    type: object
  ResultDisplayLine:
    description: The collection of fields that make up a displayed line
    properties:
      fields:
        items:
          $ref: '#/definitions/ResultDisplayField'
        type: array
    type: object
  ResultDisplayMetadata:
    properties:
      metalines:
        description: The metalines content to be displayed with the result.
        items:
          $ref: '#/definitions/ResultDisplayLine'
        type: array
      objectTypeLabel:
        description: The display label for the object.
        type: string
    type: object
  RetrievalImportance:
    properties:
      importance:
        description: |-
          Indicates the ranking importance given to property when it is matched
          during retrieval. Once set, the token importance of a property cannot be
          changed.
        enum:
          - DEFAULT
          - HIGHEST
          - HIGH
          - LOW
          - NONE
        type: string
    type: object
  Schema:
    description: The schema definition for a data source.
    properties:
      objectDefinitions:
        description: |-
          The list of top-level objects for the data source.
          The maximum number of elements is 10.
        items:
          $ref: '#/definitions/ObjectDefinition'
        type: array
      operationIds:
        description: |-
          IDs of the Long Running Operations (LROs) currently running for this
          schema. After modifying the schema, wait for operations to complete
          before indexing additional content.
        items:
          type: string
        type: array
    type: object
  ScoringConfig:
    description: |-
      Scoring configurations for a source while processing a
      Search or
      Suggest request.
    properties:
      disableFreshness:
        description: |-
          Whether to use freshness as a ranking signal. By default, freshness is used
          as a ranking signal. Note that this setting is not available in the Admin
          UI.
        type: boolean
      disablePersonalization:
        description: |-
          Whether to personalize the results. By default, personal signals will
          be used to boost results.
        type: boolean
    type: object
  SearchApplication:
    description: SearchApplication
    properties:
      dataSourceRestrictions:
        description: |-
          Retrictions applied to the configurations.
          The maximum number of elements is 10.
        items:
          $ref: '#/definitions/DataSourceRestriction'
        type: array
      defaultFacetOptions:
        description: |-
          The default fields for returning facet results.
          The sources specified here also have been included in
          data_source_restrictions
          above.
        items:
          $ref: '#/definitions/FacetOptions'
        type: array
      defaultSortOptions:
        $ref: '#/definitions/SortOptions'
        description: The default options for sorting the search results
      displayName:
        description: |-
          Display name of the Search Application.
          The maximum length is 300 characters.
        type: string
      name:
        description: |-
          Name of the Search Application.
          <br />Format: searchapplications/{application_id}.
        type: string
      operationIds:
        description: |-
          IDs of the Long Running Operations (LROs) currently running for this
          schema. Output only field.
        items:
          type: string
        type: array
      scoringConfig:
        $ref: '#/definitions/ScoringConfig'
        description: Configuration for ranking results.
      sourceConfig:
        description: Configuration for a sources specified in data_source_restrictions.
        items:
          $ref: '#/definitions/SourceConfig'
        type: array
    type: object
  SearchItemsByViewUrlRequest:
    properties:
      debugOptions:
        $ref: '#/definitions/DebugOptions'
        description: Common debug options.
      pageToken:
        description: 'The next_page_token value returned from a previous request, if any.'
        type: string
      viewUrl:
        description: |-
          Specify the full view URL to find the corresponding item.
          The maximum length is 2048 characters.
        type: string
    type: object
  SearchItemsByViewUrlResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/Item'
        type: array
      nextPageToken:
        description: |-
          Token to retrieve the next page of results, or empty if there are no
          more results in the list.
        type: string
    type: object
  SearchQualityMetadata:
    description: Additional search quality metadata of the item.
    properties:
      quality:
        description: |-
          An indication of the quality of the item, used to influence search quality.
          Value should be between 0.0 (lowest quality) and 1.0 (highest quality). The
          default value is 0.0.
        format: double
        type: number
    type: object
  SearchRequest:
    description: The search API request.
    properties:
      dataSourceRestrictions:
        description: |-
          The sources to use for querying. If not specified, all data sources
          from the current search application are used.
        items:
          $ref: '#/definitions/DataSourceRestriction'
        type: array
      facetOptions:
        items:
          $ref: '#/definitions/FacetOptions'
        type: array
      pageSize:
        description: |-
          Maximum number of search results to return in one page.
          Valid values are between 1 and 100, inclusive.
          Default value is 10.
        format: int32
        type: integer
      query:
        description: |-
          The raw query string.
          See supported search operators in the [Cloud search
          Cheat
          Sheet](https://gsuite.google.com/learning-center/products/cloudsearch/cheat-sheet/)
        type: string
      queryInterpretationOptions:
        $ref: '#/definitions/QueryInterpretationOptions'
        description: Options to interpret the user query.
      requestOptions:
        $ref: '#/definitions/RequestOptions'
        description: 'Request options, such as the search application and user timezone.'
      sortOptions:
        $ref: '#/definitions/SortOptions'
        description: The options for sorting the search results
      start:
        description: Starting index of the results.
        format: int32
        type: integer
    type: object
  SearchResponse:
    description: The search API response.
    properties:
      debugInfo:
        $ref: '#/definitions/ResponseDebugInfo'
        description: Debugging information about the response.
      errorInfo:
        $ref: '#/definitions/ErrorInfo'
        description: Error information about the response.
      facetResults:
        description: Repeated facet results.
        items:
          $ref: '#/definitions/FacetResult'
        type: array
      hasMoreResults:
        description: Whether there are more search results matching the query.
        type: boolean
      queryInterpretation:
        $ref: '#/definitions/QueryInterpretation'
        description: |-
          Query interpretation result for user query. Empty if query interpretation
          is disabled.
      resultCountEstimate:
        description: The estimated result count for this query.
        format: int64
        type: string
      resultCountExact:
        description: The exact result count for this query.
        format: int64
        type: string
      resultCounts:
        $ref: '#/definitions/ResultCounts'
        description: Expanded result count information.
      results:
        description: Results from a search query.
        items:
          $ref: '#/definitions/SearchResult'
        type: array
      spellResults:
        description: Suggested spelling for the query.
        items:
          $ref: '#/definitions/SpellResult'
        type: array
      structuredResults:
        description: |-
          Structured results for the user query. These results are not counted
          against the page_size.
        items:
          $ref: '#/definitions/StructuredResult'
        type: array
    type: object
  SearchResult:
    description: Results containing indexed information for a document.
    properties:
      clusteredResults:
        description: |-
          If source is clustered, provide list of clustered results. There will only
          be one level of clustered results. If current source is not enabled for
          clustering, this field will be empty.
        items:
          $ref: '#/definitions/SearchResult'
        type: array
      debugInfo:
        $ref: '#/definitions/ResultDebugInfo'
        description: Debugging information about this search result.
      metadata:
        $ref: '#/definitions/Metadata'
        description: Metadata of the search result.
      snippet:
        $ref: '#/definitions/Snippet'
        description: The concatenation of all snippets (summaries) available for this result.
      title:
        description: Title of the search result.
        type: string
      url:
        description: |-
          The URL of the search result. The URL contains a Google redirect to the
          actual item. This URL is signed and shouldn't be changed.
        type: string
    type: object
  Snippet:
    description: |-
      Snippet of the search result, which summarizes the content of the resulting
      page.
    properties:
      matchRanges:
        description: The matched ranges in the snippet.
        items:
          $ref: '#/definitions/MatchRange'
        type: array
      snippet:
        description: |-
          The snippet of the document.
          The snippet of the document. May contain escaped HTML character that
          should be unescaped prior to rendering.
        type: string
    type: object
  SortOptions:
    properties:
      operatorName:
        description: |-
          Name of the operator corresponding to the field to sort on.
          The corresponding property must be marked as
          sortable.
        type: string
      sortOrder:
        description: Ascending is the default sort order
        enum:
          - ASCENDING
          - DESCENDING
        type: string
    type: object
  Source:
    description: Defines sources for the suggest/search APIs.
    properties:
      name:
        description: |-
          Source name for content indexed by the
          Indexing API.
        type: string
      predefinedSource:
        description: Predefined content source for Google Apps.
        enum:
          - NONE
          - QUERY_HISTORY
          - PERSON
          - GOOGLE_DRIVE
          - GOOGLE_GMAIL
          - GOOGLE_SITES
          - GOOGLE_GROUPS
          - GOOGLE_CALENDAR
          - GOOGLE_KEEP
        type: string
    type: object
  SourceConfig:
    description: |-
      Configurations for a source while processing a
      Search or
      Suggest request.
    properties:
      crowdingConfig:
        $ref: '#/definitions/SourceCrowdingConfig'
        description: The crowding configuration for the source.
      scoringConfig:
        $ref: '#/definitions/SourceScoringConfig'
        description: The scoring configuration for the source.
      source:
        $ref: '#/definitions/Source'
        description: The source for which this configuration is to be used.
    type: object
  SourceCrowdingConfig:
    description: |-
      Set search results crowding limits. Crowding is a situation in which
      multiple results from the same source or host "crowd out" other results,
      diminishing the quality of search for users. To foster better search quality
      and source diversity in search results, you can set a condition to reduce
      repetitive results by source.
    properties:
      field:
        description: |-
          Use a field to control results crowding. For example, if you want to
          control overly similar results from Gmail topics, use `thread_id`.
          For similar pages from Google Sites, you can use `webspace_id`.
          When matching query results contain the same field value in
          `GenericMetadata`, crowding limits are set on those records.
        type: string
      numResults:
        description: |-
          Maximum number of results allowed from a source.
          No limits will be set on results if this value is less than or equal to 0.
        format: int32
        type: integer
      numSuggestions:
        description: |-
          Maximum number of suggestions allowed from a source.
          No limits will be set on results if this value is less than or equal to 0.
        format: int32
        type: integer
      source:
        description: |-
          Control results by content source. This option limits the total number
          of results from a given source and ignores field-based crowding control.
        type: boolean
    type: object
  SourceResultCount:
    description: Per source result count information.
    properties:
      hasMoreResults:
        description: Whether there are more search results for this source.
        type: boolean
      resultCountEstimate:
        description: The estimated result count for this source.
        format: int64
        type: string
      resultCountExact:
        description: The exact result count for this source.
        format: int64
        type: string
      source:
        $ref: '#/definitions/Source'
        description: The source the result count information is associated with.
    type: object
  SourceScoringConfig:
    description: |-
      Set the scoring configuration. This allows modifying the ranking of results
      for a source.
    properties:
      sourceImportance:
        description: Importance of the source.
        enum:
          - DEFAULT
          - LOW
          - HIGH
        type: string
    type: object
  SpellResult:
    properties:
      suggestedQuery:
        description: The suggested spelling of the query.
        type: string
    type: object
  StartUploadItemRequest:
    description: Start upload file request.
    properties:
      connectorName:
        description: |-
          Name of connector making this call.
          <br />Format: datasources/{source_id}/connectors/{ID}
        type: string
      debugOptions:
        $ref: '#/definitions/DebugOptions'
        description: Common debug options.
    type: object
  Status:
    description: |-
      The `Status` type defines a logical error model that is suitable for
      different programming environments, including REST APIs and RPC APIs. It is
      used by [gRPC](https://github.com/grpc). Each `Status` message contains
      three pieces of data: error code, error message, and error details.

      You can find out more about this error model and how to work with it in the
      [API Design Guide](https://cloud.google.com/apis/design/errors).
    properties:
      code:
        description: 'The status code, which should be an enum value of google.rpc.Code.'
        format: int32
        type: integer
      details:
        description: |-
          A list of messages that carry the error details.  There is a common set of
          message types for APIs to use.
        items:
          additionalProperties:
            description: Properties of the object. Contains field @type with type URL.
          type: object
        type: array
      message:
        description: |-
          A developer-facing error message, which should be in English. Any
          user-facing error message should be localized and sent in the
          google.rpc.Status.details field, or localized by the client.
        type: string
    type: object
  StructuredDataObject:
    description: A structured data object consisting of named properties.
    properties:
      properties:
        description: |-
          The properties for the object.
          The maximum number of elements is 1000.
        items:
          $ref: '#/definitions/NamedProperty'
        type: array
    type: object
  StructuredResult:
    description: Structured results that are returned as part of search request.
    properties:
      person:
        $ref: '#/definitions/Person'
        description: Representation of a person
    type: object
  SuggestRequest:
    description: Request of suggest API.
    properties:
      dataSourceRestrictions:
        description: |-
          The sources to use for suggestions. If not specified, all data sources
          from the current search application are used.
          Suggestions are based on Gmail titles. Suggestions from third party sources
          are not available.
        items:
          $ref: '#/definitions/DataSourceRestriction'
        type: array
      query:
        description: |-
          Partial query for which autocomplete suggestions will be shown.
          For example, if the query is "sea", then the server might return
          "season", "search", "seagull" and so on.
        type: string
      requestOptions:
        $ref: '#/definitions/RequestOptions'
        description: 'Request options, such as the search application and user timezone.'
    type: object
  SuggestResponse:
    description: Response of the suggest API.
    properties:
      suggestResults:
        description: List of suggestions.
        items:
          $ref: '#/definitions/SuggestResult'
        type: array
    type: object
  SuggestResult:
    description: One suggestion result.
    properties:
      peopleSuggestion:
        $ref: '#/definitions/PeopleSuggestion'
        description: |-
          This is present when the suggestion indicates a person. It
          contains more information about the person - like their email ID,
          name etc.
      querySuggestion:
        $ref: '#/definitions/QuerySuggestion'
        description: |-
          This field will be present if the suggested query is a word/phrase
          completion.
      source:
        $ref: '#/definitions/Source'
        description: The source of the suggestion.
      suggestedQuery:
        description: |-
          The suggested query that will be used for search, when the user
          clicks on the suggestion
        type: string
    type: object
  TextOperatorOptions:
    description: |-
      Used to provide a search operator for text properties. This is optional.
      Search operators let users restrict the query to specific fields relevant
      to the type of item being searched.
    properties:
      exactMatchWithOperator:
        description: |-
          If true, the text value will be tokenized as one atomic value in
          operator searches and facet matches. For example, if the operator name is
          "genre" and the value is "science-fiction" the query restrictions
          "genre:science" and "genre:fiction" will not match the item;
          "genre:science-fiction" will. Value matching is case-sensitive
          and does not remove special characters.
          If false, the text will be tokenized. For example, if the value is
          "science-fiction" the queries "genre:science" and "genre:fiction" will
          match the item.
        type: boolean
      operatorName:
        description: |-
          Indicates the operator name required in the query in order to isolate the
          text property. For example, if operatorName is *subject* and the
          property's name is *subjectLine*, then queries like
          *subject:&lt;value&gt;* will show results only where the value of the
          property named *subjectLine* matches *&lt;value&gt;*. By contrast, a
          search that uses the same *&lt;value&gt;* without an operator will return
          all items where *&lt;value&gt;* matches the value of any
          text properties or text within the content field for the item.
          The operator name can only contain lowercase letters (a-z).
          The maximum length is 32 characters.
        type: string
    type: object
  TextPropertyOptions:
    description: Options for text properties.
    properties:
      operatorOptions:
        $ref: '#/definitions/TextOperatorOptions'
        description: 'If set, describes how the property should be used as a search operator.'
      retrievalImportance:
        $ref: '#/definitions/RetrievalImportance'
        description: |-
          Indicates the search quality importance of the tokens within the
          field when used for retrieval.
    type: object
  TextValues:
    description: List of text values.
    properties:
      values:
        description: The maximum allowable length for text values is 2048 characters.
        items:
          type: string
        type: array
    type: object
  TimestampOperatorOptions:
    description: |-
      Used to provide a search operator for timestamp properties. This is
      optional. Search operators let users restrict the query to specific fields
      relevant to the type of item being searched.
    properties:
      greaterThanOperatorName:
        description: |-
          Indicates the operator name required in the query in order to isolate the
          timestamp property using the greater-than operator. For example, if
          greaterThanOperatorName is *closedafter* and the property's name is
          *closeDate*, then queries like *closedafter:&lt;value&gt;* will
          show results only where the value of the property named *closeDate* is
          later than *&lt;value&gt;*.
          The operator name can only contain lowercase letters (a-z).
          The maximum length is 32 characters.
        type: string
      lessThanOperatorName:
        description: |-
          Indicates the operator name required in the query in order to isolate the
          timestamp property using the less-than operator. For example, if
          lessThanOperatorName is *closedbefore* and the property's name is
          *closeDate*, then queries like *closedbefore:&lt;value&gt;* will
          show results only where the value of the property named *closeDate* is
          earlier than *&lt;value&gt;*.
          The operator name can only contain lowercase letters (a-z).
          The maximum length is 32 characters.
        type: string
      operatorName:
        description: |-
          Indicates the operator name required in the query in order to isolate the
          timestamp property. For example, if operatorName is *closedon* and the
          property's name is *closeDate*, then queries like
          *closedon:&lt;value&gt;* will show results only where the value of the
          property named *closeDate* matches *&lt;value&gt;*. By contrast, a
          search that uses the same *&lt;value&gt;* without an operator will return
          all items where *&lt;value&gt;* matches the value of any String
          properties or text within the content field for the item. The operator
          name can only contain lowercase letters (a-z). The maximum length is 32
          characters.
        type: string
    type: object
  TimestampPropertyOptions:
    description: Options for timestamp properties.
    properties:
      operatorOptions:
        $ref: '#/definitions/TimestampOperatorOptions'
        description: 'If set, describes how the timestamp should be used as a search operator.'
    type: object
  TimestampValues:
    description: List of timestamp values.
    properties:
      values:
        items:
          format: google-datetime
          type: string
        type: array
    type: object
  UnmappedIdentity:
    properties:
      externalIdentity:
        $ref: '#/definitions/Principal'
        description: The resource name for an external user.
      resolutionStatusCode:
        description: The resolution status for the external identity.
        enum:
          - CODE_UNSPECIFIED
          - NOT_FOUND
          - IDENTITY_SOURCE_NOT_FOUND
          - IDENTITY_SOURCE_MISCONFIGURED
          - TOO_MANY_MAPPINGS_FOUND
          - INTERNAL_ERROR
        type: string
    type: object
  UnreserveItemsRequest:
    properties:
      connectorName:
        description: |-
          Name of connector making this call.
          <br />Format: datasources/{source_id}/connectors/{ID}
        type: string
      debugOptions:
        $ref: '#/definitions/DebugOptions'
        description: Common debug options.
      queue:
        description: Name of a queue to unreserve items from.
        type: string
    type: object
  UpdateDataSourceRequest:
    properties:
      debugOptions:
        $ref: '#/definitions/DebugOptions'
        description: Common debug options.
      source:
        $ref: '#/definitions/DataSource'
    type: object
  UpdateSchemaRequest:
    properties:
      debugOptions:
        $ref: '#/definitions/DebugOptions'
        description: Common debug options.
      schema:
        $ref: '#/definitions/Schema'
        description: The new schema for the source.
      validateOnly:
        description: 'If true, the request will be validated without side effects.'
        type: boolean
    type: object
  UploadItemRef:
    description: |-
      Represents an upload session reference.
      This reference is created via upload
      method.
      Updating of item content may refer to this uploaded content via
      contentDataRef.
    properties:
      name:
        description: |-
          Name of the content reference.
          The maximum length is 2048 characters.
        type: string
    type: object
  Value:
    description: Definition of a single value with generic type.
    properties:
      booleanValue:
        type: boolean
      dateValue:
        $ref: '#/definitions/Date'
      doubleValue:
        format: double
        type: number
      integerValue:
        format: int64
        type: string
      stringValue:
        type: string
      timestampValue:
        format: google-datetime
        type: string
    type: object
  ValueFilter:
    properties:
      operatorName:
        description: |-
          The `operator_name` applied to the query, such as *price_greater_than*.
          The filter can work against both types of filters defined in the schema
          for your data source:
          <br/><br/>
          1. `operator_name`, where the query filters results by the property
          that matches the value.
          <br/>
          2. `greater_than_operator_name` or `less_than_operator_name` in your
          schema. The query filters the results for the property values that are
          greater than or less than  the supplied value in the query.
        type: string
      value:
        $ref: '#/definitions/Value'
        description: The value to be compared with.
    type: object
