# coding: utf-8

"""
    Cloud Logging API

    Writes log entries and manages your Cloud Logging configuration.

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.delete_link_request import DeleteLinkRequest

class TestDeleteLinkRequest(unittest.TestCase):
    """DeleteLinkRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteLinkRequest:
        """Test DeleteLinkRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteLinkRequest`
        """
        model = DeleteLinkRequest()
        if include_optional:
            return DeleteLinkRequest(
                name = ''
            )
        else:
            return DeleteLinkRequest(
        )
        """

    def testDeleteLinkRequest(self):
        """Test DeleteLinkRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
