# coding: utf-8

"""
    PostgreSQLManagementClient

    The Microsoft Azure management API provides create, read, update, and delete functionality for Azure PostgreSQL resources including servers, databases, firewall rules, VNET rules, security alert policies, log files and configurations with new business model.

    The version of the OpenAPI document: 2017-12-01-preview
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.firewall_rule import FirewallRule

class TestFirewallRule(unittest.TestCase):
    """FirewallRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FirewallRule:
        """Test FirewallRule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FirewallRule`
        """
        model = FirewallRule()
        if include_optional:
            return FirewallRule(
                properties = openapi_client.models.firewall_rule_properties.FirewallRuleProperties(
                    end_ip_address = '4.207.188.200', 
                    start_ip_address = '4.207.188.200', ),
                id = '',
                name = '',
                type = ''
            )
        else:
            return FirewallRule(
                properties = openapi_client.models.firewall_rule_properties.FirewallRuleProperties(
                    end_ip_address = '4.207.188.200', 
                    start_ip_address = '4.207.188.200', ),
        )
        """

    def testFirewallRule(self):
        """Test FirewallRule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
