openapi: 3.0.0
servers:
  - url: 'https://slack.com/api'
info:
  description: A messaging app for teams
  termsOfService: 'https://slack.com/terms-of-service/api'
  title: Slack
  version: 1.0.0
  x-apisguru-categories:
    - collaboration
    - messaging
  x-logo:
    url: 'http://static.tumblr.com/wvuzcz9/LlKncfhmp/slack_logo_240.png'
  x-origin:
    - format: swagger
      url: 'https://raw.githubusercontent.com/APIs-guru/unofficial_openapi_specs/master/slack.com/1.0.0/swagger.yaml'
      version: '2.0'
  x-providerName: slack.com
  x-unofficialSpec: true
paths:
  /auth.test:
    get:
      description: Checks authentication and tells you who you are.
      security:
        - oauth_2_0:
            - identify
  /channels.history:
    get:
      description: Fetches history of messages and events from a channel.
  /channels.info:
    get:
      description: Gets information about a channel.
  /channels.invite:
    get:
      description: Invites a user to a channel.
  /channels.join:
    get:
      description: 'Joins a channel, creating it if needed.'
  /channels.leave:
    get:
      description: Leaves a channel.
  /channels.list:
    get:
      description: Lists all channels in a Slack team.
  /channels.mark:
    get:
      description: Sets the read cursor in a channel.
  /channels.setPurpose:
    get:
      description: Sets the purpose for a channel.
  /channels.setTopic:
    get:
      description: Sets the topic for a channel.
  /chat.delete:
    get:
      description: Deletes a message.
  /chat.postMessage:
    get:
      description: Sends a message to a channel.
  /chat.update:
    get:
      description: Updates a message.
  /emoji.list:
    get:
      description: Lists custom emoji for a team.
  /files.info:
    get:
      description: Gets information about a team file.
  /files.list:
    get:
      description: Lists and filters team files.
  /files.upload:
    get:
      description: Uploads or creates a file.
  /groups.history:
    get:
      description: Fetches history of messages and events from a private group.
  /groups.list:
    get:
      description: Lists private groups that the calling user has access to.
  /groups.mark:
    get:
      description: Sets the read cursor in a private group.
  /groups.setPurpose:
    get:
      description: Sets the purpose for a private group.
  /groups.setTopic:
    get:
      description: Sets the topic for a private group.
  /im.history:
    get:
      description: Fetches history of messages and events from direct message channel.
  /im.list:
    get:
      description: Lists direct message channels for the calling user.
  /im.mark:
    get:
      description: Sets the read cursor in a direct message channel.
  /search.all:
    get:
      description: Searches for messages and files matching a query.
  /search.files:
    get:
      description: Searches for files matching a query.
  /search.messages:
    get:
      description: Searches for messages matching a query.
  /stars.list:
    get:
      description: Lists stars for a user.
  /users.list:
    get:
      description: Lists all users in a Slack team.
components:
  securitySchemes:
    oauth_2_0:
      description: ''
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://slack.com/oauth/authorize'
          tokenUrl: 'https://slack.com/api/oauth.access'
          scopes:
            admin: ''
            'channels:history': ''
            'channels:read': ''
            'channels:write': ''
            'chat:write:bot': ''
            'chat:write:user': ''
            client: ''
            'dnd:read': ''
            'dnd:write': ''
            'emoji:read': ''
            'files:read': ''
            'files:write:user': ''
            'groups:history': ''
            'groups:read': ''
            'groups:write': ''
            identify: ''
            identity.basic: ''
            'im:history': ''
            'im:read': ''
            'im:write': ''
            'mpim:history': ''
            'mpim:read': ''
            'mpim:write': ''
            'pins:read': ''
            'pins:write': ''
            'reactions:read': ''
            'reactions:write': ''
            'reminders:read': ''
            'reminders:write': ''
            'search:read': ''
            'stars:read': ''
            'stars:write': ''
            'team:read': ''
            'usergroups:read': ''
            'usergroups:write': ''
            'users.profile:read': ''
            'users.profile:write': ''
            'users:read': ''
            'users:write': ''
