swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /drive/v3
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: 'Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.'
  title: Drive
  version: v3
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.gstatic.com/images/icons/material/product/2x/drive_32dp.png'
  x-origin:
    format: google
    url: 'https://www.googleapis.com/discovery/v1/apis/drive/v3/rest'
    version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: drive
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/drive': View and manage the files in your Google Drive
      'https://www.googleapis.com/auth/drive.appdata': View and manage its own configuration data in your Google Drive
      'https://www.googleapis.com/auth/drive.file': View and manage Google Drive files and folders that you have opened or created with this app
      'https://www.googleapis.com/auth/drive.metadata': View and manage metadata of files in your Google Drive
      'https://www.googleapis.com/auth/drive.metadata.readonly': View metadata for files in your Google Drive
      'https://www.googleapis.com/auth/drive.photos.readonly': 'View the photos, videos and albums in your Google Photos'
      'https://www.googleapis.com/auth/drive.readonly': View the files in your Google Drive
      'https://www.googleapis.com/auth/drive.scripts': Modify your Google Apps Script scripts' behavior
    type: oauth2
tags:
  - name: about
  - name: changes
  - name: channels
  - name: comments
  - name: files
  - name: permissions
  - name: replies
  - name: revisions
paths:
  /about:
    get:
      description: 'Gets information about the user, the user''s Drive, and system capabilities.'
      operationId: drive.about.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.appdata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.photos.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
      tags:
        - about
  /changes:
    get:
      description: Lists changes for a user.
      operationId: drive.changes.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.appdata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.photos.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
      tags:
        - changes
  /changes/startPageToken:
    get:
      description: Gets the starting pageToken for listing future changes.
      operationId: drive.changes.getStartPageToken
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.appdata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.photos.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
      tags:
        - changes
  /changes/watch:
    post:
      description: Subscribes to changes for a user.
      operationId: drive.changes.watch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.appdata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.photos.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
      tags:
        - changes
  /channels/stop:
    post:
      description: Stop watching resources through this channel
      operationId: drive.channels.stop
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.appdata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.photos.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
      tags:
        - channels
  /files:
    get:
      description: Lists or searches files.
      operationId: drive.files.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.appdata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.photos.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
      tags:
        - files
    post:
      description: Creates a new file.
      operationId: drive.files.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.appdata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
      tags:
        - files
  /files/generateIds:
    get:
      description: Generates a set of file IDs which can be provided in create requests.
      operationId: drive.files.generateIds
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.appdata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
      tags:
        - files
  /files/trash:
    delete:
      description: Permanently deletes all of the user's trashed files.
      operationId: drive.files.emptyTrash
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
      tags:
        - files
  '/files/{fileId}':
    delete:
      description: 'Permanently deletes a file owned by the user without moving it to the trash. If the target is a folder, all descendants owned by the user are also deleted.'
      operationId: drive.files.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.appdata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
      tags:
        - files
    get:
      description: Gets a file's metadata or content by ID.
      operationId: drive.files.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.appdata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.photos.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
      tags:
        - files
    patch:
      description: Updates a file's metadata and/or content with patch semantics.
      operationId: drive.files.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.appdata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.scripts'
      tags:
        - files
  '/files/{fileId}/comments':
    get:
      description: Lists a file's comments.
      operationId: drive.comments.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
      tags:
        - comments
    post:
      description: Creates a new comment on a file.
      operationId: drive.comments.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
      tags:
        - comments
  '/files/{fileId}/comments/{commentId}':
    delete:
      description: Deletes a comment.
      operationId: drive.comments.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
      tags:
        - comments
    get:
      description: Gets a comment by ID.
      operationId: drive.comments.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
      tags:
        - comments
    patch:
      description: Updates a comment with patch semantics.
      operationId: drive.comments.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
      tags:
        - comments
  '/files/{fileId}/comments/{commentId}/replies':
    get:
      description: Lists a comment's replies.
      operationId: drive.replies.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
      tags:
        - replies
    post:
      description: Creates a new reply to a comment.
      operationId: drive.replies.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
      tags:
        - replies
  '/files/{fileId}/comments/{commentId}/replies/{replyId}':
    delete:
      description: Deletes a reply.
      operationId: drive.replies.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
      tags:
        - replies
    get:
      description: Gets a reply by ID.
      operationId: drive.replies.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
      tags:
        - replies
    patch:
      description: Updates a reply with patch semantics.
      operationId: drive.replies.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
      tags:
        - replies
  '/files/{fileId}/copy':
    post:
      description: Creates a copy of a file and applies any requested updates with patch semantics.
      operationId: drive.files.copy
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.appdata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.photos.readonly'
      tags:
        - files
  '/files/{fileId}/export':
    get:
      description: Exports a Google Doc to the requested MIME type and returns the exported content.
      operationId: drive.files.export
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
      tags:
        - files
  '/files/{fileId}/permissions':
    get:
      description: Lists a file's permissions.
      operationId: drive.permissions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.photos.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
      tags:
        - permissions
    post:
      description: Creates a permission for a file.
      operationId: drive.permissions.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
      tags:
        - permissions
  '/files/{fileId}/permissions/{permissionId}':
    delete:
      description: Deletes a permission.
      operationId: drive.permissions.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
      tags:
        - permissions
    get:
      description: Gets a permission by ID.
      operationId: drive.permissions.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.photos.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
      tags:
        - permissions
    patch:
      description: Updates a permission with patch semantics.
      operationId: drive.permissions.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
      tags:
        - permissions
  '/files/{fileId}/revisions':
    get:
      description: Lists a file's revisions.
      operationId: drive.revisions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.appdata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.photos.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
      tags:
        - revisions
  '/files/{fileId}/revisions/{revisionId}':
    delete:
      description: Permanently deletes a revision. This method is only applicable to files with binary content in Drive.
      operationId: drive.revisions.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.appdata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
      tags:
        - revisions
    get:
      description: Gets a revision's metadata or content by ID.
      operationId: drive.revisions.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.appdata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.photos.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
      tags:
        - revisions
    patch:
      description: Updates a revision with patch semantics.
      operationId: drive.revisions.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.appdata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
      tags:
        - revisions
  '/files/{fileId}/watch':
    post:
      description: Subscribes to changes to a file
      operationId: drive.files.watch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.appdata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.file'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.photos.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
      tags:
        - files