swagger: '2.0'
schemes:
  - https
host: api.ebay.com
basePath: /sell/fulfillment/v1
info:
  contact:
    name: eBay Inc.
    x-twitter: ebay
  description: 'Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.'
  license:
    name: eBay API License Agreement
    url: 'https://go.developer.ebay.com/api-license-agreement'
  title: Fulfillment
  version: 1.3.0
  x-apisguru-categories:
    - ecommerce
  x-logo:
    backgroundColor: '#FFFFFF'
    url: 'https://twitter.com/ebay/profile_image?size=original'
  x-origin:
    - format: swagger
      url: 'https://developer.ebay.com/api-docs/master/sell/fulfillment/openapi/2/sell_fulfillment_v1.json'
      version: '2.0'
  x-providerName: ebay.com
  x-serviceName: sell-fulfillment
securityDefinitions:
  Authorization Code:
    authorizationUrl: 'https://signin.ebay.com/authorize'
    description: The security definitions for this API. Please check individual operations for applicable scopes.
    flow: accessCode
    scopes:
      'https://api.ebay.com/oauth/api_scope/sell.fulfillment': View and manage your order fulfillments
      'https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly': View your order fulfillments
    tokenUrl: 'https://api.ebay.com/identity/v1/oauth2/token'
    type: oauth2
paths:
  /order:
    get:
      description: 'Use this call to search for and retrieve one or more orders based on their creation date, last modification date, or fulfillment status using the filter parameter. You can alternatively specify a list of orders using the orderIds parameter. The returned Order objects contain information you can use to create and process fulfillments, including: Information about the buyer and seller Information about the order''s line items The plans for packaging, addressing and shipping the[...]'
      operationId: getOrders
      security:
        - Authorization Code:
            - 'https://api.ebay.com/oauth/api_scope/sell.fulfillment'
            - 'https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly'
      summary: Get Orders
      tags:
        - order
  '/order/{orderId}':
    get:
      description: 'Use this call to retrieve the contents of an order based on its unique identifier, orderId. This value was returned in the getOrders call''s orders.orderId field when you searched for orders by creation date, modification date, or fulfillment status. The returned Order object contains information you can use to create and process fulfillments, including: Information about the buyer and seller Information about the order''s line items The plans for packaging, addressing and sh[...]'
      operationId: getOrder
      security:
        - Authorization Code:
            - 'https://api.ebay.com/oauth/api_scope/sell.fulfillment'
            - 'https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly'
      summary: Get an Order
      tags:
        - order
  '/order/{orderId}/shipping_fulfillment':
    get:
      description: 'Use this call to retrieve the contents of all fulfillments currently defined for a specified order based on the order''s unique identifier, orderId. This value is returned in the getOrders call''s members.orderId field when you search for orders by creation date or shipment status.'
      operationId: getShippingFulfillments
      security:
        - Authorization Code:
            - 'https://api.ebay.com/oauth/api_scope/sell.fulfillment'
            - 'https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly'
      summary: Get Shipping Fulfillments
      tags:
        - shipping_fulfillment
    post:
      description: 'When you group an order''s line items into one or more packages, each package requires a corresponding plan for handling, addressing, and shipping; this is a shipping fulfillment. For each package, execute this call once to generate a shipping fulfillment associated with that package. Note: A single line item in an order can consist of multiple units of a purchased item, and one unit can consist of multiple parts or components. Although these components might be provided by t[...]'
      operationId: createShippingFulfillment
      security:
        - Authorization Code:
            - 'https://api.ebay.com/oauth/api_scope/sell.fulfillment'
      summary: Create a Shipping Fulfillment
      tags:
        - shipping_fulfillment
  '/order/{orderId}/shipping_fulfillment/{fulfillmentId}':
    get:
      description: 'Use this call to retrieve the contents of a fulfillment based on its unique identifier, fulfillmentId (combined with the associated order''s orderId). The fulfillmentId value was originally generated by the createShippingFulfillment call, and is returned by the getShippingFulfillments call in the members.fulfillmentId field.'
      operationId: getShippingFulfillment
      security:
        - Authorization Code:
            - 'https://api.ebay.com/oauth/api_scope/sell.fulfillment'
            - 'https://api.ebay.com/oauth/api_scope/sell.fulfillment.readonly'
      summary: Get a Shipping Fulfillment
      tags:
        - shipping_fulfillment