from dataclasses import dataclass, field
from typing import Optional
from enum import Enum
from dataclasses_json import dataclass_json
from sdk import utils

class ExchangeAssignedTargetingOptionDetailsExchangeEnum(str, Enum):
    EXCHANGE_UNSPECIFIED = "EXCHANGE_UNSPECIFIED"
    EXCHANGE_GOOGLE_AD_MANAGER = "EXCHANGE_GOOGLE_AD_MANAGER"
    EXCHANGE_APPNEXUS = "EXCHANGE_APPNEXUS"
    EXCHANGE_BRIGHTROLL = "EXCHANGE_BRIGHTROLL"
    EXCHANGE_ADFORM = "EXCHANGE_ADFORM"
    EXCHANGE_ADMETA = "EXCHANGE_ADMETA"
    EXCHANGE_ADMIXER = "EXCHANGE_ADMIXER"
    EXCHANGE_ADSMOGO = "EXCHANGE_ADSMOGO"
    EXCHANGE_ADSWIZZ = "EXCHANGE_ADSWIZZ"
    EXCHANGE_BIDSWITCH = "EXCHANGE_BIDSWITCH"
    EXCHANGE_BRIGHTROLL_DISPLAY = "EXCHANGE_BRIGHTROLL_DISPLAY"
    EXCHANGE_CADREON = "EXCHANGE_CADREON"
    EXCHANGE_DAILYMOTION = "EXCHANGE_DAILYMOTION"
    EXCHANGE_FIVE = "EXCHANGE_FIVE"
    EXCHANGE_FLUCT = "EXCHANGE_FLUCT"
    EXCHANGE_FREEWHEEL = "EXCHANGE_FREEWHEEL"
    EXCHANGE_GENIEE = "EXCHANGE_GENIEE"
    EXCHANGE_GUMGUM = "EXCHANGE_GUMGUM"
    EXCHANGE_IMOBILE = "EXCHANGE_IMOBILE"
    EXCHANGE_IBILLBOARD = "EXCHANGE_IBILLBOARD"
    EXCHANGE_IMPROVE_DIGITAL = "EXCHANGE_IMPROVE_DIGITAL"
    EXCHANGE_INDEX = "EXCHANGE_INDEX"
    EXCHANGE_KARGO = "EXCHANGE_KARGO"
    EXCHANGE_MICROAD = "EXCHANGE_MICROAD"
    EXCHANGE_MOPUB = "EXCHANGE_MOPUB"
    EXCHANGE_NEND = "EXCHANGE_NEND"
    EXCHANGE_ONE_BY_AOL_DISPLAY = "EXCHANGE_ONE_BY_AOL_DISPLAY"
    EXCHANGE_ONE_BY_AOL_MOBILE = "EXCHANGE_ONE_BY_AOL_MOBILE"
    EXCHANGE_ONE_BY_AOL_VIDEO = "EXCHANGE_ONE_BY_AOL_VIDEO"
    EXCHANGE_OOYALA = "EXCHANGE_OOYALA"
    EXCHANGE_OPENX = "EXCHANGE_OPENX"
    EXCHANGE_PERMODO = "EXCHANGE_PERMODO"
    EXCHANGE_PLATFORMONE = "EXCHANGE_PLATFORMONE"
    EXCHANGE_PLATFORMID = "EXCHANGE_PLATFORMID"
    EXCHANGE_PUBMATIC = "EXCHANGE_PUBMATIC"
    EXCHANGE_PULSEPOINT = "EXCHANGE_PULSEPOINT"
    EXCHANGE_REVENUEMAX = "EXCHANGE_REVENUEMAX"
    EXCHANGE_RUBICON = "EXCHANGE_RUBICON"
    EXCHANGE_SMARTCLIP = "EXCHANGE_SMARTCLIP"
    EXCHANGE_SMARTRTB = "EXCHANGE_SMARTRTB"
    EXCHANGE_SMARTSTREAMTV = "EXCHANGE_SMARTSTREAMTV"
    EXCHANGE_SOVRN = "EXCHANGE_SOVRN"
    EXCHANGE_SPOTXCHANGE = "EXCHANGE_SPOTXCHANGE"
    EXCHANGE_STROER = "EXCHANGE_STROER"
    EXCHANGE_TEADSTV = "EXCHANGE_TEADSTV"
    EXCHANGE_TELARIA = "EXCHANGE_TELARIA"
    EXCHANGE_TVN = "EXCHANGE_TVN"
    EXCHANGE_UNITED = "EXCHANGE_UNITED"
    EXCHANGE_YIELDLAB = "EXCHANGE_YIELDLAB"
    EXCHANGE_YIELDMO = "EXCHANGE_YIELDMO"
    EXCHANGE_UNRULYX = "EXCHANGE_UNRULYX"
    EXCHANGE_OPEN8 = "EXCHANGE_OPEN8"
    EXCHANGE_TRITON = "EXCHANGE_TRITON"
    EXCHANGE_TRIPLELIFT = "EXCHANGE_TRIPLELIFT"
    EXCHANGE_TABOOLA = "EXCHANGE_TABOOLA"
    EXCHANGE_INMOBI = "EXCHANGE_INMOBI"
    EXCHANGE_SMAATO = "EXCHANGE_SMAATO"
    EXCHANGE_AJA = "EXCHANGE_AJA"
    EXCHANGE_SUPERSHIP = "EXCHANGE_SUPERSHIP"
    EXCHANGE_NEXSTAR_DIGITAL = "EXCHANGE_NEXSTAR_DIGITAL"
    EXCHANGE_WAZE = "EXCHANGE_WAZE"
    EXCHANGE_SOUNDCAST = "EXCHANGE_SOUNDCAST"
    EXCHANGE_SHARETHROUGH = "EXCHANGE_SHARETHROUGH"
    EXCHANGE_FYBER = "EXCHANGE_FYBER"
    EXCHANGE_RED_FOR_PUBLISHERS = "EXCHANGE_RED_FOR_PUBLISHERS"
    EXCHANGE_MEDIANET = "EXCHANGE_MEDIANET"
    EXCHANGE_TAPJOY = "EXCHANGE_TAPJOY"
    EXCHANGE_VISTAR = "EXCHANGE_VISTAR"
    EXCHANGE_DAX = "EXCHANGE_DAX"


@dataclass_json
@dataclass
class ExchangeAssignedTargetingOptionDetails:
    r"""ExchangeAssignedTargetingOptionDetails
    Details for assigned exchange targeting option. This will be populated in the details field of an AssignedTargetingOption when targeting_type is `TARGETING_TYPE_EXCHANGE`.
    """
    
    exchange: Optional[ExchangeAssignedTargetingOptionDetailsExchangeEnum] = field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.field_name('exchange') }})
    
