openapi: 3.0.0
servers:
  - url: https://dataportability.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: The Data Portability API lets you build applications that request authorization from a user to move a copy of data from Google services into your application. This enables data portability and facilitates switching services.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Data Portability API
  version: v1beta
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://upload.wikimedia.org/wikipedia/commons/e/e1/YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
    - format: google
      url: https://dataportability.googleapis.com/$discovery/rest?version=v1beta
      version: v1
  x-providerName: googleapis.com
  x-serviceName: dataportability
tags:
  - name: archiveJobs
  - name: authorization
  - name: portabilityArchive
paths:
  /v1beta/authorization:reset:
    post:
      description: Revokes OAuth tokens and resets exhausted scopes for a user/project pair. This method allows you to initiate a request after a new consent is granted. This method also indicates that previous archives can be garbage collected. You should call this method when all jobs are complete and all archives are downloaded. Do not call it only when you start a new job.
      operationId: dataportability.authorization.reset
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.businessmessaging.conversations
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.businessmessaging.conversations
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.commute_routes
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.commute_routes
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.commute_settings
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.commute_settings
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.ev_profile
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.ev_profile
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.offering_contributions
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.offering_contributions
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.photos_videos
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.photos_videos
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.reviews
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.reviews
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.starred_places
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.starred_places
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.myactivity.maps
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.myactivity.maps
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.myactivity.search
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.myactivity.search
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.myactivity.shopping
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.myactivity.shopping
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.myactivity.youtube
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.myactivity.youtube
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.shopping.addresses
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.shopping.addresses
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.shopping.reviews
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.shopping.reviews
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.channel
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.channel
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.comments
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.comments
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.live_chat
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.live_chat
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.music
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.music
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.private_playlists
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.private_playlists
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.private_videos
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.private_videos
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.public_playlists
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.public_playlists
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.public_videos
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.public_videos
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.shopping
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.shopping
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.subscriptions
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.subscriptions
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos
      tags:
        - authorization
  /v1beta/portabilityArchive:initiate:
    post:
      description: Initiates a new Archive job for the Portability API.
      operationId: dataportability.portabilityArchive.initiate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.businessmessaging.conversations
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.businessmessaging.conversations
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.commute_routes
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.commute_routes
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.commute_settings
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.commute_settings
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.ev_profile
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.ev_profile
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.offering_contributions
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.offering_contributions
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.photos_videos
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.photos_videos
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.reviews
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.reviews
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.starred_places
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.starred_places
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.myactivity.maps
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.myactivity.maps
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.myactivity.search
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.myactivity.search
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.myactivity.shopping
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.myactivity.shopping
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.myactivity.youtube
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.myactivity.youtube
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.shopping.addresses
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.shopping.addresses
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.shopping.reviews
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.shopping.reviews
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.channel
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.channel
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.comments
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.comments
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.live_chat
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.live_chat
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.music
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.music
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.private_playlists
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.private_playlists
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.private_videos
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.private_videos
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.public_playlists
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.public_playlists
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.public_videos
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.public_videos
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.shopping
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.shopping
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.subscriptions
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.subscriptions
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos
      tags:
        - portabilityArchive
  /v1beta/{name}:
    get:
      description: Retrieves the state of an Archive job for the Portability API.
      operationId: dataportability.archiveJobs.getPortabilityArchiveState
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.businessmessaging.conversations
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.businessmessaging.conversations
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.commute_routes
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.commute_routes
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.commute_settings
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.commute_settings
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.ev_profile
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.ev_profile
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.offering_contributions
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.offering_contributions
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.photos_videos
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.photos_videos
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.reviews
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.reviews
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.starred_places
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.starred_places
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.myactivity.maps
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.myactivity.maps
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.myactivity.search
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.myactivity.search
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.myactivity.shopping
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.myactivity.shopping
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.myactivity.youtube
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.myactivity.youtube
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.shopping.addresses
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.shopping.addresses
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.shopping.reviews
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.shopping.reviews
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.channel
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.channel
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.comments
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.comments
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.live_chat
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.live_chat
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.music
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.music
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.private_playlists
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.private_playlists
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.private_videos
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.private_videos
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.public_playlists
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.public_playlists
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.public_videos
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.public_videos
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.shopping
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.shopping
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.subscriptions
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.subscriptions
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos
      tags:
        - archiveJobs
  /v1beta/{name}:retry:
    post:
      description: Retries a failed Portability Archive job.
      operationId: dataportability.archiveJobs.retry
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.businessmessaging.conversations
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.businessmessaging.conversations
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.commute_routes
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.commute_routes
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.commute_settings
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.commute_settings
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.ev_profile
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.ev_profile
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.offering_contributions
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.offering_contributions
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.photos_videos
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.photos_videos
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.reviews
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.reviews
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.maps.starred_places
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.maps.starred_places
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.myactivity.maps
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.myactivity.maps
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.myactivity.search
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.myactivity.search
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.myactivity.shopping
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.myactivity.shopping
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.myactivity.youtube
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.myactivity.youtube
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.shopping.addresses
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.shopping.addresses
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.shopping.reviews
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.shopping.reviews
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.channel
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.channel
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.comments
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.comments
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.live_chat
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.live_chat
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.music
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.music
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.private_playlists
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.private_playlists
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.private_videos
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.private_videos
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.public_playlists
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.public_playlists
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.public_videos
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.public_videos
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.shopping
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.shopping
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.subscriptions
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.subscriptions
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists
        - Oauth2:
            - https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos
          Oauth2c:
            - https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos
      tags:
        - archiveJobs
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/dataportability.businessmessaging.conversations: Move a copy of messages between you and the businesses you have conversations with across Google services.
            https://www.googleapis.com/auth/dataportability.maps.commute_routes: Move a copy of your pinned trips on Maps.
            https://www.googleapis.com/auth/dataportability.maps.commute_settings: Move a copy of your commute settings on Maps.
            https://www.googleapis.com/auth/dataportability.maps.ev_profile: Move a copy of your electric vehicle profile on Maps.
            https://www.googleapis.com/auth/dataportability.maps.offering_contributions: Move a copy of your updates to places on Maps.
            https://www.googleapis.com/auth/dataportability.maps.photos_videos: Move a copy of the photos and videos you posted on Maps.
            https://www.googleapis.com/auth/dataportability.maps.reviews: Move a copy of your reviews and posts on Maps.
            https://www.googleapis.com/auth/dataportability.maps.starred_places: Move a copy of your Starred places list on Maps.
            https://www.googleapis.com/auth/dataportability.myactivity.maps: Move a copy of your Maps activity.
            https://www.googleapis.com/auth/dataportability.myactivity.search: Move a copy of your Google Search activity.
            https://www.googleapis.com/auth/dataportability.myactivity.shopping: Move a copy of your Shopping activity.
            https://www.googleapis.com/auth/dataportability.myactivity.youtube: Move a copy of your YouTube activity.
            https://www.googleapis.com/auth/dataportability.shopping.addresses: Move a copy of your shipping information on Shopping.
            https://www.googleapis.com/auth/dataportability.shopping.reviews: Move a copy of reviews you wrote about products or online stores on Google Search.
            https://www.googleapis.com/auth/dataportability.youtube.channel: Move a copy of information about your YouTube channel.
            https://www.googleapis.com/auth/dataportability.youtube.comments: Move a copy of your YouTube comments.
            https://www.googleapis.com/auth/dataportability.youtube.live_chat: Move a copy of your YouTube messages in live chat.
            https://www.googleapis.com/auth/dataportability.youtube.music: Move a copy of your uploaded YouTube music tracks and your YouTube music library.
            https://www.googleapis.com/auth/dataportability.youtube.private_playlists: Move a copy of your YouTube private playlists.
            https://www.googleapis.com/auth/dataportability.youtube.private_videos: Move a copy of your private YouTube videos and information about them.
            https://www.googleapis.com/auth/dataportability.youtube.public_playlists: Move a copy of your public YouTube playlists.
            https://www.googleapis.com/auth/dataportability.youtube.public_videos: Move a copy of your public YouTube videos and information about them.
            https://www.googleapis.com/auth/dataportability.youtube.shopping: Move a copy of your YouTube shopping wishlists, and wishlist items.
            https://www.googleapis.com/auth/dataportability.youtube.subscriptions: Move a copy of your YouTube channel subscriptions, even if they're private.
            https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists: Move a copy of your unlisted YouTube playlists.
            https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos: Move a copy of your unlisted YouTube videos and information about them.
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/dataportability.businessmessaging.conversations: Move a copy of messages between you and the businesses you have conversations with across Google services.
            https://www.googleapis.com/auth/dataportability.maps.commute_routes: Move a copy of your pinned trips on Maps.
            https://www.googleapis.com/auth/dataportability.maps.commute_settings: Move a copy of your commute settings on Maps.
            https://www.googleapis.com/auth/dataportability.maps.ev_profile: Move a copy of your electric vehicle profile on Maps.
            https://www.googleapis.com/auth/dataportability.maps.offering_contributions: Move a copy of your updates to places on Maps.
            https://www.googleapis.com/auth/dataportability.maps.photos_videos: Move a copy of the photos and videos you posted on Maps.
            https://www.googleapis.com/auth/dataportability.maps.reviews: Move a copy of your reviews and posts on Maps.
            https://www.googleapis.com/auth/dataportability.maps.starred_places: Move a copy of your Starred places list on Maps.
            https://www.googleapis.com/auth/dataportability.myactivity.maps: Move a copy of your Maps activity.
            https://www.googleapis.com/auth/dataportability.myactivity.search: Move a copy of your Google Search activity.
            https://www.googleapis.com/auth/dataportability.myactivity.shopping: Move a copy of your Shopping activity.
            https://www.googleapis.com/auth/dataportability.myactivity.youtube: Move a copy of your YouTube activity.
            https://www.googleapis.com/auth/dataportability.shopping.addresses: Move a copy of your shipping information on Shopping.
            https://www.googleapis.com/auth/dataportability.shopping.reviews: Move a copy of reviews you wrote about products or online stores on Google Search.
            https://www.googleapis.com/auth/dataportability.youtube.channel: Move a copy of information about your YouTube channel.
            https://www.googleapis.com/auth/dataportability.youtube.comments: Move a copy of your YouTube comments.
            https://www.googleapis.com/auth/dataportability.youtube.live_chat: Move a copy of your YouTube messages in live chat.
            https://www.googleapis.com/auth/dataportability.youtube.music: Move a copy of your uploaded YouTube music tracks and your YouTube music library.
            https://www.googleapis.com/auth/dataportability.youtube.private_playlists: Move a copy of your YouTube private playlists.
            https://www.googleapis.com/auth/dataportability.youtube.private_videos: Move a copy of your private YouTube videos and information about them.
            https://www.googleapis.com/auth/dataportability.youtube.public_playlists: Move a copy of your public YouTube playlists.
            https://www.googleapis.com/auth/dataportability.youtube.public_videos: Move a copy of your public YouTube videos and information about them.
            https://www.googleapis.com/auth/dataportability.youtube.shopping: Move a copy of your YouTube shopping wishlists, and wishlist items.
            https://www.googleapis.com/auth/dataportability.youtube.subscriptions: Move a copy of your YouTube channel subscriptions, even if they're private.
            https://www.googleapis.com/auth/dataportability.youtube.unlisted_playlists: Move a copy of your unlisted YouTube playlists.
            https://www.googleapis.com/auth/dataportability.youtube.unlisted_videos: Move a copy of your unlisted YouTube videos and information about them.
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
