


export enum ErrorCodeEnum {
    AgentIssue = "AGENT_ISSUE",
    AlarmActive = "ALARM_ACTIVE",
    ApplicationMissing = "APPLICATION_MISSING",
    AutoscalingValidationError = "AUTOSCALING_VALIDATION_ERROR",
    AutoScalingConfiguration = "AUTO_SCALING_CONFIGURATION",
    AutoScalingIamRolePermissions = "AUTO_SCALING_IAM_ROLE_PERMISSIONS",
    CodedeployResourceCannotBeFound = "CODEDEPLOY_RESOURCE_CANNOT_BE_FOUND",
    CustomerApplicationUnhealthy = "CUSTOMER_APPLICATION_UNHEALTHY",
    DeploymentGroupMissing = "DEPLOYMENT_GROUP_MISSING",
    EcsUpdateError = "ECS_UPDATE_ERROR",
    ElasticLoadBalancingInvalid = "ELASTIC_LOAD_BALANCING_INVALID",
    ElbInvalidInstance = "ELB_INVALID_INSTANCE",
    HealthConstraints = "HEALTH_CONSTRAINTS",
    HealthConstraintsInvalid = "HEALTH_CONSTRAINTS_INVALID",
    HookExecutionFailure = "HOOK_EXECUTION_FAILURE",
    IamRoleMissing = "IAM_ROLE_MISSING",
    IamRolePermissions = "IAM_ROLE_PERMISSIONS",
    InternalError = "INTERNAL_ERROR",
    InvalidEcsService = "INVALID_ECS_SERVICE",
    InvalidLambdaConfiguration = "INVALID_LAMBDA_CONFIGURATION",
    InvalidLambdaFunction = "INVALID_LAMBDA_FUNCTION",
    InvalidRevision = "INVALID_REVISION",
    ManualStop = "MANUAL_STOP",
    MissingBlueGreenDeploymentConfiguration = "MISSING_BLUE_GREEN_DEPLOYMENT_CONFIGURATION",
    MissingElbInformation = "MISSING_ELB_INFORMATION",
    MissingGithubToken = "MISSING_GITHUB_TOKEN",
    NoEc2Subscription = "NO_EC2_SUBSCRIPTION",
    NoInstances = "NO_INSTANCES",
    OverMaxInstances = "OVER_MAX_INSTANCES",
    ResourceLimitExceeded = "RESOURCE_LIMIT_EXCEEDED",
    RevisionMissing = "REVISION_MISSING",
    Throttled = "THROTTLED",
    Timeout = "TIMEOUT",
    CloudformationStackFailure = "CLOUDFORMATION_STACK_FAILURE"
}
