# coding: utf-8

"""
    People API

    Provides access to information about profiles and contacts.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.name import Name

class TestName(unittest.TestCase):
    """Name unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Name:
        """Test Name
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Name`
        """
        model = Name()
        if include_optional:
            return Name(
                display_name = '',
                display_name_last_first = '',
                family_name = '',
                given_name = '',
                honorific_prefix = '',
                honorific_suffix = '',
                metadata = openapi_client.models.field_metadata.FieldMetadata(
                    primary = True, 
                    source = openapi_client.models.source.Source(
                        etag = '', 
                        id = '', 
                        profile_metadata = openapi_client.models.profile_metadata.ProfileMetadata(
                            object_type = 'OBJECT_TYPE_UNSPECIFIED', 
                            user_types = [
                                'USER_TYPE_UNKNOWN'
                                ], ), 
                        type = 'SOURCE_TYPE_UNSPECIFIED', 
                        update_time = '', ), 
                    source_primary = True, 
                    verified = True, ),
                middle_name = '',
                phonetic_family_name = '',
                phonetic_full_name = '',
                phonetic_given_name = '',
                phonetic_honorific_prefix = '',
                phonetic_honorific_suffix = '',
                phonetic_middle_name = '',
                unstructured_name = ''
            )
        else:
            return Name(
        )
        """

    def testName(self):
        """Test Name"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
