{
  "swagger": "2.0",
  "info": {
    "title": "TaskQueue API",
    "x-serviceName": "taskqueue",
    "description": "Lets you access a Google App Engine Pull Task Queue over REST.",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v1beta2"
  },
  "host": "www.googleapis.com",
  "basePath": "/taskqueue/v1beta2/projects",
  "schemes": [
    "https"
  ],
  "paths": {
    "/{project}/taskqueues/{taskqueue}": {
      "get": {
        "description": "Get detailed information about a TaskQueue.",
        "operationId": "taskqueue.taskqueues.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/taskqueue",
              "https://www.googleapis.com/auth/taskqueue.consumer"
            ]
          }
        ],
        "tags": [
          "taskqueues"
        ]
      }
    },
    "/{project}/taskqueues/{taskqueue}/tasks/{task}": {
      "delete": {
        "description": "Delete a task from a TaskQueue.",
        "operationId": "taskqueue.tasks.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/taskqueue",
              "https://www.googleapis.com/auth/taskqueue.consumer"
            ]
          }
        ],
        "tags": [
          "tasks"
        ]
      },
      "get": {
        "description": "Get a particular task from a TaskQueue.",
        "operationId": "taskqueue.tasks.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/taskqueue",
              "https://www.googleapis.com/auth/taskqueue.consumer"
            ]
          }
        ],
        "tags": [
          "tasks"
        ]
      },
      "patch": {
        "description": "Update tasks that are leased out of a TaskQueue. This method supports patch semantics.",
        "operationId": "taskqueue.tasks.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/taskqueue",
              "https://www.googleapis.com/auth/taskqueue.consumer"
            ]
          }
        ],
        "tags": [
          "tasks"
        ]
      },
      "post": {
        "description": "Update tasks that are leased out of a TaskQueue.",
        "operationId": "taskqueue.tasks.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/taskqueue",
              "https://www.googleapis.com/auth/taskqueue.consumer"
            ]
          }
        ],
        "tags": [
          "tasks"
        ]
      }
    },
    "/{project}/taskqueues/{taskqueue}/tasks": {
      "post": {
        "description": "Insert a new task in a TaskQueue",
        "operationId": "taskqueue.tasks.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/taskqueue",
              "https://www.googleapis.com/auth/taskqueue.consumer"
            ]
          }
        ],
        "tags": [
          "tasks"
        ]
      },
      "get": {
        "description": "List Tasks in a TaskQueue",
        "operationId": "taskqueue.tasks.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/taskqueue",
              "https://www.googleapis.com/auth/taskqueue.consumer"
            ]
          }
        ],
        "tags": [
          "tasks"
        ]
      }
    },
    "/{project}/taskqueues/{taskqueue}/tasks/lease": {
      "post": {
        "description": "Lease 1 or more tasks from a TaskQueue.",
        "operationId": "taskqueue.tasks.lease",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/taskqueue",
              "https://www.googleapis.com/auth/taskqueue.consumer"
            ]
          }
        ],
        "tags": [
          "tasks"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/taskqueue": "Manage your Tasks and Taskqueues",
        "https://www.googleapis.com/auth/taskqueue.consumer": "Consume Tasks from your Taskqueues"
      }
    }
  }
}