swagger: '2.0'
schemes:
  - https
host: slides.googleapis.com
basePath: /
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: An API for creating and editing Google Slides presentations.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Google Slides
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://slides.googleapis.com/$discovery/rest?version=v1'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: slides
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/drive': View and manage the files in your Google Drive
      'https://www.googleapis.com/auth/drive.readonly': View the files in your Google Drive
      'https://www.googleapis.com/auth/presentations': View and manage your Google Slides presentations
      'https://www.googleapis.com/auth/presentations.readonly': View your Google Slides presentations
      'https://www.googleapis.com/auth/spreadsheets': View and manage your spreadsheets in Google Drive
      'https://www.googleapis.com/auth/spreadsheets.readonly': View your Google Spreadsheets
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/drive': View and manage the files in your Google Drive
      'https://www.googleapis.com/auth/drive.readonly': View the files in your Google Drive
      'https://www.googleapis.com/auth/presentations': View and manage your Google Slides presentations
      'https://www.googleapis.com/auth/presentations.readonly': View your Google Slides presentations
      'https://www.googleapis.com/auth/spreadsheets': View and manage your spreadsheets in Google Drive
      'https://www.googleapis.com/auth/spreadsheets.readonly': View your Google Spreadsheets
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: presentations
paths:
  /v1/presentations:
    post:
      description: |-
        Creates a new presentation using the title given in the request. Other
        fields in the request are ignored.
        Returns the created presentation.
      operationId: slides.presentations.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/presentations'
          Oauth2c:
            - 'https://www.googleapis.com/auth/presentations'
      tags:
        - presentations
  '/v1/presentations/{presentationId}':
    get:
      description: Gets the latest version of the specified presentation.
      operationId: slides.presentations.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/presentations'
          Oauth2c:
            - 'https://www.googleapis.com/auth/presentations'
        - Oauth2:
            - 'https://www.googleapis.com/auth/presentations.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/presentations.readonly'
      tags:
        - presentations
  '/v1/presentations/{presentationId}/pages/{pageObjectId}':
    get:
      description: Gets the latest version of the specified page in the presentation.
      operationId: slides.presentations.pages.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/presentations'
          Oauth2c:
            - 'https://www.googleapis.com/auth/presentations'
        - Oauth2:
            - 'https://www.googleapis.com/auth/presentations.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/presentations.readonly'
      tags:
        - presentations
  '/v1/presentations/{presentationId}/pages/{pageObjectId}/thumbnail':
    get:
      description: |-
        Generates a thumbnail of the latest version of the specified page in the
        presentation and returns a URL to the thumbnail image.
      operationId: slides.presentations.pages.getThumbnail
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/presentations'
          Oauth2c:
            - 'https://www.googleapis.com/auth/presentations'
        - Oauth2:
            - 'https://www.googleapis.com/auth/presentations.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/presentations.readonly'
      tags:
        - presentations
  '/v1/presentations/{presentationId}:batchUpdate':
    post:
      description: |-
        Applies one or more updates to the presentation.

        Each request is validated before
        being applied. If any request is not valid, then the entire request will
        fail and nothing will be applied.

        Some requests have replies to
        give you some information about how they are applied. Other requests do
        not need to return information; these each return an empty reply.
        The order of replies matches that of the requests.

        For example, suppose you call batchUpdate with four updates, and only the
        third one returns information. The response would have two empty replies:
        the reply to the third request, and another empty reply, in that order.

        Because other users may be editing the presentation, the presentation
        might not exactly reflect your changes: your changes may
        be altered with respect to collaborator changes. If there are no
        collaborators, the presentation should reflect your changes. In any case,
        the updates in your request are guaranteed to be applied together
        atomically.
      operationId: slides.presentations.batchUpdate
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/presentations'
          Oauth2c:
            - 'https://www.googleapis.com/auth/presentations'
        - Oauth2:
            - 'https://www.googleapis.com/auth/spreadsheets'
          Oauth2c:
            - 'https://www.googleapis.com/auth/spreadsheets'
        - Oauth2:
            - 'https://www.googleapis.com/auth/spreadsheets.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/spreadsheets.readonly'
      tags:
        - presentations