openapi: 3.0.0
servers:
  - url: https://connect.squareup.com
info:
  contact:
    email: developers@squareup.com
    name: Square Developer Platform
    url: https://squareup.com/developers
  description: Client library for accessing the Square Connect APIs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://connect.squareup.com/tos
  title: Square Connect API
  version: "2.0"
  x-apisguru-categories:
    - payment
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/http_square.github.io_images_logo.png
  x-origin:
    - format: openapi
      url: https://raw.githubusercontent.com/square/connect-api-specification/master/api.json
      version: "3.0"
  x-providerName: squareup.com
paths:
  /mobile/authorization-code:
    post:
      description: |-
        Generates code to authorize a mobile application to connect to a Square card reader

        Authorization codes are one-time-use and expire __60 minutes__ after being issued.

        __Important:__ The `Authorization` header you provide to this endpoint must have the following format:

        ```
        Authorization: Bearer ACCESS_TOKEN
        ```

        Replace `ACCESS_TOKEN` with a
        [valid production authorization credential](https://developer.squareup.com/docs/build-basics/access-tokens).
      operationId: CreateMobileAuthorizationCode
      security:
        - oauth2:
            - PAYMENTS_WRITE_IN_PERSON
      summary: CreateMobileAuthorizationCode
      tags:
        - MobileAuthorization
      x-oauthpermissions:
        - PAYMENTS_WRITE_IN_PERSON
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/oauth2/clients/{client_id}/access-token/renew":
    post:
      description: |-
        `RenewToken` is deprecated. For information about refreshing OAuth access tokens, see
        [Migrate from Renew to Refresh OAuth Tokens](https://developer.squareup.com/docs/oauth-api/migrate-to-refresh-tokens).


        Renews an OAuth access token before it expires.

        OAuth access tokens besides your application's personal access token expire after __30 days__.
        You can also renew expired tokens within __15 days__ of their expiration.
        You cannot renew an access token that has been expired for more than 15 days.
        Instead, the associated user must re-complete the OAuth flow from the beginning.

        __Important:__ The `Authorization` header for this endpoint must have the
        following format:

        ```
        Authorization: Client APPLICATION_SECRET
        ```

        Replace `APPLICATION_SECRET` with the application secret on the Credentials
        page in the [developer dashboard](https://developer.squareup.com/apps).
      operationId: RenewToken
      security:
        - oauth2ClientSecret: []
      summary: RenewToken
      tags:
        - OAuth
      x-is-deprecated: true
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  /oauth2/revoke:
    post:
      description: |-
        Revokes an access token generated with the OAuth flow.

        If an account has more than one OAuth access token for your application, this
        endpoint revokes all of them, regardless of which token you specify. When an
        OAuth access token is revoked, all of the active subscriptions associated
        with that OAuth token are canceled immediately.

        __Important:__ The `Authorization` header for this endpoint must have the
        following format:

        ```
        Authorization: Client APPLICATION_SECRET
        ```

        Replace `APPLICATION_SECRET` with the application secret on the OAuth
        page in the [developer dashboard](https://developer.squareup.com/apps).
      operationId: RevokeToken
      security:
        - oauth2ClientSecret: []
      summary: RevokeToken
      tags:
        - OAuth
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /oauth2/token:
    post:
      description: |-
        Returns an OAuth access token.

        The endpoint supports distinct methods of obtaining OAuth access tokens.
        Applications specify a method by adding the `grant_type` parameter
        in the request and also provide relevant information.

        __Note:__ Regardless of the method application specified,
        the endpoint always returns two items; an OAuth access token and
        a refresh token in the response.

        __OAuth tokens should only live on secure servers. Application clients
        should never interact directly with OAuth tokens__.
      operationId: ObtainToken
      security: []
      summary: ObtainToken
      tags:
        - OAuth
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v1/me/employees:
    get:
      description: Provides summary information for all of a business's employees.
      operationId: ListEmployees
      security:
        - oauth2:
            - EMPLOYEES_READ
      summary: ListEmployees
      tags:
        - V1Employees
      x-oauthpermissions:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    post:
      description: |2-
         Use the CreateEmployee endpoint to add an employee to a Square
        account. Employees created with the Connect API have an initial status
        of `INACTIVE`. Inactive employees cannot sign in to Square Point of Sale
        until they are activated from the Square Dashboard. Employee status
        cannot be changed with the Connect API.

        Employee entities cannot be deleted. To disable employee profiles,
        set the employee's status to <code>INACTIVE</code>
      operationId: CreateEmployee
      security:
        - oauth2:
            - EMPLOYEES_WRITE
      summary: CreateEmployee
      tags:
        - V1Employees
      x-oauthpermissions:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v1/me/employees/{employee_id}":
    get:
      description: Provides the details for a single employee.
      operationId: RetrieveEmployee
      security:
        - oauth2:
            - EMPLOYEES_READ
      summary: RetrieveEmployee
      tags:
        - V1Employees
      x-oauthpermissions:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    put:
      description: ""
      operationId: UpdateEmployee
      security:
        - oauth2:
            - EMPLOYEES_WRITE
      summary: UpdateEmployee
      tags:
        - V1Employees
      x-oauthpermissions:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v1/me/roles:
    get:
      description: Provides summary information for all of a business's employee roles.
      operationId: ListEmployeeRoles
      security:
        - oauth2:
            - EMPLOYEES_READ
      summary: ListEmployeeRoles
      tags:
        - V1Employees
      x-oauthpermissions:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    post:
      description: |-
        Creates an employee role you can then assign to employees.

        Square accounts can include any number of roles that can be assigned to
        employees. These roles define the actions and permissions granted to an
        employee with that role. For example, an employee with a "Shift Manager"
        role might be able to issue refunds in Square Point of Sale, whereas an
        employee with a "Clerk" role might not.

        Roles are assigned with the [V1UpdateEmployee](https://developer.squareup.com/reference/square_2021-08-18/v1-employees-api/update-employee-role)
        endpoint. An employee can have only one role at a time.

        If an employee has no role, they have none of the permissions associated
        with roles. All employees can accept payments with Square Point of Sale.
      operationId: CreateEmployeeRole
      security:
        - oauth2:
            - EMPLOYEES_WRITE
      summary: CreateEmployeeRole
      tags:
        - V1Employees
      x-oauthpermissions:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v1/me/roles/{role_id}":
    get:
      description: Provides the details for a single employee role.
      operationId: RetrieveEmployeeRole
      security:
        - oauth2:
            - EMPLOYEES_READ
      summary: RetrieveEmployeeRole
      tags:
        - V1Employees
      x-oauthpermissions:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    put:
      description: Modifies the details of an employee role.
      operationId: UpdateEmployeeRole
      security:
        - oauth2:
            - EMPLOYEES_WRITE
      summary: UpdateEmployeeRole
      tags:
        - V1Employees
      x-oauthpermissions:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v1/{location_id}/orders":
    get:
      description: Provides summary information for a merchant's online store orders.
      operationId: ListOrders
      security:
        - oauth2:
            - ORDERS_READ
      summary: ListOrders
      tags:
        - V1Transactions
      x-is-deprecated: true
      x-oauthpermissions:
        - ORDERS_READ
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
      x-visibility: SDK_ONLY
  "/v1/{location_id}/orders/{order_id}":
    get:
      description: Provides comprehensive information for a single online store order, including the order's history.
      operationId: RetrieveOrder
      security:
        - oauth2:
            - ORDERS_READ
      summary: RetrieveOrder
      tags:
        - V1Transactions
      x-is-deprecated: true
      x-oauthpermissions:
        - ORDERS_READ
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
      x-visibility: SDK_ONLY
    put:
      description: "Updates the details of an online store order. Every update you perform on an order corresponds to one of three actions:"
      operationId: UpdateOrder
      security:
        - oauth2:
            - ORDERS_WRITE
      summary: UpdateOrder
      tags:
        - V1Transactions
      x-is-deprecated: true
      x-oauthpermissions:
        - ORDERS_WRITE
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
      x-visibility: SDK_ONLY
  "/v1/{location_id}/payments":
    get:
      description: |-
        Provides summary information for all payments taken for a given
        Square account during a date range. Date ranges cannot exceed 1 year in
        length. See Date ranges for details of inclusive and exclusive dates.

        *Note**: Details for payments processed with Square Point of Sale while
        in offline mode may not be transmitted to Square for up to 72 hours.
        Offline payments have a `created_at` value that reflects the time the
        payment was originally processed, not the time it was subsequently
        transmitted to Square. Consequently, the ListPayments endpoint might
        list an offline payment chronologically between online payments that
        were seen in a previous request.
      operationId: ListPayments
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: ListPayments
      tags:
        - V1Transactions
      x-is-deprecated: true
      x-oauthpermissions:
        - PAYMENTS_READ
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  "/v1/{location_id}/payments/{payment_id}":
    get:
      description: Provides comprehensive information for a single payment.
      operationId: RetrievePayment
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: RetrievePayment
      tags:
        - V1Transactions
      x-is-deprecated: true
      x-oauthpermissions:
        - PAYMENTS_READ
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  "/v1/{location_id}/refunds":
    get:
      description: Provides the details for all refunds initiated by a merchant or any of the merchant's mobile staff during a date range. Date ranges cannot exceed one year in length.
      operationId: ListRefunds
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: ListRefunds
      tags:
        - V1Transactions
      x-is-deprecated: true
      x-oauthpermissions:
        - PAYMENTS_READ
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
    post:
      description: |-
        Issues a refund for a previously processed payment. You must issue
        a refund within 60 days of the associated payment.

        You cannot issue a partial refund for a split tender payment. You must
        instead issue a full or partial refund for a particular tender, by
        providing the applicable tender id to the V1CreateRefund endpoint.
        Issuing a full refund for a split tender payment refunds all tenders
        associated with the payment.

        Issuing a refund for a card payment is not reversible. For development
        purposes, you can create fake cash payments in Square Point of Sale and
        refund them.
      operationId: CreateRefund
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: CreateRefund
      tags:
        - V1Transactions
      x-is-deprecated: true
      x-oauthpermissions:
        - PAYMENTS_WRITE
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  "/v1/{location_id}/settlements":
    get:
      description: |-
        Provides summary information for all deposits and withdrawals
        initiated by Square to a linked bank account during a date range. Date
        ranges cannot exceed one year in length.

        *Note**: the ListSettlements endpoint does not provide entry
        information.
      operationId: ListSettlements
      security:
        - oauth2:
            - SETTLEMENTS_READ
      summary: ListSettlements
      tags:
        - V1Transactions
      x-is-deprecated: true
      x-oauthpermissions:
        - SETTLEMENTS_READ
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  "/v1/{location_id}/settlements/{settlement_id}":
    get:
      description: |-
        Provides comprehensive information for a single settlement.

        The returned `Settlement` objects include an `entries` field that lists
        the transactions that contribute to the settlement total. Most
        settlement entries correspond to a payment payout, but settlement
        entries are also generated for less common events, like refunds, manual
        adjustments, or chargeback holds.

        Square initiates its regular deposits as indicated in the
        [Deposit Options with Square](https://squareup.com/help/us/en/article/3807)
        help article. Details for a regular deposit are usually not available
        from Connect API endpoints before 10 p.m. PST the same day.

        Square does not know when an initiated settlement **completes**, only
        whether it has failed. A completed settlement is typically reflected in
        a bank account within 3 business days, but in exceptional cases it may
        take longer.
      operationId: RetrieveSettlement
      security:
        - oauth2:
            - SETTLEMENTS_READ
      summary: RetrieveSettlement
      tags:
        - V1Transactions
      x-is-deprecated: true
      x-oauthpermissions:
        - SETTLEMENTS_READ
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  /v2/apple-pay/domains:
    post:
      description: |-
        Activates a domain for use with Apple Pay on the Web and Square. A validation
        is performed on this domain by Apple to ensure that it is properly set up as
        an Apple Pay enabled domain.

        This endpoint provides an easy way for platform developers to bulk activate
        Apple Pay on the Web with Square for merchants using their platform.

        To learn more about Web Apple Pay, see
        [Add the Apple Pay on the Web Button](https://developer.squareup.com/docs/payment-form/add-digital-wallets/apple-pay).
      operationId: RegisterDomain
      security:
        - oauth2: []
      summary: RegisterDomain
      tags:
        - ApplePay
      x-oauthpermissions: []
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/bank-accounts:
    get:
      description: Returns a list of [BankAccount](https://developer.squareup.com/reference/square_2021-08-18/objects/BankAccount) objects linked to a Square account.
      operationId: ListBankAccounts
      security:
        - oauth2:
            - BANK_ACCOUNTS_READ
      summary: ListBankAccounts
      tags:
        - BankAccounts
      x-oauthpermissions:
        - BANK_ACCOUNTS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/bank-accounts/by-v1-id/{v1_bank_account_id}":
    get:
      description: Returns details of a [BankAccount](https://developer.squareup.com/reference/square_2021-08-18/objects/BankAccount) identified by V1 bank account ID.
      operationId: GetBankAccountByV1Id
      security:
        - oauth2:
            - BANK_ACCOUNTS_READ
      summary: GetBankAccountByV1Id
      tags:
        - BankAccounts
      x-oauthpermissions:
        - BANK_ACCOUNTS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/bank-accounts/{bank_account_id}":
    get:
      description: |-
        Returns details of a [BankAccount](https://developer.squareup.com/reference/square_2021-08-18/objects/BankAccount)
        linked to a Square account.
      operationId: GetBankAccount
      security:
        - oauth2:
            - BANK_ACCOUNTS_READ
      summary: GetBankAccount
      tags:
        - BankAccounts
      x-oauthpermissions:
        - BANK_ACCOUNTS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/bookings:
    post:
      description: Creates a booking.
      operationId: CreateBooking
      security:
        - oauth2:
            - APPOINTMENTS_WRITE
      summary: CreateBooking
      tags:
        - Bookings
      x-is-beta: true
      x-oauthpermissions:
        - APPOINTMENTS_WRITE
      x-release-status: BETA
      x-sq-version: 2021-08-18
  /v2/bookings/availability/search:
    post:
      description: Searches for availabilities for booking.
      operationId: SearchAvailability
      security:
        - oauth2:
            - APPOINTMENTS_READ
      summary: SearchAvailability
      tags:
        - Bookings
      x-is-beta: true
      x-oauthpermissions:
        - APPOINTMENTS_READ
      x-release-status: BETA
      x-sq-version: 2021-08-18
  /v2/bookings/business-booking-profile:
    get:
      description: Retrieves a seller's booking profile.
      operationId: RetrieveBusinessBookingProfile
      security:
        - oauth2:
            - APPOINTMENTS_BUSINESS_SETTINGS_READ
      summary: RetrieveBusinessBookingProfile
      tags:
        - Bookings
      x-is-beta: true
      x-oauthpermissions:
        - APPOINTMENTS_BUSINESS_SETTINGS_READ
      x-release-status: BETA
      x-sq-version: 2021-08-18
  /v2/bookings/team-member-booking-profiles:
    get:
      description: Lists booking profiles for team members.
      operationId: ListTeamMemberBookingProfiles
      security:
        - oauth2:
            - APPOINTMENTS_BUSINESS_SETTINGS_READ
      summary: ListTeamMemberBookingProfiles
      tags:
        - Bookings
      x-is-beta: true
      x-oauthpermissions:
        - APPOINTMENTS_BUSINESS_SETTINGS_READ
      x-release-status: BETA
      x-sq-version: 2021-08-18
  "/v2/bookings/team-member-booking-profiles/{team_member_id}":
    get:
      description: Retrieves a team member's booking profile.
      operationId: RetrieveTeamMemberBookingProfile
      security:
        - oauth2:
            - APPOINTMENTS_BUSINESS_SETTINGS_READ
      summary: RetrieveTeamMemberBookingProfile
      tags:
        - Bookings
      x-is-beta: true
      x-oauthpermissions:
        - APPOINTMENTS_BUSINESS_SETTINGS_READ
      x-release-status: BETA
      x-sq-version: 2021-08-18
  "/v2/bookings/{booking_id}":
    get:
      description: Retrieves a booking.
      operationId: RetrieveBooking
      security:
        - oauth2:
            - APPOINTMENTS_READ
      summary: RetrieveBooking
      tags:
        - Bookings
      x-is-beta: true
      x-oauthpermissions:
        - APPOINTMENTS_READ
      x-release-status: BETA
      x-sq-version: 2021-08-18
    put:
      description: Updates a booking.
      operationId: UpdateBooking
      security:
        - oauth2:
            - APPOINTMENTS_WRITE
      summary: UpdateBooking
      tags:
        - Bookings
      x-is-beta: true
      x-oauthpermissions:
        - APPOINTMENTS_WRITE
      x-release-status: BETA
      x-sq-version: 2021-08-18
  "/v2/bookings/{booking_id}/cancel":
    post:
      description: Cancels an existing booking.
      operationId: CancelBooking
      security:
        - oauth2:
            - APPOINTMENTS_WRITE
      summary: CancelBooking
      tags:
        - Bookings
      x-is-beta: true
      x-oauthpermissions:
        - APPOINTMENTS_WRITE
      x-release-status: BETA
      x-sq-version: 2021-08-18
  /v2/cards:
    get:
      description: |-
        Retrieves a list of cards owned by the account making the request.
        A max of 25 cards will be returned.
      operationId: ListCards
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: ListCards
      tags:
        - Cards
      x-oauthpermissions:
        - PAYMENTS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    post:
      description: Adds a card on file to an existing merchant.
      operationId: CreateCard
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: CreateCard
      tags:
        - Cards
      x-oauthpermissions:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/cards/{card_id}":
    get:
      description: Retrieves details for a specific Card.
      operationId: RetrieveCard
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: RetrieveCard
      tags:
        - Cards
      x-oauthpermissions:
        - PAYMENTS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/cards/{card_id}/disable":
    post:
      description: |-
        Disables the card, preventing any further updates or charges.
        Disabling an already disabled card is allowed but has no effect.
      operationId: DisableCard
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: DisableCard
      tags:
        - Cards
      x-oauthpermissions:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/cash-drawers/shifts:
    get:
      description: |-
        Provides the details for all of the cash drawer shifts for a location
        in a date range.
      operationId: ListCashDrawerShifts
      security:
        - oauth2:
            - CASH_DRAWER_READ
      summary: ListCashDrawerShifts
      tags:
        - CashDrawers
      x-oauthpermissions:
        - CASH_DRAWER_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/cash-drawers/shifts/{shift_id}":
    get:
      description: |-
        Provides the summary details for a single cash drawer shift. See
        [ListCashDrawerShiftEvents](https://developer.squareup.com/reference/square_2021-08-18/cash-drawers-api/list-cash-drawer-shift-events) for a list of cash drawer shift events.
      operationId: RetrieveCashDrawerShift
      security:
        - oauth2:
            - CASH_DRAWER_READ
      summary: RetrieveCashDrawerShift
      tags:
        - CashDrawers
      x-oauthpermissions:
        - CASH_DRAWER_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/cash-drawers/shifts/{shift_id}/events":
    get:
      description: Provides a paginated list of events for a single cash drawer shift.
      operationId: ListCashDrawerShiftEvents
      security:
        - oauth2:
            - CASH_DRAWER_READ
      summary: ListCashDrawerShiftEvents
      tags:
        - CashDrawers
      x-oauthpermissions:
        - CASH_DRAWER_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/catalog/batch-delete:
    post:
      description: |-
        Deletes a set of [CatalogItem](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogItem)s based on the
        provided list of target IDs and returns a set of successfully deleted IDs in
        the response. Deletion is a cascading event such that all children of the
        targeted object are also deleted. For example, deleting a CatalogItem will
        also delete all of its [CatalogItemVariation](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogItemVariation)
        children.

        `BatchDeleteCatalogObjects` succeeds even if only a portion of the targeted
        IDs can be deleted. The response will only include IDs that were
        actually deleted.
      operationId: BatchDeleteCatalogObjects
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: BatchDeleteCatalogObjects
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/catalog/batch-retrieve:
    post:
      description: |-
        Returns a set of objects based on the provided ID.
        Each [CatalogItem](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogItem) returned in the set includes all of its
        child information including: all of its
        [CatalogItemVariation](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogItemVariation) objects, references to
        its [CatalogModifierList](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogModifierList) objects, and the ids of
        any [CatalogTax](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogTax) objects that apply to it.
      operationId: BatchRetrieveCatalogObjects
      security:
        - oauth2:
            - ITEMS_READ
      summary: BatchRetrieveCatalogObjects
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/catalog/batch-upsert:
    post:
      description: |-
        Creates or updates up to 10,000 target objects based on the provided
        list of objects. The target objects are grouped into batches and each batch is
        inserted/updated in an all-or-nothing manner. If an object within a batch is
        malformed in some way, or violates a database constraint, the entire batch
        containing that item will be disregarded. However, other batches in the same
        request may still succeed. Each batch may contain up to 1,000 objects, and
        batches will be processed in order as long as the total object count for the
        request (items, variations, modifier lists, discounts, and taxes) is no more
        than 10,000.
      operationId: BatchUpsertCatalogObjects
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: BatchUpsertCatalogObjects
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/catalog/info:
    get:
      description: |-
        Retrieves information about the Square Catalog API, such as batch size
        limits that can be used by the `BatchUpsertCatalogObjects` endpoint.
      operationId: CatalogInfo
      security:
        - oauth2:
            - ITEMS_READ
      summary: CatalogInfo
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/catalog/list:
    get:
      description: |-
        Returns a list of [CatalogObject](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogObject)s that includes
        all objects of a set of desired types (for example, all [CatalogItem](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogItem)
        and [CatalogTax](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogTax) objects) in the catalog. The `types` parameter
        is specified as a comma-separated list of valid [CatalogObject](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogObject) types:
        `ITEM`, `ITEM_VARIATION`, `MODIFIER`, `MODIFIER_LIST`, `CATEGORY`, `DISCOUNT`, `TAX`, `IMAGE`.

        __Important:__ ListCatalog does not return deleted catalog items. To retrieve
        deleted catalog items, use [SearchCatalogObjects](https://developer.squareup.com/reference/square_2021-08-18/catalog-api/search-catalog-objects)
        and set the `include_deleted_objects` attribute value to `true`.
      operationId: ListCatalog
      security:
        - oauth2:
            - ITEMS_READ
      summary: ListCatalog
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/catalog/object:
    post:
      description: Creates or updates the target [CatalogObject](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogObject).
      operationId: UpsertCatalogObject
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: UpsertCatalogObject
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/catalog/object/{object_id}":
    delete:
      description: |-
        Deletes a single [CatalogObject](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogObject) based on the
        provided ID and returns the set of successfully deleted IDs in the response.
        Deletion is a cascading event such that all children of the targeted object
        are also deleted. For example, deleting a [CatalogItem](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogItem)
        will also delete all of its
        [CatalogItemVariation](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogItemVariation) children.
      operationId: DeleteCatalogObject
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: DeleteCatalogObject
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    get:
      description: |-
        Returns a single [CatalogItem](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogItem) as a
        [CatalogObject](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogObject) based on the provided ID. The returned
        object includes all of the relevant [CatalogItem](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogItem)
        information including: [CatalogItemVariation](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogItemVariation)
        children, references to its
        [CatalogModifierList](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogModifierList) objects, and the ids of
        any [CatalogTax](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogTax) objects that apply to it.
      operationId: RetrieveCatalogObject
      security:
        - oauth2:
            - ITEMS_READ
      summary: RetrieveCatalogObject
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/catalog/search:
    post:
      description: |-
        Searches for [CatalogObject](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogObject) of any type by matching supported search attribute values,
        excluding custom attribute values on items or item variations, against one or more of the specified query expressions.

        This (`SearchCatalogObjects`) endpoint differs from the [SearchCatalogItems](https://developer.squareup.com/reference/square_2021-08-18/catalog-api/search-catalog-items)
        endpoint in the following aspects:

        - `SearchCatalogItems` can only search for items or item variations, whereas `SearchCatalogObjects` can search for any type of catalog objects.
        - `SearchCatalogItems` supports the custom attribute query filters to return items or item variations that contain custom attribute values, where `SearchCatalogObjects` does not.
        - `SearchCatalogItems` does not support the `include_deleted_objects` filter to search for deleted items or item variations, whereas `SearchCatalogObjects` does.
        - The both endpoints have different call conventions, including the query filter formats.
      operationId: SearchCatalogObjects
      security:
        - oauth2:
            - ITEMS_READ
      summary: SearchCatalogObjects
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/catalog/search-catalog-items:
    post:
      description: |-
        Searches for catalog items or item variations by matching supported search attribute values, including
        custom attribute values, against one or more of the specified query expressions.

        This (`SearchCatalogItems`) endpoint differs from the [SearchCatalogObjects](https://developer.squareup.com/reference/square_2021-08-18/catalog-api/search-catalog-objects)
        endpoint in the following aspects:

        - `SearchCatalogItems` can only search for items or item variations, whereas `SearchCatalogObjects` can search for any type of catalog objects.
        - `SearchCatalogItems` supports the custom attribute query filters to return items or item variations that contain custom attribute values, where `SearchCatalogObjects` does not.
        - `SearchCatalogItems` does not support the `include_deleted_objects` filter to search for deleted items or item variations, whereas `SearchCatalogObjects` does.
        - The both endpoints use different call conventions, including the query filter formats.
      operationId: SearchCatalogItems
      security:
        - oauth2:
            - ITEMS_READ
      summary: SearchCatalogItems
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/catalog/update-item-modifier-lists:
    post:
      description: |-
        Updates the [CatalogModifierList](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogModifierList) objects
        that apply to the targeted [CatalogItem](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogItem) without having
        to perform an upsert on the entire item.
      operationId: UpdateItemModifierLists
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: UpdateItemModifierLists
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/catalog/update-item-taxes:
    post:
      description: |-
        Updates the [CatalogTax](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogTax) objects that apply to the
        targeted [CatalogItem](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogItem) without having to perform an
        upsert on the entire item.
      operationId: UpdateItemTaxes
      security:
        - oauth2:
            - ITEMS_WRITE
      summary: UpdateItemTaxes
      tags:
        - Catalog
      x-oauthpermissions:
        - ITEMS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/customers:
    get:
      description: |-
        Lists customer profiles associated with a Square account.

        Under normal operating conditions, newly created or updated customer profiles become available
        for the listing operation in well under 30 seconds. Occasionally, propagation of the new or updated
        profiles can take closer to one minute or longer, especially during network incidents and outages.
      operationId: ListCustomers
      security:
        - oauth2:
            - CUSTOMERS_READ
      summary: ListCustomers
      tags:
        - Customers
      x-oauthpermissions:
        - CUSTOMERS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    post:
      description: |-
        Creates a new customer for a business.

        You must provide at least one of the following values in your request to this
        endpoint:

        - `given_name`
        - `family_name`
        - `company_name`
        - `email_address`
        - `phone_number`
      operationId: CreateCustomer
      security:
        - oauth2:
            - CUSTOMERS_WRITE
      summary: CreateCustomer
      tags:
        - Customers
      x-oauthpermissions:
        - CUSTOMERS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/customers/groups:
    get:
      description: Retrieves the list of customer groups of a business.
      operationId: ListCustomerGroups
      security:
        - oauth2:
            - CUSTOMERS_READ
      summary: ListCustomerGroups
      tags:
        - CustomerGroups
      x-oauthpermissions:
        - CUSTOMERS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    post:
      description: |-
        Creates a new customer group for a business.

        The request must include the `name` value of the group.
      operationId: CreateCustomerGroup
      security:
        - oauth2:
            - CUSTOMERS_WRITE
      summary: CreateCustomerGroup
      tags:
        - CustomerGroups
      x-oauthpermissions:
        - CUSTOMERS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/customers/groups/{group_id}":
    delete:
      description: Deletes a customer group as identified by the `group_id` value.
      operationId: DeleteCustomerGroup
      security:
        - oauth2:
            - CUSTOMERS_WRITE
      summary: DeleteCustomerGroup
      tags:
        - CustomerGroups
      x-oauthpermissions:
        - CUSTOMERS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    get:
      description: Retrieves a specific customer group as identified by the `group_id` value.
      operationId: RetrieveCustomerGroup
      security:
        - oauth2:
            - CUSTOMERS_READ
      summary: RetrieveCustomerGroup
      tags:
        - CustomerGroups
      x-oauthpermissions:
        - CUSTOMERS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    put:
      description: Updates a customer group as identified by the `group_id` value.
      operationId: UpdateCustomerGroup
      security:
        - oauth2:
            - CUSTOMERS_WRITE
            - CUSTOMERS_READ
      summary: UpdateCustomerGroup
      tags:
        - CustomerGroups
      x-oauthpermissions:
        - CUSTOMERS_WRITE
        - CUSTOMERS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/customers/search:
    post:
      description: |-
        Searches the customer profiles associated with a Square account using a supported query filter.

        Calling `SearchCustomers` without any explicit query filter returns all
        customer profiles ordered alphabetically based on `given_name` and
        `family_name`.

        Under normal operating conditions, newly created or updated customer profiles become available
        for the search operation in well under 30 seconds. Occasionally, propagation of the new or updated
        profiles can take closer to one minute or longer, especially during network incidents and outages.
      operationId: SearchCustomers
      security:
        - oauth2:
            - CUSTOMERS_READ
      summary: SearchCustomers
      tags:
        - Customers
      x-oauthpermissions:
        - CUSTOMERS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/customers/segments:
    get:
      description: Retrieves the list of customer segments of a business.
      operationId: ListCustomerSegments
      security:
        - oauth2:
            - CUSTOMERS_READ
      summary: ListCustomerSegments
      tags:
        - CustomerSegments
      x-oauthpermissions:
        - CUSTOMERS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/customers/segments/{segment_id}":
    get:
      description: Retrieves a specific customer segment as identified by the `segment_id` value.
      operationId: RetrieveCustomerSegment
      security:
        - oauth2:
            - CUSTOMERS_READ
      summary: RetrieveCustomerSegment
      tags:
        - CustomerSegments
      x-oauthpermissions:
        - CUSTOMERS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/customers/{customer_id}":
    delete:
      description: |-
        Deletes a customer profile from a business. This operation also unlinks any associated cards on file. 

        As a best practice, you should include the `version` field in the request to enable [optimistic concurrency](https://developer.squareup.com/docs/working-with-apis/optimistic-concurrency) control. The value must be set to the current version of the customer profile. 

        To delete a customer profile that was created by merging existing profiles, you must use the ID of the newly created profile.
      operationId: DeleteCustomer
      security:
        - oauth2:
            - CUSTOMERS_WRITE
      summary: DeleteCustomer
      tags:
        - Customers
      x-oauthpermissions:
        - CUSTOMERS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    get:
      description: Returns details for a single customer.
      operationId: RetrieveCustomer
      security:
        - oauth2:
            - CUSTOMERS_READ
      summary: RetrieveCustomer
      tags:
        - Customers
      x-oauthpermissions:
        - CUSTOMERS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    put:
      description: |-
        Updates a customer profile. To change an attribute, specify the new value. To remove an attribute, specify the value as an empty string or empty object.

        As a best practice, you should include the `version` field in the request to enable [optimistic concurrency](https://developer.squareup.com/docs/working-with-apis/optimistic-concurrency) control. The value must be set to the current version of the customer profile.

        To update a customer profile that was created by merging existing profiles, you must use the ID of the newly created profile.

        You cannot use this endpoint to change cards on file. To make changes, use the [Cards API](https://developer.squareup.com/reference/square_2021-08-18/cards-api) or [Gift Cards API](https://developer.squareup.com/reference/square_2021-08-18/gift-cards-api).
      operationId: UpdateCustomer
      security:
        - oauth2:
            - CUSTOMERS_WRITE
      summary: UpdateCustomer
      tags:
        - Customers
      x-oauthpermissions:
        - CUSTOMERS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/customers/{customer_id}/cards":
    post:
      description: |-
        Adds a card on file to an existing customer.

        As with charges, calls to `CreateCustomerCard` are idempotent. Multiple
        calls with the same card nonce return the same card record that was created
        with the provided nonce during the _first_ call.
      operationId: CreateCustomerCard
      security:
        - oauth2:
            - CUSTOMERS_WRITE
      summary: CreateCustomerCard
      tags:
        - Customers
      x-is-deprecated: true
      x-oauthpermissions:
        - CUSTOMERS_WRITE
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  "/v2/customers/{customer_id}/cards/{card_id}":
    delete:
      description: Removes a card on file from a customer.
      operationId: DeleteCustomerCard
      security:
        - oauth2:
            - CUSTOMERS_WRITE
      summary: DeleteCustomerCard
      tags:
        - Customers
      x-is-deprecated: true
      x-oauthpermissions:
        - CUSTOMERS_WRITE
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  "/v2/customers/{customer_id}/groups/{group_id}":
    delete:
      description: |-
        Removes a group membership from a customer.

        The customer is identified by the `customer_id` value
        and the customer group is identified by the `group_id` value.
      operationId: RemoveGroupFromCustomer
      security:
        - oauth2:
            - CUSTOMERS_WRITE
      summary: RemoveGroupFromCustomer
      tags:
        - Customers
      x-oauthpermissions:
        - CUSTOMERS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    put:
      description: |-
        Adds a group membership to a customer.

        The customer is identified by the `customer_id` value
        and the customer group is identified by the `group_id` value.
      operationId: AddGroupToCustomer
      security:
        - oauth2:
            - CUSTOMERS_WRITE
      summary: AddGroupToCustomer
      tags:
        - Customers
      x-oauthpermissions:
        - CUSTOMERS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/devices/codes:
    get:
      description: Lists all DeviceCodes associated with the merchant.
      operationId: ListDeviceCodes
      security:
        - oauth2:
            - DEVICE_CREDENTIAL_MANAGEMENT
      summary: ListDeviceCodes
      tags:
        - Devices
      x-oauthpermissions:
        - DEVICE_CREDENTIAL_MANAGEMENT
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    post:
      description: |-
        Creates a DeviceCode that can be used to login to a Square Terminal device to enter the connected
        terminal mode.
      operationId: CreateDeviceCode
      security:
        - oauth2:
            - DEVICE_CREDENTIAL_MANAGEMENT
      summary: CreateDeviceCode
      tags:
        - Devices
      x-oauthpermissions:
        - DEVICE_CREDENTIAL_MANAGEMENT
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/devices/codes/{id}":
    get:
      description: Retrieves DeviceCode with the associated ID.
      operationId: GetDeviceCode
      security:
        - oauth2:
            - DEVICE_CREDENTIAL_MANAGEMENT
      summary: GetDeviceCode
      tags:
        - Devices
      x-oauthpermissions:
        - DEVICE_CREDENTIAL_MANAGEMENT
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/disputes:
    get:
      description: Returns a list of disputes associated with a particular account.
      operationId: ListDisputes
      security:
        - oauth2:
            - DISPUTES_READ
      summary: ListDisputes
      tags:
        - Disputes
      x-oauthpermissions:
        - DISPUTES_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/disputes/{dispute_id}":
    get:
      description: Returns details about a specific dispute.
      operationId: RetrieveDispute
      security:
        - oauth2:
            - DISPUTES_READ
      summary: RetrieveDispute
      tags:
        - Disputes
      x-oauthpermissions:
        - DISPUTES_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/disputes/{dispute_id}/accept":
    post:
      description: |-
        Accepts the loss on a dispute. Square returns the disputed amount to the cardholder and
        updates the dispute state to ACCEPTED.

        Square debits the disputed amount from the seller’s Square account. If the Square account
        does not have sufficient funds, Square debits the associated bank account.
      operationId: AcceptDispute
      security:
        - oauth2:
            - DISPUTES_WRITE
      summary: AcceptDispute
      tags:
        - Disputes
      x-oauthpermissions:
        - DISPUTES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/disputes/{dispute_id}/evidence":
    get:
      description: Returns a list of evidence associated with a dispute.
      operationId: ListDisputeEvidence
      security:
        - oauth2:
            - DISPUTES_READ
      summary: ListDisputeEvidence
      tags:
        - Disputes
      x-oauthpermissions:
        - DISPUTES_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/disputes/{dispute_id}/evidence-text":
    post:
      description: Uploads text to use as evidence for a dispute challenge.
      operationId: CreateDisputeEvidenceText
      security:
        - oauth2:
            - DISPUTES_WRITE
      summary: CreateDisputeEvidenceText
      tags:
        - Disputes
      x-oauthpermissions:
        - DISPUTES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/disputes/{dispute_id}/evidence/{evidence_id}":
    delete:
      description: |-
        Removes specified evidence from a dispute.

        Square does not send the bank any evidence that is removed. Also, you cannot remove evidence after
        submitting it to the bank using [SubmitEvidence](https://developer.squareup.com/reference/square_2021-08-18/disputes-api/submit-evidence).
      operationId: DeleteDisputeEvidence
      security:
        - oauth2:
            - DISPUTES_WRITE
      summary: DeleteDisputeEvidence
      tags:
        - Disputes
      x-oauthpermissions:
        - DISPUTES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    get:
      description: |-
        Returns the evidence metadata specified by the evidence ID in the request URL path

        You must maintain a copy of the evidence you upload if you want to reference it later. You cannot
        download the evidence after you upload it.
      operationId: RetrieveDisputeEvidence
      security:
        - oauth2:
            - DISPUTES_READ
      summary: RetrieveDisputeEvidence
      tags:
        - Disputes
      x-oauthpermissions:
        - DISPUTES_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/disputes/{dispute_id}/submit-evidence":
    post:
      description: |-
        Submits evidence to the cardholder's bank.

        Before submitting evidence, Square compiles all available evidence. This includes evidence uploaded
        using the [CreateDisputeEvidenceFile](https://developer.squareup.com/reference/square_2021-08-18/disputes-api/create-dispute-evidence-file) and
        [CreateDisputeEvidenceText](https://developer.squareup.com/reference/square_2021-08-18/disputes-api/create-dispute-evidence-text) endpoints and
        evidence automatically provided by Square, when available.
      operationId: SubmitEvidence
      security:
        - oauth2:
            - DISPUTES_WRITE
      summary: SubmitEvidence
      tags:
        - Disputes
      x-oauthpermissions:
        - DISPUTES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/employees:
    get:
      description: ""
      security:
        - oauth2:
            - EMPLOYEES_READ
      summary: ListEmployees
      tags:
        - Employees
      x-is-deprecated: true
      x-oauthpermissions:
        - EMPLOYEES_READ
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  "/v2/employees/{id}":
    get:
      description: ""
      security:
        - oauth2:
            - EMPLOYEES_READ
      summary: RetrieveEmployee
      tags:
        - Employees
      x-is-deprecated: true
      x-oauthpermissions:
        - EMPLOYEES_READ
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  /v2/gift-cards:
    get:
      description: |-
        Lists all gift cards. You can specify optional filters to retrieve 
        a subset of the gift cards.
      operationId: ListGiftCards
      security:
        - oauth2:
            - GIFTCARDS_READ
      summary: ListGiftCards
      tags:
        - GiftCards
      x-is-beta: true
      x-oauthpermissions:
        - GIFTCARDS_READ
      x-release-status: BETA
      x-sq-version: 2021-08-18
    post:
      description: |-
        Creates a digital gift card or registers a physical (plastic) gift card. You must activate the gift card before 
        it can be used for payment. For more information, see 
        [Selling gift cards](https://developer.squareup.com/docs/gift-cards/using-gift-cards-api#selling-square-gift-cards).
      operationId: CreateGiftCard
      security:
        - oauth2:
            - GIFTCARDS_WRITE
      summary: CreateGiftCard
      tags:
        - GiftCards
      x-is-beta: true
      x-oauthpermissions:
        - GIFTCARDS_WRITE
      x-release-status: BETA
      x-sq-version: 2021-08-18
  /v2/gift-cards/activities:
    get:
      description: |-
        Lists gift card activities. By default, you get gift card activities for all
        gift cards in the seller's account. You can optionally specify query parameters to
        filter the list. For example, you can get a list of gift card activities for a gift card,
        for all gift cards in a specific region, or for activities within a time window.
      operationId: ListGiftCardActivities
      security:
        - oauth2:
            - GIFTCARDS_READ
      summary: ListGiftCardActivities
      tags:
        - GiftCardActivities
      x-is-beta: true
      x-oauthpermissions:
        - GIFTCARDS_READ
      x-release-status: BETA
      x-sq-version: 2021-08-18
    post:
      description: |-
        Creates a gift card activity. For more information, see 
        [GiftCardActivity](https://developer.squareup.com/docs/gift-cards/using-gift-cards-api#giftcardactivity) and 
        [Using activated gift cards](https://developer.squareup.com/docs/gift-cards/using-gift-cards-api#using-activated-gift-cards).
      operationId: CreateGiftCardActivity
      security:
        - oauth2:
            - GIFTCARDS_WRITE
      summary: CreateGiftCardActivity
      tags:
        - GiftCardActivities
      x-is-beta: true
      x-oauthpermissions:
        - GIFTCARDS_WRITE
      x-release-status: BETA
      x-sq-version: 2021-08-18
  /v2/gift-cards/from-gan:
    post:
      description: Retrieves a gift card using the gift card account number (GAN).
      operationId: RetrieveGiftCardFromGAN
      security:
        - oauth2:
            - GIFTCARDS_READ
      summary: RetrieveGiftCardFromGAN
      tags:
        - GiftCards
      x-is-beta: true
      x-oauthpermissions:
        - GIFTCARDS_READ
      x-release-status: BETA
      x-sq-version: 2021-08-18
  /v2/gift-cards/from-nonce:
    post:
      description: Retrieves a gift card using a nonce (a secure token) that represents the gift card.
      operationId: RetrieveGiftCardFromNonce
      security:
        - oauth2:
            - GIFTCARDS_READ
      summary: RetrieveGiftCardFromNonce
      tags:
        - GiftCards
      x-is-beta: true
      x-oauthpermissions:
        - GIFTCARDS_READ
      x-release-status: BETA
      x-sq-version: 2021-08-18
  "/v2/gift-cards/{gift_card_id}/link-customer":
    post:
      description: Links a customer to a gift card
      operationId: LinkCustomerToGiftCard
      security:
        - oauth2:
            - GIFTCARDS_WRITE
      summary: LinkCustomerToGiftCard
      tags:
        - GiftCards
      x-is-beta: true
      x-oauthpermissions:
        - GIFTCARDS_WRITE
      x-release-status: BETA
      x-sq-version: 2021-08-18
  "/v2/gift-cards/{gift_card_id}/unlink-customer":
    post:
      description: Unlinks a customer from a gift card
      operationId: UnlinkCustomerFromGiftCard
      security:
        - oauth2:
            - GIFTCARDS_WRITE
      summary: UnlinkCustomerFromGiftCard
      tags:
        - GiftCards
      x-is-beta: true
      x-oauthpermissions:
        - GIFTCARDS_WRITE
      x-release-status: BETA
      x-sq-version: 2021-08-18
  "/v2/gift-cards/{id}":
    get:
      description: Retrieves a gift card using its ID.
      operationId: RetrieveGiftCard
      security:
        - oauth2:
            - GIFTCARDS_READ
      summary: RetrieveGiftCard
      tags:
        - GiftCards
      x-is-beta: true
      x-oauthpermissions:
        - GIFTCARDS_READ
      x-release-status: BETA
      x-sq-version: 2021-08-18
  "/v2/inventory/adjustment/{adjustment_id}":
    get:
      description: |-
        Deprecated version of [RetrieveInventoryAdjustment](https://developer.squareup.com/reference/square_2021-08-18/inventory-api/retrieve-inventory-adjustment) after the endpoint URL 
        is updated to conform to the standard convention.
      operationId: DeprecatedRetrieveInventoryAdjustment
      security:
        - oauth2:
            - INVENTORY_READ
      summary: DeprecatedRetrieveInventoryAdjustment
      tags:
        - Inventory
      x-is-deprecated: true
      x-oauthpermissions:
        - INVENTORY_READ
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  "/v2/inventory/adjustments/{adjustment_id}":
    get:
      description: |-
        Returns the [InventoryAdjustment](https://developer.squareup.com/reference/square_2021-08-18/objects/InventoryAdjustment) object
        with the provided `adjustment_id`.
      operationId: RetrieveInventoryAdjustment
      security:
        - oauth2:
            - INVENTORY_READ
      summary: RetrieveInventoryAdjustment
      tags:
        - Inventory
      x-oauthpermissions:
        - INVENTORY_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/inventory/batch-change:
    post:
      description: |-
        Deprecated version of [BatchChangeInventory](https://developer.squareup.com/reference/square_2021-08-18/inventory-api/batch-change-inventory) after the endpoint URL 
        is updated to conform to the standard convention.
      operationId: DeprecatedBatchChangeInventory
      security:
        - oauth2:
            - INVENTORY_WRITE
      summary: DeprecatedBatchChangeInventory
      tags:
        - Inventory
      x-is-deprecated: true
      x-oauthpermissions:
        - INVENTORY_WRITE
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  /v2/inventory/batch-retrieve-changes:
    post:
      description: |-
        Deprecated version of [BatchRetrieveInventoryChanges](https://developer.squareup.com/reference/square_2021-08-18/inventory-api/batch-retrieve-inventory-changes) after the endpoint URL 
        is updated to conform to the standard convention.
      operationId: DeprecatedBatchRetrieveInventoryChanges
      security:
        - oauth2:
            - INVENTORY_READ
      summary: DeprecatedBatchRetrieveInventoryChanges
      tags:
        - Inventory
      x-is-deprecated: true
      x-oauthpermissions:
        - INVENTORY_READ
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  /v2/inventory/batch-retrieve-counts:
    post:
      description: |-
        Deprecated version of [BatchRetrieveInventoryCounts](https://developer.squareup.com/reference/square_2021-08-18/inventory-api/batch-retrieve-inventory-counts) after the endpoint URL 
        is updated to conform to the standard convention.
      operationId: DeprecatedBatchRetrieveInventoryCounts
      security:
        - oauth2:
            - INVENTORY_READ
      summary: DeprecatedBatchRetrieveInventoryCounts
      tags:
        - Inventory
      x-is-deprecated: true
      x-oauthpermissions:
        - INVENTORY_READ
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  /v2/inventory/changes/batch-create:
    post:
      description: |-
        Applies adjustments and counts to the provided item quantities.

        On success: returns the current calculated counts for all objects
        referenced in the request.
        On failure: returns a list of related errors.
      operationId: BatchChangeInventory
      security:
        - oauth2:
            - INVENTORY_WRITE
      summary: BatchChangeInventory
      tags:
        - Inventory
      x-oauthpermissions:
        - INVENTORY_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/inventory/changes/batch-retrieve:
    post:
      description: |-
        Returns historical physical counts and adjustments based on the
        provided filter criteria.

        Results are paginated and sorted in ascending order according their
        `occurred_at` timestamp (oldest first).

        BatchRetrieveInventoryChanges is a catch-all query endpoint for queries
        that cannot be handled by other, simpler endpoints.
      operationId: BatchRetrieveInventoryChanges
      security:
        - oauth2:
            - INVENTORY_READ
      summary: BatchRetrieveInventoryChanges
      tags:
        - Inventory
      x-oauthpermissions:
        - INVENTORY_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/inventory/counts/batch-retrieve:
    post:
      description: |-
        Returns current counts for the provided
        [CatalogObject](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogObject)s at the requested
        [Location](https://developer.squareup.com/reference/square_2021-08-18/objects/Location)s.

        Results are paginated and sorted in descending order according to their
        `calculated_at` timestamp (newest first).

        When `updated_after` is specified, only counts that have changed since that
        time (based on the server timestamp for the most recent change) are
        returned. This allows clients to perform a "sync" operation, for example
        in response to receiving a Webhook notification.
      operationId: BatchRetrieveInventoryCounts
      security:
        - oauth2:
            - INVENTORY_READ
      summary: BatchRetrieveInventoryCounts
      tags:
        - Inventory
      x-oauthpermissions:
        - INVENTORY_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/inventory/physical-count/{physical_count_id}":
    get:
      description: |-
        Deprecated version of [RetrieveInventoryPhysicalCount](https://developer.squareup.com/reference/square_2021-08-18/inventory-api/retrieve-inventory-physical-count) after the endpoint URL 
        is updated to conform to the standard convention.
      operationId: DeprecatedRetrieveInventoryPhysicalCount
      security:
        - oauth2:
            - INVENTORY_READ
      summary: DeprecatedRetrieveInventoryPhysicalCount
      tags:
        - Inventory
      x-is-deprecated: true
      x-oauthpermissions:
        - INVENTORY_READ
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  "/v2/inventory/physical-counts/{physical_count_id}":
    get:
      description: |-
        Returns the [InventoryPhysicalCount](https://developer.squareup.com/reference/square_2021-08-18/objects/InventoryPhysicalCount)
        object with the provided `physical_count_id`.
      operationId: RetrieveInventoryPhysicalCount
      security:
        - oauth2:
            - INVENTORY_READ
      summary: RetrieveInventoryPhysicalCount
      tags:
        - Inventory
      x-oauthpermissions:
        - INVENTORY_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/inventory/transfers/{transfer_id}":
    get:
      description: |-
        Returns the [InventoryTransfer](https://developer.squareup.com/reference/square_2021-08-18/objects/InventoryTransfer) object
        with the provided `transfer_id`.
      operationId: RetrieveInventoryTransfer
      security:
        - oauth2:
            - INVENTORY_READ
      summary: RetrieveInventoryTransfer
      tags:
        - Inventory
      x-is-beta: true
      x-oauthpermissions:
        - INVENTORY_READ
      x-release-status: BETA
      x-sq-version: 2021-08-18
  "/v2/inventory/{catalog_object_id}":
    get:
      description: |-
        Retrieves the current calculated stock count for a given
        [CatalogObject](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogObject) at a given set of
        [Location](https://developer.squareup.com/reference/square_2021-08-18/objects/Location)s. Responses are paginated and unsorted.
        For more sophisticated queries, use a batch endpoint.
      operationId: RetrieveInventoryCount
      security:
        - oauth2:
            - INVENTORY_READ
      summary: RetrieveInventoryCount
      tags:
        - Inventory
      x-oauthpermissions:
        - INVENTORY_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/inventory/{catalog_object_id}/changes":
    get:
      description: |-
        Returns a set of physical counts and inventory adjustments for the
        provided [CatalogObject](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogObject) at the requested
        [Location](https://developer.squareup.com/reference/square_2021-08-18/objects/Location)s. 

        You can achieve the same result by calling [BatchRetrieveInventoryChanges](https://developer.squareup.com/reference/square_2021-08-18/inventory-api/batch-retrieve-inventory-changes) 
        and having the `catalog_object_ids` list contain a single element of the `CatalogObject` ID.

        Results are paginated and sorted in descending order according to their
        `occurred_at` timestamp (newest first).

        There are no limits on how far back the caller can page. This endpoint can be 
        used to display recent changes for a specific item. For more
        sophisticated queries, use a batch endpoint.
      operationId: RetrieveInventoryChanges
      security:
        - oauth2:
            - INVENTORY_READ
      summary: RetrieveInventoryChanges
      tags:
        - Inventory
      x-is-deprecated: true
      x-oauthpermissions:
        - INVENTORY_READ
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  /v2/invoices:
    get:
      description: |-
        Returns a list of invoices for a given location. The response 
        is paginated. If truncated, the response includes a `cursor` that you    
        use in a subsequent request to retrieve the next set of invoices.
      operationId: ListInvoices
      security:
        - oauth2:
            - INVOICES_READ
      summary: ListInvoices
      tags:
        - Invoices
      x-oauthpermissions:
        - INVOICES_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    post:
      description: |-
        Creates a draft [invoice](https://developer.squareup.com/reference/square_2021-08-18/objects/Invoice) 
        for an order created using the Orders API.

        A draft invoice remains in your account and no action is taken. 
        You must publish the invoice before Square can process it (send it to the customer's email address or charge the customer’s card on file).
      operationId: CreateInvoice
      security:
        - oauth2:
            - ORDERS_WRITE
            - INVOICES_WRITE
      summary: CreateInvoice
      tags:
        - Invoices
      x-oauthpermissions:
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/invoices/search:
    post:
      description: |-
        Searches for invoices from a location specified in 
        the filter. You can optionally specify customers in the filter for whom to 
        retrieve invoices. In the current implementation, you can only specify one location and 
        optionally one customer.

        The response is paginated. If truncated, the response includes a `cursor` 
        that you use in a subsequent request to retrieve the next set of invoices.
      operationId: SearchInvoices
      security:
        - oauth2:
            - INVOICES_READ
      summary: SearchInvoices
      tags:
        - Invoices
      x-oauthpermissions:
        - INVOICES_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/invoices/{invoice_id}":
    delete:
      description: |-
        Deletes the specified invoice. When an invoice is deleted, the 
        associated order status changes to CANCELED. You can only delete a draft 
        invoice (you cannot delete a published invoice, including one that is scheduled for processing).
      operationId: DeleteInvoice
      security:
        - oauth2:
            - ORDERS_WRITE
            - INVOICES_WRITE
      summary: DeleteInvoice
      tags:
        - Invoices
      x-oauthpermissions:
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    get:
      description: Retrieves an invoice by invoice ID.
      operationId: GetInvoice
      security:
        - oauth2:
            - INVOICES_READ
      summary: GetInvoice
      tags:
        - Invoices
      x-oauthpermissions:
        - INVOICES_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    put:
      description: |-
        Updates an invoice by modifying fields, clearing fields, or both. For most updates, you can use a sparse 
        `Invoice` object to add fields or change values and use the `fields_to_clear` field to specify fields to clear. 
        However, some restrictions apply. For example, you cannot change the `order_id` or `location_id` field and you 
        must provide the complete `custom_fields` list to update a custom field. Published invoices have additional restrictions.
      operationId: UpdateInvoice
      security:
        - oauth2:
            - ORDERS_WRITE
            - INVOICES_WRITE
      summary: UpdateInvoice
      tags:
        - Invoices
      x-oauthpermissions:
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/invoices/{invoice_id}/cancel":
    post:
      description: |-
        Cancels an invoice. The seller cannot collect payments for 
        the canceled invoice.

        You cannot cancel an invoice in the `DRAFT` state or in a terminal state: `PAID`, `REFUNDED`, `CANCELED`, or `FAILED`.
      operationId: CancelInvoice
      security:
        - oauth2:
            - ORDERS_WRITE
            - INVOICES_WRITE
      summary: CancelInvoice
      tags:
        - Invoices
      x-oauthpermissions:
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/invoices/{invoice_id}/publish":
    post:
      description: |-
        Publishes the specified draft invoice. 

        After an invoice is published, Square 
        follows up based on the invoice configuration. For example, Square 
        sends the invoice to the customer's email address, charges the customer's card on file, or does 
        nothing. Square also makes the invoice available on a Square-hosted invoice page. 

        The invoice `status` also changes from `DRAFT` to a status 
        based on the invoice configuration. For example, the status changes to `UNPAID` if 
        Square emails the invoice or `PARTIALLY_PAID` if Square charge a card on file for a portion of the 
        invoice amount.
      operationId: PublishInvoice
      security:
        - oauth2:
            - ORDERS_WRITE
            - INVOICES_WRITE
      summary: PublishInvoice
      tags:
        - Invoices
      x-oauthpermissions:
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/labor/break-types:
    get:
      description: Returns a paginated list of `BreakType` instances for a business.
      operationId: ListBreakTypes
      security:
        - oauth2:
            - TIMECARDS_SETTINGS_READ
      summary: ListBreakTypes
      tags:
        - Labor
      x-oauthpermissions:
        - TIMECARDS_SETTINGS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    post:
      description: |-
        Creates a new `BreakType`.

        A `BreakType` is a template for creating `Break` objects.
        You must provide the following values in your request to this
        endpoint:

        - `location_id`
        - `break_name`
        - `expected_duration`
        - `is_paid`

        You can only have three `BreakType` instances per location. If you attempt to add a fourth
        `BreakType` for a location, an `INVALID_REQUEST_ERROR` "Exceeded limit of 3 breaks per location."
        is returned.
      operationId: CreateBreakType
      security:
        - oauth2:
            - TIMECARDS_SETTINGS_WRITE
      summary: CreateBreakType
      tags:
        - Labor
      x-oauthpermissions:
        - TIMECARDS_SETTINGS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/labor/break-types/{id}":
    delete:
      description: |-
        Deletes an existing `BreakType`.

        A `BreakType` can be deleted even if it is referenced from a `Shift`.
      operationId: DeleteBreakType
      security:
        - oauth2:
            - TIMECARDS_SETTINGS_WRITE
      summary: DeleteBreakType
      tags:
        - Labor
      x-oauthpermissions:
        - TIMECARDS_SETTINGS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    get:
      description: Returns a single `BreakType` specified by `id`.
      operationId: GetBreakType
      security:
        - oauth2:
            - TIMECARDS_SETTINGS_READ
      summary: GetBreakType
      tags:
        - Labor
      x-oauthpermissions:
        - TIMECARDS_SETTINGS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    put:
      description: Updates an existing `BreakType`.
      operationId: UpdateBreakType
      security:
        - oauth2:
            - TIMECARDS_SETTINGS_WRITE
            - TIMECARDS_SETTINGS_READ
      summary: UpdateBreakType
      tags:
        - Labor
      x-oauthpermissions:
        - TIMECARDS_SETTINGS_WRITE
        - TIMECARDS_SETTINGS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/labor/employee-wages:
    get:
      description: Returns a paginated list of `EmployeeWage` instances for a business.
      operationId: ListEmployeeWages
      security:
        - oauth2:
            - EMPLOYEES_READ
      summary: ListEmployeeWages
      tags:
        - Labor
      x-is-deprecated: true
      x-oauthpermissions:
        - EMPLOYEES_READ
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  "/v2/labor/employee-wages/{id}":
    get:
      description: Returns a single `EmployeeWage` specified by `id`.
      operationId: GetEmployeeWage
      security:
        - oauth2:
            - EMPLOYEES_READ
      summary: GetEmployeeWage
      tags:
        - Labor
      x-is-deprecated: true
      x-oauthpermissions:
        - EMPLOYEES_READ
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  /v2/labor/shifts:
    post:
      description: |-
        Creates a new `Shift`.

        A `Shift` represents a complete workday for a single employee.
        You must provide the following values in your request to this
        endpoint:

        - `location_id`
        - `employee_id`
        - `start_at`

        An attempt to create a new `Shift` can result in a `BAD_REQUEST` error when:
        - The `status` of the new `Shift` is `OPEN` and the employee has another
        shift with an `OPEN` status.
        - The `start_at` date is in the future.
        - The `start_at` or `end_at` date overlaps another shift for the same employee.
        - The `Break` instances are set in the request and a break `start_at`
        is before the `Shift.start_at`, a break `end_at` is after
        the `Shift.end_at`, or both.
      operationId: CreateShift
      security:
        - oauth2:
            - TIMECARDS_WRITE
      summary: CreateShift
      tags:
        - Labor
      x-oauthpermissions:
        - TIMECARDS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/labor/shifts/search:
    post:
      description: |-
        Returns a paginated list of `Shift` records for a business.
        The list to be returned can be filtered by:
        - Location IDs.
        - Employee IDs.
        - Shift status (`OPEN` and `CLOSED`).
        - Shift start.
        - Shift end.
        - Workday details.

        The list can be sorted by:
        - `start_at`.
        - `end_at`.
        - `created_at`.
        - `updated_at`.
      operationId: SearchShifts
      security:
        - oauth2:
            - TIMECARDS_READ
      summary: SearchShifts
      tags:
        - Labor
      x-oauthpermissions:
        - TIMECARDS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/labor/shifts/{id}":
    delete:
      description: Deletes a `Shift`.
      operationId: DeleteShift
      security:
        - oauth2:
            - TIMECARDS_WRITE
      summary: DeleteShift
      tags:
        - Labor
      x-oauthpermissions:
        - TIMECARDS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    get:
      description: Returns a single `Shift` specified by `id`.
      operationId: GetShift
      security:
        - oauth2:
            - TIMECARDS_READ
      summary: GetShift
      tags:
        - Labor
      x-oauthpermissions:
        - TIMECARDS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    put:
      description: |-
        Updates an existing `Shift`.

        When adding a `Break` to a `Shift`, any earlier `Break` instances in the `Shift` have
        the `end_at` property set to a valid RFC-3339 datetime string.

        When closing a `Shift`, all `Break` instances in the `Shift` must be complete with `end_at`
        set on each `Break`.
      operationId: UpdateShift
      security:
        - oauth2:
            - TIMECARDS_WRITE
            - TIMECARDS_READ
      summary: UpdateShift
      tags:
        - Labor
      x-oauthpermissions:
        - TIMECARDS_WRITE
        - TIMECARDS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/labor/team-member-wages:
    get:
      description: Returns a paginated list of `TeamMemberWage` instances for a business.
      operationId: ListTeamMemberWages
      security:
        - oauth2:
            - EMPLOYEES_READ
      summary: ListTeamMemberWages
      tags:
        - Labor
      x-oauthpermissions:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/labor/team-member-wages/{id}":
    get:
      description: Returns a single `TeamMemberWage` specified by `id `.
      operationId: GetTeamMemberWage
      security:
        - oauth2:
            - EMPLOYEES_READ
      summary: GetTeamMemberWage
      tags:
        - Labor
      x-oauthpermissions:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/labor/workweek-configs:
    get:
      description: Returns a list of `WorkweekConfig` instances for a business.
      operationId: ListWorkweekConfigs
      security:
        - oauth2:
            - TIMECARDS_SETTINGS_READ
      summary: ListWorkweekConfigs
      tags:
        - Labor
      x-oauthpermissions:
        - TIMECARDS_SETTINGS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/labor/workweek-configs/{id}":
    put:
      description: Updates a `WorkweekConfig`.
      operationId: UpdateWorkweekConfig
      security:
        - oauth2:
            - TIMECARDS_SETTINGS_WRITE
            - TIMECARDS_SETTINGS_READ
      summary: UpdateWorkweekConfig
      tags:
        - Labor
      x-oauthpermissions:
        - TIMECARDS_SETTINGS_WRITE
        - TIMECARDS_SETTINGS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/locations:
    get:
      description: |-
        Provides information of all locations of a business.

        Many Square API endpoints require a `location_id` parameter.
        The `id` field of the [`Location`](https://developer.squareup.com/reference/square_2021-08-18/objects/Location) objects returned by this
        endpoint correspond to that `location_id` parameter.
      operationId: ListLocations
      security:
        - oauth2:
            - MERCHANT_PROFILE_READ
      summary: ListLocations
      tags:
        - Locations
      x-oauthpermissions:
        - MERCHANT_PROFILE_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    post:
      description: Creates a location.
      operationId: CreateLocation
      security:
        - oauth2:
            - MERCHANT_PROFILE_WRITE
      summary: CreateLocation
      tags:
        - Locations
      x-is-beta: true
      x-oauthpermissions:
        - MERCHANT_PROFILE_WRITE
      x-release-status: BETA
      x-sq-version: 2021-08-18
  "/v2/locations/{location_id}":
    get:
      description: |-
        Retrieves details of a location. You can specify "main" 
        as the location ID to retrieve details of the 
        main location.
      operationId: RetrieveLocation
      security:
        - oauth2:
            - MERCHANT_PROFILE_READ
      summary: RetrieveLocation
      tags:
        - Locations
      x-oauthpermissions:
        - MERCHANT_PROFILE_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    put:
      description: Updates a location.
      operationId: UpdateLocation
      security:
        - oauth2:
            - MERCHANT_PROFILE_WRITE
      summary: UpdateLocation
      tags:
        - Locations
      x-is-beta: true
      x-oauthpermissions:
        - MERCHANT_PROFILE_WRITE
      x-release-status: BETA
      x-sq-version: 2021-08-18
  "/v2/locations/{location_id}/checkouts":
    post:
      description: |-
        Links a `checkoutId` to a `checkout_page_url` that customers are
        directed to in order to provide their payment information using a
        payment processing workflow hosted on connect.squareup.com.
      operationId: CreateCheckout
      security:
        - oauth2:
            - PAYMENTS_WRITE
            - ORDERS_WRITE
      summary: CreateCheckout
      tags:
        - Checkout
      x-oauthpermissions:
        - PAYMENTS_WRITE
        - ORDERS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/locations/{location_id}/refunds":
    get:
      description: |-
        Lists refunds for one of a business's locations.

        In addition to full or partial tender refunds processed through Square APIs,
        refunds may result from itemized returns or exchanges through Square's
        Point of Sale applications.

        Refunds with a `status` of `PENDING` are not currently included in this
        endpoint's response.

        Max results per [page](https://developer.squareup.com/docs/working-with-apis/pagination): 50
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: ListRefunds
      tags:
        - Transactions
      x-is-deprecated: true
      x-oauthpermissions:
        - PAYMENTS_READ
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  "/v2/locations/{location_id}/transactions":
    get:
      description: |-
        Lists transactions for a particular location.

        Transactions include payment information from sales and exchanges and refund
        information from returns and exchanges.

        Max results per [page](https://developer.squareup.com/docs/working-with-apis/pagination): 50
      operationId: ListTransactions
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: ListTransactions
      tags:
        - Transactions
      x-is-deprecated: true
      x-oauthpermissions:
        - PAYMENTS_READ
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
    post:
      description: |-
        Charges a card represented by a card nonce or a customer's card on file.

        Your request to this endpoint must include _either_:

        - A value for the `card_nonce` parameter (to charge a card payment token generated
        with the Web Payments SDK)
        - Values for the `customer_card_id` and `customer_id` parameters (to charge
        a customer's card on file)

        In order for an eCommerce payment to potentially qualify for
        [Square chargeback protection](https://squareup.com/help/article/5394), you
        _must_ provide values for the following parameters in your request:

        - `buyer_email_address`
        - At least one of `billing_address` or `shipping_address`

        When this response is returned, the amount of Square's processing fee might not yet be
        calculated. To obtain the processing fee, wait about ten seconds and call
        [RetrieveTransaction](https://developer.squareup.com/reference/square_2021-08-18/transactions-api/retrieve-transaction). See the `processing_fee_money`
        field of each [Tender included](https://developer.squareup.com/reference/square_2021-08-18/objects/Tender) in the transaction.
      operationId: Charge
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: Charge
      tags:
        - Transactions
      x-is-deprecated: true
      x-oauthpermissions:
        - PAYMENTS_WRITE
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  "/v2/locations/{location_id}/transactions/{transaction_id}":
    get:
      description: Retrieves details for a single transaction.
      operationId: RetrieveTransaction
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: RetrieveTransaction
      tags:
        - Transactions
      x-is-deprecated: true
      x-oauthpermissions:
        - PAYMENTS_READ
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  "/v2/locations/{location_id}/transactions/{transaction_id}/capture":
    post:
      description: |-
        Captures a transaction that was created with the [Charge](https://developer.squareup.com/reference/square_2021-08-18/transactions-api/charge)
        endpoint with a `delay_capture` value of `true`.


        See [Delayed capture transactions](https://developer.squareup.com/docs/payments/transactions/overview#delayed-capture)
        for more information.
      operationId: CaptureTransaction
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: CaptureTransaction
      tags:
        - Transactions
      x-is-deprecated: true
      x-oauthpermissions:
        - PAYMENTS_WRITE
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  "/v2/locations/{location_id}/transactions/{transaction_id}/refund":
    post:
      description: |-
        Initiates a refund for a previously charged tender.

        You must issue a refund within 120 days of the associated payment. See
        [this article](https://squareup.com/help/us/en/article/5060) for more information
        on refund behavior.

        NOTE: Card-present transactions with Interac credit cards **cannot be
        refunded using the Connect API**. Interac transactions must refunded
        in-person (e.g., dipping the card using POS app).
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: CreateRefund
      tags:
        - Transactions
      x-is-deprecated: true
      x-oauthpermissions:
        - PAYMENTS_WRITE
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  "/v2/locations/{location_id}/transactions/{transaction_id}/void":
    post:
      description: |-
        Cancels a transaction that was created with the [Charge](https://developer.squareup.com/reference/square_2021-08-18/transactions-api/charge)
        endpoint with a `delay_capture` value of `true`.


        See [Delayed capture transactions](https://developer.squareup.com/docs/payments/transactions/overview#delayed-capture)
        for more information.
      operationId: VoidTransaction
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: VoidTransaction
      tags:
        - Transactions
      x-is-deprecated: true
      x-oauthpermissions:
        - PAYMENTS_WRITE
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  /v2/loyalty/accounts:
    post:
      description: Creates a loyalty account. To create a loyalty account, you must provide the `program_id` and a `mapping` with the `phone_number` of the buyer.
      operationId: CreateLoyaltyAccount
      security:
        - oauth2:
            - LOYALTY_WRITE
      summary: CreateLoyaltyAccount
      tags:
        - Loyalty
      x-oauthpermissions:
        - LOYALTY_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/loyalty/accounts/search:
    post:
      description: |-
        Searches for loyalty accounts in a loyalty program.  

        You can search for a loyalty account using the phone number or customer ID associated with the account. To return all loyalty accounts, specify an empty `query` object or omit it entirely.  

        Search results are sorted by `created_at` in ascending order.
      operationId: SearchLoyaltyAccounts
      security:
        - oauth2:
            - LOYALTY_READ
      summary: SearchLoyaltyAccounts
      tags:
        - Loyalty
      x-oauthpermissions:
        - LOYALTY_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/loyalty/accounts/{account_id}":
    get:
      description: Retrieves a loyalty account.
      operationId: RetrieveLoyaltyAccount
      security:
        - oauth2:
            - LOYALTY_READ
      summary: RetrieveLoyaltyAccount
      tags:
        - Loyalty
      x-oauthpermissions:
        - LOYALTY_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/loyalty/accounts/{account_id}/accumulate":
    post:
      description: |-
        Adds points to a loyalty account.

        - If you are using the Orders API to manage orders, you only provide the `order_id`. 
        The endpoint reads the order to compute points to add to the buyer's account.
        - If you are not using the Orders API to manage orders, 
        you first perform a client-side computation to compute the points.  
        For spend-based and visit-based programs, you can first call 
        [CalculateLoyaltyPoints](https://developer.squareup.com/reference/square_2021-08-18/loyalty-api/calculate-loyalty-points) to compute the points  
        that you provide to this endpoint. 

        __Note:__ The country of the seller's Square account determines whether tax is included in the purchase amount when accruing points for spend-based and visit-based programs. 
        For more information, see [Availability of Square Loyalty](https://developer.squareup.com/docs/loyalty-api/overview#loyalty-market-availability).
      operationId: AccumulateLoyaltyPoints
      security:
        - oauth2:
            - LOYALTY_WRITE
      summary: AccumulateLoyaltyPoints
      tags:
        - Loyalty
      x-oauthpermissions:
        - LOYALTY_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/loyalty/accounts/{account_id}/adjust":
    post:
      description: |-
        Adds points to or subtracts points from a buyer's account. 

        Use this endpoint only when you need to manually adjust points. Otherwise, in your application flow, you call 
        [AccumulateLoyaltyPoints](https://developer.squareup.com/reference/square_2021-08-18/loyalty-api/accumulate-loyalty-points) 
        to add points when a buyer pays for the purchase.
      operationId: AdjustLoyaltyPoints
      security:
        - oauth2:
            - LOYALTY_WRITE
      summary: AdjustLoyaltyPoints
      tags:
        - Loyalty
      x-oauthpermissions:
        - LOYALTY_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/loyalty/events/search:
    post:
      description: |-
        Searches for loyalty events.

        A Square loyalty program maintains a ledger of events that occur during the lifetime of a 
        buyer's loyalty account. Each change in the point balance 
        (for example, points earned, points redeemed, and points expired) is 
        recorded in the ledger. Using this endpoint, you can search the ledger for events.

        Search results are sorted by `created_at` in descending order.
      operationId: SearchLoyaltyEvents
      security:
        - oauth2:
            - LOYALTY_READ
      summary: SearchLoyaltyEvents
      tags:
        - Loyalty
      x-oauthpermissions:
        - LOYALTY_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/loyalty/programs:
    get:
      description: |-
        Returns a list of loyalty programs in the seller's account.
        Loyalty programs define how buyers can earn points and redeem points for rewards. Square sellers can have only one loyalty program, which is created and managed from the Seller Dashboard. For more information, see [Loyalty Program Overview](https://developer.squareup.com/docs/loyalty/overview).


        Replaced with [RetrieveLoyaltyProgram](https://developer.squareup.com/reference/square_2021-08-18/loyalty-api/retrieve-loyalty-program) when used with the keyword `main`.
      operationId: ListLoyaltyPrograms
      security:
        - oauth2:
            - LOYALTY_READ
      summary: ListLoyaltyPrograms
      tags:
        - Loyalty
      x-is-deprecated: true
      x-oauthpermissions:
        - LOYALTY_READ
      x-release-status: DEPRECATED
      x-sq-version: 2021-08-18
  "/v2/loyalty/programs/{program_id}":
    get:
      description: |-
        Retrieves the loyalty program in a seller's account, specified by the program ID or the keyword `main`. 

        Loyalty programs define how buyers can earn points and redeem points for rewards. Square sellers can have only one loyalty program, which is created and managed from the Seller Dashboard. For more information, see [Loyalty Program Overview](https://developer.squareup.com/docs/loyalty/overview).
      operationId: RetrieveLoyaltyProgram
      security:
        - oauth2:
            - LOYALTY_READ
      summary: RetrieveLoyaltyProgram
      tags:
        - Loyalty
      x-oauthpermissions:
        - LOYALTY_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/loyalty/programs/{program_id}/calculate":
    post:
      description: |-
        Calculates the points a purchase earns.

        - If you are using the Orders API to manage orders, you provide `order_id` in the request. The 
        endpoint calculates the points by reading the order.
        - If you are not using the Orders API to manage orders, you provide the purchase amount in 
        the request for the endpoint to calculate the points.

        An application might call this endpoint to show the points that a buyer can earn with the 
        specific purchase.

        __Note:__ The country of the seller's Square account determines whether tax is included in the purchase amount when accruing points for spend-based and visit-based programs. 
        For more information, see [Availability of Square Loyalty](https://developer.squareup.com/docs/loyalty-api/overview#loyalty-market-availability).
      operationId: CalculateLoyaltyPoints
      security:
        - oauth2:
            - LOYALTY_READ
      summary: CalculateLoyaltyPoints
      tags:
        - Loyalty
      x-oauthpermissions:
        - LOYALTY_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/loyalty/rewards:
    post:
      description: |-
        Creates a loyalty reward. In the process, the endpoint does following:

        - Uses the `reward_tier_id` in the request to determine the number of points 
        to lock for this reward. 
        - If the request includes `order_id`, it adds the reward and related discount to the order. 

        After a reward is created, the points are locked and 
        not available for the buyer to redeem another reward.
      operationId: CreateLoyaltyReward
      security:
        - oauth2:
            - LOYALTY_WRITE
      summary: CreateLoyaltyReward
      tags:
        - Loyalty
      x-oauthpermissions:
        - LOYALTY_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/loyalty/rewards/search:
    post:
      description: |-
        Searches for loyalty rewards in a loyalty account. 

        In the current implementation, the endpoint supports search by the reward `status`.

        If you know a reward ID, use the 
        [RetrieveLoyaltyReward](https://developer.squareup.com/reference/square_2021-08-18/loyalty-api/retrieve-loyalty-reward) endpoint.

        Search results are sorted by `updated_at` in descending order.
      operationId: SearchLoyaltyRewards
      security:
        - oauth2:
            - LOYALTY_READ
      summary: SearchLoyaltyRewards
      tags:
        - Loyalty
      x-oauthpermissions:
        - LOYALTY_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/loyalty/rewards/{reward_id}":
    delete:
      description: |-
        Deletes a loyalty reward by doing the following:

        - Returns the loyalty points back to the loyalty account.
        - If an order ID was specified when the reward was created 
        (see [CreateLoyaltyReward](https://developer.squareup.com/reference/square_2021-08-18/loyalty-api/create-loyalty-reward)), 
        it updates the order by removing the reward and related 
        discounts.

        You cannot delete a reward that has reached the terminal state (REDEEMED).
      operationId: DeleteLoyaltyReward
      security:
        - oauth2:
            - LOYALTY_WRITE
      summary: DeleteLoyaltyReward
      tags:
        - Loyalty
      x-oauthpermissions:
        - LOYALTY_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    get:
      description: Retrieves a loyalty reward.
      operationId: RetrieveLoyaltyReward
      security:
        - oauth2:
            - LOYALTY_READ
      summary: RetrieveLoyaltyReward
      tags:
        - Loyalty
      x-oauthpermissions:
        - LOYALTY_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/loyalty/rewards/{reward_id}/redeem":
    post:
      description: |-
        Redeems a loyalty reward.

        The endpoint sets the reward to the `REDEEMED` terminal state. 

        If you are using your own order processing system (not using the 
        Orders API), you call this endpoint after the buyer paid for the 
        purchase.

        After the reward reaches the terminal state, it cannot be deleted. 
        In other words, points used for the reward cannot be returned 
        to the account.
      operationId: RedeemLoyaltyReward
      security:
        - oauth2:
            - LOYALTY_WRITE
      summary: RedeemLoyaltyReward
      tags:
        - Loyalty
      x-oauthpermissions:
        - LOYALTY_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/merchants:
    get:
      description: |-
        Returns `Merchant` information for a given access token.

        If you don't know a `Merchant` ID, you can use this endpoint to retrieve the merchant ID for an access token.
        You can specify your personal access token to get your own merchant information or specify an OAuth token
        to get the information for the  merchant that granted you access.

        If you know the merchant ID, you can also use the [RetrieveMerchant](https://developer.squareup.com/reference/square_2021-08-18/merchants-api/retrieve-merchant)
        endpoint to get the merchant information.
      operationId: ListMerchants
      security:
        - oauth2:
            - MERCHANT_PROFILE_READ
      summary: ListMerchants
      tags:
        - Merchants
      x-oauthpermissions:
        - MERCHANT_PROFILE_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/merchants/{merchant_id}":
    get:
      description: Retrieve a `Merchant` object for the given `merchant_id`.
      operationId: RetrieveMerchant
      security:
        - oauth2:
            - MERCHANT_PROFILE_READ
      summary: RetrieveMerchant
      tags:
        - Merchants
      x-oauthpermissions:
        - MERCHANT_PROFILE_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/orders:
    post:
      description: |-
        Creates a new [order](https://developer.squareup.com/reference/square_2021-08-18/objects/Order) that can include information about products for
        purchase and settings to apply to the purchase.

        To pay for a created order, see 
        [Pay for Orders](https://developer.squareup.com/docs/orders-api/pay-for-orders).

        You can modify open orders using the [UpdateOrder](https://developer.squareup.com/reference/square_2021-08-18/orders-api/update-order) endpoint.
      operationId: CreateOrder
      security:
        - oauth2:
            - ORDERS_WRITE
      summary: CreateOrder
      tags:
        - Orders
      x-oauthpermissions:
        - ORDERS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/orders/batch-retrieve:
    post:
      description: |-
        Retrieves a set of [orders](https://developer.squareup.com/reference/square_2021-08-18/objects/Order) by their IDs.

        If a given order ID does not exist, the ID is ignored instead of generating an error.
      operationId: BatchRetrieveOrders
      security:
        - oauth2:
            - ORDERS_READ
      summary: BatchRetrieveOrders
      tags:
        - Orders
      x-oauthpermissions:
        - ORDERS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/orders/calculate:
    post:
      description: Enables applications to preview order pricing without creating an order.
      operationId: CalculateOrder
      security:
        - oauth2: []
      summary: CalculateOrder
      tags:
        - Orders
      x-is-beta: true
      x-oauthpermissions: []
      x-release-status: BETA
      x-sq-version: 2021-08-18
  /v2/orders/search:
    post:
      description: |-
        Search all orders for one or more locations. Orders include all sales,
        returns, and exchanges regardless of how or when they entered the Square
        ecosystem (such as Point of Sale, Invoices, and Connect APIs).

        `SearchOrders` requests need to specify which locations to search and define a
        [SearchOrdersQuery](https://developer.squareup.com/reference/square_2021-08-18/objects/SearchOrdersQuery) object that controls
        how to sort or filter the results. Your `SearchOrdersQuery` can:

          Set filter criteria.
          Set the sort order.
          Determine whether to return results as complete `Order` objects or as
        [OrderEntry](https://developer.squareup.com/reference/square_2021-08-18/objects/OrderEntry) objects.

        Note that details for orders processed with Square Point of Sale while in
        offline mode might not be transmitted to Square for up to 72 hours. Offline
        orders have a `created_at` value that reflects the time the order was created,
        not the time it was subsequently transmitted to Square.
      operationId: SearchOrders
      security:
        - oauth2:
            - ORDERS_READ
      summary: SearchOrders
      tags:
        - Orders
      x-oauthpermissions:
        - ORDERS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/orders/{order_id}":
    get:
      description: Retrieves an [Order](https://developer.squareup.com/reference/square_2021-08-18/objects/Order) by ID.
      security:
        - oauth2:
            - ORDERS_READ
      summary: RetrieveOrder
      tags:
        - Orders
      x-oauthpermissions:
        - ORDERS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    put:
      description: |-
        Updates an open [order](https://developer.squareup.com/reference/square_2021-08-18/objects/Order) by adding, replacing, or deleting
        fields. Orders with a `COMPLETED` or `CANCELED` state cannot be updated.

        An `UpdateOrder` request requires the following:

        - The `order_id` in the endpoint path, identifying the order to update.
        - The latest `version` of the order to update.
        - The [sparse order](https://developer.squareup.com/docs/orders-api/manage-orders#sparse-order-objects)
        containing only the fields to update and the version to which the update is
        being applied.
        - If deleting fields, the [dot notation paths](https://developer.squareup.com/docs/orders-api/manage-orders#on-dot-notation)
        identifying the fields to clear.

        To pay for an order, see 
        [Pay for Orders](https://developer.squareup.com/docs/orders-api/pay-for-orders).
      security:
        - oauth2:
            - ORDERS_WRITE
      summary: UpdateOrder
      tags:
        - Orders
      x-is-beta: true
      x-oauthpermissions:
        - ORDERS_WRITE
      x-release-status: BETA
      x-sq-version: 2021-08-18
  "/v2/orders/{order_id}/pay":
    post:
      description: |-
        Pay for an [order](https://developer.squareup.com/reference/square_2021-08-18/objects/Order) using one or more approved [payments](https://developer.squareup.com/reference/square_2021-08-18/objects/Payment)
        or settle an order with a total of `0`.

        The total of the `payment_ids` listed in the request must be equal to the order
        total. Orders with a total amount of `0` can be marked as paid by specifying an empty
        array of `payment_ids` in the request.

        To be used with `PayOrder`, a payment must:

        - Reference the order by specifying the `order_id` when [creating the payment](https://developer.squareup.com/reference/square_2021-08-18/payments-api/create-payment).
        Any approved payments that reference the same `order_id` not specified in the
        `payment_ids` is canceled.
        - Be approved with [delayed capture](https://developer.squareup.com/docs/payments-api/take-payments#delayed-capture).
        Using a delayed capture payment with `PayOrder` completes the approved payment.
      operationId: PayOrder
      security:
        - oauth2:
            - PAYMENTS_WRITE
            - ORDERS_WRITE
      summary: PayOrder
      tags:
        - Orders
      x-is-beta: true
      x-oauthpermissions:
        - PAYMENTS_WRITE
        - ORDERS_WRITE
      x-release-status: BETA
      x-sq-version: 2021-08-18
  /v2/payments:
    get:
      description: |-
        Retrieves a list of payments taken by the account making the request.

        Results are eventually consistent, and new payments or changes to payments might take several
        seconds to appear.

        The maximum results per page is 100.
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: ListPayments
      tags:
        - Payments
      x-oauthpermissions:
        - PAYMENTS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    post:
      description: |-
        Creates a payment using the provided source. You can use this endpoint 
        to charge a card (credit/debit card or    
        Square gift card) or record a payment that the seller received outside of Square 
        (cash payment from a buyer or a payment that an external entity 
        processed on behalf of the seller).

        The endpoint creates a 
        `Payment` object and returns it in the response.
      operationId: CreatePayment
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: CreatePayment
      tags:
        - Payments
      x-oauthpermissions:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/payments/cancel:
    post:
      description: |-
        Cancels (voids) a payment identified by the idempotency key that is specified in the
        request.

        Use this method when the status of a `CreatePayment` request is unknown (for example, after you send a
        `CreatePayment` request, a network error occurs and you do not get a response). In this case, you can
        direct Square to cancel the payment using this endpoint. In the request, you provide the same
        idempotency key that you provided in your `CreatePayment` request that you want to cancel. After
        canceling the payment, you can submit your `CreatePayment` request again.

        Note that if no payment with the specified idempotency key is found, no action is taken and the endpoint
        returns successfully.
      operationId: CancelPaymentByIdempotencyKey
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: CancelPaymentByIdempotencyKey
      tags:
        - Payments
      x-oauthpermissions:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/payments/{payment_id}":
    get:
      description: Retrieves details for a specific payment.
      operationId: GetPayment
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: GetPayment
      tags:
        - Payments
      x-oauthpermissions:
        - PAYMENTS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    put:
      description: |-
        Updates a payment with the APPROVED status.
        You can update the `amount_money` and `tip_money` using this endpoint.
      operationId: UpdatePayment
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: UpdatePayment
      tags:
        - Payments
      x-oauthpermissions:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/payments/{payment_id}/cancel":
    post:
      description: |-
        Cancels (voids) a payment. You can use this endpoint to cancel a payment with 
        the APPROVED `status`.
      operationId: CancelPayment
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: CancelPayment
      tags:
        - Payments
      x-oauthpermissions:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/payments/{payment_id}/complete":
    post:
      description: |-
        Completes (captures) a payment.
        By default, payments are set to complete immediately after they are created.

        You can use this endpoint to complete a payment with the APPROVED `status`.
      operationId: CompletePayment
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: CompletePayment
      tags:
        - Payments
      x-oauthpermissions:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/refunds:
    get:
      description: |-
        Retrieves a list of refunds for the account making the request.

        Results are eventually consistent, and new refunds or changes to refunds might take several
        seconds to appear.

        The maximum results per page is 100.
      operationId: ListPaymentRefunds
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: ListPaymentRefunds
      tags:
        - Refunds
      x-oauthpermissions:
        - PAYMENTS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    post:
      description: |-
        Refunds a payment. You can refund the entire payment amount or a
        portion of it. You can use this endpoint to refund a card payment or record a 
        refund of a cash or external payment. For more information, see
        [Refund Payment](https://developer.squareup.com/docs/payments-api/refund-payments).
      operationId: RefundPayment
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: RefundPayment
      tags:
        - Refunds
      x-oauthpermissions:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/refunds/{refund_id}":
    get:
      description: Retrieves a specific refund using the `refund_id`.
      operationId: GetPaymentRefund
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: GetPaymentRefund
      tags:
        - Refunds
      x-oauthpermissions:
        - PAYMENTS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/sites:
    get:
      description: |-
        Lists the Square Online sites that belong to a seller.


        __Note:__ Square Online APIs are publicly available as part of an early access program. For more information, see [Early access program for Square Online APIs](https://developer.squareup.com/docs/online-api#early-access-program-for-square-online-apis).
      operationId: ListSites
      security:
        - oauth2:
            - ONLINE_STORE_SITE_READ
      summary: ListSites
      tags:
        - Sites
      x-oauthpermissions:
        - ONLINE_STORE_SITE_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/sites/{site_id}/snippet":
    delete:
      description: |-
        Removes your snippet from a Square Online site.

        You can call [ListSites](https://developer.squareup.com/reference/square_2021-08-18/sites-api/list-sites) to get the IDs of the sites that belong to a seller.


        __Note:__ Square Online APIs are publicly available as part of an early access program. For more information, see [Early access program for Square Online APIs](https://developer.squareup.com/docs/online-api#early-access-program-for-square-online-apis).
      operationId: DeleteSnippet
      security:
        - oauth2:
            - ONLINE_STORE_SNIPPETS_WRITE
      summary: DeleteSnippet
      tags:
        - Snippets
      x-oauthpermissions:
        - ONLINE_STORE_SNIPPETS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    get:
      description: |-
        Retrieves your snippet from a Square Online site. A site can contain snippets from multiple snippet applications, but you can retrieve only the snippet that was added by your application.

        You can call [ListSites](https://developer.squareup.com/reference/square_2021-08-18/sites-api/list-sites) to get the IDs of the sites that belong to a seller.


        __Note:__ Square Online APIs are publicly available as part of an early access program. For more information, see [Early access program for Square Online APIs](https://developer.squareup.com/docs/online-api#early-access-program-for-square-online-apis).
      operationId: RetrieveSnippet
      security:
        - oauth2:
            - ONLINE_STORE_SNIPPETS_READ
      summary: RetrieveSnippet
      tags:
        - Snippets
      x-oauthpermissions:
        - ONLINE_STORE_SNIPPETS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    post:
      description: |-
        Adds a snippet to a Square Online site or updates the existing snippet on the site. 
        The snippet code is appended to the end of the `head` element on every page of the site, except checkout pages. A snippet application can add one snippet to a given site. 

        You can call [ListSites](https://developer.squareup.com/reference/square_2021-08-18/sites-api/list-sites) to get the IDs of the sites that belong to a seller.


        __Note:__ Square Online APIs are publicly available as part of an early access program. For more information, see [Early access program for Square Online APIs](https://developer.squareup.com/docs/online-api#early-access-program-for-square-online-apis).
      operationId: UpsertSnippet
      security:
        - oauth2:
            - ONLINE_STORE_SNIPPETS_WRITE
      summary: UpsertSnippet
      tags:
        - Snippets
      x-oauthpermissions:
        - ONLINE_STORE_SNIPPETS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/subscriptions:
    post:
      description: |-
        Creates a subscription for a customer to a subscription plan.

        If you provide a card on file in the request, Square charges the card for
        the subscription. Otherwise, Square bills an invoice to the customer's email
        address. The subscription starts immediately, unless the request includes
        the optional `start_date`. Each individual subscription is associated with a particular location.
      operationId: CreateSubscription
      security:
        - oauth2:
            - CUSTOMERS_READ
            - PAYMENTS_WRITE
            - SUBSCRIPTIONS_WRITE
            - ITEMS_READ
            - ORDERS_WRITE
            - INVOICES_WRITE
      summary: CreateSubscription
      tags:
        - Subscriptions
      x-oauthpermissions:
        - CUSTOMERS_READ
        - PAYMENTS_WRITE
        - SUBSCRIPTIONS_WRITE
        - ITEMS_READ
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/subscriptions/search:
    post:
      description: |-
        Searches for subscriptions.
        Results are ordered chronologically by subscription creation date. If
        the request specifies more than one location ID,
        the endpoint orders the result
        by location ID, and then by creation date within each location. If no locations are given
        in the query, all locations are searched.

        You can also optionally specify `customer_ids` to search by customer.
        If left unset, all customers
        associated with the specified locations are returned.
        If the request specifies customer IDs, the endpoint orders results
        first by location, within location by customer ID, and within
        customer by subscription creation date.

        For more information, see
        [Retrieve subscriptions](https://developer.squareup.com/docs/subscriptions-api/overview#retrieve-subscriptions).
      operationId: SearchSubscriptions
      security:
        - oauth2:
            - SUBSCRIPTIONS_READ
      summary: SearchSubscriptions
      tags:
        - Subscriptions
      x-oauthpermissions:
        - SUBSCRIPTIONS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/subscriptions/{subscription_id}":
    get:
      description: Retrieves a subscription.
      operationId: RetrieveSubscription
      security:
        - oauth2:
            - SUBSCRIPTIONS_READ
      summary: RetrieveSubscription
      tags:
        - Subscriptions
      x-oauthpermissions:
        - SUBSCRIPTIONS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    put:
      description: |-
        Updates a subscription. You can set, modify, and clear the
        `subscription` field values.
      operationId: UpdateSubscription
      security:
        - oauth2:
            - CUSTOMERS_READ
            - PAYMENTS_WRITE
            - SUBSCRIPTIONS_WRITE
            - ITEMS_READ
            - ORDERS_WRITE
            - INVOICES_WRITE
      summary: UpdateSubscription
      tags:
        - Subscriptions
      x-oauthpermissions:
        - CUSTOMERS_READ
        - PAYMENTS_WRITE
        - SUBSCRIPTIONS_WRITE
        - ITEMS_READ
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/subscriptions/{subscription_id}/cancel":
    post:
      description: |-
        Sets the `canceled_date` field to the end of the active billing period.
        After this date, the status changes from ACTIVE to CANCELED.
      operationId: CancelSubscription
      security:
        - oauth2:
            - SUBSCRIPTIONS_WRITE
      summary: CancelSubscription
      tags:
        - Subscriptions
      x-oauthpermissions:
        - SUBSCRIPTIONS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/subscriptions/{subscription_id}/events":
    get:
      description: |-
        Lists all events for a specific subscription.
        In the current implementation, only `START_SUBSCRIPTION` and `STOP_SUBSCRIPTION` (when the subscription was canceled) events are returned.
      operationId: ListSubscriptionEvents
      security:
        - oauth2:
            - SUBSCRIPTIONS_READ
      summary: ListSubscriptionEvents
      tags:
        - Subscriptions
      x-oauthpermissions:
        - SUBSCRIPTIONS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/subscriptions/{subscription_id}/resume":
    post:
      description: Resumes a deactivated subscription.
      operationId: ResumeSubscription
      security:
        - oauth2:
            - CUSTOMERS_READ
            - PAYMENTS_WRITE
            - SUBSCRIPTIONS_WRITE
            - ITEMS_READ
            - ORDERS_WRITE
            - INVOICES_WRITE
      summary: ResumeSubscription
      tags:
        - Subscriptions
      x-oauthpermissions:
        - CUSTOMERS_READ
        - PAYMENTS_WRITE
        - SUBSCRIPTIONS_WRITE
        - ITEMS_READ
        - ORDERS_WRITE
        - INVOICES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/team-members:
    post:
      description: |-
        Creates a single `TeamMember` object. The `TeamMember` object is returned on successful creates.
        You must provide the following values in your request to this endpoint:
        - `given_name`
        - `family_name`

        Learn about [Troubleshooting the Team API](https://developer.squareup.com/docs/team/troubleshooting#createteammember).
      operationId: CreateTeamMember
      security:
        - oauth2:
            - EMPLOYEES_WRITE
      summary: CreateTeamMember
      tags:
        - Team
      x-oauthpermissions:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/team-members/bulk-create:
    post:
      description: |-
        Creates multiple `TeamMember` objects. The created `TeamMember` objects are returned on successful creates.
        This process is non-transactional and processes as much of the request as possible. If one of the creates in
        the request cannot be successfully processed, the request is not marked as failed, but the body of the response
        contains explicit error information for the failed create.

        Learn about [Troubleshooting the Team API](https://developer.squareup.com/docs/team/troubleshooting#bulk-create-team-members).
      operationId: BulkCreateTeamMembers
      security:
        - oauth2:
            - EMPLOYEES_WRITE
      summary: BulkCreateTeamMembers
      tags:
        - Team
      x-oauthpermissions:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/team-members/bulk-update:
    post:
      description: |-
        Updates multiple `TeamMember` objects. The updated `TeamMember` objects are returned on successful updates.
        This process is non-transactional and processes as much of the request as possible. If one of the updates in
        the request cannot be successfully processed, the request is not marked as failed, but the body of the response
        contains explicit error information for the failed update.
        Learn about [Troubleshooting the Team API](https://developer.squareup.com/docs/team/troubleshooting#bulk-update-team-members).
      operationId: BulkUpdateTeamMembers
      security:
        - oauth2:
            - EMPLOYEES_WRITE
      summary: BulkUpdateTeamMembers
      tags:
        - Team
      x-oauthpermissions:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/team-members/search:
    post:
      description: |-
        Returns a paginated list of `TeamMember` objects for a business.
        The list can be filtered by the following:
        - location IDs
        - `status`
      operationId: SearchTeamMembers
      security:
        - oauth2:
            - EMPLOYEES_READ
      summary: SearchTeamMembers
      tags:
        - Team
      x-oauthpermissions:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/team-members/{team_member_id}":
    get:
      description: |-
        Retrieves a `TeamMember` object for the given `TeamMember.id`.
        Learn about [Troubleshooting the Team API](https://developer.squareup.com/docs/team/troubleshooting#retrieve-a-team-member).
      operationId: RetrieveTeamMember
      security:
        - oauth2:
            - EMPLOYEES_READ
      summary: RetrieveTeamMember
      tags:
        - Team
      x-oauthpermissions:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    put:
      description: |-
        Updates a single `TeamMember` object. The `TeamMember` object is returned on successful updates.
        Learn about [Troubleshooting the Team API](https://developer.squareup.com/docs/team/troubleshooting#update-a-team-member).
      operationId: UpdateTeamMember
      security:
        - oauth2:
            - EMPLOYEES_WRITE
      summary: UpdateTeamMember
      tags:
        - Team
      x-oauthpermissions:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/team-members/{team_member_id}/wage-setting":
    get:
      description: |-
        Retrieves a `WageSetting` object for a team member specified
        by `TeamMember.id`.
        Learn about [Troubleshooting the Team API](https://developer.squareup.com/docs/team/troubleshooting#retrievewagesetting).
      operationId: RetrieveWageSetting
      security:
        - oauth2:
            - EMPLOYEES_READ
      summary: RetrieveWageSetting
      tags:
        - Team
      x-oauthpermissions:
        - EMPLOYEES_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
    put:
      description: |-
        Creates or updates a `WageSetting` object. The object is created if a
        `WageSetting` with the specified `team_member_id` does not exist. Otherwise,
        it fully replaces the `WageSetting` object for the team member.
        The `WageSetting` is returned on a successful update.
        Learn about [Troubleshooting the Team API](https://developer.squareup.com/docs/team/troubleshooting#create-or-update-a-wage-setting).
      operationId: UpdateWageSetting
      security:
        - oauth2:
            - EMPLOYEES_WRITE
      summary: UpdateWageSetting
      tags:
        - Team
      x-oauthpermissions:
        - EMPLOYEES_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/terminals/checkouts:
    post:
      description: |-
        Creates a Terminal checkout request and sends it to the specified device to take a payment
        for the requested amount.
      operationId: CreateTerminalCheckout
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: CreateTerminalCheckout
      tags:
        - Terminal
      x-oauthpermissions:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/terminals/checkouts/search:
    post:
      description: Retrieves a filtered list of Terminal checkout requests created by the account making the request.
      operationId: SearchTerminalCheckouts
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: SearchTerminalCheckouts
      tags:
        - Terminal
      x-oauthpermissions:
        - PAYMENTS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/terminals/checkouts/{checkout_id}":
    get:
      description: Retrieves a Terminal checkout request by `checkout_id`.
      operationId: GetTerminalCheckout
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: GetTerminalCheckout
      tags:
        - Terminal
      x-oauthpermissions:
        - PAYMENTS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/terminals/checkouts/{checkout_id}/cancel":
    post:
      description: Cancels a Terminal checkout request if the status of the request permits it.
      operationId: CancelTerminalCheckout
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: CancelTerminalCheckout
      tags:
        - Terminal
      x-oauthpermissions:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/terminals/refunds:
    post:
      description: Creates a request to refund an Interac payment completed on a Square Terminal.
      operationId: CreateTerminalRefund
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: CreateTerminalRefund
      tags:
        - Terminal
      x-oauthpermissions:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  /v2/terminals/refunds/search:
    post:
      description: Retrieves a filtered list of Interac Terminal refund requests created by the seller making the request.
      operationId: SearchTerminalRefunds
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: SearchTerminalRefunds
      tags:
        - Terminal
      x-oauthpermissions:
        - PAYMENTS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/terminals/refunds/{terminal_refund_id}":
    get:
      description: Retrieves an Interac Terminal refund object by ID.
      operationId: GetTerminalRefund
      security:
        - oauth2:
            - PAYMENTS_READ
      summary: GetTerminalRefund
      tags:
        - Terminal
      x-oauthpermissions:
        - PAYMENTS_READ
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
  "/v2/terminals/refunds/{terminal_refund_id}/cancel":
    post:
      description: Cancels an Interac Terminal refund request by refund request ID if the status of the request permits it.
      operationId: CancelTerminalRefund
      security:
        - oauth2:
            - PAYMENTS_WRITE
      summary: CancelTerminalRefund
      tags:
        - Terminal
      x-oauthpermissions:
        - PAYMENTS_WRITE
      x-release-status: PUBLIC
      x-sq-version: 2021-08-18
components:
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://connect.squareup.com/oauth2/authorize
          scopes:
            APPOINTMENTS_BUSINESS_SETTINGS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to booking business settings. For example, to call the
              ListTeamMemberBookingProfiles endpoint.
            APPOINTMENTS_READ: |-
              __HTTP Method__: `GET`, `POST`

              Grants read access to booking information. For example, to call the
              RetrieveBooking endpoint.
            APPOINTMENTS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to booking information. For example, to call the CreateBooking endpoint.
            BANK_ACCOUNTS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to bank account information associated with the targeted
              Square account. For example, to call the Connect v1 ListBankAccounts endpoint.
            CASH_DRAWER_READ: |-
              __HTTP Method__: `GET`

              Grants read access to cash drawer shift information. For example, to call the
              ListCashDrawerShifts endpoint.
            CUSTOMERS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to customer information. For example, to call the
              ListCustomers endpoint.
            CUSTOMERS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to customer information. For example, to create and update
              customer profiles.
            DEVICE_CREDENTIAL_MANAGEMENT: |-
              __HTTP Method__: `POST`, `GET`

              Grants read/write access to device credentials information. For example, to
              call the CreateDeviceCode endpoint.
            DISPUTES_READ: |-
              __HTTP Method__: `GET`

              Grants read access to dispute information. For example, to call the RetrieveDispute
              endpoint.
            DISPUTES_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to dispute information. For example, to call the SubmitEvidence
              endpoint.
            EMPLOYEES_READ: |-
              __HTTP Method__: `GET`

              Grants read access to employee profile information. For example, to call the
              Connect v1 Employees API.
            EMPLOYEES_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to employee profile information. For example, to create
              and modify employee profiles.
            GIFTCARDS_READ: |-
              __HTTP Method__: `GET`, `POST`

              Grants read access to gift card information. For example, to call the RetrieveGiftCard
              endpoint.
            GIFTCARDS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to gift card information. For example, to call the CreateGiftCard
              endpoint.
            INVENTORY_READ: |-
              __HTTP Method__: `GET`

              Grants read access to inventory information. For example, to call the
              RetrieveInventoryCount endpoint.
            INVENTORY_WRITE: |-
              __HTTP Method__:  `POST`, `PUT`, `DELETE`

              Grants write access to inventory information. For example, to call the
              BatchChangeInventory endpoint.
            INVOICES_READ: |-
              __HTTP Method__: `GET`, `POST`

              Grants read access to invoice information. For example, to call the ListInvoices endpoint.
            INVOICES_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to invoice information. For example, to call the CreateInvoice endpoint.
            ITEMS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to business and location information. For example, to
              obtain a location ID for subsequent activity.
            ITEMS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to product catalog information. For example, to modify or
              add to a product catalog.
            LOYALTY_READ: |-
              __HTTP Method__: `GET`

              Grants read access to loyalty information. For example, to call the
              ListLoyaltyPrograms endpoint.
            LOYALTY_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to loyalty information. For example, to call the
              CreateLoyaltyAccount endpoint.
            MERCHANT_PROFILE_READ: |-
              __HTTP Method__: `GET`

              Grants read access to business and location information. For example, to
              obtain a location ID for subsequent activity.
            MERCHANT_PROFILE_WRITE: "*Originally missing*"
            ONLINE_STORE_SITE_READ: |-
              __HTTP Method__: `GET`, `POST`

              Read access to ECOM online store site details.
            ONLINE_STORE_SNIPPETS_READ: |-
              __HTTP Method__: `GET`, `POST`

              Read access to ECOM online store snippets on published websites.
            ONLINE_STORE_SNIPPETS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Write access to ECOM online store snippets on published websites.
            ORDERS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to order information. For example, to call the
              BatchRetrieveOrders endpoint.
            ORDERS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to order information. For example, to call the
              CreateCheckout endpoint.
            PAYMENTS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to transaction and refund information. For example, to call
              the RetrieveTransaction endpoint.
            PAYMENTS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to transaction and refunds information. For example, to
              process payments with the Payments or Checkout API.
            PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Allow third party applications to deduct a portion of each transaction amount.
              __Required__ to use multiparty transaction functionality with the Payments
              API.
            PAYMENTS_WRITE_IN_PERSON: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to payments and refunds information. For example, to
              process in-person payments.
            PAYMENTS_WRITE_SHARED_ONFILE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Allows the developer to process payments on behalf of a seller using a shared on file payment method.
            SETTLEMENTS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to settlement (deposit) information. For example, to call
              the Connect v1 ListSettlements endpoint.
            SUBSCRIPTIONS_READ: |-
              __HTTP Method__: `GET`, `POST`

              Grants read access to subscription information. For example, to call the RetrieveSubscription
              endpoint.
            SUBSCRIPTIONS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to subscription information. For example, to call the CreateSubscription
              endpoint.
            TIMECARDS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to employee timecard information. For example, to call the
              Connect v2 SearchShifts endpoint.
            TIMECARDS_SETTINGS_READ: |-
              __HTTP Method__: `GET`

              Grants read access to employee timecard settings information. For example, to
              call the GetBreakType endpoint.
            TIMECARDS_SETTINGS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to employee timecard settings information. For example, to
              call the UpdateBreakType endpoint.
            TIMECARDS_WRITE: |-
              __HTTP Method__: `POST`, `PUT`, `DELETE`

              Grants write access to employee shift information. For example, to create
              and modify employee shifts.
          tokenUrl: https://connect.squareup.com/oauth2/token
      type: oauth2
    oauth2ClientSecret:
      in: header
      name: Authorization
      type: apiKey
