swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /blogger/v3
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: API for access to the data within Blogger.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Blogger
  version: v3
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-apisguru-categories:
    - social
  x-logo:
    url: 'https://www.gstatic.com/images/icons/material/product/2x/blogger_64dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/blogger/v3/rest'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: blogger
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/blogger': Manage your Blogger account
      'https://www.googleapis.com/auth/blogger.readonly': View your Blogger account
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/blogger': Manage your Blogger account
      'https://www.googleapis.com/auth/blogger.readonly': View your Blogger account
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: blogUserInfos
  - name: blogs
  - name: comments
  - name: pageViews
  - name: pages
  - name: postUserInfos
  - name: posts
  - name: users
paths:
  /blogs/byurl:
    get:
      description: Retrieve a Blog by URL.
      operationId: blogger.blogs.getByUrl
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger.readonly'
      tags:
        - blogs
  '/blogs/{blogId}':
    get:
      description: Gets one blog by ID.
      operationId: blogger.blogs.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger.readonly'
      tags:
        - blogs
  '/blogs/{blogId}/comments':
    get:
      description: 'Retrieves the comments for a blog, across all posts, possibly filtered.'
      operationId: blogger.comments.listByBlog
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger.readonly'
      tags:
        - comments
  '/blogs/{blogId}/pages':
    get:
      description: 'Retrieves the pages for a blog, optionally including non-LIVE statuses.'
      operationId: blogger.pages.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger.readonly'
      tags:
        - pages
    post:
      description: Add a page.
      operationId: blogger.pages.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
      tags:
        - pages
  '/blogs/{blogId}/pages/{pageId}':
    delete:
      description: Delete a page by ID.
      operationId: blogger.pages.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
      tags:
        - pages
    get:
      description: Gets one blog page by ID.
      operationId: blogger.pages.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger.readonly'
      tags:
        - pages
    patch:
      description: Update a page. This method supports patch semantics.
      operationId: blogger.pages.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
      tags:
        - pages
    put:
      description: Update a page.
      operationId: blogger.pages.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
      tags:
        - pages
  '/blogs/{blogId}/pages/{pageId}/publish':
    post:
      description: Publishes a draft page.
      operationId: blogger.pages.publish
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
      tags:
        - pages
  '/blogs/{blogId}/pages/{pageId}/revert':
    post:
      description: Revert a published or scheduled page to draft state.
      operationId: blogger.pages.revert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
      tags:
        - pages
  '/blogs/{blogId}/pageviews':
    get:
      description: Retrieve pageview stats for a Blog.
      operationId: blogger.pageViews.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
      tags:
        - pageViews
  '/blogs/{blogId}/posts':
    get:
      description: 'Retrieves a list of posts, possibly filtered.'
      operationId: blogger.posts.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger.readonly'
      tags:
        - posts
    post:
      description: Add a post.
      operationId: blogger.posts.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
      tags:
        - posts
  '/blogs/{blogId}/posts/bypath':
    get:
      description: Retrieve a Post by Path.
      operationId: blogger.posts.getByPath
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger.readonly'
      tags:
        - posts
  '/blogs/{blogId}/posts/search':
    get:
      description: Search for a post.
      operationId: blogger.posts.search
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger.readonly'
      tags:
        - posts
  '/blogs/{blogId}/posts/{postId}':
    delete:
      description: Delete a post by ID.
      operationId: blogger.posts.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
      tags:
        - posts
    get:
      description: Get a post by ID.
      operationId: blogger.posts.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger.readonly'
      tags:
        - posts
    patch:
      description: Update a post. This method supports patch semantics.
      operationId: blogger.posts.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
      tags:
        - posts
    put:
      description: Update a post.
      operationId: blogger.posts.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
      tags:
        - posts
  '/blogs/{blogId}/posts/{postId}/comments':
    get:
      description: 'Retrieves the comments for a post, possibly filtered.'
      operationId: blogger.comments.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger.readonly'
      tags:
        - comments
  '/blogs/{blogId}/posts/{postId}/comments/{commentId}':
    delete:
      description: Delete a comment by ID.
      operationId: blogger.comments.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
      tags:
        - comments
    get:
      description: Gets one comment by ID.
      operationId: blogger.comments.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger.readonly'
      tags:
        - comments
  '/blogs/{blogId}/posts/{postId}/comments/{commentId}/approve':
    post:
      description: Marks a comment as not spam.
      operationId: blogger.comments.approve
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
      tags:
        - comments
  '/blogs/{blogId}/posts/{postId}/comments/{commentId}/removecontent':
    post:
      description: Removes the content of a comment.
      operationId: blogger.comments.removeContent
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
      tags:
        - comments
  '/blogs/{blogId}/posts/{postId}/comments/{commentId}/spam':
    post:
      description: Marks a comment as spam.
      operationId: blogger.comments.markAsSpam
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
      tags:
        - comments
  '/blogs/{blogId}/posts/{postId}/publish':
    post:
      description: 'Publishes a draft post, optionally at the specific time of the given publishDate parameter.'
      operationId: blogger.posts.publish
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
      tags:
        - posts
  '/blogs/{blogId}/posts/{postId}/revert':
    post:
      description: Revert a published or scheduled post to draft state.
      operationId: blogger.posts.revert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
      tags:
        - posts
  '/users/{userId}':
    get:
      description: Gets one user by ID.
      operationId: blogger.users.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger.readonly'
      tags:
        - users
  '/users/{userId}/blogs':
    get:
      description: 'Retrieves a list of blogs, possibly filtered.'
      operationId: blogger.blogs.listByUser
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger.readonly'
      tags:
        - blogs
  '/users/{userId}/blogs/{blogId}':
    get:
      description: Gets one blog and user info pair by blogId and userId.
      operationId: blogger.blogUserInfos.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger.readonly'
      tags:
        - blogUserInfos
  '/users/{userId}/blogs/{blogId}/posts':
    get:
      description: 'Retrieves a list of post and post user info pairs, possibly filtered. The post user info contains per-user information about the post, such as access rights, specific to the user.'
      operationId: blogger.postUserInfos.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger.readonly'
      tags:
        - postUserInfos
  '/users/{userId}/blogs/{blogId}/posts/{postId}':
    get:
      description: 'Gets one post and user info pair, by post ID and user ID. The post user info contains per-user information about the post, such as access rights, specific to the user.'
      operationId: blogger.postUserInfos.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger'
        - Oauth2:
            - 'https://www.googleapis.com/auth/blogger.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/blogger.readonly'
      tags:
        - postUserInfos