package shared

type GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestParticipantRoleEnum string

const (
	GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestParticipantRoleEnumRoleUnspecified GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestParticipantRoleEnum = "ROLE_UNSPECIFIED"
	GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestParticipantRoleEnumHumanAgent      GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestParticipantRoleEnum = "HUMAN_AGENT"
	GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestParticipantRoleEnumAutomatedAgent  GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestParticipantRoleEnum = "AUTOMATED_AGENT"
	GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestParticipantRoleEnumEndUser         GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestParticipantRoleEnum = "END_USER"
)

type GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnum string

const (
	GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnumTypeUnspecified           GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnum = "TYPE_UNSPECIFIED"
	GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnumArticleSuggestion         GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnum = "ARTICLE_SUGGESTION"
	GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnumFaq                       GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnum = "FAQ"
	GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnumSmartReply                GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnum = "SMART_REPLY"
	GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnumConversationSummarization GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnum = "CONVERSATION_SUMMARIZATION"
)

// GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequest
// The request message for ConversationProfiles.ClearFeature.
type GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequest struct {
	ParticipantRole       *GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestParticipantRoleEnum       `json:"participantRole,omitempty"`
	SuggestionFeatureType *GoogleCloudDialogflowV2beta1ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnum `json:"suggestionFeatureType,omitempty"`
}
