package shared




type InteractionEnumResourceStatusEnum string

const (
    InteractionEnumResourceStatusEnumAccepted InteractionEnumResourceStatusEnum = "accepted"
InteractionEnumResourceStatusEnumAnswered InteractionEnumResourceStatusEnum = "answered"
InteractionEnumResourceStatusEnumBusy InteractionEnumResourceStatusEnum = "busy"
InteractionEnumResourceStatusEnumCanceled InteractionEnumResourceStatusEnum = "canceled"
InteractionEnumResourceStatusEnumCompleted InteractionEnumResourceStatusEnum = "completed"
InteractionEnumResourceStatusEnumDeleted InteractionEnumResourceStatusEnum = "deleted"
InteractionEnumResourceStatusEnumDelivered InteractionEnumResourceStatusEnum = "delivered"
InteractionEnumResourceStatusEnumDeliveryUnknown InteractionEnumResourceStatusEnum = "delivery-unknown"
InteractionEnumResourceStatusEnumFailed InteractionEnumResourceStatusEnum = "failed"
InteractionEnumResourceStatusEnumInProgress InteractionEnumResourceStatusEnum = "in-progress"
InteractionEnumResourceStatusEnumInitiated InteractionEnumResourceStatusEnum = "initiated"
InteractionEnumResourceStatusEnumNoAnswer InteractionEnumResourceStatusEnum = "no-answer"
InteractionEnumResourceStatusEnumQueued InteractionEnumResourceStatusEnum = "queued"
InteractionEnumResourceStatusEnumReceived InteractionEnumResourceStatusEnum = "received"
InteractionEnumResourceStatusEnumReceiving InteractionEnumResourceStatusEnum = "receiving"
InteractionEnumResourceStatusEnumRinging InteractionEnumResourceStatusEnum = "ringing"
InteractionEnumResourceStatusEnumScheduled InteractionEnumResourceStatusEnum = "scheduled"
InteractionEnumResourceStatusEnumSending InteractionEnumResourceStatusEnum = "sending"
InteractionEnumResourceStatusEnumSent InteractionEnumResourceStatusEnum = "sent"
InteractionEnumResourceStatusEnumUndelivered InteractionEnumResourceStatusEnum = "undelivered"
InteractionEnumResourceStatusEnumUnknown InteractionEnumResourceStatusEnum = "unknown"
)


