# coding: utf-8

"""
    LogicManagementClient

    REST API for Azure Logic Apps.

    The version of the OpenAPI document: 2018-07-01-preview
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.workflow_version import WorkflowVersion

class TestWorkflowVersion(unittest.TestCase):
    """WorkflowVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowVersion:
        """Test WorkflowVersion
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowVersion`
        """
        model = WorkflowVersion()
        if include_optional:
            return WorkflowVersion(
                properties = openapi_client.models.workflow_version_properties.WorkflowVersionProperties(
                    access_endpoint = '', 
                    changed_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    definition = openapi_client.models.object.Object(), 
                    integration_account = openapi_client.models.resource_reference.ResourceReference(
                        id = '', 
                        name = '', 
                        type = '', ), 
                    parameters = {
                        'key' : openapi_client.models.workflow_parameter.WorkflowParameter(
                            description = '', 
                            metadata = openapi_client.models.object.Object(), 
                            type = 'NotSpecified', 
                            value = openapi_client.models.object.Object(), )
                        }, 
                    sku = openapi_client.models.sku.Sku(
                        name = 'NotSpecified', 
                        plan = openapi_client.models.resource_reference.ResourceReference(
                            id = '', ), ), 
                    state = 'NotSpecified', 
                    version = '', ),
                id = '',
                location = '',
                name = '',
                tags = {
                    'key' : ''
                    },
                type = ''
            )
        else:
            return WorkflowVersion(
        )
        """

    def testWorkflowVersion(self):
        """Test WorkflowVersion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
