# coding: utf-8

"""
    LogicManagementClient

    REST API for Azure Logic Apps.

    The version of the OpenAPI document: 2018-07-01-preview
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.workflow_trigger_histories_api import WorkflowTriggerHistoriesApi


class TestWorkflowTriggerHistoriesApi(unittest.TestCase):
    """WorkflowTriggerHistoriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkflowTriggerHistoriesApi()

    def tearDown(self) -> None:
        pass

    def test_workflow_trigger_histories_get(self) -> None:
        """Test case for workflow_trigger_histories_get

        """
        pass

    def test_workflow_trigger_histories_list(self) -> None:
        """Test case for workflow_trigger_histories_list

        """
        pass

    def test_workflow_trigger_histories_resubmit(self) -> None:
        """Test case for workflow_trigger_histories_resubmit

        """
        pass


if __name__ == '__main__':
    unittest.main()
