from .get_addpermission import *
from .get_changemessagevisibility import *
from .get_createqueue import *
from .get_deletemessage import *
from .get_deletequeue import *
from .get_getqueueattributes import *
from .get_getqueueurl import *
from .get_listdeadlettersourcequeues import *
from .get_listqueues import *
from .get_listqueuetags import *
from .get_purgequeue import *
from .get_receivemessage import *
from .get_removepermission import *
from .get_setqueueattributes import *
from .get_tagqueue import *
from .get_untagqueue import *
from .post_addpermission import *
from .post_changemessagevisibility import *
from .post_changemessagevisibilitybatch import *
from .post_createqueue import *
from .post_deletemessage import *
from .post_deletemessagebatch import *
from .post_deletequeue import *
from .post_getqueueattributes import *
from .post_getqueueurl import *
from .post_listdeadlettersourcequeues import *
from .post_listqueues import *
from .post_listqueuetags import *
from .post_purgequeue import *
from .post_receivemessage import *
from .post_removepermission import *
from .post_sendmessage import *
from .post_sendmessagebatch import *
from .post_setqueueattributes import *
from .post_tagqueue import *
from .post_untagqueue import *
