# coding: utf-8

"""
    NetworkManagementClient

    The Microsoft Azure Network management API provides a RESTful set of web services that interact with Microsoft Azure Networks service to manage your network resources. The API has entities that capture the relationship between an end user and the Microsoft Azure Networks service.

    The version of the OpenAPI document: 2018-06-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.azure_firewall_properties_format import AzureFirewallPropertiesFormat

class TestAzureFirewallPropertiesFormat(unittest.TestCase):
    """AzureFirewallPropertiesFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AzureFirewallPropertiesFormat:
        """Test AzureFirewallPropertiesFormat
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AzureFirewallPropertiesFormat`
        """
        model = AzureFirewallPropertiesFormat()
        if include_optional:
            return AzureFirewallPropertiesFormat(
                application_rule_collections = [
                    openapi_client.models.azure_firewall_application_rule_collection.AzureFirewallApplicationRuleCollection(
                        etag = '', 
                        name = '', 
                        properties = openapi_client.models.azure_firewall_application_rule_collection_properties_format.AzureFirewallApplicationRuleCollectionPropertiesFormat(
                            action = openapi_client.models.azure_firewall_rc_action.AzureFirewallRCAction(
                                type = 'Allow', ), 
                            priority = 1E+2, 
                            provisioning_state = 'Succeeded', 
                            rules = [
                                openapi_client.models.azure_firewall_application_rule.AzureFirewallApplicationRule(
                                    description = '', 
                                    name = '', 
                                    protocols = [
                                        openapi_client.models.azure_firewall_application_rule_protocol.AzureFirewallApplicationRuleProtocol(
                                            port = 0, 
                                            protocol_type = 'Http', )
                                        ], 
                                    source_addresses = [
                                        ''
                                        ], 
                                    target_urls = [
                                        ''
                                        ], )
                                ], ), )
                    ],
                ip_configurations = [
                    openapi_client.models.azure_firewall_ip_configuration.AzureFirewallIPConfiguration(
                        etag = '', 
                        name = '', 
                        properties = openapi_client.models.azure_firewall_ip_configuration_properties_format.AzureFirewallIPConfigurationPropertiesFormat(
                            internal_public_ip_address = openapi_client.models.azure_firewall_ip_configuration_properties_format_internal_public_ip_address.AzureFirewallIPConfigurationPropertiesFormat_internalPublicIpAddress(
                                id = '', ), 
                            private_ip_address = '', 
                            provisioning_state = 'Succeeded', 
                            public_ip_address = openapi_client.models.azure_firewall_ip_configuration_properties_format_internal_public_ip_address.AzureFirewallIPConfigurationPropertiesFormat_internalPublicIpAddress(
                                id = '', ), 
                            subnet = , ), )
                    ],
                network_rule_collections = [
                    openapi_client.models.azure_firewall_network_rule_collection.AzureFirewallNetworkRuleCollection(
                        etag = '', 
                        name = '', 
                        properties = openapi_client.models.azure_firewall_network_rule_collection_properties_format.AzureFirewallNetworkRuleCollectionPropertiesFormat(
                            action = openapi_client.models.azure_firewall_rc_action.AzureFirewallRCAction(
                                type = 'Allow', ), 
                            priority = 1E+2, 
                            provisioning_state = 'Succeeded', 
                            rules = [
                                openapi_client.models.azure_firewall_network_rule.AzureFirewallNetworkRule(
                                    description = '', 
                                    destination_addresses = [
                                        ''
                                        ], 
                                    destination_ports = [
                                        ''
                                        ], 
                                    name = '', 
                                    protocols = [
                                        'TCP'
                                        ], 
                                    source_addresses = [
                                        ''
                                        ], )
                                ], ), )
                    ],
                provisioning_state = 'Succeeded'
            )
        else:
            return AzureFirewallPropertiesFormat(
        )
        """

    def testAzureFirewallPropertiesFormat(self):
        """Test AzureFirewallPropertiesFormat"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
