from dataclasses import dataclass, field
from enum import Enum

class ExtendedKeyUsageTypeEnum(str, Enum):
    SERVER_AUTH = "SERVER_AUTH"
    CLIENT_AUTH = "CLIENT_AUTH"
    CODE_SIGNING = "CODE_SIGNING"
    EMAIL_PROTECTION = "EMAIL_PROTECTION"
    TIME_STAMPING = "TIME_STAMPING"
    OCSP_SIGNING = "OCSP_SIGNING"
    SMART_CARD_LOGIN = "SMART_CARD_LOGIN"
    DOCUMENT_SIGNING = "DOCUMENT_SIGNING"
    CERTIFICATE_TRANSPARENCY = "CERTIFICATE_TRANSPARENCY"

