swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /analytics/v2.4
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: View and manage your Google Analytics data
  title: Google Analytics
  version: v2.4
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.gstatic.com/images/icons/material/product/2x/analytics_64dp.png'
  x-origin:
    format: google
    url: 'https://www.googleapis.com/discovery/v1/apis/analytics/v2.4/rest'
    version: v1
  x-preferred: false
  x-providerName: googleapis.com
  x-serviceName: analytics
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/analytics': View and manage your Google Analytics data
      'https://www.googleapis.com/auth/analytics.readonly': View your Google Analytics data
    type: oauth2
paths:
  /data:
    get:
      description: Returns Analytics report data for a view (profile).
      operationId: analytics.data.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/analytics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/analytics.readonly'
      tags:
        - data
  /management/accounts:
    get:
      description: Lists all accounts to which the user has access.
      operationId: analytics.management.accounts.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/analytics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/analytics.readonly'
      tags:
        - management
  '/management/accounts/{accountId}/webproperties':
    get:
      description: Lists web properties to which the user has access.
      operationId: analytics.management.webproperties.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/analytics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/analytics.readonly'
      tags:
        - management
  '/management/accounts/{accountId}/webproperties/{webPropertyId}/profiles':
    get:
      description: Lists views (profiles) to which the user has access.
      operationId: analytics.management.profiles.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/analytics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/analytics.readonly'
      tags:
        - management
  '/management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals':
    get:
      description: Lists goals to which the user has access.
      operationId: analytics.management.goals.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/analytics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/analytics.readonly'
      tags:
        - management
  /management/segments:
    get:
      description: Lists advanced segments to which the user has access.
      operationId: analytics.management.segments.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/analytics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/analytics.readonly'
      tags:
        - management