package shared

type IncomingPhoneNumberEnumEmergencyAddressStatusEnum string

const (
	IncomingPhoneNumberEnumEmergencyAddressStatusEnumRegistered            IncomingPhoneNumberEnumEmergencyAddressStatusEnum = "registered"
	IncomingPhoneNumberEnumEmergencyAddressStatusEnumUnregistered          IncomingPhoneNumberEnumEmergencyAddressStatusEnum = "unregistered"
	IncomingPhoneNumberEnumEmergencyAddressStatusEnumPendingRegistration   IncomingPhoneNumberEnumEmergencyAddressStatusEnum = "pending-registration"
	IncomingPhoneNumberEnumEmergencyAddressStatusEnumRegistrationFailure   IncomingPhoneNumberEnumEmergencyAddressStatusEnum = "registration-failure"
	IncomingPhoneNumberEnumEmergencyAddressStatusEnumPendingUnregistration IncomingPhoneNumberEnumEmergencyAddressStatusEnum = "pending-unregistration"
	IncomingPhoneNumberEnumEmergencyAddressStatusEnumUnregistrationFailure IncomingPhoneNumberEnumEmergencyAddressStatusEnum = "unregistration-failure"
)
