package shared

type IncomingPhoneNumberTollFreeEnumVoiceReceiveModeEnum string

const (
	IncomingPhoneNumberTollFreeEnumVoiceReceiveModeEnumVoice IncomingPhoneNumberTollFreeEnumVoiceReceiveModeEnum = "voice"
	IncomingPhoneNumberTollFreeEnumVoiceReceiveModeEnumFax   IncomingPhoneNumberTollFreeEnumVoiceReceiveModeEnum = "fax"
)
