swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /admin/reports/v1
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: 'Fetches reports for the administrators of G Suite customers about the usage, collaboration, security, and risk for their users.'
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Admin Reports
  version: reports_v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-apisguru-categories:
    - analytics
  x-logo:
    url: 'https://www.gstatic.com/images/icons/material/product/2x/admin_64dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/admin/reports_v1/rest'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: admin
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/admin.reports.audit.readonly': View audit reports for your G Suite domain
      'https://www.googleapis.com/auth/admin.reports.usage.readonly': View usage reports for your G Suite domain
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/admin.reports.audit.readonly': View audit reports for your G Suite domain
      'https://www.googleapis.com/auth/admin.reports.usage.readonly': View usage reports for your G Suite domain
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: activities
  - name: channels
  - name: customerUsageReports
  - name: userUsageReport
paths:
  '/activity/users/{userKey}/applications/{applicationName}':
    get:
      description: Retrieves a list of activities for a specific customer and application.
      operationId: reports.activities.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.reports.audit.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/admin.reports.audit.readonly'
      tags:
        - activities
  '/activity/users/{userKey}/applications/{applicationName}/watch':
    post:
      description: Push changes to activities
      operationId: reports.activities.watch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.reports.audit.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/admin.reports.audit.readonly'
      tags:
        - activities
  /admin/reports_v1/channels/stop:
    post:
      description: Stop watching resources through this channel
      operationId: admin.channels.stop
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.reports.audit.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/admin.reports.audit.readonly'
      tags:
        - channels
  '/usage/dates/{date}':
    get:
      description: Retrieves a report which is a collection of properties / statistics for a specific customer.
      operationId: reports.customerUsageReports.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.reports.usage.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/admin.reports.usage.readonly'
      tags:
        - customerUsageReports
  '/usage/users/{userKey}/dates/{date}':
    get:
      description: Retrieves a report which is a collection of properties / statistics for a set of users.
      operationId: reports.userUsageReport.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.reports.usage.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/admin.reports.usage.readonly'
      tags:
        - userUsageReport