from .__xgafv_enum import *
from .alt_enum import *
from .aptsettings import *
from .cvssv3 import *
from .date import *
from .execstep import *
from .execstepconfig import *
from .executepatchjobrequest import *
from .fixedorpercent import *
from .gcsobject import *
from .inventory import *
from .inventoryitem import *
from .inventoryosinfo import *
from .inventorysoftwarepackage import *
from .inventoryversionedpackage import *
from .inventorywindowsapplication import *
from .inventorywindowsquickfixengineeringpackage import *
from .inventorywindowsupdatepackage import *
from .inventorywindowsupdatepackagewindowsupdatecategory import *
from .inventoryzypperpatch import *
from .listinventoriesresponse import *
from .listospolicyassignmentreportsresponse import *
from .listospolicyassignmentrevisionsresponse import *
from .listospolicyassignmentsresponse import *
from .listpatchdeploymentsresponse import *
from .listpatchjobinstancedetailsresponse import *
from .listpatchjobsresponse import *
from .listvulnerabilityreportsresponse import *
from .monthlyschedule import *
from .onetimeschedule import *
from .operation import *
from .ospolicy import *
from .ospolicyassignment import *
from .ospolicyassignmentinstancefilter import *
from .ospolicyassignmentinstancefilterinventory import *
from .ospolicyassignmentlabelset import *
from .ospolicyassignmentreport import *
from .ospolicyassignmentreportospolicycompliance import *
from .ospolicyassignmentreportospolicycomplianceospolicyresourcecompliance import *
from .ospolicyassignmentreportospolicycomplianceospolicyresourcecomplianceexecresourceoutput import *
from .ospolicyassignmentreportospolicycomplianceospolicyresourcecomplianceospolicyresourceconfigstep import *
from .ospolicyassignmentrollout import *
from .ospolicyinventoryfilter import *
from .ospolicyresource import *
from .ospolicyresourceexecresource import *
from .ospolicyresourceexecresourceexec import *
from .ospolicyresourcefile import *
from .ospolicyresourcefilegcs import *
from .ospolicyresourcefileremote import *
from .ospolicyresourcefileresource import *
from .ospolicyresourcegroup import *
from .ospolicyresourcepackageresource import *
from .ospolicyresourcepackageresourceapt import *
from .ospolicyresourcepackageresourcedeb import *
from .ospolicyresourcepackageresourcegooget import *
from .ospolicyresourcepackageresourcemsi import *
from .ospolicyresourcepackageresourcerpm import *
from .ospolicyresourcepackageresourceyum import *
from .ospolicyresourcepackageresourcezypper import *
from .ospolicyresourcerepositoryresource import *
from .ospolicyresourcerepositoryresourceaptrepository import *
from .ospolicyresourcerepositoryresourcegoorepository import *
from .ospolicyresourcerepositoryresourceyumrepository import *
from .ospolicyresourcerepositoryresourcezypperrepository import *
from .patchconfig import *
from .patchdeployment import *
from .patchinstancefilter import *
from .patchinstancefiltergrouplabel import *
from .patchjob import *
from .patchjobinstancedetails import *
from .patchjobinstancedetailssummary import *
from .patchrollout import *
from .recurringschedule import *
from .security import *
from .status import *
from .timeofday import *
from .timezone import *
from .vulnerabilityreport import *
from .vulnerabilityreportvulnerability import *
from .vulnerabilityreportvulnerabilitydetails import *
from .vulnerabilityreportvulnerabilitydetailsreference import *
from .vulnerabilityreportvulnerabilityitem import *
from .weekdayofmonth import *
from .weeklyschedule import *
from .windowsupdatesettings import *
from .yumsettings import *
from .zyppersettings import *
