from .createcontainer import *
from .deletecontainer import *
from .deletecontainerpolicy import *
from .deletecorspolicy import *
from .deletelifecyclepolicy import *
from .deletemetricpolicy import *
from .describecontainer import *
from .getcontainerpolicy import *
from .getcorspolicy import *
from .getlifecyclepolicy import *
from .getmetricpolicy import *
from .listcontainers import *
from .listtagsforresource import *
from .putcontainerpolicy import *
from .putcorspolicy import *
from .putlifecyclepolicy import *
from .putmetricpolicy import *
from .startaccesslogging import *
from .stopaccesslogging import *
from .tagresource import *
from .untagresource import *
