openapi: 3.0.0
servers:
  - url: https://workspaceevents.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: The Google Workspace Events API lets you subscribe to events and manage change notifications across Google Workspace applications.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Google Workspace Events API
  version: v1
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://upload.wikimedia.org/wikipedia/commons/e/e1/YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
    - format: google
      url: https://workspaceevents.googleapis.com/$discovery/rest?version=v1
      version: v1
  x-providerName: googleapis.com
  x-serviceName: workspaceevents
tags:
  - name: operations
  - name: subscriptions
paths:
  /v1/subscriptions:
    get:
      description: "[Developer Preview](https://developers.google.com/workspace/preview): Lists Google Workspace subscriptions. To learn how to use this method, see [List Google Workspace subscriptions](https://developers.google.com/workspace/events/guides/list-subscriptions)."
      operationId: workspaceevents.subscriptions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.bot
          Oauth2c:
            - https://www.googleapis.com/auth/chat.bot
        - Oauth2:
            - https://www.googleapis.com/auth/chat.memberships
          Oauth2c:
            - https://www.googleapis.com/auth/chat.memberships
        - Oauth2:
            - https://www.googleapis.com/auth/chat.memberships.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.memberships.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.reactions
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.reactions
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.reactions.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.reactions.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces.readonly
      tags:
        - subscriptions
    post:
      description: "[Developer Preview](https://developers.google.com/workspace/preview): Creates a Google Workspace subscription. To learn how to use this method, see [Create a Google Workspace subscription](https://developers.google.com/workspace/events/guides/create-subscription)."
      operationId: workspaceevents.subscriptions.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.memberships
          Oauth2c:
            - https://www.googleapis.com/auth/chat.memberships
        - Oauth2:
            - https://www.googleapis.com/auth/chat.memberships.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.memberships.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.reactions
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.reactions
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.reactions.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.reactions.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces.readonly
      tags:
        - subscriptions
  /v1/{name}:
    delete:
      description: "[Developer Preview](https://developers.google.com/workspace/preview): Deletes a Google Workspace subscription. To learn how to use this method, see [Delete a Google Workspace subscription](https://developers.google.com/workspace/events/guides/delete-subscription)."
      operationId: workspaceevents.subscriptions.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.bot
          Oauth2c:
            - https://www.googleapis.com/auth/chat.bot
        - Oauth2:
            - https://www.googleapis.com/auth/chat.memberships
          Oauth2c:
            - https://www.googleapis.com/auth/chat.memberships
        - Oauth2:
            - https://www.googleapis.com/auth/chat.memberships.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.memberships.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.reactions
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.reactions
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.reactions.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.reactions.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces.readonly
      tags:
        - subscriptions
    get:
      description: "[Developer Preview](https://developers.google.com/workspace/preview): Gets details about a Google Workspace subscription. To learn how to use this method, see [Get details about a Google Workspace subscription](https://developers.google.com/workspace/events/guides/get-subscription)."
      operationId: workspaceevents.subscriptions.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.bot
          Oauth2c:
            - https://www.googleapis.com/auth/chat.bot
        - Oauth2:
            - https://www.googleapis.com/auth/chat.memberships
          Oauth2c:
            - https://www.googleapis.com/auth/chat.memberships
        - Oauth2:
            - https://www.googleapis.com/auth/chat.memberships.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.memberships.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.reactions
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.reactions
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.reactions.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.reactions.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces.readonly
      tags:
        - subscriptions
    patch:
      description: "[Developer Preview](https://developers.google.com/workspace/preview): Updates or renews a Google Workspace subscription. To learn how to use this method, see [Update or renew a Google Workspace subscription](https://developers.google.com/workspace/events/guides/update-subscription)."
      operationId: workspaceevents.subscriptions.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.memberships
          Oauth2c:
            - https://www.googleapis.com/auth/chat.memberships
        - Oauth2:
            - https://www.googleapis.com/auth/chat.memberships.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.memberships.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.reactions
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.reactions
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.reactions.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.reactions.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces.readonly
      tags:
        - subscriptions
  /v1/{name}:reactivate:
    post:
      description: "[Developer Preview](https://developers.google.com/workspace/preview): Reactivates a suspended Google Workspace subscription. This method resets your subscription's `State` field to `ACTIVE`. Before you use this method, you must fix the error that suspended the subscription. To learn how to use this method, see [Reactivate a Google Workspace subscription](https://developers.google.com/workspace/events/guides/reactivate-subscription)."
      operationId: workspaceevents.subscriptions.reactivate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chat.memberships
          Oauth2c:
            - https://www.googleapis.com/auth/chat.memberships
        - Oauth2:
            - https://www.googleapis.com/auth/chat.memberships.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.memberships.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.reactions
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.reactions
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.reactions.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.reactions.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/chat.messages.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.messages.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces
        - Oauth2:
            - https://www.googleapis.com/auth/chat.spaces.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chat.spaces.readonly
      tags:
        - subscriptions
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/chat.bot: "Private Service: https://www.googleapis.com/auth/chat.bot"
            https://www.googleapis.com/auth/chat.memberships: View, add, and remove members from conversations in Google Chat
            https://www.googleapis.com/auth/chat.memberships.readonly: View members in Google Chat conversations.
            https://www.googleapis.com/auth/chat.messages: View, compose, send, update, and delete messages, and add, view, and delete reactions to messages.
            https://www.googleapis.com/auth/chat.messages.reactions: View, add, and delete reactions to messages in Google Chat
            https://www.googleapis.com/auth/chat.messages.reactions.readonly: View reactions to messages in Google Chat
            https://www.googleapis.com/auth/chat.messages.readonly: View messages and reactions in Google Chat
            https://www.googleapis.com/auth/chat.spaces: Create conversations and spaces and see or edit metadata (including history settings and access settings) in Google Chat
            https://www.googleapis.com/auth/chat.spaces.readonly: View chat and spaces in Google Chat
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/chat.bot: "Private Service: https://www.googleapis.com/auth/chat.bot"
            https://www.googleapis.com/auth/chat.memberships: View, add, and remove members from conversations in Google Chat
            https://www.googleapis.com/auth/chat.memberships.readonly: View members in Google Chat conversations.
            https://www.googleapis.com/auth/chat.messages: View, compose, send, update, and delete messages, and add, view, and delete reactions to messages.
            https://www.googleapis.com/auth/chat.messages.reactions: View, add, and delete reactions to messages in Google Chat
            https://www.googleapis.com/auth/chat.messages.reactions.readonly: View reactions to messages in Google Chat
            https://www.googleapis.com/auth/chat.messages.readonly: View messages and reactions in Google Chat
            https://www.googleapis.com/auth/chat.spaces: Create conversations and spaces and see or edit metadata (including history settings and access settings) in Google Chat
            https://www.googleapis.com/auth/chat.spaces.readonly: View chat and spaces in Google Chat
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
