# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API

    The version of the OpenAPI document: v0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tester_app_response import TesterAppResponse

class TestTesterAppResponse(unittest.TestCase):
    """TesterAppResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TesterAppResponse:
        """Test TesterAppResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TesterAppResponse`
        """
        model = TesterAppResponse()
        if include_optional:
            return TesterAppResponse(
                description = '',
                display_name = '',
                icon_source = '',
                icon_url = '',
                id = '',
                name = '',
                os = 'Android',
                owner = openapi_client.models.apps_list_200_response_inner_all_of_owner.apps_list_200_response_inner_allOf_owner(
                    avatar_url = '', 
                    display_name = '', 
                    email = '', 
                    id = '', 
                    name = '', 
                    type = 'org', ),
                release_type = '',
                microsoft_internal = True,
                permissions = [
                    'can_remove_from_app'
                    ]
            )
        else:
            return TesterAppResponse(
                display_name = '',
                id = '',
                name = '',
                os = 'Android',
                owner = openapi_client.models.apps_list_200_response_inner_all_of_owner.apps_list_200_response_inner_allOf_owner(
                    avatar_url = '', 
                    display_name = '', 
                    email = '', 
                    id = '', 
                    name = '', 
                    type = 'org', ),
        )
        """

    def testTesterAppResponse(self):
        """Test TesterAppResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
