swagger: '2.0'
schemes:
  - https
host: api.flat.io
basePath: /v2
info:
  contact:
    email: developers@flat.io
    name: Flat
    url: 'https://flat.io/developers/docs/api/'
  description: |
    The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:

    * Creating and importing new music scores using MusicXML or MIDI files
    * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI)
    * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.

    The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body.
    The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/).
    This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).

    You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).

    Getting Started and learn more:

    * [API Overview and interoduction](https://flat.io/developers/docs/api/)
    * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html)
    * [SDKs](https://flat.io/developers/docs/api/sdks.html)
    * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html)
    * [Changelog](https://flat.io/developers/docs/api/changelog.html)
  termsOfService: 'https://flat.io/legal'
  title: Flat
  version: 2.2.0
  x-apisguru-categories:
    - media
    - collaboration
  x-logo:
    url: 'https://flat.io/img/logo-flat.svg'
  x-origin:
    - format: swagger
      url: 'https://raw.githubusercontent.com/FlatIO/api-reference/master/spec/swagger.yaml'
      version: '2.0'
  x-providerName: flat.io
securityDefinitions:
  OAuth2:
    authorizationUrl: 'https://flat.io/auth/oauth'
    description: |
      OAuth 2.0 authentication for your app or. Please only request the most restrictive and needed scopes. Using some of the scopes may require an additional review from our team. The Flat API supports **authorization code** and **implicit** flows.
    flow: accessCode
    scopes:
      account.education_profile: |
        Provides access to the basic person's education profile and public organization information.
      account.public_profile: |
        Provides access to the basic person's public profile. Education profiles may be anonymized with this scope, you can request the scope `education_profile` to access to the a basic education account profile.
      edu.admin: 'Full, permissive scope to manage all the admin of an organization.'
      edu.admin.lti: Access and manage the LTI Credentials for an organization.
      edu.admin.lti.readonly: Read-only access to the LTI Credentials of an organization.
      edu.admin.users: Access and manage the users and invitations of the organization.
      edu.admin.users.readonly: Read-only access to the users and invitations of the organization.
      edu.assignments: Read-write access to the assignments and submissions.
      edu.assignments.readonly: Read-only access to the assignments and submissions.
      edu.classes: 'Full, permissive scope to manage the classes.'
      edu.classes.readonly: Read-only access to the classes.
      scores: |
        Full, permissive scope to access all of a user's scores.
      scores.readonly: |
        Allows read-only access to all a user's scores. You won't need this scope to read public scores.
      scores.social: |
        Allow to post comments and like scores
    tokenUrl: 'https://api.flat.io/oauth/access_token'
    type: oauth2
tags:
  - description: |
      These API endpoints are related to the Flat account you are currently using. When using an OAuth2 access token, you can use [`GET /me`](#operation/getAuthenticatedUser) to get information about the account.
    name: Account
    x-displayName: Flat Account
  - description: |
      Sheet music is the main API object type available for all Flat account.

      Here is a typical lifecycle for a music score document on Flat:
        - An end user can **create a music score** or **import a document** using our [web interface](https://flat.io) or a third-party website/app (e.g. Google Drive) using this API (see [`POST /v2/scores`](#operation/createScore). The creation and import of music scores can be done with this single API endpoint. This one currently supports the [MusicXML](http://www.musicxml.com/) (compressed or not) and [MIDI](https://www.midi.org/specifications).
        - The scores from a single account can **be listed** with [`GET /users/{user}/scores`](#operation/getUserScores) as well of scores shared with a specific group with [`GET /groups/{group}/scores`](#operation/getGroupScores).
        - The metadata of a single score can be retrieved with [`GET /scores/{score}`](#operation/getScore).
        - Scores on Flat have **one or multiple revisions**: creating a new score will create a first revision. These **revisions can be listed** using [`GET /scores/{score}/revisions`](#operation/getScoreRevisions) and a specific **revision data can be downloaded** with [`GET /scores/{score}/revisions/{revision}/{format}`](#operation/getScoreRevisionData). New revisions can be created using our [sheet music editor](https://flat.io) or using [`POST /scores/{score}/revisions`](#operation/createSc[...]
        - Scores can be **shared publicly** by changing the privacy option with [`POST /scores/{score}`](#operation/editScore), or **individually shared** using the different collaborators API endpoints (see [`POST /scores/{score}/collaborators`](#operation/addScoreCollaborator)).
    name: Score
    x-displayName: Music scores
  - description: Flat users
    name: User
  - description: Flat for Education organizations
    name: Organization
  - description: Flat for Education classes
    name: Class
  - description: Flat Groups
    name: Group
paths:
  /classes:
    get:
      operationId: listClasses
      security:
        - OAuth2:
            - edu.classes
            - edu.classes.readonly
      summary: List the classes available for the current user
      tags:
        - Class
    post:
      description: |
        Classrooms on Flat allow you to create activities with assignments and post content to a specific group.

        When creating a class, Flat automatically creates two groups: one for the teachers of the course, one for the students. The creator of this class is automatically added to the teachers group.

        If the classsroom is synchronized with another application like Google Classroom, some of the meta information will automatically be updated.

        You can add users to this class using `POST /classes/{class}/users/{user}`, they will automatically added to the group based on their role on Flat. Users can also enroll themselves to this class using `POST /classes/enroll/{enrollmentCode}` and the `enrollmentCode` returned in the `ClassDetails` response.
      operationId: createClass
      security:
        - OAuth2:
            - edu.classes
      summary: Create a new class
      tags:
        - Class
  '/classes/enroll/{enrollmentCode}':
    post:
      description: |
        Use this method to join a class using an enrollment code given one of the teacher of this class. This code is also available in the `ClassDetails` returned to the teachers when creating the class or listing / fetching a specific class.

        Flat will automatically add the user to the corresponding class group based on this role in the organization.
      operationId: enrollClass
      security:
        - OAuth2:
            - edu.classes
      summary: Join a class
      tags:
        - Class
  '/classes/{class}':
    get:
      operationId: getClass
      security:
        - OAuth2:
            - edu.classes
            - edu.classes.readonly
      summary: Get the details of a single class
      tags:
        - Class
    put:
      description: |
        Update the meta information of the class
      operationId: updateClass
      security:
        - OAuth2:
            - edu.classes
      summary: Update the class
      tags:
        - Class
  '/classes/{class}/archive':
    delete:
      description: |
        Mark the class as `active`. When this course is synchronized with another app, like Google Classroom, this state will be automatically be updated.
      operationId: unarchiveClass
      security:
        - OAuth2:
            - edu.classes
      summary: Unarchive the class
      tags:
        - Class
    post:
      description: |
        Mark the class as `archived`. When this course is synchronized with another app, like Google Classroom, this state will be automatically be updated.
      operationId: archiveClass
      security:
        - OAuth2:
            - edu.classes
      summary: Archive the class
      tags:
        - Class
  '/classes/{class}/assignments':
    get:
      operationId: listAssignments
      security:
        - OAuth2:
            - edu.classes
            - edu.classes.readonly
            - edu.assignments
            - edu.assignments.readonly
      summary: Assignments listing
      tags:
        - Class
    post:
      description: |
        Use this method as a teacher to create and post a new assignment to a class.

        If the class is synchronized with Google Classroom, the assignment will be automatically posted to your Classroom course.
      operationId: createAssignment
      security:
        - OAuth2:
            - edu.classes
            - edu.assignments
      summary: Assignment creation
      tags:
        - Class
  '/classes/{class}/assignments/{assignment}/copy':
    post:
      description: |
        Copy an assignment to a specified class.

        If the original assignment has a due date in the past, this new assingment will be created without a due date.

        If the new class is synchronized with an external app (e.g. Google Classroom), the copied assignment will also be posted on the external app.
      operationId: copyAssignment
      security:
        - OAuth2:
            - edu.classes
            - edu.assignments
      summary: Copy an assignment
      tags:
        - Class
  '/classes/{class}/assignments/{assignment}/submissions':
    get:
      operationId: getSubmissions
      security:
        - OAuth2:
            - edu.classes
            - edu.classes.readonly
            - edu.assignments
            - edu.assignments.readonly
      summary: List the students' submissions
      tags:
        - Class
    put:
      description: |
        Use this method as a student to create, update and submit a submission related to an assignment. Students can only set `attachments`, `studentComment` and `submit`.

        Teachers can use `PUT /classes/{class}/assignments/{assignment}/submissions/{submission}` to update a submission by id.
      operationId: createSubmission
      security:
        - OAuth2:
            - edu.classes
            - edu.assignments
      summary: Create or edit a submission
      tags:
        - Class
  '/classes/{class}/assignments/{assignment}/submissions/{submission}':
    get:
      operationId: getSubmission
      security:
        - OAuth2:
            - edu.classes
            - edu.classes.readonly
            - edu.assignments
            - edu.assignments.readonly
      summary: Get a student submission
      tags:
        - Class
    put:
      description: |
        Use this method as a teacher to update the different submission and give feedback.
        Teachers can only set `returnFeedback`
      operationId: editSubmission
      security:
        - OAuth2:
            - edu.classes
            - edu.assignments
      summary: Edit a submission
      tags:
        - Class
  '/classes/{class}/students/{user}/submissions':
    get:
      description: |
        Use this method as a teacher to list all the assignment submissions sent by a student of the class
      operationId: listClassStudentSubmissions
      security:
        - OAuth2:
            - edu.classes
            - edu.classes.readonly
            - edu.assignments
            - edu.assignments.readonly
      summary: List the submissions for a student
      tags:
        - Class
  '/classes/{class}/users/{user}':
    delete:
      description: |
        This method can be used by a teacher to remove a user from the class, or by a student to leave the classroom.

        Warning: Removing a user from the class will remove the associated resources, including the submissions and feedback related to these submissions.
      operationId: deleteClassUser
      security:
        - OAuth2:
            - edu.classes
      summary: Remove a user from the class
      tags:
        - Class
    put:
      description: |
        This method can be used by a teacher of the class to enroll another Flat user into the class.

        Only users that are part of your Organization can be enrolled in a class of this same Organization.

        When enrolling a user in the class, Flat will automatically add this user to the corresponding Class group, based on this role in the Organization.
      operationId: addClassUser
      security:
        - OAuth2:
            - edu.classes
      summary: Add a user to the class
      tags:
        - Class
  '/groups/{group}':
    get:
      operationId: getGroupDetails
      security:
        - OAuth2:
            - edu.admin
            - edu.admin.users
            - edu.admin.users.readonly
            - edu.classes
            - edu.classes.readonly
      summary: Get group information
      tags:
        - Group
  '/groups/{group}/scores':
    get:
      description: |
        Get the list of scores shared with a group.
      operationId: getGroupScores
      security:
        - OAuth2:
            - scores
            - scores.readonly
      summary: List group's scores
      tags:
        - Group
        - Score
  '/groups/{group}/users':
    get:
      operationId: listGroupUsers
      security:
        - OAuth2:
            - edu.admin
            - edu.admin.users
            - edu.admin.users.readonly
            - edu.classes
            - edu.classes.readonly
      summary: List group's users
      tags:
        - Group
  /me:
    get:
      description: |
        Get details about the current authenticated User.
      operationId: getAuthenticatedUser
      security:
        - OAuth2:
            - account.public_profile
            - account.education_profile
      summary: Get current user profile
      tags:
        - Account
  /organizations/invitations:
    get:
      operationId: listOrganizationInvitations
      security:
        - OAuth2:
            - edu.admin
            - edu.admin.users
            - edu.admin.users.readonly
      summary: List the organization invitations
      tags:
        - Organization
    post:
      description: |
        This method creates and sends invitation for teachers and admins.

        Invitations can only be used by new Flat users or users who are not part of the organization yet.

        If the email of the user is already associated to a user of your organization, the API will simply update the role of the existing user and won't send an invitation. In this case, the property `usedBy` will be directly filled with the uniquer identifier of the corresponding user.
      operationId: createOrganizationInvitation
      security:
        - OAuth2:
            - edu.admin
            - edu.admin.users
      summary: Create a new invitation to join the organization
      tags:
        - Organization
  '/organizations/invitations/{invitation}':
    delete:
      operationId: removeOrganizationInvitation
      security:
        - OAuth2:
            - edu.admin
            - edu.admin.users
      summary: Remove an organization invitation
      tags:
        - Organization
  /organizations/lti/credentials:
    get:
      operationId: listLtiCredentials
      security:
        - OAuth2:
            - edu.admin
            - edu.admin.lti
            - edu.admin.lti.readonly
      summary: List LTI 1.x credentials
      tags:
        - Organization
    post:
      description: |
        Flat for Education is a Certified LTI Provider. You can use these API methods to automate the creation of LTI credentials. You can read more about our LTI implementation, supported components and LTI Endpoints in our [Developer Documentation](https://flat.io/developers/docs/lti/).
      operationId: createLtiCredentials
      security:
        - OAuth2:
            - edu.admin
            - edu.admin.lti
      summary: Create a new couple of LTI 1.x credentials
      tags:
        - Organization
  '/organizations/lti/credentials/{credentials}':
    delete:
      operationId: revokeLtiCredentials
      security:
        - OAuth2:
            - edu.admin
            - edu.admin.lti
      summary: Revoke LTI 1.x credentials
      tags:
        - Organization
  /organizations/users:
    get:
      operationId: listOrganizationUsers
      security:
        - OAuth2:
            - edu.admin
            - edu.admin.users
            - edu.admin.users.readonly
      summary: List the organization users
      tags:
        - Organization
    post:
      operationId: createOrganizationUser
      security:
        - OAuth2:
            - edu.admin
            - edu.admin.users
      summary: Create a new user account
      tags:
        - Organization
  /scores:
    post:
      description: |
        Use this API method to **create a new music score in the current User account**. You will need a MusicXML 3 (`vnd.recordare.musicxml` or `vnd.recordare.musicxml+xml`) or a MIDI (`audio/midi`) file to create the new Flat document.

        This API call will automatically create the first revision of the document, the score can be modified by the using our web application or by uploading a new revision of this file (`POST /v2/scores/{score}/revisions/{revision}`).

        The currently authenticated user will be granted owner of the file and will be able to add other collaborators (users and groups).
      operationId: createScore
      security:
        - OAuth2:
            - scores
      summary: Create a new score
      tags:
        - Score
  '/scores/{score}':
    delete:
      description: |
        This API call will schedule the deletion of the score, its revisions, and whole history.
        The user calling this API method must have the `aclAdmin` rights on this document to process this action.
        The score won't be accessible anymore after calling this method and the user's quota will directly be updated.
      operationId: deleteScore
      security:
        - OAuth2:
            - scores
      summary: Delete a score
      tags:
        - Score
    get:
      description: |
        Get the details of a score identified by the `score` parameter in the URL.
        The currently authenticated user must have at least a read access to the document to use this API call.
      operationId: getScore
      security:
        - OAuth2:
            - scores
            - scores.readonly
      summary: Get a score's metadata
      tags:
        - Score
    put:
      description: |
        This API method allows you to change the metadata of a score document (e.g. its `title` or `privacy`), all the properties are optional.

        To edit the file itself, create a new revision using the appropriate method (`POST /v2/scores/{score}/revisions/{revision}`).
      operationId: editScore
      security:
        - OAuth2:
            - scores
      summary: Edit a score's metadata
      tags:
        - Score
  '/scores/{score}/collaborators':
    get:
      description: |
        This API call will list the different collaborators of a score and their rights on the document. The returned list will at least contain the owner of the document.

        Collaborators can be a single user (the object `user` will be populated) or a group (the object `group` will be populated).
      operationId: getScoreCollaborators
      security:
        - OAuth2:
            - scores.readonly
            - scores
      summary: List the collaborators
      tags:
        - Score
    post:
      description: |
        Share a score with a single user or a group. This API call allows to add, invite and update the collaborators of a document.
        - To add an existing Flat user to the document, specify its unique identifier in the `user` property.
        - To invite an external user to the document, specify its email in the `userEmail` property.
        - To add a Flat group to the document, specify its unique identifier in the `group` property.
        - To update an existing collaborator, process the same request with different rights.
      operationId: addScoreCollaborator
      security:
        - OAuth2:
            - scores
      summary: Add a new collaborator
      tags:
        - Score
  '/scores/{score}/collaborators/{collaborator}':
    delete:
      description: |
        Remove the specified collaborator from the score
      operationId: removeScoreCollaborator
      security:
        - OAuth2:
            - scores
      summary: Delete a collaborator
      tags:
        - Score
    get:
      description: |
        Get the information about a collaborator (User or Group).
      operationId: getScoreCollaborator
      security:
        - OAuth2:
            - scores.readonly
      summary: Get a collaborator
      tags:
        - Score
  '/scores/{score}/comments':
    get:
      description: This method lists the different comments added on a music score (documents and inline) sorted by their post dates.
      operationId: getScoreComments
      security:
        - OAuth2:
            - scores.readonly
            - scores.social
            - scores
      summary: List comments
      tags:
        - Score
    post:
      description: |
        Post a document or a contextualized comment on a document.

        Please note that this method includes an anti-spam system for public scores. We don't guarantee that your comments will be accepted and displayed to end-user. Comments are be blocked by returning a `403` HTTP error and hidden from other users when the `spam` property is `true`.
      operationId: postScoreComment
      security:
        - OAuth2:
            - scores.social
            - scores
      summary: Post a new comment
      tags:
        - Score
  '/scores/{score}/comments/{comment}':
    delete:
      operationId: deleteScoreComment
      security:
        - OAuth2:
            - scores.social
            - scores
      summary: Delete a comment
      tags:
        - Score
    put:
      operationId: updateScoreComment
      security:
        - OAuth2:
            - scores.social
            - scores
      summary: Update an existing comment
      tags:
        - Score
  '/scores/{score}/comments/{comment}/resolved':
    delete:
      operationId: markScoreCommentUnresolved
      security:
        - OAuth2:
            - scores.social
            - scores
      summary: Mark the comment as unresolved
      tags:
        - Score
    put:
      operationId: markScoreCommentResolved
      security:
        - OAuth2:
            - scores.social
            - scores
      summary: Mark the comment as resolved
      tags:
        - Score
  '/scores/{score}/fork':
    post:
      description: |
        This API call will make a copy of the last revision of the specified score and create a new score. The copy of the score will have a privacy set to `private`.

        When using a [Flat for Education](https://flat.io/edu) account, the inline and contextualized comments will be accessible in the child document.
      operationId: forkScore
      security:
        - OAuth2:
            - scores
      summary: Fork a score
      tags:
        - Score
  '/scores/{score}/revisions':
    get:
      description: |
        When creating a score or saving a new version of a score, a revision is created in our storage. This method allows you to list all of them, sorted by last modification.

        Depending the plan of the account, this list can be trunked to the few last revisions.
      operationId: getScoreRevisions
      security:
        - OAuth2:
            - scores
            - scores.readonly
      summary: List the revisions
      tags:
        - Score
    post:
      description: |
        Update a score by uploading a new revision for this one.
      operationId: createScoreRevision
      security:
        - OAuth2:
            - scores
      summary: Create a new revision
      tags:
        - Score
  '/scores/{score}/revisions/{revision}':
    get:
      description: |
        When creating a score or saving a new version of a score, a revision is created in our storage. This method allows you to get a specific
        revision metadata.
      operationId: getScoreRevision
      security:
        - OAuth2:
            - scores
            - scores.readonly
      summary: Get a score revision
      tags:
        - Score
  '/scores/{score}/revisions/{revision}/{format}':
    get:
      description: |
        Retrieve the file corresponding to a score revision (the following formats are available: Flat JSON/Adagio JSON `json`, MusicXML
        `mxl`/`xml`, MP3 `mp3`, WAV `wav`, MIDI `midi`, or a tumbnail of the first page `thumbnail.png`).
      operationId: getScoreRevisionData
      security:
        - OAuth2:
            - scores
            - scores.readonly
      summary: Get a score revision data
      tags:
        - Score
  '/scores/{score}/submissions':
    get:
      description: |
        This API call will list the different assignments submissions where the score is attached. This method can be used by anyone that are part of the organization and have at least read access to the document.
      operationId: getScoreSubmissions
      security:
        - OAuth2:
            - scores
            - scores.readonly
      summary: List submissions related to the score
      tags:
        - Score
        - Class
  '/users/{user}':
    get:
      description: |
        Get a public profile of a Flat User.
      operationId: getUser
      security:
        - OAuth2:
            - account.public_profile
            - account.education_profile
      summary: Get a public user profile
      tags:
        - User
  '/users/{user}/likes':
    get:
      operationId: gerUserLikes
      security:
        - OAuth2:
            - account.public_profile
      summary: List liked scores
      tags:
        - User
        - Score
  '/users/{user}/scores':
    get:
      description: |
        Get the list of scores owned by the User
      operationId: getUserScores
      security:
        - OAuth2:
            - scores
            - scores.readonly
      summary: List user's scores
      tags:
        - User
        - Score