swagger: "2.0"
schemes:
  - https
host: api.avaza.com
info:
  contact:
    x-twitter: AvazaHq
  description: "Welcome to the autogenerated documentation & test tool for Avaza's API. <br/><br/><strong>API Security & Authentication</strong><br/>Authentication options include OAuth2 Implicit and Authorization Code flows, and Personal Access Token. All connections should be encrypted over SSL/TLS <br/><br/>You can set up and manage your api authentication credentials from within your Avaza account. (requires Administrator permissions on your Avaza account).<br/><br/> OAuth2 Authorization end[...]"
  title: Avaza API Documentation
  version: v1
  x-apisguru-categories:
    - collaboration
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_AvazaHq_profile_image.jpeg
  x-origin:
    - format: swagger
      url: https://api.avaza.com/swagger/docs/v1
      version: "2.0"
  x-providerName: avaza.com
securityDefinitions:
  oauth2:
    authorizationUrl: https://any.avaza.com/oauth2/authorize
    description: OAuth2 Implicit Grant
    flow: implicit
    scopes:
      read_account: Read access to Account metadata
      read_contacts: Read access to Customers, Contacts
      read_expenses: Read access to Expense Details
      read_financials: Read access to Estimates, Invoices, Payments, Credit Notes
      read_projects: Read access to Projects, Project Settings, Tasks
      read_schedule: Read access to Schedule Details
      read_timesheets: Read access to Timesheet Details
      read_users: Read access to User Profiles
      webhook_notifications: Read access to webhook notification events
      write_account: Write access to Account metadata
      write_contacts: Write access to Customers, Contacts
      write_expenses: Write access to Expense module
      write_financials: Write access to Estimates, Invoices, Payments, Credit Notes
      write_projects: Write access to Projects, Project Settings, Tasks
      write_schedule: Write access to Schedule module
      write_timesheets: Write access to Timesheets module
      write_users: Write access to User Profiles
    type: oauth2
paths:
  /ScheduleSeries/AddBooking:
    post:
      operationId: ScheduleSeries_AddBooking
      security:
        - oauth2:
            - write_schedule
      summary: Create new Schedule Booking
      tags:
        - ScheduleSeries
  /ScheduleSeries/AddLeave:
    post:
      operationId: ScheduleSeries_AddLeave
      security:
        - oauth2:
            - write_schedule
      summary: Create new Leave Booking
      tags:
        - ScheduleSeries
  /ScheduleSeries/EditBooking:
    put:
      operationId: ScheduleSeries_EditBooking
      security:
        - oauth2:
            - write_schedule
      summary: Edit Booking
      tags:
        - ScheduleSeries
  /ScheduleSeries/EditLeave:
    put:
      operationId: ScheduleSeries_EditLeave
      security:
        - oauth2:
            - write_schedule
      summary: Edit Leave Booking
      tags:
        - ScheduleSeries
  /api/Account:
    get:
      operationId: Account_Get
      security:
        - oauth2:
            - read_account
      summary: Account Details
      tags:
        - Account
  /api/Bill:
    get:
      description: 'TransactionStatusCode values are: "Draft", "Verified", "Late", "Paid", "Partial", "Void"'
      operationId: Bill_Get
      security:
        - oauth2:
            - read_financials
      summary: Gets list of Bills
      tags:
        - Bill
    post:
      operationId: Bill_Post
      security:
        - oauth2:
            - write_financials
      summary: Create a new draft Bill
      tags:
        - Bill
  "/api/Bill/{id}":
    get:
      operationId: Bill_GetByID
      security:
        - oauth2:
            - read_financials
      summary: Gets a Bill by Bill ID
      tags:
        - Bill
  /api/BillPayment:
    get:
      operationId: BillPayment_Get
      security:
        - oauth2:
            - read_financials
      summary: Gets list of Bill Payments
      tags:
        - BillPayment
    post:
      operationId: BillPayment_Post
      security:
        - oauth2:
            - write_financials
      summary: Create new Bill Payment and optionally assign payment allocations to Bills
      tags:
        - BillPayment
  "/api/BillPayment/{id}":
    get:
      operationId: BillPayment_GetByID
      security:
        - oauth2:
            - read_financials
      summary: Gets a Bill Payment by Payment Transaction ID
      tags:
        - BillPayment
  /api/Company:
    get:
      operationId: Company_Get
      security:
        - oauth2:
            - read_contacts
      summary: Gets list of Companies
      tags:
        - Company
    post:
      operationId: Company_Post
      security:
        - oauth2:
            - write_contacts
      summary: Create a Company
      tags:
        - Company
    put:
      description: Requires CompanyID and a list of field names to update. The FieldsToUpdate field accepts a string array containing field names that should be updated.
      operationId: Company_Put
      security:
        - oauth2:
            - write_contacts
      summary: Update a Company record.
      tags:
        - Company
  /api/Company/Lookup:
    get:
      description: Certain roles see a restricted set of companies based on their project memberships
      operationId: CompanyLookup
      security:
        - oauth2:
            - read_contacts
      summary: Gets minimal list of Companies.
      tags:
        - Company
  "/api/Company/{id}":
    get:
      operationId: Company_GetByID
      security:
        - oauth2:
            - read_contacts
      summary: Gets Company by Company ID
      tags:
        - Company
  /api/Contact:
    get:
      operationId: Contact_Get
      security:
        - oauth2:
            - read_contacts
      summary: Gets list of Contacts
      tags:
        - Contact
    post:
      operationId: Contact_Post
      security:
        - oauth2:
            - write_contacts
      summary: Create a Contact
      tags:
        - Contact
  "/api/Contact/{id}":
    get:
      operationId: Contact_GetByID
      security:
        - oauth2:
            - read_contacts
      summary: Gets Contact by Contact ID
      tags:
        - Contact
  /api/CreditNote:
    get:
      operationId: CreditNote_Get
      security:
        - oauth2:
            - read_financials
      summary: Gets list of CreditNotes
      tags:
        - CreditNote
  "/api/CreditNote/{id}":
    get:
      operationId: CreditNote_GetByID
      security:
        - oauth2:
            - read_financials
      summary: Gets Credit Note by CreditNoteID
      tags:
        - CreditNote
  /api/Currency:
    get:
      operationId: Currency_Get
      summary: Gets list of Currencies
      tags:
        - Currency
  /api/Estimate:
    get:
      description: 'EstimateStatusCode values are: "Draft", "Sent", "Accepted", "Converted", "Expired", "Rejected"'
      operationId: Estimate_Get
      security:
        - oauth2:
            - read_financials
      summary: Gets list of Estimates
      tags:
        - Estimate
    post:
      operationId: Estimate_Post
      security:
        - oauth2:
            - write_financials
      summary: Create a new draft Estimate
      tags:
        - Estimate
  "/api/Estimate/{id}":
    get:
      operationId: Estimate_GetByID
      security:
        - oauth2:
            - read_financials
      summary: Gets Estimate by Estimate ID
      tags:
        - Estimate
  /api/Expense:
    delete:
      operationId: Expense_Delete
      security:
        - oauth2:
            - write_expenses
      summary: Delete a Timesheet Entry
      tags:
        - Expense
    get:
      operationId: Expense_Get
      security:
        - oauth2:
            - read_expenses
      summary: Gets list of Expenses
      tags:
        - Expense
    post:
      description: Create an Expense
      operationId: Expense_Post
      security:
        - oauth2:
            - write_expenses
      summary: Create an Expense
      tags:
        - Expense
    put:
      description: Update an Expense
      operationId: Expense_Put
      security:
        - oauth2:
            - write_expenses
      summary: Update an Expense
      tags:
        - Expense
  /api/Expense/Attachment:
    post:
      operationId: ExpenseAttachment
      security:
        - oauth2:
            - write_expenses
      tags:
        - Expense
  "/api/Expense/{id}":
    get:
      operationId: Expense_GetByID
      security:
        - oauth2:
            - read_expenses
      summary: Gets an Expense Entry by Expense ID
      tags:
        - Expense
  /api/ExpenseApproval/Submit:
    post:
      operationId: ExpenseApproval
      security:
        - oauth2:
            - write_expenses
      summary: Submit Expenses for Approval.
      tags:
        - Expense
  /api/ExpenseCategory:
    get:
      description: The default sort order is by Name asc
      operationId: ExpenseCategory_Get
      security:
        - oauth2:
            - read_expenses
      summary: Gets list of Expense Categories
      tags:
        - ExpenseCategory
  /api/ExpenseGroup/Lookup:
    get:
      description: Expense Groups are for adhoc grouping of reported expenses. e.g. for expenses incurred on a Trip
      operationId: ExpenseGroupLookup
      security:
        - oauth2:
            - read_expenses
      summary: Gets minimal list of Expense Groups.
      tags:
        - ExpenseGroup
  /api/ExpenseMerchant/Lookup:
    get:
      operationId: ExpenseMerchangeLookup
      security:
        - oauth2:
            - read_expenses
      summary: Gets minimal list of Expense Merchants.
      tags:
        - ExpenseMerchant
  /api/ExpensePaymentMethod/Lookup:
    get:
      operationId: ExpensePaymentMethodLookup
      security:
        - oauth2:
            - read_expenses
      summary: Gets minimal list of Expense Payment Methods.
      tags:
        - ExpensePaymentMethod
  /api/ExpenseSummary:
    get:
      operationId: ExpenseSummary_Get
      security:
        - oauth2:
            - read_expenses
      summary: Gets Basic Summary of Expense Statistics
      tags:
        - ExpenseSummary
  /api/FixedAmount:
    get:
      operationId: FixedAmount_Get
      security:
        - oauth2:
            - read_financials
      summary: Gets list of Fixed Amounts
      tags:
        - FixedAmount
  /api/Inventory:
    get:
      description: ""
      operationId: Inventory_Get
      security:
        - oauth2:
            - read_financials
      summary: Gets list of Inventory
      tags:
        - Inventory
  "/api/Inventory/{id}":
    get:
      operationId: Inventory_GetByID
      security:
        - oauth2:
            - read_financials
      summary: Gets InventoryItem by InventoryItem ID
      tags:
        - Inventory
  /api/Invoice:
    get:
      description: 'TransactionStatusCode values are: "Draft", "Sent", "Late", "Paid", "Partial", "Void"'
      operationId: Invoice_Get
      security:
        - oauth2:
            - read_financials
      summary: Gets list of Invoices
      tags:
        - Invoice
    post:
      operationId: Invoice_Post
      security:
        - oauth2:
            - write_financials
      summary: Create a new draft invoice
      tags:
        - Invoice
  "/api/Invoice/{id}":
    get:
      operationId: Invoice_GetByID
      security:
        - oauth2:
            - read_financials
      summary: Gets Invoice by Invoice ID
      tags:
        - Invoice
  /api/Payment:
    get:
      operationId: Payment_Get
      security:
        - oauth2:
            - read_financials
      summary: Gets list of Payments
      tags:
        - Payment
    post:
      operationId: Payment_Post
      security:
        - oauth2:
            - write_financials
      summary: Create new Payment and optionally assign payment allocations to Invoices
      tags:
        - Payment
  "/api/Payment/{id}":
    get:
      operationId: Payment_GetByID
      security:
        - oauth2:
            - read_financials
      summary: Gets Payment by Payment Transaction ID
      tags:
        - Payment
  /api/Project:
    get:
      operationId: Project_Get
      security:
        - oauth2:
            - read_projects
      summary: Gets list of Projects
      tags:
        - Project
    post:
      operationId: Project_Post
      security:
        - oauth2:
            - write_projects
      summary: Create a Project
      tags:
        - Project
    put:
      description: Update a Project
      operationId: Project_Put
      security:
        - oauth2:
            - write_projects
      summary: Update an Project
      tags:
        - Project
  /api/Project/Lookup:
    get:
      operationId: ProjectLookup
      security:
        - oauth2:
            - read_projects
      summary: Gets minimal list of active Projects for the current user
      tags:
        - Project
  "/api/Project/{id}":
    get:
      operationId: Project_GetByID
      security:
        - oauth2:
            - read_projects
      summary: Gets Project by Project ID
      tags:
        - Project
  /api/ProjectMember:
    get:
      description: Include at least one of ProjectID or UserID parameters.
      operationId: ProjectMember_Get
      security:
        - oauth2:
            - read_projects
      summary: Gets list of Project Members
      tags:
        - ProjectMember
    post:
      description: the Amount columns for Cost, Budget, Rates should be specified as a decimal. Financial amounts assume the currency of the Customer company. Budget units depend on the Budget method set on the Project.
      operationId: ProjectMember_Post
      security:
        - oauth2:
            - write_projects
      summary: Assign a user as a Member of a Project
      tags:
        - ProjectMember
    put:
      description: Fields are only updated if their field name is in the FieldsToUpdate string collection. The Amount columns for Cost, Budget, Rates if specified should be a decimal. Financial amounts assume the currency of the parent Company. Budget units depend on the Budget method set on the Project.
      operationId: ProjectMember_Put
      security:
        - oauth2:
            - write_projects
      summary: Update a Member of a Project
      tags:
        - ProjectMember
  /api/ProjectTimesheetCategory:
    get:
      description: The default sort order is by isBillable desc, Name asc
      operationId: ProjectTimesheetCategory_Get
      security:
        - oauth2:
            - read_timesheets
      summary: Gets list of Project Timesheet Categories
      tags:
        - ProjectTimesheetCategory
    post:
      description: ""
      operationId: ProjectTimesheetCategory_Post
      security:
        - oauth2:
            - write_projects
      summary: Assign a TimeSheetCategory to a Project.
      tags:
        - ProjectTimesheetCategory
  /api/ScheduleAssignment:
    get:
      description: Schedule assignments are per-day, and link to a parent Schedule Series.
      operationId: ScheduleAssignment_Get
      security:
        - oauth2:
            - read_schedule
      summary: Gets list of Schedule Assignments.
      tags:
        - ScheduleAssignment
  /api/ScheduleSeries:
    get:
      description: Schedule Series represents a strip of time assigned to a user over a date range, for a certain number of hours per day. They can be for Leave or for project work Bookings.
      operationId: ScheduleSeries_Get
      security:
        - oauth2:
            - read_schedule
      summary: Gets list of Schedule Series
      tags:
        - ScheduleSeries
  /api/Section:
    delete:
      operationId: Section_Delete
      security:
        - oauth2:
            - write_projects
      summary: Delete a Section
      tags:
        - Section
    get:
      operationId: Section_Get
      security:
        - oauth2:
            - read_projects
      summary: Gets list of Sections
      tags:
        - Section
    post:
      operationId: Section_Post
      security:
        - oauth2:
            - write_projects
      summary: Create a Section
      tags:
        - Section
  /api/Task:
    delete:
      operationId: Task_Delete
      security:
        - oauth2:
            - write_projects
      summary: Delete a Task
      tags:
        - Task
    get:
      operationId: Task_Get
      security:
        - oauth2:
            - read_projects
      summary: Gets list of Tasks
      tags:
        - Task
    post:
      operationId: Task_Post
      security:
        - oauth2:
            - write_projects
      summary: Create a Task
      tags:
        - Task
    put:
      description: Requires TaskID and a list of field names to update. The FieldsToUpdate field accepts a string array containing field names that should be updated.
      operationId: Task_Put
      security:
        - oauth2:
            - write_projects
      summary: Update a Task.
      tags:
        - Task
  /api/Task/Lookup:
    get:
      description: Groups Tasks by Section. Default sort is by Section Title followed by Task Title
      operationId: TaskLookup
      security:
        - oauth2:
            - read_projects
      summary: Gets minimal list of Tasks for the current user
      tags:
        - Task
  "/api/Task/{id}":
    get:
      operationId: Task_GetByID
      security:
        - oauth2:
            - read_projects
      summary: Gets Task by Task ID
      tags:
        - Task
  /api/TaskStatus:
    get:
      operationId: TaskStatus_Get
      security:
        - oauth2:
            - read_projects
      summary: Gets list of Task Statuses
      tags:
        - TaskStatus
  /api/TaskType:
    get:
      operationId: TaskType_Get
      security:
        - oauth2:
            - read_projects
      summary: Gets list of Task Types
      tags:
        - TaskType
  /api/Tax:
    get:
      operationId: Tax_Get
      security:
        - oauth2:
            - read_financials
      summary: Get List of Taxes configured in the Avaza account.
      tags:
        - Tax
  /api/Timesheet:
    get:
      operationId: Timesheet_Get
      security:
        - oauth2:
            - read_timesheets
      summary: Gets list of Timsheets
      tags:
        - Timesheet
    post:
      operationId: Timesheet_Post
      security:
        - oauth2:
            - write_timesheets
      summary: Create a new Timesheet Entry
      tags:
        - Timesheet
    put:
      description: The FieldsToUpdate field expects a string array collection of the field names you would like updated. Valid fields to update inlcude "ProjectIDFK", "TimeSheetCategoryIDFK", "TaskIDFK", "Duration", "EntryDate", "Notes", "hasStartEndTime", "CustomMetadata". If you intend to provide start/end times on timesheets, this is achieved by including the start time in the EntryDate field (Iso date format), along with a Duration (decimal format).
      operationId: Timesheet_Put
      security:
        - oauth2:
            - write_timesheets
      summary: Update a Timesheet
      tags:
        - Timesheet
  "/api/Timesheet/{id}":
    delete:
      operationId: Timesheet_Delete
      security:
        - oauth2:
            - write_timesheets
      summary: Delete a Timesheet Entry
      tags:
        - Timesheet
    get:
      operationId: Timesheet_GetByID
      security:
        - oauth2:
            - read_timesheets
      summary: Gets a Timesheet Entry by Timesheet ID
      tags:
        - Timesheet
  /api/TimesheetSubmission:
    post:
      description: Either provide a a specific Day (WholeDayOf) or any day in a Week (WholeWeekOf) to submit all draft timesheets in that day or week
      operationId: TimesheetSubmission_Post
      security:
        - oauth2:
            - write_timesheets
      summary: Submit Timesheets for Approval.
      tags:
        - TimesheetSubmission
  /api/TimesheetSummary:
    get:
      operationId: TimesheetSummary_Get
      security:
        - oauth2:
            - read_timesheets
      summary: Gets Basic Summary of Timesheet Statistics
      tags:
        - TimesheetSummary
  /api/TimesheetTimer:
    get:
      operationId: TimesheetTimer_GetRunningTimer
      security:
        - oauth2:
            - read_timesheets
      summary: Gets the  Running Timer if there is one for a user.
      tags:
        - TimesheetTimer
  "/api/TimesheetTimer/{id}":
    delete:
      operationId: TimesheetTimer_StopTimer
      security:
        - oauth2:
            - write_timesheets
      summary: Stop the timer running on an existing Timesheet Entry
      tags:
        - TimesheetTimer
    post:
      operationId: TimesheetTimer_StartTimer
      security:
        - oauth2:
            - write_timesheets
      summary: Starts a Timer running on an existing Timesheet Entry
      tags:
        - TimesheetTimer
  /api/UserProfile:
    get:
      description: Admin and Invoice Managers can see all. Other users are limited to seeing their own profile.
      operationId: UserProfile_Get
      security:
        - oauth2:
            - read_users
      summary: Get Collection of Users who have roles in the current Avaza account.
      tags:
        - UserProfile
  /api/Webhook:
    delete:
      operationId: Webhook_DeleteByUrl
      security:
        - oauth2:
            - webhook_notifications
      summary: Delete webhook subscription by URL
      tags:
        - Webhook
    get:
      operationId: Webhook_Get
      security:
        - oauth2:
            - webhook_notifications
      summary: Get list of Webhook Subscriptions
      tags:
        - Webhook
    post:
      description: 'When you receive a webhook, you should respond with Http 200 OK Status Code, otherwise we will retry. To create a webhook, you need both the webhook_notifications scope, as well as the scope for the required entity being monitored.  Event values are: "company_created", "company_deleted", "company_updated", "contact_created", "contact_deleted", "contact_updated", "invoice_created", "invoice_sent","invoice_updated","invoice_deleted", "project_created", "project_deleted", "proje[...]'
      operationId: Webhook_Post
      security:
        - oauth2:
            - webhook_notifications
            - read_contacts
            - read_account
            - read_users
            - read_financials
            - read_projects
            - read_schedule
            - read_timesheets
            - read_expenses
            - write_contacts
            - write_account
            - write_users
            - write_financials
            - write_projects
            - write_schedule
            - write_timesheets
            - write_expenses
      summary: Subscribe to Webhook. On success, returns ID of webhook subscription.
      tags:
        - Webhook
  "/api/Webhook/{id}":
    delete:
      operationId: Webhook_Delete
      security:
        - oauth2:
            - webhook_notifications
      summary: Delete Webhook Subscription by ID
      tags:
        - Webhook
    get:
      operationId: Webhook_GetByID
      security:
        - oauth2:
            - webhook_notifications
      summary: Get Webhook Subscription by SubscriptionID
      tags:
        - Webhook