swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /appsactivity/v1
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Provides a historical view of activity.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: G Suite Activity
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/appsactivity/v1/rest'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: appsactivity
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/activity': View the activity history of your Google apps
      'https://www.googleapis.com/auth/drive': View and manage the files in your Google Drive
      'https://www.googleapis.com/auth/drive.metadata': View and manage metadata of files in your Google Drive
      'https://www.googleapis.com/auth/drive.metadata.readonly': View metadata for files in your Google Drive
      'https://www.googleapis.com/auth/drive.readonly': View the files in your Google Drive
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/activity': View the activity history of your Google apps
      'https://www.googleapis.com/auth/drive': View and manage the files in your Google Drive
      'https://www.googleapis.com/auth/drive.metadata': View and manage metadata of files in your Google Drive
      'https://www.googleapis.com/auth/drive.metadata.readonly': View metadata for files in your Google Drive
      'https://www.googleapis.com/auth/drive.readonly': View the files in your Google Drive
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: activities
paths:
  /activities:
    get:
      description: 'Returns a list of activities visible to the current logged in user. Visible activities are determined by the visiblity settings of the object that was acted on, e.g. Drive files a user can see. An activity is a record of past events. Multiple events may be merged if they are similar. A request is scoped to activities from a given Google service using the source parameter.'
      operationId: appsactivity.activities.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/activity'
          Oauth2c:
            - 'https://www.googleapis.com/auth/activity'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.metadata.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.metadata.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.readonly'
      tags:
        - activities