# coding: utf-8

"""
    ComputeManagementClient

    The Compute Management Client.

    The version of the OpenAPI document: 2019-03-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.hyper_v_generation_type import HyperVGenerationType

class TestHyperVGenerationType(unittest.TestCase):
    """HyperVGenerationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHyperVGenerationType(self):
        """Test HyperVGenerationType"""
        # inst = HyperVGenerationType()

if __name__ == '__main__':
    unittest.main()
