from .allocatestaticip import *
from .attachcertificatetodistribution import *
from .attachdisk import *
from .attachinstancestoloadbalancer import *
from .attachloadbalancertlscertificate import *
from .attachstaticip import *
from .closeinstancepublicports import *
from .copysnapshot import *
from .createbucket import *
from .createbucketaccesskey import *
from .createcertificate import *
from .createcloudformationstack import *
from .createcontactmethod import *
from .createcontainerservice import *
from .createcontainerservicedeployment import *
from .createcontainerserviceregistrylogin import *
from .createdisk import *
from .creatediskfromsnapshot import *
from .createdisksnapshot import *
from .createdistribution import *
from .createdomain import *
from .createdomainentry import *
from .createinstances import *
from .createinstancesfromsnapshot import *
from .createinstancesnapshot import *
from .createkeypair import *
from .createloadbalancer import *
from .createloadbalancertlscertificate import *
from .createrelationaldatabase import *
from .createrelationaldatabasefromsnapshot import *
from .createrelationaldatabasesnapshot import *
from .deletealarm import *
from .deleteautosnapshot import *
from .deletebucket import *
from .deletebucketaccesskey import *
from .deletecertificate import *
from .deletecontactmethod import *
from .deletecontainerimage import *
from .deletecontainerservice import *
from .deletedisk import *
from .deletedisksnapshot import *
from .deletedistribution import *
from .deletedomain import *
from .deletedomainentry import *
from .deleteinstance import *
from .deleteinstancesnapshot import *
from .deletekeypair import *
from .deleteknownhostkeys import *
from .deleteloadbalancer import *
from .deleteloadbalancertlscertificate import *
from .deleterelationaldatabase import *
from .deleterelationaldatabasesnapshot import *
from .detachcertificatefromdistribution import *
from .detachdisk import *
from .detachinstancesfromloadbalancer import *
from .detachstaticip import *
from .disableaddon import *
from .downloaddefaultkeypair import *
from .enableaddon import *
from .exportsnapshot import *
from .getactivenames import *
from .getalarms import *
from .getautosnapshots import *
from .getblueprints import *
from .getbucketaccesskeys import *
from .getbucketbundles import *
from .getbucketmetricdata import *
from .getbuckets import *
from .getbundles import *
from .getcertificates import *
from .getcloudformationstackrecords import *
from .getcontactmethods import *
from .getcontainerapimetadata import *
from .getcontainerimages import *
from .getcontainerlog import *
from .getcontainerservicedeployments import *
from .getcontainerservicemetricdata import *
from .getcontainerservicepowers import *
from .getcontainerservices import *
from .getdisk import *
from .getdisks import *
from .getdisksnapshot import *
from .getdisksnapshots import *
from .getdistributionbundles import *
from .getdistributionlatestcachereset import *
from .getdistributionmetricdata import *
from .getdistributions import *
from .getdomain import *
from .getdomains import *
from .getexportsnapshotrecords import *
from .getinstance import *
from .getinstanceaccessdetails import *
from .getinstancemetricdata import *
from .getinstanceportstates import *
from .getinstances import *
from .getinstancesnapshot import *
from .getinstancesnapshots import *
from .getinstancestate import *
from .getkeypair import *
from .getkeypairs import *
from .getloadbalancer import *
from .getloadbalancermetricdata import *
from .getloadbalancers import *
from .getloadbalancertlscertificates import *
from .getoperation import *
from .getoperations import *
from .getoperationsforresource import *
from .getregions import *
from .getrelationaldatabase import *
from .getrelationaldatabaseblueprints import *
from .getrelationaldatabasebundles import *
from .getrelationaldatabaseevents import *
from .getrelationaldatabaselogevents import *
from .getrelationaldatabaselogstreams import *
from .getrelationaldatabasemasteruserpassword import *
from .getrelationaldatabasemetricdata import *
from .getrelationaldatabaseparameters import *
from .getrelationaldatabases import *
from .getrelationaldatabasesnapshot import *
from .getrelationaldatabasesnapshots import *
from .getstaticip import *
from .getstaticips import *
from .importkeypair import *
from .isvpcpeered import *
from .openinstancepublicports import *
from .peervpc import *
from .putalarm import *
from .putinstancepublicports import *
from .rebootinstance import *
from .rebootrelationaldatabase import *
from .registercontainerimage import *
from .releasestaticip import *
from .resetdistributioncache import *
from .sendcontactmethodverification import *
from .setipaddresstype import *
from .setresourceaccessforbucket import *
from .startinstance import *
from .startrelationaldatabase import *
from .stopinstance import *
from .stoprelationaldatabase import *
from .tagresource import *
from .testalarm import *
from .unpeervpc import *
from .untagresource import *
from .updatebucket import *
from .updatebucketbundle import *
from .updatecontainerservice import *
from .updatedistribution import *
from .updatedistributionbundle import *
from .updatedomainentry import *
from .updateloadbalancerattribute import *
from .updaterelationaldatabase import *
from .updaterelationaldatabaseparameters import *
