from .speech_operations_get import *
from .speech_operations_list import *
from .speech_projects_locations_customclasses_create import *
from .speech_projects_locations_customclasses_list import *
from .speech_projects_locations_phrasesets_create import *
from .speech_projects_locations_phrasesets_delete import *
from .speech_projects_locations_phrasesets_get import *
from .speech_projects_locations_phrasesets_list import *
from .speech_projects_locations_phrasesets_patch import *
from .speech_speech_longrunningrecognize import *
from .speech_speech_recognize import *
