package shared

type GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipMembershipEnum string

const (
	GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipMembershipEnumMembershipUnspecified        GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipMembershipEnum = "MEMBERSHIP_UNSPECIFIED"
	GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipMembershipEnumMembershipIncluded           GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipMembershipEnum = "MEMBERSHIP_INCLUDED"
	GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipMembershipEnumMembershipNotIncluded        GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipMembershipEnum = "MEMBERSHIP_NOT_INCLUDED"
	GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipMembershipEnumMembershipUnknownInfoDenied  GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipMembershipEnum = "MEMBERSHIP_UNKNOWN_INFO_DENIED"
	GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipMembershipEnumMembershipUnknownUnsupported GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipMembershipEnum = "MEMBERSHIP_UNKNOWN_UNSUPPORTED"
)

type GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipRelevanceEnum string

const (
	GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipRelevanceEnumHeuristicRelevanceUnspecified GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipRelevanceEnum = "HEURISTIC_RELEVANCE_UNSPECIFIED"
	GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipRelevanceEnumNormal                        GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipRelevanceEnum = "NORMAL"
	GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipRelevanceEnumHigh                          GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipRelevanceEnum = "HIGH"
)

type GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembership struct {
	Membership *GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipMembershipEnum `json:"membership,omitempty"`
	Relevance  *GoogleCloudPolicytroubleshooterV1BindingExplanationAnnotatedMembershipRelevanceEnum  `json:"relevance,omitempty"`
}
