from .addfieldstotemplate import *
from .batchgeneratepdfs import *
from .batchgeneratepdfv1 import *
from .combinepdfs import *
from .combinesubmissions import *
from .copytemplate import *
from .createcustomfilefromupload import *
from .createdatarequesttoken import *
from .createfolder import *
from .createhtmltemplate import *
from .createpdftemplate import *
from .createpdftemplatefromupload import *
from .deletefolder import *
from .expirecombinedsubmission import *
from .expiresubmission import *
from .generatepdf import *
from .getcombinedsubmission import *
from .getdatarequest import *
from .getpresignurl import *
from .getsubmission import *
from .getsubmissionbatch import *
from .gettemplate import *
from .gettemplateschema import *
from .listfolders import *
from .listtemplates import *
from .movefoldertofolder import *
from .movetemplatetofolder import *
from .renamefolder import *
from .testauthentication import *
from .updatedatarequest import *
from .updatetemplate import *
