# coding: utf-8

"""
    Dialogflow API

    Builds conversational interfaces (for example, chatbots, and voice-powered apps and devices).

    The version of the OpenAPI document: v3beta1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.google_cloud_dialogflow_v2_intent_message_table_card_cell import GoogleCloudDialogflowV2IntentMessageTableCardCell

class TestGoogleCloudDialogflowV2IntentMessageTableCardCell(unittest.TestCase):
    """GoogleCloudDialogflowV2IntentMessageTableCardCell unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GoogleCloudDialogflowV2IntentMessageTableCardCell:
        """Test GoogleCloudDialogflowV2IntentMessageTableCardCell
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GoogleCloudDialogflowV2IntentMessageTableCardCell`
        """
        model = GoogleCloudDialogflowV2IntentMessageTableCardCell()
        if include_optional:
            return GoogleCloudDialogflowV2IntentMessageTableCardCell(
                text = ''
            )
        else:
            return GoogleCloudDialogflowV2IntentMessageTableCardCell(
        )
        """

    def testGoogleCloudDialogflowV2IntentMessageTableCardCell(self):
        """Test GoogleCloudDialogflowV2IntentMessageTableCardCell"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
