from dataclasses import dataclass, field
from typing import Enum

class AssessmentRunStateEnum(str, Enum):
    CREATED = "CREATED"
    START_DATA_COLLECTION_PENDING = "START_DATA_COLLECTION_PENDING"
    START_DATA_COLLECTION_IN_PROGRESS = "START_DATA_COLLECTION_IN_PROGRESS"
    COLLECTING_DATA = "COLLECTING_DATA"
    STOP_DATA_COLLECTION_PENDING = "STOP_DATA_COLLECTION_PENDING"
    DATA_COLLECTED = "DATA_COLLECTED"
    START_EVALUATING_RULES_PENDING = "START_EVALUATING_RULES_PENDING"
    EVALUATING_RULES = "EVALUATING_RULES"
    FAILED = "FAILED"
    ERROR = "ERROR"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_ERRORS = "COMPLETED_WITH_ERRORS"
    CANCELED = "CANCELED"

