openapi: 3.0.0
servers:
  - url: 'https://www.googleapis.com/games/v1'
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: The API for Google Play Game Services.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Google Play Game Services
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.gstatic.com/images/icons/material/product/2x/play_games_64dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/games/v1/rest'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: games
tags:
  - name: achievementDefinitions
  - name: achievements
  - name: applications
  - name: events
  - name: leaderboards
  - name: metagame
  - name: players
  - name: pushtokens
  - name: questMilestones
  - name: quests
  - name: revisions
  - name: rooms
  - name: scores
  - name: snapshots
  - name: turnBasedMatches
paths:
  /achievements:
    get:
      description: Lists all the achievement definitions for your application.
      operationId: games.achievementDefinitions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - achievementDefinitions
  /achievements/updateMultiple:
    post:
      description: Updates multiple achievements for the currently authenticated player.
      operationId: games.achievements.updateMultiple
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - achievements
  '/achievements/{achievementId}/increment':
    post:
      description: Increments the steps of the achievement with the given ID for the currently authenticated player.
      operationId: games.achievements.increment
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - achievements
  '/achievements/{achievementId}/reveal':
    post:
      description: Sets the state of the achievement with the given ID to REVEALED for the currently authenticated player.
      operationId: games.achievements.reveal
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - achievements
  '/achievements/{achievementId}/setStepsAtLeast':
    post:
      description: 'Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified.'
      operationId: games.achievements.setStepsAtLeast
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - achievements
  '/achievements/{achievementId}/unlock':
    post:
      description: Unlocks this achievement for the currently authenticated player.
      operationId: games.achievements.unlock
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - achievements
  /applications/played:
    post:
      description: Indicate that the the currently authenticated user is playing your application.
      operationId: games.applications.played
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - applications
  '/applications/{applicationId}':
    get:
      description: 'Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified platformType, the returned response will not include any instance data.'
      operationId: games.applications.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - applications
  '/applications/{applicationId}/verify':
    get:
      description: 'Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for.'
      operationId: games.applications.verify
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - applications
  /eventDefinitions:
    get:
      description: Returns a list of the event definitions in this application.
      operationId: games.events.listDefinitions
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - events
  /events:
    get:
      description: Returns a list showing the current progress on events in this application for the currently authenticated user.
      operationId: games.events.listByPlayer
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - events
    post:
      description: Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application.
      operationId: games.events.record
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - events
  /leaderboards:
    get:
      description: Lists all the leaderboard metadata for your application.
      operationId: games.leaderboards.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - leaderboards
  /leaderboards/scores:
    post:
      description: Submits multiple scores to leaderboards.
      operationId: games.scores.submitMultiple
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - scores
  '/leaderboards/{leaderboardId}':
    get:
      description: Retrieves the metadata of the leaderboard with the given ID.
      operationId: games.leaderboards.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - leaderboards
  '/leaderboards/{leaderboardId}/scores':
    post:
      description: Submits a score to the specified leaderboard.
      operationId: games.scores.submit
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - scores
  '/leaderboards/{leaderboardId}/scores/{collection}':
    get:
      description: 'Lists the scores in a leaderboard, starting from the top.'
      operationId: games.scores.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - scores
  '/leaderboards/{leaderboardId}/window/{collection}':
    get:
      description: Lists the scores in a leaderboard around (and including) a player's score.
      operationId: games.scores.listWindow
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - scores
  /metagameConfig:
    get:
      description: Return the metagame configuration data for the calling application.
      operationId: games.metagame.getMetagameConfig
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - metagame
  '/players/me/players/{collection}':
    get:
      description: Get the collection of players for the currently authenticated user.
      operationId: games.players.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - players
  '/players/{playerId}':
    get:
      description: 'Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set playerId to me.'
      operationId: games.players.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - players
  '/players/{playerId}/achievements':
    get:
      description: Lists the progress for all your application's achievements for the currently authenticated player.
      operationId: games.achievements.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - achievements
  '/players/{playerId}/categories/{collection}':
    get:
      description: List play data aggregated per category for the player corresponding to playerId.
      operationId: games.metagame.listCategoriesByPlayer
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - metagame
  '/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}':
    get:
      description: |-
        Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, leaderboardId can be set to ALL to retrieve data for all leaderboards in a given time span.
        NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'.
      operationId: games.scores.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - scores
  '/players/{playerId}/quests':
    get:
      description: Get a list of quests for your application and the currently authenticated player.
      operationId: games.quests.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - quests
  '/players/{playerId}/snapshots':
    get:
      description: Retrieves a list of snapshots created by your application for the player corresponding to the player ID.
      operationId: games.snapshots.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.appdata'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.appdata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - snapshots
  /pushtokens:
    put:
      description: Registers a push token for the current user and application.
      operationId: games.pushtokens.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - pushtokens
  /pushtokens/remove:
    post:
      description: Removes a push token for the current user and application. Removing a non-existent push token will report success.
      operationId: games.pushtokens.remove
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - pushtokens
  '/quests/{questId}/accept':
    post:
      description: Indicates that the currently authorized user will participate in the quest.
      operationId: games.quests.accept
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - quests
  '/quests/{questId}/milestones/{milestoneId}/claim':
    put:
      description: Report that a reward for the milestone corresponding to milestoneId for the quest corresponding to questId has been claimed by the currently authorized user.
      operationId: games.questMilestones.claim
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - questMilestones
  /revisions/check:
    get:
      description: Checks whether the games client is out of date.
      operationId: games.revisions.check
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - revisions
  /rooms:
    get:
      description: Returns invitations to join rooms.
      operationId: games.rooms.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - rooms
  /rooms/create:
    post:
      description: Create a room. For internal use by the Games SDK only. Calling this method directly is unsupported.
      operationId: games.rooms.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - rooms
  '/rooms/{roomId}':
    get:
      description: Get the data for a room.
      operationId: games.rooms.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - rooms
  '/rooms/{roomId}/decline':
    post:
      description: Decline an invitation to join a room. For internal use by the Games SDK only. Calling this method directly is unsupported.
      operationId: games.rooms.decline
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - rooms
  '/rooms/{roomId}/dismiss':
    post:
      description: Dismiss an invitation to join a room. For internal use by the Games SDK only. Calling this method directly is unsupported.
      operationId: games.rooms.dismiss
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - rooms
  '/rooms/{roomId}/join':
    post:
      description: Join a room. For internal use by the Games SDK only. Calling this method directly is unsupported.
      operationId: games.rooms.join
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - rooms
  '/rooms/{roomId}/leave':
    post:
      description: Leave a room. For internal use by the Games SDK only. Calling this method directly is unsupported.
      operationId: games.rooms.leave
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - rooms
  '/rooms/{roomId}/reportstatus':
    post:
      description: Updates sent by a client reporting the status of peers in a room. For internal use by the Games SDK only. Calling this method directly is unsupported.
      operationId: games.rooms.reportStatus
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - rooms
  '/snapshots/{snapshotId}':
    get:
      description: Retrieves the metadata for a given snapshot ID.
      operationId: games.snapshots.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive.appdata'
          Oauth2c:
            - 'https://www.googleapis.com/auth/drive.appdata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - snapshots
  /turnbasedmatches:
    get:
      description: Returns turn-based matches the player is or was involved in.
      operationId: games.turnBasedMatches.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - turnBasedMatches
  /turnbasedmatches/create:
    post:
      description: Create a turn-based match.
      operationId: games.turnBasedMatches.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - turnBasedMatches
  /turnbasedmatches/sync:
    get:
      description: 'Returns turn-based matches the player is or was involved in that changed since the last sync call, with the least recent changes coming first. Matches that should be removed from the local cache will have a status of MATCH_DELETED.'
      operationId: games.turnBasedMatches.sync
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - turnBasedMatches
  '/turnbasedmatches/{matchId}':
    get:
      description: Get the data for a turn-based match.
      operationId: games.turnBasedMatches.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - turnBasedMatches
  '/turnbasedmatches/{matchId}/cancel':
    put:
      description: Cancel a turn-based match.
      operationId: games.turnBasedMatches.cancel
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - turnBasedMatches
  '/turnbasedmatches/{matchId}/decline':
    put:
      description: Decline an invitation to play a turn-based match.
      operationId: games.turnBasedMatches.decline
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - turnBasedMatches
  '/turnbasedmatches/{matchId}/dismiss':
    put:
      description: Dismiss a turn-based match from the match list. The match will no longer show up in the list and will not generate notifications.
      operationId: games.turnBasedMatches.dismiss
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - turnBasedMatches
  '/turnbasedmatches/{matchId}/finish':
    put:
      description: 'Finish a turn-based match. Each player should make this call once, after all results are in. Only the player whose turn it is may make the first call to Finish, and can pass in the final match state.'
      operationId: games.turnBasedMatches.finish
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - turnBasedMatches
  '/turnbasedmatches/{matchId}/join':
    put:
      description: Join a turn-based match.
      operationId: games.turnBasedMatches.join
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - turnBasedMatches
  '/turnbasedmatches/{matchId}/leave':
    put:
      description: 'Leave a turn-based match when it is not the current player''s turn, without canceling the match.'
      operationId: games.turnBasedMatches.leave
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - turnBasedMatches
  '/turnbasedmatches/{matchId}/leaveTurn':
    put:
      description: 'Leave a turn-based match during the current player''s turn, without canceling the match.'
      operationId: games.turnBasedMatches.leaveTurn
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - turnBasedMatches
  '/turnbasedmatches/{matchId}/rematch':
    post:
      description: 'Create a rematch of a match that was previously completed, with the same participants. This can be called by only one player on a match still in their list; the player must have called Finish first. Returns the newly created match; it will be the caller''s turn.'
      operationId: games.turnBasedMatches.rematch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - turnBasedMatches
  '/turnbasedmatches/{matchId}/turn':
    put:
      description: Commit the results of a player turn.
      operationId: games.turnBasedMatches.takeTurn
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/games'
          Oauth2c:
            - 'https://www.googleapis.com/auth/games'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
          Oauth2c:
            - 'https://www.googleapis.com/auth/plus.login'
      tags:
        - turnBasedMatches
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
          scopes:
            'https://www.googleapis.com/auth/drive.appdata': View and manage its own configuration data in your Google Drive
            'https://www.googleapis.com/auth/games': Share your Google+ profile information and view and manage your game activity
            'https://www.googleapis.com/auth/plus.login': 'Know the list of people in your circles, your age range, and language'
    Oauth2c:
      description: Oauth 2.0 accessCode authentication
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
          tokenUrl: 'https://accounts.google.com/o/oauth2/token'
          scopes:
            'https://www.googleapis.com/auth/drive.appdata': View and manage its own configuration data in your Google Drive
            'https://www.googleapis.com/auth/games': Share your Google+ profile information and view and manage your game activity
            'https://www.googleapis.com/auth/plus.login': 'Know the list of people in your circles, your age range, and language'
