from dataclasses import dataclass, field
from typing import List,Optional
from dataclasses_json import dataclass_json
from sdk.models import shared


@dataclass
class DcimDevicesListQueryParams:
    asset_tag: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'asset_tag', 'style': 'form', 'explode': True }})
    asset_tag_ic: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'asset_tag__ic', 'style': 'form', 'explode': True }})
    asset_tag_ie: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'asset_tag__ie', 'style': 'form', 'explode': True }})
    asset_tag_iew: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'asset_tag__iew', 'style': 'form', 'explode': True }})
    asset_tag_isw: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'asset_tag__isw', 'style': 'form', 'explode': True }})
    asset_tag_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'asset_tag__n', 'style': 'form', 'explode': True }})
    asset_tag_nic: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'asset_tag__nic', 'style': 'form', 'explode': True }})
    asset_tag_nie: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'asset_tag__nie', 'style': 'form', 'explode': True }})
    asset_tag_niew: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'asset_tag__niew', 'style': 'form', 'explode': True }})
    asset_tag_nisw: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'asset_tag__nisw', 'style': 'form', 'explode': True }})
    cluster_id: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'cluster_id', 'style': 'form', 'explode': True }})
    cluster_id_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'cluster_id__n', 'style': 'form', 'explode': True }})
    console_ports: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'console_ports', 'style': 'form', 'explode': True }})
    console_server_ports: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'console_server_ports', 'style': 'form', 'explode': True }})
    created: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'created', 'style': 'form', 'explode': True }})
    created_gte: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'created__gte', 'style': 'form', 'explode': True }})
    created_lte: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'created__lte', 'style': 'form', 'explode': True }})
    device_bays: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'device_bays', 'style': 'form', 'explode': True }})
    device_type_id: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'device_type_id', 'style': 'form', 'explode': True }})
    device_type_id_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'device_type_id__n', 'style': 'form', 'explode': True }})
    face: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'face', 'style': 'form', 'explode': True }})
    face_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'face__n', 'style': 'form', 'explode': True }})
    has_primary_ip: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'has_primary_ip', 'style': 'form', 'explode': True }})
    id: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'id', 'style': 'form', 'explode': True }})
    id_gt: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'id__gt', 'style': 'form', 'explode': True }})
    id_gte: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'id__gte', 'style': 'form', 'explode': True }})
    id_lt: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'id__lt', 'style': 'form', 'explode': True }})
    id_lte: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'id__lte', 'style': 'form', 'explode': True }})
    id_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'id__n', 'style': 'form', 'explode': True }})
    interfaces: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'interfaces', 'style': 'form', 'explode': True }})
    is_full_depth: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'is_full_depth', 'style': 'form', 'explode': True }})
    last_updated: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'last_updated', 'style': 'form', 'explode': True }})
    last_updated_gte: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'last_updated__gte', 'style': 'form', 'explode': True }})
    last_updated_lte: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'last_updated__lte', 'style': 'form', 'explode': True }})
    limit: Optional[int] = field(default=None, metadata={'query_param': { 'field_name': 'limit', 'style': 'form', 'explode': True }})
    local_context_data: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'local_context_data', 'style': 'form', 'explode': True }})
    mac_address: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'mac_address', 'style': 'form', 'explode': True }})
    mac_address_ic: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'mac_address__ic', 'style': 'form', 'explode': True }})
    mac_address_ie: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'mac_address__ie', 'style': 'form', 'explode': True }})
    mac_address_iew: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'mac_address__iew', 'style': 'form', 'explode': True }})
    mac_address_isw: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'mac_address__isw', 'style': 'form', 'explode': True }})
    mac_address_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'mac_address__n', 'style': 'form', 'explode': True }})
    mac_address_nic: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'mac_address__nic', 'style': 'form', 'explode': True }})
    mac_address_nie: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'mac_address__nie', 'style': 'form', 'explode': True }})
    mac_address_niew: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'mac_address__niew', 'style': 'form', 'explode': True }})
    mac_address_nisw: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'mac_address__nisw', 'style': 'form', 'explode': True }})
    manufacturer: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'manufacturer', 'style': 'form', 'explode': True }})
    manufacturer_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'manufacturer__n', 'style': 'form', 'explode': True }})
    manufacturer_id: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'manufacturer_id', 'style': 'form', 'explode': True }})
    manufacturer_id_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'manufacturer_id__n', 'style': 'form', 'explode': True }})
    model: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'model', 'style': 'form', 'explode': True }})
    model_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'model__n', 'style': 'form', 'explode': True }})
    name: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'name', 'style': 'form', 'explode': True }})
    name_ic: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'name__ic', 'style': 'form', 'explode': True }})
    name_ie: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'name__ie', 'style': 'form', 'explode': True }})
    name_iew: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'name__iew', 'style': 'form', 'explode': True }})
    name_isw: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'name__isw', 'style': 'form', 'explode': True }})
    name_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'name__n', 'style': 'form', 'explode': True }})
    name_nic: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'name__nic', 'style': 'form', 'explode': True }})
    name_nie: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'name__nie', 'style': 'form', 'explode': True }})
    name_niew: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'name__niew', 'style': 'form', 'explode': True }})
    name_nisw: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'name__nisw', 'style': 'form', 'explode': True }})
    offset: Optional[int] = field(default=None, metadata={'query_param': { 'field_name': 'offset', 'style': 'form', 'explode': True }})
    pass_through_ports: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'pass_through_ports', 'style': 'form', 'explode': True }})
    platform: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'platform', 'style': 'form', 'explode': True }})
    platform_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'platform__n', 'style': 'form', 'explode': True }})
    platform_id: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'platform_id', 'style': 'form', 'explode': True }})
    platform_id_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'platform_id__n', 'style': 'form', 'explode': True }})
    position: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'position', 'style': 'form', 'explode': True }})
    position_gt: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'position__gt', 'style': 'form', 'explode': True }})
    position_gte: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'position__gte', 'style': 'form', 'explode': True }})
    position_lt: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'position__lt', 'style': 'form', 'explode': True }})
    position_lte: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'position__lte', 'style': 'form', 'explode': True }})
    position_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'position__n', 'style': 'form', 'explode': True }})
    power_outlets: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'power_outlets', 'style': 'form', 'explode': True }})
    power_ports: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'power_ports', 'style': 'form', 'explode': True }})
    q: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'q', 'style': 'form', 'explode': True }})
    rack_group_id: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'rack_group_id', 'style': 'form', 'explode': True }})
    rack_group_id_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'rack_group_id__n', 'style': 'form', 'explode': True }})
    rack_id: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'rack_id', 'style': 'form', 'explode': True }})
    rack_id_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'rack_id__n', 'style': 'form', 'explode': True }})
    region: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'region', 'style': 'form', 'explode': True }})
    region_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'region__n', 'style': 'form', 'explode': True }})
    region_id: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'region_id', 'style': 'form', 'explode': True }})
    region_id_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'region_id__n', 'style': 'form', 'explode': True }})
    role: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'role', 'style': 'form', 'explode': True }})
    role_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'role__n', 'style': 'form', 'explode': True }})
    role_id: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'role_id', 'style': 'form', 'explode': True }})
    role_id_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'role_id__n', 'style': 'form', 'explode': True }})
    serial: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'serial', 'style': 'form', 'explode': True }})
    site: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'site', 'style': 'form', 'explode': True }})
    site_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'site__n', 'style': 'form', 'explode': True }})
    site_id: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'site_id', 'style': 'form', 'explode': True }})
    site_id_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'site_id__n', 'style': 'form', 'explode': True }})
    status: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'status', 'style': 'form', 'explode': True }})
    status_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'status__n', 'style': 'form', 'explode': True }})
    tag: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'tag', 'style': 'form', 'explode': True }})
    tag_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'tag__n', 'style': 'form', 'explode': True }})
    tenant: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'tenant', 'style': 'form', 'explode': True }})
    tenant_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'tenant__n', 'style': 'form', 'explode': True }})
    tenant_group: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'tenant_group', 'style': 'form', 'explode': True }})
    tenant_group_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'tenant_group__n', 'style': 'form', 'explode': True }})
    tenant_group_id: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'tenant_group_id', 'style': 'form', 'explode': True }})
    tenant_group_id_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'tenant_group_id__n', 'style': 'form', 'explode': True }})
    tenant_id: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'tenant_id', 'style': 'form', 'explode': True }})
    tenant_id_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'tenant_id__n', 'style': 'form', 'explode': True }})
    vc_position: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'vc_position', 'style': 'form', 'explode': True }})
    vc_position_gt: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'vc_position__gt', 'style': 'form', 'explode': True }})
    vc_position_gte: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'vc_position__gte', 'style': 'form', 'explode': True }})
    vc_position_lt: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'vc_position__lt', 'style': 'form', 'explode': True }})
    vc_position_lte: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'vc_position__lte', 'style': 'form', 'explode': True }})
    vc_position_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'vc_position__n', 'style': 'form', 'explode': True }})
    vc_priority: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'vc_priority', 'style': 'form', 'explode': True }})
    vc_priority_gt: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'vc_priority__gt', 'style': 'form', 'explode': True }})
    vc_priority_gte: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'vc_priority__gte', 'style': 'form', 'explode': True }})
    vc_priority_lt: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'vc_priority__lt', 'style': 'form', 'explode': True }})
    vc_priority_lte: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'vc_priority__lte', 'style': 'form', 'explode': True }})
    vc_priority_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'vc_priority__n', 'style': 'form', 'explode': True }})
    virtual_chassis_id: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'virtual_chassis_id', 'style': 'form', 'explode': True }})
    virtual_chassis_id_n: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'virtual_chassis_id__n', 'style': 'form', 'explode': True }})
    virtual_chassis_member: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'virtual_chassis_member', 'style': 'form', 'explode': True }})
    

@dataclass
class DcimDevicesListRequest:
    query_params: DcimDevicesListQueryParams = field(default=None)
    

@dataclass_json
@dataclass
class DcimDevicesList200ApplicationJSON:
    count: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'count' }})
    next: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'next' }})
    previous: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'previous' }})
    results: List[shared.DeviceWithConfigContext] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'results' }})
    

@dataclass
class DcimDevicesListResponse:
    content_type: str = field(default=None)
    status_code: int = field(default=None)
    dcim_devices_list_200_application_json_object: Optional[DcimDevicesList200ApplicationJSON] = field(default=None)
    
