from dataclasses import dataclass, field
from datetime import datetime
from marshmallow import fields
import dateutil.parser
from typing import List,Optional
from dataclasses_json import dataclass_json


@dataclass_json
@dataclass
class TeamRepositoryLicenseSimple:
    html_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'html_url' }})
    key: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'key' }})
    name: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'name' }})
    node_id: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'node_id' }})
    spdx_id: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'spdx_id' }})
    url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'url' }})
    

@dataclass_json
@dataclass
class TeamRepositorySimpleUser:
    avatar_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'avatar_url' }})
    events_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'events_url' }})
    followers_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'followers_url' }})
    following_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'following_url' }})
    gists_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'gists_url' }})
    gravatar_id: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'gravatar_id' }})
    html_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'html_url' }})
    id: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'id' }})
    login: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'login' }})
    node_id: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'node_id' }})
    organizations_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'organizations_url' }})
    received_events_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'received_events_url' }})
    repos_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'repos_url' }})
    site_admin: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'site_admin' }})
    starred_at: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'starred_at' }})
    starred_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'starred_url' }})
    subscriptions_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'subscriptions_url' }})
    type: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'type' }})
    url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'url' }})
    

@dataclass_json
@dataclass
class TeamRepositoryPermissions:
    admin: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'admin' }})
    maintain: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'maintain' }})
    pull: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'pull' }})
    push: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'push' }})
    triage: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'triage' }})
    

@dataclass_json
@dataclass
class TeamRepositoryRepositoryLicenseSimple:
    html_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'html_url' }})
    key: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'key' }})
    name: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'name' }})
    node_id: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'node_id' }})
    spdx_id: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'spdx_id' }})
    url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'url' }})
    

@dataclass_json
@dataclass
class TeamRepositoryRepositorySimpleUser:
    avatar_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'avatar_url' }})
    events_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'events_url' }})
    followers_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'followers_url' }})
    following_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'following_url' }})
    gists_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'gists_url' }})
    gravatar_id: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'gravatar_id' }})
    html_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'html_url' }})
    id: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'id' }})
    login: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'login' }})
    node_id: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'node_id' }})
    organizations_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'organizations_url' }})
    received_events_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'received_events_url' }})
    repos_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'repos_url' }})
    site_admin: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'site_admin' }})
    starred_at: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'starred_at' }})
    starred_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'starred_url' }})
    subscriptions_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'subscriptions_url' }})
    type: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'type' }})
    url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'url' }})
    

@dataclass_json
@dataclass
class TeamRepositoryRepositoryPermissions:
    admin: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'admin' }})
    maintain: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'maintain' }})
    pull: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'pull' }})
    push: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'push' }})
    triage: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'triage' }})
    

@dataclass_json
@dataclass
class TeamRepositoryRepositoryTemplateRepositoryOwner:
    avatar_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'avatar_url' }})
    events_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'events_url' }})
    followers_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'followers_url' }})
    following_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'following_url' }})
    gists_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'gists_url' }})
    gravatar_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'gravatar_id' }})
    html_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'html_url' }})
    id: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'id' }})
    login: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'login' }})
    node_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'node_id' }})
    organizations_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'organizations_url' }})
    received_events_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'received_events_url' }})
    repos_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'repos_url' }})
    site_admin: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'site_admin' }})
    starred_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'starred_url' }})
    subscriptions_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'subscriptions_url' }})
    type: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'type' }})
    url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'url' }})
    

@dataclass_json
@dataclass
class TeamRepositoryRepositoryTemplateRepositoryPermissions:
    admin: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'admin' }})
    pull: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'pull' }})
    push: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'push' }})
    

@dataclass_json
@dataclass
class TeamRepositoryRepositoryTemplateRepository:
    allow_merge_commit: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'allow_merge_commit' }})
    allow_rebase_merge: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'allow_rebase_merge' }})
    allow_squash_merge: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'allow_squash_merge' }})
    archive_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'archive_url' }})
    archived: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'archived' }})
    assignees_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'assignees_url' }})
    blobs_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'blobs_url' }})
    branches_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'branches_url' }})
    clone_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'clone_url' }})
    collaborators_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'collaborators_url' }})
    comments_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'comments_url' }})
    commits_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'commits_url' }})
    compare_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'compare_url' }})
    contents_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contents_url' }})
    contributors_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contributors_url' }})
    created_at: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'created_at' }})
    default_branch: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'default_branch' }})
    delete_branch_on_merge: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'delete_branch_on_merge' }})
    deployments_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'deployments_url' }})
    description: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'description' }})
    disabled: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'disabled' }})
    downloads_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'downloads_url' }})
    events_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'events_url' }})
    fork: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'fork' }})
    forks_count: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'forks_count' }})
    forks_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'forks_url' }})
    full_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'full_name' }})
    git_commits_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'git_commits_url' }})
    git_refs_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'git_refs_url' }})
    git_tags_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'git_tags_url' }})
    git_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'git_url' }})
    has_downloads: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'has_downloads' }})
    has_issues: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'has_issues' }})
    has_pages: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'has_pages' }})
    has_projects: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'has_projects' }})
    has_wiki: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'has_wiki' }})
    homepage: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'homepage' }})
    hooks_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'hooks_url' }})
    html_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'html_url' }})
    id: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'id' }})
    is_template: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'is_template' }})
    issue_comment_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'issue_comment_url' }})
    issue_events_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'issue_events_url' }})
    issues_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'issues_url' }})
    keys_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'keys_url' }})
    labels_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'labels_url' }})
    language: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'language' }})
    languages_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'languages_url' }})
    merges_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'merges_url' }})
    milestones_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'milestones_url' }})
    mirror_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'mirror_url' }})
    name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'name' }})
    network_count: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'network_count' }})
    node_id: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'node_id' }})
    notifications_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'notifications_url' }})
    open_issues_count: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'open_issues_count' }})
    owner: Optional[TeamRepositoryRepositoryTemplateRepositoryOwner] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'owner' }})
    permissions: Optional[TeamRepositoryRepositoryTemplateRepositoryPermissions] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'permissions' }})
    private: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'private' }})
    pulls_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'pulls_url' }})
    pushed_at: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'pushed_at' }})
    releases_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'releases_url' }})
    size: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'size' }})
    ssh_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'ssh_url' }})
    stargazers_count: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'stargazers_count' }})
    stargazers_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'stargazers_url' }})
    statuses_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'statuses_url' }})
    subscribers_count: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'subscribers_count' }})
    subscribers_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'subscribers_url' }})
    subscription_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'subscription_url' }})
    svn_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'svn_url' }})
    tags_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'tags_url' }})
    teams_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'teams_url' }})
    temp_clone_token: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'temp_clone_token' }})
    topics: Optional[List[str]] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'topics' }})
    trees_url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'trees_url' }})
    updated_at: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'updated_at' }})
    url: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'url' }})
    visibility: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'visibility' }})
    watchers_count: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'watchers_count' }})
    

@dataclass_json
@dataclass
class TeamRepositoryRepository:
    allow_merge_commit: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'allow_merge_commit' }})
    allow_rebase_merge: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'allow_rebase_merge' }})
    allow_squash_merge: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'allow_squash_merge' }})
    archive_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'archive_url' }})
    archived: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'archived' }})
    assignees_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'assignees_url' }})
    blobs_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'blobs_url' }})
    branches_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'branches_url' }})
    clone_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'clone_url' }})
    collaborators_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'collaborators_url' }})
    comments_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'comments_url' }})
    commits_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'commits_url' }})
    compare_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'compare_url' }})
    contents_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contents_url' }})
    contributors_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contributors_url' }})
    created_at: datetime = field(default=None, metadata={'dataclasses_json': { 'field_name': 'created_at', 'encoder': datetime.isoformat, 'decoder': dateutil.parser.isoparse, 'mm_field': fields.DateTime(format='iso') }})
    default_branch: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'default_branch' }})
    delete_branch_on_merge: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'delete_branch_on_merge' }})
    deployments_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'deployments_url' }})
    description: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'description' }})
    disabled: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'disabled' }})
    downloads_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'downloads_url' }})
    events_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'events_url' }})
    fork: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'fork' }})
    forks: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'forks' }})
    forks_count: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'forks_count' }})
    forks_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'forks_url' }})
    full_name: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'full_name' }})
    git_commits_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'git_commits_url' }})
    git_refs_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'git_refs_url' }})
    git_tags_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'git_tags_url' }})
    git_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'git_url' }})
    has_downloads: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'has_downloads' }})
    has_issues: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'has_issues' }})
    has_pages: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'has_pages' }})
    has_projects: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'has_projects' }})
    has_wiki: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'has_wiki' }})
    homepage: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'homepage' }})
    hooks_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'hooks_url' }})
    html_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'html_url' }})
    id: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'id' }})
    is_template: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'is_template' }})
    issue_comment_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'issue_comment_url' }})
    issue_events_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'issue_events_url' }})
    issues_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'issues_url' }})
    keys_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'keys_url' }})
    labels_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'labels_url' }})
    language: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'language' }})
    languages_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'languages_url' }})
    license: TeamRepositoryRepositoryLicenseSimple = field(default=None, metadata={'dataclasses_json': { 'field_name': 'license' }})
    master_branch: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'master_branch' }})
    merges_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'merges_url' }})
    milestones_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'milestones_url' }})
    mirror_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'mirror_url' }})
    name: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'name' }})
    network_count: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'network_count' }})
    node_id: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'node_id' }})
    notifications_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'notifications_url' }})
    open_issues: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'open_issues' }})
    open_issues_count: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'open_issues_count' }})
    owner: TeamRepositoryRepositorySimpleUser = field(default=None, metadata={'dataclasses_json': { 'field_name': 'owner' }})
    permissions: Optional[TeamRepositoryRepositoryPermissions] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'permissions' }})
    private: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'private' }})
    pulls_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'pulls_url' }})
    pushed_at: datetime = field(default=None, metadata={'dataclasses_json': { 'field_name': 'pushed_at', 'encoder': datetime.isoformat, 'decoder': dateutil.parser.isoparse, 'mm_field': fields.DateTime(format='iso') }})
    releases_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'releases_url' }})
    size: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'size' }})
    ssh_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'ssh_url' }})
    stargazers_count: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'stargazers_count' }})
    stargazers_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'stargazers_url' }})
    starred_at: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'starred_at' }})
    statuses_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'statuses_url' }})
    subscribers_count: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'subscribers_count' }})
    subscribers_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'subscribers_url' }})
    subscription_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'subscription_url' }})
    svn_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'svn_url' }})
    tags_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'tags_url' }})
    teams_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'teams_url' }})
    temp_clone_token: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'temp_clone_token' }})
    template_repository: Optional[TeamRepositoryRepositoryTemplateRepository] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'template_repository' }})
    topics: Optional[List[str]] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'topics' }})
    trees_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'trees_url' }})
    updated_at: datetime = field(default=None, metadata={'dataclasses_json': { 'field_name': 'updated_at', 'encoder': datetime.isoformat, 'decoder': dateutil.parser.isoparse, 'mm_field': fields.DateTime(format='iso') }})
    url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'url' }})
    visibility: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'visibility' }})
    watchers: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'watchers' }})
    watchers_count: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'watchers_count' }})
    

@dataclass_json
@dataclass
class TeamRepository:
    allow_merge_commit: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'allow_merge_commit' }})
    allow_rebase_merge: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'allow_rebase_merge' }})
    allow_squash_merge: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'allow_squash_merge' }})
    archive_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'archive_url' }})
    archived: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'archived' }})
    assignees_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'assignees_url' }})
    blobs_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'blobs_url' }})
    branches_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'branches_url' }})
    clone_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'clone_url' }})
    collaborators_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'collaborators_url' }})
    comments_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'comments_url' }})
    commits_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'commits_url' }})
    compare_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'compare_url' }})
    contents_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contents_url' }})
    contributors_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'contributors_url' }})
    created_at: datetime = field(default=None, metadata={'dataclasses_json': { 'field_name': 'created_at', 'encoder': datetime.isoformat, 'decoder': dateutil.parser.isoparse, 'mm_field': fields.DateTime(format='iso') }})
    default_branch: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'default_branch' }})
    delete_branch_on_merge: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'delete_branch_on_merge' }})
    deployments_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'deployments_url' }})
    description: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'description' }})
    disabled: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'disabled' }})
    downloads_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'downloads_url' }})
    events_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'events_url' }})
    fork: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'fork' }})
    forks: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'forks' }})
    forks_count: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'forks_count' }})
    forks_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'forks_url' }})
    full_name: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'full_name' }})
    git_commits_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'git_commits_url' }})
    git_refs_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'git_refs_url' }})
    git_tags_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'git_tags_url' }})
    git_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'git_url' }})
    has_downloads: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'has_downloads' }})
    has_issues: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'has_issues' }})
    has_pages: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'has_pages' }})
    has_projects: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'has_projects' }})
    has_wiki: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'has_wiki' }})
    homepage: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'homepage' }})
    hooks_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'hooks_url' }})
    html_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'html_url' }})
    id: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'id' }})
    is_template: Optional[bool] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'is_template' }})
    issue_comment_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'issue_comment_url' }})
    issue_events_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'issue_events_url' }})
    issues_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'issues_url' }})
    keys_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'keys_url' }})
    labels_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'labels_url' }})
    language: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'language' }})
    languages_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'languages_url' }})
    license: TeamRepositoryLicenseSimple = field(default=None, metadata={'dataclasses_json': { 'field_name': 'license' }})
    master_branch: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'master_branch' }})
    merges_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'merges_url' }})
    milestones_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'milestones_url' }})
    mirror_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'mirror_url' }})
    name: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'name' }})
    network_count: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'network_count' }})
    node_id: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'node_id' }})
    notifications_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'notifications_url' }})
    open_issues: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'open_issues' }})
    open_issues_count: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'open_issues_count' }})
    owner: TeamRepositorySimpleUser = field(default=None, metadata={'dataclasses_json': { 'field_name': 'owner' }})
    permissions: Optional[TeamRepositoryPermissions] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'permissions' }})
    private: bool = field(default=None, metadata={'dataclasses_json': { 'field_name': 'private' }})
    pulls_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'pulls_url' }})
    pushed_at: datetime = field(default=None, metadata={'dataclasses_json': { 'field_name': 'pushed_at', 'encoder': datetime.isoformat, 'decoder': dateutil.parser.isoparse, 'mm_field': fields.DateTime(format='iso') }})
    releases_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'releases_url' }})
    size: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'size' }})
    ssh_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'ssh_url' }})
    stargazers_count: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'stargazers_count' }})
    stargazers_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'stargazers_url' }})
    statuses_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'statuses_url' }})
    subscribers_count: Optional[int] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'subscribers_count' }})
    subscribers_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'subscribers_url' }})
    subscription_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'subscription_url' }})
    svn_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'svn_url' }})
    tags_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'tags_url' }})
    teams_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'teams_url' }})
    temp_clone_token: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'temp_clone_token' }})
    template_repository: Optional[TeamRepositoryRepository] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'template_repository' }})
    topics: Optional[List[str]] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'topics' }})
    trees_url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'trees_url' }})
    updated_at: datetime = field(default=None, metadata={'dataclasses_json': { 'field_name': 'updated_at', 'encoder': datetime.isoformat, 'decoder': dateutil.parser.isoparse, 'mm_field': fields.DateTime(format='iso') }})
    url: str = field(default=None, metadata={'dataclasses_json': { 'field_name': 'url' }})
    visibility: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'field_name': 'visibility' }})
    watchers: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'watchers' }})
    watchers_count: int = field(default=None, metadata={'dataclasses_json': { 'field_name': 'watchers_count' }})
    
