package shared

type ConferenceParticipantEnumJitterBufferSizeEnum string

const (
	ConferenceParticipantEnumJitterBufferSizeEnumLarge  ConferenceParticipantEnumJitterBufferSizeEnum = "large"
	ConferenceParticipantEnumJitterBufferSizeEnumSmall  ConferenceParticipantEnumJitterBufferSizeEnum = "small"
	ConferenceParticipantEnumJitterBufferSizeEnumMedium ConferenceParticipantEnumJitterBufferSizeEnum = "medium"
	ConferenceParticipantEnumJitterBufferSizeEnumOff    ConferenceParticipantEnumJitterBufferSizeEnum = "off"
)
