from .acceptmatch import *
from .claimgameserver import *
from .createalias import *
from .createbuild import *
from .createfleet import *
from .createfleetlocations import *
from .creategameservergroup import *
from .creategamesession import *
from .creategamesessionqueue import *
from .creatematchmakingconfiguration import *
from .creatematchmakingruleset import *
from .createplayersession import *
from .createplayersessions import *
from .createscript import *
from .createvpcpeeringauthorization import *
from .createvpcpeeringconnection import *
from .deletealias import *
from .deletebuild import *
from .deletefleet import *
from .deletefleetlocations import *
from .deletegameservergroup import *
from .deletegamesessionqueue import *
from .deletematchmakingconfiguration import *
from .deletematchmakingruleset import *
from .deletescalingpolicy import *
from .deletescript import *
from .deletevpcpeeringauthorization import *
from .deletevpcpeeringconnection import *
from .deregistergameserver import *
from .describealias import *
from .describebuild import *
from .describeec2instancelimits import *
from .describefleetattributes import *
from .describefleetcapacity import *
from .describefleetevents import *
from .describefleetlocationattributes import *
from .describefleetlocationcapacity import *
from .describefleetlocationutilization import *
from .describefleetportsettings import *
from .describefleetutilization import *
from .describegameserver import *
from .describegameservergroup import *
from .describegameserverinstances import *
from .describegamesessiondetails import *
from .describegamesessionplacement import *
from .describegamesessionqueues import *
from .describegamesessions import *
from .describeinstances import *
from .describematchmaking import *
from .describematchmakingconfigurations import *
from .describematchmakingrulesets import *
from .describeplayersessions import *
from .describeruntimeconfiguration import *
from .describescalingpolicies import *
from .describescript import *
from .describevpcpeeringauthorizations import *
from .describevpcpeeringconnections import *
from .getgamesessionlogurl import *
from .getinstanceaccess import *
from .listaliases import *
from .listbuilds import *
from .listfleets import *
from .listgameservergroups import *
from .listgameservers import *
from .listscripts import *
from .listtagsforresource import *
from .putscalingpolicy import *
from .registergameserver import *
from .requestuploadcredentials import *
from .resolvealias import *
from .resumegameservergroup import *
from .searchgamesessions import *
from .startfleetactions import *
from .startgamesessionplacement import *
from .startmatchbackfill import *
from .startmatchmaking import *
from .stopfleetactions import *
from .stopgamesessionplacement import *
from .stopmatchmaking import *
from .suspendgameservergroup import *
from .tagresource import *
from .untagresource import *
from .updatealias import *
from .updatebuild import *
from .updatefleetattributes import *
from .updatefleetcapacity import *
from .updatefleetportsettings import *
from .updategameserver import *
from .updategameservergroup import *
from .updategamesession import *
from .updategamesessionqueue import *
from .updatematchmakingconfiguration import *
from .updateruntimeconfiguration import *
from .updatescript import *
from .validatematchmakingruleset import *
