openapi: 3.0.0
servers:
  - url: https://people.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: Provides access to information about profiles and contacts.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: People API
  version: v1
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
    - converter:
        url: https://github.com/lucybot/api-spec-converter
        version: 2.7.31
      format: google
      url: https://people.googleapis.com/$discovery/rest?version=v1
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: people
tags:
  - name: contactGroups
  - name: otherContacts
  - name: people
paths:
  /v1/contactGroups:
    get:
      description: List all contact groups owned by the authenticated user. Members of the contact groups are not populated.
      operationId: people.contactGroups.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
        - Oauth2:
            - https://www.googleapis.com/auth/contacts.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/contacts.readonly
      tags:
        - contactGroups
    post:
      description: Create a new contact group owned by the authenticated user.
      operationId: people.contactGroups.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      tags:
        - contactGroups
  /v1/contactGroups:batchGet:
    get:
      description: Get a list of contact groups owned by the authenticated user by specifying a list of contact group resource names.
      operationId: people.contactGroups.batchGet
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
        - Oauth2:
            - https://www.googleapis.com/auth/contacts.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/contacts.readonly
      tags:
        - contactGroups
  /v1/otherContacts:
    get:
      description: List all "Other contacts", that is contacts that are not in a contact group. "Other contacts" are typically auto created contacts from interactions.
      operationId: people.otherContacts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts.other.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/contacts.other.readonly
      tags:
        - otherContacts
  /v1/people:batchGet:
    get:
      description: Provides information about a list of specific people by specifying a list of requested resource names. Use `people/me` to indicate the authenticated user. The request throws a 400 error if 'personFields' is not specified.
      operationId: people.people.getBatchGet
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
        - Oauth2:
            - https://www.googleapis.com/auth/contacts.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/contacts.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/directory.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/directory.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/user.addresses.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.addresses.read
        - Oauth2:
            - https://www.googleapis.com/auth/user.birthday.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.birthday.read
        - Oauth2:
            - https://www.googleapis.com/auth/user.emails.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.emails.read
        - Oauth2:
            - https://www.googleapis.com/auth/user.gender.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.gender.read
        - Oauth2:
            - https://www.googleapis.com/auth/user.organization.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.organization.read
        - Oauth2:
            - https://www.googleapis.com/auth/user.phonenumbers.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.phonenumbers.read
        - Oauth2:
            - https://www.googleapis.com/auth/userinfo.email
          Oauth2c:
            - https://www.googleapis.com/auth/userinfo.email
        - Oauth2:
            - https://www.googleapis.com/auth/userinfo.profile
          Oauth2c:
            - https://www.googleapis.com/auth/userinfo.profile
      tags:
        - people
  /v1/people:createContact:
    post:
      description: "Create a new contact and return the person resource for that contact. The request throws a 400 error if more than one field is specified on a field that is a singleton for contact sources: * biographies * birthdays * genders * names"
      operationId: people.people.createContact
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      tags:
        - people
  /v1/people:listDirectoryPeople:
    get:
      description: Provides a list of domain profiles and domain contacts in the authenticated user's domain directory.
      operationId: people.people.listDirectoryPeople
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/directory.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/directory.readonly
      tags:
        - people
  /v1/people:searchDirectoryPeople:
    get:
      description: Provides a list of domain profiles and domain contacts in the authenticated user's domain directory that match the search query.
      operationId: people.people.searchDirectoryPeople
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/directory.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/directory.readonly
      tags:
        - people
  "/v1/{resourceName}":
    delete:
      description: Delete an existing contact group owned by the authenticated user by specifying a contact group resource name.
      operationId: people.contactGroups.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      tags:
        - contactGroups
    get:
      description: Provides information about a person by specifying a resource name. Use `people/me` to indicate the authenticated user. The request throws a 400 error if 'personFields' is not specified.
      operationId: people.people.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
        - Oauth2:
            - https://www.googleapis.com/auth/contacts.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/contacts.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/directory.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/directory.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/user.addresses.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.addresses.read
        - Oauth2:
            - https://www.googleapis.com/auth/user.birthday.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.birthday.read
        - Oauth2:
            - https://www.googleapis.com/auth/user.emails.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.emails.read
        - Oauth2:
            - https://www.googleapis.com/auth/user.gender.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.gender.read
        - Oauth2:
            - https://www.googleapis.com/auth/user.organization.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.organization.read
        - Oauth2:
            - https://www.googleapis.com/auth/user.phonenumbers.read
          Oauth2c:
            - https://www.googleapis.com/auth/user.phonenumbers.read
        - Oauth2:
            - https://www.googleapis.com/auth/userinfo.email
          Oauth2c:
            - https://www.googleapis.com/auth/userinfo.email
        - Oauth2:
            - https://www.googleapis.com/auth/userinfo.profile
          Oauth2c:
            - https://www.googleapis.com/auth/userinfo.profile
      tags:
        - people
    put:
      description: Update the name of an existing contact group owned by the authenticated user.
      operationId: people.contactGroups.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      tags:
        - contactGroups
  "/v1/{resourceName}/connections":
    get:
      description: Provides a list of the authenticated user's contacts. The request throws a 400 error if 'personFields' is not specified.
      operationId: people.people.connections.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
        - Oauth2:
            - https://www.googleapis.com/auth/contacts.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/contacts.readonly
      tags:
        - people
  "/v1/{resourceName}/members:modify":
    post:
      description: Modify the members of a contact group owned by the authenticated user. The only system contact groups that can have members added are `contactGroups/myContacts` and `contactGroups/starred`. Other system contact groups are deprecated and can only have contacts removed.
      operationId: people.contactGroups.members.modify
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      tags:
        - contactGroups
  "/v1/{resourceName}:copyOtherContactToMyContactsGroup":
    post:
      description: Copies an "Other contact" to a new contact in the user's "myContacts" group
      operationId: people.otherContacts.copyOtherContactToMyContactsGroup
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
        - Oauth2:
            - https://www.googleapis.com/auth/contacts.other.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/contacts.other.readonly
      tags:
        - otherContacts
  "/v1/{resourceName}:deleteContact":
    delete:
      description: Delete a contact person. Any non-contact data will not be deleted.
      operationId: people.people.deleteContact
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      tags:
        - people
  "/v1/{resourceName}:deleteContactPhoto":
    delete:
      description: Delete a contact's photo.
      operationId: people.people.deleteContactPhoto
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      tags:
        - people
  "/v1/{resourceName}:updateContact":
    patch:
      description: "Update contact data for an existing contact person. Any non-contact data will not be modified. Any non-contact data in the person to update will be ignored. All fields specified in the `update_mask` will be replaced. The server returns a 400 error if `person.metadata.sources` is not specified for the contact to be updated or if there is no contact source. The server returns a 400 error with reason `\"failedPrecondition\"` if `person.metadata.sources.etag` is different than th[...]"
      operationId: people.people.updateContact
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      tags:
        - people
  "/v1/{resourceName}:updateContactPhoto":
    patch:
      description: Update a contact's photo.
      operationId: people.people.updateContactPhoto
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/contacts
          Oauth2c:
            - https://www.googleapis.com/auth/contacts
      tags:
        - people
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/contacts: See, edit, download, and permanently delete your contacts
            https://www.googleapis.com/auth/contacts.other.readonly: See and download contact info automatically saved in your "Other contacts"
            https://www.googleapis.com/auth/contacts.readonly: See and download your contacts
            https://www.googleapis.com/auth/directory.readonly: See and download your organization's GSuite directory
            https://www.googleapis.com/auth/user.addresses.read: View your street addresses
            https://www.googleapis.com/auth/user.birthday.read: View your complete date of birth
            https://www.googleapis.com/auth/user.emails.read: View your email addresses
            https://www.googleapis.com/auth/user.gender.read: See your gender
            https://www.googleapis.com/auth/user.organization.read: See your education, work history and org info
            https://www.googleapis.com/auth/user.phonenumbers.read: View your phone numbers
            https://www.googleapis.com/auth/userinfo.email: View your email address
            https://www.googleapis.com/auth/userinfo.profile: See your personal info, including any personal info you've made publicly available
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/contacts: See, edit, download, and permanently delete your contacts
            https://www.googleapis.com/auth/contacts.other.readonly: See and download contact info automatically saved in your "Other contacts"
            https://www.googleapis.com/auth/contacts.readonly: See and download your contacts
            https://www.googleapis.com/auth/directory.readonly: See and download your organization's GSuite directory
            https://www.googleapis.com/auth/user.addresses.read: View your street addresses
            https://www.googleapis.com/auth/user.birthday.read: View your complete date of birth
            https://www.googleapis.com/auth/user.emails.read: View your email addresses
            https://www.googleapis.com/auth/user.gender.read: See your gender
            https://www.googleapis.com/auth/user.organization.read: See your education, work history and org info
            https://www.googleapis.com/auth/user.phonenumbers.read: View your phone numbers
            https://www.googleapis.com/auth/userinfo.email: View your email address
            https://www.googleapis.com/auth/userinfo.profile: See your personal info, including any personal info you've made publicly available
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
