swagger: '2.0'
schemes:
  - https
host: people.googleapis.com
basePath: /
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Provides access to information about profiles and contacts.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: People
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-apisguru-categories:
    - social
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.7.31
      format: google
      url: 'https://people.googleapis.com/$discovery/rest?version=v1'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: people
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/contacts': 'See, edit, download, and permanently delete your contacts'
      'https://www.googleapis.com/auth/contacts.readonly': See and download your contacts
      'https://www.googleapis.com/auth/user.addresses.read': View your street addresses
      'https://www.googleapis.com/auth/user.birthday.read': View your complete date of birth
      'https://www.googleapis.com/auth/user.emails.read': View your email addresses
      'https://www.googleapis.com/auth/user.phonenumbers.read': View your phone numbers
      'https://www.googleapis.com/auth/userinfo.email': View your email address
      'https://www.googleapis.com/auth/userinfo.profile': 'See your personal info, including any personal info you''ve made publicly available'
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/contacts': 'See, edit, download, and permanently delete your contacts'
      'https://www.googleapis.com/auth/contacts.readonly': See and download your contacts
      'https://www.googleapis.com/auth/user.addresses.read': View your street addresses
      'https://www.googleapis.com/auth/user.birthday.read': View your complete date of birth
      'https://www.googleapis.com/auth/user.emails.read': View your email addresses
      'https://www.googleapis.com/auth/user.phonenumbers.read': View your phone numbers
      'https://www.googleapis.com/auth/userinfo.email': View your email address
      'https://www.googleapis.com/auth/userinfo.profile': 'See your personal info, including any personal info you''ve made publicly available'
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: contactGroups
  - name: people
paths:
  /v1/contactGroups:
    get:
      description: |-
        List all contact groups owned by the authenticated user. Members of the
        contact groups are not populated.
      operationId: people.contactGroups.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/contacts'
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/contacts.readonly'
      tags:
        - contactGroups
    post:
      description: Create a new contact group owned by the authenticated user.
      operationId: people.contactGroups.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/contacts'
      tags:
        - contactGroups
  '/v1/contactGroups:batchGet':
    get:
      description: |-
        Get a list of contact groups owned by the authenticated user by specifying
        a list of contact group resource names.
      operationId: people.contactGroups.batchGet
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/contacts'
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/contacts.readonly'
      tags:
        - contactGroups
  '/v1/people:batchGet':
    get:
      description: |-
        Provides information about a list of specific people by specifying a list
        of requested resource names. Use `people/me` to indicate the authenticated
        user.
        <br>
        The request throws a 400 error if 'personFields' is not specified.
      operationId: people.people.getBatchGet
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/contacts'
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/contacts.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/user.addresses.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/user.addresses.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/user.birthday.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/user.birthday.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/user.emails.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/user.emails.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/user.phonenumbers.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/user.phonenumbers.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/userinfo.email'
          Oauth2c:
            - 'https://www.googleapis.com/auth/userinfo.email'
        - Oauth2:
            - 'https://www.googleapis.com/auth/userinfo.profile'
          Oauth2c:
            - 'https://www.googleapis.com/auth/userinfo.profile'
      tags:
        - people
  '/v1/people:createContact':
    post:
      description: Create a new contact and return the person resource for that contact.
      operationId: people.people.createContact
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/contacts'
      tags:
        - people
  '/v1/{resourceName}':
    delete:
      description: |-
        Delete an existing contact group owned by the authenticated user by
        specifying a contact group resource name.
      operationId: people.contactGroups.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/contacts'
      tags:
        - contactGroups
    get:
      description: |-
        Get a specific contact group owned by the authenticated user by specifying
        a contact group resource name.
      operationId: people.contactGroups.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/contacts'
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/contacts.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/user.addresses.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/user.addresses.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/user.birthday.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/user.birthday.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/user.emails.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/user.emails.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/user.phonenumbers.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/user.phonenumbers.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/userinfo.email'
          Oauth2c:
            - 'https://www.googleapis.com/auth/userinfo.email'
        - Oauth2:
            - 'https://www.googleapis.com/auth/userinfo.profile'
          Oauth2c:
            - 'https://www.googleapis.com/auth/userinfo.profile'
      tags:
        - contactGroups
    put:
      description: |-
        Update the name of an existing contact group owned by the authenticated
        user.
      operationId: people.contactGroups.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/contacts'
      tags:
        - contactGroups
  '/v1/{resourceName}/connections':
    get:
      description: |-
        Provides a list of the authenticated user's contacts merged with any
        connected profiles.
        <br>
        The request throws a 400 error if 'personFields' is not specified.
      operationId: people.people.connections.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/contacts'
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/contacts.readonly'
      tags:
        - people
  '/v1/{resourceName}/members:modify':
    post:
      description: |-
        Modify the members of a contact group owned by the authenticated user.
        <br>
        The only system contact groups that can have members added are
        `contactGroups/myContacts` and `contactGroups/starred`. Other system
        contact groups are deprecated and can only have contacts removed.
      operationId: people.contactGroups.members.modify
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/contacts'
      tags:
        - contactGroups
  '/v1/{resourceName}:deleteContact':
    delete:
      description: Delete a contact person. Any non-contact data will not be deleted.
      operationId: people.people.deleteContact
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/contacts'
      tags:
        - people
  '/v1/{resourceName}:deleteContactPhoto':
    delete:
      description: Delete a contact's photo.
      operationId: people.people.deleteContactPhoto
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/contacts'
      tags:
        - people
  '/v1/{resourceName}:updateContact':
    patch:
      description: |-
        Update contact data for an existing contact person. Any non-contact data
        will not be modified.

        The request throws a 400 error if `updatePersonFields` is not specified.
        <br>
        The request throws a 400 error if `person.metadata.sources` is not
        specified for the contact to be updated.
        <br>
        The request throws a 412 error if `person.metadata.sources.etag` is
        different than the contact's etag, which indicates the contact has changed
        since its data was read. Clients should get the latest person and re-apply
        their updates to the latest person.
      operationId: people.people.updateContact
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/contacts'
      tags:
        - people
  '/v1/{resourceName}:updateContactPhoto':
    patch:
      description: Update a contact's photo.
      operationId: people.people.updateContactPhoto
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/contacts'
      tags:
        - people