swagger: '2.0'
schemes:
  - https
host: people.googleapis.com
basePath: /
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Provides access to information about profiles and contacts.
  title: Google People
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    format: google
    url: 'https://people.googleapis.com/$discovery/rest?version=v1'
    version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: people
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/contacts': Manage your contacts
      'https://www.googleapis.com/auth/contacts.readonly': View your contacts
      'https://www.googleapis.com/auth/plus.login': 'Know the list of people in your circles, your age range, and language'
      'https://www.googleapis.com/auth/user.addresses.read': View your street addresses
      'https://www.googleapis.com/auth/user.birthday.read': View your complete date of birth
      'https://www.googleapis.com/auth/user.emails.read': View your email addresses
      'https://www.googleapis.com/auth/user.phonenumbers.read': View your phone numbers
      'https://www.googleapis.com/auth/userinfo.email': View your email address
      'https://www.googleapis.com/auth/userinfo.profile': View your basic profile info
    type: oauth2
tags:
  - name: people
paths:
  '/v1/people:batchGet':
    get:
      description: |-
        Provides information about a list of specific people by specifying a list
        of requested resource names. Use `people/me` to indicate the authenticated
        user.
      operationId: people.people.getBatchGet
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts'
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
        - Oauth2:
            - 'https://www.googleapis.com/auth/user.addresses.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/user.birthday.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/user.emails.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/user.phonenumbers.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/userinfo.email'
        - Oauth2:
            - 'https://www.googleapis.com/auth/userinfo.profile'
      tags:
        - people
  '/v1/{resourceName}':
    get:
      description: |-
        Provides information about a person resource for a resource name. Use
        `people/me` to indicate the authenticated user.
      operationId: people.people.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts'
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/plus.login'
        - Oauth2:
            - 'https://www.googleapis.com/auth/user.addresses.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/user.birthday.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/user.emails.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/user.phonenumbers.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/userinfo.email'
        - Oauth2:
            - 'https://www.googleapis.com/auth/userinfo.profile'
      tags:
        - people
  '/v1/{resourceName}/connections':
    get:
      description: |-
        Provides a list of the authenticated user's contacts merged with any
        linked profiles.
      operationId: people.people.connections.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts'
        - Oauth2:
            - 'https://www.googleapis.com/auth/contacts.readonly'
      tags:
        - people