{
  "swagger": "2.0",
  "info": {
    "title": "Google Mirror API",
    "x-serviceName": "mirror",
    "description": "API for interacting with Glass users via the timeline.",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v1",
    "x-origin": {
      "format": "google",
      "version": "v1",
      "url": "https://www.googleapis.com/discovery/v1/apis/mirror/v1/rest"
    }
  },
  "host": "www.googleapis.com",
  "basePath": "/mirror/v1",
  "schemes": [
    "https"
  ],
  "paths": {
    "/accounts/{userToken}/{accountType}/{accountName}": {
      "post": {
        "description": "Inserts a new account for a user",
        "operationId": "mirror.accounts.insert",
        "tags": [
          "accounts"
        ]
      }
    },
    "/contacts/{id}": {
      "delete": {
        "description": "Deletes a contact.",
        "operationId": "mirror.contacts.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "contacts"
        ]
      },
      "get": {
        "description": "Gets a single contact by ID.",
        "operationId": "mirror.contacts.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "contacts"
        ]
      },
      "patch": {
        "description": "Updates a contact in place. This method supports patch semantics.",
        "operationId": "mirror.contacts.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "contacts"
        ]
      },
      "put": {
        "description": "Updates a contact in place.",
        "operationId": "mirror.contacts.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "contacts"
        ]
      }
    },
    "/contacts": {
      "post": {
        "description": "Inserts a new contact.",
        "operationId": "mirror.contacts.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "contacts"
        ]
      },
      "get": {
        "description": "Retrieves a list of contacts for the authenticated user.",
        "operationId": "mirror.contacts.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "contacts"
        ]
      }
    },
    "/locations/{id}": {
      "get": {
        "description": "Gets a single location by ID.",
        "operationId": "mirror.locations.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.location",
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "locations"
        ]
      }
    },
    "/locations": {
      "get": {
        "description": "Retrieves a list of locations for the user.",
        "operationId": "mirror.locations.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.location",
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "locations"
        ]
      }
    },
    "/settings/{id}": {
      "get": {
        "description": "Gets a single setting by ID.",
        "operationId": "mirror.settings.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "settings"
        ]
      }
    },
    "/subscriptions/{id}": {
      "delete": {
        "description": "Deletes a subscription.",
        "operationId": "mirror.subscriptions.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "subscriptions"
        ]
      },
      "put": {
        "description": "Updates an existing subscription in place.",
        "operationId": "mirror.subscriptions.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "subscriptions"
        ]
      }
    },
    "/subscriptions": {
      "post": {
        "description": "Creates a new subscription.",
        "operationId": "mirror.subscriptions.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "subscriptions"
        ]
      },
      "get": {
        "description": "Retrieves a list of subscriptions for the authenticated user and service.",
        "operationId": "mirror.subscriptions.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "subscriptions"
        ]
      }
    },
    "/timeline/{id}": {
      "delete": {
        "description": "Deletes a timeline item.",
        "operationId": "mirror.timeline.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.location",
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "timeline"
        ]
      },
      "get": {
        "description": "Gets a single timeline item by ID.",
        "operationId": "mirror.timeline.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.location",
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "timeline"
        ]
      },
      "patch": {
        "description": "Updates a timeline item in place. This method supports patch semantics.",
        "operationId": "mirror.timeline.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.location",
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "timeline"
        ]
      },
      "put": {
        "description": "Updates a timeline item in place.",
        "operationId": "mirror.timeline.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.location",
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "timeline"
        ]
      }
    },
    "/timeline": {
      "post": {
        "description": "Inserts a new item into the timeline.",
        "operationId": "mirror.timeline.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.location",
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "timeline"
        ]
      },
      "get": {
        "description": "Retrieves a list of timeline items for the authenticated user.",
        "operationId": "mirror.timeline.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.location",
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "timeline"
        ]
      }
    },
    "/timeline/{itemId}/attachments/{attachmentId}": {
      "delete": {
        "description": "Deletes an attachment from a timeline item.",
        "operationId": "mirror.timeline.attachments.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "timeline"
        ]
      },
      "get": {
        "description": "Retrieves an attachment on a timeline item by item ID and attachment ID.",
        "operationId": "mirror.timeline.attachments.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "timeline"
        ]
      }
    },
    "/timeline/{itemId}/attachments": {
      "post": {
        "description": "Adds a new attachment to a timeline item.",
        "operationId": "mirror.timeline.attachments.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "timeline"
        ]
      },
      "get": {
        "description": "Returns a list of attachments for a timeline item.",
        "operationId": "mirror.timeline.attachments.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "timeline"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/glass.location": "View your location",
        "https://www.googleapis.com/auth/glass.timeline": "View and manage your Glass timeline"
      }
    }
  }
}