{
  "swagger": "2.0",
  "info": {
    "title": "Gmail API",
    "description": "The Gmail REST API.",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v1"
  },
  "host": "www.googleapis.com",
  "basePath": "/gmail/v1/users",
  "schemes": [
    "https"
  ],
  "paths": {
    "/{userId}/profile": {
      "get": {
        "description": "Gets the current user's Gmail profile.",
        "operationId": "gmail.users.getProfile",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.compose",
              "https://www.googleapis.com/auth/gmail.modify",
              "https://www.googleapis.com/auth/gmail.readonly"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/drafts": {
      "post": {
        "description": "Creates a new draft with the DRAFT label.",
        "operationId": "gmail.users.drafts.create",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.compose",
              "https://www.googleapis.com/auth/gmail.modify"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      },
      "get": {
        "description": "Lists the drafts in the user's mailbox.",
        "operationId": "gmail.users.drafts.list",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.compose",
              "https://www.googleapis.com/auth/gmail.modify",
              "https://www.googleapis.com/auth/gmail.readonly"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/drafts/{id}": {
      "delete": {
        "description": "Immediately and permanently deletes the specified draft. Does not simply trash it.",
        "operationId": "gmail.users.drafts.delete",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.compose",
              "https://www.googleapis.com/auth/gmail.modify"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      },
      "get": {
        "description": "Gets the specified draft.",
        "operationId": "gmail.users.drafts.get",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.compose",
              "https://www.googleapis.com/auth/gmail.modify",
              "https://www.googleapis.com/auth/gmail.readonly"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      },
      "put": {
        "description": "Replaces a draft's content.",
        "operationId": "gmail.users.drafts.update",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.compose",
              "https://www.googleapis.com/auth/gmail.modify"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/drafts/send": {
      "post": {
        "description": "Sends the specified, existing draft to the recipients in the To, Cc, and Bcc headers.",
        "operationId": "gmail.users.drafts.send",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.compose",
              "https://www.googleapis.com/auth/gmail.modify"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/history": {
      "get": {
        "description": "Lists the history of all changes to the given mailbox. History results are returned in chronological order (increasing historyId).",
        "operationId": "gmail.users.history.list",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.modify",
              "https://www.googleapis.com/auth/gmail.readonly"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/labels": {
      "post": {
        "description": "Creates a new label.",
        "operationId": "gmail.users.labels.create",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.labels",
              "https://www.googleapis.com/auth/gmail.modify"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      },
      "get": {
        "description": "Lists all labels in the user's mailbox.",
        "operationId": "gmail.users.labels.list",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.labels",
              "https://www.googleapis.com/auth/gmail.modify",
              "https://www.googleapis.com/auth/gmail.readonly"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/labels/{id}": {
      "delete": {
        "description": "Immediately and permanently deletes the specified label and removes it from any messages and threads that it is applied to.",
        "operationId": "gmail.users.labels.delete",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.labels",
              "https://www.googleapis.com/auth/gmail.modify"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      },
      "get": {
        "description": "Gets the specified label.",
        "operationId": "gmail.users.labels.get",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.labels",
              "https://www.googleapis.com/auth/gmail.modify",
              "https://www.googleapis.com/auth/gmail.readonly"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      },
      "patch": {
        "description": "Updates the specified label. This method supports patch semantics.",
        "operationId": "gmail.users.labels.patch",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.labels",
              "https://www.googleapis.com/auth/gmail.modify"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      },
      "put": {
        "description": "Updates the specified label.",
        "operationId": "gmail.users.labels.update",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.labels",
              "https://www.googleapis.com/auth/gmail.modify"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/messages/{id}": {
      "delete": {
        "description": "Immediately and permanently deletes the specified message. This operation cannot be undone. Prefer messages.trash instead.",
        "operationId": "gmail.users.messages.delete",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      },
      "get": {
        "description": "Gets the specified message.",
        "operationId": "gmail.users.messages.get",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.modify",
              "https://www.googleapis.com/auth/gmail.readonly"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/messages/import": {
      "post": {
        "description": "Imports a message into only this user's mailbox, with standard email delivery scanning and classification similar to receiving via SMTP. Does not send a message.",
        "operationId": "gmail.users.messages.import",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.insert",
              "https://www.googleapis.com/auth/gmail.modify"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/messages": {
      "post": {
        "description": "Directly inserts a message into only this user's mailbox similar to IMAP APPEND, bypassing most scanning and classification. Does not send a message.",
        "operationId": "gmail.users.messages.insert",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.insert",
              "https://www.googleapis.com/auth/gmail.modify"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      },
      "get": {
        "description": "Lists the messages in the user's mailbox.",
        "operationId": "gmail.users.messages.list",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.modify",
              "https://www.googleapis.com/auth/gmail.readonly"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/messages/{id}/modify": {
      "post": {
        "description": "Modifies the labels on the specified message.",
        "operationId": "gmail.users.messages.modify",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.modify"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/messages/send": {
      "post": {
        "description": "Sends the specified message to the recipients in the To, Cc, and Bcc headers.",
        "operationId": "gmail.users.messages.send",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.compose",
              "https://www.googleapis.com/auth/gmail.modify"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/messages/{id}/trash": {
      "post": {
        "description": "Moves the specified message to the trash.",
        "operationId": "gmail.users.messages.trash",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.modify"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/messages/{id}/untrash": {
      "post": {
        "description": "Removes the specified message from the trash.",
        "operationId": "gmail.users.messages.untrash",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.modify"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/messages/{messageId}/attachments/{id}": {
      "get": {
        "description": "Gets the specified message attachment.",
        "operationId": "gmail.users.messages.attachments.get",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.modify",
              "https://www.googleapis.com/auth/gmail.readonly"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/threads/{id}": {
      "delete": {
        "description": "Immediately and permanently deletes the specified thread. This operation cannot be undone. Prefer threads.trash instead.",
        "operationId": "gmail.users.threads.delete",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      },
      "get": {
        "description": "Gets the specified thread.",
        "operationId": "gmail.users.threads.get",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.modify",
              "https://www.googleapis.com/auth/gmail.readonly"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/threads": {
      "get": {
        "description": "Lists the threads in the user's mailbox.",
        "operationId": "gmail.users.threads.list",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.modify",
              "https://www.googleapis.com/auth/gmail.readonly"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/threads/{id}/modify": {
      "post": {
        "description": "Modifies the labels applied to the thread. This applies to all messages in the thread.",
        "operationId": "gmail.users.threads.modify",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.modify"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/threads/{id}/trash": {
      "post": {
        "description": "Moves the specified thread to the trash.",
        "operationId": "gmail.users.threads.trash",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.modify"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{userId}/threads/{id}/untrash": {
      "post": {
        "description": "Removes the specified thread from the trash.",
        "operationId": "gmail.users.threads.untrash",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/",
              "https://www.googleapis.com/auth/gmail.modify"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://mail.google.com/": "View and manage your mail",
        "https://www.googleapis.com/auth/gmail.compose": "Manage drafts and send emails",
        "https://www.googleapis.com/auth/gmail.insert": "Insert mail into your mailbox",
        "https://www.googleapis.com/auth/gmail.labels": "Manage mailbox labels",
        "https://www.googleapis.com/auth/gmail.modify": "View and modify but not delete your email",
        "https://www.googleapis.com/auth/gmail.readonly": "View your emails messages and settings"
      }
    }
  }
}