package shared




type ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum string

const (
    ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationUnspecified ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_UNSPECIFIED"
ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationSecondsNone ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_SECONDS_NONE"
ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationSeconds0 ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_SECONDS_0"
ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationSeconds1 ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_SECONDS_1"
ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationSeconds2 ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_SECONDS_2"
ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationSeconds3 ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_SECONDS_3"
ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationSeconds4 ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_SECONDS_4"
ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationSeconds5 ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_SECONDS_5"
ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationSeconds6 ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_SECONDS_6"
ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationSeconds7 ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_SECONDS_7"
ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationSeconds8 ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_SECONDS_8"
ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationSeconds9 ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_SECONDS_9"
ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationSeconds10 ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_SECONDS_10"
ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationSeconds11 ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_SECONDS_11"
ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationSeconds12 ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_SECONDS_12"
ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationSeconds13 ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_SECONDS_13"
ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationSeconds14 ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_SECONDS_14"
ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationSeconds15 ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_SECONDS_15"
ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationSeconds30 ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_SECONDS_30"
ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationSeconds45 ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_SECONDS_45"
ActiveViewVideoViewabilityMetricConfigMinimumDurationEnumVideoDurationSeconds60 ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum = "VIDEO_DURATION_SECONDS_60"
)



type ActiveViewVideoViewabilityMetricConfigMinimumQuartileEnum string

const (
    ActiveViewVideoViewabilityMetricConfigMinimumQuartileEnumVideoDurationQuartileUnspecified ActiveViewVideoViewabilityMetricConfigMinimumQuartileEnum = "VIDEO_DURATION_QUARTILE_UNSPECIFIED"
ActiveViewVideoViewabilityMetricConfigMinimumQuartileEnumVideoDurationQuartileNone ActiveViewVideoViewabilityMetricConfigMinimumQuartileEnum = "VIDEO_DURATION_QUARTILE_NONE"
ActiveViewVideoViewabilityMetricConfigMinimumQuartileEnumVideoDurationQuartileFirst ActiveViewVideoViewabilityMetricConfigMinimumQuartileEnum = "VIDEO_DURATION_QUARTILE_FIRST"
ActiveViewVideoViewabilityMetricConfigMinimumQuartileEnumVideoDurationQuartileSecond ActiveViewVideoViewabilityMetricConfigMinimumQuartileEnum = "VIDEO_DURATION_QUARTILE_SECOND"
ActiveViewVideoViewabilityMetricConfigMinimumQuartileEnumVideoDurationQuartileThird ActiveViewVideoViewabilityMetricConfigMinimumQuartileEnum = "VIDEO_DURATION_QUARTILE_THIRD"
ActiveViewVideoViewabilityMetricConfigMinimumQuartileEnumVideoDurationQuartileFourth ActiveViewVideoViewabilityMetricConfigMinimumQuartileEnum = "VIDEO_DURATION_QUARTILE_FOURTH"
)



type ActiveViewVideoViewabilityMetricConfigMinimumViewabilityEnum string

const (
    ActiveViewVideoViewabilityMetricConfigMinimumViewabilityEnumViewabilityPercentUnspecified ActiveViewVideoViewabilityMetricConfigMinimumViewabilityEnum = "VIEWABILITY_PERCENT_UNSPECIFIED"
ActiveViewVideoViewabilityMetricConfigMinimumViewabilityEnumViewabilityPercent0 ActiveViewVideoViewabilityMetricConfigMinimumViewabilityEnum = "VIEWABILITY_PERCENT_0"
ActiveViewVideoViewabilityMetricConfigMinimumViewabilityEnumViewabilityPercent25 ActiveViewVideoViewabilityMetricConfigMinimumViewabilityEnum = "VIEWABILITY_PERCENT_25"
ActiveViewVideoViewabilityMetricConfigMinimumViewabilityEnumViewabilityPercent50 ActiveViewVideoViewabilityMetricConfigMinimumViewabilityEnum = "VIEWABILITY_PERCENT_50"
ActiveViewVideoViewabilityMetricConfigMinimumViewabilityEnumViewabilityPercent75 ActiveViewVideoViewabilityMetricConfigMinimumViewabilityEnum = "VIEWABILITY_PERCENT_75"
ActiveViewVideoViewabilityMetricConfigMinimumViewabilityEnumViewabilityPercent100 ActiveViewVideoViewabilityMetricConfigMinimumViewabilityEnum = "VIEWABILITY_PERCENT_100"
)



type ActiveViewVideoViewabilityMetricConfigMinimumVolumeEnum string

const (
    ActiveViewVideoViewabilityMetricConfigMinimumVolumeEnumVideoVolumePercentUnspecified ActiveViewVideoViewabilityMetricConfigMinimumVolumeEnum = "VIDEO_VOLUME_PERCENT_UNSPECIFIED"
ActiveViewVideoViewabilityMetricConfigMinimumVolumeEnumVideoVolumePercent0 ActiveViewVideoViewabilityMetricConfigMinimumVolumeEnum = "VIDEO_VOLUME_PERCENT_0"
ActiveViewVideoViewabilityMetricConfigMinimumVolumeEnumVideoVolumePercent10 ActiveViewVideoViewabilityMetricConfigMinimumVolumeEnum = "VIDEO_VOLUME_PERCENT_10"
)


type ActiveViewVideoViewabilityMetricConfig struct {
    DisplayName *string `json:"displayName,omitempty"`
    MinimumDuration *ActiveViewVideoViewabilityMetricConfigMinimumDurationEnum `json:"minimumDuration,omitempty"`
    MinimumQuartile *ActiveViewVideoViewabilityMetricConfigMinimumQuartileEnum `json:"minimumQuartile,omitempty"`
    MinimumViewability *ActiveViewVideoViewabilityMetricConfigMinimumViewabilityEnum `json:"minimumViewability,omitempty"`
    MinimumVolume *ActiveViewVideoViewabilityMetricConfigMinimumVolumeEnum `json:"minimumVolume,omitempty"`
    
}

