package shared

type AuthorizedSellerStatusTargetingOptionDetailsAuthorizedSellerStatusEnum string

const (
	AuthorizedSellerStatusTargetingOptionDetailsAuthorizedSellerStatusEnumAuthorizedSellerStatusUnspecified                             AuthorizedSellerStatusTargetingOptionDetailsAuthorizedSellerStatusEnum = "AUTHORIZED_SELLER_STATUS_UNSPECIFIED"
	AuthorizedSellerStatusTargetingOptionDetailsAuthorizedSellerStatusEnumAuthorizedSellerStatusAuthorizedDirectSellersOnly             AuthorizedSellerStatusTargetingOptionDetailsAuthorizedSellerStatusEnum = "AUTHORIZED_SELLER_STATUS_AUTHORIZED_DIRECT_SELLERS_ONLY"
	AuthorizedSellerStatusTargetingOptionDetailsAuthorizedSellerStatusEnumAuthorizedSellerStatusAuthorizedAndNonParticipatingPublishers AuthorizedSellerStatusTargetingOptionDetailsAuthorizedSellerStatusEnum = "AUTHORIZED_SELLER_STATUS_AUTHORIZED_AND_NON_PARTICIPATING_PUBLISHERS"
)

type AuthorizedSellerStatusTargetingOptionDetails struct {
	AuthorizedSellerStatus *AuthorizedSellerStatusTargetingOptionDetailsAuthorizedSellerStatusEnum `json:"authorizedSellerStatus"`
}
