package shared

type ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnum string

const (
	ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnumContentInstreamPositionUnspecified ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnum = "CONTENT_INSTREAM_POSITION_UNSPECIFIED"
	ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnumContentInstreamPositionPreRoll     ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnum = "CONTENT_INSTREAM_POSITION_PRE_ROLL"
	ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnumContentInstreamPositionMidRoll     ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnum = "CONTENT_INSTREAM_POSITION_MID_ROLL"
	ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnumContentInstreamPositionPostRoll    ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnum = "CONTENT_INSTREAM_POSITION_POST_ROLL"
	ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnumContentInstreamPositionUnknown     ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnum = "CONTENT_INSTREAM_POSITION_UNKNOWN"
)

// ContentInstreamPositionTargetingOptionDetails
// Represents a targetable content instream position, which could be used by video and audio ads. This will be populated in the content_instream_position_details field when targeting_type is `TARGETING_TYPE_CONTENT_INSTREAM_POSITION`.
type ContentInstreamPositionTargetingOptionDetails struct {
	ContentInstreamPosition *ContentInstreamPositionTargetingOptionDetailsContentInstreamPositionEnum `json:"contentInstreamPosition,omitempty"`
}
