package shared

type DigitalContentLabelAssignedTargetingOptionDetailsExcludedContentRatingTierEnum string

const (
	DigitalContentLabelAssignedTargetingOptionDetailsExcludedContentRatingTierEnumContentRatingTierUnspecified      DigitalContentLabelAssignedTargetingOptionDetailsExcludedContentRatingTierEnum = "CONTENT_RATING_TIER_UNSPECIFIED"
	DigitalContentLabelAssignedTargetingOptionDetailsExcludedContentRatingTierEnumContentRatingTierUnrated          DigitalContentLabelAssignedTargetingOptionDetailsExcludedContentRatingTierEnum = "CONTENT_RATING_TIER_UNRATED"
	DigitalContentLabelAssignedTargetingOptionDetailsExcludedContentRatingTierEnumContentRatingTierGeneral          DigitalContentLabelAssignedTargetingOptionDetailsExcludedContentRatingTierEnum = "CONTENT_RATING_TIER_GENERAL"
	DigitalContentLabelAssignedTargetingOptionDetailsExcludedContentRatingTierEnumContentRatingTierParentalGuidance DigitalContentLabelAssignedTargetingOptionDetailsExcludedContentRatingTierEnum = "CONTENT_RATING_TIER_PARENTAL_GUIDANCE"
	DigitalContentLabelAssignedTargetingOptionDetailsExcludedContentRatingTierEnumContentRatingTierTeens            DigitalContentLabelAssignedTargetingOptionDetailsExcludedContentRatingTierEnum = "CONTENT_RATING_TIER_TEENS"
	DigitalContentLabelAssignedTargetingOptionDetailsExcludedContentRatingTierEnumContentRatingTierMature           DigitalContentLabelAssignedTargetingOptionDetailsExcludedContentRatingTierEnum = "CONTENT_RATING_TIER_MATURE"
	DigitalContentLabelAssignedTargetingOptionDetailsExcludedContentRatingTierEnumContentRatingTierFamilies         DigitalContentLabelAssignedTargetingOptionDetailsExcludedContentRatingTierEnum = "CONTENT_RATING_TIER_FAMILIES"
)

type DigitalContentLabelAssignedTargetingOptionDetails struct {
	ExcludedContentRatingTier *DigitalContentLabelAssignedTargetingOptionDetailsExcludedContentRatingTierEnum `json:"excludedContentRatingTier"`
}
