package shared

type ExchangeAssignedTargetingOptionDetailsExchangeEnum string

const (
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeUnspecified       ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_UNSPECIFIED"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeGoogleAdManager   ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_GOOGLE_AD_MANAGER"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeAppnexus          ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_APPNEXUS"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeBrightroll        ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_BRIGHTROLL"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeAdform            ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_ADFORM"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeAdmeta            ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_ADMETA"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeAdmixer           ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_ADMIXER"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeAdsmogo           ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_ADSMOGO"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeAdswizz           ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_ADSWIZZ"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeBidswitch         ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_BIDSWITCH"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeBrightrollDisplay ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_BRIGHTROLL_DISPLAY"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeCadreon           ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_CADREON"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeDailymotion       ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_DAILYMOTION"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeFive              ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_FIVE"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeFluct             ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_FLUCT"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeFreewheel         ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_FREEWHEEL"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeGeniee            ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_GENIEE"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeGumgum            ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_GUMGUM"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeImobile           ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_IMOBILE"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeIbillboard        ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_IBILLBOARD"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeImproveDigital    ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_IMPROVE_DIGITAL"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeIndex             ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_INDEX"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeKargo             ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_KARGO"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeMicroad           ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_MICROAD"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeMopub             ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_MOPUB"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeNend              ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_NEND"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeOneByAolDisplay   ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_ONE_BY_AOL_DISPLAY"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeOneByAolMobile    ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_ONE_BY_AOL_MOBILE"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeOneByAolVideo     ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_ONE_BY_AOL_VIDEO"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeOoyala            ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_OOYALA"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeOpenx             ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_OPENX"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangePermodo           ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_PERMODO"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangePlatformone       ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_PLATFORMONE"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangePlatformid        ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_PLATFORMID"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangePubmatic          ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_PUBMATIC"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangePulsepoint        ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_PULSEPOINT"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeRevenuemax        ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_REVENUEMAX"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeRubicon           ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_RUBICON"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeSmartclip         ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_SMARTCLIP"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeSmartrtb          ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_SMARTRTB"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeSmartstreamtv     ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_SMARTSTREAMTV"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeSovrn             ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_SOVRN"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeSpotxchange       ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_SPOTXCHANGE"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeStroer            ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_STROER"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeTeadstv           ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_TEADSTV"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeTelaria           ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_TELARIA"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeTvn               ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_TVN"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeUnited            ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_UNITED"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeYieldlab          ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_YIELDLAB"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeYieldmo           ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_YIELDMO"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeUnrulyx           ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_UNRULYX"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeOpen8             ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_OPEN8"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeTriton            ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_TRITON"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeTriplelift        ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_TRIPLELIFT"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeTaboola           ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_TABOOLA"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeInmobi            ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_INMOBI"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeSmaato            ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_SMAATO"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeAja               ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_AJA"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeSupership         ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_SUPERSHIP"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeNexstarDigital    ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_NEXSTAR_DIGITAL"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeWaze              ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_WAZE"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeSoundcast         ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_SOUNDCAST"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeSharethrough      ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_SHARETHROUGH"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeFyber             ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_FYBER"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeRedForPublishers  ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_RED_FOR_PUBLISHERS"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeMedianet          ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_MEDIANET"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeTapjoy            ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_TAPJOY"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeVistar            ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_VISTAR"
	ExchangeAssignedTargetingOptionDetailsExchangeEnumExchangeDax               ExchangeAssignedTargetingOptionDetailsExchangeEnum = "EXCHANGE_DAX"
)

type ExchangeAssignedTargetingOptionDetails struct {
	Exchange *ExchangeAssignedTargetingOptionDetailsExchangeEnum `json:"exchange"`
}
