package shared

type HouseholdIncomeAssignedTargetingOptionDetailsHouseholdIncomeEnum string

const (
	HouseholdIncomeAssignedTargetingOptionDetailsHouseholdIncomeEnumHouseholdIncomeUnspecified      HouseholdIncomeAssignedTargetingOptionDetailsHouseholdIncomeEnum = "HOUSEHOLD_INCOME_UNSPECIFIED"
	HouseholdIncomeAssignedTargetingOptionDetailsHouseholdIncomeEnumHouseholdIncomeUnknown          HouseholdIncomeAssignedTargetingOptionDetailsHouseholdIncomeEnum = "HOUSEHOLD_INCOME_UNKNOWN"
	HouseholdIncomeAssignedTargetingOptionDetailsHouseholdIncomeEnumHouseholdIncomeLower50Percent   HouseholdIncomeAssignedTargetingOptionDetailsHouseholdIncomeEnum = "HOUSEHOLD_INCOME_LOWER_50_PERCENT"
	HouseholdIncomeAssignedTargetingOptionDetailsHouseholdIncomeEnumHouseholdIncomeTop41To50Percent HouseholdIncomeAssignedTargetingOptionDetailsHouseholdIncomeEnum = "HOUSEHOLD_INCOME_TOP_41_TO_50_PERCENT"
	HouseholdIncomeAssignedTargetingOptionDetailsHouseholdIncomeEnumHouseholdIncomeTop31To40Percent HouseholdIncomeAssignedTargetingOptionDetailsHouseholdIncomeEnum = "HOUSEHOLD_INCOME_TOP_31_TO_40_PERCENT"
	HouseholdIncomeAssignedTargetingOptionDetailsHouseholdIncomeEnumHouseholdIncomeTop21To30Percent HouseholdIncomeAssignedTargetingOptionDetailsHouseholdIncomeEnum = "HOUSEHOLD_INCOME_TOP_21_TO_30_PERCENT"
	HouseholdIncomeAssignedTargetingOptionDetailsHouseholdIncomeEnumHouseholdIncomeTop11To20Percent HouseholdIncomeAssignedTargetingOptionDetailsHouseholdIncomeEnum = "HOUSEHOLD_INCOME_TOP_11_TO_20_PERCENT"
	HouseholdIncomeAssignedTargetingOptionDetailsHouseholdIncomeEnumHouseholdIncomeTop10Percent     HouseholdIncomeAssignedTargetingOptionDetailsHouseholdIncomeEnum = "HOUSEHOLD_INCOME_TOP_10_PERCENT"
)

type HouseholdIncomeAssignedTargetingOptionDetails struct {
	HouseholdIncome *HouseholdIncomeAssignedTargetingOptionDetailsHouseholdIncomeEnum `json:"householdIncome"`
}
