package shared

type NativeContentPositionTargetingOptionDetailsContentPositionEnum string

const (
	NativeContentPositionTargetingOptionDetailsContentPositionEnumNativeContentPositionUnspecified    NativeContentPositionTargetingOptionDetailsContentPositionEnum = "NATIVE_CONTENT_POSITION_UNSPECIFIED"
	NativeContentPositionTargetingOptionDetailsContentPositionEnumNativeContentPositionUnknown        NativeContentPositionTargetingOptionDetailsContentPositionEnum = "NATIVE_CONTENT_POSITION_UNKNOWN"
	NativeContentPositionTargetingOptionDetailsContentPositionEnumNativeContentPositionInArticle      NativeContentPositionTargetingOptionDetailsContentPositionEnum = "NATIVE_CONTENT_POSITION_IN_ARTICLE"
	NativeContentPositionTargetingOptionDetailsContentPositionEnumNativeContentPositionInFeed         NativeContentPositionTargetingOptionDetailsContentPositionEnum = "NATIVE_CONTENT_POSITION_IN_FEED"
	NativeContentPositionTargetingOptionDetailsContentPositionEnumNativeContentPositionPeripheral     NativeContentPositionTargetingOptionDetailsContentPositionEnum = "NATIVE_CONTENT_POSITION_PERIPHERAL"
	NativeContentPositionTargetingOptionDetailsContentPositionEnumNativeContentPositionRecommendation NativeContentPositionTargetingOptionDetailsContentPositionEnum = "NATIVE_CONTENT_POSITION_RECOMMENDATION"
)

type NativeContentPositionTargetingOptionDetails struct {
	ContentPosition *NativeContentPositionTargetingOptionDetailsContentPositionEnum `json:"contentPosition,omitempty"`
}
