package shared

type ParentalStatusTargetingOptionDetailsParentalStatusEnum string

const (
	ParentalStatusTargetingOptionDetailsParentalStatusEnumParentalStatusUnspecified ParentalStatusTargetingOptionDetailsParentalStatusEnum = "PARENTAL_STATUS_UNSPECIFIED"
	ParentalStatusTargetingOptionDetailsParentalStatusEnumParentalStatusParent      ParentalStatusTargetingOptionDetailsParentalStatusEnum = "PARENTAL_STATUS_PARENT"
	ParentalStatusTargetingOptionDetailsParentalStatusEnumParentalStatusNotAParent  ParentalStatusTargetingOptionDetailsParentalStatusEnum = "PARENTAL_STATUS_NOT_A_PARENT"
	ParentalStatusTargetingOptionDetailsParentalStatusEnumParentalStatusUnknown     ParentalStatusTargetingOptionDetailsParentalStatusEnum = "PARENTAL_STATUS_UNKNOWN"
)

// ParentalStatusTargetingOptionDetails
// Represents a targetable parental status. This will be populated in the parental_status_details field of a TargetingOption when targeting_type is `TARGETING_TYPE_PARENTAL_STATUS`.
type ParentalStatusTargetingOptionDetails struct {
	ParentalStatus *ParentalStatusTargetingOptionDetailsParentalStatusEnum `json:"parentalStatus,omitempty"`
}
