package shared




type ParentalStatusTargetingOptionDetailsParentalStatusEnum string

const (
    ParentalStatusTargetingOptionDetailsParentalStatusEnumParentalStatusUnspecified ParentalStatusTargetingOptionDetailsParentalStatusEnum = "PARENTAL_STATUS_UNSPECIFIED"
ParentalStatusTargetingOptionDetailsParentalStatusEnumParentalStatusParent ParentalStatusTargetingOptionDetailsParentalStatusEnum = "PARENTAL_STATUS_PARENT"
ParentalStatusTargetingOptionDetailsParentalStatusEnumParentalStatusNotAParent ParentalStatusTargetingOptionDetailsParentalStatusEnum = "PARENTAL_STATUS_NOT_A_PARENT"
ParentalStatusTargetingOptionDetailsParentalStatusEnumParentalStatusUnknown ParentalStatusTargetingOptionDetailsParentalStatusEnum = "PARENTAL_STATUS_UNKNOWN"
)


type ParentalStatusTargetingOptionDetails struct {
    ParentalStatus *ParentalStatusTargetingOptionDetailsParentalStatusEnum `json:"parentalStatus,omitempty"`
    
}

