package shared




type ViewabilityAssignedTargetingOptionDetailsViewabilityEnum string

const (
    ViewabilityAssignedTargetingOptionDetailsViewabilityEnumViewabilityUnspecified ViewabilityAssignedTargetingOptionDetailsViewabilityEnum = "VIEWABILITY_UNSPECIFIED"
ViewabilityAssignedTargetingOptionDetailsViewabilityEnumViewability10PercentOrMore ViewabilityAssignedTargetingOptionDetailsViewabilityEnum = "VIEWABILITY_10_PERCENT_OR_MORE"
ViewabilityAssignedTargetingOptionDetailsViewabilityEnumViewability20PercentOrMore ViewabilityAssignedTargetingOptionDetailsViewabilityEnum = "VIEWABILITY_20_PERCENT_OR_MORE"
ViewabilityAssignedTargetingOptionDetailsViewabilityEnumViewability30PercentOrMore ViewabilityAssignedTargetingOptionDetailsViewabilityEnum = "VIEWABILITY_30_PERCENT_OR_MORE"
ViewabilityAssignedTargetingOptionDetailsViewabilityEnumViewability40PercentOrMore ViewabilityAssignedTargetingOptionDetailsViewabilityEnum = "VIEWABILITY_40_PERCENT_OR_MORE"
ViewabilityAssignedTargetingOptionDetailsViewabilityEnumViewability50PercentOrMore ViewabilityAssignedTargetingOptionDetailsViewabilityEnum = "VIEWABILITY_50_PERCENT_OR_MORE"
ViewabilityAssignedTargetingOptionDetailsViewabilityEnumViewability60PercentOrMore ViewabilityAssignedTargetingOptionDetailsViewabilityEnum = "VIEWABILITY_60_PERCENT_OR_MORE"
ViewabilityAssignedTargetingOptionDetailsViewabilityEnumViewability70PercentOrMore ViewabilityAssignedTargetingOptionDetailsViewabilityEnum = "VIEWABILITY_70_PERCENT_OR_MORE"
ViewabilityAssignedTargetingOptionDetailsViewabilityEnumViewability80PercentOrMore ViewabilityAssignedTargetingOptionDetailsViewabilityEnum = "VIEWABILITY_80_PERCENT_OR_MORE"
ViewabilityAssignedTargetingOptionDetailsViewabilityEnumViewability90PercentOrMore ViewabilityAssignedTargetingOptionDetailsViewabilityEnum = "VIEWABILITY_90_PERCENT_OR_MORE"
)


type ViewabilityAssignedTargetingOptionDetails struct {
    Viewability *ViewabilityAssignedTargetingOptionDetailsViewabilityEnum `json:"viewability,omitempty"`
    
}

