from dataclasses import dataclass, field
from enum import Enum

class ContainerServiceStateDetailCodeEnum(str, Enum):
    CREATING_SYSTEM_RESOURCES = "CREATING_SYSTEM_RESOURCES"
    CREATING_NETWORK_INFRASTRUCTURE = "CREATING_NETWORK_INFRASTRUCTURE"
    PROVISIONING_CERTIFICATE = "PROVISIONING_CERTIFICATE"
    PROVISIONING_SERVICE = "PROVISIONING_SERVICE"
    CREATING_DEPLOYMENT = "CREATING_DEPLOYMENT"
    EVALUATING_HEALTH_CHECK = "EVALUATING_HEALTH_CHECK"
    ACTIVATING_DEPLOYMENT = "ACTIVATING_DEPLOYMENT"
    CERTIFICATE_LIMIT_EXCEEDED = "CERTIFICATE_LIMIT_EXCEEDED"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"

