{
  "swagger": "2.0",
  "info": {
    "title": "Blogger API",
    "description": "API for access to the data within Blogger.",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v3"
  },
  "host": "www.googleapis.com",
  "basePath": "/blogger/v3",
  "schemes": [
    "https"
  ],
  "paths": {
    "/users/{userId}/blogs/{blogId}": {
      "get": {
        "description": "Gets one blog and user info pair by blogId and userId.",
        "operationId": "blogger.blogUserInfos.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger",
              "https://www.googleapis.com/auth/blogger.readonly"
            ]
          }
        ]
      }
    },
    "/blogs/{blogId}": {
      "get": {
        "description": "Gets one blog by ID.",
        "operationId": "blogger.blogs.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger",
              "https://www.googleapis.com/auth/blogger.readonly"
            ]
          }
        ]
      }
    },
    "/blogs/byurl": {
      "get": {
        "description": "Retrieve a Blog by URL.",
        "operationId": "blogger.blogs.getByUrl",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger",
              "https://www.googleapis.com/auth/blogger.readonly"
            ]
          }
        ]
      }
    },
    "/users/{userId}/blogs": {
      "get": {
        "description": "Retrieves a list of blogs, possibly filtered.",
        "operationId": "blogger.blogs.listByUser",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger",
              "https://www.googleapis.com/auth/blogger.readonly"
            ]
          }
        ]
      }
    },
    "/blogs/{blogId}/posts/{postId}/comments/{commentId}/approve": {
      "post": {
        "description": "Marks a comment as not spam.",
        "operationId": "blogger.comments.approve",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger"
            ]
          }
        ]
      }
    },
    "/blogs/{blogId}/posts/{postId}/comments/{commentId}": {
      "delete": {
        "description": "Delete a comment by ID.",
        "operationId": "blogger.comments.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger"
            ]
          }
        ]
      },
      "get": {
        "description": "Gets one comment by ID.",
        "operationId": "blogger.comments.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger",
              "https://www.googleapis.com/auth/blogger.readonly"
            ]
          }
        ]
      }
    },
    "/blogs/{blogId}/posts/{postId}/comments": {
      "get": {
        "description": "Retrieves the comments for a post, possibly filtered.",
        "operationId": "blogger.comments.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger",
              "https://www.googleapis.com/auth/blogger.readonly"
            ]
          }
        ]
      }
    },
    "/blogs/{blogId}/comments": {
      "get": {
        "description": "Retrieves the comments for a blog, across all posts, possibly filtered.",
        "operationId": "blogger.comments.listByBlog",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger",
              "https://www.googleapis.com/auth/blogger.readonly"
            ]
          }
        ]
      }
    },
    "/blogs/{blogId}/posts/{postId}/comments/{commentId}/spam": {
      "post": {
        "description": "Marks a comment as spam.",
        "operationId": "blogger.comments.markAsSpam",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger"
            ]
          }
        ]
      }
    },
    "/blogs/{blogId}/posts/{postId}/comments/{commentId}/removecontent": {
      "post": {
        "description": "Removes the content of a comment.",
        "operationId": "blogger.comments.removeContent",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger"
            ]
          }
        ]
      }
    },
    "/blogs/{blogId}/pageviews": {
      "get": {
        "description": "Retrieve pageview stats for a Blog.",
        "operationId": "blogger.pageViews.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger"
            ]
          }
        ]
      }
    },
    "/blogs/{blogId}/pages/{pageId}": {
      "delete": {
        "description": "Delete a page by ID.",
        "operationId": "blogger.pages.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger"
            ]
          }
        ]
      },
      "get": {
        "description": "Gets one blog page by ID.",
        "operationId": "blogger.pages.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger",
              "https://www.googleapis.com/auth/blogger.readonly"
            ]
          }
        ]
      },
      "patch": {
        "description": "Update a page. This method supports patch semantics.",
        "operationId": "blogger.pages.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger"
            ]
          }
        ]
      },
      "put": {
        "description": "Update a page.",
        "operationId": "blogger.pages.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger"
            ]
          }
        ]
      }
    },
    "/blogs/{blogId}/pages": {
      "post": {
        "description": "Add a page.",
        "operationId": "blogger.pages.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger"
            ]
          }
        ]
      },
      "get": {
        "description": "Retrieves the pages for a blog, optionally including non-LIVE statuses.",
        "operationId": "blogger.pages.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger",
              "https://www.googleapis.com/auth/blogger.readonly"
            ]
          }
        ]
      }
    },
    "/blogs/{blogId}/pages/{pageId}/publish": {
      "post": {
        "description": "Publishes a draft page.",
        "operationId": "blogger.pages.publish",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger"
            ]
          }
        ]
      }
    },
    "/blogs/{blogId}/pages/{pageId}/revert": {
      "post": {
        "description": "Revert a published or scheduled page to draft state.",
        "operationId": "blogger.pages.revert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger"
            ]
          }
        ]
      }
    },
    "/users/{userId}/blogs/{blogId}/posts/{postId}": {
      "get": {
        "description": "Gets one post and user info pair, by post ID and user ID. The post user info contains per-user information about the post, such as access rights, specific to the user.",
        "operationId": "blogger.postUserInfos.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger",
              "https://www.googleapis.com/auth/blogger.readonly"
            ]
          }
        ]
      }
    },
    "/users/{userId}/blogs/{blogId}/posts": {
      "get": {
        "description": "Retrieves a list of post and post user info pairs, possibly filtered. The post user info contains per-user information about the post, such as access rights, specific to the user.",
        "operationId": "blogger.postUserInfos.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger",
              "https://www.googleapis.com/auth/blogger.readonly"
            ]
          }
        ]
      }
    },
    "/blogs/{blogId}/posts/{postId}": {
      "delete": {
        "description": "Delete a post by ID.",
        "operationId": "blogger.posts.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger"
            ]
          }
        ]
      },
      "get": {
        "description": "Get a post by ID.",
        "operationId": "blogger.posts.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger",
              "https://www.googleapis.com/auth/blogger.readonly"
            ]
          }
        ]
      },
      "patch": {
        "description": "Update a post. This method supports patch semantics.",
        "operationId": "blogger.posts.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger"
            ]
          }
        ]
      },
      "put": {
        "description": "Update a post.",
        "operationId": "blogger.posts.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger"
            ]
          }
        ]
      }
    },
    "/blogs/{blogId}/posts/bypath": {
      "get": {
        "description": "Retrieve a Post by Path.",
        "operationId": "blogger.posts.getByPath",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger",
              "https://www.googleapis.com/auth/blogger.readonly"
            ]
          }
        ]
      }
    },
    "/blogs/{blogId}/posts": {
      "post": {
        "description": "Add a post.",
        "operationId": "blogger.posts.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger"
            ]
          }
        ]
      },
      "get": {
        "description": "Retrieves a list of posts, possibly filtered.",
        "operationId": "blogger.posts.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger",
              "https://www.googleapis.com/auth/blogger.readonly"
            ]
          }
        ]
      }
    },
    "/blogs/{blogId}/posts/{postId}/publish": {
      "post": {
        "description": "Publishes a draft post, optionally at the specific time of the given publishDate parameter.",
        "operationId": "blogger.posts.publish",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger"
            ]
          }
        ]
      }
    },
    "/blogs/{blogId}/posts/{postId}/revert": {
      "post": {
        "description": "Revert a published or scheduled post to draft state.",
        "operationId": "blogger.posts.revert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger"
            ]
          }
        ]
      }
    },
    "/blogs/{blogId}/posts/search": {
      "get": {
        "description": "Search for a post.",
        "operationId": "blogger.posts.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger",
              "https://www.googleapis.com/auth/blogger.readonly"
            ]
          }
        ]
      }
    },
    "/users/{userId}": {
      "get": {
        "description": "Gets one user by ID.",
        "operationId": "blogger.users.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/blogger",
              "https://www.googleapis.com/auth/blogger.readonly"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/blogger": "Manage your Blogger account",
        "https://www.googleapis.com/auth/blogger.readonly": "View your Blogger account"
      }
    }
  }
}