package shared

type CustomFloodlightVariableTypeEnum string

const (
	CustomFloodlightVariableTypeEnumU1   CustomFloodlightVariableTypeEnum = "U1"
	CustomFloodlightVariableTypeEnumU2   CustomFloodlightVariableTypeEnum = "U2"
	CustomFloodlightVariableTypeEnumU3   CustomFloodlightVariableTypeEnum = "U3"
	CustomFloodlightVariableTypeEnumU4   CustomFloodlightVariableTypeEnum = "U4"
	CustomFloodlightVariableTypeEnumU5   CustomFloodlightVariableTypeEnum = "U5"
	CustomFloodlightVariableTypeEnumU6   CustomFloodlightVariableTypeEnum = "U6"
	CustomFloodlightVariableTypeEnumU7   CustomFloodlightVariableTypeEnum = "U7"
	CustomFloodlightVariableTypeEnumU8   CustomFloodlightVariableTypeEnum = "U8"
	CustomFloodlightVariableTypeEnumU9   CustomFloodlightVariableTypeEnum = "U9"
	CustomFloodlightVariableTypeEnumU10  CustomFloodlightVariableTypeEnum = "U10"
	CustomFloodlightVariableTypeEnumU11  CustomFloodlightVariableTypeEnum = "U11"
	CustomFloodlightVariableTypeEnumU12  CustomFloodlightVariableTypeEnum = "U12"
	CustomFloodlightVariableTypeEnumU13  CustomFloodlightVariableTypeEnum = "U13"
	CustomFloodlightVariableTypeEnumU14  CustomFloodlightVariableTypeEnum = "U14"
	CustomFloodlightVariableTypeEnumU15  CustomFloodlightVariableTypeEnum = "U15"
	CustomFloodlightVariableTypeEnumU16  CustomFloodlightVariableTypeEnum = "U16"
	CustomFloodlightVariableTypeEnumU17  CustomFloodlightVariableTypeEnum = "U17"
	CustomFloodlightVariableTypeEnumU18  CustomFloodlightVariableTypeEnum = "U18"
	CustomFloodlightVariableTypeEnumU19  CustomFloodlightVariableTypeEnum = "U19"
	CustomFloodlightVariableTypeEnumU20  CustomFloodlightVariableTypeEnum = "U20"
	CustomFloodlightVariableTypeEnumU21  CustomFloodlightVariableTypeEnum = "U21"
	CustomFloodlightVariableTypeEnumU22  CustomFloodlightVariableTypeEnum = "U22"
	CustomFloodlightVariableTypeEnumU23  CustomFloodlightVariableTypeEnum = "U23"
	CustomFloodlightVariableTypeEnumU24  CustomFloodlightVariableTypeEnum = "U24"
	CustomFloodlightVariableTypeEnumU25  CustomFloodlightVariableTypeEnum = "U25"
	CustomFloodlightVariableTypeEnumU26  CustomFloodlightVariableTypeEnum = "U26"
	CustomFloodlightVariableTypeEnumU27  CustomFloodlightVariableTypeEnum = "U27"
	CustomFloodlightVariableTypeEnumU28  CustomFloodlightVariableTypeEnum = "U28"
	CustomFloodlightVariableTypeEnumU29  CustomFloodlightVariableTypeEnum = "U29"
	CustomFloodlightVariableTypeEnumU30  CustomFloodlightVariableTypeEnum = "U30"
	CustomFloodlightVariableTypeEnumU31  CustomFloodlightVariableTypeEnum = "U31"
	CustomFloodlightVariableTypeEnumU32  CustomFloodlightVariableTypeEnum = "U32"
	CustomFloodlightVariableTypeEnumU33  CustomFloodlightVariableTypeEnum = "U33"
	CustomFloodlightVariableTypeEnumU34  CustomFloodlightVariableTypeEnum = "U34"
	CustomFloodlightVariableTypeEnumU35  CustomFloodlightVariableTypeEnum = "U35"
	CustomFloodlightVariableTypeEnumU36  CustomFloodlightVariableTypeEnum = "U36"
	CustomFloodlightVariableTypeEnumU37  CustomFloodlightVariableTypeEnum = "U37"
	CustomFloodlightVariableTypeEnumU38  CustomFloodlightVariableTypeEnum = "U38"
	CustomFloodlightVariableTypeEnumU39  CustomFloodlightVariableTypeEnum = "U39"
	CustomFloodlightVariableTypeEnumU40  CustomFloodlightVariableTypeEnum = "U40"
	CustomFloodlightVariableTypeEnumU41  CustomFloodlightVariableTypeEnum = "U41"
	CustomFloodlightVariableTypeEnumU42  CustomFloodlightVariableTypeEnum = "U42"
	CustomFloodlightVariableTypeEnumU43  CustomFloodlightVariableTypeEnum = "U43"
	CustomFloodlightVariableTypeEnumU44  CustomFloodlightVariableTypeEnum = "U44"
	CustomFloodlightVariableTypeEnumU45  CustomFloodlightVariableTypeEnum = "U45"
	CustomFloodlightVariableTypeEnumU46  CustomFloodlightVariableTypeEnum = "U46"
	CustomFloodlightVariableTypeEnumU47  CustomFloodlightVariableTypeEnum = "U47"
	CustomFloodlightVariableTypeEnumU48  CustomFloodlightVariableTypeEnum = "U48"
	CustomFloodlightVariableTypeEnumU49  CustomFloodlightVariableTypeEnum = "U49"
	CustomFloodlightVariableTypeEnumU50  CustomFloodlightVariableTypeEnum = "U50"
	CustomFloodlightVariableTypeEnumU51  CustomFloodlightVariableTypeEnum = "U51"
	CustomFloodlightVariableTypeEnumU52  CustomFloodlightVariableTypeEnum = "U52"
	CustomFloodlightVariableTypeEnumU53  CustomFloodlightVariableTypeEnum = "U53"
	CustomFloodlightVariableTypeEnumU54  CustomFloodlightVariableTypeEnum = "U54"
	CustomFloodlightVariableTypeEnumU55  CustomFloodlightVariableTypeEnum = "U55"
	CustomFloodlightVariableTypeEnumU56  CustomFloodlightVariableTypeEnum = "U56"
	CustomFloodlightVariableTypeEnumU57  CustomFloodlightVariableTypeEnum = "U57"
	CustomFloodlightVariableTypeEnumU58  CustomFloodlightVariableTypeEnum = "U58"
	CustomFloodlightVariableTypeEnumU59  CustomFloodlightVariableTypeEnum = "U59"
	CustomFloodlightVariableTypeEnumU60  CustomFloodlightVariableTypeEnum = "U60"
	CustomFloodlightVariableTypeEnumU61  CustomFloodlightVariableTypeEnum = "U61"
	CustomFloodlightVariableTypeEnumU62  CustomFloodlightVariableTypeEnum = "U62"
	CustomFloodlightVariableTypeEnumU63  CustomFloodlightVariableTypeEnum = "U63"
	CustomFloodlightVariableTypeEnumU64  CustomFloodlightVariableTypeEnum = "U64"
	CustomFloodlightVariableTypeEnumU65  CustomFloodlightVariableTypeEnum = "U65"
	CustomFloodlightVariableTypeEnumU66  CustomFloodlightVariableTypeEnum = "U66"
	CustomFloodlightVariableTypeEnumU67  CustomFloodlightVariableTypeEnum = "U67"
	CustomFloodlightVariableTypeEnumU68  CustomFloodlightVariableTypeEnum = "U68"
	CustomFloodlightVariableTypeEnumU69  CustomFloodlightVariableTypeEnum = "U69"
	CustomFloodlightVariableTypeEnumU70  CustomFloodlightVariableTypeEnum = "U70"
	CustomFloodlightVariableTypeEnumU71  CustomFloodlightVariableTypeEnum = "U71"
	CustomFloodlightVariableTypeEnumU72  CustomFloodlightVariableTypeEnum = "U72"
	CustomFloodlightVariableTypeEnumU73  CustomFloodlightVariableTypeEnum = "U73"
	CustomFloodlightVariableTypeEnumU74  CustomFloodlightVariableTypeEnum = "U74"
	CustomFloodlightVariableTypeEnumU75  CustomFloodlightVariableTypeEnum = "U75"
	CustomFloodlightVariableTypeEnumU76  CustomFloodlightVariableTypeEnum = "U76"
	CustomFloodlightVariableTypeEnumU77  CustomFloodlightVariableTypeEnum = "U77"
	CustomFloodlightVariableTypeEnumU78  CustomFloodlightVariableTypeEnum = "U78"
	CustomFloodlightVariableTypeEnumU79  CustomFloodlightVariableTypeEnum = "U79"
	CustomFloodlightVariableTypeEnumU80  CustomFloodlightVariableTypeEnum = "U80"
	CustomFloodlightVariableTypeEnumU81  CustomFloodlightVariableTypeEnum = "U81"
	CustomFloodlightVariableTypeEnumU82  CustomFloodlightVariableTypeEnum = "U82"
	CustomFloodlightVariableTypeEnumU83  CustomFloodlightVariableTypeEnum = "U83"
	CustomFloodlightVariableTypeEnumU84  CustomFloodlightVariableTypeEnum = "U84"
	CustomFloodlightVariableTypeEnumU85  CustomFloodlightVariableTypeEnum = "U85"
	CustomFloodlightVariableTypeEnumU86  CustomFloodlightVariableTypeEnum = "U86"
	CustomFloodlightVariableTypeEnumU87  CustomFloodlightVariableTypeEnum = "U87"
	CustomFloodlightVariableTypeEnumU88  CustomFloodlightVariableTypeEnum = "U88"
	CustomFloodlightVariableTypeEnumU89  CustomFloodlightVariableTypeEnum = "U89"
	CustomFloodlightVariableTypeEnumU90  CustomFloodlightVariableTypeEnum = "U90"
	CustomFloodlightVariableTypeEnumU91  CustomFloodlightVariableTypeEnum = "U91"
	CustomFloodlightVariableTypeEnumU92  CustomFloodlightVariableTypeEnum = "U92"
	CustomFloodlightVariableTypeEnumU93  CustomFloodlightVariableTypeEnum = "U93"
	CustomFloodlightVariableTypeEnumU94  CustomFloodlightVariableTypeEnum = "U94"
	CustomFloodlightVariableTypeEnumU95  CustomFloodlightVariableTypeEnum = "U95"
	CustomFloodlightVariableTypeEnumU96  CustomFloodlightVariableTypeEnum = "U96"
	CustomFloodlightVariableTypeEnumU97  CustomFloodlightVariableTypeEnum = "U97"
	CustomFloodlightVariableTypeEnumU98  CustomFloodlightVariableTypeEnum = "U98"
	CustomFloodlightVariableTypeEnumU99  CustomFloodlightVariableTypeEnum = "U99"
	CustomFloodlightVariableTypeEnumU100 CustomFloodlightVariableTypeEnum = "U100"
)

type CustomFloodlightVariable struct {
	Kind  *string                           `json:"kind,omitempty"`
	Type  *CustomFloodlightVariableTypeEnum `json:"type,omitempty"`
	Value *string                           `json:"value,omitempty"`
}
