

export enum SectionEnum {
    Arts = "Arts"
,    Automobiles = "Automobiles"
,    Blogs = "Blogs"
,    Books = "Books"
,    BusinessDay = "Business Day"
,    Education = "Education"
,    FashionAndStyle = "Fashion & Style"
,    Food = "Food"
,    Health = "Health"
,    JobMarket = "Job Market"
,    Magazine = "Magazine"
,    Membercenter = "membercenter"
,    Movies = "Movies"
,    Multimedia = "Multimedia"
,    NYPercent20Percent2FPercent20Region = "N.Y.%20%2F%20Region"
,    NytNow = "NYT Now"
,    Obituaries = "Obituaries"
,    Open = "Open"
,    Opinion = "Opinion"
,    PublicEditor = "Public Editor"
,    RealEstate = "Real Estate"
,    Science = "Science"
,    Sports = "Sports"
,    Style = "Style"
,    SundayReview = "Sunday Review"
,    TMagazine = "T Magazine"
,    Technology = "Technology"
,    TheUpshot = "The Upshot"
,    Theater = "Theater"
,    TimesInsider = "Times Insider"
,    TodaySPaper = "Today’s Paper"
,    Travel = "Travel"
,    US = "U.S."
,    World = "World"
,    YourMoney = "Your Money"
,    AllSections = "all-sections"
}
