package shared

type BatchPutAssetPropertyValueErrorCodeEnum string

const (
	BatchPutAssetPropertyValueErrorCodeEnumResourceNotFoundException     BatchPutAssetPropertyValueErrorCodeEnum = "ResourceNotFoundException"
	BatchPutAssetPropertyValueErrorCodeEnumInvalidRequestException       BatchPutAssetPropertyValueErrorCodeEnum = "InvalidRequestException"
	BatchPutAssetPropertyValueErrorCodeEnumInternalFailureException      BatchPutAssetPropertyValueErrorCodeEnum = "InternalFailureException"
	BatchPutAssetPropertyValueErrorCodeEnumServiceUnavailableException   BatchPutAssetPropertyValueErrorCodeEnum = "ServiceUnavailableException"
	BatchPutAssetPropertyValueErrorCodeEnumThrottlingException           BatchPutAssetPropertyValueErrorCodeEnum = "ThrottlingException"
	BatchPutAssetPropertyValueErrorCodeEnumLimitExceededException        BatchPutAssetPropertyValueErrorCodeEnum = "LimitExceededException"
	BatchPutAssetPropertyValueErrorCodeEnumConflictingOperationException BatchPutAssetPropertyValueErrorCodeEnum = "ConflictingOperationException"
	BatchPutAssetPropertyValueErrorCodeEnumTimestampOutOfRangeException  BatchPutAssetPropertyValueErrorCodeEnum = "TimestampOutOfRangeException"
	BatchPutAssetPropertyValueErrorCodeEnumAccessDeniedException         BatchPutAssetPropertyValueErrorCodeEnum = "AccessDeniedException"
)
