export * from "./deletelexicon";
export * from "./describevoices";
export * from "./getlexicon";
export * from "./getspeechsynthesistask";
export * from "./listlexicons";
export * from "./listspeechsynthesistasks";
export * from "./putlexicon";
export * from "./startspeechsynthesistask";
export * from "./synthesizespeech";
