openapi: 3.0.0
servers:
  - description: Sandbox server for integrators
    url: https://sandbox.gerermesaffaires.com/api/v1/
info:
  contact:
    email: api@gerermesaffaires.com
  description: Sécurisez vos données en interfaçant votre logiciel métier avec le service en ligne GererMesAffaires
  title: GererMesAffaires {REST:API}
  version: 1.0.6
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_www.gerermesaffaires.com_wp-content_uploads_2019_09_cropped-logo-2019-180x180.png
  x-origin:
    - format: openapi
      url: https://api.gerermesaffaires.com/wp-content/uploads/2022/09/GmaAPI-GererMesAffairesAPI-1.0.6-swagger.json
      version: "3.0"
  x-providerName: gerermesaffaires.com
security:
  - gma_auth:
      - collaborator
      - owner
      - robot
paths:
  /box/menus:
    get:
      description: Returns predefined folders and workbooks of the Box for all the spaces
      security:
        - gma_auth:
            - owner
  /business-groups:
    get:
      description: Returns a list of groups custom ordered by name
      security:
        - gma_auth:
            - collaborator
    patch:
      description: Modifies an object
      security:
        - gma_auth:
            - collaborator
    post:
      description: Adds a group (only for managers and ADN collaborators)
      security:
        - gma_auth:
            - collaborator
  /business-groups/all:
    get:
      description: Returns list of groups custom for managers
      security:
        - gma_auth:
            - collaborator
  "/business-groups/{id}":
    get:
      description: Returns a group
      security:
        - gma_auth:
            - collaborator
  "/business-groups/{id}/spaces":
    get:
      description: Returns spaces of the business group with id
      security:
        - gma_auth:
            - collaborator
  "/business-groups/{id}/spaces/{spaceId}":
    delete:
      description: Remove a customer space from partner
      security:
        - gma_auth:
            - collaborator
  "/business-groups/{id}/spaces/{spaceId}/legal-entities/{personId}/customers/{folderId}/guest-in-space":
    post:
      description: send an invitation to manager the private space of personId
      security:
        - gma_auth:
            - collaborator
  "/business-groups/{id}/spaces/{spaceId}/legal-entities/{personId}/customers/{folderId}/spaces":
    post:
      description: Add a Space in a group
      security:
        - gma_auth:
            - collaborator
  "/hub/business-groups/{Id}/menus":
    get:
      description: Returns predefined folders and workbooks of the Hub for all the spaces of the business group
      security:
        - gma_auth:
            - collaborator
  /hub/documents:
    post:
      description: Add a document (this document is analyzed to be saved in the correct folder and correct space)
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  /hub/menus:
    get:
      description: Returns predefined folders and workbooks of the Hub for all the spaces
      security:
        - gma_auth:
            - collaborator
  /hub/menus/all:
    get:
      description: Returns predefined folders and workbooks of the Hub for all the spaces and customer spaces
      security:
        - gma_auth:
            - collaborator
  /hub/payslips:
    post:
      description: Add a payslip (this document is analyzed to be saved in the correct folder and correct space)
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/hub/spaces/{spaceId}/documents":
    post:
      description: Add a document in a space (this document is analyzed to be saved in the correct folder)
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/hub/spaces/{spaceId}/menus":
    get:
      description: Returns predefined folders and workbooks of the Hub for the space
  "/hub/spaces/{spaceId}/payslips":
    post:
      description: Add a payslip in a space (this document is analyzed to be saved in the correct folder)
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  /menus:
    get:
      description: Returns predefined entries
  "/menus/{menuId}/documents":
    post:
      description: add a document to the target menuId
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
            - box
            - hub
  /profile:
    get:
      description: Returns status of member
      security:
        - gma_auth:
            - owner
    patch:
      description: modify infos of profile
      security:
        - gma_auth:
            - owner
    post:
      description: create infos of profile
      security:
        - gma_auth:
            - owner
  /profile/email:
    patch:
      description: modify email of profile
      security:
        - gma_auth:
            - owner
  /profile/id-file:
    get:
      description: Returns status of member
  /profile/mobile:
    patch:
      description: modify mobile of profile
      security:
        - gma_auth:
            - owner
  /registration:
    get:
      description: Returns the method to get the validation code or the link to register after invitation
      security:
        - gma_auth:
            - owner
    post:
      description: complete the invitation
      security:
        - gma_auth:
            - owner
  /session:
    get:
      description: Returns member id of user logged
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  /spaces:
    get:
      description: Returns spaces of my group
    post:
      description: Add a Space in my group
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  /spaces/all:
    get:
      description: Returns all spaces
  "/spaces/{id}":
    delete:
      description: Delete a Space (only space not delivered to customer)
    get:
      description: Returns a space
    patch:
      description: Modify a Space (except private)
  "/spaces/{id}/accounting-year":
    get:
      description: Returns list of accounting years for the space {id}
    post:
      description: Create a accounting year for the space id
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{id}/collective-decision":
    get:
      description: Returns list of collective decisions for the space {id}
    post:
      description: Create a colletive decision for the space id
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{id}/company-entities":
    get:
      description: Returns list of company entities
    post:
      description: Add a Company Entity in a Space
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{id}/company-entities/all":
    get:
      description: Returns list of company entities even company entities archived
  "/spaces/{id}/company-entities/{companyId}":
    get:
      description: Returns a compay entity
    patch:
      description: Modify a company entity
  "/spaces/{id}/company-entities/{personId}/details":
    get:
      description: Returns all details of a company entity
    post:
      description: Replace or Add a contact detail for a person
  "/spaces/{id}/company-entities/{personId}/details/{designation}":
    delete:
      description: delete a contact detail for a company entity
  "/spaces/{id}/documents/download":
    post:
      description: create an archive with documents
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{id}/folders/{folderId}/persons/{memberId}":
    get:
      description: return the access of a person in a customer contract
    patch:
      description: Add/Modify/Delete a person in a customer contract (except manager)
  "/spaces/{id}/folders/{folderId}/persons/{memberId}/activeaccess":
    patch:
      description: open an access
  "/spaces/{id}/folders/{folderId}/persons/{memberId}/unactiveaccess":
    patch:
      description: close an access
  "/spaces/{id}/folders/{folderId}/persons/{personId}/guest-in-space":
    post:
      description: invite a owner in a space
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{id}/groups":
    get:
      description: Returns list of groups
    post:
      description: Add a group in a Space
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{id}/groups/all":
    get:
      description: Returns list of groups even archived of the space
  "/spaces/{id}/groups/{groupId}":
    get:
      description: Returns a group
    patch:
      description: Modify a group
  "/spaces/{id}/groups/{groupId}/folders/{folderId}":
    delete:
      description: delete access to a folder for a group
    patch:
      description: Add access to a folder for a group
  "/spaces/{id}/groups/{groupId}/persons/{memberId}":
    delete:
      description: Delete a person of a group
    patch:
      description: Add a person to a group
  "/spaces/{id}/legal":
    get:
      description: Returns legal information of a space (except private)
    patch:
      description: Modify legal information of a Space (except private)
  "/spaces/{id}/logo":
    get:
      description: Returns a space with the logo
  "/spaces/{id}/persons":
    get:
      description: Returns list of persons
    post:
      description: Add a Person in a Space
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{id}/persons/all":
    get:
      description: Returns list of persons even persons archived
  "/spaces/{id}/persons/{memberId}/player":
    patch:
      description: Modify the role of a person
  "/spaces/{id}/persons/{personId}":
    delete:
      description: delete a person
    get:
      description: Returns a person
    patch:
      description: Modify a person
  "/spaces/{id}/persons/{personId}/details":
    get:
      description: Returns all details of a person
    post:
      description: Replace or Add a contact detail for a person
  "/spaces/{id}/persons/{personId}/details/{designation}":
    delete:
      description: delete a contact detail for a person
  "/spaces/{id}/persons/{personId}/folders":
    get:
      description: Returns list of folders with exceptionnal access of the person personId
  "/spaces/{id}/persons/{personId}/groups":
    get:
      description: Returns list of groups of the person personId
  "/spaces/{id}/persons/{personId}/portfolios":
    get:
      description: Returns list of portfolios of the person personId
    post:
      description: Create a portfolio for the person personId
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{id}/portfolios/{portfolioId}/persons/{memberId}":
    patch:
      description: Add/Modify/Delete a person in a portfolio (except manager)
  "/spaces/{id}/professional-vehicles":
    get:
      description: Returns list of professionalvehicles for the space {id}
    post:
      description: Create a professional vehicle for the space
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{id}/settings/nf203/logs":
    get:
      description: Returns state of activation of logs
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
    post:
      description: Enable/Disable logs
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{id}/status":
    get:
      description: Returns all status of the space
    post:
      description: Replace or Add a status
  "/spaces/{id}/status/{code}":
    delete:
      description: delete a status of the space
  "/spaces/{id}/tax-contracts":
    get:
      description: Returns list of tax contracts for the space {id}
    post:
      description: Create a tax contract for the space
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{id}/triggers":
    get:
      description: Returns list of triggers for the space {id}
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{id}/triggers/{name}":
    delete:
      description: Deletes a trigger for the space id
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
    post:
      description: Creates a trigger for the space id
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/common-folders/{id}":
    delete:
      description: Delete a common folder
    patch:
      description: Modify a common folder
  "/spaces/{spaceId}/company-entities/{id}/follow-ups":
    get:
      description: Returns folder of the company entity
  "/spaces/{spaceId}/customers":
    get:
      description: Returns folder with Id and customer data
  "/spaces/{spaceId}/customers/all":
    get:
      description: Returns folder with Id and customer data (even archived)
  "/spaces/{spaceId}/documents":
    get:
      description: Returns documents of the folder
  "/spaces/{spaceId}/documents/{documentId}":
    patch:
      description: modify a doc
  "/spaces/{spaceId}/documents/{documentId}/extend":
    get:
      description: read the data of a document
    post:
      description: Add a data to a document
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/documents/{documentId}/folders":
    get:
      description: Returns versions of the document
  "/spaces/{spaceId}/documents/{documentId}/mailing":
    post:
      description: send by mail a document
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/documents/{documentId}/mailingprice":
    get:
      description: returns the number of pages and the price of the pdf to send by mail
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/documents/{documentId}/versions":
    get:
      description: Returns versions of the document
    post:
      description: Add a version to a document and set it as current
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/documents/{documentId}/versions/current":
    get:
      description: Returns current version of the document
  "/spaces/{spaceId}/documents/{id}/access":
    get:
      description: Returns accesses of one document
  "/spaces/{spaceId}/documents/{id}/accounting":
    get:
      description: Returns the document with the accounting property
  "/spaces/{spaceId}/documents/{id}/download":
    get:
      description: Returns content of one document
  "/spaces/{spaceId}/employees":
    get:
      description: Returns folders with Id and employee data
  "/spaces/{spaceId}/employees/all":
    get:
      description: Returns folders with Id and employee data (even archived)
  "/spaces/{spaceId}/employers":
    get:
      description: Returns folders with Id and employer data
  "/spaces/{spaceId}/employers/all":
    get:
      description: Returns folders with Id and employer data (even archived)
  "/spaces/{spaceId}/extend":
    get:
      description: read the data of a space
    post:
      description: Add a data to a space
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/folders":
    get:
      description: Returns folders of the space
  "/spaces/{spaceId}/folders/all":
    get:
      description: Returns folders of the space (even archived)
  "/spaces/{spaceId}/folders/{folderId}/bank-statements/{documentId}":
    delete:
      description: delete a bank statement
    patch:
      description: modify a bank statement
  "/spaces/{spaceId}/folders/{folderId}/contractual-documents/{documentId}":
    delete:
      description: delete a contractual document
    patch:
      description: modify a contractual document
  "/spaces/{spaceId}/folders/{folderId}/corporate-tax-declarations/{documentId}":
    delete:
      description: delete a corporate tax declaration
    patch:
      description: modify a coporate tax declaration
  "/spaces/{spaceId}/folders/{folderId}/expense-proofs/{documentId}":
    delete:
      description: delete an expense proof
    patch:
      description: modify an expense report
  "/spaces/{spaceId}/folders/{folderId}/expense-reports/{documentId}":
    delete:
      description: delete an expense report
    patch:
      description: modify an expense report
  "/spaces/{spaceId}/folders/{folderId}/invoices/{documentId}":
    delete:
      description: delete an invoice document
    patch:
      description: modify a invoice
  "/spaces/{spaceId}/folders/{folderId}/nominative-social-declarations/{documentId}":
    get:
      description: get a nominative social declaration
  "/spaces/{spaceId}/folders/{folderId}/other-taxes/{documentId}":
    delete:
      description: delete a tax declaration
    patch:
      description: modify an other tax declaration
  "/spaces/{spaceId}/folders/{folderId}/payrolls/{documentId}":
    delete:
      description: delete a payroll
    patch:
      description: modify a payroll
  "/spaces/{spaceId}/folders/{folderId}/payrolls/{documentId}/refresh":
    post:
      description: recalculate a payroll
  "/spaces/{spaceId}/folders/{folderId}/payslips/{documentId}":
    delete:
      description: delete a payslip
    patch:
      description: modify a payslip
  "/spaces/{spaceId}/folders/{folderId}/social-contracts/{documentId}":
    delete:
      description: delete a social contract
    patch:
      description: modify a social contract
  "/spaces/{spaceId}/folders/{folderId}/social-declarations/{documentId}":
    delete:
      description: delete a social declaration
    patch:
      description: modify a social declaration
  "/spaces/{spaceId}/folders/{folderId}/vat-declarations/{documentId}":
    delete:
      description: delete a VAT declaration
    patch:
      description: modify a vat declaration
  "/spaces/{spaceId}/folders/{id}":
    get:
      description: Returns folder with Id
    patch:
      description: Modify a Folder (except Name, Class, ModificationDate and ArchivalDate)
  "/spaces/{spaceId}/folders/{id}/accounting-year":
    delete:
      description: delete an AccountingYear
    patch:
      description: Modify a Folder (except Name, Class, ModificationDate and ArchivalDate) and AccountingYear data
  "/spaces/{spaceId}/folders/{id}/accountings":
    get:
      description: Returns accountings documents of the folder (results and taxation or accountingyear)
  "/spaces/{spaceId}/folders/{id}/accountings-journal":
    get:
      description: journal of accountings document delivered to a customer
  "/spaces/{spaceId}/folders/{id}/bank":
    delete:
      description: Delete a Folder (except Name, Class, ModificationDate and ArchivalDate) and Bank data
    get:
      description: Returns folder with Id and bank data
    patch:
      description: Modify a Folder (except Name, Class, ModificationDate and ArchivalDate) and Bank data
  "/spaces/{spaceId}/folders/{id}/bank-statements":
    get:
      description: Returns bank statements of the folder bank
    post:
      description: Add a bank statement in a folder bank
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/folders/{id}/collective-decision":
    patch:
      description: Modify a Folder (except Name, Class, ModificationDate and ArchivalDate) and Collective Decision data
  "/spaces/{spaceId}/folders/{id}/common-folders":
    get:
      description: Returns common folders of a folder
    post:
      description: Add a common folder in another folder
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/folders/{id}/common-folders/all":
    get:
      description: Returns common folders (even archived) of a folder
  "/spaces/{spaceId}/folders/{id}/contracting-partner":
    get:
      description: Returns all contracting partners of a contract
  "/spaces/{spaceId}/folders/{id}/contracting-partner/space":
    get:
      description: Returns collector space of a contract
  "/spaces/{spaceId}/folders/{id}/contractual-documents":
    get:
      description: Returns documents of the folder
    post:
      description: Add a document in a folder
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/folders/{id}/contractual-relationship":
    get:
      description: Returns folder with Id and contractual-relationship data
  "/spaces/{spaceId}/folders/{id}/coporate-tax-declarations":
    get:
      description: Returns corporate tax declarations
    post:
      description: Add a corporate tax declaration
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/folders/{id}/customer":
    delete:
      description: delete a customer
    get:
      description: Returns folder with Id and customer data
    patch:
      description: Modify a Folder (except Name, Class, ModificationDate and ArchivalDate) and Customer data
  "/spaces/{spaceId}/folders/{id}/deliveries-journal":
    get:
      description: journal of documents delivered to a customer
  "/spaces/{spaceId}/folders/{id}/documents":
    get:
      description: Returns documents of the folder
    post:
      description: Add a document in a folder
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/folders/{id}/documents/{documentId}/detach":
    patch:
      description: Detach a doc of a folder
  "/spaces/{spaceId}/folders/{id}/employee":
    delete:
      description: Delete a Folder (except Name, Class, ModificationDate and ArchivalDate) and Employee data
    get:
      description: Returns folder with Id and employee data
    patch:
      description: Modify a Folder (except Name, Class, ModificationDate and ArchivalDate) and Employee data
  "/spaces/{spaceId}/folders/{id}/expense-proofs":
    get:
      description: Returns expense proofs of the folder (social, followup or exchange)
    post:
      description: Add a expense proof in a folder followup or exchange
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/folders/{id}/expense-reports":
    get:
      description: Returns expense reports of the folder (social or followup)
    post:
      description: Add a expense report in a folder followup
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/folders/{id}/expense-reports/{expenseReportId}/expense-proofs":
    get:
      description: Returns expense proofs linked to the expenseReportId
  "/spaces/{spaceId}/folders/{id}/insurance":
    delete:
      description: Delete a Folder (except Name, Class, ModificationDate and ArchivalDate) and Insurance data
    get:
      description: Returns folder with Id and insurance data
    patch:
      description: Modify a Folder (except Name, Class, ModificationDate and ArchivalDate) and Insurance data
  "/spaces/{spaceId}/folders/{id}/invoices":
    get:
      description: Returns invoices of the folder (customer, provider, accountingyear or root folders customers or providers)
    post:
      description: Add a invoice in a folder of a customer or a provider
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/folders/{id}/legal-entity":
    get:
      description: Returns legal entity of a follow up folder
  "/spaces/{spaceId}/folders/{id}/loan":
    delete:
      description: Delete a Folder (except Name, Class, ModificationDate and ArchivalDate) and Loan data
    get:
      description: Returns folder with Id and loan data
    patch:
      description: Modify a Folder (except Name, Class, ModificationDate and ArchivalDate) and Loan data
  "/spaces/{spaceId}/folders/{id}/messages":
    get:
      description: Returns messages of the folder
    post:
      description: Write a message in the journal of a folder
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/folders/{id}/messages/{messageId}":
    get:
      description: Returns message with Id
    patch:
      description: Modify a Message
  "/spaces/{spaceId}/folders/{id}/nominative-social-declarations":
    get:
      description: Returns nominative social declarations of the folder social
  "/spaces/{spaceId}/folders/{id}/other-taxes":
    get:
      description: Returns other taxes declarations
    post:
      description: Add a tax declaration
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/folders/{id}/passwords":
    get:
      description: Returns identifiers/passwords of the folder
    post:
      description: Write a identifier/password in aa folder
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/folders/{id}/passwords/{passwordId}":
    delete:
      description: delete a password
    get:
      description: Returns password with Id
    patch:
      description: Modify a Password
  "/spaces/{spaceId}/folders/{id}/payrolls":
    get:
      description: Returns payrolls of the folder social
    post:
      description: Add a payroll in a folder social
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/folders/{id}/payrolls/{payrollId}/nominative-social-declaration":
    delete:
      description: delete a nominative social declaration in a folder social
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
    post:
      description: Add a nominative social declaration in a folder social
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/folders/{id}/payslips":
    get:
      description: Returns payslips of the folder employee
    post:
      description: Add a payslip in a folder employee
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/folders/{id}/portfolio/{portfolioId}":
    delete:
      description: delete a secondary portfolio of a customer contract
  "/spaces/{spaceId}/folders/{id}/professional-vehicle":
    delete:
      description: delete a Professional Vehicle
    patch:
      description: Modify a Folder (except Name, Class, ModificationDate and ArchivalDate) and Professional Vehicle data
  "/spaces/{spaceId}/folders/{id}/provider":
    delete:
      description: delete a provider
    get:
      description: Returns folder with Id and provider data
    patch:
      description: Modify a Folder (except Name, Class, ModificationDate and ArchivalDate) and Provider data
  "/spaces/{spaceId}/folders/{id}/required-documents":
    get:
      description: list of the required documents for a person
  "/spaces/{spaceId}/folders/{id}/required-documents/{requireddocumentid}":
    patch:
      description: Modify the status of a requireddocument
    post:
      description: Add a required document to a line
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/folders/{id}/required-documents/{requireddocumentid}/documents/{documentId}":
    delete:
      description: delete a document from a required document
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/folders/{id}/sections":
    get:
      description: Returns sections of the folder
  "/spaces/{spaceId}/folders/{id}/social-contracts":
    get:
      description: Returns social contracts of the folder employee
    post:
      description: Add a social contract in a folder employee
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/folders/{id}/social-declarations":
    get:
      description: Returns social declarations
    post:
      description: Add a social declaration
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/folders/{id}/social-regimes":
    delete:
      description: delete a social regime
    get:
      description: Returns folder with Id and social regime data
    patch:
      description: Modify a Folder (except Name, Class, ModificationDate and ArchivalDate) and Social Regime data
  "/spaces/{spaceId}/folders/{id}/sum-invoices":
    get:
      description: Returns sum of invoices of the folder (customer, provider, accountingyear or root folders customers or providers)
  "/spaces/{spaceId}/folders/{id}/tax-contract":
    delete:
      description: Delete a Folder (except Name, Class, ModificationDate and ArchivalDate) and tax contract data
    patch:
      description: Modify a Folder (except Name, Class, ModificationDate and ArchivalDate) and Tax Contract data
  "/spaces/{spaceId}/folders/{id}/vat-declarations":
    get:
      description: Returns vat declarations
    post:
      description: Add a vat declaration
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/folders/{id}/{documentClass}":
    delete:
      description: delete a class document
    get:
      description: Returns document of documentClass (without specific data) of the folder
    post:
      description: Add a document in a folder
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/legal-entities/{id}/banks":
    get:
      description: Returns list of bank folders for a legal-entity
    post:
      description: Add a folder for a bank
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/legal-entities/{id}/banks/all":
    get:
      description: Returns folder of the banks even archived
  "/spaces/{spaceId}/legal-entities/{id}/contracts":
    get:
      description: Returns all contract folders of the legal entity
  "/spaces/{spaceId}/legal-entities/{id}/contractual-relationships":
    get:
      description: Returns folder of the others contract with legal entity
  "/spaces/{spaceId}/legal-entities/{id}/contractual-relationships/all":
    get:
      description: Returns folder of the others contract with legal entity (even archived)
  "/spaces/{spaceId}/legal-entities/{id}/customers":
    get:
      description: Returns folder of the customer
    post:
      description: Add a folder for a customer
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/legal-entities/{id}/customers/all":
    get:
      description: Returns folder of the customers (even archived)
  "/spaces/{spaceId}/legal-entities/{id}/insurances":
    get:
      description: Returns list of insurance folders for a legal-entity
    post:
      description: Add a folder for a insurance
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/legal-entities/{id}/insurances/all":
    get:
      description: Returns folder of the insurances even archived
  "/spaces/{spaceId}/legal-entities/{id}/loans":
    get:
      description: Returns folder of the loan
    post:
      description: Add a folder for a loan
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/legal-entities/{id}/loans/all":
    get:
      description: Returns folder of the loans even archived
  "/spaces/{spaceId}/legal-entities/{id}/providers":
    get:
      description: Returns list of providers folders for a legal-entity
    post:
      description: Add a folder for a provider
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/legal-entities/{id}/providers/all":
    get:
      description: Returns folder of the providers even archived
  "/spaces/{spaceId}/legal-entities/{id}/social-regimes":
    get:
      description: Returns list of social regimes folders for a legal-entity
    post:
      description: Add a folder for a social regime
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/legal-entities/{id}/social-regimes/all":
    get:
      description: Returns folder of the social regimes even archived
  "/spaces/{spaceId}/loans":
    get:
      description: Returns list of all loan folders of the space
  "/spaces/{spaceId}/loans/all":
    get:
      description: Returns list of all loan folders even archived of the space
  "/spaces/{spaceId}/persons/{id}/call-for-document":
    patch:
      description: modify the invitation of a person to collect documents
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
    post:
      description: invite a person to collect documents
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/persons/{id}/employees":
    get:
      description: Returns folder of the employee
    post:
      description: Add a folder for a employee
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/persons/{id}/employees/all":
    get:
      description: Returns folder of all employees (even archived)
  "/spaces/{spaceId}/persons/{id}/exchange":
    get:
      description: Returns folder exchange of the person
  "/spaces/{spaceId}/persons/{id}/follow-ups":
    get:
      description: Returns folder of the person
  "/spaces/{spaceId}/persons/{id}/guest-in-space":
    delete:
      description: delete the invitation of a person in a space
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
    patch:
      description: invite a person in a space
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
    post:
      description: invite a person in a space
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/persons/{id}/invitation":
    delete:
      description: delete the invitation of a person in a space
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
    get:
      description: Returns invitation of a person
    patch:
      description: modify an invitation
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
    post:
      description: create an invitation in a space for a person
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/persons/{id}/invitation/{invitationId}/send":
    post:
      description: send the invitation of a person in a space
      security:
        - gma_auth:
            - collaborator
            - owner
            - robot
  "/spaces/{spaceId}/persons/{memberId}/folders/{id}":
    get:
      description: Returns folderId with the access of the person
    patch:
      description: Modify an access
  "/spaces/{spaceId}/providers":
    get:
      description: Returns folder with Id and provider data
  "/spaces/{spaceId}/providers/all":
    get:
      description: Returns folder with Id and provider data (even archived)
  "/spaces/{spaceId}/search":
    get:
      description: Research text inside documents, folders or messages
  "/spaces/{spaceId}/social-regimes":
    get:
      description: Returns folder with Id and social regime data
  "/spaces/{spaceId}/social-regimes/all":
    get:
      description: Returns folder with Id and social regime data (even archived)
  "/spaces/{spaceId}/spaces-invoicings":
    get:
      description: Returns CSV Invoicings of the spaces for the account of the spaceId
components:
  securitySchemes:
    gma_auth:
      flows:
        authorizationCode:
          authorizationUrl: https://sandbox.gerermesaffaires.com/openid/v1/authorize
          refreshUrl: https://sandbox.gerermesaffaires.com/openid/v1/token
          scopes:
            box: "*Originally missing*"
            collaborator: blue access
            hub: "*Originally missing*"
            owner: green access
          tokenUrl: https://sandbox.gerermesaffaires.com/openid/v1/token
        clientCredentials:
          refreshUrl: https://sandbox.gerermesaffaires.com/openid/v1/token
          scopes:
            box: "*Originally missing*"
            hub: "*Originally missing*"
            robot: server access
          tokenUrl: https://sandbox.gerermesaffaires.com/openid/v1/token
      type: oauth2
