{
  "swagger": "2.0",
  "info": {
    "title": "Tag Manager API",
    "x-serviceName": "tagmanager",
    "description": "API for accessing Tag Manager accounts and containers.",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v1",
    "x-providerName": "googleapis.com",
    "x-origin": {
      "format": "google",
      "version": "v1",
      "url": "https://www.googleapis.com/discovery/v1/apis/tagmanager/v1/rest"
    }
  },
  "host": "www.googleapis.com",
  "basePath": "/tagmanager/v1",
  "schemes": [
    "https"
  ],
  "paths": {
    "/accounts/{accountId}": {
      "get": {
        "description": "Gets a GTM Account.",
        "operationId": "tagmanager.accounts.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers",
              "https://www.googleapis.com/auth/tagmanager.manage.accounts",
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "put": {
        "description": "Updates a GTM Account.",
        "operationId": "tagmanager.accounts.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.manage.accounts"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts": {
      "get": {
        "description": "Lists all GTM Accounts that a user has access to.",
        "operationId": "tagmanager.accounts.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers",
              "https://www.googleapis.com/auth/tagmanager.manage.accounts",
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/containers": {
      "post": {
        "description": "Creates a Container.",
        "operationId": "tagmanager.accounts.containers.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "get": {
        "description": "Lists all Containers that belongs to a GTM Account.",
        "operationId": "tagmanager.accounts.containers.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers",
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/containers/{containerId}": {
      "delete": {
        "description": "Deletes a Container.",
        "operationId": "tagmanager.accounts.containers.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.delete.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "get": {
        "description": "Gets a Container.",
        "operationId": "tagmanager.accounts.containers.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers",
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "put": {
        "description": "Updates a Container.",
        "operationId": "tagmanager.accounts.containers.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/containers/{containerId}/macros": {
      "post": {
        "description": "Creates a GTM Macro.",
        "operationId": "tagmanager.accounts.containers.macros.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "get": {
        "description": "Lists all GTM Macros of a Container.",
        "operationId": "tagmanager.accounts.containers.macros.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers",
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/containers/{containerId}/macros/{macroId}": {
      "delete": {
        "description": "Deletes a GTM Macro.",
        "operationId": "tagmanager.accounts.containers.macros.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "get": {
        "description": "Gets a GTM Macro.",
        "operationId": "tagmanager.accounts.containers.macros.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers",
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "put": {
        "description": "Updates a GTM Macro.",
        "operationId": "tagmanager.accounts.containers.macros.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/containers/{containerId}/rules": {
      "post": {
        "description": "Creates a GTM Rule.",
        "operationId": "tagmanager.accounts.containers.rules.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "get": {
        "description": "Lists all GTM Rules of a Container.",
        "operationId": "tagmanager.accounts.containers.rules.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers",
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/containers/{containerId}/rules/{ruleId}": {
      "delete": {
        "description": "Deletes a GTM Rule.",
        "operationId": "tagmanager.accounts.containers.rules.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "get": {
        "description": "Gets a GTM Rule.",
        "operationId": "tagmanager.accounts.containers.rules.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers",
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "put": {
        "description": "Updates a GTM Rule.",
        "operationId": "tagmanager.accounts.containers.rules.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/containers/{containerId}/tags": {
      "post": {
        "description": "Creates a GTM Tag.",
        "operationId": "tagmanager.accounts.containers.tags.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "get": {
        "description": "Lists all GTM Tags of a Container.",
        "operationId": "tagmanager.accounts.containers.tags.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers",
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/containers/{containerId}/tags/{tagId}": {
      "delete": {
        "description": "Deletes a GTM Tag.",
        "operationId": "tagmanager.accounts.containers.tags.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "get": {
        "description": "Gets a GTM Tag.",
        "operationId": "tagmanager.accounts.containers.tags.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers",
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "put": {
        "description": "Updates a GTM Tag.",
        "operationId": "tagmanager.accounts.containers.tags.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/containers/{containerId}/triggers": {
      "post": {
        "description": "Creates a GTM Trigger.",
        "operationId": "tagmanager.accounts.containers.triggers.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "get": {
        "description": "Lists all GTM Triggers of a Container.",
        "operationId": "tagmanager.accounts.containers.triggers.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers",
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/containers/{containerId}/triggers/{triggerId}": {
      "delete": {
        "description": "Deletes a GTM Trigger.",
        "operationId": "tagmanager.accounts.containers.triggers.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "get": {
        "description": "Gets a GTM Trigger.",
        "operationId": "tagmanager.accounts.containers.triggers.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers",
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "put": {
        "description": "Updates a GTM Trigger.",
        "operationId": "tagmanager.accounts.containers.triggers.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/containers/{containerId}/variables": {
      "post": {
        "description": "Creates a GTM Variable.",
        "operationId": "tagmanager.accounts.containers.variables.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "get": {
        "description": "Lists all GTM Variables of a Container.",
        "operationId": "tagmanager.accounts.containers.variables.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers",
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/containers/{containerId}/variables/{variableId}": {
      "delete": {
        "description": "Deletes a GTM Variable.",
        "operationId": "tagmanager.accounts.containers.variables.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "get": {
        "description": "Gets a GTM Variable.",
        "operationId": "tagmanager.accounts.containers.variables.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers",
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "put": {
        "description": "Updates a GTM Variable.",
        "operationId": "tagmanager.accounts.containers.variables.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/containers/{containerId}/versions": {
      "post": {
        "description": "Creates a Container Version.",
        "operationId": "tagmanager.accounts.containers.versions.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "get": {
        "description": "Lists all Container Versions of a GTM Container.",
        "operationId": "tagmanager.accounts.containers.versions.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers",
              "https://www.googleapis.com/auth/tagmanager.edit.containerversions",
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}": {
      "delete": {
        "description": "Deletes a Container Version.",
        "operationId": "tagmanager.accounts.containers.versions.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "get": {
        "description": "Gets a Container Version.",
        "operationId": "tagmanager.accounts.containers.versions.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers",
              "https://www.googleapis.com/auth/tagmanager.edit.containerversions",
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "put": {
        "description": "Updates a Container Version.",
        "operationId": "tagmanager.accounts.containers.versions.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/publish": {
      "post": {
        "description": "Publishes a Container Version.",
        "operationId": "tagmanager.accounts.containers.versions.publish",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.publish"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/restore": {
      "post": {
        "description": "Restores a Container Version. This will overwrite the container's current configuration (including its macros, rules and tags). The operation will not have any effect on the version that is being served (i.e. the published version).",
        "operationId": "tagmanager.accounts.containers.versions.restore",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/undelete": {
      "post": {
        "description": "Undeletes a Container Version.",
        "operationId": "tagmanager.accounts.containers.versions.undelete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/permissions": {
      "post": {
        "description": "Creates a user's Account & Container Permissions.",
        "operationId": "tagmanager.accounts.permissions.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.manage.users"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "get": {
        "description": "List all users that have access to the account along with Account and Container Permissions granted to each of them.",
        "operationId": "tagmanager.accounts.permissions.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.manage.users"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/accounts/{accountId}/permissions/{permissionId}": {
      "delete": {
        "description": "Removes a user from the account, revoking access to it and all of its containers.",
        "operationId": "tagmanager.accounts.permissions.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.manage.users"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "get": {
        "description": "Gets a user's Account & Container Permissions.",
        "operationId": "tagmanager.accounts.permissions.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.manage.users"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      },
      "put": {
        "description": "Updates a user's Account & Container Permissions.",
        "operationId": "tagmanager.accounts.permissions.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.manage.users"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/tagmanager.delete.containers": "Delete your Google Tag Manager containers",
        "https://www.googleapis.com/auth/tagmanager.edit.containers": "Manage your Google Tag Manager containers",
        "https://www.googleapis.com/auth/tagmanager.edit.containerversions": "Manage your Google Tag Manager container versions",
        "https://www.googleapis.com/auth/tagmanager.manage.accounts": "Manage your Google Tag Manager accounts",
        "https://www.googleapis.com/auth/tagmanager.manage.users": "Manage user permissions of your Google Tag Manager data",
        "https://www.googleapis.com/auth/tagmanager.publish": "Publish your Google Tag Manager containers",
        "https://www.googleapis.com/auth/tagmanager.readonly": "View your Google Tag Manager containers"
      }
    }
  }
}