package shared

type VideoParticipantSummaryEnumRoomStatusEnum string

const (
	VideoParticipantSummaryEnumRoomStatusEnumInProgress VideoParticipantSummaryEnumRoomStatusEnum = "in_progress"
	VideoParticipantSummaryEnumRoomStatusEnumCompleted  VideoParticipantSummaryEnumRoomStatusEnum = "completed"
)
