package shared

type GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembershipMembershipEnum string

const (
	GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembershipMembershipEnumMembershipUnspecified        GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembershipMembershipEnum = "MEMBERSHIP_UNSPECIFIED"
	GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembershipMembershipEnumMembershipIncluded           GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembershipMembershipEnum = "MEMBERSHIP_INCLUDED"
	GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembershipMembershipEnumMembershipNotIncluded        GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembershipMembershipEnum = "MEMBERSHIP_NOT_INCLUDED"
	GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembershipMembershipEnumMembershipUnknownInfoDenied  GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembershipMembershipEnum = "MEMBERSHIP_UNKNOWN_INFO_DENIED"
	GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembershipMembershipEnumMembershipUnknownUnsupported GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembershipMembershipEnum = "MEMBERSHIP_UNKNOWN_UNSUPPORTED"
)

type GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembershipRelevanceEnum string

const (
	GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembershipRelevanceEnumHeuristicRelevanceUnspecified GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembershipRelevanceEnum = "HEURISTIC_RELEVANCE_UNSPECIFIED"
	GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembershipRelevanceEnumNormal                        GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembershipRelevanceEnum = "NORMAL"
	GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembershipRelevanceEnumHigh                          GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembershipRelevanceEnum = "HIGH"
)

type GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembership struct {
	Membership *GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembershipMembershipEnum `json:"membership,omitempty"`
	Relevance  *GoogleCloudPolicytroubleshooterV1betaBindingExplanationAnnotatedMembershipRelevanceEnum  `json:"relevance,omitempty"`
}
