# coding: utf-8

"""
    Meraki Dashboard API

    The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 05 April, 2023 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

    The version of the OpenAPI document: 1.32.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.create_organization_adaptive_policy_group_request_policy_objects_inner import CreateOrganizationAdaptivePolicyGroupRequestPolicyObjectsInner
from typing import Optional, Set
from typing_extensions import Self

class CreateOrganizationAdaptivePolicyGroupRequest(BaseModel):
    """
    CreateOrganizationAdaptivePolicyGroupRequest
    """ # noqa: E501
    description: Optional[StrictStr] = Field(default=None, description="Description of the group (default: \"\")")
    name: StrictStr = Field(description="Name of the group")
    policy_objects: Optional[List[CreateOrganizationAdaptivePolicyGroupRequestPolicyObjectsInner]] = Field(default=None, description="The policy objects that belong to this group; traffic from addresses specified by these policy objects will be tagged with this group's SGT value if no other tagging scheme is being used (each requires one unique attribute) (default: [])", alias="policyObjects")
    sgt: StrictInt = Field(description="SGT value of the group")
    __properties: ClassVar[List[str]] = ["description", "name", "policyObjects", "sgt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateOrganizationAdaptivePolicyGroupRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in policy_objects (list)
        _items = []
        if self.policy_objects:
            for _item_policy_objects in self.policy_objects:
                if _item_policy_objects:
                    _items.append(_item_policy_objects.to_dict())
            _dict['policyObjects'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateOrganizationAdaptivePolicyGroupRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "description": obj.get("description"),
            "name": obj.get("name"),
            "policyObjects": [CreateOrganizationAdaptivePolicyGroupRequestPolicyObjectsInner.from_dict(_item) for _item in obj["policyObjects"]] if obj.get("policyObjects") is not None else None,
            "sgt": obj.get("sgt")
        })
        return _obj


