openapi: 3.0.0
servers:
  - url: https://searchconsole.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: The Search Console API provides access to both Search Console data (verified users only) and to public information on an URL basis (anyone)
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Google Search Console API
  version: v1
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png
  x-origin:
    - converter:
        url: https://github.com/mermade/oas-kit
        version: 7.0.4
      format: google
      url: https://searchconsole.googleapis.com/$discovery/rest?version=v1
      version: v1
  x-providerName: googleapis.com
  x-serviceName: searchconsole
tags:
  - name: searchanalytics
  - name: sitemaps
  - name: sites
  - name: urlInspection
  - name: urlTestingTools
paths:
  /v1/urlInspection/index:inspect:
    post:
      description: Index inspection.
      operationId: searchconsole.urlInspection.index.inspect
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters.readonly
      tags:
        - urlInspection
  /v1/urlTestingTools/mobileFriendlyTest:run:
    post:
      description: Runs Mobile-Friendly Test for a given URL.
      operationId: searchconsole.urlTestingTools.mobileFriendlyTest.run
      tags:
        - urlTestingTools
  /webmasters/v3/sites:
    get:
      description: " Lists the user's Search Console sites."
      operationId: webmasters.sites.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters.readonly
      tags:
        - sites
  "/webmasters/v3/sites/{siteUrl}":
    delete:
      description: " Removes a site from the set of the user's Search Console sites."
      operationId: webmasters.sites.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters
      tags:
        - sites
    get:
      description: " Retrieves information about specific site."
      operationId: webmasters.sites.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters.readonly
      tags:
        - sites
    put:
      description: " Adds a site to the set of the user's sites in Search Console."
      operationId: webmasters.sites.add
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters
      tags:
        - sites
  "/webmasters/v3/sites/{siteUrl}/searchAnalytics/query":
    post:
      description: Query your data with filters and parameters that you define. Returns zero or more rows grouped by the row keys that you define. You must define a date range of one or more days. When date is one of the group by values, any days without data are omitted from the result list. If you need to know which days have data, issue a broad date range query grouped by date for any metric, and see which day rows are returned.
      operationId: webmasters.searchanalytics.query
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters.readonly
      tags:
        - searchanalytics
  "/webmasters/v3/sites/{siteUrl}/sitemaps":
    get:
      description: " Lists the [sitemaps-entries](/webmaster-tools/v3/sitemaps) submitted for this site, or included in the sitemap index file (if `sitemapIndex` is specified in the request)."
      operationId: webmasters.sitemaps.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters.readonly
      tags:
        - sitemaps
  "/webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}":
    delete:
      description: Deletes a sitemap from the Sitemaps report. Does not stop Google from crawling this sitemap or the URLs that were previously crawled in the deleted sitemap.
      operationId: webmasters.sitemaps.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters
      tags:
        - sitemaps
    get:
      description: Retrieves information about a specific sitemap.
      operationId: webmasters.sitemaps.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters.readonly
      tags:
        - sitemaps
    put:
      description: Submits a sitemap for a site.
      operationId: webmasters.sitemaps.submit
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/webmasters
          Oauth2c:
            - https://www.googleapis.com/auth/webmasters
      tags:
        - sitemaps
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/webmasters: View and manage Search Console data for your verified sites
            https://www.googleapis.com/auth/webmasters.readonly: View Search Console data for your verified sites
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/webmasters: View and manage Search Console data for your verified sites
            https://www.googleapis.com/auth/webmasters.readonly: View Search Console data for your verified sites
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
