from dataclasses import dataclass, field
from typing import Enum

class ChatItemTypeEnum(str, Enum):
    TYPING = "TYPING"
    PARTICIPANT_JOINED = "PARTICIPANT_JOINED"
    PARTICIPANT_LEFT = "PARTICIPANT_LEFT"
    CHAT_ENDED = "CHAT_ENDED"
    TRANSFER_SUCCEEDED = "TRANSFER_SUCCEEDED"
    TRANSFER_FAILED = "TRANSFER_FAILED"
    MESSAGE = "MESSAGE"
    EVENT = "EVENT"
    ATTACHMENT = "ATTACHMENT"
    CONNECTION_ACK = "CONNECTION_ACK"

