# coding: utf-8

"""
    DataShareManagementClient

    Creates a Microsoft.DataShare management client.

    The version of the OpenAPI document: 2019-11-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class BlobContainerMappingProperties(BaseModel):
    """
    Azure storage Blob container data set mapping property bag.
    """ # noqa: E501
    container_name: StrictStr = Field(description="BLOB Container name.", alias="containerName")
    data_set_id: StrictStr = Field(description="The id of the source data set.", alias="dataSetId")
    data_set_mapping_status: Optional[StrictStr] = Field(default=None, description="Gets the status of the data set mapping.", alias="dataSetMappingStatus")
    provisioning_state: Optional[StrictStr] = Field(default=None, description="Provisioning state of the data set mapping.", alias="provisioningState")
    resource_group: StrictStr = Field(description="Resource group of storage account.", alias="resourceGroup")
    storage_account_name: StrictStr = Field(description="Storage account name of the source data set.", alias="storageAccountName")
    subscription_id: StrictStr = Field(description="Subscription id of storage account.", alias="subscriptionId")
    __properties: ClassVar[List[str]] = ["containerName", "dataSetId", "dataSetMappingStatus", "provisioningState", "resourceGroup", "storageAccountName", "subscriptionId"]

    @field_validator('data_set_mapping_status')
    def data_set_mapping_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Ok', 'Broken']):
            raise ValueError("must be one of enum values ('Ok', 'Broken')")
        return value

    @field_validator('provisioning_state')
    def provisioning_state_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Succeeded', 'Creating', 'Deleting', 'Moving', 'Failed']):
            raise ValueError("must be one of enum values ('Succeeded', 'Creating', 'Deleting', 'Moving', 'Failed')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BlobContainerMappingProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "data_set_mapping_status",
            "provisioning_state",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BlobContainerMappingProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "containerName": obj.get("containerName"),
            "dataSetId": obj.get("dataSetId"),
            "dataSetMappingStatus": obj.get("dataSetMappingStatus"),
            "provisioningState": obj.get("provisioningState"),
            "resourceGroup": obj.get("resourceGroup"),
            "storageAccountName": obj.get("storageAccountName"),
            "subscriptionId": obj.get("subscriptionId")
        })
        return _obj


