openapi: 3.0.1
servers:
  - url: https://api.spotify.com/v1
info:
  contact:
    name: sonallux
    url: https://github.com/sonallux/spotify-web-api
  title: Spotify Web API
  version: 2021.6.30
  x-apisguru-categories:
    - media
  x-logo:
    url: https://logo-core.clearbit.com/spotify.com
  x-origin:
    - format: openapi
      url: https://raw.githubusercontent.com/sonallux/spotify-web-api/master/spotify-web-api-generator-open-api/spotify-web-api-openapi.yml
      version: "3.0"
  x-providerName: spotify.com
  x-unofficialSpec: true
tags:
  - description: Albums API
    name: category-albums
  - description: Artists API
    name: category-artists
  - description: Browse API
    name: category-browse
  - description: Episodes API
    name: category-episodes
  - description: Follow API
    name: category-follow
  - description: Library API
    name: category-library
  - description: Markets API
    name: category-markets
  - description: Personalization API
    name: category-personalization
  - description: Player API
    name: category-player
  - description: Playlists API
    name: category-playlists
  - description: Search API
    name: category-search
  - description: Shows API
    name: category-shows
  - description: Tracks API
    name: category-tracks
  - description: Users Profile API
    name: category-users-profile
paths:
  /albums:
    get:
      description: Get Spotify catalog information for multiple albums identified by their Spotify IDs.
      operationId: endpoint-get-multiple-albums
      security:
        - spotify_auth: []
      summary: Get Multiple Albums
      tags:
        - category-albums
  "/albums/{id}":
    get:
      description: Get Spotify catalog information for a single album.
      operationId: endpoint-get-an-album
      security:
        - spotify_auth: []
      summary: Get an Album
      tags:
        - category-albums
  "/albums/{id}/tracks":
    get:
      description: |-
        Get Spotify catalog information about an album's tracks.
        Optional parameters can be used to limit the number of tracks returned.
      operationId: endpoint-get-an-albums-tracks
      security:
        - spotify_auth: []
      summary: Get an Album's Tracks
      tags:
        - category-albums
  /artists:
    get:
      description: Get Spotify catalog information for several artists based on their Spotify IDs.
      operationId: endpoint-get-multiple-artists
      security:
        - spotify_auth: []
      summary: Get Multiple Artists
      tags:
        - category-artists
  "/artists/{id}":
    get:
      description: Get Spotify catalog information for a single artist identified by their unique Spotify ID.
      operationId: endpoint-get-an-artist
      security:
        - spotify_auth: []
      summary: Get an Artist
      tags:
        - category-artists
  "/artists/{id}/albums":
    get:
      description: Get Spotify catalog information about an artist's albums.
      operationId: endpoint-get-an-artists-albums
      security:
        - spotify_auth: []
      summary: Get an Artist's Albums
      tags:
        - category-artists
  "/artists/{id}/related-artists":
    get:
      description: Get Spotify catalog information about artists similar to a given artist. Similarity is based on analysis of the Spotify community's [listening history](http://news.spotify.com/se/2010/02/03/related-artists/).
      operationId: endpoint-get-an-artists-related-artists
      security:
        - spotify_auth: []
      summary: Get an Artist's Related Artists
      tags:
        - category-artists
  "/artists/{id}/top-tracks":
    get:
      description: Get Spotify catalog information about an artist's top tracks by country.
      operationId: endpoint-get-an-artists-top-tracks
      security:
        - spotify_auth: []
      summary: Get an Artist's Top Tracks
      tags:
        - category-artists
  "/audio-analysis/{id}":
    get:
      description: |-
        Get a detailed audio analysis for a single track identified by its unique
        Spotify ID.
      operationId: endpoint-get-audio-analysis
      security:
        - spotify_auth: []
      summary: Get Audio Analysis for a Track
      tags:
        - category-tracks
  /audio-features:
    get:
      description: Get audio features for multiple tracks based on their Spotify IDs.
      operationId: endpoint-get-several-audio-features
      security:
        - spotify_auth: []
      summary: Get Audio Features for Several Tracks
      tags:
        - category-tracks
  "/audio-features/{id}":
    get:
      description: |-
        Get audio feature information for a single track identified by its unique
        Spotify ID.
      operationId: endpoint-get-audio-features
      security:
        - spotify_auth: []
      summary: Get Audio Features for a Track
      tags:
        - category-tracks
  /browse/categories:
    get:
      description: Get a list of categories used to tag items in Spotify (on, for example, the Spotify player's "Browse" tab).
      operationId: endpoint-get-categories
      security:
        - spotify_auth: []
      summary: Get All Categories
      tags:
        - category-browse
  "/browse/categories/{category_id}":
    get:
      description: Get a single category used to tag items in Spotify (on, for example, the Spotify player's "Browse" tab).
      operationId: endpoint-get-a-category
      security:
        - spotify_auth: []
      summary: Get a Category
      tags:
        - category-browse
  "/browse/categories/{category_id}/playlists":
    get:
      description: Get a list of Spotify playlists tagged with a particular category.
      operationId: endpoint-get-a-categories-playlists
      security:
        - spotify_auth: []
      summary: Get a Category's Playlists
      tags:
        - category-browse
  /browse/featured-playlists:
    get:
      description: Get a list of Spotify featured playlists (shown, for example, on a Spotify player's 'Browse' tab).
      operationId: endpoint-get-featured-playlists
      security:
        - spotify_auth: []
      summary: Get All Featured Playlists
      tags:
        - category-browse
  /browse/new-releases:
    get:
      description: Get a list of new album releases featured in Spotify (shown, for example, on a Spotify player's "Browse" tab).
      operationId: endpoint-get-new-releases
      security:
        - spotify_auth: []
      summary: Get All New Releases
      tags:
        - category-browse
  /episodes:
    get:
      description: Get Spotify catalog information for several episodes based on their Spotify IDs.
      operationId: endpoint-get-multiple-episodes
      security:
        - spotify_auth: []
      summary: Get Multiple Episodes
      tags:
        - category-episodes
  "/episodes/{id}":
    get:
      description: |-
        Get Spotify catalog information for a single episode identified by its
        unique Spotify ID.
      operationId: endpoint-get-an-episode
      security:
        - spotify_auth: []
      summary: Get an Episode
      tags:
        - category-episodes
  /markets:
    get:
      description: Get the list of markets where Spotify is available.
      operationId: endpoint-get-available-markets
      security:
        - spotify_auth: []
      summary: Get Available Markets
      tags:
        - category-markets
  /me:
    get:
      description: |-
        Get detailed profile information about the current user (including the
        current user's username).
      operationId: endpoint-get-current-users-profile
      security:
        - spotify_auth:
            - user-read-email
            - user-read-private
      summary: Get Current User's Profile
      tags:
        - category-users-profile
  /me/albums:
    delete:
      description: Remove one or more albums from the current user's 'Your Music' library.
      operationId: endpoint-remove-albums-user
      security:
        - spotify_auth:
            - user-library-modify
      summary: Remove Albums for Current User
      tags:
        - category-library
    get:
      description: Get a list of the albums saved in the current Spotify user's 'Your Music' library.
      operationId: endpoint-get-users-saved-albums
      security:
        - spotify_auth:
            - user-library-read
      summary: Get User's Saved Albums
      tags:
        - category-library
    put:
      description: Save one or more albums to the current user's 'Your Music' library.
      operationId: endpoint-save-albums-user
      security:
        - spotify_auth:
            - user-library-modify
      summary: Save Albums for Current User
      tags:
        - category-library
  /me/albums/contains:
    get:
      description: Check if one or more albums is already saved in the current Spotify user's 'Your Music' library.
      operationId: endpoint-check-users-saved-albums
      security:
        - spotify_auth:
            - user-library-read
      summary: Check User's Saved Albums
      tags:
        - category-library
  /me/episodes:
    delete:
      description: |-
        Remove one or more episodes from the current user's library.  

        This API endpoint is in **beta** and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
      operationId: endpoint-remove-episodes-user
      security:
        - spotify_auth:
            - user-library-modify
      summary: Remove User's Saved Episodes
      tags:
        - category-library
    get:
      description: |-
        Get a list of the episodes saved in the current Spotify user's library.  

        This API endpoint is in **beta** and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
      operationId: endpoint-get-users-saved-episodes
      security:
        - spotify_auth:
            - user-library-read
      summary: Get User's Saved Episodes
      tags:
        - category-library
    put:
      description: |-
        Save one or more episodes to the current user's library.  

        This API endpoint is in **beta** and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer).
      operationId: endpoint-save-episodes-user
      security:
        - spotify_auth:
            - user-library-modify
      summary: Save Episodes for User
      tags:
        - category-library
  /me/episodes/contains:
    get:
      description: |-
        Check if one or more episodes is already saved in the current Spotify user's 'Your Episodes' library.  

        This API endpoint is in **beta** and could change without warning. Please share any feedback that you have, or issues that you discover, in our [developer community forum](https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer)..
      operationId: endpoint-check-users-saved-episodes
      security:
        - spotify_auth:
            - user-library-read
      summary: Check User's Saved Episodes
      tags:
        - category-library
  /me/following:
    delete:
      description: Remove the current user as a follower of one or more artists or other Spotify users.
      operationId: endpoint-unfollow-artists-users
      security:
        - spotify_auth:
            - user-follow-modify
      summary: Unfollow Artists or Users
      tags:
        - category-follow
    get:
      description: Get the current user's followed artists.
      operationId: endpoint-get-followed
      security:
        - spotify_auth:
            - user-follow-modify
      summary: Get User's Followed Artists
      tags:
        - category-follow
    put:
      description: Add the current user as a follower of one or more artists or other Spotify users.
      operationId: endpoint-follow-artists-users
      security:
        - spotify_auth:
            - user-follow-modify
      summary: Follow Artists or Users
      tags:
        - category-follow
  /me/following/contains:
    get:
      description: Check to see if the current user is following one or more artists or other Spotify users.
      operationId: endpoint-check-current-user-follows
      security:
        - spotify_auth:
            - user-follow-read
      summary: Get Following State for Artists/Users
      tags:
        - category-follow
  /me/player:
    get:
      description: Get information about the user's current playback state, including track or episode, progress, and active device.
      operationId: endpoint-get-information-about-the-users-current-playback
      security:
        - spotify_auth:
            - user-read-playback-state
      summary: Get Information About The User's Current Playback
      tags:
        - category-player
    put:
      description: Transfer playback to a new device and determine if it should start playing.
      operationId: endpoint-transfer-a-users-playback
      security:
        - spotify_auth:
            - user-modify-playback-state
      summary: Transfer a User's Playback
      tags:
        - category-player
  /me/player/currently-playing:
    get:
      description: Get the object currently being played on the user's Spotify account.
      operationId: endpoint-get-the-users-currently-playing-track
      security:
        - spotify_auth:
            - user-read-currently-playing
            - user-read-playback-state
      summary: Get the User's Currently Playing Track
      tags:
        - category-player
  /me/player/devices:
    get:
      description: Get information about a user's available devices.
      operationId: endpoint-get-a-users-available-devices
      security:
        - spotify_auth:
            - user-read-playback-state
      summary: Get a User's Available Devices
      tags:
        - category-player
  /me/player/next:
    post:
      description: Skips to next track in the user's queue.
      operationId: endpoint-skip-users-playback-to-next-track
      security:
        - spotify_auth:
            - user-modify-playback-state
      summary: Skip User’s Playback To Next Track
      tags:
        - category-player
  /me/player/pause:
    put:
      description: Pause playback on the user's account.
      operationId: endpoint-pause-a-users-playback
      security:
        - spotify_auth: []
      summary: Pause a User's Playback
      tags:
        - category-player
  /me/player/play:
    put:
      description: Start a new context or resume current playback on the user's active device.
      operationId: endpoint-start-a-users-playback
      security:
        - spotify_auth:
            - user-modify-playback-state
      summary: Start/Resume a User's Playback
      tags:
        - category-player
  /me/player/previous:
    post:
      description: Skips to previous track in the user's queue.
      operationId: endpoint-skip-users-playback-to-previous-track
      security:
        - spotify_auth:
            - user-modify-playback-state
      summary: Skip User’s Playback To Previous Track
      tags:
        - category-player
  /me/player/queue:
    post:
      description: Add an item to the end of the user's current playback queue.
      operationId: endpoint-add-to-queue
      security:
        - spotify_auth:
            - user-modify-playback-state
      summary: Add an item to queue
      tags:
        - category-player
  /me/player/recently-played:
    get:
      description: |-
        Get tracks from the current user's recently played tracks.
        *Note: Currently doesn't support podcast episodes.*
      operationId: endpoint-get-recently-played
      security:
        - spotify_auth: []
      summary: Get Current User's Recently Played Tracks
      tags:
        - category-player
  /me/player/repeat:
    put:
      description: |-
        Set the repeat mode for the user's playback. Options are repeat-track,
        repeat-context, and off.
      operationId: endpoint-set-repeat-mode-on-users-playback
      security:
        - spotify_auth:
            - user-modify-playback-state
      summary: Set Repeat Mode On User’s Playback
      tags:
        - category-player
  /me/player/seek:
    put:
      description: Seeks to the given position in the user's currently playing track.
      operationId: endpoint-seek-to-position-in-currently-playing-track
      security:
        - spotify_auth:
            - user-modify-playback-state
      summary: Seek To Position In Currently Playing Track
      tags:
        - category-player
  /me/player/shuffle:
    put:
      description: Toggle shuffle on or off for user's playback.
      operationId: endpoint-toggle-shuffle-for-users-playback
      security:
        - spotify_auth:
            - user-modify-playback-state
      summary: Toggle Shuffle For User’s Playback
      tags:
        - category-player
  /me/player/volume:
    put:
      description: Set the volume for the user's current playback device.
      operationId: endpoint-set-volume-for-users-playback
      security:
        - spotify_auth:
            - user-modify-playback-state
      summary: Set Volume For User's Playback
      tags:
        - category-player
  /me/playlists:
    get:
      description: |-
        Get a list of the playlists owned or followed by the current Spotify
        user.
      operationId: endpoint-get-a-list-of-current-users-playlists
      security:
        - spotify_auth:
            - playlist-read-private
            - playlist-read-collaborative
      summary: Get a List of Current User's Playlists
      tags:
        - category-playlists
  /me/shows:
    delete:
      description: Delete one or more shows from current Spotify user's library.
      operationId: endpoint-remove-shows-user
      security:
        - spotify_auth:
            - user-library-modify
      summary: Remove User's Saved Shows
      tags:
        - category-library
    get:
      description: Get a list of shows saved in the current Spotify user's library. Optional parameters can be used to limit the number of shows returned.
      operationId: endpoint-get-users-saved-shows
      security:
        - spotify_auth:
            - user-library-read
      summary: Get User's Saved Shows
      tags:
        - category-library
    put:
      description: Save one or more shows to current Spotify user's library.
      operationId: endpoint-save-shows-user
      security:
        - spotify_auth:
            - user-library-modify
      summary: Save Shows for Current User
      tags:
        - category-library
  /me/shows/contains:
    get:
      description: Check if one or more shows is already saved in the current Spotify user's library.
      operationId: endpoint-check-users-saved-shows
      security:
        - spotify_auth:
            - user-library-read
      summary: Check User's Saved Shows
      tags:
        - category-library
  "/me/top/{type}":
    get:
      description: Get the current user's top artists or tracks based on calculated affinity.
      operationId: endpoint-get-users-top-artists-and-tracks
      security:
        - spotify_auth:
            - user-top-read
      summary: Get a User's Top Artists and Tracks
      tags:
        - category-personalization
  /me/tracks:
    delete:
      description: Remove one or more tracks from the current user's 'Your Music' library.
      operationId: endpoint-remove-tracks-user
      security:
        - spotify_auth:
            - user-library-modify
      summary: Remove User's Saved Tracks
      tags:
        - category-library
    get:
      description: Get a list of the songs saved in the current Spotify user's 'Your Music' library.
      operationId: endpoint-get-users-saved-tracks
      security:
        - spotify_auth:
            - user-library-read
      summary: Get User's Saved Tracks
      tags:
        - category-library
    put:
      description: Save one or more tracks to the current user's 'Your Music' library.
      operationId: endpoint-save-tracks-user
      security:
        - spotify_auth:
            - user-library-modify
      summary: Save Tracks for User
      tags:
        - category-library
  /me/tracks/contains:
    get:
      description: Check if one or more tracks is already saved in the current Spotify user's 'Your Music' library.
      operationId: endpoint-check-users-saved-tracks
      security:
        - spotify_auth:
            - user-library-read
      summary: Check User's Saved Tracks
      tags:
        - category-library
  "/playlists/{playlist_id}":
    get:
      description: Get a playlist owned by a Spotify user.
      operationId: endpoint-get-playlist
      security:
        - spotify_auth: []
      summary: Get a Playlist
      tags:
        - category-playlists
    put:
      description: |-
        Change a playlist's name and public/private state. (The user must, of
        course, own the playlist.)
      operationId: endpoint-change-playlist-details
      security:
        - spotify_auth:
            - playlist-modify-public
            - playlist-modify-private
      summary: Change a Playlist's Details
      tags:
        - category-playlists
  "/playlists/{playlist_id}/followers":
    delete:
      description: Remove the current user as a follower of a playlist.
      operationId: endpoint-unfollow-playlist
      security:
        - spotify_auth:
            - playlist-modify-public
            - playlist-modify-private
      summary: Unfollow Playlist
      tags:
        - category-follow
    put:
      description: Add the current user as a follower of a playlist.
      operationId: endpoint-follow-playlist
      security:
        - spotify_auth:
            - playlist-modify-public
            - playlist-modify-private
      summary: Follow a Playlist
      tags:
        - category-follow
  "/playlists/{playlist_id}/followers/contains":
    get:
      description: Check to see if one or more Spotify users are following a specified playlist.
      operationId: endpoint-check-if-user-follows-playlist
      security:
        - spotify_auth:
            - playlist-read-private
      summary: Check if Users Follow a Playlist
      tags:
        - category-follow
  "/playlists/{playlist_id}/images":
    get:
      description: Get the current image associated with a specific playlist.
      operationId: endpoint-get-playlist-cover
      security:
        - spotify_auth: []
      summary: Get a Playlist Cover Image
      tags:
        - category-playlists
    put:
      description: Replace the image used to represent a specific playlist.
      operationId: endpoint-upload-custom-playlist-cover
      security:
        - spotify_auth:
            - ugc-image-upload
            - playlist-modify-public
            - playlist-modify-private
      summary: Upload a Custom Playlist Cover Image
      tags:
        - category-playlists
  "/playlists/{playlist_id}/tracks":
    delete:
      description: Remove one or more items from a user's playlist.
      operationId: endpoint-remove-tracks-playlist
      security:
        - spotify_auth:
            - playlist-modify-public
            - playlist-modify-private
      summary: Remove Items from a Playlist
      tags:
        - category-playlists
    get:
      description: Get full details of the items of a playlist owned by a Spotify user.
      operationId: endpoint-get-playlists-tracks
      security:
        - spotify_auth: []
      summary: Get a Playlist's Items
      tags:
        - category-playlists
    post:
      description: Add one or more items to a user's playlist.
      operationId: endpoint-add-tracks-to-playlist
      security:
        - spotify_auth:
            - playlist-modify-public
            - playlist-modify-private
      summary: Add Items to a Playlist
      tags:
        - category-playlists
    put:
      description: |-
        Either reorder or replace items in a playlist depending on the request's parameters.
        To reorder items, include `range_start`, `insert_before`, `range_length` and `snapshot_id` in the request's body.
        To replace items, include `uris` as either a query parameter or in the request's body.
        Replacing items in a playlist will overwrite its existing items. This operation can be used for replacing or clearing items in a playlist.


        **Note**: Replace and reorder are mutually exclusive operations which share the same endpoint, but have different parameters.
        These operations can't be applied together in a single request.
      operationId: endpoint-reorder-or-replace-playlists-tracks
      security:
        - spotify_auth:
            - playlist-modify-public
            - playlist-modify-private
      summary: Reorder or Replace a Playlist's Items
      tags:
        - category-playlists
  /recommendations:
    get:
      description: Recommendations are generated based on the available information for a given seed entity and matched against similar artists and tracks. If there is sufficient information about the provided seeds, a list of tracks will be returned together with pool size details.
      operationId: endpoint-get-recommendations
      security:
        - spotify_auth: []
      summary: Get Recommendations
      tags:
        - category-browse
  /recommendations/available-genre-seeds:
    get:
      description: Retrieve a list of available genres seed parameter values for [recommendations](https://developer.spotify.com/documentation/web-api/reference/#endpoint-get-recommendations).
      operationId: endpoint-get-recommendation-genres
      security:
        - spotify_auth: []
      summary: Get Recommendation Genres
      tags:
        - category-browse
  /search:
    get:
      description: |-
        Get Spotify Catalog information about albums, artists, playlists, tracks, shows or episodes
        that match a keyword string.
      operationId: endpoint-search
      security:
        - spotify_auth: []
      summary: Search for an Item
      tags:
        - category-search
  /shows:
    get:
      description: Get Spotify catalog information for several shows based on their Spotify IDs.
      operationId: endpoint-get-multiple-shows
      security:
        - spotify_auth: []
      summary: Get Multiple Shows
      tags:
        - category-shows
  "/shows/{id}":
    get:
      description: |-
        Get Spotify catalog information for a single show identified by its
        unique Spotify ID.
      operationId: endpoint-get-a-show
      security:
        - spotify_auth: []
      summary: Get a Show
      tags:
        - category-shows
  "/shows/{id}/episodes":
    get:
      description: Get Spotify catalog information about an show's episodes. Optional parameters can be used to limit the number of episodes returned.
      operationId: endpoint-get-a-shows-episodes
      security:
        - spotify_auth: []
      summary: Get a Show's Episodes
      tags:
        - category-shows
  /tracks:
    get:
      description: Get Spotify catalog information for multiple tracks based on their Spotify IDs.
      operationId: endpoint-get-several-tracks
      security:
        - spotify_auth: []
      summary: Get Several Tracks
      tags:
        - category-tracks
  "/tracks/{id}":
    get:
      description: |-
        Get Spotify catalog information for a single track identified by its
        unique Spotify ID.
      operationId: endpoint-get-track
      security:
        - spotify_auth: []
      summary: Get a Track
      tags:
        - category-tracks
  "/users/{user_id}":
    get:
      description: Get public profile information about a Spotify user.
      operationId: endpoint-get-users-profile
      security:
        - spotify_auth: []
      summary: Get a User's Profile
      tags:
        - category-users-profile
  "/users/{user_id}/playlists":
    get:
      description: Get a list of the playlists owned or followed by a Spotify user.
      operationId: endpoint-get-list-users-playlists
      security:
        - spotify_auth:
            - playlist-read-private
            - playlist-read-collaborative
      summary: Get a List of a User's Playlists
      tags:
        - category-playlists
    post:
      description: |-
        Create a playlist for a Spotify user. (The playlist will be empty until
        you [add tracks](https://developer.spotify.com/documentation/web-api/reference/#endpoint-add-tracks-to-playlist).)
      operationId: endpoint-create-playlist
      security:
        - spotify_auth:
            - playlist-modify-public
            - playlist-modify-private
      summary: Create a Playlist
      tags:
        - category-playlists
components:
  securitySchemes:
    spotify_auth:
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.spotify.com/authorize
          scopes:
            app-remote-control: Remote control playback of Spotify. This scope is currently available to Spotify iOS and Android SDKs.
            playlist-modify-private: Write access to a user's private playlists.
            playlist-modify-public: Write access to a user's public playlists.
            playlist-read-collaborative: Include collaborative playlists when requesting a user's playlists.
            playlist-read-private: Read access to user's private playlists.
            streaming: Control playback of a Spotify track. This scope is currently available to the Web Playback SDK. The user must have a Spotify Premium account.
            ugc-image-upload: Write access to user-provided images.
            user-follow-modify: Write/delete access to the list of artists and other users that the user follows.
            user-follow-read: Read access to the list of artists and other users that the user follows.
            user-library-modify: Write/delete access to a user's "Your Music" library.
            user-library-read: Read access to a user's library.
            user-modify-playback-state: Write access to a user’s playback state
            user-read-currently-playing: Read access to a user’s currently playing content.
            user-read-email: Read access to user’s email address.
            user-read-playback-position: Read access to a user’s playback position in a content.
            user-read-playback-state: Read access to a user’s player state.
            user-read-private: Read access to user’s subscription details (type of user account).
            user-read-recently-played: Read access to a user’s recently played tracks.
            user-top-read: Read access to a user's top artists and tracks.
          tokenUrl: https://accounts.spotify.com/api/token
      type: oauth2
