openapi: 3.0.0
servers:
  - url: https://analyticsadmin.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: ""
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Google Analytics Admin API
  version: v1alpha
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://upload.wikimedia.org/wikipedia/commons/e/e1/YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
    - format: google
      url: https://analyticsadmin.googleapis.com/$discovery/rest?version=v1alpha
      version: v1
  x-providerName: googleapis.com
  x-serviceName: analyticsadmin
  x-preferred: null
tags:
  - name: accounts
  - name: accountSummaries
  - name: properties
paths:
  /v1alpha/accountSummaries:
    get:
      description: Returns summaries of all accounts accessible by the caller.
      operationId: analyticsadmin.accountSummaries.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      tags:
        - accountSummaries
  /v1alpha/accounts:
    get:
      description: 'Returns all accounts accessible by the caller. Note that these accounts might not currently have GA4 properties. Soft-deleted (ie: "trashed") accounts are excluded by default. Returns an empty list if no relevant accounts are found.'
      operationId: analyticsadmin.accounts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      tags:
        - accounts
  /v1alpha/accounts:provisionAccountTicket:
    post:
      description: Requests a ticket for creating an account.
      operationId: analyticsadmin.accounts.provisionAccountTicket
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      tags:
        - accounts
  /v1alpha/properties:
    get:
      description: 'Returns child Properties under the specified parent Account. Only "GA4" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: "trashed") properties are excluded by default. Returns an empty list if no relevant properties are found.'
      operationId: analyticsadmin.properties.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      tags:
        - properties
    post:
      description: Creates an "GA4" property with the specified location and attributes.
      operationId: analyticsadmin.properties.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      tags:
        - properties
  "/v1alpha/{name}":
    delete:
      description: Deletes a web stream on a property.
      operationId: analyticsadmin.properties.webDataStreams.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      tags:
        - properties
    get:
      description: Returns the Site Tag for the specified web stream. Site Tags are immutable singletons.
      operationId: analyticsadmin.properties.webDataStreams.getGlobalSiteTag
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      tags:
        - properties
    patch:
      description: Updates the singleton enhanced measurement settings for this web stream. Note that the stream must enable enhanced measurement for these settings to take effect.
      operationId: analyticsadmin.properties.webDataStreams.updateEnhancedMeasurementSettings
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      tags:
        - properties
  "/v1alpha/{parent}/androidAppDataStreams":
    get:
      description: Returns child android app streams under the specified parent property. Android app streams will be excluded if the caller does not have access. Returns an empty list if no relevant android app streams are found.
      operationId: analyticsadmin.properties.androidAppDataStreams.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      tags:
        - properties
    post:
      description: Creates an Android app stream with the specified location and attributes. Note that an Android app stream must be linked to a Firebase app to receive traffic. To create a working app stream, make sure your property is linked to a Firebase project. Then, use the Firebase API to create a Firebase app, which will also create an appropriate data stream in Analytics (may take up to 24 hours).
      operationId: analyticsadmin.properties.androidAppDataStreams.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      tags:
        - properties
  "/v1alpha/{parent}/firebaseLinks":
    get:
      description: Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.
      operationId: analyticsadmin.properties.firebaseLinks.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      tags:
        - properties
    post:
      description: Creates a FirebaseLink. Properties can have at most one FirebaseLink.
      operationId: analyticsadmin.properties.firebaseLinks.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      tags:
        - properties
  "/v1alpha/{parent}/googleAdsLinks":
    get:
      description: Lists GoogleAdsLinks on a property.
      operationId: analyticsadmin.properties.googleAdsLinks.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      tags:
        - properties
    post:
      description: Creates a GoogleAdsLink.
      operationId: analyticsadmin.properties.googleAdsLinks.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      tags:
        - properties
  "/v1alpha/{parent}/iosAppDataStreams":
    get:
      description: Returns child iOS app data streams under the specified parent property. iOS app data streams will be excluded if the caller does not have access. Returns an empty list if no relevant iOS app data streams are found.
      operationId: analyticsadmin.properties.iosAppDataStreams.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      tags:
        - properties
    post:
      description: Creates an iOS app stream with the specified location and attributes. Note that an iOS app stream must be linked to a Firebase app to receive traffic. To create a working app stream, make sure your property is linked to a Firebase project. Then, use the Firebase API to create a Firebase app, which will also create an appropriate data stream in Analytics (may take up to 24 hours).
      operationId: analyticsadmin.properties.iosAppDataStreams.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      tags:
        - properties
  "/v1alpha/{parent}/userLinks":
    get:
      description: Lists all user links on an account or property.
      operationId: analyticsadmin.properties.userLinks.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
      tags:
        - properties
    post:
      description: Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.
      operationId: analyticsadmin.properties.userLinks.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      tags:
        - properties
  "/v1alpha/{parent}/userLinks:audit":
    post:
      description: Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.
      operationId: analyticsadmin.properties.userLinks.audit
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
      tags:
        - properties
  "/v1alpha/{parent}/userLinks:batchCreate":
    post:
      description: Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.
      operationId: analyticsadmin.properties.userLinks.batchCreate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      tags:
        - properties
  "/v1alpha/{parent}/userLinks:batchDelete":
    post:
      description: Deletes information about multiple users' links to an account or property.
      operationId: analyticsadmin.properties.userLinks.batchDelete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      tags:
        - properties
  "/v1alpha/{parent}/userLinks:batchGet":
    get:
      description: Gets information about multiple users' links to an account or property.
      operationId: analyticsadmin.properties.userLinks.batchGet
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users.readonly
      tags:
        - properties
  "/v1alpha/{parent}/userLinks:batchUpdate":
    post:
      description: Updates information about multiple users' links to an account or property.
      operationId: analyticsadmin.properties.userLinks.batchUpdate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.manage.users
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.manage.users
      tags:
        - properties
  "/v1alpha/{parent}/webDataStreams":
    get:
      description: Returns child web data streams under the specified parent property. Web data streams will be excluded if the caller does not have access. Returns an empty list if no relevant web data streams are found.
      operationId: analyticsadmin.properties.webDataStreams.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.readonly
      tags:
        - properties
    post:
      description: Creates a web stream with the specified location and attributes.
      operationId: analyticsadmin.properties.webDataStreams.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/analytics.edit
          Oauth2c:
            - https://www.googleapis.com/auth/analytics.edit
      tags:
        - properties
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/analytics.edit: Edit Google Analytics management entities
            https://www.googleapis.com/auth/analytics.manage.users: Manage Google Analytics Account users by email address
            https://www.googleapis.com/auth/analytics.manage.users.readonly: View Google Analytics user permissions
            https://www.googleapis.com/auth/analytics.readonly: See and download your Google Analytics data
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/analytics.edit: Edit Google Analytics management entities
            https://www.googleapis.com/auth/analytics.manage.users: Manage Google Analytics Account users by email address
            https://www.googleapis.com/auth/analytics.manage.users.readonly: View Google Analytics user permissions
            https://www.googleapis.com/auth/analytics.readonly: See and download your Google Analytics data
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
