# coding: utf-8

"""
    Ad Exchange Buyer API II

    Accesses the latest features for managing Authorized Buyers accounts, Real-Time Bidding configurations and auction metrics, and Marketplace programmatic deals.

    The version of the OpenAPI document: v2beta1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.buyers_api import BuyersApi


class TestBuyersApi(unittest.TestCase):
    """BuyersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BuyersApi()

    def tearDown(self) -> None:
        pass

    def test_adexchangebuyer2_buyers_filter_sets_bid_metrics_list(self) -> None:
        """Test case for adexchangebuyer2_buyers_filter_sets_bid_metrics_list

        """
        pass

    def test_adexchangebuyer2_buyers_filter_sets_bid_response_errors_list(self) -> None:
        """Test case for adexchangebuyer2_buyers_filter_sets_bid_response_errors_list

        """
        pass

    def test_adexchangebuyer2_buyers_filter_sets_bid_responses_without_bids_list(self) -> None:
        """Test case for adexchangebuyer2_buyers_filter_sets_bid_responses_without_bids_list

        """
        pass

    def test_adexchangebuyer2_buyers_filter_sets_create(self) -> None:
        """Test case for adexchangebuyer2_buyers_filter_sets_create

        """
        pass

    def test_adexchangebuyer2_buyers_filter_sets_delete(self) -> None:
        """Test case for adexchangebuyer2_buyers_filter_sets_delete

        """
        pass

    def test_adexchangebuyer2_buyers_filter_sets_filtered_bid_requests_list(self) -> None:
        """Test case for adexchangebuyer2_buyers_filter_sets_filtered_bid_requests_list

        """
        pass

    def test_adexchangebuyer2_buyers_filter_sets_filtered_bids_creatives_list(self) -> None:
        """Test case for adexchangebuyer2_buyers_filter_sets_filtered_bids_creatives_list

        """
        pass

    def test_adexchangebuyer2_buyers_filter_sets_filtered_bids_details_list(self) -> None:
        """Test case for adexchangebuyer2_buyers_filter_sets_filtered_bids_details_list

        """
        pass

    def test_adexchangebuyer2_buyers_filter_sets_filtered_bids_list(self) -> None:
        """Test case for adexchangebuyer2_buyers_filter_sets_filtered_bids_list

        """
        pass

    def test_adexchangebuyer2_buyers_filter_sets_get(self) -> None:
        """Test case for adexchangebuyer2_buyers_filter_sets_get

        """
        pass

    def test_adexchangebuyer2_buyers_filter_sets_impression_metrics_list(self) -> None:
        """Test case for adexchangebuyer2_buyers_filter_sets_impression_metrics_list

        """
        pass

    def test_adexchangebuyer2_buyers_filter_sets_list(self) -> None:
        """Test case for adexchangebuyer2_buyers_filter_sets_list

        """
        pass

    def test_adexchangebuyer2_buyers_filter_sets_losing_bids_list(self) -> None:
        """Test case for adexchangebuyer2_buyers_filter_sets_losing_bids_list

        """
        pass

    def test_adexchangebuyer2_buyers_filter_sets_non_billable_winning_bids_list(self) -> None:
        """Test case for adexchangebuyer2_buyers_filter_sets_non_billable_winning_bids_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
