package shared

type GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipMembershipEnum string

const (
	GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipMembershipEnumMembershipUnspecified        GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipMembershipEnum = "MEMBERSHIP_UNSPECIFIED"
	GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipMembershipEnumMembershipIncluded           GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipMembershipEnum = "MEMBERSHIP_INCLUDED"
	GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipMembershipEnumMembershipNotIncluded        GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipMembershipEnum = "MEMBERSHIP_NOT_INCLUDED"
	GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipMembershipEnumMembershipUnknownInfoDenied  GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipMembershipEnum = "MEMBERSHIP_UNKNOWN_INFO_DENIED"
	GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipMembershipEnumMembershipUnknownUnsupported GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipMembershipEnum = "MEMBERSHIP_UNKNOWN_UNSUPPORTED"
)

type GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipRelevanceEnum string

const (
	GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipRelevanceEnumHeuristicRelevanceUnspecified GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipRelevanceEnum = "HEURISTIC_RELEVANCE_UNSPECIFIED"
	GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipRelevanceEnumNormal                        GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipRelevanceEnum = "NORMAL"
	GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipRelevanceEnumHigh                          GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipRelevanceEnum = "HIGH"
)

// GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembership
// Details about whether the binding includes the principal.
type GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembership struct {
	Membership *GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipMembershipEnum `json:"membership,omitempty"`
	Relevance  *GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipRelevanceEnum  `json:"relevance,omitempty"`
}
