# coding: utf-8

"""
    Content API for Shopping

    Manage your product listings and accounts for Google Shopping

    The version of the OpenAPI document: v2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.promotion_promotion_status_destination_status import PromotionPromotionStatusDestinationStatus
from openapi_client.models.promotion_promotion_status_promotion_issue import PromotionPromotionStatusPromotionIssue
from typing import Optional, Set
from typing_extensions import Self

class PromotionPromotionStatus(BaseModel):
    """
    The status of the promotion.
    """ # noqa: E501
    creation_date: Optional[StrictStr] = Field(default=None, description="Date on which the promotion has been created in [ISO 8601](http://en.wikipedia.org/wiki/ISO_8601) format: Date, time, and offset, for example \"2020-01-02T09:00:00+01:00\" or \"2020-01-02T09:00:00Z\"", alias="creationDate")
    destination_statuses: Optional[List[PromotionPromotionStatusDestinationStatus]] = Field(default=None, description="The intended destinations for the promotion.", alias="destinationStatuses")
    last_update_date: Optional[StrictStr] = Field(default=None, description="Date on which the promotion status has been last updated in [ISO 8601](http://en.wikipedia.org/wiki/ISO_8601) format: Date, time, and offset, for example \"2020-01-02T09:00:00+01:00\" or \"2020-01-02T09:00:00Z\"", alias="lastUpdateDate")
    promotion_issue: Optional[List[PromotionPromotionStatusPromotionIssue]] = Field(default=None, description="A list of issues associated with the promotion.", alias="promotionIssue")
    __properties: ClassVar[List[str]] = ["creationDate", "destinationStatuses", "lastUpdateDate", "promotionIssue"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PromotionPromotionStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in destination_statuses (list)
        _items = []
        if self.destination_statuses:
            for _item_destination_statuses in self.destination_statuses:
                if _item_destination_statuses:
                    _items.append(_item_destination_statuses.to_dict())
            _dict['destinationStatuses'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in promotion_issue (list)
        _items = []
        if self.promotion_issue:
            for _item_promotion_issue in self.promotion_issue:
                if _item_promotion_issue:
                    _items.append(_item_promotion_issue.to_dict())
            _dict['promotionIssue'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PromotionPromotionStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "creationDate": obj.get("creationDate"),
            "destinationStatuses": [PromotionPromotionStatusDestinationStatus.from_dict(_item) for _item in obj["destinationStatuses"]] if obj.get("destinationStatuses") is not None else None,
            "lastUpdateDate": obj.get("lastUpdateDate"),
            "promotionIssue": [PromotionPromotionStatusPromotionIssue.from_dict(_item) for _item in obj["promotionIssue"]] if obj.get("promotionIssue") is not None else None
        })
        return _obj


