package shared

type GoogleCloudDialogflowV2SmartReplyModelMetadataTrainingModelTypeEnum string

const (
	GoogleCloudDialogflowV2SmartReplyModelMetadataTrainingModelTypeEnumModelTypeUnspecified       GoogleCloudDialogflowV2SmartReplyModelMetadataTrainingModelTypeEnum = "MODEL_TYPE_UNSPECIFIED"
	GoogleCloudDialogflowV2SmartReplyModelMetadataTrainingModelTypeEnumSmartReplyDualEncoderModel GoogleCloudDialogflowV2SmartReplyModelMetadataTrainingModelTypeEnum = "SMART_REPLY_DUAL_ENCODER_MODEL"
	GoogleCloudDialogflowV2SmartReplyModelMetadataTrainingModelTypeEnumSmartReplyBertModel        GoogleCloudDialogflowV2SmartReplyModelMetadataTrainingModelTypeEnum = "SMART_REPLY_BERT_MODEL"
)

type GoogleCloudDialogflowV2SmartReplyModelMetadata struct {
	TrainingModelType *GoogleCloudDialogflowV2SmartReplyModelMetadataTrainingModelTypeEnum `json:"trainingModelType,omitempty"`
}
