package shared

type GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequestParticipantRoleEnum string

const (
	GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequestParticipantRoleEnumRoleUnspecified GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequestParticipantRoleEnum = "ROLE_UNSPECIFIED"
	GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequestParticipantRoleEnumHumanAgent      GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequestParticipantRoleEnum = "HUMAN_AGENT"
	GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequestParticipantRoleEnumAutomatedAgent  GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequestParticipantRoleEnum = "AUTOMATED_AGENT"
	GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequestParticipantRoleEnumEndUser         GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequestParticipantRoleEnum = "END_USER"
)

type GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnum string

const (
	GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnumTypeUnspecified   GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnum = "TYPE_UNSPECIFIED"
	GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnumArticleSuggestion GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnum = "ARTICLE_SUGGESTION"
	GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnumFaq               GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnum = "FAQ"
	GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnumSmartReply        GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnum = "SMART_REPLY"
)

type GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequest struct {
	ParticipantRole       *GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequestParticipantRoleEnum       `json:"participantRole"`
	SuggestionFeatureType *GoogleCloudDialogflowV2ClearSuggestionFeatureConfigRequestSuggestionFeatureTypeEnum `json:"suggestionFeatureType"`
}
