swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /siteVerification/v1
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Verifies ownership of websites or domains with Google.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Google Site Verification
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/siteVerification/v1/rest'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: siteVerification
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/siteverification': Manage the list of sites and domains you control
      'https://www.googleapis.com/auth/siteverification.verify_only': Manage your new site verifications with Google
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/siteverification': Manage the list of sites and domains you control
      'https://www.googleapis.com/auth/siteverification.verify_only': Manage your new site verifications with Google
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: webResource
paths:
  /token:
    post:
      description: Get a verification token for placing on a website or domain.
      operationId: siteVerification.webResource.getToken
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/siteverification'
          Oauth2c:
            - 'https://www.googleapis.com/auth/siteverification'
        - Oauth2:
            - 'https://www.googleapis.com/auth/siteverification.verify_only'
          Oauth2c:
            - 'https://www.googleapis.com/auth/siteverification.verify_only'
      tags:
        - webResource
  /webResource:
    get:
      description: Get the list of your verified websites and domains.
      operationId: siteVerification.webResource.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/siteverification'
          Oauth2c:
            - 'https://www.googleapis.com/auth/siteverification'
      tags:
        - webResource
    post:
      description: Attempt verification of a website or domain.
      operationId: siteVerification.webResource.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/siteverification'
          Oauth2c:
            - 'https://www.googleapis.com/auth/siteverification'
        - Oauth2:
            - 'https://www.googleapis.com/auth/siteverification.verify_only'
          Oauth2c:
            - 'https://www.googleapis.com/auth/siteverification.verify_only'
      tags:
        - webResource
  '/webResource/{id}':
    delete:
      description: Relinquish ownership of a website or domain.
      operationId: siteVerification.webResource.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/siteverification'
          Oauth2c:
            - 'https://www.googleapis.com/auth/siteverification'
      tags:
        - webResource
    get:
      description: Get the most current data for a website or domain.
      operationId: siteVerification.webResource.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/siteverification'
          Oauth2c:
            - 'https://www.googleapis.com/auth/siteverification'
      tags:
        - webResource
    patch:
      description: Modify the list of owners for your website or domain. This method supports patch semantics.
      operationId: siteVerification.webResource.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/siteverification'
          Oauth2c:
            - 'https://www.googleapis.com/auth/siteverification'
      tags:
        - webResource
    put:
      description: Modify the list of owners for your website or domain.
      operationId: siteVerification.webResource.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/siteverification'
          Oauth2c:
            - 'https://www.googleapis.com/auth/siteverification'
      tags:
        - webResource