# coding: utf-8

"""
    PI Web API 2018 SP1 Swagger Spec

    Swagger Spec file that describes PI Web API

    The version of the OpenAPI document: 1.11.1.5383
    Contact: techsupport@osisoft.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.security_rights import SecurityRights

class TestSecurityRights(unittest.TestCase):
    """SecurityRights unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecurityRights:
        """Test SecurityRights
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecurityRights`
        """
        model = SecurityRights()
        if include_optional:
            return SecurityRights(
                can_annotate = True,
                can_delete = True,
                can_execute = True,
                can_read = True,
                can_read_data = True,
                can_subscribe = True,
                can_subscribe_others = True,
                can_write = True,
                can_write_data = True,
                has_admin = True,
                links = openapi_client.models.security_rights_links.SecurityRightsLinks(
                    owner = '', 
                    self = '', ),
                owner_web_id = 'I1EmDqD5loBNH0erqeqJodtALAYIKyyz2F5BGAxQAVXYRDBA',
                rights = [Read, WriteData],
                security_item = 'Default',
                user_identity = 'domain\user',
                web_exception = openapi_client.models.web_exception.WebException(
                    errors = [An error has occurred.], 
                    status_code = 500, )
            )
        else:
            return SecurityRights(
        )
        """

    def testSecurityRights(self):
        """Test SecurityRights"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
