package shared




type GoogleCloudAssuredworkloadsV1beta1RestrictAllowedResourcesRequestRestrictionTypeEnum string

const (
    GoogleCloudAssuredworkloadsV1beta1RestrictAllowedResourcesRequestRestrictionTypeEnumRestrictionTypeUnspecified GoogleCloudAssuredworkloadsV1beta1RestrictAllowedResourcesRequestRestrictionTypeEnum = "RESTRICTION_TYPE_UNSPECIFIED"
GoogleCloudAssuredworkloadsV1beta1RestrictAllowedResourcesRequestRestrictionTypeEnumAllowAllGcpResources GoogleCloudAssuredworkloadsV1beta1RestrictAllowedResourcesRequestRestrictionTypeEnum = "ALLOW_ALL_GCP_RESOURCES"
GoogleCloudAssuredworkloadsV1beta1RestrictAllowedResourcesRequestRestrictionTypeEnumAllowCompliantResources GoogleCloudAssuredworkloadsV1beta1RestrictAllowedResourcesRequestRestrictionTypeEnum = "ALLOW_COMPLIANT_RESOURCES"
)


type GoogleCloudAssuredworkloadsV1beta1RestrictAllowedResourcesRequest struct {
    RestrictionType *GoogleCloudAssuredworkloadsV1beta1RestrictAllowedResourcesRequestRestrictionTypeEnum `json:"restrictionType,omitempty"`
    
}

