{
  "swagger": "2.0",
  "info": {
    "title": "Enterprise Apps Reseller API",
    "x-serviceName": "reseller",
    "description": "Lets you create and manage your customers and their subscriptions.",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v1",
    "x-origin": {
      "format": "google",
      "version": "v1",
      "url": "https://www.googleapis.com/discovery/v1/apis/reseller/v1/rest"
    }
  },
  "host": "www.googleapis.com",
  "basePath": "/apps/reseller/v1",
  "schemes": [
    "https"
  ],
  "paths": {
    "/customers/{customerId}": {
      "get": {
        "description": "Gets a customer resource if one exists and is owned by the reseller.",
        "operationId": "reseller.customers.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/apps.order",
              "https://www.googleapis.com/auth/apps.order.readonly"
            ]
          }
        ],
        "tags": [
          "customers"
        ]
      },
      "patch": {
        "description": "Update a customer resource if one it exists and is owned by the reseller. This method supports patch semantics.",
        "operationId": "reseller.customers.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/apps.order"
            ]
          }
        ],
        "tags": [
          "customers"
        ]
      },
      "put": {
        "description": "Update a customer resource if one it exists and is owned by the reseller.",
        "operationId": "reseller.customers.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/apps.order"
            ]
          }
        ],
        "tags": [
          "customers"
        ]
      }
    },
    "/customers": {
      "post": {
        "description": "Creates a customer resource if one does not already exist.",
        "operationId": "reseller.customers.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/apps.order"
            ]
          }
        ],
        "tags": [
          "customers"
        ]
      }
    },
    "/customers/{customerId}/subscriptions/{subscriptionId}/activate": {
      "post": {
        "description": "Activates a subscription previously suspended by the reseller",
        "operationId": "reseller.subscriptions.activate",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/apps.order"
            ]
          }
        ],
        "tags": [
          "subscriptions"
        ]
      }
    },
    "/customers/{customerId}/subscriptions/{subscriptionId}/changePlan": {
      "post": {
        "description": "Changes the plan of a subscription",
        "operationId": "reseller.subscriptions.changePlan",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/apps.order"
            ]
          }
        ],
        "tags": [
          "subscriptions"
        ]
      }
    },
    "/customers/{customerId}/subscriptions/{subscriptionId}/changeRenewalSettings": {
      "post": {
        "description": "Changes the renewal settings of a subscription",
        "operationId": "reseller.subscriptions.changeRenewalSettings",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/apps.order"
            ]
          }
        ],
        "tags": [
          "subscriptions"
        ]
      }
    },
    "/customers/{customerId}/subscriptions/{subscriptionId}/changeSeats": {
      "post": {
        "description": "Changes the seats configuration of a subscription",
        "operationId": "reseller.subscriptions.changeSeats",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/apps.order"
            ]
          }
        ],
        "tags": [
          "subscriptions"
        ]
      }
    },
    "/customers/{customerId}/subscriptions/{subscriptionId}": {
      "delete": {
        "description": "Cancels/Downgrades a subscription.",
        "operationId": "reseller.subscriptions.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/apps.order"
            ]
          }
        ],
        "tags": [
          "subscriptions"
        ]
      },
      "get": {
        "description": "Gets a subscription of the customer.",
        "operationId": "reseller.subscriptions.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/apps.order",
              "https://www.googleapis.com/auth/apps.order.readonly"
            ]
          }
        ],
        "tags": [
          "subscriptions"
        ]
      }
    },
    "/customers/{customerId}/subscriptions": {
      "post": {
        "description": "Creates/Transfers a subscription for the customer.",
        "operationId": "reseller.subscriptions.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/apps.order"
            ]
          }
        ],
        "tags": [
          "subscriptions"
        ]
      }
    },
    "/subscriptions": {
      "get": {
        "description": "Lists subscriptions of a reseller, optionally filtered by a customer name prefix.",
        "operationId": "reseller.subscriptions.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/apps.order",
              "https://www.googleapis.com/auth/apps.order.readonly"
            ]
          }
        ],
        "tags": [
          "subscriptions"
        ]
      }
    },
    "/customers/{customerId}/subscriptions/{subscriptionId}/startPaidService": {
      "post": {
        "description": "Starts paid service of a trial subscription",
        "operationId": "reseller.subscriptions.startPaidService",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/apps.order"
            ]
          }
        ],
        "tags": [
          "subscriptions"
        ]
      }
    },
    "/customers/{customerId}/subscriptions/{subscriptionId}/suspend": {
      "post": {
        "description": "Suspends an active subscription",
        "operationId": "reseller.subscriptions.suspend",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/apps.order"
            ]
          }
        ],
        "tags": [
          "subscriptions"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/apps.order": "Manage users on your domain",
        "https://www.googleapis.com/auth/apps.order.readonly": "Manage users on your domain"
      }
    }
  }
}