{
  "openapi": "3.0.0",
  "servers": [
    {
      "url": "https://vault.googleapis.com/"
    }
  ],
  "info": {
    "contact": {
      "name": "Google",
      "url": "https://google.com",
      "x-twitter": "youtube"
    },
    "description": "Retention and eDiscovery for Google Workspace. To work with Vault resources, the account must have the [required Vault privileges](https://support.google.com/vault/answer/2799699) and access to the matter. To access a matter, the account must have created the matter, have the matter shared with them, or have the **View All Matters** privilege. For example, to download an export, an account needs the **Manage Exports** privilege and the matter shared with them. ",
    "license": {
      "name": "Creative Commons Attribution 3.0",
      "url": "http://creativecommons.org/licenses/by/3.0/"
    },
    "termsOfService": "https://developers.google.com/terms/",
    "title": "Google Vault API",
    "version": "v1",
    "x-apiClientRegistration": {
      "url": "https://console.developers.google.com"
    },
    "x-apisguru-categories": [
      "analytics",
      "media"
    ],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png"
    },
    "x-origin": [
      {
        "converter": {
          "url": "https://github.com/mermade/oas-kit",
          "version": "7.0.4"
        },
        "format": "google",
        "url": "https://vault.googleapis.com/$discovery/rest?version=v1",
        "version": "v1"
      }
    ],
    "x-providerName": "googleapis.com",
    "x-serviceName": "vault"
  },
  "tags": [
    {
      "name": "matters"
    },
    {
      "name": "operations"
    }
  ],
  "paths": {
    "/v1/matters": {
      "get": {
        "description": "Lists matters the requestor has access to.",
        "operationId": "vault.matters.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      },
      "post": {
        "description": "Creates a matter with the given name and description. The initial state is open, and the owner is the method caller. Returns the created matter with default view.",
        "operationId": "vault.matters.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      }
    },
    "/v1/matters/{matterId}": {
      "delete": {
        "description": "Deletes the specified matter. Returns the matter with updated state.",
        "operationId": "vault.matters.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      },
      "get": {
        "description": "Gets the specified matter.",
        "operationId": "vault.matters.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      },
      "put": {
        "description": "Updates the specified matter. This updates only the name and description of the matter, identified by matter ID. Changes to any other fields are ignored. Returns the default view of the matter.",
        "operationId": "vault.matters.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      }
    },
    "/v1/matters/{matterId}/exports": {
      "get": {
        "description": "Lists details about the exports in the specified matter.",
        "operationId": "vault.matters.exports.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      },
      "post": {
        "description": "Creates an export.",
        "operationId": "vault.matters.exports.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      }
    },
    "/v1/matters/{matterId}/exports/{exportId}": {
      "delete": {
        "description": "Deletes an export.",
        "operationId": "vault.matters.exports.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      },
      "get": {
        "description": "Gets an export.",
        "operationId": "vault.matters.exports.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      }
    },
    "/v1/matters/{matterId}/holds": {
      "get": {
        "description": "Lists the holds in a matter.",
        "operationId": "vault.matters.holds.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      },
      "post": {
        "description": "Creates a hold in the specified matter.",
        "operationId": "vault.matters.holds.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      }
    },
    "/v1/matters/{matterId}/holds/{holdId}": {
      "delete": {
        "description": "Removes the specified hold and releases the accounts or organizational unit covered by the hold. If the data is not preserved by another hold or retention rule, it might be purged.",
        "operationId": "vault.matters.holds.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      },
      "get": {
        "description": "Gets the specified hold.",
        "operationId": "vault.matters.holds.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      },
      "put": {
        "description": "Updates the scope (organizational unit or accounts) and query parameters of a hold. You cannot add accounts to a hold that covers an organizational unit, nor can you add organizational units to a hold that covers individual accounts. If you try, the unsupported values are ignored.",
        "operationId": "vault.matters.holds.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      }
    },
    "/v1/matters/{matterId}/holds/{holdId}/accounts": {
      "get": {
        "description": "Lists the accounts covered by a hold. This can list only individually-specified accounts covered by the hold. If the hold covers an organizational unit, use the [Admin SDK](https://developers.google.com/admin-sdk/). to list the members of the organizational unit on hold.",
        "operationId": "vault.matters.holds.accounts.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      },
      "post": {
        "description": "Adds an account to a hold. Accounts can be added only to a hold that does not have an organizational unit set. If you try to add an account to an organizational unit-based hold, an error is returned.",
        "operationId": "vault.matters.holds.accounts.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      }
    },
    "/v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}": {
      "delete": {
        "description": "Removes an account from a hold.",
        "operationId": "vault.matters.holds.accounts.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      }
    },
    "/v1/matters/{matterId}/holds/{holdId}:addHeldAccounts": {
      "post": {
        "description": "Adds accounts to a hold. Returns a list of accounts that have been successfully added. Accounts can be added only to an existing account-based hold.",
        "operationId": "vault.matters.holds.addHeldAccounts",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      }
    },
    "/v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts": {
      "post": {
        "description": "Removes the specified accounts from a hold. Returns a list of statuses in the same order as the request.",
        "operationId": "vault.matters.holds.removeHeldAccounts",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      }
    },
    "/v1/matters/{matterId}/savedQueries": {
      "get": {
        "description": "Lists the saved queries in a matter.",
        "operationId": "vault.matters.savedQueries.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      },
      "post": {
        "description": "Creates a saved query.",
        "operationId": "vault.matters.savedQueries.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      }
    },
    "/v1/matters/{matterId}/savedQueries/{savedQueryId}": {
      "delete": {
        "description": "Deletes the specified saved query.",
        "operationId": "vault.matters.savedQueries.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      },
      "get": {
        "description": "Retrieves the specified saved query.",
        "operationId": "vault.matters.savedQueries.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      }
    },
    "/v1/matters/{matterId}:addPermissions": {
      "post": {
        "description": "Adds an account as a matter collaborator.",
        "operationId": "vault.matters.addPermissions",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      }
    },
    "/v1/matters/{matterId}:close": {
      "post": {
        "description": "Closes the specified matter. Returns the matter with updated state.",
        "operationId": "vault.matters.close",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      }
    },
    "/v1/matters/{matterId}:count": {
      "post": {
        "description": "Counts the accounts processed by the specified query.",
        "operationId": "vault.matters.count",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      }
    },
    "/v1/matters/{matterId}:removePermissions": {
      "post": {
        "description": "Removes an account as a matter collaborator.",
        "operationId": "vault.matters.removePermissions",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      }
    },
    "/v1/matters/{matterId}:reopen": {
      "post": {
        "description": "Reopens the specified matter. Returns the matter with updated state.",
        "operationId": "vault.matters.reopen",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      }
    },
    "/v1/matters/{matterId}:undelete": {
      "post": {
        "description": "Undeletes the specified matter. Returns the matter with updated state.",
        "operationId": "vault.matters.undelete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ]
      }
    },
    "/v1/{name}": {
      "delete": {
        "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
        "operationId": "vault.operations.delete",
        "tags": [
          "operations"
        ]
      },
      "get": {
        "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
        "operationId": "vault.operations.list",
        "tags": [
          "operations"
        ]
      }
    },
    "/v1/{name}:cancel": {
      "post": {
        "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an o[...]",
        "operationId": "vault.operations.cancel",
        "tags": [
          "operations"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Oauth2": {
        "description": "Oauth 2.0 implicit authentication",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
            "scopes": {
              "https://www.googleapis.com/auth/ediscovery": "Manage your eDiscovery data",
              "https://www.googleapis.com/auth/ediscovery.readonly": "View your eDiscovery data"
            }
          }
        },
        "type": "oauth2"
      },
      "Oauth2c": {
        "description": "Oauth 2.0 authorizationCode authentication",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
            "scopes": {
              "https://www.googleapis.com/auth/ediscovery": "Manage your eDiscovery data",
              "https://www.googleapis.com/auth/ediscovery.readonly": "View your eDiscovery data"
            },
            "tokenUrl": "https://accounts.google.com/o/oauth2/token"
          }
        },
        "type": "oauth2"
      }
    }
  }
}