package shared

type LambdaFunctionMemoryMetricStatisticEnum string

const (
	LambdaFunctionMemoryMetricStatisticEnumLowerBound LambdaFunctionMemoryMetricStatisticEnum = "LowerBound"
	LambdaFunctionMemoryMetricStatisticEnumUpperBound LambdaFunctionMemoryMetricStatisticEnum = "UpperBound"
	LambdaFunctionMemoryMetricStatisticEnumExpected   LambdaFunctionMemoryMetricStatisticEnum = "Expected"
)
