package shared




type LambdaFunctionRecommendationFindingReasonCodeEnum string

const (
    LambdaFunctionRecommendationFindingReasonCodeEnumMemoryOverprovisioned LambdaFunctionRecommendationFindingReasonCodeEnum = "MemoryOverprovisioned"
LambdaFunctionRecommendationFindingReasonCodeEnumMemoryUnderprovisioned LambdaFunctionRecommendationFindingReasonCodeEnum = "MemoryUnderprovisioned"
LambdaFunctionRecommendationFindingReasonCodeEnumInsufficientData LambdaFunctionRecommendationFindingReasonCodeEnum = "InsufficientData"
LambdaFunctionRecommendationFindingReasonCodeEnumInconclusive LambdaFunctionRecommendationFindingReasonCodeEnum = "Inconclusive"
)


