package shared

type DirectConnectGatewayAttachmentTypeEnum string

const (
	DirectConnectGatewayAttachmentTypeEnumTransitVirtualInterface DirectConnectGatewayAttachmentTypeEnum = "TransitVirtualInterface"
	DirectConnectGatewayAttachmentTypeEnumPrivateVirtualInterface DirectConnectGatewayAttachmentTypeEnum = "PrivateVirtualInterface"
)
