swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /clouduseraccounts/vm_beta/projects
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Creates and manages users and groups for accessing Google Compute Engine virtual machines.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Cloud User Accounts
  version: vm_beta
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://cloud.google.com/_static/images/new-gcp-logo.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.6.0
      format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/clouduseraccounts/vm_beta/rest'
      version: v1
  x-preferred: false
  x-providerName: googleapis.com
  x-serviceName: clouduseraccounts
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/cloud-platform': View and manage your data across Google Cloud Platform services
      'https://www.googleapis.com/auth/cloud-platform.read-only': View your data across Google Cloud Platform services
      'https://www.googleapis.com/auth/cloud.useraccounts': Manage your Google Cloud User Accounts
      'https://www.googleapis.com/auth/cloud.useraccounts.readonly': View your Google Cloud User Accounts
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/cloud-platform': View and manage your data across Google Cloud Platform services
      'https://www.googleapis.com/auth/cloud-platform.read-only': View your data across Google Cloud Platform services
      'https://www.googleapis.com/auth/cloud.useraccounts': Manage your Google Cloud User Accounts
      'https://www.googleapis.com/auth/cloud.useraccounts.readonly': View your Google Cloud User Accounts
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: globalAccountsOperations
  - name: groups
  - name: linux
  - name: users
paths:
  '/{project}/global/groups':
    get:
      description: Retrieves the list of groups contained within the specified project.
      operationId: clouduseraccounts.groups.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts.readonly'
      tags:
        - groups
    post:
      description: Creates a Group resource in the specified project using the data included in the request.
      operationId: clouduseraccounts.groups.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
      tags:
        - groups
  '/{project}/global/groups/{groupName}':
    delete:
      description: Deletes the specified Group resource.
      operationId: clouduseraccounts.groups.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
      tags:
        - groups
    get:
      description: Returns the specified Group resource.
      operationId: clouduseraccounts.groups.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts.readonly'
      tags:
        - groups
  '/{project}/global/groups/{groupName}/addMember':
    post:
      description: Adds users to the specified group.
      operationId: clouduseraccounts.groups.addMember
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
      tags:
        - groups
  '/{project}/global/groups/{groupName}/removeMember':
    post:
      description: Removes users from the specified group.
      operationId: clouduseraccounts.groups.removeMember
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
      tags:
        - groups
  '/{project}/global/operations':
    get:
      description: Retrieves the list of operation resources contained within the specified project.
      operationId: clouduseraccounts.globalAccountsOperations.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts.readonly'
      tags:
        - globalAccountsOperations
  '/{project}/global/operations/{operation}':
    delete:
      description: Deletes the specified operation resource.
      operationId: clouduseraccounts.globalAccountsOperations.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
      tags:
        - globalAccountsOperations
    get:
      description: Retrieves the specified operation resource.
      operationId: clouduseraccounts.globalAccountsOperations.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts.readonly'
      tags:
        - globalAccountsOperations
  '/{project}/global/users':
    get:
      description: Retrieves a list of users contained within the specified project.
      operationId: clouduseraccounts.users.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts.readonly'
      tags:
        - users
    post:
      description: Creates a User resource in the specified project using the data included in the request.
      operationId: clouduseraccounts.users.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
      tags:
        - users
  '/{project}/global/users/{user}':
    delete:
      description: Deletes the specified User resource.
      operationId: clouduseraccounts.users.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
      tags:
        - users
    get:
      description: Returns the specified User resource.
      operationId: clouduseraccounts.users.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts.readonly'
      tags:
        - users
  '/{project}/global/users/{user}/addPublicKey':
    post:
      description: Adds a public key to the specified User resource with the data included in the request.
      operationId: clouduseraccounts.users.addPublicKey
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
      tags:
        - users
  '/{project}/global/users/{user}/removePublicKey':
    post:
      description: Removes the specified public key from the user.
      operationId: clouduseraccounts.users.removePublicKey
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
      tags:
        - users
  '/{project}/zones/{zone}/authorizedKeysView/{user}':
    post:
      description: Returns a list of authorized public keys for a specific user account.
      operationId: clouduseraccounts.linux.getAuthorizedKeysView
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts.readonly'
      tags:
        - linux
  '/{project}/zones/{zone}/linuxAccountViews':
    post:
      description: Retrieves a list of user accounts for an instance within a specific project.
      operationId: clouduseraccounts.linux.getLinuxAccountViews
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud.useraccounts.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud.useraccounts.readonly'
      tags:
        - linux