swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /dfareporting/v2.7
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Manages your DoubleClick Campaign Manager ad campaigns and reports.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: DCM/DFA Reporting And Trafficking
  version: v2.7
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/dfareporting/v2.7/rest'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: dfareporting
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/ddmconversions': Manage DoubleClick Digital Marketing conversions
      'https://www.googleapis.com/auth/dfareporting': View and manage DoubleClick for Advertisers reports
      'https://www.googleapis.com/auth/dfatrafficking': View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/ddmconversions': Manage DoubleClick Digital Marketing conversions
      'https://www.googleapis.com/auth/dfareporting': View and manage DoubleClick for Advertisers reports
      'https://www.googleapis.com/auth/dfatrafficking': View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: accountActiveAdSummaries
  - name: accountPermissionGroups
  - name: accountPermissions
  - name: accountUserProfiles
  - name: accounts
  - name: ads
  - name: advertiserGroups
  - name: advertisers
  - name: browsers
  - name: campaignCreativeAssociations
  - name: campaigns
  - name: changeLogs
  - name: cities
  - name: connectionTypes
  - name: contentCategories
  - name: conversions
  - name: countries
  - name: creativeAssets
  - name: creativeFieldValues
  - name: creativeFields
  - name: creativeGroups
  - name: creatives
  - name: dimensionValues
  - name: directorySiteContacts
  - name: directorySites
  - name: dynamicTargetingKeys
  - name: eventTags
  - name: files
  - name: floodlightActivities
  - name: floodlightActivityGroups
  - name: floodlightConfigurations
  - name: inventoryItems
  - name: landingPages
  - name: languages
  - name: metros
  - name: mobileCarriers
  - name: operatingSystemVersions
  - name: operatingSystems
  - name: orderDocuments
  - name: orders
  - name: placementGroups
  - name: placementStrategies
  - name: placements
  - name: platformTypes
  - name: postalCodes
  - name: projects
  - name: regions
  - name: remarketingListShares
  - name: remarketingLists
  - name: reports
  - name: sites
  - name: sizes
  - name: subaccounts
  - name: targetableRemarketingLists
  - name: targetingTemplates
  - name: userProfiles
  - name: userRolePermissionGroups
  - name: userRolePermissions
  - name: userRoles
  - name: videoFormats
paths:
  '/reports/{reportId}/files/{fileId}':
    get:
      description: Retrieves a report file by its report ID and file ID. This method supports media download.
      operationId: dfareporting.files.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfareporting'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfareporting'
      tags:
        - files
  /userprofiles:
    get:
      description: Retrieves list of user profiles for a user.
      operationId: dfareporting.userProfiles.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfareporting'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfareporting'
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - userProfiles
  '/userprofiles/{profileId}':
    get:
      description: Gets one user profile by ID.
      operationId: dfareporting.userProfiles.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfareporting'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfareporting'
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - userProfiles
  '/userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}':
    get:
      description: Gets the account's active ad summary by account ID.
      operationId: dfareporting.accountActiveAdSummaries.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - accountActiveAdSummaries
  '/userprofiles/{profileId}/accountPermissionGroups':
    get:
      description: Retrieves the list of account permission groups.
      operationId: dfareporting.accountPermissionGroups.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - accountPermissionGroups
  '/userprofiles/{profileId}/accountPermissionGroups/{id}':
    get:
      description: Gets one account permission group by ID.
      operationId: dfareporting.accountPermissionGroups.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - accountPermissionGroups
  '/userprofiles/{profileId}/accountPermissions':
    get:
      description: Retrieves the list of account permissions.
      operationId: dfareporting.accountPermissions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - accountPermissions
  '/userprofiles/{profileId}/accountPermissions/{id}':
    get:
      description: Gets one account permission by ID.
      operationId: dfareporting.accountPermissions.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - accountPermissions
  '/userprofiles/{profileId}/accountUserProfiles':
    get:
      description: 'Retrieves a list of account user profiles, possibly filtered. This method supports paging.'
      operationId: dfareporting.accountUserProfiles.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - accountUserProfiles
    patch:
      description: Updates an existing account user profile. This method supports patch semantics.
      operationId: dfareporting.accountUserProfiles.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - accountUserProfiles
    post:
      description: Inserts a new account user profile.
      operationId: dfareporting.accountUserProfiles.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - accountUserProfiles
    put:
      description: Updates an existing account user profile.
      operationId: dfareporting.accountUserProfiles.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - accountUserProfiles
  '/userprofiles/{profileId}/accountUserProfiles/{id}':
    get:
      description: Gets one account user profile by ID.
      operationId: dfareporting.accountUserProfiles.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - accountUserProfiles
  '/userprofiles/{profileId}/accounts':
    get:
      description: 'Retrieves the list of accounts, possibly filtered. This method supports paging.'
      operationId: dfareporting.accounts.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - accounts
    patch:
      description: Updates an existing account. This method supports patch semantics.
      operationId: dfareporting.accounts.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - accounts
    put:
      description: Updates an existing account.
      operationId: dfareporting.accounts.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - accounts
  '/userprofiles/{profileId}/accounts/{id}':
    get:
      description: Gets one account by ID.
      operationId: dfareporting.accounts.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - accounts
  '/userprofiles/{profileId}/ads':
    get:
      description: 'Retrieves a list of ads, possibly filtered. This method supports paging.'
      operationId: dfareporting.ads.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - ads
    patch:
      description: Updates an existing ad. This method supports patch semantics.
      operationId: dfareporting.ads.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - ads
    post:
      description: Inserts a new ad.
      operationId: dfareporting.ads.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - ads
    put:
      description: Updates an existing ad.
      operationId: dfareporting.ads.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - ads
  '/userprofiles/{profileId}/ads/{id}':
    get:
      description: Gets one ad by ID.
      operationId: dfareporting.ads.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - ads
  '/userprofiles/{profileId}/advertiserGroups':
    get:
      description: 'Retrieves a list of advertiser groups, possibly filtered. This method supports paging.'
      operationId: dfareporting.advertiserGroups.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - advertiserGroups
    patch:
      description: Updates an existing advertiser group. This method supports patch semantics.
      operationId: dfareporting.advertiserGroups.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - advertiserGroups
    post:
      description: Inserts a new advertiser group.
      operationId: dfareporting.advertiserGroups.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - advertiserGroups
    put:
      description: Updates an existing advertiser group.
      operationId: dfareporting.advertiserGroups.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - advertiserGroups
  '/userprofiles/{profileId}/advertiserGroups/{id}':
    delete:
      description: Deletes an existing advertiser group.
      operationId: dfareporting.advertiserGroups.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - advertiserGroups
    get:
      description: Gets one advertiser group by ID.
      operationId: dfareporting.advertiserGroups.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - advertiserGroups
  '/userprofiles/{profileId}/advertisers':
    get:
      description: 'Retrieves a list of advertisers, possibly filtered. This method supports paging.'
      operationId: dfareporting.advertisers.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - advertisers
    patch:
      description: Updates an existing advertiser. This method supports patch semantics.
      operationId: dfareporting.advertisers.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - advertisers
    post:
      description: Inserts a new advertiser.
      operationId: dfareporting.advertisers.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - advertisers
    put:
      description: Updates an existing advertiser.
      operationId: dfareporting.advertisers.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - advertisers
  '/userprofiles/{profileId}/advertisers/{id}':
    get:
      description: Gets one advertiser by ID.
      operationId: dfareporting.advertisers.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - advertisers
  '/userprofiles/{profileId}/browsers':
    get:
      description: Retrieves a list of browsers.
      operationId: dfareporting.browsers.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - browsers
  '/userprofiles/{profileId}/campaigns':
    get:
      description: 'Retrieves a list of campaigns, possibly filtered. This method supports paging.'
      operationId: dfareporting.campaigns.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - campaigns
    patch:
      description: Updates an existing campaign. This method supports patch semantics.
      operationId: dfareporting.campaigns.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - campaigns
    post:
      description: Inserts a new campaign.
      operationId: dfareporting.campaigns.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - campaigns
    put:
      description: Updates an existing campaign.
      operationId: dfareporting.campaigns.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - campaigns
  '/userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations':
    get:
      description: Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.
      operationId: dfareporting.campaignCreativeAssociations.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - campaignCreativeAssociations
    post:
      description: Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.
      operationId: dfareporting.campaignCreativeAssociations.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - campaignCreativeAssociations
  '/userprofiles/{profileId}/campaigns/{campaignId}/landingPages':
    get:
      description: Retrieves the list of landing pages for the specified campaign.
      operationId: dfareporting.landingPages.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - landingPages
    patch:
      description: Updates an existing campaign landing page. This method supports patch semantics.
      operationId: dfareporting.landingPages.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - landingPages
    post:
      description: Inserts a new landing page for the specified campaign.
      operationId: dfareporting.landingPages.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - landingPages
    put:
      description: Updates an existing campaign landing page.
      operationId: dfareporting.landingPages.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - landingPages
  '/userprofiles/{profileId}/campaigns/{campaignId}/landingPages/{id}':
    delete:
      description: Deletes an existing campaign landing page.
      operationId: dfareporting.landingPages.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - landingPages
    get:
      description: Gets one campaign landing page by ID.
      operationId: dfareporting.landingPages.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - landingPages
  '/userprofiles/{profileId}/campaigns/{id}':
    get:
      description: Gets one campaign by ID.
      operationId: dfareporting.campaigns.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - campaigns
  '/userprofiles/{profileId}/changeLogs':
    get:
      description: Retrieves a list of change logs. This method supports paging.
      operationId: dfareporting.changeLogs.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - changeLogs
  '/userprofiles/{profileId}/changeLogs/{id}':
    get:
      description: Gets one change log by ID.
      operationId: dfareporting.changeLogs.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - changeLogs
  '/userprofiles/{profileId}/cities':
    get:
      description: 'Retrieves a list of cities, possibly filtered.'
      operationId: dfareporting.cities.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - cities
  '/userprofiles/{profileId}/connectionTypes':
    get:
      description: Retrieves a list of connection types.
      operationId: dfareporting.connectionTypes.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - connectionTypes
  '/userprofiles/{profileId}/connectionTypes/{id}':
    get:
      description: Gets one connection type by ID.
      operationId: dfareporting.connectionTypes.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - connectionTypes
  '/userprofiles/{profileId}/contentCategories':
    get:
      description: 'Retrieves a list of content categories, possibly filtered. This method supports paging.'
      operationId: dfareporting.contentCategories.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - contentCategories
    patch:
      description: Updates an existing content category. This method supports patch semantics.
      operationId: dfareporting.contentCategories.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - contentCategories
    post:
      description: Inserts a new content category.
      operationId: dfareporting.contentCategories.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - contentCategories
    put:
      description: Updates an existing content category.
      operationId: dfareporting.contentCategories.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - contentCategories
  '/userprofiles/{profileId}/contentCategories/{id}':
    delete:
      description: Deletes an existing content category.
      operationId: dfareporting.contentCategories.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - contentCategories
    get:
      description: Gets one content category by ID.
      operationId: dfareporting.contentCategories.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - contentCategories
  '/userprofiles/{profileId}/conversions/batchinsert':
    post:
      description: Inserts conversions.
      operationId: dfareporting.conversions.batchinsert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ddmconversions'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ddmconversions'
      tags:
        - conversions
  '/userprofiles/{profileId}/countries':
    get:
      description: Retrieves a list of countries.
      operationId: dfareporting.countries.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - countries
  '/userprofiles/{profileId}/countries/{dartId}':
    get:
      description: Gets one country by ID.
      operationId: dfareporting.countries.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - countries
  '/userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets':
    post:
      description: Inserts a new creative asset.
      operationId: dfareporting.creativeAssets.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creativeAssets
  '/userprofiles/{profileId}/creativeFields':
    get:
      description: 'Retrieves a list of creative fields, possibly filtered. This method supports paging.'
      operationId: dfareporting.creativeFields.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creativeFields
    patch:
      description: Updates an existing creative field. This method supports patch semantics.
      operationId: dfareporting.creativeFields.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creativeFields
    post:
      description: Inserts a new creative field.
      operationId: dfareporting.creativeFields.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creativeFields
    put:
      description: Updates an existing creative field.
      operationId: dfareporting.creativeFields.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creativeFields
  '/userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues':
    get:
      description: 'Retrieves a list of creative field values, possibly filtered. This method supports paging.'
      operationId: dfareporting.creativeFieldValues.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creativeFieldValues
    patch:
      description: Updates an existing creative field value. This method supports patch semantics.
      operationId: dfareporting.creativeFieldValues.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creativeFieldValues
    post:
      description: Inserts a new creative field value.
      operationId: dfareporting.creativeFieldValues.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creativeFieldValues
    put:
      description: Updates an existing creative field value.
      operationId: dfareporting.creativeFieldValues.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creativeFieldValues
  '/userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}':
    delete:
      description: Deletes an existing creative field value.
      operationId: dfareporting.creativeFieldValues.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creativeFieldValues
    get:
      description: Gets one creative field value by ID.
      operationId: dfareporting.creativeFieldValues.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creativeFieldValues
  '/userprofiles/{profileId}/creativeFields/{id}':
    delete:
      description: Deletes an existing creative field.
      operationId: dfareporting.creativeFields.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creativeFields
    get:
      description: Gets one creative field by ID.
      operationId: dfareporting.creativeFields.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creativeFields
  '/userprofiles/{profileId}/creativeGroups':
    get:
      description: 'Retrieves a list of creative groups, possibly filtered. This method supports paging.'
      operationId: dfareporting.creativeGroups.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creativeGroups
    patch:
      description: Updates an existing creative group. This method supports patch semantics.
      operationId: dfareporting.creativeGroups.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creativeGroups
    post:
      description: Inserts a new creative group.
      operationId: dfareporting.creativeGroups.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creativeGroups
    put:
      description: Updates an existing creative group.
      operationId: dfareporting.creativeGroups.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creativeGroups
  '/userprofiles/{profileId}/creativeGroups/{id}':
    get:
      description: Gets one creative group by ID.
      operationId: dfareporting.creativeGroups.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creativeGroups
  '/userprofiles/{profileId}/creatives':
    get:
      description: 'Retrieves a list of creatives, possibly filtered. This method supports paging.'
      operationId: dfareporting.creatives.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creatives
    patch:
      description: Updates an existing creative. This method supports patch semantics.
      operationId: dfareporting.creatives.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creatives
    post:
      description: Inserts a new creative.
      operationId: dfareporting.creatives.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creatives
    put:
      description: Updates an existing creative.
      operationId: dfareporting.creatives.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creatives
  '/userprofiles/{profileId}/creatives/{id}':
    get:
      description: Gets one creative by ID.
      operationId: dfareporting.creatives.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - creatives
  '/userprofiles/{profileId}/dimensionvalues/query':
    post:
      description: Retrieves list of report dimension values for a list of filters.
      operationId: dfareporting.dimensionValues.query
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfareporting'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfareporting'
      tags:
        - dimensionValues
  '/userprofiles/{profileId}/directorySiteContacts':
    get:
      description: 'Retrieves a list of directory site contacts, possibly filtered. This method supports paging.'
      operationId: dfareporting.directorySiteContacts.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - directorySiteContacts
  '/userprofiles/{profileId}/directorySiteContacts/{id}':
    get:
      description: Gets one directory site contact by ID.
      operationId: dfareporting.directorySiteContacts.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - directorySiteContacts
  '/userprofiles/{profileId}/directorySites':
    get:
      description: 'Retrieves a list of directory sites, possibly filtered. This method supports paging.'
      operationId: dfareporting.directorySites.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - directorySites
    post:
      description: Inserts a new directory site.
      operationId: dfareporting.directorySites.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - directorySites
  '/userprofiles/{profileId}/directorySites/{id}':
    get:
      description: Gets one directory site by ID.
      operationId: dfareporting.directorySites.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - directorySites
  '/userprofiles/{profileId}/dynamicTargetingKeys':
    get:
      description: Retrieves a list of dynamic targeting keys.
      operationId: dfareporting.dynamicTargetingKeys.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - dynamicTargetingKeys
    post:
      description: 'Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser''s ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.'
      operationId: dfareporting.dynamicTargetingKeys.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - dynamicTargetingKeys
  '/userprofiles/{profileId}/dynamicTargetingKeys/{objectId}':
    delete:
      description: Deletes an existing dynamic targeting key.
      operationId: dfareporting.dynamicTargetingKeys.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - dynamicTargetingKeys
  '/userprofiles/{profileId}/eventTags':
    get:
      description: 'Retrieves a list of event tags, possibly filtered.'
      operationId: dfareporting.eventTags.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - eventTags
    patch:
      description: Updates an existing event tag. This method supports patch semantics.
      operationId: dfareporting.eventTags.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - eventTags
    post:
      description: Inserts a new event tag.
      operationId: dfareporting.eventTags.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - eventTags
    put:
      description: Updates an existing event tag.
      operationId: dfareporting.eventTags.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - eventTags
  '/userprofiles/{profileId}/eventTags/{id}':
    delete:
      description: Deletes an existing event tag.
      operationId: dfareporting.eventTags.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - eventTags
    get:
      description: Gets one event tag by ID.
      operationId: dfareporting.eventTags.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - eventTags
  '/userprofiles/{profileId}/files':
    get:
      description: Lists files for a user profile.
      operationId: dfareporting.files.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfareporting'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfareporting'
      tags:
        - files
  '/userprofiles/{profileId}/floodlightActivities':
    get:
      description: 'Retrieves a list of floodlight activities, possibly filtered. This method supports paging.'
      operationId: dfareporting.floodlightActivities.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - floodlightActivities
    patch:
      description: Updates an existing floodlight activity. This method supports patch semantics.
      operationId: dfareporting.floodlightActivities.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - floodlightActivities
    post:
      description: Inserts a new floodlight activity.
      operationId: dfareporting.floodlightActivities.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - floodlightActivities
    put:
      description: Updates an existing floodlight activity.
      operationId: dfareporting.floodlightActivities.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - floodlightActivities
  '/userprofiles/{profileId}/floodlightActivities/generatetag':
    post:
      description: Generates a tag for a floodlight activity.
      operationId: dfareporting.floodlightActivities.generatetag
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - floodlightActivities
  '/userprofiles/{profileId}/floodlightActivities/{id}':
    delete:
      description: Deletes an existing floodlight activity.
      operationId: dfareporting.floodlightActivities.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - floodlightActivities
    get:
      description: Gets one floodlight activity by ID.
      operationId: dfareporting.floodlightActivities.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - floodlightActivities
  '/userprofiles/{profileId}/floodlightActivityGroups':
    get:
      description: 'Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.'
      operationId: dfareporting.floodlightActivityGroups.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - floodlightActivityGroups
    patch:
      description: Updates an existing floodlight activity group. This method supports patch semantics.
      operationId: dfareporting.floodlightActivityGroups.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - floodlightActivityGroups
    post:
      description: Inserts a new floodlight activity group.
      operationId: dfareporting.floodlightActivityGroups.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - floodlightActivityGroups
    put:
      description: Updates an existing floodlight activity group.
      operationId: dfareporting.floodlightActivityGroups.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - floodlightActivityGroups
  '/userprofiles/{profileId}/floodlightActivityGroups/{id}':
    get:
      description: Gets one floodlight activity group by ID.
      operationId: dfareporting.floodlightActivityGroups.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - floodlightActivityGroups
  '/userprofiles/{profileId}/floodlightConfigurations':
    get:
      description: 'Retrieves a list of floodlight configurations, possibly filtered.'
      operationId: dfareporting.floodlightConfigurations.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - floodlightConfigurations
    patch:
      description: Updates an existing floodlight configuration. This method supports patch semantics.
      operationId: dfareporting.floodlightConfigurations.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - floodlightConfigurations
    put:
      description: Updates an existing floodlight configuration.
      operationId: dfareporting.floodlightConfigurations.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - floodlightConfigurations
  '/userprofiles/{profileId}/floodlightConfigurations/{id}':
    get:
      description: Gets one floodlight configuration by ID.
      operationId: dfareporting.floodlightConfigurations.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - floodlightConfigurations
  '/userprofiles/{profileId}/languages':
    get:
      description: Retrieves a list of languages.
      operationId: dfareporting.languages.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - languages
  '/userprofiles/{profileId}/metros':
    get:
      description: Retrieves a list of metros.
      operationId: dfareporting.metros.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - metros
  '/userprofiles/{profileId}/mobileCarriers':
    get:
      description: Retrieves a list of mobile carriers.
      operationId: dfareporting.mobileCarriers.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - mobileCarriers
  '/userprofiles/{profileId}/mobileCarriers/{id}':
    get:
      description: Gets one mobile carrier by ID.
      operationId: dfareporting.mobileCarriers.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - mobileCarriers
  '/userprofiles/{profileId}/operatingSystemVersions':
    get:
      description: Retrieves a list of operating system versions.
      operationId: dfareporting.operatingSystemVersions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - operatingSystemVersions
  '/userprofiles/{profileId}/operatingSystemVersions/{id}':
    get:
      description: Gets one operating system version by ID.
      operationId: dfareporting.operatingSystemVersions.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - operatingSystemVersions
  '/userprofiles/{profileId}/operatingSystems':
    get:
      description: Retrieves a list of operating systems.
      operationId: dfareporting.operatingSystems.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - operatingSystems
  '/userprofiles/{profileId}/operatingSystems/{dartId}':
    get:
      description: Gets one operating system by DART ID.
      operationId: dfareporting.operatingSystems.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - operatingSystems
  '/userprofiles/{profileId}/placementGroups':
    get:
      description: 'Retrieves a list of placement groups, possibly filtered. This method supports paging.'
      operationId: dfareporting.placementGroups.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - placementGroups
    patch:
      description: Updates an existing placement group. This method supports patch semantics.
      operationId: dfareporting.placementGroups.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - placementGroups
    post:
      description: Inserts a new placement group.
      operationId: dfareporting.placementGroups.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - placementGroups
    put:
      description: Updates an existing placement group.
      operationId: dfareporting.placementGroups.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - placementGroups
  '/userprofiles/{profileId}/placementGroups/{id}':
    get:
      description: Gets one placement group by ID.
      operationId: dfareporting.placementGroups.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - placementGroups
  '/userprofiles/{profileId}/placementStrategies':
    get:
      description: 'Retrieves a list of placement strategies, possibly filtered. This method supports paging.'
      operationId: dfareporting.placementStrategies.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - placementStrategies
    patch:
      description: Updates an existing placement strategy. This method supports patch semantics.
      operationId: dfareporting.placementStrategies.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - placementStrategies
    post:
      description: Inserts a new placement strategy.
      operationId: dfareporting.placementStrategies.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - placementStrategies
    put:
      description: Updates an existing placement strategy.
      operationId: dfareporting.placementStrategies.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - placementStrategies
  '/userprofiles/{profileId}/placementStrategies/{id}':
    delete:
      description: Deletes an existing placement strategy.
      operationId: dfareporting.placementStrategies.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - placementStrategies
    get:
      description: Gets one placement strategy by ID.
      operationId: dfareporting.placementStrategies.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - placementStrategies
  '/userprofiles/{profileId}/placements':
    get:
      description: 'Retrieves a list of placements, possibly filtered. This method supports paging.'
      operationId: dfareporting.placements.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - placements
    patch:
      description: Updates an existing placement. This method supports patch semantics.
      operationId: dfareporting.placements.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - placements
    post:
      description: Inserts a new placement.
      operationId: dfareporting.placements.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - placements
    put:
      description: Updates an existing placement.
      operationId: dfareporting.placements.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - placements
  '/userprofiles/{profileId}/placements/generatetags':
    post:
      description: Generates tags for a placement.
      operationId: dfareporting.placements.generatetags
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - placements
  '/userprofiles/{profileId}/placements/{id}':
    get:
      description: Gets one placement by ID.
      operationId: dfareporting.placements.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - placements
  '/userprofiles/{profileId}/platformTypes':
    get:
      description: Retrieves a list of platform types.
      operationId: dfareporting.platformTypes.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - platformTypes
  '/userprofiles/{profileId}/platformTypes/{id}':
    get:
      description: Gets one platform type by ID.
      operationId: dfareporting.platformTypes.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - platformTypes
  '/userprofiles/{profileId}/postalCodes':
    get:
      description: Retrieves a list of postal codes.
      operationId: dfareporting.postalCodes.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - postalCodes
  '/userprofiles/{profileId}/postalCodes/{code}':
    get:
      description: Gets one postal code by ID.
      operationId: dfareporting.postalCodes.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - postalCodes
  '/userprofiles/{profileId}/projects':
    get:
      description: 'Retrieves a list of projects, possibly filtered. This method supports paging.'
      operationId: dfareporting.projects.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - projects
  '/userprofiles/{profileId}/projects/{id}':
    get:
      description: Gets one project by ID.
      operationId: dfareporting.projects.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - projects
  '/userprofiles/{profileId}/projects/{projectId}/inventoryItems':
    get:
      description: 'Retrieves a list of inventory items, possibly filtered. This method supports paging.'
      operationId: dfareporting.inventoryItems.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - inventoryItems
  '/userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}':
    get:
      description: Gets one inventory item by ID.
      operationId: dfareporting.inventoryItems.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - inventoryItems
  '/userprofiles/{profileId}/projects/{projectId}/orderDocuments':
    get:
      description: 'Retrieves a list of order documents, possibly filtered. This method supports paging.'
      operationId: dfareporting.orderDocuments.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - orderDocuments
  '/userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}':
    get:
      description: Gets one order document by ID.
      operationId: dfareporting.orderDocuments.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - orderDocuments
  '/userprofiles/{profileId}/projects/{projectId}/orders':
    get:
      description: 'Retrieves a list of orders, possibly filtered. This method supports paging.'
      operationId: dfareporting.orders.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - orders
  '/userprofiles/{profileId}/projects/{projectId}/orders/{id}':
    get:
      description: Gets one order by ID.
      operationId: dfareporting.orders.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - orders
  '/userprofiles/{profileId}/regions':
    get:
      description: Retrieves a list of regions.
      operationId: dfareporting.regions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - regions
  '/userprofiles/{profileId}/remarketingListShares':
    patch:
      description: Updates an existing remarketing list share. This method supports patch semantics.
      operationId: dfareporting.remarketingListShares.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - remarketingListShares
    put:
      description: Updates an existing remarketing list share.
      operationId: dfareporting.remarketingListShares.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - remarketingListShares
  '/userprofiles/{profileId}/remarketingListShares/{remarketingListId}':
    get:
      description: Gets one remarketing list share by remarketing list ID.
      operationId: dfareporting.remarketingListShares.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - remarketingListShares
  '/userprofiles/{profileId}/remarketingLists':
    get:
      description: 'Retrieves a list of remarketing lists, possibly filtered. This method supports paging.'
      operationId: dfareporting.remarketingLists.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - remarketingLists
    patch:
      description: Updates an existing remarketing list. This method supports patch semantics.
      operationId: dfareporting.remarketingLists.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - remarketingLists
    post:
      description: Inserts a new remarketing list.
      operationId: dfareporting.remarketingLists.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - remarketingLists
    put:
      description: Updates an existing remarketing list.
      operationId: dfareporting.remarketingLists.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - remarketingLists
  '/userprofiles/{profileId}/remarketingLists/{id}':
    get:
      description: Gets one remarketing list by ID.
      operationId: dfareporting.remarketingLists.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - remarketingLists
  '/userprofiles/{profileId}/reports':
    get:
      description: Retrieves list of reports.
      operationId: dfareporting.reports.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfareporting'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfareporting'
      tags:
        - reports
    post:
      description: Creates a report.
      operationId: dfareporting.reports.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfareporting'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfareporting'
      tags:
        - reports
  '/userprofiles/{profileId}/reports/compatiblefields/query':
    post:
      description: 'Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.'
      operationId: dfareporting.reports.compatibleFields.query
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfareporting'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfareporting'
      tags:
        - reports
  '/userprofiles/{profileId}/reports/{reportId}':
    delete:
      description: Deletes a report by its ID.
      operationId: dfareporting.reports.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfareporting'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfareporting'
      tags:
        - reports
    get:
      description: Retrieves a report by its ID.
      operationId: dfareporting.reports.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfareporting'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfareporting'
      tags:
        - reports
    patch:
      description: Updates a report. This method supports patch semantics.
      operationId: dfareporting.reports.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfareporting'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfareporting'
      tags:
        - reports
    put:
      description: Updates a report.
      operationId: dfareporting.reports.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfareporting'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfareporting'
      tags:
        - reports
  '/userprofiles/{profileId}/reports/{reportId}/files':
    get:
      description: Lists files for a report.
      operationId: dfareporting.reports.files.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfareporting'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfareporting'
      tags:
        - reports
  '/userprofiles/{profileId}/reports/{reportId}/files/{fileId}':
    get:
      description: Retrieves a report file. This method supports media download.
      operationId: dfareporting.reports.files.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfareporting'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfareporting'
      tags:
        - reports
  '/userprofiles/{profileId}/reports/{reportId}/run':
    post:
      description: Runs a report.
      operationId: dfareporting.reports.run
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfareporting'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfareporting'
      tags:
        - reports
  '/userprofiles/{profileId}/sites':
    get:
      description: 'Retrieves a list of sites, possibly filtered. This method supports paging.'
      operationId: dfareporting.sites.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - sites
    patch:
      description: Updates an existing site. This method supports patch semantics.
      operationId: dfareporting.sites.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - sites
    post:
      description: Inserts a new site.
      operationId: dfareporting.sites.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - sites
    put:
      description: Updates an existing site.
      operationId: dfareporting.sites.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - sites
  '/userprofiles/{profileId}/sites/{id}':
    get:
      description: Gets one site by ID.
      operationId: dfareporting.sites.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - sites
  '/userprofiles/{profileId}/sizes':
    get:
      description: 'Retrieves a list of sizes, possibly filtered.'
      operationId: dfareporting.sizes.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - sizes
    post:
      description: Inserts a new size.
      operationId: dfareporting.sizes.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - sizes
  '/userprofiles/{profileId}/sizes/{id}':
    get:
      description: Gets one size by ID.
      operationId: dfareporting.sizes.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - sizes
  '/userprofiles/{profileId}/subaccounts':
    get:
      description: 'Gets a list of subaccounts, possibly filtered. This method supports paging.'
      operationId: dfareporting.subaccounts.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - subaccounts
    patch:
      description: Updates an existing subaccount. This method supports patch semantics.
      operationId: dfareporting.subaccounts.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - subaccounts
    post:
      description: Inserts a new subaccount.
      operationId: dfareporting.subaccounts.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - subaccounts
    put:
      description: Updates an existing subaccount.
      operationId: dfareporting.subaccounts.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - subaccounts
  '/userprofiles/{profileId}/subaccounts/{id}':
    get:
      description: Gets one subaccount by ID.
      operationId: dfareporting.subaccounts.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - subaccounts
  '/userprofiles/{profileId}/targetableRemarketingLists':
    get:
      description: 'Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.'
      operationId: dfareporting.targetableRemarketingLists.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - targetableRemarketingLists
  '/userprofiles/{profileId}/targetableRemarketingLists/{id}':
    get:
      description: Gets one remarketing list by ID.
      operationId: dfareporting.targetableRemarketingLists.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - targetableRemarketingLists
  '/userprofiles/{profileId}/targetingTemplates':
    get:
      description: 'Retrieves a list of targeting templates, optionally filtered. This method supports paging.'
      operationId: dfareporting.targetingTemplates.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - targetingTemplates
    patch:
      description: Updates an existing targeting template. This method supports patch semantics.
      operationId: dfareporting.targetingTemplates.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - targetingTemplates
    post:
      description: Inserts a new targeting template.
      operationId: dfareporting.targetingTemplates.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - targetingTemplates
    put:
      description: Updates an existing targeting template.
      operationId: dfareporting.targetingTemplates.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - targetingTemplates
  '/userprofiles/{profileId}/targetingTemplates/{id}':
    get:
      description: Gets one targeting template by ID.
      operationId: dfareporting.targetingTemplates.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - targetingTemplates
  '/userprofiles/{profileId}/userRolePermissionGroups':
    get:
      description: Gets a list of all supported user role permission groups.
      operationId: dfareporting.userRolePermissionGroups.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - userRolePermissionGroups
  '/userprofiles/{profileId}/userRolePermissionGroups/{id}':
    get:
      description: Gets one user role permission group by ID.
      operationId: dfareporting.userRolePermissionGroups.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - userRolePermissionGroups
  '/userprofiles/{profileId}/userRolePermissions':
    get:
      description: 'Gets a list of user role permissions, possibly filtered.'
      operationId: dfareporting.userRolePermissions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - userRolePermissions
  '/userprofiles/{profileId}/userRolePermissions/{id}':
    get:
      description: Gets one user role permission by ID.
      operationId: dfareporting.userRolePermissions.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - userRolePermissions
  '/userprofiles/{profileId}/userRoles':
    get:
      description: 'Retrieves a list of user roles, possibly filtered. This method supports paging.'
      operationId: dfareporting.userRoles.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - userRoles
    patch:
      description: Updates an existing user role. This method supports patch semantics.
      operationId: dfareporting.userRoles.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - userRoles
    post:
      description: Inserts a new user role.
      operationId: dfareporting.userRoles.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - userRoles
    put:
      description: Updates an existing user role.
      operationId: dfareporting.userRoles.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - userRoles
  '/userprofiles/{profileId}/userRoles/{id}':
    delete:
      description: Deletes an existing user role.
      operationId: dfareporting.userRoles.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - userRoles
    get:
      description: Gets one user role by ID.
      operationId: dfareporting.userRoles.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - userRoles
  '/userprofiles/{profileId}/videoFormats':
    get:
      description: Lists available video formats.
      operationId: dfareporting.videoFormats.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - videoFormats
  '/userprofiles/{profileId}/videoFormats/{id}':
    get:
      description: Gets one video format by ID.
      operationId: dfareporting.videoFormats.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/dfatrafficking'
          Oauth2c:
            - 'https://www.googleapis.com/auth/dfatrafficking'
      tags:
        - videoFormats