# coding: utf-8

"""
    Shop

    Search for millions of products from the world's greatest brands.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_details(self) -> None:
        """Test case for details

        Return more details about a list of products.
        """
        pass

    def test_search(self) -> None:
        """Test case for search

        Search for products
        """
        pass


if __name__ == '__main__':
    unittest.main()
