from .createparalleldata import *
from .deleteparalleldata import *
from .deleteterminology import *
from .describetexttranslationjob import *
from .getparalleldata import *
from .getterminology import *
from .importterminology import *
from .listparalleldata import *
from .listterminologies import *
from .listtexttranslationjobs import *
from .starttexttranslationjob import *
from .stoptexttranslationjob import *
from .translatetext import *
from .updateparalleldata import *
