# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API

    The version of the OpenAPI document: v0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.test_run_summary import TestRunSummary
from typing import Optional, Set
from typing_extensions import Self

class TestSeries(BaseModel):
    """
    Summary of a single test series
    """ # noqa: E501
    most_recent_activity: Optional[StrictStr] = Field(default=None, description="Date of the latest test run that used this test series", alias="mostRecentActivity")
    name: StrictStr = Field(description="Name of the test series")
    slug: StrictStr = Field(description="Unique, human-readable identifier of the test series")
    test_runs: Optional[List[TestRunSummary]] = Field(default=None, description="Most recent test runs", alias="testRuns")
    __properties: ClassVar[List[str]] = ["mostRecentActivity", "name", "slug", "testRuns"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TestSeries from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in test_runs (list)
        _items = []
        if self.test_runs:
            for _item_test_runs in self.test_runs:
                if _item_test_runs:
                    _items.append(_item_test_runs.to_dict())
            _dict['testRuns'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TestSeries from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "mostRecentActivity": obj.get("mostRecentActivity"),
            "name": obj.get("name"),
            "slug": obj.get("slug"),
            "testRuns": [TestRunSummary.from_dict(_item) for _item in obj["testRuns"]] if obj.get("testRuns") is not None else None
        })
        return _obj


