swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /webmasters/v3
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: View Google Search Console data for your verified sites.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Search Console
  version: v3
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/webmasters/v3/rest'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: webmasters
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/webmasters': View and manage Search Console data for your verified sites
      'https://www.googleapis.com/auth/webmasters.readonly': View Search Console data for your verified sites
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/webmasters': View and manage Search Console data for your verified sites
      'https://www.googleapis.com/auth/webmasters.readonly': View Search Console data for your verified sites
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: searchanalytics
  - name: sitemaps
  - name: sites
  - name: urlcrawlerrorscounts
  - name: urlcrawlerrorssamples
paths:
  /sites:
    get:
      description: Lists the user's Search Console sites.
      operationId: webmasters.sites.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters'
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters.readonly'
      tags:
        - sites
  '/sites/{siteUrl}':
    delete:
      description: Removes a site from the set of the user's Search Console sites.
      operationId: webmasters.sites.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters'
      tags:
        - sites
    get:
      description: Retrieves information about specific site.
      operationId: webmasters.sites.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters'
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters.readonly'
      tags:
        - sites
    put:
      description: Adds a site to the set of the user's sites in Search Console.
      operationId: webmasters.sites.add
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters'
      tags:
        - sites
  '/sites/{siteUrl}/searchAnalytics/query':
    post:
      description: |-
        Query your data with filters and parameters that you define. Returns zero or more rows grouped by the row keys that you define. You must define a date range of one or more days.

        When date is one of the group by values, any days without data are omitted from the result list. If you need to know which days have data, issue a broad date range query grouped by date for any metric, and see which day rows are returned.
      operationId: webmasters.searchanalytics.query
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters'
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters.readonly'
      tags:
        - searchanalytics
  '/sites/{siteUrl}/sitemaps':
    get:
      description: 'Lists the sitemaps-entries submitted for this site, or included in the sitemap index file (if sitemapIndex is specified in the request).'
      operationId: webmasters.sitemaps.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters'
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters.readonly'
      tags:
        - sitemaps
  '/sites/{siteUrl}/sitemaps/{feedpath}':
    delete:
      description: Deletes a sitemap from this site.
      operationId: webmasters.sitemaps.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters'
      tags:
        - sitemaps
    get:
      description: Retrieves information about a specific sitemap.
      operationId: webmasters.sitemaps.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters'
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters.readonly'
      tags:
        - sitemaps
    put:
      description: Submits a sitemap for a site.
      operationId: webmasters.sitemaps.submit
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters'
      tags:
        - sitemaps
  '/sites/{siteUrl}/urlCrawlErrorsCounts/query':
    get:
      description: Retrieves a time series of the number of URL crawl errors per error category and platform.
      operationId: webmasters.urlcrawlerrorscounts.query
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters'
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters.readonly'
      tags:
        - urlcrawlerrorscounts
  '/sites/{siteUrl}/urlCrawlErrorsSamples':
    get:
      description: Lists a site's sample URLs for the specified crawl error category and platform.
      operationId: webmasters.urlcrawlerrorssamples.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters'
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters.readonly'
      tags:
        - urlcrawlerrorssamples
  '/sites/{siteUrl}/urlCrawlErrorsSamples/{url}':
    delete:
      description: 'Marks the provided site''s sample URL as fixed, and removes it from the samples list.'
      operationId: webmasters.urlcrawlerrorssamples.markAsFixed
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters'
      tags:
        - urlcrawlerrorssamples
    get:
      description: Retrieves details about crawl errors for a site's sample URL.
      operationId: webmasters.urlcrawlerrorssamples.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters'
        - Oauth2:
            - 'https://www.googleapis.com/auth/webmasters.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/webmasters.readonly'
      tags:
        - urlcrawlerrorssamples