# coding: utf-8

"""
    DataLakeAnalyticsCatalogManagementClient

    Creates an Azure Data Lake Analytics catalog client.

    The version of the OpenAPI document: 2015-10-01-preview
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.external_table import ExternalTable
from openapi_client.models.u_sql_distribution_info import USqlDistributionInfo
from openapi_client.models.u_sql_index import USqlIndex
from openapi_client.models.u_sql_table_column import USqlTableColumn
from typing import Optional, Set
from typing_extensions import Self

class USqlTable(BaseModel):
    """
    A Data Lake Analytics catalog U-SQL table item.
    """ # noqa: E501
    column_list: Optional[List[USqlTableColumn]] = Field(default=None, description="the list of columns in this table", alias="columnList")
    database_name: Optional[StrictStr] = Field(default=None, description="the name of the database.", alias="databaseName")
    distribution_info: Optional[USqlDistributionInfo] = Field(default=None, alias="distributionInfo")
    external_table: Optional[ExternalTable] = Field(default=None, alias="externalTable")
    index_list: Optional[List[USqlIndex]] = Field(default=None, description="the list of indices in this table", alias="indexList")
    partition_key_list: Optional[List[StrictStr]] = Field(default=None, description="the list of partition keys in the table", alias="partitionKeyList")
    schema_name: Optional[StrictStr] = Field(default=None, description="the name of the schema associated with this table and database.", alias="schemaName")
    table_name: Optional[StrictStr] = Field(default=None, description="the name of the table.", alias="tableName")
    compute_account_name: Optional[StrictStr] = Field(default=None, description="the name of the Data Lake Analytics account.", alias="computeAccountName")
    version: Optional[StrictStr] = Field(default=None, description="the version of the catalog item.")
    __properties: ClassVar[List[str]] = ["computeAccountName", "version"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of USqlTable from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of USqlTable from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "computeAccountName": obj.get("computeAccountName"),
            "version": obj.get("version")
        })
        return _obj


