openapi: 3.0.0
servers:
  - url: https://cloudbilling.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: Allows developers to manage billing for their Google Cloud Platform projects programmatically.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Cloud Billing API
  version: v1beta
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png
  x-origin:
    - format: google
      url: https://cloudbilling.googleapis.com/$discovery/rest?version=v1beta
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: cloudbilling
tags:
  - name: billingAccounts
  - name: v1beta
paths:
  "/v1beta/{billingAccount}:estimateCostScenario":
    post:
      description: Use custom pricing in the estimate, using a `CostScenario` with a defined `billingAccount`.
      operationId: cloudbilling.billingAccounts.estimateCostScenario
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-billing
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-billing
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-billing.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-billing.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - billingAccounts
  /v1beta:estimateCostScenario:
    post:
      description: Estimate list prices using a `CostScenario` without a defined `billingAccount`.
      operationId: cloudbilling.estimateCostScenario
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-billing
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-billing
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-billing.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-billing.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - v1beta
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/cloud-billing: View and manage your Google Cloud Platform billing accounts
            https://www.googleapis.com/auth/cloud-billing.readonly: View your Google Cloud Platform billing accounts
            https://www.googleapis.com/auth/cloud-platform: See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account.
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/cloud-billing: View and manage your Google Cloud Platform billing accounts
            https://www.googleapis.com/auth/cloud-billing.readonly: View your Google Cloud Platform billing accounts
            https://www.googleapis.com/auth/cloud-platform: See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account.
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
