from .activity_check_repo_is_starred_by_authenticated_user import *
from .activity_delete_repo_subscription import *
from .activity_delete_thread_subscription import *
from .activity_get_feeds import *
from .activity_get_repo_subscription import *
from .activity_get_thread import *
from .activity_get_thread_subscription_for_authenticated_user import *
from .activity_list_events_for_authenticated_user import *
from .activity_list_notifications_for_authenticated_user import *
from .activity_list_org_events_for_authenticated_user import *
from .activity_list_public_events import *
from .activity_list_public_events_for_repo_network import *
from .activity_list_public_events_for_user import *
from .activity_list_public_org_events import *
from .activity_list_received_events_for_user import *
from .activity_list_received_public_events_for_user import *
from .activity_list_repo_events import *
from .activity_list_repo_notifications_for_authenticated_user import *
from .activity_list_repos_starred_by_authenticated_user import *
from .activity_list_repos_starred_by_user import *
from .activity_list_repos_watched_by_user import *
from .activity_list_stargazers_for_repo import *
from .activity_list_watched_repos_for_authenticated_user import *
from .activity_list_watchers_for_repo import *
from .activity_mark_notifications_as_read import *
from .activity_mark_repo_notifications_as_read import *
from .activity_mark_thread_as_read import *
from .activity_set_repo_subscription import *
from .activity_set_thread_subscription import *
from .activity_star_repo_for_authenticated_user import *
from .activity_unstar_repo_for_authenticated_user import *
from .apps_add_repo_to_installation import *
from .apps_check_authorization import *
from .apps_check_token import *
from .apps_create_content_attachment import *
from .apps_create_from_manifest import *
from .apps_create_installation_access_token import *
from .apps_delete_authorization import *
from .apps_delete_installation import *
from .apps_delete_token import *
from .apps_get_authenticated import *
from .apps_get_by_slug import *
from .apps_get_installation import *
from .apps_get_org_installation import *
from .apps_get_repo_installation import *
from .apps_get_user_installation import *
from .apps_list_installation_repos_for_authenticated_user import *
from .apps_list_installations import *
from .apps_list_installations_for_authenticated_user import *
from .apps_list_repos_accessible_to_installation import *
from .apps_remove_repo_from_installation import *
from .apps_reset_authorization import *
from .apps_reset_token import *
from .apps_revoke_authorization_for_application import *
from .apps_revoke_grant_for_application import *
from .apps_revoke_installation_access_token import *
from .checks_create import *
from .checks_create_suite import *
from .checks_get import *
from .checks_get_suite import *
from .checks_list_annotations import *
from .checks_list_for_ref import *
from .checks_list_for_suite import *
from .checks_list_suites_for_ref import *
from .checks_rerequest_suite import *
from .checks_set_suites_preferences import *
from .checks_update import *
from .codes_of_conduct_get_all_codes_of_conduct import *
from .codes_of_conduct_get_conduct_code import *
from .emojis_get import *
from .enterprise_admin_add_authorized_ssh_key import *
from .enterprise_admin_create_enterprise_server_license import *
from .enterprise_admin_create_global_webhook import *
from .enterprise_admin_create_impersonation_o_auth_token import *
from .enterprise_admin_create_org import *
from .enterprise_admin_create_pre_receive_environment import *
from .enterprise_admin_create_pre_receive_hook import *
from .enterprise_admin_create_user import *
from .enterprise_admin_delete_global_webhook import *
from .enterprise_admin_delete_impersonation_o_auth_token import *
from .enterprise_admin_delete_personal_access_token import *
from .enterprise_admin_delete_pre_receive_environment import *
from .enterprise_admin_delete_pre_receive_hook import *
from .enterprise_admin_delete_public_key import *
from .enterprise_admin_delete_user import *
from .enterprise_admin_demote_site_administrator import *
from .enterprise_admin_enable_or_disable_maintenance_mode import *
from .enterprise_admin_get_all_authorized_ssh_keys import *
from .enterprise_admin_get_configuration_status import *
from .enterprise_admin_get_download_status_for_pre_receive_environment import *
from .enterprise_admin_get_global_webhook import *
from .enterprise_admin_get_license_information import *
from .enterprise_admin_get_maintenance_status import *
from .enterprise_admin_get_pre_receive_environment import *
from .enterprise_admin_get_pre_receive_hook import *
from .enterprise_admin_get_pre_receive_hook_for_org import *
from .enterprise_admin_get_pre_receive_hook_for_repo import *
from .enterprise_admin_get_settings import *
from .enterprise_admin_get_type_stats import *
from .enterprise_admin_list_global_webhooks import *
from .enterprise_admin_list_personal_access_tokens import *
from .enterprise_admin_list_pre_receive_environments import *
from .enterprise_admin_list_pre_receive_hooks import *
from .enterprise_admin_list_pre_receive_hooks_for_org import *
from .enterprise_admin_list_pre_receive_hooks_for_repo import *
from .enterprise_admin_list_public_keys import *
from .enterprise_admin_ping_global_webhook import *
from .enterprise_admin_promote_user_to_be_site_administrator import *
from .enterprise_admin_remove_authorized_ssh_key import *
from .enterprise_admin_remove_pre_receive_hook_enforcement_for_org import *
from .enterprise_admin_remove_pre_receive_hook_enforcement_for_repo import *
from .enterprise_admin_set_settings import *
from .enterprise_admin_start_configuration_process import *
from .enterprise_admin_start_pre_receive_environment_download import *
from .enterprise_admin_suspend_user import *
from .enterprise_admin_sync_ldap_mapping_for_team import *
from .enterprise_admin_sync_ldap_mapping_for_user import *
from .enterprise_admin_unsuspend_user import *
from .enterprise_admin_update_global_webhook import *
from .enterprise_admin_update_ldap_mapping_for_team import *
from .enterprise_admin_update_ldap_mapping_for_user import *
from .enterprise_admin_update_org_name import *
from .enterprise_admin_update_pre_receive_environment import *
from .enterprise_admin_update_pre_receive_hook import *
from .enterprise_admin_update_pre_receive_hook_enforcement_for_org import *
from .enterprise_admin_update_pre_receive_hook_enforcement_for_repo import *
from .enterprise_admin_update_username_for_user import *
from .enterprise_admin_upgrade_license import *
from .gists_check_is_starred import *
from .gists_create import *
from .gists_create_comment import *
from .gists_delete import *
from .gists_delete_comment import *
from .gists_fork import *
from .gists_get import *
from .gists_get_comment import *
from .gists_get_revision import *
from .gists_list import *
from .gists_list_comments import *
from .gists_list_commits import *
from .gists_list_for_user import *
from .gists_list_forks import *
from .gists_list_public import *
from .gists_list_starred import *
from .gists_star import *
from .gists_unstar import *
from .gists_update import *
from .gists_update_comment import *
from .git_create_blob import *
from .git_create_commit import *
from .git_create_ref import *
from .git_create_tag import *
from .git_create_tree import *
from .git_delete_ref import *
from .git_get_blob import *
from .git_get_commit import *
from .git_get_ref import *
from .git_get_tag import *
from .git_get_tree import *
from .git_list_matching_refs import *
from .git_update_ref import *
from .gitignore_get_all_templates import *
from .gitignore_get_template import *
from .issues_add_assignees import *
from .issues_add_labels import *
from .issues_check_user_can_be_assigned import *
from .issues_create import *
from .issues_create_comment import *
from .issues_create_label import *
from .issues_create_milestone import *
from .issues_delete_comment import *
from .issues_delete_label import *
from .issues_delete_milestone import *
from .issues_get import *
from .issues_get_comment import *
from .issues_get_event import *
from .issues_get_label import *
from .issues_get_milestone import *
from .issues_list import *
from .issues_list_assignees import *
from .issues_list_comments import *
from .issues_list_comments_for_repo import *
from .issues_list_events import *
from .issues_list_events_for_repo import *
from .issues_list_events_for_timeline import *
from .issues_list_for_authenticated_user import *
from .issues_list_for_org import *
from .issues_list_for_repo import *
from .issues_list_labels_for_milestone import *
from .issues_list_labels_for_repo import *
from .issues_list_labels_on_issue import *
from .issues_list_milestones import *
from .issues_lock import *
from .issues_remove_all_labels import *
from .issues_remove_assignees import *
from .issues_remove_label import *
from .issues_set_labels import *
from .issues_unlock import *
from .issues_update import *
from .issues_update_comment import *
from .issues_update_label import *
from .issues_update_milestone import *
from .licenses_get import *
from .licenses_get_all_commonly_used import *
from .licenses_get_for_repo import *
from .markdown_render import *
from .markdown_render_raw import *
from .meta_get import *
from .meta_get_octocat import *
from .meta_get_zen import *
from .meta_root import *
from .oauth_authorizations_create_authorization import *
from .oauth_authorizations_delete_authorization import *
from .oauth_authorizations_delete_grant import *
from .oauth_authorizations_get_authorization import *
from .oauth_authorizations_get_grant import *
from .oauth_authorizations_get_or_create_authorization_for_app import *
from .oauth_authorizations_get_or_create_authorization_for_app_and_fingerprint import *
from .oauth_authorizations_list_authorizations import *
from .oauth_authorizations_list_grants import *
from .oauth_authorizations_update_authorization import *
from .orgs_check_membership_for_user import *
from .orgs_check_public_membership_for_user import *
from .orgs_convert_member_to_outside_collaborator import *
from .orgs_create_webhook import *
from .orgs_delete_webhook import *
from .orgs_get import *
from .orgs_get_membership_for_authenticated_user import *
from .orgs_get_membership_for_user import *
from .orgs_get_webhook import *
from .orgs_list import *
from .orgs_list_app_installations import *
from .orgs_list_for_authenticated_user import *
from .orgs_list_for_user import *
from .orgs_list_members import *
from .orgs_list_memberships_for_authenticated_user import *
from .orgs_list_outside_collaborators import *
from .orgs_list_public_members import *
from .orgs_list_webhooks import *
from .orgs_ping_webhook import *
from .orgs_remove_member import *
from .orgs_remove_membership_for_user import *
from .orgs_remove_outside_collaborator import *
from .orgs_remove_public_membership_for_authenticated_user import *
from .orgs_set_membership_for_user import *
from .orgs_set_public_membership_for_authenticated_user import *
from .orgs_update import *
from .orgs_update_membership_for_authenticated_user import *
from .orgs_update_webhook import *
from .projects_add_collaborator import *
from .projects_create_card import *
from .projects_create_column import *
from .projects_create_for_authenticated_user import *
from .projects_create_for_org import *
from .projects_create_for_repo import *
from .projects_delete import *
from .projects_delete_card import *
from .projects_delete_column import *
from .projects_get import *
from .projects_get_card import *
from .projects_get_column import *
from .projects_get_permission_for_user import *
from .projects_list_cards import *
from .projects_list_collaborators import *
from .projects_list_columns import *
from .projects_list_for_org import *
from .projects_list_for_repo import *
from .projects_list_for_user import *
from .projects_move_card import *
from .projects_move_column import *
from .projects_remove_collaborator import *
from .projects_update import *
from .projects_update_card import *
from .projects_update_column import *
from .pulls_check_if_merged import *
from .pulls_create import *
from .pulls_create_reply_for_review_comment import *
from .pulls_create_review import *
from .pulls_create_review_comment import *
from .pulls_delete_pending_review import *
from .pulls_delete_review_comment import *
from .pulls_dismiss_review import *
from .pulls_get import *
from .pulls_get_review import *
from .pulls_get_review_comment import *
from .pulls_list import *
from .pulls_list_comments_for_review import *
from .pulls_list_commits import *
from .pulls_list_files import *
from .pulls_list_requested_reviewers import *
from .pulls_list_review_comments import *
from .pulls_list_review_comments_for_repo import *
from .pulls_list_reviews import *
from .pulls_merge import *
from .pulls_remove_requested_reviewers import *
from .pulls_request_reviewers import *
from .pulls_submit_review import *
from .pulls_update import *
from .pulls_update_branch import *
from .pulls_update_review import *
from .pulls_update_review_comment import *
from .rate_limit_get import *
from .reactions_create_for_commit_comment import *
from .reactions_create_for_issue import *
from .reactions_create_for_issue_comment import *
from .reactions_create_for_pull_request_review_comment import *
from .reactions_create_for_team_discussion_comment_in_org import *
from .reactions_create_for_team_discussion_comment_legacy import *
from .reactions_create_for_team_discussion_in_org import *
from .reactions_create_for_team_discussion_legacy import *
from .reactions_delete_for_commit_comment import *
from .reactions_delete_for_issue import *
from .reactions_delete_for_issue_comment import *
from .reactions_delete_for_pull_request_comment import *
from .reactions_delete_for_team_discussion import *
from .reactions_delete_for_team_discussion_comment import *
from .reactions_delete_legacy import *
from .reactions_list_for_commit_comment import *
from .reactions_list_for_issue import *
from .reactions_list_for_issue_comment import *
from .reactions_list_for_pull_request_review_comment import *
from .reactions_list_for_team_discussion_comment_in_org import *
from .reactions_list_for_team_discussion_comment_legacy import *
from .reactions_list_for_team_discussion_in_org import *
from .reactions_list_for_team_discussion_legacy import *
from .repos_accept_invitation import *
from .repos_add_app_access_restrictions import *
from .repos_add_collaborator import *
from .repos_add_status_check_contexts import *
from .repos_add_team_access_restrictions import *
from .repos_add_user_access_restrictions import *
from .repos_check_collaborator import *
from .repos_compare_commits import *
from .repos_create_commit_comment import *
from .repos_create_commit_signature_protection import *
from .repos_create_commit_status import *
from .repos_create_deploy_key import *
from .repos_create_deployment import *
from .repos_create_deployment_status import *
from .repos_create_dispatch_event import *
from .repos_create_for_authenticated_user import *
from .repos_create_fork import *
from .repos_create_in_org import *
from .repos_create_or_update_file_contents import *
from .repos_create_pages_site import *
from .repos_create_release import *
from .repos_create_using_template import *
from .repos_create_webhook import *
from .repos_decline_invitation import *
from .repos_delete import *
from .repos_delete_access_restrictions import *
from .repos_delete_admin_branch_protection import *
from .repos_delete_branch_protection import *
from .repos_delete_commit_comment import *
from .repos_delete_commit_signature_protection import *
from .repos_delete_deploy_key import *
from .repos_delete_deployment import *
from .repos_delete_file import *
from .repos_delete_invitation import *
from .repos_delete_pages_site import *
from .repos_delete_pull_request_review_protection import *
from .repos_delete_release import *
from .repos_delete_release_asset import *
from .repos_delete_webhook import *
from .repos_download_tarball_archive import *
from .repos_download_zipball_archive import *
from .repos_get import *
from .repos_get_access_restrictions import *
from .repos_get_admin_branch_protection import *
from .repos_get_all_status_check_contexts import *
from .repos_get_all_topics import *
from .repos_get_apps_with_access_to_protected_branch import *
from .repos_get_branch import *
from .repos_get_branch_protection import *
from .repos_get_code_frequency_stats import *
from .repos_get_collaborator_permission_level import *
from .repos_get_combined_status_for_ref import *
from .repos_get_commit import *
from .repos_get_commit_activity_stats import *
from .repos_get_commit_comment import *
from .repos_get_commit_signature_protection import *
from .repos_get_content import *
from .repos_get_contributors_stats import *
from .repos_get_deploy_key import *
from .repos_get_deployment import *
from .repos_get_deployment_status import *
from .repos_get_latest_pages_build import *
from .repos_get_latest_release import *
from .repos_get_pages import *
from .repos_get_pages_build import *
from .repos_get_participation_stats import *
from .repos_get_pull_request_review_protection import *
from .repos_get_punch_card_stats import *
from .repos_get_readme import *
from .repos_get_readme_in_directory import *
from .repos_get_release import *
from .repos_get_release_asset import *
from .repos_get_release_by_tag import *
from .repos_get_status_checks_protection import *
from .repos_get_teams_with_access_to_protected_branch import *
from .repos_get_users_with_access_to_protected_branch import *
from .repos_get_webhook import *
from .repos_list_branches import *
from .repos_list_branches_for_head_commit import *
from .repos_list_collaborators import *
from .repos_list_comments_for_commit import *
from .repos_list_commit_comments_for_repo import *
from .repos_list_commit_statuses_for_ref import *
from .repos_list_commits import *
from .repos_list_contributors import *
from .repos_list_deploy_keys import *
from .repos_list_deployment_statuses import *
from .repos_list_deployments import *
from .repos_list_for_authenticated_user import *
from .repos_list_for_org import *
from .repos_list_for_user import *
from .repos_list_forks import *
from .repos_list_invitations import *
from .repos_list_invitations_for_authenticated_user import *
from .repos_list_languages import *
from .repos_list_pages_builds import *
from .repos_list_public import *
from .repos_list_pull_requests_associated_with_commit import *
from .repos_list_release_assets import *
from .repos_list_releases import *
from .repos_list_tags import *
from .repos_list_teams import *
from .repos_list_webhooks import *
from .repos_merge import *
from .repos_ping_webhook import *
from .repos_remove_app_access_restrictions import *
from .repos_remove_collaborator import *
from .repos_remove_status_check_contexts import *
from .repos_remove_status_check_protection import *
from .repos_remove_team_access_restrictions import *
from .repos_remove_user_access_restrictions import *
from .repos_replace_all_topics import *
from .repos_request_pages_build import *
from .repos_set_admin_branch_protection import *
from .repos_set_app_access_restrictions import *
from .repos_set_status_check_contexts import *
from .repos_set_team_access_restrictions import *
from .repos_set_user_access_restrictions import *
from .repos_test_push_webhook import *
from .repos_transfer import *
from .repos_update import *
from .repos_update_branch_protection import *
from .repos_update_commit_comment import *
from .repos_update_information_about_pages_site import *
from .repos_update_invitation import *
from .repos_update_pull_request_review_protection import *
from .repos_update_release import *
from .repos_update_release_asset import *
from .repos_update_status_check_protection import *
from .repos_update_webhook import *
from .repos_upload_release_asset import *
from .search_code import *
from .search_commits import *
from .search_issues_and_pull_requests import *
from .search_labels import *
from .search_repos import *
from .search_topics import *
from .search_users import *
from .teams_add_member_legacy import *
from .teams_add_or_update_membership_for_user_in_org import *
from .teams_add_or_update_membership_for_user_legacy import *
from .teams_add_or_update_project_permissions_in_org import *
from .teams_add_or_update_project_permissions_legacy import *
from .teams_add_or_update_repo_permissions_in_org import *
from .teams_add_or_update_repo_permissions_legacy import *
from .teams_check_permissions_for_project_in_org import *
from .teams_check_permissions_for_project_legacy import *
from .teams_check_permissions_for_repo_in_org import *
from .teams_check_permissions_for_repo_legacy import *
from .teams_create import *
from .teams_create_discussion_comment_in_org import *
from .teams_create_discussion_comment_legacy import *
from .teams_create_discussion_in_org import *
from .teams_create_discussion_legacy import *
from .teams_delete_discussion_comment_in_org import *
from .teams_delete_discussion_comment_legacy import *
from .teams_delete_discussion_in_org import *
from .teams_delete_discussion_legacy import *
from .teams_delete_in_org import *
from .teams_delete_legacy import *
from .teams_get_by_name import *
from .teams_get_discussion_comment_in_org import *
from .teams_get_discussion_comment_legacy import *
from .teams_get_discussion_in_org import *
from .teams_get_discussion_legacy import *
from .teams_get_legacy import *
from .teams_get_member_legacy import *
from .teams_get_membership_for_user_in_org import *
from .teams_get_membership_for_user_legacy import *
from .teams_list import *
from .teams_list_child_in_org import *
from .teams_list_child_legacy import *
from .teams_list_discussion_comments_in_org import *
from .teams_list_discussion_comments_legacy import *
from .teams_list_discussions_in_org import *
from .teams_list_discussions_legacy import *
from .teams_list_for_authenticated_user import *
from .teams_list_members_in_org import *
from .teams_list_members_legacy import *
from .teams_list_projects_in_org import *
from .teams_list_projects_legacy import *
from .teams_list_repos_in_org import *
from .teams_list_repos_legacy import *
from .teams_remove_member_legacy import *
from .teams_remove_membership_for_user_in_org import *
from .teams_remove_membership_for_user_legacy import *
from .teams_remove_project_in_org import *
from .teams_remove_project_legacy import *
from .teams_remove_repo_in_org import *
from .teams_remove_repo_legacy import *
from .teams_update_discussion_comment_in_org import *
from .teams_update_discussion_comment_legacy import *
from .teams_update_discussion_in_org import *
from .teams_update_discussion_legacy import *
from .teams_update_in_org import *
from .teams_update_legacy import *
from .users_add_email_for_authenticated import *
from .users_check_following_for_user import *
from .users_check_person_is_followed_by_authenticated import *
from .users_create_gpg_key_for_authenticated import *
from .users_create_public_ssh_key_for_authenticated import *
from .users_delete_email_for_authenticated import *
from .users_delete_gpg_key_for_authenticated import *
from .users_delete_public_ssh_key_for_authenticated import *
from .users_follow import *
from .users_get_authenticated import *
from .users_get_by_username import *
from .users_get_context_for_user import *
from .users_get_gpg_key_for_authenticated import *
from .users_get_public_ssh_key_for_authenticated import *
from .users_list import *
from .users_list_emails_for_authenticated import *
from .users_list_followed_by_authenticated import *
from .users_list_followers_for_authenticated_user import *
from .users_list_followers_for_user import *
from .users_list_following_for_user import *
from .users_list_gpg_keys_for_authenticated import *
from .users_list_gpg_keys_for_user import *
from .users_list_public_emails_for_authenticated import *
from .users_list_public_keys_for_user import *
from .users_list_public_ssh_keys_for_authenticated import *
from .users_unfollow import *
from .users_update_authenticated import *
