# coding: utf-8

# flake8: noqa
"""
    Feed API

    <p>The <strong>Feed API</strong> lets sellers upload input files, download reports and files including their status, filter reports using URI parameters, and retrieve customer service metrics task details.</p>

    The version of the OpenAPI document: v1.3.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.create_inventory_task_request import CreateInventoryTaskRequest
from openapi_client.models.create_order_task_request import CreateOrderTaskRequest
from openapi_client.models.create_service_metrics_task_request import CreateServiceMetricsTaskRequest
from openapi_client.models.create_task_request import CreateTaskRequest
from openapi_client.models.create_user_schedule_request import CreateUserScheduleRequest
from openapi_client.models.customer_service_metric_task_collection import CustomerServiceMetricTaskCollection
from openapi_client.models.customer_service_metrics_filter_criteria import CustomerServiceMetricsFilterCriteria
from openapi_client.models.date_range import DateRange
from openapi_client.models.error import Error
from openapi_client.models.error_parameter import ErrorParameter
from openapi_client.models.inventory_filter_criteria import InventoryFilterCriteria
from openapi_client.models.inventory_task import InventoryTask
from openapi_client.models.inventory_task_collection import InventoryTaskCollection
from openapi_client.models.order_filter_criteria import OrderFilterCriteria
from openapi_client.models.order_task import OrderTask
from openapi_client.models.order_task_collection import OrderTaskCollection
from openapi_client.models.schedule_template_collection import ScheduleTemplateCollection
from openapi_client.models.schedule_template_response import ScheduleTemplateResponse
from openapi_client.models.service_metrics_task import ServiceMetricsTask
from openapi_client.models.supported_configuration import SupportedConfiguration
from openapi_client.models.task import Task
from openapi_client.models.task_collection import TaskCollection
from openapi_client.models.update_user_schedule_request import UpdateUserScheduleRequest
from openapi_client.models.upload_summary import UploadSummary
from openapi_client.models.user_schedule_collection import UserScheduleCollection
from openapi_client.models.user_schedule_response import UserScheduleResponse
