from dataclasses import dataclass, field
from typing import Enum,Optional
from sdk.models import shared
CREATE_STREAM_SERVERS = [
	"https://api.twilio.com",
]


@dataclass
class CreateStreamPathParams:
    account_sid: str = field(default=None, metadata={'path_param': { 'field_name': 'AccountSid', 'style': 'simple', 'explode': False }})
    call_sid: str = field(default=None, metadata={'path_param': { 'field_name': 'CallSid', 'style': 'simple', 'explode': False }})
    
class CreateStreamCreateStreamRequestStatusCallbackMethodEnum(str, Enum):
    HEAD = "HEAD"
    GET = "GET"
    POST = "POST"
    PATCH = "PATCH"
    PUT = "PUT"
    DELETE = "DELETE"


@dataclass
class CreateStreamCreateStreamRequest:
    name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Name' }})
    parameter1_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter1.Name' }})
    parameter1_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter1.Value' }})
    parameter10_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter10.Name' }})
    parameter10_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter10.Value' }})
    parameter11_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter11.Name' }})
    parameter11_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter11.Value' }})
    parameter12_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter12.Name' }})
    parameter12_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter12.Value' }})
    parameter13_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter13.Name' }})
    parameter13_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter13.Value' }})
    parameter14_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter14.Name' }})
    parameter14_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter14.Value' }})
    parameter15_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter15.Name' }})
    parameter15_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter15.Value' }})
    parameter16_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter16.Name' }})
    parameter16_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter16.Value' }})
    parameter17_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter17.Name' }})
    parameter17_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter17.Value' }})
    parameter18_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter18.Name' }})
    parameter18_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter18.Value' }})
    parameter19_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter19.Name' }})
    parameter19_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter19.Value' }})
    parameter2_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter2.Name' }})
    parameter2_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter2.Value' }})
    parameter20_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter20.Name' }})
    parameter20_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter20.Value' }})
    parameter21_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter21.Name' }})
    parameter21_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter21.Value' }})
    parameter22_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter22.Name' }})
    parameter22_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter22.Value' }})
    parameter23_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter23.Name' }})
    parameter23_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter23.Value' }})
    parameter24_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter24.Name' }})
    parameter24_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter24.Value' }})
    parameter25_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter25.Name' }})
    parameter25_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter25.Value' }})
    parameter26_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter26.Name' }})
    parameter26_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter26.Value' }})
    parameter27_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter27.Name' }})
    parameter27_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter27.Value' }})
    parameter28_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter28.Name' }})
    parameter28_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter28.Value' }})
    parameter29_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter29.Name' }})
    parameter29_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter29.Value' }})
    parameter3_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter3.Name' }})
    parameter3_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter3.Value' }})
    parameter30_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter30.Name' }})
    parameter30_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter30.Value' }})
    parameter31_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter31.Name' }})
    parameter31_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter31.Value' }})
    parameter32_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter32.Name' }})
    parameter32_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter32.Value' }})
    parameter33_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter33.Name' }})
    parameter33_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter33.Value' }})
    parameter34_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter34.Name' }})
    parameter34_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter34.Value' }})
    parameter35_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter35.Name' }})
    parameter35_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter35.Value' }})
    parameter36_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter36.Name' }})
    parameter36_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter36.Value' }})
    parameter37_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter37.Name' }})
    parameter37_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter37.Value' }})
    parameter38_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter38.Name' }})
    parameter38_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter38.Value' }})
    parameter39_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter39.Name' }})
    parameter39_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter39.Value' }})
    parameter4_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter4.Name' }})
    parameter4_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter4.Value' }})
    parameter40_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter40.Name' }})
    parameter40_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter40.Value' }})
    parameter41_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter41.Name' }})
    parameter41_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter41.Value' }})
    parameter42_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter42.Name' }})
    parameter42_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter42.Value' }})
    parameter43_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter43.Name' }})
    parameter43_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter43.Value' }})
    parameter44_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter44.Name' }})
    parameter44_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter44.Value' }})
    parameter45_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter45.Name' }})
    parameter45_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter45.Value' }})
    parameter46_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter46.Name' }})
    parameter46_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter46.Value' }})
    parameter47_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter47.Name' }})
    parameter47_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter47.Value' }})
    parameter48_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter48.Name' }})
    parameter48_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter48.Value' }})
    parameter49_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter49.Name' }})
    parameter49_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter49.Value' }})
    parameter5_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter5.Name' }})
    parameter5_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter5.Value' }})
    parameter50_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter50.Name' }})
    parameter50_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter50.Value' }})
    parameter51_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter51.Name' }})
    parameter51_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter51.Value' }})
    parameter52_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter52.Name' }})
    parameter52_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter52.Value' }})
    parameter53_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter53.Name' }})
    parameter53_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter53.Value' }})
    parameter54_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter54.Name' }})
    parameter54_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter54.Value' }})
    parameter55_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter55.Name' }})
    parameter55_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter55.Value' }})
    parameter56_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter56.Name' }})
    parameter56_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter56.Value' }})
    parameter57_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter57.Name' }})
    parameter57_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter57.Value' }})
    parameter58_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter58.Name' }})
    parameter58_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter58.Value' }})
    parameter59_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter59.Name' }})
    parameter59_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter59.Value' }})
    parameter6_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter6.Name' }})
    parameter6_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter6.Value' }})
    parameter60_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter60.Name' }})
    parameter60_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter60.Value' }})
    parameter61_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter61.Name' }})
    parameter61_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter61.Value' }})
    parameter62_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter62.Name' }})
    parameter62_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter62.Value' }})
    parameter63_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter63.Name' }})
    parameter63_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter63.Value' }})
    parameter64_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter64.Name' }})
    parameter64_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter64.Value' }})
    parameter65_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter65.Name' }})
    parameter65_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter65.Value' }})
    parameter66_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter66.Name' }})
    parameter66_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter66.Value' }})
    parameter67_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter67.Name' }})
    parameter67_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter67.Value' }})
    parameter68_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter68.Name' }})
    parameter68_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter68.Value' }})
    parameter69_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter69.Name' }})
    parameter69_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter69.Value' }})
    parameter7_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter7.Name' }})
    parameter7_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter7.Value' }})
    parameter70_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter70.Name' }})
    parameter70_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter70.Value' }})
    parameter71_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter71.Name' }})
    parameter71_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter71.Value' }})
    parameter72_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter72.Name' }})
    parameter72_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter72.Value' }})
    parameter73_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter73.Name' }})
    parameter73_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter73.Value' }})
    parameter74_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter74.Name' }})
    parameter74_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter74.Value' }})
    parameter75_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter75.Name' }})
    parameter75_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter75.Value' }})
    parameter76_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter76.Name' }})
    parameter76_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter76.Value' }})
    parameter77_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter77.Name' }})
    parameter77_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter77.Value' }})
    parameter78_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter78.Name' }})
    parameter78_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter78.Value' }})
    parameter79_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter79.Name' }})
    parameter79_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter79.Value' }})
    parameter8_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter8.Name' }})
    parameter8_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter8.Value' }})
    parameter80_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter80.Name' }})
    parameter80_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter80.Value' }})
    parameter81_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter81.Name' }})
    parameter81_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter81.Value' }})
    parameter82_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter82.Name' }})
    parameter82_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter82.Value' }})
    parameter83_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter83.Name' }})
    parameter83_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter83.Value' }})
    parameter84_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter84.Name' }})
    parameter84_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter84.Value' }})
    parameter85_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter85.Name' }})
    parameter85_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter85.Value' }})
    parameter86_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter86.Name' }})
    parameter86_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter86.Value' }})
    parameter87_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter87.Name' }})
    parameter87_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter87.Value' }})
    parameter88_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter88.Name' }})
    parameter88_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter88.Value' }})
    parameter89_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter89.Name' }})
    parameter89_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter89.Value' }})
    parameter9_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter9.Name' }})
    parameter9_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter9.Value' }})
    parameter90_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter90.Name' }})
    parameter90_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter90.Value' }})
    parameter91_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter91.Name' }})
    parameter91_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter91.Value' }})
    parameter92_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter92.Name' }})
    parameter92_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter92.Value' }})
    parameter93_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter93.Name' }})
    parameter93_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter93.Value' }})
    parameter94_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter94.Name' }})
    parameter94_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter94.Value' }})
    parameter95_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter95.Name' }})
    parameter95_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter95.Value' }})
    parameter96_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter96.Name' }})
    parameter96_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter96.Value' }})
    parameter97_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter97.Name' }})
    parameter97_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter97.Value' }})
    parameter98_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter98.Name' }})
    parameter98_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter98.Value' }})
    parameter99_name: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter99.Name' }})
    parameter99_value: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'Parameter99.Value' }})
    status_callback: Optional[str] = field(default=None, metadata={'form': { 'field_name': 'StatusCallback' }})
    status_callback_method: Optional[CreateStreamCreateStreamRequestStatusCallbackMethodEnum] = field(default=None, metadata={'form': { 'field_name': 'StatusCallbackMethod' }})
    track: Optional[shared.StreamEnumTrackEnum] = field(default=None, metadata={'form': { 'field_name': 'Track' }})
    url: str = field(default=None, metadata={'form': { 'field_name': 'Url' }})
    

@dataclass
class CreateStreamSecurity:
    account_sid_auth_token: shared.SchemeAccountSidAuthToken = field(default=None, metadata={'security': { 'scheme': True, 'type': 'http', 'sub_type': 'basic' }})
    

@dataclass
class CreateStreamRequest:
    server_url: Optional[str] = field(default=None)
    path_params: CreateStreamPathParams = field(default=None)
    request: Optional[CreateStreamCreateStreamRequest] = field(default=None, metadata={'request': { 'media_type': 'application/x-www-form-urlencoded' }})
    security: CreateStreamSecurity = field(default=None)
    

@dataclass
class CreateStreamResponse:
    content_type: str = field(default=None)
    status_code: int = field(default=None)
    api_v2010_account_call_stream: Optional[shared.APIV2010AccountCallStream] = field(default=None)
    
