package shared




type IncomingPhoneNumberTollFreeEnumEmergencyAddressStatusEnum string

const (
    IncomingPhoneNumberTollFreeEnumEmergencyAddressStatusEnumRegistered IncomingPhoneNumberTollFreeEnumEmergencyAddressStatusEnum = "registered"
IncomingPhoneNumberTollFreeEnumEmergencyAddressStatusEnumUnregistered IncomingPhoneNumberTollFreeEnumEmergencyAddressStatusEnum = "unregistered"
IncomingPhoneNumberTollFreeEnumEmergencyAddressStatusEnumPendingRegistration IncomingPhoneNumberTollFreeEnumEmergencyAddressStatusEnum = "pending-registration"
IncomingPhoneNumberTollFreeEnumEmergencyAddressStatusEnumRegistrationFailure IncomingPhoneNumberTollFreeEnumEmergencyAddressStatusEnum = "registration-failure"
IncomingPhoneNumberTollFreeEnumEmergencyAddressStatusEnumPendingUnregistration IncomingPhoneNumberTollFreeEnumEmergencyAddressStatusEnum = "pending-unregistration"
IncomingPhoneNumberTollFreeEnumEmergencyAddressStatusEnumUnregistrationFailure IncomingPhoneNumberTollFreeEnumEmergencyAddressStatusEnum = "unregistration-failure"
)


