openapi: 3.0.0
servers:
  - url: https://games.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: The Google Play games service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Google Play Game Services
  version: v1
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png
  x-origin:
    - format: google
      url: https://games.googleapis.com/$discovery/rest?version=v1
      version: v1
  x-providerName: googleapis.com
  x-serviceName: games
tags:
  - name: achievementDefinitions
  - name: achievements
  - name: applications
  - name: events
  - name: leaderboards
  - name: metagame
  - name: players
  - name: revisions
  - name: scores
  - name: snapshots
  - name: stats
paths:
  /games/v1/achievements:
    get:
      description: Lists all the achievement definitions for your application.
      operationId: games.achievementDefinitions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - achievementDefinitions
  /games/v1/achievements/updateMultiple:
    post:
      description: Updates multiple achievements for the currently authenticated player.
      operationId: games.achievements.updateMultiple
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - achievements
  "/games/v1/achievements/{achievementId}/increment":
    post:
      description: Increments the steps of the achievement with the given ID for the currently authenticated player.
      operationId: games.achievements.increment
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - achievements
  "/games/v1/achievements/{achievementId}/reveal":
    post:
      description: Sets the state of the achievement with the given ID to `REVEALED` for the currently authenticated player.
      operationId: games.achievements.reveal
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - achievements
  "/games/v1/achievements/{achievementId}/setStepsAtLeast":
    post:
      description: Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified.
      operationId: games.achievements.setStepsAtLeast
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - achievements
  "/games/v1/achievements/{achievementId}/unlock":
    post:
      description: Unlocks this achievement for the currently authenticated player.
      operationId: games.achievements.unlock
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - achievements
  /games/v1/applications/getEndPoint:
    post:
      description: Returns a URL for the requested end point type.
      operationId: games.applications.getEndPoint
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - applications
  /games/v1/applications/played:
    post:
      description: Indicate that the currently authenticated user is playing your application.
      operationId: games.applications.played
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - applications
  "/games/v1/applications/{applicationId}":
    get:
      description: Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified `platformType`, the returned response will not include any instance data.
      operationId: games.applications.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - applications
  "/games/v1/applications/{applicationId}/verify":
    get:
      description: Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for.
      operationId: games.applications.verify
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - applications
  /games/v1/eventDefinitions:
    get:
      description: Returns a list of the event definitions in this application.
      operationId: games.events.listDefinitions
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - events
  /games/v1/events:
    get:
      description: Returns a list showing the current progress on events in this application for the currently authenticated user.
      operationId: games.events.listByPlayer
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - events
    post:
      description: Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application.
      operationId: games.events.record
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - events
  /games/v1/leaderboards:
    get:
      description: Lists all the leaderboard metadata for your application.
      operationId: games.leaderboards.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - leaderboards
  /games/v1/leaderboards/scores:
    post:
      description: Submits multiple scores to leaderboards.
      operationId: games.scores.submitMultiple
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - scores
  "/games/v1/leaderboards/{leaderboardId}":
    get:
      description: Retrieves the metadata of the leaderboard with the given ID.
      operationId: games.leaderboards.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - leaderboards
  "/games/v1/leaderboards/{leaderboardId}/scores":
    post:
      description: Submits a score to the specified leaderboard.
      operationId: games.scores.submit
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - scores
  "/games/v1/leaderboards/{leaderboardId}/scores/{collection}":
    get:
      description: Lists the scores in a leaderboard, starting from the top.
      operationId: games.scores.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - scores
  "/games/v1/leaderboards/{leaderboardId}/window/{collection}":
    get:
      description: Lists the scores in a leaderboard around (and including) a player's score.
      operationId: games.scores.listWindow
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - scores
  /games/v1/metagameConfig:
    get:
      description: Return the metagame configuration data for the calling application.
      operationId: games.metagame.getMetagameConfig
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - metagame
  /games/v1/players/me/multipleApplicationPlayerIds:
    get:
      description: Get the application player ids for the currently authenticated player across all requested games by the same developer as the calling application. This will only return ids for players that actually have an id (scoped or otherwise) with that game.
      operationId: games.players.getMultipleApplicationPlayerIds
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - players
  "/games/v1/players/me/players/{collection}":
    get:
      description: Get the collection of players for the currently authenticated user.
      operationId: games.players.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - players
  /games/v1/players/me/scopedIds:
    get:
      description: Retrieves scoped player identifiers for currently authenticated user.
      operationId: games.players.getScopedPlayerIds
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - players
  "/games/v1/players/{playerId}":
    get:
      description: Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set `playerId` to `me`.
      operationId: games.players.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - players
  "/games/v1/players/{playerId}/achievements":
    get:
      description: Lists the progress for all your application's achievements for the currently authenticated player.
      operationId: games.achievements.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - achievements
  "/games/v1/players/{playerId}/categories/{collection}":
    get:
      description: List play data aggregated per category for the player corresponding to `playerId`.
      operationId: games.metagame.listCategoriesByPlayer
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - metagame
  "/games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}":
    get:
      description: "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, `leaderboardId` can be set to `ALL` to retrieve data for all leaderboards in a given time span. `NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'."
      operationId: games.scores.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - scores
  "/games/v1/players/{playerId}/snapshots":
    get:
      description: Retrieves a list of snapshots created by your application for the player corresponding to the player ID.
      operationId: games.snapshots.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - snapshots
  /games/v1/revisions/check:
    get:
      description: Checks whether the games client is out of date.
      operationId: games.revisions.check
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - revisions
  "/games/v1/snapshots/{snapshotId}":
    get:
      description: Retrieves the metadata for a given snapshot ID.
      operationId: games.snapshots.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/drive.appdata
          Oauth2c:
            - https://www.googleapis.com/auth/drive.appdata
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - snapshots
  /games/v1/stats:
    get:
      description: Returns engagement and spend statistics in this application for the currently authenticated user.
      operationId: games.stats.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/games
          Oauth2c:
            - https://www.googleapis.com/auth/games
      tags:
        - stats
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/drive.appdata: See, create, and delete its own configuration data in your Google Drive
            https://www.googleapis.com/auth/games: Create, edit, and delete your Google Play Games activity
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/drive.appdata: See, create, and delete its own configuration data in your Google Drive
            https://www.googleapis.com/auth/games: Create, edit, and delete your Google Play Games activity
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
