openapi: 3.0.0
servers:
  - url: 'https://cloudidentity.googleapis.com/'
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: API for provisioning and managing identity resources.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Cloud Identity
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.7.31
      format: google
      url: 'https://cloudidentity.googleapis.com/$discovery/rest?version=v1'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: cloudidentity
tags:
  - name: groups
paths:
  /v1/groups:
    get:
      description: Lists groups within a customer or a domain.
      operationId: cloudidentity.groups.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-identity.groups'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-identity.groups'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-identity.groups.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-identity.groups.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - groups
    post:
      description: Creates a Group.
      operationId: cloudidentity.groups.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-identity.groups'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-identity.groups'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - groups
  '/v1/groups:lookup':
    get:
      description: |-
        Looks up [resource
        name](https://cloud.google.com/apis/design/resource_names) of a Group by
        its EntityKey.
      operationId: cloudidentity.groups.lookup
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-identity.groups'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-identity.groups'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-identity.groups.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-identity.groups.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - groups
  '/v1/groups:search':
    get:
      description: Searches for Groups.
      operationId: cloudidentity.groups.search
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-identity.groups'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-identity.groups'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-identity.groups.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-identity.groups.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - groups
  '/v1/{name}':
    delete:
      description: Deletes a Membership.
      operationId: cloudidentity.groups.memberships.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-identity.groups'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-identity.groups'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - groups
    get:
      description: Retrieves a Membership.
      operationId: cloudidentity.groups.memberships.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-identity.groups'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-identity.groups'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-identity.groups.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-identity.groups.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - groups
    patch:
      description: Updates a Group.
      operationId: cloudidentity.groups.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-identity.groups'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-identity.groups'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - groups
  '/v1/{parent}/memberships':
    get:
      description: Lists Memberships within a Group.
      operationId: cloudidentity.groups.memberships.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-identity.groups'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-identity.groups'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-identity.groups.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-identity.groups.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - groups
    post:
      description: Creates a Membership.
      operationId: cloudidentity.groups.memberships.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-identity.groups'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-identity.groups'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - groups
  '/v1/{parent}/memberships:lookup':
    get:
      description: |-
        Looks up [resource
        name](https://cloud.google.com/apis/design/resource_names) of a Membership
        within a Group by member's EntityKey.
      operationId: cloudidentity.groups.memberships.lookup
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-identity.groups'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-identity.groups'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-identity.groups.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-identity.groups.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
      tags:
        - groups
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
          scopes:
            'https://www.googleapis.com/auth/cloud-identity.groups': 'See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group'
            'https://www.googleapis.com/auth/cloud-identity.groups.readonly': 'See any Cloud Identity Groups that you can access, including group members and their emails'
            'https://www.googleapis.com/auth/cloud-platform': View and manage your data across Google Cloud Platform services
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 accessCode authentication
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
          scopes:
            'https://www.googleapis.com/auth/cloud-identity.groups': 'See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group'
            'https://www.googleapis.com/auth/cloud-identity.groups.readonly': 'See any Cloud Identity Groups that you can access, including group members and their emails'
            'https://www.googleapis.com/auth/cloud-platform': View and manage your data across Google Cloud Platform services
          tokenUrl: 'https://accounts.google.com/o/oauth2/token'
      type: oauth2
