# coding: utf-8

"""
    Cloud Dataproc API

    Manages Hadoop-based clusters and jobs on Google Cloud Platform.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.node_pool import NodePool

class TestNodePool(unittest.TestCase):
    """NodePool unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodePool:
        """Test NodePool
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodePool`
        """
        model = NodePool()
        if include_optional:
            return NodePool(
                id = '',
                instance_names = [
                    ''
                    ],
                repair_action = 'REPAIR_ACTION_UNSPECIFIED'
            )
        else:
            return NodePool(
        )
        """

    def testNodePool(self):
        """Test NodePool"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
