{
  "swagger": "2.0",
  "info": {
    "title": "Google Site Verification API",
    "description": "Lets you programatically verify ownership of websites or domains with Google.",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v1"
  },
  "host": "www.googleapis.com",
  "basePath": "/siteVerification/v1",
  "schemes": [
    "https"
  ],
  "paths": {
    "/webResource/{id}": {
      "delete": {
        "description": "Relinquish ownership of a website or domain.",
        "operationId": "siteVerification.webResource.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/siteverification"
            ]
          }
        ],
        "tags": [
          "webResource"
        ]
      },
      "get": {
        "description": "Get the most current data for a website or domain.",
        "operationId": "siteVerification.webResource.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/siteverification"
            ]
          }
        ],
        "tags": [
          "webResource"
        ]
      },
      "patch": {
        "description": "Modify the list of owners for your website or domain. This method supports patch semantics.",
        "operationId": "siteVerification.webResource.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/siteverification"
            ]
          }
        ],
        "tags": [
          "webResource"
        ]
      },
      "put": {
        "description": "Modify the list of owners for your website or domain.",
        "operationId": "siteVerification.webResource.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/siteverification"
            ]
          }
        ],
        "tags": [
          "webResource"
        ]
      }
    },
    "/token": {
      "post": {
        "description": "Get a verification token for placing on a website or domain.",
        "operationId": "siteVerification.webResource.getToken",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/siteverification",
              "https://www.googleapis.com/auth/siteverification.verify_only"
            ]
          }
        ],
        "tags": [
          "webResource"
        ]
      }
    },
    "/webResource": {
      "post": {
        "description": "Attempt verification of a website or domain.",
        "operationId": "siteVerification.webResource.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/siteverification",
              "https://www.googleapis.com/auth/siteverification.verify_only"
            ]
          }
        ],
        "tags": [
          "webResource"
        ]
      },
      "get": {
        "description": "Get the list of your verified websites and domains.",
        "operationId": "siteVerification.webResource.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/siteverification"
            ]
          }
        ],
        "tags": [
          "webResource"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/siteverification": "Manage the list of sites and domains you control",
        "https://www.googleapis.com/auth/siteverification.verify_only": "Manage your new site verifications with Google"
      }
    }
  }
}