# coding: utf-8

"""
    SchedulerManagementClient

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2016-01-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.http_authentication import HttpAuthentication

class TestHttpAuthentication(unittest.TestCase):
    """HttpAuthentication unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HttpAuthentication:
        """Test HttpAuthentication
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HttpAuthentication`
        """
        model = HttpAuthentication()
        if include_optional:
            return HttpAuthentication(
                type = 'NotSpecified'
            )
        else:
            return HttpAuthentication(
        )
        """

    def testHttpAuthentication(self):
        """Test HttpAuthentication"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
