from dataclasses import dataclass, field
from typing import Enum

class TargetTypeEnum(str, Enum):
    GATEWAY = "GATEWAY"
    CARRIER_GATEWAY = "CARRIER_GATEWAY"
    INSTANCE = "INSTANCE"
    LOCAL_GATEWAY = "LOCAL_GATEWAY"
    NAT_GATEWAY = "NAT_GATEWAY"
    NETWORK_INTERFACE = "NETWORK_INTERFACE"
    VPC_ENDPOINT = "VPC_ENDPOINT"
    VPC_PEERING_CONNECTION = "VPC_PEERING_CONNECTION"
    EGRESS_ONLY_INTERNET_GATEWAY = "EGRESS_ONLY_INTERNET_GATEWAY"
    TRANSIT_GATEWAY = "TRANSIT_GATEWAY"

