swagger: '2.0'
schemes:
  - https
host: script.googleapis.com
basePath: /
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: |
    Manages and executes Google Apps Script projects.
  title: Apps Script
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-apisguru-categories:
    - cloud
  x-logo:
    url: 'https://www.gstatic.com/images/icons/material/product/2x/apps_script_64dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.7.18
      format: google
      url: 'https://script.googleapis.com/$discovery/rest?version=v1'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: script
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 authentication
    flow: implicit
    scopes:
      'https://mail.google.com/': 'Read, compose, send, and permanently delete all your email from Gmail'
      'https://www.google.com/calendar/feeds': 'See, edit, share, and permanently delete all the calendars you can access using Google Calendar'
      'https://www.google.com/m8/feeds': 'See, edit, download, and permanently delete your contacts'
      'https://www.googleapis.com/auth/admin.directory.group': View and manage the provisioning of groups on your domain
      'https://www.googleapis.com/auth/admin.directory.user': View and manage the provisioning of users on your domain
      'https://www.googleapis.com/auth/documents': View and manage your Google Docs documents
      'https://www.googleapis.com/auth/drive': 'See, edit, create, and delete all of your Google Drive files'
      'https://www.googleapis.com/auth/forms': View and manage your forms in Google Drive
      'https://www.googleapis.com/auth/forms.currentonly': View and manage forms that this application has been installed in
      'https://www.googleapis.com/auth/groups': View and manage your Google Groups
      'https://www.googleapis.com/auth/script.deployments': Create and update Google Apps Script deployments
      'https://www.googleapis.com/auth/script.deployments.readonly': View Google Apps Script deployments
      'https://www.googleapis.com/auth/script.metrics': View Google Apps Script project's metrics
      'https://www.googleapis.com/auth/script.processes': View Google Apps Script processes
      'https://www.googleapis.com/auth/script.projects': Create and update Google Apps Script projects
      'https://www.googleapis.com/auth/script.projects.readonly': View Google Apps Script projects
      'https://www.googleapis.com/auth/spreadsheets': 'See, edit, create, and delete your spreadsheets in Google Drive'
      'https://www.googleapis.com/auth/userinfo.email': View your email address
    type: oauth2
tags:
  - name: processes
  - name: projects
  - name: scripts
paths:
  /v1/processes:
    get:
      description: |-
        List information about processes made by or on behalf of a user,
        such as process type and current status.
      operationId: script.processes.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.processes'
      tags:
        - processes
  '/v1/processes:listScriptProcesses':
    get:
      description: |-
        List information about a script's executed processes, such as process type
        and current status.
      operationId: script.processes.listScriptProcesses
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.processes'
      tags:
        - processes
  /v1/projects:
    post:
      description: |-
        Creates a new, empty script project with no script files and a base
        manifest file.
      operationId: script.projects.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.projects'
      tags:
        - projects
  '/v1/projects/{scriptId}':
    get:
      description: Gets a script project's metadata.
      operationId: script.projects.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.projects'
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.projects.readonly'
      tags:
        - projects
  '/v1/projects/{scriptId}/content':
    get:
      description: |-
        Gets the content of the script project, including the code source and
        metadata for each script file.
      operationId: script.projects.getContent
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.projects'
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.projects.readonly'
      tags:
        - projects
    put:
      description: |-
        Updates the content of the specified script project.
        This content is stored as the HEAD version, and is used when the script is
        executed as a trigger, in the script editor, in add-on preview mode, or as
        a web app or Apps Script API in development mode. This clears all the
        existing files in the project.
      operationId: script.projects.updateContent
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.projects'
      tags:
        - projects
  '/v1/projects/{scriptId}/deployments':
    get:
      description: Lists the deployments of an Apps Script project.
      operationId: script.projects.deployments.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.deployments'
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.deployments.readonly'
      tags:
        - projects
    post:
      description: Creates a deployment of an Apps Script project.
      operationId: script.projects.deployments.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.deployments'
      tags:
        - projects
  '/v1/projects/{scriptId}/deployments/{deploymentId}':
    delete:
      description: Deletes a deployment of an Apps Script project.
      operationId: script.projects.deployments.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.deployments'
      tags:
        - projects
    get:
      description: Gets a deployment of an Apps Script project.
      operationId: script.projects.deployments.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.deployments'
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.deployments.readonly'
      tags:
        - projects
    put:
      description: Updates a deployment of an Apps Script project.
      operationId: script.projects.deployments.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.deployments'
      tags:
        - projects
  '/v1/projects/{scriptId}/metrics':
    get:
      description: |-
        Get metrics data for scripts, such as number of executions and
        active users.
      operationId: script.projects.getMetrics
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.metrics'
      tags:
        - projects
  '/v1/projects/{scriptId}/versions':
    get:
      description: List the versions of a script project.
      operationId: script.projects.versions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.projects'
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.projects.readonly'
      tags:
        - projects
    post:
      description: |-
        Creates a new immutable version using the current code, with a unique
        version number.
      operationId: script.projects.versions.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.projects'
      tags:
        - projects
  '/v1/projects/{scriptId}/versions/{versionNumber}':
    get:
      description: Gets a version of a script project.
      operationId: script.projects.versions.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.projects'
        - Oauth2:
            - 'https://www.googleapis.com/auth/script.projects.readonly'
      tags:
        - projects
  '/v1/scripts/{scriptId}:run':
    post:
      description: |-
        Runs a function in an Apps Script project. The script project must be
        deployed for use with the Apps Script API and the calling application must
        share the same Cloud Platform project.

        This method requires authorization with an OAuth 2.0 token that includes at
        least one of the scopes listed in the [Authorization](#authorization)
        section; script projects that do not require authorization cannot be
        executed through this API. To find the correct scopes to include in the
        authentication token, open the project in the script editor, then select
        **File > Project properties** and click the **Scopes** tab.

        The error `403, PERMISSION_DENIED: The caller does not have permission`
        indicates that the Cloud Platform project used to authorize the request is
        not the same as the one used by the script.
      operationId: script.scripts.run
      security:
        - Oauth2:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.google.com/calendar/feeds'
        - Oauth2:
            - 'https://www.google.com/m8/feeds'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user'
        - Oauth2:
            - 'https://www.googleapis.com/auth/documents'
        - Oauth2:
            - 'https://www.googleapis.com/auth/drive'
        - Oauth2:
            - 'https://www.googleapis.com/auth/forms'
        - Oauth2:
            - 'https://www.googleapis.com/auth/forms.currentonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/groups'
        - Oauth2:
            - 'https://www.googleapis.com/auth/spreadsheets'
        - Oauth2:
            - 'https://www.googleapis.com/auth/userinfo.email'
      tags:
        - scripts