# coding: utf-8

"""
    NetworkManagementClient

    The Microsoft Azure Network management API provides a RESTful set of web services that interact with Microsoft Azure Networks service to manage your network resources. The API has entities that capture the relationship between an end user and the Microsoft Azure Networks service.

    The version of the OpenAPI document: 2019-06-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.firewall_policy_filter_rule_action_type import FirewallPolicyFilterRuleActionType

class TestFirewallPolicyFilterRuleActionType(unittest.TestCase):
    """FirewallPolicyFilterRuleActionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFirewallPolicyFilterRuleActionType(self):
        """Test FirewallPolicyFilterRuleActionType"""
        # inst = FirewallPolicyFilterRuleActionType()

if __name__ == '__main__':
    unittest.main()
