{
  "openapi": "3.0.0",
  "servers": [
    {
      "url": "https://admob.googleapis.com/"
    }
  ],
  "info": {
    "contact": {
      "name": "Google",
      "url": "https://google.com",
      "x-twitter": "youtube"
    },
    "description": "The AdMob API allows publishers to programmatically get information about their AdMob account. ",
    "license": {
      "name": "Creative Commons Attribution 3.0",
      "url": "http://creativecommons.org/licenses/by/3.0/"
    },
    "termsOfService": "https://developers.google.com/terms/",
    "title": "AdMob API",
    "version": "v1beta",
    "x-apiClientRegistration": {
      "url": "https://console.developers.google.com"
    },
    "x-apisguru-categories": [
      "analytics",
      "media"
    ],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png"
    },
    "x-origin": [
      {
        "format": "google",
        "url": "https://admob.googleapis.com/$discovery/rest?version=v1beta",
        "version": "v1"
      }
    ],
    "x-preferred": true,
    "x-providerName": "googleapis.com",
    "x-serviceName": "admob"
  },
  "tags": [
    {
      "name": "accounts"
    }
  ],
  "paths": {
    "/v1beta/accounts": {
      "get": {
        "description": "Lists the AdMob publisher account that was most recently signed in to from the AdMob UI. For more information, see https://support.google.com/admob/answer/10243672.",
        "operationId": "admob.accounts.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admob.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admob.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admob.report"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admob.report"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/v1beta/{name}": {
      "get": {
        "description": "Gets information about the specified AdMob publisher account.",
        "operationId": "admob.accounts.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admob.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admob.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admob.report"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admob.report"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/v1beta/{parent}/adSources": {
      "get": {
        "description": "List the ad sources.",
        "operationId": "admob.accounts.adSources.list",
        "tags": [
          "accounts"
        ]
      }
    },
    "/v1beta/{parent}/adUnits": {
      "get": {
        "description": "List the ad units under the specified AdMob account.",
        "operationId": "admob.accounts.adUnits.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admob.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admob.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/v1beta/{parent}/apps": {
      "get": {
        "description": "List the apps under the specified AdMob account.",
        "operationId": "admob.accounts.apps.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admob.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admob.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/v1beta/{parent}/mediationReport:generate": {
      "post": {
        "description": "Generates an AdMob mediation report based on the provided report specification. Returns result of a server-side streaming RPC. The result is returned in a sequence of responses.",
        "operationId": "admob.accounts.mediationReport.generate",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admob.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admob.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admob.report"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admob.report"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    },
    "/v1beta/{parent}/networkReport:generate": {
      "post": {
        "description": "Generates an AdMob Network report based on the provided report specification. Returns result of a server-side streaming RPC. The result is returned in a sequence of responses.",
        "operationId": "admob.accounts.networkReport.generate",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admob.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admob.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admob.report"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admob.report"
            ]
          }
        ],
        "tags": [
          "accounts"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Oauth2": {
        "description": "Oauth 2.0 implicit authentication",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
            "scopes": {
              "https://www.googleapis.com/auth/admob.readonly": "See your AdMob data",
              "https://www.googleapis.com/auth/admob.report": "See your AdMob data"
            }
          }
        },
        "type": "oauth2"
      },
      "Oauth2c": {
        "description": "Oauth 2.0 authorizationCode authentication",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
            "scopes": {
              "https://www.googleapis.com/auth/admob.readonly": "See your AdMob data",
              "https://www.googleapis.com/auth/admob.report": "See your AdMob data"
            },
            "tokenUrl": "https://accounts.google.com/o/oauth2/token"
          }
        },
        "type": "oauth2"
      }
    }
  }
}