{
  "swagger": "2.0",
  "info": {
    "title": "Google Analytics API",
    "description": "View and manage your Google Analytics data",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v2.4"
  },
  "host": "www.googleapis.com",
  "basePath": "/analytics/v2.4",
  "schemes": [
    "https"
  ],
  "paths": {
    "/data": {
      "get": {
        "description": "Returns Analytics report data for a view (profile).",
        "operationId": "analytics.data.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ]
      }
    },
    "/management/accounts": {
      "get": {
        "description": "Lists all accounts to which the user has access.",
        "operationId": "analytics.management.accounts.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals": {
      "get": {
        "description": "Lists goals to which the user has access.",
        "operationId": "analytics.management.goals.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties/{webPropertyId}/profiles": {
      "get": {
        "description": "Lists views (profiles) to which the user has access.",
        "operationId": "analytics.management.profiles.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ]
      }
    },
    "/management/segments": {
      "get": {
        "description": "Lists advanced segments to which the user has access.",
        "operationId": "analytics.management.segments.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ]
      }
    },
    "/management/accounts/{accountId}/webproperties": {
      "get": {
        "description": "Lists web properties to which the user has access.",
        "operationId": "analytics.management.webproperties.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/analytics",
              "https://www.googleapis.com/auth/analytics.readonly"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/analytics": "View and manage your Google Analytics data",
        "https://www.googleapis.com/auth/analytics.readonly": "View your Google Analytics data"
      }
    }
  }
}