package shared




type GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum string

const (
    GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumUnknownLandmark GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "UNKNOWN_LANDMARK"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumLeftEye GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "LEFT_EYE"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumRightEye GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "RIGHT_EYE"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumLeftOfLeftEyebrow GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "LEFT_OF_LEFT_EYEBROW"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumRightOfLeftEyebrow GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "RIGHT_OF_LEFT_EYEBROW"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumLeftOfRightEyebrow GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "LEFT_OF_RIGHT_EYEBROW"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumRightOfRightEyebrow GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "RIGHT_OF_RIGHT_EYEBROW"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumMidpointBetweenEyes GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "MIDPOINT_BETWEEN_EYES"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumNoseTip GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "NOSE_TIP"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumUpperLip GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "UPPER_LIP"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumLowerLip GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "LOWER_LIP"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumMouthLeft GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "MOUTH_LEFT"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumMouthRight GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "MOUTH_RIGHT"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumMouthCenter GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "MOUTH_CENTER"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumNoseBottomRight GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "NOSE_BOTTOM_RIGHT"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumNoseBottomLeft GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "NOSE_BOTTOM_LEFT"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumNoseBottomCenter GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "NOSE_BOTTOM_CENTER"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumLeftEyeTopBoundary GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "LEFT_EYE_TOP_BOUNDARY"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumLeftEyeRightCorner GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "LEFT_EYE_RIGHT_CORNER"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumLeftEyeBottomBoundary GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "LEFT_EYE_BOTTOM_BOUNDARY"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumLeftEyeLeftCorner GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "LEFT_EYE_LEFT_CORNER"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumRightEyeTopBoundary GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "RIGHT_EYE_TOP_BOUNDARY"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumRightEyeRightCorner GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "RIGHT_EYE_RIGHT_CORNER"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumRightEyeBottomBoundary GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "RIGHT_EYE_BOTTOM_BOUNDARY"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumRightEyeLeftCorner GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "RIGHT_EYE_LEFT_CORNER"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumLeftEyebrowUpperMidpoint GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "LEFT_EYEBROW_UPPER_MIDPOINT"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumRightEyebrowUpperMidpoint GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "RIGHT_EYEBROW_UPPER_MIDPOINT"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumLeftEarTragion GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "LEFT_EAR_TRAGION"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumRightEarTragion GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "RIGHT_EAR_TRAGION"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumLeftEyePupil GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "LEFT_EYE_PUPIL"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumRightEyePupil GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "RIGHT_EYE_PUPIL"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumForeheadGlabella GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "FOREHEAD_GLABELLA"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumChinGnathion GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "CHIN_GNATHION"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumChinLeftGonion GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "CHIN_LEFT_GONION"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumChinRightGonion GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "CHIN_RIGHT_GONION"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumLeftCheekCenter GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "LEFT_CHEEK_CENTER"
GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnumRightCheekCenter GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum = "RIGHT_CHEEK_CENTER"
)


type GoogleCloudVisionV1p2beta1FaceAnnotationLandmark struct {
    Position *GoogleCloudVisionV1p2beta1Position `json:"position,omitempty"`
    Type *GoogleCloudVisionV1p2beta1FaceAnnotationLandmarkTypeEnum `json:"type,omitempty"`
    
}

