# coding: utf-8

"""
    Google Site Verification API

    Verifies ownership of websites or domains with Google.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.site_verification_web_resource_gettoken_request_site import SiteVerificationWebResourceGettokenRequestSite

class TestSiteVerificationWebResourceGettokenRequestSite(unittest.TestCase):
    """SiteVerificationWebResourceGettokenRequestSite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SiteVerificationWebResourceGettokenRequestSite:
        """Test SiteVerificationWebResourceGettokenRequestSite
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SiteVerificationWebResourceGettokenRequestSite`
        """
        model = SiteVerificationWebResourceGettokenRequestSite()
        if include_optional:
            return SiteVerificationWebResourceGettokenRequestSite(
                identifier = '',
                type = ''
            )
        else:
            return SiteVerificationWebResourceGettokenRequestSite(
        )
        """

    def testSiteVerificationWebResourceGettokenRequestSite(self):
        """Test SiteVerificationWebResourceGettokenRequestSite"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
