package shared

type LaunchTemplateInstanceMetadataEndpointStateEnum string

const (
	LaunchTemplateInstanceMetadataEndpointStateEnumDisabled LaunchTemplateInstanceMetadataEndpointStateEnum = "disabled"
	LaunchTemplateInstanceMetadataEndpointStateEnumEnabled  LaunchTemplateInstanceMetadataEndpointStateEnum = "enabled"
)
