from dataclasses import dataclass, field
from typing import Enum

class LeaveLineCalculationTypeEnum(str, Enum):
    NOCALCULATIONREQUIRED = "NOCALCULATIONREQUIRED"
    FIXEDAMOUNTEACHPERIOD = "FIXEDAMOUNTEACHPERIOD"
    ENTERRATEINPAYTEMPLATE = "ENTERRATEINPAYTEMPLATE"
    BASEDONORDINARYEARNINGS = "BASEDONORDINARYEARNINGS"
    UNKNOWN = ""

