from .osconfig_projects_guestpolicies_create import *
from .osconfig_projects_guestpolicies_list import *
from .osconfig_projects_patchdeployments_create import *
from .osconfig_projects_patchdeployments_delete import *
from .osconfig_projects_patchdeployments_list import *
from .osconfig_projects_patchdeployments_patch import *
from .osconfig_projects_patchdeployments_pause import *
from .osconfig_projects_patchdeployments_resume import *
from .osconfig_projects_patchjobs_cancel import *
from .osconfig_projects_patchjobs_execute import *
from .osconfig_projects_patchjobs_get import *
from .osconfig_projects_patchjobs_instancedetails_list import *
from .osconfig_projects_patchjobs_list import *
from .osconfig_projects_zones_instances_lookupeffectiveguestpolicy import *
