package shared




type GoogleCloudRecommendationengineV1beta1RejoinUserEventsRequestUserEventRejoinScopeEnum string

const (
    GoogleCloudRecommendationengineV1beta1RejoinUserEventsRequestUserEventRejoinScopeEnumUserEventRejoinScopeUnspecified GoogleCloudRecommendationengineV1beta1RejoinUserEventsRequestUserEventRejoinScopeEnum = "USER_EVENT_REJOIN_SCOPE_UNSPECIFIED"
GoogleCloudRecommendationengineV1beta1RejoinUserEventsRequestUserEventRejoinScopeEnumJoinedEvents GoogleCloudRecommendationengineV1beta1RejoinUserEventsRequestUserEventRejoinScopeEnum = "JOINED_EVENTS"
GoogleCloudRecommendationengineV1beta1RejoinUserEventsRequestUserEventRejoinScopeEnumUnjoinedEvents GoogleCloudRecommendationengineV1beta1RejoinUserEventsRequestUserEventRejoinScopeEnum = "UNJOINED_EVENTS"
)


type GoogleCloudRecommendationengineV1beta1RejoinUserEventsRequest struct {
    UserEventRejoinScope *GoogleCloudRecommendationengineV1beta1RejoinUserEventsRequestUserEventRejoinScopeEnum `json:"userEventRejoinScope,omitempty"`
    
}

