{
  "swagger": "2.0",
  "info": {
    "title": "Google Compute Engine Instance Group Updater API",
    "description": "The Google Compute Engine Instance Group Updater API provides services for updating groups of Compute Engine Instances.",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v1beta1"
  },
  "host": "www.googleapis.com",
  "basePath": "/replicapoolupdater/v1beta1/projects",
  "schemes": [
    "https"
  ],
  "paths": {
    "/{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/cancel": {
      "post": {
        "description": "Cancels an update. The update must be PAUSED before it can be cancelled. This has no effect if the update is already CANCELLED.",
        "operationId": "replicapoolupdater.rollingUpdates.cancel",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/replicapool"
            ]
          }
        ],
        "tags": [
          "rollingUpdates"
        ]
      }
    },
    "/{project}/zones/{zone}/rollingUpdates/{rollingUpdate}": {
      "get": {
        "description": "Returns information about an update.",
        "operationId": "replicapoolupdater.rollingUpdates.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/replicapool",
              "https://www.googleapis.com/auth/replicapool.readonly"
            ]
          }
        ],
        "tags": [
          "rollingUpdates"
        ]
      }
    },
    "/{project}/zones/{zone}/rollingUpdates": {
      "post": {
        "description": "Inserts and starts a new update.",
        "operationId": "replicapoolupdater.rollingUpdates.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/replicapool"
            ]
          }
        ],
        "tags": [
          "rollingUpdates"
        ]
      },
      "get": {
        "description": "Lists recent updates for a given managed instance group, in reverse chronological order and paginated format.",
        "operationId": "replicapoolupdater.rollingUpdates.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/replicapool",
              "https://www.googleapis.com/auth/replicapool.readonly"
            ]
          }
        ],
        "tags": [
          "rollingUpdates"
        ]
      }
    },
    "/{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/instanceUpdates": {
      "get": {
        "description": "Lists the current status for each instance within a given update.",
        "operationId": "replicapoolupdater.rollingUpdates.listInstanceUpdates",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/replicapool",
              "https://www.googleapis.com/auth/replicapool.readonly"
            ]
          }
        ],
        "tags": [
          "rollingUpdates"
        ]
      }
    },
    "/{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/pause": {
      "post": {
        "description": "Pauses the update in state from ROLLING_FORWARD or ROLLING_BACK. Has no effect if invoked when the state of the update is PAUSED.",
        "operationId": "replicapoolupdater.rollingUpdates.pause",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/replicapool"
            ]
          }
        ],
        "tags": [
          "rollingUpdates"
        ]
      }
    },
    "/{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/resume": {
      "post": {
        "description": "Continues an update in PAUSED state. Has no effect if invoked when the state of the update is ROLLED_OUT.",
        "operationId": "replicapoolupdater.rollingUpdates.resume",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/replicapool"
            ]
          }
        ],
        "tags": [
          "rollingUpdates"
        ]
      }
    },
    "/{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/rollback": {
      "post": {
        "description": "Rolls back the update in state from ROLLING_FORWARD or PAUSED. Has no effect if invoked when the state of the update is ROLLED_BACK.",
        "operationId": "replicapoolupdater.rollingUpdates.rollback",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/replicapool"
            ]
          }
        ],
        "tags": [
          "rollingUpdates"
        ]
      }
    },
    "/{project}/zones/{zone}/operations/{operation}": {
      "get": {
        "description": "Retrieves the specified zone-specific operation resource.",
        "operationId": "replicapoolupdater.zoneOperations.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/replicapool"
            ]
          }
        ],
        "tags": [
          "zoneOperations"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/cloud-platform": "View and manage your data across Google Cloud Platform services",
        "https://www.googleapis.com/auth/replicapool": "View and manage replica pools",
        "https://www.googleapis.com/auth/replicapool.readonly": "View replica pools"
      }
    }
  }
}