from ._xgafv_enum import *
from .affinetransform import *
from .alt_enum import *
from .autofit import *
from .autotext import *
from .batchupdatepresentationrequest import *
from .batchupdatepresentationresponse import *
from .bullet import *
from .colorscheme import *
from .colorstop import *
from .createimagerequest import *
from .createimageresponse import *
from .createlinerequest import *
from .createlineresponse import *
from .createparagraphbulletsrequest import *
from .createshaperequest import *
from .createshaperesponse import *
from .createsheetschartrequest import *
from .createsheetschartresponse import *
from .createsliderequest import *
from .createslideresponse import *
from .createtablerequest import *
from .createtableresponse import *
from .createvideorequest import *
from .createvideoresponse import *
from .cropproperties import *
from .deleteobjectrequest import *
from .deleteparagraphbulletsrequest import *
from .deletetablecolumnrequest import *
from .deletetablerowrequest import *
from .deletetextrequest import *
from .dimension import *
from .duplicateobjectrequest import *
from .duplicateobjectresponse import *
from .group import *
from .groupobjectsrequest import *
from .groupobjectsresponse import *
from .image import *
from .imageproperties import *
from .inserttablecolumnsrequest import *
from .inserttablerowsrequest import *
from .inserttextrequest import *
from .layoutplaceholderidmapping import *
from .layoutproperties import *
from .layoutreference import *
from .line import *
from .lineconnection import *
from .linefill import *
from .lineproperties import *
from .link import *
from .list import *
from .masterproperties import *
from .mergetablecellsrequest import *
from .nestinglevel import *
from .notesproperties import *
from .opaquecolor import *
from .optionalcolor import *
from .outline import *
from .outlinefill import *
from .page import *
from .pagebackgroundfill import *
from .pageelement import *
from .pageelementproperties import *
from .pageproperties import *
from .paragraphmarker import *
from .paragraphstyle import *
from .placeholder import *
from .presentation import *
from .range import *
from .recolor import *
from .refreshsheetschartrequest import *
from .replaceallshapeswithimagerequest import *
from .replaceallshapeswithimageresponse import *
from .replaceallshapeswithsheetschartrequest import *
from .replaceallshapeswithsheetschartresponse import *
from .replacealltextrequest import *
from .replacealltextresponse import *
from .replaceimagerequest import *
from .request import *
from .reroutelinerequest import *
from .response import *
from .rgbcolor import *
from .security import *
from .shadow import *
from .shape import *
from .shapebackgroundfill import *
from .shapeproperties import *
from .sheetschart import *
from .sheetschartproperties import *
from .size import *
from .slideproperties import *
from .solidfill import *
from .stretchedpicturefill import *
from .substringmatchcriteria import *
from .table import *
from .tablebordercell import *
from .tableborderfill import *
from .tableborderproperties import *
from .tableborderrow import *
from .tablecell import *
from .tablecellbackgroundfill import *
from .tablecelllocation import *
from .tablecellproperties import *
from .tablecolumnproperties import *
from .tablerange import *
from .tablerow import *
from .tablerowproperties import *
from .textcontent import *
from .textelement import *
from .textrun import *
from .textstyle import *
from .themecolorpair import *
from .thumbnail import *
from .ungroupobjectsrequest import *
from .unmergetablecellsrequest import *
from .updateimagepropertiesrequest import *
from .updatelinecategoryrequest import *
from .updatelinepropertiesrequest import *
from .updatepageelementalttextrequest import *
from .updatepageelementszorderrequest import *
from .updatepageelementtransformrequest import *
from .updatepagepropertiesrequest import *
from .updateparagraphstylerequest import *
from .updateshapepropertiesrequest import *
from .updateslidepropertiesrequest import *
from .updateslidespositionrequest import *
from .updatetableborderpropertiesrequest import *
from .updatetablecellpropertiesrequest import *
from .updatetablecolumnpropertiesrequest import *
from .updatetablerowpropertiesrequest import *
from .updatetextstylerequest import *
from .updatevideopropertiesrequest import *
from .video import *
from .videoproperties import *
from .weightedfontfamily import *
from .wordart import *
from .writecontrol import *
