from dataclasses import dataclass, field
from enum import Enum

class EntityTypeEnum(str, Enum):
    MEDICATION = "MEDICATION"
    MEDICAL_CONDITION = "MEDICAL_CONDITION"
    PROTECTED_HEALTH_INFORMATION = "PROTECTED_HEALTH_INFORMATION"
    TEST_TREATMENT_PROCEDURE = "TEST_TREATMENT_PROCEDURE"
    ANATOMY = "ANATOMY"
    TIME_EXPRESSION = "TIME_EXPRESSION"

