package operations

import (
"openapi/pkg/models/shared")


type DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum string

const (
    DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeUnspecified DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_UNSPECIFIED"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeChannel DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_CHANNEL"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeAppCategory DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_APP_CATEGORY"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeApp DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_APP"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeURL DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_URL"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeDayAndTime DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_DAY_AND_TIME"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeAgeRange DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_AGE_RANGE"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeRegionalLocationList DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_REGIONAL_LOCATION_LIST"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeProximityLocationList DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_PROXIMITY_LOCATION_LIST"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeGender DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_GENDER"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeVideoPlayerSize DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_VIDEO_PLAYER_SIZE"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeUserRewardedContent DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_USER_REWARDED_CONTENT"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeParentalStatus DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_PARENTAL_STATUS"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeContentInstreamPosition DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_CONTENT_INSTREAM_POSITION"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeContentOutstreamPosition DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_CONTENT_OUTSTREAM_POSITION"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeDeviceType DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_DEVICE_TYPE"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeAudienceGroup DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_AUDIENCE_GROUP"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeBrowser DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_BROWSER"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeHouseholdIncome DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_HOUSEHOLD_INCOME"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeOnScreenPosition DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_ON_SCREEN_POSITION"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeThirdPartyVerifier DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_THIRD_PARTY_VERIFIER"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeDigitalContentLabelExclusion DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_DIGITAL_CONTENT_LABEL_EXCLUSION"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeSensitiveCategoryExclusion DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_SENSITIVE_CATEGORY_EXCLUSION"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeEnvironment DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_ENVIRONMENT"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeCarrierAndIsp DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_CARRIER_AND_ISP"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeOperatingSystem DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_OPERATING_SYSTEM"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeDeviceMakeModel DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_DEVICE_MAKE_MODEL"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeKeyword DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_KEYWORD"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeNegativeKeywordList DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_NEGATIVE_KEYWORD_LIST"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeViewability DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_VIEWABILITY"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeCategory DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_CATEGORY"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeInventorySource DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_INVENTORY_SOURCE"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeLanguage DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_LANGUAGE"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeAuthorizedSellerStatus DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_AUTHORIZED_SELLER_STATUS"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeGeoRegion DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_GEO_REGION"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeInventorySourceGroup DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_INVENTORY_SOURCE_GROUP"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeExchange DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_EXCHANGE"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeSubExchange DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_SUB_EXCHANGE"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypePoi DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_POI"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeBusinessChain DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_BUSINESS_CHAIN"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeContentDuration DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_CONTENT_DURATION"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeContentStreamType DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_CONTENT_STREAM_TYPE"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeNativeContentPosition DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_NATIVE_CONTENT_POSITION"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeOmid DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_OMID"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeAudioContentType DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_AUDIO_CONTENT_TYPE"
DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnumTargetingTypeContentGenre DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum = "TARGETING_TYPE_CONTENT_GENRE"
)


type DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreatePathParams struct {
    AdvertiserID string `pathParam:"style=simple,explode=false,name=advertiserId"`
    TargetingType DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateTargetingTypeEnum `pathParam:"style=simple,explode=false,name=targetingType"`
    
}

type DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateQueryParams struct {
    DollarXgafv *shared.XgafvEnum `queryParam:"style=form,explode=true,name=$.xgafv"`
    AccessToken *string `queryParam:"style=form,explode=true,name=access_token"`
    Alt *shared.AltEnum `queryParam:"style=form,explode=true,name=alt"`
    Callback *string `queryParam:"style=form,explode=true,name=callback"`
    Fields *string `queryParam:"style=form,explode=true,name=fields"`
    Key *string `queryParam:"style=form,explode=true,name=key"`
    OauthToken *string `queryParam:"style=form,explode=true,name=oauth_token"`
    PrettyPrint *bool `queryParam:"style=form,explode=true,name=prettyPrint"`
    QuotaUser *string `queryParam:"style=form,explode=true,name=quotaUser"`
    UploadType *string `queryParam:"style=form,explode=true,name=uploadType"`
    UploadProtocol *string `queryParam:"style=form,explode=true,name=upload_protocol"`
    
}

type DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateSecurity struct {
    Oauth2 shared.SchemeOauth2 `security:"scheme,type=oauth2"`
    Oauth2c shared.SchemeOauth2c `security:"scheme,type=oauth2"`
    
}

type DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateRequest struct {
    PathParams DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreatePathParams 
    QueryParams DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateQueryParams 
    Request *shared.AssignedTargetingOption `request:"mediaType=application/json"`
    Security DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateSecurity 
    
}

type DisplayvideoAdvertisersTargetingTypesAssignedTargetingOptionsCreateResponse struct {
    AssignedTargetingOption *shared.AssignedTargetingOption 
    ContentType string 
    StatusCode int64 
    
}

