swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /replicapoolupdater/v1beta1/projects
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: '[Deprecated. Please use compute.instanceGroupManagers.update method. replicapoolupdater API will be disabled after December 30th, 2016] Updates groups of Compute Engine instances.'
  title: Google Compute Engine Instance Group Updater
  version: v1beta1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    format: google
    url: 'https://www.googleapis.com/discovery/v1/apis/replicapoolupdater/v1beta1/rest'
    version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: replicapoolupdater
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/cloud-platform': View and manage your data across Google Cloud Platform services
      'https://www.googleapis.com/auth/cloud-platform.read-only': View your data across Google Cloud Platform services
      'https://www.googleapis.com/auth/replicapool': View and manage replica pools
      'https://www.googleapis.com/auth/replicapool.readonly': View replica pools
    type: oauth2
tags:
  - name: rollingUpdates
  - name: rollout
  - name: zoneOperations
paths:
  '/{project}/zones/{zone}/operations':
    get:
      description: Retrieves the list of Operation resources contained within the specified zone.
      operationId: replicapoolupdater.zoneOperations.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool'
      tags:
        - zoneOperations
  '/{project}/zones/{zone}/operations/{operation}':
    get:
      description: Retrieves the specified zone-specific operation resource.
      operationId: replicapoolupdater.zoneOperations.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool'
      tags:
        - zoneOperations
  '/{project}/zones/{zone}/rollingUpdates':
    get:
      description: 'Lists recent updates for a given managed instance group, in reverse chronological order and paginated format.'
      operationId: replicapoolupdater.rollingUpdates.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool.readonly'
      tags:
        - rollingUpdates
    post:
      description: Inserts and starts a new update.
      operationId: replicapoolupdater.rollingUpdates.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool'
      tags:
        - rollingUpdates
  '/{project}/zones/{zone}/rollingUpdates/{rollingUpdate}':
    get:
      description: Returns information about an update.
      operationId: replicapoolupdater.rollingUpdates.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool.readonly'
      tags:
        - rollingUpdates
  '/{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/cancel':
    post:
      description: Cancels an update. The update must be PAUSED before it can be cancelled. This has no effect if the update is already CANCELLED.
      operationId: replicapoolupdater.rollingUpdates.cancel
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool'
      tags:
        - rollingUpdates
  '/{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/instanceUpdates':
    get:
      description: Lists the current status for each instance within a given update.
      operationId: replicapoolupdater.rollingUpdates.listInstanceUpdates
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool.readonly'
      tags:
        - rollingUpdates
  '/{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/pause':
    post:
      description: Pauses the update in state from ROLLING_FORWARD or ROLLING_BACK. Has no effect if invoked when the state of the update is PAUSED.
      operationId: replicapoolupdater.rollingUpdates.pause
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool'
      tags:
        - rollingUpdates
  '/{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/resume':
    post:
      description: Continues an update in PAUSED state. Has no effect if invoked when the state of the update is ROLLED_OUT.
      operationId: replicapoolupdater.rollingUpdates.resume
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool'
      tags:
        - rollingUpdates
  '/{project}/zones/{zone}/rollingUpdates/{rollingUpdate}/rollback':
    post:
      description: Rolls back the update in state from ROLLING_FORWARD or PAUSED. Has no effect if invoked when the state of the update is ROLLED_BACK.
      operationId: replicapoolupdater.rollingUpdates.rollback
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool'
      tags:
        - rollingUpdates
  '/{project}/zones/{zone}/rollouts':
    get:
      description: Resume a rollout. This lets the rollout continue updating instances after a pause.
      operationId: replicapoolupdater.rollout.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool.readonly'
      tags:
        - rollout
    post:
      description: Inserts and starts a new rollout
      operationId: replicapoolupdater.rollout.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool'
      tags:
        - rollout
  '/{project}/zones/{zone}/rollouts/{rollout}':
    get:
      description: Get the details of a rollout
      operationId: replicapoolupdater.rollout.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform.read-only'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool.readonly'
      tags:
        - rollout
  '/{project}/zones/{zone}/rollouts/{rollout}/abandon':
    post:
      description: 'Abandon a rollout, leaving the IGM in the state it is already configured. This allows you to apply a new rollout to the IGM.'
      operationId: replicapoolupdater.rollout.abandon
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool'
      tags:
        - rollout
  '/{project}/zones/{zone}/rollouts/{rollout}/commit':
    post:
      description: 'Commits a rollout, so that it is final and can not be rolled back'
      operationId: replicapoolupdater.rollout.commit
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool'
      tags:
        - rollout
  '/{project}/zones/{zone}/rollouts/{rollout}/pause':
    post:
      description: 'Pause the application of a rollout. This stops the update, and the instances managed by the instance group manager do not change their instance templates.'
      operationId: replicapoolupdater.rollout.pause
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool'
      tags:
        - rollout
  '/{project}/zones/{zone}/rollouts/{rollout}/rampup':
    post:
      description: Change the amount of instances within an IGM that should be updated to the new instance template
      operationId: replicapoolupdater.rollout.rampup
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool'
      tags:
        - rollout
  '/{project}/zones/{zone}/rollouts/{rollout}/resume':
    post:
      description: Resume a rollout. This lets the rollout continue updating instances after a pause.
      operationId: replicapoolupdater.rollout.resume
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool'
      tags:
        - rollout
  '/{project}/zones/{zone}/rollouts/{rollout}/rollback':
    post:
      description: 'Rollback a rollout, cancelling the update and changing all instances with the updated version to have the instanceTemplateToRollback template.'
      operationId: replicapoolupdater.rollout.rollback
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/replicapool'
      tags:
        - rollout