openapi: 3.0.0
servers:
  - url: https://www.daniweb.com/connect/api/v4
info:
  contact:
    email: dani@daniwebmail.com
    name: Dani Wolkowicki
    url: https://www.daniweb.com/members/1/dani
    x-twitter: DaniWeb
  description: User Recommendation Engine and Chat Network
  termsOfService: https://www.daniweb.com/connect/welcome/privacy
  title: DaniWeb Connect API
  version: "4"
  x-apisguru-categories:
    - developer_tools
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_DaniWeb_profile_image.jpeg
  x-origin:
    - format: openapi
      url: https://www.daniweb.com/connect/developers/swagger
      version: "3.0"
  x-providerName: daniweb.com
tags:
  - description: Operations involving Apps
    name: apps
  - description: Operations involving Audiences
    name: audiences
  - description: Operations involving Autocompletes
    name: autocompletes
  - description: Operations involving Conversations
    name: conversations
  - description: Operations involving Groups
    name: groups
  - description: Operations involving Industries
    name: industries
  - description: Operations involving Markdown
    name: markdown
  - description: Operations involving Messages
    name: messages
  - description: Operations involving Users
    name: users
  - description: Operations involving Positions
    name: positions
  - description: Operations involving Webhooks
    name: webhooks
paths:
  /apps:
    get:
      description: Fetch all Daniapps that are currently in production mode.
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - apps
  "/apps/{ID}":
    get:
      description: Fetch an array of Daniapps that are currently in production mode.
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - apps
  /audiences:
    get:
      description: Fetch all Daniapp audience segments that comprise the current access token's bubble.
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - audiences
  "/audiences/{ID}":
    get:
      description: Fetch an array of Daniapp audience segments that comprise the current access token's bubble.
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - audiences
  "/audiences/{ID}/memberships":
    post:
      description: Create a membership record for the OAuth'ed end-user based on the current audience segment/bubble combination.
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - audiences
  /autocompletes:
    get:
      description: "Retrieve an array of names and locations, filtered by category, that begin with the query string passed in. Ideally used for search autocomplete dropdowns, as the search functionality filters against name and location. The four potential categories are: `conversations` for names of users you are in existing conversations with; `matches` for names of users you have previously skipped over; `people` for names of all other users; `locations` for locations of users. Only users an[...]"
      security:
        - explicit_flow:
            - profile_read
        - implicit_flow:
            - profile_read
      tags:
        - autocompletes
  /conversations/schedules:
    post:
      description: Paginated report of information about messages contributed by conversation and date. Only conversations that exist within the current access token's bubble are considered in the calculations. Optionally roll up all conversations to retrieve one record per date. Optionally specify a date formatted as YYYY-MM-DD to retrieve information just from the single date, along with additional navigational information, which is useful when generating a transcript for a single day and want[...]
      security:
        - explicit_flow:
            - conversations_read
        - implicit_flow:
            - conversations_read
      tags:
        - conversations
  /conversations/searches:
    post:
      description: Fetch messages authored from within the current bubble that match a query string passed in as a search parameter along with their relevancy score.
      security:
        - explicit_flow:
            - conversations_read
        - implicit_flow:
            - conversations_read
      tags:
        - conversations
  /conversations/statuses:
    get:
      description: "Retrieve conversations that you are participating in with users who exists within the same bubble, along with your current relationship with the conversations. The user_a / user_b properties of the conversation are populated with as much data as is available if the user is not you. If the user is you, only the id field is populated. There is a separate status endpoint to retrieve relationship information for individual conversations. Optionally filter: 'new' to only show conv[...]"
      security:
        - explicit_flow:
            - conversations_read
        - implicit_flow:
            - conversations_read
      tags:
        - conversations
  "/conversations/{ID}":
    get:
      description: Fetch an array of conversations. You can only retrieve conversations with users who exist within the current access token's bubble.
      security:
        - explicit_flow:
            - conversations_read
        - implicit_flow:
            - conversations_read
      tags:
        - conversations
  "/conversations/{ID}/messages":
    get:
      description: Retrieve the last {limit} messages in the conversation, provided the conversations exist within the current access token's bubble. If a timeout is 0 or greater, the batch is sorted oldest first. Otherwise, if timeout is a negative number, the transcript is paginated and sorted newest first. Specify a timeout for long polling (which delays the server sending back results for up to n seconds or until results are available, whichever comes first), or default to 0 for immediate re[...]
      security:
        - explicit_flow:
            - conversations_read
        - implicit_flow:
            - conversations_read
      tags:
        - conversations
    post:
      description: Post a message to a conversation that is with a user who exists within the current access token's bubble. Optionally specify whether emoticons should be parsed into smiley images. Optionally specify whether the message should be bubbled within the app. Additionally, optionally attach a single metadata key/value pair to the message upon submission.
      security:
        - explicit_flow:
            - conversations_read
            - conversations_write
        - implicit_flow:
            - conversations_read
            - conversations_write
      tags:
        - conversations
  "/conversations/{ID}/schedules":
    post:
      description: Paginated report of information about messages contributed by conversation and date. Only conversations that exist within the current access token's bubble are considered in the calculations. Optionally roll up all conversations to retrieve one record per date. Optionally specify a date formatted as YYYY-MM-DD to retrieve information just from the single date, along with additional navigational information, which is useful when generating a transcript for a single day and want[...]
      security:
        - explicit_flow:
            - conversations_read
        - implicit_flow:
            - conversations_read
      tags:
        - conversations
  "/conversations/{ID}/searches":
    post:
      description: Fetch messages authored from within specified conversations that match a query string passed in as a search parameter along with their relevancy score.
      security:
        - explicit_flow:
            - conversations_read
        - implicit_flow:
            - conversations_read
      tags:
        - conversations
  "/conversations/{ID}/statuses":
    get:
      description: Status information about your current relationship with one or more conversations you participating in, provided the conversations exist within the current access token's bubble.
      security:
        - explicit_flow:
            - conversations_read
        - implicit_flow:
            - conversations_read
      tags:
        - conversations
    patch:
      description: Archive or unarchive a conversation that is with a user who exists within the same bubble.
      security:
        - explicit_flow:
            - conversations_read
            - conversations_write
        - implicit_flow:
            - conversations_read
            - conversations_write
      tags:
        - conversations
  /groups:
    get:
      description: Fetch an array of all groups that were created by users existing within the current access token's bubble. The groups must be either Public or you must be a member of them. Unlisted and Private groups that you are not a member of are not listed.
      security:
        - explicit_flow:
            - groups_read
        - implicit_flow:
            - groups_read
      tags:
        - groups
    post:
      description: Create a new group for other members to join. Any user who is using an access token whose bubble you exist in can join your group provided it is not a private group. Private groups can only be joined by members who know its passphrase. Unlisted groups can be joined by anybody as long as they know the Group ID, but they are not referenced anywhere to non-members. Public groups can be joined by anybody, are discoverable, and anyone can see the public groups a user is a member of[...]
      security:
        - explicit_flow:
            - groups_read
            - groups_write
        - implicit_flow:
            - groups_read
            - groups_write
      tags:
        - groups
  /groups/messages/metadata/filters:
    post:
      description: Paginated listing of messages filtered by arbitrary metadata criteria. Messages must match on all key/value pairs passed in. Messages may only match on one value of an array passed in. However, messages are sorted based on how many distinct values they match on (most matches first).
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - groups
  "/groups/messages/{ID}":
    delete:
      description: Delete an array of group messages. You must be the owner or moderator of the group.
      security:
        - explicit_flow:
            - groups_read
            - groups_write
        - implicit_flow:
            - groups_read
            - groups_write
      tags:
        - groups
    get:
      description: Fetch an array of group messages. You can only retrieve messages authored by you or by users existing within the current access token's bubble.
      security:
        - explicit_flow:
            - groups_read
        - implicit_flow:
            - groups_read
      tags:
        - groups
  "/groups/messages/{ID}/metadata":
    get:
      description: Retrieve all key/value pairs attached to the current message that you have access to, so long as the user who created the group exists within the current access token's bubble. This includes all public metadata, bubbled metadata that was created by an access token existing within the current bubble, user metadata that was created by you, or private metadata created by you from an access token existing within the current bubble.
      security:
        - explicit_flow:
            - groups_read
        - implicit_flow:
            - groups_read
      tags:
        - groups
    post:
      description: "Attach one-to-many key/value pairs of metadata to a group message, so long as the user who authored the message exists within the current access token's bubble and you are a member of their group. A key is unique for each author/bubble combination. Attaching metadata with an existing key that was previously created by you, from within the same bubble, overwrites the key with the new value or set of values. The privacy setting allows you to specify who will have access to the [...]"
      security:
        - explicit_flow:
            - groups_read
        - implicit_flow:
            - groups_read
      tags:
        - groups
  "/groups/messages/{ID}/metadata/collections":
    get:
      description: Retrieve all key/value pairs attached to the current message that you have access to, so long as the user who created the group exists within the current access token's bubble. This includes all public metadata, bubbled metadata that was created by an access token existing within the current bubble, user metadata that was created by you, or private metadata created by you from an access token existing within the current bubble. Metadata will be grouped by key.
      security:
        - explicit_flow:
            - groups_read
        - implicit_flow:
            - groups_read
      tags:
        - groups
  /groups/schedules:
    post:
      description: Paginated report of information about messages contributed by group and date. Only groups you're a member of and group messages authored by users the current access token has access to are considered in the calculations. Optionally roll up all groups to retrieve one record per date. Optionally specify a date formatted as YYYY-MM-DD to retrieve information just from the single date, along with additional navigational information, which is useful when generating a transcript for[...]
      security:
        - explicit_flow:
            - groups_read
        - implicit_flow:
            - groups_read
      tags:
        - groups
  /groups/statuses:
    get:
      description: Retrieve groups that were created by users within the current access token's bubble, along with your current relationship with the groups. The groups must be either Public or you must be a member of them. Unlisted and Private groups that you are not a member of are not listed. Optionally only retrieve groups that you are a member of.
      security:
        - explicit_flow:
            - groups_read
        - implicit_flow:
            - groups_read
      tags:
        - groups
  "/groups/{ID}":
    get:
      description: Fetch an array of groups. You can only retrieve groups created by users existing within the current access token's bubble.
      security:
        - explicit_flow:
            - groups_read
        - implicit_flow:
            - groups_read
      tags:
        - groups
    patch:
      description: Modify a group you previously created.
      security:
        - explicit_flow:
            - groups_read
            - groups_write
        - implicit_flow:
            - groups_read
            - groups_write
      tags:
        - groups
  "/groups/{ID}/memberships":
    delete:
      description: Leave a group that you are a member of and that was created by a user who exists within the current access token's bubble.
      security:
        - explicit_flow:
            - groups_read
            - groups_write
        - implicit_flow:
            - groups_read
            - groups_write
      tags:
        - groups
    get:
      description: Fetch an array of users who are members of specific groups that you are also a member of. You can only retrieve users existing within the current access token's bubble.
      security:
        - explicit_flow:
            - groups_read
        - implicit_flow:
            - groups_read
      tags:
        - groups
    patch:
      description: Promote or demote a member's privileges within a group that you created. The user must exist within the current access token's bubble and be an existing member of the group.
      security:
        - explicit_flow:
            - groups_read
        - implicit_flow:
            - groups_read
      tags:
        - groups
    post:
      description: Join a group that was created by a user who exists within the current access token's bubble, or join other users into a group that you created. If you are the group owner, you can pass in a user_id to create membership records for a user you are in a conversation with. The user must exist within the current access token's bubble. If the group is private, you must successfully pass in its passphrase in order to join. You can obtain the passphrase from the group's owner.
      security:
        - explicit_flow:
            - groups_read
            - groups_write
        - implicit_flow:
            - groups_read
            - groups_write
      tags:
        - groups
  "/groups/{ID}/messages":
    get:
      description: Retrieve the last {limit} messages in the group, for messages authored by users within the current access token's bubble. If a timeout is 0 or greater, the batch is sorted oldest first. Otherwise, if timeout is a negative number, the transcript is paginated and sorted newest first. Specify a timeout for long polling (which delays the server sending back results for up to n seconds or until results are available, whichever comes first), or default to 0 for immediate results. Op[...]
      security:
        - explicit_flow:
            - groups_read
        - implicit_flow:
            - groups_read
      tags:
        - groups
    post:
      description: Post a message to a group that you are a member of and that was created by a user who exists within the current access token's bubble. Optionally specify whether emoticons should be parsed into smiley images. Additionally, optionally attach a single metadata key/value pair to the group message upon submission.
      security:
        - explicit_flow:
            - groups_read
            - groups_write
        - implicit_flow:
            - groups_read
            - groups_write
      tags:
        - groups
  "/groups/{ID}/schedules":
    post:
      description: Paginated report of information about group messages contributed by conversation and date. Only groups you're a member of and group messages authored by users existing within the current access token's bubble are considered in the calculations. Optionally roll up all groups to retrieve one record per date. Optionally specify a date formatted as YYYY-MM-DD to retrieve information just from the single date, along with additional navigational information, which is useful when gen[...]
      security:
        - explicit_flow:
            - groups_read
        - implicit_flow:
            - groups_read
      tags:
        - groups
  "/groups/{ID}/statuses":
    get:
      description: Status information about your current relationship with one or more groups you are a member of, provided the users who created the groups exist within the current access token's bubble.
      security:
        - explicit_flow:
            - groups_read
        - implicit_flow:
            - groups_read
      tags:
        - groups
  /industries:
    get:
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - industries
  /markdown:
    post:
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - markdown
  /markdown/emoticons:
    get:
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - markdown
  /messages/metadata/filters:
    post:
      description: Paginated listing of messages filtered by arbitrary metadata criteria. Messages must match on all key/value pairs passed in. Messages may only match on one value of an array passed in. However, messages are sorted based on how many distinct values they match on (most matches first).
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - messages
  "/messages/{ID}":
    get:
      description: Fetch an array of messages. You can only retrieve messages authored by you or by users who exist within the current access token's bubble.
      security:
        - explicit_flow:
            - conversations_read
        - implicit_flow:
            - conversations_read
      tags:
        - messages
  "/messages/{ID}/metadata":
    get:
      description: Retrieve all key/value pairs attached to the current message that you have access to, so long as the user who authored the message exists within the current access token's bubble. This includes all public metadata, bubbled metadata that was created by an access token existing within the current bubble, user metadata that was created by you, or private metadata created by you from an access token existing within the current bubble.
      security:
        - explicit_flow:
            - conversations_read
        - implicit_flow:
            - conversations_read
      tags:
        - messages
    post:
      description: "Attach one-to-many key/value pairs of metadata to a message, so long as the user who authored the message exists within the current access token's bubble. A key is unique for each author/bubble combination. Attaching metadata with an existing key that was previously created by you, from within the same bubble, overwrites the key with the new value or set of values. The privacy setting allows you to specify who will have access to the metadata: Public metadata by you or the ot[...]"
      security:
        - explicit_flow:
            - conversations_read
        - implicit_flow:
            - conversations_read
      tags:
        - messages
  "/messages/{ID}/metadata/collections":
    get:
      description: Retrieve all key/value pairs attached to the current message that you have access to, so long as the user who authored the message exists within the current access token's bubble. This includes all public metadata, bubbled metadata that was created by an access token existing within the current bubble, user metadata that was created by you, or private metadata created by you from an access token existing within the current bubble. Metadata will be grouped by key.
      security:
        - explicit_flow:
            - conversations_read
        - implicit_flow:
            - conversations_read
      tags:
        - messages
  /positions:
    post:
      description: Update the OAuth'ed end user's Curriculum Vitae by adding a position.
      security:
        - explicit_flow:
            - profile_read
            - profile_write
        - implicit_flow:
            - profile_read
            - profile_write
      tags:
        - positions
  "/positions/{ID}":
    delete:
      description: Remove an item from the OAuth'ed end user's Curriculum Vitae.
      security:
        - explicit_flow:
            - profile_read
            - profile_write
        - implicit_flow:
            - profile_read
            - profile_write
      tags:
        - positions
    patch:
      description: Update the OAuth'ed end user's Curriculum Vitae by modifying an existing position.
      security:
        - explicit_flow:
            - profile_read
            - profile_write
        - implicit_flow:
            - profile_read
            - profile_write
      tags:
        - positions
  /users:
    get:
      description: "Fetch an array of users that you've been matched with, connected with, skipped, or muted. You can only retrieve users existing within the current access token's bubble. This report may be limited to the last ~500-1000 users you've communicated with within the access token's bubble. Matches are always ordered by synergy, and the order_by parameter is ignored. You can only retrieve bubbled users when retrieving matches, and the bubbled parameter is ignored otherwise. Your 100 b[...]"
      security:
        - explicit_flow:
            - profile_read
        - implicit_flow:
            - profile_read
      tags:
        - users
  /users/invites:
    post:
      description: "Invite users to into your current access token's bubble by having Dazah send out email invitations on your behalf. The invitation sends users to begin the OAuth flow for the current application (based on the settings specified in the application's profile), and therefore they will be redirected to the application upon signing up / logging in. Upon doing so, if they aren't already, they will automatically be connected with you as well. If your current access token does not esc[...]"
      security:
        - explicit_flow:
            - profile_read
            - conversations_write
        - implicit_flow:
            - profile_read
            - conversations_write
      tags:
        - users
  /users/metadata/filters:
    post:
      description: Paginated listing of users filtered by arbitrary metadata criteria. Users must match on all key/value pairs passed in. Users may only match on one value of an array passed in. However, users are sorted based on how many distinct values they match on (most matches first).
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - users
  /users/nearby:
    get:
      description: Fetch an array of users that are geographically close to a set of coordinates. You can only retrieve users existing within the current access token's bubble.
      security:
        - explicit_flow:
            - profile_read
        - implicit_flow:
            - profile_read
      tags:
        - users
  /users/searches:
    post:
      description: Filter and perform a weighted search against user profile fields, CV fields, and metadata by specifying a string to search on for each individual field. By default, results are filtered such that all words in the string must exist, unless you seprate the words with OR. To perform a weighted search (as opposed to filtering), specify the weight (from 0-100) the search algorithm should assign to the field. You can optionally exclude users who you are already in or not in conversa[...]
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - users
  "/users/{ID}":
    get:
      description: Fetch an array of users. You can only retrieve users existing within the current access token's bubble.
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - users
  "/users/{ID}/groups":
    get:
      description: You can only retrieve groups that were created by users existing within the current access token's bubble.
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - users
  "/users/{ID}/groups/messages":
    get:
      description: Paginated transcript of group messages authored by an individual user who exists within the current access token's bubble. Messages are sorted oldest to newest.
      security:
        - explicit_flow:
            - groups_read
        - implicit_flow:
            - groups_read
      tags:
        - users
  "/users/{ID}/messages":
    post:
      description: Initiate a conversation with a user who exists within the current access token's bubble by sending them an introductory message. If you aren't already in a conversation with them, this endpoint meets them first, and then sends the message. Note that if you aren't in an existing conversation, you still must meet the criteria to meet them, meaning the user must currently be free for you to meet. You will receive an error message unless it is currently free for you to meet the us[...]
      security:
        - explicit_flow:
            - profile_read
            - conversations_write
        - implicit_flow:
            - profile_read
            - conversations_write
      tags:
        - users
  "/users/{ID}/metadata":
    get:
      description: Retrieve all key/value pairs attached to the current user that you have access to, so long as the user exists within the current access token's bubble. This includes all public metadata, bubbled metadata that was created by an access token existing within the current bubble, user metadata that was created by you, or private metadata created by you from an access token existing within the current bubble. You will receive an error message unless either the current access token i[...]
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - users
    post:
      description: "Attach one-to-many key/value pairs of metadata to a user, so long as the user exists within the current access token's bubble. You can set one key at a time, with one or many values. A key is unique for each author/bubble combination. Attaching metadata with an existing key that was previously created by you, from within the same bubble, overwrites the key with the new value or set of values. The privacy setting allows you to specify who will have access to the metadata: Publ[...]"
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - users
  "/users/{ID}/metadata/collections":
    get:
      description: Retrieve all key/value pairs attached to the current user that you have access to, so long as the user exists within the current access token's bubble. This includes all public metadata, bubbled metadata that was created by an access token existing within the current bubble, user metadata that was created by you, or private metadata created by you from an access token existing within the current bubble. You will receive an error message unless either the current access token i[...]
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - users
  "/users/{ID}/positions":
    get:
      description: Retrieve the CV of a user who exists within the current access token's bubble. You will receive an error message unless either the current access token is bubbled, the user is an algorithmic match for you and you have not reached your quota of new introductions for the day, or you have paid to meet them. You can only record CV data to your own account. However, any app that you have OAuth'ed against can do so. By default, you will receive CV data that all apps have recorded fo[...]
      security:
        - explicit_flow:
            - profile_read
        - implicit_flow:
            - profile_read
      tags:
        - users
  "/users/{ID}/synergies":
    get:
      description: Determine your match relationship with one or more users who exist within the current access token's bubble. Under some conditions, the price to meet the user will be $0. However, if this is not the case, the PayPal URL payment method will be provided along with the price to meet the user. The PayPal API can be leveraged to send payments programatically, provided the parameters passed in remain the same to ensure that the payment is correctly recorded. Once the payment has bee[...]
      security:
        - explicit_flow:
            - profile_read
        - implicit_flow:
            - profile_read
      tags:
        - users
    patch:
      description: Skip, mute or unmute a user you've been matched with. Skipped matches are only presented as algorithmic matches after all other candidates have been exhausted. You cannot be matched with or meet muted users. You can only skip, mute or unmute users existing within the same bubble.
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - users
  /users/~:
    get:
      description: Retrieve the currently OAuth'ed end-user, based on the access token being used, including private information and settings such as their email address.
      security:
        - explicit_flow:
            - profile_read
        - implicit_flow:
            - profile_read
      tags:
        - users
    patch:
      description: Update the OAuth'ed end user's account profile. At this time, for anti-spam reasons, restrictions preclude the ability to update email address and some other settings via the API.
      security:
        - explicit_flow:
            - profile_read
            - profile_write
        - implicit_flow:
            - profile_read
            - profile_write
      tags:
        - users
  /webhooks:
    get:
      description: Fetch a listing of all webhooks owned by the current user/bubble combination.
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - webhooks
    post:
      description: Register a new webhook for the current user/bubble combination. Specify an object_id to only be notified on an event related to that specific Conversation ID, Group ID, or User ID. Your access token must have access to the user being tracked, user you are in the conversation with, or user who created the group. You must be connected with a user in order to keep track of their online status. Alternatively, do not specify an object_id to be notified on all events that are relate[...]
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - webhooks
  "/webhooks/{ID}":
    delete:
      description: Delete a webhook that was previously registered by the current user/bubble combination.
      security:
        - explicit_flow:
            - basic
        - implicit_flow:
            - basic
      tags:
        - webhooks
components:
  securitySchemes:
    explicit_flow:
      flows:
        authorizationCode:
          authorizationUrl: https://www.daniweb.com/connect/oauth/auth
          scopes:
            basic: "*Originally missing*"
            conversations_read: Access your DaniWeb conversations
            conversations_write: Manage your DaniWeb conversations
            groups_read: Access your DaniWeb groups
            groups_write: Manage your DaniWeb groups
            profile_read: Access your DaniWeb user profile
            profile_write: Manage your DaniWeb user profile
          tokenUrl: https://www.daniweb.com/connect/oauth/access_token
      type: oauth2
    implicit_flow:
      flows:
        implicit:
          authorizationUrl: https://www.daniweb.com/connect/oauth/auth
          scopes:
            basic: "*Originally missing*"
            conversations_read: Access your DaniWeb conversations
            conversations_write: Manage your DaniWeb conversations
            groups_read: Access your DaniWeb groups
            groups_write: Manage your DaniWeb groups
            profile_read: Access your DaniWeb user profile
            profile_write: Manage your DaniWeb user profile
      type: oauth2
