package shared

type RendererFormattedStrings struct {
	AuditGroupExpandTooltip          *string `json:"auditGroupExpandTooltip,omitempty"`
	CalculatorLink                   *string `json:"calculatorLink,omitempty"`
	CrcInitialNavigation             *string `json:"crcInitialNavigation,omitempty"`
	CrcLongestDurationLabel          *string `json:"crcLongestDurationLabel,omitempty"`
	DropdownCopyJSON                 *string `json:"dropdownCopyJSON,omitempty"`
	DropdownDarkTheme                *string `json:"dropdownDarkTheme,omitempty"`
	DropdownPrintExpanded            *string `json:"dropdownPrintExpanded,omitempty"`
	DropdownPrintSummary             *string `json:"dropdownPrintSummary,omitempty"`
	DropdownSaveGist                 *string `json:"dropdownSaveGist,omitempty"`
	DropdownSaveHTML                 *string `json:"dropdownSaveHTML,omitempty"`
	DropdownSaveJSON                 *string `json:"dropdownSaveJSON,omitempty"`
	DropdownViewer                   *string `json:"dropdownViewer,omitempty"`
	ErrorLabel                       *string `json:"errorLabel,omitempty"`
	ErrorMissingAuditInfo            *string `json:"errorMissingAuditInfo,omitempty"`
	FooterIssue                      *string `json:"footerIssue,omitempty"`
	LabDataTitle                     *string `json:"labDataTitle,omitempty"`
	LsPerformanceCategoryDescription *string `json:"lsPerformanceCategoryDescription,omitempty"`
	ManualAuditsGroupTitle           *string `json:"manualAuditsGroupTitle,omitempty"`
	NotApplicableAuditsGroupTitle    *string `json:"notApplicableAuditsGroupTitle,omitempty"`
	OpportunityResourceColumnLabel   *string `json:"opportunityResourceColumnLabel,omitempty"`
	OpportunitySavingsColumnLabel    *string `json:"opportunitySavingsColumnLabel,omitempty"`
	PassedAuditsGroupTitle           *string `json:"passedAuditsGroupTitle,omitempty"`
	RuntimeDesktopEmulation          *string `json:"runtimeDesktopEmulation,omitempty"`
	RuntimeMobileEmulation           *string `json:"runtimeMobileEmulation,omitempty"`
	RuntimeNoEmulation               *string `json:"runtimeNoEmulation,omitempty"`
	RuntimeSettingsAxeVersion        *string `json:"runtimeSettingsAxeVersion,omitempty"`
	RuntimeSettingsBenchmark         *string `json:"runtimeSettingsBenchmark,omitempty"`
	RuntimeSettingsCPUThrottling     *string `json:"runtimeSettingsCPUThrottling,omitempty"`
	RuntimeSettingsChannel           *string `json:"runtimeSettingsChannel,omitempty"`
	RuntimeSettingsDevice            *string `json:"runtimeSettingsDevice,omitempty"`
	RuntimeSettingsFetchTime         *string `json:"runtimeSettingsFetchTime,omitempty"`
	RuntimeSettingsNetworkThrottling *string `json:"runtimeSettingsNetworkThrottling,omitempty"`
	RuntimeSettingsTitle             *string `json:"runtimeSettingsTitle,omitempty"`
	RuntimeSettingsUa                *string `json:"runtimeSettingsUA,omitempty"`
	RuntimeSettingsUaNetwork         *string `json:"runtimeSettingsUANetwork,omitempty"`
	RuntimeSettingsURL               *string `json:"runtimeSettingsUrl,omitempty"`
	RuntimeUnknown                   *string `json:"runtimeUnknown,omitempty"`
	ScorescaleLabel                  *string `json:"scorescaleLabel,omitempty"`
	ShowRelevantAudits               *string `json:"showRelevantAudits,omitempty"`
	SnippetCollapseButtonLabel       *string `json:"snippetCollapseButtonLabel,omitempty"`
	SnippetExpandButtonLabel         *string `json:"snippetExpandButtonLabel,omitempty"`
	ThirdPartyResourcesLabel         *string `json:"thirdPartyResourcesLabel,omitempty"`
	ThrottlingProvided               *string `json:"throttlingProvided,omitempty"`
	ToplevelWarningsMessage          *string `json:"toplevelWarningsMessage,omitempty"`
	VarianceDisclaimer               *string `json:"varianceDisclaimer,omitempty"`
	ViewTreemapLabel                 *string `json:"viewTreemapLabel,omitempty"`
	WarningAuditsGroupTitle          *string `json:"warningAuditsGroupTitle,omitempty"`
	WarningHeader                    *string `json:"warningHeader,omitempty"`
}
