# coding: utf-8

"""
    Bare Metal Solution API

    Provides ways to manage Bare Metal Solution hardware installed in a regional extension located near a Google Cloud data center.

    The version of the OpenAPI document: v2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.google_cloud_baremetalsolution_v2_server_network_template_logical_interface import GoogleCloudBaremetalsolutionV2ServerNetworkTemplateLogicalInterface
from typing import Optional, Set
from typing_extensions import Self

class ServerNetworkTemplate(BaseModel):
    """
    Network template.
    """ # noqa: E501
    applicable_instance_types: Optional[List[StrictStr]] = Field(default=None, description="Instance types this template is applicable to.", alias="applicableInstanceTypes")
    logical_interfaces: Optional[List[GoogleCloudBaremetalsolutionV2ServerNetworkTemplateLogicalInterface]] = Field(default=None, description="Logical interfaces.", alias="logicalInterfaces")
    name: Optional[StrictStr] = Field(default=None, description="Output only. Template's unique name. The full resource name follows the pattern: `projects/{project}/locations/{location}/serverNetworkTemplate/{server_network_template}` Generally, the {server_network_template} follows the syntax of \"bond\" or \"nic\".")
    __properties: ClassVar[List[str]] = ["applicableInstanceTypes", "logicalInterfaces", "name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServerNetworkTemplate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "name",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in logical_interfaces (list)
        _items = []
        if self.logical_interfaces:
            for _item_logical_interfaces in self.logical_interfaces:
                if _item_logical_interfaces:
                    _items.append(_item_logical_interfaces.to_dict())
            _dict['logicalInterfaces'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServerNetworkTemplate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "applicableInstanceTypes": obj.get("applicableInstanceTypes"),
            "logicalInterfaces": [GoogleCloudBaremetalsolutionV2ServerNetworkTemplateLogicalInterface.from_dict(_item) for _item in obj["logicalInterfaces"]] if obj.get("logicalInterfaces") is not None else None,
            "name": obj.get("name")
        })
        return _obj


