# coding: utf-8

"""
    StorSimpleManagementClient

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2016-10-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.available_provider_operation_display import AvailableProviderOperationDisplay
from typing import Optional, Set
from typing_extensions import Self

class AvailableProviderOperation(BaseModel):
    """
    Class represents provider operation
    """ # noqa: E501
    display: Optional[AvailableProviderOperationDisplay] = None
    name: Optional[StrictStr] = Field(default=None, description="Gets or sets the name of the operation being performed on this particular object  Return value format: \"{resourceProviderNamespace}/{resourceType}/{read|write|deletion|action}\"  Eg: Microsoft.StorSimple/managers/devices/fileServers/read      Microsoft.StorSimple/managers/devices/alerts/clearAlerts/action")
    origin: Optional[StrictStr] = Field(default=None, description="Gets or sets Origin  The intended executor of the operation; governs the display of the operation in the RBAC UX and the audit logs UX.  Default value is “user,system”")
    properties: Optional[Dict[str, Any]] = Field(default=None, description="Class represents Properties in AvailableProviderOperations")
    __properties: ClassVar[List[str]] = ["display", "name", "origin", "properties"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AvailableProviderOperation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of display
        if self.display:
            _dict['display'] = self.display.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AvailableProviderOperation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "display": AvailableProviderOperationDisplay.from_dict(obj["display"]) if obj.get("display") is not None else None,
            "name": obj.get("name"),
            "origin": obj.get("origin"),
            "properties": obj.get("properties")
        })
        return _obj


