{
  "swagger": "2.0",
  "info": {
    "title": "Replica Pool API",
    "x-serviceName": "replicapool",
    "description": "The Replica Pool API allows users to declaratively provision and manage groups of Google Compute Engine instances based on a common template.",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v1beta1",
    "x-origin": {
      "format": "google",
      "version": "v1",
      "uri": "https://www.googleapis.com/discovery/v1/apis/replicapool/v1beta1/rest"
    }
  },
  "host": "www.googleapis.com",
  "basePath": "/replicapool/v1beta1/projects",
  "schemes": [
    "https"
  ],
  "paths": {
    "/{projectName}/zones/{zone}/pools/{poolName}": {
      "post": {
        "description": "Deletes a replica pool.",
        "operationId": "replicapool.pools.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/ndev.cloudman",
              "https://www.googleapis.com/auth/replicapool"
            ]
          }
        ],
        "tags": [
          "pools"
        ]
      },
      "get": {
        "description": "Gets information about a single replica pool.",
        "operationId": "replicapool.pools.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/ndev.cloudman",
              "https://www.googleapis.com/auth/ndev.cloudman.readonly",
              "https://www.googleapis.com/auth/replicapool",
              "https://www.googleapis.com/auth/replicapool.readonly"
            ]
          }
        ],
        "tags": [
          "pools"
        ]
      }
    },
    "/{projectName}/zones/{zone}/pools": {
      "post": {
        "description": "Inserts a new replica pool.",
        "operationId": "replicapool.pools.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/ndev.cloudman",
              "https://www.googleapis.com/auth/replicapool"
            ]
          }
        ],
        "tags": [
          "pools"
        ]
      },
      "get": {
        "description": "List all replica pools.",
        "operationId": "replicapool.pools.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/ndev.cloudman",
              "https://www.googleapis.com/auth/ndev.cloudman.readonly",
              "https://www.googleapis.com/auth/replicapool",
              "https://www.googleapis.com/auth/replicapool.readonly"
            ]
          }
        ],
        "tags": [
          "pools"
        ]
      }
    },
    "/{projectName}/zones/{zone}/pools/{poolName}/resize": {
      "post": {
        "description": "Resize a pool. This is an asynchronous operation, and multiple overlapping resize requests can be made. Replica Pools will use the information from the last resize request.",
        "operationId": "replicapool.pools.resize",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/ndev.cloudman",
              "https://www.googleapis.com/auth/replicapool"
            ]
          }
        ],
        "tags": [
          "pools"
        ]
      }
    },
    "/{projectName}/zones/{zone}/pools/{poolName}/updateTemplate": {
      "post": {
        "description": "Update the template used by the pool.",
        "operationId": "replicapool.pools.updatetemplate",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/ndev.cloudman",
              "https://www.googleapis.com/auth/replicapool"
            ]
          }
        ],
        "tags": [
          "pools"
        ]
      }
    },
    "/{projectName}/zones/{zone}/pools/{poolName}/replicas/{replicaName}": {
      "post": {
        "description": "Deletes a replica from the pool.",
        "operationId": "replicapool.replicas.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/ndev.cloudman",
              "https://www.googleapis.com/auth/replicapool"
            ]
          }
        ],
        "tags": [
          "replicas"
        ]
      },
      "get": {
        "description": "Gets information about a specific replica.",
        "operationId": "replicapool.replicas.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/ndev.cloudman",
              "https://www.googleapis.com/auth/ndev.cloudman.readonly",
              "https://www.googleapis.com/auth/replicapool",
              "https://www.googleapis.com/auth/replicapool.readonly"
            ]
          }
        ],
        "tags": [
          "replicas"
        ]
      }
    },
    "/{projectName}/zones/{zone}/pools/{poolName}/replicas": {
      "get": {
        "description": "Lists all replicas in a pool.",
        "operationId": "replicapool.replicas.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/ndev.cloudman",
              "https://www.googleapis.com/auth/ndev.cloudman.readonly",
              "https://www.googleapis.com/auth/replicapool",
              "https://www.googleapis.com/auth/replicapool.readonly"
            ]
          }
        ],
        "tags": [
          "replicas"
        ]
      }
    },
    "/{projectName}/zones/{zone}/pools/{poolName}/replicas/{replicaName}/restart": {
      "post": {
        "description": "Restarts a replica in a pool.",
        "operationId": "replicapool.replicas.restart",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/ndev.cloudman",
              "https://www.googleapis.com/auth/replicapool"
            ]
          }
        ],
        "tags": [
          "replicas"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/cloud-platform": "View and manage your data across Google Cloud Platform services",
        "https://www.googleapis.com/auth/ndev.cloudman": "View and manage your Google Cloud Platform management resources and deployment status information",
        "https://www.googleapis.com/auth/ndev.cloudman.readonly": "View your Google Cloud Platform management resources and deployment status information",
        "https://www.googleapis.com/auth/replicapool": "View and manage replica pools",
        "https://www.googleapis.com/auth/replicapool.readonly": "View replica pools"
      }
    }
  }
}