swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /tagmanager/v1
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Accesses Tag Manager accounts and containers.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Tag Manager
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/tagmanager/v1/rest'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: tagmanager
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/tagmanager.delete.containers': Delete your Google Tag Manager containers
      'https://www.googleapis.com/auth/tagmanager.edit.containers': 'Manage your Google Tag Manager container and its subcomponents, excluding versioning and publishing'
      'https://www.googleapis.com/auth/tagmanager.edit.containerversions': Manage your Google Tag Manager container versions
      'https://www.googleapis.com/auth/tagmanager.manage.accounts': View and manage your Google Tag Manager accounts
      'https://www.googleapis.com/auth/tagmanager.manage.users': Manage user permissions of your Google Tag Manager account and container
      'https://www.googleapis.com/auth/tagmanager.publish': Publish your Google Tag Manager container versions
      'https://www.googleapis.com/auth/tagmanager.readonly': View your Google Tag Manager container and its subcomponents
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/tagmanager.delete.containers': Delete your Google Tag Manager containers
      'https://www.googleapis.com/auth/tagmanager.edit.containers': 'Manage your Google Tag Manager container and its subcomponents, excluding versioning and publishing'
      'https://www.googleapis.com/auth/tagmanager.edit.containerversions': Manage your Google Tag Manager container versions
      'https://www.googleapis.com/auth/tagmanager.manage.accounts': View and manage your Google Tag Manager accounts
      'https://www.googleapis.com/auth/tagmanager.manage.users': Manage user permissions of your Google Tag Manager account and container
      'https://www.googleapis.com/auth/tagmanager.publish': Publish your Google Tag Manager container versions
      'https://www.googleapis.com/auth/tagmanager.readonly': View your Google Tag Manager container and its subcomponents
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: accounts
paths:
  /accounts:
    get:
      description: Lists all GTM Accounts that a user has access to.
      operationId: tagmanager.accounts.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.manage.accounts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.manage.accounts'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
      tags:
        - accounts
  '/accounts/{accountId}':
    get:
      description: Gets a GTM Account.
      operationId: tagmanager.accounts.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.manage.accounts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.manage.accounts'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
      tags:
        - accounts
    put:
      description: Updates a GTM Account.
      operationId: tagmanager.accounts.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.manage.accounts'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.manage.accounts'
      tags:
        - accounts
  '/accounts/{accountId}/containers':
    get:
      description: Lists all Containers that belongs to a GTM Account.
      operationId: tagmanager.accounts.containers.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
      tags:
        - accounts
    post:
      description: Creates a Container.
      operationId: tagmanager.accounts.containers.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
      tags:
        - accounts
  '/accounts/{accountId}/containers/{containerId}':
    delete:
      description: Deletes a Container.
      operationId: tagmanager.accounts.containers.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.delete.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.delete.containers'
      tags:
        - accounts
    get:
      description: Gets a Container.
      operationId: tagmanager.accounts.containers.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
      tags:
        - accounts
    put:
      description: Updates a Container.
      operationId: tagmanager.accounts.containers.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
      tags:
        - accounts
  '/accounts/{accountId}/containers/{containerId}/environments':
    get:
      description: Lists all GTM Environments of a GTM Container.
      operationId: tagmanager.accounts.containers.environments.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
      tags:
        - accounts
    post:
      description: Creates a GTM Environment.
      operationId: tagmanager.accounts.containers.environments.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
      tags:
        - accounts
  '/accounts/{accountId}/containers/{containerId}/environments/{environmentId}':
    delete:
      description: Deletes a GTM Environment.
      operationId: tagmanager.accounts.containers.environments.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
      tags:
        - accounts
    get:
      description: Gets a GTM Environment.
      operationId: tagmanager.accounts.containers.environments.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
      tags:
        - accounts
    patch:
      description: Updates a GTM Environment. This method supports patch semantics.
      operationId: tagmanager.accounts.containers.environments.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
      tags:
        - accounts
    put:
      description: Updates a GTM Environment.
      operationId: tagmanager.accounts.containers.environments.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
      tags:
        - accounts
  '/accounts/{accountId}/containers/{containerId}/folders':
    get:
      description: Lists all GTM Folders of a Container.
      operationId: tagmanager.accounts.containers.folders.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
      tags:
        - accounts
    post:
      description: Creates a GTM Folder.
      operationId: tagmanager.accounts.containers.folders.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
      tags:
        - accounts
  '/accounts/{accountId}/containers/{containerId}/folders/{folderId}':
    delete:
      description: Deletes a GTM Folder.
      operationId: tagmanager.accounts.containers.folders.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
      tags:
        - accounts
    get:
      description: Gets a GTM Folder.
      operationId: tagmanager.accounts.containers.folders.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
      tags:
        - accounts
    put:
      description: Updates a GTM Folder.
      operationId: tagmanager.accounts.containers.folders.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
      tags:
        - accounts
  '/accounts/{accountId}/containers/{containerId}/folders/{folderId}/entities':
    get:
      description: List all entities in a GTM Folder.
      operationId: tagmanager.accounts.containers.folders.entities.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
      tags:
        - accounts
  '/accounts/{accountId}/containers/{containerId}/move_folders/{folderId}':
    put:
      description: Moves entities to a GTM Folder.
      operationId: tagmanager.accounts.containers.move_folders.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
      tags:
        - accounts
  '/accounts/{accountId}/containers/{containerId}/reauthorize_environments/{environmentId}':
    put:
      description: Re-generates the authorization code for a GTM Environment.
      operationId: tagmanager.accounts.containers.reauthorize_environments.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.publish'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.publish'
      tags:
        - accounts
  '/accounts/{accountId}/containers/{containerId}/tags':
    get:
      description: Lists all GTM Tags of a Container.
      operationId: tagmanager.accounts.containers.tags.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
      tags:
        - accounts
    post:
      description: Creates a GTM Tag.
      operationId: tagmanager.accounts.containers.tags.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
      tags:
        - accounts
  '/accounts/{accountId}/containers/{containerId}/tags/{tagId}':
    delete:
      description: Deletes a GTM Tag.
      operationId: tagmanager.accounts.containers.tags.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
      tags:
        - accounts
    get:
      description: Gets a GTM Tag.
      operationId: tagmanager.accounts.containers.tags.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
      tags:
        - accounts
    put:
      description: Updates a GTM Tag.
      operationId: tagmanager.accounts.containers.tags.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
      tags:
        - accounts
  '/accounts/{accountId}/containers/{containerId}/triggers':
    get:
      description: Lists all GTM Triggers of a Container.
      operationId: tagmanager.accounts.containers.triggers.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
      tags:
        - accounts
    post:
      description: Creates a GTM Trigger.
      operationId: tagmanager.accounts.containers.triggers.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
      tags:
        - accounts
  '/accounts/{accountId}/containers/{containerId}/triggers/{triggerId}':
    delete:
      description: Deletes a GTM Trigger.
      operationId: tagmanager.accounts.containers.triggers.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
      tags:
        - accounts
    get:
      description: Gets a GTM Trigger.
      operationId: tagmanager.accounts.containers.triggers.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
      tags:
        - accounts
    put:
      description: Updates a GTM Trigger.
      operationId: tagmanager.accounts.containers.triggers.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
      tags:
        - accounts
  '/accounts/{accountId}/containers/{containerId}/variables':
    get:
      description: Lists all GTM Variables of a Container.
      operationId: tagmanager.accounts.containers.variables.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
      tags:
        - accounts
    post:
      description: Creates a GTM Variable.
      operationId: tagmanager.accounts.containers.variables.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
      tags:
        - accounts
  '/accounts/{accountId}/containers/{containerId}/variables/{variableId}':
    delete:
      description: Deletes a GTM Variable.
      operationId: tagmanager.accounts.containers.variables.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
      tags:
        - accounts
    get:
      description: Gets a GTM Variable.
      operationId: tagmanager.accounts.containers.variables.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
      tags:
        - accounts
    put:
      description: Updates a GTM Variable.
      operationId: tagmanager.accounts.containers.variables.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
      tags:
        - accounts
  '/accounts/{accountId}/containers/{containerId}/versions':
    get:
      description: Lists all Container Versions of a GTM Container.
      operationId: tagmanager.accounts.containers.versions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containerversions'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containerversions'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
      tags:
        - accounts
    post:
      description: Creates a Container Version.
      operationId: tagmanager.accounts.containers.versions.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containerversions'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containerversions'
      tags:
        - accounts
  '/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}':
    delete:
      description: Deletes a Container Version.
      operationId: tagmanager.accounts.containers.versions.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containerversions'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containerversions'
      tags:
        - accounts
    get:
      description: Gets a Container Version.
      operationId: tagmanager.accounts.containers.versions.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containerversions'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containerversions'
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.readonly'
      tags:
        - accounts
    put:
      description: Updates a Container Version.
      operationId: tagmanager.accounts.containers.versions.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containerversions'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containerversions'
      tags:
        - accounts
  '/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/publish':
    post:
      description: Publishes a Container Version.
      operationId: tagmanager.accounts.containers.versions.publish
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.publish'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.publish'
      tags:
        - accounts
  '/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/restore':
    post:
      description: 'Restores a Container Version. This will overwrite the container''s current configuration (including its variables, triggers and tags). The operation will not have any effect on the version that is being served (i.e. the published version).'
      operationId: tagmanager.accounts.containers.versions.restore
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containers'
      tags:
        - accounts
  '/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/undelete':
    post:
      description: Undeletes a Container Version.
      operationId: tagmanager.accounts.containers.versions.undelete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containerversions'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.edit.containerversions'
      tags:
        - accounts
  '/accounts/{accountId}/permissions':
    get:
      description: List all users that have access to the account along with Account and Container Permissions granted to each of them.
      operationId: tagmanager.accounts.permissions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.manage.users'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.manage.users'
      tags:
        - accounts
    post:
      description: Creates a user's Account & Container Permissions.
      operationId: tagmanager.accounts.permissions.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.manage.users'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.manage.users'
      tags:
        - accounts
  '/accounts/{accountId}/permissions/{permissionId}':
    delete:
      description: 'Removes a user from the account, revoking access to it and all of its containers.'
      operationId: tagmanager.accounts.permissions.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.manage.users'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.manage.users'
      tags:
        - accounts
    get:
      description: Gets a user's Account & Container Permissions.
      operationId: tagmanager.accounts.permissions.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.manage.users'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.manage.users'
      tags:
        - accounts
    put:
      description: Updates a user's Account & Container Permissions.
      operationId: tagmanager.accounts.permissions.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/tagmanager.manage.users'
          Oauth2c:
            - 'https://www.googleapis.com/auth/tagmanager.manage.users'
      tags:
        - accounts