# coding: utf-8

"""
    Azure Media Services

    Streaming resource management client for Azure Media Services

    The version of the OpenAPI document: 2018-03-30-preview
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.live_events_list_default_response import LiveEventsListDefaultResponse

class TestLiveEventsListDefaultResponse(unittest.TestCase):
    """LiveEventsListDefaultResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LiveEventsListDefaultResponse:
        """Test LiveEventsListDefaultResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LiveEventsListDefaultResponse`
        """
        model = LiveEventsListDefaultResponse()
        if include_optional:
            return LiveEventsListDefaultResponse(
                error = openapi_client.models.live_events_list_default_response_error.LiveEvents_List_default_response_error(
                    code = '', 
                    details = [
                        openapi_client.models.o_data_error.ODataError()
                        ], 
                    message = '', 
                    target = '', )
            )
        else:
            return LiveEventsListDefaultResponse(
        )
        """

    def testLiveEventsListDefaultResponse(self):
        """Test LiveEventsListDefaultResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
