package shared

import (
	"time"
)

type CommitteeTotals struct {
	AllLoansReceived                               *float64   `json:"all_loans_received"`
	AllOtherLoans                                  *float64   `json:"all_other_loans"`
	AllocatedFederalElectionLevinShare             *float64   `json:"allocated_federal_election_levin_share"`
	CandidateContribution                          *float64   `json:"candidate_contribution"`
	CashOnHandBeginningPeriod                      *float64   `json:"cash_on_hand_beginning_period"`
	CommitteeDesignation                           *string    `json:"committee_designation"`
	CommitteeDesignationFull                       *string    `json:"committee_designation_full"`
	CommitteeID                                    *string    `json:"committee_id"`
	CommitteeName                                  *string    `json:"committee_name"`
	CommitteeState                                 *string    `json:"committee_state"`
	CommitteeType                                  *string    `json:"committee_type"`
	CommitteeTypeFull                              *string    `json:"committee_type_full"`
	ContributionRefunds                            *float64   `json:"contribution_refunds"`
	Contributions                                  *float64   `json:"contributions"`
	ContributionsIeAndPartyExpendituresMadePercent *float64   `json:"contributions_ie_and_party_expenditures_made_percent"`
	ConventionExp                                  *float64   `json:"convention_exp"`
	CoordinatedExpendituresByPartyCommittee        *float64   `json:"coordinated_expenditures_by_party_committee"`
	CoverageEndDate                                *time.Time `json:"coverage_end_date"`
	CoverageStartDate                              *time.Time `json:"coverage_start_date"`
	Cycle                                          int32      `json:"cycle"`
	Disbursements                                  *float64   `json:"disbursements"`
	ExemptLegalAccountingDisbursement              *float64   `json:"exempt_legal_accounting_disbursement"`
	ExpPriorYearsSubjectLimits                     *float64   `json:"exp_prior_years_subject_limits"`
	ExpSubjectLimits                               *float64   `json:"exp_subject_limits"`
	FedCandidateCommitteeContributions             *float64   `json:"fed_candidate_committee_contributions"`
	FedCandidateContributionRefunds                *float64   `json:"fed_candidate_contribution_refunds"`
	FedDisbursements                               *float64   `json:"fed_disbursements"`
	FedElectionActivity                            *float64   `json:"fed_election_activity"`
	FedOperatingExpenditures                       *float64   `json:"fed_operating_expenditures"`
	FedReceipts                                    *float64   `json:"fed_receipts"`
	FederalFunds                                   *float64   `json:"federal_funds"`
	FilingFrequency                                *string    `json:"filing_frequency"`
	FilingFrequencyFull                            *string    `json:"filing_frequency_full"`
	FirstFileDate                                  *time.Time `json:"first_file_date"`
	FundraisingDisbursements                       *float64   `json:"fundraising_disbursements"`
	IndependentExpenditures                        *float64   `json:"independent_expenditures"`
	IndividualContributions                        *float64   `json:"individual_contributions"`
	IndividualContributionsPercent                 *float64   `json:"individual_contributions_percent"`
	IndividualItemizedContributions                *float64   `json:"individual_itemized_contributions"`
	IndividualUnitemizedContributions              *float64   `json:"individual_unitemized_contributions"`
	ItemizedConventionExp                          *float64   `json:"itemized_convention_exp"`
	ItemizedOtherDisb                              *float64   `json:"itemized_other_disb"`
	ItemizedOtherIncome                            *float64   `json:"itemized_other_income"`
	ItemizedOtherRefunds                           *float64   `json:"itemized_other_refunds"`
	ItemizedRefundsRelatingConventionExp           *float64   `json:"itemized_refunds_relating_convention_exp"`
	LastBeginningImageNumber                       *string    `json:"last_beginning_image_number"`
	LastCashOnHandEndPeriod                        *float64   `json:"last_cash_on_hand_end_period"`
	LastDebtsOwedByCommittee                       *float64   `json:"last_debts_owed_by_committee"`
	LastDebtsOwedToCommittee                       *float64   `json:"last_debts_owed_to_committee"`
	LastReportTypeFull                             *string    `json:"last_report_type_full"`
	LastReportYear                                 *int32     `json:"last_report_year"`
	LoanRepayments                                 *float64   `json:"loan_repayments"`
	LoanRepaymentsCandidateLoans                   *float64   `json:"loan_repayments_candidate_loans"`
	LoanRepaymentsMade                             *float64   `json:"loan_repayments_made"`
	LoanRepaymentsOtherLoans                       *float64   `json:"loan_repayments_other_loans"`
	LoanRepaymentsReceived                         *float64   `json:"loan_repayments_received"`
	Loans                                          *float64   `json:"loans"`
	LoansAndLoanRepaymentsMade                     *float64   `json:"loans_and_loan_repayments_made"`
	LoansAndLoanRepaymentsReceived                 *float64   `json:"loans_and_loan_repayments_received"`
	LoansMade                                      *float64   `json:"loans_made"`
	LoansMadeByCandidate                           *float64   `json:"loans_made_by_candidate"`
	LoansReceived                                  *float64   `json:"loans_received"`
	LoansReceivedFromCandidate                     *float64   `json:"loans_received_from_candidate"`
	NetContributions                               *float64   `json:"net_contributions"`
	NetOperatingExpenditures                       *float64   `json:"net_operating_expenditures"`
	NonAllocatedFedElectionActivity                *float64   `json:"non_allocated_fed_election_activity"`
	OffsetsToFundraisingExpenditures               *float64   `json:"offsets_to_fundraising_expenditures"`
	OffsetsToLegalAccounting                       *float64   `json:"offsets_to_legal_accounting"`
	OffsetsToOperatingExpenditures                 *float64   `json:"offsets_to_operating_expenditures"`
	OperatingExpenditures                          *float64   `json:"operating_expenditures"`
	OperatingExpendituresPercent                   *float64   `json:"operating_expenditures_percent"`
	OrganizationType                               *string    `json:"organization_type"`
	OrganizationTypeFull                           *string    `json:"organization_type_full"`
	OtherDisbursements                             *float64   `json:"other_disbursements"`
	OtherFedOperatingExpenditures                  *float64   `json:"other_fed_operating_expenditures"`
	OtherFedReceipts                               *float64   `json:"other_fed_receipts"`
	OtherLoansReceived                             *float64   `json:"other_loans_received"`
	OtherPoliticalCommitteeContributions           *float64   `json:"other_political_committee_contributions"`
	OtherReceipts                                  *float64   `json:"other_receipts"`
	OtherRefunds                                   *float64   `json:"other_refunds"`
	PartyAndOtherCommitteeContributionsPercent     *float64   `json:"party_and_other_committee_contributions_percent"`
	PartyFull                                      *string    `json:"party_full"`
	PdfURL                                         *string    `json:"pdf_url"`
	PoliticalPartyCommitteeContributions           *float64   `json:"political_party_committee_contributions"`
	Receipts                                       *float64   `json:"receipts"`
	RefundedIndividualContributions                *float64   `json:"refunded_individual_contributions"`
	RefundedOtherPoliticalCommitteeContributions   *float64   `json:"refunded_other_political_committee_contributions"`
	RefundedPoliticalPartyCommitteeContributions   *float64   `json:"refunded_political_party_committee_contributions"`
	RefundsRelatingConventionExp                   *float64   `json:"refunds_relating_convention_exp"`
	RepaymentsLoansMadeByCandidate                 *float64   `json:"repayments_loans_made_by_candidate"`
	RepaymentsOtherLoans                           *float64   `json:"repayments_other_loans"`
	ReportForm                                     *string    `json:"report_form"`
	SharedFedActivity                              *float64   `json:"shared_fed_activity"`
	SharedFedActivityNonfed                        *float64   `json:"shared_fed_activity_nonfed"`
	SharedFedOperatingExpenditures                 *float64   `json:"shared_fed_operating_expenditures"`
	SharedNonfedOperatingExpenditures              *float64   `json:"shared_nonfed_operating_expenditures"`
	TotalExpSubjectLimits                          *float64   `json:"total_exp_subject_limits"`
	TotalIndependentContributions                  *float64   `json:"total_independent_contributions"`
	TotalIndependentExpenditures                   *float64   `json:"total_independent_expenditures"`
	TotalOffsetsToOperatingExpenditures            *float64   `json:"total_offsets_to_operating_expenditures"`
	TotalTransfers                                 *float64   `json:"total_transfers"`
	TransactionCoverageDate                        *time.Time `json:"transaction_coverage_date"`
	TransfersFromAffiliatedCommittee               *float64   `json:"transfers_from_affiliated_committee"`
	TransfersFromAffiliatedParty                   *float64   `json:"transfers_from_affiliated_party"`
	TransfersFromNonfedAccount                     *float64   `json:"transfers_from_nonfed_account"`
	TransfersFromNonfedLevin                       *float64   `json:"transfers_from_nonfed_levin"`
	TransfersFromOtherAuthorizedCommittee          *float64   `json:"transfers_from_other_authorized_committee"`
	TransfersToAffiliatedCommittee                 *float64   `json:"transfers_to_affiliated_committee"`
	TransfersToOtherAuthorizedCommittee            *float64   `json:"transfers_to_other_authorized_committee"`
	TreasurerName                                  *string    `json:"treasurer_name"`
	UnitemizedConventionExp                        *float64   `json:"unitemized_convention_exp"`
	UnitemizedOtherDisb                            *float64   `json:"unitemized_other_disb"`
	UnitemizedOtherIncome                          *float64   `json:"unitemized_other_income"`
	UnitemizedOtherRefunds                         *float64   `json:"unitemized_other_refunds"`
	UnitemizedRefundsRelatingConventionExp         *float64   `json:"unitemized_refunds_relating_convention_exp"`
}
