package shared

import (
	"time"
)

type ScheduleA struct {
	AmendmentIndicator                 *string           `json:"amendment_indicator,omitempty"`
	AmendmentIndicatorDesc             *string           `json:"amendment_indicator_desc,omitempty"`
	BackReferenceScheduleName          *string           `json:"back_reference_schedule_name,omitempty"`
	BackReferenceTransactionID         *string           `json:"back_reference_transaction_id,omitempty"`
	CandidateFirstName                 *string           `json:"candidate_first_name,omitempty"`
	CandidateID                        *string           `json:"candidate_id,omitempty"`
	CandidateLastName                  *string           `json:"candidate_last_name,omitempty"`
	CandidateMiddleName                *string           `json:"candidate_middle_name,omitempty"`
	CandidateName                      *string           `json:"candidate_name,omitempty"`
	CandidateOffice                    *string           `json:"candidate_office,omitempty"`
	CandidateOfficeDistrict            *string           `json:"candidate_office_district,omitempty"`
	CandidateOfficeFull                *string           `json:"candidate_office_full,omitempty"`
	CandidateOfficeState               *string           `json:"candidate_office_state,omitempty"`
	CandidateOfficeStateFull           *string           `json:"candidate_office_state_full,omitempty"`
	CandidatePrefix                    *string           `json:"candidate_prefix,omitempty"`
	CandidateSuffix                    *string           `json:"candidate_suffix,omitempty"`
	Committee                          *CommitteeHistory `json:"committee,omitempty"`
	CommitteeID                        *string           `json:"committee_id,omitempty"`
	CommitteeName                      *string           `json:"committee_name,omitempty"`
	ConduitCommitteeCity               *string           `json:"conduit_committee_city,omitempty"`
	ConduitCommitteeID                 *string           `json:"conduit_committee_id,omitempty"`
	ConduitCommitteeName               *string           `json:"conduit_committee_name,omitempty"`
	ConduitCommitteeState              *string           `json:"conduit_committee_state,omitempty"`
	ConduitCommitteeStreet1            *string           `json:"conduit_committee_street1,omitempty"`
	ConduitCommitteeStreet2            *string           `json:"conduit_committee_street2,omitempty"`
	ConduitCommitteeZip                *int32            `json:"conduit_committee_zip,omitempty"`
	ContributionReceiptAmount          *float64          `json:"contribution_receipt_amount,omitempty"`
	ContributionReceiptDate            *time.Time        `json:"contribution_receipt_date,omitempty"`
	Contributor                        *CommitteeHistory `json:"contributor,omitempty"`
	ContributorAggregateYtd            *float64          `json:"contributor_aggregate_ytd,omitempty"`
	ContributorCity                    *string           `json:"contributor_city,omitempty"`
	ContributorEmployer                *string           `json:"contributor_employer,omitempty"`
	ContributorFirstName               *string           `json:"contributor_first_name,omitempty"`
	ContributorID                      *string           `json:"contributor_id,omitempty"`
	ContributorLastName                *string           `json:"contributor_last_name,omitempty"`
	ContributorMiddleName              *string           `json:"contributor_middle_name,omitempty"`
	ContributorName                    *string           `json:"contributor_name,omitempty"`
	ContributorOccupation              *string           `json:"contributor_occupation,omitempty"`
	ContributorPrefix                  *string           `json:"contributor_prefix,omitempty"`
	ContributorState                   *string           `json:"contributor_state,omitempty"`
	ContributorStreet1                 *string           `json:"contributor_street_1,omitempty"`
	ContributorStreet2                 *string           `json:"contributor_street_2,omitempty"`
	ContributorSuffix                  *string           `json:"contributor_suffix,omitempty"`
	ContributorZip                     *string           `json:"contributor_zip,omitempty"`
	DonorCommitteeName                 *string           `json:"donor_committee_name,omitempty"`
	ElectionType                       *string           `json:"election_type,omitempty"`
	ElectionTypeFull                   *string           `json:"election_type_full,omitempty"`
	EntityType                         *string           `json:"entity_type,omitempty"`
	EntityTypeDesc                     *string           `json:"entity_type_desc,omitempty"`
	FecElectionTypeDesc                *string           `json:"fec_election_type_desc,omitempty"`
	FecElectionYear                    *string           `json:"fec_election_year,omitempty"`
	FileNumber                         *int32            `json:"file_number,omitempty"`
	FilingForm                         *string           `json:"filing_form,omitempty"`
	ImageNumber                        *string           `json:"image_number,omitempty"`
	IncreasedLimit                     *string           `json:"increased_limit,omitempty"`
	IsIndividual                       *bool             `json:"is_individual,omitempty"`
	LineNumber                         *string           `json:"line_number,omitempty"`
	LineNumberLabel                    *string           `json:"line_number_label,omitempty"`
	LinkID                             *int32            `json:"link_id,omitempty"`
	LoadDate                           *time.Time        `json:"load_date,omitempty"`
	MemoCode                           *string           `json:"memo_code,omitempty"`
	MemoCodeFull                       *string           `json:"memo_code_full,omitempty"`
	MemoText                           *string           `json:"memo_text,omitempty"`
	MemoedSubtotal                     *bool             `json:"memoed_subtotal,omitempty"`
	NationalCommitteeNonfederalAccount *string           `json:"national_committee_nonfederal_account,omitempty"`
	OriginalSubID                      *string           `json:"original_sub_id,omitempty"`
	PdfURL                             *string           `json:"pdf_url,omitempty"`
	ReceiptType                        *string           `json:"receipt_type,omitempty"`
	ReceiptTypeDesc                    *string           `json:"receipt_type_desc,omitempty"`
	ReceiptTypeFull                    *string           `json:"receipt_type_full,omitempty"`
	RecipientCommitteeDesignation      *string           `json:"recipient_committee_designation,omitempty"`
	RecipientCommitteeOrgType          *string           `json:"recipient_committee_org_type,omitempty"`
	RecipientCommitteeType             *string           `json:"recipient_committee_type,omitempty"`
	ReportType                         *string           `json:"report_type,omitempty"`
	ReportYear                         *int32            `json:"report_year,omitempty"`
	ScheduleType                       *string           `json:"schedule_type,omitempty"`
	ScheduleTypeFull                   *string           `json:"schedule_type_full,omitempty"`
	SubID                              *string           `json:"sub_id,omitempty"`
	TransactionID                      *string           `json:"transaction_id,omitempty"`
	TwoYearTransactionPeriod           *int32            `json:"two_year_transaction_period,omitempty"`
	UnusedContbrID                     *string           `json:"unused_contbr_id,omitempty"`
}
