package shared

import (
	"time"
)

type ScheduleA struct {
	AmendmentIndicator                 *string           `json:"amendment_indicator"`
	AmendmentIndicatorDesc             *string           `json:"amendment_indicator_desc"`
	BackReferenceScheduleName          *string           `json:"back_reference_schedule_name"`
	BackReferenceTransactionID         *string           `json:"back_reference_transaction_id"`
	CandidateFirstName                 *string           `json:"candidate_first_name"`
	CandidateID                        *string           `json:"candidate_id"`
	CandidateLastName                  *string           `json:"candidate_last_name"`
	CandidateMiddleName                *string           `json:"candidate_middle_name"`
	CandidateName                      *string           `json:"candidate_name"`
	CandidateOffice                    *string           `json:"candidate_office"`
	CandidateOfficeDistrict            *string           `json:"candidate_office_district"`
	CandidateOfficeFull                *string           `json:"candidate_office_full"`
	CandidateOfficeState               *string           `json:"candidate_office_state"`
	CandidateOfficeStateFull           *string           `json:"candidate_office_state_full"`
	CandidatePrefix                    *string           `json:"candidate_prefix"`
	CandidateSuffix                    *string           `json:"candidate_suffix"`
	Committee                          *CommitteeHistory `json:"committee"`
	CommitteeID                        *string           `json:"committee_id"`
	CommitteeName                      *string           `json:"committee_name"`
	ConduitCommitteeCity               *string           `json:"conduit_committee_city"`
	ConduitCommitteeID                 *string           `json:"conduit_committee_id"`
	ConduitCommitteeName               *string           `json:"conduit_committee_name"`
	ConduitCommitteeState              *string           `json:"conduit_committee_state"`
	ConduitCommitteeStreet1            *string           `json:"conduit_committee_street1"`
	ConduitCommitteeStreet2            *string           `json:"conduit_committee_street2"`
	ConduitCommitteeZip                *int32            `json:"conduit_committee_zip"`
	ContributionReceiptAmount          *float64          `json:"contribution_receipt_amount"`
	ContributionReceiptDate            *time.Time        `json:"contribution_receipt_date"`
	Contributor                        *CommitteeHistory `json:"contributor"`
	ContributorAggregateYtd            *float64          `json:"contributor_aggregate_ytd"`
	ContributorCity                    *string           `json:"contributor_city"`
	ContributorEmployer                *string           `json:"contributor_employer"`
	ContributorFirstName               *string           `json:"contributor_first_name"`
	ContributorID                      *string           `json:"contributor_id"`
	ContributorLastName                *string           `json:"contributor_last_name"`
	ContributorMiddleName              *string           `json:"contributor_middle_name"`
	ContributorName                    *string           `json:"contributor_name"`
	ContributorOccupation              *string           `json:"contributor_occupation"`
	ContributorPrefix                  *string           `json:"contributor_prefix"`
	ContributorState                   *string           `json:"contributor_state"`
	ContributorStreet1                 *string           `json:"contributor_street_1"`
	ContributorStreet2                 *string           `json:"contributor_street_2"`
	ContributorSuffix                  *string           `json:"contributor_suffix"`
	ContributorZip                     *string           `json:"contributor_zip"`
	DonorCommitteeName                 *string           `json:"donor_committee_name"`
	ElectionType                       *string           `json:"election_type"`
	ElectionTypeFull                   *string           `json:"election_type_full"`
	EntityType                         *string           `json:"entity_type"`
	EntityTypeDesc                     *string           `json:"entity_type_desc"`
	FecElectionTypeDesc                *string           `json:"fec_election_type_desc"`
	FecElectionYear                    *string           `json:"fec_election_year"`
	FileNumber                         *int32            `json:"file_number"`
	FilingForm                         *string           `json:"filing_form"`
	ImageNumber                        *string           `json:"image_number"`
	IncreasedLimit                     *string           `json:"increased_limit"`
	IsIndividual                       *bool             `json:"is_individual"`
	LineNumber                         *string           `json:"line_number"`
	LineNumberLabel                    *string           `json:"line_number_label"`
	LinkID                             *int32            `json:"link_id"`
	LoadDate                           *time.Time        `json:"load_date"`
	MemoCode                           *string           `json:"memo_code"`
	MemoCodeFull                       *string           `json:"memo_code_full"`
	MemoText                           *string           `json:"memo_text"`
	MemoedSubtotal                     *bool             `json:"memoed_subtotal"`
	NationalCommitteeNonfederalAccount *string           `json:"national_committee_nonfederal_account"`
	OriginalSubID                      *string           `json:"original_sub_id"`
	PdfURL                             *string           `json:"pdf_url"`
	ReceiptType                        *string           `json:"receipt_type"`
	ReceiptTypeDesc                    *string           `json:"receipt_type_desc"`
	ReceiptTypeFull                    *string           `json:"receipt_type_full"`
	RecipientCommitteeDesignation      *string           `json:"recipient_committee_designation"`
	RecipientCommitteeOrgType          *string           `json:"recipient_committee_org_type"`
	RecipientCommitteeType             *string           `json:"recipient_committee_type"`
	ReportType                         *string           `json:"report_type"`
	ReportYear                         *int32            `json:"report_year"`
	ScheduleType                       *string           `json:"schedule_type"`
	ScheduleTypeFull                   *string           `json:"schedule_type_full"`
	SubID                              *string           `json:"sub_id"`
	TransactionID                      *string           `json:"transaction_id"`
	TwoYearTransactionPeriod           *int32            `json:"two_year_transaction_period"`
	UnusedContbrID                     *string           `json:"unused_contbr_id"`
}
