openapi: 3.0.0
servers:
  - url: https://chromemanagement.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Chrome Management API
  version: v1
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_upload.wikimedia.org_wikipedia_commons_e_e1_YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
    - format: openapi
      url: https://chromemanagement.googleapis.com/$discovery/rest?version=v1
      version: "3.0"
  x-providerName: googleapis.com
  x-serviceName: chromemanagement
tags:
  - name: customers
paths:
  "/v1/{customer}/apps:countChromeAppRequests":
    get:
      description: Generate summary of app installation requests.
      operationId: chromemanagement.customers.apps.countChromeAppRequests
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.appdetails.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.appdetails.readonly
      tags:
        - customers
  "/v1/{customer}/reports:countChromeBrowsersNeedingAttention":
    get:
      description: Count of Chrome Browsers that have been recently enrolled, have new policy to be synced, or have no recent activity.
      operationId: chromemanagement.customers.reports.countChromeBrowsersNeedingAttention
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
      tags:
        - customers
  "/v1/{customer}/reports:countChromeDevicesReachingAutoExpirationDate":
    get:
      description: Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947).
      operationId: chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
      tags:
        - customers
  "/v1/{customer}/reports:countChromeDevicesThatNeedAttention":
    get:
      description: Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947
      operationId: chromemanagement.customers.reports.countChromeDevicesThatNeedAttention
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
      tags:
        - customers
  "/v1/{customer}/reports:countChromeHardwareFleetDevices":
    get:
      description: Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947
      operationId: chromemanagement.customers.reports.countChromeHardwareFleetDevices
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
      tags:
        - customers
  "/v1/{customer}/reports:countChromeVersions":
    get:
      description: Generate report of installed Chrome versions.
      operationId: chromemanagement.customers.reports.countChromeVersions
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
      tags:
        - customers
  "/v1/{customer}/reports:countInstalledApps":
    get:
      description: Generate report of app installations.
      operationId: chromemanagement.customers.reports.countInstalledApps
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
      tags:
        - customers
  "/v1/{customer}/reports:findInstalledAppDevices":
    get:
      description: Generate report of managed Chrome browser devices that have a specified app installed.
      operationId: chromemanagement.customers.reports.findInstalledAppDevices
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.reports.readonly
      tags:
        - customers
  "/v1/{name}":
    get:
      description: Get telemetry user.
      operationId: chromemanagement.customers.telemetry.users.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.telemetry.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.telemetry.readonly
      tags:
        - customers
  "/v1/{parent}/telemetry/devices":
    get:
      description: List all telemetry devices.
      operationId: chromemanagement.customers.telemetry.devices.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.telemetry.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.telemetry.readonly
      tags:
        - customers
  "/v1/{parent}/telemetry/events":
    get:
      description: List telemetry events.
      operationId: chromemanagement.customers.telemetry.events.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.telemetry.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.telemetry.readonly
      tags:
        - customers
  "/v1/{parent}/telemetry/users":
    get:
      description: List all telemetry users.
      operationId: chromemanagement.customers.telemetry.users.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/chrome.management.telemetry.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/chrome.management.telemetry.readonly
      tags:
        - customers
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/chrome.management.appdetails.readonly: See detailed information about apps installed on Chrome browsers and devices managed by your organization
            https://www.googleapis.com/auth/chrome.management.reports.readonly: See reports about devices and Chrome browsers managed within your organization
            https://www.googleapis.com/auth/chrome.management.telemetry.readonly: See basic device and telemetry information collected from Chrome OS devices or users managed within your organization
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/chrome.management.appdetails.readonly: See detailed information about apps installed on Chrome browsers and devices managed by your organization
            https://www.googleapis.com/auth/chrome.management.reports.readonly: See reports about devices and Chrome browsers managed within your organization
            https://www.googleapis.com/auth/chrome.management.telemetry.readonly: See basic device and telemetry information collected from Chrome OS devices or users managed within your organization
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
