openapi: 3.0.0
servers:
  - url: https://admin.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: Admin SDK lets administrators of enterprise domains to view and manage resources like user, groups etc. It also provides audit and usage reports of domain.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Admin SDK
  version: directory_v1
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
    - format: google
      url: https://admin.googleapis.com/$discovery/rest?version=directory_v1
      version: v1
  x-preferred: false
  x-providerName: googleapis.com
  x-serviceName: admin
tags:
  - name: asps
  - name: channels
  - name: chromeosdevices
  - name: customer
  - name: customers
  - name: domainAliases
  - name: domains
  - name: groups
  - name: members
  - name: mobiledevices
  - name: orgunits
  - name: privileges
  - name: resources
  - name: roleAssignments
  - name: roles
  - name: schemas
  - name: tokens
  - name: twoStepVerification
  - name: users
  - name: verificationCodes
paths:
  "/admin/directory/v1/customer/{customerId}/devices/chromeos":
    get:
      description: Retrieve all Chrome OS Devices of a customer (paginated)
      operationId: directory.chromeosdevices.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly
      tags:
        - chromeosdevices
  "/admin/directory/v1/customer/{customerId}/devices/chromeos/moveDevicesToOu":
    post:
      description: Move or insert multiple Chrome OS Devices to organizational unit
      operationId: directory.chromeosdevices.moveDevicesToOu
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
      tags:
        - chromeosdevices
  "/admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}":
    get:
      description: Retrieve Chrome OS Device
      operationId: directory.chromeosdevices.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly
      tags:
        - chromeosdevices
    patch:
      description: Patch Chrome OS Device
      operationId: directory.chromeosdevices.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
      tags:
        - chromeosdevices
    put:
      description: Update Chrome OS Device
      operationId: directory.chromeosdevices.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
      tags:
        - chromeosdevices
  "/admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}/commands/{commandId}":
    get:
      description: Gets command data a specific command issued to the device.
      operationId: admin.customer.devices.chromeos.commands.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly
      tags:
        - customer
  "/admin/directory/v1/customer/{customerId}/devices/chromeos/{deviceId}:issueCommand":
    post:
      description: Issues a command for the device to execute.
      operationId: admin.customer.devices.chromeos.issueCommand
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
      tags:
        - customer
  "/admin/directory/v1/customer/{customerId}/devices/chromeos/{resourceId}/action":
    post:
      description: Take action on Chrome OS Device
      operationId: directory.chromeosdevices.action
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.chromeos
      tags:
        - chromeosdevices
  "/admin/directory/v1/customer/{customerId}/devices/mobile":
    get:
      description: Retrieve all Mobile Devices of a customer (paginated)
      operationId: directory.mobiledevices.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.mobile
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.mobile
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.mobile.action
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.mobile.action
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.mobile.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.mobile.readonly
      tags:
        - mobiledevices
  "/admin/directory/v1/customer/{customerId}/devices/mobile/{resourceId}":
    delete:
      description: Delete Mobile Device
      operationId: directory.mobiledevices.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.mobile
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.mobile
      tags:
        - mobiledevices
    get:
      description: Retrieve Mobile Device
      operationId: directory.mobiledevices.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.mobile
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.mobile
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.mobile.action
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.mobile.action
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.mobile.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.mobile.readonly
      tags:
        - mobiledevices
  "/admin/directory/v1/customer/{customerId}/devices/mobile/{resourceId}/action":
    post:
      description: Take action on Mobile Device
      operationId: directory.mobiledevices.action
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.mobile
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.mobile
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.device.mobile.action
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.device.mobile.action
      tags:
        - mobiledevices
  "/admin/directory/v1/customer/{customerId}/orgunits":
    get:
      description: Retrieve all organizational units
      operationId: directory.orgunits.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.orgunit
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.orgunit
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.orgunit.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.orgunit.readonly
      tags:
        - orgunits
    post:
      description: Add organizational unit
      operationId: directory.orgunits.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.orgunit
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.orgunit
      tags:
        - orgunits
  "/admin/directory/v1/customer/{customerId}/orgunits/{orgUnitPath}":
    delete:
      description: Remove organizational unit
      operationId: directory.orgunits.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.orgunit
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.orgunit
      tags:
        - orgunits
    get:
      description: Retrieve organizational unit
      operationId: directory.orgunits.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.orgunit
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.orgunit
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.orgunit.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.orgunit.readonly
      tags:
        - orgunits
    patch:
      description: Patch organization unit via Apiary Patch Orchestration
      operationId: directory.orgunits.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.orgunit
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.orgunit
      tags:
        - orgunits
    put:
      description: Update organizational unit
      operationId: directory.orgunits.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.orgunit
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.orgunit
      tags:
        - orgunits
  "/admin/directory/v1/customer/{customerId}/schemas":
    get:
      description: Retrieve all schemas for a customer
      operationId: directory.schemas.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.userschema
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.userschema
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.userschema.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.userschema.readonly
      tags:
        - schemas
    post:
      description: Create schema.
      operationId: directory.schemas.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.userschema
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.userschema
      tags:
        - schemas
  "/admin/directory/v1/customer/{customerId}/schemas/{schemaKey}":
    delete:
      description: Delete schema
      operationId: directory.schemas.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.userschema
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.userschema
      tags:
        - schemas
    get:
      description: Retrieve schema
      operationId: directory.schemas.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.userschema
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.userschema
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.userschema.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.userschema.readonly
      tags:
        - schemas
    patch:
      description: Patch Schema via Apiary Patch Orchestration
      operationId: directory.schemas.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.userschema
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.userschema
      tags:
        - schemas
    put:
      description: Update schema
      operationId: directory.schemas.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.userschema
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.userschema
      tags:
        - schemas
  "/admin/directory/v1/customer/{customer}/domainaliases":
    get:
      description: Lists the domain aliases of the customer.
      operationId: directory.domainAliases.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain.readonly
      tags:
        - domainAliases
    post:
      description: Inserts a domain alias of the customer.
      operationId: directory.domainAliases.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain
      tags:
        - domainAliases
  "/admin/directory/v1/customer/{customer}/domainaliases/{domainAliasName}":
    delete:
      description: Deletes a domain Alias of the customer.
      operationId: directory.domainAliases.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain
      tags:
        - domainAliases
    get:
      description: Retrieves a domain alias of the customer.
      operationId: directory.domainAliases.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain.readonly
      tags:
        - domainAliases
  "/admin/directory/v1/customer/{customer}/domains":
    get:
      description: Lists the domains of the customer.
      operationId: directory.domains.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain.readonly
      tags:
        - domains
    post:
      description: Inserts a domain of the customer.
      operationId: directory.domains.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain
      tags:
        - domains
  "/admin/directory/v1/customer/{customer}/domains/{domainName}":
    delete:
      description: Deletes a domain of the customer.
      operationId: directory.domains.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain
      tags:
        - domains
    get:
      description: Retrieves a domain of the customer.
      operationId: directory.domains.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.domain.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.domain.readonly
      tags:
        - domains
  "/admin/directory/v1/customer/{customer}/resources/buildings":
    get:
      description: Retrieves a list of buildings for an account.
      operationId: directory.resources.buildings.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
      tags:
        - resources
    post:
      description: Inserts a building.
      operationId: directory.resources.buildings.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      tags:
        - resources
  "/admin/directory/v1/customer/{customer}/resources/buildings/{buildingId}":
    delete:
      description: Deletes a building.
      operationId: directory.resources.buildings.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      tags:
        - resources
    get:
      description: Retrieves a building.
      operationId: directory.resources.buildings.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
      tags:
        - resources
    patch:
      description: Patches a building via Apiary Patch Orchestration.
      operationId: directory.resources.buildings.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      tags:
        - resources
    put:
      description: Updates a building.
      operationId: directory.resources.buildings.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      tags:
        - resources
  "/admin/directory/v1/customer/{customer}/resources/calendars":
    get:
      description: Retrieves a list of calendar resources for an account.
      operationId: directory.resources.calendars.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
      tags:
        - resources
    post:
      description: Inserts a calendar resource.
      operationId: directory.resources.calendars.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      tags:
        - resources
  "/admin/directory/v1/customer/{customer}/resources/calendars/{calendarResourceId}":
    delete:
      description: Deletes a calendar resource.
      operationId: directory.resources.calendars.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      tags:
        - resources
    get:
      description: Retrieves a calendar resource.
      operationId: directory.resources.calendars.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
      tags:
        - resources
    patch:
      description: Patches a calendar resource via Apiary Patch Orchestration.
      operationId: directory.resources.calendars.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      tags:
        - resources
    put:
      description: Updates a calendar resource. This method supports patch semantics, meaning you only need to include the fields you wish to update. Fields that are not present in the request will be preserved.
      operationId: directory.resources.calendars.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      tags:
        - resources
  "/admin/directory/v1/customer/{customer}/resources/features":
    get:
      description: Retrieves a list of features for an account.
      operationId: directory.resources.features.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
      tags:
        - resources
    post:
      description: Inserts a feature.
      operationId: directory.resources.features.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      tags:
        - resources
  "/admin/directory/v1/customer/{customer}/resources/features/{featureKey}":
    delete:
      description: Deletes a feature.
      operationId: directory.resources.features.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      tags:
        - resources
    get:
      description: Retrieves a feature.
      operationId: directory.resources.features.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly
      tags:
        - resources
    patch:
      description: Patches a feature via Apiary Patch Orchestration.
      operationId: directory.resources.features.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      tags:
        - resources
    put:
      description: Updates a feature.
      operationId: directory.resources.features.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      tags:
        - resources
  "/admin/directory/v1/customer/{customer}/resources/features/{oldName}/rename":
    post:
      description: Renames a feature.
      operationId: directory.resources.features.rename
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.resource.calendar
      tags:
        - resources
  "/admin/directory/v1/customer/{customer}/roleassignments":
    get:
      description: Retrieves a paginated list of all roleAssignments.
      operationId: directory.roleAssignments.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
      tags:
        - roleAssignments
    post:
      description: Creates a role assignment.
      operationId: directory.roleAssignments.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
      tags:
        - roleAssignments
  "/admin/directory/v1/customer/{customer}/roleassignments/{roleAssignmentId}":
    delete:
      description: Deletes a role assignment.
      operationId: directory.roleAssignments.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
      tags:
        - roleAssignments
    get:
      description: Retrieve a role assignment.
      operationId: directory.roleAssignments.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
      tags:
        - roleAssignments
  "/admin/directory/v1/customer/{customer}/roles":
    get:
      description: Retrieves a paginated list of all the roles in a domain.
      operationId: directory.roles.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
      tags:
        - roles
    post:
      description: Creates a role.
      operationId: directory.roles.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
      tags:
        - roles
  "/admin/directory/v1/customer/{customer}/roles/ALL/privileges":
    get:
      description: Retrieves a paginated list of all privileges for a customer.
      operationId: directory.privileges.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
      tags:
        - privileges
  "/admin/directory/v1/customer/{customer}/roles/{roleId}":
    delete:
      description: Deletes a role.
      operationId: directory.roles.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
      tags:
        - roles
    get:
      description: Retrieves a role.
      operationId: directory.roles.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly
      tags:
        - roles
    patch:
      description: Patch role via Apiary Patch Orchestration
      operationId: directory.roles.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
      tags:
        - roles
    put:
      description: Updates a role.
      operationId: directory.roles.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.rolemanagement
      tags:
        - roles
  "/admin/directory/v1/customers/{customerKey}":
    get:
      description: Retrieves a customer.
      operationId: directory.customers.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.customer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.customer
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.customer.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.customer.readonly
      tags:
        - customers
    patch:
      description: Patch Customers via Apiary Patch Orchestration
      operationId: directory.customers.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.customer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.customer
      tags:
        - customers
    put:
      description: Updates a customer.
      operationId: directory.customers.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.customer
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.customer
      tags:
        - customers
  /admin/directory/v1/groups:
    get:
      description: Retrieve all groups of a domain or of a user given a userKey (paginated)
      operationId: directory.groups.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
      tags:
        - groups
    post:
      description: Create Group
      operationId: directory.groups.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
      tags:
        - groups
  "/admin/directory/v1/groups/{groupKey}":
    delete:
      description: Delete Group
      operationId: directory.groups.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
      tags:
        - groups
    get:
      description: Retrieve Group
      operationId: directory.groups.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
      tags:
        - groups
    patch:
      description: Patch Groups via Apiary Patch Orchestration
      operationId: directory.groups.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
      tags:
        - groups
    put:
      description: Update Group
      operationId: directory.groups.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
      tags:
        - groups
  "/admin/directory/v1/groups/{groupKey}/aliases":
    get:
      description: List all aliases for a group
      operationId: directory.groups.aliases.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
      tags:
        - groups
    post:
      description: Add a alias for the group
      operationId: directory.groups.aliases.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
      tags:
        - groups
  "/admin/directory/v1/groups/{groupKey}/aliases/{alias}":
    delete:
      description: Remove a alias for the group
      operationId: directory.groups.aliases.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
      tags:
        - groups
  "/admin/directory/v1/groups/{groupKey}/hasMember/{memberKey}":
    get:
      description: Checks whether the given user is a member of the group. Membership can be direct or nested.
      operationId: directory.members.hasMember
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.member
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.member
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.member.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.member.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
      tags:
        - members
  "/admin/directory/v1/groups/{groupKey}/members":
    get:
      description: Retrieve all members in a group (paginated)
      operationId: directory.members.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.member
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.member
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.member.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.member.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
      tags:
        - members
    post:
      description: Add user to the specified group.
      operationId: directory.members.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.member
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.member
      tags:
        - members
  "/admin/directory/v1/groups/{groupKey}/members/{memberKey}":
    delete:
      description: Remove membership.
      operationId: directory.members.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.member
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.member
      tags:
        - members
    get:
      description: Retrieve Group Member
      operationId: directory.members.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.member
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.member
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.member.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.member.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.readonly
      tags:
        - members
    patch:
      description: Patch Member via Apiary Patch Orchestration
      operationId: directory.members.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.member
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.member
      tags:
        - members
    put:
      description: Update membership of a user in the specified group.
      operationId: directory.members.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group.member
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group.member
      tags:
        - members
  /admin/directory/v1/users:
    get:
      description: Retrieve either deleted users or all users in a domain (paginated)
      operationId: directory.users.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - users
    post:
      description: create user.
      operationId: directory.users.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
      tags:
        - users
  /admin/directory/v1/users/watch:
    post:
      description: Watch for changes in users list
      operationId: directory.users.watch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - users
  "/admin/directory/v1/users/{userKey}":
    delete:
      description: Delete user
      operationId: directory.users.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
      tags:
        - users
    get:
      description: retrieve user
      operationId: directory.users.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
      tags:
        - users
    patch:
      description: Patch Users via Apiary Patch Orchestration
      operationId: directory.users.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
      tags:
        - users
    put:
      description: update user
      operationId: directory.users.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
      tags:
        - users
  "/admin/directory/v1/users/{userKey}/aliases":
    get:
      description: List all aliases for a user
      operationId: directory.users.aliases.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.alias
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.alias
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.alias.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.alias.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
      tags:
        - users
    post:
      description: Add a alias for the user
      operationId: directory.users.aliases.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.alias
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.alias
      tags:
        - users
  "/admin/directory/v1/users/{userKey}/aliases/watch":
    post:
      description: Watch for changes in users list
      operationId: directory.users.aliases.watch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.alias
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.alias
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.alias.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.alias.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
      tags:
        - users
  "/admin/directory/v1/users/{userKey}/aliases/{alias}":
    delete:
      description: Remove a alias for the user
      operationId: directory.users.aliases.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.alias
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.alias
      tags:
        - users
  "/admin/directory/v1/users/{userKey}/asps":
    get:
      description: List the ASPs issued by a user.
      operationId: directory.asps.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      tags:
        - asps
  "/admin/directory/v1/users/{userKey}/asps/{codeId}":
    delete:
      description: Delete an ASP issued by a user.
      operationId: directory.asps.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      tags:
        - asps
    get:
      description: Get information about an ASP issued by a user.
      operationId: directory.asps.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      tags:
        - asps
  "/admin/directory/v1/users/{userKey}/makeAdmin":
    post:
      description: change admin status of a user
      operationId: directory.users.makeAdmin
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
      tags:
        - users
  "/admin/directory/v1/users/{userKey}/photos/thumbnail":
    delete:
      description: Remove photos for the user
      operationId: directory.users.photos.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
      tags:
        - users
    get:
      description: Retrieve photo of a user
      operationId: directory.users.photos.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
      tags:
        - users
    patch:
      description: Patch Photo via Apiary Patch Orchestration
      operationId: directory.users.photos.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
      tags:
        - users
    put:
      description: Add a photo for the user
      operationId: directory.users.photos.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
      tags:
        - users
  "/admin/directory/v1/users/{userKey}/signOut":
    post:
      description: Sign a user out of all web and device sessions and reset their sign-in cookies. User will have to sign in by authenticating again.
      operationId: directory.users.signOut
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      tags:
        - users
  "/admin/directory/v1/users/{userKey}/tokens":
    get:
      description: Returns the set of tokens specified user has issued to 3rd party applications.
      operationId: directory.tokens.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      tags:
        - tokens
  "/admin/directory/v1/users/{userKey}/tokens/{clientId}":
    delete:
      description: Delete all access tokens issued by a user for an application.
      operationId: directory.tokens.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      tags:
        - tokens
    get:
      description: Get information about an access token issued by a user.
      operationId: directory.tokens.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      tags:
        - tokens
  "/admin/directory/v1/users/{userKey}/twoStepVerification/turnOff":
    post:
      description: Turn off 2-Step Verification for user.
      operationId: directory.twoStepVerification.turnOff
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      tags:
        - twoStepVerification
  "/admin/directory/v1/users/{userKey}/undelete":
    post:
      description: Undelete a deleted user
      operationId: directory.users.undelete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
      tags:
        - users
  "/admin/directory/v1/users/{userKey}/verificationCodes":
    get:
      description: Returns the current set of valid backup verification codes for the specified user.
      operationId: directory.verificationCodes.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      tags:
        - verificationCodes
  "/admin/directory/v1/users/{userKey}/verificationCodes/generate":
    post:
      description: Generate new backup verification codes for the user.
      operationId: directory.verificationCodes.generate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      tags:
        - verificationCodes
  "/admin/directory/v1/users/{userKey}/verificationCodes/invalidate":
    post:
      description: Invalidate the current backup verification codes for the user.
      operationId: directory.verificationCodes.invalidate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.security
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.security
      tags:
        - verificationCodes
  /admin/directory_v1/channels/stop:
    post:
      description: Stop watching resources through this channel.
      operationId: admin.channels.stop
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.alias
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.alias
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.alias.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.alias.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user.readonly
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - channels
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/admin.directory.customer: View and manage customer related information
            https://www.googleapis.com/auth/admin.directory.customer.readonly: View customer related information
            https://www.googleapis.com/auth/admin.directory.device.chromeos: View and manage your Chrome OS devices' metadata
            https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly: View your Chrome OS devices' metadata
            https://www.googleapis.com/auth/admin.directory.device.mobile: View and manage your mobile devices' metadata
            https://www.googleapis.com/auth/admin.directory.device.mobile.action: Manage your mobile devices by performing administrative tasks
            https://www.googleapis.com/auth/admin.directory.device.mobile.readonly: View your mobile devices' metadata
            https://www.googleapis.com/auth/admin.directory.domain: View and manage the provisioning of domains for your customers
            https://www.googleapis.com/auth/admin.directory.domain.readonly: View domains related to your customers
            https://www.googleapis.com/auth/admin.directory.group: View and manage the provisioning of groups on your domain
            https://www.googleapis.com/auth/admin.directory.group.member: View and manage group subscriptions on your domain
            https://www.googleapis.com/auth/admin.directory.group.member.readonly: View group subscriptions on your domain
            https://www.googleapis.com/auth/admin.directory.group.readonly: View groups on your domain
            https://www.googleapis.com/auth/admin.directory.orgunit: View and manage organization units on your domain
            https://www.googleapis.com/auth/admin.directory.orgunit.readonly: View organization units on your domain
            https://www.googleapis.com/auth/admin.directory.resource.calendar: View and manage the provisioning of calendar resources on your domain
            https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly: View calendar resources on your domain
            https://www.googleapis.com/auth/admin.directory.rolemanagement: Manage delegated admin roles for your domain
            https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly: View delegated admin roles for your domain
            https://www.googleapis.com/auth/admin.directory.user: View and manage the provisioning of users on your domain
            https://www.googleapis.com/auth/admin.directory.user.alias: View and manage user aliases on your domain
            https://www.googleapis.com/auth/admin.directory.user.alias.readonly: View user aliases on your domain
            https://www.googleapis.com/auth/admin.directory.user.readonly: View users on your domain
            https://www.googleapis.com/auth/admin.directory.user.security: Manage data access permissions for users on your domain
            https://www.googleapis.com/auth/admin.directory.userschema: View and manage the provisioning of user schemas on your domain
            https://www.googleapis.com/auth/admin.directory.userschema.readonly: View user schemas on your domain
            https://www.googleapis.com/auth/cloud-platform: View and manage your data across Google Cloud Platform services
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/admin.directory.customer: View and manage customer related information
            https://www.googleapis.com/auth/admin.directory.customer.readonly: View customer related information
            https://www.googleapis.com/auth/admin.directory.device.chromeos: View and manage your Chrome OS devices' metadata
            https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly: View your Chrome OS devices' metadata
            https://www.googleapis.com/auth/admin.directory.device.mobile: View and manage your mobile devices' metadata
            https://www.googleapis.com/auth/admin.directory.device.mobile.action: Manage your mobile devices by performing administrative tasks
            https://www.googleapis.com/auth/admin.directory.device.mobile.readonly: View your mobile devices' metadata
            https://www.googleapis.com/auth/admin.directory.domain: View and manage the provisioning of domains for your customers
            https://www.googleapis.com/auth/admin.directory.domain.readonly: View domains related to your customers
            https://www.googleapis.com/auth/admin.directory.group: View and manage the provisioning of groups on your domain
            https://www.googleapis.com/auth/admin.directory.group.member: View and manage group subscriptions on your domain
            https://www.googleapis.com/auth/admin.directory.group.member.readonly: View group subscriptions on your domain
            https://www.googleapis.com/auth/admin.directory.group.readonly: View groups on your domain
            https://www.googleapis.com/auth/admin.directory.orgunit: View and manage organization units on your domain
            https://www.googleapis.com/auth/admin.directory.orgunit.readonly: View organization units on your domain
            https://www.googleapis.com/auth/admin.directory.resource.calendar: View and manage the provisioning of calendar resources on your domain
            https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly: View calendar resources on your domain
            https://www.googleapis.com/auth/admin.directory.rolemanagement: Manage delegated admin roles for your domain
            https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly: View delegated admin roles for your domain
            https://www.googleapis.com/auth/admin.directory.user: View and manage the provisioning of users on your domain
            https://www.googleapis.com/auth/admin.directory.user.alias: View and manage user aliases on your domain
            https://www.googleapis.com/auth/admin.directory.user.alias.readonly: View user aliases on your domain
            https://www.googleapis.com/auth/admin.directory.user.readonly: View users on your domain
            https://www.googleapis.com/auth/admin.directory.user.security: Manage data access permissions for users on your domain
            https://www.googleapis.com/auth/admin.directory.userschema: View and manage the provisioning of user schemas on your domain
            https://www.googleapis.com/auth/admin.directory.userschema.readonly: View user schemas on your domain
            https://www.googleapis.com/auth/cloud-platform: View and manage your data across Google Cloud Platform services
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
