swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /admin/directory/v1
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: 'The Admin SDK Directory API lets you view and manage enterprise resources such as users and groups, administrative notifications, security features, and more.'
  title: Admin Directory
  version: directory_v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-apisguru-categories:
    - analytics
  x-logo:
    url: 'https://www.gstatic.com/images/icons/material/product/2x/admin_64dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.6.2
      format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/admin/directory_v1/rest'
      version: v1
  x-preferred: false
  x-providerName: googleapis.com
  x-serviceName: admin
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/admin.directory.customer': View and manage customer related information
      'https://www.googleapis.com/auth/admin.directory.customer.readonly': View customer related information
      'https://www.googleapis.com/auth/admin.directory.device.chromeos': View and manage your Chrome OS devices' metadata
      'https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly': View your Chrome OS devices' metadata
      'https://www.googleapis.com/auth/admin.directory.device.mobile': View and manage your mobile devices' metadata
      'https://www.googleapis.com/auth/admin.directory.device.mobile.action': Manage your mobile devices by performing administrative tasks
      'https://www.googleapis.com/auth/admin.directory.device.mobile.readonly': View your mobile devices' metadata
      'https://www.googleapis.com/auth/admin.directory.domain': View and manage the provisioning of domains for your customers
      'https://www.googleapis.com/auth/admin.directory.domain.readonly': View domains related to your customers
      'https://www.googleapis.com/auth/admin.directory.group': View and manage the provisioning of groups on your domain
      'https://www.googleapis.com/auth/admin.directory.group.member': View and manage group subscriptions on your domain
      'https://www.googleapis.com/auth/admin.directory.group.member.readonly': View group subscriptions on your domain
      'https://www.googleapis.com/auth/admin.directory.group.readonly': View groups on your domain
      'https://www.googleapis.com/auth/admin.directory.notifications': View and manage notifications received on your domain
      'https://www.googleapis.com/auth/admin.directory.orgunit': View and manage organization units on your domain
      'https://www.googleapis.com/auth/admin.directory.orgunit.readonly': View organization units on your domain
      'https://www.googleapis.com/auth/admin.directory.resource.calendar': View and manage the provisioning of calendar resources on your domain
      'https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly': View calendar resources on your domain
      'https://www.googleapis.com/auth/admin.directory.rolemanagement': Manage delegated admin roles for your domain
      'https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly': View delegated admin roles for your domain
      'https://www.googleapis.com/auth/admin.directory.user': View and manage the provisioning of users on your domain
      'https://www.googleapis.com/auth/admin.directory.user.alias': View and manage user aliases on your domain
      'https://www.googleapis.com/auth/admin.directory.user.alias.readonly': View user aliases on your domain
      'https://www.googleapis.com/auth/admin.directory.user.readonly': View users on your domain
      'https://www.googleapis.com/auth/admin.directory.user.security': Manage data access permissions for users on your domain
      'https://www.googleapis.com/auth/admin.directory.userschema': View and manage the provisioning of user schemas on your domain
      'https://www.googleapis.com/auth/admin.directory.userschema.readonly': View user schemas on your domain
    type: oauth2
tags:
  - name: asps
  - name: channels
  - name: chromeosdevices
  - name: customers
  - name: domainAliases
  - name: domains
  - name: groups
  - name: members
  - name: mobiledevices
  - name: notifications
  - name: orgunits
  - name: privileges
  - name: resolvedAppAccessSettings
  - name: resources
  - name: roleAssignments
  - name: roles
  - name: schemas
  - name: tokens
  - name: users
  - name: verificationCodes
paths:
  /admin/directory_v1/channels/stop:
    post:
      description: Stop watching resources through this channel
      operationId: admin.channels.stop
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.alias'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.alias.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.readonly'
      tags:
        - channels
  '/customer/{customerId}/devices/chromeos':
    get:
      description: Retrieve all Chrome OS Devices of a customer (paginated)
      operationId: directory.chromeosdevices.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.device.chromeos'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly'
      tags:
        - chromeosdevices
  '/customer/{customerId}/devices/chromeos/moveDevicesToOu':
    post:
      description: Move or insert multiple Chrome OS Devices to organizational unit
      operationId: directory.chromeosdevices.moveDevicesToOu
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.device.chromeos'
      tags:
        - chromeosdevices
  '/customer/{customerId}/devices/chromeos/{deviceId}':
    get:
      description: Retrieve Chrome OS Device
      operationId: directory.chromeosdevices.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.device.chromeos'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly'
      tags:
        - chromeosdevices
    patch:
      description: Update Chrome OS Device. This method supports patch semantics.
      operationId: directory.chromeosdevices.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.device.chromeos'
      tags:
        - chromeosdevices
    put:
      description: Update Chrome OS Device
      operationId: directory.chromeosdevices.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.device.chromeos'
      tags:
        - chromeosdevices
  '/customer/{customerId}/devices/chromeos/{resourceId}/action':
    post:
      description: Take action on Chrome OS Device
      operationId: directory.chromeosdevices.action
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.device.chromeos'
      tags:
        - chromeosdevices
  '/customer/{customerId}/devices/mobile':
    get:
      description: Retrieve all Mobile Devices of a customer (paginated)
      operationId: directory.mobiledevices.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.device.mobile'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.device.mobile.action'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.device.mobile.readonly'
      tags:
        - mobiledevices
  '/customer/{customerId}/devices/mobile/{resourceId}':
    delete:
      description: Delete Mobile Device
      operationId: directory.mobiledevices.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.device.mobile'
      tags:
        - mobiledevices
    get:
      description: Retrieve Mobile Device
      operationId: directory.mobiledevices.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.device.mobile'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.device.mobile.action'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.device.mobile.readonly'
      tags:
        - mobiledevices
  '/customer/{customerId}/devices/mobile/{resourceId}/action':
    post:
      description: Take action on Mobile Device
      operationId: directory.mobiledevices.action
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.device.mobile'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.device.mobile.action'
      tags:
        - mobiledevices
  '/customer/{customerId}/orgunits':
    get:
      description: Retrieve all organizational units
      operationId: directory.orgunits.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.orgunit'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.orgunit.readonly'
      tags:
        - orgunits
    post:
      description: Add organizational unit
      operationId: directory.orgunits.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.orgunit'
      tags:
        - orgunits
  '/customer/{customerId}/orgunits/{orgUnitPath}':
    delete:
      description: Remove Organization Unit
      operationId: directory.orgunits.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.orgunit'
      tags:
        - orgunits
    get:
      description: Retrieve Organization Unit
      operationId: directory.orgunits.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.orgunit'
            - 'https://www.googleapis.com/auth/admin.directory.orgunit.readonly'
      tags:
        - orgunits
    patch:
      description: Update Organization Unit. This method supports patch semantics.
      operationId: directory.orgunits.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.orgunit'
      tags:
        - orgunits
    put:
      description: Update Organization Unit
      operationId: directory.orgunits.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.orgunit'
      tags:
        - orgunits
  '/customer/{customerId}/schemas':
    get:
      description: Retrieve all schemas for a customer
      operationId: directory.schemas.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.userschema'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.userschema.readonly'
      tags:
        - schemas
    post:
      description: Create schema.
      operationId: directory.schemas.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.userschema'
      tags:
        - schemas
  '/customer/{customerId}/schemas/{schemaKey}':
    delete:
      description: Delete schema
      operationId: directory.schemas.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.userschema'
      tags:
        - schemas
    get:
      description: Retrieve schema
      operationId: directory.schemas.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.userschema'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.userschema.readonly'
      tags:
        - schemas
    patch:
      description: Update schema. This method supports patch semantics.
      operationId: directory.schemas.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.userschema'
      tags:
        - schemas
    put:
      description: Update schema
      operationId: directory.schemas.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.userschema'
      tags:
        - schemas
  '/customer/{customer}/domainaliases':
    get:
      description: Lists the domain aliases of the customer.
      operationId: directory.domainAliases.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.domain'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.domain.readonly'
      tags:
        - domainAliases
    post:
      description: Inserts a Domain alias of the customer.
      operationId: directory.domainAliases.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.domain'
      tags:
        - domainAliases
  '/customer/{customer}/domainaliases/{domainAliasName}':
    delete:
      description: Deletes a Domain Alias of the customer.
      operationId: directory.domainAliases.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.domain'
      tags:
        - domainAliases
    get:
      description: Retrieves a domain alias of the customer.
      operationId: directory.domainAliases.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.domain'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.domain.readonly'
      tags:
        - domainAliases
  '/customer/{customer}/domains':
    get:
      description: Lists the domains of the customer.
      operationId: directory.domains.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.domain'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.domain.readonly'
      tags:
        - domains
    post:
      description: Inserts a domain of the customer.
      operationId: directory.domains.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.domain'
      tags:
        - domains
  '/customer/{customer}/domains/{domainName}':
    delete:
      description: Deletes a domain of the customer.
      operationId: directory.domains.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.domain'
      tags:
        - domains
    get:
      description: Retrieves a domain of the customer.
      operationId: directory.domains.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.domain'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.domain.readonly'
      tags:
        - domains
  '/customer/{customer}/notifications':
    get:
      description: Retrieves a list of notifications.
      operationId: directory.notifications.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.notifications'
      tags:
        - notifications
  '/customer/{customer}/notifications/{notificationId}':
    delete:
      description: Deletes a notification
      operationId: directory.notifications.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.notifications'
      tags:
        - notifications
    get:
      description: Retrieves a notification.
      operationId: directory.notifications.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.notifications'
      tags:
        - notifications
    patch:
      description: Updates a notification. This method supports patch semantics.
      operationId: directory.notifications.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.notifications'
      tags:
        - notifications
    put:
      description: Updates a notification.
      operationId: directory.notifications.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.notifications'
      tags:
        - notifications
  '/customer/{customer}/resources/buildings':
    get:
      description: Retrieves a list of buildings for an account.
      operationId: directory.resources.buildings.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly'
      tags:
        - resources
    post:
      description: Inserts a building.
      operationId: directory.resources.buildings.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar'
      tags:
        - resources
  '/customer/{customer}/resources/buildings/{buildingId}':
    delete:
      description: Deletes a building.
      operationId: directory.resources.buildings.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar'
      tags:
        - resources
    get:
      description: Retrieves a building.
      operationId: directory.resources.buildings.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly'
      tags:
        - resources
    patch:
      description: Updates a building. This method supports patch semantics.
      operationId: directory.resources.buildings.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar'
      tags:
        - resources
    put:
      description: Updates a building.
      operationId: directory.resources.buildings.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar'
      tags:
        - resources
  '/customer/{customer}/resources/calendars':
    get:
      description: Retrieves a list of calendar resources for an account.
      operationId: directory.resources.calendars.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly'
      tags:
        - resources
    post:
      description: Inserts a calendar resource.
      operationId: directory.resources.calendars.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar'
      tags:
        - resources
  '/customer/{customer}/resources/calendars/{calendarResourceId}':
    delete:
      description: Deletes a calendar resource.
      operationId: directory.resources.calendars.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar'
      tags:
        - resources
    get:
      description: Retrieves a calendar resource.
      operationId: directory.resources.calendars.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly'
      tags:
        - resources
    patch:
      description: |-
        Updates a calendar resource.

        This method supports patch semantics, meaning you only need to include the fields you wish to update. Fields that are not present in the request will be preserved. This method supports patch semantics.
      operationId: directory.resources.calendars.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar'
      tags:
        - resources
    put:
      description: |-
        Updates a calendar resource.

        This method supports patch semantics, meaning you only need to include the fields you wish to update. Fields that are not present in the request will be preserved.
      operationId: directory.resources.calendars.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar'
      tags:
        - resources
  '/customer/{customer}/resources/features':
    get:
      description: Retrieves a list of features for an account.
      operationId: directory.resources.features.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly'
      tags:
        - resources
    post:
      description: Inserts a feature.
      operationId: directory.resources.features.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar'
      tags:
        - resources
  '/customer/{customer}/resources/features/{featureKey}':
    delete:
      description: Deletes a feature.
      operationId: directory.resources.features.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar'
      tags:
        - resources
    get:
      description: Retrieves a feature.
      operationId: directory.resources.features.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly'
      tags:
        - resources
    patch:
      description: Updates a feature. This method supports patch semantics.
      operationId: directory.resources.features.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar'
      tags:
        - resources
    put:
      description: Updates a feature.
      operationId: directory.resources.features.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar'
      tags:
        - resources
  '/customer/{customer}/resources/features/{oldName}/rename':
    post:
      description: Renames a feature.
      operationId: directory.resources.features.rename
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.resource.calendar'
      tags:
        - resources
  '/customer/{customer}/roleassignments':
    get:
      description: Retrieves a paginated list of all roleAssignments.
      operationId: directory.roleAssignments.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.rolemanagement'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly'
      tags:
        - roleAssignments
    post:
      description: Creates a role assignment.
      operationId: directory.roleAssignments.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.rolemanagement'
      tags:
        - roleAssignments
  '/customer/{customer}/roleassignments/{roleAssignmentId}':
    delete:
      description: Deletes a role assignment.
      operationId: directory.roleAssignments.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.rolemanagement'
      tags:
        - roleAssignments
    get:
      description: Retrieve a role assignment.
      operationId: directory.roleAssignments.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.rolemanagement'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly'
      tags:
        - roleAssignments
  '/customer/{customer}/roles':
    get:
      description: Retrieves a paginated list of all the roles in a domain.
      operationId: directory.roles.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.rolemanagement'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly'
      tags:
        - roles
    post:
      description: Creates a role.
      operationId: directory.roles.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.rolemanagement'
      tags:
        - roles
  '/customer/{customer}/roles/ALL/privileges':
    get:
      description: Retrieves a paginated list of all privileges for a customer.
      operationId: directory.privileges.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.rolemanagement'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly'
      tags:
        - privileges
  '/customer/{customer}/roles/{roleId}':
    delete:
      description: Deletes a role.
      operationId: directory.roles.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.rolemanagement'
      tags:
        - roles
    get:
      description: Retrieves a role.
      operationId: directory.roles.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.rolemanagement'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly'
      tags:
        - roles
    patch:
      description: Updates a role. This method supports patch semantics.
      operationId: directory.roles.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.rolemanagement'
      tags:
        - roles
    put:
      description: Updates a role.
      operationId: directory.roles.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.rolemanagement'
      tags:
        - roles
  '/customers/{customerKey}':
    get:
      description: Retrieves a customer.
      operationId: directory.customers.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.customer'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.customer.readonly'
      tags:
        - customers
    patch:
      description: Updates a customer. This method supports patch semantics.
      operationId: directory.customers.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.customer'
      tags:
        - customers
    put:
      description: Updates a customer.
      operationId: directory.customers.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.customer'
      tags:
        - customers
  /groups:
    get:
      description: Retrieve all groups in a domain (paginated)
      operationId: directory.groups.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group.readonly'
      tags:
        - groups
    post:
      description: Create Group
      operationId: directory.groups.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group'
      tags:
        - groups
  '/groups/{groupKey}':
    delete:
      description: Delete Group
      operationId: directory.groups.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group'
      tags:
        - groups
    get:
      description: Retrieve Group
      operationId: directory.groups.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group.readonly'
      tags:
        - groups
    patch:
      description: Update Group. This method supports patch semantics.
      operationId: directory.groups.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group'
      tags:
        - groups
    put:
      description: Update Group
      operationId: directory.groups.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group'
      tags:
        - groups
  '/groups/{groupKey}/aliases':
    get:
      description: List all aliases for a group
      operationId: directory.groups.aliases.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group.readonly'
      tags:
        - groups
    post:
      description: Add a alias for the group
      operationId: directory.groups.aliases.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group'
      tags:
        - groups
  '/groups/{groupKey}/aliases/{alias}':
    delete:
      description: Remove a alias for the group
      operationId: directory.groups.aliases.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group'
      tags:
        - groups
  '/groups/{groupKey}/hasMember/{memberKey}':
    get:
      description: Checks whether the given user is a member of the group. Membership can be direct or nested.
      operationId: directory.members.hasMember
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group.member'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group.member.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group.readonly'
      tags:
        - members
  '/groups/{groupKey}/members':
    get:
      description: Retrieve all members in a group (paginated)
      operationId: directory.members.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group.member'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group.member.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group.readonly'
      tags:
        - members
    post:
      description: Add user to the specified group.
      operationId: directory.members.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group.member'
      tags:
        - members
  '/groups/{groupKey}/members/{memberKey}':
    delete:
      description: Remove membership.
      operationId: directory.members.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group.member'
      tags:
        - members
    get:
      description: Retrieve Group Member
      operationId: directory.members.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group.member'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group.member.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group.readonly'
      tags:
        - members
    patch:
      description: Update membership of a user in the specified group. This method supports patch semantics.
      operationId: directory.members.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group.member'
      tags:
        - members
    put:
      description: Update membership of a user in the specified group.
      operationId: directory.members.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.group.member'
      tags:
        - members
  /resolvedappaccesssettings:
    get:
      description: Retrieves resolved app access settings of the logged in user.
      operationId: directory.resolvedAppAccessSettings.GetSettings
      tags:
        - resolvedAppAccessSettings
  /trustedapps:
    get:
      description: Retrieves the list of apps trusted by the admin of the logged in user.
      operationId: directory.resolvedAppAccessSettings.ListTrustedApps
      tags:
        - resolvedAppAccessSettings
  /users:
    get:
      description: Retrieve either deleted users or all users in a domain (paginated)
      operationId: directory.users.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.readonly'
      tags:
        - users
    post:
      description: create user.
      operationId: directory.users.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user'
      tags:
        - users
  /users/watch:
    post:
      description: Watch for changes in users list
      operationId: directory.users.watch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.readonly'
      tags:
        - users
  '/users/{userKey}':
    delete:
      description: Delete user
      operationId: directory.users.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user'
      tags:
        - users
    get:
      description: retrieve user
      operationId: directory.users.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.readonly'
      tags:
        - users
    patch:
      description: update user. This method supports patch semantics.
      operationId: directory.users.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user'
      tags:
        - users
    put:
      description: update user
      operationId: directory.users.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user'
      tags:
        - users
  '/users/{userKey}/aliases':
    get:
      description: List all aliases for a user
      operationId: directory.users.aliases.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.alias'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.alias.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.readonly'
      tags:
        - users
    post:
      description: Add a alias for the user
      operationId: directory.users.aliases.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.alias'
      tags:
        - users
  '/users/{userKey}/aliases/watch':
    post:
      description: Watch for changes in user aliases list
      operationId: directory.users.aliases.watch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.alias'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.alias.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.readonly'
      tags:
        - users
  '/users/{userKey}/aliases/{alias}':
    delete:
      description: Remove a alias for the user
      operationId: directory.users.aliases.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.alias'
      tags:
        - users
  '/users/{userKey}/asps':
    get:
      description: List the ASPs issued by a user.
      operationId: directory.asps.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.security'
      tags:
        - asps
  '/users/{userKey}/asps/{codeId}':
    delete:
      description: Delete an ASP issued by a user.
      operationId: directory.asps.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.security'
      tags:
        - asps
    get:
      description: Get information about an ASP issued by a user.
      operationId: directory.asps.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.security'
      tags:
        - asps
  '/users/{userKey}/makeAdmin':
    post:
      description: change admin status of a user
      operationId: directory.users.makeAdmin
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user'
      tags:
        - users
  '/users/{userKey}/photos/thumbnail':
    delete:
      description: Remove photos for the user
      operationId: directory.users.photos.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user'
      tags:
        - users
    get:
      description: Retrieve photo of a user
      operationId: directory.users.photos.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.readonly'
      tags:
        - users
    patch:
      description: Add a photo for the user. This method supports patch semantics.
      operationId: directory.users.photos.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user'
      tags:
        - users
    put:
      description: Add a photo for the user
      operationId: directory.users.photos.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user'
      tags:
        - users
  '/users/{userKey}/tokens':
    get:
      description: Returns the set of tokens specified user has issued to 3rd party applications.
      operationId: directory.tokens.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.security'
      tags:
        - tokens
  '/users/{userKey}/tokens/{clientId}':
    delete:
      description: Delete all access tokens issued by a user for an application.
      operationId: directory.tokens.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.security'
      tags:
        - tokens
    get:
      description: Get information about an access token issued by a user.
      operationId: directory.tokens.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.security'
      tags:
        - tokens
  '/users/{userKey}/undelete':
    post:
      description: Undelete a deleted user
      operationId: directory.users.undelete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user'
      tags:
        - users
  '/users/{userKey}/verificationCodes':
    get:
      description: Returns the current set of valid backup verification codes for the specified user.
      operationId: directory.verificationCodes.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.security'
      tags:
        - verificationCodes
  '/users/{userKey}/verificationCodes/generate':
    post:
      description: Generate new backup verification codes for the user.
      operationId: directory.verificationCodes.generate
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.security'
      tags:
        - verificationCodes
  '/users/{userKey}/verificationCodes/invalidate':
    post:
      description: Invalidate the current backup verification codes for the user.
      operationId: directory.verificationCodes.invalidate
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.directory.user.security'
      tags:
        - verificationCodes