QT += network

HEADERS += \
# Models
    $${PWD}/OAI_assets_analysis_absorption_ratio_post_200_response.h \
    $${PWD}/OAI_assets_analysis_absorption_ratio_post_request.h \
    $${PWD}/OAI_assets_analysis_absorption_ratio_post_request_assetsCovarianceMatrixEigenvectors.h \
    $${PWD}/OAI_assets_analysis_turbulence_index_post_200_response.h \
    $${PWD}/OAI_assets_analysis_turbulence_index_post_request.h \
    $${PWD}/OAI_assets_correlation_matrix_bounds_post_200_response.h \
    $${PWD}/OAI_assets_correlation_matrix_bounds_post_request.h \
    $${PWD}/OAI_assets_correlation_matrix_denoised_post_200_response.h \
    $${PWD}/OAI_assets_correlation_matrix_denoised_post_request.h \
    $${PWD}/OAI_assets_correlation_matrix_distance_post_200_response.h \
    $${PWD}/OAI_assets_correlation_matrix_distance_post_request.h \
    $${PWD}/OAI_assets_correlation_matrix_effective_rank_post_200_response.h \
    $${PWD}/OAI_assets_correlation_matrix_effective_rank_post_request.h \
    $${PWD}/OAI_assets_correlation_matrix_informativeness_post_200_response.h \
    $${PWD}/OAI_assets_correlation_matrix_informativeness_post_request.h \
    $${PWD}/OAI_assets_correlation_matrix_nearest_post_request.h \
    $${PWD}/OAI_assets_correlation_matrix_post_200_response.h \
    $${PWD}/OAI_assets_correlation_matrix_post_request.h \
    $${PWD}/OAI_assets_correlation_matrix_post_request_oneOf.h \
    $${PWD}/OAI_assets_correlation_matrix_post_request_oneOf_1.h \
    $${PWD}/OAI_assets_correlation_matrix_post_request_oneOf_assets_inner.h \
    $${PWD}/OAI_assets_correlation_matrix_random_post_request.h \
    $${PWD}/OAI_assets_correlation_matrix_shrinkage_post_request.h \
    $${PWD}/OAI_assets_correlation_matrix_shrinkage_post_request_oneOf.h \
    $${PWD}/OAI_assets_correlation_matrix_shrinkage_post_request_oneOf_1.h \
    $${PWD}/OAI_assets_correlation_matrix_theory_implied_post_request.h \
    $${PWD}/OAI_assets_correlation_matrix_theory_implied_post_request_assets_inner.h \
    $${PWD}/OAI_assets_correlation_matrix_theory_implied_post_request_assets_inner_assetHierarchicalClassification_inner.h \
    $${PWD}/OAI_assets_correlation_matrix_validation_post_200_response.h \
    $${PWD}/OAI_assets_correlation_matrix_validation_post_request.h \
    $${PWD}/OAI_assets_covariance_matrix_effective_rank_post_200_response.h \
    $${PWD}/OAI_assets_covariance_matrix_effective_rank_post_request.h \
    $${PWD}/OAI_assets_covariance_matrix_exponentially_weighted_post_200_response.h \
    $${PWD}/OAI_assets_covariance_matrix_exponentially_weighted_post_request.h \
    $${PWD}/OAI_assets_covariance_matrix_post_200_response.h \
    $${PWD}/OAI_assets_covariance_matrix_post_request.h \
    $${PWD}/OAI_assets_covariance_matrix_post_request_oneOf.h \
    $${PWD}/OAI_assets_covariance_matrix_post_request_oneOf_1.h \
    $${PWD}/OAI_assets_covariance_matrix_validation_post_200_response.h \
    $${PWD}/OAI_assets_kurtosis_post_200_response.h \
    $${PWD}/OAI_assets_kurtosis_post_200_response_assets_inner.h \
    $${PWD}/OAI_assets_kurtosis_post_request.h \
    $${PWD}/OAI_assets_kurtosis_post_request_assets_inner.h \
    $${PWD}/OAI_assets_prices_adjusted_post_200_response.h \
    $${PWD}/OAI_assets_prices_adjusted_post_200_response_assets_inner.h \
    $${PWD}/OAI_assets_prices_adjusted_post_200_response_assets_inner_assetAdjustedPrices_inner.h \
    $${PWD}/OAI_assets_prices_adjusted_post_request.h \
    $${PWD}/OAI_assets_prices_adjusted_post_request_assets_inner.h \
    $${PWD}/OAI_assets_prices_adjusted_post_request_assets_inner_assetDividends_inner.h \
    $${PWD}/OAI_assets_prices_adjusted_post_request_assets_inner_assetPrices_inner.h \
    $${PWD}/OAI_assets_prices_adjusted_post_request_assets_inner_assetSplits_inner.h \
    $${PWD}/OAI_assets_returns_average_post_200_response.h \
    $${PWD}/OAI_assets_returns_average_post_200_response_assets_inner.h \
    $${PWD}/OAI_assets_returns_average_post_request.h \
    $${PWD}/OAI_assets_returns_average_post_request_assets_inner.h \
    $${PWD}/OAI_assets_returns_logarithmic_post_200_response.h \
    $${PWD}/OAI_assets_returns_logarithmic_post_200_response_assets_inner.h \
    $${PWD}/OAI_assets_returns_post_200_response.h \
    $${PWD}/OAI_assets_returns_post_200_response_assets_inner.h \
    $${PWD}/OAI_assets_returns_post_request.h \
    $${PWD}/OAI_assets_returns_post_request_assets_inner.h \
    $${PWD}/OAI_assets_returns_simulation_bootstrap_post_200_response.h \
    $${PWD}/OAI_assets_returns_simulation_bootstrap_post_200_response_simulations_inner.h \
    $${PWD}/OAI_assets_returns_simulation_bootstrap_post_200_response_simulations_inner_assets_inner.h \
    $${PWD}/OAI_assets_returns_simulation_bootstrap_post_request.h \
    $${PWD}/OAI_assets_returns_simulation_bootstrap_post_request_assets_inner.h \
    $${PWD}/OAI_assets_returns_simulation_monte_carlo_cornish_fisher_corrected_post_request.h \
    $${PWD}/OAI_assets_returns_simulation_monte_carlo_cornish_fisher_post_200_response.h \
    $${PWD}/OAI_assets_returns_simulation_monte_carlo_cornish_fisher_post_200_response_simulations_inner.h \
    $${PWD}/OAI_assets_returns_simulation_monte_carlo_cornish_fisher_post_request.h \
    $${PWD}/OAI_assets_returns_simulation_monte_carlo_gaussian_post_request.h \
    $${PWD}/OAI_assets_returns_turbulence_partitioned_post_200_response.h \
    $${PWD}/OAI_assets_returns_turbulence_partitioned_post_200_response_assets_inner.h \
    $${PWD}/OAI_assets_returns_turbulence_partitioned_post_200_response_assets_inner_assetTurbulencePartitionedReturns_inner.h \
    $${PWD}/OAI_assets_returns_turbulence_partitioned_post_request.h \
    $${PWD}/OAI_assets_skewness_post_200_response.h \
    $${PWD}/OAI_assets_skewness_post_200_response_assets_inner.h \
    $${PWD}/OAI_assets_skewness_post_request.h \
    $${PWD}/OAI_assets_skewness_post_request_assets_inner.h \
    $${PWD}/OAI_assets_variance_post_200_response.h \
    $${PWD}/OAI_assets_variance_post_200_response_assets_inner.h \
    $${PWD}/OAI_assets_variance_post_request.h \
    $${PWD}/OAI_assets_variance_post_request_oneOf.h \
    $${PWD}/OAI_assets_variance_post_request_oneOf_1.h \
    $${PWD}/OAI_assets_variance_post_request_oneOf_1_assets_inner.h \
    $${PWD}/OAI_assets_variance_post_request_oneOf_assets_inner.h \
    $${PWD}/OAI_assets_volatility_post_200_response.h \
    $${PWD}/OAI_assets_volatility_post_200_response_assets_inner.h \
    $${PWD}/OAI_assets_volatility_post_request.h \
    $${PWD}/OAI_assets_volatility_post_request_oneOf.h \
    $${PWD}/OAI_assets_volatility_post_request_oneOf_assets_inner.h \
    $${PWD}/OAI_factors_residualization_post_200_response.h \
    $${PWD}/OAI_factors_residualization_post_request.h \
    $${PWD}/OAI_factors_residualization_post_request_factors_inner.h \
    $${PWD}/OAI_portfolio_analysis_alpha_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_alpha_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_alpha_post_request.h \
    $${PWD}/OAI_portfolio_analysis_alpha_post_request_oneOf.h \
    $${PWD}/OAI_portfolio_analysis_alpha_post_request_oneOf_1.h \
    $${PWD}/OAI_portfolio_analysis_alpha_post_request_oneOf_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_beta_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_beta_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_contributions_return_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_contributions_return_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_contributions_return_post_request.h \
    $${PWD}/OAI_portfolio_analysis_contributions_return_post_request_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_contributions_risk_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_contributions_risk_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_contributions_risk_post_request.h \
    $${PWD}/OAI_portfolio_analysis_correlation_spectrum_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_correlation_spectrum_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_correlation_spectrum_post_request.h \
    $${PWD}/OAI_portfolio_analysis_correlation_spectrum_post_request_oneOf.h \
    $${PWD}/OAI_portfolio_analysis_correlation_spectrum_post_request_oneOf_1.h \
    $${PWD}/OAI_portfolio_analysis_correlation_spectrum_post_request_oneOf_1_assets_inner.h \
    $${PWD}/OAI_portfolio_analysis_correlation_spectrum_post_request_oneOf_1_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_diversification_ratio_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_diversification_ratio_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_drawdowns_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_drawdowns_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_drawdowns_post_200_response_portfolios_inner_portfolioWorstDrawdowns_inner.h \
    $${PWD}/OAI_portfolio_analysis_drawdowns_post_request.h \
    $${PWD}/OAI_portfolio_analysis_drawdowns_post_request_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_effective_number_of_bets_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_effective_number_of_bets_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_effective_number_of_bets_post_request.h \
    $${PWD}/OAI_portfolio_analysis_effective_number_of_bets_post_request_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_factors_exposures_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_factors_exposures_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_factors_exposures_post_request.h \
    $${PWD}/OAI_portfolio_analysis_factors_exposures_post_request_factors_inner.h \
    $${PWD}/OAI_portfolio_analysis_factors_exposures_post_request_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_mean_variance_efficient_frontier_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_mean_variance_efficient_frontier_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_mean_variance_efficient_frontier_post_request.h \
    $${PWD}/OAI_portfolio_analysis_mean_variance_efficient_frontier_post_request_constraints.h \
    $${PWD}/OAI_portfolio_analysis_mean_variance_minimum_variance_frontier_post_request.h \
    $${PWD}/OAI_portfolio_analysis_return_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_return_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_return_post_request.h \
    $${PWD}/OAI_portfolio_analysis_return_post_request_oneOf.h \
    $${PWD}/OAI_portfolio_analysis_return_post_request_oneOf_1.h \
    $${PWD}/OAI_portfolio_analysis_return_post_request_oneOf_1_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_returns_average_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_returns_average_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_bias_adjusted_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_bias_adjusted_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_bias_adjusted_post_request.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_bias_adjusted_post_request_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_confidence_interval_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_confidence_interval_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_confidence_interval_post_request.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_post_request.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_post_request_oneOf.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_post_request_oneOf_1.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_post_request_oneOf_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_minimum_track_record_length_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_minimum_track_record_length_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_minimum_track_record_length_post_request.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_minimum_track_record_length_post_request_oneOf.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_minimum_track_record_length_post_request_oneOf_1.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_post_request.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_post_request_oneOf.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_post_request_oneOf_1.h \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_post_request_oneOf_1_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_tracking_error_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_tracking_error_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_tracking_error_post_request.h \
    $${PWD}/OAI_portfolio_analysis_tracking_error_post_request_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_ulcer_index_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_ulcer_index_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_ulcer_performance_index_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_ulcer_performance_index_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_value_at_risk_conditional_cornish_fisher_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_value_at_risk_conditional_cornish_fisher_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_value_at_risk_conditional_cornish_fisher_post_request.h \
    $${PWD}/OAI_portfolio_analysis_value_at_risk_conditional_cornish_fisher_post_request_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_value_at_risk_conditional_gaussian_post_request.h \
    $${PWD}/OAI_portfolio_analysis_value_at_risk_conditional_gaussian_post_request_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_value_at_risk_conditional_historical_post_request.h \
    $${PWD}/OAI_portfolio_analysis_value_at_risk_cornish_fisher_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_value_at_risk_cornish_fisher_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_volatility_post_200_response.h \
    $${PWD}/OAI_portfolio_analysis_volatility_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_analysis_volatility_post_request.h \
    $${PWD}/OAI_portfolio_analysis_volatility_post_request_oneOf.h \
    $${PWD}/OAI_portfolio_construction_investable_post_200_response.h \
    $${PWD}/OAI_portfolio_construction_investable_post_request.h \
    $${PWD}/OAI_portfolio_construction_mimicking_post_request.h \
    $${PWD}/OAI_portfolio_construction_random_post_200_response.h \
    $${PWD}/OAI_portfolio_construction_random_post_request.h \
    $${PWD}/OAI_portfolio_construction_random_post_request_constraints.h \
    $${PWD}/OAI_portfolio_optimization_equal_risk_contributions_post_request.h \
    $${PWD}/OAI_portfolio_optimization_equal_risk_contributions_post_request_constraints.h \
    $${PWD}/OAI_portfolio_optimization_equal_sharpe_ratio_contributions_post_request.h \
    $${PWD}/OAI_portfolio_optimization_equal_volatility_weighted_post_request.h \
    $${PWD}/OAI_portfolio_optimization_hierarchical_risk_parity_clustering_based_post_request.h \
    $${PWD}/OAI_portfolio_optimization_hierarchical_risk_parity_post_request.h \
    $${PWD}/OAI_portfolio_optimization_inverse_variance_weighted_post_request.h \
    $${PWD}/OAI_portfolio_optimization_market_capitalization_weighted_post_request.h \
    $${PWD}/OAI_portfolio_optimization_maximum_decorrelation_post_request.h \
    $${PWD}/OAI_portfolio_optimization_maximum_return_diversified_post_request.h \
    $${PWD}/OAI_portfolio_optimization_maximum_return_diversified_post_request_constraints.h \
    $${PWD}/OAI_portfolio_optimization_maximum_return_post_request.h \
    $${PWD}/OAI_portfolio_optimization_maximum_return_subset_resampling_based_post_request.h \
    $${PWD}/OAI_portfolio_optimization_maximum_sharpe_ratio_diversified_post_request.h \
    $${PWD}/OAI_portfolio_optimization_maximum_sharpe_ratio_diversified_post_request_constraints.h \
    $${PWD}/OAI_portfolio_optimization_maximum_sharpe_ratio_post_request.h \
    $${PWD}/OAI_portfolio_optimization_maximum_sharpe_ratio_subset_resampling_based_post_request.h \
    $${PWD}/OAI_portfolio_optimization_maximum_ulcer_performance_index_post_request.h \
    $${PWD}/OAI_portfolio_optimization_mean_variance_efficient_diversified_post_request.h \
    $${PWD}/OAI_portfolio_optimization_mean_variance_efficient_diversified_post_request_constraints.h \
    $${PWD}/OAI_portfolio_optimization_mean_variance_efficient_post_request.h \
    $${PWD}/OAI_portfolio_optimization_mean_variance_efficient_post_request_constraints.h \
    $${PWD}/OAI_portfolio_optimization_mean_variance_efficient_subset_resampling_based_post_request.h \
    $${PWD}/OAI_portfolio_optimization_minimum_correlation_post_request.h \
    $${PWD}/OAI_portfolio_optimization_minimum_ulcer_index_post_request.h \
    $${PWD}/OAI_portfolio_optimization_minimum_variance_diversified_post_request.h \
    $${PWD}/OAI_portfolio_optimization_minimum_variance_diversified_post_request_constraints.h \
    $${PWD}/OAI_portfolio_optimization_minimum_variance_post_request.h \
    $${PWD}/OAI_portfolio_optimization_minimum_variance_subset_resampling_based_post_request.h \
    $${PWD}/OAI_portfolio_optimization_most_diversified_post_request.h \
    $${PWD}/OAI_portfolio_simulation_rebalancing_drift_weight_post_200_response.h \
    $${PWD}/OAI_portfolio_simulation_rebalancing_drift_weight_post_200_response_portfolios_inner.h \
    $${PWD}/OAI_portfolio_simulation_rebalancing_drift_weight_post_request.h \
    $${PWD}/OAI_portfolio_simulation_rebalancing_random_weight_post_request.h \
# APIs
    $${PWD}/OAIAssetsAnalysisApi.h \
    $${PWD}/OAIAssetsCorrelationMatrixApi.h \
    $${PWD}/OAIAssetsCovarianceMatrixApi.h \
    $${PWD}/OAIAssetsKurtosisApi.h \
    $${PWD}/OAIAssetsMonteCarloReturnsSimulationApi.h \
    $${PWD}/OAIAssetsPricesApi.h \
    $${PWD}/OAIAssetsReturnsApi.h \
    $${PWD}/OAIAssetsReturnsSimulationApi.h \
    $${PWD}/OAIAssetsSkewnessApi.h \
    $${PWD}/OAIAssetsVarianceApi.h \
    $${PWD}/OAIAssetsVolatilityApi.h \
    $${PWD}/OAIFactorsApi.h \
    $${PWD}/OAIPortfolioAnalysisApi.h \
    $${PWD}/OAIPortfolioAnalysisConditionalValueAtRiskApi.h \
    $${PWD}/OAIPortfolioAnalysisSharpeRatioApi.h \
    $${PWD}/OAIPortfolioAnalysisValueAtRiskApi.h \
    $${PWD}/OAIPortfolioConstructionApi.h \
    $${PWD}/OAIPortfolioOptimizationApi.h \
    $${PWD}/OAIPortfolioOptimizationMeanVarianceApi.h \
    $${PWD}/OAIPortfolioSimulationApi.h \
# Others
    $${PWD}/OAIHelpers.h \
    $${PWD}/OAIHttpRequest.h \
    $${PWD}/OAIObject.h \
    $${PWD}/OAIEnum.h \
    $${PWD}/OAIHttpFileElement.h \
    $${PWD}/OAIServerConfiguration.h \
    $${PWD}/OAIServerVariable.h \
    $${PWD}/OAIOauth.h

SOURCES += \
# Models
    $${PWD}/OAI_assets_analysis_absorption_ratio_post_200_response.cpp \
    $${PWD}/OAI_assets_analysis_absorption_ratio_post_request.cpp \
    $${PWD}/OAI_assets_analysis_absorption_ratio_post_request_assetsCovarianceMatrixEigenvectors.cpp \
    $${PWD}/OAI_assets_analysis_turbulence_index_post_200_response.cpp \
    $${PWD}/OAI_assets_analysis_turbulence_index_post_request.cpp \
    $${PWD}/OAI_assets_correlation_matrix_bounds_post_200_response.cpp \
    $${PWD}/OAI_assets_correlation_matrix_bounds_post_request.cpp \
    $${PWD}/OAI_assets_correlation_matrix_denoised_post_200_response.cpp \
    $${PWD}/OAI_assets_correlation_matrix_denoised_post_request.cpp \
    $${PWD}/OAI_assets_correlation_matrix_distance_post_200_response.cpp \
    $${PWD}/OAI_assets_correlation_matrix_distance_post_request.cpp \
    $${PWD}/OAI_assets_correlation_matrix_effective_rank_post_200_response.cpp \
    $${PWD}/OAI_assets_correlation_matrix_effective_rank_post_request.cpp \
    $${PWD}/OAI_assets_correlation_matrix_informativeness_post_200_response.cpp \
    $${PWD}/OAI_assets_correlation_matrix_informativeness_post_request.cpp \
    $${PWD}/OAI_assets_correlation_matrix_nearest_post_request.cpp \
    $${PWD}/OAI_assets_correlation_matrix_post_200_response.cpp \
    $${PWD}/OAI_assets_correlation_matrix_post_request.cpp \
    $${PWD}/OAI_assets_correlation_matrix_post_request_oneOf.cpp \
    $${PWD}/OAI_assets_correlation_matrix_post_request_oneOf_1.cpp \
    $${PWD}/OAI_assets_correlation_matrix_post_request_oneOf_assets_inner.cpp \
    $${PWD}/OAI_assets_correlation_matrix_random_post_request.cpp \
    $${PWD}/OAI_assets_correlation_matrix_shrinkage_post_request.cpp \
    $${PWD}/OAI_assets_correlation_matrix_shrinkage_post_request_oneOf.cpp \
    $${PWD}/OAI_assets_correlation_matrix_shrinkage_post_request_oneOf_1.cpp \
    $${PWD}/OAI_assets_correlation_matrix_theory_implied_post_request.cpp \
    $${PWD}/OAI_assets_correlation_matrix_theory_implied_post_request_assets_inner.cpp \
    $${PWD}/OAI_assets_correlation_matrix_theory_implied_post_request_assets_inner_assetHierarchicalClassification_inner.cpp \
    $${PWD}/OAI_assets_correlation_matrix_validation_post_200_response.cpp \
    $${PWD}/OAI_assets_correlation_matrix_validation_post_request.cpp \
    $${PWD}/OAI_assets_covariance_matrix_effective_rank_post_200_response.cpp \
    $${PWD}/OAI_assets_covariance_matrix_effective_rank_post_request.cpp \
    $${PWD}/OAI_assets_covariance_matrix_exponentially_weighted_post_200_response.cpp \
    $${PWD}/OAI_assets_covariance_matrix_exponentially_weighted_post_request.cpp \
    $${PWD}/OAI_assets_covariance_matrix_post_200_response.cpp \
    $${PWD}/OAI_assets_covariance_matrix_post_request.cpp \
    $${PWD}/OAI_assets_covariance_matrix_post_request_oneOf.cpp \
    $${PWD}/OAI_assets_covariance_matrix_post_request_oneOf_1.cpp \
    $${PWD}/OAI_assets_covariance_matrix_validation_post_200_response.cpp \
    $${PWD}/OAI_assets_kurtosis_post_200_response.cpp \
    $${PWD}/OAI_assets_kurtosis_post_200_response_assets_inner.cpp \
    $${PWD}/OAI_assets_kurtosis_post_request.cpp \
    $${PWD}/OAI_assets_kurtosis_post_request_assets_inner.cpp \
    $${PWD}/OAI_assets_prices_adjusted_post_200_response.cpp \
    $${PWD}/OAI_assets_prices_adjusted_post_200_response_assets_inner.cpp \
    $${PWD}/OAI_assets_prices_adjusted_post_200_response_assets_inner_assetAdjustedPrices_inner.cpp \
    $${PWD}/OAI_assets_prices_adjusted_post_request.cpp \
    $${PWD}/OAI_assets_prices_adjusted_post_request_assets_inner.cpp \
    $${PWD}/OAI_assets_prices_adjusted_post_request_assets_inner_assetDividends_inner.cpp \
    $${PWD}/OAI_assets_prices_adjusted_post_request_assets_inner_assetPrices_inner.cpp \
    $${PWD}/OAI_assets_prices_adjusted_post_request_assets_inner_assetSplits_inner.cpp \
    $${PWD}/OAI_assets_returns_average_post_200_response.cpp \
    $${PWD}/OAI_assets_returns_average_post_200_response_assets_inner.cpp \
    $${PWD}/OAI_assets_returns_average_post_request.cpp \
    $${PWD}/OAI_assets_returns_average_post_request_assets_inner.cpp \
    $${PWD}/OAI_assets_returns_logarithmic_post_200_response.cpp \
    $${PWD}/OAI_assets_returns_logarithmic_post_200_response_assets_inner.cpp \
    $${PWD}/OAI_assets_returns_post_200_response.cpp \
    $${PWD}/OAI_assets_returns_post_200_response_assets_inner.cpp \
    $${PWD}/OAI_assets_returns_post_request.cpp \
    $${PWD}/OAI_assets_returns_post_request_assets_inner.cpp \
    $${PWD}/OAI_assets_returns_simulation_bootstrap_post_200_response.cpp \
    $${PWD}/OAI_assets_returns_simulation_bootstrap_post_200_response_simulations_inner.cpp \
    $${PWD}/OAI_assets_returns_simulation_bootstrap_post_200_response_simulations_inner_assets_inner.cpp \
    $${PWD}/OAI_assets_returns_simulation_bootstrap_post_request.cpp \
    $${PWD}/OAI_assets_returns_simulation_bootstrap_post_request_assets_inner.cpp \
    $${PWD}/OAI_assets_returns_simulation_monte_carlo_cornish_fisher_corrected_post_request.cpp \
    $${PWD}/OAI_assets_returns_simulation_monte_carlo_cornish_fisher_post_200_response.cpp \
    $${PWD}/OAI_assets_returns_simulation_monte_carlo_cornish_fisher_post_200_response_simulations_inner.cpp \
    $${PWD}/OAI_assets_returns_simulation_monte_carlo_cornish_fisher_post_request.cpp \
    $${PWD}/OAI_assets_returns_simulation_monte_carlo_gaussian_post_request.cpp \
    $${PWD}/OAI_assets_returns_turbulence_partitioned_post_200_response.cpp \
    $${PWD}/OAI_assets_returns_turbulence_partitioned_post_200_response_assets_inner.cpp \
    $${PWD}/OAI_assets_returns_turbulence_partitioned_post_200_response_assets_inner_assetTurbulencePartitionedReturns_inner.cpp \
    $${PWD}/OAI_assets_returns_turbulence_partitioned_post_request.cpp \
    $${PWD}/OAI_assets_skewness_post_200_response.cpp \
    $${PWD}/OAI_assets_skewness_post_200_response_assets_inner.cpp \
    $${PWD}/OAI_assets_skewness_post_request.cpp \
    $${PWD}/OAI_assets_skewness_post_request_assets_inner.cpp \
    $${PWD}/OAI_assets_variance_post_200_response.cpp \
    $${PWD}/OAI_assets_variance_post_200_response_assets_inner.cpp \
    $${PWD}/OAI_assets_variance_post_request.cpp \
    $${PWD}/OAI_assets_variance_post_request_oneOf.cpp \
    $${PWD}/OAI_assets_variance_post_request_oneOf_1.cpp \
    $${PWD}/OAI_assets_variance_post_request_oneOf_1_assets_inner.cpp \
    $${PWD}/OAI_assets_variance_post_request_oneOf_assets_inner.cpp \
    $${PWD}/OAI_assets_volatility_post_200_response.cpp \
    $${PWD}/OAI_assets_volatility_post_200_response_assets_inner.cpp \
    $${PWD}/OAI_assets_volatility_post_request.cpp \
    $${PWD}/OAI_assets_volatility_post_request_oneOf.cpp \
    $${PWD}/OAI_assets_volatility_post_request_oneOf_assets_inner.cpp \
    $${PWD}/OAI_factors_residualization_post_200_response.cpp \
    $${PWD}/OAI_factors_residualization_post_request.cpp \
    $${PWD}/OAI_factors_residualization_post_request_factors_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_alpha_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_alpha_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_alpha_post_request.cpp \
    $${PWD}/OAI_portfolio_analysis_alpha_post_request_oneOf.cpp \
    $${PWD}/OAI_portfolio_analysis_alpha_post_request_oneOf_1.cpp \
    $${PWD}/OAI_portfolio_analysis_alpha_post_request_oneOf_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_beta_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_beta_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_contributions_return_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_contributions_return_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_contributions_return_post_request.cpp \
    $${PWD}/OAI_portfolio_analysis_contributions_return_post_request_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_contributions_risk_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_contributions_risk_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_contributions_risk_post_request.cpp \
    $${PWD}/OAI_portfolio_analysis_correlation_spectrum_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_correlation_spectrum_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_correlation_spectrum_post_request.cpp \
    $${PWD}/OAI_portfolio_analysis_correlation_spectrum_post_request_oneOf.cpp \
    $${PWD}/OAI_portfolio_analysis_correlation_spectrum_post_request_oneOf_1.cpp \
    $${PWD}/OAI_portfolio_analysis_correlation_spectrum_post_request_oneOf_1_assets_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_correlation_spectrum_post_request_oneOf_1_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_diversification_ratio_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_diversification_ratio_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_drawdowns_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_drawdowns_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_drawdowns_post_200_response_portfolios_inner_portfolioWorstDrawdowns_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_drawdowns_post_request.cpp \
    $${PWD}/OAI_portfolio_analysis_drawdowns_post_request_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_effective_number_of_bets_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_effective_number_of_bets_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_effective_number_of_bets_post_request.cpp \
    $${PWD}/OAI_portfolio_analysis_effective_number_of_bets_post_request_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_factors_exposures_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_factors_exposures_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_factors_exposures_post_request.cpp \
    $${PWD}/OAI_portfolio_analysis_factors_exposures_post_request_factors_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_factors_exposures_post_request_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_mean_variance_efficient_frontier_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_mean_variance_efficient_frontier_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_mean_variance_efficient_frontier_post_request.cpp \
    $${PWD}/OAI_portfolio_analysis_mean_variance_efficient_frontier_post_request_constraints.cpp \
    $${PWD}/OAI_portfolio_analysis_mean_variance_minimum_variance_frontier_post_request.cpp \
    $${PWD}/OAI_portfolio_analysis_return_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_return_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_return_post_request.cpp \
    $${PWD}/OAI_portfolio_analysis_return_post_request_oneOf.cpp \
    $${PWD}/OAI_portfolio_analysis_return_post_request_oneOf_1.cpp \
    $${PWD}/OAI_portfolio_analysis_return_post_request_oneOf_1_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_returns_average_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_returns_average_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_bias_adjusted_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_bias_adjusted_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_bias_adjusted_post_request.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_bias_adjusted_post_request_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_confidence_interval_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_confidence_interval_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_confidence_interval_post_request.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_post_request.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_post_request_oneOf.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_post_request_oneOf_1.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_post_request_oneOf_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_minimum_track_record_length_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_minimum_track_record_length_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_minimum_track_record_length_post_request.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_minimum_track_record_length_post_request_oneOf.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_minimum_track_record_length_post_request_oneOf_1.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_post_request.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_post_request_oneOf.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_post_request_oneOf_1.cpp \
    $${PWD}/OAI_portfolio_analysis_sharpe_ratio_probabilistic_post_request_oneOf_1_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_tracking_error_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_tracking_error_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_tracking_error_post_request.cpp \
    $${PWD}/OAI_portfolio_analysis_tracking_error_post_request_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_ulcer_index_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_ulcer_index_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_ulcer_performance_index_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_ulcer_performance_index_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_value_at_risk_conditional_cornish_fisher_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_value_at_risk_conditional_cornish_fisher_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_value_at_risk_conditional_cornish_fisher_post_request.cpp \
    $${PWD}/OAI_portfolio_analysis_value_at_risk_conditional_cornish_fisher_post_request_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_value_at_risk_conditional_gaussian_post_request.cpp \
    $${PWD}/OAI_portfolio_analysis_value_at_risk_conditional_gaussian_post_request_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_value_at_risk_conditional_historical_post_request.cpp \
    $${PWD}/OAI_portfolio_analysis_value_at_risk_cornish_fisher_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_value_at_risk_cornish_fisher_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_volatility_post_200_response.cpp \
    $${PWD}/OAI_portfolio_analysis_volatility_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_analysis_volatility_post_request.cpp \
    $${PWD}/OAI_portfolio_analysis_volatility_post_request_oneOf.cpp \
    $${PWD}/OAI_portfolio_construction_investable_post_200_response.cpp \
    $${PWD}/OAI_portfolio_construction_investable_post_request.cpp \
    $${PWD}/OAI_portfolio_construction_mimicking_post_request.cpp \
    $${PWD}/OAI_portfolio_construction_random_post_200_response.cpp \
    $${PWD}/OAI_portfolio_construction_random_post_request.cpp \
    $${PWD}/OAI_portfolio_construction_random_post_request_constraints.cpp \
    $${PWD}/OAI_portfolio_optimization_equal_risk_contributions_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_equal_risk_contributions_post_request_constraints.cpp \
    $${PWD}/OAI_portfolio_optimization_equal_sharpe_ratio_contributions_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_equal_volatility_weighted_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_hierarchical_risk_parity_clustering_based_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_hierarchical_risk_parity_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_inverse_variance_weighted_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_market_capitalization_weighted_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_maximum_decorrelation_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_maximum_return_diversified_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_maximum_return_diversified_post_request_constraints.cpp \
    $${PWD}/OAI_portfolio_optimization_maximum_return_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_maximum_return_subset_resampling_based_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_maximum_sharpe_ratio_diversified_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_maximum_sharpe_ratio_diversified_post_request_constraints.cpp \
    $${PWD}/OAI_portfolio_optimization_maximum_sharpe_ratio_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_maximum_sharpe_ratio_subset_resampling_based_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_maximum_ulcer_performance_index_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_mean_variance_efficient_diversified_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_mean_variance_efficient_diversified_post_request_constraints.cpp \
    $${PWD}/OAI_portfolio_optimization_mean_variance_efficient_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_mean_variance_efficient_post_request_constraints.cpp \
    $${PWD}/OAI_portfolio_optimization_mean_variance_efficient_subset_resampling_based_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_minimum_correlation_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_minimum_ulcer_index_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_minimum_variance_diversified_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_minimum_variance_diversified_post_request_constraints.cpp \
    $${PWD}/OAI_portfolio_optimization_minimum_variance_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_minimum_variance_subset_resampling_based_post_request.cpp \
    $${PWD}/OAI_portfolio_optimization_most_diversified_post_request.cpp \
    $${PWD}/OAI_portfolio_simulation_rebalancing_drift_weight_post_200_response.cpp \
    $${PWD}/OAI_portfolio_simulation_rebalancing_drift_weight_post_200_response_portfolios_inner.cpp \
    $${PWD}/OAI_portfolio_simulation_rebalancing_drift_weight_post_request.cpp \
    $${PWD}/OAI_portfolio_simulation_rebalancing_random_weight_post_request.cpp \
# APIs
    $${PWD}/OAIAssetsAnalysisApi.cpp \
    $${PWD}/OAIAssetsCorrelationMatrixApi.cpp \
    $${PWD}/OAIAssetsCovarianceMatrixApi.cpp \
    $${PWD}/OAIAssetsKurtosisApi.cpp \
    $${PWD}/OAIAssetsMonteCarloReturnsSimulationApi.cpp \
    $${PWD}/OAIAssetsPricesApi.cpp \
    $${PWD}/OAIAssetsReturnsApi.cpp \
    $${PWD}/OAIAssetsReturnsSimulationApi.cpp \
    $${PWD}/OAIAssetsSkewnessApi.cpp \
    $${PWD}/OAIAssetsVarianceApi.cpp \
    $${PWD}/OAIAssetsVolatilityApi.cpp \
    $${PWD}/OAIFactorsApi.cpp \
    $${PWD}/OAIPortfolioAnalysisApi.cpp \
    $${PWD}/OAIPortfolioAnalysisConditionalValueAtRiskApi.cpp \
    $${PWD}/OAIPortfolioAnalysisSharpeRatioApi.cpp \
    $${PWD}/OAIPortfolioAnalysisValueAtRiskApi.cpp \
    $${PWD}/OAIPortfolioConstructionApi.cpp \
    $${PWD}/OAIPortfolioOptimizationApi.cpp \
    $${PWD}/OAIPortfolioOptimizationMeanVarianceApi.cpp \
    $${PWD}/OAIPortfolioSimulationApi.cpp \
# Others
    $${PWD}/OAIHelpers.cpp \
    $${PWD}/OAIHttpRequest.cpp \
    $${PWD}/OAIHttpFileElement.cpp \
    $${PWD}/OAIOauth.cpp
