package shared

type LanguageEnum string

const (
	LanguageEnumAr      LanguageEnum = "ar"
	LanguageEnumCaEs    LanguageEnum = "ca-ES"
	LanguageEnumCmnCn   LanguageEnum = "cmn-CN"
	LanguageEnumCmnTw   LanguageEnum = "cmn-TW"
	LanguageEnumCsCz    LanguageEnum = "cs-CZ"
	LanguageEnumCyGb    LanguageEnum = "cy-GB"
	LanguageEnumDaDk    LanguageEnum = "da-DK"
	LanguageEnumDeDe    LanguageEnum = "de-DE"
	LanguageEnumElGr    LanguageEnum = "el-GR"
	LanguageEnumEnAu    LanguageEnum = "en-AU"
	LanguageEnumEnGb    LanguageEnum = "en-GB"
	LanguageEnumEnGbWls LanguageEnum = "en-GB-WLS"
	LanguageEnumEnIn    LanguageEnum = "en-IN"
	LanguageEnumEnUs    LanguageEnum = "en-US"
	LanguageEnumEnZa    LanguageEnum = "en-ZA"
	LanguageEnumEsEs    LanguageEnum = "es-ES"
	LanguageEnumEsMx    LanguageEnum = "es-MX"
	LanguageEnumEsUs    LanguageEnum = "es-US"
	LanguageEnumEuEs    LanguageEnum = "eu-ES"
	LanguageEnumFiFi    LanguageEnum = "fi-FI"
	LanguageEnumFilPh   LanguageEnum = "fil-PH"
	LanguageEnumFrCa    LanguageEnum = "fr-CA"
	LanguageEnumFrFr    LanguageEnum = "fr-FR"
	LanguageEnumHeIl    LanguageEnum = "he-IL"
	LanguageEnumHiIn    LanguageEnum = "hi-IN"
	LanguageEnumHuHu    LanguageEnum = "hu-HU"
	LanguageEnumIdid    LanguageEnum = "id-ID"
	LanguageEnumIsIs    LanguageEnum = "is-IS"
	LanguageEnumItIt    LanguageEnum = "it-IT"
	LanguageEnumJaJp    LanguageEnum = "ja-JP"
	LanguageEnumKoKr    LanguageEnum = "ko-KR"
	LanguageEnumNbNo    LanguageEnum = "nb-NO"
	LanguageEnumNlNl    LanguageEnum = "nl-NL"
	LanguageEnumNoNo    LanguageEnum = "no-NO"
	LanguageEnumPlPl    LanguageEnum = "pl-PL"
	LanguageEnumPtBr    LanguageEnum = "pt-BR"
	LanguageEnumPtPt    LanguageEnum = "pt-PT"
	LanguageEnumRoRo    LanguageEnum = "ro-RO"
	LanguageEnumRuRu    LanguageEnum = "ru-RU"
	LanguageEnumSkSk    LanguageEnum = "sk-SK"
	LanguageEnumSvSe    LanguageEnum = "sv-SE"
	LanguageEnumThTh    LanguageEnum = "th-TH"
	LanguageEnumTrTr    LanguageEnum = "tr-TR"
	LanguageEnumUkUa    LanguageEnum = "uk-UA"
	LanguageEnumViVn    LanguageEnum = "vi-VN"
	LanguageEnumYueCn   LanguageEnum = "yue-CN"
)
