openapi: 3.0.0
servers:
  - url: https://reseller.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: Perform common functions that are available on the Channel Services console at scale, like placing orders and viewing customer information
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Google Workspace Reseller API
  version: v1
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png
  x-origin:
    - format: openapi
      url: https://reseller.googleapis.com/$discovery/rest?version=v1
      version: "3.0"
  x-providerName: googleapis.com
  x-serviceName: reseller
tags:
  - name: customers
  - name: resellernotify
  - name: subscriptions
paths:
  /apps/reseller/v1/customers:
    post:
      description: Orders a new customer's account. Before ordering a new customer account, establish whether the customer account already exists using the [`customers.get`](/admin-sdk/reseller/v1/reference/customers/get) If the customer account exists as a direct Google account or as a resold customer account from another reseller, use the `customerAuthToken\` as described in [order a resold account for an existing customer](/admin-sdk/reseller/v1/how-tos/manage_customers#create_existing_custom[...]
      operationId: reseller.customers.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - customers
  "/apps/reseller/v1/customers/{customerId}":
    get:
      description: Gets a customer account. Use this operation to see a customer account already in your reseller management, or to see the minimal account information for an existing customer that you do not manage. For more information about the API response for existing customers, see [retrieving a customer account](/admin-sdk/reseller/v1/how-tos/manage_customers#get_customer).
      operationId: reseller.customers.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order.readonly
      tags:
        - customers
    patch:
      description: Updates a customer account's settings. This method supports patch semantics. You cannot update `customerType` via the Reseller API, but a `"team"` customer can verify their domain and become `customerType = "domain"`. For more information, see [Verify your domain to unlock Essentials features](https://support.google.com/a/answer/9122284).
      operationId: reseller.customers.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - customers
    put:
      description: Updates a customer account's settings. You cannot update `customerType` via the Reseller API, but a `"team"` customer can verify their domain and become `customerType = "domain"`. For more information, see [update a customer's settings](/admin-sdk/reseller/v1/how-tos/manage_customers#update_customer).
      operationId: reseller.customers.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - customers
  "/apps/reseller/v1/customers/{customerId}/subscriptions":
    post:
      description: Creates or transfer a subscription. Create a subscription for a customer's account that you ordered using the [Order a new customer account](/admin-sdk/reseller/v1/reference/customers/insert.html) method. For more information about creating a subscription for different payment plans, see [manage subscriptions](/admin-sdk/reseller/v1/how-tos/manage_subscriptions#create_subscription).\ If you did not order the customer's account using the customer insert method, use the customer[...]
      operationId: reseller.subscriptions.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - subscriptions
  "/apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}":
    delete:
      description: Cancels, suspends, or transfers a subscription to direct.
      operationId: reseller.subscriptions.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - subscriptions
    get:
      description: Gets a specific subscription. The `subscriptionId` can be found using the [Retrieve all reseller subscriptions](/admin-sdk/reseller/v1/how-tos/manage_subscriptions#get_all_subscriptions) method. For more information about retrieving a specific subscription, see the information descrived in [manage subscriptions](/admin-sdk/reseller/v1/how-tos/manage_subscriptions#get_subscription).
      operationId: reseller.subscriptions.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order.readonly
      tags:
        - subscriptions
  "/apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/activate":
    post:
      description: Activates a subscription previously suspended by the reseller. If you did not suspend the customer subscription and it is suspended for any other reason, such as for abuse or a pending ToS acceptance, this call will not reactivate the customer subscription.
      operationId: reseller.subscriptions.activate
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - subscriptions
  "/apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/changePlan":
    post:
      description: Updates a subscription plan. Use this method to update a plan for a 30-day trial or a flexible plan subscription to an annual commitment plan with monthly or yearly payments. How a plan is updated differs depending on the plan and the products. For more information, see the description in [manage subscriptions](/admin-sdk/reseller/v1/how-tos/manage_subscriptions#update_subscription_plan).
      operationId: reseller.subscriptions.changePlan
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - subscriptions
  "/apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/changeRenewalSettings":
    post:
      description: Updates a user license's renewal settings. This is applicable for accounts with annual commitment plans only. For more information, see the description in [manage subscriptions](/admin-sdk/reseller/v1/how-tos/manage_subscriptions#update_renewal).
      operationId: reseller.subscriptions.changeRenewalSettings
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - subscriptions
  "/apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/changeSeats":
    post:
      description: Updates a subscription's user license settings. For more information about updating an annual commitment plan or a flexible plan subscription’s licenses, see [Manage Subscriptions](/admin-sdk/reseller/v1/how-tos/manage_subscriptions#update_subscription_seat).
      operationId: reseller.subscriptions.changeSeats
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - subscriptions
  "/apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/startPaidService":
    post:
      description: Immediately move a 30-day free trial subscription to a paid service subscription. This method is only applicable if a payment plan has already been set up for the 30-day trial subscription. For more information, see [manage subscriptions](/admin-sdk/reseller/v1/how-tos/manage_subscriptions#paid_service).
      operationId: reseller.subscriptions.startPaidService
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - subscriptions
  "/apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/suspend":
    post:
      description: "Suspends an active subscription. You can use this method to suspend a paid subscription that is currently in the `ACTIVE` state. * For `FLEXIBLE` subscriptions, billing is paused. * For `ANNUAL_MONTHLY_PAY` or `ANNUAL_YEARLY_PAY` subscriptions: * Suspending the subscription does not change the renewal date that was originally committed to. * A suspended subscription does not renew. If you activate the subscription after the original renewal date, a new annual subscription wil[...]"
      operationId: reseller.subscriptions.suspend
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - subscriptions
  /apps/reseller/v1/resellernotify/getwatchdetails:
    get:
      description: Returns all the details of the watch corresponding to the reseller.
      operationId: reseller.resellernotify.getwatchdetails
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order.readonly
      tags:
        - resellernotify
  /apps/reseller/v1/resellernotify/register:
    post:
      description: Registers a Reseller for receiving notifications.
      operationId: reseller.resellernotify.register
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - resellernotify
  /apps/reseller/v1/resellernotify/unregister:
    post:
      description: Unregisters a Reseller for receiving notifications.
      operationId: reseller.resellernotify.unregister
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
      tags:
        - resellernotify
  /apps/reseller/v1/subscriptions:
    get:
      description: Lists of subscriptions managed by the reseller. The list can be all subscriptions, all of a customer's subscriptions, or all of a customer's transferable subscriptions. Optionally, this method can filter the response by a `customerNamePrefix`. For more information, see [manage subscriptions](/admin-sdk/reseller/v1/how-tos/manage_subscriptions).
      operationId: reseller.subscriptions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order
        - Oauth2:
            - https://www.googleapis.com/auth/apps.order.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/apps.order.readonly
      tags:
        - subscriptions
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/apps.order: Manage users on your domain
            https://www.googleapis.com/auth/apps.order.readonly: Manage users on your domain
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/apps.order: Manage users on your domain
            https://www.googleapis.com/auth/apps.order.readonly: Manage users on your domain
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
