{
  "swagger": "2.0",
  "info": {
    "title": "Genomics API",
    "x-serviceName": "genomics",
    "description": "Provides access to Genomics data.",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v1beta2",
    "x-origin": {
      "format": "google",
      "version": "v1",
      "uri": "https://www.googleapis.com/discovery/v1/apis/genomics/v1beta2/rest"
    }
  },
  "host": "www.googleapis.com",
  "basePath": "/genomics/v1beta2",
  "schemes": [
    "https"
  ],
  "paths": {
    "/annotationSets": {
      "post": {
        "description": "Creates a new annotation set. Caller must have WRITE permission for the associated dataset.",
        "operationId": "genomics.annotationSets.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "annotationSets"
        ]
      }
    },
    "/annotationSets/{annotationSetId}": {
      "delete": {
        "description": "Deletes an annotation set. Caller must have WRITE permission for the associated annotation set.",
        "operationId": "genomics.annotationSets.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "annotationSets"
        ]
      },
      "get": {
        "description": "Gets an annotation set. Caller must have READ permission for the associated dataset.",
        "operationId": "genomics.annotationSets.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "annotationSets"
        ]
      },
      "patch": {
        "description": "Updates an annotation set. The update must respect all mutability restrictions and other invariants described on the annotation set resource. Caller must have WRITE permission for the associated dataset. This method supports patch semantics.",
        "operationId": "genomics.annotationSets.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "annotationSets"
        ]
      },
      "put": {
        "description": "Updates an annotation set. The update must respect all mutability restrictions and other invariants described on the annotation set resource. Caller must have WRITE permission for the associated dataset.",
        "operationId": "genomics.annotationSets.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "annotationSets"
        ]
      }
    },
    "/annotationSets/search": {
      "post": {
        "description": "Searches for annotation sets that match the given criteria. Results are returned in a deterministic order. Caller must have READ permission for the queried datasets.",
        "operationId": "genomics.annotationSets.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "annotationSets"
        ]
      }
    },
    "/annotations:batchCreate": {
      "post": {
        "description": "Creates one or more new annotations atomically. All annotations must belong to the same annotation set. Caller must have WRITE permission for this annotation set. For optimal performance, batch positionally adjacent annotations together.\n\n\nIf the request has a systemic issue, such as an attempt to write to an inaccessible annotation set, the entire RPC will fail accordingly. For lesser data issues, when possible an error will be isolated to the corresponding batch entr[...]",
        "operationId": "genomics.annotations.batchCreate",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "annotations"
        ]
      }
    },
    "/annotations": {
      "post": {
        "description": "Creates a new annotation. Caller must have WRITE permission for the associated annotation set.",
        "operationId": "genomics.annotations.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "annotations"
        ]
      }
    },
    "/annotations/{annotationId}": {
      "delete": {
        "description": "Deletes an annotation. Caller must have WRITE permission for the associated annotation set.",
        "operationId": "genomics.annotations.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "annotations"
        ]
      },
      "get": {
        "description": "Gets an annotation. Caller must have READ permission for the associated annotation set.",
        "operationId": "genomics.annotations.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "annotations"
        ]
      },
      "patch": {
        "description": "Updates an annotation. The update must respect all mutability restrictions and other invariants described on the annotation resource. Caller must have WRITE permission for the associated dataset. This method supports patch semantics.",
        "operationId": "genomics.annotations.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "annotations"
        ]
      },
      "put": {
        "description": "Updates an annotation. The update must respect all mutability restrictions and other invariants described on the annotation resource. Caller must have WRITE permission for the associated dataset.",
        "operationId": "genomics.annotations.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "annotations"
        ]
      }
    },
    "/annotations/search": {
      "post": {
        "description": "Searches for annotations that match the given criteria. Results are returned ordered by start position. Annotations that have matching start positions are ordered deterministically. Caller must have READ permission for the queried annotation sets.",
        "operationId": "genomics.annotations.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "annotations"
        ]
      }
    },
    "/callsets": {
      "post": {
        "description": "Creates a new call set.",
        "operationId": "genomics.callsets.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "callsets"
        ]
      }
    },
    "/callsets/{callSetId}": {
      "delete": {
        "description": "Deletes a call set.",
        "operationId": "genomics.callsets.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "callsets"
        ]
      },
      "get": {
        "description": "Gets a call set by ID.",
        "operationId": "genomics.callsets.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "callsets"
        ]
      },
      "patch": {
        "description": "Updates a call set. This method supports patch semantics.",
        "operationId": "genomics.callsets.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "callsets"
        ]
      },
      "put": {
        "description": "Updates a call set.",
        "operationId": "genomics.callsets.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "callsets"
        ]
      }
    },
    "/callsets/search": {
      "post": {
        "description": "Gets a list of call sets matching the criteria.\n\nImplements GlobalAllianceApi.searchCallSets.",
        "operationId": "genomics.callsets.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "callsets"
        ]
      }
    },
    "/datasets": {
      "post": {
        "description": "Creates a new dataset.",
        "operationId": "genomics.datasets.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "datasets"
        ]
      },
      "get": {
        "description": "Lists datasets within a project.",
        "operationId": "genomics.datasets.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "datasets"
        ]
      }
    },
    "/datasets/{datasetId}": {
      "delete": {
        "description": "Deletes a dataset.",
        "operationId": "genomics.datasets.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "datasets"
        ]
      },
      "get": {
        "description": "Gets a dataset by ID.",
        "operationId": "genomics.datasets.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "datasets"
        ]
      },
      "patch": {
        "description": "Updates a dataset. This method supports patch semantics.",
        "operationId": "genomics.datasets.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "datasets"
        ]
      },
      "put": {
        "description": "Updates a dataset.",
        "operationId": "genomics.datasets.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "datasets"
        ]
      }
    },
    "/datasets/{datasetId}/undelete": {
      "post": {
        "description": "Undeletes a dataset by restoring a dataset which was deleted via this API. This operation is only possible for a week after the deletion occurred.",
        "operationId": "genomics.datasets.undelete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "datasets"
        ]
      }
    },
    "/experimental/jobs/create": {
      "post": {
        "description": "Creates and asynchronously runs an ad-hoc job. This is an experimental call and may be removed or changed at any time.",
        "operationId": "genomics.experimental.jobs.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/devstorage.read_write",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "experimental"
        ]
      }
    },
    "/jobs/{jobId}/cancel": {
      "post": {
        "description": "Cancels a job by ID. Note that it is possible for partial results to be generated and stored for cancelled jobs.",
        "operationId": "genomics.jobs.cancel",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "jobs"
        ]
      }
    },
    "/jobs/{jobId}": {
      "get": {
        "description": "Gets a job by ID.",
        "operationId": "genomics.jobs.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "jobs"
        ]
      }
    },
    "/jobs/search": {
      "post": {
        "description": "Gets a list of jobs matching the criteria.",
        "operationId": "genomics.jobs.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "jobs"
        ]
      }
    },
    "/readgroupsets/align": {
      "post": {
        "description": "Aligns read data from existing read group sets or files from Google Cloud Storage. See the  alignment and variant calling documentation for more details.",
        "operationId": "genomics.readgroupsets.align",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/devstorage.read_write",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "readgroupsets"
        ]
      }
    },
    "/readgroupsets/call": {
      "post": {
        "description": "Calls variants on read data from existing read group sets or files from Google Cloud Storage. See the  alignment and variant calling documentation for more details.",
        "operationId": "genomics.readgroupsets.call",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/devstorage.read_write",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "readgroupsets"
        ]
      }
    },
    "/readgroupsets/{readGroupSetId}": {
      "delete": {
        "description": "Deletes a read group set.",
        "operationId": "genomics.readgroupsets.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "readgroupsets"
        ]
      },
      "get": {
        "description": "Gets a read group set by ID.",
        "operationId": "genomics.readgroupsets.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "readgroupsets"
        ]
      },
      "patch": {
        "description": "Updates a read group set. This method supports patch semantics.",
        "operationId": "genomics.readgroupsets.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "readgroupsets"
        ]
      },
      "put": {
        "description": "Updates a read group set.",
        "operationId": "genomics.readgroupsets.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "readgroupsets"
        ]
      }
    },
    "/readgroupsets/export": {
      "post": {
        "description": "Exports read group sets to a BAM file in Google Cloud Storage.\n\nNote that currently there may be some differences between exported BAM files and the original BAM file at the time of import. In particular, comments in the input file header will not be preserved, some custom tags will be converted to strings, and original reference sequence order is not necessarily preserved.",
        "operationId": "genomics.readgroupsets.export",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/devstorage.read_write",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "readgroupsets"
        ]
      }
    },
    "/readgroupsets/import": {
      "post": {
        "description": "Creates read group sets by asynchronously importing the provided information.\n\nNote that currently comments in the input file header are not imported and some custom tags will be converted to strings, rather than preserving tag types. The caller must have WRITE permissions to the dataset.",
        "operationId": "genomics.readgroupsets.import",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/devstorage.read_write",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "readgroupsets"
        ]
      }
    },
    "/readgroupsets/search": {
      "post": {
        "description": "Searches for read group sets matching the criteria.\n\nImplements GlobalAllianceApi.searchReadGroupSets.",
        "operationId": "genomics.readgroupsets.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "readgroupsets"
        ]
      }
    },
    "/readgroupsets/{readGroupSetId}/coveragebuckets": {
      "get": {
        "description": "Lists fixed width coverage buckets for a read group set, each of which correspond to a range of a reference sequence. Each bucket summarizes coverage information across its corresponding genomic range.\n\nCoverage is defined as the number of reads which are aligned to a given base in the reference sequence. Coverage buckets are available at several precomputed bucket widths, enabling retrieval of various coverage 'zoom levels'. The caller must have READ permissions for th[...]",
        "operationId": "genomics.readgroupsets.coveragebuckets.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "readgroupsets"
        ]
      }
    },
    "/reads/search": {
      "post": {
        "description": "Gets a list of reads for one or more read group sets. Reads search operates over a genomic coordinate space of reference sequence & position defined over the reference sequences to which the requested read group sets are aligned.\n\nIf a target positional range is specified, search returns all reads whose alignment to the reference genome overlap the range. A query which specifies only read group set IDs yields all reads in those read group sets, including unmapped reads.[...]",
        "operationId": "genomics.reads.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "reads"
        ]
      }
    },
    "/references/{referenceId}": {
      "get": {
        "description": "Gets a reference.\n\nImplements GlobalAllianceApi.getReference.",
        "operationId": "genomics.references.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "references"
        ]
      }
    },
    "/references/search": {
      "post": {
        "description": "Searches for references which match the given criteria.\n\nImplements GlobalAllianceApi.searchReferences.",
        "operationId": "genomics.references.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "references"
        ]
      }
    },
    "/references/{referenceId}/bases": {
      "get": {
        "description": "Lists the bases in a reference, optionally restricted to a range.\n\nImplements GlobalAllianceApi.getReferenceBases.",
        "operationId": "genomics.references.bases.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "references"
        ]
      }
    },
    "/referencesets/{referenceSetId}": {
      "get": {
        "description": "Gets a reference set.\n\nImplements GlobalAllianceApi.getReferenceSet.",
        "operationId": "genomics.referencesets.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "referencesets"
        ]
      }
    },
    "/referencesets/search": {
      "post": {
        "description": "Searches for reference sets which match the given criteria.\n\nImplements GlobalAllianceApi.searchReferenceSets.",
        "operationId": "genomics.referencesets.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "referencesets"
        ]
      }
    },
    "/variants": {
      "post": {
        "description": "Creates a new variant.",
        "operationId": "genomics.variants.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "variants"
        ]
      }
    },
    "/variants/{variantId}": {
      "delete": {
        "description": "Deletes a variant.",
        "operationId": "genomics.variants.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "variants"
        ]
      },
      "get": {
        "description": "Gets a variant by ID.",
        "operationId": "genomics.variants.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "variants"
        ]
      },
      "put": {
        "description": "Updates a variant's names and info fields. All other modifications are silently ignored. Returns the modified variant without its calls.",
        "operationId": "genomics.variants.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "variants"
        ]
      }
    },
    "/variants/search": {
      "post": {
        "description": "Gets a list of variants matching the criteria.\n\nImplements GlobalAllianceApi.searchVariants.",
        "operationId": "genomics.variants.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "variants"
        ]
      }
    },
    "/variantsets/{variantSetId}": {
      "delete": {
        "description": "Deletes the contents of a variant set. The variant set object is not deleted.",
        "operationId": "genomics.variantsets.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "variantsets"
        ]
      },
      "get": {
        "description": "Gets a variant set by ID.",
        "operationId": "genomics.variantsets.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "variantsets"
        ]
      },
      "patch": {
        "description": "Updates a variant set's metadata. All other modifications are silently ignored. This method supports patch semantics.",
        "operationId": "genomics.variantsets.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "variantsets"
        ]
      },
      "put": {
        "description": "Updates a variant set's metadata. All other modifications are silently ignored.",
        "operationId": "genomics.variantsets.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "variantsets"
        ]
      }
    },
    "/variantsets/{variantSetId}/export": {
      "post": {
        "description": "Exports variant set data to an external destination.",
        "operationId": "genomics.variantsets.export",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/bigquery",
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "variantsets"
        ]
      }
    },
    "/variantsets/{variantSetId}/importVariants": {
      "post": {
        "description": "Creates variant data by asynchronously importing the provided information.\n\nThe variants for import will be merged with any existing data and each other according to the behavior of mergeVariants. In particular, this means for merged VCF variants that have conflicting INFO fields, some data will be arbitrarily discarded. As a special case, for single-sample VCF files, QUAL and FILTER fields will be moved to the call level; these are sometimes interpreted in a call-speci[...]",
        "operationId": "genomics.variantsets.importVariants",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/devstorage.read_write",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "variantsets"
        ]
      }
    },
    "/variantsets/{variantSetId}/mergeVariants": {
      "post": {
        "description": "Merges the given variants with existing variants. Each variant will be merged with an existing variant that matches its reference sequence, start, end, reference bases, and alternative bases. If no such variant exists, a new one will be created.\n\nWhen variants are merged, the call information from the new variant is added to the existing variant, and other fields (such as key/value pairs) are discarded.",
        "operationId": "genomics.variantsets.mergeVariants",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "variantsets"
        ]
      }
    },
    "/variantsets/search": {
      "post": {
        "description": "Returns a list of all variant sets matching search criteria.\n\nImplements GlobalAllianceApi.searchVariantSets.",
        "operationId": "genomics.variantsets.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/genomics",
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "variantsets"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/bigquery": "View and manage your data in Google BigQuery",
        "https://www.googleapis.com/auth/cloud-platform": "View and manage your data across Google Cloud Platform services",
        "https://www.googleapis.com/auth/devstorage.read_write": "Manage your data in Google Cloud Storage",
        "https://www.googleapis.com/auth/genomics": "View and manage Genomics data",
        "https://www.googleapis.com/auth/genomics.readonly": "View Genomics data"
      }
    }
  }
}