# coding: utf-8

"""
    WebSite Management Client

    Use these APIs to manage Azure Websites resources through the Azure Resource Manager. All task operations conform to the HTTP/1.1 protocol specification and each operation returns an x-ms-request-id header that can be used to obtain information about the request. You must make sure that requests made to these resources are secure. For more information, see https://msdn.microsoft.com/en-us/library/azure/dn790557.aspx.

    The version of the OpenAPI document: 2015-08-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.managed_hosting_environments_api import ManagedHostingEnvironmentsApi


class TestManagedHostingEnvironmentsApi(unittest.TestCase):
    """ManagedHostingEnvironmentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ManagedHostingEnvironmentsApi()

    def tearDown(self) -> None:
        pass

    def test_managed_hosting_environments_create_or_update_managed_hosting_environment(self) -> None:
        """Test case for managed_hosting_environments_create_or_update_managed_hosting_environment

        Create or update a managed hosting environment.
        """
        pass

    def test_managed_hosting_environments_delete_managed_hosting_environment(self) -> None:
        """Test case for managed_hosting_environments_delete_managed_hosting_environment

        Delete a managed hosting environment.
        """
        pass

    def test_managed_hosting_environments_get_managed_hosting_environment(self) -> None:
        """Test case for managed_hosting_environments_get_managed_hosting_environment

        Get properties of a managed hosting environment.
        """
        pass

    def test_managed_hosting_environments_get_managed_hosting_environment_operation(self) -> None:
        """Test case for managed_hosting_environments_get_managed_hosting_environment_operation

        Get status of an operation on a managed hosting environment.
        """
        pass

    def test_managed_hosting_environments_get_managed_hosting_environment_server_farms(self) -> None:
        """Test case for managed_hosting_environments_get_managed_hosting_environment_server_farms

        Get all serverfarms (App Service Plans) on the managed hosting environment.
        """
        pass

    def test_managed_hosting_environments_get_managed_hosting_environment_sites(self) -> None:
        """Test case for managed_hosting_environments_get_managed_hosting_environment_sites

        Get all sites on the managed hosting environment.
        """
        pass

    def test_managed_hosting_environments_get_managed_hosting_environment_vips(self) -> None:
        """Test case for managed_hosting_environments_get_managed_hosting_environment_vips

        Get list of ip addresses assigned to a managed hosting environment
        """
        pass

    def test_managed_hosting_environments_get_managed_hosting_environment_web_hosting_plans(self) -> None:
        """Test case for managed_hosting_environments_get_managed_hosting_environment_web_hosting_plans

        Get all serverfarms (App Service Plans) on the managed hosting environment.
        """
        pass

    def test_managed_hosting_environments_get_managed_hosting_environments(self) -> None:
        """Test case for managed_hosting_environments_get_managed_hosting_environments

        Get all managed hosting environments in a resource group.
        """
        pass


if __name__ == '__main__':
    unittest.main()
