swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /admin/datatransfer/v1
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Transfers user data from one user to another.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Admin Data Transfer
  version: datatransfer_v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-apisguru-categories:
    - analytics
  x-logo:
    url: 'https://www.gstatic.com/images/icons/material/product/2x/admin_64dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/admin/datatransfer_v1/rest'
      version: v1
  x-preferred: false
  x-providerName: googleapis.com
  x-serviceName: admin
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/admin.datatransfer': View and manage data transfers between users in your organization
      'https://www.googleapis.com/auth/admin.datatransfer.readonly': View data transfers between users in your organization
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/admin.datatransfer': View and manage data transfers between users in your organization
      'https://www.googleapis.com/auth/admin.datatransfer.readonly': View data transfers between users in your organization
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: applications
  - name: transfers
paths:
  /applications:
    get:
      description: Lists the applications available for data transfer for a customer.
      operationId: datatransfer.applications.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.datatransfer'
          Oauth2c:
            - 'https://www.googleapis.com/auth/admin.datatransfer'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.datatransfer.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/admin.datatransfer.readonly'
      tags:
        - applications
  '/applications/{applicationId}':
    get:
      description: Retrieves information about an application for the given application ID.
      operationId: datatransfer.applications.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.datatransfer'
          Oauth2c:
            - 'https://www.googleapis.com/auth/admin.datatransfer'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.datatransfer.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/admin.datatransfer.readonly'
      tags:
        - applications
  /transfers:
    get:
      description: 'Lists the transfers for a customer by source user, destination user, or status.'
      operationId: datatransfer.transfers.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.datatransfer'
          Oauth2c:
            - 'https://www.googleapis.com/auth/admin.datatransfer'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.datatransfer.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/admin.datatransfer.readonly'
      tags:
        - transfers
    post:
      description: Inserts a data transfer request.
      operationId: datatransfer.transfers.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.datatransfer'
          Oauth2c:
            - 'https://www.googleapis.com/auth/admin.datatransfer'
      tags:
        - transfers
  '/transfers/{dataTransferId}':
    get:
      description: Retrieves a data transfer request by its resource ID.
      operationId: datatransfer.transfers.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.datatransfer'
          Oauth2c:
            - 'https://www.googleapis.com/auth/admin.datatransfer'
        - Oauth2:
            - 'https://www.googleapis.com/auth/admin.datatransfer.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/admin.datatransfer.readonly'
      tags:
        - transfers