package shared

type Request struct {
	AddBanding                   *AddBandingRequest                   `json:"addBanding,omitempty"`
	AddChart                     *AddChartRequest                     `json:"addChart,omitempty"`
	AddConditionalFormatRule     *AddConditionalFormatRuleRequest     `json:"addConditionalFormatRule,omitempty"`
	AddDataSource                *AddDataSourceRequest                `json:"addDataSource,omitempty"`
	AddDimensionGroup            *AddDimensionGroupRequest            `json:"addDimensionGroup,omitempty"`
	AddFilterView                *AddFilterViewRequest                `json:"addFilterView,omitempty"`
	AddNamedRange                *AddNamedRangeRequest                `json:"addNamedRange,omitempty"`
	AddProtectedRange            *AddProtectedRangeRequest            `json:"addProtectedRange,omitempty"`
	AddSheet                     *AddSheetRequest                     `json:"addSheet,omitempty"`
	AddSlicer                    *AddSlicerRequest                    `json:"addSlicer,omitempty"`
	AppendCells                  *AppendCellsRequest                  `json:"appendCells,omitempty"`
	AppendDimension              *AppendDimensionRequest              `json:"appendDimension,omitempty"`
	AutoFill                     *AutoFillRequest                     `json:"autoFill,omitempty"`
	AutoResizeDimensions         *AutoResizeDimensionsRequest         `json:"autoResizeDimensions,omitempty"`
	ClearBasicFilter             *ClearBasicFilterRequest             `json:"clearBasicFilter,omitempty"`
	CopyPaste                    *CopyPasteRequest                    `json:"copyPaste,omitempty"`
	CreateDeveloperMetadata      *CreateDeveloperMetadataRequest      `json:"createDeveloperMetadata,omitempty"`
	CutPaste                     *CutPasteRequest                     `json:"cutPaste,omitempty"`
	DeleteBanding                *DeleteBandingRequest                `json:"deleteBanding,omitempty"`
	DeleteConditionalFormatRule  *DeleteConditionalFormatRuleRequest  `json:"deleteConditionalFormatRule,omitempty"`
	DeleteDataSource             *DeleteDataSourceRequest             `json:"deleteDataSource,omitempty"`
	DeleteDeveloperMetadata      *DeleteDeveloperMetadataRequest      `json:"deleteDeveloperMetadata,omitempty"`
	DeleteDimension              *DeleteDimensionRequest              `json:"deleteDimension,omitempty"`
	DeleteDimensionGroup         *DeleteDimensionGroupRequest         `json:"deleteDimensionGroup,omitempty"`
	DeleteDuplicates             *DeleteDuplicatesRequest             `json:"deleteDuplicates,omitempty"`
	DeleteEmbeddedObject         *DeleteEmbeddedObjectRequest         `json:"deleteEmbeddedObject,omitempty"`
	DeleteFilterView             *DeleteFilterViewRequest             `json:"deleteFilterView,omitempty"`
	DeleteNamedRange             *DeleteNamedRangeRequest             `json:"deleteNamedRange,omitempty"`
	DeleteProtectedRange         *DeleteProtectedRangeRequest         `json:"deleteProtectedRange,omitempty"`
	DeleteRange                  *DeleteRangeRequest                  `json:"deleteRange,omitempty"`
	DeleteSheet                  *DeleteSheetRequest                  `json:"deleteSheet,omitempty"`
	DuplicateFilterView          *DuplicateFilterViewRequest          `json:"duplicateFilterView,omitempty"`
	DuplicateSheet               *DuplicateSheetRequest               `json:"duplicateSheet,omitempty"`
	FindReplace                  *FindReplaceRequest                  `json:"findReplace,omitempty"`
	InsertDimension              *InsertDimensionRequest              `json:"insertDimension,omitempty"`
	InsertRange                  *InsertRangeRequest                  `json:"insertRange,omitempty"`
	MergeCells                   *MergeCellsRequest                   `json:"mergeCells,omitempty"`
	MoveDimension                *MoveDimensionRequest                `json:"moveDimension,omitempty"`
	PasteData                    *PasteDataRequest                    `json:"pasteData,omitempty"`
	RandomizeRange               *RandomizeRangeRequest               `json:"randomizeRange,omitempty"`
	RefreshDataSource            *RefreshDataSourceRequest            `json:"refreshDataSource,omitempty"`
	RepeatCell                   *RepeatCellRequest                   `json:"repeatCell,omitempty"`
	SetBasicFilter               *SetBasicFilterRequest               `json:"setBasicFilter,omitempty"`
	SetDataValidation            *SetDataValidationRequest            `json:"setDataValidation,omitempty"`
	SortRange                    *SortRangeRequest                    `json:"sortRange,omitempty"`
	TextToColumns                *TextToColumnsRequest                `json:"textToColumns,omitempty"`
	TrimWhitespace               *TrimWhitespaceRequest               `json:"trimWhitespace,omitempty"`
	UnmergeCells                 *UnmergeCellsRequest                 `json:"unmergeCells,omitempty"`
	UpdateBanding                *UpdateBandingRequest                `json:"updateBanding,omitempty"`
	UpdateBorders                *UpdateBordersRequest                `json:"updateBorders,omitempty"`
	UpdateCells                  *UpdateCellsRequest                  `json:"updateCells,omitempty"`
	UpdateChartSpec              *UpdateChartSpecRequest              `json:"updateChartSpec,omitempty"`
	UpdateConditionalFormatRule  *UpdateConditionalFormatRuleRequest  `json:"updateConditionalFormatRule,omitempty"`
	UpdateDataSource             *UpdateDataSourceRequest             `json:"updateDataSource,omitempty"`
	UpdateDeveloperMetadata      *UpdateDeveloperMetadataRequest      `json:"updateDeveloperMetadata,omitempty"`
	UpdateDimensionGroup         *UpdateDimensionGroupRequest         `json:"updateDimensionGroup,omitempty"`
	UpdateDimensionProperties    *UpdateDimensionPropertiesRequest    `json:"updateDimensionProperties,omitempty"`
	UpdateEmbeddedObjectBorder   *UpdateEmbeddedObjectBorderRequest   `json:"updateEmbeddedObjectBorder,omitempty"`
	UpdateEmbeddedObjectPosition *UpdateEmbeddedObjectPositionRequest `json:"updateEmbeddedObjectPosition,omitempty"`
	UpdateFilterView             *UpdateFilterViewRequest             `json:"updateFilterView,omitempty"`
	UpdateNamedRange             *UpdateNamedRangeRequest             `json:"updateNamedRange,omitempty"`
	UpdateProtectedRange         *UpdateProtectedRangeRequest         `json:"updateProtectedRange,omitempty"`
	UpdateSheetProperties        *UpdateSheetPropertiesRequest        `json:"updateSheetProperties,omitempty"`
	UpdateSlicerSpec             *UpdateSlicerSpecRequest             `json:"updateSlicerSpec,omitempty"`
	UpdateSpreadsheetProperties  *UpdateSpreadsheetPropertiesRequest  `json:"updateSpreadsheetProperties,omitempty"`
}
