{
  "swagger": "2.0",
  "info": {
    "title": "Google Classroom API",
    "x-serviceName": "classroom",
    "description": "Google Classroom API",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v1beta1",
    "x-providerName": "googleapis.com",
    "x-origin": {
      "format": "google",
      "version": "v1",
      "url": "https://www.googleapis.com/discovery/v1/apis/classroom/v1beta1/rest"
    }
  },
  "host": "classroom.googleapis.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/v1beta1/courses": {
      "post": {
        "description": "Creates a course. The user specified as the primary teacher in `primary_teacher_id` is the owner of the created course and added as a teacher. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create courses. * `NOT_FOUND` if the primary teacher is not a valid user. * `ALREADY_EXISTS` if an alias was specified and already exists.",
        "operationId": "classroom.courses.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/classroom.courses"
            ]
          }
        ],
        "tags": [
          "courses"
        ]
      },
      "get": {
        "description": "Returns a list of courses that the requesting user is permitted to view, restricted to those that match the request. This method returns the following error codes: * `INVALID_ARGUMENT` if the query argument is malformed. * `NOT_FOUND` if any users specified in the query arguments do not exist.",
        "operationId": "classroom.courses.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/classroom.courses",
              "https://www.googleapis.com/auth/classroom.courses.readonly"
            ]
          }
        ],
        "tags": [
          "courses"
        ]
      }
    },
    "/v1beta1/courses/{id}": {
      "get": {
        "description": "Returns a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course. * `NOT_FOUND` if no course exists with the requested ID.",
        "operationId": "classroom.courses.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/classroom.courses",
              "https://www.googleapis.com/auth/classroom.courses.readonly"
            ]
          }
        ],
        "tags": [
          "courses"
        ]
      },
      "put": {
        "description": "Updates a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to modify the requested course. * `NOT_FOUND` if no course exists with the requested ID.",
        "operationId": "classroom.courses.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/classroom.courses"
            ]
          }
        ],
        "tags": [
          "courses"
        ]
      },
      "patch": {
        "description": "Updates one or more fields a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to modify the requested course. * `NOT_FOUND` if no course exists with the requested ID. * `INVALID_ARGUMENT` if invalid fields are specified in the update mask or if no update mask is supplied.",
        "operationId": "classroom.courses.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/classroom.courses"
            ]
          }
        ],
        "tags": [
          "courses"
        ]
      },
      "delete": {
        "description": "Deletes a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete the requested course. * `NOT_FOUND` if no course exists with the requested ID.",
        "operationId": "classroom.courses.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/classroom.courses"
            ]
          }
        ],
        "tags": [
          "courses"
        ]
      }
    },
    "/v1beta1/courses/{courseId}/aliases": {
      "post": {
        "description": "Creates an alias to a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create the alias. * `NOT_FOUND` if the course does not exist. * `ALREADY_EXISTS` if the alias already exists.",
        "operationId": "classroom.courses.aliases.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/classroom.courses"
            ]
          }
        ],
        "tags": [
          "courses"
        ]
      },
      "get": {
        "description": "Lists the aliases of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the course. * `NOT_FOUND` if the course does not exist.",
        "operationId": "classroom.courses.aliases.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/classroom.courses",
              "https://www.googleapis.com/auth/classroom.courses.readonly"
            ]
          }
        ],
        "tags": [
          "courses"
        ]
      }
    },
    "/v1beta1/courses/{courseId}/aliases/{alias}": {
      "delete": {
        "description": "Deletes an alias of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to remove the alias. * `NOT_FOUND` if the alias does not exist.",
        "operationId": "classroom.courses.aliases.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/classroom.courses"
            ]
          }
        ],
        "tags": [
          "courses"
        ]
      }
    },
    "/v1beta1/courses/{courseId}/teachers": {
      "post": {
        "description": "Creates a teacher of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create teachers in this course. * `NOT_FOUND` if the requested course ID does not exist. * `ALREADY_EXISTS` if the user is already a teacher or student in the course.",
        "operationId": "classroom.courses.teachers.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/classroom.profile.emails",
              "https://www.googleapis.com/auth/classroom.profile.photos",
              "https://www.googleapis.com/auth/classroom.rosters"
            ]
          }
        ],
        "tags": [
          "courses"
        ]
      },
      "get": {
        "description": "Returns a list of teachers of this course that the requester is permitted to view. Fails with `NOT_FOUND` if the course does not exist.",
        "operationId": "classroom.courses.teachers.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/classroom.profile.emails",
              "https://www.googleapis.com/auth/classroom.profile.photos",
              "https://www.googleapis.com/auth/classroom.rosters",
              "https://www.googleapis.com/auth/classroom.rosters.readonly"
            ]
          }
        ],
        "tags": [
          "courses"
        ]
      }
    },
    "/v1beta1/courses/{courseId}/teachers/{userId}": {
      "get": {
        "description": "Returns a teacher of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view teachers of this course. * `NOT_FOUND` if no teacher of this course has the requested ID or if the course does not exist.",
        "operationId": "classroom.courses.teachers.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/classroom.profile.emails",
              "https://www.googleapis.com/auth/classroom.profile.photos",
              "https://www.googleapis.com/auth/classroom.rosters",
              "https://www.googleapis.com/auth/classroom.rosters.readonly"
            ]
          }
        ],
        "tags": [
          "courses"
        ]
      },
      "delete": {
        "description": "Deletes a teacher of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete teachers of this course. * `NOT_FOUND` if no teacher of this course has the requested ID or if the course does not exist. * `FAILED_PRECONDITION` if the requested ID belongs to the primary teacher of this course.",
        "operationId": "classroom.courses.teachers.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/classroom.rosters"
            ]
          }
        ],
        "tags": [
          "courses"
        ]
      }
    },
    "/v1beta1/courses/{courseId}/students": {
      "post": {
        "description": "Adds a user as a student of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create students in this course. * `NOT_FOUND` if the requested course ID does not exist. * `ALREADY_EXISTS` if the user is already a student or student in the course.",
        "operationId": "classroom.courses.students.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/classroom.profile.emails",
              "https://www.googleapis.com/auth/classroom.profile.photos",
              "https://www.googleapis.com/auth/classroom.rosters"
            ]
          }
        ],
        "tags": [
          "courses"
        ]
      },
      "get": {
        "description": "Returns a list of students of this course that the requester is permitted to view. Fails with `NOT_FOUND` if the course does not exist.",
        "operationId": "classroom.courses.students.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/classroom.profile.emails",
              "https://www.googleapis.com/auth/classroom.profile.photos",
              "https://www.googleapis.com/auth/classroom.rosters",
              "https://www.googleapis.com/auth/classroom.rosters.readonly"
            ]
          }
        ],
        "tags": [
          "courses"
        ]
      }
    },
    "/v1beta1/courses/{courseId}/students/{userId}": {
      "get": {
        "description": "Returns a student of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view students of this course. * `NOT_FOUND` if no student of this course has the requested ID or if the course does not exist.",
        "operationId": "classroom.courses.students.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/classroom.profile.emails",
              "https://www.googleapis.com/auth/classroom.profile.photos",
              "https://www.googleapis.com/auth/classroom.rosters",
              "https://www.googleapis.com/auth/classroom.rosters.readonly"
            ]
          }
        ],
        "tags": [
          "courses"
        ]
      },
      "delete": {
        "description": "Deletes a student of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete students of this course. * `NOT_FOUND` if no student of this course has the requested ID or if the course does not exist.",
        "operationId": "classroom.courses.students.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/classroom.rosters"
            ]
          }
        ],
        "tags": [
          "courses"
        ]
      }
    },
    "/v1beta1/userProfiles/{userId}": {
      "get": {
        "description": "Returns a user profile. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access this user profile. * `NOT_FOUND` if the profile does not exist.",
        "operationId": "classroom.userProfiles.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/classroom.profile.emails",
              "https://www.googleapis.com/auth/classroom.profile.photos",
              "https://www.googleapis.com/auth/classroom.rosters",
              "https://www.googleapis.com/auth/classroom.rosters.readonly"
            ]
          }
        ],
        "tags": [
          "userProfiles"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/classroom.courses": "Manage your Google Classroom classes",
        "https://www.googleapis.com/auth/classroom.courses.readonly": "View your Google Classroom classes",
        "https://www.googleapis.com/auth/classroom.profile.emails": "View the email addresses of people in your classes",
        "https://www.googleapis.com/auth/classroom.profile.photos": "View the profile photos of people in your classes",
        "https://www.googleapis.com/auth/classroom.rosters": "Manage your Google Classroom class rosters",
        "https://www.googleapis.com/auth/classroom.rosters.readonly": "View your Google Classroom class rosters"
      }
    }
  }
}