openapi: 3.0.0
servers:
  - url: https://bigtableadmin.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: Administer your Cloud Bigtable tables and instances.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Cloud Bigtable Admin API
  version: v2
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png
  x-origin:
    - format: openapi
      url: https://bigtableadmin.googleapis.com/$discovery/rest?version=v2
      version: "3.0"
  x-providerName: googleapis.com
  x-serviceName: bigtableadmin
tags:
  - name: operations
  - name: projects
paths:
  "/v2/{name}":
    delete:
      description: Permanently deletes a specified table and all of its data.
      operationId: bigtableadmin.projects.instances.tables.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
    get:
      description: Gets information about a location.
      operationId: bigtableadmin.projects.locations.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.instance
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.instance
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform.read-only
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform.read-only
      tags:
        - projects
    patch:
      description: Updates a specified table.
      operationId: bigtableadmin.projects.instances.tables.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
    put:
      description: Updates a cluster within an instance. Note that UpdateCluster does not support updating cluster_config.cluster_autoscaling_config. In order to update it, you must use PartialUpdateCluster.
      operationId: bigtableadmin.projects.instances.clusters.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.instance
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.instance
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
  "/v2/{name}/locations":
    get:
      description: Lists information about the supported locations for this service.
      operationId: bigtableadmin.projects.locations.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.instance
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.instance
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform.read-only
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform.read-only
      tags:
        - projects
  "/v2/{name}/operations":
    get:
      description: Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.
      operationId: bigtableadmin.operations.projects.operations.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.instance
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.instance
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform.read-only
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform.read-only
      tags:
        - operations
  "/v2/{name}:cancel":
    post:
      description: Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an operat[...]
      operationId: bigtableadmin.operations.cancel
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.instance
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.instance
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - operations
  "/v2/{name}:checkConsistency":
    post:
      description: Checks replication consistency based on a consistency token, that is, if replication has caught up based on the conditions specified in the token and the check request.
      operationId: bigtableadmin.projects.instances.tables.checkConsistency
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
  "/v2/{name}:dropRowRange":
    post:
      description: Permanently drop/delete a row range from a specified table. The request can specify whether to delete all rows in a table, or only those that match a particular prefix.
      operationId: bigtableadmin.projects.instances.tables.dropRowRange
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
  "/v2/{name}:generateConsistencyToken":
    post:
      description: Generates a consistency token for a Table, which can be used in CheckConsistency to check whether mutations to the table that finished before this call started have been replicated. The tokens will be available for 90 days.
      operationId: bigtableadmin.projects.instances.tables.generateConsistencyToken
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
  "/v2/{name}:modifyColumnFamilies":
    post:
      description: Performs a series of column family modifications on the specified table. Either all or none of the modifications will occur before this method returns, but data requests received prior to that point may see a table where only some modifications have taken effect.
      operationId: bigtableadmin.projects.instances.tables.modifyColumnFamilies
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
  "/v2/{name}:undelete":
    post:
      description: Restores a specified table which was accidentally deleted.
      operationId: bigtableadmin.projects.instances.tables.undelete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
  "/v2/{parent}/appProfiles":
    get:
      description: Lists information about app profiles in an instance.
      operationId: bigtableadmin.projects.instances.appProfiles.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.instance
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.instance
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
    post:
      description: Creates an app profile within an instance.
      operationId: bigtableadmin.projects.instances.appProfiles.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.instance
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.instance
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
  "/v2/{parent}/backups":
    get:
      description: Lists Cloud Bigtable backups. Returns both completed and pending backups.
      operationId: bigtableadmin.projects.instances.clusters.backups.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
    post:
      description: Starts creating a new Cloud Bigtable Backup. The returned backup long-running operation can be used to track creation of the backup. The metadata field type is CreateBackupMetadata. The response field type is Backup, if successful. Cancelling the returned operation will stop the creation and delete the backup.
      operationId: bigtableadmin.projects.instances.clusters.backups.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
  "/v2/{parent}/backups:copy":
    post:
      description: Copy a Cloud Bigtable backup to a new backup in the destination cluster located in the destination instance and project.
      operationId: bigtableadmin.projects.instances.clusters.backups.copy
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
  "/v2/{parent}/clusters":
    get:
      description: Lists information about clusters in an instance.
      operationId: bigtableadmin.projects.instances.clusters.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.instance
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.instance
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform.read-only
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform.read-only
      tags:
        - projects
    post:
      description: Creates a cluster within an instance. Note that exactly one of Cluster.serve_nodes and Cluster.cluster_config.cluster_autoscaling_config can be set. If serve_nodes is set to non-zero, then the cluster is manually scaled. If cluster_config.cluster_autoscaling_config is non-empty, then autoscaling is enabled.
      operationId: bigtableadmin.projects.instances.clusters.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.instance
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.instance
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
  "/v2/{parent}/hotTablets":
    get:
      description: Lists hot tablets in a cluster, within the time range provided. Hot tablets are ordered based on CPU usage.
      operationId: bigtableadmin.projects.instances.clusters.hotTablets.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.instance
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.instance
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
  "/v2/{parent}/instances":
    get:
      description: Lists information about instances in a project.
      operationId: bigtableadmin.projects.instances.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.instance
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.instance
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform.read-only
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform.read-only
      tags:
        - projects
    post:
      description: Create an instance within a project. Note that exactly one of Cluster.serve_nodes and Cluster.cluster_config.cluster_autoscaling_config can be set. If serve_nodes is set to non-zero, then the cluster is manually scaled. If cluster_config.cluster_autoscaling_config is non-empty, then autoscaling is enabled.
      operationId: bigtableadmin.projects.instances.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.instance
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.instance
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.cluster
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
  "/v2/{parent}/tables":
    get:
      description: Lists all tables served from a specified instance.
      operationId: bigtableadmin.projects.instances.tables.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform.read-only
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform.read-only
      tags:
        - projects
    post:
      description: Creates a new table in the specified instance. The table can be created with a full set of initial column families, specified in the request.
      operationId: bigtableadmin.projects.instances.tables.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
  "/v2/{parent}/tables:restore":
    post:
      description: Create a new table by restoring from a completed backup. The returned table long-running operation can be used to track the progress of the operation, and to cancel it. The metadata field type is RestoreTableMetadata. The response type is Table, if successful.
      operationId: bigtableadmin.projects.instances.tables.restore
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
  "/v2/{resource}:getIamPolicy":
    post:
      description: Gets the access control policy for a Table resource. Returns an empty policy if the resource exists but does not have a policy set.
      operationId: bigtableadmin.projects.instances.tables.getIamPolicy
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
  "/v2/{resource}:setIamPolicy":
    post:
      description: Sets the access control policy on a Table resource. Replaces any existing policy.
      operationId: bigtableadmin.projects.instances.tables.setIamPolicy
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
  "/v2/{resource}:testIamPermissions":
    post:
      description: Returns permissions that the caller has on the specified table resource.
      operationId: bigtableadmin.projects.instances.tables.testIamPermissions
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-bigtable.admin.table
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
        - Oauth2:
            - https://www.googleapis.com/auth/cloud-platform
          Oauth2c:
            - https://www.googleapis.com/auth/cloud-platform
      tags:
        - projects
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/bigtable.admin: Administer your Cloud Bigtable tables and clusters
            https://www.googleapis.com/auth/bigtable.admin.cluster: Administer your Cloud Bigtable clusters
            https://www.googleapis.com/auth/bigtable.admin.instance: Administer your Cloud Bigtable clusters
            https://www.googleapis.com/auth/bigtable.admin.table: Administer your Cloud Bigtable tables
            https://www.googleapis.com/auth/cloud-bigtable.admin: Administer your Cloud Bigtable tables and clusters
            https://www.googleapis.com/auth/cloud-bigtable.admin.cluster: Administer your Cloud Bigtable clusters
            https://www.googleapis.com/auth/cloud-bigtable.admin.table: Administer your Cloud Bigtable tables
            https://www.googleapis.com/auth/cloud-platform: See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account.
            https://www.googleapis.com/auth/cloud-platform.read-only: View your data across Google Cloud services and see the email address of your Google Account
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/bigtable.admin: Administer your Cloud Bigtable tables and clusters
            https://www.googleapis.com/auth/bigtable.admin.cluster: Administer your Cloud Bigtable clusters
            https://www.googleapis.com/auth/bigtable.admin.instance: Administer your Cloud Bigtable clusters
            https://www.googleapis.com/auth/bigtable.admin.table: Administer your Cloud Bigtable tables
            https://www.googleapis.com/auth/cloud-bigtable.admin: Administer your Cloud Bigtable tables and clusters
            https://www.googleapis.com/auth/cloud-bigtable.admin.cluster: Administer your Cloud Bigtable clusters
            https://www.googleapis.com/auth/cloud-bigtable.admin.table: Administer your Cloud Bigtable tables
            https://www.googleapis.com/auth/cloud-platform: See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account.
            https://www.googleapis.com/auth/cloud-platform.read-only: View your data across Google Cloud services and see the email address of your Google Account
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
