openapi: 3.0.0
servers:
  - url: https://marketingplatformadmin.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: marketingplatformadmin.googleapis.com API.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Google Marketing Platform Admin API
  version: v1alpha
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://upload.wikimedia.org/wikipedia/commons/e/e1/YouTube_play_buttom_icon_%282013-2017%29.svg
  x-origin:
    - format: google
      url: https://marketingplatformadmin.googleapis.com/$discovery/rest?version=v1alpha
      version: v1
  x-providerName: googleapis.com
  x-serviceName: marketingplatformadmin
tags:
  - name: organizations
paths:
  /v1alpha/{analyticsAccountLink}:setPropertyServiceLevel:
    post:
      description: Updates the service level for an Analytics property.
      operationId: marketingplatformadmin.organizations.analyticsAccountLinks.setPropertyServiceLevel
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/marketingplatformadmin.analytics.update
          Oauth2c:
            - https://www.googleapis.com/auth/marketingplatformadmin.analytics.update
      tags:
        - organizations
  /v1alpha/{name}:
    delete:
      description: Deletes the AnalyticsAccountLink, which detaches the Analytics account from the Google Marketing Platform organization. User needs to be an org user, and admin on the Analytics account in order to delete the link.
      operationId: marketingplatformadmin.organizations.analyticsAccountLinks.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/marketingplatformadmin.analytics.update
          Oauth2c:
            - https://www.googleapis.com/auth/marketingplatformadmin.analytics.update
      tags:
        - organizations
  /v1alpha/{parent}/analyticsAccountLinks:
    get:
      description: Lists the Google Analytics accounts link to the specified Google Marketing Platform organization.
      operationId: marketingplatformadmin.organizations.analyticsAccountLinks.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/marketingplatformadmin.analytics.read
          Oauth2c:
            - https://www.googleapis.com/auth/marketingplatformadmin.analytics.read
        - Oauth2:
            - https://www.googleapis.com/auth/marketingplatformadmin.analytics.update
          Oauth2c:
            - https://www.googleapis.com/auth/marketingplatformadmin.analytics.update
      tags:
        - organizations
    post:
      description: Creates the link between the Analytics account and the Google Marketing Platform organization. User needs to be an org user, and admin on the Analytics account to create the link. If the account is already linked to an organization, user needs to unlink the account from the current organization, then try link again.
      operationId: marketingplatformadmin.organizations.analyticsAccountLinks.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/marketingplatformadmin.analytics.update
          Oauth2c:
            - https://www.googleapis.com/auth/marketingplatformadmin.analytics.update
      tags:
        - organizations
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/marketingplatformadmin.analytics.read: View your Google Analytics product account data in GMP home
            https://www.googleapis.com/auth/marketingplatformadmin.analytics.update: Manage your Google Analytics product account data in GMP home
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/marketingplatformadmin.analytics.read: View your Google Analytics product account data in GMP home
            https://www.googleapis.com/auth/marketingplatformadmin.analytics.update: Manage your Google Analytics product account data in GMP home
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
