# coding: utf-8

"""
    Vertex AI API

    Train high-quality custom machine learning models with minimal machine learning expertise and effort.

    The version of the OpenAPI document: v1beta1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.google_cloud_aiplatform_v1beta1_fetch_feature_values_request import GoogleCloudAiplatformV1beta1FetchFeatureValuesRequest

class TestGoogleCloudAiplatformV1beta1FetchFeatureValuesRequest(unittest.TestCase):
    """GoogleCloudAiplatformV1beta1FetchFeatureValuesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GoogleCloudAiplatformV1beta1FetchFeatureValuesRequest:
        """Test GoogleCloudAiplatformV1beta1FetchFeatureValuesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GoogleCloudAiplatformV1beta1FetchFeatureValuesRequest`
        """
        model = GoogleCloudAiplatformV1beta1FetchFeatureValuesRequest()
        if include_optional:
            return GoogleCloudAiplatformV1beta1FetchFeatureValuesRequest(
                data_format = 'FEATURE_VIEW_DATA_FORMAT_UNSPECIFIED',
                data_key = openapi_client.models.google_cloud_aiplatform_v1beta1_feature_view_data_key.GoogleCloudAiplatformV1beta1FeatureViewDataKey(
                    composite_key = openapi_client.models.google_cloud_aiplatform_v1beta1_feature_view_data_key_composite_key.GoogleCloudAiplatformV1beta1FeatureViewDataKeyCompositeKey(
                        parts = [
                            ''
                            ], ), 
                    key = '', ),
                format = 'FORMAT_UNSPECIFIED',
                id = ''
            )
        else:
            return GoogleCloudAiplatformV1beta1FetchFeatureValuesRequest(
        )
        """

    def testGoogleCloudAiplatformV1beta1FetchFeatureValuesRequest(self):
        """Test GoogleCloudAiplatformV1beta1FetchFeatureValuesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
