package shared

type PermissionsBoundaryAttachmentTypeEnum string

const (
	PermissionsBoundaryAttachmentTypeEnumPermissionsBoundaryPolicy PermissionsBoundaryAttachmentTypeEnum = "PermissionsBoundaryPolicy"
)
