# coding: utf-8

"""
    DataLakeAnalyticsAccountManagementClient

    Creates an Azure Data Lake Analytics account management client.

    The version of the OpenAPI document: 2016-11-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.capability_information import CapabilityInformation

class TestCapabilityInformation(unittest.TestCase):
    """CapabilityInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CapabilityInformation:
        """Test CapabilityInformation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CapabilityInformation`
        """
        model = CapabilityInformation()
        if include_optional:
            return CapabilityInformation(
                account_count = 56,
                max_account_count = 56,
                migration_state = True,
                state = 'Registered',
                subscription_id = ''
            )
        else:
            return CapabilityInformation(
        )
        """

    def testCapabilityInformation(self):
        """Test CapabilityInformation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
