from dataclasses import dataclass, field
from typing import Enum

class FundingEventTypeEnum(str, Enum):
    PAYOR_FUNDING_DETECTED = "PAYOR_FUNDING_DETECTED"
    PAYOR_FUNDING_REQUESTED = "PAYOR_FUNDING_REQUESTED"
    PAYOR_FUNDING_RETURN_RECEIVED = "PAYOR_FUNDING_RETURN_RECEIVED"
    FUNDING_RETURN_DETECTED = "FUNDING_RETURN_DETECTED"
    PAYOR_FUNDING_REQUEST_SUBMITTED = "PAYOR_FUNDING_REQUEST_SUBMITTED"
    PAYOR_FUNDING_ENTRY_DETAIL_RECEIVED = "PAYOR_FUNDING_ENTRY_DETAIL_RECEIVED"
    FUNDING_DEALLOCATED = "FUNDING_DEALLOCATED"

