# coding: utf-8

"""
    Azure Machine Learning Model Management Service

    These APIs allow end users to manage Azure Machine Learning Models, Images, Profiles, and Services.

    The version of the OpenAPI document: 2019-09-30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.aks_replica_status import AKSReplicaStatus

class TestAKSReplicaStatus(unittest.TestCase):
    """AKSReplicaStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AKSReplicaStatus:
        """Test AKSReplicaStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AKSReplicaStatus`
        """
        model = AKSReplicaStatus()
        if include_optional:
            return AKSReplicaStatus(
                available_replicas = 1,
                desired_replicas = 2,
                error = openapi_client.models.model_error_response.ModelErrorResponse(
                    code = '', 
                    details = [
                        openapi_client.models.error_details.ErrorDetails(
                            code = '', 
                            message = '', 
                            target = '', )
                        ], 
                    message = '', 
                    status_code = 56, ),
                updated_replicas = 1
            )
        else:
            return AKSReplicaStatus(
        )
        """

    def testAKSReplicaStatus(self):
        """Test AKSReplicaStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
