{
  "swagger": "2.0",
  "info": {
    "title": "Drive API",
    "description": "The API to interact with Drive.",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v2"
  },
  "host": "www.googleapis.com",
  "basePath": "/drive/v2",
  "schemes": [
    "https"
  ],
  "paths": {
    "/about": {
      "get": {
        "description": "Gets the information about the current user along with Drive API settings",
        "operationId": "drive.about.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.metadata.readonly",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "about"
        ]
      }
    },
    "/apps/{appId}": {
      "get": {
        "description": "Gets a specific app.",
        "operationId": "drive.apps.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.apps.readonly",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.metadata.readonly",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "apps"
        ]
      }
    },
    "/apps": {
      "get": {
        "description": "Lists a user's installed apps.",
        "operationId": "drive.apps.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.apps.readonly"
            ]
          }
        ],
        "tags": [
          "apps"
        ]
      }
    },
    "/changes/{changeId}": {
      "get": {
        "description": "Gets a specific change.",
        "operationId": "drive.changes.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.apps.readonly",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.metadata.readonly",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "changes"
        ]
      }
    },
    "/changes": {
      "get": {
        "description": "Lists the changes for a user.",
        "operationId": "drive.changes.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.apps.readonly",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.metadata.readonly",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "changes"
        ]
      }
    },
    "/changes/watch": {
      "post": {
        "description": "Subscribe to changes for a user.",
        "operationId": "drive.changes.watch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.apps.readonly",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.metadata.readonly",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "changes"
        ]
      }
    },
    "/channels/stop": {
      "post": {
        "description": "Stop watching resources through this channel",
        "operationId": "drive.channels.stop",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.apps.readonly",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.metadata.readonly",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "channels"
        ]
      }
    },
    "/files/{folderId}/children/{childId}": {
      "delete": {
        "description": "Removes a child from a folder.",
        "operationId": "drive.children.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "children"
        ]
      },
      "get": {
        "description": "Gets a specific child reference.",
        "operationId": "drive.children.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.metadata.readonly",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "children"
        ]
      }
    },
    "/files/{folderId}/children": {
      "post": {
        "description": "Inserts a file into a folder.",
        "operationId": "drive.children.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "children"
        ]
      },
      "get": {
        "description": "Lists a folder's children.",
        "operationId": "drive.children.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.metadata.readonly",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "children"
        ]
      }
    },
    "/files/{fileId}/comments/{commentId}": {
      "delete": {
        "description": "Deletes a comment.",
        "operationId": "drive.comments.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "comments"
        ]
      },
      "get": {
        "description": "Gets a comment by ID.",
        "operationId": "drive.comments.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "comments"
        ]
      },
      "patch": {
        "description": "Updates an existing comment. This method supports patch semantics.",
        "operationId": "drive.comments.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "comments"
        ]
      },
      "put": {
        "description": "Updates an existing comment.",
        "operationId": "drive.comments.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "comments"
        ]
      }
    },
    "/files/{fileId}/comments": {
      "post": {
        "description": "Creates a new comment on the given file.",
        "operationId": "drive.comments.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "comments"
        ]
      },
      "get": {
        "description": "Lists a file's comments.",
        "operationId": "drive.comments.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "comments"
        ]
      }
    },
    "/files/{fileId}/copy": {
      "post": {
        "description": "Creates a copy of the specified file.",
        "operationId": "drive.files.copy",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.apps.readonly",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "files"
        ]
      }
    },
    "/files/{fileId}": {
      "delete": {
        "description": "Permanently deletes a file by ID. Skips the trash.",
        "operationId": "drive.files.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "files"
        ]
      },
      "get": {
        "description": "Gets a file's metadata by ID.",
        "operationId": "drive.files.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.apps.readonly",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.metadata.readonly",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "files"
        ]
      },
      "patch": {
        "description": "Updates file metadata and/or content. This method supports patch semantics.",
        "operationId": "drive.files.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.apps.readonly",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.scripts"
            ]
          }
        ],
        "tags": [
          "files"
        ]
      },
      "put": {
        "description": "Updates file metadata and/or content.",
        "operationId": "drive.files.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.apps.readonly",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.scripts"
            ]
          }
        ],
        "tags": [
          "files"
        ]
      }
    },
    "/files/trash": {
      "delete": {
        "description": "Permanently deletes all of the user's trashed files.",
        "operationId": "drive.files.emptyTrash",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ]
          }
        ],
        "tags": [
          "files"
        ]
      }
    },
    "/files": {
      "post": {
        "description": "Insert a new file.",
        "operationId": "drive.files.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.apps.readonly",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "files"
        ]
      },
      "get": {
        "description": "Lists the user's files.",
        "operationId": "drive.files.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.apps.readonly",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.metadata.readonly",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "files"
        ]
      }
    },
    "/files/{fileId}/touch": {
      "post": {
        "description": "Set the file's updated time to the current server time.",
        "operationId": "drive.files.touch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.apps.readonly",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "files"
        ]
      }
    },
    "/files/{fileId}/trash": {
      "post": {
        "description": "Moves a file to the trash.",
        "operationId": "drive.files.trash",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.apps.readonly",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "files"
        ]
      }
    },
    "/files/{fileId}/untrash": {
      "post": {
        "description": "Restores a file from the trash.",
        "operationId": "drive.files.untrash",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.apps.readonly",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "files"
        ]
      }
    },
    "/files/{fileId}/watch": {
      "post": {
        "description": "Subscribe to changes on a file",
        "operationId": "drive.files.watch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.apps.readonly",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.metadata.readonly",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "files"
        ]
      }
    },
    "/files/{fileId}/parents/{parentId}": {
      "delete": {
        "description": "Removes a parent from a file.",
        "operationId": "drive.parents.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "parents"
        ]
      },
      "get": {
        "description": "Gets a specific parent reference.",
        "operationId": "drive.parents.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.metadata.readonly",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "parents"
        ]
      }
    },
    "/files/{fileId}/parents": {
      "post": {
        "description": "Adds a parent folder for a file.",
        "operationId": "drive.parents.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "parents"
        ]
      },
      "get": {
        "description": "Lists a file's parents.",
        "operationId": "drive.parents.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.metadata.readonly",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "parents"
        ]
      }
    },
    "/files/{fileId}/permissions/{permissionId}": {
      "delete": {
        "description": "Deletes a permission from a file.",
        "operationId": "drive.permissions.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "permissions"
        ]
      },
      "get": {
        "description": "Gets a permission by ID.",
        "operationId": "drive.permissions.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.metadata.readonly",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "permissions"
        ]
      },
      "patch": {
        "description": "Updates a permission. This method supports patch semantics.",
        "operationId": "drive.permissions.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "permissions"
        ]
      },
      "put": {
        "description": "Updates a permission.",
        "operationId": "drive.permissions.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "permissions"
        ]
      }
    },
    "/permissionIds/{email}": {
      "get": {
        "description": "Returns the permission ID for an email address.",
        "operationId": "drive.permissions.getIdForEmail",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.apps.readonly",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.metadata.readonly",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "permissions"
        ]
      }
    },
    "/files/{fileId}/permissions": {
      "post": {
        "description": "Inserts a permission for a file.",
        "operationId": "drive.permissions.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "permissions"
        ]
      },
      "get": {
        "description": "Lists a file's permissions.",
        "operationId": "drive.permissions.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.metadata.readonly",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "permissions"
        ]
      }
    },
    "/files/{fileId}/properties/{propertyKey}": {
      "delete": {
        "description": "Deletes a property.",
        "operationId": "drive.properties.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "properties"
        ]
      },
      "get": {
        "description": "Gets a property by its key.",
        "operationId": "drive.properties.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.metadata.readonly",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "properties"
        ]
      },
      "patch": {
        "description": "Updates a property. This method supports patch semantics.",
        "operationId": "drive.properties.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "properties"
        ]
      },
      "put": {
        "description": "Updates a property.",
        "operationId": "drive.properties.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "properties"
        ]
      }
    },
    "/files/{fileId}/properties": {
      "post": {
        "description": "Adds a property to a file.",
        "operationId": "drive.properties.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "properties"
        ]
      },
      "get": {
        "description": "Lists a file's properties.",
        "operationId": "drive.properties.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.metadata.readonly",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "properties"
        ]
      }
    },
    "/files/{fileId}/realtime": {
      "get": {
        "description": "Exports the contents of the Realtime API data model associated with this file as JSON.",
        "operationId": "drive.realtime.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "realtime"
        ]
      },
      "put": {
        "description": "Overwrites the Realtime API data model associated with this file with the provided JSON data model.",
        "operationId": "drive.realtime.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "realtime"
        ]
      }
    },
    "/files/{fileId}/comments/{commentId}/replies/{replyId}": {
      "delete": {
        "description": "Deletes a reply.",
        "operationId": "drive.replies.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "replies"
        ]
      },
      "get": {
        "description": "Gets a reply.",
        "operationId": "drive.replies.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "replies"
        ]
      },
      "patch": {
        "description": "Updates an existing reply. This method supports patch semantics.",
        "operationId": "drive.replies.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "replies"
        ]
      },
      "put": {
        "description": "Updates an existing reply.",
        "operationId": "drive.replies.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "replies"
        ]
      }
    },
    "/files/{fileId}/comments/{commentId}/replies": {
      "post": {
        "description": "Creates a new reply to the given comment.",
        "operationId": "drive.replies.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "replies"
        ]
      },
      "get": {
        "description": "Lists all of the replies to a comment.",
        "operationId": "drive.replies.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "replies"
        ]
      }
    },
    "/files/{fileId}/revisions/{revisionId}": {
      "delete": {
        "description": "Removes a revision.",
        "operationId": "drive.revisions.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "revisions"
        ]
      },
      "get": {
        "description": "Gets a specific revision.",
        "operationId": "drive.revisions.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.metadata.readonly",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "revisions"
        ]
      },
      "patch": {
        "description": "Updates a revision. This method supports patch semantics.",
        "operationId": "drive.revisions.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "revisions"
        ]
      },
      "put": {
        "description": "Updates a revision.",
        "operationId": "drive.revisions.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.file"
            ]
          }
        ],
        "tags": [
          "revisions"
        ]
      }
    },
    "/files/{fileId}/revisions": {
      "get": {
        "description": "Lists a file's revisions.",
        "operationId": "drive.revisions.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive",
              "https://www.googleapis.com/auth/drive.appdata",
              "https://www.googleapis.com/auth/drive.file",
              "https://www.googleapis.com/auth/drive.metadata.readonly",
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          }
        ],
        "tags": [
          "revisions"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/drive": "View and manage the files and documents in your Google Drive",
        "https://www.googleapis.com/auth/drive.appdata": "View and manage its own configuration data in your Google Drive",
        "https://www.googleapis.com/auth/drive.apps.readonly": "View your Google Drive apps",
        "https://www.googleapis.com/auth/drive.file": "View and manage Google Drive files that you have opened or created with this app",
        "https://www.googleapis.com/auth/drive.metadata.readonly": "View metadata for files and documents in your Google Drive",
        "https://www.googleapis.com/auth/drive.readonly": "View the files and documents in your Google Drive",
        "https://www.googleapis.com/auth/drive.scripts": "Modify your Google Apps Script scripts' behavior"
      }
    }
  }
}