# coding: utf-8

"""
    QnAMaker Client

    An API for QnAMaker Service

    The version of the OpenAPI document: 4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.error_response import ErrorResponse
from openapi_client.models.operation_state import OperationState
from typing import Optional, Set
from typing_extensions import Self

class Operation(BaseModel):
    """
    Record to track long running operation.
    """ # noqa: E501
    created_timestamp: Optional[StrictStr] = Field(default=None, description="Timestamp when the operation was created.", alias="createdTimestamp")
    error_response: Optional[ErrorResponse] = Field(default=None, alias="errorResponse")
    last_action_timestamp: Optional[StrictStr] = Field(default=None, description="Timestamp when the current state was entered.", alias="lastActionTimestamp")
    operation_id: Optional[StrictStr] = Field(default=None, description="Operation Id.", alias="operationId")
    operation_state: Optional[OperationState] = Field(default=None, alias="operationState")
    resource_location: Optional[StrictStr] = Field(default=None, description="Relative URI to the target resource location for completed resources.", alias="resourceLocation")
    user_id: Optional[StrictStr] = Field(default=None, description="User Id", alias="userId")
    __properties: ClassVar[List[str]] = ["createdTimestamp", "errorResponse", "lastActionTimestamp", "operationId", "operationState", "resourceLocation", "userId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Operation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of error_response
        if self.error_response:
            _dict['errorResponse'] = self.error_response.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Operation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createdTimestamp": obj.get("createdTimestamp"),
            "errorResponse": ErrorResponse.from_dict(obj["errorResponse"]) if obj.get("errorResponse") is not None else None,
            "lastActionTimestamp": obj.get("lastActionTimestamp"),
            "operationId": obj.get("operationId"),
            "operationState": obj.get("operationState"),
            "resourceLocation": obj.get("resourceLocation"),
            "userId": obj.get("userId")
        })
        return _obj


