# coding: utf-8

"""
    The SMS Works API

    The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.

    The version of the OpenAPI document: 1.8.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.messages_api import MessagesApi


class TestMessagesApi(unittest.TestCase):
    """MessagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessagesApi()

    def tearDown(self) -> None:
        pass

    def test_message_schedule_post(self) -> None:
        """Test case for message_schedule_post

        """
        pass

    def test_message_send_post(self) -> None:
        """Test case for message_send_post

        """
        pass

    def test_messages_failed_post(self) -> None:
        """Test case for messages_failed_post

        """
        pass

    def test_messages_inbox_post(self) -> None:
        """Test case for messages_inbox_post

        """
        pass

    def test_messages_messageid_delete(self) -> None:
        """Test case for messages_messageid_delete

        """
        pass

    def test_messages_messageid_get(self) -> None:
        """Test case for messages_messageid_get

        """
        pass

    def test_messages_post(self) -> None:
        """Test case for messages_post

        """
        pass

    def test_messages_schedule_get(self) -> None:
        """Test case for messages_schedule_get

        """
        pass

    def test_messages_schedule_messageid_delete(self) -> None:
        """Test case for messages_schedule_messageid_delete

        """
        pass

    def test_send_flash_message(self) -> None:
        """Test case for send_flash_message

        """
        pass


if __name__ == '__main__':
    unittest.main()
