{
  "swagger": "2.0",
  "info": {
    "title": "Google Maps Coordinate API",
    "x-serviceName": "coordinate",
    "description": "Lets you view and manage jobs in a Coordinate team.",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "v1",
    "x-origin": {
      "format": "google",
      "version": "v1",
      "url": "https://www.googleapis.com/discovery/v1/apis/coordinate/v1/rest"
    }
  },
  "host": "www.googleapis.com",
  "basePath": "/coordinate/v1",
  "schemes": [
    "https"
  ],
  "paths": {
    "/teams/{teamId}/custom_fields": {
      "get": {
        "description": "Retrieves a list of custom field definitions for a team.",
        "operationId": "coordinate.customFieldDef.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/coordinate",
              "https://www.googleapis.com/auth/coordinate.readonly"
            ]
          }
        ],
        "tags": [
          "customFieldDef"
        ]
      }
    },
    "/teams/{teamId}/jobs/{jobId}": {
      "get": {
        "description": "Retrieves a job, including all the changes made to the job.",
        "operationId": "coordinate.jobs.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/coordinate",
              "https://www.googleapis.com/auth/coordinate.readonly"
            ]
          }
        ],
        "tags": [
          "jobs"
        ]
      },
      "patch": {
        "description": "Updates a job. Fields that are set in the job state will be updated. This method supports patch semantics.",
        "operationId": "coordinate.jobs.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/coordinate"
            ]
          }
        ],
        "tags": [
          "jobs"
        ]
      },
      "put": {
        "description": "Updates a job. Fields that are set in the job state will be updated.",
        "operationId": "coordinate.jobs.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/coordinate"
            ]
          }
        ],
        "tags": [
          "jobs"
        ]
      }
    },
    "/teams/{teamId}/jobs": {
      "post": {
        "description": "Inserts a new job. Only the state field of the job should be set.",
        "operationId": "coordinate.jobs.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/coordinate"
            ]
          }
        ],
        "tags": [
          "jobs"
        ]
      },
      "get": {
        "description": "Retrieves jobs created or modified since the given timestamp.",
        "operationId": "coordinate.jobs.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/coordinate",
              "https://www.googleapis.com/auth/coordinate.readonly"
            ]
          }
        ],
        "tags": [
          "jobs"
        ]
      }
    },
    "/teams/{teamId}/workers/{workerEmail}/locations": {
      "get": {
        "description": "Retrieves a list of locations for a worker.",
        "operationId": "coordinate.location.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/coordinate",
              "https://www.googleapis.com/auth/coordinate.readonly"
            ]
          }
        ],
        "tags": [
          "location"
        ]
      }
    },
    "/teams/{teamId}/jobs/{jobId}/schedule": {
      "get": {
        "description": "Retrieves the schedule for a job.",
        "operationId": "coordinate.schedule.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/coordinate",
              "https://www.googleapis.com/auth/coordinate.readonly"
            ]
          }
        ],
        "tags": [
          "schedule"
        ]
      },
      "patch": {
        "description": "Replaces the schedule of a job with the provided schedule. This method supports patch semantics.",
        "operationId": "coordinate.schedule.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/coordinate"
            ]
          }
        ],
        "tags": [
          "schedule"
        ]
      },
      "put": {
        "description": "Replaces the schedule of a job with the provided schedule.",
        "operationId": "coordinate.schedule.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/coordinate"
            ]
          }
        ],
        "tags": [
          "schedule"
        ]
      }
    },
    "/teams": {
      "get": {
        "description": "Retrieves a list of teams for a user.",
        "operationId": "coordinate.team.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/coordinate",
              "https://www.googleapis.com/auth/coordinate.readonly"
            ]
          }
        ],
        "tags": [
          "team"
        ]
      }
    },
    "/teams/{teamId}/workers": {
      "get": {
        "description": "Retrieves a list of workers in a team.",
        "operationId": "coordinate.worker.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/coordinate",
              "https://www.googleapis.com/auth/coordinate.readonly"
            ]
          }
        ],
        "tags": [
          "worker"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/coordinate": "View and manage your Google Maps Coordinate jobs",
        "https://www.googleapis.com/auth/coordinate.readonly": "View your Google Coordinate jobs"
      }
    }
  }
}