from .createsuitedefinition import *
from .deletesuitedefinition import *
from .getsuitedefinition import *
from .getsuiterun import *
from .getsuiterunreport import *
from .listsuitedefinitions import *
from .listsuiteruns import *
from .listtagsforresource import *
from .startsuiterun import *
from .stopsuiterun import *
from .tagresource import *
from .untagresource import *
from .updatesuitedefinition import *
