# coding: utf-8

"""
    Azure Action Groups

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2018-03-01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.logic_app_receiver import LogicAppReceiver

class TestLogicAppReceiver(unittest.TestCase):
    """LogicAppReceiver unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LogicAppReceiver:
        """Test LogicAppReceiver
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LogicAppReceiver`
        """
        model = LogicAppReceiver()
        if include_optional:
            return LogicAppReceiver(
                callback_url = '',
                name = '',
                resource_id = ''
            )
        else:
            return LogicAppReceiver(
                callback_url = '',
                name = '',
                resource_id = '',
        )
        """

    def testLogicAppReceiver(self):
        """Test LogicAppReceiver"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
