from dataclasses import dataclass, field
from typing import Enum

class StreamingSessionStatusCodeEnum(str, Enum):
    STREAMING_SESSION_READY = "STREAMING_SESSION_READY"
    STREAMING_SESSION_DELETED = "STREAMING_SESSION_DELETED"
    STREAMING_SESSION_CREATE_IN_PROGRESS = "STREAMING_SESSION_CREATE_IN_PROGRESS"
    STREAMING_SESSION_DELETE_IN_PROGRESS = "STREAMING_SESSION_DELETE_IN_PROGRESS"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    INSUFFICIENT_CAPACITY = "INSUFFICIENT_CAPACITY"
    ACTIVE_DIRECTORY_DOMAIN_JOIN_ERROR = "ACTIVE_DIRECTORY_DOMAIN_JOIN_ERROR"
    NETWORK_CONNECTION_ERROR = "NETWORK_CONNECTION_ERROR"
    INITIALIZATION_SCRIPT_ERROR = "INITIALIZATION_SCRIPT_ERROR"
    DECRYPT_STREAMING_IMAGE_ERROR = "DECRYPT_STREAMING_IMAGE_ERROR"
    NETWORK_INTERFACE_ERROR = "NETWORK_INTERFACE_ERROR"

