from .availableproducts import *
from .bookingavailability import *
from .bookingavailabilitydates import *
from .bookingavailabilitytourgrades import *
from .bookingavailabilitytourgradespricingmatrix import *
from .bookingbook import *
from .bookingcalculateprice import *
from .bookinghotels import *
from .bookingmybookings import *
from .bookingpastbooking import *
from .bookingpricingmatrix import *
from .bookingstatus import *
from .bookingstatusitems import *
from .bookingvoucher import *
from .cancelbooking import *
from .cancelbookingquote import *
from .cancellationreasons import *
from .healthcheck import *
from .merchantcancellation import *
from .product import *
from .productphotos import *
from .productreviews import *
from .searchfreetext import *
from .searchproducts import *
from .searchproductscodes import *
from .taxonomyattractions import *
from .taxonomycategories import *
from .taxonomydestinations import *
