openapi: 3.0.0
servers:
  - url: https://blogger.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: The Blogger API provides access to posts, comments and pages of a Blogger blog.
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Blogger API
  version: v3
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png
  x-origin:
    - format: google
      url: https://blogger.googleapis.com/$discovery/rest?version=v3
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: blogger
tags:
  - name: blogs
  - name: blogUserInfos
  - name: comments
  - name: pages
  - name: pageViews
  - name: posts
  - name: postUserInfos
  - name: users
paths:
  /v3/blogs/byurl:
    get:
      description: Gets a blog by url.
      operationId: blogger.blogs.getByUrl
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - blogs
  "/v3/blogs/{blogId}":
    get:
      description: Gets a blog by id.
      operationId: blogger.blogs.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - blogs
  "/v3/blogs/{blogId}/comments":
    get:
      description: Lists comments by blog.
      operationId: blogger.comments.listByBlog
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - comments
  "/v3/blogs/{blogId}/pages":
    get:
      description: Lists pages.
      operationId: blogger.pages.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - pages
    post:
      description: Inserts a page.
      operationId: blogger.pages.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - pages
  "/v3/blogs/{blogId}/pages/{pageId}":
    delete:
      description: Deletes a page by blog id and page id.
      operationId: blogger.pages.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - pages
    get:
      description: Gets a page by blog id and page id.
      operationId: blogger.pages.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - pages
    patch:
      description: Patches a page.
      operationId: blogger.pages.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - pages
    put:
      description: Updates a page by blog id and page id.
      operationId: blogger.pages.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - pages
  "/v3/blogs/{blogId}/pages/{pageId}/publish":
    post:
      description: Publishes a page.
      operationId: blogger.pages.publish
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - pages
  "/v3/blogs/{blogId}/pages/{pageId}/revert":
    post:
      description: Reverts a published or scheduled page to draft state.
      operationId: blogger.pages.revert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - pages
  "/v3/blogs/{blogId}/pageviews":
    get:
      description: Gets page views by blog id.
      operationId: blogger.pageViews.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - pageViews
  "/v3/blogs/{blogId}/posts":
    get:
      description: Lists posts.
      operationId: blogger.posts.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - posts
    post:
      description: Inserts a post.
      operationId: blogger.posts.insert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - posts
  "/v3/blogs/{blogId}/posts/bypath":
    get:
      description: Gets a post by path.
      operationId: blogger.posts.getByPath
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - posts
  "/v3/blogs/{blogId}/posts/search":
    get:
      description: Searches for posts matching given query terms in the specified blog.
      operationId: blogger.posts.search
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - posts
  "/v3/blogs/{blogId}/posts/{postId}":
    delete:
      description: Deletes a post by blog id and post id.
      operationId: blogger.posts.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - posts
    get:
      description: Gets a post by blog id and post id
      operationId: blogger.posts.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - posts
    patch:
      description: Patches a post.
      operationId: blogger.posts.patch
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - posts
    put:
      description: Updates a post by blog id and post id.
      operationId: blogger.posts.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - posts
  "/v3/blogs/{blogId}/posts/{postId}/comments":
    get:
      description: Lists comments.
      operationId: blogger.comments.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - comments
  "/v3/blogs/{blogId}/posts/{postId}/comments/{commentId}":
    delete:
      description: Deletes a comment by blog id, post id and comment id.
      operationId: blogger.comments.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - comments
    get:
      description: Gets a comment by id.
      operationId: blogger.comments.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - comments
  "/v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/approve":
    post:
      description: Marks a comment as not spam by blog id, post id and comment id.
      operationId: blogger.comments.approve
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - comments
  "/v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/removecontent":
    post:
      description: Removes the content of a comment by blog id, post id and comment id.
      operationId: blogger.comments.removeContent
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - comments
  "/v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/spam":
    post:
      description: Marks a comment as spam by blog id, post id and comment id.
      operationId: blogger.comments.markAsSpam
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - comments
  "/v3/blogs/{blogId}/posts/{postId}/publish":
    post:
      description: Publishes a post.
      operationId: blogger.posts.publish
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - posts
  "/v3/blogs/{blogId}/posts/{postId}/revert":
    post:
      description: Reverts a published or scheduled post to draft state.
      operationId: blogger.posts.revert
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - posts
  "/v3/users/{userId}":
    get:
      description: Gets one user by user_id.
      operationId: blogger.users.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - users
  "/v3/users/{userId}/blogs":
    get:
      description: Lists blogs by user.
      operationId: blogger.blogs.listByUser
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - blogs
  "/v3/users/{userId}/blogs/{blogId}":
    get:
      description: Gets one blog and user info pair by blog id and user id.
      operationId: blogger.blogUserInfos.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - blogUserInfos
  "/v3/users/{userId}/blogs/{blogId}/posts":
    get:
      description: Lists post and user info pairs.
      operationId: blogger.postUserInfos.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - postUserInfos
  "/v3/users/{userId}/blogs/{blogId}/posts/{postId}":
    get:
      description: Gets one post and user info pair, by post_id and user_id.
      operationId: blogger.postUserInfos.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - postUserInfos
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/blogger: Manage your Blogger account
            https://www.googleapis.com/auth/blogger.readonly: View your Blogger account
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/blogger: Manage your Blogger account
            https://www.googleapis.com/auth/blogger.readonly: View your Blogger account
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
