from dataclasses import dataclass, field
from typing import Enum,Optional
from sdk.models import shared


@dataclass
class SearchQueryParams:
    api_key: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'api_key', 'style': 'form', 'explode': True }})
    append_api_key: Optional[bool] = field(default=None, metadata={'query_param': { 'field_name': 'append_api_key', 'style': 'form', 'explode': True }})
    base_exterior_color: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'base_exterior_color', 'style': 'form', 'explode': True }})
    base_interior_color: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'base_interior_color', 'style': 'form', 'explode': True }})
    body_subtype: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'body_subtype', 'style': 'form', 'explode': True }})
    body_type: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'body_type', 'style': 'form', 'explode': True }})
    car_type: Optional[shared.CarCarTypeEnum] = field(default=None, metadata={'query_param': { 'field_name': 'car_type', 'style': 'form', 'explode': True }})
    carfax_1_owner: Optional[shared.Carfax1OwnerEnum] = field(default=None, metadata={'query_param': { 'field_name': 'carfax_1_owner', 'style': 'form', 'explode': True }})
    carfax_clean_title: Optional[shared.CarfaxCleanTitleEnum] = field(default=None, metadata={'query_param': { 'field_name': 'carfax_clean_title', 'style': 'form', 'explode': True }})
    city: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'city', 'style': 'form', 'explode': True }})
    city_mpg_range: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'city_mpg_range', 'style': 'form', 'explode': True }})
    country: Optional[shared.CarCountryEnum] = field(default=None, metadata={'query_param': { 'field_name': 'country', 'style': 'form', 'explode': True }})
    cylinders: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'cylinders', 'style': 'form', 'explode': True }})
    dealer_type: Optional[shared.DealerTypeEnum] = field(default=None, metadata={'query_param': { 'field_name': 'dealer_type', 'style': 'form', 'explode': True }})
    dedup: Optional[bool] = field(default=None, metadata={'query_param': { 'field_name': 'dedup', 'style': 'form', 'explode': True }})
    dom_180_range: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'dom_180_range', 'style': 'form', 'explode': True }})
    dom_active_range: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'dom_active_range', 'style': 'form', 'explode': True }})
    dom_range: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'dom_range', 'style': 'form', 'explode': True }})
    doors: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'doors', 'style': 'form', 'explode': True }})
    drivetrain: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'drivetrain', 'style': 'form', 'explode': True }})
    engine: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'engine', 'style': 'form', 'explode': True }})
    engine_aspiration: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'engine_aspiration', 'style': 'form', 'explode': True }})
    engine_block: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'engine_block', 'style': 'form', 'explode': True }})
    engine_size: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'engine_size', 'style': 'form', 'explode': True }})
    exclude_certified: Optional[bool] = field(default=None, metadata={'query_param': { 'field_name': 'exclude_certified', 'style': 'form', 'explode': True }})
    exterior_color: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'exterior_color', 'style': 'form', 'explode': True }})
    facet_sort: Optional[shared.FacetSortEnum] = field(default=None, metadata={'query_param': { 'field_name': 'facet_sort', 'style': 'form', 'explode': True }})
    facets: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'facets', 'style': 'form', 'explode': True }})
    finance_down_payment: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'finance_down_payment', 'style': 'form', 'explode': True }})
    finance_down_payment_per: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'finance_down_payment_per', 'style': 'form', 'explode': True }})
    finance_emp: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'finance_emp', 'style': 'form', 'explode': True }})
    finance_loan_apr: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'finance_loan_apr', 'style': 'form', 'explode': True }})
    finance_loan_term: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'finance_loan_term', 'style': 'form', 'explode': True }})
    first_seen_at_mc_days: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'first_seen_at_mc_days', 'style': 'form', 'explode': True }})
    first_seen_at_mc_range: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'first_seen_at_mc_range', 'style': 'form', 'explode': True }})
    first_seen_at_source_days: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'first_seen_at_source_days', 'style': 'form', 'explode': True }})
    first_seen_at_source_range: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'first_seen_at_source_range', 'style': 'form', 'explode': True }})
    first_seen_days: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'first_seen_days', 'style': 'form', 'explode': True }})
    first_seen_range: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'first_seen_range', 'style': 'form', 'explode': True }})
    fuel_type: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'fuel_type', 'style': 'form', 'explode': True }})
    highway_mpg_range: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'highway_mpg_range', 'style': 'form', 'explode': True }})
    include_finance: Optional[bool] = field(default=None, metadata={'query_param': { 'field_name': 'include_finance', 'style': 'form', 'explode': True }})
    include_lease: Optional[bool] = field(default=None, metadata={'query_param': { 'field_name': 'include_lease', 'style': 'form', 'explode': True }})
    include_non_vin_listings: Optional[bool] = field(default=None, metadata={'query_param': { 'field_name': 'include_non_vin_listings', 'style': 'form', 'explode': True }})
    include_relevant_links: Optional[bool] = field(default=None, metadata={'query_param': { 'field_name': 'include_relevant_links', 'style': 'form', 'explode': True }})
    interior_color: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'interior_color', 'style': 'form', 'explode': True }})
    last_seen_days: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'last_seen_days', 'style': 'form', 'explode': True }})
    last_seen_range: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'last_seen_range', 'style': 'form', 'explode': True }})
    latitude: Optional[float] = field(default=None, metadata={'query_param': { 'field_name': 'latitude', 'style': 'form', 'explode': True }})
    lease_down_payment: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'lease_down_payment', 'style': 'form', 'explode': True }})
    lease_emp: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'lease_emp', 'style': 'form', 'explode': True }})
    lease_term: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'lease_term', 'style': 'form', 'explode': True }})
    longitude: Optional[float] = field(default=None, metadata={'query_param': { 'field_name': 'longitude', 'style': 'form', 'explode': True }})
    make: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'make', 'style': 'form', 'explode': True }})
    match: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'match', 'style': 'form', 'explode': True }})
    miles_range: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'miles_range', 'style': 'form', 'explode': True }})
    mm: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'mm', 'style': 'form', 'explode': True }})
    model: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'model', 'style': 'form', 'explode': True }})
    msa_code: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'msa_code', 'style': 'form', 'explode': True }})
    msrp_range: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'msrp_range', 'style': 'form', 'explode': True }})
    nodedup: Optional[bool] = field(default=None, metadata={'query_param': { 'field_name': 'nodedup', 'style': 'form', 'explode': True }})
    owned: Optional[bool] = field(default=None, metadata={'query_param': { 'field_name': 'owned', 'style': 'form', 'explode': True }})
    photo_links: Optional[bool] = field(default=None, metadata={'query_param': { 'field_name': 'photo_links', 'style': 'form', 'explode': True }})
    plot: Optional[bool] = field(default=None, metadata={'query_param': { 'field_name': 'plot', 'style': 'form', 'explode': True }})
    price_range: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'price_range', 'style': 'form', 'explode': True }})
    radius: Optional[int] = field(default=None, metadata={'query_param': { 'field_name': 'radius', 'style': 'form', 'explode': True }})
    range_facets: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'range_facets', 'style': 'form', 'explode': True }})
    rows: Optional[int] = field(default=None, metadata={'query_param': { 'field_name': 'rows', 'style': 'form', 'explode': True }})
    sort_by: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'sort_by', 'style': 'form', 'explode': True }})
    sort_order: Optional[shared.SortOrderEnum] = field(default=None, metadata={'query_param': { 'field_name': 'sort_order', 'style': 'form', 'explode': True }})
    start: Optional[int] = field(default=None, metadata={'query_param': { 'field_name': 'start', 'style': 'form', 'explode': True }})
    state: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'state', 'style': 'form', 'explode': True }})
    stats: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'stats', 'style': 'form', 'explode': True }})
    stock_no: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'stock_no', 'style': 'form', 'explode': True }})
    taxonomy_vins: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'taxonomy_vins', 'style': 'form', 'explode': True }})
    transmission: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'transmission', 'style': 'form', 'explode': True }})
    trim: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'trim', 'style': 'form', 'explode': True }})
    trim_o: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'trim_o', 'style': 'form', 'explode': True }})
    trim_r: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'trim_r', 'style': 'form', 'explode': True }})
    vehicle_type: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'vehicle_type', 'style': 'form', 'explode': True }})
    vin: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'vin', 'style': 'form', 'explode': True }})
    vins: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'vins', 'style': 'form', 'explode': True }})
    year: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'year', 'style': 'form', 'explode': True }})
    ymm: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'ymm', 'style': 'form', 'explode': True }})
    ymmt: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'ymmt', 'style': 'form', 'explode': True }})
    zip: Optional[str] = field(default=None, metadata={'query_param': { 'field_name': 'zip', 'style': 'form', 'explode': True }})
    

@dataclass
class SearchRequest:
    query_params: SearchQueryParams = field(default=None)
    

@dataclass
class SearchResponse:
    content_type: str = field(default=None)
    error: Optional[shared.Error] = field(default=None)
    search_response: Optional[shared.SearchResponse] = field(default=None)
    status_code: int = field(default=None)
    
