# coding: utf-8

"""
    Content API for Shopping

    Manage your product listings and accounts for Google Shopping

    The version of the OpenAPI document: v2.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.settlement_transaction_transaction import SettlementTransactionTransaction

class TestSettlementTransactionTransaction(unittest.TestCase):
    """SettlementTransactionTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettlementTransactionTransaction:
        """Test SettlementTransactionTransaction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettlementTransactionTransaction`
        """
        model = SettlementTransactionTransaction()
        if include_optional:
            return SettlementTransactionTransaction(
                post_date = '',
                type = ''
            )
        else:
            return SettlementTransactionTransaction(
        )
        """

    def testSettlementTransactionTransaction(self):
        """Test SettlementTransactionTransaction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
