swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /fitness/v1/users
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Stores and accesses user data in the fitness store from apps on any platform.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Fitness
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/fitness/v1/rest'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: fitness
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/fitness.activity.read': View your activity information in Google Fit
      'https://www.googleapis.com/auth/fitness.activity.write': View and store your activity information in Google Fit
      'https://www.googleapis.com/auth/fitness.blood_glucose.read': View blood glucose data in Google Fit
      'https://www.googleapis.com/auth/fitness.blood_glucose.write': View and store blood glucose data in Google Fit
      'https://www.googleapis.com/auth/fitness.blood_pressure.read': View blood pressure data in Google Fit
      'https://www.googleapis.com/auth/fitness.blood_pressure.write': View and store blood pressure data in Google Fit
      'https://www.googleapis.com/auth/fitness.body.read': View body sensor information in Google Fit
      'https://www.googleapis.com/auth/fitness.body.write': View and store body sensor data in Google Fit
      'https://www.googleapis.com/auth/fitness.body_temperature.read': View body temperature data in Google Fit
      'https://www.googleapis.com/auth/fitness.body_temperature.write': View and store body temperature data in Google Fit
      'https://www.googleapis.com/auth/fitness.location.read': View your stored location data in Google Fit
      'https://www.googleapis.com/auth/fitness.location.write': View and store your location data in Google Fit
      'https://www.googleapis.com/auth/fitness.nutrition.read': View nutrition information in Google Fit
      'https://www.googleapis.com/auth/fitness.nutrition.write': View and store nutrition information in Google Fit
      'https://www.googleapis.com/auth/fitness.oxygen_saturation.read': View oxygen saturation data in Google Fit
      'https://www.googleapis.com/auth/fitness.oxygen_saturation.write': View and store oxygen saturation data in Google Fit
      'https://www.googleapis.com/auth/fitness.reproductive_health.read': View reproductive health data in Google Fit
      'https://www.googleapis.com/auth/fitness.reproductive_health.write': View and store reproductive health data in Google Fit
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/fitness.activity.read': View your activity information in Google Fit
      'https://www.googleapis.com/auth/fitness.activity.write': View and store your activity information in Google Fit
      'https://www.googleapis.com/auth/fitness.blood_glucose.read': View blood glucose data in Google Fit
      'https://www.googleapis.com/auth/fitness.blood_glucose.write': View and store blood glucose data in Google Fit
      'https://www.googleapis.com/auth/fitness.blood_pressure.read': View blood pressure data in Google Fit
      'https://www.googleapis.com/auth/fitness.blood_pressure.write': View and store blood pressure data in Google Fit
      'https://www.googleapis.com/auth/fitness.body.read': View body sensor information in Google Fit
      'https://www.googleapis.com/auth/fitness.body.write': View and store body sensor data in Google Fit
      'https://www.googleapis.com/auth/fitness.body_temperature.read': View body temperature data in Google Fit
      'https://www.googleapis.com/auth/fitness.body_temperature.write': View and store body temperature data in Google Fit
      'https://www.googleapis.com/auth/fitness.location.read': View your stored location data in Google Fit
      'https://www.googleapis.com/auth/fitness.location.write': View and store your location data in Google Fit
      'https://www.googleapis.com/auth/fitness.nutrition.read': View nutrition information in Google Fit
      'https://www.googleapis.com/auth/fitness.nutrition.write': View and store nutrition information in Google Fit
      'https://www.googleapis.com/auth/fitness.oxygen_saturation.read': View oxygen saturation data in Google Fit
      'https://www.googleapis.com/auth/fitness.oxygen_saturation.write': View and store oxygen saturation data in Google Fit
      'https://www.googleapis.com/auth/fitness.reproductive_health.read': View reproductive health data in Google Fit
      'https://www.googleapis.com/auth/fitness.reproductive_health.write': View and store reproductive health data in Google Fit
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: users
paths:
  '/{userId}/dataSources':
    get:
      description: 'Lists all data sources that are visible to the developer, using the OAuth scopes provided. The list is not exhaustive; the user may have private data sources that are only visible to other developers, or calls using other scopes.'
      operationId: fitness.users.dataSources.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.activity.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.activity.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.location.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.location.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.location.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.location.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.nutrition.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.nutrition.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
      tags:
        - users
    post:
      description: 'Creates a new data source that is unique across all data sources belonging to this user. The data stream ID field can be omitted and will be generated by the server with the correct format. The data stream ID is an ordered combination of some fields from the data source. In addition to the data source fields reflected into the data source ID, the developer project number that is authenticated when creating the data source is included. This developer project number is obfuscat[...]'
      operationId: fitness.users.dataSources.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.location.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.location.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
      tags:
        - users
  '/{userId}/dataSources/{dataSourceId}':
    delete:
      description: Deletes the specified data source. The request will fail if the data source contains any data points.
      operationId: fitness.users.dataSources.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.location.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.location.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
      tags:
        - users
    get:
      description: Returns the specified data source.
      operationId: fitness.users.dataSources.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.activity.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.activity.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.location.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.location.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.location.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.location.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.nutrition.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.nutrition.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
      tags:
        - users
    patch:
      description: |-
        Updates the specified data source. The dataStreamId, dataType, type, dataStreamName, and device properties with the exception of version, cannot be modified.

        Data sources are identified by their dataStreamId. This method supports patch semantics.
      operationId: fitness.users.dataSources.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.location.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.location.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
      tags:
        - users
    put:
      description: |-
        Updates the specified data source. The dataStreamId, dataType, type, dataStreamName, and device properties with the exception of version, cannot be modified.

        Data sources are identified by their dataStreamId.
      operationId: fitness.users.dataSources.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.location.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.location.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
      tags:
        - users
  '/{userId}/dataSources/{dataSourceId}/datasets/{datasetId}':
    delete:
      description: 'Performs an inclusive delete of all data points whose start and end times have any overlap with the time range specified by the dataset ID. For most data types, the entire data point will be deleted. For data types where the time span represents a consistent value (such as com.google.activity.segment), and a data point straddles either end point of the dataset, only the overlapping portion of the data point will be deleted.'
      operationId: fitness.users.dataSources.datasets.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.location.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.location.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
      tags:
        - users
    get:
      description: 'Returns a dataset containing all data points whose start and end times overlap with the specified range of the dataset minimum start time and maximum end time. Specifically, any data point whose start time is less than or equal to the dataset end time and whose end time is greater than or equal to the dataset start time.'
      operationId: fitness.users.dataSources.datasets.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.activity.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.activity.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.location.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.location.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.location.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.location.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.nutrition.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.nutrition.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
      tags:
        - users
    patch:
      description: Adds data points to a dataset. The dataset need not be previously created. All points within the given dataset will be returned with subsquent calls to retrieve this dataset. Data points can belong to more than one dataset. This method does not use patch semantics.
      operationId: fitness.users.dataSources.datasets.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.location.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.location.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
      tags:
        - users
  '/{userId}/dataset:aggregate':
    post:
      description: Aggregates data of a certain type or stream into buckets divided by a given type of boundary. Multiple data sets of multiple types and from multiple sources can be aggreated into exactly one bucket type per request.
      operationId: fitness.users.dataset.aggregate
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.activity.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.activity.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.location.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.location.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.location.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.location.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.nutrition.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.nutrition.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
      tags:
        - users
  '/{userId}/sessions':
    get:
      description: Lists sessions previously created.
      operationId: fitness.users.sessions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.activity.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.activity.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_glucose.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.blood_pressure.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.body_temperature.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.location.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.location.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.location.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.location.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.nutrition.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.nutrition.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.nutrition.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.oxygen_saturation.write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.read'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.read'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.reproductive_health.write'
      tags:
        - users
  '/{userId}/sessions/{sessionId}':
    delete:
      description: Deletes a session specified by the given session ID.
      operationId: fitness.users.sessions.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
      tags:
        - users
    put:
      description: Updates or insert a given session.
      operationId: fitness.users.sessions.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/fitness.activity.write'
      tags:
        - users