package shared

type InstanceTypeEnum string

const (
	InstanceTypeEnumMlT2Medium     InstanceTypeEnum = "ml.t2.medium"
	InstanceTypeEnumMlT2Large      InstanceTypeEnum = "ml.t2.large"
	InstanceTypeEnumMlT2Xlarge     InstanceTypeEnum = "ml.t2.xlarge"
	InstanceTypeEnumMlT22xlarge    InstanceTypeEnum = "ml.t2.2xlarge"
	InstanceTypeEnumMlT3Medium     InstanceTypeEnum = "ml.t3.medium"
	InstanceTypeEnumMlT3Large      InstanceTypeEnum = "ml.t3.large"
	InstanceTypeEnumMlT3Xlarge     InstanceTypeEnum = "ml.t3.xlarge"
	InstanceTypeEnumMlT32xlarge    InstanceTypeEnum = "ml.t3.2xlarge"
	InstanceTypeEnumMlM4Xlarge     InstanceTypeEnum = "ml.m4.xlarge"
	InstanceTypeEnumMlM42xlarge    InstanceTypeEnum = "ml.m4.2xlarge"
	InstanceTypeEnumMlM44xlarge    InstanceTypeEnum = "ml.m4.4xlarge"
	InstanceTypeEnumMlM410xlarge   InstanceTypeEnum = "ml.m4.10xlarge"
	InstanceTypeEnumMlM416xlarge   InstanceTypeEnum = "ml.m4.16xlarge"
	InstanceTypeEnumMlM5Xlarge     InstanceTypeEnum = "ml.m5.xlarge"
	InstanceTypeEnumMlM52xlarge    InstanceTypeEnum = "ml.m5.2xlarge"
	InstanceTypeEnumMlM54xlarge    InstanceTypeEnum = "ml.m5.4xlarge"
	InstanceTypeEnumMlM512xlarge   InstanceTypeEnum = "ml.m5.12xlarge"
	InstanceTypeEnumMlM524xlarge   InstanceTypeEnum = "ml.m5.24xlarge"
	InstanceTypeEnumMlM5dLarge     InstanceTypeEnum = "ml.m5d.large"
	InstanceTypeEnumMlM5dXlarge    InstanceTypeEnum = "ml.m5d.xlarge"
	InstanceTypeEnumMlM5d2xlarge   InstanceTypeEnum = "ml.m5d.2xlarge"
	InstanceTypeEnumMlM5d4xlarge   InstanceTypeEnum = "ml.m5d.4xlarge"
	InstanceTypeEnumMlM5d8xlarge   InstanceTypeEnum = "ml.m5d.8xlarge"
	InstanceTypeEnumMlM5d12xlarge  InstanceTypeEnum = "ml.m5d.12xlarge"
	InstanceTypeEnumMlM5d16xlarge  InstanceTypeEnum = "ml.m5d.16xlarge"
	InstanceTypeEnumMlM5d24xlarge  InstanceTypeEnum = "ml.m5d.24xlarge"
	InstanceTypeEnumMlC4Xlarge     InstanceTypeEnum = "ml.c4.xlarge"
	InstanceTypeEnumMlC42xlarge    InstanceTypeEnum = "ml.c4.2xlarge"
	InstanceTypeEnumMlC44xlarge    InstanceTypeEnum = "ml.c4.4xlarge"
	InstanceTypeEnumMlC48xlarge    InstanceTypeEnum = "ml.c4.8xlarge"
	InstanceTypeEnumMlC5Xlarge     InstanceTypeEnum = "ml.c5.xlarge"
	InstanceTypeEnumMlC52xlarge    InstanceTypeEnum = "ml.c5.2xlarge"
	InstanceTypeEnumMlC54xlarge    InstanceTypeEnum = "ml.c5.4xlarge"
	InstanceTypeEnumMlC59xlarge    InstanceTypeEnum = "ml.c5.9xlarge"
	InstanceTypeEnumMlC518xlarge   InstanceTypeEnum = "ml.c5.18xlarge"
	InstanceTypeEnumMlC5dXlarge    InstanceTypeEnum = "ml.c5d.xlarge"
	InstanceTypeEnumMlC5d2xlarge   InstanceTypeEnum = "ml.c5d.2xlarge"
	InstanceTypeEnumMlC5d4xlarge   InstanceTypeEnum = "ml.c5d.4xlarge"
	InstanceTypeEnumMlC5d9xlarge   InstanceTypeEnum = "ml.c5d.9xlarge"
	InstanceTypeEnumMlC5d18xlarge  InstanceTypeEnum = "ml.c5d.18xlarge"
	InstanceTypeEnumMlP2Xlarge     InstanceTypeEnum = "ml.p2.xlarge"
	InstanceTypeEnumMlP28xlarge    InstanceTypeEnum = "ml.p2.8xlarge"
	InstanceTypeEnumMlP216xlarge   InstanceTypeEnum = "ml.p2.16xlarge"
	InstanceTypeEnumMlP32xlarge    InstanceTypeEnum = "ml.p3.2xlarge"
	InstanceTypeEnumMlP38xlarge    InstanceTypeEnum = "ml.p3.8xlarge"
	InstanceTypeEnumMlP316xlarge   InstanceTypeEnum = "ml.p3.16xlarge"
	InstanceTypeEnumMlP3dn24xlarge InstanceTypeEnum = "ml.p3dn.24xlarge"
	InstanceTypeEnumMlG4dnXlarge   InstanceTypeEnum = "ml.g4dn.xlarge"
	InstanceTypeEnumMlG4dn2xlarge  InstanceTypeEnum = "ml.g4dn.2xlarge"
	InstanceTypeEnumMlG4dn4xlarge  InstanceTypeEnum = "ml.g4dn.4xlarge"
	InstanceTypeEnumMlG4dn8xlarge  InstanceTypeEnum = "ml.g4dn.8xlarge"
	InstanceTypeEnumMlG4dn12xlarge InstanceTypeEnum = "ml.g4dn.12xlarge"
	InstanceTypeEnumMlG4dn16xlarge InstanceTypeEnum = "ml.g4dn.16xlarge"
	InstanceTypeEnumMlR5Large      InstanceTypeEnum = "ml.r5.large"
	InstanceTypeEnumMlR5Xlarge     InstanceTypeEnum = "ml.r5.xlarge"
	InstanceTypeEnumMlR52xlarge    InstanceTypeEnum = "ml.r5.2xlarge"
	InstanceTypeEnumMlR54xlarge    InstanceTypeEnum = "ml.r5.4xlarge"
	InstanceTypeEnumMlR58xlarge    InstanceTypeEnum = "ml.r5.8xlarge"
	InstanceTypeEnumMlR512xlarge   InstanceTypeEnum = "ml.r5.12xlarge"
	InstanceTypeEnumMlR516xlarge   InstanceTypeEnum = "ml.r5.16xlarge"
	InstanceTypeEnumMlR524xlarge   InstanceTypeEnum = "ml.r5.24xlarge"
)
