package shared

type ProcessingInstanceTypeEnum string

const (
	ProcessingInstanceTypeEnumMlT3Medium     ProcessingInstanceTypeEnum = "ml.t3.medium"
	ProcessingInstanceTypeEnumMlT3Large      ProcessingInstanceTypeEnum = "ml.t3.large"
	ProcessingInstanceTypeEnumMlT3Xlarge     ProcessingInstanceTypeEnum = "ml.t3.xlarge"
	ProcessingInstanceTypeEnumMlT32xlarge    ProcessingInstanceTypeEnum = "ml.t3.2xlarge"
	ProcessingInstanceTypeEnumMlM4Xlarge     ProcessingInstanceTypeEnum = "ml.m4.xlarge"
	ProcessingInstanceTypeEnumMlM42xlarge    ProcessingInstanceTypeEnum = "ml.m4.2xlarge"
	ProcessingInstanceTypeEnumMlM44xlarge    ProcessingInstanceTypeEnum = "ml.m4.4xlarge"
	ProcessingInstanceTypeEnumMlM410xlarge   ProcessingInstanceTypeEnum = "ml.m4.10xlarge"
	ProcessingInstanceTypeEnumMlM416xlarge   ProcessingInstanceTypeEnum = "ml.m4.16xlarge"
	ProcessingInstanceTypeEnumMlC4Xlarge     ProcessingInstanceTypeEnum = "ml.c4.xlarge"
	ProcessingInstanceTypeEnumMlC42xlarge    ProcessingInstanceTypeEnum = "ml.c4.2xlarge"
	ProcessingInstanceTypeEnumMlC44xlarge    ProcessingInstanceTypeEnum = "ml.c4.4xlarge"
	ProcessingInstanceTypeEnumMlC48xlarge    ProcessingInstanceTypeEnum = "ml.c4.8xlarge"
	ProcessingInstanceTypeEnumMlP2Xlarge     ProcessingInstanceTypeEnum = "ml.p2.xlarge"
	ProcessingInstanceTypeEnumMlP28xlarge    ProcessingInstanceTypeEnum = "ml.p2.8xlarge"
	ProcessingInstanceTypeEnumMlP216xlarge   ProcessingInstanceTypeEnum = "ml.p2.16xlarge"
	ProcessingInstanceTypeEnumMlP32xlarge    ProcessingInstanceTypeEnum = "ml.p3.2xlarge"
	ProcessingInstanceTypeEnumMlP38xlarge    ProcessingInstanceTypeEnum = "ml.p3.8xlarge"
	ProcessingInstanceTypeEnumMlP316xlarge   ProcessingInstanceTypeEnum = "ml.p3.16xlarge"
	ProcessingInstanceTypeEnumMlC5Xlarge     ProcessingInstanceTypeEnum = "ml.c5.xlarge"
	ProcessingInstanceTypeEnumMlC52xlarge    ProcessingInstanceTypeEnum = "ml.c5.2xlarge"
	ProcessingInstanceTypeEnumMlC54xlarge    ProcessingInstanceTypeEnum = "ml.c5.4xlarge"
	ProcessingInstanceTypeEnumMlC59xlarge    ProcessingInstanceTypeEnum = "ml.c5.9xlarge"
	ProcessingInstanceTypeEnumMlC518xlarge   ProcessingInstanceTypeEnum = "ml.c5.18xlarge"
	ProcessingInstanceTypeEnumMlM5Large      ProcessingInstanceTypeEnum = "ml.m5.large"
	ProcessingInstanceTypeEnumMlM5Xlarge     ProcessingInstanceTypeEnum = "ml.m5.xlarge"
	ProcessingInstanceTypeEnumMlM52xlarge    ProcessingInstanceTypeEnum = "ml.m5.2xlarge"
	ProcessingInstanceTypeEnumMlM54xlarge    ProcessingInstanceTypeEnum = "ml.m5.4xlarge"
	ProcessingInstanceTypeEnumMlM512xlarge   ProcessingInstanceTypeEnum = "ml.m5.12xlarge"
	ProcessingInstanceTypeEnumMlM524xlarge   ProcessingInstanceTypeEnum = "ml.m5.24xlarge"
	ProcessingInstanceTypeEnumMlR5Large      ProcessingInstanceTypeEnum = "ml.r5.large"
	ProcessingInstanceTypeEnumMlR5Xlarge     ProcessingInstanceTypeEnum = "ml.r5.xlarge"
	ProcessingInstanceTypeEnumMlR52xlarge    ProcessingInstanceTypeEnum = "ml.r5.2xlarge"
	ProcessingInstanceTypeEnumMlR54xlarge    ProcessingInstanceTypeEnum = "ml.r5.4xlarge"
	ProcessingInstanceTypeEnumMlR58xlarge    ProcessingInstanceTypeEnum = "ml.r5.8xlarge"
	ProcessingInstanceTypeEnumMlR512xlarge   ProcessingInstanceTypeEnum = "ml.r5.12xlarge"
	ProcessingInstanceTypeEnumMlR516xlarge   ProcessingInstanceTypeEnum = "ml.r5.16xlarge"
	ProcessingInstanceTypeEnumMlR524xlarge   ProcessingInstanceTypeEnum = "ml.r5.24xlarge"
	ProcessingInstanceTypeEnumMlG4dnXlarge   ProcessingInstanceTypeEnum = "ml.g4dn.xlarge"
	ProcessingInstanceTypeEnumMlG4dn2xlarge  ProcessingInstanceTypeEnum = "ml.g4dn.2xlarge"
	ProcessingInstanceTypeEnumMlG4dn4xlarge  ProcessingInstanceTypeEnum = "ml.g4dn.4xlarge"
	ProcessingInstanceTypeEnumMlG4dn8xlarge  ProcessingInstanceTypeEnum = "ml.g4dn.8xlarge"
	ProcessingInstanceTypeEnumMlG4dn12xlarge ProcessingInstanceTypeEnum = "ml.g4dn.12xlarge"
	ProcessingInstanceTypeEnumMlG4dn16xlarge ProcessingInstanceTypeEnum = "ml.g4dn.16xlarge"
)
