from dataclasses import dataclass, field
from enum import Enum

class ClusterStateEnum(str, Enum):
    CREATE_IN_PROGRESS = "CREATE_IN_PROGRESS"
    UNINITIALIZED = "UNINITIALIZED"
    INITIALIZE_IN_PROGRESS = "INITIALIZE_IN_PROGRESS"
    INITIALIZED = "INITIALIZED"
    ACTIVE = "ACTIVE"
    UPDATE_IN_PROGRESS = "UPDATE_IN_PROGRESS"
    DELETE_IN_PROGRESS = "DELETE_IN_PROGRESS"
    DELETED = "DELETED"
    DEGRADED = "DEGRADED"

