swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /adexchangeseller/v2.0
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Accesses the inventory of Ad Exchange seller users and generates reports.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Ad Exchange Seller
  version: v2.0
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.doubleclickbygoogle.com/static/core/img/doubleclick-google-logo-wide.svg'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/adexchangeseller/v2.0/rest'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: adexchangeseller
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/adexchange.seller': View and manage your Ad Exchange data
      'https://www.googleapis.com/auth/adexchange.seller.readonly': View your Ad Exchange data
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/adexchange.seller': View and manage your Ad Exchange data
      'https://www.googleapis.com/auth/adexchange.seller.readonly': View your Ad Exchange data
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: accounts
paths:
  /accounts:
    get:
      description: List all accounts available to this Ad Exchange account.
      operationId: adexchangeseller.accounts.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - accounts
  '/accounts/{accountId}':
    get:
      description: Get information about the selected Ad Exchange account.
      operationId: adexchangeseller.accounts.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - accounts
  '/accounts/{accountId}/adclients':
    get:
      description: List all ad clients in this Ad Exchange account.
      operationId: adexchangeseller.accounts.adclients.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - accounts
  '/accounts/{accountId}/adclients/{adClientId}/customchannels':
    get:
      description: List all custom channels in the specified ad client for this Ad Exchange account.
      operationId: adexchangeseller.accounts.customchannels.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - accounts
  '/accounts/{accountId}/adclients/{adClientId}/customchannels/{customChannelId}':
    get:
      description: Get the specified custom channel from the specified ad client.
      operationId: adexchangeseller.accounts.customchannels.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - accounts
  '/accounts/{accountId}/adclients/{adClientId}/urlchannels':
    get:
      description: List all URL channels in the specified ad client for this Ad Exchange account.
      operationId: adexchangeseller.accounts.urlchannels.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - accounts
  '/accounts/{accountId}/alerts':
    get:
      description: List the alerts for this Ad Exchange account.
      operationId: adexchangeseller.accounts.alerts.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - accounts
  '/accounts/{accountId}/metadata/dimensions':
    get:
      description: List the metadata for the dimensions available to this AdExchange account.
      operationId: adexchangeseller.accounts.metadata.dimensions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - accounts
  '/accounts/{accountId}/metadata/metrics':
    get:
      description: List the metadata for the metrics available to this AdExchange account.
      operationId: adexchangeseller.accounts.metadata.metrics.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - accounts
  '/accounts/{accountId}/preferreddeals':
    get:
      description: List the preferred deals for this Ad Exchange account.
      operationId: adexchangeseller.accounts.preferreddeals.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - accounts
  '/accounts/{accountId}/preferreddeals/{dealId}':
    get:
      description: Get information about the selected Ad Exchange Preferred Deal.
      operationId: adexchangeseller.accounts.preferreddeals.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - accounts
  '/accounts/{accountId}/reports':
    get:
      description: Generate an Ad Exchange report based on the report request sent in the query parameters. Returns the result as JSON; to retrieve output in CSV format specify "alt=csv" as a query parameter.
      operationId: adexchangeseller.accounts.reports.generate
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - accounts
  '/accounts/{accountId}/reports/saved':
    get:
      description: List all saved reports in this Ad Exchange account.
      operationId: adexchangeseller.accounts.reports.saved.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - accounts
  '/accounts/{accountId}/reports/{savedReportId}':
    get:
      description: Generate an Ad Exchange report based on the saved report ID sent in the query parameters.
      operationId: adexchangeseller.accounts.reports.saved.generate
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller'
        - Oauth2:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/adexchange.seller.readonly'
      tags:
        - accounts