openapi: 3.0.0
servers:
  - url: 'https://www.googleapis.com/gmail/v1/users'
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Access Gmail mailboxes including sending user email.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Gmail
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-apisguru-categories:
    - email
  x-logo:
    url: 'https://www.gstatic.com/images/icons/material/product/2x/gmail_64dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: gmail
tags:
  - name: users
paths:
  '/{userId}/drafts':
    get:
      description: Lists the drafts in the user's mailbox.
      operationId: gmail.users.drafts.list
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.compose'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.compose'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
      tags:
        - users
    post:
      description: Creates a new draft with the DRAFT label.
      operationId: gmail.users.drafts.create
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.compose'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.compose'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
      tags:
        - users
  '/{userId}/drafts/send':
    post:
      description: 'Sends the specified, existing draft to the recipients in the To, Cc, and Bcc headers.'
      operationId: gmail.users.drafts.send
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.compose'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.compose'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
      tags:
        - users
  '/{userId}/drafts/{id}':
    delete:
      description: Immediately and permanently deletes the specified draft. Does not simply trash it.
      operationId: gmail.users.drafts.delete
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.compose'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.compose'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
      tags:
        - users
    get:
      description: Gets the specified draft.
      operationId: gmail.users.drafts.get
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.compose'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.compose'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
      tags:
        - users
    put:
      description: Replaces a draft's content.
      operationId: gmail.users.drafts.update
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.compose'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.compose'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
      tags:
        - users
  '/{userId}/history':
    get:
      description: Lists the history of all changes to the given mailbox. History results are returned in chronological order (increasing historyId).
      operationId: gmail.users.history.list
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.metadata'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
      tags:
        - users
  '/{userId}/labels':
    get:
      description: Lists all labels in the user's mailbox.
      operationId: gmail.users.labels.list
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.labels'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.labels'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.metadata'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
      tags:
        - users
    post:
      description: Creates a new label.
      operationId: gmail.users.labels.create
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.labels'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.labels'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
      tags:
        - users
  '/{userId}/labels/{id}':
    delete:
      description: Immediately and permanently deletes the specified label and removes it from any messages and threads that it is applied to.
      operationId: gmail.users.labels.delete
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.labels'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.labels'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
      tags:
        - users
    get:
      description: Gets the specified label.
      operationId: gmail.users.labels.get
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.labels'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.labels'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.metadata'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
      tags:
        - users
    patch:
      description: Updates the specified label. This method supports patch semantics.
      operationId: gmail.users.labels.patch
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.labels'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.labels'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
      tags:
        - users
    put:
      description: Updates the specified label.
      operationId: gmail.users.labels.update
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.labels'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.labels'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
      tags:
        - users
  '/{userId}/messages':
    get:
      description: Lists the messages in the user's mailbox.
      operationId: gmail.users.messages.list
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.metadata'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
      tags:
        - users
    post:
      description: 'Directly inserts a message into only this user''s mailbox similar to IMAP APPEND, bypassing most scanning and classification. Does not send a message.'
      operationId: gmail.users.messages.insert
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.insert'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.insert'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
      tags:
        - users
  '/{userId}/messages/batchDelete':
    post:
      description: Deletes many messages by message ID. Provides no guarantees that messages were not already deleted or even existed at all.
      operationId: gmail.users.messages.batchDelete
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
      tags:
        - users
  '/{userId}/messages/batchModify':
    post:
      description: Modifies the labels on the specified messages.
      operationId: gmail.users.messages.batchModify
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
      tags:
        - users
  '/{userId}/messages/import':
    post:
      description: 'Imports a message into only this user''s mailbox, with standard email delivery scanning and classification similar to receiving via SMTP. Does not send a message.'
      operationId: gmail.users.messages.import
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.insert'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.insert'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
      tags:
        - users
  '/{userId}/messages/send':
    post:
      description: 'Sends the specified message to the recipients in the To, Cc, and Bcc headers.'
      operationId: gmail.users.messages.send
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.compose'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.compose'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.send'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.send'
      tags:
        - users
  '/{userId}/messages/{id}':
    delete:
      description: Immediately and permanently deletes the specified message. This operation cannot be undone. Prefer messages.trash instead.
      operationId: gmail.users.messages.delete
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
      tags:
        - users
    get:
      description: Gets the specified message.
      operationId: gmail.users.messages.get
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.metadata'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
      tags:
        - users
  '/{userId}/messages/{id}/modify':
    post:
      description: Modifies the labels on the specified message.
      operationId: gmail.users.messages.modify
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
      tags:
        - users
  '/{userId}/messages/{id}/trash':
    post:
      description: Moves the specified message to the trash.
      operationId: gmail.users.messages.trash
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
      tags:
        - users
  '/{userId}/messages/{id}/untrash':
    post:
      description: Removes the specified message from the trash.
      operationId: gmail.users.messages.untrash
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
      tags:
        - users
  '/{userId}/messages/{messageId}/attachments/{id}':
    get:
      description: Gets the specified message attachment.
      operationId: gmail.users.messages.attachments.get
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
      tags:
        - users
  '/{userId}/profile':
    get:
      description: Gets the current user's Gmail profile.
      operationId: gmail.users.getProfile
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.compose'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.compose'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.metadata'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
      tags:
        - users
  '/{userId}/settings/autoForwarding':
    get:
      description: Gets the auto-forwarding setting for the specified account.
      operationId: gmail.users.settings.getAutoForwarding
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
      tags:
        - users
    put:
      description: |-
        Updates the auto-forwarding setting for the specified account. A verified forwarding address must be specified when auto-forwarding is enabled.

        This method is only available to service account clients that have been delegated domain-wide authority.
      operationId: gmail.users.settings.updateAutoForwarding
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
      tags:
        - users
  '/{userId}/settings/filters':
    get:
      description: Lists the message filters of a Gmail user.
      operationId: gmail.users.settings.filters.list
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
      tags:
        - users
    post:
      description: Creates a filter.
      operationId: gmail.users.settings.filters.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
      tags:
        - users
  '/{userId}/settings/filters/{id}':
    delete:
      description: Deletes a filter.
      operationId: gmail.users.settings.filters.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
      tags:
        - users
    get:
      description: Gets a filter.
      operationId: gmail.users.settings.filters.get
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
      tags:
        - users
  '/{userId}/settings/forwardingAddresses':
    get:
      description: Lists the forwarding addresses for the specified account.
      operationId: gmail.users.settings.forwardingAddresses.list
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
      tags:
        - users
    post:
      description: |-
        Creates a forwarding address. If ownership verification is required, a message will be sent to the recipient and the resource's verification status will be set to pending; otherwise, the resource will be created with verification status set to accepted.

        This method is only available to service account clients that have been delegated domain-wide authority.
      operationId: gmail.users.settings.forwardingAddresses.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
      tags:
        - users
  '/{userId}/settings/forwardingAddresses/{forwardingEmail}':
    delete:
      description: |-
        Deletes the specified forwarding address and revokes any verification that may have been required.

        This method is only available to service account clients that have been delegated domain-wide authority.
      operationId: gmail.users.settings.forwardingAddresses.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
      tags:
        - users
    get:
      description: Gets the specified forwarding address.
      operationId: gmail.users.settings.forwardingAddresses.get
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
      tags:
        - users
  '/{userId}/settings/imap':
    get:
      description: Gets IMAP settings.
      operationId: gmail.users.settings.getImap
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
      tags:
        - users
    put:
      description: Updates IMAP settings.
      operationId: gmail.users.settings.updateImap
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
      tags:
        - users
  '/{userId}/settings/pop':
    get:
      description: Gets POP settings.
      operationId: gmail.users.settings.getPop
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
      tags:
        - users
    put:
      description: Updates POP settings.
      operationId: gmail.users.settings.updatePop
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
      tags:
        - users
  '/{userId}/settings/sendAs':
    get:
      description: Lists the send-as aliases for the specified account. The result includes the primary send-as address associated with the account as well as any custom "from" aliases.
      operationId: gmail.users.settings.sendAs.list
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
      tags:
        - users
    post:
      description: |-
        Creates a custom "from" send-as alias. If an SMTP MSA is specified, Gmail will attempt to connect to the SMTP service to validate the configuration before creating the alias. If ownership verification is required for the alias, a message will be sent to the email address and the resource's verification status will be set to pending; otherwise, the resource will be created with verification status set to accepted. If a signature is provided, Gmail will sanitize the HTML before saving it w[...]

        This method is only available to service account clients that have been delegated domain-wide authority.
      operationId: gmail.users.settings.sendAs.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
      tags:
        - users
  '/{userId}/settings/sendAs/{sendAsEmail}':
    delete:
      description: |-
        Deletes the specified send-as alias. Revokes any verification that may have been required for using it.

        This method is only available to service account clients that have been delegated domain-wide authority.
      operationId: gmail.users.settings.sendAs.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
      tags:
        - users
    get:
      description: Gets the specified send-as alias. Fails with an HTTP 404 error if the specified address is not a member of the collection.
      operationId: gmail.users.settings.sendAs.get
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
      tags:
        - users
    patch:
      description: |-
        Updates a send-as alias. If a signature is provided, Gmail will sanitize the HTML before saving it with the alias.

        Addresses other than the primary address for the account can only be updated by service account clients that have been delegated domain-wide authority. This method supports patch semantics.
      operationId: gmail.users.settings.sendAs.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
      tags:
        - users
    put:
      description: |-
        Updates a send-as alias. If a signature is provided, Gmail will sanitize the HTML before saving it with the alias.

        Addresses other than the primary address for the account can only be updated by service account clients that have been delegated domain-wide authority.
      operationId: gmail.users.settings.sendAs.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
      tags:
        - users
  '/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo':
    get:
      description: Lists S/MIME configs for the specified send-as alias.
      operationId: gmail.users.settings.sendAs.smimeInfo.list
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
      tags:
        - users
    post:
      description: Insert (upload) the given S/MIME config for the specified send-as alias. Note that pkcs12 format is required for the key.
      operationId: gmail.users.settings.sendAs.smimeInfo.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
      tags:
        - users
  '/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}':
    delete:
      description: Deletes the specified S/MIME config for the specified send-as alias.
      operationId: gmail.users.settings.sendAs.smimeInfo.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
      tags:
        - users
    get:
      description: Gets the specified S/MIME config for the specified send-as alias.
      operationId: gmail.users.settings.sendAs.smimeInfo.get
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
      tags:
        - users
  '/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault':
    post:
      description: Sets the default S/MIME config for the specified send-as alias.
      operationId: gmail.users.settings.sendAs.smimeInfo.setDefault
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
      tags:
        - users
  '/{userId}/settings/sendAs/{sendAsEmail}/verify':
    post:
      description: |-
        Sends a verification email to the specified send-as alias address. The verification status must be pending.

        This method is only available to service account clients that have been delegated domain-wide authority.
      operationId: gmail.users.settings.sendAs.verify
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.sharing'
      tags:
        - users
  '/{userId}/settings/vacation':
    get:
      description: Gets vacation responder settings.
      operationId: gmail.users.settings.getVacation
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
      tags:
        - users
    put:
      description: Updates vacation responder settings.
      operationId: gmail.users.settings.updateVacation
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.settings.basic'
      tags:
        - users
  '/{userId}/stop':
    post:
      description: Stop receiving push notifications for the given user mailbox.
      operationId: gmail.users.stop
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.metadata'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
      tags:
        - users
  '/{userId}/threads':
    get:
      description: Lists the threads in the user's mailbox.
      operationId: gmail.users.threads.list
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.metadata'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
      tags:
        - users
  '/{userId}/threads/{id}':
    delete:
      description: Immediately and permanently deletes the specified thread. This operation cannot be undone. Prefer threads.trash instead.
      operationId: gmail.users.threads.delete
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
      tags:
        - users
    get:
      description: Gets the specified thread.
      operationId: gmail.users.threads.get
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.metadata'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
      tags:
        - users
  '/{userId}/threads/{id}/modify':
    post:
      description: Modifies the labels applied to the thread. This applies to all messages in the thread.
      operationId: gmail.users.threads.modify
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
      tags:
        - users
  '/{userId}/threads/{id}/trash':
    post:
      description: Moves the specified thread to the trash.
      operationId: gmail.users.threads.trash
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
      tags:
        - users
  '/{userId}/threads/{id}/untrash':
    post:
      description: Removes the specified thread from the trash.
      operationId: gmail.users.threads.untrash
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
      tags:
        - users
  '/{userId}/watch':
    post:
      description: Set up or update a push notification watch on the given user mailbox.
      operationId: gmail.users.watch
      security:
        - Oauth2:
            - 'https://mail.google.com/'
          Oauth2c:
            - 'https://mail.google.com/'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.metadata'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.metadata'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.modify'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.modify'
        - Oauth2:
            - 'https://www.googleapis.com/auth/gmail.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/gmail.readonly'
      tags:
        - users
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
          scopes:
            'https://mail.google.com/': 'Read, send, delete, and manage your email'
            'https://www.googleapis.com/auth/gmail.compose': Manage drafts and send emails
            'https://www.googleapis.com/auth/gmail.insert': Insert mail into your mailbox
            'https://www.googleapis.com/auth/gmail.labels': Manage mailbox labels
            'https://www.googleapis.com/auth/gmail.metadata': 'View your email message metadata such as labels and headers, but not the email body'
            'https://www.googleapis.com/auth/gmail.modify': View and modify but not delete your email
            'https://www.googleapis.com/auth/gmail.readonly': View your emails messages and settings
            'https://www.googleapis.com/auth/gmail.send': Send email on your behalf
            'https://www.googleapis.com/auth/gmail.settings.basic': Manage your basic mail settings
            'https://www.googleapis.com/auth/gmail.settings.sharing': 'Manage your sensitive mail settings, including who can manage your mail'
    Oauth2c:
      description: Oauth 2.0 accessCode authentication
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
          tokenUrl: 'https://accounts.google.com/o/oauth2/token'
          scopes:
            'https://mail.google.com/': 'Read, send, delete, and manage your email'
            'https://www.googleapis.com/auth/gmail.compose': Manage drafts and send emails
            'https://www.googleapis.com/auth/gmail.insert': Insert mail into your mailbox
            'https://www.googleapis.com/auth/gmail.labels': Manage mailbox labels
            'https://www.googleapis.com/auth/gmail.metadata': 'View your email message metadata such as labels and headers, but not the email body'
            'https://www.googleapis.com/auth/gmail.modify': View and modify but not delete your email
            'https://www.googleapis.com/auth/gmail.readonly': View your emails messages and settings
            'https://www.googleapis.com/auth/gmail.send': Send email on your behalf
            'https://www.googleapis.com/auth/gmail.settings.basic': Manage your basic mail settings
            'https://www.googleapis.com/auth/gmail.settings.sharing': 'Manage your sensitive mail settings, including who can manage your mail'
