

export enum CreativeImagesFieldValuesEnum {
    AllowedUse = "allowed_use"
,    AlternativeIds = "alternative_ids"
,    Artist = "artist"
,    AssetFamily = "asset_family"
,    CallForImage = "call_for_image"
,    Caption = "caption"
,    CollectionCode = "collection_code"
,    CollectionId = "collection_id"
,    CollectionName = "collection_name"
,    ColorType = "color_type"
,    Comp = "comp"
,    Copyright = "copyright"
,    DateCameraShot = "date_camera_shot"
,    DateCreated = "date_created"
,    DateSubmitted = "date_submitted"
,    DetailSet = "detail_set"
,    DisplaySet = "display_set"
,    DownloadProduct = "download_product"
,    DownloadSizes = "download_sizes"
,    GraphicalStyle = "graphical_style"
,    Id = "id"
,    IstockCollection = "istock_collection"
,    Keywords = "keywords"
,    LargestDownloads = "largest_downloads"
,    LicenseModel = "license_model"
,    MaxDimensions = "max_dimensions"
,    Orientation = "orientation"
,    Preview = "preview"
,    ProductTypes = "product_types"
,    QualityRank = "quality_rank"
,    ReferralDestinations = "referral_destinations"
,    SummarySet = "summary_set"
,    Thumb = "thumb"
,    Title = "title"
,    UriOembed = "uri_oembed"
}
