


export enum ImageDetailFieldValuesEnum {
    AllowedUse = "allowed_use",
    AlternativeIds = "alternative_ids",
    Artist = "artist",
    ArtistTitle = "artist_title",
    AssetFamily = "asset_family",
    CallForImage = "call_for_image",
    Caption = "caption",
    City = "city",
    CollectionCode = "collection_code",
    CollectionId = "collection_id",
    CollectionName = "collection_name",
    ColorType = "color_type",
    Comp = "comp",
    Copyright = "copyright",
    Country = "country",
    CreditLine = "credit_line",
    DateCameraShot = "date_camera_shot",
    DateCreated = "date_created",
    DateSubmitted = "date_submitted",
    DetailSet = "detail_set",
    DisplaySet = "display_set",
    DownloadSizes = "download_sizes",
    DownloadProduct = "download_product",
    Downloads = "downloads",
    EditorialSegments = "editorial_segments",
    EditorialSource = "editorial_source",
    EntityDetails = "entity_details",
    EventIds = "event_ids",
    GraphicalStyle = "graphical_style",
    Id = "id",
    IstockCollection = "istock_collection",
    IstockLicenses = "istock_licenses",
    Keywords = "keywords",
    LargestDownloads = "largest_downloads",
    LicenseModel = "license_model",
    Links = "links",
    MaxDimensions = "max_dimensions",
    ObjectName = "object_name",
    Orientation = "orientation",
    People = "people",
    Preview = "preview",
    ProductTypes = "product_types",
    QualityRank = "quality_rank",
    ReferralDestinations = "referral_destinations",
    StateProvince = "state_province",
    SummarySet = "summary_set",
    Thumb = "thumb",
    Title = "title",
    UriOembed = "uri_oembed"
}
