

export enum VideoDetailFieldValuesEnum {
    Id = "id"
,    AllowedUse = "allowed_use"
,    Artist = "artist"
,    AssetFamily = "asset_family"
,    CallForImage = "call_for_image"
,    Caption = "caption"
,    ClipLength = "clip_length"
,    CollectionCode = "collection_code"
,    CollectionId = "collection_id"
,    CollectionName = "collection_name"
,    ColorType = "color_type"
,    Comp = "comp"
,    Copyright = "copyright"
,    DateCreated = "date_created"
,    DateSubmitted = "date_submitted"
,    DetailSet = "detail_set"
,    DisplaySet = "display_set"
,    DownloadSizes = "download_sizes"
,    DownloadProduct = "download_product"
,    Downloads = "downloads"
,    EditorialSegments = "editorial_segments"
,    EntityDetails = "entity_details"
,    Era = "era"
,    EventIds = "event_ids"
,    IstockCollection = "istock_collection"
,    IstockLicenses = "istock_licenses"
,    Keywords = "keywords"
,    LicenseModel = "license_model"
,    MasteredTo = "mastered_to"
,    ObjectName = "object_name"
,    Orientation = "orientation"
,    OriginallyShotOn = "originally_shot_on"
,    Preview = "preview"
,    ProductTypes = "product_types"
,    QualityRank = "quality_rank"
,    ReferralDestinations = "referral_destinations"
,    ShotSpeed = "shot_speed"
,    Source = "source"
,    SummarySet = "summary_set"
,    Thumb = "thumb"
,    Title = "title"
}
