from .credentials import *
from .district import *
from .districtadmin import *
from .districtadminresponse import *
from .districtadminsresponse import *
from .districtresponse import *
from .districtsresponse import *
from .districtstatus import *
from .districtstatusresponse import *
from .districtstatusresponses import *
from .gradelevelsresponse import *
from .location import *
from .name import *
from .notfound import *
from .principal import *
from .school import *
from .schooladmin import *
from .schooladminresponse import *
from .schooladminsresponse import *
from .schoolresponse import *
from .schoolsresponse import *
from .section import *
from .sectionresponse import *
from .sectionsresponse import *
from .security import *
from .student import *
from .studentcontact import *
from .studentcontactresponse import *
from .studentcontactsforstudentresponse import *
from .studentcontactsresponse import *
from .studentresponse import *
from .studentsresponse import *
from .teacher import *
from .teacherresponse import *
from .teachersresponse import *
from .term import *
