from .appendchatmessageusingget import *
from .appendchatmessageusingpost import *
from .appendtextusingget import *
from .appendtextusingpost import *
from .checktokenusingget import *
from .checktokenusingpost import *
from .copypadusingget import *
from .copypadusingpost import *
from .copypadwithouthistoryusingget import *
from .copypadwithouthistoryusingpost import *
from .createauthorifnotexistsforusingget import *
from .createauthorifnotexistsforusingpost import *
from .createauthorusingget import *
from .createauthorusingpost import *
from .creatediffhtmlusingget import *
from .creatediffhtmlusingpost import *
from .creategroupifnotexistsforusingget import *
from .creategroupifnotexistsforusingpost import *
from .creategrouppadusingget import *
from .creategrouppadusingpost import *
from .creategroupusingget import *
from .creategroupusingpost import *
from .createpadusingget import *
from .createpadusingpost import *
from .createsessionusingget import *
from .createsessionusingpost import *
from .deletegroupusingget import *
from .deletegroupusingpost import *
from .deletepadusingget import *
from .deletepadusingpost import *
from .deletesessionusingget import *
from .deletesessionusingpost import *
from .getattributepoolusingget import *
from .getattributepoolusingpost import *
from .getauthornameusingget import *
from .getauthornameusingpost import *
from .getchatheadusingget import *
from .getchatheadusingpost import *
from .getchathistoryusingget import *
from .getchathistoryusingpost import *
from .gethtmlusingget import *
from .gethtmlusingpost import *
from .getlasteditedusingget import *
from .getlasteditedusingpost import *
from .getpadidusingget import *
from .getpadidusingpost import *
from .getpublicstatususingget import *
from .getpublicstatususingpost import *
from .getreadonlyidusingget import *
from .getreadonlyidusingpost import *
from .getrevisionchangesetusingget import *
from .getrevisionchangesetusingpost import *
from .getrevisionscountusingget import *
from .getrevisionscountusingpost import *
from .getsavedrevisionscountusingget import *
from .getsavedrevisionscountusingpost import *
from .getsessioninfousingget import *
from .getsessioninfousingpost import *
from .getstatsusingget import *
from .getstatsusingpost import *
from .gettextusingget import *
from .gettextusingpost import *
from .listallgroupsusingget import *
from .listallgroupsusingpost import *
from .listallpadsusingget import *
from .listallpadsusingpost import *
from .listauthorsofpadusingget import *
from .listauthorsofpadusingpost import *
from .listpadsofauthorusingget import *
from .listpadsofauthorusingpost import *
from .listpadsusingget import *
from .listpadsusingpost import *
from .listsavedrevisionsusingget import *
from .listsavedrevisionsusingpost import *
from .listsessionsofauthorusingget import *
from .listsessionsofauthorusingpost import *
from .listsessionsofgroupusingget import *
from .listsessionsofgroupusingpost import *
from .movepadusingget import *
from .movepadusingpost import *
from .paduserscountusingget import *
from .paduserscountusingpost import *
from .padusersusingget import *
from .padusersusingpost import *
from .restorerevisionusingget import *
from .restorerevisionusingpost import *
from .saverevisionusingget import *
from .saverevisionusingpost import *
from .sendclientsmessageusingget import *
from .sendclientsmessageusingpost import *
from .sethtmlusingget import *
from .sethtmlusingpost import *
from .setpublicstatususingget import *
from .setpublicstatususingpost import *
from .settextusingget import *
from .settextusingpost import *
