package shared

type Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnum string

const (
	Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnumEnableBackups  Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnum = "enable_backups"
	Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnumDisableBackups Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnum = "disable_backups"
	Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnumReboot         Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnum = "reboot"
	Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnumPowerCycle     Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnum = "power_cycle"
	Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnumShutdown       Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnum = "shutdown"
	Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnumPowerOff       Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnum = "power_off"
	Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnumPowerOn        Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnum = "power_on"
	Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnumRestore        Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnum = "restore"
	Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnumPasswordReset  Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnum = "password_reset"
	Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnumResize         Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnum = "resize"
	Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnumRebuild        Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnum = "rebuild"
	Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnumRename         Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnum = "rename"
	Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnumChangeKernel   Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnum = "change_kernel"
	Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnumEnableIpv6     Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnum = "enable_ipv6"
	Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnumSnapshot       Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnum = "snapshot"
)

type Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6 struct {
	Name *string                                                                                                      `json:"name"`
	Type Onev21droplets1Percent7BdropletIDPercent7D1actionsPostRequestBodyContentApplication1jsonSchemaAnyOf6TypeEnum `json:"type"`
}
