from .proximitybeacon_beaconinfo_getforobserved import *
from .proximitybeacon_beacons_activate import *
from .proximitybeacon_beacons_attachments_batchdelete import *
from .proximitybeacon_beacons_attachments_create import *
from .proximitybeacon_beacons_attachments_delete import *
from .proximitybeacon_beacons_attachments_list import *
from .proximitybeacon_beacons_deactivate import *
from .proximitybeacon_beacons_decommission import *
from .proximitybeacon_beacons_delete import *
from .proximitybeacon_beacons_diagnostics_list import *
from .proximitybeacon_beacons_get import *
from .proximitybeacon_beacons_list import *
from .proximitybeacon_beacons_register import *
from .proximitybeacon_beacons_update import *
from .proximitybeacon_geteidparams import *
from .proximitybeacon_namespaces_list import *
from .proximitybeacon_namespaces_update import *
