openapi: 3.0.0
servers:
  - url: https://script.googleapis.com/
info:
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: "Manages and executes Google Apps Script projects. "
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Apps Script API
  version: v1
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png
  x-origin:
    - converter:
        url: https://github.com/mermade/oas-kit
        version: 7.0.4
      format: google
      url: https://script.googleapis.com/$discovery/rest?version=v1
      version: v1
  x-providerName: googleapis.com
  x-serviceName: script
tags:
  - name: processes
  - name: projects
  - name: scripts
paths:
  /v1/processes:
    get:
      description: List information about processes made by or on behalf of a user, such as process type and current status.
      operationId: script.processes.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/script.processes
          Oauth2c:
            - https://www.googleapis.com/auth/script.processes
      tags:
        - processes
  /v1/processes:listScriptProcesses:
    get:
      description: List information about a script's executed processes, such as process type and current status.
      operationId: script.processes.listScriptProcesses
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/script.processes
          Oauth2c:
            - https://www.googleapis.com/auth/script.processes
      tags:
        - processes
  /v1/projects:
    post:
      description: Creates a new, empty script project with no script files and a base manifest file.
      operationId: script.projects.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/script.projects
          Oauth2c:
            - https://www.googleapis.com/auth/script.projects
      tags:
        - projects
  "/v1/projects/{scriptId}":
    get:
      description: Gets a script project's metadata.
      operationId: script.projects.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/script.projects
          Oauth2c:
            - https://www.googleapis.com/auth/script.projects
        - Oauth2:
            - https://www.googleapis.com/auth/script.projects.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/script.projects.readonly
      tags:
        - projects
  "/v1/projects/{scriptId}/content":
    get:
      description: Gets the content of the script project, including the code source and metadata for each script file.
      operationId: script.projects.getContent
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/script.projects
          Oauth2c:
            - https://www.googleapis.com/auth/script.projects
        - Oauth2:
            - https://www.googleapis.com/auth/script.projects.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/script.projects.readonly
      tags:
        - projects
    put:
      description: Updates the content of the specified script project. This content is stored as the HEAD version, and is used when the script is executed as a trigger, in the script editor, in add-on preview mode, or as a web app or Apps Script API in development mode. This clears all the existing files in the project.
      operationId: script.projects.updateContent
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/script.projects
          Oauth2c:
            - https://www.googleapis.com/auth/script.projects
      tags:
        - projects
  "/v1/projects/{scriptId}/deployments":
    get:
      description: Lists the deployments of an Apps Script project.
      operationId: script.projects.deployments.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/script.deployments
          Oauth2c:
            - https://www.googleapis.com/auth/script.deployments
        - Oauth2:
            - https://www.googleapis.com/auth/script.deployments.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/script.deployments.readonly
      tags:
        - projects
    post:
      description: Creates a deployment of an Apps Script project.
      operationId: script.projects.deployments.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/script.deployments
          Oauth2c:
            - https://www.googleapis.com/auth/script.deployments
      tags:
        - projects
  "/v1/projects/{scriptId}/deployments/{deploymentId}":
    delete:
      description: Deletes a deployment of an Apps Script project.
      operationId: script.projects.deployments.delete
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/script.deployments
          Oauth2c:
            - https://www.googleapis.com/auth/script.deployments
      tags:
        - projects
    get:
      description: Gets a deployment of an Apps Script project.
      operationId: script.projects.deployments.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/script.deployments
          Oauth2c:
            - https://www.googleapis.com/auth/script.deployments
        - Oauth2:
            - https://www.googleapis.com/auth/script.deployments.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/script.deployments.readonly
      tags:
        - projects
    put:
      description: Updates a deployment of an Apps Script project.
      operationId: script.projects.deployments.update
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/script.deployments
          Oauth2c:
            - https://www.googleapis.com/auth/script.deployments
      tags:
        - projects
  "/v1/projects/{scriptId}/metrics":
    get:
      description: Get metrics data for scripts, such as number of executions and active users.
      operationId: script.projects.getMetrics
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/script.metrics
          Oauth2c:
            - https://www.googleapis.com/auth/script.metrics
      tags:
        - projects
  "/v1/projects/{scriptId}/versions":
    get:
      description: List the versions of a script project.
      operationId: script.projects.versions.list
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/script.projects
          Oauth2c:
            - https://www.googleapis.com/auth/script.projects
        - Oauth2:
            - https://www.googleapis.com/auth/script.projects.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/script.projects.readonly
      tags:
        - projects
    post:
      description: Creates a new immutable version using the current code, with a unique version number.
      operationId: script.projects.versions.create
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/script.projects
          Oauth2c:
            - https://www.googleapis.com/auth/script.projects
      tags:
        - projects
  "/v1/projects/{scriptId}/versions/{versionNumber}":
    get:
      description: Gets a version of a script project.
      operationId: script.projects.versions.get
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/script.projects
          Oauth2c:
            - https://www.googleapis.com/auth/script.projects
        - Oauth2:
            - https://www.googleapis.com/auth/script.projects.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/script.projects.readonly
      tags:
        - projects
  "/v1/scripts/{scriptId}:run":
    post:
      description: 'Runs a function in an Apps Script project. The script project must be deployed for use with the Apps Script API and the calling application must share the same Cloud Platform project. This method requires authorization with an OAuth 2.0 token that includes at least one of the scopes listed in the [Authorization](#authorization-scopes) section; script projects that do not require authorization cannot be executed through this API. To find the correct scopes to include in the au[...]'
      operationId: script.scripts.run
      security:
        - Oauth2:
            - https://mail.google.com/
          Oauth2c:
            - https://mail.google.com/
        - Oauth2:
            - https://www.google.com/calendar/feeds
          Oauth2c:
            - https://www.google.com/calendar/feeds
        - Oauth2:
            - https://www.google.com/m8/feeds
          Oauth2c:
            - https://www.google.com/m8/feeds
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.group
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.group
        - Oauth2:
            - https://www.googleapis.com/auth/admin.directory.user
          Oauth2c:
            - https://www.googleapis.com/auth/admin.directory.user
        - Oauth2:
            - https://www.googleapis.com/auth/documents
          Oauth2c:
            - https://www.googleapis.com/auth/documents
        - Oauth2:
            - https://www.googleapis.com/auth/drive
          Oauth2c:
            - https://www.googleapis.com/auth/drive
        - Oauth2:
            - https://www.googleapis.com/auth/forms
          Oauth2c:
            - https://www.googleapis.com/auth/forms
        - Oauth2:
            - https://www.googleapis.com/auth/forms.currentonly
          Oauth2c:
            - https://www.googleapis.com/auth/forms.currentonly
        - Oauth2:
            - https://www.googleapis.com/auth/groups
          Oauth2c:
            - https://www.googleapis.com/auth/groups
        - Oauth2:
            - https://www.googleapis.com/auth/spreadsheets
          Oauth2c:
            - https://www.googleapis.com/auth/spreadsheets
        - Oauth2:
            - https://www.googleapis.com/auth/userinfo.email
          Oauth2c:
            - https://www.googleapis.com/auth/userinfo.email
      tags:
        - scripts
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://mail.google.com/: Read, compose, send, and permanently delete all your email from Gmail
            https://www.google.com/calendar/feeds: See, edit, share, and permanently delete all the calendars you can access using Google Calendar
            https://www.google.com/m8/feeds: See, edit, download, and permanently delete your contacts
            https://www.googleapis.com/auth/admin.directory.group: View and manage the provisioning of groups on your domain
            https://www.googleapis.com/auth/admin.directory.user: View and manage the provisioning of users on your domain
            https://www.googleapis.com/auth/documents: See, edit, create, and delete all your Google Docs documents
            https://www.googleapis.com/auth/drive: See, edit, create, and delete all of your Google Drive files
            https://www.googleapis.com/auth/forms: View and manage your forms in Google Drive
            https://www.googleapis.com/auth/forms.currentonly: View and manage forms that this application has been installed in
            https://www.googleapis.com/auth/groups: View and manage your Google Groups
            https://www.googleapis.com/auth/script.deployments: Create and update Google Apps Script deployments
            https://www.googleapis.com/auth/script.deployments.readonly: View Google Apps Script deployments
            https://www.googleapis.com/auth/script.metrics: View Google Apps Script project's metrics
            https://www.googleapis.com/auth/script.processes: View Google Apps Script processes
            https://www.googleapis.com/auth/script.projects: Create and update Google Apps Script projects
            https://www.googleapis.com/auth/script.projects.readonly: View Google Apps Script projects
            https://www.googleapis.com/auth/spreadsheets: See, edit, create, and delete all your Google Sheets spreadsheets
            https://www.googleapis.com/auth/userinfo.email: See your primary Google Account email address
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://mail.google.com/: Read, compose, send, and permanently delete all your email from Gmail
            https://www.google.com/calendar/feeds: See, edit, share, and permanently delete all the calendars you can access using Google Calendar
            https://www.google.com/m8/feeds: See, edit, download, and permanently delete your contacts
            https://www.googleapis.com/auth/admin.directory.group: View and manage the provisioning of groups on your domain
            https://www.googleapis.com/auth/admin.directory.user: View and manage the provisioning of users on your domain
            https://www.googleapis.com/auth/documents: See, edit, create, and delete all your Google Docs documents
            https://www.googleapis.com/auth/drive: See, edit, create, and delete all of your Google Drive files
            https://www.googleapis.com/auth/forms: View and manage your forms in Google Drive
            https://www.googleapis.com/auth/forms.currentonly: View and manage forms that this application has been installed in
            https://www.googleapis.com/auth/groups: View and manage your Google Groups
            https://www.googleapis.com/auth/script.deployments: Create and update Google Apps Script deployments
            https://www.googleapis.com/auth/script.deployments.readonly: View Google Apps Script deployments
            https://www.googleapis.com/auth/script.metrics: View Google Apps Script project's metrics
            https://www.googleapis.com/auth/script.processes: View Google Apps Script processes
            https://www.googleapis.com/auth/script.projects: Create and update Google Apps Script projects
            https://www.googleapis.com/auth/script.projects.readonly: View Google Apps Script projects
            https://www.googleapis.com/auth/spreadsheets: See, edit, create, and delete all your Google Sheets spreadsheets
            https://www.googleapis.com/auth/userinfo.email: See your primary Google Account email address
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
