

export enum UpdateParamTypeEnum {
    Version = "Version"
,    PlatformVersion = "PlatformVersion"
,    EndpointPrivateAccess = "EndpointPrivateAccess"
,    EndpointPublicAccess = "EndpointPublicAccess"
,    ClusterLogging = "ClusterLogging"
,    DesiredSize = "DesiredSize"
,    LabelsToAdd = "LabelsToAdd"
,    LabelsToRemove = "LabelsToRemove"
,    TaintsToAdd = "TaintsToAdd"
,    TaintsToRemove = "TaintsToRemove"
,    MaxSize = "MaxSize"
,    MinSize = "MinSize"
,    ReleaseVersion = "ReleaseVersion"
,    PublicAccessCidrs = "PublicAccessCidrs"
,    LaunchTemplateName = "LaunchTemplateName"
,    LaunchTemplateVersion = "LaunchTemplateVersion"
,    IdentityProviderConfig = "IdentityProviderConfig"
,    EncryptionConfig = "EncryptionConfig"
,    AddonVersion = "AddonVersion"
,    ServiceAccountRoleArn = "ServiceAccountRoleArn"
,    ResolveConflicts = "ResolveConflicts"
,    MaxUnavailable = "MaxUnavailable"
,    MaxUnavailablePercentage = "MaxUnavailablePercentage"
}
