openapi: 3.0.0
servers:
  - url: https://api.netatmo.net/api
info:
  contact:
    email: contact-api@netatmo.com
    name: Netatmo
  description: |
    <h3>Welcome to the Netatmo swagger on-line documentation !</h3>
    This site is a complement to the official <a href="https://dev.netatmo.com/">Netatmo developper documentation</a> using swagger to bring interactivity and easy testing of requests with the "try it" button (authenticate with the authorization code OAuth2 flow by clicking the authenticate button in the methods). You can find the source code for this site can be found in the project <a href="https://github.com/cbornet/netatmo-swagger-ui">netatmo-swagger-ui</a>. You can also use the online <a hr[...]
  license:
    name: "Netatmo : Terms of Service"
    url: https://dev.netatmo.com/dev/resources/legal/introduction
  termsOfService: https://dev.netatmo.com/dev/resources/legal/introduction
  title: Netatmo
  version: 1.1.5
  x-apiClientRegistration:
    url: https://dev.netatmo.com/dev/createanapp
  x-apisguru-categories:
    - iot
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_netatmo_profile_image.jpeg
  x-origin:
    - format: openapi
      url: https://raw.githubusercontent.com/cbornet/netatmo-swagger-decl/master/spec/swagger.yaml
      version: "3.0"
  x-providerName: netatmo.net
  x-unofficialSpec: true
tags:
  - description: Weather station specific methods
    name: station
  - description: Healthy Home Coach specific methods
    name: healthyhomecoach
  - description: Thermostat specific methods
    name: thermostat
  - description: Welcome specific methods
    name: welcome
  - description: Public stations specific methods
    name: public
  - description: Partner API specific methods
    name: partner
  - description: These methods are no longer maintained nor supported
    name: deprecated
paths:
  /addwebhook:
    get:
      description: |
        Links a callback url to a user.
      operationId: addwebhook
      security:
        - code_oauth: []
        - password_oauth: []
      tags:
        - welcome
  /createnewschedule:
    post:
      description: The method createnewschedule creates a new schedule stored in the backup list.
      operationId: createnewschedule
      security:
        - code_oauth:
            - write_thermostat
        - password_oauth:
            - write_thermostat
      tags:
        - thermostat
  /devicelist:
    get:
      deprecated: true
      description: |
        The method devicelist returns the list of devices owned by the user, and their modules.
        A device is identified by its _id (which is its mac address) and each device may have one, several or no modules, also identified by an _id.
      operationId: devicelist
      security:
        - code_oauth:
            - read_thermostat
            - read_station
        - password_oauth:
            - read_thermostat
            - read_station
      tags:
        - deprecated
  /dropwebhook:
    get:
      description: |
        Dissociates a webhook from a user.
      operationId: dropwebhook
      security:
        - code_oauth: []
        - password_oauth: []
      tags:
        - welcome
  /getcamerapicture:
    get:
      description: |
        Returns the snapshot associated to an event.
      operationId: getcamerapicture
      security:
        - code_oauth: []
        - password_oauth: []
      tags:
        - welcome
  /geteventsuntil:
    get:
      description: |
        Returns the snapshot associated to an event.
      operationId: geteventsuntil
      security:
        - code_oauth:
            - access_camera
            - read_camera
        - password_oauth:
            - access_camera
            - read_camera
      tags:
        - welcome
  /gethomecoachsdata:
    get:
      description: The method gethomecoachsdata Returns data from a user Healthy Home Coach Station (measures and device specific data).
      operationId: gethomecoachsdata
      security:
        - code_oauth:
            - read_homecoach
        - password_oauth:
            - read_homecoach
      tags:
        - healthyhomecoach
  /gethomedata:
    get:
      description: |
        Returns information about users homes and cameras.
      operationId: gethomedata
      security:
        - code_oauth:
            - access_camera
            - read_camera
        - password_oauth:
            - access_camera
            - read_camera
      tags:
        - welcome
  /getlasteventof:
    get:
      description: |
        Returns most recent events.
      operationId: getlasteventof
      security:
        - code_oauth:
            - access_camera
            - read_camera
        - password_oauth:
            - access_camera
            - read_camera
      tags:
        - welcome
  /getmeasure:
    get:
      description: |
        The method getmeasure returns the measurements of a device or a module.
      operationId: getmeasure
      security:
        - code_oauth:
            - read_thermostat
            - read_station
        - password_oauth:
            - read_thermostat
            - read_station
      tags:
        - station
        - thermostat
        - partner
        - public
  /getnextevents:
    get:
      description: |
        Returns previous events.
      operationId: getnextevents
      security:
        - code_oauth:
            - access_camera
            - read_camera
        - password_oauth:
            - access_camera
            - read_camera
      tags:
        - welcome
  /getpublicdata:
    get:
      description: Retrieves publicly shared weather data from Outdoor Modules within a predefined area.
      operationId: getpublicdata
      security:
        - code_oauth: []
        - password_oauth: []
      tags:
        - public
  /getstationsdata:
    get:
      description: The method getstationsdata Returns data from a user's Weather Stations (measures and device specific data).
      operationId: getstationsdata
      security:
        - code_oauth:
            - read_station
        - password_oauth:
            - read_station
      tags:
        - station
  /getthermostatsdata:
    get:
      description: The method getthermostatsdata returns information about user's thermostats such as their last measurements.
      operationId: getthermostatsdata
      security:
        - code_oauth:
            - read_thermostat
        - password_oauth:
            - read_thermostat
      tags:
        - thermostat
  /getthermstate:
    get:
      deprecated: true
      description: The method getthermstate returns the last Thermostat measurements, its current weekly schedule, and, if present, its current manual temperature setpoint.
      operationId: getthermstate
      security:
        - code_oauth:
            - read_thermostat
        - password_oauth:
            - read_thermostat
      tags:
        - deprecated
  /getuser:
    get:
      deprecated: true
      description: |
        The method getuser returns information about a user such as prefered language, prefered units, and list of devices.
      operationId: getuser
      security:
        - code_oauth: []
        - password_oauth: []
      tags:
        - deprecated
  /partnerdevices:
    get:
      description: The method partnerdevices returns the list of device_id to which your partner application has access to.
      operationId: partnerdevices
      security:
        - code_oauth: []
        - password_oauth: []
      tags:
        - partner
  /setpersonsaway:
    post:
      description: |
        Sets a person as 'Away' or the Home as 'Empty'. The event will be added to the user’s timeline.
      operationId: setpersonsaway
      security:
        - code_oauth:
            - write_camera
        - password_oauth:
            - write_camera
      tags:
        - welcome
  /setpersonshome:
    post:
      description: |
        Sets a person as 'At home'.
      operationId: setpersonshome
      security:
        - code_oauth:
            - write_camera
        - password_oauth:
            - write_camera
      tags:
        - welcome
  /setthermpoint:
    post:
      description: The method setthermpoint changes the Thermostat manual temperature setpoint.
      operationId: setthermpoint
      security:
        - code_oauth:
            - write_thermostat
        - password_oauth:
            - write_thermostat
      tags:
        - thermostat
  /switchschedule:
    post:
      description: The method switchschedule switches the Thermostat's schedule to another existing schedule.
      operationId: switchschedule
      security:
        - code_oauth:
            - write_thermostat
        - password_oauth:
            - write_thermostat
      tags:
        - thermostat
  /syncschedule:
    post:
      description: The method syncschedule changes the Thermostat weekly schedule.
      operationId: syncschedule
      security:
        - code_oauth:
            - write_thermostat
        - password_oauth:
            - write_thermostat
      tags:
        - thermostat
components:
  securitySchemes:
    code_oauth:
      flows:
        authorizationCode:
          authorizationUrl: https://api.netatmo.net/oauth2/authorize
          scopes:
            access_camera: Access welcome camera
            read_camera: Read welcome camera's data
            read_homecoach: Read data coming from Healthy Home Coach
            read_station: Read weather station's data
            read_thermostat: Read thermostat's data
            write_camera: Write welcome camera's data
            write_thermostat: Configure the thermostat
          tokenUrl: https://api.netatmo.net/oauth2/token
      type: oauth2
    password_oauth:
      flows:
        password:
          scopes:
            access_camera: Access welcome camera
            read_camera: Read welcome camera's data
            read_homecoach: Read data coming from Healthy Home Coach
            read_station: Read weather station's data
            read_thermostat: Read thermostat's data
            write_camera: Write welcome camera's data
            write_thermostat: Configure the thermostat
          tokenUrl: https://api.netatmo.net/oauth2/token
      type: oauth2
