swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /mirror/v1
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Interacts with Glass users via the timeline.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Google Mirror
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/mirror/v1/rest'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: mirror
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/glass.location': View your location
      'https://www.googleapis.com/auth/glass.timeline': View and manage your Glass timeline
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/glass.location': View your location
      'https://www.googleapis.com/auth/glass.timeline': View and manage your Glass timeline
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: accounts
  - name: contacts
  - name: locations
  - name: settings
  - name: subscriptions
  - name: timeline
paths:
  '/accounts/{userToken}/{accountType}/{accountName}':
    post:
      description: Inserts a new account for a user
      operationId: mirror.accounts.insert
      tags:
        - accounts
  /contacts:
    get:
      description: Retrieves a list of contacts for the authenticated user.
      operationId: mirror.contacts.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - contacts
    post:
      description: Inserts a new contact.
      operationId: mirror.contacts.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - contacts
  '/contacts/{id}':
    delete:
      description: Deletes a contact.
      operationId: mirror.contacts.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - contacts
    get:
      description: Gets a single contact by ID.
      operationId: mirror.contacts.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - contacts
    patch:
      description: Updates a contact in place. This method supports patch semantics.
      operationId: mirror.contacts.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - contacts
    put:
      description: Updates a contact in place.
      operationId: mirror.contacts.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - contacts
  /locations:
    get:
      description: Retrieves a list of locations for the user.
      operationId: mirror.locations.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.location'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.location'
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - locations
  '/locations/{id}':
    get:
      description: Gets a single location by ID.
      operationId: mirror.locations.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.location'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.location'
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - locations
  '/settings/{id}':
    get:
      description: Gets a single setting by ID.
      operationId: mirror.settings.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - settings
  /subscriptions:
    get:
      description: Retrieves a list of subscriptions for the authenticated user and service.
      operationId: mirror.subscriptions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - subscriptions
    post:
      description: Creates a new subscription.
      operationId: mirror.subscriptions.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - subscriptions
  '/subscriptions/{id}':
    delete:
      description: Deletes a subscription.
      operationId: mirror.subscriptions.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - subscriptions
    put:
      description: Updates an existing subscription in place.
      operationId: mirror.subscriptions.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - subscriptions
  /timeline:
    get:
      description: Retrieves a list of timeline items for the authenticated user.
      operationId: mirror.timeline.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.location'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.location'
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - timeline
    post:
      description: Inserts a new item into the timeline.
      operationId: mirror.timeline.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.location'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.location'
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - timeline
  '/timeline/{id}':
    delete:
      description: Deletes a timeline item.
      operationId: mirror.timeline.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.location'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.location'
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - timeline
    get:
      description: Gets a single timeline item by ID.
      operationId: mirror.timeline.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.location'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.location'
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - timeline
    patch:
      description: Updates a timeline item in place. This method supports patch semantics.
      operationId: mirror.timeline.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.location'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.location'
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - timeline
    put:
      description: Updates a timeline item in place.
      operationId: mirror.timeline.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.location'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.location'
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - timeline
  '/timeline/{itemId}/attachments':
    get:
      description: Returns a list of attachments for a timeline item.
      operationId: mirror.timeline.attachments.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - timeline
    post:
      description: Adds a new attachment to a timeline item.
      operationId: mirror.timeline.attachments.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - timeline
  '/timeline/{itemId}/attachments/{attachmentId}':
    delete:
      description: Deletes an attachment from a timeline item.
      operationId: mirror.timeline.attachments.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - timeline
    get:
      description: Retrieves an attachment on a timeline item by item ID and attachment ID.
      operationId: mirror.timeline.attachments.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/glass.timeline'
          Oauth2c:
            - 'https://www.googleapis.com/auth/glass.timeline'
      tags:
        - timeline