{
  "openapi": "3.0.0",
  "servers": [
    {
      "url": "https://people.googleapis.com/"
    }
  ],
  "info": {
    "contact": {
      "name": "Google",
      "url": "https://google.com",
      "x-twitter": "youtube"
    },
    "description": "Provides access to information about profiles and contacts.",
    "license": {
      "name": "Creative Commons Attribution 3.0",
      "url": "http://creativecommons.org/licenses/by/3.0/"
    },
    "termsOfService": "https://developers.google.com/terms/",
    "title": "People API",
    "version": "v1",
    "x-apiClientRegistration": {
      "url": "https://console.developers.google.com"
    },
    "x-apisguru-categories": [
      "analytics",
      "media"
    ],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png"
    },
    "x-origin": [
      {
        "converter": {
          "url": "https://github.com/mermade/oas-kit",
          "version": "7.0.4"
        },
        "format": "google",
        "url": "https://people.googleapis.com/$discovery/rest?version=v1",
        "version": "v1"
      }
    ],
    "x-providerName": "googleapis.com",
    "x-serviceName": "people"
  },
  "tags": [
    {
      "name": "contactGroups"
    },
    {
      "name": "otherContacts"
    },
    {
      "name": "people"
    }
  ],
  "paths": {
    "/v1/contactGroups": {
      "get": {
        "description": "List all contact groups owned by the authenticated user. Members of the contact groups are not populated.",
        "operationId": "people.contactGroups.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts.readonly"
            ]
          }
        ],
        "tags": [
          "contactGroups"
        ]
      },
      "post": {
        "description": "Create a new contact group owned by the authenticated user. Created contact group names must be unique to the users contact groups. Attempting to create a group with a duplicate name will return a HTTP 409 error. Mutate requests for the same user should be sent sequentially to avoid increased latency and failures.",
        "operationId": "people.contactGroups.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts"
            ]
          }
        ],
        "tags": [
          "contactGroups"
        ]
      }
    },
    "/v1/contactGroups:batchGet": {
      "get": {
        "description": "Get a list of contact groups owned by the authenticated user by specifying a list of contact group resource names.",
        "operationId": "people.contactGroups.batchGet",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts.readonly"
            ]
          }
        ],
        "tags": [
          "contactGroups"
        ]
      }
    },
    "/v1/otherContacts": {
      "get": {
        "description": "List all \"Other contacts\", that is contacts that are not in a contact group. \"Other contacts\" are typically auto created contacts from interactions. Sync tokens expire 7 days after the full sync. A request with an expired sync token will get an error with an [google.rpc.ErrorInfo](https://cloud.google.com/apis/design/errors#error_info) with reason \"EXPIRED_SYNC_TOKEN\". In the case of such an error clients should make a full sync request without a `sync_token`. The f[...]",
        "operationId": "people.otherContacts.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts.other.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts.other.readonly"
            ]
          }
        ],
        "tags": [
          "otherContacts"
        ]
      }
    },
    "/v1/otherContacts:search": {
      "get": {
        "description": "Provides a list of contacts in the authenticated user's other contacts that matches the search query. The query matches on a contact's `names`, `emailAddresses`, and `phoneNumbers` fields that are from the OTHER_CONTACT source. **IMPORTANT**: Before searching, clients should send a warmup request with an empty query to update the cache. See https://developers.google.com/people/v1/other-contacts#search_the_users_other_contacts",
        "operationId": "people.otherContacts.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts.other.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts.other.readonly"
            ]
          }
        ],
        "tags": [
          "otherContacts"
        ]
      }
    },
    "/v1/people:batchCreateContacts": {
      "post": {
        "description": "Create a batch of new contacts and return the PersonResponses for the newly Mutate requests for the same user should be sent sequentially to avoid increased latency and failures.",
        "operationId": "people.people.batchCreateContacts",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts"
            ]
          }
        ],
        "tags": [
          "people"
        ]
      }
    },
    "/v1/people:batchDeleteContacts": {
      "post": {
        "description": "Delete a batch of contacts. Any non-contact data will not be deleted. Mutate requests for the same user should be sent sequentially to avoid increased latency and failures.",
        "operationId": "people.people.batchDeleteContacts",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts"
            ]
          }
        ],
        "tags": [
          "people"
        ]
      }
    },
    "/v1/people:batchGet": {
      "get": {
        "description": "Provides information about a list of specific people by specifying a list of requested resource names. Use `people/me` to indicate the authenticated user. The request returns a 400 error if 'personFields' is not specified.",
        "operationId": "people.people.getBatchGet",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/directory.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/directory.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/user.addresses.read"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/user.addresses.read"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/user.birthday.read"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/user.birthday.read"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/user.emails.read"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/user.emails.read"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/user.gender.read"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/user.gender.read"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/user.organization.read"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/user.organization.read"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/user.phonenumbers.read"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/user.phonenumbers.read"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/userinfo.email"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/userinfo.email"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/userinfo.profile"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/userinfo.profile"
            ]
          }
        ],
        "tags": [
          "people"
        ]
      }
    },
    "/v1/people:batchUpdateContacts": {
      "post": {
        "description": "Update a batch of contacts and return a map of resource names to PersonResponses for the updated contacts. Mutate requests for the same user should be sent sequentially to avoid increased latency and failures.",
        "operationId": "people.people.batchUpdateContacts",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts"
            ]
          }
        ],
        "tags": [
          "people"
        ]
      }
    },
    "/v1/people:createContact": {
      "post": {
        "description": "Create a new contact and return the person resource for that contact. The request returns a 400 error if more than one field is specified on a field that is a singleton for contact sources: * biographies * birthdays * genders * names Mutate requests for the same user should be sent sequentially to avoid increased latency and failures.",
        "operationId": "people.people.createContact",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts"
            ]
          }
        ],
        "tags": [
          "people"
        ]
      }
    },
    "/v1/people:listDirectoryPeople": {
      "get": {
        "description": "Provides a list of domain profiles and domain contacts in the authenticated user's domain directory. When the `sync_token` is specified, resources deleted since the last sync will be returned as a person with `PersonMetadata.deleted` set to true. When the `page_token` or `sync_token` is specified, all other request parameters must match the first call. Writes may have a propagation delay of several minutes for sync requests. Incremental syncs are not intended for read-aft[...]",
        "operationId": "people.people.listDirectoryPeople",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/directory.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/directory.readonly"
            ]
          }
        ],
        "tags": [
          "people"
        ]
      }
    },
    "/v1/people:searchContacts": {
      "get": {
        "description": "Provides a list of contacts in the authenticated user's grouped contacts that matches the search query. The query matches on a contact's `names`, `nickNames`, `emailAddresses`, `phoneNumbers`, and `organizations` fields that are from the CONTACT source. **IMPORTANT**: Before searching, clients should send a warmup request with an empty query to update the cache. See https://developers.google.com/people/v1/contacts#search_the_users_contacts",
        "operationId": "people.people.searchContacts",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts.readonly"
            ]
          }
        ],
        "tags": [
          "people"
        ]
      }
    },
    "/v1/people:searchDirectoryPeople": {
      "get": {
        "description": "Provides a list of domain profiles and domain contacts in the authenticated user's domain directory that match the search query.",
        "operationId": "people.people.searchDirectoryPeople",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/directory.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/directory.readonly"
            ]
          }
        ],
        "tags": [
          "people"
        ]
      }
    },
    "/v1/{resourceName}": {
      "delete": {
        "description": "Delete an existing contact group owned by the authenticated user by specifying a contact group resource name. Mutate requests for the same user should be sent sequentially to avoid increased latency and failures.",
        "operationId": "people.contactGroups.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts"
            ]
          }
        ],
        "tags": [
          "contactGroups"
        ]
      },
      "get": {
        "description": "Provides information about a person by specifying a resource name. Use `people/me` to indicate the authenticated user. The request returns a 400 error if 'personFields' is not specified.",
        "operationId": "people.people.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/directory.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/directory.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/user.addresses.read"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/user.addresses.read"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/user.birthday.read"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/user.birthday.read"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/user.emails.read"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/user.emails.read"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/user.gender.read"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/user.gender.read"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/user.organization.read"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/user.organization.read"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/user.phonenumbers.read"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/user.phonenumbers.read"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/userinfo.email"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/userinfo.email"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/userinfo.profile"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/userinfo.profile"
            ]
          }
        ],
        "tags": [
          "people"
        ]
      },
      "put": {
        "description": "Update the name of an existing contact group owned by the authenticated user. Updated contact group names must be unique to the users contact groups. Attempting to create a group with a duplicate name will return a HTTP 409 error. Mutate requests for the same user should be sent sequentially to avoid increased latency and failures.",
        "operationId": "people.contactGroups.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts"
            ]
          }
        ],
        "tags": [
          "contactGroups"
        ]
      }
    },
    "/v1/{resourceName}/connections": {
      "get": {
        "description": "Provides a list of the authenticated user's contacts. Sync tokens expire 7 days after the full sync. A request with an expired sync token will get an error with an [google.rpc.ErrorInfo](https://cloud.google.com/apis/design/errors#error_info) with reason \"EXPIRED_SYNC_TOKEN\". In the case of such an error clients should make a full sync request without a `sync_token`. The first page of a full sync request has an additional quota. If the quota is exceeded, a 429 error wil[...]",
        "operationId": "people.people.connections.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts.readonly"
            ]
          }
        ],
        "tags": [
          "people"
        ]
      }
    },
    "/v1/{resourceName}/members:modify": {
      "post": {
        "description": "Modify the members of a contact group owned by the authenticated user. The only system contact groups that can have members added are `contactGroups/myContacts` and `contactGroups/starred`. Other system contact groups are deprecated and can only have contacts removed.",
        "operationId": "people.contactGroups.members.modify",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts"
            ]
          }
        ],
        "tags": [
          "contactGroups"
        ]
      }
    },
    "/v1/{resourceName}:copyOtherContactToMyContactsGroup": {
      "post": {
        "description": "Copies an \"Other contact\" to a new contact in the user's \"myContacts\" group Mutate requests for the same user should be sent sequentially to avoid increased latency and failures.",
        "operationId": "people.otherContacts.copyOtherContactToMyContactsGroup",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts.other.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts.other.readonly"
            ]
          }
        ],
        "tags": [
          "otherContacts"
        ]
      }
    },
    "/v1/{resourceName}:deleteContact": {
      "delete": {
        "description": "Delete a contact person. Any non-contact data will not be deleted. Mutate requests for the same user should be sent sequentially to avoid increased latency and failures.",
        "operationId": "people.people.deleteContact",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts"
            ]
          }
        ],
        "tags": [
          "people"
        ]
      }
    },
    "/v1/{resourceName}:deleteContactPhoto": {
      "delete": {
        "description": "Delete a contact's photo. Mutate requests for the same user should be done sequentially to avoid // lock contention.",
        "operationId": "people.people.deleteContactPhoto",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts"
            ]
          }
        ],
        "tags": [
          "people"
        ]
      }
    },
    "/v1/{resourceName}:updateContact": {
      "patch": {
        "description": "Update contact data for an existing contact person. Any non-contact data will not be modified. Any non-contact data in the person to update will be ignored. All fields specified in the `update_mask` will be replaced. The server returns a 400 error if `person.metadata.sources` is not specified for the contact to be updated or if there is no contact source. The server returns a 400 error with reason `\"failedPrecondition\"` if `person.metadata.sources.etag` is different tha[...]",
        "operationId": "people.people.updateContact",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts"
            ]
          }
        ],
        "tags": [
          "people"
        ]
      }
    },
    "/v1/{resourceName}:updateContactPhoto": {
      "patch": {
        "description": "Update a contact's photo. Mutate requests for the same user should be sent sequentially to avoid increased latency and failures.",
        "operationId": "people.people.updateContactPhoto",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/contacts"
            ]
          }
        ],
        "tags": [
          "people"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Oauth2": {
        "description": "Oauth 2.0 implicit authentication",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
            "scopes": {
              "https://www.googleapis.com/auth/contacts": "See, edit, download, and permanently delete your contacts",
              "https://www.googleapis.com/auth/contacts.other.readonly": "See and download contact info automatically saved in your \"Other contacts\"",
              "https://www.googleapis.com/auth/contacts.readonly": "See and download your contacts",
              "https://www.googleapis.com/auth/directory.readonly": "See and download your organization's GSuite directory",
              "https://www.googleapis.com/auth/user.addresses.read": "View your street addresses",
              "https://www.googleapis.com/auth/user.birthday.read": "See and download your exact date of birth",
              "https://www.googleapis.com/auth/user.emails.read": "See and download all of your Google Account email addresses",
              "https://www.googleapis.com/auth/user.gender.read": "See your gender",
              "https://www.googleapis.com/auth/user.organization.read": "See your education, work history and org info",
              "https://www.googleapis.com/auth/user.phonenumbers.read": "See and download your personal phone numbers",
              "https://www.googleapis.com/auth/userinfo.email": "See your primary Google Account email address",
              "https://www.googleapis.com/auth/userinfo.profile": "See your personal info, including any personal info you've made publicly available"
            }
          }
        },
        "type": "oauth2"
      },
      "Oauth2c": {
        "description": "Oauth 2.0 authorizationCode authentication",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
            "scopes": {
              "https://www.googleapis.com/auth/contacts": "See, edit, download, and permanently delete your contacts",
              "https://www.googleapis.com/auth/contacts.other.readonly": "See and download contact info automatically saved in your \"Other contacts\"",
              "https://www.googleapis.com/auth/contacts.readonly": "See and download your contacts",
              "https://www.googleapis.com/auth/directory.readonly": "See and download your organization's GSuite directory",
              "https://www.googleapis.com/auth/user.addresses.read": "View your street addresses",
              "https://www.googleapis.com/auth/user.birthday.read": "See and download your exact date of birth",
              "https://www.googleapis.com/auth/user.emails.read": "See and download all of your Google Account email addresses",
              "https://www.googleapis.com/auth/user.gender.read": "See your gender",
              "https://www.googleapis.com/auth/user.organization.read": "See your education, work history and org info",
              "https://www.googleapis.com/auth/user.phonenumbers.read": "See and download your personal phone numbers",
              "https://www.googleapis.com/auth/userinfo.email": "See your primary Google Account email address",
              "https://www.googleapis.com/auth/userinfo.profile": "See your personal info, including any personal info you've made publicly available"
            },
            "tokenUrl": "https://accounts.google.com/o/oauth2/token"
          }
        },
        "type": "oauth2"
      }
    }
  }
}