package shared




type ServiceConversationParticipantEnumWebhookEnabledTypeEnum string

const (
    ServiceConversationParticipantEnumWebhookEnabledTypeEnumTrue ServiceConversationParticipantEnumWebhookEnabledTypeEnum = "true"
ServiceConversationParticipantEnumWebhookEnabledTypeEnumFalse ServiceConversationParticipantEnumWebhookEnabledTypeEnum = "false"
)


