package shared

type ServiceUserConversationEnumNotificationLevelEnum string

const (
	ServiceUserConversationEnumNotificationLevelEnumDefault ServiceUserConversationEnumNotificationLevelEnum = "default"
	ServiceUserConversationEnumNotificationLevelEnumMuted   ServiceUserConversationEnumNotificationLevelEnum = "muted"
)
