from .createfulfillmentpolicy import *
from .createorreplacesalestax import *
from .createpaymentpolicy import *
from .createreturnpolicy import *
from .deletefulfillmentpolicy import *
from .deletepaymentpolicy import *
from .deletereturnpolicy import *
from .deletesalestax import *
from .getfulfillmentpolicies import *
from .getfulfillmentpolicy import *
from .getfulfillmentpolicybyname import *
from .getkyc import *
from .getoptedinprograms import *
from .getpaymentpolicies import *
from .getpaymentpolicy import *
from .getpaymentpolicybyname import *
from .getpaymentsprogram import *
from .getpaymentsprogramonboarding import *
from .getprivileges import *
from .getratetables import *
from .getreturnpolicies import *
from .getreturnpolicy import *
from .getreturnpolicybyname import *
from .getsalestax import *
from .getsalestaxes import *
from .optintoprogram import *
from .optoutofprogram import *
from .updatefulfillmentpolicy import *
from .updatepaymentpolicy import *
from .updatereturnpolicy import *
