# coding: utf-8

"""
    VictorOps

    This API allows you to interact with the VictorOps platform in various ways. Your account may be limited to a total number of API calls per month. Also, some of these API calls have rate limits.  NOTE: In this documentation when creating a sample curl request (clicking the TRY IT OUT! button), in some API viewing interfaces, the '@' in an email address may be encoded. Please note that the REST endpoints will not process the encoded version. Make sure that the encoded character '%40' is changed to its unencoded form before submitting the curl request. 

    The version of the OpenAPI document: 0.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class NotificationDescription(str, Enum):
    """
    NotificationDescription
    """

    """
    allowed enum values
    """
    SEND_A_PUSH_NOTIFICATION_TO_ALL_MY_DEVICES = 'Send a push notification to all my devices'
    SEND_AN_EMAIL_TO_AN_EMAIL_ADDRESS = 'Send an email to an email address'
    SEND_AN_SMS_TO_A_PHONE_NUMBER = 'Send an SMS to a phone number'
    MAKE_A_PHONE_CALL_TO_A_PHONE_NUMBER = 'Make a phone call to a phone number'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NotificationDescription from a JSON string"""
        return cls(json.loads(json_str))


