from .get_decodeauthorizationmessage import *
from .get_getaccesskeyinfo import *
from .get_getcalleridentity import *
from .get_getsessiontoken import *
from .post_assumerole import *
from .post_assumerolewithsaml import *
from .post_assumerolewithwebidentity import *
from .post_decodeauthorizationmessage import *
from .post_getaccesskeyinfo import *
from .post_getcalleridentity import *
from .post_getfederationtoken import *
from .post_getsessiontoken import *
