swagger: '2.0'
schemes:
  - https
host: api.reverb.com
basePath: /api
x-hasEquivalentPaths: true
info:
  contact:
    email: integrations@reverb.com
    name: Reverb API
    url: 'https://www.reverb-api.com'
  description: reverb
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  termsOfService: 'https://reverb.com/page/terms'
  title: reverb
  version: '3.0'
  x-apisguru-categories:
    - ecommerce
  x-logo:
    url: 'https://d1g5417jjjo7sf.cloudfront.net/assets/top-level/reverb-logo-d2c75af0b020521f0bc5e90c883a13b5.svg'
  x-origin:
    - format: swagger
      url: 'https://s3.amazonaws.com/swagger.reverb.com/swagger.json'
      version: '2.0'
  x-providerName: reverb.com
securityDefinitions:
  oauth2:
    flow: application
    scopes:
      public: ''
      read_feedback: ''
      read_listings: ''
      read_lists: ''
      read_messages: ''
      read_offers: ''
      read_orders: ''
      read_payouts: ''
      read_profile: ''
      write_feedback: ''
      write_listings: ''
      write_lists: ''
      write_messages: ''
      write_offers: ''
      write_orders: ''
      write_profile: ''
      write_reviews: ''
    tokenUrl: 'https://reverb.com/oauth/token'
    type: oauth2
paths:
  /articles:
    get:
      tags:
        - articles
  /categories:
    get:
      description: List of supported product categories
      summary: List of supported product categories
      tags:
        - categories
  /categories/flat:
    get:
      tags:
        - categories
  /categories/taxonomy:
    get:
      description: Full taxonomy tree of categories including middle categories
      summary: Full taxonomy tree of categories including middle categories
      tags:
        - categories
  '/categories/{product_type}/{category}':
    get:
      description: Get subcategory details
      summary: Get subcategory details
      tags:
        - categories
  '/categories/{uuid}':
    get:
      description: Get category details
      summary: Get category details
      tags:
        - categories
  /comparison_shopping_pages:
    get:
      description: Returns a set of comparison shopping pages based on the current params
      summary: Returns a set of comparison shopping pages based on the current params
      tags:
        - comparison_shopping_pages
  /comparison_shopping_pages/find:
    get:
      description: Show comparison shopping page
      summary: Show comparison shopping page
      tags:
        - comparison_shopping_pages
  '/comparison_shopping_pages/{id}':
    get:
      tags:
        - comparison_shopping_pages
  '/comparison_shopping_pages/{id}/listings':
    get:
      description: Return new or used listings for a comparison shopping page
      summary: Return new or used listings for a comparison shopping page
      tags:
        - comparison_shopping_pages
  '/comparison_shopping_pages/{id}/reviews':
    get:
      description: View reviews of a comparison shopping page
      summary: View reviews of a comparison shopping page
      tags:
        - comparison_shopping_pages
  '/conversations/{conversation_id}/offer':
    post:
      description: Make an offer to the other participant in the conversation
      security:
        - oauth2:
            - write_offers
      summary: Make an offer to the other participant in the conversation
      tags:
        - conversations
  '/conversations/{id}/offer':
    post:
      description: Make an offer to the other participant in the conversation
      security:
        - oauth2:
            - write_offers
      summary: Make an offer to the other participant in the conversation
      tags:
        - conversations
  /countries:
    get:
      description: Retrieve a list of country codes with corresponding subregions
      summary: Retrieve a list of country codes with corresponding subregions
      tags:
        - countries
  '/curated_sets/{slug}':
    get:
      tags:
        - curated_sets
  /currencies/display:
    get:
      description: List of supported display currencies for browsing listings
      summary: List of supported display currencies for browsing listings
      tags:
        - currencies
  /currencies/listing:
    get:
      description: List of supported listing currencies for shops
      summary: List of supported listing currencies for shops
      tags:
        - currencies
  '/feedback/{feedback_id}':
    get:
      description: Feedback details
      summary: Feedback details
      tags:
        - feedback
  '/handpicked/{slug}':
    get:
      description: Get results from a handpicked collection
      summary: Get results from a handpicked collection
      tags:
        - handpicked
  /listing_conditions:
    get:
      description: List of supported product conditions
      summary: List of supported product conditions
      tags:
        - listing_conditions
  /listings:
    get:
      description: Default search of listings includes only used & handmade. Add a filter to view all listings or use the /listings/all endpoint.
      summary: Default search of listings includes only used & handmade. Add a filter to view all listings or use the /listings/all endpoint.
      tags:
        - listings
    post:
      description: Create a listing
      security:
        - oauth2:
            - write_listings
      summary: Create a listing
      tags:
        - listings
  /listings/all:
    get:
      description: 'All listings including used, handmade, and brand new'
      summary: 'All listings including used, handmade, and brand new'
      tags:
        - listings
  /listings/facets/seller_location:
    get:
      description: Individual facets
      summary: Individual facets
      tags:
        - listings
  '/listings/{id}/negotiation':
    get:
      description: Returns the latest negotiation for the requesting user given a listing id
      security:
        - oauth2:
            - read_offers
      summary: Returns the latest negotiation for the requesting user given a listing id
      tags:
        - listings
  '/listings/{id}/offer':
    post:
      description: Make an offer to the seller of a listing
      security:
        - oauth2:
            - write_offers
      summary: Make an offer to the seller of a listing
      tags:
        - listings
  '/listings/{listing_id}/bump':
    get:
      description: View available bump tiers and stats for a listing
      security:
        - oauth2:
            - read_listings
      summary: View available bump tiers and stats for a listing
      tags:
        - listings
  '/listings/{listing_id}/bump/{budget_type}':
    post:
      description: Bump a listing
      security:
        - oauth2:
            - write_listings
      summary: Bump a listing
      tags:
        - listings
  '/listings/{listing_id}/conversations':
    post:
      description: Start a conversation with a seller
      security:
        - oauth2:
            - write_messages
      summary: Start a conversation with a seller
      tags:
        - listings
  '/listings/{listing_id}/images':
    get:
      description: View the images associated with a particular listing
      security:
        - oauth2:
            - read_listings
      summary: View the images associated with a particular listing
      tags:
        - listings
  '/listings/{listing_id}/images/{image_id}':
    delete:
      description: Delete an image from a listing
      security:
        - oauth2:
            - write_listings
      summary: Delete an image from a listing
      tags:
        - listings
  '/listings/{listing_id}/product_bundle':
    get:
      description: Find a product bundle attached to a listing
      summary: Find a product bundle attached to a listing
      tags:
        - listings
  '/listings/{listing_id}/sales':
    get:
      description: See all sales that include a listing.
      summary: See all sales that include a listing.
      tags:
        - listings
  '/listings/{slug}':
    delete:
      description: Delete a draft listing. Cannot be used on non-drafts.
      security:
        - oauth2:
            - write_listings
      summary: Delete a draft listing. Cannot be used on non-drafts.
      tags:
        - listings
    get:
      description: Listing details
      summary: Listing details
      tags:
        - listings
    put:
      description: Update a listing
      security:
        - oauth2:
            - write_listings
      summary: Update a listing
      tags:
        - listings
  '/listings/{slug}/edit':
    get:
      description: Edit listing.
      security:
        - oauth2:
            - write_listings
      summary: Edit listing.
      tags:
        - listings
  '/listings/{slug}/flag':
    post:
      description: Flag a listing for inappropriate content or fraud
      summary: Flag a listing for inappropriate content or fraud
      tags:
        - listings
  '/listings/{slug}/reviews':
    get:
      description: View reviews of a listing
      summary: View reviews of a listing
      tags:
        - listings
    post:
      description: Create a review for a listing
      security:
        - oauth2:
            - write_reviews
      summary: Create a review for a listing
      tags:
        - listings
  '/listings/{slug}/similar_listings':
    get:
      description: Listing details
      summary: Listing details
      tags:
        - listings
  /my/account:
    get:
      description: Get account details
      security:
        - oauth2:
            - read_profile
      summary: Get account details
      tags:
        - my
    put:
      description: Update account details
      security:
        - oauth2:
            - write_profile
      summary: Update account details
      tags:
        - my
  /my/addresses:
    get:
      description: See all addresses in your address book
      security:
        - oauth2:
            - read_profile
      summary: See all addresses in your address book
      tags:
        - my
    post:
      description: Create a new address in your address book
      security:
        - oauth2:
            - write_profile
      summary: Create a new address in your address book
      tags:
        - my
  '/my/addresses/{address_id}':
    delete:
      description: Delete an existing address in your address book
      security:
        - oauth2:
            - write_profile
      summary: Delete an existing address in your address book
      tags:
        - my
    put:
      description: Update an existing address in your address book
      security:
        - oauth2:
            - write_profile
      summary: Update an existing address in your address book
      tags:
        - my
  /my/conversations:
    get:
      description: Get a list of your conversations
      security:
        - oauth2:
            - read_messages
      summary: Get a list of your conversations
      tags:
        - my
    post:
      description: Start a conversation
      security:
        - oauth2:
            - write_messages
      summary: Start a conversation
      tags:
        - my
  '/my/conversations/{conversation_id}/messages':
    post:
      description: Send a message
      security:
        - oauth2:
            - write_messages
      summary: Send a message
      tags:
        - my
  '/my/conversations/{id}':
    get:
      description: Display conversation details with messages in natural time order (oldest to newest)
      security:
        - oauth2:
            - read_messages
      summary: Display conversation details with messages in natural time order (oldest to newest)
      tags:
        - my
    put:
      description: Mark a conversation read/unread
      security:
        - oauth2:
            - write_messages
      summary: Mark a conversation read/unread
      tags:
        - my
  /my/counts:
    get:
      description: Get your actionable status counts
      security:
        - oauth2:
            - read_profile
      summary: Get your actionable status counts
      tags:
        - my
  '/my/curated_set/product/{product_id}':
    delete:
      tags:
        - my
    post:
      tags:
        - my
  /my/feed:
    get:
      description: Get listings from your feed
      security:
        - oauth2:
            - read_lists
      summary: Get listings from your feed
      tags:
        - my
  /my/feed/customize:
    get:
      description: get your feed customization options
      security:
        - oauth2:
            - read_lists
      summary: get your feed customization options
      tags:
        - my
  /my/feed/grid:
    get:
      description: get your feed
      security:
        - oauth2:
            - read_lists
      summary: get your feed
      tags:
        - my
  /my/feedback/received:
    get:
      description: List of received feedback
      security:
        - oauth2:
            - read_feedback
      summary: List of received feedback
      tags:
        - my
  /my/feedback/sent:
    get:
      description: List of sent feedback
      security:
        - oauth2:
            - read_feedback
      summary: List of sent feedback
      tags:
        - my
  /my/follows:
    get:
      description: See what the user is following
      security:
        - oauth2:
            - read_lists
      summary: See what the user is following
      tags:
        - my
  /my/follows/articles:
    get:
      description: Returns a user's ArticleCategoryFollows
      security:
        - oauth2:
            - read_lists
      summary: Returns a user's ArticleCategoryFollows
      tags:
        - my
    post:
      description: Set a user's ArticleCategoryFollows
      security:
        - oauth2:
            - write_lists
      summary: Set a user's ArticleCategoryFollows
      tags:
        - my
  '/my/follows/brands/{slug}':
    delete:
      description: Unfollow a brand
      security:
        - oauth2:
            - write_lists
      summary: Unfollow a brand
      tags:
        - my
    get:
      description: Follow status for a brand
      security:
        - oauth2:
            - read_lists
      summary: Follow status for a brand
      tags:
        - my
    post:
      description: Follow a brand
      security:
        - oauth2:
            - write_lists
      summary: Follow a brand
      tags:
        - my
  '/my/follows/categories/{category}/{subcategory}':
    delete:
      description: Unfollow a subcategory
      security:
        - oauth2:
            - write_lists
      summary: Unfollow a subcategory
      tags:
        - my
    get:
      description: Follow status for a subcategory
      security:
        - oauth2:
            - read_lists
      summary: Follow status for a subcategory
      tags:
        - my
    post:
      description: Follow a subcategory
      security:
        - oauth2:
            - write_lists
      summary: Follow a subcategory
      tags:
        - my
  '/my/follows/categories/{identifier}':
    delete:
      description: Unfollow a category
      security:
        - oauth2:
            - write_lists
      summary: Unfollow a category
      tags:
        - my
    get:
      description: Follow status for a category
      security:
        - oauth2:
            - read_lists
      summary: Follow status for a category
      tags:
        - my
    post:
      description: Follow a category
      security:
        - oauth2:
            - write_lists
      summary: Follow a category
      tags:
        - my
  '/my/follows/collections/{slug}':
    delete:
      description: Unfollow a collection
      security:
        - oauth2:
            - write_lists
      summary: Unfollow a collection
      tags:
        - my
    get:
      description: Follow status for a collection
      security:
        - oauth2:
            - read_lists
      summary: Follow status for a collection
      tags:
        - my
    post:
      description: Follow a collection
      security:
        - oauth2:
            - write_lists
      summary: Follow a collection
      tags:
        - my
  '/my/follows/handpicked/{slug}':
    delete:
      description: Unfollow a handpicked collection
      security:
        - oauth2:
            - write_lists
      summary: Unfollow a handpicked collection
      tags:
        - my
    get:
      description: Follow status for a handpicked collection
      security:
        - oauth2:
            - read_lists
      summary: Follow status for a handpicked collection
      tags:
        - my
    post:
      description: Follow a handpicked collection
      security:
        - oauth2:
            - write_lists
      summary: Follow a handpicked collection
      tags:
        - my
  /my/follows/search:
    get:
      description: Follow status for a search
      security:
        - oauth2:
            - read_lists
      summary: Follow status for a search
      tags:
        - my
    post:
      description: Follow a search
      security:
        - oauth2:
            - write_lists
      summary: Follow a search
      tags:
        - my
  '/my/follows/shops/{slug}':
    delete:
      description: Unfollow a shop
      security:
        - oauth2:
            - write_lists
      summary: Unfollow a shop
      tags:
        - my
    get:
      description: Follow status for a shop
      security:
        - oauth2:
            - read_lists
      summary: Follow status for a shop
      tags:
        - my
    post:
      description: Follow a shop
      security:
        - oauth2:
            - write_lists
      summary: Follow a shop
      tags:
        - my
  '/my/follows/{follow_id}':
    delete:
      description: Delete a follow
      security:
        - oauth2:
            - write_lists
      summary: Delete a follow
      tags:
        - my
  '/my/follows/{follow_id}/alert':
    delete:
      tags:
        - my
    post:
      tags:
        - my
  /my/listings:
    get:
      description: Retrieve a list of live listings for the seller. To search all listings specify state=all
      security:
        - oauth2:
            - read_listings
      summary: Retrieve a list of live listings for the seller. To search all listings specify state=all
      tags:
        - my
  /my/listings/drafts:
    get:
      description: Retrieve a list your draft listings
      security:
        - oauth2:
            - read_listings
      summary: Retrieve a list your draft listings
      tags:
        - my
  /my/listings/negotiations:
    get:
      description: Get a list of active negotiations as a seller
      security:
        - oauth2:
            - read_offers
      summary: Get a list of active negotiations as a seller
      tags:
        - my
  '/my/listings/{slug}/state/end':
    put:
      description: End a listing
      security:
        - oauth2:
            - write_listings
      summary: End a listing
      tags:
        - my
  /my/lists:
    get:
      description: 'Get a list of your lists (wishlist, watch list, etc)'
      security:
        - oauth2:
            - read_lists
      summary: 'Get a list of your lists (wishlist, watch list, etc)'
      tags:
        - my
  /my/negotiations/buying:
    get:
      description: Get a list of active negotiations as a buyer
      security:
        - oauth2:
            - read_offers
      summary: Get a list of active negotiations as a buyer
      tags:
        - my
  '/my/negotiations/{id}':
    get:
      description: Get offer details
      security:
        - oauth2:
            - read_offers
      summary: Get offer details
      tags:
        - my
  '/my/negotiations/{id}/accept':
    post:
      description: Accept an offer
      security:
        - oauth2:
            - write_offers
      summary: Accept an offer
      tags:
        - my
  '/my/negotiations/{id}/counter':
    post:
      description: Counter an offer
      security:
        - oauth2:
            - write_offers
      summary: Counter an offer
      tags:
        - my
  '/my/negotiations/{id}/decline':
    post:
      description: Decline an offer
      security:
        - oauth2:
            - write_offers
      summary: Decline an offer
      tags:
        - my
  /my/orders/awaiting_feedback:
    get:
      description: List of orders that need feedback
      security:
        - oauth2:
            - read_feedback
      summary: List of orders that need feedback
      tags:
        - my
  /my/orders/buying/all:
    get:
      description: 'Returns all orders, newest first.'
      security:
        - oauth2:
            - read_orders
      summary: 'Returns all orders, newest first.'
      tags:
        - my
  /my/orders/buying/unpaid:
    get:
      description: 'Returns unpaid orders, newest first.'
      security:
        - oauth2:
            - read_orders
      summary: 'Returns unpaid orders, newest first.'
      tags:
        - my
  '/my/orders/buying/{id}':
    get:
      description: Returns order details for a buyer
      security:
        - oauth2:
            - read_orders
      summary: Returns order details for a buyer
      tags:
        - my
  '/my/orders/buying/{id}/mark_received':
    post:
      description: Marks an order as received by the buyer
      security:
        - oauth2:
            - write_orders
      summary: Marks an order as received by the buyer
      tags:
        - my
  /my/orders/selling/all:
    get:
      description: 'Get all seller orders, newest first.'
      security:
        - oauth2:
            - read_orders
      summary: 'Get all seller orders, newest first.'
      tags:
        - my
  /my/orders/selling/awaiting_shipment:
    get:
      description: 'Get seller orders awaiting shipment, newest first.'
      security:
        - oauth2:
            - read_orders
      summary: 'Get seller orders awaiting shipment, newest first.'
      tags:
        - my
  '/my/orders/selling/buyer_history/{buyer_id}':
    get:
      description: See previous orders from buyer
      security:
        - oauth2:
            - read_orders
      summary: See previous orders from buyer
      tags:
        - my
  /my/orders/selling/unpaid:
    get:
      description: 'Get unpaid seller orders, newest first.'
      security:
        - oauth2:
            - read_orders
      summary: 'Get unpaid seller orders, newest first.'
      tags:
        - my
  '/my/orders/selling/{id}':
    get:
      description: Returns order details for a seller
      security:
        - oauth2:
            - read_orders
      summary: Returns order details for a seller
      tags:
        - my
  '/my/orders/selling/{id}/mark_picked_up':
    post:
      description: Marks an order as picked up
      security:
        - oauth2:
            - write_orders
      summary: Marks an order as picked up
      tags:
        - my
  '/my/orders/selling/{id}/ship':
    post:
      description: Marks an order as shipped
      security:
        - oauth2:
            - write_orders
      summary: Marks an order as shipped
      tags:
        - my
  '/my/orders/selling/{order_id}/refund_requests':
    post:
      description: Initiate a refund for a sold order
      security:
        - oauth2:
            - write_orders
      summary: Initiate a refund for a sold order
      tags:
        - my
  /my/payments/selling:
    get:
      description: Get payments
      security:
        - oauth2:
            - read_orders
      summary: Get payments
      tags:
        - my
  '/my/payments/selling/{id}':
    get:
      description: Get payment
      security:
        - oauth2:
            - read_orders
      summary: Get payment
      tags:
        - my
  /my/payouts:
    get:
      description: Get a list of payouts
      security:
        - oauth2:
            - read_payouts
      summary: Get a list of payouts
      tags:
        - my
  '/my/payouts/{id}/line_items':
    get:
      description: Read the line items of a payout
      security:
        - oauth2:
            - read_payouts
      summary: Read the line items of a payout
      tags:
        - my
  /my/refund_requests/selling:
    get:
      description: Get a list of refund requests as a seller
      security:
        - oauth2:
            - read_orders
      summary: Get a list of refund requests as a seller
      tags:
        - my
  '/my/refund_requests/selling/{id}':
    put:
      description: Update a refund request for a sold order
      security:
        - oauth2:
            - write_orders
      summary: Update a refund request for a sold order
      tags:
        - my
  /my/viewed_listings:
    get:
      description: Get a list of your recently viewed listings.
      security:
        - oauth2:
            - read_lists
      summary: Get a list of your recently viewed listings.
      tags:
        - my
  /my/wishlist:
    get:
      description: Get a list of wishlisted items
      security:
        - oauth2:
            - read_lists
      summary: Get a list of wishlisted items
      tags:
        - my
  '/my/wishlist/{id}':
    delete:
      description: Remove a listing from your wishlist
      security:
        - oauth2:
            - write_lists
      summary: Remove a listing from your wishlist
      tags:
        - my
    put:
      description: Add a listing to your wishlist
      security:
        - oauth2:
            - write_lists
      summary: Add a listing to your wishlist
      tags:
        - my
  '/orders/{order_id}/feedback/buyer':
    get:
      description: Feedback details for an order's buyer
      summary: Feedback details for an order's buyer
      tags:
        - orders
    post:
      description: Add feedback about an order's buyer
      security:
        - oauth2:
            - write_feedback
      summary: Add feedback about an order's buyer
      tags:
        - orders
  '/orders/{order_id}/feedback/seller':
    get:
      description: Feedback details for an order's seller
      summary: Feedback details for an order's seller
      tags:
        - orders
    post:
      description: Add feedback about an order's seller
      security:
        - oauth2:
            - write_feedback
      summary: Add feedback about an order's seller
      tags:
        - orders
  /payment_methods:
    get:
      description: Get list of payment methods
      summary: Get list of payment methods
      tags:
        - payment_methods
  /priceguide:
    get:
      description: Search the Price Guide
      summary: Search the Price Guide
      tags:
        - priceguide
  '/priceguide/{id}':
    get:
      description: Retrieve a Price Guide
      summary: Retrieve a Price Guide
      tags:
        - priceguide
  '/priceguide/{id}/transactions':
    get:
      description: Get a list of paginated transactions for a price guide.
      summary: Get a list of paginated transactions for a price guide.
      tags:
        - priceguide
  '/priceguide/{id}/transactions/summary':
    get:
      description: Get a summary of transactions for a given price guide
      summary: Get a summary of transactions for a given price guide
      tags:
        - priceguide
  '/products/reviews/{id}':
    get:
      description: View a review
      summary: View a review
      tags:
        - products
    put:
      description: Update a review
      security:
        - oauth2:
            - write_reviews
      summary: Update a review
      tags:
        - products
  '/products/{slug}/reviews':
    get:
      description: View reviews of a comparison shopping page
      summary: View reviews of a comparison shopping page
      tags:
        - products
    post:
      description: Create a review for a product
      security:
        - oauth2:
            - write_reviews
      summary: Create a review for a product
      tags:
        - products
  /sales/reverb:
    get:
      description: View upcoming and live Reverb official sales.
      security:
        - oauth2:
            - read_listings
      summary: View upcoming and live Reverb official sales.
      tags:
        - sales
  /sales/seller:
    get:
      description: View your created sales.
      security:
        - oauth2:
            - read_listings
      summary: View your created sales.
      tags:
        - sales
  '/sales/{sale_id}/listings':
    delete:
      description: Remove a listing from a sale
      security:
        - oauth2:
            - write_listings
      summary: Remove a listing from a sale
      tags:
        - sales
    post:
      description: Add listings to a sale
      security:
        - oauth2:
            - write_listings
      summary: Add listings to a sale
      tags:
        - sales
  '/sales/{slug}':
    get:
      tags:
        - sales
  /shipping/providers:
    get:
      description: List of supported shipping providers
      summary: List of supported shipping providers
      tags:
        - shipping
  /shipping/regions:
    get:
      tags:
        - shipping
  /shop:
    get:
      description: Get your own shop details
      security:
        - oauth2:
            - read_profile
      summary: Get your own shop details
      tags:
        - shop
    put:
      description: Update your shop profile
      security:
        - oauth2:
            - write_profile
      summary: Update your shop profile
      tags:
        - shop
  /shop/listing_conditions:
    get:
      description: List of supported product conditions
      security:
        - oauth2:
            - read_profile
      summary: List of supported product conditions
      tags:
        - shop
  /shop/payment_methods:
    get:
      description: Get accepted payment methods
      security:
        - oauth2:
            - read_profile
      summary: Get accepted payment methods
      tags:
        - shop
  /shop/vacation:
    delete:
      description: Disable vacation mode. All listings will be re-enabled.
      security:
        - oauth2:
            - write_profile
      summary: Disable vacation mode. All listings will be re-enabled.
      tags:
        - shop
    get:
      description: Returns shop vacation status
      security:
        - oauth2:
            - read_profile
      summary: Returns shop vacation status
      tags:
        - shop
    post:
      description: Enable vacation mode. All listings will be unavailable until vacation mode is turned off.
      security:
        - oauth2:
            - write_profile
      summary: Enable vacation mode. All listings will be unavailable until vacation mode is turned off.
      tags:
        - shop
  '/shops/{shop_id}/shipping_profiles':
    get:
      description: List of shipping profiles for your shop
      security:
        - oauth2:
            - read_profile
      summary: List of shipping profiles for your shop
      tags:
        - shops
  '/shops/{slug}':
    get:
      description: Get details on a shop.
      summary: Get details on a shop.
      tags:
        - shops
  '/shops/{slug}/feedback':
    get:
      description: Get seller's feedback
      summary: Get seller's feedback
      tags:
        - shops
  '/shops/{slug}/feedback/buyer':
    get:
      description: Get seller's feedback as a buyer
      summary: Get seller's feedback as a buyer
      tags:
        - shops
  '/shops/{slug}/feedback/seller':
    get:
      description: Get seller's feedback as a seller
      summary: Get seller's feedback as a seller
      tags:
        - shops
  /wants:
    get:
      description: A list of wanted items by the user
      security:
        - oauth2:
            - read_lists
      summary: A list of wanted items by the user
      tags:
        - wants
  '/wants/{id}':
    delete:
      description: Unmark an item wanted.
      security:
        - oauth2:
            - write_lists
      summary: Unmark an item wanted.
      tags:
        - wants
    put:
      description: Mark an item wanted. Returns 200 on success or 422 on failure.
      security:
        - oauth2:
            - write_lists
      summary: Mark an item wanted. Returns 200 on success or 422 on failure.
      tags:
        - wants
  /webhooks/registrations:
    get:
      description: Get webhook registrations
      summary: Get webhook registrations
      tags:
        - webhooks
    post:
      description: Register a webhook
      summary: Register a webhook
      tags:
        - webhooks
  '/webhooks/registrations/{id}':
    delete:
      description: Remove a webhook
      summary: Remove a webhook
      tags:
        - webhooks
    get:
      description: Get details of a webhook registration
      summary: Get details of a webhook registration
      tags:
        - webhooks