from .deploymentmanager_compositetypes_delete import *
from .deploymentmanager_compositetypes_get import *
from .deploymentmanager_compositetypes_insert import *
from .deploymentmanager_compositetypes_list import *
from .deploymentmanager_compositetypes_patch import *
from .deploymentmanager_compositetypes_update import *
from .deploymentmanager_deployments_cancelpreview import *
from .deploymentmanager_deployments_delete import *
from .deploymentmanager_deployments_get import *
from .deploymentmanager_deployments_getiampolicy import *
from .deploymentmanager_deployments_insert import *
from .deploymentmanager_deployments_list import *
from .deploymentmanager_deployments_patch import *
from .deploymentmanager_deployments_setiampolicy import *
from .deploymentmanager_deployments_stop import *
from .deploymentmanager_deployments_testiampermissions import *
from .deploymentmanager_deployments_update import *
from .deploymentmanager_manifests_get import *
from .deploymentmanager_manifests_list import *
from .deploymentmanager_operations_get import *
from .deploymentmanager_operations_list import *
from .deploymentmanager_resources_get import *
from .deploymentmanager_resources_list import *
from .deploymentmanager_typeproviders_delete import *
from .deploymentmanager_typeproviders_get import *
from .deploymentmanager_typeproviders_gettype import *
from .deploymentmanager_typeproviders_insert import *
from .deploymentmanager_typeproviders_list import *
from .deploymentmanager_typeproviders_listtypes import *
from .deploymentmanager_typeproviders_patch import *
from .deploymentmanager_typeproviders_update import *
from .deploymentmanager_types_get import *
from .deploymentmanager_types_list import *
