{
  "swagger": "2.0",
  "info": {
    "title": "Cloud User Accounts API",
    "x-serviceName": "clouduseraccounts",
    "description": "API for the Google Cloud User Accounts service.",
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "version": "vm_alpha",
    "x-providerName": "googleapis.com",
    "x-origin": {
      "format": "google",
      "version": "v1",
      "url": "https://www.googleapis.com/discovery/v1/apis/clouduseraccounts/vm_alpha/rest"
    },
    "x-logo": "https://www.google.com/images/srpr/logo11w.png"
  },
  "host": "www.googleapis.com",
  "basePath": "/clouduseraccounts/vm_alpha/projects",
  "schemes": [
    "https"
  ],
  "paths": {
    "/{project}/global/operations/{operation}": {
      "delete": {
        "description": "Deletes the specified operation resource.",
        "operationId": "clouduseraccounts.globalAccountsOperations.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/cloud.useraccounts",
              "https://www.googleapis.com/auth/computeaccounts"
            ]
          }
        ],
        "tags": [
          "globalAccountsOperations"
        ]
      },
      "get": {
        "description": "Retrieves the specified operation resource.",
        "operationId": "clouduseraccounts.globalAccountsOperations.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/cloud.useraccounts",
              "https://www.googleapis.com/auth/cloud.useraccounts.readonly",
              "https://www.googleapis.com/auth/computeaccounts",
              "https://www.googleapis.com/auth/computeaccounts.readonly"
            ]
          }
        ],
        "tags": [
          "globalAccountsOperations"
        ]
      }
    },
    "/{project}/global/operations": {
      "get": {
        "description": "Retrieves the list of operation resources contained within the specified project.",
        "operationId": "clouduseraccounts.globalAccountsOperations.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/cloud.useraccounts",
              "https://www.googleapis.com/auth/cloud.useraccounts.readonly",
              "https://www.googleapis.com/auth/computeaccounts",
              "https://www.googleapis.com/auth/computeaccounts.readonly"
            ]
          }
        ],
        "tags": [
          "globalAccountsOperations"
        ]
      }
    },
    "/{project}/global/groups/{groupName}/addMember": {
      "post": {
        "description": "Adds users to the specified group.",
        "operationId": "clouduseraccounts.groups.addMember",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/cloud.useraccounts",
              "https://www.googleapis.com/auth/computeaccounts"
            ]
          }
        ],
        "tags": [
          "groups"
        ]
      }
    },
    "/{project}/global/groups/{groupName}": {
      "delete": {
        "description": "Deletes the specified Group resource.",
        "operationId": "clouduseraccounts.groups.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/cloud.useraccounts",
              "https://www.googleapis.com/auth/computeaccounts"
            ]
          }
        ],
        "tags": [
          "groups"
        ]
      },
      "get": {
        "description": "Returns the specified Group resource.",
        "operationId": "clouduseraccounts.groups.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/cloud.useraccounts",
              "https://www.googleapis.com/auth/cloud.useraccounts.readonly",
              "https://www.googleapis.com/auth/computeaccounts",
              "https://www.googleapis.com/auth/computeaccounts.readonly"
            ]
          }
        ],
        "tags": [
          "groups"
        ]
      }
    },
    "/{project}/global/groups": {
      "post": {
        "description": "Creates a Group resource in the specified project using the data included in the request.",
        "operationId": "clouduseraccounts.groups.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/cloud.useraccounts",
              "https://www.googleapis.com/auth/computeaccounts"
            ]
          }
        ],
        "tags": [
          "groups"
        ]
      },
      "get": {
        "description": "Retrieves the list of groups contained within the specified project.",
        "operationId": "clouduseraccounts.groups.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/cloud.useraccounts",
              "https://www.googleapis.com/auth/cloud.useraccounts.readonly",
              "https://www.googleapis.com/auth/computeaccounts",
              "https://www.googleapis.com/auth/computeaccounts.readonly"
            ]
          }
        ],
        "tags": [
          "groups"
        ]
      }
    },
    "/{project}/global/groups/{groupName}/removeMember": {
      "post": {
        "description": "Removes users from the specified group.",
        "operationId": "clouduseraccounts.groups.removeMember",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/cloud.useraccounts",
              "https://www.googleapis.com/auth/computeaccounts"
            ]
          }
        ],
        "tags": [
          "groups"
        ]
      }
    },
    "/{project}/zones/{zone}/authorizedKeysView/{user}": {
      "post": {
        "description": "Returns a list of authorized public keys for a specific user account.",
        "operationId": "clouduseraccounts.linux.getAuthorizedKeysView",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/cloud.useraccounts",
              "https://www.googleapis.com/auth/cloud.useraccounts.readonly",
              "https://www.googleapis.com/auth/computeaccounts",
              "https://www.googleapis.com/auth/computeaccounts.readonly"
            ]
          }
        ],
        "tags": [
          "linux"
        ]
      }
    },
    "/{project}/zones/{zone}/linuxAccountViews": {
      "post": {
        "description": "Retrieves a list of user accounts for an instance within a specific project.",
        "operationId": "clouduseraccounts.linux.getLinuxAccountViews",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/cloud.useraccounts",
              "https://www.googleapis.com/auth/cloud.useraccounts.readonly",
              "https://www.googleapis.com/auth/computeaccounts",
              "https://www.googleapis.com/auth/computeaccounts.readonly"
            ]
          }
        ],
        "tags": [
          "linux"
        ]
      }
    },
    "/{project}/global/users/{user}/addPublicKey": {
      "post": {
        "description": "Adds a public key to the specified User resource with the data included in the request.",
        "operationId": "clouduseraccounts.users.addPublicKey",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/cloud.useraccounts",
              "https://www.googleapis.com/auth/computeaccounts"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{project}/global/users/{user}": {
      "delete": {
        "description": "Deletes the specified User resource.",
        "operationId": "clouduseraccounts.users.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/cloud.useraccounts",
              "https://www.googleapis.com/auth/computeaccounts"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      },
      "get": {
        "description": "Returns the specified User resource.",
        "operationId": "clouduseraccounts.users.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/cloud.useraccounts",
              "https://www.googleapis.com/auth/cloud.useraccounts.readonly",
              "https://www.googleapis.com/auth/computeaccounts",
              "https://www.googleapis.com/auth/computeaccounts.readonly"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{project}/global/users": {
      "post": {
        "description": "Creates a User resource in the specified project using the data included in the request.",
        "operationId": "clouduseraccounts.users.insert",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/cloud.useraccounts",
              "https://www.googleapis.com/auth/computeaccounts"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      },
      "get": {
        "description": "Retrieves a list of users contained within the specified project.",
        "operationId": "clouduseraccounts.users.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/cloud.useraccounts",
              "https://www.googleapis.com/auth/cloud.useraccounts.readonly",
              "https://www.googleapis.com/auth/computeaccounts",
              "https://www.googleapis.com/auth/computeaccounts.readonly"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    },
    "/{project}/global/users/{user}/removePublicKey": {
      "post": {
        "description": "Removes the specified public key from the user.",
        "operationId": "clouduseraccounts.users.removePublicKey",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform",
              "https://www.googleapis.com/auth/cloud.useraccounts",
              "https://www.googleapis.com/auth/computeaccounts"
            ]
          }
        ],
        "tags": [
          "users"
        ]
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "type": "oauth2",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "scopes": {
        "https://www.googleapis.com/auth/cloud-platform": "View and manage your data across Google Cloud Platform services",
        "https://www.googleapis.com/auth/cloud.useraccounts": "Manage your Google Cloud User Accounts",
        "https://www.googleapis.com/auth/cloud.useraccounts.readonly": "View your Google Cloud User Accounts",
        "https://www.googleapis.com/auth/computeaccounts": "Manage your Google Compute Accounts",
        "https://www.googleapis.com/auth/computeaccounts.readonly": "View your Google Compute Accounts"
      }
    }
  }
}