swagger: '2.0'
schemes:
  - https
host: genomics.googleapis.com
basePath: /
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: 'Upload, process, query, and search Genomics data in the cloud.'
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Genomics
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://genomics.googleapis.com/$discovery/rest?version=v1'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: genomics
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/bigquery': View and manage your data in Google BigQuery
      'https://www.googleapis.com/auth/cloud-platform': View and manage your data across Google Cloud Platform services
      'https://www.googleapis.com/auth/devstorage.read_write': Manage your data in Google Cloud Storage
      'https://www.googleapis.com/auth/genomics': View and manage Genomics data
      'https://www.googleapis.com/auth/genomics.readonly': View Genomics data
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/bigquery': View and manage your data in Google BigQuery
      'https://www.googleapis.com/auth/cloud-platform': View and manage your data across Google Cloud Platform services
      'https://www.googleapis.com/auth/devstorage.read_write': Manage your data in Google Cloud Storage
      'https://www.googleapis.com/auth/genomics': View and manage Genomics data
      'https://www.googleapis.com/auth/genomics.readonly': View Genomics data
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: annotations
  - name: annotationsets
  - name: callsets
  - name: datasets
  - name: operations
  - name: readgroupsets
  - name: reads
  - name: references
  - name: referencesets
  - name: variants
  - name: variantsets
paths:
  /v1/annotations:
    post:
      description: |-
        Creates a new annotation. Caller must have WRITE permission
        for the associated annotation set.

        The following fields are required:

        * annotationSetId
        * referenceName or
          referenceId

        ### Transcripts

        For annotations of type TRANSCRIPT, the following fields of
        transcript must be provided:

        * exons.start
        * exons.end

        All other fields may be optionally specified, unless documented as being
        server-generated (for example, the `id` field). The annotated
        range must be no longer than 100Mbp (mega base pairs). See the
        Annotation resource
        for additional restrictions on each field.
      operationId: genomics.annotations.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - annotations
  /v1/annotations/search:
    post:
      description: |-
        Searches for annotations that match the given criteria. Results are
        ordered by genomic coordinate (by reference sequence, then position).
        Annotations with equivalent genomic coordinates are returned in an
        unspecified order. This order is consistent, such that two queries for the
        same content (regardless of page size) yield annotations in the same order
        across their respective streams of paginated responses. Caller must have
        READ permission for the queried annotation sets.
      operationId: genomics.annotations.search
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - annotations
  '/v1/annotations/{annotationId}':
    delete:
      description: |-
        Deletes an annotation. Caller must have WRITE permission for
        the associated annotation set.
      operationId: genomics.annotations.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - annotations
    get:
      description: |-
        Gets an annotation. Caller must have READ permission
        for the associated annotation set.
      operationId: genomics.annotations.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - annotations
    put:
      description: |-
        Updates an annotation. Caller must have
        WRITE permission for the associated dataset.
      operationId: genomics.annotations.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - annotations
  '/v1/annotations:batchCreate':
    post:
      description: |-
        Creates one or more new annotations atomically. All annotations must
        belong to the same annotation set. Caller must have WRITE
        permission for this annotation set. For optimal performance, batch
        positionally adjacent annotations together.

        If the request has a systemic issue, such as an attempt to write to
        an inaccessible annotation set, the entire RPC will fail accordingly. For
        lesser data issues, when possible an error will be isolated to the
        corresponding batch entry in the response; the remaining well formed
        annotations will be created normally.

        For details on the requirements for each individual annotation resource,
        see
        CreateAnnotation.
      operationId: genomics.annotations.batchCreate
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - annotations
  /v1/annotationsets:
    post:
      description: |-
        Creates a new annotation set. Caller must have WRITE permission for the
        associated dataset.

        The following fields are required:

          * datasetId
          * referenceSetId

        All other fields may be optionally specified, unless documented as being
        server-generated (for example, the `id` field).
      operationId: genomics.annotationsets.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - annotationsets
  /v1/annotationsets/search:
    post:
      description: |-
        Searches for annotation sets that match the given criteria. Annotation sets
        are returned in an unspecified order. This order is consistent, such that
        two queries for the same content (regardless of page size) yield annotation
        sets in the same order across their respective streams of paginated
        responses. Caller must have READ permission for the queried datasets.
      operationId: genomics.annotationsets.search
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - annotationsets
  '/v1/annotationsets/{annotationSetId}':
    delete:
      description: |-
        Deletes an annotation set. Caller must have WRITE permission
        for the associated annotation set.
      operationId: genomics.annotationsets.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - annotationsets
    get:
      description: |-
        Gets an annotation set. Caller must have READ permission for
        the associated dataset.
      operationId: genomics.annotationsets.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - annotationsets
    put:
      description: |-
        Updates an annotation set. The update must respect all mutability
        restrictions and other invariants described on the annotation set resource.
        Caller must have WRITE permission for the associated dataset.
      operationId: genomics.annotationsets.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - annotationsets
  /v1/callsets:
    post:
      description: |-
        Creates a new call set.

        For the definitions of call sets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      operationId: genomics.callsets.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - callsets
  /v1/callsets/search:
    post:
      description: |-
        Gets a list of call sets matching the criteria.

        For the definitions of call sets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        Implements
        [GlobalAllianceApi.searchCallSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/variantmethods.avdl#L178).
      operationId: genomics.callsets.search
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - callsets
  '/v1/callsets/{callSetId}':
    delete:
      description: |-
        Deletes a call set.

        For the definitions of call sets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      operationId: genomics.callsets.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - callsets
    get:
      description: |-
        Gets a call set by ID.

        For the definitions of call sets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      operationId: genomics.callsets.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - callsets
    patch:
      description: |-
        Updates a call set.

        For the definitions of call sets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        This method supports patch semantics.
      operationId: genomics.callsets.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - callsets
  /v1/datasets:
    get:
      description: |-
        Lists datasets within a project.

        For the definitions of datasets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      operationId: genomics.datasets.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - datasets
    post:
      description: |-
        Creates a new dataset.

        For the definitions of datasets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      operationId: genomics.datasets.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - datasets
  '/v1/datasets/{datasetId}':
    delete:
      description: |-
        Deletes a dataset and all of its contents (all read group sets,
        reference sets, variant sets, call sets, annotation sets, etc.)
        This is reversible (up to one week after the deletion) via
        the
        datasets.undelete
        operation.

        For the definitions of datasets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      operationId: genomics.datasets.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - datasets
    get:
      description: |-
        Gets a dataset by ID.

        For the definitions of datasets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      operationId: genomics.datasets.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - datasets
    patch:
      description: |-
        Updates a dataset.

        For the definitions of datasets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        This method supports patch semantics.
      operationId: genomics.datasets.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - datasets
  '/v1/datasets/{datasetId}:undelete':
    post:
      description: |-
        Undeletes a dataset by restoring a dataset which was deleted via this API.

        For the definitions of datasets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        This operation is only possible for a week after the deletion occurred.
      operationId: genomics.datasets.undelete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - datasets
  /v1/readgroupsets/search:
    post:
      description: |-
        Searches for read group sets matching the criteria.

        For the definitions of read group sets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        Implements
        [GlobalAllianceApi.searchReadGroupSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/readmethods.avdl#L135).
      operationId: genomics.readgroupsets.search
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - readgroupsets
  '/v1/readgroupsets/{readGroupSetId}':
    delete:
      description: |-
        Deletes a read group set.

        For the definitions of read group sets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      operationId: genomics.readgroupsets.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - readgroupsets
    get:
      description: |-
        Gets a read group set by ID.

        For the definitions of read group sets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      operationId: genomics.readgroupsets.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - readgroupsets
    patch:
      description: |-
        Updates a read group set.

        For the definitions of read group sets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        This method supports patch semantics.
      operationId: genomics.readgroupsets.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - readgroupsets
  '/v1/readgroupsets/{readGroupSetId}/coveragebuckets':
    get:
      description: |-
        Lists fixed width coverage buckets for a read group set, each of which
        correspond to a range of a reference sequence. Each bucket summarizes
        coverage information across its corresponding genomic range.

        For the definitions of read group sets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        Coverage is defined as the number of reads which are aligned to a given
        base in the reference sequence. Coverage buckets are available at several
        precomputed bucket widths, enabling retrieval of various coverage 'zoom
        levels'. The caller must have READ permissions for the target read group
        set.
      operationId: genomics.readgroupsets.coveragebuckets.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - readgroupsets
  '/v1/readgroupsets/{readGroupSetId}:export':
    post:
      description: |-
        Exports a read group set to a BAM file in Google Cloud Storage.

        For the definitions of read group sets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        Note that currently there may be some differences between exported BAM
        files and the original BAM file at the time of import. See
        ImportReadGroupSets
        for caveats.
      operationId: genomics.readgroupsets.export
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/devstorage.read_write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/devstorage.read_write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - readgroupsets
  '/v1/readgroupsets:import':
    post:
      description: |-
        Creates read group sets by asynchronously importing the provided
        information.

        For the definitions of read group sets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        The caller must have WRITE permissions to the dataset.

        ## Notes on [BAM](https://samtools.github.io/hts-specs/SAMv1.pdf) import

        - Tags will be converted to strings - tag types are not preserved
        - Comments (`@CO`) in the input file header will not be preserved
        - Original header order of references (`@SQ`) will not be preserved
        - Any reverse stranded unmapped reads will be reverse complemented, and
        their qualities (also the "BQ" and "OQ" tags, if any) will be reversed
        - Unmapped reads will be stripped of positional information (reference name
        and position)
      operationId: genomics.readgroupsets.import
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/devstorage.read_write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/devstorage.read_write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - readgroupsets
  /v1/reads/search:
    post:
      description: |-
        Gets a list of reads for one or more read group sets.

        For the definitions of read group sets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        Reads search operates over a genomic coordinate space of reference sequence
        & position defined over the reference sequences to which the requested
        read group sets are aligned.

        If a target positional range is specified, search returns all reads whose
        alignment to the reference genome overlap the range. A query which
        specifies only read group set IDs yields all reads in those read group
        sets, including unmapped reads.

        All reads returned (including reads on subsequent pages) are ordered by
        genomic coordinate (by reference sequence, then position). Reads with
        equivalent genomic coordinates are returned in an unspecified order. This
        order is consistent, such that two queries for the same content (regardless
        of page size) yield reads in the same order across their respective streams
        of paginated responses.

        Implements
        [GlobalAllianceApi.searchReads](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/readmethods.avdl#L85).
      operationId: genomics.reads.search
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - reads
  /v1/references/search:
    post:
      description: |-
        Searches for references which match the given criteria.

        For the definitions of references and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        Implements
        [GlobalAllianceApi.searchReferences](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/referencemethods.avdl#L146).
      operationId: genomics.references.search
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - references
  '/v1/references/{referenceId}':
    get:
      description: |-
        Gets a reference.

        For the definitions of references and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        Implements
        [GlobalAllianceApi.getReference](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/referencemethods.avdl#L158).
      operationId: genomics.references.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - references
  '/v1/references/{referenceId}/bases':
    get:
      description: |-
        Lists the bases in a reference, optionally restricted to a range.

        For the definitions of references and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        Implements
        [GlobalAllianceApi.getReferenceBases](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/referencemethods.avdl#L221).
      operationId: genomics.references.bases.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - references
  /v1/referencesets/search:
    post:
      description: |-
        Searches for reference sets which match the given criteria.

        For the definitions of references and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        Implements
        [GlobalAllianceApi.searchReferenceSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/referencemethods.avdl#L71)
      operationId: genomics.referencesets.search
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - referencesets
  '/v1/referencesets/{referenceSetId}':
    get:
      description: |-
        Gets a reference set.

        For the definitions of references and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        Implements
        [GlobalAllianceApi.getReferenceSet](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/referencemethods.avdl#L83).
      operationId: genomics.referencesets.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - referencesets
  /v1/variants:
    post:
      description: |-
        Creates a new variant.

        For the definitions of variants and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      operationId: genomics.variants.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - variants
  /v1/variants/search:
    post:
      description: |-
        Gets a list of variants matching the criteria.

        For the definitions of variants and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        Implements
        [GlobalAllianceApi.searchVariants](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/variantmethods.avdl#L126).
      operationId: genomics.variants.search
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - variants
  '/v1/variants/{variantId}':
    delete:
      description: |-
        Deletes a variant.

        For the definitions of variants and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      operationId: genomics.variants.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - variants
    get:
      description: |-
        Gets a variant by ID.

        For the definitions of variants and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      operationId: genomics.variants.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - variants
    patch:
      description: |-
        Updates a variant.

        For the definitions of variants and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        This method supports patch semantics. Returns the modified variant without
        its calls.
      operationId: genomics.variants.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - variants
  '/v1/variants:import':
    post:
      description: |-
        Creates variant data by asynchronously importing the provided information.

        For the definitions of variant sets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        The variants for import will be merged with any existing variant that
        matches its reference sequence, start, end, reference bases, and
        alternative bases. If no such variant exists, a new one will be created.

        When variants are merged, the call information from the new variant
        is added to the existing variant, and Variant info fields are merged
        as specified in
        infoMergeConfig.
        As a special case, for single-sample VCF files, QUAL and FILTER fields will
        be moved to the call level; these are sometimes interpreted in a
        call-specific context.
        Imported VCF headers are appended to the metadata already in a variant set.
      operationId: genomics.variants.import
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/devstorage.read_write'
          Oauth2c:
            - 'https://www.googleapis.com/auth/devstorage.read_write'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - variants
  '/v1/variants:merge':
    post:
      description: |-
        Merges the given variants with existing variants.

        For the definitions of variants and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        Each variant will be
        merged with an existing variant that matches its reference sequence,
        start, end, reference bases, and alternative bases. If no such variant
        exists, a new one will be created.

        When variants are merged, the call information from the new variant
        is added to the existing variant. Variant info fields are merged as
        specified in the
        infoMergeConfig
        field of the MergeVariantsRequest.

        Please exercise caution when using this method!  It is easy to introduce
        mistakes in existing variants and difficult to back out of them.  For
        example,
        suppose you were trying to merge a new variant with an existing one and
        both
        variants contain calls that belong to callsets with the same callset ID.

            // Existing variant - irrelevant fields trimmed for clarity
            {
                "variantSetId": "10473108253681171589",
                "referenceName": "1",
                "start": "10582",
                "referenceBases": "G",
                "alternateBases": [
                    "A"
                ],
                "calls": [
                    {
                        "callSetId": "10473108253681171589-0",
                        "callSetName": "CALLSET0",
                        "genotype": [
                            0,
                            1
                        ]
                    }
                ]
            }

            // New variant with conflicting call information
            {
                "variantSetId": "10473108253681171589",
                "referenceName": "1",
                "start": "10582",
                "referenceBases": "G",
                "alternateBases": [
                    "A"
                ],
                "calls": [
                    {
                        "callSetId": "10473108253681171589-0",
                        "callSetName": "CALLSET0",
                        "genotype": [
                            1,
                            1
                        ]
                    }
                ]
            }

        The resulting merged variant would overwrite the existing calls with those
        from the new variant:

            {
                "variantSetId": "10473108253681171589",
                "referenceName": "1",
                "start": "10582",
                "referenceBases": "G",
                "alternateBases": [
                    "A"
                ],
                "calls": [
                    {
                        "callSetId": "10473108253681171589-0",
                        "callSetName": "CALLSET0",
                        "genotype": [
                            1,
                            1
                        ]
                    }
                ]
            }

        This may be the desired outcome, but it is up to the user to determine if
        if that is indeed the case.
      operationId: genomics.variants.merge
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - variants
  /v1/variantsets:
    post:
      description: |-
        Creates a new variant set.

        For the definitions of variant sets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        The provided variant set must have a valid `datasetId` set - all other
        fields are optional. Note that the `id` field will be ignored, as this is
        assigned by the server.
      operationId: genomics.variantsets.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - variantsets
  /v1/variantsets/search:
    post:
      description: |-
        Returns a list of all variant sets matching search criteria.

        For the definitions of variant sets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        Implements
        [GlobalAllianceApi.searchVariantSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/variantmethods.avdl#L49).
      operationId: genomics.variantsets.search
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - variantsets
  '/v1/variantsets/{variantSetId}':
    delete:
      description: |-
        Deletes a variant set including all variants, call sets, and calls within.
        This is not reversible.

        For the definitions of variant sets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      operationId: genomics.variantsets.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - variantsets
    get:
      description: |-
        Gets a variant set by ID.

        For the definitions of variant sets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      operationId: genomics.variantsets.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics.readonly'
      tags:
        - variantsets
    patch:
      description: |-
        Updates a variant set using patch semantics.

        For the definitions of variant sets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      operationId: genomics.variantsets.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - variantsets
  '/v1/variantsets/{variantSetId}:export':
    post:
      description: |-
        Exports variant set data to an external destination.

        For the definitions of variant sets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      operationId: genomics.variantsets.export
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/bigquery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/bigquery'
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - variantsets
  '/v1/{name}':
    get:
      description: Lists operations that match the specified filter in the request.
      operationId: genomics.operations.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - operations
  '/v1/{name}:cancel':
    post:
      description: 'Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. Clients may use Operations.GetOperation or Operations.ListOperations to check whether the cancellation succeeded or the operation completed despite cancellation.'
      operationId: genomics.operations.cancel
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - operations
  '/v1/{resource}:getIamPolicy':
    post:
      description: |-
        Gets the access control policy for the dataset. This is empty if the
        policy or resource does not exist.

        See <a href="/iam/docs/managing-policies#getting_a_policy">Getting a
        Policy</a> for more information.

        For the definitions of datasets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      operationId: genomics.datasets.getIamPolicy
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - datasets
  '/v1/{resource}:setIamPolicy':
    post:
      description: |-
        Sets the access control policy on the specified dataset. Replaces any
        existing policy.

        For the definitions of datasets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)

        See <a href="/iam/docs/managing-policies#setting_a_policy">Setting a
        Policy</a> for more information.
      operationId: genomics.datasets.setIamPolicy
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - datasets
  '/v1/{resource}:testIamPermissions':
    post:
      description: |-
        Returns permissions that a caller has on the specified resource.
        See <a href="/iam/docs/managing-policies#testing_permissions">Testing
        Permissions</a> for more information.

        For the definitions of datasets and other genomics resources, see
        [Fundamentals of Google
        Genomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)
      operationId: genomics.datasets.testIamPermissions
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/cloud-platform'
          Oauth2c:
            - 'https://www.googleapis.com/auth/cloud-platform'
        - Oauth2:
            - 'https://www.googleapis.com/auth/genomics'
          Oauth2c:
            - 'https://www.googleapis.com/auth/genomics'
      tags:
        - datasets