swagger: '2.0'
schemes:
  - https
host: api.spotify.com
basePath: /v1
info:
  title: Spotify
  version: v1
  x-apisguru-categories:
    - media
  x-logo:
    url: 'https://logo-core.clearbit.com/spotify.com'
  x-origin:
    - format: raml
      url: 'https://raw.githubusercontent.com/spotify/web-api/master/specifications/raml/api.raml'
      version: '0.8'
  x-providerName: spotify.com
securityDefinitions:
  oauth_2_0_accessCode:
    authorizationUrl: 'https://accounts.spotify.com/authorize'
    description: |
      Spotify supports OAuth 2.0 for authenticating all API requests.
    flow: accessCode
    scopes:
      playlist-modify-private: ''
      playlist-modify-public: ''
      playlist-read-collaborative: ''
      playlist-read-private: ''
      user-follow-modify: ''
      user-follow-read: ''
      user-library-modify: ''
      user-library-read: ''
      user-read-birthdate: ''
      user-read-email: ''
      user-read-private: ''
    tokenUrl: 'https://accounts.spotify.com/api/token'
    type: oauth2
  oauth_2_0_implicit:
    authorizationUrl: 'https://accounts.spotify.com/authorize'
    description: |
      Spotify supports OAuth 2.0 for authenticating all API requests.
    flow: implicit
    scopes:
      playlist-modify-private: ''
      playlist-modify-public: ''
      playlist-read-collaborative: ''
      playlist-read-private: ''
      user-follow-modify: ''
      user-follow-read: ''
      user-library-modify: ''
      user-library-read: ''
      user-read-birthdate: ''
      user-read-email: ''
      user-read-private: ''
    type: oauth2
paths:
  /albums:
    get:
      description: |
        [Get Several Albums](https://developer.spotify.com/web-api/get-several-albums/)
  '/albums/{id}':
    get:
      description: |
        [Get an Album](https://developer.spotify.com/web-api/get-album/)
  '/albums/{id}/tracks':
    get:
      description: |
        [Get an Album's Tracks](https://developer.spotify.com/web-api/get-albums-tracks/)
  /artists:
    get:
      description: |
        [Get Several Artists](https://developer.spotify.com/web-api/get-several-artists/)
  '/artists/{id}':
    get:
      description: |
        [Get an Artist](https://developer.spotify.com/web-api/get-artist/)
  '/artists/{id}/albums':
    get:
      description: |
        [Get an Artist's Albums](https://developer.spotify.com/web-api/get-artists-albums/)
  '/artists/{id}/related-artists':
    get:
      description: |
        [Get an Artist's Related Artists](https://developer.spotify.com/web-api/get-related-artists/)
  '/artists/{id}/top-tracks':
    get:
      description: |
        [Get an Artist's Top Tracks](https://developer.spotify.com/web-api/get-artists-top-tracks/)
  /browse/categories:
    get:
      description: |
        [Get a List of Browse Categories](https://developer.spotify.com/web-api/get-list-categories/)
  '/browse/categories/{category_id}':
    get:
      description: |
        [Get a Single Browse Category](https://developer.spotify.com/web-api/get-category/)
  '/browse/categories/{category_id}/playlists':
    get:
      description: |
        [Get a Category's playlists](https://developer.spotify.com/web-api/get-categorys-playlists/)
  /browse/featured-playlists:
    get:
      description: |
        [Get a List of Featured Playlists](https://developer.spotify.com/web-api/get-list-featured-playlists/)
  /browse/new-releases:
    get:
      description: |
        [Get a List of New Releases](https://developer.spotify.com/web-api/get-list-new-releases/)
  /me:
    get:
      description: |
        [Get Current User's Profile](https://developer.spotify.com/web-api/get-current-users-profile/)
  /me/following:
    delete:
      description: |
        [Unfollow Artists or Users](https://developer.spotify.com/web-api/unfollow-artists-users/)
    get:
      description: |
        [Get User's Followed Artists](https://developer.spotify.com/web-api/get-followed-artists/)
    put:
      description: |
        [Follow Artists or Users](https://developer.spotify.com/web-api/follow-artists-users/)
  /me/following/contains:
    get:
      description: |
        [Check if Current User Follows Artists or Users](https://developer.spotify.com/web-api/check-current-user-follows/)
  /me/tracks:
    delete:
      description: |
        [Remove Tracks for Current User](https://developer.spotify.com/web-api/remove-tracks-user/)
    get:
      description: |
        [Get Current User's Saved Tracks](https://developer.spotify.com/web-api/get-users-saved-tracks/)
    put:
      description: |
        [Save Tracks for Current User](https://developer.spotify.com/web-api/save-tracks-user/)
  /me/tracks/contains:
    get:
      description: |
        [Check Current User's Saved Tracks](https://developer.spotify.com/web-api/check-users-saved-tracks/)
  /search:
    get:
      description: |
        [Search for an Item](https://developer.spotify.com/web-api/search-item/)
  /tracks:
    get:
      description: |
        [Get Several Tracks](https://developer.spotify.com/web-api/get-several-tracks/)
  '/tracks/{id}':
    get:
      description: |
        [Get a Track](https://developer.spotify.com/web-api/get-track/)
  '/users/{user_id}':
    get:
      description: |
        [Get a User's Profile](https://developer.spotify.com/web-api/get-users-profile/)
  '/users/{user_id}/playlists':
    get:
      description: |
        [Get a List of a User's Playlists](https://developer.spotify.com/web-api/get-list-users-playlists/)
    post:
      description: |
        [Create a Playlist](https://developer.spotify.com/web-api/create-playlist/)
  '/users/{user_id}/playlists/{playlist_id}':
    get:
      description: |
        [Get a Playlist](https://developer.spotify.com/web-api/get-playlist/)
    put:
      description: |
        [Change a Playlist's Details](https://developer.spotify.com/web-api/change-playlist-details/)
  '/users/{user_id}/playlists/{playlist_id}/followers':
    delete:
      description: |
        [Unfollow a Playlist](https://developer.spotify.com/web-api/unfollow-playlist/)
    put:
      description: |
        [Follow a Playlist](https://developer.spotify.com/web-api/follow-playlist/)
  '/users/{user_id}/playlists/{playlist_id}/followers/contains':
    get:
      description: |
        [Check if Users Follow a Playlist](https://developer.spotify.com/web-api/check-user-following-playlist/)
  '/users/{user_id}/playlists/{playlist_id}/tracks':
    delete:
      description: |
        [Remove Tracks from a Playlist](https://developer.spotify.com/web-api/remove-tracks-playlist/)
    get:
      description: |
        [Get a Playlist's Tracks](https://developer.spotify.com/web-api/get-playlists-tracks/)
    post:
      description: |
        [Add Tracks to a Playlist](https://developer.spotify.com/web-api/add-tracks-to-playlist/)
    put:
      description: |
        [Reorder or replace a Playlist's Tracks](https://developer.spotify.com/web-api/reorder-playlists-tracks/)