# coding: utf-8

"""
    QnAMaker Runtime Client

    An API for QnAMaker runtime

    The version of the OpenAPI document: 4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.metadata_dto import MetadataDTO

class TestMetadataDTO(unittest.TestCase):
    """MetadataDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MetadataDTO:
        """Test MetadataDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MetadataDTO`
        """
        model = MetadataDTO()
        if include_optional:
            return MetadataDTO(
                name = '0',
                value = '0'
            )
        else:
            return MetadataDTO(
                name = '0',
                value = '0',
        )
        """

    def testMetadataDTO(self):
        """Test MetadataDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
