# coding: utf-8

"""
    StorageManagementClient

    The Admin Storage Management Client.

    The version of the OpenAPI document: 2015-12-01-preview
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.farms_list_metric_definitions200_response_value_inner_metric_availabilities_inner import FarmsListMetricDefinitions200ResponseValueInnerMetricAvailabilitiesInner

class TestFarmsListMetricDefinitions200ResponseValueInnerMetricAvailabilitiesInner(unittest.TestCase):
    """FarmsListMetricDefinitions200ResponseValueInnerMetricAvailabilitiesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FarmsListMetricDefinitions200ResponseValueInnerMetricAvailabilitiesInner:
        """Test FarmsListMetricDefinitions200ResponseValueInnerMetricAvailabilitiesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FarmsListMetricDefinitions200ResponseValueInnerMetricAvailabilitiesInner`
        """
        model = FarmsListMetricDefinitions200ResponseValueInnerMetricAvailabilitiesInner()
        if include_optional:
            return FarmsListMetricDefinitions200ResponseValueInnerMetricAvailabilitiesInner(
                retention = '',
                time_grain = ''
            )
        else:
            return FarmsListMetricDefinitions200ResponseValueInnerMetricAvailabilitiesInner(
        )
        """

    def testFarmsListMetricDefinitions200ResponseValueInnerMetricAvailabilitiesInner(self):
        """Test FarmsListMetricDefinitions200ResponseValueInnerMetricAvailabilitiesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
