from .accessibility import *
from .alarmvolume import *
from .appdeviceid import *
from .changediscoverability import *
from .checkreadystatus import *
from .chromecasticon import *
from .connecttowi_finetwork import *
from .deletealarmsandtimers import *
from .donotdisturb import *
from .eurekainfo import *
from .forgetpaireddevice import *
from .forgetwi_finetwork import *
from .getalarmsandtimers import *
from .getpaireddevices import *
from .getsavednetworks import *
from .getscanresults import *
from .getwi_fiscanresults import *
from .legalnotice import *
from .locales import *
from .nightmodesettings import *
from .offer import *
from .pairwithspeaker import *
from .rebootandfactoryreset import *
from .scanfordevices import *
from .scanfornetworks import *
from .setequalizervalues import *
from .seteurekainfo import *
from .status import *
from .testinternetdownloadspeed import *
from .timezones import *
