openapi: 3.0.1
servers:
  - url: https://api.hubapi.com
info:
  description: |
    These APIs allow you to interact with HubSpot's Marketing Events Extension. It allows you to:
    * Create, Read or update Marketing Event information in HubSpot
    * Specify whether a HubSpot contact has registered, attended or cancelled a registration to a Marketing Event.
    * Specify a URL that can be called to get the details of a Marketing Event.
  title: Marketing Events
  version: v3
  x-hubspot-api-use-case: You have an external system that handles registration for your webinars and you want to ensure that attendee data and behavior is synced with your HubSpot CRM.
  x-hubspot-documentation-banner: NONE
  x-hubspot-introduction: The marketing events API allows you to build a custom integration that will sync event and registration data with your HubSpot account.The marketing events API allows you to build a custom integration that will sync event and registration data with your HubSpot account.
  x-hubspot-product-tier-requirements:
    cms: STARTER
    marketing: FREE
  x-hubspot-related-documentation:
    - name: Marketing Events Guide
      url: https://hubspot.dev/guides/api/marketing/marketing-events
  x-logo:
    url: https://developers.hubspot.com/hubfs/assets/hubspot.com/buzz/HubSpotOpenGraph.png
  x-origin:
    - format: openapi
      url: https://api.hubspot.com/api-catalog-public/v1/apis/marketing/v3/marketing-events-beta
      version: "3.0"
  x-providerName: hubapi.com
  x-serviceName: marketing
tags:
  - description: ""
    name: Batch
    x-hubspot-tag-name-english-source: Batch
  - description: ""
    name: Attendance Subscriber State Changes
    x-hubspot-tag-name-english-source: Attendance Subscriber State Changes
  - description: ""
    name: Subscriber State Changes
    x-hubspot-tag-name-english-source: Subscriber State Changes
  - description: ""
    name: Marketing_Events_External
    x-hubspot-tag-name-english-source: Marketing_Events_External
  - description: ""
    name: Basic
    x-hubspot-tag-name-english-source: Basic
  - description: ""
    name: Settings
    x-hubspot-tag-name-english-source: Settings
  - description: ""
    name: Search
    x-hubspot-tag-name-english-source: Search
paths:
  /marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create:
    post:
      description: Record a subscription state between multiple HubSpot contacts and a marketing event, using HubSpot contact ids.
      operationId: post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create_create
      security:
        - private_apps_legacy: []
        - oauth2_legacy:
            - crm.objects.marketing_events.write
      summary: Record
      tags:
        - Attendance Subscriber State Changes
  /marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create:
    post:
      description: Record a subscription state between multiple HubSpot contacts and a marketing event, using contact email addresses. If contact is not present it will be automatically created.
      operationId: post-/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/email-create_createByEmail
      security:
        - private_apps_legacy: []
        - oauth2_legacy:
            - crm.objects.marketing_events.write
      summary: Record
      tags:
        - Attendance Subscriber State Changes
  /marketing/v3/marketing-events/events:
    post:
      description: Creates a new marketing event in HubSpot
      operationId: post-/marketing/v3/marketing-events/events_create
      security:
        - private_apps_legacy: []
        - oauth2_legacy:
            - crm.objects.marketing_events.write
      summary: Create a marketing event
      tags:
        - Basic
  /marketing/v3/marketing-events/events/delete:
    post:
      description: Bulk delete a number of marketing events in HubSpot
      operationId: post-/marketing/v3/marketing-events/events/delete_archive
      security:
        - private_apps_legacy: []
        - oauth2_legacy:
            - crm.objects.marketing_events.write
      summary: Delete multiple marketing events
      tags:
        - Batch
  /marketing/v3/marketing-events/events/search:
    get:
      description: Search for marketing events that have an event id that starts with the query string
      operationId: get-/marketing/v3/marketing-events/events/search_doSearch
      security:
        - oauth2_legacy:
            - crm.objects.marketing_events.read
        - private_apps_legacy: []
      summary: Search for marketing events
      tags:
        - Search
  /marketing/v3/marketing-events/events/upsert:
    post:
      description: Upset multiple Marketing Event. If there is an existing Marketing event with the specified id, it will be updated; otherwise a new event will be created.
      operationId: post-/marketing/v3/marketing-events/events/upsert_doUpsert
      security:
        - private_apps_legacy: []
        - oauth2_legacy:
            - crm.objects.marketing_events.write
      summary: Create or update multiple marketing events
      tags:
        - Batch
  /marketing/v3/marketing-events/events/{externalEventId}:
    delete:
      description: Deletes an existing Marketing Event with the specified id, if one exists.
      operationId: delete-/marketing/v3/marketing-events/events/{externalEventId}_archive
      security:
        - private_apps_legacy: []
        - oauth2_legacy:
            - crm.objects.marketing_events.write
      summary: Delete a marketing event
      tags:
        - Basic
    get:
      description: Returns the details of the Marketing Event with the specified id, if one exists.
      operationId: get-/marketing/v3/marketing-events/events/{externalEventId}_getById
      security:
        - oauth2_legacy:
            - crm.objects.marketing_events.read
        - private_apps_legacy: []
      summary: Get a marketing event
      tags:
        - Basic
    patch:
      description: Updates an existing Marketing Event with the specified id, if one exists.
      operationId: patch-/marketing/v3/marketing-events/events/{externalEventId}_update
      security:
        - private_apps_legacy: []
        - oauth2_legacy:
            - crm.objects.marketing_events.write
      summary: Update a marketing event
      tags:
        - Basic
    put:
      description: Upsets a Marketing Event. If there is an existing Marketing event with the specified id, it will be updated; otherwise a new event will be created.
      operationId: put-/marketing/v3/marketing-events/events/{externalEventId}_replace
      security:
        - private_apps_legacy: []
        - oauth2_legacy:
            - crm.objects.marketing_events.write
      summary: Create or update a marketing event
      tags:
        - Basic
  /marketing/v3/marketing-events/events/{externalEventId}/cancel:
    post:
      description: Mark a marketing event as cancelled.
      operationId: post-/marketing/v3/marketing-events/events/{externalEventId}/cancel_doCancel
      security:
        - private_apps_legacy: []
        - oauth2_legacy:
            - crm.objects.marketing_events.write
      summary: Mark a marketing event as cancelled
      tags:
        - Basic
  /marketing/v3/marketing-events/events/{externalEventId}/complete:
    post:
      operationId: post-/marketing/v3/marketing-events/events/{externalEventId}/complete_complete
      security:
        - private_apps_legacy: []
        - oauth2_legacy:
            - crm.objects.marketing_events.write
      tags:
        - Marketing_Events_External
  /marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert:
    post:
      description: Record a subscription state between multiple HubSpot contacts and a marketing event, using contact email addresses. Note that the contact must already exist in HubSpot; a contact will not be created.
      operationId: post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/email-upsert_doEmailUpsertById
      security:
        - private_apps_legacy: []
        - oauth2_legacy:
            - crm.objects.marketing_events.write
      summary: Record
      tags:
        - Subscriber State Changes
  /marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert:
    post:
      description: Record a subscription state between multiple HubSpot contacts and a marketing event, using HubSpot contact ids. Note that the contact must already exist in HubSpot; a contact will not be create.
      operationId: post-/marketing/v3/marketing-events/events/{externalEventId}/{subscriberState}/upsert_doUpsertById
      security:
        - private_apps_legacy: []
        - oauth2_legacy:
            - crm.objects.marketing_events.write
      summary: Record
      tags:
        - Subscriber State Changes
  /marketing/v3/marketing-events/{appId}/settings:
    get:
      description: Retrieve the current settings for the application.
      operationId: get-/marketing/v3/marketing-events/{appId}/settings_getAll
      security:
        - developer_hapikey: []
      summary: Retrieve the application settings
      tags:
        - Settings
    post:
      description: Create or update the current settings for the application.
      operationId: post-/marketing/v3/marketing-events/{appId}/settings_create
      security:
        - developer_hapikey: []
      summary: Update the application settings
      tags:
        - Settings
components:
  securitySchemes:
    developer_hapikey:
      in: query
      name: hapikey
      type: apiKey
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.marketing_events.read: Read marketing events
            crm.objects.marketing_events.write: Write marketing events
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
x-hubspot-available-client-libraries:
  - PHP
  - Node
  - Ruby
  - Python
x-hubspot-documentation-banner: NONE
x-hubspot-product-tier-requirements:
  cms: STARTER
  marketing: FREE
