package shared

type ArtistsVideoSearchFieldValuesEnum string

const (
	ArtistsVideoSearchFieldValuesEnumID                   ArtistsVideoSearchFieldValuesEnum = "id"
	ArtistsVideoSearchFieldValuesEnumAllowedUse           ArtistsVideoSearchFieldValuesEnum = "allowed_use"
	ArtistsVideoSearchFieldValuesEnumAlternativeIds       ArtistsVideoSearchFieldValuesEnum = "alternative_ids"
	ArtistsVideoSearchFieldValuesEnumArtist               ArtistsVideoSearchFieldValuesEnum = "artist"
	ArtistsVideoSearchFieldValuesEnumAssetFamily          ArtistsVideoSearchFieldValuesEnum = "asset_family"
	ArtistsVideoSearchFieldValuesEnumAssetType            ArtistsVideoSearchFieldValuesEnum = "asset_type"
	ArtistsVideoSearchFieldValuesEnumCallForImage         ArtistsVideoSearchFieldValuesEnum = "call_for_image"
	ArtistsVideoSearchFieldValuesEnumCaption              ArtistsVideoSearchFieldValuesEnum = "caption"
	ArtistsVideoSearchFieldValuesEnumClipLength           ArtistsVideoSearchFieldValuesEnum = "clip_length"
	ArtistsVideoSearchFieldValuesEnumCollectionID         ArtistsVideoSearchFieldValuesEnum = "collection_id"
	ArtistsVideoSearchFieldValuesEnumCollectionCode       ArtistsVideoSearchFieldValuesEnum = "collection_code"
	ArtistsVideoSearchFieldValuesEnumCollectionName       ArtistsVideoSearchFieldValuesEnum = "collection_name"
	ArtistsVideoSearchFieldValuesEnumComp                 ArtistsVideoSearchFieldValuesEnum = "comp"
	ArtistsVideoSearchFieldValuesEnumCopyright            ArtistsVideoSearchFieldValuesEnum = "copyright"
	ArtistsVideoSearchFieldValuesEnumDateCreated          ArtistsVideoSearchFieldValuesEnum = "date_created"
	ArtistsVideoSearchFieldValuesEnumDateSubmitted        ArtistsVideoSearchFieldValuesEnum = "date_submitted"
	ArtistsVideoSearchFieldValuesEnumDetailSet            ArtistsVideoSearchFieldValuesEnum = "detail_set"
	ArtistsVideoSearchFieldValuesEnumDisplaySet           ArtistsVideoSearchFieldValuesEnum = "display_set"
	ArtistsVideoSearchFieldValuesEnumEditorialSegments    ArtistsVideoSearchFieldValuesEnum = "editorial_segments"
	ArtistsVideoSearchFieldValuesEnumEventIds             ArtistsVideoSearchFieldValuesEnum = "event_ids"
	ArtistsVideoSearchFieldValuesEnumGraphicalStyle       ArtistsVideoSearchFieldValuesEnum = "graphical_style"
	ArtistsVideoSearchFieldValuesEnumHighResComp          ArtistsVideoSearchFieldValuesEnum = "high_res_comp"
	ArtistsVideoSearchFieldValuesEnumKeywords             ArtistsVideoSearchFieldValuesEnum = "keywords"
	ArtistsVideoSearchFieldValuesEnumLicenseModel         ArtistsVideoSearchFieldValuesEnum = "license_model"
	ArtistsVideoSearchFieldValuesEnumMaxDimensions        ArtistsVideoSearchFieldValuesEnum = "max_dimensions"
	ArtistsVideoSearchFieldValuesEnumMidResComp           ArtistsVideoSearchFieldValuesEnum = "mid_res_comp"
	ArtistsVideoSearchFieldValuesEnumOrientation          ArtistsVideoSearchFieldValuesEnum = "orientation"
	ArtistsVideoSearchFieldValuesEnumPreview              ArtistsVideoSearchFieldValuesEnum = "preview"
	ArtistsVideoSearchFieldValuesEnumProductTypes         ArtistsVideoSearchFieldValuesEnum = "product_types"
	ArtistsVideoSearchFieldValuesEnumQualityRank          ArtistsVideoSearchFieldValuesEnum = "quality_rank"
	ArtistsVideoSearchFieldValuesEnumReferralDestinations ArtistsVideoSearchFieldValuesEnum = "referral_destinations"
	ArtistsVideoSearchFieldValuesEnumSummarySet           ArtistsVideoSearchFieldValuesEnum = "summary_set"
	ArtistsVideoSearchFieldValuesEnumThumb                ArtistsVideoSearchFieldValuesEnum = "thumb"
	ArtistsVideoSearchFieldValuesEnumTitle                ArtistsVideoSearchFieldValuesEnum = "title"
)
