package shared

type CreativeImagesFieldValuesEnum string

const (
	CreativeImagesFieldValuesEnumAllowedUse           CreativeImagesFieldValuesEnum = "allowed_use"
	CreativeImagesFieldValuesEnumAlternativeIds       CreativeImagesFieldValuesEnum = "alternative_ids"
	CreativeImagesFieldValuesEnumArtist               CreativeImagesFieldValuesEnum = "artist"
	CreativeImagesFieldValuesEnumAssetFamily          CreativeImagesFieldValuesEnum = "asset_family"
	CreativeImagesFieldValuesEnumCallForImage         CreativeImagesFieldValuesEnum = "call_for_image"
	CreativeImagesFieldValuesEnumCaption              CreativeImagesFieldValuesEnum = "caption"
	CreativeImagesFieldValuesEnumCollectionCode       CreativeImagesFieldValuesEnum = "collection_code"
	CreativeImagesFieldValuesEnumCollectionID         CreativeImagesFieldValuesEnum = "collection_id"
	CreativeImagesFieldValuesEnumCollectionName       CreativeImagesFieldValuesEnum = "collection_name"
	CreativeImagesFieldValuesEnumColorType            CreativeImagesFieldValuesEnum = "color_type"
	CreativeImagesFieldValuesEnumComp                 CreativeImagesFieldValuesEnum = "comp"
	CreativeImagesFieldValuesEnumCopyright            CreativeImagesFieldValuesEnum = "copyright"
	CreativeImagesFieldValuesEnumDateCameraShot       CreativeImagesFieldValuesEnum = "date_camera_shot"
	CreativeImagesFieldValuesEnumDateCreated          CreativeImagesFieldValuesEnum = "date_created"
	CreativeImagesFieldValuesEnumDateSubmitted        CreativeImagesFieldValuesEnum = "date_submitted"
	CreativeImagesFieldValuesEnumDetailSet            CreativeImagesFieldValuesEnum = "detail_set"
	CreativeImagesFieldValuesEnumDisplaySet           CreativeImagesFieldValuesEnum = "display_set"
	CreativeImagesFieldValuesEnumDownloadProduct      CreativeImagesFieldValuesEnum = "download_product"
	CreativeImagesFieldValuesEnumDownloadSizes        CreativeImagesFieldValuesEnum = "download_sizes"
	CreativeImagesFieldValuesEnumGraphicalStyle       CreativeImagesFieldValuesEnum = "graphical_style"
	CreativeImagesFieldValuesEnumID                   CreativeImagesFieldValuesEnum = "id"
	CreativeImagesFieldValuesEnumIstockCollection     CreativeImagesFieldValuesEnum = "istock_collection"
	CreativeImagesFieldValuesEnumKeywords             CreativeImagesFieldValuesEnum = "keywords"
	CreativeImagesFieldValuesEnumLargestDownloads     CreativeImagesFieldValuesEnum = "largest_downloads"
	CreativeImagesFieldValuesEnumLicenseModel         CreativeImagesFieldValuesEnum = "license_model"
	CreativeImagesFieldValuesEnumMaxDimensions        CreativeImagesFieldValuesEnum = "max_dimensions"
	CreativeImagesFieldValuesEnumOrientation          CreativeImagesFieldValuesEnum = "orientation"
	CreativeImagesFieldValuesEnumPreview              CreativeImagesFieldValuesEnum = "preview"
	CreativeImagesFieldValuesEnumProductTypes         CreativeImagesFieldValuesEnum = "product_types"
	CreativeImagesFieldValuesEnumQualityRank          CreativeImagesFieldValuesEnum = "quality_rank"
	CreativeImagesFieldValuesEnumReferralDestinations CreativeImagesFieldValuesEnum = "referral_destinations"
	CreativeImagesFieldValuesEnumSummarySet           CreativeImagesFieldValuesEnum = "summary_set"
	CreativeImagesFieldValuesEnumThumb                CreativeImagesFieldValuesEnum = "thumb"
	CreativeImagesFieldValuesEnumTitle                CreativeImagesFieldValuesEnum = "title"
	CreativeImagesFieldValuesEnumURIOembed            CreativeImagesFieldValuesEnum = "uri_oembed"
)
