package shared

type EditorialVideosFieldValuesEnum string

const (
	EditorialVideosFieldValuesEnumAllowedUse           EditorialVideosFieldValuesEnum = "allowed_use"
	EditorialVideosFieldValuesEnumArtist               EditorialVideosFieldValuesEnum = "artist"
	EditorialVideosFieldValuesEnumAspectRatio          EditorialVideosFieldValuesEnum = "aspect_ratio"
	EditorialVideosFieldValuesEnumAssetFamily          EditorialVideosFieldValuesEnum = "asset_family"
	EditorialVideosFieldValuesEnumCallForImage         EditorialVideosFieldValuesEnum = "call_for_image"
	EditorialVideosFieldValuesEnumCaption              EditorialVideosFieldValuesEnum = "caption"
	EditorialVideosFieldValuesEnumClipLength           EditorialVideosFieldValuesEnum = "clip_length"
	EditorialVideosFieldValuesEnumCollectionCode       EditorialVideosFieldValuesEnum = "collection_code"
	EditorialVideosFieldValuesEnumCollectionID         EditorialVideosFieldValuesEnum = "collection_id"
	EditorialVideosFieldValuesEnumCollectionName       EditorialVideosFieldValuesEnum = "collection_name"
	EditorialVideosFieldValuesEnumColorType            EditorialVideosFieldValuesEnum = "color_type"
	EditorialVideosFieldValuesEnumComp                 EditorialVideosFieldValuesEnum = "comp"
	EditorialVideosFieldValuesEnumCopyright            EditorialVideosFieldValuesEnum = "copyright"
	EditorialVideosFieldValuesEnumDateCreated          EditorialVideosFieldValuesEnum = "date_created"
	EditorialVideosFieldValuesEnumDateSubmitted        EditorialVideosFieldValuesEnum = "date_submitted"
	EditorialVideosFieldValuesEnumDetailSet            EditorialVideosFieldValuesEnum = "detail_set"
	EditorialVideosFieldValuesEnumDisplaySet           EditorialVideosFieldValuesEnum = "display_set"
	EditorialVideosFieldValuesEnumDownloadProduct      EditorialVideosFieldValuesEnum = "download_product"
	EditorialVideosFieldValuesEnumDownloadSizes        EditorialVideosFieldValuesEnum = "download_sizes"
	EditorialVideosFieldValuesEnumEditorialSegments    EditorialVideosFieldValuesEnum = "editorial_segments"
	EditorialVideosFieldValuesEnumEntityDetails        EditorialVideosFieldValuesEnum = "entity_details"
	EditorialVideosFieldValuesEnumEra                  EditorialVideosFieldValuesEnum = "era"
	EditorialVideosFieldValuesEnumEventIds             EditorialVideosFieldValuesEnum = "event_ids"
	EditorialVideosFieldValuesEnumID                   EditorialVideosFieldValuesEnum = "id"
	EditorialVideosFieldValuesEnumIstockCollection     EditorialVideosFieldValuesEnum = "istock_collection"
	EditorialVideosFieldValuesEnumKeywords             EditorialVideosFieldValuesEnum = "keywords"
	EditorialVideosFieldValuesEnumLargestDownloads     EditorialVideosFieldValuesEnum = "largest_downloads"
	EditorialVideosFieldValuesEnumLicenseModel         EditorialVideosFieldValuesEnum = "license_model"
	EditorialVideosFieldValuesEnumMasteredTo           EditorialVideosFieldValuesEnum = "mastered_to"
	EditorialVideosFieldValuesEnumObjectName           EditorialVideosFieldValuesEnum = "object_name"
	EditorialVideosFieldValuesEnumOrientation          EditorialVideosFieldValuesEnum = "orientation"
	EditorialVideosFieldValuesEnumOriginallyShotOn     EditorialVideosFieldValuesEnum = "originally_shot_on"
	EditorialVideosFieldValuesEnumPreview              EditorialVideosFieldValuesEnum = "preview"
	EditorialVideosFieldValuesEnumProductTypes         EditorialVideosFieldValuesEnum = "product_types"
	EditorialVideosFieldValuesEnumQualityRank          EditorialVideosFieldValuesEnum = "quality_rank"
	EditorialVideosFieldValuesEnumReferralDestinations EditorialVideosFieldValuesEnum = "referral_destinations"
	EditorialVideosFieldValuesEnumShotSpeed            EditorialVideosFieldValuesEnum = "shot_speed"
	EditorialVideosFieldValuesEnumSource               EditorialVideosFieldValuesEnum = "source"
	EditorialVideosFieldValuesEnumSummarySet           EditorialVideosFieldValuesEnum = "summary_set"
	EditorialVideosFieldValuesEnumThumb                EditorialVideosFieldValuesEnum = "thumb"
	EditorialVideosFieldValuesEnumTitle                EditorialVideosFieldValuesEnum = "title"
	EditorialVideosFieldValuesEnumIstockLicenses       EditorialVideosFieldValuesEnum = "istock_licenses"
)
