swagger: '2.0'
schemes:
  - https
host: slack.com
basePath: /api
info:
  description: 'One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.'
  title: Slack
  version: 1.0.4
  x-apisguru-categories:
    - collaboration
    - messaging
  x-logo:
    url: 'http://static.tumblr.com/wvuzcz9/LlKncfhmp/slack_logo_240.png'
  x-origin:
    - format: swagger
      url: 'https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2.json'
      version: '2.0'
  x-providerName: slack.com
securityDefinitions:
  slackAuth:
    authorizationUrl: 'https://slack.com/oauth/authorize'
    flow: accessCode
    scopes:
      admin: admin
      bot: Bot user scope
      'channels:history': 'channels:history'
      'channels:read': 'channels:read'
      'channels:write': 'channels:write'
      'chat:write': 'chat:write'
      'chat:write:bot': Author messages as a bot
      'chat:write:user': 'chat:write:user'
      'conversations:history': 'conversations:history'
      'conversations:read': 'conversations:read'
      'conversations:write': 'conversations:write'
      'dnd:read': 'dnd:read'
      'dnd:write': 'dnd:write'
      'emoji:read': 'emoji:read'
      'files:read': 'files:read'
      'files:write:user': 'files:write:user'
      'groups:history': 'groups:history'
      'groups:read': 'groups:read'
      'groups:write': 'groups:write'
      identity.basic: identity.basic
      'im:history': 'im:history'
      'im:read': 'im:read'
      'im:write': 'im:write'
      'links:write': 'links:write'
      'mpim:history': 'mpim:history'
      'mpim:read': 'mpim:read'
      'mpim:write': 'mpim:write'
      none: No scope required
      'pins:read': 'pins:read'
      'pins:write': 'pins:write'
      'reactions:read': 'reactions:read'
      'reactions:write': 'reactions:write'
      'reminders:read': 'reminders:read'
      'reminders:write': 'reminders:write'
      'rtm:stream': 'rtm:stream'
      'search:read': 'search:read'
      'stars:read': 'stars:read'
      'stars:write': 'stars:write'
      'team:read': 'team:read'
      tokens.basic: tokens.basic
      'usergroups:read': 'usergroups:read'
      'usergroups:write': 'usergroups:write'
      'users.profile:read': 'users.profile:read'
      'users.profile:write': 'users.profile:write'
      'users:read': 'users:read'
      'users:read.email': 'users:read.email'
      'users:write': 'users:write'
    tokenUrl: 'https://slack.com/api/oauth.access'
    type: oauth2
paths:
  /api.test:
    get:
      description: Checks API calling code.
      operationId: api_test
      security:
        - slackAuth:
            - none
      tags:
        - api
  /apps.permissions.info:
    get:
      description: Returns list of permissions this app has on a team.
      operationId: apps_permissions_info
      security:
        - slackAuth:
            - none
      tags:
        - apps.permissions
        - apps
  /apps.permissions.request:
    get:
      description: Allows an app to request additional scopes
      operationId: apps_permissions_request
      security:
        - slackAuth:
            - none
      tags:
        - apps.permissions
        - apps
  /auth.revoke:
    get:
      description: Revokes a token.
      operationId: auth_revoke
      security:
        - slackAuth:
            - none
      tags:
        - auth
  /auth.test:
    get:
      description: Checks authentication & identity.
      operationId: auth_test
      security:
        - slackAuth:
            - none
      tags:
        - auth
  /bots.info:
    get:
      description: Gets information about a bot user.
      operationId: bots_info
      security:
        - slackAuth:
            - 'users:read'
      tags:
        - bots
  /channels.archive:
    post:
      description: Archives a channel.
      operationId: channels_archive
      security:
        - slackAuth:
            - 'channels:write'
      tags:
        - channels
  /channels.create:
    post:
      description: Creates a channel.
      operationId: channels_create
      security:
        - slackAuth:
            - 'channels:write'
      tags:
        - channels
  /channels.history:
    get:
      description: Fetches history of messages and events from a channel.
      operationId: channels_history
      security:
        - slackAuth:
            - 'channels:history'
      tags:
        - channels
  /channels.info:
    get:
      description: Gets information about a channel.
      operationId: channels_info
      security:
        - slackAuth:
            - 'channels:read'
      tags:
        - channels
  /channels.invite:
    post:
      description: Invites a user to a channel.
      operationId: channels_invite
      security:
        - slackAuth:
            - 'channels:write'
      tags:
        - channels
  /channels.join:
    post:
      description: 'Joins a channel, creating it if needed.'
      operationId: channels_join
      security:
        - slackAuth:
            - 'channels:write'
      tags:
        - channels
  /channels.kick:
    post:
      description: Removes a user from a channel.
      operationId: channels_kick
      security:
        - slackAuth:
            - 'channels:write'
      tags:
        - channels
  /channels.leave:
    post:
      description: Leaves a channel.
      operationId: channels_leave
      security:
        - slackAuth:
            - 'channels:write'
      tags:
        - channels
  /channels.list:
    get:
      description: Lists all channels in a Slack team.
      operationId: channels_list
      security:
        - slackAuth:
            - 'channels:read'
      tags:
        - channels
  /channels.mark:
    post:
      description: Sets the read cursor in a channel.
      operationId: channels_mark
      security:
        - slackAuth:
            - 'channels:write'
      tags:
        - channels
  /channels.rename:
    post:
      description: Renames a channel.
      operationId: channels_rename
      security:
        - slackAuth:
            - 'channels:write'
      tags:
        - channels
  /channels.replies:
    get:
      description: Retrieve a thread of messages posted to a channel
      operationId: channels_replies
      security:
        - slackAuth:
            - 'channels:history'
      tags:
        - channels
  /channels.setPurpose:
    post:
      description: Sets the purpose for a channel.
      operationId: channels_setPurpose
      security:
        - slackAuth:
            - 'channels:write'
      tags:
        - channels
  /channels.setTopic:
    post:
      description: Sets the topic for a channel.
      operationId: channels_setTopic
      security:
        - slackAuth:
            - 'channels:write'
      tags:
        - channels
  /channels.unarchive:
    post:
      description: Unarchives a channel.
      operationId: channels_unarchive
      security:
        - slackAuth:
            - 'channels:write'
      tags:
        - channels
  /chat.delete:
    post:
      description: Deletes a message.
      operationId: chat_delete
      security:
        - slackAuth:
            - 'chat:write:user'
            - 'chat:write:bot'
      tags:
        - chat
  /chat.getPermalink:
    get:
      description: Retrieve a permalink URL for a specific extant message
      operationId: chat_getPermalink
      security:
        - slackAuth:
            - none
      tags:
        - chat
  /chat.meMessage:
    post:
      description: Share a me message into a channel.
      operationId: chat_meMessage
      security:
        - slackAuth:
            - 'chat:write:user'
      tags:
        - chat
  /chat.postEphemeral:
    post:
      description: Sends an ephemeral message to a user in a channel.
      operationId: chat_postEphemeral
      security:
        - slackAuth:
            - 'chat:write:user'
            - 'chat:write:bot'
      tags:
        - chat
  /chat.postMessage:
    post:
      description: Sends a message to a channel.
      operationId: chat_postMessage
      security:
        - slackAuth:
            - 'chat:write:user'
            - 'chat:write:bot'
      tags:
        - chat
  /chat.unfurl:
    post:
      description: Provide custom unfurl behavior for user-posted URLs
      operationId: chat_unfurl
      security:
        - slackAuth:
            - 'links:write'
      tags:
        - chat
  /chat.update:
    post:
      description: Updates a message.
      operationId: chat_update
      security:
        - slackAuth:
            - 'chat:write:user'
            - 'chat:write:bot'
      tags:
        - chat
  /conversations.archive:
    post:
      description: Archives a conversation.
      operationId: conversations_archive
      security:
        - slackAuth:
            - 'channels:write'
            - 'groups:write'
            - 'im:write'
            - 'mpim:write'
      tags:
        - conversations
  /conversations.close:
    post:
      description: Closes a direct message or multi-person direct message.
      operationId: conversations_close
      security:
        - slackAuth:
            - 'channels:write'
            - 'groups:write'
            - 'im:write'
            - 'mpim:write'
      tags:
        - conversations
  /conversations.create:
    post:
      description: Initiates a public or private channel-based conversation
      operationId: conversations_create
      security:
        - slackAuth:
            - 'channels:write'
            - 'groups:write'
            - 'im:write'
            - 'mpim:write'
      tags:
        - conversations
  /conversations.history:
    get:
      description: Fetches a conversation's history of messages and events.
      operationId: conversations_history
      security:
        - slackAuth:
            - 'channels:history'
            - 'groups:history'
            - 'im:history'
            - 'mpim:history'
      tags:
        - conversations
  /conversations.info:
    get:
      description: Retrieve information about a conversation.
      operationId: conversations_info
      security:
        - slackAuth:
            - 'channels:read'
            - 'groups:read'
            - 'im:read'
            - 'mpim:read'
      tags:
        - conversations
  /conversations.invite:
    post:
      description: Invites users to a channel.
      operationId: conversations_invite
      security:
        - slackAuth:
            - 'channels:write'
            - 'groups:write'
            - 'im:write'
            - 'mpim:write'
      tags:
        - conversations
  /conversations.join:
    post:
      description: Joins an existing conversation.
      operationId: conversations_join
      security:
        - slackAuth:
            - 'channels:write'
      tags:
        - conversations
  /conversations.kick:
    post:
      description: Removes a user from a conversation.
      operationId: conversations_kick
      security:
        - slackAuth:
            - 'channels:write'
            - 'groups:write'
            - 'im:write'
            - 'mpim:write'
      tags:
        - conversations
  /conversations.leave:
    post:
      description: Leaves a conversation.
      operationId: conversations_leave
      security:
        - slackAuth:
            - 'channels:write'
            - 'groups:write'
            - 'im:write'
            - 'mpim:write'
      tags:
        - conversations
  /conversations.list:
    get:
      description: Lists all channels in a Slack team.
      operationId: conversations_list
      security:
        - slackAuth:
            - 'channels:read'
            - 'groups:read'
            - 'im:read'
            - 'mpim:read'
      tags:
        - conversations
  /conversations.members:
    get:
      description: Retrieve members of a conversation.
      operationId: conversations_members
      security:
        - slackAuth:
            - 'channels:read'
            - 'groups:read'
            - 'im:read'
            - 'mpim:read'
      tags:
        - conversations
  /conversations.open:
    post:
      description: Opens or resumes a direct message or multi-person direct message.
      operationId: conversations_open
      security:
        - slackAuth:
            - 'channels:write'
            - 'groups:write'
            - 'im:write'
            - 'mpim:write'
      tags:
        - conversations
  /conversations.rename:
    post:
      description: Renames a conversation.
      operationId: conversations_rename
      security:
        - slackAuth:
            - 'channels:write'
            - 'groups:write'
            - 'im:write'
            - 'mpim:write'
      tags:
        - conversations
  /conversations.replies:
    get:
      description: Retrieve a thread of messages posted to a conversation
      operationId: conversations_replies
      security:
        - slackAuth:
            - 'channels:history'
            - 'groups:history'
            - 'im:history'
            - 'mpim:history'
      tags:
        - conversations
  /conversations.setPurpose:
    post:
      description: Sets the purpose for a conversation.
      operationId: conversations_setPurpose
      security:
        - slackAuth:
            - 'channels:write'
            - 'groups:write'
            - 'im:write'
            - 'mpim:write'
      tags:
        - conversations
  /conversations.setTopic:
    post:
      description: Sets the topic for a conversation.
      operationId: conversations_setTopic
      security:
        - slackAuth:
            - 'channels:write'
            - 'groups:write'
            - 'im:write'
            - 'mpim:write'
      tags:
        - conversations
  /conversations.unarchive:
    post:
      description: Reverses conversation archival.
      operationId: conversations_unarchive
      security:
        - slackAuth:
            - 'channels:write'
            - 'groups:write'
            - 'im:write'
            - 'mpim:write'
      tags:
        - conversations
  /dialog.open:
    get:
      description: Open a dialog with a user
      operationId: dialog_open
      security:
        - slackAuth:
            - none
      tags:
        - dialog
  /dnd.endDnd:
    post:
      description: Ends the current user's Do Not Disturb session immediately.
      operationId: dnd_endDnd
      security:
        - slackAuth:
            - 'dnd:write'
      tags:
        - dnd
  /dnd.endSnooze:
    post:
      description: Ends the current user's snooze mode immediately.
      operationId: dnd_endSnooze
      security:
        - slackAuth:
            - 'dnd:write'
      tags:
        - dnd
  /dnd.info:
    get:
      description: Retrieves a user's current Do Not Disturb status.
      operationId: dnd_info
      security:
        - slackAuth:
            - 'dnd:read'
      tags:
        - dnd
  /dnd.setSnooze:
    post:
      description: 'Turns on Do Not Disturb mode for the current user, or changes its duration.'
      operationId: dnd_setSnooze
      security:
        - slackAuth:
            - 'dnd:write'
      tags:
        - dnd
  /dnd.teamInfo:
    get:
      description: Retrieves the Do Not Disturb status for users on a team.
      operationId: dnd_teamInfo
      security:
        - slackAuth:
            - 'dnd:read'
      tags:
        - dnd
  /emoji.list:
    get:
      description: Lists custom emoji for a team.
      operationId: emoji_list
      security:
        - slackAuth:
            - 'emoji:read'
      tags:
        - emoji
  /files.comments.add:
    post:
      description: Add a comment to an existing file.
      operationId: files_comments_add
      security:
        - slackAuth:
            - 'files:write:user'
      tags:
        - files.comments
        - files
  /files.comments.delete:
    post:
      description: Deletes an existing comment on a file.
      operationId: files_comments_delete
      security:
        - slackAuth:
            - 'files:write:user'
      tags:
        - files.comments
        - files
  /files.comments.edit:
    post:
      description: Edit an existing file comment.
      operationId: files_comments_edit
      security:
        - slackAuth:
            - 'files:write:user'
      tags:
        - files.comments
        - files
  /files.delete:
    post:
      description: Deletes a file.
      operationId: files_delete
      security:
        - slackAuth:
            - 'files:write:user'
      tags:
        - files
  /files.info:
    get:
      description: Gets information about a team file.
      operationId: files_info
      security:
        - slackAuth:
            - 'files:read'
      tags:
        - files
  /files.list:
    get:
      description: Lists & filters team files.
      operationId: files_list
      security:
        - slackAuth:
            - 'files:read'
      tags:
        - files
  /files.revokePublicURL:
    post:
      description: Revokes public/external sharing access for a file
      operationId: files_revokePublicURL
      security:
        - slackAuth:
            - 'files:write:user'
      tags:
        - files
  /files.sharedPublicURL:
    post:
      description: Enables a file for public/external sharing.
      operationId: files_sharedPublicURL
      security:
        - slackAuth:
            - 'files:write:user'
      tags:
        - files
  /files.upload:
    post:
      description: Uploads or creates a file.
      operationId: files_upload
      security:
        - slackAuth:
            - 'files:write:user'
      tags:
        - files
  /groups.archive:
    post:
      description: Archives a private channel.
      operationId: groups_archive
      security:
        - slackAuth:
            - 'groups:write'
      tags:
        - groups
  /groups.create:
    post:
      description: Creates a private channel.
      operationId: groups_create
      security:
        - slackAuth:
            - 'groups:write'
      tags:
        - groups
  /groups.createChild:
    post:
      description: Clones and archives a private channel.
      operationId: groups_createChild
      security:
        - slackAuth:
            - 'groups:write'
      tags:
        - groups
  /groups.history:
    get:
      description: Fetches history of messages and events from a private channel.
      operationId: groups_history
      security:
        - slackAuth:
            - 'groups:history'
      tags:
        - groups
  /groups.info:
    get:
      description: Gets information about a private channel.
      operationId: groups_info
      security:
        - slackAuth:
            - 'groups:read'
      tags:
        - groups
  /groups.invite:
    post:
      description: Invites a user to a private channel.
      operationId: groups_invite
      security:
        - slackAuth:
            - 'groups:write'
      tags:
        - groups
  /groups.kick:
    post:
      description: Removes a user from a private channel.
      operationId: groups_kick
      security:
        - slackAuth:
            - 'groups:write'
      tags:
        - groups
  /groups.leave:
    post:
      description: Leaves a private channel.
      operationId: groups_leave
      security:
        - slackAuth:
            - 'groups:write'
      tags:
        - groups
  /groups.list:
    get:
      description: Lists private channels that the calling user has access to.
      operationId: groups_list
      security:
        - slackAuth:
            - 'groups:read'
      tags:
        - groups
  /groups.mark:
    post:
      description: Sets the read cursor in a private channel.
      operationId: groups_mark
      security:
        - slackAuth:
            - 'groups:write'
      tags:
        - groups
  /groups.open:
    post:
      description: Opens a private channel.
      operationId: groups_open
      security:
        - slackAuth:
            - 'groups:write'
      tags:
        - groups
  /groups.rename:
    post:
      description: Renames a private channel.
      operationId: groups_rename
      security:
        - slackAuth:
            - 'groups:write'
      tags:
        - groups
  /groups.replies:
    get:
      description: Retrieve a thread of messages posted to a private channel
      operationId: groups_replies
      security:
        - slackAuth:
            - 'groups:history'
      tags:
        - groups
  /groups.setPurpose:
    post:
      description: Sets the purpose for a private channel.
      operationId: groups_setPurpose
      security:
        - slackAuth:
            - 'groups:write'
      tags:
        - groups
  /groups.setTopic:
    post:
      description: Sets the topic for a private channel.
      operationId: groups_setTopic
      security:
        - slackAuth:
            - 'groups:write'
      tags:
        - groups
  /groups.unarchive:
    post:
      description: Unarchives a private channel.
      operationId: groups_unarchive
      security:
        - slackAuth:
            - 'groups:write'
      tags:
        - groups
  /im.close:
    post:
      description: Close a direct message channel.
      operationId: im_close
      security:
        - slackAuth:
            - 'im:write'
      tags:
        - im
  /im.history:
    get:
      description: Fetches history of messages and events from direct message channel.
      operationId: im_history
      security:
        - slackAuth:
            - 'im:history'
      tags:
        - im
  /im.list:
    get:
      description: Lists direct message channels for the calling user.
      operationId: im_list
      security:
        - slackAuth:
            - 'im:read'
      tags:
        - im
  /im.mark:
    post:
      description: Sets the read cursor in a direct message channel.
      operationId: im_mark
      security:
        - slackAuth:
            - 'im:write'
      tags:
        - im
  /im.open:
    post:
      description: Opens a direct message channel.
      operationId: im_open
      security:
        - slackAuth:
            - 'im:write'
      tags:
        - im
  /im.replies:
    get:
      description: Retrieve a thread of messages posted to a direct message conversation
      operationId: im_replies
      security:
        - slackAuth:
            - 'im:history'
      tags:
        - im
  /migration.exchange:
    get:
      description: 'For Enterprise Grid workspaces, map local user IDs to global user IDs'
      operationId: migration_exchange
      security:
        - slackAuth:
            - tokens.basic
      tags:
        - migration
  /mpim.close:
    post:
      description: Closes a multiparty direct message channel.
      operationId: mpim_close
      security:
        - slackAuth:
            - 'mpim:write'
      tags:
        - mpim
  /mpim.history:
    get:
      description: Fetches history of messages and events from a multiparty direct message.
      operationId: mpim_history
      security:
        - slackAuth:
            - 'mpim:history'
      tags:
        - mpim
  /mpim.list:
    get:
      description: Lists multiparty direct message channels for the calling user.
      operationId: mpim_list
      security:
        - slackAuth:
            - 'mpim:read'
      tags:
        - mpim
  /mpim.mark:
    post:
      description: Sets the read cursor in a multiparty direct message channel.
      operationId: mpim_mark
      security:
        - slackAuth:
            - 'mpim:write'
      tags:
        - mpim
  /mpim.open:
    post:
      description: This method opens a multiparty direct message.
      operationId: mpim_open
      security:
        - slackAuth:
            - 'mpim:write'
      tags:
        - mpim
  /mpim.replies:
    get:
      description: Retrieve a thread of messages posted to a direct message conversation from a multiparty direct message.
      operationId: mpim_replies
      security:
        - slackAuth:
            - 'mpim:history'
      tags:
        - mpim
  /oauth.access:
    get:
      description: Exchanges a temporary OAuth code for an API token.
      operationId: oauth_access
      security:
        - slackAuth:
            - none
      tags:
        - oauth
  /oauth.token:
    get:
      description: Exchanges a temporary OAuth verifier code for a workspace token.
      operationId: oauth_token
      security:
        - slackAuth:
            - none
      tags:
        - oauth
  /pins.add:
    post:
      description: Pins an item to a channel.
      operationId: pins_add
      security:
        - slackAuth:
            - 'pins:write'
      tags:
        - pins
  /pins.list:
    get:
      description: Lists items pinned to a channel.
      operationId: pins_list
      security:
        - slackAuth:
            - 'pins:read'
      tags:
        - pins
  /pins.remove:
    post:
      description: Un-pins an item from a channel.
      operationId: pins_remove
      security:
        - slackAuth:
            - 'pins:write'
      tags:
        - pins
  /reactions.add:
    post:
      description: Adds a reaction to an item.
      operationId: reactions_add
      security:
        - slackAuth:
            - 'reactions:write'
      tags:
        - reactions
  /reactions.get:
    get:
      description: Gets reactions for an item.
      operationId: reactions_get
      security:
        - slackAuth:
            - 'reactions:read'
      tags:
        - reactions
  /reactions.list:
    get:
      description: Lists reactions made by a user.
      operationId: reactions_list
      security:
        - slackAuth:
            - 'reactions:read'
      tags:
        - reactions
  /reactions.remove:
    post:
      description: Removes a reaction from an item.
      operationId: reactions_remove
      security:
        - slackAuth:
            - 'reactions:write'
      tags:
        - reactions
  /reminders.add:
    post:
      description: Creates a reminder.
      operationId: reminders_add
      security:
        - slackAuth:
            - 'reminders:write'
      tags:
        - reminders
  /reminders.complete:
    post:
      description: Marks a reminder as complete.
      operationId: reminders_complete
      security:
        - slackAuth:
            - 'reminders:write'
      tags:
        - reminders
  /reminders.delete:
    post:
      description: Deletes a reminder.
      operationId: reminders_delete
      security:
        - slackAuth:
            - 'reminders:write'
      tags:
        - reminders
  /reminders.info:
    get:
      description: Gets information about a reminder.
      operationId: reminders_info
      security:
        - slackAuth:
            - 'reminders:read'
      tags:
        - reminders
  /reminders.list:
    get:
      description: Lists all reminders created by or for a given user.
      operationId: reminders_list
      security:
        - slackAuth:
            - 'reminders:read'
      tags:
        - reminders
  /rtm.connect:
    get:
      description: Starts a Real Time Messaging session.
      operationId: rtm_connect
      security:
        - slackAuth:
            - 'rtm:stream'
      tags:
        - rtm
  /rtm.start:
    get:
      description: Starts a Real Time Messaging session.
      operationId: rtm_start
      security:
        - slackAuth:
            - 'rtm:stream'
      tags:
        - rtm
  /search.all:
    get:
      description: Searches for messages and files matching a query.
      operationId: search_all
      security:
        - slackAuth:
            - 'search:read'
      tags:
        - search
  /search.files:
    get:
      description: Searches for files matching a query.
      operationId: search_files
      security:
        - slackAuth:
            - 'search:read'
      tags:
        - search
  /search.messages:
    get:
      description: Searches for messages matching a query.
      operationId: search_messages
      security:
        - slackAuth:
            - 'search:read'
      tags:
        - search
  /stars.add:
    post:
      description: Adds a star to an item.
      operationId: stars_add
      security:
        - slackAuth:
            - 'stars:write'
      tags:
        - stars
  /stars.list:
    get:
      description: Lists stars for a user.
      operationId: stars_list
      security:
        - slackAuth:
            - 'stars:read'
      tags:
        - stars
  /stars.remove:
    post:
      description: Removes a star from an item.
      operationId: stars_remove
      security:
        - slackAuth:
            - 'stars:write'
      tags:
        - stars
  /team.accessLogs:
    get:
      description: Gets the access logs for the current team.
      operationId: team_accessLogs
      security:
        - slackAuth:
            - admin
      tags:
        - team
  /team.billableInfo:
    get:
      description: Gets billable users information for the current team.
      operationId: team_billableInfo
      security:
        - slackAuth:
            - admin
      tags:
        - team
  /team.info:
    get:
      description: Gets information about the current team.
      operationId: team_info
      security:
        - slackAuth:
            - 'team:read'
      tags:
        - team
  /team.integrationLogs:
    get:
      description: Gets the integration logs for the current team.
      operationId: team_integrationLogs
      security:
        - slackAuth:
            - admin
      tags:
        - team
  /team.profile.get:
    get:
      description: Retrieve a team's profile.
      operationId: team_profile_get
      security:
        - slackAuth:
            - 'users.profile:read'
      tags:
        - team.profile
        - team
  /usergroups.create:
    post:
      description: Create a User Group
      operationId: usergroups_create
      security:
        - slackAuth:
            - 'usergroups:write'
      tags:
        - usergroups
  /usergroups.disable:
    post:
      description: Disable an existing User Group
      operationId: usergroups_disable
      security:
        - slackAuth:
            - 'usergroups:write'
      tags:
        - usergroups
  /usergroups.enable:
    post:
      description: Enable a User Group
      operationId: usergroups_enable
      security:
        - slackAuth:
            - 'usergroups:write'
      tags:
        - usergroups
  /usergroups.list:
    get:
      description: List all User Groups for a team
      operationId: usergroups_list
      security:
        - slackAuth:
            - 'usergroups:read'
      tags:
        - usergroups
  /usergroups.update:
    post:
      description: Update an existing User Group
      operationId: usergroups_update
      security:
        - slackAuth:
            - 'usergroups:write'
      tags:
        - usergroups
  /usergroups.users.list:
    get:
      description: List all users in a User Group
      operationId: usergroups_users_list
      security:
        - slackAuth:
            - 'usergroups:read'
      tags:
        - usergroups.users
        - usergroups
  /usergroups.users.update:
    post:
      description: Update the list of users for a User Group
      operationId: usergroups_users_update
      security:
        - slackAuth:
            - 'usergroups:write'
      tags:
        - usergroups.users
        - usergroups
  /users.deletePhoto:
    post:
      description: Delete the user profile photo
      operationId: users_deletePhoto
      security:
        - slackAuth:
            - 'users.profile:write'
      tags:
        - users
  /users.getPresence:
    get:
      description: Gets user presence information.
      operationId: users_getPresence
      security:
        - slackAuth:
            - 'users:read'
      tags:
        - users
  /users.identity:
    get:
      description: Get a user's identity.
      operationId: users_identity
      security:
        - slackAuth:
            - identity.basic
      tags:
        - users
  /users.info:
    get:
      description: Gets information about a user.
      operationId: users_info
      security:
        - slackAuth:
            - 'users:read'
      tags:
        - users
  /users.list:
    get:
      description: Lists all users in a Slack team.
      operationId: users_list
      security:
        - slackAuth:
            - 'users:read'
      tags:
        - users
  /users.lookupByEmail:
    get:
      description: Find a user with an email address.
      operationId: users_lookupByEmail
      security:
        - slackAuth:
            - 'users:read.email'
      tags:
        - users
  /users.profile.get:
    get:
      description: Retrieves a user's profile information.
      operationId: users_profile_get
      security:
        - slackAuth:
            - 'users.profile:read'
      tags:
        - users.profile
        - users
  /users.profile.set:
    post:
      description: Set the profile information for a user.
      operationId: users_profile_set
      security:
        - slackAuth:
            - 'users.profile:write'
      tags:
        - users.profile
        - users
  /users.setActive:
    post:
      description: Marked a user as active. Deprecated and non-functional.
      operationId: users_setActive
      security:
        - slackAuth:
            - 'users:write'
      tags:
        - users
  /users.setPhoto:
    post:
      description: Set the user profile photo
      operationId: users_setPhoto
      security:
        - slackAuth:
            - 'users.profile:write'
      tags:
        - users
  /users.setPresence:
    post:
      description: Manually sets user presence.
      operationId: users_setPresence
      security:
        - slackAuth:
            - 'users:write'
      tags:
        - users