swagger: '2.0'
schemes:
  - https
host: classroom.googleapis.com
basePath: /
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: 'Manages classes, rosters, and invitations in Google Classroom.'
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: Google Classroom
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-apisguru-categories:
    - education
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.0.1
      format: google
      url: 'https://classroom.googleapis.com/$discovery/rest?version=v1'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: classroom
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/classroom.courses': Manage your Google Classroom classes
      'https://www.googleapis.com/auth/classroom.courses.readonly': View your Google Classroom classes
      'https://www.googleapis.com/auth/classroom.coursework.me': Manage your course work and view your grades in Google Classroom
      'https://www.googleapis.com/auth/classroom.coursework.me.readonly': View your course work and grades in Google Classroom
      'https://www.googleapis.com/auth/classroom.coursework.students': Manage course work and grades for students in the Google Classroom classes you teach and view the course work and grades for classes you administer
      'https://www.googleapis.com/auth/classroom.coursework.students.readonly': View course work and grades for students in the Google Classroom classes you teach or administer
      'https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly': View your Google Classroom guardians
      'https://www.googleapis.com/auth/classroom.guardianlinks.students': View and manage guardians for students in your Google Classroom classes
      'https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly': View guardians for students in your Google Classroom classes
      'https://www.googleapis.com/auth/classroom.profile.emails': View the email addresses of people in your classes
      'https://www.googleapis.com/auth/classroom.profile.photos': View the profile photos of people in your classes
      'https://www.googleapis.com/auth/classroom.rosters': Manage your Google Classroom class rosters
      'https://www.googleapis.com/auth/classroom.rosters.readonly': View your Google Classroom class rosters
      'https://www.googleapis.com/auth/classroom.student-submissions.me.readonly': View your course work and grades in Google Classroom
      'https://www.googleapis.com/auth/classroom.student-submissions.students.readonly': View course work and grades for students in the Google Classroom classes you teach or administer
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/classroom.courses': Manage your Google Classroom classes
      'https://www.googleapis.com/auth/classroom.courses.readonly': View your Google Classroom classes
      'https://www.googleapis.com/auth/classroom.coursework.me': Manage your course work and view your grades in Google Classroom
      'https://www.googleapis.com/auth/classroom.coursework.me.readonly': View your course work and grades in Google Classroom
      'https://www.googleapis.com/auth/classroom.coursework.students': Manage course work and grades for students in the Google Classroom classes you teach and view the course work and grades for classes you administer
      'https://www.googleapis.com/auth/classroom.coursework.students.readonly': View course work and grades for students in the Google Classroom classes you teach or administer
      'https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly': View your Google Classroom guardians
      'https://www.googleapis.com/auth/classroom.guardianlinks.students': View and manage guardians for students in your Google Classroom classes
      'https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly': View guardians for students in your Google Classroom classes
      'https://www.googleapis.com/auth/classroom.profile.emails': View the email addresses of people in your classes
      'https://www.googleapis.com/auth/classroom.profile.photos': View the profile photos of people in your classes
      'https://www.googleapis.com/auth/classroom.rosters': Manage your Google Classroom class rosters
      'https://www.googleapis.com/auth/classroom.rosters.readonly': View your Google Classroom class rosters
      'https://www.googleapis.com/auth/classroom.student-submissions.me.readonly': View your course work and grades in Google Classroom
      'https://www.googleapis.com/auth/classroom.student-submissions.students.readonly': View course work and grades for students in the Google Classroom classes you teach or administer
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: courses
  - name: invitations
  - name: userProfiles
paths:
  /v1/courses:
    get:
      description: |-
        Returns a list of courses that the requesting user is permitted to view,
        restricted to those that match the request. Returned courses are ordered by
        creation time, with the most recently created coming first.

        This method returns the following error codes:

        * `PERMISSION_DENIED` for access errors.
        * `INVALID_ARGUMENT` if the query argument is malformed.
        * `NOT_FOUND` if any users specified in the query arguments do not exist.
      operationId: classroom.courses.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.courses'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.courses.readonly'
      tags:
        - courses
    post:
      description: |-
        Creates a course.

        The user specified in `ownerId` is the owner of the created course
        and added as a teacher.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to create
        courses or for access errors.
        * `NOT_FOUND` if the primary teacher is not a valid user.
        * `FAILED_PRECONDITION` if the course owner's account is disabled or for
        the following request errors:
            * UserGroupsMembershipLimitReached
        * `ALREADY_EXISTS` if an alias was specified in the `id` and
        already exists.
      operationId: classroom.courses.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.courses'
      tags:
        - courses
  '/v1/courses/{courseId}/aliases':
    get:
      description: |-
        Returns a list of aliases for a course.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to access the
        course or for access errors.
        * `NOT_FOUND` if the course does not exist.
      operationId: classroom.courses.aliases.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.courses'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.courses.readonly'
      tags:
        - courses
    post:
      description: |-
        Creates an alias for a course.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to create the
        alias or for access errors.
        * `NOT_FOUND` if the course does not exist.
        * `ALREADY_EXISTS` if the alias already exists.
        * `FAILED_PRECONDITION` if the alias requested does not make sense for the
          requesting user or course (for example, if a user not in a domain
          attempts to access a domain-scoped alias).
      operationId: classroom.courses.aliases.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.courses'
      tags:
        - courses
  '/v1/courses/{courseId}/aliases/{alias}':
    delete:
      description: |-
        Deletes an alias of a course.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to remove the
        alias or for access errors.
        * `NOT_FOUND` if the alias does not exist.
        * `FAILED_PRECONDITION` if the alias requested does not make sense for the
          requesting user or course (for example, if a user not in a domain
          attempts to delete a domain-scoped alias).
      operationId: classroom.courses.aliases.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.courses'
      tags:
        - courses
  '/v1/courses/{courseId}/courseWork':
    get:
      description: |-
        Returns a list of course work that the requester is permitted to view.

        Course students may only view `PUBLISHED` course work. Course teachers
        and domain administrators may view all course work.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to access
        the requested course or for access errors.
        * `INVALID_ARGUMENT` if the request is malformed.
        * `NOT_FOUND` if the requested course does not exist.
      operationId: classroom.courses.courseWork.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.me'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.me'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.me.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.me.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.students'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.students'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.students.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.students.readonly'
      tags:
        - courses
    post:
      description: |-
        Creates course work.

        The resulting course work (and corresponding student submissions) are
        associated with the Developer Console project of the
        [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to
        make the request. Classroom API requests to modify course work and student
        submissions must be made with an OAuth client ID from the associated
        Developer Console project.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to access the
        requested course, create course work in the requested course, share a
        Drive attachment, or for access errors.
        * `INVALID_ARGUMENT` if the request is malformed.
        * `NOT_FOUND` if the requested course does not exist.
        * `FAILED_PRECONDITION` for the following request error:
            * AttachmentNotVisible
      operationId: classroom.courses.courseWork.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.students'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.students'
      tags:
        - courses
  '/v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions':
    get:
      description: |-
        Returns a list of student submissions that the requester is permitted to
        view, factoring in the OAuth scopes of the request.
        `-` may be specified as the `course_work_id` to include student
        submissions for multiple course work items.

        Course students may only view their own work. Course teachers
        and domain administrators may view all student submissions.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to access the
        requested course or course work, or for access errors.
        * `INVALID_ARGUMENT` if the request is malformed.
        * `NOT_FOUND` if the requested course does not exist.
      operationId: classroom.courses.courseWork.studentSubmissions.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.me'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.me'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.me.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.me.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.students'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.students'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.students.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.students.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.student-submissions.me.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.student-submissions.me.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.student-submissions.students.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.student-submissions.students.readonly'
      tags:
        - courses
  '/v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}':
    get:
      description: |-
        Returns a student submission.

        * `PERMISSION_DENIED` if the requesting user is not permitted to access the
        requested course, course work, or student submission or for
        access errors.
        * `INVALID_ARGUMENT` if the request is malformed.
        * `NOT_FOUND` if the requested course, course work, or student submission
        does not exist.
      operationId: classroom.courses.courseWork.studentSubmissions.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.me'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.me'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.me.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.me.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.students'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.students'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.students.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.students.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.student-submissions.me.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.student-submissions.me.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.student-submissions.students.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.student-submissions.students.readonly'
      tags:
        - courses
    patch:
      description: |-
        Updates one or more fields of a student submission.

        See google.classroom.v1.StudentSubmission for details
        of which fields may be updated and who may change them.

        This request must be made by the Developer Console project of the
        [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to
        create the corresponding course work item.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting developer project did not create
        the corresponding course work, if the user is not permitted to make the
        requested modification to the student submission, or for
        access errors.
        * `INVALID_ARGUMENT` if the request is malformed.
        * `NOT_FOUND` if the requested course, course work, or student submission
        does not exist.
      operationId: classroom.courses.courseWork.studentSubmissions.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.me'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.me'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.students'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.students'
      tags:
        - courses
  '/v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:modifyAttachments':
    post:
      description: |-
        Modifies attachments of student submission.

        Attachments may only be added to student submissions belonging to course
        work objects with a `workType` of `ASSIGNMENT`.

        This request must be made by the Developer Console project of the
        [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to
        create the corresponding course work item.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to access the
        requested course or course work, if the user is not permitted to modify
        attachments on the requested student submission, or for
        access errors.
        * `INVALID_ARGUMENT` if the request is malformed.
        * `NOT_FOUND` if the requested course, course work, or student submission
        does not exist.
      operationId: classroom.courses.courseWork.studentSubmissions.modifyAttachments
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.me'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.me'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.students'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.students'
      tags:
        - courses
  '/v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:reclaim':
    post:
      description: |-
        Reclaims a student submission on behalf of the student that owns it.

        Reclaiming a student submission transfers ownership of attached Drive
        files to the student and update the submission state.

        Only the student that owns the requested student submission may call this
        method, and only for a student submission that has been turned in.

        This request must be made by the Developer Console project of the
        [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to
        create the corresponding course work item.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to access the
        requested course or course work, unsubmit the requested student submission,
        or for access errors.
        * `FAILED_PRECONDITION` if the student submission has not been turned in.
        * `INVALID_ARGUMENT` if the request is malformed.
        * `NOT_FOUND` if the requested course, course work, or student submission
        does not exist.
      operationId: classroom.courses.courseWork.studentSubmissions.reclaim
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.me'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.me'
      tags:
        - courses
  '/v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:return':
    post:
      description: |-
        Returns a student submission.

        Returning a student submission transfers ownership of attached Drive
        files to the student and may also update the submission state.
        Unlike the Classroom application, returning a student submission does not
        set assignedGrade to the draftGrade value.

        Only a teacher of the course that contains the requested student submission
        may call this method.

        This request must be made by the Developer Console project of the
        [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to
        create the corresponding course work item.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to access the
        requested course or course work, return the requested student submission,
        or for access errors.
        * `INVALID_ARGUMENT` if the request is malformed.
        * `NOT_FOUND` if the requested course, course work, or student submission
        does not exist.
      operationId: classroom.courses.courseWork.studentSubmissions.return
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.students'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.students'
      tags:
        - courses
  '/v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:turnIn':
    post:
      description: |-
        Turns in a student submission.

        Turning in a student submission transfers ownership of attached Drive
        files to the teacher and may also update the submission state.

        This may only be called by the student that owns the specified student
        submission.

        This request must be made by the Developer Console project of the
        [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to
        create the corresponding course work item.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to access the
        requested course or course work, turn in the requested student submission,
        or for access errors.
        * `INVALID_ARGUMENT` if the request is malformed.
        * `NOT_FOUND` if the requested course, course work, or student submission
        does not exist.
      operationId: classroom.courses.courseWork.studentSubmissions.turnIn
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.me'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.me'
      tags:
        - courses
  '/v1/courses/{courseId}/courseWork/{id}':
    delete:
      description: |-
        Deletes a course work.

        This request must be made by the Developer Console project of the
        [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to
        create the corresponding course work item.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting developer project did not create
        the corresponding course work, if the requesting user is not permitted
        to delete the requested course or for access errors.
        * `FAILED_PRECONDITION` if the requested course work has already been
        deleted.
        * `NOT_FOUND` if no course exists with the requested ID.
      operationId: classroom.courses.courseWork.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.students'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.students'
      tags:
        - courses
    get:
      description: |-
        Returns course work.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to access the
        requested course or course work, or for access errors.
        * `INVALID_ARGUMENT` if the request is malformed.
        * `NOT_FOUND` if the requested course or course work does not exist.
      operationId: classroom.courses.courseWork.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.me'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.me'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.me.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.me.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.students'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.students'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.students.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.students.readonly'
      tags:
        - courses
    patch:
      description: |-
        Updates one or more fields of a course work.

        See google.classroom.v1.CourseWork for details
        of which fields may be updated and who may change them.

        This request must be made by the Developer Console project of the
        [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to
        create the corresponding course work item.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting developer project did not create
        the corresponding course work, if the user is not permitted to make the
        requested modification to the student submission, or for
        access errors.
        * `INVALID_ARGUMENT` if the request is malformed.
        * `FAILED_PRECONDITION` if the requested course work has already been
        deleted.
        * `NOT_FOUND` if the requested course, course work, or student submission
        does not exist.
      operationId: classroom.courses.courseWork.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.coursework.students'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.coursework.students'
      tags:
        - courses
  '/v1/courses/{courseId}/students':
    get:
      description: |-
        Returns a list of students of this course that the requester
        is permitted to view.

        This method returns the following error codes:

        * `NOT_FOUND` if the course does not exist.
        * `PERMISSION_DENIED` for access errors.
      operationId: classroom.courses.students.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
      tags:
        - courses
    post:
      description: |-
        Adds a user as a student of a course.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to create
        students in this course or for access errors.
        * `NOT_FOUND` if the requested course ID does not exist.
        * `FAILED_PRECONDITION` if the requested user's account is disabled,
        for the following request errors:
            * CourseMemberLimitReached
            * CourseNotModifiable
            * UserGroupsMembershipLimitReached
        * `ALREADY_EXISTS` if the user is already a student or teacher in the
        course.
      operationId: classroom.courses.students.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters'
      tags:
        - courses
  '/v1/courses/{courseId}/students/{userId}':
    delete:
      description: |-
        Deletes a student of a course.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to delete
        students of this course or for access errors.
        * `NOT_FOUND` if no student of this course has the requested ID or if the
        course does not exist.
      operationId: classroom.courses.students.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters'
      tags:
        - courses
    get:
      description: |-
        Returns a student of a course.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to view
        students of this course or for access errors.
        * `NOT_FOUND` if no student of this course has the requested ID or if the
        course does not exist.
      operationId: classroom.courses.students.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
      tags:
        - courses
  '/v1/courses/{courseId}/teachers':
    get:
      description: |-
        Returns a list of teachers of this course that the requester
        is permitted to view.

        This method returns the following error codes:

        * `NOT_FOUND` if the course does not exist.
        * `PERMISSION_DENIED` for access errors.
      operationId: classroom.courses.teachers.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
      tags:
        - courses
    post:
      description: |-
        Creates a teacher of a course.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not  permitted to create
        teachers in this course or for access errors.
        * `NOT_FOUND` if the requested course ID does not exist.
        * `FAILED_PRECONDITION` if the requested user's account is disabled,
        for the following request errors:
            * CourseMemberLimitReached
            * CourseNotModifiable
            * CourseTeacherLimitReached
            * UserGroupsMembershipLimitReached
        * `ALREADY_EXISTS` if the user is already a teacher or student in the
        course.
      operationId: classroom.courses.teachers.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters'
      tags:
        - courses
  '/v1/courses/{courseId}/teachers/{userId}':
    delete:
      description: |-
        Deletes a teacher of a course.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to delete
        teachers of this course or for access errors.
        * `NOT_FOUND` if no teacher of this course has the requested ID or if the
        course does not exist.
        * `FAILED_PRECONDITION` if the requested ID belongs to the primary teacher
        of this course.
      operationId: classroom.courses.teachers.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters'
      tags:
        - courses
    get:
      description: |-
        Returns a teacher of a course.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to view
        teachers of this course or for access errors.
        * `NOT_FOUND` if no teacher of this course has the requested ID or if the
        course does not exist.
      operationId: classroom.courses.teachers.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
      tags:
        - courses
  '/v1/courses/{id}':
    delete:
      description: |-
        Deletes a course.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to delete the
        requested course or for access errors.
        * `NOT_FOUND` if no course exists with the requested ID.
      operationId: classroom.courses.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.courses'
      tags:
        - courses
    get:
      description: |-
        Returns a course.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to access the
        requested course or for access errors.
        * `NOT_FOUND` if no course exists with the requested ID.
      operationId: classroom.courses.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.courses'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.courses.readonly'
      tags:
        - courses
    patch:
      description: |-
        Updates one or more fields in a course.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to modify the
        requested course or for access errors.
        * `NOT_FOUND` if no course exists with the requested ID.
        * `INVALID_ARGUMENT` if invalid fields are specified in the update mask or
        if no update mask is supplied.
        * `FAILED_PRECONDITION` for the following request errors:
            * CourseNotModifiable
      operationId: classroom.courses.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.courses'
      tags:
        - courses
    put:
      description: |-
        Updates a course.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to modify the
        requested course or for access errors.
        * `NOT_FOUND` if no course exists with the requested ID.
        * `FAILED_PRECONDITION` for the following request errors:
            * CourseNotModifiable
      operationId: classroom.courses.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.courses'
      tags:
        - courses
  /v1/invitations:
    get:
      description: |-
        Returns a list of invitations that the requesting user is permitted to
        view, restricted to those that match the list request.

        *Note:* At least one of `user_id` or `course_id` must be supplied. Both
        fields can be supplied.

        This method returns the following error codes:

        * `PERMISSION_DENIED` for access errors.
      operationId: classroom.invitations.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
      tags:
        - invitations
    post:
      description: |-
        Creates an invitation. Only one invitation for a user and course may exist
        at a time. Delete and re-create an invitation to make changes.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to create
        invitations for this course or for access errors.
        * `NOT_FOUND` if the course or the user does not exist.
        * `FAILED_PRECONDITION` if the requested user's account is disabled or if
        the user already has this role or a role with greater permissions.
        * `ALREADY_EXISTS` if an invitation for the specified user and course
        already exists.
      operationId: classroom.invitations.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters'
      tags:
        - invitations
  '/v1/invitations/{id}':
    delete:
      description: |-
        Deletes an invitation.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to delete the
        requested invitation or for access errors.
        * `NOT_FOUND` if no invitation exists with the requested ID.
      operationId: classroom.invitations.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters'
      tags:
        - invitations
    get:
      description: |-
        Returns an invitation.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to view the
        requested invitation or for access errors.
        * `NOT_FOUND` if no invitation exists with the requested ID.
      operationId: classroom.invitations.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
      tags:
        - invitations
  '/v1/invitations/{id}:accept':
    post:
      description: |-
        Accepts an invitation, removing it and adding the invited user to the
        teachers or students (as appropriate) of the specified course. Only the
        invited user may accept an invitation.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to accept the
        requested invitation or for access errors.
        * `FAILED_PRECONDITION` for the following request errors:
            * CourseMemberLimitReached
            * CourseNotModifiable
            * CourseTeacherLimitReached
            * UserGroupsMembershipLimitReached
        * `NOT_FOUND` if no invitation exists with the requested ID.
      operationId: classroom.invitations.accept
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters'
      tags:
        - invitations
  '/v1/userProfiles/{studentId}/guardianInvitations':
    get:
      description: |-
        Returns a list of guardian invitations that the requesting user is
        permitted to view, filtered by the parameters provided.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if a `student_id` is specified, and the requesting
          user is not permitted to view guardian invitations for that student, if
          `"-"` is specified as the `student_id` and the user is not a domain
          administrator, if guardians are not enabled for the domain in question,
          or for other access errors.
        * `INVALID_ARGUMENT` if a `student_id` is specified, but its format cannot
          be recognized (it is not an email address, nor a `student_id` from the
          API, nor the literal string `me`). May also be returned if an invalid
          `page_token` or `state` is provided.
        * `NOT_FOUND` if a `student_id` is specified, and its format can be
          recognized, but Classroom has no record of that student.
      operationId: classroom.userProfiles.guardianInvitations.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly'
      tags:
        - userProfiles
    post:
      description: |-
        Creates a guardian invitation, and sends an email to the guardian asking
        them to confirm that they are the student's guardian.

        Once the guardian accepts the invitation, their `state` will change to
        `COMPLETED` and they will start receiving guardian notifications. A
        `Guardian` resource will also be created to represent the active guardian.

        The request object must have the `student_id` and
        `invited_email_address` fields set. Failing to set these fields, or
        setting any other fields in the request, will result in an error.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the current user does not have permission to
          manage guardians, if the guardian in question has already rejected
          too many requests for that student, if guardians are not enabled for the
          domain in question, or for other access errors.
        * `RESOURCE_EXHAUSTED` if the student or guardian has exceeded the guardian
          link limit.
        * `INVALID_ARGUMENT` if the guardian email address is not valid (for
          example, if it is too long), or if the format of the student ID provided
          cannot be recognized (it is not an email address, nor a `user_id` from
          this API). This error will also be returned if read-only fields are set,
          or if the `state` field is set to to a value other than `PENDING`.
        * `NOT_FOUND` if the student ID provided is a valid student ID, but
          Classroom has no record of that student.
        * `ALREADY_EXISTS` if there is already a pending guardian invitation for
          the student and `invited_email_address` provided, or if the provided
          `invited_email_address` matches the Google account of an existing
          `Guardian` for this user.
      operationId: classroom.userProfiles.guardianInvitations.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students'
      tags:
        - userProfiles
  '/v1/userProfiles/{studentId}/guardianInvitations/{invitationId}':
    get:
      description: |-
        Returns a specific guardian invitation.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to view
          guardian invitations for the student identified by the `student_id`, if
          guardians are not enabled for the domain in question, or for other
          access errors.
        * `INVALID_ARGUMENT` if a `student_id` is specified, but its format cannot
          be recognized (it is not an email address, nor a `student_id` from the
          API, nor the literal string `me`).
        * `NOT_FOUND` if Classroom cannot find any record of the given student or
          `invitation_id`. May also be returned if the student exists, but the
          requesting user does not have access to see that student.
      operationId: classroom.userProfiles.guardianInvitations.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly'
      tags:
        - userProfiles
    patch:
      description: |-
        Modifies a guardian invitation.

        Currently, the only valid modification is to change the `state` from
        `PENDING` to `COMPLETE`. This has the effect of withdrawing the invitation.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the current user does not have permission to
          manage guardians, if guardians are not enabled for the domain in question
          or for other access errors.
        * `FAILED_PRECONDITION` if the guardian link is not in the `PENDING` state.
        * `INVALID_ARGUMENT` if the format of the student ID provided
          cannot be recognized (it is not an email address, nor a `user_id` from
          this API), or if the passed `GuardianInvitation` has a `state` other than
          `COMPLETE`, or if it modifies fields other than `state`.
        * `NOT_FOUND` if the student ID provided is a valid student ID, but
          Classroom has no record of that student, or if the `id` field does not
          refer to a guardian invitation known to Classroom.
      operationId: classroom.userProfiles.guardianInvitations.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students'
      tags:
        - userProfiles
  '/v1/userProfiles/{studentId}/guardians':
    get:
      description: |-
        Returns a list of guardians that the requesting user is permitted to
        view, restricted to those that match the request.

        To list guardians for any student that the requesting user may view
        guardians for, use the literal character `-` for the student ID.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if a `student_id` is specified, and the requesting
          user is not permitted to view guardian information for that student, if
          `"-"` is specified as the `student_id` and the user is not a domain
          administrator, if guardians are not enabled for the domain in question,
          if the `invited_email_address` filter is set by a user who is not a
          domain administrator, or for other access errors.
        * `INVALID_ARGUMENT` if a `student_id` is specified, but its format cannot
          be recognized (it is not an email address, nor a `student_id` from the
          API, nor the literal string `me`). May also be returned if an invalid
          `page_token` is provided.
        * `NOT_FOUND` if a `student_id` is specified, and its format can be
          recognized, but Classroom has no record of that student.
      operationId: classroom.userProfiles.guardians.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly'
      tags:
        - userProfiles
  '/v1/userProfiles/{studentId}/guardians/{guardianId}':
    delete:
      description: |-
        Deletes a guardian.

        The guardian will no longer receive guardian notifications and the guardian
        will no longer be accessible via the API.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if no user that matches the provided `student_id`
          is visible to the requesting user, if the requesting user is not
          permitted to manage guardians for the student identified by the
          `student_id`, if guardians are not enabled for the domain in question,
          or for other access errors.
        * `INVALID_ARGUMENT` if a `student_id` is specified, but its format cannot
          be recognized (it is not an email address, nor a `student_id` from the
          API).
        * `NOT_FOUND` if the requesting user is permitted to modify guardians for
          the requested `student_id`, but no `Guardian` record exists for that
          student with the provided `guardian_id`.
      operationId: classroom.userProfiles.guardians.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students'
      tags:
        - userProfiles
    get:
      description: |-
        Returns a specific guardian.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if no user that matches the provided `student_id`
          is visible to the requesting user, if the requesting user is not
          permitted to view guardian information for the student identified by the
          `student_id`, if guardians are not enabled for the domain in question,
          or for other access errors.
        * `INVALID_ARGUMENT` if a `student_id` is specified, but its format cannot
          be recognized (it is not an email address, nor a `student_id` from the
          API, nor the literal string `me`).
        * `NOT_FOUND` if the requesting user is permitted to view guardians for
          the requested `student_id`, but no `Guardian` record exists for that
          student that matches the provided `guardian_id`.
      operationId: classroom.userProfiles.guardians.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly'
      tags:
        - userProfiles
  '/v1/userProfiles/{userId}':
    get:
      description: |-
        Returns a user profile.

        This method returns the following error codes:

        * `PERMISSION_DENIED` if the requesting user is not permitted to access
        this user profile, if no profile exists with the requested ID, or for
        access errors.
      operationId: classroom.userProfiles.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters'
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
      tags:
        - userProfiles