swagger: '2.0'
schemes:
  - https
host: classroom.googleapis.com
basePath: /
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Google Classroom API
  title: Google Classroom API
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    format: google
    url: 'https://www.googleapis.com/discovery/v1/apis/classroom/v1/rest'
    version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: classroom
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/classroom.courses': Manage your Google Classroom classes
      'https://www.googleapis.com/auth/classroom.courses.readonly': View your Google Classroom classes
      'https://www.googleapis.com/auth/classroom.profile.emails': View the email addresses of people in your classes
      'https://www.googleapis.com/auth/classroom.profile.photos': View the profile photos of people in your classes
      'https://www.googleapis.com/auth/classroom.rosters': Manage your Google Classroom class rosters
      'https://www.googleapis.com/auth/classroom.rosters.readonly': View your Google Classroom class rosters
    type: oauth2
paths:
  /v1/courses:
    get:
      description: 'Returns a list of courses that the requesting user is permitted to view, restricted to those that match the request. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the query argument is malformed. * `NOT_FOUND` if any users specified in the query arguments do not exist.'
      operationId: classroom.courses.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses'
            - 'https://www.googleapis.com/auth/classroom.courses.readonly'
      tags:
        - courses
    post:
      description: "Creates a course. The user specified in `ownerId` is the owner of the created course and added as a teacher. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create courses or for access errors. * `NOT_FOUND` if the primary teacher is not a valid user. * `FAILED_PRECONDITION` if the course owner's account is disabled or for the following request errors: * UserGroupsMembershipLimitReached * `ALREADY_EXISTS` if an a[...]"
      operationId: classroom.courses.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses'
      tags:
        - courses
  '/v1/courses/{courseId}/aliases':
    get:
      description: 'Returns a list of aliases for a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the course or for access errors. * `NOT_FOUND` if the course does not exist.'
      operationId: classroom.courses.aliases.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses'
            - 'https://www.googleapis.com/auth/classroom.courses.readonly'
      tags:
        - courses
    post:
      description: 'Creates an alias for a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create the alias or for access errors. * `NOT_FOUND` if the course does not exist. * `ALREADY_EXISTS` if the alias already exists.'
      operationId: classroom.courses.aliases.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses'
      tags:
        - courses
  '/v1/courses/{courseId}/aliases/{alias}':
    delete:
      description: 'Deletes an alias of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to remove the alias or for access errors. * `NOT_FOUND` if the alias does not exist.'
      operationId: classroom.courses.aliases.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses'
      tags:
        - courses
  '/v1/courses/{courseId}/students':
    get:
      description: 'Returns a list of students of this course that the requester is permitted to view. This method returns the following error codes: * `NOT_FOUND` if the course does not exist. * `PERMISSION_DENIED` for access errors.'
      operationId: classroom.courses.students.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
            - 'https://www.googleapis.com/auth/classroom.rosters'
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
      tags:
        - courses
    post:
      description: "Adds a user as a student of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create students in this course or for access errors. * `NOT_FOUND` if the requested course ID does not exist. * `FAILED_PRECONDITION` if the requested user's account is disabled, for the following request errors: * CourseMemberLimitReached * CourseNotModifiable * UserGroupsMembershipLimitReached * `ALREADY_EXISTS` if the user is[...]"
      operationId: classroom.courses.students.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
            - 'https://www.googleapis.com/auth/classroom.rosters'
      tags:
        - courses
  '/v1/courses/{courseId}/students/{userId}':
    delete:
      description: 'Deletes a student of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete students of this course or for access errors. * `NOT_FOUND` if no student of this course has the requested ID or if the course does not exist.'
      operationId: classroom.courses.students.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
      tags:
        - courses
    get:
      description: 'Returns a student of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view students of this course or for access errors. * `NOT_FOUND` if no student of this course has the requested ID or if the course does not exist.'
      operationId: classroom.courses.students.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
            - 'https://www.googleapis.com/auth/classroom.rosters'
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
      tags:
        - courses
  '/v1/courses/{courseId}/teachers':
    get:
      description: 'Returns a list of teachers of this course that the requester is permitted to view. This method returns the following error codes: * `NOT_FOUND` if the course does not exist. * `PERMISSION_DENIED` for access errors.'
      operationId: classroom.courses.teachers.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
            - 'https://www.googleapis.com/auth/classroom.rosters'
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
      tags:
        - courses
    post:
      description: "Creates a teacher of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create teachers in this course or for access errors. * `NOT_FOUND` if the requested course ID does not exist. * `FAILED_PRECONDITION` if the requested user's account is disabled, for the following request errors: * CourseMemberLimitReached * CourseNotModifiable * CourseTeacherLimitReached * UserGroupsMembershipLimitReached * `ALREADY_E[...]"
      operationId: classroom.courses.teachers.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
            - 'https://www.googleapis.com/auth/classroom.rosters'
      tags:
        - courses
  '/v1/courses/{courseId}/teachers/{userId}':
    delete:
      description: 'Deletes a teacher of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete teachers of this course or for access errors. * `NOT_FOUND` if no teacher of this course has the requested ID or if the course does not exist. * `FAILED_PRECONDITION` if the requested ID belongs to the primary teacher of this course.'
      operationId: classroom.courses.teachers.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
      tags:
        - courses
    get:
      description: 'Returns a teacher of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view teachers of this course or for access errors. * `NOT_FOUND` if no teacher of this course has the requested ID or if the course does not exist.'
      operationId: classroom.courses.teachers.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
            - 'https://www.googleapis.com/auth/classroom.rosters'
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
      tags:
        - courses
  '/v1/courses/{id}':
    delete:
      description: 'Deletes a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete the requested course or for access errors. * `NOT_FOUND` if no course exists with the requested ID.'
      operationId: classroom.courses.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses'
      tags:
        - courses
    get:
      description: 'Returns a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course or for access errors. * `NOT_FOUND` if no course exists with the requested ID.'
      operationId: classroom.courses.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses'
            - 'https://www.googleapis.com/auth/classroom.courses.readonly'
      tags:
        - courses
    patch:
      description: 'Updates one or more fields in a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to modify the requested course or for access errors. * `NOT_FOUND` if no course exists with the requested ID. * `INVALID_ARGUMENT` if invalid fields are specified in the update mask or if no update mask is supplied. * `FAILED_PRECONDITION` for the following request errors: * CourseNotModifiable'
      operationId: classroom.courses.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses'
      tags:
        - courses
    put:
      description: 'Updates a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to modify the requested course or for access errors. * `NOT_FOUND` if no course exists with the requested ID. * `FAILED_PRECONDITION` for the following request errors: * CourseNotModifiable'
      operationId: classroom.courses.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.courses'
      tags:
        - courses
  /v1/invitations:
    get:
      description: 'Returns a list of invitations that the requesting user is permitted to view, restricted to those that match the list request. *Note:* At least one of `user_id` or `course_id` must be supplied. Both fields can be supplied. This method returns the following error codes: * `PERMISSION_DENIED` for access errors.'
      operationId: classroom.invitations.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
      tags:
        - invitations
    post:
      description: "Creates an invitation. Only one invitation for a user and course may exist at a time. Delete and re-create an invitation to make changes. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create invitations for this course or for access errors. * `NOT_FOUND` if the course or the user does not exist. * `FAILED_PRECONDITION` if the requested user's account is disabled or if the user already has this role or a role wi[...]"
      operationId: classroom.invitations.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
      tags:
        - invitations
  '/v1/invitations/{id}':
    delete:
      description: 'Deletes an invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete the requested invitation or for access errors. * `NOT_FOUND` if no invitation exists with the requested ID.'
      operationId: classroom.invitations.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
      tags:
        - invitations
    get:
      description: 'Returns an invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view the requested invitation or for access errors. * `NOT_FOUND` if no invitation exists with the requested ID.'
      operationId: classroom.invitations.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
      tags:
        - invitations
  '/v1/invitations/{id}:accept':
    post:
      description: 'Accepts an invitation, removing it and adding the invited user to the teachers or students (as appropriate) of the specified course. Only the invited user may accept an invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to accept the requested invitation or for access errors. * `FAILED_PRECONDITION` for the following request errors: * CourseMemberLimitReached * CourseNotModifiable * CourseTeacherLimitReache[...]'
      operationId: classroom.invitations.accept
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.rosters'
      tags:
        - invitations
  '/v1/userProfiles/{userId}':
    get:
      description: 'Returns a user profile. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access this user profile or if no profile exists with the requested ID or for access errors.'
      operationId: classroom.userProfiles.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/classroom.profile.emails'
            - 'https://www.googleapis.com/auth/classroom.profile.photos'
            - 'https://www.googleapis.com/auth/classroom.rosters'
            - 'https://www.googleapis.com/auth/classroom.rosters.readonly'
      tags:
        - userProfiles