package shared

type EntityTypeEnum string

const (
	EntityTypeEnumVirtualMachine              EntityTypeEnum = "VirtualMachine"
	EntityTypeEnumEc2Instance                 EntityTypeEnum = "EC2Instance"
	EntityTypeEnumHost                        EntityTypeEnum = "Host"
	EntityTypeEnumVnic                        EntityTypeEnum = "Vnic"
	EntityTypeEnumVmknic                      EntityTypeEnum = "Vmknic"
	EntityTypeEnumVxlanLayer2Network          EntityTypeEnum = "VxlanLayer2Network"
	EntityTypeEnumVlanL2Network               EntityTypeEnum = "VlanL2Network"
	EntityTypeEnumCluster                     EntityTypeEnum = "Cluster"
	EntityTypeEnumSecurityTag                 EntityTypeEnum = "SecurityTag"
	EntityTypeEnumResourcePool                EntityTypeEnum = "ResourcePool"
	EntityTypeEnumNsxipSet                    EntityTypeEnum = "NSXIPSet"
	EntityTypeEnumEc2IPSet                    EntityTypeEnum = "EC2IPSet"
	EntityTypeEnumNsxSecurityGroup            EntityTypeEnum = "NSXSecurityGroup"
	EntityTypeEnumEc2SecurityGroup            EntityTypeEnum = "EC2SecurityGroup"
	EntityTypeEnumFlow                        EntityTypeEnum = "Flow"
	EntityTypeEnumProblemEvent                EntityTypeEnum = "ProblemEvent"
	EntityTypeEnumApplication                 EntityTypeEnum = "Application"
	EntityTypeEnumTier                        EntityTypeEnum = "Tier"
	EntityTypeEnumNsxFirewallRule             EntityTypeEnum = "NSXFirewallRule"
	EntityTypeEnumEc2SgFirewallRule           EntityTypeEnum = "EC2SGFirewallRule"
	EntityTypeEnumNsxRedirectRule             EntityTypeEnum = "NSXRedirectRule"
	EntityTypeEnumVCenterManager              EntityTypeEnum = "VCenterManager"
	EntityTypeEnumNsxvManager                 EntityTypeEnum = "NSXVManager"
	EntityTypeEnumNsxService                  EntityTypeEnum = "NSXService"
	EntityTypeEnumEc2Service                  EntityTypeEnum = "EC2Service"
	EntityTypeEnumVpc                         EntityTypeEnum = "VPC"
	EntityTypeEnumNsxDistributedFirewall      EntityTypeEnum = "NSXDistributedFirewall"
	EntityTypeEnumEc2Firewall                 EntityTypeEnum = "EC2Firewall"
	EntityTypeEnumNsxServiceGroup             EntityTypeEnum = "NSXServiceGroup"
	EntityTypeEnumDistributedVirtualSwitch    EntityTypeEnum = "DistributedVirtualSwitch"
	EntityTypeEnumDistributedVirtualPortgroup EntityTypeEnum = "DistributedVirtualPortgroup"
	EntityTypeEnumVcDatacenter                EntityTypeEnum = "VCDatacenter"
	EntityTypeEnumDatastore                   EntityTypeEnum = "Datastore"
	EntityTypeEnumFolder                      EntityTypeEnum = "Folder"
)
