from dataclasses import dataclass, field
from datetime import date, datetime
from marshmallow import fields
import dateutil.parser
from typing import Optional
from enum import Enum
from dataclasses_json import dataclass_json
from sdk import utils

class ScanConfigErrorCodeEnum(str, Enum):
    CODE_UNSPECIFIED = "CODE_UNSPECIFIED"
    OK = "OK"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    APPENGINE_API_BACKEND_ERROR = "APPENGINE_API_BACKEND_ERROR"
    APPENGINE_API_NOT_ACCESSIBLE = "APPENGINE_API_NOT_ACCESSIBLE"
    APPENGINE_DEFAULT_HOST_MISSING = "APPENGINE_DEFAULT_HOST_MISSING"
    CANNOT_USE_GOOGLE_COM_ACCOUNT = "CANNOT_USE_GOOGLE_COM_ACCOUNT"
    CANNOT_USE_OWNER_ACCOUNT = "CANNOT_USE_OWNER_ACCOUNT"
    COMPUTE_API_BACKEND_ERROR = "COMPUTE_API_BACKEND_ERROR"
    COMPUTE_API_NOT_ACCESSIBLE = "COMPUTE_API_NOT_ACCESSIBLE"
    CUSTOM_LOGIN_URL_DOES_NOT_BELONG_TO_CURRENT_PROJECT = "CUSTOM_LOGIN_URL_DOES_NOT_BELONG_TO_CURRENT_PROJECT"
    CUSTOM_LOGIN_URL_MALFORMED = "CUSTOM_LOGIN_URL_MALFORMED"
    CUSTOM_LOGIN_URL_MAPPED_TO_NON_ROUTABLE_ADDRESS = "CUSTOM_LOGIN_URL_MAPPED_TO_NON_ROUTABLE_ADDRESS"
    CUSTOM_LOGIN_URL_MAPPED_TO_UNRESERVED_ADDRESS = "CUSTOM_LOGIN_URL_MAPPED_TO_UNRESERVED_ADDRESS"
    CUSTOM_LOGIN_URL_HAS_NON_ROUTABLE_IP_ADDRESS = "CUSTOM_LOGIN_URL_HAS_NON_ROUTABLE_IP_ADDRESS"
    CUSTOM_LOGIN_URL_HAS_UNRESERVED_IP_ADDRESS = "CUSTOM_LOGIN_URL_HAS_UNRESERVED_IP_ADDRESS"
    DUPLICATE_SCAN_NAME = "DUPLICATE_SCAN_NAME"
    INVALID_FIELD_VALUE = "INVALID_FIELD_VALUE"
    FAILED_TO_AUTHENTICATE_TO_TARGET = "FAILED_TO_AUTHENTICATE_TO_TARGET"
    FINDING_TYPE_UNSPECIFIED = "FINDING_TYPE_UNSPECIFIED"
    FORBIDDEN_TO_SCAN_COMPUTE = "FORBIDDEN_TO_SCAN_COMPUTE"
    FORBIDDEN_UPDATE_TO_MANAGED_SCAN = "FORBIDDEN_UPDATE_TO_MANAGED_SCAN"
    MALFORMED_FILTER = "MALFORMED_FILTER"
    MALFORMED_RESOURCE_NAME = "MALFORMED_RESOURCE_NAME"
    PROJECT_INACTIVE = "PROJECT_INACTIVE"
    REQUIRED_FIELD = "REQUIRED_FIELD"
    RESOURCE_NAME_INCONSISTENT = "RESOURCE_NAME_INCONSISTENT"
    SCAN_ALREADY_RUNNING = "SCAN_ALREADY_RUNNING"
    SCAN_NOT_RUNNING = "SCAN_NOT_RUNNING"
    SEED_URL_DOES_NOT_BELONG_TO_CURRENT_PROJECT = "SEED_URL_DOES_NOT_BELONG_TO_CURRENT_PROJECT"
    SEED_URL_MALFORMED = "SEED_URL_MALFORMED"
    SEED_URL_MAPPED_TO_NON_ROUTABLE_ADDRESS = "SEED_URL_MAPPED_TO_NON_ROUTABLE_ADDRESS"
    SEED_URL_MAPPED_TO_UNRESERVED_ADDRESS = "SEED_URL_MAPPED_TO_UNRESERVED_ADDRESS"
    SEED_URL_HAS_NON_ROUTABLE_IP_ADDRESS = "SEED_URL_HAS_NON_ROUTABLE_IP_ADDRESS"
    SEED_URL_HAS_UNRESERVED_IP_ADDRESS = "SEED_URL_HAS_UNRESERVED_IP_ADDRESS"
    SERVICE_ACCOUNT_NOT_CONFIGURED = "SERVICE_ACCOUNT_NOT_CONFIGURED"
    TOO_MANY_SCANS = "TOO_MANY_SCANS"
    UNABLE_TO_RESOLVE_PROJECT_INFO = "UNABLE_TO_RESOLVE_PROJECT_INFO"
    UNSUPPORTED_BLACKLIST_PATTERN_FORMAT = "UNSUPPORTED_BLACKLIST_PATTERN_FORMAT"
    UNSUPPORTED_FILTER = "UNSUPPORTED_FILTER"
    UNSUPPORTED_FINDING_TYPE = "UNSUPPORTED_FINDING_TYPE"
    UNSUPPORTED_URL_SCHEME = "UNSUPPORTED_URL_SCHEME"


@dataclass_json
@dataclass
class ScanConfigError:
    r"""ScanConfigError
    Defines a custom error message used by CreateScanConfig and UpdateScanConfig APIs when scan configuration validation fails. It is also reported as part of a ScanRunErrorTrace message if scan validation fails due to a scan configuration error.
    """
    
    code: Optional[ScanConfigErrorCodeEnum] = field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.field_name('code') }})
    field_name: Optional[str] = field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.field_name('fieldName') }})
    
