from dataclasses import dataclass, field
from typing import Enum

class DomainAvailabilityEnum(str, Enum):
    AVAILABLE = "AVAILABLE"
    AVAILABLE_RESERVED = "AVAILABLE_RESERVED"
    AVAILABLE_PREORDER = "AVAILABLE_PREORDER"
    UNAVAILABLE = "UNAVAILABLE"
    UNAVAILABLE_PREMIUM = "UNAVAILABLE_PREMIUM"
    UNAVAILABLE_RESTRICTED = "UNAVAILABLE_RESTRICTED"
    RESERVED = "RESERVED"
    DONT_KNOW = "DONT_KNOW"

