swagger: '2.0'
schemes:
  - https
host: www.googleapis.com
basePath: /fusiontables/v1
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: API for working with Fusion Tables data.
  title: Fusion Tables
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - format: google
      url: 'https://www.googleapis.com/discovery/v1/apis/fusiontables/v1/rest'
      version: v1
  x-preferred: false
  x-providerName: googleapis.com
  x-serviceName: fusiontables
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/fusiontables': Manage your Fusion Tables
      'https://www.googleapis.com/auth/fusiontables.readonly': View your Fusion Tables
    type: oauth2
tags:
  - name: column
  - name: query
  - name: style
  - name: table
  - name: task
  - name: template
paths:
  /query:
    get:
      description: Executes an SQL SELECT/SHOW/DESCRIBE statement.
      operationId: fusiontables.query.sqlGet
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables.readonly'
      tags:
        - query
    post:
      description: Executes an SQL SELECT/INSERT/UPDATE/DELETE/SHOW/DESCRIBE/CREATE statement.
      operationId: fusiontables.query.sql
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables.readonly'
      tags:
        - query
  /tables:
    get:
      description: Retrieves a list of tables a user owns.
      operationId: fusiontables.table.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables.readonly'
      tags:
        - table
    post:
      description: Creates a new table.
      operationId: fusiontables.table.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
      tags:
        - table
  /tables/import:
    post:
      description: Import a new table.
      operationId: fusiontables.table.importTable
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
      tags:
        - table
  '/tables/{tableId}':
    delete:
      description: Deletes a table.
      operationId: fusiontables.table.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
      tags:
        - table
    get:
      description: Retrieves a specific table by its id.
      operationId: fusiontables.table.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables.readonly'
      tags:
        - table
    patch:
      description: 'Updates an existing table. Unless explicitly requested, only the name, description, and attribution will be updated. This method supports patch semantics.'
      operationId: fusiontables.table.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
      tags:
        - table
    put:
      description: 'Updates an existing table. Unless explicitly requested, only the name, description, and attribution will be updated.'
      operationId: fusiontables.table.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
      tags:
        - table
  '/tables/{tableId}/columns':
    get:
      description: Retrieves a list of columns.
      operationId: fusiontables.column.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables.readonly'
      tags:
        - column
    post:
      description: Adds a new column to the table.
      operationId: fusiontables.column.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
      tags:
        - column
  '/tables/{tableId}/columns/{columnId}':
    delete:
      description: Deletes the column.
      operationId: fusiontables.column.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
      tags:
        - column
    get:
      description: Retrieves a specific column by its id.
      operationId: fusiontables.column.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables.readonly'
      tags:
        - column
    patch:
      description: Updates the name or type of an existing column. This method supports patch semantics.
      operationId: fusiontables.column.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
      tags:
        - column
    put:
      description: Updates the name or type of an existing column.
      operationId: fusiontables.column.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
      tags:
        - column
  '/tables/{tableId}/copy':
    post:
      description: Copies a table.
      operationId: fusiontables.table.copy
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables.readonly'
      tags:
        - table
  '/tables/{tableId}/import':
    post:
      description: Import more rows into a table.
      operationId: fusiontables.table.importRows
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
      tags:
        - table
  '/tables/{tableId}/styles':
    get:
      description: Retrieves a list of styles.
      operationId: fusiontables.style.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables.readonly'
      tags:
        - style
    post:
      description: Adds a new style for the table.
      operationId: fusiontables.style.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
      tags:
        - style
  '/tables/{tableId}/styles/{styleId}':
    delete:
      description: Deletes a style.
      operationId: fusiontables.style.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
      tags:
        - style
    get:
      description: Gets a specific style.
      operationId: fusiontables.style.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables.readonly'
      tags:
        - style
    patch:
      description: Updates an existing style. This method supports patch semantics.
      operationId: fusiontables.style.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
      tags:
        - style
    put:
      description: Updates an existing style.
      operationId: fusiontables.style.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
      tags:
        - style
  '/tables/{tableId}/tasks':
    get:
      description: Retrieves a list of tasks.
      operationId: fusiontables.task.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables.readonly'
      tags:
        - task
  '/tables/{tableId}/tasks/{taskId}':
    delete:
      description: 'Deletes the task, unless already started.'
      operationId: fusiontables.task.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
      tags:
        - task
    get:
      description: Retrieves a specific task by its id.
      operationId: fusiontables.task.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables.readonly'
      tags:
        - task
  '/tables/{tableId}/templates':
    get:
      description: Retrieves a list of templates.
      operationId: fusiontables.template.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables.readonly'
      tags:
        - template
    post:
      description: Creates a new template for the table.
      operationId: fusiontables.template.insert
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
      tags:
        - template
  '/tables/{tableId}/templates/{templateId}':
    delete:
      description: Deletes a template
      operationId: fusiontables.template.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
      tags:
        - template
    get:
      description: Retrieves a specific template by its id
      operationId: fusiontables.template.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables.readonly'
      tags:
        - template
    patch:
      description: Updates an existing template. This method supports patch semantics.
      operationId: fusiontables.template.patch
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
      tags:
        - template
    put:
      description: Updates an existing template
      operationId: fusiontables.template.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/fusiontables'
      tags:
        - template