package shared




type SimulationJobErrorCodeEnum string

const (
    SimulationJobErrorCodeEnumInternalServiceError SimulationJobErrorCodeEnum = "InternalServiceError"
SimulationJobErrorCodeEnumRobotApplicationCrash SimulationJobErrorCodeEnum = "RobotApplicationCrash"
SimulationJobErrorCodeEnumSimulationApplicationCrash SimulationJobErrorCodeEnum = "SimulationApplicationCrash"
SimulationJobErrorCodeEnumRobotApplicationHealthCheckFailure SimulationJobErrorCodeEnum = "RobotApplicationHealthCheckFailure"
SimulationJobErrorCodeEnumSimulationApplicationHealthCheckFailure SimulationJobErrorCodeEnum = "SimulationApplicationHealthCheckFailure"
SimulationJobErrorCodeEnumBadPermissionsRobotApplication SimulationJobErrorCodeEnum = "BadPermissionsRobotApplication"
SimulationJobErrorCodeEnumBadPermissionsSimulationApplication SimulationJobErrorCodeEnum = "BadPermissionsSimulationApplication"
SimulationJobErrorCodeEnumBadPermissionsS3Object SimulationJobErrorCodeEnum = "BadPermissionsS3Object"
SimulationJobErrorCodeEnumBadPermissionsS3Output SimulationJobErrorCodeEnum = "BadPermissionsS3Output"
SimulationJobErrorCodeEnumBadPermissionsCloudwatchLogs SimulationJobErrorCodeEnum = "BadPermissionsCloudwatchLogs"
SimulationJobErrorCodeEnumSubnetIPLimitExceeded SimulationJobErrorCodeEnum = "SubnetIpLimitExceeded"
SimulationJobErrorCodeEnumEniLimitExceeded SimulationJobErrorCodeEnum = "ENILimitExceeded"
SimulationJobErrorCodeEnumBadPermissionsUserCredentials SimulationJobErrorCodeEnum = "BadPermissionsUserCredentials"
SimulationJobErrorCodeEnumInvalidBundleRobotApplication SimulationJobErrorCodeEnum = "InvalidBundleRobotApplication"
SimulationJobErrorCodeEnumInvalidBundleSimulationApplication SimulationJobErrorCodeEnum = "InvalidBundleSimulationApplication"
SimulationJobErrorCodeEnumInvalidS3Resource SimulationJobErrorCodeEnum = "InvalidS3Resource"
SimulationJobErrorCodeEnumThrottlingError SimulationJobErrorCodeEnum = "ThrottlingError"
SimulationJobErrorCodeEnumLimitExceeded SimulationJobErrorCodeEnum = "LimitExceeded"
SimulationJobErrorCodeEnumMismatchedEtag SimulationJobErrorCodeEnum = "MismatchedEtag"
SimulationJobErrorCodeEnumRobotApplicationVersionMismatchedEtag SimulationJobErrorCodeEnum = "RobotApplicationVersionMismatchedEtag"
SimulationJobErrorCodeEnumSimulationApplicationVersionMismatchedEtag SimulationJobErrorCodeEnum = "SimulationApplicationVersionMismatchedEtag"
SimulationJobErrorCodeEnumResourceNotFound SimulationJobErrorCodeEnum = "ResourceNotFound"
SimulationJobErrorCodeEnumRequestThrottled SimulationJobErrorCodeEnum = "RequestThrottled"
SimulationJobErrorCodeEnumBatchTimedOut SimulationJobErrorCodeEnum = "BatchTimedOut"
SimulationJobErrorCodeEnumBatchCanceled SimulationJobErrorCodeEnum = "BatchCanceled"
SimulationJobErrorCodeEnumInvalidInput SimulationJobErrorCodeEnum = "InvalidInput"
SimulationJobErrorCodeEnumWrongRegionS3Bucket SimulationJobErrorCodeEnum = "WrongRegionS3Bucket"
SimulationJobErrorCodeEnumWrongRegionS3Output SimulationJobErrorCodeEnum = "WrongRegionS3Output"
SimulationJobErrorCodeEnumWrongRegionRobotApplication SimulationJobErrorCodeEnum = "WrongRegionRobotApplication"
SimulationJobErrorCodeEnumWrongRegionSimulationApplication SimulationJobErrorCodeEnum = "WrongRegionSimulationApplication"
SimulationJobErrorCodeEnumUploadContentMismatchError SimulationJobErrorCodeEnum = "UploadContentMismatchError"
)


