from .associateapprovalruletemplatewithrepository import *
from .batchassociateapprovalruletemplatewithrepositories import *
from .batchdescribemergeconflicts import *
from .batchdisassociateapprovalruletemplatefromrepositories import *
from .batchgetcommits import *
from .batchgetrepositories import *
from .createapprovalruletemplate import *
from .createbranch import *
from .createcommit import *
from .createpullrequest import *
from .createpullrequestapprovalrule import *
from .createrepository import *
from .createunreferencedmergecommit import *
from .deleteapprovalruletemplate import *
from .deletebranch import *
from .deletecommentcontent import *
from .deletefile import *
from .deletepullrequestapprovalrule import *
from .deleterepository import *
from .describemergeconflicts import *
from .describepullrequestevents import *
from .disassociateapprovalruletemplatefromrepository import *
from .evaluatepullrequestapprovalrules import *
from .getapprovalruletemplate import *
from .getblob import *
from .getbranch import *
from .getcomment import *
from .getcommentreactions import *
from .getcommentsforcomparedcommit import *
from .getcommentsforpullrequest import *
from .getcommit import *
from .getdifferences import *
from .getfile import *
from .getfolder import *
from .getmergecommit import *
from .getmergeconflicts import *
from .getmergeoptions import *
from .getpullrequest import *
from .getpullrequestapprovalstates import *
from .getpullrequestoverridestate import *
from .getrepository import *
from .getrepositorytriggers import *
from .listapprovalruletemplates import *
from .listassociatedapprovalruletemplatesforrepository import *
from .listbranches import *
from .listpullrequests import *
from .listrepositories import *
from .listrepositoriesforapprovalruletemplate import *
from .listtagsforresource import *
from .mergebranchesbyfastforward import *
from .mergebranchesbysquash import *
from .mergebranchesbythreeway import *
from .mergepullrequestbyfastforward import *
from .mergepullrequestbysquash import *
from .mergepullrequestbythreeway import *
from .overridepullrequestapprovalrules import *
from .postcommentforcomparedcommit import *
from .postcommentforpullrequest import *
from .postcommentreply import *
from .putcommentreaction import *
from .putfile import *
from .putrepositorytriggers import *
from .tagresource import *
from .testrepositorytriggers import *
from .untagresource import *
from .updateapprovalruletemplatecontent import *
from .updateapprovalruletemplatedescription import *
from .updateapprovalruletemplatename import *
from .updatecomment import *
from .updatedefaultbranch import *
from .updatepullrequestapprovalrulecontent import *
from .updatepullrequestapprovalstate import *
from .updatepullrequestdescription import *
from .updatepullrequeststatus import *
from .updatepullrequesttitle import *
from .updaterepositorydescription import *
from .updaterepositoryname import *
