swagger: '2.0'
schemes:
  - https
host: vault.googleapis.com
basePath: /
info:
  contact:
    name: Google
    url: 'https://google.com'
  description: Archiving and eDiscovery for G Suite.
  license:
    name: Creative Commons Attribution 3.0
    url: 'http://creativecommons.org/licenses/by/3.0/'
  termsOfService: 'https://developers.google.com/terms/'
  title: G Suite Vault
  version: v1
  x-apiClientRegistration:
    url: 'https://console.developers.google.com'
  x-apisguru-categories:
    - storage
  x-logo:
    url: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png'
  x-origin:
    - converter:
        url: 'https://github.com/lucybot/api-spec-converter'
        version: 2.7.31
      format: google
      url: 'https://vault.googleapis.com/$discovery/rest?version=v1'
      version: v1
  x-preferred: true
  x-providerName: googleapis.com
  x-serviceName: vault
securityDefinitions:
  Oauth2:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 implicit authentication
    flow: implicit
    scopes:
      'https://www.googleapis.com/auth/ediscovery': Manage your eDiscovery data
      'https://www.googleapis.com/auth/ediscovery.readonly': View your eDiscovery data
    type: oauth2
  Oauth2c:
    authorizationUrl: 'https://accounts.google.com/o/oauth2/auth'
    description: Oauth 2.0 accessCode authentication
    flow: accessCode
    scopes:
      'https://www.googleapis.com/auth/ediscovery': Manage your eDiscovery data
      'https://www.googleapis.com/auth/ediscovery.readonly': View your eDiscovery data
    tokenUrl: 'https://accounts.google.com/o/oauth2/token'
    type: oauth2
tags:
  - name: matters
paths:
  /v1/matters:
    get:
      description: Lists matters the user has access to.
      operationId: vault.matters.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery.readonly'
      tags:
        - matters
    post:
      description: |-
        Creates a new matter with the given name and description. The initial state
        is open, and the owner is the method caller. Returns the created matter
        with default view.
      operationId: vault.matters.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
      tags:
        - matters
  '/v1/matters/{matterId}':
    delete:
      description: Deletes the specified matter. Returns matter with updated state.
      operationId: vault.matters.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
      tags:
        - matters
    get:
      description: Gets the specified matter.
      operationId: vault.matters.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery.readonly'
      tags:
        - matters
    put:
      description: |-
        Updates the specified matter.
        This updates only the name and description of the matter, identified by
        matter id. Changes to any other fields are ignored.
        Returns the default view of the matter.
      operationId: vault.matters.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
      tags:
        - matters
  '/v1/matters/{matterId}/exports':
    get:
      description: Lists Exports.
      operationId: vault.matters.exports.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery.readonly'
      tags:
        - matters
    post:
      description: Creates an Export.
      operationId: vault.matters.exports.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
      tags:
        - matters
  '/v1/matters/{matterId}/exports/{exportId}':
    delete:
      description: Deletes an Export.
      operationId: vault.matters.exports.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
      tags:
        - matters
    get:
      description: Gets an Export.
      operationId: vault.matters.exports.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery.readonly'
      tags:
        - matters
  '/v1/matters/{matterId}/holds':
    get:
      description: |-
        Lists holds within a matter. An empty page token in ListHoldsResponse
        denotes no more holds to list.
      operationId: vault.matters.holds.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery.readonly'
      tags:
        - matters
    post:
      description: Creates a hold in the given matter.
      operationId: vault.matters.holds.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
      tags:
        - matters
  '/v1/matters/{matterId}/holds/{holdId}':
    delete:
      description: Removes a hold by ID. This will release any HeldAccounts on this Hold.
      operationId: vault.matters.holds.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
      tags:
        - matters
    get:
      description: Gets a hold by ID.
      operationId: vault.matters.holds.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery.readonly'
      tags:
        - matters
    put:
      description: |-
        Updates the OU and/or query parameters of a hold. You cannot add accounts
        to a hold that covers an OU, nor can you add OUs to a hold that covers
        individual accounts. Accounts listed in the hold will be ignored.
      operationId: vault.matters.holds.update
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
      tags:
        - matters
  '/v1/matters/{matterId}/holds/{holdId}/accounts':
    get:
      description: |-
        Lists HeldAccounts for a hold. This will only list individually specified
        held accounts. If the hold is on an OU, then use
        <a href="https://developers.google.com/admin-sdk/">Admin SDK</a>
        to enumerate its members.
      operationId: vault.matters.holds.accounts.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery.readonly'
      tags:
        - matters
    post:
      description: |-
        Adds a HeldAccount to a hold. Accounts can only be added to a hold that
        has no held_org_unit set. Attempting to add an account to an OU-based
        hold will result in an error.
      operationId: vault.matters.holds.accounts.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
      tags:
        - matters
  '/v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}':
    delete:
      description: |-
        Removes a HeldAccount from a hold. If this request leaves the hold with
        no held accounts, the hold will not apply to any accounts.
      operationId: vault.matters.holds.accounts.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
      tags:
        - matters
  '/v1/matters/{matterId}/holds/{holdId}:addHeldAccounts':
    post:
      description: |-
        Adds HeldAccounts to a hold. Returns a list of accounts that have been
        successfully added. Accounts can only be added to an existing account-based
        hold.
      operationId: vault.matters.holds.addHeldAccounts
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
      tags:
        - matters
  '/v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts':
    post:
      description: |-
        Removes HeldAccounts from a hold. Returns a list of statuses in the same
        order as the request. If this request leaves the hold with no held
        accounts, the hold will not apply to any accounts.
      operationId: vault.matters.holds.removeHeldAccounts
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
      tags:
        - matters
  '/v1/matters/{matterId}/savedQueries':
    get:
      description: |-
        Lists saved queries within a matter. An empty page token in
        ListSavedQueriesResponse denotes no more saved queries to list.
      operationId: vault.matters.savedQueries.list
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery.readonly'
      tags:
        - matters
    post:
      description: Creates a saved query.
      operationId: vault.matters.savedQueries.create
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
      tags:
        - matters
  '/v1/matters/{matterId}/savedQueries/{savedQueryId}':
    delete:
      description: Deletes a saved query by Id.
      operationId: vault.matters.savedQueries.delete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
      tags:
        - matters
    get:
      description: Retrieves a saved query by Id.
      operationId: vault.matters.savedQueries.get
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery.readonly'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery.readonly'
      tags:
        - matters
  '/v1/matters/{matterId}:addPermissions':
    post:
      description: Adds an account as a matter collaborator.
      operationId: vault.matters.addPermissions
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
      tags:
        - matters
  '/v1/matters/{matterId}:close':
    post:
      description: Closes the specified matter. Returns matter with updated state.
      operationId: vault.matters.close
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
      tags:
        - matters
  '/v1/matters/{matterId}:removePermissions':
    post:
      description: Removes an account as a matter collaborator.
      operationId: vault.matters.removePermissions
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
      tags:
        - matters
  '/v1/matters/{matterId}:reopen':
    post:
      description: Reopens the specified matter. Returns matter with updated state.
      operationId: vault.matters.reopen
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
      tags:
        - matters
  '/v1/matters/{matterId}:undelete':
    post:
      description: Undeletes the specified matter. Returns matter with updated state.
      operationId: vault.matters.undelete
      security:
        - Oauth2:
            - 'https://www.googleapis.com/auth/ediscovery'
          Oauth2c:
            - 'https://www.googleapis.com/auth/ediscovery'
      tags:
        - matters