from .associateattributegroup import *
from .associateresource import *
from .createapplication import *
from .createattributegroup import *
from .deleteapplication import *
from .deleteattributegroup import *
from .disassociateattributegroup import *
from .disassociateresource import *
from .getapplication import *
from .getassociatedresource import *
from .getattributegroup import *
from .listapplications import *
from .listassociatedattributegroups import *
from .listassociatedresources import *
from .listattributegroups import *
from .listtagsforresource import *
from .syncresource import *
from .tagresource import *
from .untagresource import *
from .updateapplication import *
from .updateattributegroup import *
